/***********************************************************************

ai_alphalabs2_scientist1.script

***********************************************************************/

#define ED_WAIT_GETCLOSER		4
#define	ED_LEAD_TIMEOUT			1
#define ED_MIN_LOOK_DELAY		4
#define	ED_MAX_LOOK_DELAY		8
#define	ED_LOOK_TIME			1.5
#define ED_LEAD_DIST			128
#define ED_LOST_DIST			256

#define ED_NUM_EVENTS			7
#define ED_POINT_OF_NO_RETURN	(ED_NUM_EVENTS - 1)

#define ED_COWER_ANGLE_LEFT		85
#define ED_COWER_ANGLE_RIGHT	-85

#define	ED_COWER_BLEND			9
#define ED_BLEND_TURN_TO_IDLE	0

#define ED_TURN_THRESHOLD		25

object ai_alphalabs2_scientist1 : ai {
	boolean		attack_count;
	boolean		hurry_count;
	boolean		cower;
	float		talk_count;
	float		event;
	float		lastHurryTime;
	entity		light;
	entity		playerEnemy;
	entity		lookTarget;
	float		playerMoveState;
	vector		lastValidPlayerPosition;
	float		playerPositionThread;
	
	//
	// States
	//
	void		state_WorkingOnStuff();
	void		state_DeathScene();
	void		state_Killed();
	void		state_NoticePlayer();
	void		state_Wait();
	void		state_Spooked();
	void		state_Lead();
	void		state_FindPlayer();
	void		state_Cower();

	void		init();
	void		destroy();

	void		faceTowardsEntity( entity target, float duration );
	void		light_fade_out( float fadeTime );
	void		light_fade_in( float fadeTime );
	void		light_fade( float stay_off );
	void		light_fade1();
	void		light_fade2();
	void		doEvent();
	void		sayStuff();
	void		hurry_up();

	float		checkDestinationDistance();
	void		updatePlayerPositionThread();
	void		checkBlocked();
	
	// head anim states	
	void		Head_Idle();
	void		Head_Death();
	void		Head_DeathScene();
	void 		Head_Greeting();
	void 		Head_Speech();
	void		Head_Hurry();
	void 		Head_StayClose();
	void 		Head_Electro_Pulses();
	void 		Head_Pulse1();
	void 		Head_Pulse2();
	void 		Head_WatchIt();
	void 		Head_Spooked();
	void 		Head_Exit();
	void		Head_SayStuff();
	void 		Head_Attacked();
	void 		Head_AttackDone();

	// torso anim states
	void		Torso_DeathScene();
	void		Torso_Death();
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_Work();
	
	// legs anim states
	void		Legs_Death();
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_TurnLeft();
	void		Legs_TurnRight();
	void		Legs_Cower();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void ai_alphalabs2_scientist1::Head_Idle() {
	idleAnim( ANIMCHANNEL_HEAD, "stand" );
}

void ai_alphalabs2_scientist1::Head_Death() {
	playAnim( ANIMCHANNEL_HEAD, "dead" );
	while( AI_DEAD ) {
		waitFrame();
	}
}

void ai_alphalabs2_scientist1::Head_DeathScene() {
	stopAnim( ANIMCHANNEL_HEAD, 0 );
	while( AI_DEAD ) {
		waitFrame();
	}
}

void ai_alphalabs2_scientist1::Head_Greeting() {
	playAnim( ANIMCHANNEL_HEAD, "lips_dontshoot" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );
	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

void ai_alphalabs2_scientist1::Head_Speech() {
	playAnim( ANIMCHANNEL_HEAD, "lips_canhelp" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_HEAD, "lips_lightsout" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	
	lookAt( $player1, 0 );
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

void ai_alphalabs2_scientist1::Head_Hurry() {
	if ( hurry_count ) {
		playAnim( ANIMCHANNEL_HEAD, "lips_hurry1" );
	} else {
		playAnim( ANIMCHANNEL_HEAD, "lips_hurry2" );
	}
	
	hurry_count = !hurry_count;
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

void ai_alphalabs2_scientist1::Head_StayClose() {
	playAnim( ANIMCHANNEL_HEAD, "lips_stayclose" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_Electro_Pulses() {
	playAnim( ANIMCHANNEL_HEAD, "lips_electro" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_Pulse1() {
	playAnim( ANIMCHANNEL_HEAD, "lips_theresone" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_Pulse2() {
	playAnim( ANIMCHANNEL_HEAD, "lips_hangon" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_WatchIt() {
	playAnim( ANIMCHANNEL_HEAD, "lips_watchit" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_Spooked() {
	playAnim( ANIMCHANNEL_HEAD, "lips_whatwasthat" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		waitFrame();
	}
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_Exit() {
	playAnim( ANIMCHANNEL_HEAD, "lips_theexit" );
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 00 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}
		
void ai_alphalabs2_scientist1::Head_SayStuff() {
	if ( !talk_count ) {
		talk_count = 1;
		playAnim( ANIMCHANNEL_HEAD, "lips_wecantstop" );
	} else if ( talk_count == 1 ) {
		talk_count = 2;
		playAnim( ANIMCHANNEL_HEAD, "lips_canttalknow" );
	} else if ( talk_count == 2 ) {
		talk_count = 1;
		playAnim( ANIMCHANNEL_HEAD, "lips_itisntfar" );
	}	
	
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

void ai_alphalabs2_scientist1::Head_Attacked() {
	if ( attack_count ) {
		playAnim( ANIMCHANNEL_HEAD, "lips_ohgod" );
	} else {
		playAnim( ANIMCHANNEL_HEAD, "lips_killit" );
	}
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

void ai_alphalabs2_scientist1::Head_AttackDone() {
	if ( attack_count ) {
		playAnim( ANIMCHANNEL_HEAD, "lips_ohthankgod" );
	} else {
		playAnim( ANIMCHANNEL_HEAD, "lips_thatwasclose" );
	}
	attack_count = !attack_count;
	while( !( animDone( ANIMCHANNEL_HEAD, 0 ) ) ) {
		lookAt( $player1, 1 );
		waitFrame();
	}
	lookAt( $player1, 0 );	
	animState( ANIMCHANNEL_HEAD, "Head_Idle", 4 );
}

/***********************************************************************

	Torso animation control

***********************************************************************/

void ai_alphalabs2_scientist1::Torso_Work() {
	playAnim( ANIMCHANNEL_TORSO, "working" );	
	while( !( animDone( ANIMCHANNEL_TORSO, 12 ) ) ) {
		waitFrame();
	}	
	finishAction( "work" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 12 );
}

void ai_alphalabs2_scientist1::Torso_DeathScene() {
	string animname;

	overrideAnim( ANIMCHANNEL_LEGS );
	
	playAnim( ANIMCHANNEL_TORSO, "killme" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	
	becomeRagdoll();
	finishAction( "dead" );

	// never exit
	waitUntil( 0 );
}

void ai_alphalabs2_scientist1::Torso_Death() {
	finishAction( "dead" );

	// never exit
	waitUntil( 0 );
}

void ai_alphalabs2_scientist1::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
}

void ai_alphalabs2_scientist1::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}
	
	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void ai_alphalabs2_scientist1::Legs_Death() {
	while( AI_DEAD ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void ai_alphalabs2_scientist1::Legs_Idle() {
	float delta;
	
	delta = getTurnDelta();
	if ( !AI_FORWARD && !facingIdeal() ) {
		if ( delta > 10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
		}
		if ( delta < -10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
		}
	}
	
	if ( AI_FORWARD ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
	}
	
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
		}
		if ( cower ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Cower", 12 );
		}
		
		if ( !facingIdeal() ) {
			delta = getTurnDelta();
			if ( delta > 10 ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
			}
			if ( delta < -10 ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
			}
		}
	}
}

void ai_alphalabs2_scientist1::Legs_Walk() {
	float delta;
	
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD )	{
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
}

void ai_alphalabs2_scientist1::Legs_TurnLeft() {
	float delta;

	allowMovement( true );
	animTurn( 180 );
	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, ED_BLEND_TURN_TO_IDLE ) ) {
		if ( AI_FORWARD ) {
			break;
		}
		waitFrame();
	}
	animTurn( 0 );
	
	if ( AI_FORWARD ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
	}
	
	if ( !facingIdeal() ) {
		delta = getTurnDelta();
		if ( delta > 10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", ED_BLEND_TURN_TO_IDLE );
		}
		if ( delta < -10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", ED_BLEND_TURN_TO_IDLE );
		}
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", ED_BLEND_TURN_TO_IDLE );
}

void ai_alphalabs2_scientist1::Legs_TurnRight() {
	float delta;

	allowMovement( true );
	animTurn( 180 );
	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, ED_BLEND_TURN_TO_IDLE ) ) {
		if ( AI_FORWARD ) {
			break;
		}
		waitFrame();
	}
	animTurn( 0 );

	if ( AI_FORWARD ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
	}

	if ( !facingIdeal() ) {
		delta = getTurnDelta();
		if ( delta > 10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", ED_BLEND_TURN_TO_IDLE );
		}
		if ( delta < -10 ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", ED_BLEND_TURN_TO_IDLE );
		}
	}

    animState( ANIMCHANNEL_LEGS, "Legs_Idle", ED_BLEND_TURN_TO_IDLE );
}

void ai_alphalabs2_scientist1::Legs_Cower() {
	vector delta;
	vector ang1;
	vector ang2;
	vector ang3;
	float  yaw;
	float  frac;
	
	yaw = 0;
	overrideAnim( ANIMCHANNEL_TORSO );
	playCycle( ANIMCHANNEL_LEGS, "cower" );
	while( cower ) {
		disableEyeFocus();	// gets reenabled by the head anim ending, so just set it every frame

		if ( playerEnemy ) {
			delta = playerEnemy.getOrigin();
			delta = delta - getOrigin();
			ang1 = sys.VecToAngles( delta );
			ang2 = getAngles();
			ang3 = anglemod180( ang1 - ang2 );
			if ( ang3_y > ED_COWER_ANGLE_LEFT ) {
				ang3_y = ED_COWER_ANGLE_LEFT;
			} else if ( ang3_y < ED_COWER_ANGLE_RIGHT ) {
				ang3_y = ED_COWER_ANGLE_RIGHT;
			}

			yaw = yaw * 0.9 + ang3_y * 0.1;
			if ( yaw < 0 ) {
				frac = yaw / ED_COWER_ANGLE_RIGHT;
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 0, 1 - frac );	// center
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 1, 0 );			// left
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 2, frac );		// right
			} else {
				frac = yaw / ED_COWER_ANGLE_LEFT;
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 0, 1 - frac );	// center
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 1, frac );		// left
				setSyncedAnimWeight( ANIMCHANNEL_LEGS, 2, 0 );			// right
			}
		}
		waitFrame();
	}
	
	enableEyeFocus();
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
ai_alphalabs2_scientist1::init
=====================
*/
void ai_alphalabs2_scientist1::init() {
	setBoneMod( true );
	
	talk_count = 0;
	lastHurryTime = 0;
	cower = false;
	attack_count = 0;
	hurry_count = 0;
	event = 0;
	
	lookTarget = sys.spawn( "target_null" );
	lookTarget.bind( self );
	lookTarget.setOrigin( '120 0 72' );	
	
	light = sys.spawn( "light" );
	light.setShader( "lights/lanternglow" );
	light.setRadius( 192 );		
	light.setAngles( '0 -90 0' );
	light.bindToJoint( self, "lanternlight", true );
	light.setOrigin( '-5 0 0' );

	animState( ANIMCHANNEL_HEAD, "Head_Idle", 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	setState( "state_WorkingOnStuff" );
}

/*
=====================
ai_alphalabs2_scientist1::destroy
=====================
*/
void ai_alphalabs2_scientist1::destroy() {
	lookTarget.remove();
	light.remove();
	if ( playerPositionThread ) {
		sys.terminate( playerPositionThread );
		playerPositionThread = 0;
	}
}

/*
=====================
ai_alphalabs2_scientist1::faceTowardsEntity
=====================
*/
void ai_alphalabs2_scientist1::faceTowardsEntity( entity target, float duration ) {
	vector delta;
	vector ang1;
	vector ang2;
	vector ang3;
	
	delta = target.getOrigin();
	delta = delta - getOrigin();
	ang1 = sys.VecToAngles( delta );
	ang2 = getAngles();
	ang3 = anglemod180( ang1 - ang2 );
	if ( ang3_y < -ED_TURN_THRESHOLD ) {
		turnTo( ang1_y );
	} else if ( ang3_y > ED_TURN_THRESHOLD ) {
		turnTo( ang1_y );
	}
	
	lookAt( target, duration );
}

/*
=====================
ai_alphalabs2_scientist1::light_fade_out
=====================
*/
void ai_alphalabs2_scientist1::light_fade_out( float fadeTime ) {
	float i;
	vector c;
	float frac;
	float numTics;

	setSkin( "skins/characters/npcs/labcoat_old_lantern_off.skin" );
	
	// convert to the total number of game tics
	numTics = fadeTime * GAME_FPS;

	for( i = 0; i < numTics; i++ ) {
		frac = 1 - ( i / numTics );
		light.setColor( frac, frac, frac );
		global_flashlight_intensity = frac;

		// wait one game frame
		sys.wait( GAME_FRAMETIME );
	}
	
	// make sure we are set to exactly the final value
	light.setColor( 0, 0, 0 );
	global_flashlight_intensity = 0;
}

/*
=====================
ai_alphalabs2_scientist1::light_fade_in
=====================
*/
void ai_alphalabs2_scientist1::light_fade_in( float fadeTime ) {
	float i;
	vector c;
	float frac;
	float numTics;

	setSkin( "skins/characters/npcs/body_labcoat_lantern" );
	
	// convert to the total number of game tics
	numTics = fadeTime * GAME_FPS;	

	for( i = 0; i < numTics; i++ ) {
		frac = i / numTics;
		light.setColor( frac, frac, frac );
		global_flashlight_intensity = frac;

		// wait one game frame
		sys.wait( GAME_FRAMETIME );
	}
	
	// make sure we are set to exactly the final value
	light.setColor( 1, 1, 1 );
	global_flashlight_intensity = 1;
}

/*
=====================
ai_alphalabs2_scientist1::light_fade
=====================
*/
void ai_alphalabs2_scientist1::light_fade( float stay_off ) {
	light_fade_out( 0.1 );
	light_fade_in( 0.05 );
	light_fade_out( 0.1 );
	light_fade_in( 0.2 );
	light_fade_out( 0.05 );
	if ( !stay_off ) {
		sys.wait( 2 );
		thread light_fade_in( 3 );
		
		lookTarget.setOrigin( '80 -40 72' );	
		lookAt( lookTarget, 1.2 );
		sys.wait( 1.2 );
		
		lookTarget.setOrigin( '80 40 72' );	
		lookAt( lookTarget, 1.5 );
		sys.wait( 1.5 );
	}
}

/*
=====================
ai_alphalabs2_scientist1::light_fade1
=====================
*/
void ai_alphalabs2_scientist1::light_fade1() {
	float currentTime;
	float threadNum;
	
	sys.wait( 0.2 );
	threadNum = thread light_fade( false );
	sys.wait( 1 );
	
	stopMove();
	currentTime = sys.getTime();

	animState( ANIMCHANNEL_HEAD, "Head_Pulse1", 4 );
	sys.waitForThread( threadNum );
	setState( "state_Lead" );
}

/*
=====================
ai_alphalabs2_scientist1::light_fade2
=====================
*/
void ai_alphalabs2_scientist1::light_fade2() {
	float currentTime;
	float threadNum;

	threadNum = thread light_fade( false );
	sys.wait( 0.5 );
	
	stopMove();
	currentTime = sys.getTime();
	animState( ANIMCHANNEL_HEAD, "Head_Pulse2", 4 );
	sys.waitForThread( threadNum );
	setState( "state_Lead" );
}

/*
=====================
ai_alphalabs2_scientist1::doEvent
=====================
*/
void ai_alphalabs2_scientist1::doEvent() {
	float currentTime;
	
	AI_ACTIVATED = false;
	currentTime = sys.getTime();
	event = event + 1;
	if ( event == 1 ) {
		animState( ANIMCHANNEL_HEAD, "Head_Electro_Pulses", 4 );
		setState( "state_Lead" );
	} else if ( event == 2 ) {
		light_fade1();
	} else if ( event == 3 ) {
		setState( "state_Spooked" );
	} else if ( event == 4) {
		light_fade2();
	} else if ( event == 5 ) {
		animState( ANIMCHANNEL_HEAD, "Head_Exit", 4 );
		setState( "state_Lead" );
	} else if ( event == ( ED_NUM_EVENTS - 1) ) {
		// point of no return
		;
	} else if ( event >= ED_NUM_EVENTS ) {
		setState( "state_DeathScene" );
	}
}

/*
=====================
ai_alphalabs2_scientist1::sayStuff
=====================
*/
void ai_alphalabs2_scientist1::sayStuff() {
	setTalkTarget( $null_entity );
	if ( !inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
		return;
	}
	animState( ANIMCHANNEL_HEAD, "Head_SayStuff", 4 );
}

/*
=====================
ai_alphalabs2_scientist1::hurry_up
=====================
*/
void ai_alphalabs2_scientist1::hurry_up() {
	float currentTime;

	currentTime = sys.getTime();
	if ( ( currentTime > lastHurryTime ) && inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
		animState( ANIMCHANNEL_HEAD, "Head_Hurry", 4 );
		lastHurryTime = currentTime + 6;
	}
}

/*
=====================
ai_alphalabs2_scientist1::checkDestinationDistance()
=====================
*/
float ai_alphalabs2_scientist1::checkDestinationDistance() {
	float	playerDist;
	float	currentDist;
	float	leadDistance;
	float	relativeMoveDir;
	vector	delta;

	// determine if the player is moving toward us
	delta = getOrigin() - $player1.getOrigin();
	relativeMoveDir = delta * $player1.getLinearVelocity();
	if ( relativeMoveDir > 1 ) {
		// Player is approaching
		playerMoveState = APPROACHING;
	} else if ( relativeMoveDir < -1 ) {
		// Player is moving away from us
		playerMoveState = RETREATING;
	} else {
		// Player is standing still
		playerMoveState = NOT_MOVING;
	}

	playerDist = distanceToPoint( lastValidPlayerPosition );
	if ( playerDist < ED_LEAD_DIST ) {
		return PLAYER_OK;
	}

	if ( !canSee( $player1 ) ) {
		currentDist = travelDistanceToEntity( $scientist_destination );
		leadDistance = travelDistanceBetweenPoints( lastValidPlayerPosition, $scientist_destination.getOrigin() );
		if ( currentDist > leadDistance ) {
			return PLAYER_AHEAD_OF_ME;
		} else {
			return PLAYER_LOST;
		}
	}

	if ( playerDist > ED_LOST_DIST ) {
		currentDist = travelDistanceToEntity( $scientist_destination );
		leadDistance = travelDistanceBetweenPoints( lastValidPlayerPosition, $scientist_destination.getOrigin() );
		if ( currentDist > leadDistance ) {
			return PLAYER_AHEAD_OF_ME;
		} else {
			return PLAYER_BEHIND_ME;
		}
	}

	return PLAYER_OK;
}

/*
=====================
ai_alphalabs2_scientist1::updatePlayerPositionThread()
=====================
*/
void ai_alphalabs2_scientist1::updatePlayerPositionThread() {
	vector pos;

	while( 1 ) {
		if ( canReachEntity( $player1 ) ) {
			lastValidPlayerPosition = getReachableEntityPosition( $player1 );
		}
		//sys.debugBounds( '1 0 0', lastValidPlayerPosition + $player1.getMins(), lastValidPlayerPosition + $player1.getMaxs(), 0 );
		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::checkBlocked
=====================
*/
void ai_alphalabs2_scientist1::checkBlocked() {
	entity obstacle;
	vector player_pos;
	vector delta;

	if ( moveStatus() >= MOVE_STATUS_BLOCKED_BY_OBJECT ) {
		obstacle = getObstacle();
		if ( obstacle != $player1 ) {
			kickObstacles( obstacle, 60 );
			return;
		}

		hurry_up();
		player_pos = $player1.getOrigin();
		saveMove();
		stopMove();
		while( 1 ) {
			delta = player_pos - $player1.getOrigin();
			delta_z = 0;
			if ( sys.vecLength( delta ) > 4 ) {
				restoreMove();
				if ( moveStatus() < MOVE_STATUS_BLOCKED_BY_OBJECT ) {
					break;
				}
				if ( getObstacle() != $player1 ) {
					break;
				}
				stopMove();
			}
			if ( $player1.hasEnemies() ) {
				setState( "state_Cower" );
			}
			faceTowardsEntity( $player1, 1 );
			if ( AI_TALK ) {
				sayStuff();
			}
			waitFrame();
		}
	}
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
ai_alphalabs2_scientist1::state_Killed
=====================
*/
void ai_alphalabs2_scientist1::state_Killed() {
	light.Off();
	setSkin( "skins/characters/npcs/body_labcoat_no_lantern.skin" );
	stopMove();

	sys.terminate( playerPositionThread );
	playerPositionThread = 0;

	animState( ANIMCHANNEL_HEAD, "Head_Death", 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );

	waitAction( "dead" );
	stopThinking();
}

/*
=====================
ai_alphalabs2_scientist1::state_DeathScene
=====================
*/
void ai_alphalabs2_scientist1::state_DeathScene() {
	// keep walking
	AI_FORWARD = true;
	setNeverDormant( false );

	sys.terminate( playerPositionThread );
	playerPositionThread = 0;

	thread light_fade( true );
	sys.wait( 0.5 );
	
	setTalkState( TALK_DEAD );

	stopMove();
	sys.trigger( $edkiller );
	animState( ANIMCHANNEL_HEAD, "Head_DeathScene", 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_DeathScene", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );
	waitAction( "dead" );
	stopThinking();
}

/*
=====================
ai_alphalabs2_scientist1::state_WorkingOnStuff
=====================
*/
void ai_alphalabs2_scientist1::state_WorkingOnStuff() {
	vector ang1;
	vector ang2;
	
	ang1 = $interesting_object1.getAngles();
	ang2 = $interesting_object2.getAngles();

	AI_ACTIVATED = false;	
	while( 1 ) {
		moveToEntity( $interesting_object1 );
		while( !AI_MOVE_DONE ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}
		
		turnTo( ang1_y );
		while( !facingIdeal() ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}

		while( !inAnimState( ANIMCHANNEL_LEGS, "Legs_Idle" ) ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}

		animState( ANIMCHANNEL_TORSO, "Torso_Work", 8 );
		while( inAnimState( ANIMCHANNEL_TORSO, "Torso_Work" ) ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}

		moveToEntity( $interesting_object2 );
		while( !AI_MOVE_DONE ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}
		
		turnTo( ang2_y );
		while( !facingIdeal() ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}

		while( !inAnimState( ANIMCHANNEL_LEGS, "Legs_Idle" ) ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}

		animState( ANIMCHANNEL_TORSO, "Torso_Work", 8 );
		while( inAnimState( ANIMCHANNEL_TORSO, "Torso_Work" ) ) {
			if ( AI_ACTIVATED ) {
				setState( "state_NoticePlayer" );
			}
			waitFrame();
		}
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_NoticePlayer
=====================
*/
void ai_alphalabs2_scientist1::state_NoticePlayer() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 12 );
	
	setNeverDormant( true );
	AI_ACTIVATED = false;
	lookAt( $player1, 10 );
	animState( ANIMCHANNEL_HEAD, "Head_Greeting", 4 );
	moveToEntity( $greet_player );
	while( !AI_MOVE_DONE ) {
		if ( distanceTo( $player1 ) < 64 ) {
			AI_ACTIVATED = true;
			turnToEntity( $player1 );
			break;
		}
		lookAt( $player1, 1 );
		waitFrame();
	}
	stopMove();
	
	while( !AI_ACTIVATED ) {
		faceTowardsEntity( $player1, 1 );
		waitFrame();
	}
	AI_ACTIVATED = false;
	
	animState( ANIMCHANNEL_HEAD, "Head_Speech", 4 );
	while( !inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
		faceTowardsEntity( $player1, 1 );
		waitFrame();
	}
	
	setTalkTarget( $null_entity );

	playerPositionThread = thread updatePlayerPositionThread();
	setState( "state_Lead" );
}

/*
=====================
ai_alphalabs2_scientist1::state_Wait
=====================
*/
void ai_alphalabs2_scientist1::state_Wait() {
	float getCloserTime;
	float currentTime;

	float result = checkDestinationDistance();
	if ( result == PLAYER_LOST ) {
		setState( "state_FindPlayer" );
	} else if ( result == PLAYER_AHEAD_OF_ME ) {
		setState( "state_Lead" );
	} else if ( ( result == PLAYER_OK ) && ( playerMoveState == APPROACHING ) ) {
		setState( "state_Lead" );
	}

	stopMove();
	hurry_up();

	getCloserTime = currentTime + ED_WAIT_GETCLOSER;
	
	while( 1 ) {
		faceTowardsEntity( $player1, 1 );
		if ( AI_TALK ) {
			sayStuff();
		}
	
		result = checkDestinationDistance();
		if ( result == PLAYER_LOST ) {
			setState( "state_FindPlayer" );
		} else if ( result == PLAYER_AHEAD_OF_ME ) {
			setState( "state_Lead" );
		} else if ( ( result == PLAYER_OK ) && ( playerMoveState == APPROACHING ) ) {
			setState( "state_Lead" );
		} else  if ( ( sys.getTime() > getCloserTime ) && ( result == PLAYER_BEHIND_ME ) ) {
			setState( "state_GetCloser" );
		}

		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}
		
		if ( AI_ACTIVATED ) {
			if ( inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
				doEvent();
			}
		}
		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_GetCloser
=====================
*/
void ai_alphalabs2_scientist1::state_GetCloser() {
	while( 1 ) {
		moveToPosition( lastValidPlayerPosition );
		if ( AI_MOVE_DONE ) {
			if ( !canReachEntity( $player1 ) ) {
				setState( "state_CantReachPlayer" );
			}
		}

		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}

		checkBlocked();

		float result = checkDestinationDistance();
		if ( result == PLAYER_LOST ) {
			setState( "state_FindPlayer" );
		}
        if ( result == PLAYER_OK ) {
			setState( "state_Wait" );
		}
		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_CantReachPlayer
=====================
*/
void ai_alphalabs2_scientist1::state_CantReachPlayer() {
	startSound( "snd_cant_reach_player", SND_CHANNEL_VOICE, false );
	stopMove();
	while( 1 ) {
		if ( canReachEntity( $player1 ) ) {
			setState( "state_Wait" );
		}
		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}
		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_Spooked
=====================
*/
void ai_alphalabs2_scientist1::state_Spooked() {
	vector ang;
	float endTime;

	animState( ANIMCHANNEL_HEAD, "Head_Spooked", 4 );
	lookAt( $player1, 1.2 );
	stopMove();
	sys.wait( 1.2 );
	
	if ( $player1.hasEnemies() ) {
		setState( "state_Cower" );
	}

	lookTarget.setOrigin( '80 -120 72' );	
	lookAt( lookTarget, 1.7 );
	endTime = sys.getTime() + 1.7;
	while( endTime > sys.getTime() ) {
		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}
		waitFrame();
	}
	
	lookTarget.setOrigin( '80 120 72' );	
	lookAt( lookTarget, 1.7 );
	endTime = sys.getTime() + 1.7;
	while( endTime > sys.getTime() ) {
		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}
		waitFrame();
	}
	
	if ( $player1.hasEnemies() ) {
		setState( "state_Cower" );
	}
	
	animState( ANIMCHANNEL_HEAD, "Head_StayClose", 4 );
	while( !inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
		waitFrame();
	}

	setState( "state_Lead" );
}

/*
=====================
ai_alphalabs2_scientist1::state_Lead
=====================
*/
void ai_alphalabs2_scientist1::state_Lead() {
	float	nextLookTime;
	float	leadTimeOut;

	nextLookTime = RandomDelay( ED_MIN_LOOK_DELAY, ED_MAX_LOOK_DELAY );
	moveToEntity( $scientist_destination );

	leadTimeOut = sys.getTime() + ED_LEAD_TIMEOUT;

	while( 1 ) {
		if ( AI_TALK ) {
			sayStuff();
		}
		
		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}

		if ( sys.getTime() > nextLookTime ) {
			lookAt( $player1, ED_LOOK_TIME );
			nextLookTime = RandomDelay( ED_MIN_LOOK_DELAY, ED_MAX_LOOK_DELAY );
		}

		checkBlocked();

		float result = checkDestinationDistance();
		if ( ( result != PLAYER_BEHIND_ME ) && ( result != PLAYER_LOST ) ) {
			leadTimeOut = sys.getTime() + ED_LEAD_TIMEOUT;
		} else if ( sys.getTime() > leadTimeOut ) {
			if ( event < ED_POINT_OF_NO_RETURN ) {
				setState( "state_Wait" );
			}
		} else {
			// look back at player to see what he's up to
			lookAt( $player1, 0.1 );
			nextLookTime += 0.1;
		}

		if ( AI_MOVE_DONE ) {
			moveToEntity( $scientist_destination );
		}		
		
		if ( AI_ACTIVATED ) {
			if ( inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
				doEvent();
			}
		}
		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_FindPlayer
=====================
*/
void ai_alphalabs2_scientist1::state_FindPlayer() {
	setTalkTarget( $null_entity );
	while( 1 ) {
		moveToPosition( lastValidPlayerPosition );
		if ( AI_MOVE_DONE || AI_DEST_UNREACHABLE ) {
			if ( !canReachEntity( $player1 ) ) {
				setState( "state_CantReachPlayer" );
			}
		}

		if ( $player1.hasEnemies() ) {
			setState( "state_Cower" );
		}
		
		if ( AI_TALK ) {
			sayStuff();
		}

		checkBlocked();
		
		if ( AI_ACTIVATED ) {
			if ( inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
				doEvent();
			}
		}

		float result = checkDestinationDistance();
		if ( canSee( $player1 ) && ( ( result == PLAYER_BEHIND_ME ) || ( result == PLAYER_OK ) ) ) {
			setState( "state_Wait" );
		} else if ( result == PLAYER_AHEAD_OF_ME ) {
			setState( "state_Lead" );
		}

		waitFrame();
	}
}

/*
=====================
ai_alphalabs2_scientist1::state_Cower
=====================
*/
void ai_alphalabs2_scientist1::state_Cower() {
	sys.wait( 0.6 );

	setTalkState( TALK_BUSY );
	setTalkTarget( $null_entity );

	lookAt( self, 0 );
	playerEnemy = $player1.closestEnemyToPoint( getOrigin() );
	if ( playerEnemy ) {
		stopMove();
		faceTowardsEntity( playerEnemy, 1 );
		sys.wait( 0.4 );

		animState( ANIMCHANNEL_HEAD, "Head_Attacked", 4 );

		sys.wait( 0.2 );
		cower = true;
		stopMove();

		while( $player1.hasEnemies() ) {
			if ( !playerEnemy ) {
				playerEnemy = $player1.closestEnemyToPoint( getOrigin() );
			}
			waitFrame();
		}
	}
	
	sys.wait( 0.8 );
	cower = false;
	setTalkState( TALK_OK );
	lookAt( $player1, 1 );
	sys.wait( 0.5 );
	
	animState( ANIMCHANNEL_HEAD, "Head_AttackDone", 10 );
	while( !inAnimState( ANIMCHANNEL_HEAD, "Head_Idle" ) ) {
		faceTowardsEntity( $player1, 1 );
		waitFrame();
	}
	
	sys.wait( 0.2 );

	setState( "state_Lead" );
}

//@doomscript-blueprint begin 6
//@source 4581ACA2
//@catalog 0C260740
//@node F06595FF-0 40 40
//@node 6A7D9DC7-0 330 40
//@node 6FD27941-0 40 40
//@node 58C1CC29-0 330 40
//@node D40BF2CA-0 610 40
//@node 54A9488E-0 405 145
//@node D28CDCAB-0 890 200
//@node 9E17650F-0 40 40
//@node FF85147D-0 330 40
//@node 361BA34C-0 610 40
//@node D85635EB-0 405 145
//@node 80BB72E5-0 890 200
//@node 83B5DDCA-0 40 40
//@node E10CCC07-0 330 40
//@node 0D9480E3-0 610 40
//@node C5D43E96-0 170 145
//@node 00E49226-0 400 145
//@node C4707E6F-0 890 200
//@node FDB85C4E-0 1170 200
//@node 3B2F3226-0 1450 40
//@node 90A32A00-0 1730 40
//@node 0AA4140B-0 40 40
//@node D8498CB5-0 330 40
//@node 00BDD8B6-0 610 40
//@node 0284F8A6-0 170 145
//@node 77205736-0 400 145
//@node 499205E0-0 890 200
//@node 8167014D-0 1170 200
//@node 125519DB-0 1450 40
//@node 00BDD8B6-1 1730 40
//@node 263D479B-0 1290 145
//@node 66F7626B-0 1520 145
//@node 499205E0-1 2010 200
//@node 8167014D-1 2290 200
//@node 3DDD3931-0 2570 40
//@node B154F873-0 2850 40
//@node DCC2A5BD-0 40 40
//@node FB4792AF-0 330 40
//@node 032364E2-0 125 145
//@node 15726A7B-0 610 200
//@node AEE259CA-0 1170 200
//@node 86DA0975-0 1450 40
//@node 95414F3F-0 1245 145
//@node 62DA2971-0 1040 145
//@node 687A5C8C-0 1730 40
//@node BCD5E78D-0 1290 145
//@node 36F9261D-0 1520 145
//@node DD2AD5CE-0 2010 200
//@node 74DEF52F-0 2290 200
//@node 9FC87977-0 2570 40
//@node EDD69F69-0 2850 40
//@node 549D6450-0 40 40
//@node 6DE6167C-0 330 40
//@node AAC782D5-0 610 40
//@node FAE20106-0 170 145
//@node 530216B6-0 400 145
//@node 0FA54EF9-0 890 200
//@node 95DE28E4-0 1170 200
//@node D556A048-0 1450 40
//@node 64C999A2-0 1730 40
//@node 54B6C1A2-0 40 40
//@node 6DD28719-0 330 40
//@node B1ADE82B-0 610 40
//@node 6F1A121A-0 170 145
//@node 7A9178EA-0 400 145
//@node 06E90FB7-0 890 200
//@node EC9C29A6-0 1170 200
//@node 444B6C0E-0 1450 40
//@node 2E4D4A78-0 1730 40
//@node 79475909-0 40 40
//@node 2258295F-0 330 40
//@node 05B62838-0 610 40
//@node 61EB2920-0 170 145
//@node 322DAC90-0 400 145
//@node F86C707A-0 890 200
//@node 7EC94FE3-0 1170 200
//@node F06FA593-0 1450 40
//@node E4C51B2D-0 1730 40
//@node 76475450-0 40 40
//@node D69FC664-0 330 40
//@node 61F6E285-0 610 40
//@node F1D4AFF0-0 170 145
//@node 52BF1C80-0 400 145
//@node 9900015D-0 890 200
//@node C11E5670-0 1170 200
//@node DE12B86C-0 1450 40
//@node A910FBFE-0 1730 40
//@node F092A199-0 40 40
//@node 5BE452B4-0 330 40
//@node AE453848-0 610 40
//@node 9C581366-0 170 145
//@node DD177676-0 400 145
//@node 0A70BD9A-0 890 200
//@node 84116E03-0 1170 200
//@node 770ACCB3-0 1450 40
//@node DDD7C88D-0 1730 40
//@node 72B818A8-0 40 40
//@node F0432FA5-0 330 40
//@node EBF1E77D-0 610 40
//@node 9960CADA-0 170 145
//@node 876DA6EA-0 400 145
//@node 59BB1DC4-0 890 200
//@node 72C3B042-0 1170 40
//@node 96872F49-0 40 40
//@node AD36FD3D-0 330 40
//@node 82BC1288-0 610 40
//@node A6618F00-0 170 145
//@node E2023E50-0 400 145
//@node 1722F1CE-0 890 200
//@node BFAF312F-0 1170 200
//@node 869CF3E9-0 1450 40
//@node EE553B69-0 1730 40
//@node 88CB6C66-0 40 40
//@node 4159B275-0 330 40
//@node 526F133F-0 125 145
//@node A5A68FBF-0 -80 145
//@node 4A247C8E-0 610 200
//@node DC0A7FDD-0 405 305
//@node 3D49AF35-0 890 200
//@node 326C5BC8-0 1170 200
//@node E76EE536-0 965 305
//@node E0B1358A-0 760 305
//@node CA1CF749-0 1450 200
//@node C1FE6524-0 1245 305
//@node 9DF2F2C9-0 1730 200
//@node A3535DC9-0 2010 200
//@node 91BC51D4-0 1805 305
//@node E86CEABB-0 1600 305
//@node 4A247C8E-1 2290 200
//@node 488E41FA-0 2085 305
//@node 4B88F745-0 2570 200
//@node 2CAD664F-0 2850 40
//@node 54467E25-0 2410 145
//@node 730617D5-0 2640 145
//@node CB4B534B-0 3130 200
//@node 3EC7DAB2-0 3410 200
//@node 98ACFF52-0 3690 40
//@node 5B87CAB4-0 3970 40
//@node C8E77208-0 40 40
//@node B6428AF4-0 330 40
//@node A4D75B79-0 125 145
//@node 742CFA14-0 610 200
//@node E49FE080-0 1170 200
//@node C9358DCD-0 1450 40
//@node 050378B6-0 1010 145
//@node 0543DDC6-0 1240 145
//@node B1A85085-0 1730 200
//@node AA87E0C8-0 2010 200
//@node 3E9B1B34-0 2290 40
//@node 360B4DD6-0 2570 40
//@node 61F2D79D-0 40 40
//@node 180F7959-0 330 40
//@node FF2B63EA-0 125 145
//@node FA913607-0 610 200
//@node 2E558948-0 1170 200
//@node D40F9327-0 1450 40
//@node FEE627DC-0 1245 145
//@node F66A7F52-0 1040 145
//@node 70EEF06C-0 1730 40
//@node 01F85942-0 1290 145
//@node 2D2B2652-0 1520 145
//@node FECDA202-0 2010 200
//@node AC35D09B-0 2290 200
//@node 77BF233B-0 2570 40
//@node 3FE02EA5-0 2850 40
//@node 1E824DAF-0 40 40
//@node 7479ADCF-0 330 40
//@node 0B1A4FE0-0 610 40
//@node 1AFC7A43-0 170 145
//@node 812C5913-0 400 145
//@node D1BEB095-0 890 200
//@node 2A9CDCEB-0 1170 40
//@node 50D4FE08-0 1450 40
//@node F97BF020-0 40 40
//@node 2AB65565-0 330 40
//@node 8ECB517B-0 610 40
//@node 5240F695-0 890 40
//@node 1AE651F2-0 450 145
//@node 84CA6EE2-0 680 145
//@node 5E4B2188-0 1170 200
//@node 6A3A064A-0 1450 40
//@node 92A3526B-0 1730 40
//@node EC9C428D-0 2010 40
//@node CE1EC298-0 40 40
//@node 35B1204B-0 330 40
//@node 000662ED-0 610 40
//@node 6E454A5C-0 40 40
//@node 6CBE823B-0 330 40
//@node AD896160-0 610 40
//@node 41E2C512-0 405 145
//@node 1FE70118-0 200 145
//@node DB841E60-0 890 200
//@node D992ED38-0 1170 40
//@node 78ED81F6-0 40 40
//@node B2FA6793-0 330 40
//@node 75E6CB61-0 105 145
//@node 2C97CBCD-0 610 40
//@node ABEB24C2-0 405 232
//@node CA36552B-0 890 40
//@node 5591B31F-0 685 145
//@node F839FC67-0 1170 40
//@node BA6C95F1-0 730 145
//@node 6AB4F941-0 960 145
//@node 8E3867BF-0 1450 200
//@node 0AC6B628-0 1245 305
//@node 87E6D43A-0 1730 360
//@node 23756979-0 1505 465
//@node 1F6DE5E1-0 2010 360
//@node 00B27335-0 1805 465
//@node 26D0B536-0 1600 465
//@node F49D833D-0 1600 549
//@node 8411134A-0 2290 520
//@node 799D67C2-0 2570 200
//@node CCF84253-0 2850 40
//@node 297525C4-0 3130 40
//@node 73000D0A-0 40 40
//@node C05EF8D3-0 330 40
//@node BFFF1D8B-0 125 145
//@node 2C7A4E02-0 610 200
//@node E1C6D03E-0 890 40
//@node 8B9ADF3A-0 40 40
//@node 231C46C1-0 330 40
//@node 2D62426C-0 105 145
//@node ACF7B95A-0 610 40
//@node E72DE443-0 170 145
//@node F6EADD33-0 400 145
//@node 2593046F-0 890 200
//@node A2E999EB-0 685 305
//@node 5669A3A1-0 480 305
//@node D49003DA-0 1170 360
//@node 51271F74-0 1450 200
//@node 9CC2AAA6-0 1245 305
//@node AE29D8E1-0 1040 305
//@node CC9AE055-0 1730 360
//@node EA4A65BA-0 2010 40
//@node 4ACA051D-0 1805 145
//@node 92C35F6C-0 2290 200
//@node D53849C3-0 2570 40
//@node 89B61C39-0 2850 40
//@node EA4A65BA-1 3130 200
//@node CF67934C-0 2925 305
//@node 92C35F6C-1 3410 360
//@node 3D31AAC4-0 3690 200
//@node 8F5144B8-0 3485 305
//@node C4A1CB99-0 3970 360
//@node DF508987-0 4250 200
//@node E870E1AA-0 3810 305
//@node 752A4B7A-0 4040 305
//@node 231C46C1-1 4530 360
//@node AD8812D9-0 4305 465
//@node 2593046F-1 4810 360
//@node E345CAFE-0 4605 465
//@node D942076A-0 4400 465
//@node D49003DA-1 5090 520
//@node 51271F74-1 5370 360
//@node 0A323C79-0 5165 465
//@node 5B0292AA-0 4960 465
//@node CC9AE055-1 5650 520
//@node A1A32529-0 40 40
//@node E320FAE4-0 330 40
//@node 2BB8D673-0 610 40
//@node 14E1A41F-0 405 145
//@node 960D03E7-0 890 200
//@node C80600A0-0 1170 40
//@node F71FCC4E-0 40 40
//@node A3E563C0-0 330 40
//@node 2E82AE9B-0 610 40
//@node 3DBAB6F6-0 890 40
//@node F12FC0E3-0 1170 40
//@node 8E12703F-0 730 145
//@node 47A6166F-0 960 145
//@node 9A7ED512-0 1450 200
//@node 7C202344-0 1245 305
//@node E39F689B-0 1730 360
//@node 9A1B619E-0 2010 200
//@node 42CD2D52-0 2290 40
//@node 9A7ED512-1 2570 40
//@node 973FADD5-0 2365 145
//@node 9CE9D9C4-0 2850 200
//@node C4A130AF-0 3130 40
//@node A984A636-0 2690 145
//@node 89F2DF46-0 2920 145
//@node 79E11221-0 3410 200
//@node 97474297-0 3185 305
//@node 03969B97-0 3690 200
//@node 0E8F97B7-0 3485 305
//@node 6E182DF1-0 3280 305
//@node 3423B014-0 3970 360
//@node 6A587F5C-0 4250 200
//@node 0B6CBB86-0 4045 305
//@node 9E648FDD-0 3840 305
//@node 4729880B-0 4530 360
//@node D3C9FB7C-0 4810 40
//@node 8DEC10A3-0 40 40
//@node B9FA099F-0 330 40
//@node 022D89A0-0 610 40
//@node F510D95A-0 890 40
//@node BF4A07AE-0 1170 40
//@node 4DD93B56-0 730 145
//@node C84698E6-0 960 145
//@node 1C3E541F-0 1450 200
//@node 8672E76B-0 1245 305
//@node 182BF7B6-0 1730 360
//@node 37074E61-0 2010 200
//@node 98C30AE9-0 2290 40
//@node 1C3E541F-1 2570 40
//@node 47AC3AE2-0 2365 145
//@node 425A4055-0 2850 200
//@node 74E5D12E-0 3130 40
//@node 9BAF6119-0 2690 145
//@node 2579EBC9-0 2920 145
//@node 1A878DF6-0 3410 200
//@node F4AFAEF1-0 3185 305
//@node CFAF6A0E-0 3690 200
//@node 8096DB15-0 3485 305
//@node 9E69353D-0 3280 305
//@node 449B2883-0 3970 360
//@node 6D55E15F-0 4250 200
//@node 98962669-0 4045 305
//@node E2B15644-0 3840 305
//@node D4A50B32-0 4530 360
//@node E9A6CF23-0 4810 40
//@node 66E3458C-0 40 40
//@node B846819E-0 330 40
//@node 9B31EAA3-0 125 145
//@node 07465D5F-0 610 40
//@node 162D742E-0 890 40
//@node AECEE2CB-0 685 232
//@node F80304C8-0 480 232
//@node 9B80D1CC-0 1170 40
//@node 64AA9F3C-0 965 145
//@node F0972437-0 1450 200
//@node 4C4184BD-0 1730 200
//@node 678EDDA5-0 1525 305
//@node B6496659-0 2010 360
//@node 25A1E41B-0 1785 465
//@node E4B3FD51-0 2290 360
//@node D9419CFC-0 2065 465
//@node 358239AD-0 2570 360
//@node 18CEF44C-0 2345 465
//@node 1FBED414-0 2140 565
//@node 02DACA56-0 2850 360
//@node 79DDD1A2-0 2625 465
//@node 4D5FCD6B-0 3130 360
//@node 12735924-0 2905 465
//@node 020A7FC4-0 2700 565
//@node C3260EB0-0 2495 565
//@node C6261369-0 2495 643
//@node D6504191-0 3410 360
//@node 43AD5E44-0 3205 465
//@node 9FE0166C-0 3690 520
//@node 349ADE99-0 3485 625
//@node 40B1FDAD-0 3970 520
//@node EB92866F-0 3765 625
//@node 34EE80D1-0 4250 520
//@node 5378A87E-0 4045 625
//@node A3EBEEE3-0 4530 360
//@node E59C8C6D-0 4325 465
//@node 47B42AAC-0 4120 465
//@node BF6A2DC1-0 4810 360
//@node 54D1BF31-0 4605 465
//@node 2A680366-0 4400 465
//@node 53963D66-0 5090 520
//@node EA3B6BCA-0 4885 625
//@node D9C4D67D-0 4680 625
//@node 510DB52D-0 5370 520
//@node 9D90368C-0 5165 804
//@node 3AFFC909-0 4960 804
//@node 938C8220-0 5650 520
//@node 2618F823-0 5930 520
//@node 84F9EA66-0 5725 804
//@node 06F14095-0 6490 520
//@node 3E9F91F4-0 6285 625
//@node 9AABF798-0 6080 625
//@node 510DB52D-1 6770 520
//@node 4E4FE88D-0 6565 804
//@node 32CC2220-0 6360 804
//@node 7A176D20-0 7050 520
//@node 8B0A7D46-0 6845 804
//@node DB75C3A1-0 7330 520
//@node CA412200-0 7610 200
//@node 7C37D586-0 7890 40
//@node 44A5D645-0 8170 40
//@node D556F0A8-0 40 40
//@node F22E5270-0 330 40
//@node 3BB73FD7-0 610 40
//@node 7F04E768-0 405 145
//@node 0E092CA2-0 890 40
//@node 68CB3F06-0 685 145
//@node F1B90F06-0 1170 40
//@node 7893A135-0 965 145
//@node A42E3799-0 1450 40
//@node EE762E06-0 1245 145
//@node 148A9251-0 1730 40
//@node 9DDE0C79-0 1525 145
//@node 24BE2C7F-0 2010 40
//@node 34FC1723-0 1805 145
//@node D67DB035-0 2290 40
//@node 9D39DB64-0 2065 145
//@node 09B4126D-0 2570 40
//@node 7303A618-0 2850 40
//@node EEB58A6A-0 3130 40
//@node 0D9EE39E-0 2905 145
//@node 2777C84B-0 2700 245
//@node 2867B414-0 2495 245
//@node 6FE83F60-0 3410 40
//@node 388D015A-0 3690 40
//@node 8EE60AA2-0 3970 40
//@node 616E4740-0 4250 40
//@node 3019B702-0 4530 40
//@node 0BFFFE0E-0 4810 40
//@node 614CCE16-0 5090 40
//@node B6B1F5C8-0 5370 40
//@node B14153B7-0 5650 40
//@node 7FB55D0C-0 40 40
//@node D308AAC2-0 330 40
//@node 416E93D8-0 610 40
//@node 61CE4A76-0 890 40
//@node FE5ACC23-0 685 145
//@node 79698ADC-0 1170 200
//@node C1733401-0 965 300
//@node CAA73569-0 1450 200
//@node 6E39D991-0 1245 305
//@node 29AAD576-0 40 40
//@node CB024C33-0 330 40
//@node 4B838F26-0 105 145
//@node 0CF85C05-0 610 40
//@node B3966FF2-0 385 145
//@node 735962C1-0 890 40
//@node BA86F877-0 665 145
//@node C81424AD-0 460 245
//@node F107AA02-0 1170 40
//@node F47B6ABC-0 945 145
//@node D3239E87-0 1450 40
//@node A6436D01-0 1225 145
//@node 0E9CC400-0 1020 245
//@node CB434796-0 815 245
//@node CA434603-0 815 323
//@node 46C791BF-0 1730 40
//@node 3401A566-0 1525 145
//@node 3CB95D93-0 2010 200
//@node 12ED02AD-0 2290 200
//@node 2B196050-0 2085 305
//@node 3CB95D93-1 2570 200
//@node EE1A952D-0 2850 40
//@node D7DC7712-0 40 40
//@node 40947524-0 330 40
//@node A4642FDD-0 610 40
//@node D47FE079-0 405 145
//@node 2E1A5E15-0 890 40
//@node 45F611A5-0 685 145
//@node 38370B80-0 480 145
//@node B992025E-0 480 229
//@node 46832FCF-0 1170 200
//@node 49F35681-0 965 305
//@node 33547E85-0 760 305
//@node E4B0131B-0 760 389
//@node 8C7EC11B-0 1450 200
//@node 84D1C88C-0 1245 300
//@node 32A35311-0 1245 392
//@node A86B89DA-0 1245 484
//@node AAF31061-0 1730 200
//@node 68AA7A5B-0 1525 305
//@node 0E5D872B-0 2010 200
//@node CC43F169-0 2290 40
//@node 112DE741-0 2570 40
//@node AEED67FF-0 2365 145
//@node 8223DBF1-0 40 40
//@node CA298FD3-0 330 40
//@node C6A1083E-0 610 40
//@node 29907F5C-0 405 145
//@node 9EBFFAFC-0 890 40
//@node E821F827-0 685 145
//@node D7541F70-0 480 145
//@node D9EEBEAE-0 480 229
//@node 807202C7-0 1170 200
//@node 835F9714-0 965 305
//@node F4219D2D-0 760 305
//@node 0C60D323-0 760 389
//@node 4854E398-0 1450 200
//@node 4090EAEB-0 1245 300
//@node 069A984E-0 1245 392
//@node 44C17DA5-0 1245 484
//@node 2C654A38-0 1730 200
//@node 2E32DD43-0 1525 305
//@node A6466534-0 2010 200
//@node FE01DA23-0 2290 40
//@node 3ECE1A77-0 2570 40
//@node EBE931B0-0 2365 145
//@node 18AB1245-0 40 40
//@node DF6FDE32-0 330 40
//@node 4E2ACAD3-0 610 40
//@node DF6FDE32-1 890 40
//@node CAF7DFCC-0 1170 40
//@node 1845E550-0 1450 40
//@node 0BFB97C1-0 1730 40
//@node 92387270-0 1525 145
//@node C514C7A3-0 2010 200
//@node E8B4C331-0 2290 200
//@node 018794EB-0 2570 200
//@node 33CF7DF0-0 2850 200
//@node 4BF329B1-0 2645 300
//@node 93B95DAC-0 3130 200
//@node 78655B1A-0 3410 200
//@node CAD8B85B-0 3690 200
//@node 59427E3C-0 3485 300
//@node 20A19AFF-0 3970 200
//@node 494E0C9C-0 40 40
//@node 25022A36-0 330 40
//@node B93D0B0A-0 610 40
//@node 84B82BD4-0 385 145
//@node 69ADC277-0 890 40
//@node 5866D24D-0 1170 40
//@node D8563E86-0 1450 40
//@node DF3AE62A-0 1225 145
//@node BDD8D970-0 1730 40
//@node 0F3AA04D-0 2010 40
//@node 90BBFF61-0 1805 140
//@node D8070C3D-0 2290 40
//@node 4C4E1155-0 40 40
//@node 4F3C426B-0 330 40
//@node 0BB8FE22-0 105 145
//@node 9AD43C02-0 610 40
//@node D9B99210-0 890 40
//@node 27D5B7D5-0 1170 40
//@node 70C57D90-0 945 145
//@node BA578B30-0 1450 40
//@node 2552B068-0 1730 40
//@node 8A114D6B-0 1525 140
//@node 40D5AE20-0 2010 40
//@node E36B6625-0 40 40
//@node 8EEED609-0 330 40
//@node DBBDB680-0 125 145
//@node CD309AB1-0 610 40
//@node 80651857-0 385 145
//@node 230D43C8-0 890 40
//@node ACDDD049-0 685 145
//@node 4F258BAA-0 480 145
//@node AC4D263C-0 1170 40
//@node 592A83B1-0 965 145
//@node 57970225-0 760 145
//@node 1BB82032-0 1450 200
//@node 8422D41C-0 1730 200
//@node 39BB6F4E-0 2010 200
//@node 82A72BAF-0 1805 305
//@node BAAAF2B8-0 1600 305
//@node C003B18B-0 2290 200
//@node 2D72DB79-0 2570 200
//@node 90D01B2A-0 2365 305
//@node 1107F282-0 2160 305
//@node 6892C9ED-0 2850 200
//@node 4A9A80AA-0 3130 200
//@node CB36F011-0 2925 305
//@node 102627A4-0 2720 305
//@node 21C39404-0 3410 200
//@node 2AA1A7CF-0 3690 200
//@node DDC95FA9-0 3485 305
//@node 20FACCC9-0 3280 305
//@node EE13251B-0 3970 200
//@node 8422D41C-1 4250 200
//@node B77918EB-0 4530 200
//@node C8D438C8-0 4325 305
//@node B162B192-0 4120 305
//@node 323C1159-0 4810 200
//@node 4F6C05C5-0 5090 200
//@node 046E26EF-0 4885 305
//@node 5BFDB9A5-0 4680 305
//@node AD0E4BF8-0 5370 200
//@node E989F475-0 40 40
//@node 02DAE33B-0 330 40
//@node 3A827ACA-0 610 40
//@node 5BB23886-0 170 145
//@node B7452EF6-0 400 145
//@node 1419FE3A-0 890 200
//@node E626BC6E-0 1170 40
//@node 3AEF79A0-0 40 40
//@node 7BC5908C-0 330 40
//@node 372CCFBC-0 105 145
//@node 1CD81174-0 610 40
//@node 98F930A2-0 405 145
//@node 57DFC2E7-0 200 145
//@node 82E973A0-0 200 229
//@node 88A7728E-0 890 200
//@node D8355D07-0 1170 200
//@node BA44C4BE-0 965 305
//@node B7B9E1F2-0 760 305
//@node F76DA9AD-0 40 40
//@node EF8158AF-0 330 40
//@node 360D3C69-0 125 145
//@node 04E8EB9F-0 610 40
//@node FB42A8E4-0 385 145
//@node 1BCC9DD8-0 890 40
//@node 981BA2EB-0 685 145
//@node B4C7F47D-0 480 145
//@node CB3ABB63-0 1170 200
//@node 1804D7C4-0 965 305
//@node A5B2A954-0 1450 200
//@node A81281B7-0 1245 305
//@node 55CE7D2C-0 1040 305
//@node 0F470EB0-0 1730 200
//@node DD542565-0 1525 305
//@node EC3525E3-0 2290 200
//@node F89C5229-0 2085 305
//@node 2364DF72-0 2570 40
//@node 5DD926C5-0 2345 145
//@node E0040E9D-0 2140 245
//@node 62977B6B-0 2850 40
//@node 857E5BCD-0 2645 145
//@node B3428D29-0 2440 145
//@node 914168DA-0 3130 200
//@node B155F5F8-0 3410 40
//@node 0FE71C60-0 2970 145
//@node 4FE44B10-0 3200 145
//@node D84CFD26-0 3690 200
//@node 3086BC6D-0 3465 305
//@node 0C4F4542-0 3970 200
//@node 4CA4ECE3-0 3745 305
//@node F26CDD37-0 3540 405
//@node C4C713A5-0 4250 200
//@node BEDB3687-0 4045 305
//@node E5889987-0 3840 305
//@node DE60FC7F-0 3840 389
//@node FC256C64-0 4530 360
//@node A97A5D66-0 5090 360
//@node AD8E6AC5-0 5370 40
//@node 827FECA1-0 5165 145
//@node 96C1FDF7-0 4960 145
//@node D84CFD26-1 5650 200
//@node 1FD10B5C-0 5425 305
//@node 0C4F4542-1 5930 200
//@node 07F3ED38-0 5705 305
//@node D5EE7C13-0 5500 405
//@node C4C713A5-1 6210 200
//@node A387B172-0 6005 305
//@node E67F17B0-0 5800 305
//@node 096F570E-0 5800 389
//@node FC256C64-1 6490 360
//@node 4B9C6B5F-0 7050 360
//@node 914168DA-1 7330 40
//@node BBD38D61-0 40 40
//@node AA384F18-0 330 40
//@node 80030E58-0 125 145
//@node 06D83854-0 610 200
//@node EAB3581F-0 385 305
//@node 9C81BF72-0 890 360
//@node 6B00BCB0-0 665 465
//@node 472358B7-0 1170 200
//@node 4F724A26-0 40 40
//@node 3579BA18-0 330 40
//@node F7F258E3-0 125 145
//@node 7EE63106-0 610 200
//@node F882454E-0 385 305
//@node D6D57C09-0 890 200
//@node E4906CA2-0 685 305
//@node 3340DFC9-0 480 305
//@node 0D203E31-0 1170 360
//@node EC1162D9-0 965 460
//@node F6DE8805-0 1450 360
//@node EF0DCBC6-0 1730 200
//@node C0AE2C8E-0 2010 200
//@node 682C7D4D-0 1785 305
//@node 59FC3A18-0 2290 200
//@node 819A848F-0 2570 200
//@node C28084A9-0 2850 200
//@node CF9CA008-0 2645 305
//@node 3B8FA035-0 3130 360
//@node 1AAA8F82-0 2905 465
//@node 137B3CF8-0 3410 360
//@node EA754ADD-0 3205 465
//@node C72583BE-0 3690 360
//@node DD4545D0-0 3485 465
//@node 80EA3CC5-0 3280 465
//@node 9B1DA5B1-0 3970 520
//@node DE7D0DEF-0 4250 520
//@node 7BC3E175-0 4045 625
//@node 15FD630D-0 4530 680
//@node E9D2F4E0-0 4810 520
//@node F41A465C-0 4605 625
//@node 15FD630D-1 5090 680
//@node 819A848F-1 5370 520
//@node C270705D-0 5650 360
//@node 8AE77256-0 5425 465
//@node 6371383B-0 5930 520
//@node 5824C195-0 6210 360
//@node D372D841-0 6490 360
//@node EE4ECBEA-0 6285 465
//@node 15E62E15-0 6770 520
//@node 629DA726-0 7050 360
//@node 6E23CAC9-0 40 40
//@node 3414AD90-0 330 40
//@node 71BDAF1C-0 610 40
//@node DA4A4D9C-0 890 40
//@node C88BF8C3-0 1170 40
//@node 7BBFA128-0 965 140
//@node 1B86A526-0 1450 40
//@node 68A2CEBE-0 1245 145
//@node 1D551AEB-0 1730 40
//@node A4A0D0F7-0 2010 40
//@node 79FF4845-0 2290 40
//@node E9582D24-0 2570 40
//@node EE7821B3-0 2850 40
//@node 09624AFA-0 40 40
//@node 05F3523F-0 330 40
//@node 9178FA02-0 125 145
//@node D29E0D36-0 610 40
//@node E6BDDD8A-0 890 40
//@node 1DE0887A-0 685 140
//@node EE4A7715-0 1170 40
//@node 41327A55-0 965 145
//@node 92515369-0 1450 40
//@node 95DE8683-0 1730 40
//@node 37C9BC98-0 2010 40
//@node 8DE8524B-0 2290 40
//@node DEBE81D1-0 2570 40
//@node 115F2158-0 2850 40
//@node E6ACACB8-0 3130 40
//@node DFF2C3BE-0 3410 40
//@node AEE81833-0 3690 40
//@node 89077B38-0 3970 40
//@node E6A5DA58-0 40 40
//@node 0A817824-0 330 40
//@node AEFBEB19-0 105 145
//@node B64DC79E-0 610 40
//@node 7F884F28-0 385 145
//@node 28E8E916-0 890 40
//@node 5DF86203-0 685 145
//@node B8D9EDF3-0 1170 40
//@node AC9A8B5A-0 965 145
//@node 8365E2F2-0 1450 200
//@node D17B58E0-0 1730 200
//@node E4A5CC53-0 1525 305
//@node C18836A3-0 1320 305
//@node 988CEEB6-0 2010 360
//@node 48565DEA-0 1805 465
//@node B0F8CEAA-0 2290 520
//@node 25F34144-0 2570 360
//@node 77C9FB5D-0 2850 200
//@node 2D22C5CB-0 3130 200
//@node C6D8FFF8-0 2690 305
//@node D28B50C8-0 2920 305
//@node 988CEEB6-1 3410 360
//@node B1FD159F-0 3205 465
//@node B0F8CEAA-1 3690 520
//@node 25F34144-1 3970 360
//@node 0F599DB9-0 4250 200
//@node 60E5946F-0 3810 305
//@node 24021EFF-0 4040 305
//@node 988CEEB6-2 4530 360
//@node 19E004F8-0 4325 465
//@node B0F8CEAA-2 4810 520
//@node 25F34144-2 5090 360
//@node 96B2AF6B-0 5370 200
//@node 7F770193-0 5650 200
//@node D138D1C7-0 5425 305
//@node 988CEEB6-3 5930 360
//@node 319E4AED-0 5725 465
//@node B0F8CEAA-3 6210 520
//@node 25F34144-3 6490 360
//@node 0F609DA5-0 6770 200
//@node D17B58E0-1 7050 200
//@node 91F41AC4-0 6845 305
//@node 0A3E57EA-0 6640 305
//@node 988CEEB6-4 7330 360
//@node 122C91B6-0 7125 465
//@node B0F8CEAA-4 7610 520
//@node 25F34144-4 7890 360
//@node 98ABECBE-0 8170 200
//@node 2D22C5CB-1 8450 200
//@node 48441A0F-0 8010 305
//@node 85DA935F-0 8240 305
//@node 988CEEB6-5 8730 360
//@node F488EF7B-0 8525 465
//@node B0F8CEAA-5 9010 520
//@node 25F34144-5 9290 360
//@node 0F599DB9-1 9570 200
//@node DEF0EA08-0 9130 305
//@node 61A24B58-0 9360 305
//@node 988CEEB6-6 9850 360
//@node 00B4B9C4-0 9645 465
//@node B0F8CEAA-6 10130 520
//@node 25F34144-6 10410 360
//@node 96B2AF6B-1 10690 200
//@node 7F770193-1 10970 200
//@node A904E0C0-0 10745 305
//@node 988CEEB6-7 11250 360
//@node ECF39319-0 11045 465
//@node B0F8CEAA-7 11530 520
//@node 25F34144-7 11810 360
//@node 45304929-0 40 40
//@node 10D6F1BE-0 330 40
//@node 547EABAC-0 610 40
//@node 00350B77-0 890 40
//@node F43E8A9E-0 685 145
//@node 48D96772-0 1170 40
//@node 2AFAECFE-0 1450 40
//@node DFE1BC87-0 1730 40
//@node 3FCC956F-0 2010 40
//@node CB1924E3-0 1805 145
//@node 8D5E7BAF-0 1600 145
//@node 7AA72994-0 2290 200
//@node 0CC91AE3-0 2085 305
//@node 628A7030-0 2570 360
//@node 30111052-0 2365 465
//@node 0CF9CBC4-0 2850 360
//@node 1ED99F74-0 3130 360
//@node B63EB7AE-0 3410 200
//@node C175698F-0 3690 200
//@node 77A638E8-0 3970 40
//@node B4CFD7E6-0 4250 40
//@node 2BDC88AA-0 4045 145
//@node 7197CF8E-0 3840 145
//@node D71E4BDE-0 4530 200
//@node C175698F-1 4810 200
//@node 00350B77-1 5090 40
//@node EDF59C35-0 4885 145
//@node 859A1F35-0 5370 40
//@node 6A73D4EC-0 5650 40
//@node C6A9482B-0 5210 145
//@node 359022BB-0 5440 145
//@node D71E4BDE-1 5930 200
//@node C175698F-2 6210 200
//@node 8710BC7F-0 6490 40
//@node 74FEF1E2-0 6770 40
//@node 9A0D1B62-0 6545 145
//@node 6B25CE68-0 7050 40
//@node D0C22379-0 40 40
//@node 9FD2F3A8-0 330 40
//@node C5519148-0 125 145
//@node 38580E4F-0 -80 145
//@node 28381830-0 890 200
//@node 61FA17F9-0 890 200
//@node E889A3F6-0 685 305
//@node 362DB921-0 480 305
//@node 267A9E7C-0 1450 200
//@node 08442138-0 1450 200
//@node 1F208AF8-0 1245 305
//@node 5535F194-0 1040 305
//@node 7129391E-0 1040 389
//@node 267A9E7C-1 2010 200
//@node 47464A1C-0 2290 40
//@node 95F2C905-0 2570 40
//@node 7FB9A710-0 2570 40
//@node CC651AB8-0 2365 145
//@node A3398128-0 2160 145
//@node 32E509E0-0 2850 40
//@node CFB2219F-0 2645 145
//@node 7779ED62-0 3410 200
//@node 379F9AF0-0 3410 200
//@node 106E27C9-0 3205 305
//@node 5F8BB472-0 3970 360
//@node B9D2B19B-0 3970 200
//@node DED55E39-0 3745 305
//@node 9FD2F3A8-1 4250 200
//@node C4FE497F-0 4045 305
//@node CB1E636E-0 3840 305
//@node 28381830-1 4810 360
//@node 61FA17F9-1 4810 360
//@node 54A7613F-0 4605 465
//@node 44FE57B0-0 4400 465
//@node 267A9E7C-2 5370 360
//@node 08442138-1 5370 360
//@node 272D2263-0 5165 465
//@node 3DE5B6D5-0 4960 465
//@node 93FE63D5-0 4960 549
//@node 267A9E7C-3 5930 360
//@node F8E3DB9A-0 5930 360
//@node 71960A9A-0 5725 465
//@node 2BE5F250-0 5520 465
//@node 21D578C8-0 5520 549
//@node D8B3F67C-0 6490 360
//@node F379949C-0 6490 200
//@node 2F34D12B-0 6265 305
//@node 5A86267A-0 7050 360
//@node 1B2CE0BB-0 7050 200
//@node BE32E0F2-0 6845 305
//@node A68C9D51-0 7330 360
//@node 37AC0B31-0 7105 465
//@node A25F3994-0 7890 520
//@node 2A923483-0 8170 200
//@node D4E6DBEE-0 40 40
//@node D7339151-0 330 40
//@node 7A0CF3DE-0 125 145
//@node AC38DCFB-0 610 200
//@node 75128E26-0 405 300
//@node C18C4A1D-0 890 200
//@node 0FF92720-0 685 305
//@node 413E1F5A-0 1170 360
//@node 2B6B90D0-0 730 465
//@node 49698580-0 960 465
//@node 064B091F-0 1450 520
//@node 45DD75C9-0 1730 200
//@node 8068B7ED-0 1505 305
//@node 4D067207-0 2010 360
//@node 7FB3C078-0 2290 200
//@node 517AE435-0 2570 200
//@node 6B07CEE5-0 2365 305
//@node A7B3771A-0 2160 305
//@node C2694073-0 3130 360
//@node C2D50E01-0 3130 200
//@node D6D63E14-0 2925 305
//@node ED830391-0 2720 305
//@node 265C2940-0 3690 360
//@node 4FBD9C2A-0 3970 200
//@node 8DD0D04C-0 40 40
//@node F034E6F4-0 330 40
//@node 7F6C0F45-0 610 40
//@node 0547DCCF-0 890 40
//@node F9336A75-0 685 145
//@node 057A0549-0 1170 200
//@node A7D81A85-0 945 305
//@node E3A12BD6-0 1450 360
//@node E32F8E83-0 1730 200
//@node 7794DF48-0 1505 305
//@node 0A99F1ED-0 2010 360
//@node 74CB15CC-0 2290 200
//@node 5ECC2AAF-0 40 40
//@node 157ED142-0 330 40
//@node BCBEFBA0-0 610 40
//@node D54F2CFE-0 890 40
//@node 0CF352DE-0 1170 40
//@node 9C6E6306-0 1450 40
//@node CBBDAF59-0 1225 145
//@node 34C79D30-0 1730 200
//@node 2171549C-0 2010 40
//@node 180A64AF-0 2290 40
//@node FB91280E-0 2085 140
//@node BA0AFEB4-0 2570 40
//@node 04BA9B29-0 2365 145
//@node 83DDAA4A-0 2850 40
//@node 4D311F82-0 2625 145
//@node 9C6E6306-1 3130 200
//@node 6C36C308-0 2905 305
//@node 34C79D30-1 3410 360
//@node CD075FF5-0 3690 200
//@node 5E9942BF-0 3970 40
//@node 180A64AF-1 4250 40
//@node 1FE01BF7-0 4045 140
//@node BA0AFEB4-1 4530 40
//@node 0B9E2ABA-0 4325 145
//@node 83DDAA4A-1 4810 40
//@node C2C01FFD-0 4585 145
//@node 9C6E6306-2 5090 200
//@node A0F6E65F-0 4865 305
//@node 34C79D30-2 5370 360
//@node CD075FF5-1 5650 200
//@node 9C6E6306-3 5930 40
//@node 7FA794EE-0 5705 145
//@node 34C79D30-3 6210 200
//@node D9E3F64A-0 6490 40
//@node 21258036-0 6770 40
//@node 1DB5E685-0 6330 145
//@node 58DDA5F5-0 6560 145
//@node CD075FF5-2 7050 200
//@node 1E0AE6EE-0 7330 40
//@node 70F432AE-0 40 40
//@node BD46713F-0 330 40
//@node 355F5495-0 105 145
//@node C5776912-0 610 40
//@node 1127CC72-0 890 40
//@node 5F0EC22D-0 685 145
//@node 106040D1-0 1170 40
//@node D4369D67-0 965 145
//@node 96527855-0 1450 200
//@node 9AED3B24-0 1245 305
//@node A6D632F1-0 1730 360
//@node 9D377DA1-0 2010 200
//@node 7CD91970-0 1785 305
//@node 42C3189F-0 2290 360
//@node EBB7E37C-0 2570 200
//@node C97DE6F9-0 2365 305
//@node A123906D-0 2160 305
//@node 2A3B3B93-0 2850 360
//@node BD46713F-1 3130 360
//@node 2DA44182-0 2905 465
//@node F0FCDA70-0 3410 200
//@node 2C106A79-0 3690 200
//@node 5D7A6209-0 3485 305
//@node C679E758-0 3280 305
//@node 1127CC72-1 3970 360
//@node 2730658A-0 3765 465
//@node 24924A51-0 4250 360
//@node 4BDE36B9-0 4045 465
//@node BAF6CCA1-0 3840 465
//@node D5AFBDA1-0 4530 360
//@node 9D6877C6-0 4325 465
//@node 54988BE4-0 4120 465
//@node 5BCDCDE8-0 5090 520
//@node 507CF035-0 5650 360
//@node 76A4C93C-0 5650 360
//@node 2F503FA3-0 5445 465
//@node 9B9A6335-0 5240 465
//@node 5429C285-0 5930 200
//@node D64FB2D1-0 5725 305
//@node C5776912-1 6490 360
//@node 06435468-0 6490 200
//@node 49497A2A-0 6285 305
//@node 36185E6E-0 6770 360
//@node 1BC8D816-0 6545 465
//@node 9C56D1E1-0 7330 520
//@node D66E2EE2-0 7610 200
//@node FEF0C272-0 40 40
//@node F3EFA47A-0 330 40
//@node 109F00FD-0 610 40
//@node 71DC6947-0 405 145
//@node 9F07A7A3-0 890 200
//@node 10E2EC28-0 685 300
//@node 1ED6DDA3-0 1170 200
//@node ACD1D474-0 965 305
//@node 9CAE0D5F-0 760 305
//@node FAA342EA-0 760 389
//@node 9040EFB2-0 1450 360
//@node 78891F1E-0 1010 465
//@node 59CF91EE-0 1240 465
//@node 412BF517-0 1730 520
//@node 8800BEA1-0 2010 200
//@node E0F5755B-0 1785 305
//@node 8FAA6D6F-0 2290 360
//@node DD2BE155-0 2570 200
//@node B818EE99-0 2365 305
//@node 8C760DE1-0 2850 360
//@node 81C62700-0 3130 200
//@node C8FD4F68-0 3410 200
//@node 6F8F2751-0 3205 305
//@node 716BD96E-0 3690 360
//@node D97F30CF-0 3465 465
//@node F73542D1-0 3970 520
//@node DFD3B7AC-0 4250 200
//@node 416F723B-0 4045 305
//@node 6C66FFE5-0 3840 305
//@node 189EDAD8-0 4810 360
//@node 86B5B7D8-0 4810 360
//@node 1159F31A-0 4605 465
//@node C28A6C3D-0 4400 465
//@node 9CAFD9E3-0 5370 360
//@node F1633572-0 5650 200
//@node 23B24A2C-0 40 40
//@node ED51673E-0 330 40
//@node 19859E53-0 610 40
//@node B8BBBBD0-0 890 40
//@node 9747464A-0 1170 40
//@node D127D2EE-0 1450 40
//@node CFA6B420-0 1225 145
//@node 544478CD-0 1730 40
//@node 5034A80A-0 1525 145
//@node 3900E0B1-0 2010 200
//@node 8C461E8C-0 2290 200
//@node 236F5DF1-0 2085 300
//@node 3EADC160-0 2570 200
//@node C0F9CE9B-0 2850 200
//@node 23B74212-0 3130 200
//@node B97D6D35-0 3410 200
//@node D087A9FC-0 3205 305
//@node 3900E0B1-1 3690 200
//@node FBFDFD2D-0 3970 200
//@node AFD9E160-0 3745 305
//@node 82ED6A16-0 4250 360
//@node 55E40166-0 4045 465
//@node 63AE80F6-0 3840 465
//@node D127D2EE-1 4530 520
//@node DCA5CF8B-0 4305 625
//@node DC791E48-0 4810 360
//@node BAE44A3C-0 5090 40
//@node 2419D72C-0 5370 40
//@node 248B299D-0 5165 145
//@node 62BFEA4A-0 5650 40
//@node E5E73A05-0 5930 40
//@node 32F8F4B1-0 6210 40
//@node 13700AF7-0 6490 40
//@node F331B1E3-0 6770 40
//@node 72773637-0 6330 145
//@node 6D4BFC87-0 6560 145
//@node 61A487DF-0 7050 200
//@node DC791E48-1 7330 200
//@node 23B74212-1 7610 40
//@node F22B29D1-0 7890 40
//@doomscript-blueprint end
