/***********************************************************************

ai_character_sentry.script

***********************************************************************/

#define SENTRY_WAIT_GETCLOSER		3
#define	SENTRY_LEAD_TIMEOUT			1
#define SENTRY_FIRERATE				0.1
#define SENTRY_MIN_SHOTS			8
#define SENTRY_MIN_LOOK_DELAY		4
#define	SENTRY_MAX_LOOK_DELAY		8
#define	SENTRY_LOOK_TIME			1.5
#define SENTRY_LEAD_DIST			140
#define SENTRY_LOST_DIST			280
#define SENTRY_WALKTURN				65
#define SENTRY_WALKTURN2			30
#define SENTRY_ATTACK_MAX_LENGTH	4
#define SENTRY_ATTACK_MIN_LENGTH	1.2
#define SENTRY_WAIT_MAX_LENGTH		1
#define SENTRY_WAIT_MIN_LENGTH		0.3
#define SENTRY_MIN_TURN				10

#define RETREATING					-1
#define	NOT_MOVING					0
#define	APPROACHING					1

#define RETREATING_DEST				-1
#define	APPROACHING_DEST			1

#define PLAYER_LOST					0
#define PLAYER_BEHIND_ME			1
#define PLAYER_OK					2
#define PLAYER_AHEAD_OF_ME			3

object char_sentry : character {
	boolean		lead_player;
	float		hanging;
	boolean		awake;
	boolean		fire;
	float		playerMoveState;
	entity		light;
	boolean		light_on;
	float		nextPositionSearch;
	entity		ignore_enemy;
	float		ignore_enemy_time;
	vector		lastValidPlayerPosition;
	float		playerPositionThread;
	
	//
	// States
	//
	void		state_WaitForTrigger();
	void		state_Idle();
	void		state_Killed();
	void		state_FollowPath();
	void		state_Wait();
	void		state_GetCloser();
	void		state_CantReachPlayer();
	void		state_Lead();
	void		state_FindPlayer();
	void		state_Combat();
	void		combat_chase();
	boolean		find_attack_position();

	// attack checks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();

	void		state_Begin();
	void		init();
	void		destroy();

	void		spawn_flashlight();
	void		flashlight_off();
	void		flashlight_on();
	void		ignore( entity ignore_ent );
	boolean		checkForEnemy( float use_fov );
	
	float		checkDestinationDistance();
	void		updatePlayerPositionThread();

	// path commands
	void		path_sentry_light_on();
	void		path_sentry_light_off();
	void		path_sentry_shutdown();
	void		path_sentry_unlock_door();
	void		path_corner();
	void		path_sentry_lead_player();
	void		path_sentry_ignore_player();
		
	// torso anim states
	void		Torso_Death();
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_RangeAttack();
	
	// legs anim states
	void		Legs_Fold();
	void		Legs_Folded();
	void		Legs_Unfold();
	void		Legs_Hanging();
	void		Legs_Death();
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_TurnLeft();
	void		Legs_TurnRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void char_sentry::Torso_Death() {
	finishAction( "dead" );

	// never exit
	waitUntil( 0 );
}

void char_sentry::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	eachFrame {
		if ( AI_PAIN ) {
			Torso_Pain();
			idleAnim( ANIMCHANNEL_TORSO, "stand" );
		}
		if ( fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
		}
	}
}

void char_sentry::Torso_Pain() {
	string animname;

	animname = getPainAnim();
	setBlendFrames( ANIMCHANNEL_TORSO, 2 );
	playAnim( ANIMCHANNEL_TORSO, animname );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	// no pain for 2 seconds
	preventPain( 2 );
	
	finishAction( "pain" );
	setBlendFrames( ANIMCHANNEL_TORSO, 4 );
}

void char_sentry::Torso_RangeAttack() {
	float endtime;
	float firetime;
	float numshots;
	
	setAnimPrefix( "" );
		
	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	numshots = 0;
	while( fire || ( numshots < SENTRY_MIN_SHOTS ) ) {
		endtime = RandomDelay( SENTRY_ATTACK_MIN_LENGTH, SENTRY_ATTACK_MAX_LENGTH );
		setBlendFrames( ANIMCHANNEL_TORSO, 2 );
		playCycle( ANIMCHANNEL_TORSO, "range_attack_loop" );
		firetime = sys.getTime();
		while( ( fire || ( numshots < SENTRY_MIN_SHOTS ) ) && ( sys.getTime() < endtime ) ) {
			if ( sys.getTime() >= firetime ) {
				startSound( "snd_fire", SND_CHANNEL_WEAPON, false );
				attackMissile( "Barrel" );
				numshots++;
				firetime = sys.getTime() + SENTRY_FIRERATE;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
				playCycle( ANIMCHANNEL_TORSO, "range_attack_loop" );
			}
			waitFrame();
		}

		if ( !fire && ( numshots >= SENTRY_MIN_SHOTS ) ) {
			break;
		}

		setBlendFrames( ANIMCHANNEL_TORSO, 2 );
		playCycle( ANIMCHANNEL_TORSO, "range_attack_aim" );
		endtime = RandomDelay( SENTRY_WAIT_MIN_LENGTH, SENTRY_WAIT_MAX_LENGTH );
		while( ( fire || ( numshots < SENTRY_MIN_SHOTS ) ) && ( sys.getTime() < endtime ) ) {
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void char_sentry::Legs_Death() {
	while( AI_DEAD ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void char_sentry::Legs_Idle() {
	float delta;
	
	if ( !AI_FORWARD && !facingIdeal() ) {
		if ( getTurnDelta() > SENTRY_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
		}

		if ( getTurnDelta() < -SENTRY_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
		}
	}
	
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( !awake ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Fold", 4 );
		}
		if ( AI_FORWARD ) {
			delta = getTurnDelta();
			if ( ( delta <= SENTRY_WALKTURN ) && ( delta >= -SENTRY_WALKTURN ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
			}
		}
		if ( !facingIdeal() ) {
			if ( getTurnDelta() > SENTRY_MIN_TURN ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
			}
			if ( getTurnDelta() < -SENTRY_MIN_TURN ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
			}
		}
	}
}

void char_sentry::Legs_Walk() {
	float delta;
	
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD )	{
		delta = getTurnDelta();
		if ( ( delta > SENTRY_WALKTURN ) || ( delta < -SENTRY_WALKTURN ) ) {
			break;
		}

		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
}

void char_sentry::Legs_Fold() {
	startSound( "snd_shutdown", SND_CHANNEL_VOICE, false );
	playAnim( ANIMCHANNEL_LEGS, "fold" );	
	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		waitFrame();
	}
	flashlight_off();
	finishAction( "fold" );
	animState( ANIMCHANNEL_LEGS, "Legs_Folded", 0 );
}

void char_sentry::Legs_Folded() {
	playCycle( ANIMCHANNEL_LEGS, "folded" );	
	while( !awake ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Unfold", 4 );
}

void char_sentry::Legs_Unfold() {
	playAnim( ANIMCHANNEL_LEGS, "unfold" );	
	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "unfold" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void char_sentry::Legs_Hanging() {
	playCycle( ANIMCHANNEL_LEGS, "releaseidle" );	
	while( hanging ) {
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_LEGS, "load" );	
	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "unload" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void char_sentry::Legs_TurnLeft() {
	float turnAmount;
	float delta;
	
	turnAmount = getTurnDelta();
	if ( turnAmount > 110 ) {
		// do it in two turns
		turnAmount *= 0.5;
	}

	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		if ( AI_FORWARD ) {
			delta = getTurnDelta();
			if ( ( delta <= SENTRY_WALKTURN2 ) && ( delta >= -SENTRY_WALKTURN2 ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
			}
		}
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		if ( AI_FORWARD ) {
			delta = getTurnDelta();
			if ( ( delta <= SENTRY_WALKTURN2 ) && ( delta >= -SENTRY_WALKTURN2 ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 );
			}
		}
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void char_sentry::Legs_TurnRight() {
	float turnAmount;
	float delta;
	
	turnAmount = getTurnDelta();
	if ( turnAmount < -110 ) {
		// do it in two turns
		turnAmount *= 0.5;
	}

	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		if ( AI_FORWARD ) {
			delta = getTurnDelta();
			if ( ( delta <= SENTRY_WALKTURN2 ) && ( delta >= -SENTRY_WALKTURN2 ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
			}
		}
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		if ( AI_FORWARD ) {
			delta = getTurnDelta();
			if ( ( delta <= SENTRY_WALKTURN2 ) && ( delta >= -SENTRY_WALKTURN2 ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 );
			}
		}
		waitFrame();
	}

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
char_sentry::state_Begin
=====================
*/
void char_sentry::state_Begin() {
	fire = false;
	setBoneMod( true );

	light_on = false;
	if ( getIntKey( "flashlight" ) ) {
		spawn_flashlight();
	}

	hanging = getIntKey( "hanging" );
	awake = getIntKey( "unfolded" );

	waitFrame();
	if ( hanging ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Hanging", 0 );
	} else if ( !awake ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Folded", 0 );
	} else {
		animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	setState( "state_WaitForTrigger" );
}

/*
=====================
char_sentry::init
=====================
*/
void char_sentry::init() {
	lead_player = getIntKey( "lead_player" );
	can_talk = false;
	no_cower_saved = true;
	no_cower = true;
}

/*
=====================
char_sentry::destroy
=====================
*/
void char_sentry::destroy() {
	light.remove();
	if ( playerPositionThread ) {
		sys.terminate( playerPositionThread );
		playerPositionThread = 0;
	}
}

/*
=====================
char_sentry::spawn_flashlight
=====================
*/
void char_sentry::spawn_flashlight() {
	string texture;
	float distance;

	distance = getFloatKey( "flashlight_distance" );
	if ( !distance ) {
		distance = 640;
	}
	
	// use ik_pose to bind light
	playAnim( ANIMCHANNEL_TORSO, "ik_pose" );
	if ( getIntKey( "flashlight" ) == 2 ) {
		// spot light
		sys.setSpawnArg( "light_target", "1 0 0" );
		sys.setSpawnArg( "light_up", "0 0 .5" );
		sys.setSpawnArg( "light_right", "0 -.5 0" );	
		sys.setSpawnArg( "light_end", distance + " 0 0" );

		texture = getKey( "mtr_flashlight" );
		sys.setSpawnArg( "texture", texture );

		sys.setSpawnArg( "name", getName() + "_light" );	
		light = sys.spawn( "light" );
		light.setAngles( getAngles() );
		light.bindToJoint( self, "light", true );
		light.setOrigin( '0 0 0' );
	} else {
		// radial light
		sys.setSpawnArg( "name", getName() + "_light" );	
		light = sys.spawn( "light" );
		light.setRadius( 256 );	
		light.setAngles( getAngles() + '0 90 0' );
		light.bindToJoint( self, "light", true );
		texture = getKey( "mtr_flashlight" );
		light.setShader( texture );
		light.setOrigin( '0 0 0' );
	}
	stopAnim( ANIMCHANNEL_TORSO, 0 );

	flashlight_off();
}

/*
=====================
char_sentry::flashlight_off
=====================
*/
void char_sentry::flashlight_off() {
	string skin;

	if ( light ) {
		light.Off();
		skin = getKey( "skin_flashlight_off" );
		setSkin( skin );
		light_on = false;
	}
}
	
/*
=====================
char_sentry::flashlight_on
=====================
*/
void char_sentry::flashlight_on() {
	string skin;

	if ( light ) {
		light.On();
		skin = getKey( "skin_flashlight_on" );
		setSkin( skin );
		light_on = true;
	}
}
	
/*
=====================
char_sentry::ignore
=====================
*/
void char_sentry::ignore( entity ignore_ent ) {
	ignore_enemy = ignore_ent;
	ignore_enemy_time = sys.getTime() + 2;
}

/*
=====================
char_sentry::checkForEnemy
=====================
*/
boolean	char_sentry::checkForEnemy( float use_fov ) {
	entity enemy;
	entity ent;

	enemy = $null_entity;
	if ( lead_player && $player1.hasEnemies() ) {
		enemy = closestReachableEnemyOfEntity( $player1 );
		if ( ( ignore_enemy_time > sys.getTime() ) && ( ignore_enemy == enemy ) ) {
			enemy = $null_entity;
		}
		if ( !enemy ) {
			enemy = $player1.closestEnemyToPoint( getOrigin() );
			if ( ( ignore_enemy_time > sys.getTime() ) && ( ignore_enemy == enemy ) ) {
				enemy = $null_entity;
			}
		}
	}
	
	if ( !enemy ) {
		enemy = findEnemyAI( false );
		if ( ( ignore_enemy_time > sys.getTime() ) && ( ignore_enemy == enemy ) ) {
			enemy = $null_entity;
		}
	}

	if ( enemy ) {
		startSound( "snd_sight_enemy", SND_CHANNEL_VOICE, false );
		setEnemy( enemy );
        return true;
	} else {
		clearEnemy();
	}

	return false;
}

/*
=====================
char_sentry::checkDestinationDistance()
=====================
*/
float char_sentry::checkDestinationDistance() {
	float	playerDist;
	float	currentDist;
	float	leadDistance;
	float	relativeMoveDir;
	vector	delta;

	// determine if the player is moving toward us
	delta = getOrigin() - lastValidPlayerPosition;
	relativeMoveDir = delta * $player1.getLinearVelocity();
	if ( relativeMoveDir > 1 ) {
		// Player is approaching
		playerMoveState = APPROACHING;
	} else if ( relativeMoveDir < -1 ) {
		// Player is moving away from us
		playerMoveState = RETREATING;
	} else {
		// Player is standing still
		playerMoveState = NOT_MOVING;
	}

	if ( !current_path ) {
		return PLAYER_OK;
	}

	playerDist = distanceToPoint( lastValidPlayerPosition );
	if ( playerDist < SENTRY_LEAD_DIST ) {
		return PLAYER_OK;
	}

	if ( !canSee( $player1 ) ) {
		currentDist = travelDistanceToEntity( current_path );
		leadDistance = travelDistanceBetweenPoints( lastValidPlayerPosition, current_path.getOrigin() );
		if ( currentDist > leadDistance ) {
			return PLAYER_AHEAD_OF_ME;
		} else {
			return PLAYER_LOST;
		}
	}

	if ( playerDist > SENTRY_LOST_DIST ) {
		currentDist = travelDistanceToEntity( current_path );
		leadDistance = travelDistanceBetweenPoints( lastValidPlayerPosition, current_path.getOrigin() );
		if ( currentDist > leadDistance ) {
			return PLAYER_AHEAD_OF_ME;
		} else {
			return PLAYER_BEHIND_ME;
		}
	}

	return PLAYER_OK;
}

/*
=====================
char_sentry::updatePlayerPositionThread()
=====================
*/
void char_sentry::updatePlayerPositionThread() {
	vector pos;

	while( 1 ) {
		if ( canReachEntity( $player1 ) ) {
			lastValidPlayerPosition = getReachableEntityPosition( $player1 );
		}
		//sys.debugBounds( '1 0 0', lastValidPlayerPosition + $player1.getMins(), lastValidPlayerPosition + $player1.getMaxs(), 0 );
		waitFrame();
	}
}

/***********************************************************************

	Path commands

***********************************************************************/

/*
=====================
char_sentry::path_sentry_light_on
=====================
*/
void char_sentry::path_sentry_light_on() {
	flashlight_on();
}

/*
=====================
char_sentry::path_sentry_light_off
=====================
*/
void char_sentry::path_sentry_light_off() {
	flashlight_off();
}

/*
=====================
char_sentry::path_sentry_shutdown
=====================
*/
void char_sentry::path_sentry_shutdown() {
	vector ang;

	stopMove();

	ang = current_path.getAngles();
	turnTo( ang_y );
	waitUntil( facingIdeal() );

	awake = false;
	AI_ACTIVATED = false;

	if ( playerPositionThread ) {
		sys.terminate( playerPositionThread );
		playerPositionThread = 0;
	}

	waitAction( "fold" );
	while( !AI_ACTIVATED ) {
		waitFrame();
	}

	if ( getIntKey( "flashlight_on" ) ) {
		flashlight_on();
	}
	awake = true;
	waitAction( "unfold" );
}

/*
=====================
char_sentry::path_sentry_unlock_door
=====================
*/
void char_sentry::path_sentry_unlock_door() {
	vector ang;
	string triggername;
	entity triggerent;

	if ( current_path.getKey( "trigger" ) == "" ) {
		// already unlocked the door
		return;
	}

	ang = current_path.getAngles();
	turnTo( ang_y );
	waitUntil( facingIdeal() );

	startSound( "snd_open_door", SND_CHANNEL_VOICE, false );
	playCustomAnim( "unlock_door", 4, 4 );
	waitAction( "customAnim" );

	// trigger any entities the path had targeted
	triggername = current_path.getKey( "trigger" );
	if ( triggername != "" ) {
		triggerent = sys.getEntity( triggername );
		if ( triggerent ) {
			triggerent.activate( self );
		}
	}

	current_path.setKey( "trigger", "" );
}

/*
=====================
char_sentry::path_corner
=====================
*/
void char_sentry::path_corner() {
	if ( !lead_player ) {
		setState( "state_FollowPath" );
	}

	setNeverDormant( true );
	if ( !canSee( $player1 ) ) {
		setState( "state_FindPlayer" );
	}

	if ( checkDestinationDistance() == PLAYER_BEHIND_ME ) {
		setState( "state_Wait" );
	} else {
		setState( "state_Lead" );
	}
}

/*
=====================
char_sentry::path_sentry_lead_player
=====================
*/
void char_sentry::path_sentry_lead_player() {
	lead_player = true;
	if ( !playerPositionThread ) {
		playerPositionThread = thread updatePlayerPositionThread();
	}
}

/*
=====================
char_sentry::path_sentry_ignore_player
=====================
*/
void char_sentry::path_sentry_ignore_player() {
	lead_player = false;
	if ( playerPositionThread ) {
		sys.terminate( playerPositionThread );
		playerPositionThread = 0;
	}
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
char_sentry::state_Killed
=====================
*/
void char_sentry::state_Killed() {
	stopMove();

	if ( playerPositionThread ) {
		sys.terminate( playerPositionThread );
		playerPositionThread = 0;
	}

	flashlight_off();

	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );

	waitAction( "dead" );

	float burnDelay = getFloatKey( "burnaway" );
	if ( burnDelay != 0 ) {
		preBurn();
		sys.wait( burnDelay );
		burn();
		startSound( "snd_burn", SND_CHANNEL_BODY, false );
		sys.wait( 3 );
		remove();
	}

	stopThinking();
}

/*
=====================
char_sentry::state_WaitForTrigger
=====================
*/
void char_sentry::state_WaitForTrigger() {
	if ( hanging != 2 ) {
		AI_ACTIVATED = false;
		while( !AI_ACTIVATED ) {
			waitFrame();
		}
	}

	if ( getIntKey( "flashlight_on" ) ) {
		flashlight_on();
	}
	
	if ( hanging ) {
		hanging = false;
		awake = true;
		waitAction( "unload" );
	} else if ( !awake ) {
		awake = true;
		waitAction( "unfold" );
	}

	// hanging guys turn off damage untill they're out.  make sure we get damage turned back on.
	allowDamage();	
	lookAt( $player1, 3 );

	current_path = randomPath();
	//next_path = current_path.randomPath();
	lookAt( $player1, 3 );

	setState( "state_Idle" );
}

/*
=====================
char_sentry::state_Idle
=====================
*/
void char_sentry::state_Idle() {
	stopMove();

	if ( lead_player && !playerPositionThread ) {
		playerPositionThread = thread updatePlayerPositionThread();
	}

	if ( current_path ) {
		executePathCommand( current_path );
	}

	while( 1 ) {
		if ( lead_player ) {
			if ( !canSee( $player1 ) ) {
				setState( "state_FindPlayer" );
			}
		}

		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}
		if ( AI_PUSHED ) {
			getOutOfWay();
		}
		if ( current_path ) {
			executePathCommand( current_path );
		}
		waitFrame();
	}
}

/*
=====================
char_sentry::state_FollowPath
=====================
*/
void char_sentry::state_FollowPath() {
	if ( !current_path ) {
		setState( "state_Idle" );
	}

	moveToEntity( current_path );

	while( 1 ) {
		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}

		checkBlocked();

		if ( AI_MOVE_DONE ) {
			if ( AI_DEST_UNREACHABLE ) {
				waitFrame();
				setState( "state_FindPlayer" );
			}
			setNeverDormant( getFloatKey( "neverdormant" ) );
			finishPathCommand();
			setState( "state_Idle" );
		}
		
		waitFrame();
	}
}

/*
=====================
char_sentry::state_Wait
=====================
*/
void char_sentry::state_Wait() {
	float getCloserTime;

	float result = checkDestinationDistance();
	if ( result == PLAYER_LOST ) {
		setState( "state_FindPlayer" );
	} else if ( result == PLAYER_AHEAD_OF_ME ) {
		setState( "state_Lead" );
	} else if ( ( result == PLAYER_OK ) && ( playerMoveState == APPROACHING ) ) {
		setState( "state_Lead" );
	}

	stopMove();
	startSound( "snd_waiting_for_player", SND_CHANNEL_VOICE, false );

	getCloserTime = sys.getTime() + SENTRY_WAIT_GETCLOSER;
	while( 1 ) {
		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}

		lookAt( $player1, 0.1 );

		if ( AI_PUSHED ) {
			getOutOfWay();
		}

		result = checkDestinationDistance();
		if ( result == PLAYER_LOST ) {
			setState( "state_FindPlayer" );
		} else if ( result == PLAYER_AHEAD_OF_ME ) {
			setState( "state_Lead" );
		} else if ( ( result == PLAYER_OK ) && ( playerMoveState == APPROACHING ) ) {
			setState( "state_Lead" );
		} else  if ( ( sys.getTime() > getCloserTime ) && ( result == PLAYER_BEHIND_ME ) ) {
			setState( "state_GetCloser" );
		}
		waitFrame();
	}
}

/*
=====================
char_sentry::state_GetCloser
=====================
*/
void char_sentry::state_GetCloser() {
	while( 1 ) {
		moveToPosition( lastValidPlayerPosition );
		if ( AI_MOVE_DONE ) {
			if ( !canReachEntity( $player1 ) ) {
				setState( "state_CantReachPlayer" );
			}
		}

		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}

		checkBlocked();

		float result = checkDestinationDistance();
		
		if ( result == PLAYER_LOST ) {
			setState( "state_FindPlayer" );
		}
        if ( result == PLAYER_OK ) {
			setState( "state_Wait" );
		}
		waitFrame();
	}
}

/*
=====================
char_sentry::state_CantReachPlayer
=====================
*/
void char_sentry::state_CantReachPlayer() {
	startSound( "snd_cant_reach_player", SND_CHANNEL_VOICE, false );
	stopMove();
	while( 1 ) {
		if ( canReachEntity( $player1 ) ) {
			setState( "state_Wait" );
		}
		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}
		waitFrame();
	}
}

/*
=====================
char_sentry::state_Lead
=====================
*/
void char_sentry::state_Lead() {
	float	nextLookTime;
	float	leadTimeOut;

	if ( !current_path ) {
		setState( "state_Idle" );
	}

	nextLookTime = RandomDelay( SENTRY_MIN_LOOK_DELAY, SENTRY_MAX_LOOK_DELAY );
	moveToEntity( current_path );

	leadTimeOut = sys.getTime() + SENTRY_LEAD_TIMEOUT;

	while( 1 ) {
		if ( checkForEnemy( true ) ) {
			setState( "state_Combat" );
		}

		if ( !light_on && ( sys.getTime() > nextLookTime ) ) {
			lookAt( $player1, SENTRY_LOOK_TIME );
			nextLookTime = RandomDelay( SENTRY_MIN_LOOK_DELAY, SENTRY_MAX_LOOK_DELAY );
		}

		checkBlocked();
		
		float result = checkDestinationDistance();
		if ( ( result != PLAYER_BEHIND_ME ) && ( result != PLAYER_LOST ) ) {
			leadTimeOut = sys.getTime() + SENTRY_LEAD_TIMEOUT;
		} else if ( sys.getTime() > leadTimeOut ) {
			setState( "state_Wait" );
		} else if ( !light_on ) {
			// look back at player to see what he's up to
			lookAt( $player1, 0.1 );
			nextLookTime += 0.1;
		}

		if ( AI_MOVE_DONE ) {
			if ( AI_DEST_UNREACHABLE ) {
				waitFrame();
				setState( "state_FindPlayer" );
			}
			setNeverDormant( getFloatKey( "neverdormant" ) );
			finishPathCommand();
			setState( "state_Idle" );
		}
		
		waitFrame();
	}
}

/*
=====================
char_sentry::state_FindPlayer
=====================
*/
void char_sentry::state_FindPlayer() {
	while( 1 ) {
		moveToPosition( lastValidPlayerPosition );
		if ( AI_MOVE_DONE || AI_DEST_UNREACHABLE ) {
			if ( !canReachEntity( $player1 ) ) {
				setState( "state_CantReachPlayer" );
			}
		}

		if ( checkForEnemy( true ) ) {
			waitFrame();
			setState( "state_Combat" );
		}

		checkBlocked();
		
		float result = checkDestinationDistance();
		if ( canSee( $player1 ) && ( ( result == PLAYER_BEHIND_ME ) || ( result == PLAYER_OK ) ) ) {
			setState( "state_Wait" );
		} else if ( result == PLAYER_AHEAD_OF_ME ) {
			setState( "state_Lead" );
		}
		waitFrame();
	}
}

/*
=====================
char_sentry::state_Combat
=====================
*/
void char_sentry::state_Combat() {
	float attack_flags;

	eachFrame {
		faceEnemy();
		lookAtEnemy( 1 );
		
		if ( AI_ENEMY_DEAD || !getEnemy() ) {
			startSound( "snd_target_lost", SND_CHANNEL_VOICE, false );
			AI_ENEMY_DEAD = false;
			clearEnemy();
			setState( "state_Idle" );
		}
		
		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			continue;
		}
		
		if ( canReachEnemy() ) {
			combat_chase();
		} else if ( !find_attack_position() ) {
			ignore( getEnemy() );
			checkForEnemy( false );
		}
		
		waitFrame();
	}
}

/*
=====================
char_sentry::combat_chase
=====================
*/
void char_sentry::combat_chase() {
	float attack_flags;
	
	moveToEnemy();
	while( !AI_DEST_UNREACHABLE ) {
		if ( AI_ENEMY_DEAD ) {
			startSound( "snd_target_lost", SND_CHANNEL_VOICE, false );
			AI_ENEMY_DEAD = false;
			clearEnemy();
			setState( "state_Idle" );
		}

		if ( AI_MOVE_DONE ) {
			if ( !enemyPositionValid() ) {
				clearEnemy();
				setState( "state_Idle" );
			}
			moveToEnemy();
		}
		
		lookAtEnemy( 1 );

		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			return;
		}
		
		waitFrame();
	}
	stopMove();
}

/*
=====================
char_sentry::find_attack_position
=====================
*/
boolean char_sentry::find_attack_position() {
	float attack_flags;

	if ( sys.getTime() < nextPositionSearch ) {
		return false;
	}
	nextPositionSearch = sys.getTime() + 1;
	locateEnemy();
	moveToAttackPosition( getEnemy(), "range_attack_loop" );
	if ( AI_DEST_UNREACHABLE ) {
		return false;
	}

	while( !AI_MOVE_DONE ) {
		if ( AI_ENEMY_DEAD ) {
			startSound( "snd_target_lost", SND_CHANNEL_VOICE, false );
			AI_ENEMY_DEAD = false;
			clearEnemy();
			setState( "state_Idle" );
		}

		lookAtEnemy( 1 );

		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			return true;
		}
		
		waitFrame();
	}
	stopMove();

	return true;
}


/*
=====================
char_sentry::do_attack
=====================
*/
void char_sentry::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
char_sentry::check_attacks
=====================
*/
float char_sentry::check_attacks() {
	float attack_flags = 0;
	
	if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
		attack_flags |= ATTACK_MISSILE;
	}
	
	return attack_flags;
}

/*
=====================
char_sentry::combat_range
=====================
*/
void char_sentry::combat_range() {
	faceEnemy();
	fire = true;
	while( canHitEnemyFromAnim( "range_attack_loop" ) ) {
		waitFrame();
	}
	fire = false;
	waitUntil( !inAnimState( ANIMCHANNEL_TORSO, "Torso_RangeAttack" ) );
}

//@doomscript-blueprint begin 6
//@source ADB1A727
//@catalog 0C260740
//@node E6BBD505-0 40 40
//@node 8E533232-0 330 40
//@node C8CCB998-0 610 40
//@node 7DEBE78B-0 40 40
//@node 35F41620-0 330 40
//@node AC04CDB4-0 610 40
//@node C737DFA8-0 890 200
//@node C457EEF1-0 685 305
//@node D34463A5-0 1170 360
//@node 35F41620-1 1450 360
//@node 45D7930B-0 1730 200
//@node B7D2DDD3-0 1525 305
//@node D3DF2988-0 2010 360
//@node C929990D-0 40 40
//@node 78816232-0 330 40
//@node EE380655-0 105 145
//@node D0DAA072-0 610 40
//@node 90F0F56C-0 890 40
//@node CD36D0D3-0 685 232
//@node 10C7BC6A-0 1170 40
//@node D9316FC1-0 730 145
//@node C02B1711-0 960 145
//@node 05DB36EB-0 1450 200
//@node 0E8E2F9B-0 1730 40
//@node F4342D70-0 2010 40
//@node EBD11FC0-0 2290 40
//@node 447153A6-0 40 40
//@node 0362D78B-0 330 40
//@node 465B256D-0 610 40
//@node 85151B1B-0 890 40
//@node 145919D0-0 450 145
//@node 88914340-0 680 145
//@node 6800DC53-0 1170 200
//@node B533F660-0 965 305
//@node CB51F458-0 1450 360
//@node ACC95D66-0 1730 200
//@node DC55175C-0 2010 40
//@node D56BFDB3-0 1805 145
//@node 393D46E4-0 2290 40
//@node 6217FCB1-0 2085 145
//@node B811CA1D-0 1880 145
//@node 92282710-0 1880 229
//@node 4F351ADC-0 2570 200
//@node D5B7A57D-0 2345 305
//@node AB388621-0 2850 200
//@node 322A5115-0 3130 200
//@node 9D838A93-0 3410 200
//@node D557C7A8-0 3185 305
//@node 6CDF6B55-0 3690 200
//@node CD84D601-0 3485 305
//@node 29D1254F-0 3280 305
//@node 76CB74A4-0 3280 389
//@node A0314275-0 3280 473
//@node B3F74563-0 3970 360
//@node AB3EDEF0-0 3765 465
//@node 48C0D6A9-0 3560 465
//@node E1AF94AE-0 4250 520
//@node A7C577DC-0 4530 520
//@node 1D5F1DAF-0 4810 520
//@node E3699342-0 4605 625
//@node 6D8C1B95-0 4400 625
//@node 31423646-0 5090 520
//@node EB197114-0 4885 625
//@node 6800DC53-1 5370 360
//@node 6DA9C7CB-0 5165 465
//@node CB51F458-1 5650 520
//@node 322A5115-1 5930 520
//@node ACC95D66-1 6210 360
//@node D0A3BF28-0 6490 200
//@node ADF29531-0 6285 305
//@node 9A279A67-0 6080 305
//@node 70437662-0 6080 389
//@node C4FECEE9-0 6770 360
//@node AB388621-1 7050 200
//@node D64CB158-0 7330 200
//@node B365B57C-0 7610 200
//@node EECF041D-0 7385 305
//@node 6CDF6B55-1 7890 200
//@node 7EDE4048-0 7685 305
//@node B10DBD4C-0 7480 305
//@node CA7E6D51-0 7480 389
//@node 19205E1C-0 7480 473
//@node 6800DC53-2 8170 360
//@node 7F723D56-0 7965 465
//@node CB51F458-2 8450 520
//@node ACC95D66-2 8730 360
//@node 4485E43B-0 9010 40
//@node D9FDA727-0 9290 40
//@node EFAA1995-0 8850 145
//@node E5334945-0 9080 145
//@node 6800DC53-3 9570 200
//@node 6024B0A9-0 9365 305
//@node CB51F458-3 9850 360
//@node ACC95D66-3 10130 200
//@node 0B880D41-0 10410 40
//@node 4C927418-0 10690 40
//@node A77DAF45-0 40 40
//@node 0F729806-0 330 40
//@node 5CE55BE6-0 125 145
//@node 243DB0CF-0 610 200
//@node 2291E28F-0 890 40
//@node 0C0B29CB-0 40 40
//@node E55B8135-0 330 40
//@node 702C2F5C-0 -110 145
//@node 9977B9CC-0 120 145
//@node 199ED2BB-0 610 200
//@node 35CF2036-0 405 305
//@node 74C6DD99-0 890 360
//@node 96D62798-0 1170 200
//@node 6750DEB0-0 965 305
//@node 4EC8CB38-0 1450 360
//@node D70DB0BC-0 1730 40
//@node 18F5FCFA-0 2010 40
//@node 672ECC51-0 2290 200
//@node DF39FA3C-0 2085 305
//@node C85721F2-0 1880 305
//@node 6F5D5592-0 2570 360
//@node 81C18BF3-0 2850 200
//@node 4A3A03E7-0 2645 305
//@node C1274052-0 3130 360
//@node 955DC8EC-0 2905 465
//@node 92EAA792-0 3410 360
//@node D780030B-0 3205 465
//@node 360448FB-0 3000 465
//@node 231888F1-0 3690 520
//@node 06A57AEA-0 3970 200
//@node CBC73EA0-0 3530 305
//@node 8ADCC8D0-0 3760 305
//@node 199ED2BB-1 4250 360
//@node 8605F937-0 4045 465
//@node 74C6DD99-1 4530 520
//@node 96D62798-1 4810 360
//@node E04361BB-0 4605 465
//@node 4EC8CB38-1 5090 520
//@node 6EDADDE8-0 40 40
//@node A5165FBB-0 330 40
//@node 4135F296-0 610 40
//@node 516EB03E-0 405 145
//@node 6015DEE5-0 890 200
//@node 601394D4-0 665 305
//@node 966B58C5-0 1170 200
//@node D705BC9C-0 965 305
//@node 14FDE866-0 760 305
//@node 30DAC817-0 1450 360
//@node DD3B8478-0 1730 200
//@node BB6F54AD-0 2010 40
//@node 38849DC2-0 40 40
//@node 187423D4-0 330 40
//@node C4AC848E-0 610 40
//@node 1CF750A1-0 890 40
//@node A5A674B3-0 450 145
//@node A7A47CE3-0 680 145
//@node 3C0FFB46-0 1170 200
//@node 6C835B7C-0 1450 40
//@node 242474EC-0 1730 40
//@node F8D36C7A-0 2010 40
//@node 02D3A213-0 40 40
//@node 70D1BF75-0 330 40
//@node 482B7D47-0 610 40
//@node CB0D1D60-0 405 145
//@node 72422D02-0 200 145
//@node 48CF03CD-0 890 200
//@node 8F137887-0 1170 40
//@node 72D153D1-0 40 40
//@node 474CC8FE-0 330 40
//@node 0DCE562E-0 610 40
//@node DEB117E2-0 170 145
//@node 26597A12-0 400 145
//@node 7F4E8F93-0 890 200
//@node 6B2A68E8-0 1170 40
//@node D4B42557-0 1450 40
//@node 2E2915CF-0 40 40
//@node 732DF8C2-0 330 40
//@node 84200DB1-0 610 40
//@node 468AA1F6-0 405 145
//@node C46A756D-0 890 200
//@node DC8DE218-0 1170 40
//@node 14B759F0-0 1450 40
//@node 08514D9E-0 1010 145
//@node 6A57898E-0 1240 145
//@node C46A756D-1 1730 200
//@node 88CA12F1-0 2010 40
//@node 878CAC9D-0 2290 40
//@node F93B4E0F-0 40 40
//@node 9D35950F-0 330 40
//@node 6D3FE22B-0 105 145
//@node 285801F8-0 610 40
//@node AE86A7C9-0 405 145
//@node 0B66E3C4-0 200 145
//@node CC79264C-0 890 200
//@node C4C281D2-0 685 305
//@node 6CA468A7-0 480 305
//@node 6C46B8DD-0 1170 40
//@node 28D5FA68-0 1450 40
//@node E7C7309C-0 1010 145
//@node 3A789B8C-0 1240 145
//@node E61444B3-0 1730 200
//@node 70960B1A-0 1525 305
//@node DFAD6F26-0 2010 360
//@node B7999155-0 1785 465
//@node 21DBECB8-0 2290 360
//@node ABC1658E-0 2085 465
//@node 36B9FE14-0 1880 465
//@node 885F68D1-0 2570 520
//@node 81459A05-0 2850 200
//@node 2DEBE0AE-0 3130 40
//@node E04384E0-0 3410 40
//@node B10F5B3D-0 2970 145
//@node 4E8B360D-0 3200 145
//@node E61444B3-1 3690 200
//@node 2B760563-0 3485 305
//@node DFAD6F26-1 3970 360
//@node 9949A2F8-0 3745 465
//@node 21DBECB8-1 4250 360
//@node DEB039ED-0 4045 465
//@node 316F9373-0 3840 465
//@node 227F2128-0 4530 520
//@node 81459A05-1 4810 200
//@node 9F70EA65-0 5090 40
//@node E52CBC80-0 40 40
//@node 601324B4-0 330 40
//@node 986FAB37-0 105 145
//@node 2B0A0A30-0 610 40
//@node 26E205E4-0 405 145
//@node 10448FC6-0 200 145
//@node CBE1F747-0 890 200
//@node 8A94FB6B-0 685 305
//@node 0EE36EBC-0 480 305
//@node 03632E85-0 1170 40
//@node 82B23C73-0 1450 40
//@node A6D062F1-0 1010 145
//@node BF8A1FC1-0 1240 145
//@node 6E60BAF0-0 1730 200
//@node 8866B434-0 1525 305
//@node E24A6017-0 2010 360
//@node 12517F9F-0 1785 465
//@node C1DED281-0 2290 360
//@node E9954700-0 2085 465
//@node 72383D04-0 1880 465
//@node 8C374CD6-0 2570 520
//@node 6C00E7DC-0 2850 200
//@node 18089D38-0 3130 40
//@node 755FAB5B-0 3410 40
//@node B3947486-0 2970 145
//@node 490702D6-0 3200 145
//@node 6E60BAF0-1 3690 200
//@node F378AA45-0 3485 305
//@node E24A6017-1 3970 360
//@node 5EAD4502-0 3745 465
//@node C1DED281-1 4250 360
//@node 209E482F-0 4045 465
//@node 24A42B63-0 3840 465
//@node 019EBEE1-0 4530 520
//@node 6C00E7DC-1 4810 200
//@node 8617DF08-0 5090 40
//@node 1A6AFAE8-0 40 40
//@node D83F36BC-0 330 40
//@node 0D349C8A-0 125 145
//@node 38804544-0 610 40
//@node 35C425DC-0 890 40
//@node 06607C4E-0 685 145
//@node FD471E0F-0 1170 40
//@node 06C055CF-0 945 145
//@node 360F4D60-0 1450 200
//@node 2F822D4A-0 1730 40
//@node 9482FB2F-0 1505 145
//@node 96398614-0 1300 245
//@node 3789613F-0 1095 245
//@node 2CD9607E-0 2010 40
//@node 3F6616F6-0 1785 145
//@node 9037B990-0 2290 40
//@node 7FD72A72-0 2570 40
//@node 258B2112-0 2365 145
//@node B086CEA6-0 2850 200
//@node EC081C3B-0 3130 200
//@node 43C8AB3E-0 2925 305
//@node 0D70A268-0 2720 305
//@node A22115E8-0 3410 200
//@node A20D596C-0 3970 200
//@node EC1DC6AA-0 4250 40
//@node B552254B-0 4530 40
//@node E36F12FF-0 40 40
//@node 305D7B43-0 330 40
//@node 6FEA0325-0 105 145
//@node 373EEC02-0 -100 245
//@node 06C810C3-0 -305 245
//@node 5317568E-0 610 40
//@node 44212EFA-0 405 145
//@node 0B70FD62-0 890 40
//@node F83D8012-0 685 145
//@node 66A4DF36-0 1170 40
//@node D8927685-0 965 145
//@node F08CE529-0 40 40
//@node 94C62651-0 330 40
//@node F78E727B-0 610 40
//@node 8B035F95-0 405 145
//@node 6A1A1B8F-0 890 200
//@node DD0FBE7D-0 685 300
//@node 5093D95E-0 1170 200
//@node D29BB985-0 965 305
//@node A1A7607F-0 40 40
//@node 2BDB4BA5-0 330 40
//@node F23598F8-0 105 145
//@node 8EEF0D37-0 610 40
//@node 280429DE-0 405 145
//@node BB777FAA-0 200 145
//@node 099F13FF-0 890 200
//@node 0B582F67-0 685 305
//@node 3DAC1068-0 1170 40
//@node 225FB4A0-0 1450 40
//@node 8556DBEB-0 1245 145
//@node 74881EA0-0 1730 200
//@node 3E2C725C-0 2010 200
//@node D54D3EC8-0 2290 200
//@node DE866245-0 2570 200
//@node 35610F79-0 2365 392
//@node 7EA01615-0 2160 392
//@node E53953F1-0 2850 200
//@node 506B07DB-0 2625 305
//@node A20E37F9-0 3130 200
//@node 3F736474-0 2925 300
//@node 50ED4FBF-0 2720 300
//@node A2C7205C-0 2925 392
//@node DDB88174-0 3410 200
//@node F8F8B37F-0 3690 200
//@node 270AB69E-0 3465 305
//@node C470A658-0 3260 405
//@node C03E510D-0 3055 405
//@node 5BF7DED6-0 3970 200
//@node CB27829F-0 4250 200
//@node 01726E8E-0 4045 392
//@node B1228D77-0 3840 392
//@node 8DA0AE9D-0 4530 200
//@node DDB88174-1 5090 200
//@node F8F8B37F-1 5370 200
//@node 76E0FF51-0 5145 305
//@node C3E05300-0 4940 405
//@node ACBB2A1D-0 4735 405
//@node 47E4520E-0 5650 200
//@node E3185014-0 5930 200
//@node CB27829F-1 6210 200
//@node 3465B36D-0 6005 392
//@node CDB8D69C-0 5800 392
//@node E53953F1-1 6490 200
//@node 56C442A2-0 6265 305
//@node 94F9FF57-0 6770 200
//@node 6A6EE720-0 6565 300
//@node 8DA0AE9D-1 7050 200
//@node A502011E-0 7330 40
//@node 390A1EED-0 7610 40
//@node 18691FDD-0 40 40
//@node 687CFA59-0 330 40
//@node 7AF367C8-0 125 145
//@node 896A6924-0 610 200
//@node CEC964AD-0 890 200
//@node 319BBE9D-0 665 305
//@node AAEAE609-0 1170 200
//@node 12140332-0 965 300
//@node AA29246F-0 1450 200
//@node F2866BA9-0 1245 305
//@node E7C90B41-0 40 40
//@node BA705A75-0 330 40
//@node B8613F89-0 125 145
//@node F9FDDF2E-0 610 200
//@node FE0B815B-0 890 200
//@node 56E59D77-0 665 305
//@node F176E235-0 1170 200
//@node 304A20D1-0 965 300
//@node FB0359D2-0 1450 200
//@node 6F1CD790-0 1245 305
//@node A413B52F-0 40 40
//@node AC878B4B-0 330 40
//@node 2EDA584B-0 610 40
//@node 6EFED8C3-0 405 145
//@node 99AB045A-0 40 40
//@node EDEBBB42-0 330 40
//@node A24AF961-0 125 145
//@node 6314ED45-0 610 40
//@node FD8F6C0A-0 385 145
//@node A00E7578-0 890 200
//@node 80DD1F23-0 665 305
//@node 2DA3B221-0 1170 200
//@node 726296D7-0 965 305
//@node 13771F93-0 760 305
//@node DB64D480-0 760 389
//@node 931894CC-0 760 473
//@node EDEBBB42-1 1450 360
//@node 59D0D008-0 1245 465
//@node DE88F58B-0 1730 200
//@node 3A9B4AAC-0 1525 305
//@node 25ED4A28-0 1320 305
//@node D864795F-0 2010 360
//@node D20D6149-0 1785 465
//@node 2DA3B221-1 2290 360
//@node 77DAA056-0 2085 465
//@node 5DA61A78-0 1880 465
//@node 3F9B8FA1-0 1880 549
//@node 03F63D1B-0 1880 633
//@node EDEBBB42-2 2570 520
//@node 69120C67-0 2365 625
//@node DE88F58B-1 2850 40
//@node 732C3D51-0 2645 145
//@node DBBE4F43-0 2440 145
//@node 7B12BBBE-0 3130 200
//@node 33D38EB6-0 2905 305
//@node 2DA3B221-2 3410 200
//@node C75ECB6D-0 3205 305
//@node 6ED523ED-0 3000 305
//@node 67CCE732-0 3000 389
//@node 6F9C6986-0 3000 473
//@node EDEBBB42-3 3690 360
//@node 0E5FED7E-0 3485 465
//@node 6369F228-0 3970 40
//@node F2BF8644-0 3765 145
//@node 21673D4E-0 4250 200
//@node DF8B5A34-0 4530 200
//@node 3730B943-0 4325 300
//@node 9F6635A9-0 4810 200
//@node 291AD3AD-0 5370 200
//@node AB3A2788-0 5650 40
//@node 472CF0B6-0 40 40
//@node E8804C4F-0 330 40
//@node 948FC153-0 125 145
//@node 0DC4AB1C-0 -80 145
//@node 381A531E-0 610 40
//@node 136557ED-0 385 145
//@node 298D86F1-0 890 40
//@node 124D9AC4-0 685 145
//@node AF54C27C-0 480 145
//@node 4C0A9878-0 1170 200
//@node 24A01533-0 965 305
//@node 1D140A99-0 1450 200
//@node 1034DE0C-0 1245 305
//@node 67435FFB-0 1040 305
//@node 7EDD932D-0 1730 200
//@node 09229916-0 1525 305
//@node 4F32909A-0 2290 200
//@node AFF1BB79-0 2085 305
//@node ADC845A2-0 2570 40
//@node 75CCB56B-0 2365 145
//@node 931C516D-0 2160 145
//@node 3D06379D-0 2850 200
//@node 6CF3EDE5-0 3130 40
//@node F23606E7-0 2905 145
//@node 9DB6BD7F-0 2700 245
//@node 83BD3308-0 3410 40
//@node 766CC5EA-0 3205 145
//@node 58A5B918-0 3000 145
//@node 3D06379D-1 3690 200
//@node E0B343B1-0 3970 40
//@node AA9AEC6B-0 3530 145
//@node 8895B03B-0 3760 145
//@node 3BBFA3DF-0 4250 200
//@node 4E56A154-0 4025 305
//@node A4B1D25C-0 3820 405
//@node F9726619-0 4530 200
//@node C3517B34-0 4305 305
//@node E1CE5C46-0 4100 405
//@node BF91C5C2-0 4100 497
//@node FDEBD9B6-0 3895 497
//@node 79F54182-0 4810 200
//@node 92D5CAB1-0 4605 305
//@node 9752536F-0 4400 305
//@node 26AC0207-0 4400 389
//@node AE030EE9-0 5090 360
//@node DF1FFFB1-0 5650 360
//@node 90C47982-0 5930 40
//@node A14394ED-0 5725 145
//@node EAD359DB-0 5520 145
//@node 3BBFA3DF-1 6210 200
//@node 8C01A0E5-0 5985 305
//@node C4630DAE-0 5780 405
//@node F9726619-1 6490 200
//@node 7D5BDB1F-0 6265 305
//@node 9E67BF31-0 6060 405
//@node 5EF78483-0 6060 497
//@node 6AC9782B-0 5855 497
//@node 79F54182-1 6770 200
//@node B5D70BF4-0 6565 305
//@node 4081DAF8-0 6360 305
//@node DE584236-0 6360 389
//@node AE030EE9-1 7050 360
//@node D8D96B82-0 7610 360
//@node 3D06379D-2 7890 40
//@node 86D5CD3E-0 40 40
//@node 1B56C401-0 330 40
//@node 4D6C2A29-0 125 145
//@node BF43CCEF-0 610 200
//@node DE777C42-0 385 305
//@node F6523453-0 890 360
//@node BDCDC417-0 665 465
//@node C31E189A-0 1170 200
//@node D67EDA09-0 40 40
//@node B67F2A1B-0 330 40
//@node 08C54B45-0 40 40
//@node 94A16413-0 330 40
//@node CFFA7ADB-0 40 40
//@node 885C58B2-0 330 40
//@node ACB8D7CA-0 610 40
//@node 3270C51C-0 385 145
//@node 0ED85ED9-0 890 40
//@node 2E7C996E-0 1170 40
//@node 0D8627F4-0 1450 40
//@node C7A21FB9-0 1245 145
//@node 2013611F-0 1730 40
//@node 77FF30BE-0 1525 145
//@node 4D45502D-0 2010 40
//@node 53E9AED5-0 1805 145
//@node F464A4A1-0 2290 200
//@node 3F83B0BA-0 2085 300
//@node 3BFC6882-0 2570 200
//@node 22B4898F-0 2365 305
//@node DBBFDAF3-0 2850 40
//@node CE0947E4-0 3130 40
//@node 598F4C92-0 2925 145
//@node AF9AC464-0 2720 145
//@node B4A824E9-0 3410 200
//@node BC949226-0 3690 40
//@node 8901A5C2-0 3465 145
//@node D4C9615D-0 3970 200
//@node 8080F8FD-0 4250 40
//@node 2FE14327-0 4045 145
//@node FF264360-0 4530 40
//@node 808E5202-0 40 40
//@node 5E950801-0 330 40
//@node 5F02F0C7-0 125 145
//@node 827A2820-0 -80 145
//@node 8D868B11-0 610 200
//@node 15812835-0 890 40
//@node 1560BE19-0 665 145
//@node 35F2B47A-0 1170 40
//@node 46F646D7-0 1450 40
//@node 5569EF55-0 1730 40
//@node A9D59545-0 2010 40
//@node 68B7E4A7-0 2290 40
//@node 3F690AB9-0 2085 140
//@node BEA67BF4-0 1880 140
//@node 164E91A9-0 2570 40
//@node D032F3CD-0 2345 145
//@node 254886ED-0 2850 40
//@node 34E6B504-0 2645 145
//@node 1AC5FF85-0 2440 145
//@node BA73F98A-0 3130 200
//@node C31FE140-0 2905 305
//@node 70DCF4DE-0 2700 405
//@node A6DBE483-0 3410 200
//@node 173579BA-0 3205 305
//@node D1B08EDE-0 3690 360
//@node 0922E032-0 3970 40
//@node 057034F6-0 40 40
//@node 45352401-0 330 40
//@node 4C6BECA0-0 125 145
//@node 77FB2FF8-0 -80 145
//@node D14D9FF7-0 610 200
//@node 15AFC15D-0 890 40
//@node 67173405-0 1170 40
//@node FCE645B6-0 730 145
//@node 49703E46-0 960 145
//@node 8941572F-0 1450 200
//@node B1895E5D-0 1730 40
//@node 68A54579-0 1525 145
//@node 286E8D04-0 2010 200
//@node 10655617-0 2570 200
//@node B751F4D5-0 40 40
//@node DAF8F840-0 330 40
//@node 343A69B2-0 125 145
//@node 995C5580-0 610 40
//@node C86B444B-0 405 145
//@node 1FB90ECD-0 200 145
//@node A34B22F6-0 890 200
//@node 1F494644-0 665 305
//@node BF86D959-0 40 40
//@node B274EB9B-0 330 40
//@node 2B37C52D-0 125 145
//@node 9DEC7B7B-0 610 40
//@node 17C6DDA6-0 405 145
//@node 7A07A0C7-0 890 200
//@node 4B27C52D-0 685 300
//@node A8FA3D9A-0 1170 200
//@node 9F880220-0 965 305
//@node CC76A0E6-0 40 40
//@node 99E39AA7-0 330 40
//@node D54CA348-0 610 40
//@node 29FD1172-0 405 145
//@node 6D8CA42E-0 890 200
//@node 41D01697-0 685 300
//@node 9CB5E0D3-0 1170 200
//@node 59812797-0 965 305
//@node C4978174-0 1450 40
//@node AF728834-0 1730 40
//@node 239E967A-0 2010 40
//@node C2C1ECFF-0 2290 40
//@node E8AA9738-0 2570 40
//@node 25F32BD7-0 2365 145
//@node 9587E6EA-0 2160 145
//@node 506DE320-0 3130 200
//@node 596E2BE4-0 3410 200
//@node 7DB8A9C6-0 2925 300
//@node E806D9EF-0 3690 200
//@node B0126515-0 3970 200
//@node 8D6876C3-0 4250 200
//@node EB274DAC-0 4530 200
//@node 31359E64-0 4810 40
//@node 8B745063-0 40 40
//@node 292925DF-0 330 40
//@node F19F20E5-0 125 145
//@node 53987D6A-0 -80 145
//@node E4A4053F-0 610 200
//@node FC2780B8-0 405 305
//@node 82E708AC-0 890 200
//@node 3CCF8D23-0 685 305
//@node B855CC0B-0 480 305
//@node 8D98B135-0 1170 360
//@node AD89B06A-0 1450 40
//@node 74D9AC96-0 1225 145
//@node D5E58FA1-0 1730 200
//@node 1A415A8B-0 2010 40
//@node 088D7044-0 1805 145
//@node 3C71B9D9-0 2290 200
//@node 92076466-0 2085 305
//@node 3A607D1D-0 2570 200
//@node 6E69AD3B-0 2365 305
//@node 8D3C93A3-0 2850 200
//@node 004688B2-0 3130 200
//@node BA29CDA0-0 2925 305
//@node D9642C4C-0 2720 305
//@node 3A607D1D-1 3410 200
//@node 28BE3F4A-0 3205 305
//@node 646B62C4-0 3690 200
//@node D6B46F3F-0 3970 40
//@node B7316876-0 4250 40
//@node EE05C8AE-0 4530 40
//@node 8E272ECD-0 4305 145
//@node B7316876-1 4810 40
//@node 83E56082-0 5090 40
//@node 582D32C5-0 40 40
//@node 1645C6E4-0 330 40
//@node E4F3363E-0 610 40
//@node 5AF0D798-0 405 145
//@node A269F966-0 200 229
//@node 49CDFFF2-0 200 145
//@node D0CB7B04-0 890 200
//@node 79B414AC-0 665 305
//@node 97F8D724-0 1170 40
//@node 922CA967-0 965 145
//@node CCF6A5B7-0 1450 200
//@node EB95330F-0 1245 300
//@node 9ACEAA64-0 1730 40
//@node 7C3D5D8E-0 1525 145
//@node 83F509EF-0 2010 200
//@node A88041C9-0 1805 305
//@node 828A8980-0 2290 360
//@node D0D3CCDC-0 1850 465
//@node 7BCB0CCC-0 2080 465
//@node CC4C6398-0 2570 520
//@node 19C93C47-0 2850 200
//@node 7A7F8C59-0 2625 305
//@node A27D427E-0 3130 360
//@node 4981D083-0 3410 200
//@node D523CEDC-0 3205 305
//@node 55D25261-0 3690 360
//@node 97F8D724-1 3970 200
//@node 3F4ED406-0 3765 305
//@node CCF6A5B7-1 4250 360
//@node 1B3C357A-0 4045 460
//@node 6602134B-0 4530 200
//@node 56EB4509-0 40 40
//@node 64FB7F6F-0 330 40
//@node 96A2BBA7-0 125 145
//@node 777372B1-0 -80 145
//@node 24EEF0FC-0 610 200
//@node 081A6235-0 890 40
//@node D7A5CF70-0 685 140
//@node CB9D6C90-0 1170 40
//@node 71AA0882-0 965 145
//@node B1B93D23-0 1450 200
//@node BE99342C-0 1225 305
//@node 2396F9BA-0 1730 360
//@node F82C6223-0 2010 200
//@node 4B50784A-0 2290 200
//@node BA92837F-0 2085 305
//@node 3CF7A843-0 2570 360
//@node 0EF261E4-0 2365 465
//@node 6F44B557-0 2850 520
//@node C804D2E4-0 3130 520
//@node B60DBF1D-0 3410 360
//@node B5B6DFB2-0 3690 360
//@node 24EEF0FC-1 3970 360
//@node 6F44B557-1 4250 200
//@node 9A4F09AE-0 40 40
//@node 287BE3C9-0 330 40
//@node 1B6F2351-0 125 145
//@node FA3851BA-0 -80 145
//@node 5B43A417-0 890 200
//@node 221AD3C4-0 890 200
//@node 47C57CC6-0 685 305
//@node 32084AC7-0 480 305
//@node 819C508F-0 1450 200
//@node 98F1062B-0 1450 200
//@node F816C18D-0 1245 305
//@node E2AEEA3D-0 1040 305
//@node C0D46C5D-0 1040 389
//@node 819C508F-1 2010 200
//@node F044F5E7-0 2290 40
//@node 00424C4F-0 2570 40
//@node F5C817FA-0 2570 40
//@node 6F469DB0-0 2365 145
//@node 0C8F2A71-0 2850 40
//@node 0F971DB7-0 2645 145
//@node CA03CA92-0 3130 200
//@node 9DE0670B-0 2905 305
//@node AFD51A7D-0 3690 360
//@node 0084A0A1-0 3970 200
//@node 3D5CA862-0 3970 200
//@node 404F1AEE-0 3765 305
//@node 9A8F81AC-0 4530 360
//@node 70647DA0-0 4530 200
//@node 828B9A3E-0 4305 305
//@node 287BE3C9-1 4810 200
//@node BBA2A872-0 4605 305
//@node EAF0BBDB-0 4400 305
//@node 5B43A417-1 5370 360
//@node 221AD3C4-1 5370 360
//@node A4CEAF0F-0 5165 465
//@node 983BCEE6-0 4960 465
//@node 819C508F-2 5930 360
//@node 98F1062B-1 5930 360
//@node A276E82A-0 5725 465
//@node F1F75A3C-0 5520 465
//@node 8B1FCA06-0 5520 549
//@node 819C508F-3 6490 360
//@node 82918FA1-0 6490 360
//@node D555AB15-0 6285 465
//@node F9ABE4E5-0 6080 465
//@node 295D832F-0 6080 549
//@node B28C80E5-0 7050 360
//@node 075471BE-0 7330 200
//@node 7FC1F247-0 40 40
//@node B68319DE-0 330 40
//@node 635A7288-0 125 145
//@node E8269CEC-0 610 200
//@node E8F5AD74-0 405 300
//@node 22B3FF4C-0 890 200
//@node 271E72D8-0 685 305
//@node 25AFC935-0 1170 360
//@node 7CCC02BB-0 730 465
//@node 5408890B-0 960 465
//@node D5424A28-0 1450 520
//@node 504164E9-0 1730 200
//@node 0D461DF6-0 1505 305
//@node 7B6E7CF0-0 2010 360
//@node ABDD4F51-0 2290 200
//@node 2E84B5A2-0 2570 200
//@node C2212E26-0 2365 305
//@node 3A2C8765-0 2160 305
//@node F51D67A2-0 3130 360
//@node F8C0D70E-0 3130 200
//@node 53E1A132-0 2925 305
//@node 43C4F64D-0 2720 305
//@node DDBEAC51-0 3690 360
//@node 065E9CC9-0 3970 200
//@node E2C14415-0 40 40
//@node E4B73FD7-0 330 40
//@node 2A3D0B4C-0 610 40
//@node 81B22404-0 890 40
//@node 39244B8B-0 685 145
//@node 196661D0-0 1170 200
//@node 35D3EB16-0 945 305
//@node C731C0CF-0 1450 360
//@node F06BF1B7-0 1730 200
//@node 9F2BBC96-0 1505 305
//@node 91587226-0 2010 360
//@node 04C68AB3-0 2290 200
//@node 177A2169-0 40 40
//@node 3DDAA607-0 330 40
//@node F68C89C2-0 125 145
//@node A4AE538A-0 -80 145
//@node 7CB7B8C4-0 610 200
//@node 3760475A-0 890 40
//@node 8EBB35DC-0 665 145
//@node A80BD5BD-0 1170 40
//@node 17120D74-0 965 140
//@node 94725433-0 1450 40
//@node 770F2AB7-0 1245 145
//@node 30190D90-0 1730 40
//@node 85E5C4B8-0 1525 145
//@node D90614EB-0 2010 200
//@node BFABD56B-0 1785 305
//@node 68327702-0 2290 360
//@node B56FF3BB-0 2570 200
//@node ED455DEA-0 2365 305
//@node DCA4B570-0 2160 305
//@node D9A975EF-0 2160 389
//@node BE64EC56-0 2850 360
//@node 3760475A-1 3130 360
//@node BA193D3F-0 2905 465
//@node 04542DCB-0 3410 200
//@node 94C6A79C-0 3690 200
//@node B3F6ECD3-0 3485 305
//@node 63B8C154-0 3280 305
//@node 94725433-1 3970 360
//@node E8439374-0 3765 465
//@node 52DE0B06-0 4250 360
//@node 1635CC7C-0 4045 465
//@node 99C3C61E-0 3840 465
//@node C9ECB9D3-0 4810 360
//@node E06B3E6B-0 4810 360
//@node 8D45D47C-0 4605 465
//@node 3F729B8E-0 4400 465
//@node E9E2EB34-0 5370 360
//@node 96F5613B-0 5370 360
//@node ACB16194-0 5165 465
//@node 9160CA14-0 4960 465
//@node 7FC87212-0 5650 200
//@node 922EEF1E-0 5445 305
//@node 8A1446CB-0 5930 360
//@node 252A990C-0 5725 465
//@node FBC54A9F-0 6490 520
//@node 98AF75AC-0 6770 520
//@node 34FAF7B5-0 7050 360
//@node C56445EA-0 7330 360
//@node 7CB7B8C4-1 7610 360
//@node FBC54A9F-1 7890 200
//@node 1AB2E351-0 40 40
//@node 98A81FD8-0 330 40
//@node 58CA9C03-0 125 145
//@node 17E3AC2A-0 610 200
//@node 215390E8-0 405 300
//@node C32FDB0E-0 890 200
//@node E37BA5B2-0 685 305
//@node 1599CDEB-0 480 305
//@node 1C1457BE-0 480 389
//@node 3E3194DB-0 1170 360
//@node 3DD5C9BC-0 730 465
//@node 8900D62C-0 960 465
//@node 1CC49E12-0 1450 520
//@node 6F61D867-0 1730 200
//@node AF4952BE-0 1505 305
//@node D8FA6FAB-0 2010 360
//@node 66BD955E-0 2290 360
//@node 2B0A58CF-0 2570 200
//@node 1EF840C1-0 2850 200
//@node C8949B02-0 2645 305
//@node FD719BE0-0 2440 305
//@node 4DA73AD7-0 3410 360
//@node 0438D261-0 3410 360
//@node F04A5349-0 3205 465
//@node C2392A68-0 3000 465
//@node 91C026B4-0 3970 360
//@node D8FA6FAB-1 4250 200
//@node 854EA0BF-0 40 40
//@node 81271D78-0 330 40
//@node 72ED5F12-0 610 200
//@node 7A48660A-0 890 200
//@node 029A343B-0 1170 200
//@node 02626E33-0 945 305
//@node 6DD33EBF-0 1450 360
//@node 376F4E41-0 1730 360
//@node 345ED7F8-0 1525 465
//@node 37B9F82C-0 2010 360
//@node D05C4562-0 2290 360
//@node 97481323-0 2570 200
//@node EECFA7BA-0 2345 305
//@node 400F3823-0 2850 200
//@node 7639F761-0 2645 305
//@node 7A180E91-0 3130 360
//@node 331AA8C9-0 2925 460
//@node CF249EC2-0 3410 360
//@node A015A41F-0 3690 200
//@node 68057615-0 3465 305
//@node 344F0346-0 3970 360
//@node 5A2DB138-0 4250 360
//@node 9377FE81-0 3810 465
//@node 50303C11-0 4040 465
//@node 0847737A-0 4530 360
//@node 47A40D21-0 4810 360
//@node 84DC8E95-0 5090 200
//@node B63A2680-0 40 40
//@node 1431FDF2-0 330 40
//@node B95A5899-0 610 40
//@node DBAECCCC-0 405 145
//@node 3A296EA6-0 200 145
//@node 95A9B39A-0 890 200
//@node 9B3F53ED-0 685 305
//@node BF6F7C8E-0 1170 360
//@node E193A1A4-0 1450 360
//@node EA1EA36A-0 1245 465
//@node D017676B-0 1730 360
//@node 3E3CED7D-0 2010 360
//@node 7C05B563-0 2290 200
//@node DB950866-0 2085 305
//@node 3C6F1B35-0 2570 360
//@node 3DAFE10A-0 2130 465
//@node 92EF4F5A-0 2360 465
//@node D017676B-1 2850 520
//@node 3E3CED7D-1 3130 520
//@node 1431FDF2-1 3410 360
//@node EEBD204D-0 3690 200
//@node DA00CA50-0 3970 200
//@node 9242B222-0 3745 305
//@node C110D4F0-0 4250 200
//@node 592D25BD-0 4045 305
//@node F15DF648-0 4530 360
//@node 17169A86-0 4325 460
//@node 6393A6A7-0 4810 360
//@node EFD27250-0 5090 200
//@node CDCF53B9-0 5370 40
//@node 4FF5CF8F-0 40 40
//@node 526B768E-0 330 40
//@node 9C9F03E2-0 125 145
//@node 50BF57EA-0 -80 145
//@node 08D45CF1-0 610 200
//@node 0BE50653-0 890 40
//@node 7BDF5329-0 685 145
//@node EA3E1419-0 1170 40
//@node B8D2F81A-0 1450 40
//@node 52F4AFAD-0 1730 40
//@node 79D1B86C-0 1525 145
//@node 08D45CF1-1 2010 200
//@node F5F7395D-0 2290 40
//@node CE509CDF-0 2085 145
//@node 5C8B631D-0 1880 145
//@node A0E8556F-0 2570 200
//@node 0B5AF07B-0 2365 305
//@node F1CBA95B-0 2850 360
//@node 9B5713BD-0 3130 360
//@node 9432303F-0 2925 465
//@node C3D1DE88-0 3410 360
//@node 0BF0D5DE-0 3690 360
//@node 8DC1AA06-0 3970 200
//@node 8EDCBA47-0 4250 200
//@node 7057E04B-0 4025 305
//@node 1D7F57D7-0 4530 200
//@node 7BC781D0-0 4325 305
//@node 61815A8D-0 4810 360
//@node 798C9DAD-0 4605 460
//@node E7E6E4B2-0 5090 360
//@node D99AECB1-0 5370 200
//@node 8785C31A-0 5650 40
//@node E7E6E4B2-1 5930 40
//@node 2B698065-0 40 40
//@node 8644A974-0 330 40
//@node 4A0FF348-0 125 145
//@node 6E709DB1-0 610 200
//@node 08886B49-0 40 40
//@node A4AC1C09-0 330 40
//@node C7EADA25-0 105 145
//@node 7E947229-0 890 200
//@node 517E03A4-0 1170 40
//@node A371EF2B-0 40 40
//@node EB1844F6-0 330 40
//@node CF25A5AE-0 610 40
//@node 3BFAB75F-0 405 145
//@node 89F97A15-0 890 40
//@node C93E242B-0 665 145
//@node EC4EA901-0 1170 200
//@node C03FB065-0 1450 40
//@node 7E72A313-0 1245 145
//@node A7C7F8B0-0 1730 40
//@doomscript-blueprint end
