/***********************************************************************

character.script

***********************************************************************/

#define CHAR_TALK_TRIGGERED			0
#define CHAR_TALK_PRIMARY			1
#define CHAR_TALK_SECONDARY			2
#define CHAR_WALKTURN				65
#define CHAR_MIN_TURN				10
#define CHAR_TURN_THRESHOLD			45
#define CHAR_GETOUTOFWAY_DIST		124
#define CHAR_ALLOW_WALK_DIST		180
#define CHAR_ALLOW_WALK_DIST_NPC	80
#define CHAR_WAIT_BLOCKED			6
#define CHAR_PUSH_DELAY				0.35

#define CHAR_BLEND_COWER_TO_IDLE	6
#define CHAR_BLEND_TURN_TO_IDLE		0

object character : ai {
	entity		head;
	float		talkMode;
	float		talk_secondary_index;
	string		customAnim;
	float		customBlendOut;
	string		walkAnim;
	boolean		allow_turn;
	boolean		run;
	boolean		can_talk;
	boolean		no_cower;
	boolean		no_cower_saved;
	boolean		ignore_push;
	boolean		skipOutOfPath;
	character	listening_to_character;
	character	next_listener;
	float		lastPushTime;
	float		pushTime;

	entity		current_path;
	entity		next_path;
	
	boolean		follow_nodes;
	boolean		dont_push_others;

	float		playHeadAnim( string animname, float blend_frames );
	void		endHeadAnim( float blend_out );
	
	void		executePathCommand( entity pathnode );
	void		finishPathCommand();
	void		cancelPathCommand();

	void		checkBlocked();
	boolean		getOutOfWay();

	//
	// States
	//
	void		state_Begin();
	void		state_TalkTrigger();
	void		state_Idle();
	void		state_Killed();

	//
	// actions
	//
	void		idle_stand();
	void		idle_followPathEntities( entity pathnode );
	void		idle_talk();

	void		init();
	void		destroy();
	void		faceTowardsEntity( entity target, float duration );
	
	void		playCustomCycle( string animname, float blendTime );
	void		playCustomAnim( string animname, float blendIn, float blendOut );
	boolean		inCustomAnim();
	void		endCustomAnim();
	void		waitForCustomAnim( string animname, float blendIn, float blendOut );

	void		state_Spawner();
	void		state_Cower();
	void		check_cower();
	void		target_talk();
	void		say_triggered();
	void		say_primary();
	void		say_secondary();

	void		skip_conversation();

	void		disable_turning();
	void		enable_turning();

	// path following
	void 		path_corner();
	void 		path_anim();
	void 		path_cycleanim();
	void 		path_turn();
	void 		path_wait();
	void 		path_waitfortrigger();
	void 		path_hide();
	void 		path_show();
	void		path_conversation_listen();
	void		path_conversation();
	void		path_headanim();
	void 		path_talk();
	void 		path_talk_triggered();
	void 		path_talk_primary();
	void 		path_talk_secondary();
	void		path_lookat();
	void 		state_FollowAlternatePath();
	void 		follow_alternate_path1();
	void 		follow_alternate_path2();
	void 		follow_alternate_path3();

	// head anim states
	void		Anim_Disable();
	void		Head_Idle();
	void		Head_Dead();
	void		Head_TalkHeadOnly();

	// legs anim states
	void		Legs_Death();
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Walk_Special();
	void		Legs_Run();
	void		Legs_TurnLeft();
	void		Legs_TurnRight();
	void		Legs_Cower();
	void		Legs_CustomAnim();
	void		Legs_CustomCycle();
};

/***********************************************************************

	Head animation control

***********************************************************************/

void character::Anim_Disable() {
}

void character::Head_Idle() {
	idleAnim( ANIMCHANNEL_HEAD, "stand" );
}

void character::Head_Dead() {
	playAnim( ANIMCHANNEL_HEAD, "dead" );
}

void character::Head_TalkHeadOnly() {
	playAnim( ANIMCHANNEL_HEAD, customAnim );
	while( !animDone( ANIMCHANNEL_HEAD, customBlendOut ) ) {
		waitFrame();
	}
	finishAction( "talkAnim" );
	animState( ANIMCHANNEL_HEAD, "Head_Idle", customBlendOut );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void character::Legs_Death() {
	finishAction( "dead" );
}

void character::Legs_Idle() {
	float delta;

	if ( allow_turn && !AI_FORWARD ) {
		delta = getTurnDelta();
		if ( delta > CHAR_MIN_TURN ) {
			Legs_TurnLeft();
		}
		if ( delta < -CHAR_MIN_TURN ) {
			Legs_TurnRight();
		}
	}
	
	allowMovement( false );
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD ) {
			if ( walkAnim != "" ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk_Special", 8 );
			} else if ( run ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 );
			} else {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 );
			}
		}
		
		if ( allow_turn ) {
			if ( getTurnDelta() > CHAR_MIN_TURN ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
			}
			if ( getTurnDelta() < -CHAR_MIN_TURN ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
			}
		}
	}
}

void character::Legs_Walk() {
	float delta;

	allowMovement( true );
	playCycle( ANIMCHANNEL_LEGS, "walk" );

	while( AI_FORWARD && ( walkAnim == "" ) ) {
		if ( run ) {
			delta = getTurnDelta();
			if ( ( delta < CHAR_WALKTURN ) && ( delta > -CHAR_WALKTURN ) ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 );
			}
		}
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void character::Legs_Walk_Special() {
	allowMovement( true );
	playCycle( ANIMCHANNEL_LEGS, walkAnim );
	
	while( AI_FORWARD && ( walkAnim != "" ) )	{
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void character::Legs_Run() {
	float delta;

	allowMovement( true );
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	while( AI_FORWARD && run && ( walkAnim == "" ) ) {
		delta = getTurnDelta();
		if ( ( delta > CHAR_WALKTURN ) || ( delta < -CHAR_WALKTURN ) ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 );
		}

		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void character::Legs_TurnLeft() {
	float delta;

	allowMovement( true );
	animTurn( 180 );
	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, CHAR_BLEND_TURN_TO_IDLE ) ) {
		waitFrame();
	}
	animTurn( 0 );
	
	if ( allow_turn && !AI_FORWARD ) {
		delta = getTurnDelta();
		if ( delta > CHAR_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", CHAR_BLEND_TURN_TO_IDLE );
		}
		if ( delta < -CHAR_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", CHAR_BLEND_TURN_TO_IDLE );
		}
	}

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", CHAR_BLEND_TURN_TO_IDLE );
}

void character::Legs_TurnRight() {
	float delta;

	allowMovement( true );
	animTurn( 180 );
	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, CHAR_BLEND_TURN_TO_IDLE ) ) {
		waitFrame();
	}
	animTurn( 0 );

	if ( allow_turn && !AI_FORWARD ) {
		delta = getTurnDelta();
		if ( delta > CHAR_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", CHAR_BLEND_TURN_TO_IDLE );
		}
		if ( delta < -CHAR_MIN_TURN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", CHAR_BLEND_TURN_TO_IDLE );
		}
	}

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", CHAR_BLEND_TURN_TO_IDLE );
}

void character::Legs_Cower() {
	setTalkTarget( $null_entity );
	startSound( "snd_cower", SND_CHANNEL_VOICE, false );
	playAnim( ANIMCHANNEL_LEGS, "cower" );
	
	while( !animDone( ANIMCHANNEL_LEGS, CHAR_BLEND_COWER_TO_IDLE ) ) {
		lookAt( $player1, 0.1 );
		waitFrame();
	}
	
	setTalkTarget( $null_entity );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", CHAR_BLEND_COWER_TO_IDLE );
}

void character::Legs_CustomCycle() {
	allowMovement( true );
	playCycle( ANIMCHANNEL_LEGS, customAnim );
	while( 1 ) {
		waitFrame();
	}
}

void character::Legs_CustomAnim() {
	allowMovement( true );
	playAnim( ANIMCHANNEL_LEGS, customAnim );
	
	while( !animDone( ANIMCHANNEL_LEGS, customBlendOut ) ) {
		waitFrame();
	}
	
	finishAction( "customAnim" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", customBlendOut );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
character::init
=====================
*/
void character::init() {
	float mod;

	mod = getIntKey( "head_look" );
	setBoneMod( mod );

	lastPushTime = 0;
	pushTime = 0;

	dont_push_others = getIntKey( "dont_push_others" );

	talkMode = CHAR_TALK_PRIMARY;
	talk_secondary_index = 1;
	follow_nodes = true;
	walkAnim = "";
	run = false;

	can_talk = getIntKey( "talks" );
	no_cower = getIntKey( "no_cower" );
	ignore_push = getIntKey( "ignore_push" );
	no_cower_saved = no_cower;
	if ( getFloatKey( "turn_rate" ) != 0 ) {
		allow_turn = true;
	} else {
		ignore_push = true;
	}

	self.setKey( "conversationNext", "" );
	
	if ( getIntKey( "spawner" ) ) {
		setNextState( "state_Spawner" );
	} else {
		setNextState( "state_Begin" );
	}
}

/*
=====================
character::destroy
=====================
*/
void character::destroy() {
	character conversation_char;

	// disconnect from anyone we're listening to
	if ( listening_to_character ) {
		conversation_char = listening_to_character;
        while( conversation_char ) {
			if ( self == conversation_char.next_listener ) {
				// point the previous one in the list to the our next listener
				conversation_char.next_listener = next_listener;
				break;
			}

			conversation_char = conversation_char.next_listener;
		}
	}
}

/*
=====================
character::state_Spawner
=====================
*/
void character::state_Spawner() {
	entity	ent;
	float	triggerCount;
	float	maxSpawn;
	float	i;
	string	name;

	maxSpawn = getIntKey( "spawner" );
	name = getName();

	hide();

	triggerCount = 0;
	AI_ACTIVATED = false;
	while( 1 ) {
		if ( AI_ACTIVATED ) {
			triggerCount++;
			AI_ACTIVATED = false;
		}

		if ( triggerCount ) {
			if ( canBecomeSolid() ) {
				for( i = 0; i < maxSpawn; i++ ) {
					ent = sys.getEntity( name + "_" + i );
					if ( !ent ) {
						break;
					}
				}

				if ( i < maxSpawn ) {
					triggerCount--;
					sys.copySpawnArgs( self );
					sys.setSpawnArg( "spawner", "0" );
					sys.setSpawnArg( "name", name + "_" + i );
					if ( getKey( "spawn_target" ) != "" ) {
						sys.setSpawnArg( "target", getKey( "spawn_target" ) );
					}
					ent = sys.spawn( getKey( "classname" ) );
					sys.trigger( ent );
				}
			}
		}
		waitFrame();
	}
}

/*
=====================
character::state_Cower
=====================
*/
void character::state_Cower() {
	float waittime;

	stopSound( SND_CHANNEL_VOICE, false );
	if ( head ) {
		head.stopSound( SND_CHANNEL_VOICE, false );
	}

	endHeadAnim( 6 );
	animState( ANIMCHANNEL_LEGS, "Legs_Cower", 6 );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_Cower" ) ) {
		waitFrame();
	}

	setTalkTarget( $null_entity );
	setState( "state_Idle" );
}

/*
=====================
character::check_cower
=====================
*/
void character::check_cower() {
	if ( !no_cower ) {
		if ( heardSound( false ) ) {
			endHeadAnim( 6 );
			cancelPathCommand();
			setState( "state_Cower" );
		}
	}
}

/*
=====================
character::target_talk

forces character to talk to the player
=====================
*/
void character::target_talk() {
	cancelPathCommand();
	setTalkTarget( $player1 );
	idle_talk();
	setState( "state_Idle" );
}

/*
=====================
character::say_triggered

forces character to say his triggered talk anim to the player
=====================
*/
void character::say_triggered() {
	cancelPathCommand();
	talkMode = CHAR_TALK_TRIGGERED;
	setTalkTarget( $player1 );
	setState( "state_Idle" );
}

/*
=====================
character::say_primary

forces character to say his primary talk anim to the player
=====================
*/
void character::say_primary() {
	cancelPathCommand();
	talkMode = CHAR_TALK_PRIMARY;
	setTalkTarget( $player1 );
	setState( "state_Idle" );
}

/*
=====================
character::say_secondary

forces character to say his secondary talk anim to the player
=====================
*/
void character::say_secondary() {
	cancelPathCommand();
	talkMode = CHAR_TALK_SECONDARY;
	setTalkTarget( $player1 );
	setState( "state_Idle" );
}

/*
=====================
character::faceTowardsEntity
=====================
*/
void character::faceTowardsEntity( entity target, float duration ) {
	vector delta;
	vector ang1;
	vector ang2;
	vector ang3;

	delta = target.getOrigin();
	delta = delta - getOrigin();
	ang1 = sys.VecToAngles( delta );
	ang2 = getAngles();
	ang3 = anglemod180( ang1 - ang2 );
	if ( ang3_y < -CHAR_TURN_THRESHOLD ) {
		turnTo( ang1_y );
	} else if ( ang3_y > CHAR_TURN_THRESHOLD ) {
		turnTo( ang1_y );
	}
	
	lookAt( target, duration );
}

/*
=====================
character::playCustomCycle
=====================
*/
void character::playCustomCycle( string animname, float blendTime ) {
	customAnim = animname;
	animState( ANIMCHANNEL_LEGS, "Legs_CustomCycle", blendTime );
}

/*
=====================
character::playCustomAnim
=====================
*/
void character::playCustomAnim( string animname, float blendIn, float blendOut ) {
	customBlendOut = blendOut;
	customAnim = animname;
	animState( ANIMCHANNEL_LEGS, "Legs_CustomAnim", blendIn );
}

/*
=====================
character::inCustomAnim
=====================
*/
boolean character::inCustomAnim() {
	return inAnimState( ANIMCHANNEL_LEGS, "Legs_CustomAnim" );
}

/*
=====================
character::endCustomAnim
=====================
*/
void character::endCustomAnim() {
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", customBlendOut );
}

/*
=====================
character::waitForCustomAnim
=====================
*/
void character::waitForCustomAnim( string animname, float blendIn, float blendOut ) {
	check_cower();
	customBlendOut = blendOut;
	customAnim = animname;
	animState( ANIMCHANNEL_LEGS, "Legs_CustomAnim", blendIn );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_CustomAnim" ) ) {
		check_cower();
		waitFrame();
	}
}

/*
=====================
character::endHeadAnim
=====================
*/
void character::endHeadAnim( float blend_out ) {
	if ( getHead() ) {
		stopAnim( ANIMCHANNEL_HEAD, blend_out );
	}
	setBlendFrames( ANIMCHANNEL_LEGS, blend_out );
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
	if ( getHead() ) {
		animState( ANIMCHANNEL_HEAD, "Head_Idle", blend_out );
	}
}

/*
=====================
character::playHeadAnim
=====================
*/
float character::playHeadAnim( string animname, float blend_frames ) {
	string anim;
	float headlength;
	float bodylength;

	animState( ANIMCHANNEL_LEGS, "Anim_Disable", blend_frames );
	setBlendFrames( ANIMCHANNEL_LEGS, blend_frames );
	idleAnim( ANIMCHANNEL_LEGS, "stand" );
	waitFrame();

	anim = chooseAnim( ANIMCHANNEL_HEAD, animname );
	if ( anim != "" ) {
		setBlendFrames( ANIMCHANNEL_HEAD, blend_frames );
		playAnim( ANIMCHANNEL_HEAD, anim );
		headlength = animLength( ANIMCHANNEL_HEAD, anim );

		anim = chooseAnim( ANIMCHANNEL_LEGS, animname );
		if ( anim == "" ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_frames );
		} else {
			bodylength = animLength( ANIMCHANNEL_LEGS, anim );
			if ( bodylength < headlength ) {
				playCycle( ANIMCHANNEL_LEGS, anim );
			} else {
				playAnim( ANIMCHANNEL_LEGS, anim );
			}
		}

		return ANIMCHANNEL_HEAD;
	} else {
		// play on legs
		if ( blend_frames >= 0 ) {
			setBlendFrames( ANIMCHANNEL_LEGS, blend_frames );
		}
		anim = chooseAnim( ANIMCHANNEL_LEGS, animname );
		if ( anim == "" ) {
			playAnim( ANIMCHANNEL_LEGS, "stand" );
		} else {
			playAnim( ANIMCHANNEL_LEGS, animname );
		}
		return ANIMCHANNEL_LEGS;
	}
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
character::state_Begin
=====================
*/
void character::state_Begin() {
	float	doHide;
	float	teleportType;
	string	triggerAnim;
	float	movetype;
	
	head = getHead();

	talkMode = CHAR_TALK_PRIMARY;
	follow_nodes = true;
	walkAnim = "";
	run = false;

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	if ( getHead() ) {
		animState( ANIMCHANNEL_HEAD, "Head_Idle", 0 );
	}

	doHide = getIntKey( "hide" );
	teleportType = getIntKey( "teleport" );
	triggerAnim = getKey( "trigger_anim" );
	if ( triggerAnim != "" ) {
		//
		// hide until triggered and then play a special animation
		//
		checkAnim( ANIMCHANNEL_LEGS, triggerAnim );
		hide();
		waitUntil( AI_ACTIVATED );
		clearEnemy();
		waitUntil( canBecomeSolid() );
		show();
		waitForCustomAnim( triggerAnim, 0, 4 );
	} else if ( teleportType > 0 ) {
		//
		// teleport in when triggered
		//
		hide();
		AI_ACTIVATED = false;	
		waitUntil( AI_ACTIVATED );
		clearEnemy();
		waitUntil( canBecomeSolid() );
		becomeSolid();
		movetype = getMoveType();
		setMoveType( MOVETYPE_STATIC );
		if ( teleportType == 1 ) {
			startFx( "fx/teleporter1.fx" );
			wait( 1.6 );
		} else if ( teleportType == 2 ) {
			startFx( "fx/teleporter2.fx" );
			wait( 2.6 );
		} else if ( teleportType == 3 ) {
			startFx( "fx/teleporter3.fx" );
			wait( 3.6 );
		} else {
			startFx( "fx/teleporter.fx" );
			wait( 0.6 );
		}
		show();
		playCustomAnim( "teleport", 0, 4 );
		waitAction( "customAnim" );
		setMoveType( movetype );
	} else if ( doHide ) {
		//
		// hide until triggered
		//
		hide();
		AI_ACTIVATED = false;	
		waitUntil( AI_ACTIVATED );
		if ( doHide == 1 ) {
			AI_ACTIVATED = false;
			clearEnemy();
		}
		waitUntil( canBecomeSolid() );
		show();
	}

	if ( getIntKey( "trigger" )  ) {
		AI_ACTIVATED = false;
		waitUntil( AI_ACTIVATED );
	}

	float waittime;
	waittime = getFloatKey( "wait" );
	if ( waittime > 0 ) {
		sys.wait( waittime );
	}
	
	if ( getIntKey( "talktrigger" )  ) {
		setState( "state_TalkTrigger" );
	} else {
		setState( "state_Idle" );
	}
}

/*
=====================
character::state_TalkTrigger
=====================
*/
void character::state_TalkTrigger() {
	string animname;
	entity activator;

	animname = getKey( "anim" );
	if ( animname != "" ) {
		playCustomCycle( animname, 0 );
	}

	while( !AI_ACTIVATED ) {
		check_cower();
		waitFrame();
	}

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
	
	setTalkTarget( $player1 );
	talkMode = CHAR_TALK_TRIGGERED;
	
	setState( "state_Idle" );
}
	
/*
=====================
character::state_Idle
=====================
*/
void character::state_Idle() {
	entity node;
	
	if ( can_talk ) {
		setTalkState( TALK_OK );
	}
	no_cower = no_cower_saved;

	while( 1 ) {
		if ( AI_TALK ) {
			idle_talk();
			continue;
		}
		
		if ( follow_nodes ) {
			if ( !current_path ) {
				current_path = randomPath();
			}
			if ( current_path ) {
				idle_followPathEntities( current_path );
                if ( getIntKey( "follow_once" ) ) {
					follow_nodes = false;
				}
				continue;
			}
		}

        idle_stand();
	}
}

/*
=====================
character::state_Killed
=====================
*/
void character::state_Killed() {
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );
	if ( getHead() ) {
		animState( ANIMCHANNEL_HEAD, "Head_Dead", 0 );
	}
	stopThinking();
}

/***********************************************************************

	Idle

***********************************************************************/

/*
=====================
character::idle_stand
=====================
*/
void character::idle_stand() {
	stopMove();
	while( !AI_TALK ) {
		check_cower();
		if ( AI_PUSHED ) {
			getOutOfWay();
		}

		waitFrame();
	}
}

/*
=====================
character::idle_talk
=====================
*/
void character::idle_talk() {
	float	ang;
	float	talktime;
	float	endtime;
	float	talkradius;
	float	blendin;
	float	blendout;
	entity	target;
	vector	originalAngles;
	float	currentTime;
	boolean	no_turn;
	entity  talkTo;
	float	channel;

	talkTo = getTalkTarget();
	
	no_turn = getIntKey( "talk_no_turn" );

	originalAngles = getAngles();
	stopMove();

	if ( !no_turn && allow_turn ) {
		faceTowardsEntity( talkTo, 0.1 );
		sys.wait( 0.5 );
		// wait for turn anim to finish
		while( !inAnimState( ANIMCHANNEL_LEGS, "Legs_Idle" ) ) {
			if ( talkMode != CHAR_TALK_TRIGGERED ) {
				check_cower();
			}
			lookAt( talkTo, 0.1 );
			waitFrame();
		}
	}	

	allowMovement( true );

	talkradius = getFloatKey( "talkradius" );
	if ( talkMode == CHAR_TALK_TRIGGERED ) {
		// triggered response
		blendin = self.getIntKey( "talk0_blendin" );
		blendout = self.getIntKey( "talk0_blendout" );
		channel = playHeadAnim( "talk_trigger", blendin );
		talkMode = CHAR_TALK_PRIMARY;
	} else if ( talkMode == CHAR_TALK_PRIMARY ) {
		// primary response
		blendin = self.getIntKey( "talk1_blendin" );
		blendout = self.getIntKey( "talk1_blendout" );
		channel = playHeadAnim( "talk_primary", blendin );
		talkMode = CHAR_TALK_SECONDARY;
	} else if ( talkMode == CHAR_TALK_SECONDARY ) {
		// secondary response
		blendin = self.getIntKey( "talk2_blendin" );
		blendout = self.getIntKey( "talk2_blendout" );
		channel = playHeadAnim( "talk_secondary" + talk_secondary_index, blendin );
		talk_secondary_index = talk_secondary_index + 1;
		if ( !hasAnim( ANIMCHANNEL_HEAD, "talk_secondary" + talk_secondary_index ) && !hasAnim( ANIMCHANNEL_LEGS, "talk_secondary" + talk_secondary_index ) ) {
			talk_secondary_index = 1;
		}
	}

	while( !animDone( channel, blendout ) ) {
		if ( distanceTo( talkTo ) > talkradius ) {
			// stop talking
			stopSound( SND_CHANNEL_VOICE, false );
			if ( head ) {
				head.stopSound( SND_CHANNEL_VOICE, false );
			}
			break;
		}

		check_cower();
		if ( no_turn || !allow_turn ) {
			lookAt( talkTo, 0.1 );
		} else {
			faceTowardsEntity( talkTo, 0.1 );
		}
		waitFrame();
	}
	endHeadAnim( blendout );
	setTalkTarget( $null_entity );
	
	talktime = getFloatKey( "talktime" );
	currentTime = sys.getTime();
	endtime = currentTime + talktime;
	while( ( currentTime < endtime ) && ( distanceTo( talkTo ) <= talkradius ) ) {
		check_cower();
		if ( no_turn || !allow_turn ) {
			lookAt( talkTo, 0.1 );
		} else {
			faceTowardsEntity( talkTo, 0.1 );
		}
		if ( AI_TALK ) {
			allowMovement( false );
			return;
		}
		if ( AI_PUSHED ) {
			getOutOfWay();
		}
		waitFrame();
		currentTime = sys.getTime();
	}

	lookAt( $null_entity, 0 );
	turnTo( originalAngles_y );
	allowMovement( false );
}

/*
=====================
character::idle_followPathEntities
=====================
*/
void character::idle_followPathEntities( entity pathnode ) {
	current_path = pathnode;
	while( current_path ) {
		check_cower();
		executePathCommand( current_path );
		if ( AI_TALK ) {
			setState( "state_Idle" );
		}
	}
}

/*
=====================
character::executePathCommand
=====================
*/
void character::executePathCommand( entity pathnode ) {
	string nodeaction;

	current_path = pathnode;
	next_path = current_path.randomPath();
	nodeaction = current_path.getKey( "classname" );
	if ( !hasFunction( nodeaction ) ) {
		sys.warning( "'" + getName() + "' encountered an unsupported path entity '" + nodeaction + "' on entity '" + current_path.getName() + "'\n" );
		return;
	}

	//sys.print( getName() + " : " + current_path.getName() + " : " + nodeaction + "\n" );

	skipOutOfPath = current_path.getIntKey( "skip" );

	if ( current_path.getIntKey( "no_cower" ) ) {
		no_cower = true;
	}
	if ( current_path.getIntKey( "no_talk" ) && can_talk ) {
		setTalkState( TALK_BUSY );
	}

	callFunction( nodeaction );

	if ( AI_TALK ) {
		cancelPathCommand();
		setState( "state_Idle" );
	}

	finishPathCommand();
}

/*
=====================
character::finishPathCommand
=====================
*/
void character::finishPathCommand() {
	string triggername;
	entity triggerent;

	// trigger any entities the path had targeted
	triggername = current_path.getKey( "trigger" );
	if ( triggername != "" ) {
		triggerent = sys.getEntity( triggername );
		if ( triggerent ) {
			triggerent.activate( self );
		}
	}
	current_path = next_path;

	skipOutOfPath = false;
	if ( can_talk ) {
		setTalkState( TALK_OK );
	}
	no_cower = no_cower_saved;
}

/*
=====================
character::cancelPathCommand
=====================
*/
void character::cancelPathCommand() {
	if ( skipOutOfPath ) {
		finishPathCommand();
	}

	skipOutOfPath = false;
	if ( can_talk ) {
		setTalkState( TALK_OK );
	}
	no_cower = no_cower_saved;
}

/*
=====================
character::getOutOfWay
=====================
*/
boolean character::getOutOfWay() {
	vector org;
	vector oldorigin;
	vector pos;
	vector ang;
	vector dir;

	if ( ignore_push ) {
		return false;
	}

	// check if we were pushed in the last frame
	if ( ( sys.getTime() - lastPushTime ) > GAME_FRAMETIME ) {
		// start the push timer
		lastPushTime = sys.getTime();
		pushTime = lastPushTime + CHAR_PUSH_DELAY;
		return false;
	}

	// update the last push time so next frame we know we were pushed this frame
	lastPushTime = sys.getTime() + GAME_FRAMETIME;

	// check if we've been pushed long enough
	if ( sys.getTime() < pushTime ) {
		return false;
	}

	// choose a point inside the aas
	oldorigin = getOrigin();
	org = pushPointIntoAAS( oldorigin );

	// determine if there's a direction we can walk
	setOrigin( org );
	for( ang_y = 0; ang_y < 360; ang_y += 45 ) {
		dir = sys.angToForward( ang );
		pos = pushPointIntoAAS( org + dir * CHAR_GETOUTOFWAY_DIST );
		if ( testMoveToPosition( pos ) ) {
			break;
		}
	}
	setOrigin( oldorigin );

	if ( ang_y >= 360 ) {
		// no direction that we can move in, so don't do anything
		return false;
	}

	// make sure we're inside the aas
	moveToPosition( org );
	while( !AI_MOVE_DONE ) {
		check_cower();
		if ( AI_TALK ) {
			setState( "state_Idle" );
		}
		waitFrame();
	}

	turnToPos( pos );

	// slide him the rest of the way to make sure we're fully in the aas
	if ( org != getOrigin() ) {
		slideTo( org, 0.2 );
		while( !AI_MOVE_DONE ) {
			check_cower();
			if ( AI_TALK ) {
				setState( "state_Idle" );
			}
			waitFrame();
		}
	}

	// move out of the way
	moveToPosition( pos );
	while( !AI_MOVE_DONE ) {
		check_cower();
		if ( AI_TALK ) {
			setState( "state_Idle" );
		}
		waitFrame();
	}
	
	// turn around so we face the way we came
	turnTo( getCurrentYaw() + 180 );

	stopMove();

	return true;
}

/*
=====================
character::checkBlocked
=====================
*/
void character::checkBlocked() {
	entity obstacle;
	vector playerMoveDir;
	character npc;
	float allow_walk_dist;
	float end_time;
	boolean waitUntilPathClear;
	float channel;
	vector obstacle_pos;
	vector delta;

	if ( dont_push_others ) {
		if ( moveStatus() >= MOVE_STATUS_BLOCKED_BY_OBJECT ) {
			// just wait for the path to be clear
			obstacle = getObstacle();

			if ( moveStatus() == MOVE_STATUS_BLOCKED_BY_OBJECT ) {
				kickObstacles( getObstacle(), 60 );
				return;
			}

			obstacle_pos = obstacle.getOrigin();
			saveMove();
			stopMove();
			while( 1 ) {
				delta = obstacle_pos - obstacle.getOrigin();
				delta_z = 0;
				if ( sys.vecLength( delta ) > 4 ) {
					restoreMove();
					if ( moveStatus() < MOVE_STATUS_BLOCKED_BY_OBJECT ) {
						break;
					}
					if ( getObstacle() != obstacle ) {
						break;
					}
					stopMove();
				}
				check_cower();
				if ( AI_PUSHED ) {
					getOutOfWay();
				}
				if ( AI_TALK ) {
					setState( "state_Idle" );
				}
				waitFrame();
			}
		}
		return;
	}

	waitUntilPathClear = false;
	while( moveStatus() >= MOVE_STATUS_BLOCKED_BY_OBJECT ) {
		obstacle = getObstacle();
		npc = obstacle;
		if ( npc ) {
			if ( npc.ignore_push ) {
				// can't push this guy
				break;
			}
		} else if ( moveStatus() == MOVE_STATUS_BLOCKED_BY_OBJECT ) {
			kickObstacles( getObstacle(), 60 );
			break;
		}

		obstacle_pos = obstacle.getOrigin();

		saveMove();
		stopMove();

		channel = playHeadAnim( "talk_excuseme", 8 );

		// prevent an infinite loop if we don't have an excuse me anim
		waitFrame();

		while( !animDone( channel, 8 ) ) {
			check_cower();
			faceTowardsEntity( obstacle, 0.1 );
			waitFrame();
		}
		endHeadAnim( 8 );

		if ( npc ) {
			npc.AI_PUSHED = true;
			npc.lastPushTime = sys.getTime();
			npc.pushTime = sys.getTime();
			allow_walk_dist = CHAR_ALLOW_WALK_DIST_NPC;
		} else {
			allow_walk_dist = CHAR_ALLOW_WALK_DIST;
		}

		end_time = sys.getTime() + CHAR_WAIT_BLOCKED;
		while( ( sys.getTime() < end_time ) || AI_PUSHED || waitUntilPathClear ) {
			check_cower();
			faceTowardsEntity( obstacle, 0.1 );

			delta = obstacle_pos - obstacle.getOrigin();
			delta_z = 0;
			
			if ( sys.vecLength( delta ) < 4 ) {
				if ( sys.getTime() > end_time ) {
					break;
				}
				if ( AI_PUSHED ) {
					if ( getOutOfWay() ) {
						waitUntilPathClear = true;
						end_time = sys.getTime() + CHAR_WAIT_BLOCKED;
					}
				}
			} else {
				restoreMove();
				if ( !AI_OBSTACLE_IN_PATH ) {
					if ( !waitUntilPathClear || ( sys.getTime() > end_time ) ) {
						break;
					}
				} else if ( getObstacle() != obstacle ) {
					break;
				}

				if ( distanceTo( obstacle ) > allow_walk_dist ) {
					break;
				}
				if ( moveStatus() >= MOVE_STATUS_BLOCKED_BY_OBJECT ) {
					if ( AI_PUSHED ) {
						if ( getOutOfWay() ) {
							waitUntilPathClear = true;
							end_time = sys.getTime() + CHAR_WAIT_BLOCKED;
						}
					}
				}
				stopMove();
			}

			if ( AI_TALK ) {
				setState( "state_Idle" );
			}

			waitFrame();
		}
		restoreMove();
	}
}

/***********************************************************************

	path functions

***********************************************************************/

/*
=====================
character::path_corner
=====================
*/
void character::path_corner() {
	run = current_path.getIntKey( "run" );
	walkAnim = current_path.getKey( "anim" );
	moveToEntity( current_path );
	waitFrame();
	while( !AI_MOVE_DONE && !AI_TALK ) {
		check_cower();
		checkBlocked();
		moveToEntity( current_path );
		waitFrame();
	}
	walkAnim = "";
	run = false;

	if ( AI_TALK ) {
		cancelPathCommand();
		setState( "state_Idle" );
	}
	if ( AI_DEST_UNREACHABLE ) {
		// Can't reach
		sys.warning( "entity '" + getName() + "' couldn't reach path_corner '" + current_path.getName() + "'" );
		waitFrame();
	}
}

/*
=====================
character::path_anim
=====================
*/
void character::path_anim() {
	string	animname;
	float	ang;
	float	blend_in;
	float	blend_out;
	float	channel;

	animname = current_path.getKey( "anim" );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );

	if ( current_path.getKey( "angle" ) != "" ) {
		ang = current_path.getFloatKey( "angle" );
		turnTo( ang );
		while( !facingIdeal() ) {
			check_cower();
			waitFrame();
		}
	}

	if ( current_path.getIntKey( "head_anim" ) ) {
		channel = playHeadAnim( animname, blend_in );
		while( !animDone( channel, blend_out ) ) {
			check_cower();
			if ( AI_TALK ) {
				endHeadAnim( blend_out );
				sys.wait( blend_out / 24 );
				cancelPathCommand();
				setState( "state_Idle" );
			}
			waitFrame();
		}
		endHeadAnim( blend_out );
	} else {
		playCustomAnim( animname, blend_in, blend_out );
		while( inCustomAnim() ) {
			check_cower();
			if ( AI_TALK ) {
				endCustomAnim();
				sys.wait( blend_out / 24 );
				cancelPathCommand();
				setState( "state_Idle" );
			}
			waitFrame();
		}
	}
}

/*
=====================
character::path_cycleanim
=====================
*/
void character::path_cycleanim() {
	string	animname;
	float	ang;
	float	blend_in;
	float	blend_out;
	float	waittime;

	animname = current_path.getKey( "anim" );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );

	waittime = current_path.getFloatKey( "wait" );

	AI_ACTIVATED = false;

	if ( current_path.getKey( "angle" ) != "" ) {
		ang = current_path.getFloatKey( "angle" );
		turnTo( ang );
		while( !facingIdeal() ) {
			if ( !waittime && AI_ACTIVATED ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
				return;
			}
			check_cower();
			waitFrame();
		}
	}

	playCustomCycle( animname, blend_in );

	if ( waittime ) {
		waittime += sys.getTime();
		while( sys.getTime() < waittime ) {
			check_cower();
			if ( AI_TALK ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
				sys.wait( blend_out / 24 );
				cancelPathCommand();
				setState( "state_Idle" );
			}
			waitFrame();
		}
	} else {
		while( !AI_ACTIVATED ) {
			check_cower();
			if ( AI_TALK ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
				sys.wait( blend_out / 24 );
				cancelPathCommand();
				setState( "state_Idle" );
				return;
			}
			waitFrame();
		}
	}
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
}

/*
=====================
character::path_turn
=====================
*/
void character::path_turn() {
	vector ang;

	ang = current_path.getAngles();
	turnTo( ang_y );

	// wait 1 frame so that Legs_Idle can start turning.
	waitFrame();

	while( !facingIdeal() ) {
		check_cower();
		waitFrame();
	}
}

/*
=====================
character::path_wait
=====================
*/
void character::path_wait() {
	float waittime;

	waittime = current_path.getFloatKey( "wait" );
	waittime += sys.getTime();
	while( sys.getTime() < waittime ) {
		check_cower();
		waitFrame();
	}
}

/*
=====================
character::path_waitfortrigger
=====================
*/
void character::path_waitfortrigger() {
	AI_ACTIVATED = false;
	while( !AI_ACTIVATED ) {
		check_cower();
		if ( AI_TALK ) {
			cancelPathCommand();
			setState( "state_Idle" );
		}
		waitFrame();
	}
}
			
/*
=====================
character::path_hide
=====================
*/
void character::path_hide() {
	hide();
}

/*
=====================
character::path_show
=====================
*/
void character::path_show() {
	waitUntil( canBecomeSolid() );
	show();
}

/*
=====================
character::skip_conversation
=====================
*/
void character::skip_conversation() {
	string classname;

	classname = current_path.getKey( "classname" );
	while( sys.strLeft( classname, 17 ) == "path_conversation" ) {
		current_path = next_path;
		next_path = next_path.randomPath();
		if ( !next_path ) {
			break;
		}
		classname = current_path.getKey( "classname" );
	}
	stopSound( SND_CHANNEL_VOICE, false );
	if ( head ) {
		head.stopSound( SND_CHANNEL_VOICE, false );
	}
}

/*
=====================
character::break_out_of_conversation
=====================
*/
void character::break_out_of_conversation() {
	character listener;

	// tell our listeners to skip out
	while( next_listener ) {
		listener = next_listener;
		next_listener = listener.next_listener;
		listener.skip_conversation();
		listener.next_listener = $null_entity;
		listener.listening_to_character  = $null_entity;
	}

	skip_conversation();
}

/*
=====================
character::path_conversation_listen
=====================
*/
void character::path_conversation_listen() {
	string	focus_character;
	string	anim;
	boolean no_look;
	float	blend_in;
	float	blend_out;
	
	stopMove();

	focus_character = current_path.getKey( "focus" );
	listening_to_character = sys.getEntity( focus_character );

	anim = current_path.getKey( "anim" );
	if ( anim != "" ) {
		blend_in = current_path.getIntKey( "blend_in" );
		blend_out = current_path.getIntKey( "blend_out" );
		playCustomCycle( anim, blend_in );
	}

	no_look = current_path.getIntKey( "no_look" );

	// link ourselves into the focus character's listeners
	next_listener = listening_to_character.next_listener;
	listening_to_character.next_listener = self;

	while( listening_to_character ) {
		if ( AI_TALK ) {
			listening_to_character.break_out_of_conversation();
			cancelPathCommand();
			setState( "state_Idle" );
		}
		check_cower();
		if ( !no_look ) {
			lookAt( listening_to_character, 0.1 );
		}
		waitFrame();
	}

	if ( anim != "" ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
	}
}

/*
=====================
character::path_conversation
=====================
*/
void character::path_conversation() {
	string		dialog;
	string		anim;
	string		focus_character;
	float		waitTime;
	entity		listener;
	character	char_listener;
	float		blend_in;
	float		blend_out;
	float		channel;

	stopMove();

	anim = current_path.getKey( "anim" );
	focus_character = current_path.getKey( "focus" );
	waitTime = current_path.getFloatKey( "wait" );
	listener = sys.getEntity( focus_character );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );

	// say the conversation line
	dialog = current_path.getKey( "snd_dialog" );
	if ( dialog != "" ) {
		startSoundShader( dialog, SND_CHANNEL_VOICE );
	}

	setBlendFrames( ANIMCHANNEL_LEGS, blend_in );
	if ( getHead() ) {
		animState( ANIMCHANNEL_HEAD, "Anim_Disable", blend_in );
	}

	channel = playHeadAnim( anim, blend_in );
	while( !animDone( channel, blend_out ) ) {
		if ( AI_TALK ) {
			break;
		}
		check_cower();
		lookAt( listener, 0.1 );
		waitFrame();
	}

	endHeadAnim( blend_out );

	if ( AI_TALK ) {
		break_out_of_conversation();
		cancelPathCommand();
		setState( "state_Idle" );
	}

	if ( waitTime ) {
		// wait for a bit
		waitTime += sys.getTime();
		while( waitTime > sys.getTime() ) {
			if ( AI_TALK ) {
				break_out_of_conversation();
				cancelPathCommand();
				setState( "state_Idle" );
			}
			check_cower();
			lookAt( listener, 0.1 );
			waitFrame();
		}
	}

	// tell our listeners we're done
	while( next_listener ) {
		char_listener = next_listener;
		next_listener = char_listener.next_listener;
		char_listener.next_listener = $null_entity;
		char_listener.listening_to_character  = $null_entity;
	}
}

/*
=====================
character::path_headanim
=====================
*/
void character::path_headanim() {
	float blendIn;
	
	blendIn = current_path.getIntKey( "blend_in" );
	customBlendOut = current_path.getIntKey( "blend_out" );
	customAnim = current_path.getKey( "anim" );
	animState( ANIMCHANNEL_HEAD, "Head_TalkHeadOnly", blendIn );
}

/*
=====================
character::path_waitforheadanim
=====================
*/
void character::path_waitforheadanim() {
	string	focus_entity;
	entity	focus;
	
	stopMove();

	focus_entity = current_path.getKey( "focus" );
	focus = sys.getEntity( focus_entity );

	while( inAnimState( ANIMCHANNEL_HEAD, "Head_TalkHeadOnly" ) ) {
		if ( AI_TALK ) {
			cancelPathCommand();
			setState( "state_Idle" );
		}
		check_cower();
		lookAt( focus, 0.1 );
		waitFrame();
	}
}

/*
=====================
character::path_talk

forces character to talk to the player
=====================
*/
void character::path_talk() {
	setTalkTarget( $player1 );
	idle_talk();
}

/*
=====================
character::path_talk_triggered

forces character to say his triggered talk anim to the player
=====================
*/
void character::path_talk_triggered() {
	talkMode = CHAR_TALK_TRIGGERED;
	setTalkTarget( $player1 );
	idle_talk();
}

/*
=====================
character::path_talk_primary

forces character to say his primary talk anim to the player
=====================
*/
void character::path_talk_primary() {
	talkMode = CHAR_TALK_PRIMARY;
	setTalkTarget( $player1 );
	idle_talk();
}

/*
=====================
character::path_talk_secondary

forces character to say his secondary talk anim to the player
=====================
*/
void character::path_talk_secondary() {
	talkMode = CHAR_TALK_SECONDARY;
	setTalkTarget( $player1 );
	idle_talk();
}

/*
=====================
character::path_lookat
=====================
*/
void character::path_lookat() {
	string		dialog;
	string		anim;
	string		focus_entity;
	float		waitTime;
	entity		focus;
	float		blend_in;
	float		blend_out;
	
	stopMove();

	anim = current_path.getKey( "anim" );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );
	focus_entity = current_path.getKey( "focus" );
	focus = sys.getEntity( focus_entity );
	waitTime = current_path.getFloatKey( "wait" );

	if ( anim != "" ) {
		playCustomCycle( anim, blend_in );
	}

	if ( !waitTime ) {
		AI_ACTIVATED = false;
		while( !AI_ACTIVATED ) {
			if ( AI_TALK ) {
				cancelPathCommand();
				if ( anim != "" ) {
					animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
				}
				setState( "state_Idle" );
			}
			check_cower();
			lookAt( focus, 0.1 );
			waitFrame();
		}
	} else {
		waitTime += sys.getTime();
		AI_ACTIVATED = false;
		while( waitTime > sys.getTime() ) {
			if ( AI_ACTIVATED ) {
				break;
			}
			if ( AI_TALK ) {
				if ( anim != "" ) {
					animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
				}
				cancelPathCommand();
				setState( "state_Idle" );
			}
			check_cower();
			lookAt( focus, 0.1 );
			waitFrame();
		}
	}

	if ( anim != "" ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Idle", blend_out );
	}
}

/*
=====================
character::state_FollowAlternatePath
=====================
*/
void character::state_FollowAlternatePath() {
	endHeadAnim( 8 );

	idle_followPathEntities( current_path );
	setState( "state_Idle" );
}

/*
=====================
character::follow_alternate_path1
=====================
*/
void character::follow_alternate_path1() {
	current_path = getEntityKey( "alt_path1" );
	setState( "state_FollowAlternatePath" );
}

/*
=====================
character::follow_alternate_path2
=====================
*/
void character::follow_alternate_path2() {
	current_path = getEntityKey( "alt_path2" );
	setState( "state_FollowAlternatePath" );
}

/*
=====================
character::follow_alternate_path3
=====================
*/
void character::follow_alternate_path3() {
	current_path = getEntityKey( "alt_path3" );
	setState( "state_FollowAlternatePath" );
}

/*
=====================
character::disable_turning
=====================
*/
void character::disable_turning() {
	allow_turn = false;
}

/*
=====================
character::enable_turning
=====================
*/
void character::enable_turning() {
	allow_turn = true;
}

//@doomscript-blueprint begin 6
//@source 133C3DF7
//@catalog 0C260740
//@node C65EFFDA-0 40 40
//@node 08DB9F61-0 40 40
//@node 3E7FE349-0 330 40
//@node 2AD98E7D-0 40 40
//@node CAE16309-0 330 40
//@node D4813629-0 40 40
//@node E1BD90B9-0 330 40
//@node 8FFD7B8A-0 125 232
//@node 6C17C5E3-0 610 40
//@node 3AE6F289-0 170 145
//@node A038B1FE-0 -35 337
//@node 50EFD1B9-0 400 145
//@node C4E8238B-0 890 200
//@node 818F17C3-0 1170 40
//@node 780B6C49-0 1450 40
//@node F06D02B6-0 1245 324
//@node C1AEDF50-0 40 40
//@node 1EEA6B47-0 330 40
//@node DEB7E614-0 40 40
//@node 3320729E-0 330 40
//@node F7270A72-0 125 145
//@node 0392C5C3-0 -80 145
//@node D18989C6-0 -80 145
//@node E8C0F715-0 610 200
//@node A64F7BE2-0 385 305
//@node F54E8191-0 890 200
//@node 0689CC9D-0 685 305
//@node D1AA48E3-0 480 305
//@node CEF447D6-0 1170 360
//@node 85E4C110-0 1450 200
//@node 7BDCC6A2-0 1245 305
//@node 4E2D6DBF-0 1040 305
//@node 0C08EFD1-0 1730 360
//@node CFB05C53-0 2010 40
//@node 06C9096D-0 2290 40
//@node 7F2B1F4D-0 2570 40
//@node F52F91F0-0 2850 200
//@node BB083C1D-0 2645 305
//@node D809A23E-0 3130 360
//@node 9DCF83E5-0 2925 465
//@node 25BA42C2-0 2720 465
//@node 699D1991-0 3410 520
//@node 596083DC-0 3690 520
//@node 09EB90B3-0 3485 625
//@node 254E5E75-0 3970 520
//@node 9463F4F9-0 4530 520
//@node 292D9B41-0 4810 200
//@node 0A37BAD6-0 4605 305
//@node 38FC0AD5-0 5090 360
//@node 5FAAAE36-0 4885 465
//@node A6796A08-0 5370 520
//@node CA244A74-0 5650 360
//@node 0E81A62D-0 5445 465
//@node CD6F601B-0 5930 520
//@node 856DDBDB-0 40 40
//@node 217EADAB-0 330 40
//@node 553414AA-0 610 40
//@node B705AE70-0 890 40
//@node D06F3D8E-0 685 145
//@node 88AF01B6-0 480 145
//@node 1C61213E-0 480 145
//@node 2EBE6BE2-0 1170 200
//@node 1E71C659-0 965 305
//@node 21B7F216-0 1450 360
//@node B48B49C3-0 1225 465
//@node 38E43F7C-0 1730 360
//@node B4E3BA42-0 1525 465
//@node 8BA78760-0 1320 465
//@node B2506442-0 2010 520
//@node 0B96853D-0 2290 200
//@node AFADF50D-0 2570 40
//@node 8FD3AC4F-0 40 40
//@node 8655A8FB-0 330 40
//@node 671220B7-0 610 40
//@node 5B21CBE1-0 405 232
//@node AE0A0EF0-0 890 40
//@node 7F33DDD9-0 685 145
//@node CD152385-0 480 145
//@node 86CFEE0D-0 480 145
//@node 4C5A092D-0 1170 200
//@node C12521DD-0 1450 40
//@node 4725BC23-0 40 40
//@node 201E6227-0 330 40
//@node 7738A6F8-0 610 40
//@node 18D3323E-0 405 232
//@node B30E9461-0 200 232
//@node CF42B555-0 890 40
//@node 92B76B60-0 685 145
//@node C6EAEFB3-0 480 145
//@node 389F5A3F-0 480 145
//@node A3E5FB3C-0 480 229
//@node 570659EC-0 1170 200
//@node 74817D9E-0 945 305
//@node 4AEF26A0-0 1450 200
//@node C35D540A-0 1245 305
//@node 8964D506-0 1040 305
//@node D8738CEC-0 1730 360
//@node 33CDF479-0 2010 200
//@node AD431E71-0 2290 40
//@node DFDFBC3C-0 40 40
//@node 539240A6-0 330 40
//@node 68B6C33D-0 610 40
//@node 13CC4804-0 890 40
//@node 23697296-0 1170 40
//@node 704DE061-0 730 145
//@node BE071591-0 960 145
//@node B4885640-0 1450 200
//@node 8E3C46AC-0 1730 40
//@node 3C585EC2-0 2010 40
//@node D3FF4121-0 1805 145
//@node 33F7E212-0 1600 145
//@node C9D24F7F-0 1600 145
//@node 67EEDA55-0 2290 200
//@node 0608640B-0 2065 305
//@node DBBCAEDD-0 2570 200
//@node F13CD5FD-0 2365 305
//@node 52196B63-0 2160 305
//@node 41466A87-0 2850 360
//@node FC013D7C-0 3130 200
//@node 348091B0-0 2925 305
//@node 4674E391-0 2720 305
//@node EE1E88B8-0 3410 360
//@node E135FA63-0 3690 40
//@node 90827A09-0 40 40
//@node 37A1DBA5-0 330 40
//@node 2D8A5CE2-0 610 40
//@node 80598008-0 890 40
//@node BC76A33B-0 1170 40
//@node CEF75F57-0 730 145
//@node A33442C7-0 960 145
//@node B81A492B-0 1450 200
//@node 7D20F8C3-0 1730 40
//@node 767623E9-0 2010 40
//@node BF9DA317-0 1805 145
//@node 128B893E-0 1600 145
//@node 6EA1EB53-0 1600 145
//@node F5319802-0 2290 200
//@node 10AF4B52-0 2065 305
//@node AC5CCA86-0 2570 200
//@node F7ADA34B-0 2365 305
//@node E5E1699B-0 2160 305
//@node 9DA2D630-0 2850 360
//@node 9C91452D-0 3130 200
//@node DC2E46AF-0 2925 305
//@node 082244BE-0 2720 305
//@node E43BDDD5-0 3410 360
//@node 3222028C-0 3690 40
//@node 8D15DCD2-0 40 40
//@node C5B21F4A-0 330 40
//@node FDBAB018-0 610 40
//@node 935A34DB-0 890 40
//@node EBB6A0ED-0 685 232
//@node D770235C-0 480 232
//@node A0609D03-0 1170 40
//@node F9E9F874-0 730 145
//@node BF34D884-0 960 145
//@node 1D66C5D5-0 1450 200
//@node B5DB9E02-0 1730 200
//@node C5B21F4A-1 2010 40
//@node 6F20C7C2-0 2290 40
//@node D104C46D-0 40 40
//@node 9DD06DDD-0 330 40
//@node 744C3DE7-0 610 40
//@node 81FC426F-0 405 232
//@node FB2C14FC-0 890 40
//@node 463723ED-0 685 145
//@node 44973DD3-0 1170 200
//@node C6D121D4-0 40 40
//@node 860D013A-0 330 40
//@node 22E4D4B1-0 610 40
//@node A50B08E7-0 405 232
//@node CCE42047-0 890 40
//@node 35DE4D61-0 450 145
//@node 5A9029E5-0 245 337
//@node 0EDF8911-0 680 145
//@node DEA4A164-0 1170 200
//@node 28DDFA5F-0 1450 40
//@node 0C764EE7-0 1245 140
//@node 2668F5FA-0 1040 140
//@node E7C6484E-0 1730 40
//@node 20E822B6-0 1525 324
//@node E20D34C6-0 40 40
//@node 97F3BB1A-0 330 40
//@node 5740C261-0 105 145
//@node 51A09072-0 610 40
//@node 4885560F-0 405 140
//@node 2289998A-0 890 40
//@node C10AC54C-0 685 145
//@node 716DFB6A-0 1170 40
//@node 3D9D0FB9-0 965 145
//@node 9C4D5B60-0 1450 40
//@node 9014C6CD-0 1225 145
//@node 85818EAB-0 1020 245
//@node 803D8E54-0 815 245
//@node 0C8B1910-0 1730 40
//@node CF8064AD-0 1525 145
//@node 1D9EF5C0-0 2010 40
//@node 7B158EB0-0 1805 145
//@node 0969E1F2-0 2290 40
//@node 5268A256-0 2085 145
//@node 7221691D-0 2570 40
//@node 4CDC56F2-0 2365 145
//@node 969F7DA5-0 2850 40
//@node CC2769DC-0 2645 145
//@node DD97E236-0 3130 40
//@node C0708D86-0 2905 145
//@node EABD3370-0 3410 40
//@node 14C03AE1-0 3185 145
//@node 7D727837-0 2980 245
//@node 10CB2158-0 2775 245
//@node 4DC4D726-0 3690 40
//@node C72F731A-0 3465 145
//@node B70427F6-0 3260 245
//@node 8E0B701D-0 3055 245
//@node FA823219-0 3970 40
//@node C00DAA76-0 3765 145
//@node 42A18E64-0 4250 40
//@node A0560D0A-0 4045 145
//@node 51C0B6C8-0 4530 200
//@node 10B4B124-0 4325 305
//@node 3201920C-0 5090 200
//@node FC2C7E2E-0 4885 305
//@node C387EAB3-0 5370 40
//@node 88A82EFD-0 5650 40
//@node A70EAC4E-0 5425 145
//@node 6D44A059-0 5220 245
//@node BBBF3F70-0 5015 245
//@node 7F8BE440-0 5930 200
//@node D1146A05-0 6490 200
//@node CC82E676-0 40 40
//@node A512A3A5-0 330 40
//@node B82BA622-0 125 145
//@node 98CD56D4-0 610 200
//@node 065517A8-0 405 305
//@node BC91ADB6-0 890 200
//@node 0D89B050-0 685 305
//@node 6C32D20C-0 1170 360
//@node 2DE120AE-0 965 465
//@node F84239E5-0 760 465
//@node 7CAA464B-0 760 549
//@node DBD91699-0 1450 520
//@node C5D55D39-0 1730 520
//@node 6B1E1DE1-0 2010 360
//@node 9BA44F92-0 1805 465
//@node DF123D51-0 1600 465
//@node 5F253E9F-0 1600 549
//@node 5E7DAF12-0 40 40
//@node D71E9467-0 330 40
//@node 2782C6A7-0 105 145
//@node 3BB6A87D-0 -100 245
//@node 8E02B072-0 -305 245
//@node ECC05822-0 610 40
//@node 3E716467-0 385 145
//@node 14AE6260-0 890 40
//@node B3BC7B96-0 1170 40
//@node 1CA24972-0 965 145
//@node B1A873D8-0 1450 40
//@node 69FADFA9-0 1245 145
//@node EE4BE54D-0 1730 40
//@node F8B70D51-0 1525 145
//@node 7511CD68-0 2010 200
//@node B0300B07-0 1805 305
//@node 19DA7491-0 2290 360
//@node 95A33E60-0 2085 465
//@node 3DA8B493-0 1880 465
//@node B1A873D8-1 2570 360
//@node 7DC97E42-0 2365 465
//@node E29088D9-0 2850 200
//@node D0881C50-0 2645 305
//@node 6052FCDB-0 3130 360
//@node 703F0958-0 2905 465
//@node 498D3237-0 3410 520
//@node 2E3E732C-0 3205 625
//@node B2C13E85-0 3000 625
//@node 0ADA3293-0 3000 709
//@node 1ADF5046-0 3690 680
//@node 3638F5C2-0 3465 785
//@node 057BF7BA-0 3260 885
//@node 9E594003-0 3055 885
//@node 611DA31B-0 3055 963
//@node 29817B02-0 3970 680
//@node CDD6E516-0 3765 785
//@node F26D0FEC-0 3560 785
//@node 953C7D99-0 4250 840
//@node 8FFC6AB6-0 4530 520
//@node A63C9629-0 4325 625
//@node D895ADA1-0 4120 625
//@node E2C92B2F-0 4120 709
//@node A73E4AA1-0 4810 680
//@node 054D9AF1-0 4605 785
//@node AD92E2C8-0 4400 785
//@node 350292A8-0 5090 680
//@node 34BC30B6-0 5370 680
//@node 38D7C272-0 5165 780
//@node 0DF080E5-0 4960 780
//@node AFD604FC-0 5650 680
//@node 654E8140-0 5445 780
//@node 02FBBE2F-0 5240 780
//@node 8E388927-0 5445 872
//@node 85420D3C-0 5240 872
//@node 5BEEF03E-0 5240 950
//@node 7846BA13-0 5930 680
//@node 1BEFC46C-0 5725 785
//@node FBD32A16-0 6210 840
//@node F182E6A8-0 6490 680
//@node A133308C-0 6265 785
//@node AD4BCF58-0 6770 680
//@node 30AE6E0C-0 6565 780
//@node 3A840022-0 7050 200
//@node 28B8B022-0 40 40
//@node 0D1796BE-0 330 40
//@node F5B205FC-0 610 40
//@node 6DA458C5-0 405 145
//@node 130538DA-0 890 200
//@node 671202AC-0 1170 40
//@node 5D61C49E-0 1450 40
//@node ADBE02A4-0 1730 40
//@node 53A4BA5E-0 1505 145
//@node 773FDEA2-0 2010 200
//@node 40D4376A-0 2290 40
//@node F3F0D3EF-0 2570 40
//@node 942BFCAB-0 40 40
//@node 7504DE38-0 330 40
//@node AD8A7787-0 125 145
//@node 0C9F6E1D-0 -80 145
//@node F070A906-0 610 200
//@node A06D3847-0 385 305
//@node 74B9D5C5-0 890 360
//@node 54BA106D-0 1170 360
//@node B5A67E7C-0 1450 360
//@node 45E66980-0 40 40
//@node 9429B9A4-0 330 40
//@node BE4D69F7-0 610 40
//@node 461F7B71-0 890 40
//@node B5E16099-0 1170 40
//@node FF90094D-0 40 40
//@node 15E31207-0 330 40
//@node ACBA7E30-0 610 40
//@node 483938B5-0 405 145
//@node 588D9920-0 890 40
//@node 3F3B78A4-0 1170 40
//@node 8964F88E-0 40 40
//@node 079460E2-0 330 40
//@node 1EE5CF9E-0 610 40
//@node EB30F46A-0 405 145
//@node 8C83D689-0 890 40
//@node C69C8713-0 1170 40
//@node 412E6CA2-0 40 40
//@node 57A4F0B2-0 330 40
//@node 7D0A0ECA-0 610 40
//@node BAEF3116-0 405 145
//@node B185B959-0 890 40
//@node 44C8DCA3-0 1170 40
//@node FE0459B0-0 40 40
//@node B97AF407-0 330 40
//@node 54AD5EFC-0 105 145
//@node 9983D951-0 610 40
//@node 82A1E410-0 385 145
//@node 2E73D5AD-0 890 40
//@node B41A0C56-0 665 145
//@node D051B568-0 460 245
//@node 42627E56-0 1170 40
//@node 346918E9-0 945 145
//@node C4D0C96B-0 1450 40
//@node 1B22B8EB-0 1225 145
//@node 2689ED83-0 1020 245
//@node 191141E5-0 815 245
//@node 16113D2C-0 815 323
//@node 3F90A9EA-0 1730 40
//@node 30C49311-0 1525 145
//@node 843938C1-0 2010 200
//@node 164D5448-0 2290 200
//@node FFF89DE8-0 2085 305
//@node 843938C1-1 2570 200
//@node 1F604BB3-0 2850 40
//@node 17D1A951-0 40 40
//@node 3984CCDE-0 330 40
//@node F7602A38-0 610 40
//@node 89BDC730-0 40 40
//@node 5320001A-0 330 40
//@node A2B466DF-0 610 40
//@node FB20063C-0 890 40
//@node 1B79335D-0 40 40
//@node 2ED521E6-0 330 40
//@node C0F1A0CB-0 40 40
//@node E619EE95-0 330 40
//@node 5D8D81E8-0 125 324
//@node 0F942212-0 40 40
//@node B7CB56F5-0 330 40
//@node 61B2ACAA-0 610 40
//@node AAED042F-0 890 40
//@node D2A0993E-0 1170 40
//@node C107B116-0 1450 40
//@node 84A6411A-0 1225 145
//@node B7CB56F5-1 1730 200
//@node 390B0B4A-0 2010 200
//@node 05E95E4E-0 40 40
//@node 80209A8D-0 330 40
//@node A8B4EC6C-0 105 145
//@node F9D2DC02-0 610 200
//@node 648C650D-0 890 40
//@node 41662DDB-0 1170 40
//@node 93AB1756-0 1450 40
//@node 80209A8D-1 1730 40
//@node 1B3E76AF-0 1505 145
//@node 53B52004-0 2010 200
//@node 9232BC5D-0 40 40
//@node 98E65203-0 330 40
//@node 004B30EE-0 610 40
//@node 5B4C8A72-0 890 40
//@node F3504E07-0 1170 40
//@node 50FE6F83-0 1450 40
//@node 8671C644-0 1225 145
//@node 060C59BA-0 1730 40
//@node CBA5923D-0 1525 145
//@node 60F3759C-0 1320 145
//@node 449E7B97-0 2010 200
//@node 536B2960-0 2290 200
//@node 945B821A-0 2085 392
//@node 3C144E7A-0 2570 200
//@node AF829032-0 2345 305
//@node A17F38F4-0 2140 497
//@node FCA54FCE-0 2850 200
//@node ECB9D21A-0 2625 305
//@node B3A7E906-0 3130 200
//@node 1588D5A4-0 2925 305
//@node F4C6CC71-0 2720 305
//@node 3D0353AF-0 3410 360
//@node 0F14FB59-0 3970 360
//@node B957254D-0 3745 465
//@node 6B81CF5F-0 3540 657
//@node D0FBCEFB-0 4250 360
//@node DD384EF4-0 4045 465
//@node 394830A3-0 3840 465
//@node CC0DDCED-0 3840 549
//@node D9FFEB82-0 4530 520
//@node 384F4EE5-0 4325 712
//@node CA31624D-0 5090 520
//@node C4B58FFB-0 4885 712
//@node 8A70C205-0 5370 200
//@node 46E14B02-0 5930 200
//@node CBCACDC9-0 5725 305
//@node 004B30EE-1 6210 360
//@node FCA54FCE-1 6490 200
//@node 728875AF-0 6265 305
//@node B3A7E906-1 6770 200
//@node 80337525-0 6565 305
//@node 660ACB70-0 6360 305
//@node 0A297772-0 7050 360
//@node 14681C6C-0 7610 360
//@node F06B60A4-0 7890 200
//@node 425FC1F7-0 40 40
//@node B0F649AF-0 330 40
//@node 5B8C2DAD-0 105 145
//@node 017B4F1B-0 610 40
//@node B2235299-0 405 145
//@node 0F628B97-0 890 40
//@node FC776819-0 685 145
//@node 53DAEAE8-0 1170 40
//@node 1766F26D-0 965 145
//@node BED133A4-0 1450 40
//@node 48D97E19-0 1245 145
//@node 80F74589-0 1730 40
//@node FEE6FC6A-0 2010 40
//@node 58B4C163-0 1785 145
//@node 612392C3-0 2290 200
//@node B7D60BE8-0 2570 40
//@node 099B621F-0 2345 145
//@node 93F0ECE5-0 2850 40
//@node 19A10149-0 2625 145
//@node B9D9F611-0 3130 40
//@node E1503BB4-0 2905 145
//@node 5FD9DC7C-0 3410 40
//@node DF69E2D0-0 3205 145
//@node 0F4E5719-0 3000 145
//@node 4F14AA2B-0 3690 200
//@node 473DE49E-0 3485 392
//@node 67B36441-0 3970 200
//@node 3C61A2AC-0 4250 200
//@node 06521C15-0 4045 300
//@node BE56FB50-0 4530 200
//@node 0728C60D-0 4810 200
//@node 4B53D57E-0 5090 200
//@node 12C7D584-0 5370 200
//@node A5253F7A-0 5165 300
//@node 9ACAF06D-0 5650 200
//@node 6A9FE45B-0 5445 305
//@node 1C3F3B54-0 5240 305
//@node 67B36441-1 5930 200
//@node 258495F5-0 6210 200
//@node 501F059E-0 6005 305
//@node 3C61A2AC-1 6490 200
//@node F10DB0B4-0 6285 300
//@node BE56FB50-1 6770 200
//@node 0728C60D-1 7050 200
//@node A8CAA113-0 7330 200
//@node 18B48EFF-0 7610 200
//@node C2D9DF88-0 7385 305
//@node 8E60F3FC-0 7890 200
//@node 228935F7-0 8170 200
//@node 6BCEB82C-0 7965 305
//@node 48906A52-0 7760 305
//@node 320BC50D-0 8450 360
//@node 593FAA7F-0 8730 360
//@node 9CD255AB-0 9010 360
//@node 37791C26-0 8805 465
//@node CC2D84D7-0 8600 465
//@node D024D15E-0 9290 360
//@node 431C5C04-0 9570 360
//@node 09B95160-0 9850 360
//@node 2E7D2AA4-0 9645 465
//@node 45B011D8-0 9440 465
//@node 9B055883-0 10130 360
//@node 6458A6B9-0 10410 360
//@node 00F5EF8C-0 10970 360
//@node 95B03E12-0 11250 360
//@node 4B53D57E-1 11530 200
//@node 39946D66-0 11810 200
//@node 0779D1AE-0 12090 200
//@node 84B263A0-0 11885 300
//@node C4C79351-0 11680 300
//@node 76678293-0 12370 200
//@node 07BDA626-0 12165 300
//@node 5089C24D-0 12650 200
//@node 043D5DA9-0 12445 305
//@node 67B36441-2 12930 200
//@node 258495F5-1 13210 200
//@node 49D61735-0 13005 305
//@node 3C61A2AC-2 13490 200
//@node 40B190DB-0 13285 300
//@node 2C391AF9-0 13770 200
//@node A1F669D2-0 13565 305
//@node B0A9F4B0-0 13360 305
//@node 258495F5-2 14050 360
//@node FA9AA4F0-0 13845 465
//@node BE56FB50-2 14330 360
//@node 0728C60D-2 14610 200
//@node 4B53D57E-2 14890 200
//@node 9F1D32C4-0 15170 40
//@node 016C8CD1-0 14945 145
//@node 258495F5-3 15450 200
//@node F0D23A07-0 15245 305
//@node 3C61A2AC-3 15730 200
//@node AE4D6AD2-0 15525 300
//@node BAC8DA71-0 16010 40
//@node C3D9E191-0 15785 145
//@node 75091559-0 16290 40
//@node 4A1A760F-0 16085 145
//@node 15659A70-0 15880 145
//@node 4B715445-0 16570 200
//@node 631C2327-0 16365 300
//@node C406FB2A-0 16850 40
//@node 10FE1929-0 16625 145
//@node CCCC75C2-0 17130 200
//@node D4A933F6-0 17690 200
//@node 42F3ABC0-0 40 40
//@node 0E0CE2BA-0 330 40
//@node 3454C53B-0 105 145
//@node 064B71C4-0 610 40
//@node B0A5A442-0 405 145
//@node 14CE4985-0 200 145
//@node 264CDDF5-0 890 200
//@node 6AC8117A-0 685 300
//@node 819D1E39-0 1170 40
//@node 8EED849C-0 965 145
//@node 23EEFFC4-0 760 145
//@node 5174577F-0 1450 200
//@node FFC70DD0-0 1730 200
//@node BCC47135-0 2010 40
//@node 7895F3BB-0 2290 40
//@node 1D83708D-0 2570 40
//@node B9C6763F-0 2365 145
//@node 160BAFFD-0 2850 40
//@node AF805C84-0 40 40
//@node 864D7071-0 330 40
//@node 12793AA6-0 125 145
//@node 3385F7A6-0 610 200
//@node 626CA4B7-0 890 40
//@node B5574BF3-0 685 145
//@node 8F7E85B7-0 1170 40
//@node 1E5339D9-0 965 145
//@node 3E92925B-0 1450 200
//@node C0F80F7A-0 1245 305
//@node 72EA0489-0 1730 360
//@node A7540995-0 2010 360
//@node 203F47D3-0 2290 200
//@node A0574B46-0 2085 305
//@node A0668224-0 2570 360
//@node 2FDAC9AE-0 2365 465
//@node 6E05F38A-0 2160 465
//@node 6348E77B-0 2850 520
//@node 7F9181D0-0 2625 625
//@node C315A0AD-0 3130 360
//@node D745A6A9-0 2925 465
//@node 27E5E61B-0 3410 520
//@node F20685B0-0 3205 620
//@node E449C40A-0 3690 520
//@node A4BF6388-0 3465 625
//@node 4739DD17-0 3970 680
//@node 268C851A-0 3765 785
//@node A7540995-1 4250 520
//@node EC193795-0 4530 200
//@node 12A2F187-0 40 40
//@node BFE43BE6-0 330 40
//@node 349DFCAF-0 610 40
//@node 8BC91C06-0 890 40
//@node A97B330D-0 665 145
//@node 89C97413-0 1170 200
//@node A4D57255-0 1450 40
//@node 2519EA4D-0 40 40
//@node A5DDA538-0 330 40
//@node 39435017-0 610 40
//@node E189C882-0 405 145
//@node 2D8BFFD2-0 200 145
//@node 34AF1030-0 890 200
//@node 1574FA17-0 1170 200
//@node D4577FAD-0 965 305
//@node 941D0135-0 1450 360
//@node 949BD95F-0 1730 200
//@node D038CD01-0 40 40
//@node 0E60477D-0 330 40
//@node 4C14A9AB-0 105 145
//@node 14A96826-0 610 40
//@node 4B0F7312-0 385 145
//@node C0BF426C-0 890 40
//@node CA5A5505-0 665 145
//@node F32F4F4C-0 1170 40
//@node F7FC9146-0 1450 40
//@node 702871D1-0 1245 145
//@node 19B8E3EE-0 1040 145
//@node 19D73D9A-0 1040 229
//@node D4D2D913-0 1730 200
//@node CEB2420D-0 1525 300
//@node E001B24E-0 2010 200
//@node 67641652-0 2290 200
//@node 91277705-0 1850 305
//@node 0A123CF5-0 2080 305
//@node 17A3A295-0 2570 360
//@node C725802F-0 2365 465
//@node A2B911CD-0 2160 465
//@node 7D7378E4-0 2850 520
//@node 5333ABEB-0 3130 360
//@node F4FAF53C-0 2925 460
//@node 5A2796B3-0 3410 360
//@node D093FF3D-0 3690 40
//@node BE9CB8A6-0 3970 40
//@node B27E07F6-0 3745 145
//@node EC2DBD9F-0 3540 245
//@node 4E4F724A-0 3335 245
//@node 39A4B189-0 4250 40
//@node 87DE3F31-0 4045 145
//@node AD333FAB-0 3840 145
//@node FD94C2A4-0 4530 200
//@node CCE733E8-0 4305 305
//@node BBE64C70-0 4810 200
//@node AE3366BE-0 4585 305
//@node C434BB86-0 5090 200
//@node CB29F4E2-0 4865 305
//@node 008F2F21-0 4660 497
//@node 0C23898D-0 5370 200
//@node DDE56F75-0 5165 305
//@node 73F291A3-0 5650 200
//@node C3E128BD-0 5445 305
//@node 95E4636A-0 5240 305
//@node C61A16C7-0 5930 200
//@node 31B7E9C9-0 5705 305
//@node 23465B25-0 6210 200
//@node 4E09709C-0 5985 305
//@node 16610E00-0 6490 200
//@node 03BCC4FF-0 6265 305
//@node 96F1414D-0 6060 497
//@node 3AC65765-0 6770 200
//@node E9A9D2D8-0 6565 305
//@node E1F9D393-0 7050 200
//@node DD8E7A4F-0 6845 305
//@node 9A6E4768-0 6640 305
//@node 1800E4E6-0 7330 200
//@node 3E900014-0 7105 305
//@node 74468EA6-0 7610 200
//@node 24B1DC62-0 7385 305
//@node F4770323-0 7890 200
//@node 503E5EC6-0 7665 305
//@node BA998F36-0 7460 405
//@node 431EFA17-0 7255 405
//@node 4BBAF94A-0 7460 497
//@node 27EE0428-0 8170 200
//@node 0D680EA5-0 7965 305
//@node 3BF7E55A-0 7760 305
//@node 512EF230-0 8450 200
//@node 924053AB-0 8245 305
//@node A503B93B-0 8040 305
//@node 58A30B49-0 8730 360
//@node 40014702-0 8525 465
//@node E8016ED8-0 9010 40
//@node F7B198A5-0 8570 145
//@node CD0D747D-0 8365 245
//@node 2D02C9CE-0 8365 337
//@node BFD52BB5-0 8800 145
//@node 2E2ED9F5-0 9290 200
//@node ADA903C0-0 9085 305
//@node E5FDE691-0 8880 305
//@node 3588B2EE-0 8880 389
//@node 7E9991FF-0 9570 360
//@node 7D2591E3-0 9850 360
//@node 54FC53B9-0 9645 465
//@node 3586A199-0 10130 520
//@node 5A764FCC-0 10410 360
//@node 7D7378E4-1 10690 200
//@node 8D09BD5A-0 10970 200
//@node B9F5EAC0-0 10765 305
//@node 86C6D46D-0 10560 305
//@node D04C7FFB-0 10560 389
//@node 5333ABEB-1 11250 360
//@node A390ED85-0 11045 460
//@node D4D2D913-1 11810 360
//@node F4EAB344-0 11605 460
//@node 5A2796B3-1 12090 200
//@node 7C4753F0-0 12370 40
//@node 2B556D23-0 12165 140
//@node 422A41BB-0 12650 40
//@node CA46C7A4-0 12930 40
//@node CC261693-0 12705 145
//@node 74619A62-0 12500 245
//@node 1D08CCA5-0 12295 245
//@node 961589CF-0 13210 40
//@node B83B8211-0 12985 145
//@node 3A0CFF66-0 13490 40
//@node 28AE77C1-0 13285 145
//@node A2D2D61B-0 13080 145
//@node 69CEAF30-0 13080 229
//@node 77377B14-0 13770 40
//@node 00852491-0 13565 145
//@node 0DDE5D0D-0 13360 145
//@node C49137CB-0 13360 229
//@node BE577E69-0 13360 313
//@node C97FD29C-0 13360 397
//@node 7D7378E4-2 14050 200
//@node 8D09BD5A-1 14330 200
//@node D04D1BE1-0 14125 305
//@node 407FE02E-0 13920 305
//@node 62DD3ADA-0 13920 389
//@node 5333ABEB-2 14610 360
//@node 61FF0236-0 14405 460
//@node D4D2D913-2 15170 360
//@node 60480C6F-0 14965 460
//@node A04C2820-0 15450 200
//@node 63087F68-0 15245 305
//@node D4F4CFFA-0 15730 360
//@node 1FEC16EE-0 16010 360
//@node DFF79E9B-0 16290 200
//@node 64236F9F-0 16085 305
//@node A6EB90F9-0 16570 360
//@node 5A2796B3-2 16850 200
//@node 961589CF-1 17130 200
//@node 307FF196-0 16905 305
//@node DE7AA87E-0 17410 40
//@node EDBE47C0-0 17690 40
//@node D4F4CFFA-1 17970 40
//@node 4F2C9B92-0 40 40
//@node 47DF315B-0 330 40
//@node 7A7053D1-0 610 40
//@node B68312A1-0 405 145
//@node 56DA3E39-0 890 200
//@node 291B3CC8-0 1170 200
//@node C98EB35A-0 965 300
//@node 78B1DA51-0 1450 200
//@node DA6A3B92-0 1245 305
//@node 12A0914B-0 1730 360
//@node CC0510ED-0 40 40
//@node CD441B38-0 330 40
//@node 91FD45EB-0 610 40
//@node 4CEF8D3F-0 385 145
//@node F822983E-0 890 40
//@node 9199CAB5-0 665 145
//@node 524CC771-0 1170 40
//@node 638D3FB1-0 730 145
//@node 52697800-0 525 245
//@node 2DC725E1-0 960 145
//@node AAC8DD1F-0 1450 200
//@node ABB9E78B-0 1245 300
//@node BF280D7B-0 1040 300
//@node 066EEDC4-0 1040 378
//@node 00BC64DC-0 1040 456
//@node 14067DA2-0 1730 200
//@node B5EEFA64-0 2010 40
//@node B7533455-0 1785 145
//@node E7213D15-0 2290 40
//@node F91BE671-0 2065 145
//@node BDF1C743-0 1860 245
//@node 5365DA80-0 1655 245
//@node A6B8A754-0 2570 200
//@node AAA94A79-0 2365 305
//@node A7808D50-0 2850 40
//@node 876086C2-0 2645 145
//@node B5CAE547-0 2440 145
//@node 3D6B1D1B-0 2440 229
//@node CD54F234-0 3130 200
//@node 207C9EBD-0 3410 40
//@node 87811E1D-0 3205 140
//@node 1BAABC80-0 3690 40
//@node B4E8EC4C-0 3485 145
//@node 8E270C9B-0 3970 200
//@node 775555A8-0 4250 200
//@node 9843E286-0 4530 40
//@node A3DEFBBD-0 40 40
//@node 69579C3E-0 330 40
//@node 0BF92C75-0 105 145
//@node C86CB018-0 610 40
//@node 7D26FC90-0 405 145
//@node 3AC7BD49-0 200 145
//@node B41D1C97-0 890 200
//@node D54D186F-0 665 305
//@node 858DD99A-0 460 405
//@node A48AFC4C-0 1170 200
//@node 669EC192-0 965 305
//@node FAB9708F-0 1450 360
//@node C3DB1718-0 1730 40
//@node 457F3E51-0 1525 145
//@node 8EB6BE98-0 2010 40
//@node 46565665-0 1805 145
//@node 60C5C8CC-0 2290 40
//@node D46F17CB-0 2085 145
//@node 0594D3A5-0 2570 200
//@node 830D3222-0 2850 40
//@node 94F9A87F-0 2645 145
//@node 9277F0AA-0 40 40
//@node E8D41C47-0 330 40
//@node 6A1129B3-0 125 145
//@node FAD6ACE7-0 610 200
//@node 185D54D5-0 890 40
//@node ED2761C1-0 685 145
//@node 3140F627-0 1170 40
//@node AFBB3A50-0 965 145
//@node A45ED684-0 1450 200
//@node EBBF6AA7-0 1730 40
//@node D99F266E-0 1525 145
//@node 524A5194-0 40 40
//@node 35D1C0E5-0 330 40
//@node ECC88FCF-0 125 145
//@node 0F005CE2-0 610 200
//@node 2678FBE5-0 890 40
//@node E7E6E6FF-0 685 145
//@node F8D8CCB0-0 480 145
//@node CA3D88BD-0 1170 200
//@node 432117E4-0 945 305
//@node 46C9FCFF-0 1450 200
//@node EC849D55-0 1245 305
//@node FAF09194-0 1040 305
//@node 0F005CE2-1 1730 200
//@node D46AE38F-0 2010 40
//@node 2EAF89F7-0 1805 145
//@node 3C06DA82-0 2290 40
//@node 758C798A-0 2085 145
//@node 39341C54-0 1880 145
//@node 0F005CE2-2 2570 200
//@node 20DBCF2D-0 2850 40
//@node 65318F59-0 2625 145
//@node 9A61F762-0 3130 40
//@node FF947E73-0 2905 145
//@node 85362C14-0 2700 245
//@node 78D0358A-0 3410 40
//@node 613ED19E-0 3205 140
//@node FFC6D81D-0 3690 40
//@node 0770B266-0 3485 145
//@node 1C50DDB4-0 3970 200
//@node 18CF17BB-0 3745 305
//@node 5AA857D8-0 3540 405
//@node 2E445141-0 4250 200
//@node 277AD693-0 4025 305
//@node 2AB21DDC-0 3820 405
//@node 0263C107-0 3615 405
//@node A1CD3CEA-0 3615 483
//@node 838185B2-0 4530 200
//@node D7F2105C-0 4305 305
//@node 3784674A-0 4100 405
//@node 11F296D3-0 4810 360
//@node E35F9119-0 5090 40
//@node 460AB768-0 4885 140
//@node E96EAE86-0 5370 40
//@node 1BF20E20-0 5165 145
//@node 0F005CE2-3 5650 200
//@node B8B01D3F-0 5930 40
//@node A49E24DA-0 5725 140
//@node B3395AA4-0 6210 40
//@node FC0E6759-0 6005 145
//@node F1C3ED7D-0 5800 145
//@node C0B70C93-0 6490 200
//@node 31D5E6B3-0 6770 200
//@node 3835DCA0-0 6565 305
//@node 2CB9FE81-0 7050 360
//@node 1A2FCDC4-0 7330 200
//@node 8F5AA760-0 7610 40
//@node 679EF520-0 7405 140
//@node CB218C15-0 7890 40
//@node 0607EA31-0 7665 145
//@node E7BA8BE4-0 8170 200
//@node 1DB8E2C8-0 7965 300
//@node B3395AA4-1 8450 200
//@node D65AE702-0 8245 305
//@node BDDAD2FC-0 8040 305
//@node C0B70C93-1 8730 360
//@node 31D5E6B3-1 9010 360
//@node 358F58E7-0 8805 465
//@node 2CB9FE81-1 9290 520
//@node 1A2FCDC4-1 9570 360
//@node B10DD74F-0 9850 40
//@node 331CC628-0 9645 140
//@node B3395AA4-2 10130 40
//@node C8B46FBB-0 9925 145
//@node B7115B9B-0 9720 145
//@node C0B70C93-2 10410 200
//@node 31D5E6B3-2 10690 200
//@node C287348A-0 10485 305
//@node 2CB9FE81-2 10970 360
//@node 1A2FCDC4-2 11250 200
//@node 08FCE3CB-0 11530 40
//@node 79389BDD-0 11810 40
//@node 78F99873-0 12090 40
//@node 04904FCC-0 40 40
//@node E7019702-0 330 40
//@node 3C0F9749-0 125 145
//@node 2D6FF24E-0 610 200
//@node 70C35494-0 405 305
//@node 3930636A-0 890 360
//@node C1451876-0 665 465
//@node 9CE98001-0 1170 360
//@node 36017D1B-0 965 465
//@node 5DD98E2A-0 1450 520
//@node E75D1E0B-0 1730 520
//@node 0A1CBF71-0 2010 360
//@node DF8FD53F-0 1785 465
//@node 3FBAF462-0 2290 360
//@node 9BC26FF1-0 2570 360
//@node 6730A58F-0 2850 360
//@node 2DA237AF-0 2645 465
//@node B3737E3A-0 3130 520
//@node 90C4C511-0 2905 625
//@node 0D550B94-0 3410 520
//@node 7CD0FDF1-0 3205 625
//@node C5D5A320-0 3690 520
//@node FABE9D68-0 3485 625
//@node DD59FC2B-0 3280 625
//@node 255620B7-0 3970 680
//@node C9178A0D-0 4250 680
//@node 43F11C83-0 4045 785
//@node B9AE0611-0 4530 840
//@node EDE6E57F-0 4810 680
//@node B77F4895-0 4605 785
//@node DAB29CCA-0 4400 785
//@node B9AE0611-1 5090 840
//@node 9BC26FF1-1 5370 680
//@node 5B7256F7-0 5650 520
//@node A19C1F30-0 5930 520
//@node B826E3CC-0 5725 625
//@node B01977DE-0 6210 680
//@node 4B5EE9C7-0 6490 520
//@node A0F1AE81-0 6285 625
//@node 3D3B3FB5-0 6770 680
//@node 37C1DB88-0 7050 520
//@node E75D1E0B-1 7330 200
//@node DB545D41-0 7610 40
//@node B926D7BA-0 7405 145
//@node 2D961AD8-0 7890 40
//@node 2C1A00E6-0 7685 145
//@node 3930636A-1 8170 200
//@node 2C492B29-0 7945 305
//@node 405967E5-0 8450 200
//@node 4DF1866C-0 8245 305
//@node 9EC2A619-0 8730 200
//@node D63A5185-0 8525 305
//@node 6CF130F0-0 9010 360
//@node B908882C-0 8805 465
//@node B84D6CFC-0 8600 465
//@node 01661FD4-0 8600 549
//@node B9AE0611-2 9290 520
//@node A137855E-0 9570 360
//@node 704029AF-0 9365 465
//@node 5DD98E2A-1 9850 360
//@node B9AE0611-3 10130 360
//@node 0A1CBF71-1 10410 200
//@node BCE64570-0 10185 305
//@node 3FBAF462-1 10690 200
//@node 9BC26FF1-2 10970 200
//@node 97331BC8-0 11250 200
//@node 1AF4E789-0 11025 305
//@node 37C1DB88-1 11530 200
//@node 9AE54738-0 11810 200
//@node A0E27F0D-0 11370 305
//@node B55C1026-0 11165 405
//@node 06F9961D-0 11600 305
//@node 5B7256F7-1 12090 360
//@node A1C82B78-0 12370 360
//@node 5C465B25-0 12165 460
//@node 37C1DB88-2 12650 360
//@node 2FE55164-0 12930 200
//@node 9EC2A619-1 13210 200
//@node 149655BA-0 13005 305
//@node 09008F04-0 13490 360
//@node C7ACC0EB-0 13770 360
//@node FDA1BFAF-0 14050 360
//@node ED34DCD0-0 14330 360
//@node FCD398FD-0 14125 465
//@node 8991BA58-0 14890 360
//@node 5FEB99FB-0 14685 465
//@node C4CB30CB-0 15170 200
//@node DD652F92-0 14965 305
//@node 1688674E-0 15450 200
//@node D8404238-0 15245 305
//@node F73E9BCE-0 15040 305
//@node A4BC1990-0 15040 389
//@node 99913D65-0 15040 473
//@node 5B7256F7-2 15730 360
//@node A1C82B78-1 16010 360
//@node 73F96E80-0 15805 460
//@node B3737E3A-1 16290 360
//@node 4E2CDD52-0 16065 465
//@node 0D550B94-1 16570 360
//@node 0E4D38AE-0 16365 465
//@node F4B73306-0 16850 360
//@node E15A3EE2-0 16645 465
//@node 8C0C8FD3-0 16440 465
//@node 09708222-0 17130 520
//@node 33B2BEAF-0 16925 625
//@node 47C8099D-0 16720 625
//@node B9AE0611-4 17130 680
//@node A19C1F30-1 17690 520
//@node 2B790B1F-0 17485 625
//@node E67BC55D-0 17970 680
//@node 06410325-0 17745 785
//@node F9887522-0 18250 840
//@node 5A6452EF-0 18045 945
//@node C4CB30CB-1 18530 840
//@node F7D324F1-0 18325 945
//@node 255620B7-1 19090 520
//@node 4F4DB32B-0 19370 520
//@node BEBFE8BB-0 19165 625
//@node F13D83F3-0 18960 625
//@node 9F387429-0 19650 680
//@node 86F5B948-0 19445 785
//@node ECC0CC25-0 19240 785
//@node 8FA5E9BF-0 19240 869
//@node B9AE0611-5 19370 840
//@node 1CDB68D0-0 20210 680
//@node 1CA7FDB0-0 20005 785
//@node 44665E2D-0 19800 785
//@node B9AE0611-6 19930 680
//@node A8191CC6-0 20770 520
//@node 9B321A6F-0 20565 625
//@node 0363775B-0 20360 625
//@node 5A787EE6-0 20360 709
//@node B9AE0611-7 20490 680
//@node 2D6FF24E-1 21330 520
//@node 96F82593-0 21125 625
//@node A19C1F30-2 21610 680
//@node C783555E-0 21405 785
//@node E67BC55D-1 21890 840
//@node E9E092BE-0 21665 945
//@node F9887522-1 22170 1000
//@node 0B43A6BE-0 21965 1105
//@node C4CB30CB-2 22450 1000
//@node 76F1ADB4-0 22245 1105
//@node 9BC26FF1-3 22730 520
//@node 4B5EE9C7-1 23010 360
//@node 66F22172-0 22805 465
//@node 3D3B3FB5-1 23290 520
//@node 37C1DB88-3 23570 360
//@node 255620B7-2 23850 200
//@node 6595EBC9-0 40 40
//@node A635C614-0 330 40
//@node 3CC0860C-0 105 145
//@node BDC733B5-0 -100 245
//@node 434BD7C4-0 -305 245
//@node D1E42A7A-0 610 40
//@node 83331AD7-0 385 145
//@node 12513141-0 890 40
//@node C818DA3A-0 685 140
//@node D6FD36B3-0 1170 40
//@node BA4FA363-0 1450 40
//@node 6EF01686-0 1245 145
//@node DBC18E50-0 1040 145
//@node 80B351A4-0 1040 229
//@node BF5218E4-0 1730 200
//@node 33CD2D37-0 2010 200
//@node 12513141-1 2290 200
//@node 8F02DFCF-0 2085 300
//@node D6FD36B3-1 2570 200
//@node E7750B86-0 2850 40
//@node BECE1F3B-0 2645 145
//@node 1E5C24CE-0 3130 40
//@node 341CD1B6-0 2925 145
//@node 2A842D18-0 3410 40
//@node 2A6E9C42-0 3205 145
//@node 0F42073B-0 3690 200
//@node 0613F188-0 3970 200
//@node 979FD537-0 4250 40
//@node 16BB32F5-0 4045 145
//@node 49A11EB6-0 4530 200
//@node AD8074CF-0 4325 300
//@node 7CF765CD-0 4120 300
//@node D6FD36B3-2 4810 200
//@node DE7BEA89-0 40 40
//@node 84E21248-0 330 40
//@node C235C222-0 105 145
//@node B3831716-0 610 40
//@node AC08D5CA-0 385 145
//@node 7E0EF84C-0 180 245
//@node C1EF7E73-0 -25 245
//@node 895852DA-0 890 40
//@node 3BC9B7FD-0 665 145
//@node 785AD4DC-0 460 245
//@node 0E0657AF-0 255 245
//@node 02818DBB-0 1170 40
//@node 303D2477-0 965 145
//@node 96E3F38D-0 760 145
//@node E568D850-0 1450 200
//@node 8AF7C2A3-0 1225 305
//@node 5AF21E7F-0 1730 200
//@node 2715806A-0 1525 300
//@node 0A90D5EA-0 2010 200
//@node A691601F-0 1570 305
//@node C077C34F-0 1800 305
//@node FAF799AC-0 2290 360
//@node 9B379E5B-0 2570 360
//@node 36E58FA9-0 2850 40
//@node 4ECC0B54-0 2625 145
//@node 6897A3F0-0 3130 200
//@node 07DEA3CC-0 2905 305
//@node 97C9FA2B-0 2700 405
//@node 8D383AA7-0 2700 497
//@node 384AC793-0 3410 200
//@node 7F09BDF6-0 2970 305
//@node B7524F34-0 2765 405
//@node 8E3990C4-0 2765 497
//@node 437B4246-0 3200 305
//@node FAF799AC-1 3690 360
//@node 444D06B8-0 3970 360
//@node 9DAF0FB4-0 3765 465
//@node 7F1CAB49-0 4250 520
//@node 8C82A8BA-0 4045 620
//@node 74B3AD80-0 4530 520
//@node 9FAF1AB6-0 4325 620
//@node 6B34A512-0 4120 620
//@node 6DEDC933-0 4810 520
//@node F722D310-0 5090 520
//@node 9B379E5B-1 5370 360
//@node 7F1CAB49-1 5650 200
//@node 3853AF31-0 5445 300
//@node 4D82A78C-0 6210 200
//@node 422DFD96-0 6005 300
//@node 172F8142-0 6005 392
//@node 0E1E743E-0 6005 484
//@node 4F068411-0 6490 200
//@node B7AE66F2-0 6265 305
//@node FAF799AC-2 6770 360
//@node 444D06B8-1 7050 360
//@node 7A3D303B-0 6845 465
//@node 8632790C-0 7330 520
//@node 74B3AD80-1 7610 520
//@node A724831B-0 7405 620
//@node 2FA50DC9-0 7200 620
//@node 6DEDC933-1 7890 520
//@node F722D310-1 8170 520
//@node 9B379E5B-2 8450 360
//@node F28821C3-0 40 40
//@node 650951EC-0 330 40
//@node F18A031A-0 105 145
//@node A6A17ABA-0 610 40
//@node 8E6766A7-0 385 145
//@node 5649B59F-0 180 245
//@node 1BA80E0A-0 -25 245
//@node 5AF561FE-0 890 40
//@node 648EBB7C-0 665 145
//@node 5BD780A5-0 460 245
//@node 867921DC-0 255 245
//@node A875CC0C-0 1170 40
//@node F800FF9C-0 945 145
//@node E8F46C1B-0 1450 40
//@node F76BB7C5-0 1245 145
//@node 6EBA15E5-0 1730 40
//@node 38B7FF0A-0 1525 145
//@node A003AC06-0 1320 145
//@node 868FDDE4-0 2010 200
//@node 01C5E9BF-0 1785 305
//@node A74C4DD9-0 2290 200
//@node E1901125-0 2085 300
//@node 7DEFC9B0-0 2570 200
//@node 8253625A-0 2130 305
//@node 333661AA-0 2360 305
//@node A07C1756-0 2850 360
//@node F24A679D-0 2645 465
//@node 4260A1E7-0 2440 465
//@node 50FA303D-0 2440 549
//@node 41D17CF5-0 3130 520
//@node 00FEC02A-0 2925 804
//@node 79EB78C0-0 3410 520
//@node D0B6BB8A-0 3690 360
//@node 2AA9C5DD-0 3970 360
//@node 97AA6AA3-0 4250 40
//@node 3835C03A-0 4045 140
//@node 8DA8266E-0 4045 232
//@node BEE79F0B-0 4530 40
//@node FC6811BF-0 4325 145
//@node 5103050E-0 4810 200
//@node 8E043706-0 4605 305
//@node 6CBDC55E-0 4400 305
//@node B9E829F6-0 5090 200
//@node 1FD64144-0 4885 305
//@node 224951FC-0 4680 305
//@node D0B6BB8A-1 5370 360
//@node 12FB6466-0 5650 360
//@node 2DFE9785-0 5445 465
//@node 41D17CF5-1 5930 520
//@node ED984389-0 5725 804
//@node 0533E1D2-0 6210 520
//@node B5524AC8-0 6005 620
//@node F652A596-0 5800 620
//@node 0452DFA1-0 6490 520
//@node A4BC5C4A-0 6770 520
//@node 2AA9C5DD-1 7050 360
//@node 537C386C-0 7610 200
//@node 1436419F-0 7405 305
//@node 0CDD0607-0 7200 305
//@node D0B6BB8A-2 7890 360
//@node 12FB6466-1 8170 360
//@node 6716C476-0 7965 465
//@node 41D17CF5-2 8450 520
//@node 1D7DFBA8-0 8245 804
//@node 0533E1D2-1 8730 520
//@node A95B7925-0 8525 620
//@node 009443ED-0 8320 620
//@node 0452DFA1-1 9010 520
//@node A4BC5C4A-1 9290 520
//@node 79EB78C0-1 9570 520
//@node 2AA9C5DD-2 9850 360
//@node 41D17CF5-3 10130 40
//@node 395659A7-0 9925 324
//@node 5E23E29B-0 40 40
//@node 1DB39968-0 330 40
//@node D3C048AB-0 105 145
//@node 34D00185-0 610 40
//@node 118A01FD-0 890 40
//@node D3907378-0 1170 40
//@node F9837087-0 730 145
//@node 16FA0037-0 960 145
//@node 517EACAA-0 1450 200
//@node 118A01FD-1 1730 200
//@node 2B2109D5-0 40 40
//@node 4200D9A0-0 330 40
//@node 60BB4EF2-0 105 145
//@node 265E52F2-0 610 40
//@node A4CFD3BA-0 405 145
//@node BF54E410-0 200 145
//@node 925E8870-0 890 40
//@node 56EBBECB-0 685 145
//@node 0A4F3839-0 480 145
//@node 2F8D2B10-0 1170 200
//@node 11302CBF-0 1450 200
//@node DD608B9C-0 40 40
//@node 46E18D82-0 330 40
//@node C3DC3C8F-0 125 145
//@node 048469FD-0 610 40
//@node DE98FE3F-0 405 145
//@node AD395425-0 200 145
//@node 578EF273-0 890 200
//@node D5AB687B-0 1170 200
//@node 5C0706B8-0 965 305
//@node 3B1CCCFC-0 1450 360
//@node 13F9E4E1-0 1730 360
//@node 14CB28A4-0 2010 200
//@node 50944004-0 40 40
//@node AEDE4042-0 330 40
//@node 8246895D-0 40 40
//@node 7E5530CB-0 330 40
//@node BE233AC0-0 610 40
//@node 63DE974B-0 40 40
//@node 6E859853-0 330 40
//@node ADD3CB69-0 105 145
//@node 950CA53F-0 -100 245
//@node 8865F7B2-0 -305 245
//@node 4DA37E2B-0 610 40
//@node 5E8561A6-0 405 145
//@node FA1B597C-0 200 145
//@node 1C8F0D66-0 890 200
//@node 4E6E4F94-0 685 305
//@node A5CD2DAB-0 1170 200
//@node E829394B-0 945 305
//@node DFD62AEB-0 1450 200
//@node 39DB3C86-0 1245 305
//@node A7AEAE38-0 1040 305
//@node 2572361A-0 1730 360
//@node 6E859853-1 2010 200
//@node 71580A88-0 1785 305
//@node AA57F7C9-0 1580 405
//@node 146F2470-0 1375 405
//@node 1A973B29-0 2290 40
//@node 0AA7BB55-0 2570 40
//@node B18E34A8-0 2365 145
//@node 1D8145DB-0 2850 200
//@node 530FB676-0 40 40
//@node 47C7E3A4-0 330 40
//@node A1FFE8F4-0 125 145
//@node 3C86EB71-0 610 200
//@node B2C58721-0 405 305
//@node C641F287-0 890 200
//@node 3303CB58-0 685 305
//@node 88E1EE21-0 480 305
//@node BA7F5911-0 480 389
//@node 03BEE31F-0 1170 200
//@node 7C123FEA-0 1450 200
//@node 2CC57DF9-0 1730 200
//@node B170EA05-0 2010 40
//@node BED850FF-0 40 40
//@node 699F6712-0 330 40
//@node C08C718D-0 610 40
//@node CE1DD3EC-0 385 145
//@node 2620CD28-0 890 40
//@node E777073B-0 665 145
//@node 741CB4A1-0 460 245
//@node D7036E41-0 1170 40
//@node EC655B78-0 945 145
//@node 586DE122-0 740 245
//@node 6C796A73-0 535 245
//@node F808DD70-0 1450 40
//@node 37712784-0 1245 145
//@node 759A98A5-0 1040 145
//@node 747CE842-0 1730 200
//@node EAF1EBF1-0 1505 305
//@node 1688DE88-0 1300 405
//@node 949747C5-0 1095 405
//@node 11BB2226-0 2010 200
//@node 20BD500D-0 1785 305
//@node A93F01FB-0 1580 405
//@node 1EF1939E-0 1375 405
//@node AB286B26-0 2290 200
//@node E5A8BABF-0 2085 300
//@node 2AED6FE0-0 2085 392
//@node 1BF38894-0 2570 40
//@node 08D91086-0 2345 145
//@node 497B8D5B-0 2140 245
//@node AF5AE180-0 1935 245
//@node DFA4F8C1-0 2850 40
//@node 183D4800-0 2645 145
//@node C7F07F8B-0 2440 145
//@node 9333DF3E-0 2440 229
//@node 13AB95DD-0 3130 40
//@node A8E5907E-0 3410 40
//@node FDC3586E-0 3205 145
//@node ADB9FD7A-0 3690 200
//@node 8E22DD8E-0 3485 305
//@node B391BABC-0 3970 360
//@node 1C42553D-0 4250 360
//@node 263D8736-0 4530 360
//@node 0AF173D6-0 4810 200
//@node 31DBD49D-0 5090 200
//@node 36C4E5D7-0 4885 305
//@node BE2301B9-0 4680 305
//@node 7638DE39-0 5370 360
//@node B04007FD-0 5165 460
//@node 464B6F49-0 5650 200
//@node F808DD70-1 5930 40
//@node 0635B61D-0 5725 145
//@node 8B2AB6F4-0 5520 145
//@node F77B26D9-0 6210 200
//@node 444BD158-0 6005 484
//@node 5CB4FF93-0 40 40
//@node 6DA490E6-0 330 40
//@node 3D0EBE8F-0 610 40
//@node 0908BB35-0 385 145
//@node 9BAB4B3C-0 180 245
//@node 7223A22F-0 -25 245
//@node 3805B677-0 890 40
//@node 442DB172-0 665 145
//@node B2B652F6-0 1170 40
//@node 23CBA95F-0 945 145
//@node 2FC1F9D5-0 1450 40
//@node 2FBADC50-0 1225 145
//@node 7BE72AFC-0 1020 245
//@node 5378E780-0 1730 40
//@node 8F3A6206-0 1505 145
//@node FD8171BF-0 1300 245
//@node CFA67630-0 1095 245
//@node 099EF2EC-0 2010 40
//@node BF0AEF84-0 1785 145
//@node 48D9768A-0 1580 245
//@node 336A20E9-0 1375 245
//@node B42723F5-0 2290 40
//@node F5C5C33D-0 2065 145
//@node E98922F5-0 2570 40
//@node 7B70D232-0 2365 145
//@node 6FF01021-0 2160 145
//@node F5CA0CF3-0 2850 200
//@node EB36AA0A-0 2645 300
//@node BE9FF7AB-0 3130 40
//@node 90DA8BEF-0 2925 232
//@node DAC4F266-0 3410 40
//@node 70235B67-0 3185 145
//@node 43506DFB-0 3690 200
//@node 3BAF61A8-0 3485 484
//@node 24B500D3-0 3970 40
//@node BBD19D20-0 3745 145
//@node 1A1C4486-0 3540 245
//@node 238E2749-0 3540 337
//@node 6E29548D-0 4250 40
//@node 139F5D61-0 3810 145
//@node A7BD4EE5-0 3605 245
//@node 1A73B639-0 3605 337
//@node 86A2CCB1-0 4040 145
//@node 4A480A86-0 4530 200
//@node D668CFAC-0 4325 305
//@node B29167B6-0 4810 360
//@node 383C978A-0 5090 200
//@node 9733769A-0 5370 200
//@node 154A4408-0 5165 300
//@node 27AD41DD-0 5650 200
//@node 9266C743-0 5930 40
//@node D18A6E1D-0 5725 140
//@node 4A480A86-1 6210 40
//@node B5D31A73-0 6005 145
//@node 0C79AB21-0 6490 200
//@node E8C9DBA1-0 6770 200
//@node 0F42504A-0 7050 200
//@node AB68B04B-0 7330 40
//@node 53A01ED6-0 7125 145
//@node 7F00F240-0 7610 200
//@node 9CCDD208-0 7405 305
//@node 6CAA9CF6-0 7200 305
//@node 8CD7705E-0 7890 200
//@node 5EE3D31D-0 7665 305
//@node 4A480A86-2 8170 360
//@node EF34F4B6-0 7965 465
//@node 0C79AB21-1 8450 520
//@node E8C9DBA1-1 8730 520
//@node 0F42504A-1 9010 520
//@node 383C978A-1 9290 360
//@node 9733769A-1 9570 360
//@node 922D89F9-0 9365 460
//@node 27AD41DD-1 9850 360
//@node 9A9A1877-0 10130 40
//@node E3CE2E0E-0 9925 145
//@node A0BE0853-0 10410 200
//@node 76BA3FB1-0 10205 305
//@node 873A8C13-0 10690 200
//@node 0FF637F5-0 10485 305
//@node F33340FA-0 10280 305
//@node 3A686B81-0 10280 389
//@node 1BC797C8-0 10970 200
//@node AAAC32DB-0 11250 200
//@node 0FCE798F-0 40 40
//@node A6CD923B-0 330 40
//@node AE275A57-0 105 145
//@node 37AD696E-0 610 40
//@node 3575CA7E-0 385 145
//@node 70B0FA2E-0 890 40
//@node DA2C4AEB-0 665 145
//@node 0102D757-0 1170 40
//@node E1E3479F-0 965 324
//@node 8C71FC9B-0 40 40
//@node F4AA14D6-0 330 40
//@node 05D890AF-0 610 40
//@node CEBC305D-0 385 145
//@node 56681EDB-0 180 245
//@node 8588EF0E-0 -25 245
//@node 97652297-0 890 40
//@node DA8B94D5-0 665 145
//@node 5834C5FA-0 460 245
//@node C7F14189-0 1170 40
//@node A30C0CFF-0 945 145
//@node 2F5D0936-0 1450 200
//@node 05CA6807-0 1245 305
//@node B97B08B1-0 1730 360
//@node D0B78F9A-0 2010 360
//@node 3A40D37A-0 2290 200
//@node 41DE3EA4-0 2570 200
//@node FD3A19EA-0 2365 300
//@node BBAF6C8D-0 2850 200
//@node 7C3E2F82-0 40 40
//@node 12E91CBD-0 330 40
//@node D983FF63-0 610 40
//@node 51C64380-0 40 40
//@node F45DD449-0 330 40
//@node E8785808-0 125 145
//@node F35A3C93-0 610 40
//@node 256D7255-0 890 40
//@node 70027C07-0 40 40
//@node BEAE4D8B-0 330 40
//@node ADC1F8DF-0 125 145
//@node FD94BFDA-0 610 40
//@node 56866E1C-0 890 40
//@node 138AB9A3-0 40 40
//@node 9988E99B-0 330 40
//@node 86029F6D-0 125 145
//@node 591FA9BA-0 610 40
//@node C888773C-0 890 40
//@node 6BDC532A-0 40 40
//@node 62100753-0 330 40
//@node EB6875EA-0 610 40
//@node 4CBB2638-0 385 145
//@node A53EB6FA-0 180 245
//@node 3074443D-0 -25 245
//@node B9302C47-0 890 40
//@node AADC55CE-0 665 145
//@node 402133D5-0 460 245
//@node EA14460E-0 255 245
//@node 6B158CAB-0 1170 40
//@node 7AED4B2E-0 945 145
//@node F4FE7BA7-0 740 245
//@node 92317BA4-0 535 245
//@node 903648D2-0 1450 40
//@node 8F7C7EB7-0 1225 145
//@node C6F0F13A-0 1020 245
//@node 6D538AED-0 815 245
//@node 8C65AF2A-0 1730 40
//@node E0A4573F-0 1505 145
//@node C59385FB-0 1300 245
//@node 6ACCB0F1-0 2010 40
//@node BAAC5D5B-0 1785 145
//@node 5EE5AA61-0 2290 40
//@node 32A7B40B-0 2085 145
//@node 2BB68B2C-0 1880 145
//@node 35AB814D-0 2570 200
//@node 70897953-0 2365 300
//@node E7785A84-0 2365 392
//@node F3882E73-0 2850 40
//@node 441D5470-0 2645 145
//@node 522CDE5C-0 2440 145
//@node ECCAA334-0 3130 200
//@node 5C24EC84-0 2925 305
//@node 319B0D07-0 3410 200
//@node B40A591C-0 3205 305
//@node 4D156E80-0 3000 305
//@node E4DC8465-0 3690 360
//@node AF7D7054-0 3485 465
//@node 2914A286-0 3970 520
//@node 5EE5AA61-1 4250 520
//@node CB0E1B6A-0 4045 625
//@node 3FF8F9DD-0 3840 625
//@node A99D8C1A-0 4530 680
//@node 2DF394D4-0 4325 964
//@node EB918E67-0 4810 520
//@node 07E7EDE5-0 5090 360
//@node 19687D5D-0 5370 360
//@node 9F61F89C-0 5165 460
//@node 06F4FBFA-0 5650 360
//@node 355117AF-0 6210 200
//@node 42C21961-0 6005 305
//@node 48D7055B-0 5800 305
//@node ECCAA334-1 6490 200
//@node 2AB6A2CB-0 6285 305
//@node 3604D37F-0 6770 200
//@node DDCE5FB2-0 6545 305
//@node C17FCD98-0 7050 360
//@node 9B767BA3-0 6845 465
//@node 4244D665-0 7050 520
//@node E4DC8465-1 7610 360
//@node 9DE9925B-0 7405 465
//@node 5EE5AA61-2 7890 520
//@node 890221E9-0 7685 625
//@node DF05765A-0 7480 625
//@node A99D8C1A-1 8170 680
//@node ED95DC83-0 7965 964
//@node 2914A286-1 8450 520
//@node EB918E67-1 8730 520
//@node 07E7EDE5-1 9010 360
//@node 19687D5D-1 9290 360
//@node CD47C77F-0 9085 460
//@node 06F4FBFA-1 9570 360
//@node 5EE5AA61-3 9850 40
//@node A736BCE0-0 9645 145
//@node 5540B5DB-0 9440 145
//@node A99D8C1A-2 10130 200
//@node FFA3ECD6-0 9925 484
//@node C67C856C-0 40 40
//@node F7F4C91C-0 330 40
//@node B336EE8F-0 610 40
//@node A2A6890F-0 405 140
//@node F4C1E59D-0 890 40
//@node D2DE0E19-0 40 40
//@node B4D776CC-0 330 40
//@node 95926C55-0 105 145
//@node 96FD10A8-0 610 40
//@node CFDE0960-0 40 40
//@node FC2ED5A8-0 330 40
//@node 1ED6BE50-0 105 145
//@node 35EFB0B3-0 610 40
//@node D0DE0AF3-0 40 40
//@node C030AB44-0 330 40
//@node 0A3BE36E-0 105 145
//@node 02E22916-0 610 40
//@node 539028EE-0 40 40
//@node BE68CCF5-0 330 40
//@node 5D817A9F-0 125 145
//@node 699F4E6D-0 40 40
//@node 34F80959-0 330 40
//@node 19560395-0 125 145
//@doomscript-blueprint end
