/***********************************************************************

ai_character_prone.script

editor keys:
"die_after_speaking"		character dies after being talked to twice.

***********************************************************************/

object ai_character_prone : ai {
	float		talkMode;
	float		talk_secondary_index;

	//
	// States
	//
	void		state_Idle();
	void		state_Pain();
	void		state_Dead();
	void		state_Killed();

	//
	// actions
	//
	void		idle_talk();
	void		init();
		
	// torso anim states
	void 		Torso_TalkPrimary();
	void 		Torso_TalkTrigger();
	void 		Torso_TalkSecondary();
	void		Torso_Idle();
	void		Torso_Dead();
	void		Torso_PlayDead();
	void		Torso_Pain();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void ai_character_prone::Torso_Dead() {
	stopAnim( ANIMCHANNEL_TORSO, 4 );
	playAnim( ANIMCHANNEL_HEAD, "dead" );
	waitFrame();
	finishAction( "dead" );
}

void ai_character_prone::Torso_PlayDead() {
	setBoneMod( false );
	if ( hasAnim( ANIMCHANNEL_HEAD, "dead" ) ) {
		playAnim( ANIMCHANNEL_HEAD, "dead" );
	}
	if ( hasAnim( ANIMCHANNEL_TORSO, "dead" ) ) {
		playAnim( ANIMCHANNEL_TORSO, "dead" );
	}
	waitFrame();
	finishAction( "dead" );
}

void ai_character_prone::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );

	while( 1 ) {
		waitFrame();
	}
}

void ai_character_prone::Torso_TalkPrimary() {
	playAnim( ANIMCHANNEL_TORSO, "talk_primary" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
}

void ai_character_prone::Torso_TalkTrigger() {
	playAnim( ANIMCHANNEL_TORSO, "talk_trigger" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
}

void ai_character_prone::Torso_TalkSecondary() {
	playAnim( ANIMCHANNEL_TORSO, "talk_secondary" + talk_secondary_index );
	talk_secondary_index = talk_secondary_index + 1;
	if ( !hasAnim( ANIMCHANNEL_TORSO, "talk_secondary" + talk_secondary_index ) ) {
		talk_secondary_index = 1;
	}

	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	
	if ( getIntKey( "die_after_speaking" ) ) {
		playAnim( ANIMCHANNEL_HEAD, "dead" );
		animState( ANIMCHANNEL_TORSO, "Torso_PlayDead", 0 );
	} else {
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	}
}

void ai_character_prone::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;

	stopSound( SND_CHANNEL_VOICE, false );
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	
	finishAction( "pain" );

	setState( "state_Dead" );
	animState( ANIMCHANNEL_TORSO, "Torso_PlayDead", 0 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
ai_character_prone::init
=====================
*/
void ai_character_prone::init() {
	talkMode = getIntKey( "talk_mode" );
	talk_secondary_index = 1;
	setBoneMod( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	setState( "state_Idle" );
}

/*
=====================
ai_character_prone::state_Idle
=====================
*/
void ai_character_prone::state_Idle() {
	AI_ACTIVATED = false;
	while( !AI_ACTIVATED ) {
		if ( AI_PAIN ) {
			setState( "state_Pain" );
		}
		waitFrame();
	}

	setTalkTarget( $player1 );
	
	idle_talk();
	while( 1 ) {
		while( !AI_TALK ) {
			if ( AI_PAIN ) {
				setState( "state_Pain" );
			}
			waitFrame();
		}
		idle_talk();
	}
}

/*
=====================
ai_character_prone::state_Pain
=====================
*/
void ai_character_prone::state_Pain() {
	setTalkState( TALK_BUSY );
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 );
	waitAction( "pain" );
	setState( "state_Dead" );
}

/*
=====================
ai_character_prone::state_Dead
=====================
*/
void ai_character_prone::state_Dead() {
	setTalkState( TALK_DEAD );
	setBoneMod( false );
	animState( ANIMCHANNEL_TORSO, "Torso_PlayDead", 0 );
	stopThinking();
}

/*
=====================
ai_character_prone::state_Killed
=====================
*/
void ai_character_prone::state_Killed() {
	animState( ANIMCHANNEL_TORSO, "Torso_Dead", 0 );
	waitAction( "dead" );
	stopThinking();
}

/*
=====================
ai_character_prone::idle_talk
=====================
*/
void ai_character_prone::idle_talk() {
	float	talktime;
	float	endtime;
	float	talkradius;
	float	currentTime;
	entity	talkTo;

	talkTo = getTalkTarget();
	
	lookAt( talkTo, 5 );
	
	// wait at least half a second
	wait( 0.5 );
	
	talkradius = getFloatKey( "talkradius" );

	if ( talkMode == 0 ) {
		animState( ANIMCHANNEL_TORSO, "Torso_TalkTrigger", 4 );
		talkMode = 1;
		setTalkState( TALK_BUSY );
		while( inAnimState( ANIMCHANNEL_TORSO, "Torso_TalkTrigger" ) ) {
			if ( AI_PAIN ) {
				setState( "state_Pain" );
			}
			if ( distanceTo( talkTo ) > talkradius ) {
				break;
			}
			lookAt( talkTo, 2 );
			waitFrame();
		}
		setTalkState( TALK_OK );
	} else if ( talkMode == 1 ) {
		animState( ANIMCHANNEL_TORSO, "Torso_TalkPrimary", 4 );
		talkMode = 2;
		setTalkState( TALK_BUSY );
		while( inAnimState( ANIMCHANNEL_TORSO, "Torso_TalkPrimary" ) ) {
			if ( AI_PAIN ) {
				setState( "state_Pain" );
			}
			if ( distanceTo( talkTo ) > talkradius ) {
				break;
			}
			lookAt( talkTo, 2 );
			waitFrame();
		}
		setTalkState( TALK_OK );
	} else if ( getFloatKey( "die_after_speaking" ) ) {
		setTalkState( TALK_BUSY );
		animState( ANIMCHANNEL_TORSO, "Torso_TalkSecondary", 4 );
		while( !inAnimState( ANIMCHANNEL_TORSO, "Torso_PlayDead" ) ) {
			lookAt( talkTo, 0.1 );
			waitFrame();
		}
		setState( "state_Dead" );
	} else {
		setTalkState( TALK_BUSY );
        animState( ANIMCHANNEL_TORSO, "Torso_TalkSecondary", 4 );
		while( inAnimState( ANIMCHANNEL_TORSO, "Torso_TalkSecondary" ) ) {
			if ( AI_PAIN ) {
				setState( "state_Pain" );
			}
			if ( distanceTo( talkTo ) > talkradius ) {
				break;
			}
			lookAt( talkTo, 2 );
			waitFrame();
		}
		setTalkState( TALK_OK );
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	setTalkTarget( $null_entity );
	
	talktime = getFloatKey( "talktime" );
	currentTime = sys.getTime();
	endtime = currentTime + talktime;
	while( ( currentTime < endtime ) && ( distanceTo( talkTo ) <= talkradius ) ) {
		lookAt( talkTo, 2 );
		if ( AI_PAIN ) {
			setState( "state_Pain" );
		}
		if ( AI_TALK ) {
			return;
		}
		waitFrame();
		currentTime = sys.getTime();
	}

	lookAt( self, 0 );
	stopSound( SND_CHANNEL_VOICE, false );
}

//@doomscript-blueprint begin 6
//@source 5743D5DC
//@catalog 0C260740
//@node D5397F88-0 40 40
//@node 59502AE5-0 330 40
//@node 06039578-0 610 40
//@node 588BABEC-0 890 40
//@node F9AB817F-0 1170 40
//@node 42E97D02-0 40 40
//@node 92C0049F-0 330 40
//@node 21418417-0 610 40
//@node 5AFB3EE5-0 385 145
//@node 592137F6-0 890 200
//@node 232FD234-0 1170 40
//@node CFE7DC25-0 945 145
//@node 2EAC3229-0 1450 200
//@node EFCC73AA-0 1730 40
//@node 1A04BCA5-0 2010 40
//@node 44846E54-0 40 40
//@node 474AA92F-0 330 40
//@node 27412FA7-0 610 40
//@node 05D41F29-0 405 145
//@node B29F1FA8-0 890 200
//@node 82A1858A-0 40 40
//@node 3F599160-0 330 40
//@node 21EA184F-0 610 40
//@node 4A38C3CD-0 170 145
//@node 0182585D-0 400 145
//@node 4AA06782-0 890 200
//@node C4B3EDF0-0 1170 40
//@node 94B4A6B0-0 40 40
//@node 54C18DCC-0 330 40
//@node F8BEB855-0 610 40
//@node 6A776DDA-0 170 145
//@node 4C25332A-0 400 145
//@node 6B39C504-0 890 200
//@node D2960236-0 1170 40
//@node 553E6B96-0 40 40
//@node B1EDA0C1-0 330 40
//@node B477E51B-0 125 232
//@node 037667E6-0 -80 232
//@node 5EBC2563-0 610 40
//@node 489F38F6-0 405 145
//@node 11D5C953-0 200 145
//@node E4AEC68D-0 890 40
//@node 442997EF-0 450 145
//@node ADD9ABC8-0 245 337
//@node 9F644D13-0 40 337
//@node 44233F9F-0 680 145
//@node E9E34608-0 1170 200
//@node F4ADAD9D-0 965 305
//@node 54A87D8B-0 1450 40
//@node 38053E66-0 1010 145
//@node 14F9E556-0 1240 145
//@node FDCB244A-0 1730 200
//@node BFAEAFD5-0 2010 40
//@node CC8459E2-0 1785 145
//@node 4D6C5296-0 2290 200
//@node F57F3B92-0 2570 200
//@node 5716AB98-0 3130 200
//@node 1010F72E-0 40 40
//@node F9B78146-0 330 40
//@node AE87F107-0 610 40
//@node 9488850C-0 385 145
//@node 7BE31805-0 890 40
//@node DBFC5E80-0 685 232
//@node 4C9EB0F3-0 1170 40
//@node C26321FD-0 730 145
//@node 5B7354CD-0 960 145
//@node 1881010A-0 1450 200
//@node 5496953B-0 1730 40
//@node A8537013-0 2010 40
//@node A7244FD2-0 2290 40
//@node D4319260-0 40 40
//@node D63B0765-0 330 40
//@node 117A06DF-0 105 145
//@node F70DE140-0 610 40
//@node DAE47A2C-0 405 145
//@node 78C319C8-0 890 40
//@node DD3BA97E-0 1170 40
//@node 9EEBE929-0 1450 40
//@node 1F8CF0F2-0 40 40
//@node 0D9E66AC-0 330 40
//@node 3678392D-0 125 145
//@node 4C74686F-0 610 40
//@node 95B0DE4E-0 405 145
//@node 3475A942-0 200 145
//@node D8B5814B-0 890 200
//@node 95DE67DF-0 685 305
//@node C59DC119-0 1170 360
//@node 0EE7FCC6-0 1450 200
//@node 8C8FA369-0 1730 40
//@node 6B47B5B7-0 2010 40
//@node 7BEECEED-0 2290 40
//@node 24AA2385-0 2085 145
//@node 63A3A364-0 2570 200
//@node 40F9F4EA-0 2365 305
//@node 59CF859C-0 2160 305
//@node D8B5814B-1 2850 360
//@node A27908C4-0 2645 465
//@node C59DC119-1 3130 520
//@node 0EE7FCC6-1 3410 360
//@node 6B47B5B7-1 3690 200
//@node 14018550-0 40 40
//@node A2D51827-0 330 40
//@node E0194A75-0 610 40
//@node A9B704FA-0 890 40
//@node 88BF6923-0 1170 40
//@node FD3CA5FD-0 1450 40
//@node 5D46780E-0 40 40
//@node BC1B3AC8-0 330 40
//@node 4F1208C7-0 610 40
//@node 6C61BCEA-0 890 40
//@node 999773C8-0 1170 40
//@node 771701E1-0 40 40
//@node E3BFF991-0 330 40
//@node F6C3DE5C-0 610 40
//@node 458144DB-0 890 40
//@node 02CCB473-0 40 40
//@node 11AE29FD-0 330 40
//@node F7DA2393-0 105 145
//@node E9D554B7-0 610 40
//@node C20B8F6F-0 405 140
//@node F5149E2D-0 890 40
//@node A5E83B26-0 1170 40
//@node 2C34B3B8-0 945 145
//@node E75EE005-0 740 245
//@node 13C2B10E-0 535 245
//@node DF3836AA-0 1450 40
//@node 9F8DEF33-0 1245 145
//@node E07ACBF0-0 1040 145
//@node 7F364D9D-0 1730 200
//@node D737EE06-0 2010 200
//@node 0977B6E9-0 1805 305
//@node E5BB20DA-0 2290 200
//@node 25646073-0 2570 200
//@node 01F51D5F-0 2345 305
//@node 9099CDC8-0 2850 360
//@node A45D3161-0 2645 465
//@node BF5BE3A8-0 3130 520
//@node 96387E57-0 3410 360
//@node F867BA08-0 3205 465
//@node F8A467E7-0 3000 465
//@node 322592A8-0 3000 549
//@node 2263A5AC-0 3690 520
//@node DDDB6384-0 3970 360
//@node 8D98343D-0 3765 460
//@node 57E21D91-0 4250 360
//@node B7BAE0B7-0 4530 200
//@node DA463834-0 4810 200
//@node CAB7BE5F-0 4605 305
//@node 6CC042B1-0 4400 305
//@node 7F159577-0 5090 200
//@node 573068C1-0 5370 200
//@node 4D4499D2-0 5165 305
//@node E5BB20DA-1 5650 200
//@node 767182C1-0 5930 200
//@node BC3BA32B-0 5705 305
//@node 9099CDC8-1 6210 360
//@node 908F8E0E-0 6005 465
//@node BF5BE3A8-1 6490 520
//@node 96387E57-1 6770 360
//@node 6FB0E133-0 6565 465
//@node 64E88BAA-0 6360 465
//@node 96619A5D-0 6360 549
//@node 2263A5AC-1 7050 520
//@node DDDB6384-1 7330 360
//@node 7D3CF4F4-0 7125 460
//@node 57E21D91-1 7610 360
//@node B7BAE0B7-1 7890 200
//@node 97645F5A-0 8170 200
//@node 298BA835-0 7945 305
//@node E5BB20DA-2 8450 200
//@node 5CE187F3-0 8730 200
//@node 6A59D0F8-0 9010 200
//@node 361CBC55-0 8570 305
//@node 00DEB0C5-0 8800 305
//@node C8235C35-0 9290 360
//@node B8A1BB26-0 9085 460
//@node 57E21D91-2 9570 360
//@node B8A856C2-0 9850 200
//@node E5BB20DA-3 10410 200
//@node 5CE187F3-1 10690 200
//@node BF3AC8C9-0 10970 200
//@node 7C2870F3-0 10745 305
//@node 9099CDC8-2 11250 360
//@node 921BB203-0 11045 465
//@node BF5BE3A8-2 11530 520
//@node 96387E57-2 11810 360
//@node 0F055C3E-0 11605 465
//@node CB0ABCE1-0 11400 465
//@node E0D6C2FE-0 11400 549
//@node 2263A5AC-2 11810 520
//@node DDDB6384-2 12370 360
//@node B3664A9F-0 12165 460
//@node 57E21D91-3 12650 360
//@node B7BAE0B7-2 12930 200
//@node 6DDA4667-0 13210 40
//@node 2F480A11-0 13490 40
//@node DD472224-0 13770 40
//@node E231B9D5-0 13545 145
//@node 14696EA4-0 13340 245
//@node 668E5E39-0 13135 245
//@node 8246654F-0 14050 40
//@node 117B46C5-0 13825 145
//@node E0A4B1E6-0 14330 40
//@node D950D3B6-0 14125 145
//@node 760A0DD6-0 13920 145
//@node 8A59A753-0 13920 229
//@node EEB9096E-0 14610 40
//@node 2F06E622-0 14405 145
//@node 34D53830-0 14200 145
//@node CEA2D930-0 14200 229
//@node B29F5ED8-0 14200 313
//@node 287F9537-0 14200 397
//@node DDDB6384-3 14890 200
//@node B44E2C2E-0 14685 300
//@node 9099CDC8-3 15170 200
//@node 08B08938-0 14965 305
//@node BF5BE3A8-3 15450 360
//@node 82C8B77A-0 15730 200
//@node E83931CA-0 15525 305
//@node F41905B8-0 16010 360
//@node 57E21D91-4 16290 200
//@node 8246654F-1 16570 200
//@node 2401814A-0 16345 305
//@node AD649E17-0 16850 40
//@node BD30C2B5-0 17130 40
//@doomscript-blueprint end
