/***********************************************************************

ai_follower.script

***********************************************************************/

#define FOLLOW_MAXDIST	120
#define FOLLOW_MINDIST	80
#define FOLLOW_RUNDIST	180

object follower : ai {
	string		customAnim;
	boolean		inCustomAnim;
	float		customBlendOut;
	boolean		run;
	
	//
	// States
	//
	void		state_Idle();
	void		state_Killed();
	void		state_Follow();
	void		getCloser();

	void		init();
	
	void		playCustomCycle( string animname, float blendTime );
	void		playCustomAnim( string animname, float blendIn, float blendOut );

	float		should_turn_left();
	float		should_turn_right();
		
	// torso anim states
	void		Torso_Death();
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_CustomAnim();
	void		Torso_CustomCycle();
	
	// legs anim states
	void		Legs_Death();
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_TurnLeft();
	void		Legs_TurnRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void follower::Torso_CustomCycle() {
	overrideAnim( ANIMCHANNEL_LEGS );
	playCycle( ANIMCHANNEL_TORSO, customAnim );
	eachFrame {
		;
	}
}

void follower::Torso_CustomAnim() {
	inCustomAnim = true;
	playAnim( ANIMCHANNEL_TORSO, customAnim );
	
	while( !( animDone( ANIMCHANNEL_TORSO, customBlendOut ) ) ) {
		waitFrame();
	}
	
	finishAction( "customAnim" );
	inCustomAnim = false;
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", customBlendOut );
}

void follower::Torso_Death() {
	finishAction( "dead" );
}

void follower::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
}

void follower::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}
	
	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void follower::Legs_Death() {
}

float follower::should_turn_left() {
	float turnAmount;
	
	turnAmount = getTurnDelta();
	if ( turnAmount > 10 ) {
		if ( hasAnim( ANIMCHANNEL_LEGS, "turn_left" ) ) {
			return true;
		}
	}
	return false;
}

float follower::should_turn_right() {
	float turnAmount;
	
	turnAmount = getTurnDelta();
	if ( turnAmount < -10 ) {
		if ( hasAnim( ANIMCHANNEL_LEGS, "turn_right" ) ) {
			return true;
		}
	}
	return false;
}

void follower::Legs_Idle() {
	if ( !AI_FORWARD && !facingIdeal() ) {
		if ( should_turn_left() ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
		}
		if ( should_turn_right() ) {
			animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
		}
	}
	
	idleAnim( ANIMCHANNEL_LEGS, "idle" );
	eachFrame {
		if ( AI_FORWARD ) {
			if ( run ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Run", 12 );
			} else {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
			}
		}
		
		if ( !facingIdeal() ) {
			if ( should_turn_left() ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnLeft", 4 );
			}
			if ( should_turn_right() ) {
				animState( ANIMCHANNEL_LEGS, "Legs_TurnRight", 4 );
			}
		}
	}
}

void follower::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD && !run )	{
		waitFrame();
	}
	
	if ( AI_FORWARD && run ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Run", 12 );
	}
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
}

void follower::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	while( AI_FORWARD && run )	{
		waitFrame();
	}
	
	if ( AI_FORWARD ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 12 );
	}
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 12 );
}

void follower::Legs_TurnLeft() {
	float turnAmount;
	
	turnAmount = getTurnDelta();
	if ( turnAmount > 110 ) {
		// do it in two turns
		turnAmount *= 0.5;
	}

	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void follower::Legs_TurnRight() {
	float turnAmount;
	
	turnAmount = getTurnDelta();
	if ( turnAmount < -110 ) {
		// do it in two turns
		turnAmount *= 0.5;
	}

	playAnim( ANIMCHANNEL_LEGS, "turn_right" );
	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		waitFrame();
	}
	
	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
follower::init
=====================
*/
void follower::init() {
	inCustomAnim = false;
	run = false;
	
	float mod;
	mod = getIntKey( "head_look" );
	setBoneMod( mod );
	
	setTalkState( TALK_OK );

	self.setKey( "conversationNext", "" );
	
	setKey( "wander", "1" );
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	setState( "state_Idle" );
}

/*
=====================
follower::playCustomCycle
=====================
*/
void follower::playCustomCycle( string animname, float blendTime ) {
	customAnim = animname;
	animState( ANIMCHANNEL_TORSO, "Torso_CustomCycle", blendTime );
}

/*
=====================
follower::playCustomAnim
=====================
*/
void follower::playCustomAnim( string animname, float blendIn, float blendOut ) {
	customBlendOut = blendOut;
	customAnim = animname;
	inCustomAnim = true;
	animState( ANIMCHANNEL_TORSO, "Torso_CustomAnim", blendIn );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
follower::state_Idle
=====================
*/
void follower::state_Idle() {
	stopMove();
	setTalkTarget( $null_entity );
	while( 1 ) {
		if ( AI_TALK ) {
			setState( "state_Follow" );
		}
		waitFrame();
	}
}

/*
=====================
follower::state_Killed
=====================
*/
void follower::state_Killed() {
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );

	waitAction( "dead" );
	stopThinking();
}

/*
=====================
follower::state_Follow
=====================
*/
void follower::state_Follow() {
	entity leader;

	leader = getTalkTarget();
	if ( !leader ) {
		leader = $player1;
	}
	setTalkTarget( $null_entity );
	while( 1 ) {
		lookAt( leader, 0.1 );
		if ( AI_TALK ) {
			setState( "state_Idle" );
		}
		if ( distanceTo( leader ) > FOLLOW_MAXDIST ) {
			getCloser();
		} else {
			faceEntity( leader );
		}
		waitFrame();
	}
}

void follower::getCloser() {
	entity leader;

	leader = getTalkTarget();
	if ( !leader ) {
		leader = $player1;
	}
	setTalkTarget( $null_entity );
	run = false;
	moveToEntity( leader );
	while( !AI_DEST_UNREACHABLE && !AI_MOVE_DONE && ( distanceTo( leader ) > FOLLOW_MINDIST ) ) {
		lookAt( leader, 0.1 );
		if ( distanceTo( leader ) > FOLLOW_RUNDIST ) {
			run = true;
		}
		if ( distanceTo( leader ) < FOLLOW_MAXDIST ) {
			run = false;
		}
		if ( AI_TALK ) {
			setState( "state_Idle" );
		}
			
		waitFrame();
	}
	stopMove();
}

//@doomscript-blueprint begin 6
//@source B85FEDBA
//@catalog 0C260740
//@node 53253112-0 40 40
//@node 3A072587-0 330 40
//@node 41946F1A-0 610 40
//@node 87D088EF-0 405 232
//@node 589C222D-0 890 40
//@node 8F456762-0 1170 200
//@node 1C34E561-0 40 40
//@node 8921D197-0 330 40
//@node 982202E8-0 125 145
//@node CC6A73B8-0 610 40
//@node 8C98FF9B-0 405 232
//@node 9E8786DF-0 890 40
//@node 56846489-0 450 145
//@node 03B02B08-0 245 337
//@node A028B999-0 680 145
//@node 9A309E43-0 1170 200
//@node 68033166-0 1450 40
//@node 6FE5B2E3-0 1245 140
//@node 06B0ED16-0 1040 140
//@node 5EB8B0DE-0 1730 40
//@node 8AD370C3-0 1525 145
//@node 61B30F45-0 2010 40
//@node 3D6D0EE0-0 1805 324
//@node 32FF8E83-0 40 40
//@node C680E884-0 330 40
//@node 6A1F58CD-0 40 40
//@node 403A7660-0 330 40
//@node C0B27149-0 610 40
//@node 308FEB8C-0 405 145
//@node A25EDF2A-0 200 145
//@node E3B109CF-0 890 200
//@node 467AD19B-0 1170 40
//@node 430D7DAB-0 40 40
//@node 2164FBDA-0 330 40
//@node EB6906F4-0 105 145
//@node E37A82EA-0 610 40
//@node 8C56D748-0 405 232
//@node 0CD04A38-0 890 40
//@node DCD3BED0-0 685 145
//@node 27A3E9B0-0 1170 40
//@node 0F4E8397-0 730 145
//@node 06409027-0 960 145
//@node CA1C2A9C-0 1450 200
//@node C884DEE9-0 1245 305
//@node 725E58B5-0 1730 360
//@node F15EA887-0 1505 465
//@node 75B68DE0-0 2010 360
//@node 6A940038-0 1805 465
//@node 204D5217-0 1600 465
//@node AB4267D6-0 1600 549
//@node 1AD92669-0 2290 520
//@node A6763315-0 2570 200
//@node CA7F5E86-0 2850 40
//@node 4B72A5DF-0 3130 40
//@node 34A66F27-0 40 40
//@node 5D247722-0 40 40
//@node FD24DFD4-0 330 40
//@node EC95D7DF-0 105 145
//@node C5CFBE16-0 610 40
//@node EF32BB4E-0 405 145
//@node 4EF2BFCE-0 200 145
//@node ACBB8315-0 890 200
//@node 93D446E8-0 665 305
//@node 24A94FD9-0 1170 360
//@node 6839E998-0 1450 40
//@node 5D27530F-0 40 40
//@node 4875DC81-0 330 40
//@node 5BFFAED0-0 105 145
//@node 3B0AB4A6-0 610 40
//@node 4C20C4EC-0 405 145
//@node F46C25E5-0 200 145
//@node DCE89D43-0 890 200
//@node 208E1972-0 665 305
//@node DF79634A-0 1170 360
//@node A97EB4C9-0 1450 40
//@node 1D3D8369-0 40 40
//@node F350093B-0 330 40
//@node B089E9A2-0 -110 145
//@node 423100B2-0 120 145
//@node 1935B01B-0 610 200
//@node 66DB3CB7-0 385 305
//@node 2B063CC3-0 890 360
//@node CA53DC64-0 1170 200
//@node 2A5C35A4-0 945 305
//@node EC9190B2-0 1450 360
//@node 9D62A7FC-0 1730 40
//@node E04A5FE2-0 2010 40
//@node D9D448DD-0 2290 200
//@node 43DB6AFC-0 2085 305
//@node ADCDB7A0-0 2570 360
//@node 86F43856-0 2365 465
//@node 0CA04F7D-0 2850 520
//@node 55024667-0 3410 520
//@node 835DF56C-0 3690 200
//@node 741B32B4-0 3250 305
//@node 393451E4-0 3480 305
//@node 1935B01B-1 3970 360
//@node CBA65CCA-0 3745 465
//@node 2B063CC3-1 4250 520
//@node CA53DC64-1 4530 360
//@node 91289F73-0 4305 465
//@node EC9190B2-1 4810 520
//@node 5927EF1E-0 40 40
//@node 1146A69D-0 330 40
//@node 511D10C4-0 610 40
//@node 72FEEDF6-0 405 145
//@node 9C1ACABD-0 200 145
//@node E0D5653A-0 200 145
//@node E9B4EAD2-0 890 200
//@node 1C205061-0 1170 40
//@node BF54F4CC-0 965 145
//@node 7AA9B00C-0 760 145
//@node 0A93FC09-0 760 145
//@node 6461ED58-0 1450 200
//@node 515202CB-0 1730 40
//@node 36E4FF14-0 40 40
//@node 528BC81F-0 330 40
//@node 35379516-0 125 232
//@node 08A4EBCF-0 -80 232
//@node 48A1766D-0 610 40
//@node AB228271-0 405 145
//@node 27EC6B55-0 200 145
//@node 38DFC5A2-0 200 145
//@node C00C2F70-0 890 200
//@node BCD180EC-0 1170 40
//@node AB27F90A-0 965 145
//@node A357F5D2-0 1450 200
//@node 611FE215-0 1730 40
//@node 3E760249-0 40 40
//@node 16DEF4A7-0 330 40
//@node 4150F8F6-0 105 145
//@node A319C892-0 610 40
//@node B9F61FF7-0 405 145
//@node 01B200D8-0 200 145
//@node 715009C4-0 890 200
//@node 97D87EE2-0 685 305
//@node 15AE56F5-0 480 305
//@node 8D60D567-0 1170 40
//@node 19BA684E-0 1450 40
//@node 5DD88B84-0 1010 145
//@node 490ED554-0 1240 145
//@node E9428D43-0 1730 200
//@node 2FCF18C0-0 2010 40
//@node FB494EDA-0 2290 40
//@node D88773DF-0 1850 145
//@node 176E7A6F-0 2080 145
//@node E9428D43-1 2570 200
//@node A63E37F3-0 2850 40
//@node CC70F8EA-0 40 40
//@node 836AA4AC-0 330 40
//@node 4F6D9C3E-0 105 145
//@node A7A338F2-0 610 40
//@node ED7C2152-0 405 145
//@node F7D605B2-0 200 145
//@node 8101D6BF-0 890 200
//@node C8941224-0 685 305
//@node 548508E9-0 480 305
//@node 29D49AFF-0 1170 40
//@node 89528629-0 1450 40
//@node 06B7C752-0 1010 145
//@node CC150C02-0 1240 145
//@node 6CF8D41A-0 1730 200
//@node 1A68F2DA-0 2010 40
//@node 5D9C77F5-0 2290 40
//@node C2F27621-0 1850 145
//@node 10DAD171-0 2080 145
//@node 6CF8D41A-1 2570 200
//@node DFF9D876-0 2850 40
//@node 3030C4D9-0 40 40
//@node 47DB84BA-0 330 40
//@node AE73A234-0 125 145
//@node 3FC7C8F6-0 610 40
//@node 6D3CA3DE-0 405 145
//@node 82753627-0 890 40
//@node 1BF16AE3-0 665 145
//@node 09B13D7B-0 1170 40
//@node 4D263C6F-0 965 140
//@node 43BD1879-0 1450 40
//@node DE32C7B6-0 1730 40
//@node DB2E914A-0 2010 40
//@node 3E81CF5D-0 2290 40
//@node 4310F0FF-0 2570 40
//@node 5B9C7EA8-0 2850 40
//@node 560D33D8-0 40 40
//@node DBA111DF-0 330 40
//@node 59CBF273-0 610 40
//@node 9AEFC26F-0 40 40
//@node AB6CB11D-0 330 40
//@node 7B58E30C-0 610 40
//@node 10BC2B89-0 890 40
//@node 4EDC2A5A-0 685 145
//@node 1F49389F-0 1170 40
//@node 8D61F14B-0 40 40
//@node 4733D466-0 330 40
//@node ABEB0475-0 610 40
//@node DC5B6A6A-0 890 40
//@node D513B80A-0 685 145
//@node 893C41FE-0 1170 200
//@node 1A9FE8F1-0 965 305
//@node E5333AB5-0 1450 360
//@node 2434845D-0 1730 200
//@node 8BCA9068-0 40 40
//@node 458C5405-0 330 40
//@node DEAA51A2-0 610 40
//@node 03A51A88-0 890 40
//@node 2004425D-0 1170 40
//@node AF565502-0 1450 40
//@node 819B5C48-0 40 40
//@node 7DB2732A-0 330 40
//@node 2EF9C54B-0 105 145
//@node 88ABE314-0 610 40
//@node 93EA83E9-0 405 145
//@node 25568635-0 200 145
//@node 3F711F20-0 890 200
//@node 2B903A26-0 685 305
//@node 7E9841F0-0 1170 40
//@node 51348C53-0 1450 40
//@node EE465075-0 1245 145
//@node 56503E86-0 1730 200
//@node A41B4E01-0 1525 300
//@node AD2CC3DF-0 2010 200
//@node 4435AA09-0 1805 305
//@node 7C4B2F15-0 2290 360
//@node 3E63F94C-0 2570 200
//@node 425C6BF0-0 2365 305
//@node EDDCA512-0 2160 305
//@node 96925E94-0 2850 360
//@node 367E6EAF-0 3410 360
//@node 9DC302A0-0 3205 460
//@node 7A72ADE8-0 3690 200
//@node CA88199F-0 40 40
//@node 0A09F413-0 330 40
//@node BB78937E-0 105 145
//@node 8B987CAD-0 610 40
//@node 7D851FA6-0 405 145
//@node 39AEEA46-0 200 145
//@node 3EB69CA3-0 890 200
//@node C8496E83-0 685 305
//@node 46EC6D01-0 1170 40
//@node 90BEAE9E-0 1450 40
//@node 818A817E-0 1245 145
//@node 1B062ACF-0 1730 40
//@node 28FBDBA7-0 1525 140
//@node B8ACB291-0 2010 40
//@node C4CE510C-0 1805 145
//@node D015E9F2-0 1600 145
//@node 88206F48-0 1600 229
//@node 0CEA11D7-0 1600 313
//@node D2859AC7-0 2290 200
//@node 2F775543-0 2085 300
//@node 063A540E-0 2570 200
//@node 37578279-0 2365 305
//@node 25BAEE6A-0 2160 305
//@node 7767BC57-0 2850 360
//@node 64CD5481-0 2645 465
//@node 19B3AE7B-0 3130 200
//@node 8A65EF4E-0 2925 305
//@node 7927B2D4-0 2720 305
//@node 90BEAE9E-1 3410 360
//@node 22895615-0 3205 465
//@node 27B3E28A-0 3690 200
//@node 2371EE78-0 3485 305
//@node EB11C2CE-0 3970 360
//@node 315F2D81-0 4250 200
//@node 9AF9CDEA-0 4530 40
//@doomscript-blueprint end
