/***********************************************************************

ai_monster_demon_archvile.script

monster_demon_archvile

***********************************************************************/

#define ARCH_ATTACK_RATE				2
#define ARCH_DODGE_RATE					4
#define	ARCH_PAIN_DELAY					0.25
#define	ARCH_TURRET_TO_IDLE				4
#define	ARCH_FLAME_WALL_NUM				20
#define	ARCH_FLAME_WALL_SEPERATION		48
#define	ARCH_FLAME_WALL_RANGE			( ARCH_FLAME_WALL_NUM * ARCH_FLAME_WALL_SEPERATION )
#define ARCH_NOFOVTIME					4

// anim blend times
#define	ARCH_PAIN_TO_IDLE				2
#define ARCH_PAIN_TO_PAIN				0
#define ARCH_SIGHT_TO_IDLE				4
#define ARCH_RESURRECT_TO_IDLE			4
#define ARCH_IDLE_TO_RESURRECT			4
#define	ARCH_MELEE_TO_IDLE				4
#define ARCH_INCINERATE_TO_IDLE			4
#define ARCH_FLAMEWALL_TO_IDLE			4
#define ARCH_DODGE_LEFT_TO_IDLE			4
#define	ARCH_DODGE_RIGHT_TO_IDLE		4
#define ARCH_WAIT_TO_OUT				4
#define	ARCH_IN_TO_WAIT					4
#define	ARCH_WALK_TO_WAIT				4
#define ARCH_WALK_TO_ACTION				4
#define ARCH_ACTION_TO_IDLE				4
#define ARCH_WALK_TO_DODGE_LEFT			4
#define ARCH_WALK_TO_DODGE_RIGHT		4
#define ARCH_IDLE_TO_PAIN				0
#define ARCH_IDLE_TO_WALK				4
#define ARCH_IDLE_TO_SIGHT				4
#define ARCH_WALK_TO_IDLE				4
#define ARCH_WALK_TO_FLAMEWALLATTACK	4
#define ARCH_IDLE_TO_FLAMEWALLATTACK	4
#define ARCH_WALK_TO_INCINERATEATTACK	4
#define ARCH_IDLE_TO_INCINERATEATTACK	4
#define ARCH_WALK_TO_MELEE				4
#define ARCH_IDLE_TO_TURRETATTACK		4
#define ARCH_TURRETATTACK_TO_IDLE		4

#define ATTACK_FLAMEWALL				ATTACK_SPECIAL1
#define ATTACK_RESURRECT				ATTACK_SPECIAL2

object monster_demon_archvile : monster_base {
	float			nextDodge;
	float			nextAttack;
	float			nextNoFOVAttack;
	entity			combat_node;
	float			keep_alive;
	float			num_start;
	float			summon_delay;
	float			summon_time;

	//
	// States
	//
	void			state_Begin();
	void			state_Idle();

	void			init();
	
	// attacks
	float			check_attacks();
	void			do_attack( float attack_flags );
	void			combat_resurrect();
	void			combat_flamewall();
	void			combat_incinerate();
	void			combat_melee();
	void			combat_dodge_left();
	void			combat_dodge_right();
	
	void 			spawn_flame_wall( vector org );
	void 			spawn_incerate( vector org );
	void 			flame_wall_loop();
	void 			flame_wall();
	void 			incinerate();
	float			num_minions();
	monster_base	choose_random_dead_minion();
	void			resurrection();

	// torso anim states
	void			Torso_Idle();
	void			Torso_Pain();
	void			Torso_Resurrect();
	void			Torso_MeleeAttack();
	void			Torso_FlameWallAttack();
	void			Torso_IncinerateAttack();
	void			Torso_TurretAttack();
	
	// legs anim states
	void			Legs_Idle();
	void			Legs_Walk();
	void			Legs_DodgeLeft();
	void			Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_archvile::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", ARCH_IDLE_TO_PAIN );
}

void monster_demon_archvile::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + ARCH_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_TORSO, ARCH_PAIN_TO_IDLE ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", ARCH_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", ARCH_PAIN_TO_IDLE );
}

void monster_demon_archvile::Torso_Resurrect() {
	setShaderParm( 4, -sys.getTime() );
	setSmokeVisibility( ALL_PARTICLES, 1 );
	playAnim( ANIMCHANNEL_TORSO, "resurrection" );

	while( !animDone( ANIMCHANNEL_TORSO, ARCH_RESURRECT_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "resurrection" );
	setSmokeVisibility( ALL_PARTICLES, 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", ARCH_RESURRECT_TO_IDLE );
}

void monster_demon_archvile::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, ARCH_MELEE_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", ARCH_MELEE_TO_IDLE );
}

void monster_demon_archvile::Torso_FlameWallAttack() {
	string anim;
	
	disablePain();

	setShaderParm( 4, -sys.getTime() );
	setSmokeVisibility( ALL_PARTICLES, 1 );
	anim = chooseAnim( ANIMCHANNEL_TORSO, "flamewall_attack" );
	if ( testAnimMoveTowardEnemy( anim ) ) {
		playAnim( ANIMCHANNEL_TORSO, anim );
	} else {
		allowMovement( false );
		playAnim( ANIMCHANNEL_TORSO, "turret_attack" );
	}

	while( !animDone( ANIMCHANNEL_TORSO, ARCH_FLAMEWALL_TO_IDLE ) ) {
		waitFrame();
	}

	allowMovement( true );
	finishAction( "flamewall_attack" );
	setSmokeVisibility( ALL_PARTICLES, 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", ARCH_FLAMEWALL_TO_IDLE );
}

void monster_demon_archvile::Torso_IncinerateAttack() {
	disablePain();
	setShaderParm( 4, -sys.getTime() );
	setSmokeVisibility( ALL_PARTICLES, 1 );
	playAnim( ANIMCHANNEL_TORSO, "incinerate_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, ARCH_INCINERATE_TO_IDLE ) ) {
		waitFrame();
	}

	allowMovement( true );
	finishAction( "incinerate_attack" );
	setSmokeVisibility( ALL_PARTICLES, 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", ARCH_INCINERATE_TO_IDLE );
}

void monster_demon_archvile::Torso_TurretAttack() {
	allowMovement( false );
	if ( num_minions() < keep_alive ) {
		// check if we can resurrect a minion
		if ( choose_random_dead_minion() ) {
			Torso_Resurrect();
			return;
		}
	}
	Torso_IncinerateAttack();
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_archvile::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	while( !AI_FORWARD ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Walk", ARCH_IDLE_TO_WALK );
}

void monster_demon_archvile::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD )	{
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", ARCH_WALK_TO_IDLE );
}

void monster_demon_archvile::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, ARCH_DODGE_LEFT_TO_IDLE ) ) {
		preventPain( GAME_FRAMETIME );
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", ARCH_DODGE_LEFT_TO_IDLE );
}

void monster_demon_archvile::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, ARCH_DODGE_RIGHT_TO_IDLE ) ) {
		preventPain( GAME_FRAMETIME );
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", ARCH_DODGE_RIGHT_TO_IDLE );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_archvile::init
=====================
*/
void monster_demon_archvile::init() {
	float i;
	float num;
	float total;
	monster_base monster;

	keep_alive = getIntKey( "keep_alive" );
	num_start = getIntKey( "num_start" );
	summon_delay = getFloatKey( "delay" );

	summon_time = 0;

	// wait for other monsters to start up
	waitFrame();

	// count how many resurrection targets there are
	total = 0;
	num = numTargets();
	for( i = 0; i < num; i++ ) {
		monster = getTarget( i );
		if ( !monster ) {
			continue;
		}
		total++;
		monster.archvile_minion();
	}
	if ( !keep_alive ) {
		keep_alive = total;
	}

	if ( keep_alive > total ) {
		keep_alive = total;
	}
	if ( num_start > total ) {
		num_start = total;
	}

	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_archvile::state_Begin
=====================
*/
void monster_demon_archvile::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_demon_archvile::state_Idle
=====================
*/
void monster_demon_archvile::state_Idle() {
	setSmokeVisibility( ALL_PARTICLES, 0 );
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;
	nextDodge		= RandomTime( ARCH_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_archvile::do_attack
=====================
*/
void monster_demon_archvile::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + ARCH_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_RESURRECT ) {
		combat_resurrect();
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_FLAMEWALL ) {
		combat_flamewall();
	}
}

/*
=====================
monster_demon_archvile::check_attacks
=====================
*/
float monster_demon_archvile::check_attacks() {
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}

	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}
	
	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			if ( enemyRange() < ARCH_FLAME_WALL_RANGE ) {
				if ( testChargeAttack() ) {
					attack_flags |= ATTACK_FLAMEWALL;
				}
			}
		}
	}

	if ( num_minions() < keep_alive ) {
		if ( summon_time < currentTime ) {
			// check if we can resurrect a minion
			if ( choose_random_dead_minion() ) {
				attack_flags |= ATTACK_RESURRECT;
			}
		}
	} else {
		summon_time = currentTime + summon_delay;
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_archvile::combat_resurrect
=====================
*/
void monster_demon_archvile::combat_resurrect() {
	stopMove();
	lookAtEnemy( 0 );
	animState( ANIMCHANNEL_TORSO, "Torso_Resurrect", ARCH_IDLE_TO_RESURRECT );
	waitAction( "resurrection" );
	summon_time = sys.getTime() + summon_delay;
}

/*
=====================
monster_demon_archvile::combat_flamewall
=====================
*/
void monster_demon_archvile::combat_flamewall() {
	faceEnemy();
	stopMove();
	lookAtEnemy( 0 );

	animState( ANIMCHANNEL_TORSO, "Torso_FlameWallAttack", ARCH_IDLE_TO_FLAMEWALLATTACK );
	waitAction( "flamewall_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( ARCH_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + ARCH_NOFOVTIME;
}

/*
=====================
monster_demon_archvile::combat_incinerate
=====================
*/
void monster_demon_archvile::combat_incinerate() {
	faceEnemy();
	stopMove();
	lookAtEnemy( 0 );

	animState( ANIMCHANNEL_TORSO, "Torso_IncinerateAttack", ARCH_IDLE_TO_INCINERATEATTACK );
	waitAction( "incinerate_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( ARCH_ATTACK_RATE );
}

/*
=====================
monster_demon_archvile::combat_melee
=====================
*/
void monster_demon_archvile::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", ARCH_WALK_TO_MELEE );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_archvile::combat_dodge_left
=====================
*/
void monster_demon_archvile::combat_dodge_left() {
	AI_PAIN = false;
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", ARCH_WALK_TO_DODGE_LEFT );
	waitAction( "strafe" );
	nextDodge = DelayTime( ARCH_DODGE_RATE );
}

/*
=====================
monster_demon_archvile::combat_dodge_right
=====================
*/
void monster_demon_archvile::combat_dodge_right() {
	AI_PAIN = false;
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", ARCH_WALK_TO_DODGE_RIGHT );
	waitAction( "strafe" );
	nextDodge = DelayTime( ARCH_DODGE_RATE );
}

/*
=====================
monster_demon_archvile::spawn_flame_wall
=====================
*/
void monster_demon_archvile::spawn_flame_wall( vector org ) {
	entity ent;
	vector ang;

	ang_y = sys.random( 360 );
	ent = sys.spawn( "archvile_flamewall" );
	ent.setKey( "cinematic_remove", "1" );	// make sure it gets removed in cinematics
	ent.setShaderParm( 4, -sys.getTime() );
	ent.setShaderParm( 5, sys.random( 1 ) );
	ent.setOrigin( org );
	ent.setAngles( ang );
	ent.setOwner( self );
	ent.disable();
	sys.wait( 0.2 );
	ent.enable();
	sys.wait( 0.5 );
	ent.disable();
	sys.wait( 2.0 );
	ent.remove();
}

/*
=====================
monster_demon_archvile::spawn_incerate
=====================
*/
void monster_demon_archvile::spawn_incerate( vector org ) {
	entity ent;
	vector ang;

	ang_y = sys.random( 360 );
	ent = sys.spawn( "archvile_incinerate" );
	ent.setKey( "cinematic_remove", "1" );	// make sure it gets removed in cinematics
	ent.setShaderParm( 4, -sys.getTime() );
	ent.setShaderParm( 5, sys.random( 1 ) );
	ent.setOrigin( org );
	ent.setAngles( ang );
	ent.setOwner( self );
	ent.disable();
	sys.wait( 0.4 );
	ent.enable();
	sys.wait( 0.4 );
	ent.disable();
	sys.wait( 0.6 );
	ent.remove();
}

/*
=====================
monster_demon_archvile::flame_wall_loop
=====================
*/
void monster_demon_archvile::flame_wall_loop() {
	float	i;
	vector	dir;
	vector	ang;
	vector	pos;
	float	frac;

	ang = getAngles();
	dir = sys.angToForward( ang ) * ARCH_FLAME_WALL_SEPERATION;
	pos = getOrigin();
	for( i = 0; i < ARCH_FLAME_WALL_NUM; i++ ) {
		pos_z += 48;
		if ( sys.trace( pos, pos + dir, '-8 -8 0', '8 8 16', MASK_SOLID, self ) < 1 ) {
			break;
		}
		pos = pos + dir;
		frac = sys.trace( pos, pos - '0 0 96', '-8 -8 0', '8 8 16', MASK_SOLID, self );
		if ( frac == 1 ) {
			break;
		}
		pos_z -= 96 * frac;
		thread spawn_flame_wall( pos );
		sys.wait( 0.075 );
	}
}

/*
=====================
monster_demon_archvile::flame_wall
=====================
*/
void monster_demon_archvile::flame_wall() {
	thread flame_wall_loop();
}

/*
=====================
monster_demon_archvile::incinerate
=====================
*/
void monster_demon_archvile::incinerate() {
	thread spawn_incerate( predictEnemyPos( 0.4 ) );
}

/*
=====================
monster_demon_archvile::num_minions
=====================
*/
float monster_demon_archvile::num_minions() {
	float i;
	float num;
	monster_base monster;
	float minions;

	minions = 0;
	num = numTargets();
	for( i = 0; i < num; i++ ) {
		monster = getTarget( i );
		if ( !monster || monster.AI_DEAD ) {
			continue;
		}
		minions++;
	}

	return minions;
}

/*
=====================
monster_demon_archvile::choose_random_dead_minion
=====================
*/
monster_base monster_demon_archvile::choose_random_dead_minion() {
	float i;
	float num;
	float startnum;
	monster_base monster;

	num = numTargets();
	startnum = sys.random( num );
	for( i = 0; i < num; i++ ) {
		monster = getTarget( ( i + startnum ) % num );
		if ( monster ) {
			if ( monster.can_resurrect() ) {
				return monster;
			}
		}
	}
	return $null_entity;
}

/*
=====================
monster_demon_archvile::resurrection
=====================
*/
void monster_demon_archvile::resurrection() {
	float i;
	float num;
	monster_base monster;
	float alive;
	entity enemy;
	
	alive = num_minions();

	if ( !num_start ) {
		num = keep_alive;
	} else {
		num = num_start;
		num_start = 0;
	}

	enemy = getEnemy();
	for( i = alive; i < num; i++ ) {
		monster = choose_random_dead_minion();
		if ( !monster ) {
			break;
		}
		if ( monster == enemy ) {
			clearEnemy();
			checkForEnemy( false );
			enemy = getEnemy();
		}
		monster.monster_resurrect( enemy );
	}
}

//@doomscript-blueprint begin 6
//@source AC66B6F7
//@catalog 0C260740
//@node 08DC1EF6-0 40 40
//@node 0F927971-0 330 40
//@node 2EA001BE-0 610 40
//@node BBA58979-0 405 145
//@node ADBEF595-0 200 145
//@node 2BCAEC76-0 890 200
//@node 79926A74-0 1170 40
//@node 5A3EFE74-0 40 40
//@node DB7709C5-0 330 40
//@node 21C694EE-0 105 145
//@node EF8DB02B-0 610 40
//@node CA02CB48-0 405 232
//@node 354F33F9-0 890 40
//@node 4038BEA1-0 685 145
//@node FE618A8F-0 1170 40
//@node 8ADDD526-0 730 145
//@node 81359776-0 960 145
//@node 0494203D-0 1450 200
//@node 50AD1E99-0 1245 305
//@node 262E5F34-0 1730 360
//@node 81B69EC0-0 1505 465
//@node A3F2B0A7-0 2010 360
//@node C2B4EAFE-0 1805 465
//@node F3520B69-0 1600 465
//@node 4C6DD594-0 1600 549
//@node BE732C68-0 2290 520
//@node EFFD66CC-0 2570 200
//@node B7E48129-0 2850 40
//@node D7477828-0 3130 40
//@node 9D21517F-0 40 40
//@node 642568E6-0 330 40
//@node 75E462EC-0 610 40
//@node 92689E33-0 890 40
//@node 5DAD9EEF-0 1170 40
//@node C8D1A767-0 730 145
//@node E47F29B7-0 960 145
//@node 924A7EED-0 1450 200
//@node 1B95608D-0 1730 40
//@node 30D1ABDD-0 2010 40
//@node A56EEA44-0 2290 40
//@node 85A2C454-0 40 40
//@node 73DC84DC-0 330 40
//@node ADB9D1E3-0 610 40
//@node C1C98646-0 170 145
//@node 4CB8BE76-0 400 145
//@node E7A6942C-0 890 200
//@node D711ACE4-0 1170 40
//@node ECF69032-0 1450 40
//@node B53AA64B-0 40 40
//@node 34E36FFF-0 330 40
//@node A1EA7B3E-0 610 40
//@node A9B7BF74-0 890 40
//@node AB7797DA-0 1170 40
//@node A0C0B1C7-0 945 145
//@node C0BB5BA0-0 1450 40
//@node DDF30997-0 1225 145
//@node 3AE8C434-0 1020 245
//@node 5C1B37BF-0 1730 200
//@node D2E86BD2-0 1525 392
//@node 1613AED0-0 2290 200
//@node 8B2EA84F-0 2570 200
//@node 93FF6937-0 2850 40
//@node D7159499-0 2410 145
//@node 6D01E709-0 2640 145
//@node C4EDD475-0 3130 200
//@node B3419653-0 3410 40
//@node A206B3AA-0 3690 40
//@node 1CC4F4C5-0 3970 40
//@node DCA25000-0 4250 40
//@node 5F0B9868-0 40 40
//@node 830E5BD6-0 330 40
//@node 43E3CF4D-0 610 40
//@node EF213B8F-0 890 40
//@node 6919BF26-0 1170 40
//@node EE4E04D3-0 1450 40
//@node 58F5C829-0 1010 145
//@node 80346AD9-0 1240 145
//@node AEAEE58C-0 1730 200
//@node 591EE652-0 2010 40
//@node D14702DE-0 2290 40
//@node 73C447C6-0 2570 40
//@node 73C06190-0 2850 40
//@node 6CC3D9C2-0 40 40
//@node DDAA125D-0 330 40
//@node A98BBA54-0 610 40
//@node 3176082B-0 405 145
//@node 35482467-0 200 145
//@node 864A106C-0 890 200
//@node 8EE3DF66-0 665 305
//@node 3A75F6DD-0 1170 360
//@node A0E0FB89-0 1450 360
//@node 3F8E5230-0 1730 40
//@node 228D9210-0 40 40
//@node BE5AC6E9-0 330 40
//@node 1B2D2F23-0 610 40
//@node 88F0EB58-0 405 145
//@node E7196BBA-0 200 145
//@node 67FC8890-0 890 200
//@node 04E16C10-0 1170 40
//@node 77B5528F-0 40 40
//@node 6866BEB6-0 330 40
//@node 0E0B75AD-0 610 40
//@node 74AEF177-0 405 145
//@node F7C61C31-0 890 200
//@node 292439D4-0 1170 40
//@node 408F06DC-0 40 40
//@node CCA90DAC-0 330 40
//@node 0F2E88E8-0 610 40
//@node 3F1A5DF7-0 170 145
//@node 5E19A6E7-0 400 145
//@node 21E2DF97-0 890 200
//@node 16EC7024-0 1170 200
//@node C0F11CCA-0 1450 40
//@node 8F2689F5-0 1730 40
//@node 24748F29-0 40 40
//@node 6B79C1AA-0 330 40
//@node A121BF4C-0 610 40
//@node 799A1FB4-0 170 145
//@node C469CD44-0 400 145
//@node BBC7B2F0-0 890 200
//@node EAAA5347-0 1170 200
//@node A3502A77-0 1450 40
//@node 89459D87-0 1730 40
//@node B3265242-0 40 40
//@node 5F0E31DC-0 330 40
//@node 4F4F60FB-0 105 145
//@node 88FD5818-0 -100 245
//@node 558E2783-0 -305 245
//@node BFC38BE8-0 610 40
//@node CC0E91AB-0 385 145
//@node 62858CF4-0 180 245
//@node 0095EFF9-0 -25 245
//@node 6A019F73-0 890 40
//@node 09DF6834-0 665 145
//@node 75AD2FAE-0 1170 40
//@node BEE5B3C7-0 965 145
//@node C7AADEE2-0 1450 40
//@node C0059A83-0 1730 40
//@node 58AF1F33-0 1525 145
//@node D52B677E-0 2010 40
//@node AD9CBB44-0 1785 145
//@node 88DD9502-0 2290 40
//@node 07076255-0 2085 145
//@node 65E8B3BB-0 1880 145
//@node C7E318F0-0 1880 229
//@node D0410B8A-0 2570 200
//@node BA813FE5-0 2345 305
//@node 71E96C08-0 2140 405
//@node EE26E891-0 2850 200
//@node C8A9CDFD-0 2645 305
//@node 4A61066F-0 2440 305
//@node 77A010CD-0 3130 360
//@node 9BCFEC7C-0 3410 200
//@node F986DFEF-0 3205 305
//@node C5D100FA-0 3000 305
//@node EEA9B50B-0 3690 200
//@node 54FBCAB0-0 3970 40
//@node A0C02F84-0 3765 145
//@node CC520D8E-0 3560 145
//@node 81399218-0 4250 200
//@node 47B2D0CF-0 4045 305
//@node 09580A2D-0 4530 40
//@node A01A05FB-0 4325 145
//@node AB0E95E1-0 4120 145
//@node 860ADEA2-0 4120 229
//@node 81399218-1 4810 200
//@node FD1A8E28-0 4605 305
//@node 60815B1F-0 5090 40
//@node 045227D5-0 4885 145
//@node F38F6347-0 4680 145
//@node FDB8F2C6-0 4680 229
//@node 5BB0E54E-0 5370 200
//@node 0E89F2D6-0 5165 305
//@node 6DB48C82-0 5650 40
//@node E7EA9B83-0 40 40
//@node C78DED23-0 330 40
//@node B63F605D-0 610 40
//@node CBD08F7B-0 890 40
//@node 4098EA39-0 1170 40
//@node 3AB260C2-0 1450 40
//@node 7BB5AC08-0 40 40
//@node 3CC6C9EA-0 330 40
//@node 987A8350-0 610 40
//@node 384696AA-0 890 40
//@node 464C3646-0 685 145
//@node 1AA73568-0 1170 40
//@node 6DD413D2-0 965 145
//@node E5090BE1-0 1450 40
//@node 4F8B511D-0 1225 145
//@node 32F5CD3B-0 1730 40
//@node 4C42A1BE-0 40 40
//@node 198AC0AA-0 330 40
//@node B66E1D9D-0 125 145
//@node EC534484-0 610 40
//@node 0CA063DB-0 405 145
//@node 5BFABDCC-0 890 200
//@node A34D8AAC-0 1170 200
//@node C97D6863-0 965 305
//@node B1A0FE3F-0 1450 200
//@node 59A8B32F-0 1730 200
//@node 56074887-0 1525 305
//@node 0A125C30-0 2010 200
//@node 1F3EE152-0 1805 300
//@node 94A855AD-0 2290 200
//@node DF130F46-0 2085 305
//@node 4C675DEC-0 2570 200
//@node BEF2969E-0 2850 200
//@node EBAEA36E-0 2645 305
//@node 40CA182D-0 3130 200
//@node 5CBFF9D5-0 3410 200
//@node CD7107DB-0 3205 305
//@node A93390A0-0 3690 200
//@node 6819034A-0 40 40
//@node 3C0F46C5-0 330 40
//@node 3D07DDDC-0 125 145
//@node 7956604E-0 610 40
//@node 625EACE6-0 385 145
//@node 8E015E58-0 890 40
//@node 916F75A6-0 665 145
//@node 838639A9-0 1170 40
//@node 399D3E17-0 965 145
//@node C0E4556F-0 760 145
//@node A5F303C9-0 1450 200
//@node B589FEB6-0 1245 305
//@node 973DF17A-0 1040 305
//@node 710AA96D-0 1040 389
//@node 3D8055F6-0 1040 389
//@node D05A5DA8-0 1730 360
//@node 64481ECA-0 1505 465
//@node 1F31AD69-0 2010 520
//@node EE3DA44F-0 2290 360
//@node 636AF56A-0 2065 465
//@node 8102A112-0 2570 520
//@node 8FFBED04-0 2850 520
//@node 0C997FA6-0 2645 625
//@node A70F167B-0 2440 625
//@node 43984321-0 3130 680
//@node 7D0775EE-0 2925 785
//@node 69232796-0 3410 840
//@node 2F49B685-0 3970 840
//@node 9BCFC4C9-0 4250 200
//@node 67368939-0 4025 305
//@node 5B3E4989-0 4530 200
//@node CE2046D0-0 4325 305
//@node B93435C7-0 4810 360
//@node 8E438AC0-0 5090 40
//@node EE39921E-0 4885 145
//@node CE4EE870-0 5370 200
//@node DC5D389D-0 5650 40
//@node C30B7E70-0 5445 145
//@node C9859460-0 5240 145
//@node 8B857F05-0 5240 229
//@node 2CC61C35-0 5240 145
//@node 12B8AC36-0 5930 200
//@node A73B00E1-0 5725 305
//@node 70D9B07A-0 5520 305
//@node 6BE96B37-0 5520 389
//@node 318D198B-0 6210 360
//@node 1195A218-0 6005 465
//@node C1161311-0 6490 520
//@node 72FA6FF3-0 6265 625
//@node 8D98482D-0 6770 680
//@node E05BE8B0-0 7050 40
//@node 9E073718-0 6845 145
//@node 7D03ABAE-0 6640 145
//@node CC5741F1-0 7330 200
//@node DFFF72E6-0 7125 305
//@node 88625672-0 6920 305
//@node E80351CB-0 6920 389
//@node 467927F0-0 7610 360
//@node E500EE8C-0 7385 465
//@node CC855E81-0 7890 520
//@node 8D377F2E-0 8450 200
//@node 81E511B3-0 8245 305
//@node EE9AAC78-0 8040 305
//@node E38019E7-0 8040 389
//@node 598D91F9-0 8730 40
//@node 47D005B8-0 40 40
//@node 11BF3F25-0 330 40
//@node 422FBEA8-0 610 40
//@node 1B160DD8-0 890 40
//@node FC76F50C-0 1170 40
//@node 9A997B83-0 1450 40
//@node B2D85AAC-0 1245 145
//@node C6684191-0 1040 145
//@node 4A523D5C-0 40 40
//@node 3DF4C4EF-0 330 40
//@node 7E38C78D-0 610 40
//@node C4E22CB0-0 890 40
//@node C62A1888-0 1170 40
//@node 989571FF-0 1450 40
//@node AB778439-0 1730 40
//@node 45FD261F-0 1505 145
//@node C59DCB3E-0 2010 40
//@node C6D3D743-0 1805 145
//@node 6DF07EE9-0 40 40
//@node C83141E8-0 330 40
//@node B3471E24-0 610 40
//@node 59CD0B19-0 890 40
//@node 1D5A6E29-0 1170 40
//@node A938D843-0 1450 40
//@node 433B142A-0 1730 40
//@node 6D652547-0 1505 145
//@node B37A1083-0 40 40
//@node 961860FA-0 330 40
//@node C8E774B2-0 610 40
//@node 35275668-0 890 40
//@node 17709A25-0 1170 40
//@node 692096EA-0 1450 40
//@node F579DB20-0 40 40
//@node 6DEAFC85-0 330 40
//@node 235798E7-0 125 145
//@node 35F034C5-0 610 40
//@node 27278877-0 890 40
//@node 7687C138-0 1170 40
//@node FAF46394-0 1450 40
//@node FC2235B7-0 1730 40
//@node E304A434-0 1505 145
//@node C06E1AD5-0 40 40
//@node 89DE0A2C-0 330 40
//@node DD53B0DA-0 125 145
//@node 38A9A968-0 610 40
//@node F31A60C4-0 890 40
//@node 83574F0B-0 1170 40
//@node A783C865-0 1450 40
//@node 80E023C0-0 1730 40
//@node 354D2808-0 1505 145
//@node 50285E40-0 40 40
//@node 1D79B90D-0 330 40
//@node D39BAB6F-0 105 145
//@node AD580A3B-0 610 40
//@node DD989149-0 385 145
//@node 165563FD-0 890 40
//@node 3216D3B2-0 1170 40
//@node 9C80432B-0 1450 40
//@node 5A39CD05-0 1730 40
//@node B96BF279-0 2010 40
//@node F7E97BE9-0 1805 140
//@node 2226809A-0 2290 40
//@node 54A36233-0 2570 40
//@node EC100F7E-0 2850 40
//@node 7C85E22C-0 3130 40
//@node A1C98105-0 3410 40
//@node 54A36233-1 3690 40
//@node 193E55CE-0 3970 40
//@node 764E012D-0 4250 40
//@node 582D3519-0 40 40
//@node AE4F3102-0 330 40
//@node CFBB5CD0-0 105 145
//@node 5638D8D5-0 610 40
//@node 9A40F10B-0 385 145
//@node 98A1F742-0 890 40
//@node 7C88D137-0 1170 40
//@node 88F0666C-0 1450 40
//@node FF755CD4-0 1730 40
//@node 51DE9204-0 2010 40
//@node CE088629-0 1805 140
//@node 04EB681B-0 2290 40
//@node 1D8D3468-0 2570 40
//@node FEF81DD7-0 2850 40
//@node 5CD1A3E9-0 3130 40
//@node FEF81DD7-1 3410 40
//@node 1D8D3468-1 3690 40
//@node C8F305A1-0 3970 40
//@node 1CE22734-0 4250 40
//@node 713531D3-0 40 40
//@node 7F49C911-0 330 40
//@node 0136A1CF-0 105 145
//@node 9F006C87-0 610 40
//@node 3ED97ABD-0 405 145
//@node 4F4F2134-0 200 145
//@node D7EFB8D9-0 890 40
//@node A47065FA-0 665 145
//@node 0E3CCB9B-0 1170 40
//@node 280758D3-0 965 145
//@node 3E547585-0 760 145
//@node 0CF24604-0 1450 200
//@node C58F1DBC-0 1245 305
//@node 734A8DD0-0 1730 200
//@node E1CE14C0-0 1525 305
//@node 64EFD84F-0 1320 305
//@node E1D0E0B2-0 1320 389
//@node 6EAD27E0-0 2010 360
//@node 80C889DA-0 2290 200
//@node FC391D53-0 2085 305
//@node ED3755B9-0 1880 305
//@node 7A2304A8-0 1880 389
//@node F0F67888-0 2570 200
//@node D540F833-0 2345 305
//@node AA305DC2-0 2140 405
//@node C6ECE346-0 2140 497
//@node EDCE5DE5-0 1935 497
//@node 5FE5802A-0 2850 200
//@node 15A0BEC5-0 2645 305
//@node C1B0461F-0 2440 305
//@node 6EAD27E0-1 3130 360
//@node D52D50ED-0 3410 200
//@node DBE10099-0 3205 305
//@node B73FF968-0 3000 305
//@node 66B71303-0 3690 200
//@node 921D6B59-0 3970 200
//@node A7759D70-0 40 40
//@node F0472B0F-0 330 40
//@node 39B30A38-0 40 40
//@node 0DA8854D-0 330 40
//@node 78B9CE58-0 40 40
//@node 286D6914-0 330 40
//@node 11B25348-0 125 145
//@node 8A2C914A-0 610 40
//@node 83A0A0C7-0 385 145
//@node F171493C-0 890 40
//@node 775E7923-0 685 145
//@node 35AC6DBF-0 480 145
//@node 32DE9D6C-0 480 229
//@node 18EF98B6-0 1170 200
//@node 8A2E8944-0 945 305
//@node A814CBC4-0 740 405
//@node 8AC4CF4A-0 1450 200
//@node 01535DD3-0 1245 305
//@node 79DE1F2C-0 1040 305
//@node 49BA1917-0 1040 389
//@node D2340C89-0 1730 360
//@node 56C28C77-0 2010 200
//@node 2EFB3995-0 1805 305
//@node C4D1F27A-0 1600 305
//@node F41D51C6-0 2290 40
//@node 9ED869EF-0 40 40
//@node A97B432D-0 330 40
//@node 01EBD283-0 105 145
//@node 78F4B4BF-0 610 40
//@node 07C8389F-0 385 145
//@node F1C3C461-0 180 245
//@node 7D3CC775-0 890 40
//@node DB11C1E1-0 685 145
//@node BF89C351-0 480 145
//@node 9A50986A-0 480 229
//@node 4CAEA076-0 1170 200
//@node 6D4AE471-0 945 305
//@node 2F95AD08-0 740 405
//@node 0A599BAC-0 535 405
//@node 2B306D4B-0 535 483
//@node 530495E5-0 535 561
//@node A2C918F5-0 1450 200
//@node 04A1CF14-0 1245 305
//@node 26165E9E-0 1730 360
//@node CC91B062-0 1505 465
//@node 4E6A96DE-0 2010 520
//@node E5A3996D-0 2290 40
//@node A2D1BBFF-0 40 40
//@node 32EB43CC-0 330 40
//@node DB16833C-0 105 145
//@node 0C11FE0D-0 610 40
//@node 480DD410-0 405 145
//@node 137A093A-0 200 145
//@node 0AE74391-0 890 200
//@node CA692292-0 685 305
//@node 72C14583-0 1450 200
//@node 98905FDF-0 1245 305
//@node 03286607-0 1730 200
//@node EF31BD45-0 1525 305
//@node 0FED8985-0 2010 40
//@node CCF3DD2E-0 1785 145
//@node 62F73048-0 2290 40
//@node 29A5594B-0 2085 145
//@node B8096D08-0 1880 145
//@node 3C3AFD5F-0 1880 229
//@node EF7F81B2-0 1880 313
//@node 192E9F9C-0 2570 200
//@node A85D6612-0 2345 305
//@node 1F944278-0 2850 200
//@node A05EF39A-0 2645 305
//@node 81B91ED6-0 2440 305
//@node DCCC0CC6-0 2850 360
//@node 953C7207-0 3410 200
//@node CDB4B03C-0 3205 305
//@node E090187D-0 3000 305
//@node E7831A5F-0 3000 389
//@node 5C98382C-0 3690 360
//@node B6144D21-0 3970 360
//@node 0FED8985-1 4250 360
//@node E470AA5F-0 4025 465
//@node A3AD979B-0 4530 200
//@node 3503AC4B-0 4325 300
//@doomscript-blueprint end
