/***********************************************************************

ai_monster_boss_guardian_seeker.script

monster_boss_guardian_seeker

***********************************************************************/

#define SEEKER_TOOCLOSE_RANGE	200
#define	SEEKER_TOOFAR_RANGE		650
#define	SEEKER_IDEAL_RANGE		430
#define	SEEKER_MAXIMUM_RETREAT_RANGE ( SEEKER_TOOFAR_RANGE + 200 )

#define SEEKER_RUNTIME			2
#define SEEKER_GETCLOSER_DELAY	3
#define SEEKER_GETCLOSER_TIME	1
#define SEEKER_SIGHTTIME		2
#define SEEKER_ESCAPE_SPEED		800

object monster_boss_guardian_seeker : seeker_base {
	//
	// States
	//
	void		state_Inactive();
	void		state_Idle();
	void		state_WatchPlayer();
	void		state_GetCloser();
	void		state_FindPlayer();
	void		state_Retreat();
	void		state_RunAway();

	void		init();
	
	// Torso anim states
	void		Torso_Idle();
	void		Torso_Fly();
	void		Torso_Pain();
	void		Torso_MeleeAttack();

	monster_boss_guardian	guardian;
	entity					light1;
	entity					light2;
	entity					light_beam;
	float					last_enemy_sight;
	float					fly_speed;
};

void monster_boss_guardian_seeker::Torso_Idle() {
	playCycle( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN )		{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Fly", 4 ); }
	}
}

void monster_boss_guardian_seeker::Torso_Fly() {
	playCycle( ANIMCHANNEL_TORSO, "fly" );
	
	eachFrame {
		if ( AI_PAIN )		{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( !AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_boss_guardian_seeker::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );
	
	guardian.AI_PAIN = true;

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_boss_guardian_seeker::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );
	
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_boss_guardian_seeker::Torso_Death() {
	waitUntil( 0 );
}

void monster_boss_guardian_seeker::see_enemy() {
	if ( last_enemy_sight < sys.getTime() ) {
		startSound( "snd_sight", SND_CHANNEL_VOICE, false );
	}
	last_enemy_sight = sys.getTime() + SEEKER_SIGHTTIME;
	guardian.sightEnemy();
	light1.setColor( 1, 0.8, 0.4 );
	light2.setColor( 1, 0.8, 0.4 );
}

void monster_boss_guardian_seeker::lost_enemy() {
	light1.setColor( 0.5, 0.2, 0.1 );
	light2.setColor( 0.5, 0.2, 0.1 );
}

void monster_boss_guardian_seeker::init() {
	string name;
	entity ent;
	string classname;

	ent = getTarget( 0 );
	if ( ent ) {
		guardian = getTarget( 0 );
		if ( !guardian ) {
			sys.error( "Entity '" + ent.getName() + "' targeted by '" + getName() + "' is not monster_boss_guardian" );
		}
		guardian.addSeeker( self );
	}

	fly_speed = getFloatKey( "fly_speed" );

	// point light
	sys.setSpawnArg( "name", getName() + "_light1" );
	classname = getKey( "def_light1" );
	light1 = sys.spawn( classname );
	light1.bindToJoint( self, "head", true );
	light1.setOrigin( '0 0 30' );

	// spot light
	float distance = 3096;
	sys.setSpawnArg( "light_target", "0 1 0" );
	sys.setSpawnArg( "light_up", "0 0 0.5" );
	sys.setSpawnArg( "light_right", "-0.5 0 0" );	
	sys.setSpawnArg( "light_end", "0 " + distance + " 0" );
	sys.setSpawnArg( "name", getName() + "_light2" );
	classname = getKey( "def_light2" );
	light2 = sys.spawn( classname );
	light2.bindToJoint( self, "head", true );
	light2.setOrigin( '0 0 30' );

	// light beam
	sys.setSpawnArg( "name", getName() + "_lightbeam" );
    sys.setSpawnArg( "model", getKey( "model_lightbeam" ) );
	sys.setSpawnArg( "noclipmodel", "1" );
	classname = getKey( "def_light2" );
	light_beam = sys.spawn( "func_static" );
	light_beam.bindToJoint( self, "head", true );
	light_beam.setOrigin( '0 0 30' );
	light_beam.setAngles( '0 0 -90' );

	last_enemy_sight = 0;
	lost_enemy();

	setMoveType( MOVETYPE_FLY );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );

	if ( guardian ) {
		setState( "state_Inactive" );
	} else {
		setState( "state_Idle" );
	}
}

void monster_boss_guardian_seeker::destory() {
	light_beam.remove();
	light1.remove();
	light2.remove();
}

void monster_boss_guardian_seeker::respawnSeeker( entity enemy ) {
	setEnemy( enemy );
	setState( "state_Respawn" );
}

void monster_boss_guardian_seeker::state_Respawn() {
	float health;
	vector ang;
	vector dir;

	ang_y = sys.random( 360 );
	dir = sys.angToForward( ang );
	setAngles( ang );

	setOrigin( guardian.spawner.getWorldOrigin() - '0 0 48' + dir * 82 );
	waitUntil( canBecomeSolid() );
	clearBurn();
	show();
	health = getFloatKey( "health" );
	setHealth( health );
	setMoveType( MOVETYPE_FLY );
	setEnemy( guardian.getEnemy() );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );

	moveToPosition( getOrigin() + dir * 512 );

	// invulnerable for a bit so player can't just keep firing rockets at spawn location
	ignoreDamage();

	waitFrame();

	light_beam.show();
	light1.On();
	light2.On();

	sys.wait( 2 );
	allowDamage();
	setState( "state_Idle" );
}

void monster_boss_guardian_seeker::state_Inactive() {
	AI_DEAD = true;
	light_beam.hide();
	light1.Off();
	light2.Off();
	hide();
	while( 1 ) {
		waitFrame();
	}
}

void monster_boss_guardian_seeker::state_Idle() {
	wait_for_enemy();
	guardian.setEnemy( getEnemy() );
	setState( "state_FindPlayer" );
}

void monster_boss_guardian_seeker::state_Killed() {
	guardian.AI_PAIN = true;
	light_beam.hide();
	light1.Off();
	light2.Off();
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	burn();
	startSound( "snd_burn", SND_CHANNEL_BODY, false );
	sys.wait( 4 );
	hide();
	clearBurn();

	if ( !guardian ) {
		remove();
	}

	waitUntil( 0 );
}

void monster_boss_guardian_seeker::state_WatchPlayer() {
	float getCloserTime;
	float range;

	getCloserTime = sys.getTime() + SEEKER_GETCLOSER_DELAY;
	eachFrame {
		faceEnemy();
		moveToEnemyHeight();
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
			continue;
		}
		
		if ( AI_DAMAGE ) {
			setState( "state_RunAway" );
		}

		if ( !AI_ENEMY_VISIBLE ) {
			lost_enemy();
			setState( "state_FindPlayer" );
		}

		range = enemyRange2D();
		if ( range < SEEKER_TOOCLOSE_RANGE ) {
			lost_enemy();
			setState( "state_Retreat" );
		}

		if ( range > SEEKER_TOOFAR_RANGE ) {
			if ( sys.getTime() > getCloserTime ) {
				setState( "state_GetCloser" );
			}
		}

		if ( AI_ENEMY_IN_FOV ) {
			see_enemy();
		}
	}
}

void monster_boss_guardian_seeker::state_GetCloser() {
	float getCloserTime;
	float range;

	setFlySpeed( fly_speed );
	getCloserTime = sys.getTime() + SEEKER_GETCLOSER_TIME;
	moveToEnemy();

	while( !AI_ENEMY_DEAD ) {
		if ( AI_MOVE_DONE && !enemyPositionValid() ) {
			// Cheat
			locateEnemy();
			moveToEnemy();
		}

		if ( !AI_ENEMY_VISIBLE ) {
			lost_enemy();
			setState( "state_FindPlayer" );
		}
		if ( AI_DAMAGE ) {
			setState( "state_RunAway" );
		}
		range = enemyRange2D() - sys.vecLength( getLinearVelocity() ) * 0.25;
		if ( range < SEEKER_TOOCLOSE_RANGE ) {
			lost_enemy();
			setState( "state_Retreat" );
		}

		if ( range < SEEKER_IDEAL_RANGE ) {
			setState( "state_WatchPlayer" );
		}
		
		if ( AI_ENEMY_IN_FOV ) {
			see_enemy();
		}

		waitFrame();
	}
	setState( "state_WatchPlayer" );
}

void monster_boss_guardian_seeker::state_FindPlayer() {
	float visTime;
	boolean visible;

	visible = false;
	moveToEnemy();
	while( !AI_ENEMY_DEAD ) {
		if ( AI_MOVE_DONE && !enemyPositionValid() ) {
			// Cheat
			locateEnemy();
			moveToEnemy();
		}
		if ( AI_DAMAGE ) {
			setState( "state_RunAway" );
		}
		// don't spot the player instantly
		if ( AI_ENEMY_VISIBLE ) {
			if ( !visible ) {
				visTime = sys.getTime() + 0.5;
				visible = true;
			} else if ( sys.getTime() > visTime ) {
				break;
			}
		} else {
			visible = false;
		}

		waitFrame();
	}

	setFlySpeed( fly_speed );

	setState( "state_WatchPlayer" );
}

void monster_boss_guardian_seeker::state_Retreat() {
	float run_time;

	setFlySpeed( SEEKER_ESCAPE_SPEED );

	run_time = sys.getTime() + SEEKER_RUNTIME;
	moveOutOfRange( getEnemy(), enemyRange2D() + 200 );
	while( !AI_ENEMY_DEAD && AI_ENEMY_VISIBLE ) {
		if ( AI_MOVE_DONE ) {
			// can't find a place to run to so just move randomly
			wander();
		}
		if ( AI_DAMAGE ) {
			setState( "state_RunAway" );
		}
		if ( AI_ENEMY_IN_FOV ) {
			see_enemy();
		}
		if ( ( sys.getTime() > run_time ) || ( ( enemyRange2D() + sys.vecLength( getLinearVelocity() ) * 0.5 ) > SEEKER_MAXIMUM_RETREAT_RANGE ) ) {
			break;
		}
		waitFrame();
	}
	setState( "state_WatchPlayer" );
}

void monster_boss_guardian_seeker::state_RunAway() {
	float run_time;
	float lastSightTime;

	setFlySpeed( SEEKER_ESCAPE_SPEED );

	AI_DAMAGE = false;
	sys.wait( 0.5 );
	moveOutOfRange( getEnemy(), enemyRange2D() + 200 );
	run_time = sys.getTime() + SEEKER_RUNTIME;
	lastSightTime = sys.getTime();
	while( !AI_ENEMY_DEAD ) {
		if ( AI_MOVE_DONE ) {
			// can't find a place to run to so just move randomly
			wander();
		}
		// run away until we haven't seen the player for a bit
		if ( AI_ENEMY_VISIBLE ) {
			lastSightTime = sys.getTime();
			if ( AI_ENEMY_IN_FOV ) {
				see_enemy();
			}
		} else if ( sys.getTime() > lastSightTime + 0.5 ) {
			break;
		}
		if ( AI_DAMAGE ) {
			run_time = sys.getTime() + SEEKER_RUNTIME;
			AI_DAMAGE = false;
		}
		if ( sys.getTime() > run_time ) {
			if ( ( enemyRange2D() + sys.vecLength( getLinearVelocity() ) * 0.5 ) > SEEKER_MAXIMUM_RETREAT_RANGE ) {
				break;
			}
		}
		waitFrame();
	}

	setFlySpeed( fly_speed );
	setState( "state_WatchPlayer" );
}

//@doomscript-blueprint begin 6
//@source D357D564
//@catalog 0C260740
//@node A965A5FD-0 40 40
//@node D357C3F1-0 330 40
//@node 3494F854-0 610 40
//@node E846FB20-0 890 200
//@node C29ABDF0-0 685 305
//@node 2A6DABCF-0 480 305
//@node 2CDCCF2A-0 1170 200
//@node BADF3FC5-0 965 305
//@node F83E2215-0 760 305
//@node 70ABDBF4-0 40 40
//@node 60C5CFAF-0 330 40
//@node B20CC63F-0 610 40
//@node 7BA90F51-0 890 200
//@node 739529B9-0 685 305
//@node 4D3B69F4-0 480 305
//@node FBB030AF-0 1170 200
//@node 8130BCAA-0 965 305
//@node 37FB1682-0 760 305
//@node 073D12BB-0 40 40
//@node 40702AAA-0 330 40
//@node F3AA368C-0 105 145
//@node A14FCD7A-0 610 40
//@node DFBC9559-0 405 232
//@node 5E5EFCA4-0 890 40
//@node DAE37AC8-0 1170 40
//@node 482D196B-0 965 145
//@node E2A67FF2-0 1450 40
//@node 1F6E8069-0 1010 145
//@node 44B7A859-0 1240 145
//@node 6F8043D4-0 1730 200
//@node 3578D061-0 1525 305
//@node 6BD2DF25-0 2010 360
//@node 5DBEC6A9-0 1785 465
//@node 7F9CEAE8-0 2290 360
//@node 0E3C70D1-0 2085 465
//@node 60F07FBA-0 1880 465
//@node A8894951-0 1880 549
//@node 82BCC459-0 2570 520
//@node CAD37085-0 2850 200
//@node 1ED0B496-0 3130 40
//@node 2B7722CD-0 3410 40
//@node 24EB1419-0 40 40
//@node 318B58EF-0 330 40
//@node 649298FE-0 610 40
//@node 52BF623D-0 170 145
//@node 8215F9ED-0 400 145
//@node CF1DC1E7-0 890 200
//@node 408F6EF5-0 1170 40
//@node 5BC9E24D-0 1450 40
//@node B9E4CA33-0 40 40
//@node 45C7E93A-0 330 40
//@node 579881B5-0 40 40
//@node FBCB2CF5-0 330 40
//@node B6D296BB-0 105 145
//@node 519C17DC-0 610 200
//@node 40D11E05-0 890 40
//@node 34EC9D78-0 685 145
//@node B375D5C5-0 1170 40
//@node 447A855E-0 1450 40
//@node 09265901-0 1730 40
//@node 5C42AAD2-0 40 40
//@node 1BEABD54-0 330 40
//@node 3F6AD5CB-0 610 40
//@node B484F9E9-0 40 40
//@node 3B06ADC3-0 330 40
//@node EF1225A2-0 105 145
//@node 69686118-0 610 40
//@node 82B29953-0 405 145
//@node 6291A8E9-0 890 200
//@node 1627F967-0 665 305
//@node 4FA879E9-0 1170 200
//@node C77D8403-0 965 305
//@node 7F22001F-0 760 305
//@node 48BE217E-0 1450 360
//@node 4E657C68-0 1245 460
//@node BE52C442-0 1040 460
//@node 836C4156-0 1730 200
//@node DABB61C6-0 2010 40
//@node 174BC995-0 1785 145
//@node 60C110EF-0 1580 245
//@node 6B9A2332-0 1375 245
//@node 0655AE75-0 2290 40
//@node 9030E22B-0 2085 140
//@node BBAC1450-0 1880 140
//@node 0F031F42-0 2570 40
//@node 8A76DFAC-0 2345 145
//@node 86F7C399-0 2850 40
//@node 35DB2D29-0 2625 145
//@node 5D865795-0 2420 245
//@node 5150B0EE-0 3130 40
//@node 65E6AFB2-0 2925 232
//@node 2A2FB8E3-0 2720 232
//@node 90F32DB3-0 3410 40
//@node E68A7F9A-0 3970 40
//@node 2E82F86C-0 4250 40
//@node 19D70328-0 4530 40
//@node 41F3112E-0 4810 40
//@node ED1B6EFF-0 4325 232
//@node 040C06B6-0 4120 232
//@node A301FAC8-0 5090 40
//@node 9490B7CE-0 4605 140
//@node 59195A09-0 4400 140
//@node EA82A233-0 5090 40
//@node 85B50CDD-0 4865 145
//@node 3B858C58-0 5370 40
//@node A63D4DA6-0 5145 145
//@node A5560D07-0 4940 245
//@node 140629A1-0 5930 40
//@node 4BA3899F-0 5445 232
//@node 95B86C1E-0 5240 232
//@node B365A930-0 6210 40
//@node 63B33839-0 6490 40
//@node DF15A6D0-0 6005 140
//@node DC240A63-0 5800 140
//@node CFFB28AB-0 6770 40
//@node 9120F402-0 7050 40
//@node EA82A233-1 7050 40
//@node 6FED0CFC-0 6825 145
//@node 28D612C4-0 7330 40
//@node 398D6A94-0 7105 145
//@node 16C507A9-0 7890 40
//@node 6D4DD007-0 7405 232
//@node 1197C86A-0 7200 232
//@node 170B8F48-0 8170 40
//@node C7A43933-0 8450 40
//@node E616E1C7-0 8450 40
//@node 8E394611-0 8245 145
//@node 615B4D40-0 9010 40
//@node 587A8F67-0 9290 40
//@node 06D8ABAD-0 9570 40
//@node 233CB12A-0 9570 40
//@node D3A5EE8F-0 9365 145
//@node A157003F-0 10130 200
//@node E24C84B8-0 10690 200
//@node C7D96BB9-0 40 40
//@node BC912199-0 330 40
//@node 686970A0-0 610 40
//@node EC8F5E69-0 890 40
//@node C827898A-0 40 40
//@node AE371D94-0 330 40
//@node 51A11E73-0 610 40
//@node 015A1F07-0 40 40
//@node F8F43542-0 330 40
//@node 6052849C-0 105 145
//@node D382FB07-0 610 40
//@node 825367E5-0 385 145
//@node 46405020-0 180 245
//@node 7712EED5-0 890 40
//@node 18FC8097-0 685 140
//@node 7C6B248E-0 1170 40
//@node 409CA0E2-0 965 140
//@node 7E19E673-0 760 140
//@node 7BF09DF0-0 760 218
//@node 2899663F-0 760 296
//@node 9C828449-0 1450 40
//@node 4A1901B3-0 1730 40
//@node 3F0B3122-0 2010 40
//@node D156F8FE-0 2290 40
//@node 95DA62BD-0 2065 145
//@node 452B4381-0 1860 245
//@node 854086BA-0 1655 245
//@node 37461D4F-0 2570 40
//@node FBD6C5F2-0 2365 140
//@node A9F92901-0 2850 40
//@node DC50EB93-0 3130 40
//@node D33A0201-0 2925 140
//@node 79E7E3AF-0 2720 140
//@node 816FE01B-0 3410 40
//@node 44CA4013-0 3690 40
//@node 0CEE7313-0 3485 140
//@node 31A558B8-0 3280 140
//@node 99700DB0-0 3970 40
//@node EC16E28D-0 4250 40
//@node 8B8BB818-0 4530 40
//@node 3F831C79-0 4810 40
//@node 48987CB8-0 5090 40
//@node 14720601-0 5370 40
//@node C7D66657-0 5650 40
//@node 1A3AB19A-0 5930 40
//@node FBBCA530-0 40 40
//@node 194750FE-0 330 40
//@node 3BBB0433-0 125 145
//@node 5A3C7D56-0 610 40
//@node 7E6FA01E-0 890 40
//@node BE75A7B1-0 1170 40
//@node AD4E9922-0 1450 40
//@node 59C4FB1B-0 1730 40
//@node 7FD1092B-0 1525 145
//@node D7982994-0 2010 200
//@node E44AE9BB-0 40 40
//@node 604B7257-0 330 40
//@node E467FFCB-0 610 40
//@node 626BFF56-0 890 40
//@node 16369A18-0 40 40
//@node 01DBDE75-0 330 40
//@node 0BE1031E-0 610 40
//@node 6103A026-0 890 40
//@node 70EDA1F9-0 1170 40
//@node 9C0F1D95-0 1450 40
//@node 7F2BBD92-0 1730 40
//@node 664BD991-0 2010 40
//@node F21C72DF-0 2290 40
//@node 2DD898DA-0 2570 40
//@node 0C94FCBA-0 2850 40
//@node 92FD618A-0 3130 40
//@node 7E42F44A-0 3410 40
//@node BAD88F7E-0 3205 145
//@node A35AAA44-0 3000 145
//@node 873DAB66-0 3690 200
//@node AC6C0801-0 3970 40
//@node 67155A05-0 40 40
//@node 94D94E51-0 330 40
//@node E324FB95-0 125 145
//@node B144460A-0 610 40
//@node 30619100-0 890 200
//@node A8BB73F4-0 1170 200
//@node B8AFBAC9-0 1450 200
//@node 8DE0413B-0 1245 305
//@node 25875D02-0 1730 360
//@node E9850748-0 2010 360
//@node F40230C7-0 2290 200
//@node 6CE1A1F0-0 2085 305
//@node CE6DF6C1-0 2570 360
//@node 32827E92-0 2850 200
//@node 59FD99F5-0 2645 305
//@node 86E5C761-0 2440 305
//@node A31A8C10-0 3130 360
//@node CD80A400-0 3410 360
//@node 34BEB1B1-0 3690 200
//@node CEA885B6-0 3465 305
//@node C4039720-0 3970 200
//@node 5BB71253-0 3765 305
//@node A83D8E7E-0 3560 305
//@node A31A8C10-1 4250 360
//@node 1F871871-0 4530 360
//@node 5FA5F9EF-0 4810 200
//@node 5B7EA01B-0 4605 305
//@node 1F07AAD1-0 4400 305
//@node F8D933A1-0 5090 360
//@node 657033AB-0 4885 465
//@node 8AD2B2DD-0 4680 465
//@node 4926832C-0 5370 520
//@node 8D7F53E0-0 5650 200
//@node 07671562-0 5445 305
//@node 3B6E71F1-0 5930 360
//@node 5696D525-0 40 40
//@node F3B4AF78-0 330 40
//@node 48004329-0 125 140
//@node 2A23C399-0 610 40
//@node 709D0D36-0 405 145
//@node 34D50441-0 890 40
//@node A990FACA-0 1170 40
//@node C1C002A1-0 965 145
//@node C70D2E99-0 760 145
//@node 0E376FA3-0 1450 200
//@node C280A133-0 1225 305
//@node 3B1FCF53-0 1730 360
//@node 34D50441-1 2010 360
//@node DA37DAC2-0 2290 200
//@node 9608D6A2-0 2085 305
//@node 336AF6BC-0 1880 305
//@node 705DB010-0 2570 360
//@node 232B6800-0 2850 360
//@node 3F07E037-0 3130 200
//@node 8BA19C22-0 2925 305
//@node 80EFC2C1-0 3410 360
//@node 52450E5E-0 3690 200
//@node 8A12CEFC-0 3485 305
//@node B6FB8990-0 3970 200
//@node 894E8179-0 3765 305
//@node 14865560-0 3560 305
//@node 705DB010-1 4250 360
//@node D208E471-0 4530 360
//@node B587136D-0 4810 200
//@node F37B6094-0 4605 305
//@node DD17E9AC-0 4400 305
//@node E0352C50-0 5090 360
//@node 27139AD0-0 5370 200
//@node 0B13C60F-0 5165 305
//@node 48A53DF1-0 5650 360
//@node 43B75E93-0 5930 200
//@node E0352C50-1 6210 40
//@node A29DD27B-0 40 40
//@node E880C981-0 330 40
//@node 3F779816-0 125 145
//@node 11232C8B-0 610 40
//@node 22DE8798-0 890 40
//@node C903BF88-0 685 145
//@node 792B88B4-0 480 145
//@node 57B371BD-0 1170 200
//@node 6F76C767-0 945 305
//@node 80D15529-0 1450 360
//@node 11232C8B-1 1730 360
//@node 98A7B001-0 2010 200
//@node F7CA8D89-0 1805 305
//@node 7052C2E7-0 2290 360
//@node B012B04B-0 2570 200
//@node D051804E-0 2365 305
//@node 14D26530-0 2850 360
//@node 283BFEC0-0 2645 465
//@node 5FCC8C60-0 2440 465
//@node 24B850B4-0 3130 520
//@node 35D74BAE-0 2925 625
//@node 79A89F62-0 3410 520
//@node 32E27757-0 3205 625
//@node 07E0AA5E-0 3690 520
//@node 267E7EF8-0 3485 625
//@node 8203DD2C-0 3280 625
//@node 00B084F2-0 3970 520
//@node E880C981-1 4530 360
//@node 3BA912AD-0 4325 465
//@node 40046FE1-0 4810 200
//@node A77ECD06-0 5090 40
//@node E610482D-0 4885 140
//@node 07B877DE-0 5370 40
//@node 49C638E8-0 40 40
//@node 91B210EF-0 330 40
//@node 8B3B19A8-0 610 40
//@node 08ADE837-0 405 145
//@node 3BE76E93-0 890 40
//@node B17348AB-0 1170 40
//@node A3DE2786-0 965 145
//@node A2D1DE8C-0 760 145
//@node 003885D0-0 760 229
//@node 635D80C7-0 1450 200
//@node 6D6FA7A3-0 1245 305
//@node 55255255-0 1730 360
//@node B2A0DFA8-0 2010 200
//@node 34CC383C-0 1805 305
//@node C695B02E-0 2290 360
//@node F89CC4DB-0 2570 200
//@node AB96371A-0 2365 305
//@node 36334522-0 2850 360
//@node 1529689E-0 3130 200
//@node F333EC90-0 2925 305
//@node 1EC2446A-0 2720 305
//@node 7B88F525-0 3410 360
//@node 29488B04-0 3690 200
//@node A968D663-0 3970 40
//@node 6D801168-0 40 40
//@node 7F90E7FB-0 330 40
//@node 55D1F2DE-0 610 40
//@node 2B42DC1D-0 405 145
//@node 8801D0C1-0 890 40
//@node BFEC26F7-0 1170 40
//@node 6CACFA80-0 1450 40
//@node 838C1A7D-0 1245 145
//@node F125B65E-0 1730 40
//@node 8053DE2D-0 1505 145
//@node ED19D2DB-0 2010 40
//@node 04BE82DF-0 1805 145
//@node 4FA64E3F-0 1600 145
//@node 79EAF77B-0 2290 200
//@node E4F7BF17-0 2085 305
//@node BFDC5FC9-0 2570 360
//@node C6D10944-0 2850 200
//@node F1D5817B-0 2645 305
//@node F125B65E-1 3130 360
//@node ECBB2CF2-0 2905 465
//@node 4D248A8F-0 3410 360
//@node E92562D2-0 3205 465
//@node A2DA3386-0 3690 520
//@node 52686CB2-0 3970 360
//@node F094C44C-0 3765 465
//@node 0DE3CDD6-0 3560 465
//@node B68D1FBD-0 4250 360
//@node 70B7C29C-0 4530 200
//@node 01763243-0 4325 305
//@node 6CACFA80-1 4810 360
//@node 489DFB94-0 4605 465
//@node 55D1F2DE-1 5090 360
//@node CADFDA86-0 4885 465
//@node 95030756-0 5370 200
//@node B90DD006-0 5165 305
//@node 93A38120-0 4960 305
//@node EA9A5354-0 5650 360
//@node DE4713A8-0 5445 465
//@node B68D1FBD-1 5930 520
//@node 9C19A518-0 6210 200
//@node 2A2EF15D-0 6490 40
//@node 480765D3-0 6285 140
//@node 429FA467-0 6770 40
//@doomscript-blueprint end
