/***********************************************************************

ai_monster_demon_revenant.script

monster_demon_revenant

***********************************************************************/

#define REV_WALKTURN		65
#define REV_ATTACK_RATE		1.2
#define REV_DODGE_RATE		8
#define REV_NOFOVTIME		4

object monster_demon_revenant : monster_base {
	float		nextDodge;
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;
	string		range_attack_anim;

	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_revenant::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN ) { animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 ); }
	}
}

void monster_demon_revenant::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 7 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 7 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 7 );
}

void monster_demon_revenant::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_revenant::Torso_RangeAttack() {
	string anim;
	
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, range_attack_anim );
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}

	allowMovement( true );
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_revenant::Torso_TurretAttack() {
	allowMovement( false );
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "turret_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "turret_attack" );
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_revenant::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 2 ); }
	}
}

void monster_demon_revenant::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 ); }
	}
}

void monster_demon_revenant::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 2 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 );
}

void monster_demon_revenant::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 2 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_revenant::init
=====================
*/
void monster_demon_revenant::init() {
	walk_turn = REV_WALKTURN;
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_revenant::state_Begin
=====================
*/
void monster_demon_revenant::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );	

	monster_begin();
	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_demon_revenant::state_Idle
=====================
*/
void monster_demon_revenant::state_Idle() {
	wait_for_enemy();
	
	nextAttack		= 0;
	nextNoFOVAttack = 0;
	nextDodge		= RandomTime( REV_DODGE_RATE );
	
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_revenant::do_attack
=====================
*/
void monster_demon_revenant::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + REV_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_demon_revenant::check_attacks
=====================
*/
float monster_demon_revenant::check_attacks() {
	float	currentTime;
	float	canMelee;
	float	attack_flags;
	float	range;
	string	anim;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			range_attack_anim = chooseAnim( ANIMCHANNEL_LEGS, "turret_attack" );
			if ( canHitEnemyFromAnim( range_attack_anim ) ) {
				attack_flags |= ATTACK_MISSILE;
			}

			anim = chooseAnim( ANIMCHANNEL_LEGS, "range_attack" );
			if ( testAnimMoveTowardEnemy( anim ) ) {
				if ( canHitEnemyFromAnim( anim ) ) {
					range_attack_anim = anim;
					attack_flags |= ATTACK_MISSILE;
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_revenant::combat_range
=====================
*/
void monster_demon_revenant::combat_range() {
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 2 );
	waitAction( "range_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( REV_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + REV_NOFOVTIME;
}

/*
=====================
monster_demon_revenant::combat_melee
=====================
*/
void monster_demon_revenant::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_revenant::combat_dodge_left
=====================
*/
void monster_demon_revenant::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( REV_DODGE_RATE );
	moveToEnemy();
}

/*
=====================
monster_demon_revenant::combat_dodge_right
=====================
*/
void monster_demon_revenant::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( REV_DODGE_RATE );
	moveToEnemy();
}

//@doomscript-blueprint begin 6
//@source A63D0BD7
//@catalog 0C260740
//@node 19C4B657-0 40 40
//@node 9C68131E-0 330 40
//@node A93AEC1E-0 610 40
//@node 18EE9D94-0 890 200
//@node B66AA132-0 685 305
//@node A4B6E87F-0 480 305
//@node 13D594E9-0 40 40
//@node 41B9DC48-0 330 40
//@node 624322E5-0 105 145
//@node AB168454-0 610 40
//@node 79F421C9-0 405 232
//@node 7D00FC62-0 890 40
//@node DF7AB459-0 685 145
//@node 1812876B-0 1170 40
//@node 9DA7EA79-0 730 145
//@node 1D2E9649-0 960 145
//@node 451A3966-0 1450 200
//@node 31F345CF-0 1245 305
//@node 18797683-0 1730 360
//@node 94BA005B-0 1505 465
//@node 01E19A8A-0 2010 360
//@node 304F51A9-0 1805 465
//@node E014BFD6-0 1600 465
//@node 208FFF5D-0 1600 549
//@node 7896D044-0 2290 520
//@node 17AD1A03-0 2570 200
//@node C3D2F008-0 2850 40
//@node 6476DD86-0 3130 40
//@node 8202930F-0 40 40
//@node A2F0C295-0 330 40
//@node 07916E36-0 610 40
//@node 7EB8A1C5-0 170 145
//@node 3F927A55-0 400 145
//@node B1DDA57D-0 890 200
//@node 1DEB1FC7-0 1170 40
//@node 78739465-0 1450 40
//@node B781964A-0 40 40
//@node A2CE66B0-0 330 40
//@node B82770C9-0 610 40
//@node B5F421C3-0 890 40
//@node 0069A6C1-0 685 232
//@node 43EFB9A5-0 1170 40
//@node 567DBD5E-0 730 145
//@node D8DA6F6E-0 960 145
//@node 54E00A8B-0 1450 200
//@node 291D5CAE-0 1730 200
//@node A1F1CBF0-0 2010 40
//@node C39752B9-0 2290 40
//@node 49818C72-0 2570 40
//@node BC8FEC2B-0 40 40
//@node B622D500-0 330 40
//@node E5983BCF-0 610 40
//@node 6D57AA22-0 890 40
//@node A1F4E2BF-0 1170 40
//@node 62925280-0 1450 40
//@node B5A1DD9E-0 1010 145
//@node 71C6394E-0 1240 145
//@node 9A205DE5-0 1730 200
//@node 8929EF6D-0 2010 40
//@node 2AEAE4A3-0 2290 40
//@node 0625654F-0 2570 40
//@node 3977791F-0 40 40
//@node FE128AD2-0 330 40
//@node A472F250-0 610 40
//@node FBADA910-0 890 200
//@node 0920331B-0 685 305
//@node 4FC399E1-0 480 305
//@node B6A4D214-0 40 40
//@node 55237953-0 330 40
//@node 46F12CEB-0 610 40
//@node F8B4F387-0 890 200
//@node 8D318A66-0 685 305
//@node D102CF5E-0 480 305
//@node 12D4DEF5-0 40 40
//@node 4E871581-0 330 40
//@node E5ABC5AC-0 610 40
//@node 7EF52C0F-0 170 145
//@node 472C93FF-0 400 145
//@node F8CF4687-0 890 200
//@node 1B161EB7-0 1170 40
//@node 9B0507E5-0 1450 40
//@node 23BE090E-0 40 40
//@node A8274F3F-0 330 40
//@node DF7E5F8F-0 610 40
//@node 938CD6C4-0 170 145
//@node 5D011414-0 400 145
//@node 3771C9E6-0 890 200
//@node 37E34EC8-0 1170 40
//@node AEF61BA0-0 1450 40
//@node B3A4D893-0 40 40
//@node 4E3235D5-0 330 40
//@node B91A0457-0 125 145
//@node 2986834D-0 610 40
//@node D721057C-0 40 40
//@node 61E76E12-0 330 40
//@node A194C894-0 610 40
//@node C3195BEE-0 890 40
//@node 01AB554E-0 1170 40
//@node A663DCC5-0 1450 40
//@node FBE2D721-0 40 40
//@node 3CC44539-0 330 40
//@node FA42E79B-0 610 40
//@node 77DA9411-0 405 145
//@node 9F11D55B-0 890 40
//@node 93ECA1F4-0 685 145
//@node D2D5B815-0 1170 40
//@node 007BF294-0 945 145
//@node 337D8136-0 1450 40
//@node C15B86C9-0 40 40
//@node 1D8A3582-0 330 40
//@node D0190FF7-0 125 145
//@node 51017DA7-0 610 40
//@node 13A4F54E-0 405 145
//@node E13EA4F5-0 890 200
//@node 271EB38B-0 1170 200
//@node 77BC3355-0 965 305
//@node 2C9B3990-0 1450 200
//@node 4DB5E104-0 1730 200
//@node C10BCDAD-0 1525 305
//@node 72233343-0 2010 200
//@node 524AE695-0 1805 300
//@node 458761E1-0 2290 200
//@node 956540DE-0 2085 305
//@node AE3C374E-0 2570 200
//@node 64B04C15-0 2850 200
//@node B237E65C-0 2645 305
//@node 555293A9-0 3130 200
//@node EA7FAE65-0 40 40
//@node A8019162-0 330 40
//@node 3095304F-0 125 145
//@node 8E81BD01-0 610 40
//@node FE590C70-0 385 145
//@node 1321EB89-0 890 40
//@node C64A5F15-0 665 145
//@node 5D0678F4-0 1170 40
//@node D25F814D-0 965 145
//@node 49D8B089-0 760 145
//@node 6E311334-0 1450 200
//@node 88E0FFC1-0 1245 305
//@node 8005583D-0 1040 305
//@node 02FBF0EA-0 1040 389
//@node 9E9FB495-0 1040 389
//@node 6AFCC867-0 1730 360
//@node 5BC3319D-0 1505 465
//@node 611C1584-0 2010 520
//@node 83595CC6-0 2290 360
//@node 47E479FD-0 2065 465
//@node F7F371E9-0 2570 520
//@node F1D761B7-0 2850 520
//@node D3E8B1CA-0 2645 625
//@node 34EAE027-0 2440 625
//@node 599C25E2-0 3130 680
//@node 68E72D49-0 2925 785
//@node 24FF5FC3-0 3410 840
//@node DDE1A216-0 3970 840
//@node A884AEE8-0 4250 200
//@node 3BA7A61F-0 4025 305
//@node 415923A8-0 4530 200
//@node 49527E49-0 4325 305
//@node DF0F37AC-0 4810 360
//@node BA401547-0 5090 40
//@node 2479F69D-0 4885 145
//@node 9FA4CB6F-0 5370 200
//@node 66AB0A8A-0 5650 40
//@node 92A43098-0 5445 145
//@node B369CDA0-0 5240 145
//@node 461BCE45-0 5240 229
//@node CF3F6C75-0 5240 145
//@node AAB3B34B-0 5930 200
//@node 1A091750-0 5725 305
//@node 99709043-0 5520 305
//@node AD53088C-0 5520 389
//@node 0A8267CA-0 6210 360
//@node 2298F459-0 5985 465
//@node 10170350-0 6490 360
//@node 3C35330C-0 6265 465
//@node 3364185E-0 6060 565
//@node 7883B06B-0 6770 520
//@node EDCBFDFE-0 7050 360
//@node 14A7430A-0 6825 465
//@node 7B619082-0 7330 360
//@node 1277E06F-0 7105 465
//@node 8F97410E-0 6900 565
//@node CFFFE8E7-0 7610 520
//@node 4B54BE89-0 7385 625
//@node 32EA5D65-0 7180 725
//@node BD5D5019-0 7890 680
//@node 9C8326A8-0 7685 785
//@node 7883B06B-1 8170 680
//@node 29723E28-0 8450 40
//@node 6A8DFB27-0 40 40
//@node 49DB9F0E-0 330 40
//@node A56908C2-0 610 40
//@node 49C43366-0 890 40
//@node 7F5EAA4D-0 1170 40
//@node 42300B66-0 945 145
//@node 47F71BBE-0 1450 40
//@node 8A50A3AD-0 1245 145
//@node 24853C32-0 40 40
//@node C04C444F-0 330 40
//@node D73677FD-0 610 40
//@node B91B1F77-0 890 40
//@node E0C8C9C8-0 1170 40
//@node 8AD5DCF7-0 1450 40
//@node 2843DB3B-0 40 40
//@node DE230876-0 330 40
//@node 00F8AEFA-0 610 40
//@node FE978ED9-0 890 40
//@node E0531B6F-0 1170 40
//@node 2E4D8A6F-0 1450 40
//@node C4B8A49F-0 1225 145
//@node 1745800F-0 1730 40
//@node 5B3FD904-0 40 40
//@node 7559143D-0 330 40
//@node 4A52305F-0 610 40
//@node 1FF87879-0 890 40
//@node 897A131C-0 1170 40
//@node B0C402F8-0 1450 40
//@node 5EA5931B-0 1225 145
//@node D855160E-0 1730 40
//@doomscript-blueprint end
