/***********************************************************************

ai_monster_zombie_security_pistol.script

monster_zombie_sergeant
monster_zsec_shotgun
monster_zsec_p90_helmet
monster_zsec_p90_zombie
monster_zsec_pistol_shield

***********************************************************************/

#define ZSECP_RUNDISTANCE				192
#define ZSECP_WALKTURN					65
#define ZSECP_DODGE_RATE				3
#define ZSECP_ATTACK_DELAY_MIN			0.5
#define ZSECP_ATTACK_DELAY_MAX			2
#define ZSECP_ATTACK_MAX_LENGTH			3
#define ZSECP_ATTACK_MIN_LENGTH			1
#define ZSECP_WAIT_MIN_LENGTH			0.3
#define ZSECP_WAIT_MAX_LENGTH			1.5
#define ZSECP_CROUCH_ATTACK_MAX_LENGTH	15
#define ZSECP_CROUCH_ATTACK_MIN_LENGTH	3
#define ZSECP_STAND_ATTACK_MAX_LENGTH	15
#define ZSECP_STAND_ATTACK_MIN_LENGTH	3
#define ZSECP_ATTACK_MIN_SHOOT_TIME		0.5
#define ZSECP_NOFOVTIME					4

#define ATTACK_ZSECP_CROUCHFIRE			ATTACK_SPECIAL1

// start out with a 50/50 chance of stand vs. crouch attacks.
float zsecp_num_stand_attacks = 1;
float zsecp_num_crouch_attacks = 1;

object monster_zombie_security_pistol : monster_zombie_base {
	boolean		fire;
	boolean		crouch_fire;
	boolean		run_attack;
	float		nextDodge;
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;

	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		crouch_attack();
	void		stand_attack();
	void		combat_dodge_left();
	void		combat_dodge_right();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	void		Torso_CrouchAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
	void		Legs_StepLeft();
	void		Legs_StepRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_zombie_security_pistol::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	eachFrame {
		if ( AI_PAIN ) {
			Torso_Pain();
			idleAnim( ANIMCHANNEL_TORSO, "stand" );
		}
		if ( fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
		}
		if ( crouch_fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_CrouchAttack", 4 );
		}
	}
}

void monster_zombie_security_pistol::Torso_Pain() {
	string animname;

	animname = getPainAnim();
	setBlendFrames( ANIMCHANNEL_TORSO, 2 );
	playAnim( ANIMCHANNEL_TORSO, animname );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	// no pain for 1 second
	preventPain( 1 );
	
	finishAction( "pain" );
	setBlendFrames( ANIMCHANNEL_TORSO, 4 );
}

void monster_zombie_security_pistol::Torso_RangeAttack() {
	float endtime;
	float mintime;
	boolean first_shot;
	
	setAnimPrefix( "" );

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	first_shot = true;
	while( ( fire || first_shot ) && !sys.influenceActive() ) {
		mintime = sys.getTime() + ZSECP_ATTACK_MIN_SHOOT_TIME;
		endtime = RandomDelay( ZSECP_ATTACK_MIN_LENGTH, ZSECP_ATTACK_MAX_LENGTH );
		while( ( fire || ( sys.getTime() < mintime ) ) && ( sys.getTime() < endtime ) ) {
			playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
			while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
				if ( sys.influenceActive() ) {
					endtime = 0;
					fire = false;
					break;
				}

				if ( AI_FORWARD ) {
					if ( !entityInAttackCone( getEnemy() ) ) {
						endtime = 0;
						fire = false;
						break;
					}
				}

				if ( AI_PAIN ) {
					Torso_Pain();
				}
				waitFrame();
			}
		}

		first_shot = false;
		if ( !fire ) {
			break;
		}

		playCycle( ANIMCHANNEL_TORSO, "range_attack_aim" );
		endtime = RandomDelay( ZSECP_WAIT_MIN_LENGTH, ZSECP_WAIT_MAX_LENGTH );
		while( fire && ( sys.getTime() < endtime ) ) {
			if ( sys.influenceActive() ) {
				fire = false;
				break;
			}
			if ( AI_FORWARD ) {
				if ( !entityInAttackCone( getEnemy() ) ) {
					break;
				}
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_zombie_security_pistol::Torso_TurretAttack() {
	float endtime;
	float mintime;
	boolean first_shot;
	
	setAnimPrefix( "" );
		
	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	first_shot = true;
	while( ( first_shot || canHitEnemyFromAnim( "range_attack_loop" ) ) && !sys.influenceActive() ) {
		mintime = sys.getTime() + ZSECP_ATTACK_MIN_SHOOT_TIME;
		endtime = RandomDelay( ZSECP_ATTACK_MIN_LENGTH, ZSECP_ATTACK_MAX_LENGTH );
		while( ( sys.getTime() < mintime ) || ( ( sys.getTime() < endtime ) && canHitEnemyFromAnim( "range_attack_loop" ) ) ) {
			playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
			while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
				if ( sys.influenceActive() ) {
					endtime = 0;
					break;
				}
				if ( AI_PAIN ) {
					Torso_Pain();
				}
				waitFrame();
			}
		}
		first_shot = false;

		playCycle( ANIMCHANNEL_TORSO, "range_attack_aim" );
		endtime = RandomDelay( ZSECP_WAIT_MIN_LENGTH, ZSECP_WAIT_MAX_LENGTH );
		while( fire && ( sys.getTime() < endtime ) ) {
			if ( sys.influenceActive() ) {
				break;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "turret_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_zombie_security_pistol::Torso_CrouchAttack() {
	float endtime;
	float mintime;
	boolean first_shot;
	
	overrideAnim( ANIMCHANNEL_LEGS );
	
	setAnimPrefix( "crouch" );

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}

	first_shot = true;
	while( ( crouch_fire || first_shot ) && !sys.influenceActive() ) {
		mintime = sys.getTime() + ZSECP_ATTACK_MIN_SHOOT_TIME;
		endtime = RandomDelay( ZSECP_ATTACK_MIN_LENGTH, ZSECP_ATTACK_MAX_LENGTH );
		while( ( crouch_fire || ( sys.getTime() < mintime ) ) && ( sys.getTime() < endtime ) ) {
			playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
			while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
				if ( sys.influenceActive() ) {
					crouch_fire = false;
					endtime = 0;
					break;
				}
				if ( AI_PAIN ) {
					Torso_Pain();
				}
				waitFrame();
			}
		}

		first_shot = false;
		if ( !crouch_fire ) {
			break;
		}

		playCycle( ANIMCHANNEL_TORSO, "range_attack_aim" );
		endtime = RandomDelay( ZSECP_WAIT_MIN_LENGTH, ZSECP_WAIT_MAX_LENGTH );
		while( crouch_fire && ( sys.getTime() < endtime ) ) {
			if ( sys.influenceActive() ) {
				crouch_fire = false;
				endtime = 0;
				break;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 6 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "crouch_attack" );
	setAnimPrefix( "" );
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 6 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_zombie_security_pistol::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( getEnemy() ) {
			run = true;
		}
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
	}
}

void monster_zombie_security_pistol::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( getEnemy() ) {
			run = true;
		}
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void monster_zombie_security_pistol::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( getEnemy() ) {
			run = true;
		}
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void monster_zombie_security_pistol::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void monster_zombie_security_pistol::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void monster_zombie_security_pistol::Legs_StepLeft() {
	playAnim( ANIMCHANNEL_LEGS, "step_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "sidestep" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void monster_zombie_security_pistol::Legs_StepRight() {
	playAnim( ANIMCHANNEL_LEGS, "step_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}

	finishAction( "sidestep" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_zombie_security_pistol::init
=====================
*/
void monster_zombie_security_pistol::init() {
	run_distance	= ZSECP_RUNDISTANCE;
	walk_turn		= ZSECP_WALKTURN;
	run_attack		= getIntKey( "run_attack" );

	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_zombie_security_pistol::state_Begin
=====================
*/
void monster_zombie_security_pistol::state_Begin() {
	fire = false;
	crouch_fire = false;
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_zombie_security_pistol::state_Idle
=====================
*/
void monster_zombie_security_pistol::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;
	nextDodge		= RandomTime( ZSECP_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_zombie_security_pistol::do_attack
=====================
*/
void monster_zombie_security_pistol::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + ZSECP_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_ZSECP_CROUCHFIRE ) {
		crouch_attack();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		stand_attack();
	}
}

/*
=====================
monster_zombie_security_pistol::check_attacks
=====================
*/
float monster_zombie_security_pistol::check_attacks() {
	float currentTime;
	float attack_flags;
	boolean try_attack;
	boolean reachable;
	
	attack_flags = 0;
	
	currentTime = sys.getTime();
	if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
		if ( testAnimMove( "evade_left" ) ) {
			attack_flags |= ATTACK_DODGE_LEFT;
		}
		if ( testAnimMove( "evade_right" ) ) {
			attack_flags |= ATTACK_DODGE_RIGHT;
			
			// if we can dodge either direction, pick one
			if ( attack_flags & ATTACK_DODGE_LEFT ) {
				if ( sys.random( 100 ) < 50 ) {
					attack_flags &= ~ATTACK_DODGE_RIGHT;
				} else {
					attack_flags &= ~ATTACK_DODGE_LEFT;
				}
			}
		}
	}

	combat_node = getCombatNode();
	if ( combat_node ) {
		attack_flags |= ATTACK_COMBAT_NODE;
	}

	reachable = canReachEnemy();
	if ( AI_ENEMY_IN_FOV && ( !reachable || ( currentTime >= nextAttack ) ) ) {
		try_attack = true;
	} else if ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE && ( !reachable || ( currentTime >= nextAttack ) ) ) {
		try_attack = true;
	} else if ( touches( getEnemy() ) ) {
		try_attack = true;
	} else {
		try_attack = false;
	}

	if ( try_attack ) {
		// adjust the likelyhood of a crouch vs. stand attack based on the # of each.
		if ( sys.random( zsecp_num_stand_attacks + zsecp_num_crouch_attacks ) < zsecp_num_stand_attacks ) {
			if ( canHitEnemyFromAnim( "crouch_range_attack_loop" ) ) {
				attack_flags |= ATTACK_ZSECP_CROUCHFIRE;
			} else if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		} else if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
			attack_flags |= ATTACK_MISSILE;
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_zombie_security_pistol::stand_attack
=====================
*/
void monster_zombie_security_pistol::stand_attack() {
	float attackTime;
	float endtime;
	float left;
	float right;
	float attack_flags;
	boolean do_run_attack;

	zsecp_num_stand_attacks++;

	if ( sys.random( 10 ) < 6 ) {
		do_run_attack = run_attack;
	} else {
		do_run_attack = false;
	}

	fire = true;
	attackTime = RandomDelay( ZSECP_STAND_ATTACK_MIN_LENGTH, ZSECP_STAND_ATTACK_MAX_LENGTH );
	while( AI_ENEMY_VISIBLE ) {
		endtime = RandomDelay( 0.5, 1 );
		while( sys.getTime() < endtime ) {
			if ( sys.influenceActive() ) {
				fire = false;
				break;
			}
			lookAtEnemy( 1 );
			if ( !do_run_attack || ( enemyRange() < 90 ) ) {
				faceEnemy();
			} else if ( !entityInAttackCone( getEnemy() ) ) {
				attackTime = 0;
				break;
			} else {
				moveToEnemy();
			}
			if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
				break;
			}
			if ( AI_PAIN ) {
				attack_flags = check_attacks();
				if ( attack_flags & ( ATTACK_DODGE_LEFT | ATTACK_DODGE_RIGHT ) ) {
					fire = false;
					do_attack( attack_flags );
					return;
				}
			}
			
			waitFrame();
		}

		if ( sys.influenceActive() ) {
			break;
		}
		
		if ( sys.getTime() > attackTime ) {
			break;
		}

		if ( !AI_ENEMY_VISIBLE || !canHitEnemyFromAnim( "range_attack_loop" ) ) {
			break;
		}
		
		left  = testAnimMove( "step_left" );
		right =	testAnimMove( "step_right" );
		if ( left && right ) {
			if ( sys.random( 100 ) < 50 ) {
				left = false;
			} else {
				right = false;
			}
		}
		
		if ( left ) {
			animState( ANIMCHANNEL_LEGS, "Legs_StepLeft", 4 );
			while( inAnimState( ANIMCHANNEL_LEGS, "Legs_StepLeft" ) ) {
				lookAtEnemy( 1 );
				waitFrame();
			}
		} else if ( right ) {
			animState( ANIMCHANNEL_LEGS, "Legs_StepRight", 4 );
			while( inAnimState( ANIMCHANNEL_LEGS, "Legs_StepRight" ) ) {
				lookAtEnemy( 1 );
				waitFrame();
			}
		}
	}
	
	fire = false;
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_RangeAttack" ) ) {
		waitFrame();
	}

	// don't attack for a bit
	nextAttack = RandomDelay( ZSECP_ATTACK_DELAY_MIN, ZSECP_ATTACK_DELAY_MAX );
	nextNoFOVAttack = sys.getTime() + ZSECP_NOFOVTIME;
}
	
/*
=====================
monster_zombie_security_pistol::crouch_attack
=====================
*/
void monster_zombie_security_pistol::crouch_attack() {
	float attackTime;
	float attack_flags;

	zsecp_num_crouch_attacks++;

	faceEnemy();
	crouch_fire = true;
	
	attackTime = RandomDelay( ZSECP_CROUCH_ATTACK_MIN_LENGTH, ZSECP_CROUCH_ATTACK_MAX_LENGTH );
	while( AI_ENEMY_VISIBLE ) {
		if ( sys.influenceActive() ) {
			crouch_fire = false;
			break;
		}
		if ( sys.getTime() > attackTime ) {
			break;
		}
		
		if ( AI_PAIN ) {
			attack_flags = check_attacks();
			if ( attack_flags & ( ATTACK_DODGE_LEFT | ATTACK_DODGE_RIGHT ) ) {
				crouch_fire = false;
				setAnimPrefix( "" );
				do_attack( attack_flags );
				return;
			}
		}
		
		lookAtEnemy( 1 );
		if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
			break;
		}
		waitFrame();
	}
	
	crouch_fire = false;
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_CrouchAttack" ) ) {
		waitFrame();
	}

	// don't attack for a bit
	nextAttack = RandomDelay( ZSECP_ATTACK_DELAY_MIN, ZSECP_ATTACK_DELAY_MAX );
	nextNoFOVAttack = sys.getTime() + ZSECP_NOFOVTIME;
}

/*
=====================
monster_zombie_security_pistol::combat_dodge_left
=====================
*/
void monster_zombie_security_pistol::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( ZSECP_DODGE_RATE );
}

/*
=====================
monster_zombie_security_pistol::combat_dodge_right
=====================
*/
void monster_zombie_security_pistol::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( ZSECP_DODGE_RATE );
}

//@doomscript-blueprint begin 6
//@source 73A7A91B
//@catalog 0C260740
//@node A6306609-0 40 40
//@node DFAEB6BA-0 330 40
//@node 53271DD0-0 610 40
//@node 394ABEDE-0 890 200
//@node 615DB203-0 685 305
//@node 5ABDE217-0 1170 360
//@node DFAEB6BA-1 1450 360
//@node F6984E3D-0 1730 200
//@node 4BB788EC-0 1525 305
//@node B965D8AE-0 2010 360
//@node 295F4BE2-0 2290 200
//@node BC77B465-0 2085 305
//@node 160F3191-0 2570 360
//@node ADEF28E7-0 40 40
//@node 95C16FAE-0 330 40
//@node 281B49A0-0 105 145
//@node 1FBD1B18-0 610 40
//@node D362384E-0 890 40
//@node 6D9231F7-0 685 232
//@node 71E0DBF4-0 1170 40
//@node 1AE01D31-0 730 145
//@node FA803641-0 960 145
//@node E1E58049-0 1450 200
//@node 67F103E2-0 1730 40
//@node 1CF2B48A-0 2010 40
//@node 8428018A-0 2290 40
//@node EC67A314-0 40 40
//@node 875BC2C9-0 330 40
//@node 0A7F94AB-0 610 40
//@node 523AA039-0 890 40
//@node D78FE655-0 450 145
//@node CC8F09C5-0 680 145
//@node 04727341-0 1170 200
//@node 32B497F7-0 965 305
//@node A42B4ECA-0 1450 360
//@node ADBB33B8-0 1730 200
//@node 22486020-0 2010 40
//@node E7A5F74C-0 1805 145
//@node D59F5AC2-0 2290 40
//@node 778E25B6-0 2085 145
//@node 843BA932-0 1880 145
//@node 93242FC9-0 1880 229
//@node 4738F0B7-0 2570 200
//@node BAC47699-0 2365 305
//@node 6B5EB034-0 2850 200
//@node 22A026AF-0 2625 305
//@node 6A03EBB4-0 3130 200
//@node 1DFCE772-0 2925 305
//@node D3C59ECD-0 2720 305
//@node FEC60470-0 2720 389
//@node 1A85258B-0 2720 473
//@node 301B66A2-0 3410 360
//@node 523AA039-1 3690 360
//@node 3284FA38-0 3250 465
//@node 8D67B9E8-0 3480 465
//@node 31249D83-0 3970 520
//@node F12ABD61-0 3745 625
//@node 7BCD5B31-0 4250 680
//@node 02AE99C1-0 4045 785
//@node 34F7C816-0 4530 680
//@node 517FDF1F-0 4325 785
//@node A9935D2D-0 4810 680
//@node E6110DD4-0 5090 520
//@node 1486D1E7-0 4885 625
//@node 4D627F02-0 5370 680
//@node C52D8728-0 4930 785
//@node F9980DF8-0 5160 785
//@node 7BCD5B31-1 5650 840
//@node 942AD47E-0 5445 945
//@node 34F7C816-1 5930 840
//@node 29FF2E68-0 5725 945
//@node A9935D2D-1 6210 840
//@node 04727341-1 6490 520
//@node 63D7C87C-0 6285 625
//@node A42B4ECA-1 6770 680
//@node ADBB33B8-1 7050 520
//@node EBDA94C7-0 7330 200
//@node 42564ACC-0 7125 305
//@node C6F885A1-0 7610 200
//@node 1812ADCC-0 7405 305
//@node 1B0BFA32-0 7200 305
//@node A9935D2D-2 7890 360
//@node 47F7A302-0 8170 200
//@node 50CA9C7A-0 8450 200
//@node 80D40E45-0 8225 305
//@node C25B0F42-0 8730 200
//@node 79D72599-0 8525 305
//@node CCE0C6EE-0 8320 305
//@node 63DFE126-0 8320 389
//@node 31249D83-1 9010 360
//@node 997B0AEE-0 8785 465
//@node 34F7C816-2 9290 520
//@node C54D178D-0 9085 625
//@node A9935D2D-3 9570 520
//@node E6110DD4-1 9850 360
//@node EEED72EE-0 9645 465
//@node 4D627F02-1 10130 520
//@node 00D09031-0 9690 625
//@node F9DAE941-0 9920 625
//@node A9935D2D-4 10410 680
//@node 04727341-2 10690 360
//@node CE09E975-0 10485 465
//@node A42B4ECA-2 10970 520
//@node ADBB33B8-2 11250 360
//@node 3B8357F9-0 11530 40
//@node 328C5245-0 11810 40
//@node D98ED49B-0 11370 145
//@node ECCFA2AB-0 11600 145
//@node 04727341-3 12090 200
//@node 182C23F2-0 11885 305
//@node A42B4ECA-3 12370 360
//@node ADBB33B8-3 12650 200
//@node 6FBA9D03-0 12930 40
//@node AA867A7E-0 13210 40
//@node A51337A5-0 40 40
//@node 48F26E7E-0 330 40
//@node 4440CEE0-0 610 40
//@node E20675D6-0 890 40
//@node F17891BD-0 450 145
//@node 7A3A940D-0 680 145
//@node 4A07E11A-0 1170 200
//@node 5D1B8258-0 965 305
//@node EC9608C3-0 1450 360
//@node ACAB4797-0 1730 200
//@node E82D6191-0 2010 40
//@node 63013BBF-0 1805 145
//@node B769C20F-0 2290 40
//@node 69B59579-0 2085 145
//@node 4C430487-0 1880 145
//@node B044533A-0 2570 200
//@node FDD9DAFB-0 2365 305
//@node DDCC5DC1-0 2850 200
//@node 2C90F006-0 2625 305
//@node 048D9E7B-0 3130 200
//@node A03DB7A7-0 2925 305
//@node FAB86E96-0 2720 305
//@node 85EFBE07-0 2720 389
//@node 84EC9653-0 3410 360
//@node E20675D6-1 3690 360
//@node 621A1DE0-0 3250 465
//@node 506FFB70-0 3480 465
//@node E4A8FF2C-0 3970 520
//@node 17F64A49-0 3745 625
//@node BA15D784-0 4250 680
//@node B22C50F3-0 4045 785
//@node 685F3E60-0 4530 680
//@node 4A07E11A-1 4810 520
//@node DD0CB3A3-0 4605 625
//@node EC9608C3-1 5090 680
//@node ACAB4797-1 5370 520
//@node 12D2AB30-0 5650 200
//@node 949FD843-0 5445 305
//@node D06FD5A7-0 5930 200
//@node D5CA8207-0 6210 200
//@node 8EB74475-0 5985 305
//@node C693E7A9-0 6490 200
//@node 96998F8B-0 6285 305
//@node E03E74E6-0 6080 305
//@node 986153AE-0 6080 389
//@node E4A8FF2C-1 6770 360
//@node 0E1E0B96-0 6545 465
//@node 685F3E60-1 7050 520
//@node 4A07E11A-2 7330 360
//@node 0A46CC2E-0 7125 465
//@node EC9608C3-2 7610 520
//@node ACAB4797-2 7890 360
//@node E871ED02-0 8170 40
//@node 42F6C222-0 8450 40
//@node 788CA761-0 8010 145
//@node 5FBCB9F1-0 8240 145
//@node 4A07E11A-3 8730 200
//@node 81498101-0 8525 305
//@node EC9608C3-3 9010 360
//@node ACAB4797-3 9290 200
//@node AFFD46B7-0 9570 40
//@node E7111EDD-0 9850 40
//@node D49263B1-0 40 40
//@node EB83FFC8-0 330 40
//@node EAA36AC8-0 610 40
//@node 7FB5F484-0 890 40
//@node FD5CA1D2-0 1170 40
//@node C2955C62-0 730 145
//@node 07944AB2-0 960 145
//@node 10846AD6-0 1450 200
//@node 9FB6366C-0 1245 305
//@node E0047ED7-0 1730 360
//@node 61D48103-0 2010 200
//@node E9EB6295-0 2290 40
//@node 5EEFCB8A-0 2085 145
//@node 369BD6AC-0 2570 40
//@node BE0E52C1-0 2365 145
//@node 633A5C30-0 2160 145
//@node FE8724CE-0 2160 229
//@node FB257296-0 2850 200
//@node 5C0DF59A-0 2645 305
//@node 1BFEF86D-0 3130 200
//@node 8D3C9E4F-0 2905 305
//@node 3FD26522-0 3410 200
//@node 90C246ED-0 3205 305
//@node B04CB14B-0 3000 305
//@node A90F7386-0 3000 389
//@node D0F00790-0 3000 473
//@node 199D006F-0 3690 360
//@node FD5CA1D2-1 3970 360
//@node 08802727-0 3530 465
//@node D8DBBE37-0 3760 465
//@node BFC725F0-0 4250 520
//@node 2C8800E3-0 4025 625
//@node 07756068-0 4530 680
//@node 3D4C23AF-0 4325 785
//@node DDD82448-0 4810 680
//@node 28F6A8A3-0 4605 785
//@node 603E7424-0 5090 680
//@node 10846AD6-1 5370 520
//@node B9787327-0 5165 625
//@node E0047ED7-1 5650 680
//@node 61D48103-1 5930 520
//@node F337AA8C-0 6210 200
//@node D13E03E0-0 6005 305
//@node 285C5BEB-0 6490 200
//@node 341B8642-0 6285 305
//@node 95CA6FC4-0 6080 305
//@node 603E7424-1 6770 360
//@node C28D66E3-0 7050 200
//@node 89C34BB3-0 7330 200
//@node 70256889-0 7105 305
//@node 0C52EFB8-0 7610 200
//@node 28AC4284-0 7405 305
//@node A708E34E-0 7200 305
//@node 2EF05399-0 7200 389
//@node BFC725F0-1 7890 360
//@node 79FA28E8-0 7665 465
//@node 07756068-1 8170 520
//@node A5735478-0 7965 625
//@node DDD82448-1 8450 520
//@node 4A5EAB58-0 8245 625
//@node 603E7424-2 8730 520
//@node 10846AD6-2 9010 360
//@node 679D2522-0 8805 465
//@node E0047ED7-2 9290 520
//@node 61D48103-2 9570 360
//@node 30423976-0 9850 40
//@node CF1D6140-0 10130 40
//@node 120EC9A3-0 9690 145
//@node 7F7E14F3-0 9920 145
//@node 10846AD6-3 10410 200
//@node 23CE2365-0 10205 305
//@node E0047ED7-3 10690 360
//@node 61D48103-3 10970 200
//@node 995D32A7-0 11250 40
//@node E3F29792-0 11530 40
//@node 1B02284F-0 11810 40
//@node FBF328FD-0 40 40
//@node B9D71A0E-0 330 40
//@node F682972E-0 610 40
//@node 14DEBA5E-0 890 200
//@node 1C1DECEC-0 665 305
//@node B3B18C05-0 1170 360
//@node 132958FD-0 965 465
//@node 642E9781-0 1450 200
//@node 62188C82-0 1245 305
//@node 07F813FD-0 1040 305
//@node A42E317A-0 1040 389
//@node 989E8734-0 1730 200
//@node C2A8FD7A-0 1525 305
//@node 36901F02-0 1320 305
//@node 007FAFCA-0 40 40
//@node 4314A809-0 330 40
//@node 1558AE59-0 610 40
//@node BA498B75-0 890 200
//@node 5AB27E5C-0 665 305
//@node B1CD038A-0 1170 360
//@node 16169162-0 965 465
//@node 2098E3F4-0 1450 200
//@node 388C33B6-0 1245 305
//@node DBC21E95-0 1040 305
//@node 6A6D61E2-0 1040 389
//@node 46BC38F3-0 1730 200
//@node 9EE7B3E1-0 1525 305
//@node CF49A0A5-0 1320 305
//@node 66520368-0 40 40
//@node D30E4CAB-0 330 40
//@node B03D673F-0 125 232
//@node 2CDB5A1A-0 -80 232
//@node B45A69E9-0 610 40
//@node 9E765A23-0 890 200
//@node D92FD0C2-0 665 305
//@node 7DF02FA6-0 1170 360
//@node 6A294134-0 965 465
//@node F8A41D17-0 1450 200
//@node BE75999A-0 1245 305
//@node AA86FF14-0 1040 305
//@node F5669E21-0 1040 389
//@node 0652CB71-0 1730 200
//@node F3A47472-0 1525 305
//@node AC1CB8D2-0 1320 305
//@node 49CAC6C3-0 40 40
//@node 8079AB6B-0 330 40
//@node 4682CE9C-0 610 40
//@node 3E4D9D5A-0 170 145
//@node 1158854A-0 400 145
//@node 3A72895D-0 890 200
//@node FDE3DDC1-0 1170 40
//@node CB1639ED-0 1450 40
//@node 379CB2CC-0 40 40
//@node 38718391-0 330 40
//@node 69913A2F-0 610 40
//@node 44E8E222-0 170 145
//@node 8CC40CF2-0 400 145
//@node 0F9BD314-0 890 200
//@node 2D87FD5A-0 1170 40
//@node 7C5772D0-0 1450 40
//@node B3F06818-0 40 40
//@node F8E31A07-0 330 40
//@node B77833BF-0 125 232
//@node FC46A7CA-0 -80 232
//@node EF4AB9F7-0 610 40
//@node F7D8CBA1-0 170 145
//@node BF8830D1-0 400 145
//@node 578A2230-0 890 200
//@node 1FBBD2E0-0 1170 40
//@node 064D4CF8-0 1450 40
//@node F5BC21ED-0 40 40
//@node 678DFF49-0 330 40
//@node 27D8DFB4-0 125 232
//@node A00D6FC3-0 -80 232
//@node A9A7A43E-0 610 40
//@node E937F559-0 170 145
//@node 9517C0A9-0 400 145
//@node 8EDC629B-0 890 200
//@node FE83AEA5-0 1170 40
//@node 2342054B-0 1450 40
//@node FCA813FD-0 40 40
//@node 68782BAF-0 330 40
//@node 0455C310-0 125 145
//@node 134A5697-0 610 40
//@node F3134A4A-0 405 145
//@node CBCC44C9-0 890 40
//@node 1FF2FECC-0 665 145
//@node 6D5FD88E-0 460 245
//@node 92666EEB-0 255 245
//@node 196910A7-0 1170 40
//@node F76532DA-0 40 40
//@node 53FC8730-0 330 40
//@node EF510E28-0 125 145
//@node F531B7FF-0 610 40
//@node A03AFE73-0 405 145
//@node C61E516C-0 890 40
//@node 0501D5FE-0 1170 40
//@node 27978138-0 1450 40
//@node 40C18820-0 1730 40
//@node 358D7ED3-0 2010 40
//@node 378E9CC7-0 40 40
//@node 629EAA7B-0 330 40
//@node 3F08DA01-0 610 40
//@node 9B0ACFA6-0 405 145
//@node 79BDECC9-0 890 40
//@node A939D7D5-0 685 145
//@node 0DC5A1B7-0 1170 40
//@node 014CBA06-0 945 145
//@node 1A96F538-0 1450 40
//@node 5AEE814B-0 40 40
//@node 9CEA73C4-0 330 40
//@node 9C6E27D6-0 125 145
//@node AF773889-0 610 40
//@node D4A52AE1-0 405 145
//@node 57D14CB3-0 890 200
//@node 732D45E5-0 1170 200
//@node 9A7CF75A-0 965 305
//@node 7666B87E-0 1450 200
//@node 9FFAE4FA-0 1730 200
//@node B9EEC2E2-0 1525 305
//@node 1342F795-0 2010 200
//@node 75B27D29-0 1805 300
//@node 2CB270D3-0 2290 200
//@node 624AE910-0 2085 305
//@node 8757BDAE-0 2570 200
//@node 168BCC5B-0 2850 200
//@node 0C488C59-0 2645 305
//@node 7AC8FDFA-0 3130 200
//@node 0874B9BB-0 40 40
//@node 2A0AD70C-0 330 40
//@node A2CA172F-0 125 145
//@node 4B6C3A7F-0 610 40
//@node 8D4FEAA2-0 385 145
//@node 3C8B4DF6-0 890 40
//@node 8E183A91-0 685 145
//@node 11819E6D-0 480 145
//@node D0F7D5BA-0 480 229
//@node FFCEFB25-0 480 229
//@node CA611811-0 1170 200
//@node A5666A17-0 945 305
//@node 4DBCD9AA-0 1450 360
//@node 5EC1E448-0 1730 200
//@node 8486A528-0 1505 305
//@node 2ADA6AAF-0 2010 360
//@node 7C4794F5-0 2290 360
//@node 4A963E6B-0 2085 465
//@node 31C2FB52-0 1880 465
//@node ADECBA50-0 2570 520
//@node 0D5B19C0-0 2365 625
//@node 1A012715-0 2850 680
//@node 2AA71688-0 3410 680
//@node 83D11ABE-0 3690 40
//@node 208A2386-0 3465 145
//@node 14E55DD2-0 3970 40
//@node 65B0EB80-0 3765 145
//@node A51E74DE-0 4250 200
//@node F6B792AD-0 4530 40
//@node 8C891EE1-0 4305 145
//@node 1AC2E1AC-0 4810 40
//@node D8B56520-0 4605 145
//@node 4480306C-0 4400 145
//@node 94568C8F-0 4400 229
//@node 94085599-0 4400 313
//@node 94E5D3C1-0 4400 313
//@node E8741A68-0 5090 200
//@node F7532095-0 4885 305
//@node 9154275B-0 5370 200
//@node FCF55886-0 5165 305
//@node AF6E3116-0 4960 305
//@node 1B2D4EE5-0 4960 389
//@node 9A04165A-0 4960 473
//@node 5E5C8E3B-0 4960 473
//@node DBA82F13-0 4960 557
//@node E8741A68-1 5650 200
//@node 14282EEC-0 5445 305
//@node 5E400865-0 5930 200
//@node 6533A163-0 5705 305
//@node E8741A68-2 6210 200
//@node 6F60E72B-0 6005 305
//@node CC1CDECF-0 6770 200
//@node D3B7D922-0 6565 305
//@node 7A7755E9-0 7050 40
//@node 984301E3-0 6845 145
//@node 82EE0E68-0 7330 200
//@node E20417D4-0 7125 305
//@node CB4F73BB-0 6920 305
//@node 4E066D6F-0 6920 389
//@node C0C5E51C-0 7610 360
//@node D949DD72-0 7385 465
//@node 90D1326D-0 7890 520
//@node EC0D4648-0 8170 520
//@node 53A10E29-0 7945 625
//@node 312105A5-0 8450 520
//@node EC0D4648-1 8730 360
//@node 8949E63E-0 8505 465
//@node 312105A5-1 9010 360
//@node 850F6412-0 9290 40
//@node 472EED02-0 40 40
//@node E8CC3937-0 330 40
//@node F1543BC7-0 125 145
//@node 9AEFDA62-0 -80 145
//@node AD97D41C-0 610 40
//@node F82E1618-0 405 145
//@node BB8FDD6F-0 890 200
//@node 9ECEAB68-0 685 305
//@node 846E8C2C-0 1450 200
//@node E5C728B4-0 1245 305
//@node 7D9F69C3-0 1730 40
//@node A74A51BD-0 1525 145
//@node 5FD88F5F-0 2010 40
//@node 8CD6283A-0 1785 145
//@node 69AF3EBC-0 2290 40
//@node 6E5CE5FF-0 2085 145
//@node 0104A3D6-0 2570 200
//@node 2CD7FE0D-0 2345 305
//@node 07D54483-0 2850 200
//@node A6878755-0 2645 305
//@node EB02A447-0 2440 305
//@node 8E7600F5-0 3130 360
//@node 25990D4C-0 2905 465
//@node D85E0E52-0 3410 520
//@node 7E9B7479-0 3205 625
//@node 1555EBC9-0 3410 520
//@node 7D1B835F-0 3970 360
//@node 12DE5277-0 4250 360
//@node 2A8CB2A5-0 4045 465
//@node 5DCE5EA9-0 3840 465
//@node E1A55AF5-0 4530 520
//@node 1CAB4083-0 4810 520
//@node 9497F62F-0 4370 625
//@node 13B64A3F-0 4600 625
//@node B0FFE038-0 5090 520
//@node F117A99C-0 4885 625
//@node 1555EBC9-1 5090 520
//@node 6E2FD220-0 5930 520
//@node 84697BF7-0 6210 360
//@node D8053B2D-0 5770 465
//@node A8D110BD-0 6000 465
//@node 1555EBC9-2 5930 520
//@node E7E35A5F-0 6770 360
//@node 3E276386-0 6565 465
//@node F1AC4A60-0 7050 520
//@node 2AF411AC-0 6825 625
//@node 893BB900-0 7330 520
//@node 03E0A384-0 7125 625
//@node DE9E07FD-0 6920 625
//@node D85E0E52-1 7610 680
//@node 47854112-0 7405 785
//@node 544F89CE-0 7890 680
//@node F60418CE-0 7685 780
//@node C63A0539-0 8170 680
//@node 16AD8822-0 8450 360
//@node 8E7600F5-1 8730 200
//@node EEACA1D7-0 8505 305
//@node 1555EBC9-3 8450 360
//@node 58CAA2BE-0 9290 200
//@node E00F873C-0 9085 305
//@node B64BE25C-0 8880 305
//@node 1555EBC9-4 9010 360
//@node D023735C-0 9850 200
//@node 9AB1A4D7-0 9410 305
//@node EB3C1467-0 9640 305
//@node 1555EBC9-5 9570 360
//@node 2BBBCF2F-0 10410 200
//@node 7B94CC6D-0 10185 305
//@node 63D9453F-0 9980 405
//@node D2DB9A74-0 9775 405
//@node 1324C5E9-0 10690 200
//@node 268F24CE-0 10465 305
//@node 66800B2A-0 10260 405
//@node 37292A25-0 10055 405
//@node C8C75B1D-0 10970 200
//@node 9F9DBC2D-0 10765 305
//@node 0287CA68-0 10560 305
//@node B67D597D-0 10560 389
//@node 894671CD-0 11250 360
//@node 57A21E68-0 11045 465
//@node DACABB49-0 11530 520
//@node 8C5CD14B-0 11325 625
//@node D381C126-0 12090 520
//@node 51F52555-0 11885 625
//@node 68505937-0 12370 200
//@node EC8BF348-0 12165 305
//@node A22459E1-0 12650 360
//@node 276EE3BD-0 12930 360
//@node 453CDDE5-0 12705 465
//@node 7D1B835F-1 13210 520
//@node 16AD8822-1 13490 520
//@node 8BBECDC1-0 13770 360
//@node A9EF4952-0 13565 465
//@node B6024CC0-0 14050 360
//@node 867FFC3C-0 14330 360
//@node 32E7778F-0 14105 465
//@node 7D1B835F-2 14610 520
//@node 16AD8822-2 14890 520
//@node D85E0E52-2 15170 40
//@node 2597974B-0 14965 145
//@node 440A16AD-0 15450 40
//@node 236E54B8-0 15225 145
//@node 16AD8822-3 15730 200
//@node 15592431-0 16010 40
//@node 4272CA3E-0 15785 145
//@node 9662602D-0 16290 40
//@node 3A0B9095-0 16085 145
//@node 201F411E-0 40 40
//@node 04F36F27-0 330 40
//@node 681789AC-0 125 145
//@node 7B291DDD-0 -80 145
//@node 1968515D-0 610 40
//@node DCD47978-0 890 40
//@node BE3975D0-0 685 145
//@node FBFD9423-0 1170 40
//@node EE366316-0 945 145
//@node 1A36B550-0 1450 40
//@node 8714A41F-0 1245 145
//@node ACC3B76D-0 1730 200
//@node 23624FAE-0 1505 305
//@node BBDF52FF-0 2010 360
//@node 81F7F184-0 1805 465
//@node 775E358F-0 2290 360
//@node 3964E4F6-0 2570 200
//@node 1E462A4C-0 2365 305
//@node B647C70A-0 2160 305
//@node 775E358F-1 2850 360
//@node 386FAA07-0 3130 200
//@node FFB1B41D-0 2925 305
//@node 94C6398A-0 3410 360
//@node 2F720129-0 3185 465
//@node 09001098-0 3690 360
//@node 9CAC7858-0 3485 465
//@node C1F8D20B-0 3280 465
//@node BBDF52FF-1 3970 520
//@node 5089A7CB-0 3765 625
//@node 81285097-0 4250 520
//@node E7174946-0 4530 520
//@node 75144557-0 4325 620
//@node A9BB858D-0 4810 520
//@node 1B39CC97-0 5090 200
//@node D610BC3F-0 5370 200
//@node D7C90429-0 4930 305
//@node 94ACDAD9-0 5160 305
//@node 775E358F-2 5650 360
//@node 4D12351A-0 5930 200
//@node BBDF52FF-2 6210 40
//@node 72775192-0 6005 145
//@node 9E69C0C4-0 6490 40
//@node 9FCC96CC-0 6265 145
//@node 4D12351A-1 6770 200
//@node C820A96B-0 7050 40
//@node E3AF6B9D-0 6825 145
//@node 30D2D92F-0 7330 40
//@node 019D0B20-0 7125 145
//@node A5C8F9B5-0 40 40
//@node 7B922198-0 330 40
//@node E7B21CB4-0 610 40
//@node B27A8B3B-0 890 40
//@node 389E3E95-0 1170 40
//@node 1B5655F9-0 1450 40
//@node 68740E74-0 1225 145
//@node D35010CE-0 40 40
//@node A67F6507-0 330 40
//@node 00AE57F9-0 610 40
//@node 22F7CE1B-0 890 40
//@node 4B4F4792-0 1170 40
//@node 16530BF6-0 1450 40
//@node EDC65185-0 1225 145
//@doomscript-blueprint end
