/***********************************************************************

ai_monster_boss_guardian.script

monster_boss_guardian

***********************************************************************/

#define	SPAWNER_PAIN_FADEOUT			2.5
#define	SPAWNER_FADEOUT					1
#define SPAWNER_FADEIN_TIME				0.25

#define	GUARDIAN_PAIN_DELAY				0.25
#define GUARDIAN_RANGE_ATTACK_RANGE		1024
#define GUARDIAN_RANGE_ATTACK_DELAY		7
#define GUARDIAN_CHARGE_ATTACK_RANGE	680
#define GUARDIAN_NUM_PROJECTILES		12

// anim blend times
#define	GUARDIAN_PAIN_TO_IDLE			3
#define GUARDIAN_PAIN_TO_PAIN			3
#define GUARDIAN_SIGHT_TO_IDLE			8
#define	GUARDIAN_MELEE_TO_IDLE			12
#define GUARDIAN_IDLE_TO_PAIN			3
#define GUARDIAN_IDLE_TO_WALK			12
#define GUARDIAN_IDLE_TO_CHARGE			12
#define GUARDIAN_IDLE_TO_MELEE			12
#define	GUARDIAN_IDLE_TO_RANGE			12
#define GUARDIAN_IDLE_TO_SIGHT			12
#define GUARDIAN_IDLE_TO_LOST			12
#define GUARDIAN_WALK_TO_IDLE			12
#define GUARDIAN_WALK_TO_PAIN			3
#define	GUARDIAN_WALK_TO_CHARGE			8
#define	GUARDIAN_CHARGE_TO_WALK			0
#define GUARDIAN_CHARGE_TO_IDLE			12
#define GUARDIAN_CHARGE_TO_PAIN			3
#define GUARDIAN_LOST_TO_IDLE			10
#define GUARDIAN_LOST_TO_PAIN			3
#define GUARDIAN_LOST_TO_WALK			24
#define GUARDIAN_LOST_TO_CHARGE			24
#define GUARDIAN_RANGEATTACK_TO_IDLE	4
#define GUARDIAN_SPAWN_TO_IDLE			4
#define	GUARDIAN_IDLE_TO_SPAWN			4

object seeker_base : monster_base {
	boolean			isAlive()						{ return !AI_DEAD; }
	void			respawnSeeker( entity enemy )	{ 0; }
};

object monster_boss_guardian_spawner : monster_base {
	entity			lightning;
	entity			guardianEnt;
	entity			light;
	entity			beam;
	entity			beam_target;

	vector			beam_offset;
	vector			rotation;
	vector			beam_pain_color;
	vector			beam_color;
	vector			lightning_pain_color;
	vector			lightning_color;

	float			pain_time;
	float			inactive_time;
	float			active_time;

	void 			init();
	void 			destory();
	void 			setGuardian( entity owner );
	void			update_effects();
	void 			state_Inactive();
	void 			state_Active();
	void 			state_Killed();
};

object monster_boss_guardian : monster_base {
	float			nextAttack;
	seeker_base		seeker1;
	seeker_base		seeker2;
	seeker_base		seeker3;
	float			sightEnemyTime;
	boolean			in_melee;
	boolean			rightfoot;
	boolean			charge;

	entity			light1;
	entity			light2;

	monster_boss_guardian_spawner spawner;

	void 			Legs_Sight();
	void 			Legs_Death();
	void 			Legs_Pain();
	void			Legs_RangeAttack();
	void 			Legs_MeleeAttack();
	void 			Legs_Walk_Melee_Left();
	void 			Legs_Walk_Melee_Right();
	void 			Legs_Walk();
	void 			Legs_Run_Melee_Left();
	void 			Legs_Run_Melee_Right();
	void 			Legs_Charge();
	void 			Legs_Lost();
	void 			Legs_Idle();
	void 			Legs_SpawnSeeker();

	void 			init();
	void 			destory();
	void 			addSeeker( entity seeker );
	void 			sightEnemy();
	boolean 		seekersAreDead();
	boolean 		spawnSeeker();
	void 			state_Idle();
	void 			state_Killed();
	void 			state_Combat();
	void 			combat_melee();
	void			combat_range();
	void			combat_charge();
};

void monster_boss_guardian_spawner::init() {
	active_time		= 0;
	inactive_time	= 0;
	pain_time		= 0;

	beam_offset				= getVectorKey( "beam_offset" );
	rotation				= getVectorKey( "rotate" );
	beam_pain_color 		= getVectorKey( "beam_pain_color" );
	beam_color				= getVectorKey( "beam_color" );
	lightning_pain_color	= getVectorKey( "lightning_pain_color" );
	lightning_color			= getVectorKey( "lightning_color" );

	sys.setSpawnArg( "_color", beam_color );
	sys.setSpawnArg( "name", getName() + "light" );
	sys.setSpawnArg( "light", "1024" );
	sys.setSpawnArg( "texture", getKey( "mtr_beam_light_shader" ) );
	sys.setSpawnArg( "start_off", "1" );
	light = sys.spawn( "light" );
	light.setOrigin( getWorldOrigin() );
	light.bind( self );

	sys.setSpawnArg( "name", getName() + "beam_target" );
	beam_target = sys.spawn( "func_beam" );
	beam_target.setOrigin( getWorldOrigin() );
	beam_target.bind( self );

	sys.setSpawnArg( "_color", beam_color );
	sys.setSpawnArg( "name", getName() + "beam" );
	sys.setSpawnArg( "skin", getKey( "mtr_beam_skin" ) );
	sys.setSpawnArg( "target", getName() + "beam_target" );
	sys.setSpawnArg( "start_off", "1" );
	beam = sys.spawn( "func_beam" );
	beam.setOrigin( getWorldOrigin() + beam_offset );
	beam.bind( self );

	setMoveType( MOVETYPE_STATIC );
	setState( "state_Inactive" );
}

void monster_boss_guardian_spawner::destory() {
	light.remove();
	beam.remove();
	beam_target.remove();
}

void monster_boss_guardian_spawner::setGuardian( entity owner ) {
	vector offset;

	guardianEnt = owner;
	setOwner( owner );

	offset = getVectorKey( "offset" );
	setOrigin( guardianEnt.getWorldOrigin() + offset );

	sys.setSpawnArg( "name", getName() + "_lightning" );
	sys.setSpawnArg( "nopush", "1" );
	sys.setSpawnArg( "solid", "0" );
	sys.setSpawnArg( "model", getKey( "lightning_model" ) );
	lightning = sys.spawn( "func_mover_amodel" );
	lightning.setOrigin( guardianEnt.getWorldOrigin() + offset );

	bindToJoint( guardianEnt, "origin", false );
	lightning.bind( self );
}

void monster_boss_guardian_spawner::update_effects() {
	vector	c;
	float	pain_frac;
	float	normal_frac;
	float	hide_frac;

	if ( active_time <= inactive_time ) {
		hide_frac = ( inactive_time + SPAWNER_FADEOUT - sys.getTime() ) / SPAWNER_FADEOUT;
	} else {
		hide_frac = ( sys.getTime() - active_time ) / SPAWNER_FADEIN_TIME;
		if ( hide_frac > 1 ) {
			hide_frac = 1;
		}
	}

	if ( hide_frac < 0 ) {
		hide();
		beam.hide();
		lightning.hide();
		return;
	}

	lightning.show();
	show();
	beam.show();

	lightning.setAngles( rotation * sys.getTime() );

	pain_frac = ( pain_time + SPAWNER_PAIN_FADEOUT - sys.getTime() ) / SPAWNER_PAIN_FADEOUT;
	if ( pain_frac < 0 ) {
		pain_frac = 0;
	}

	normal_frac = 1 - pain_frac;
	pain_frac *= hide_frac;
	normal_frac *= hide_frac;

	c = beam_pain_color * pain_frac + beam_color * normal_frac;
	setColor( c_x, c_y, c_z );
	beam.setColor( c_x, c_y, c_z );
	light.setColor( c_x, c_y, c_z );

	c = lightning_pain_color * pain_frac + lightning_color * normal_frac;
	lightning.setColor( c_x, c_y, c_z );
}

void monster_boss_guardian_spawner::state_Inactive() {
	inactive_time = sys.getTime();
	while( 1 ) {
		update_effects();
		waitFrame();
	}
}

void monster_boss_guardian_spawner::state_Active() {
	monster_boss_guardian guardian;

	active_time = sys.getTime();
	guardian = guardianEnt;

	lightning.show();
	show();
	light.fadeInLight( 0.5 );
	beam.show();

	while( 1 ) {
		if ( AI_DAMAGE ) {
			guardian.AI_PAIN = true;
			guardian.startSound( "snd_pain", SND_CHANNEL_VOICE, false );
			pain_time = sys.getTime();
			AI_DAMAGE = false;
		}
		update_effects();
		waitFrame();
	}
}

void monster_boss_guardian_spawner::state_Killed() {
	guardianEnt.setState( "state_Killed" );
	remove();
/*
	setMoveType( MOVETYPE_STATIC );
	inactive_time = sys.getTime();
	pain_time = sys.getTime();

	update_effects();
	while( !isHidden() ) {
		update_effects();
		waitFrame();
	}
	stopThinking();
*/
}

/***********************************************************************

	animation control

***********************************************************************/

void monster_boss_guardian::Legs_Sight() {
	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "sight" );
	while( !animDone( ANIMCHANNEL_LEGS, GUARDIAN_SIGHT_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "sight" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_SIGHT_TO_IDLE );
}

void monster_boss_guardian::Legs_Death() {
	seeker1.kill();
	seeker2.kill();
	seeker3.kill();
	playAnim( ANIMCHANNEL_LEGS, "death" );

	// never exit
	waitUntil( 0 );
}

void monster_boss_guardian::Legs_Pain() {
	float nextpain;
	float currenttime;

	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "pain" );

	nextpain = sys.getTime() + GUARDIAN_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_LEGS, GUARDIAN_PAIN_TO_IDLE ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Pain", GUARDIAN_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_PAIN_TO_IDLE );
}

void monster_boss_guardian::Legs_RangeAttack() {
	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "range_attack" );

	while( !animDone( ANIMCHANNEL_LEGS, GUARDIAN_RANGEATTACK_TO_IDLE ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	preventPain( 1 );
	waitFrame();
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_RANGEATTACK_TO_IDLE );
}

void monster_boss_guardian::Legs_MeleeAttack() {
	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "melee_attack" );

	while( !animDone( ANIMCHANNEL_LEGS, GUARDIAN_MELEE_TO_IDLE ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	preventPain( 1 );
	waitFrame();
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_MELEE_TO_IDLE );
}

void monster_boss_guardian::Legs_Walk_Melee_Left() {
	in_melee = true;
	rightfoot = false;
	playAnim( ANIMCHANNEL_LEGS, "walk_attack_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	preventPain( 1 );
	in_melee = false;

	if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Left", 0 );
	} else {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 0 );
	}
}

void monster_boss_guardian::Legs_Walk_Melee_Right() {
	in_melee = true;
	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "walk_attack_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	in_melee = false;
	preventPain( 1 );

	if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Right", 0 );
	} else {
		animState( ANIMCHANNEL_LEGS, "Legs_Walk", 0 );
	}
}

void monster_boss_guardian::Legs_Walk() {
	if ( rightfoot ) {
		if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Right", 0 );
		}
		playAnim( ANIMCHANNEL_LEGS, "walk_right" );
	} else {
		if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Left", 0 );
		}
		playAnim( ANIMCHANNEL_LEGS, "walk_left" );
	}
	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Pain", GUARDIAN_WALK_TO_PAIN );
		}
		if ( !AI_FORWARD ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_WALK_TO_IDLE );
		}

		if ( animDone( ANIMCHANNEL_LEGS, 0 ) ) {
			if ( charge ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Charge", GUARDIAN_WALK_TO_CHARGE );
			}
			rightfoot = !rightfoot;
			if ( rightfoot ) {
				if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
					animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Right", 0 );
				}
				playAnim( ANIMCHANNEL_LEGS, "walk_right" );
			} else {
				if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
					animState( ANIMCHANNEL_LEGS, "Legs_Walk_Melee_Left", 0 );
				}
				playAnim( ANIMCHANNEL_LEGS, "walk_left" );
			}

		}
	}
}

void monster_boss_guardian::Legs_Run_Melee_Left() {
	in_melee = true;
	rightfoot = false;
	attackBegin( "damage_guardianCharge" );
	playAnim( ANIMCHANNEL_LEGS, "run_attack_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	attackEnd();
	preventPain( 1 );
	in_melee = false;

	boolean canMelee = testMeleeAttack() && AI_ENEMY_IN_FOV;
	if ( canMelee || testAnimAttack( "run_attack_left" ) ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Run_Melee_Left", 0 );
	} else {
		animState( ANIMCHANNEL_LEGS, "Legs_Charge", 0 );
	}
}

void monster_boss_guardian::Legs_Run_Melee_Right() {
	in_melee = true;
	rightfoot = true;
	attackBegin( "damage_guardianCharge" );
	playAnim( ANIMCHANNEL_LEGS, "run_attack_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 0 ) ) {
		preventPain( 1 );
		waitFrame();
	}
	
	attackEnd();
	in_melee = false;
	preventPain( 1 );

	boolean canMelee = testMeleeAttack() && AI_ENEMY_IN_FOV;
	if ( canMelee || testAnimAttack( "run_attack_right" ) ) {
		animState( ANIMCHANNEL_LEGS, "Legs_Run_Melee_Right", 0 );
	} else {
		animState( ANIMCHANNEL_LEGS, "Legs_Charge", 0 );
	}
}

void monster_boss_guardian::Legs_Charge() {
	boolean canMelee = testMeleeAttack() && AI_ENEMY_IN_FOV;

	if ( rightfoot ) {
		if ( canMelee || testAnimAttack( "run_attack_right" ) ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Run_Melee_Right", 0 );
		}
		playAnim( ANIMCHANNEL_LEGS, "run_right" );
	} else {
		if ( canMelee || testAnimAttack( "run_attack_left" ) ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Run_Melee_Left", 0 );
		}
		playAnim( ANIMCHANNEL_LEGS, "run_left" );
	}

	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Pain", GUARDIAN_CHARGE_TO_PAIN );
		}
		if ( animDone( ANIMCHANNEL_LEGS, GUARDIAN_CHARGE_TO_WALK ) ) {
			charge = false;
			animState( ANIMCHANNEL_LEGS, "Legs_Walk", GUARDIAN_CHARGE_TO_WALK );
		}
	}
}

void monster_boss_guardian::Legs_Lost() {
	rightfoot = true;
	idleAnim( ANIMCHANNEL_LEGS, "lost_enemy" );

	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Pain", GUARDIAN_LOST_TO_PAIN );
		}
		if ( AI_FORWARD ) {
			if ( charge ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Charge", GUARDIAN_LOST_TO_CHARGE );
			} else {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", GUARDIAN_LOST_TO_WALK );
			}
		}
		if ( sightEnemyTime >= sys.getTime() ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_LOST_TO_IDLE );
		}
	}
}

void monster_boss_guardian::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Pain", GUARDIAN_IDLE_TO_PAIN );
		}
		if ( AI_FORWARD ) {
			if ( charge ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Charge", GUARDIAN_IDLE_TO_CHARGE );
			} else {
				animState( ANIMCHANNEL_LEGS, "Legs_Walk", GUARDIAN_IDLE_TO_WALK );
			}
		}
		if ( getEnemy() ) {
			if ( sightEnemyTime < sys.getTime() ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Lost", GUARDIAN_IDLE_TO_LOST );
			}
		}
	}
}

void monster_boss_guardian::Legs_SpawnSeeker() {
	rightfoot = true;
	playAnim( ANIMCHANNEL_LEGS, "spawn_seeker" );
	while( !animDone( ANIMCHANNEL_LEGS, GUARDIAN_SPAWN_TO_IDLE ) ) {
		preventPain( 1 );
		waitFrame();
	}
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", GUARDIAN_SPAWN_TO_IDLE );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_boss_guardian::init
=====================
*/
void monster_boss_guardian::init() {
	vector color;

	color = getVectorKey( "light_color" );

	sys.setSpawnArg( "name", getName() + "_light1" );
	light1 = sys.spawn( "light" );
	light1.setShader( getKey( "mtr_light_shader" ) );
	light1.setRadius( getFloatKey( "light_radius" ) );
	light1.bindToJoint( self, "Rhand", true );
	light1.setOrigin( getVectorKey( "light_offset_right" ) );
	light1.setColor( color_x, color_y, color_z );

	sys.setSpawnArg( "name", getName() + "_light2" );
	light2 = sys.spawn( "light" );
	light2.setShader( getKey( "mtr_light_shader" ) );
	light2.setRadius( getFloatKey( "light_radius" ) );
	light2.bindToJoint( self, "Lhand", true );
	light2.setOrigin( getVectorKey( "light_offset_left" ) );
	light2.setColor( color_x, color_y, color_z );

	rightfoot = true;
	charge = false;

	setMoveType( MOVETYPE_ANIM );

	ignoreDamage();

	sightEnemyTime = -1;

	sys.setSpawnArg( "name", getName() + "_spawn" );
	spawner = sys.spawn( "monster_boss_guardian_spawner" );
	spawner.setGuardian( self );
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	setState( "state_Idle" );
}

/*
=====================
monster_boss_guardian::destory
=====================
*/
void monster_boss_guardian::destory() {
	spawner.remove();
	light1.remove();
	light2.remove();
}

/*
=====================
monster_boss_guardian::addSeeker
=====================
*/
void monster_boss_guardian::addSeeker( entity seeker ) {
	if ( !seeker1 ) {
		seeker1 = seeker;
	} else if ( !seeker2 ) {
		seeker2 = seeker;
	} else if ( !seeker3 ) {
		seeker3 = seeker;
	} else {
		sys.error( "'" + getName() + "' was targeted by more than 3 seekers" );
	}
}

/*
=====================
monster_boss_guardian::sightEnemy
=====================
*/
void monster_boss_guardian::sightEnemy() {
	sightEnemyTime = sys.getTime() + 0.5;
	locateEnemy();

	// all seeker's now know the location
	seeker1.locateEnemy();
	seeker2.locateEnemy();
	seeker3.locateEnemy();
}

/*
=====================
monster_boss_guardian::seekersAreDead
=====================
*/
boolean monster_boss_guardian::seekersAreDead() {
	if ( seeker1.isAlive() ) {
		return false;
	}

	if ( seeker2.isAlive() ) {
		return false;
	}

	if ( seeker3.isAlive() ) {
		return false;
	}

	return true;
}


/*
=====================
monster_boss_guardian::spawnSeeker
=====================
*/
boolean monster_boss_guardian::spawnSeeker() {
	entity enemy;

	// don't go into lost anim for a bit
	sightEnemyTime = sys.getTime() + 20;
	stopMove();

	spawner.setState( "state_Active" );
	sys.wait( 1 );

	animState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker", GUARDIAN_IDLE_TO_SPAWN );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker" ) ) {
		waitFrame();
	}

	enemy = getEnemy();
	if ( !( !seeker1 ) && !seeker1.isAlive() ) {
		seeker1.respawnSeeker( enemy );
	}

	animState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker", GUARDIAN_IDLE_TO_SPAWN );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker" ) ) {
		waitFrame();
	}

	if ( !( !seeker2 ) && !seeker2.isAlive() ) {
		seeker2.respawnSeeker( enemy );
	}

	animState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker", GUARDIAN_IDLE_TO_SPAWN );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_SpawnSeeker" ) ) {
		waitFrame();
	}

	if ( !( !seeker3 ) && !seeker3.isAlive() ) {
		seeker3.respawnSeeker( enemy );
	}

	sys.wait( 0.5 );
	sightEnemyTime = sys.getTime() - 0.1;
	spawner.setState( "state_Inactive" );
}

/*
=====================
monster_boss_guardian::state_Idle
=====================
*/
void monster_boss_guardian::state_Idle() {
	if ( getIntKey( "hide" ) ) {
		//
		// hide until triggered
		//
		hide();
		waitUntil( AI_ACTIVATED );
		if ( getIntKey( "hide" ) == 1 ) {
			AI_ACTIVATED = false;
			clearEnemy();
		}
		waitUntil( canBecomeSolid() );
		show();
		ignoreDamage();
	}

	wait_for_enemy();

	faceEnemy();

	// don't go into lost anim for a bit
	sightEnemyTime = sys.getTime() + 20;
	animState( ANIMCHANNEL_LEGS, "Legs_Sight", GUARDIAN_IDLE_TO_SIGHT );
	waitAction( "sight" );

	nextAttack = RandomTime( GUARDIAN_RANGE_ATTACK_DELAY );
	setState( "state_Combat" );
}

/*
=====================
monster_boss_guardian::state_Killed
=====================
*/
void monster_boss_guardian::state_Killed() {
	activateTargets( $world );

	light1.fadeOutLight( 0.5 );
	light2.fadeOutLight( 0.5 );

	AI_DEAD = true;
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );
	waitAction( "dead" );
	
	stopThinking();
}

/*
=====================
monster_boss_guardian::state_Combat
=====================
*/
void monster_boss_guardian::state_Combat() {
	while( 1 ) {
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
			continue;
		}
		while( sightEnemyTime < sys.getTime() ) {
			stopMove();
			if ( seekersAreDead() ) {
				spawnSeeker();
			}
			waitFrame();
		}

		while( sightEnemyTime >= sys.getTime() ) {
			if ( in_melee ) {
				waitFrame();
				continue;
			}
			if ( seekersAreDead() ) {
				spawnSeeker();
			}
			moveToEnemy();
			if ( !inAnimState( ANIMCHANNEL_TORSO, "Legs_Pain" ) ) {
				if ( AI_DEST_UNREACHABLE || ( sys.getTime() >= nextAttack ) ) {
					if ( enemyRange() < GUARDIAN_RANGE_ATTACK_RANGE ) {
						if ( canHitEnemy() ) {
							combat_range();
							waitFrame();
							continue;
						}
					}
				} else if ( enemyRange() > GUARDIAN_CHARGE_ATTACK_RANGE ) {
					if ( canHitEnemy() ) {
						combat_charge();
						waitFrame();
						continue;
					}
				}
			}

			if ( testMeleeAttack() && AI_ENEMY_IN_FOV ) {
				combat_melee();
			} 
			waitFrame();
		}
	}
}

/*
=====================
monster_boss_guardian::combat_melee
=====================
*/
void monster_boss_guardian::combat_melee() {
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_MeleeAttack", GUARDIAN_IDLE_TO_MELEE );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_MeleeAttack" ) ) {
		waitFrame();
	}
}

/*
=====================
monster_boss_guardian::combat_range
=====================
*/
void monster_boss_guardian::combat_range() {
	faceEnemy();
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_RangeAttack", GUARDIAN_IDLE_TO_RANGE );
	while( inAnimState( ANIMCHANNEL_LEGS, "Legs_RangeAttack" ) ) {
		waitFrame();
	}

	nextAttack = DelayTime( GUARDIAN_RANGE_ATTACK_DELAY );
}

/*
=====================
monster_boss_guardian::combat_charge
=====================
*/
void monster_boss_guardian::combat_charge() {
	charge = true;
	moveToEnemy();
	while( charge ) {
		waitFrame();
	}
	stopMove();
	charge = false;
}

/*
=====================
monster_boss_guardian::pound_impact
=====================
*/
void monster_boss_guardian::pound_impact( string joint ) {
	string	entname;
	entity	explosion;
	float	handJoint;
	vector	org;

	handJoint = getJointHandle( joint );
	org = getJointPos( handJoint );

	sys.radiusDamage( org, self, self, spawner, "damage_guardianPoundGround", 1.0 );

	entname = getKey( "def_poundground" );
	explosion = sys.spawn( entname );
	explosion.setOrigin( org - '0 0 32');
	explosion.setShaderParm( 4, -sys.getTime() );	
	sys.wait( 0.75 );
	explosion.remove();
}

/*
=====================
monster_boss_guardian::pound_attack
=====================
*/
void monster_boss_guardian::pound_attack( string joint ) {
	float	handJoint;
	vector	org;
	vector	ang;
	float	i;

	handJoint = getJointHandle( joint );
	org = getJointPos( handJoint );

	sys.radiusDamage( org, self, self, spawner, "damage_guardianPoundGround", 1.0 );

	ang = getAngles();
	for( i = 0; i < GUARDIAN_NUM_PROJECTILES; i++ ) {
		ang_y += 360 / GUARDIAN_NUM_PROJECTILES;
		launchMissile( org, ang );
	}

	thread pound_impact( joint );
}

/*
=====================
monster_boss_guardian::pound_attack_left
=====================
*/
void monster_boss_guardian::pound_attack_left() {
	pound_attack( "lhand" );
}

/*
=====================
monster_boss_guardian::pound_attack_right
=====================
*/
void monster_boss_guardian::pound_attack_right() {
	pound_attack( "rhand" );
}

/*
=====================
monster_boss_guardian::smash_ground
=====================
*/
void monster_boss_guardian::smash_ground() {
	float	handJoint;
	vector	org1, org2, org;
	vector	ang;
	float	i;
	
	thread pound_impact( "lhand" );
	thread pound_impact( "rhand" );

	handJoint = getJointHandle( "lhand" );
	org1 = getJointPos( handJoint );
	handJoint = getJointHandle( "rhand" );
	org2 = getJointPos( handJoint );
	org = ( org1 + org2 ) * 0.5;

	ang = getAngles();
	for( i = 0; i < GUARDIAN_NUM_PROJECTILES; i++ ) {
		ang_y += 360 / GUARDIAN_NUM_PROJECTILES;
		launchMissile( org, ang );
	}
}

//@doomscript-blueprint begin 6
//@source 83BBB5F6
//@catalog 0C260740
//@node BCC4266E-0 40 40
//@node C91A5D8A-0 330 40
//@node 1D992CDA-0 610 40
//@node 459832F2-0 40 40
//@node 772477F5-0 330 40
//@node AC82522D-0 125 145
//@node 1B1A7AFE-0 610 40
//@node 410FD22A-0 405 145
//@node D16381C7-0 890 40
//@node 7092F57F-0 685 145
//@node D12F3BDE-0 1170 40
//@node 5E884179-0 945 145
//@node 4981BED9-0 740 245
//@node CCCF2702-0 535 245
//@node F2CCD9D3-0 1450 40
//@node 7DD42092-0 1225 145
//@node 585C4428-0 1730 40
//@node B73445EF-0 1505 145
//@node A3F29ED5-0 1300 245
//@node 6EB9B8EC-0 1095 245
//@node 12B4EE1A-0 2010 40
//@node 96DED645-0 1785 145
//@node F980F815-0 1580 245
//@node 5F606DB0-0 1375 245
//@node C89BE0EA-0 2290 40
//@node C64F7573-0 2065 145
//@node 369DB169-0 1860 245
//@node 441AAE5C-0 1655 245
//@node E1A69448-0 2570 40
//@node 6BE95DE6-0 2345 145
//@node F4A08A67-0 2140 245
//@node 18A1DE9E-0 1935 245
//@node 409262FB-0 2850 40
//@node 50027673-0 2645 232
//@node CBC05EE8-0 3130 40
//@node 077BFD3E-0 2925 232
//@node C2182416-0 2720 232
//@node C51AB375-0 3410 40
//@node 0D800120-0 3205 140
//@node A431B70D-0 3000 140
//@node A1BFFE2F-0 3690 40
//@node 5345E847-0 3970 40
//@node 1D02E022-0 4250 40
//@node 28E7C519-0 4025 145
//@node B76AAB45-0 3820 245
//@node 84A1F7E8-0 3615 245
//@node 4829C2E3-0 4530 40
//@node 174CC26D-0 4810 40
//@node 43C4B671-0 5090 40
//@node E0B30042-0 4885 232
//@node 87371EC0-0 4680 232
//@node 89B5896F-0 5370 40
//@node F5CC87D2-0 5145 145
//@node 9282A81C-0 5650 40
//@node 3B702FA8-0 5930 40
//@node 409262FB-1 6210 40
//@node BC5D65CA-0 6005 232
//@node CD4442EF-0 6490 40
//@node 52AF050E-0 6285 232
//@node 827535C4-0 6080 232
//@node 099945E8-0 6770 40
//@node F00204F7-0 7050 40
//@node 99C34E73-0 6845 232
//@node 6F41E6B5-0 6640 232
//@node 5345E847-1 7330 40
//@node C66645BF-0 7610 40
//@node AA96EB35-0 7385 145
//@node 524D55DC-0 7890 40
//@node 4C944200-0 7685 140
//@node 52921D0B-0 7480 140
//@node 26BFD8B6-0 8170 40
//@node 7CAC9DDD-0 8450 40
//@node 801ED5A8-0 8730 40
//@node 861E7AA0-0 40 40
//@node 8A3B7364-0 330 40
//@node FB4B1103-0 610 40
//@node 7DFDE0D9-0 890 40
//@node E5527CC3-0 40 40
//@node ED2575EF-0 330 40
//@node C9AC08D5-0 610 40
//@node 6A38A567-0 890 40
//@node 3BCDAFB8-0 665 145
//@node 66A19142-0 460 245
//@node A4E515E9-0 255 245
//@node 3500E8D8-0 1170 40
//@node 415D791A-0 965 140
//@node 82193547-0 760 140
//@node 34E1009C-0 760 218
//@node 6724AD52-0 1450 40
//@node B58CCAF5-0 1730 40
//@node 0AC00C48-0 2010 40
//@node D1055D50-0 2290 40
//@node B6E0E1E6-0 2570 40
//@node 58C9187A-0 2345 145
//@node A5DEF990-0 2850 40
//@node 71696576-0 2645 140
//@node 685A714B-0 2440 140
//@node E96C9338-0 2440 218
//@node 71DD89E2-0 3130 40
//@node BD553FA9-0 2925 140
//@node 4A59DD2E-0 3410 40
//@node 859FA2CC-0 40 40
//@node 3A6E47EE-0 330 40
//@node 55F2C04F-0 125 145
//@node B8BF7C15-0 -80 145
//@node E1E17E74-0 -80 229
//@node 0DD893F0-0 610 200
//@node CB87828D-0 405 305
//@node FFF8A3AD-0 200 305
//@node D9AE2308-0 1170 200
//@node 82F5D559-0 965 305
//@node A4D2A380-0 760 305
//@node A6635062-0 1450 200
//@node CB2865B4-0 1245 305
//@node D8248898-0 1040 305
//@node C3CDC67B-0 1730 360
//@node 572D591E-0 1525 465
//@node 7D569987-0 2010 40
//@node 83CDA92F-0 1805 145
//@node DB5B09B2-0 1600 145
//@node 8E7B3216-0 2290 200
//@node 64B282EB-0 2570 200
//@node 4113BCB6-0 2850 200
//@node F433F8B3-0 3130 200
//@node 04731EA1-0 3410 40
//@node 70797501-0 3690 40
//@node 2FDD568C-0 3970 40
//@node 9A069C2D-0 4250 40
//@node 560EDC92-0 4045 140
//@node BB9173EE-0 3840 140
//@node BD7C24CD-0 4530 40
//@node DD12F8D1-0 4325 145
//@node 9D978D0D-0 4120 145
//@node 34DBC773-0 4810 40
//@node C6F9D3D9-0 4605 145
//@node EEC0B97C-0 4400 145
//@node DD43A11A-0 5090 200
//@node A89F0F0D-0 4885 305
//@node 9425CF1E-0 5370 40
//@node DF7E0983-0 5165 145
//@node D7873616-0 4960 145
//@node 6E48B2D3-0 5650 40
//@node 97D198C0-0 5445 145
//@node 00EF9851-0 5240 145
//@node 4B44E361-0 5240 229
//@node 19F28332-0 5930 40
//@node 798CB11B-0 5725 145
//@node F34C357E-0 5520 145
//@node 1F9AED0F-0 5520 229
//@node 1D2FBB51-0 6210 40
//@node 2C5BBFE1-0 6005 145
//@node 8A5D89FA-0 5800 145
//@node B2C7391F-0 5800 229
//@node 889A18A3-0 5800 313
//@node 8C54DC8E-0 5800 397
//@node DBADCE8E-0 6490 40
//@node 3AC04B3D-0 6770 40
//@node 876B38C8-0 7050 40
//@node 4EDA811B-0 7330 40
//@node 6731529E-0 7125 145
//@node 0B231D55-0 6920 145
//@node DFDB3E78-0 6920 229
//@node 512BEC0F-0 6920 313
//@node 4F371842-0 6920 397
//@node 34B6A22E-0 7610 40
//@node 071E6263-0 40 40
//@node FC094896-0 330 40
//@node CB79F949-0 105 145
//@node AFFA8292-0 610 40
//@node FCB9F20D-0 405 145
//@node 587264C1-0 890 200
//@node 7DC447C9-0 1170 200
//@node E4183388-0 40 40
//@node 35C40E1C-0 330 40
//@node 5668735F-0 105 145
//@node AD8E76A2-0 610 40
//@node AEB40FB0-0 405 145
//@node 37743729-0 890 40
//@node 65AD57D9-0 1170 40
//@node 61B528B4-0 1450 40
//@node 4BBA9B34-0 1730 40
//@node BA389C73-0 2010 40
//@node 6D3C9C1F-0 1805 145
//@node 890E90C4-0 2290 200
//@node B95B6538-0 2085 305
//@node 82C62327-0 2570 360
//@node D5244159-0 2850 360
//@node AB1CFFEA-0 3130 360
//@node 16A5D3BE-0 2905 465
//@node C0D67606-0 3410 360
//@node 599E5B29-0 3205 465
//@node 1CA2AAAE-0 3690 200
//@node ED1B4CB0-0 3970 200
//@node 33108123-0 40 40
//@node 4856FBAB-0 330 40
//@node D6CBD245-0 610 40
//@node 41706980-0 40 40
//@node F86AD00F-0 330 40
//@node F7AD85F3-0 125 145
//@node CFAE673C-0 610 40
//@node 8BC61943-0 890 40
//@node 37B1E3DB-0 450 145
//@node BBFD162B-0 680 145
//@node B2CC0290-0 1170 200
//@node A1F368E6-0 1450 40
//@node 5A303F1A-0 1730 40
//@node 17B79217-0 40 40
//@node EFDD06B1-0 330 40
//@node 4427870C-0 610 40
//@node F97D91FB-0 890 40
//@node E92FF02A-0 1170 40
//@node E286001E-0 1450 40
//@node 85DE3C17-0 40 40
//@node 6BFB1772-0 330 40
//@node 9CBD51F6-0 125 145
//@node 04F920D8-0 610 40
//@node 8023A55D-0 890 40
//@node 3C83BC8C-0 685 145
//@node 2FC75843-0 1170 40
//@node 819A722C-0 730 145
//@node 1BF2503C-0 960 145
//@node 657C8330-0 1450 200
//@node C98D6AA5-0 1245 305
//@node 69F2D4D1-0 1730 360
//@node 31558042-0 1505 465
//@node 005B994C-0 2010 360
//@node DD9E61DF-0 1805 465
//@node FEBDBCA0-0 1600 465
//@node 00025723-0 1600 549
//@node B2B43EE8-0 2290 520
//@node C84A6391-0 2570 200
//@node 0C6CCF30-0 2850 40
//@node 3CB5ECA4-0 40 40
//@node 130270CF-0 330 40
//@node 896D486C-0 125 145
//@node 9E7C22AD-0 610 40
//@node 677287B3-0 890 40
//@node F396102F-0 450 145
//@node 174CC13F-0 680 145
//@node E0AF8669-0 1170 200
//@node 64A1D430-0 1450 200
//@node E0AF8669-1 1730 40
//@node 64A1D430-1 2010 40
//@node B0CC5DEE-0 2290 40
//@node C23667CD-0 40 40
//@node 05A121BA-0 330 40
//@node 045E52D6-0 125 145
//@node 6A91DDAF-0 610 40
//@node 21498FC9-0 890 40
//@node 70472A7A-0 450 145
//@node 503D838A-0 680 145
//@node EE103A94-0 1170 200
//@node 1481647B-0 1450 200
//@node EE103A94-1 1730 40
//@node 1481647B-1 2010 40
//@node D4ECCB30-0 2290 40
//@node 14D79E2B-0 40 40
//@node 91DC154A-0 330 40
//@node C5DF65D5-0 125 145
//@node 772BD6E7-0 610 40
//@node 84EC5046-0 405 145
//@node 47ACC412-0 890 40
//@node A5AEEF4C-0 1170 40
//@node F7161766-0 730 145
//@node FC550536-0 960 145
//@node 3511690A-0 1450 200
//@node E2C5B491-0 1730 200
//@node 3511690A-1 2010 40
//@node 7ADCEAC9-0 2290 40
//@node D9B583F9-0 2085 145
//@node 2E770F43-0 2570 40
//@node E1BB655C-0 2365 145
//@node DBC82014-0 2160 145
//@node 1021A277-0 2850 200
//@node 8F7F2A3C-0 3410 200
//@node BBA4E0B4-0 40 40
//@node F55D9D7D-0 330 40
//@node 201971E4-0 125 145
//@node 23C14509-0 610 40
//@node 6821D0FB-0 405 145
//@node A3C43AC2-0 890 40
//@node 2879183F-0 1170 40
//@node F5354E1F-0 730 145
//@node 9D70164F-0 960 145
//@node 76DBB9C9-0 1450 200
//@node BBD49B10-0 1730 200
//@node 84DD1D74-0 2010 40
//@node BA99F337-0 1805 145
//@node 76DBB9C9-1 2290 40
//@node A416A268-0 2570 40
//@node FC903466-0 2365 145
//@node 8D41B93C-0 2160 145
//@node C86937CB-0 2850 200
//@node 5AB6055D-0 3410 200
//@node 345423AE-0 40 40
//@node 28A7285E-0 330 40
//@node A1E5D598-0 125 145
//@node 2AD79C02-0 610 200
//@node 7F17727F-0 405 305
//@node BE06F74B-0 200 305
//@node 80E0003D-0 890 360
//@node 0131624D-0 1170 200
//@node 2AD79C02-1 1730 200
//@node 9961440A-0 1525 305
//@node FD425E84-0 1320 305
//@node DAB0AFCA-0 2010 360
//@node 3BCE8360-0 2290 200
//@node 9A26CF5B-0 2570 40
//@node 57A58483-0 2850 200
//@node 1B6E04E8-0 2645 305
//@node DB7286D8-0 3130 360
//@node 5B356BEF-0 3410 200
//@node F4825C88-0 3205 305
//@node 40A9FE30-0 3000 305
//@node 9A0B5638-0 3690 360
//@node 643A347C-0 3970 200
//@node EBA50D3A-0 3745 305
//@node 59949C26-0 4250 360
//@node 157F77E1-0 4045 465
//@node 05BC76A0-0 4530 520
//@node DDAD2BAE-0 4810 360
//@node 64D664FF-0 4605 465
//@node 5185FCA5-0 4400 465
//@node 28A7285E-1 5090 360
//@node BD320253-0 4885 465
//@node 2AD79C02-2 5370 520
//@node C0827C99-0 5165 625
//@node 2ADC62A5-0 4960 625
//@node 80E0003D-1 5650 680
//@node 0131624D-1 5930 520
//@node 2AD79C02-3 6490 520
//@node 77FB18F4-0 6285 625
//@node 88F241F6-0 6080 625
//@node DAB0AFCA-1 6770 680
//@node 3BCE8360-1 7050 520
//@node 24933079-0 40 40
//@node 8826E582-0 330 40
//@node 1C80B35F-0 125 145
//@node DFCB891F-0 610 40
//@node 6025D45D-0 405 145
//@node 94E8554B-0 890 40
//@node F4BCFCF0-0 1170 40
//@node 6FFDD2EE-0 1450 40
//@node 7C3E7586-0 1010 145
//@node 253C7BD6-0 1240 145
//@node D7287FB0-0 1730 200
//@node 015600C7-0 2010 200
//@node B2E31056-0 2290 40
//@node D7287FB0-1 2570 40
//@node FEBFA921-0 2850 40
//@node 2086F298-0 2645 145
//@node B9E7AA29-0 3130 40
//@node 79EC8AFA-0 2905 145
//@node 3E072B3F-0 3690 200
//@node 0EAB29ED-0 4250 200
//@node 601B2EDA-0 40 40
//@node 21809855-0 330 40
//@node C9FB4154-0 125 145
//@node 2F343F61-0 610 40
//@node 3940B22B-0 405 145
//@node A144B53C-0 890 40
//@node E350D7CE-0 1170 40
//@node C127F149-0 1450 40
//@node 5F8C1A96-0 1010 145
//@node 855A3FE6-0 1240 145
//@node 463CA1B7-0 1730 200
//@node B0F11026-0 2010 200
//@node EC751D73-0 2290 40
//@node EC18324C-0 2570 40
//@node F19C8118-0 2365 145
//@node 463CA1B7-1 2850 40
//@node E3855E63-0 3130 40
//@node D32C8A63-0 2905 145
//@node 37EE1995-0 3690 200
//@node AFB82CB8-0 4250 200
//@node 28238593-0 40 40
//@node 7CCEC755-0 330 40
//@node EC335E0B-0 125 145
//@node 2DE856CE-0 610 200
//@node 0AD13562-0 385 305
//@node C7F2FF9C-0 1170 360
//@node 063A4854-0 1450 200
//@node 405EBF4F-0 1730 200
//@node 6FFE3BF6-0 1505 305
//@node 54F0453D-0 2290 360
//@node FCEF0013-0 2570 200
//@node AF239E96-0 2570 40
//@node FD20118C-0 2850 200
//@node 5C813A5B-0 2645 305
//@node B928F1E8-0 3410 360
//@node 5B8DF40B-0 3410 200
//@node FD59579B-0 3185 305
//@node E9716B4B-0 3690 360
//@node 0A735E08-0 3485 465
//@node A9CEE3DC-0 4250 360
//@node 3D01E0D1-0 40 40
//@node 167013B0-0 330 40
//@node 00FFEEE1-0 125 145
//@node 73195EF7-0 610 40
//@node 7C257EDC-0 890 40
//@node 9754EC26-0 1170 200
//@node 756827B3-0 965 305
//@node 674BB918-0 1450 360
//@node 8B076179-0 1730 200
//@node 6E64B7B5-0 1525 305
//@node 59D54551-0 2010 360
//@node FFB23EB7-0 1805 465
//@node AFB70230-0 2290 520
//@node E0CCB2B8-0 2850 520
//@node 607DD6D3-0 3130 200
//@node 3D093760-0 2905 305
//@node 5DCB1B68-0 3410 360
//@node 38973259-0 40 40
//@node 3F61D638-0 330 40
//@node 7544B5E0-0 610 40
//@node 6ECCD3DE-0 890 200
//@node C3879A9F-0 685 305
//@node B1CBB628-0 1170 360
//@node 81E9B9B1-0 1450 200
//@node E41289A8-0 1245 305
//@node 4235FA89-0 1730 360
//@node 597A6FD3-0 1525 465
//@node 1DFBC5F0-0 2010 520
//@node ED5B9BBC-0 2570 520
//@node 47D18B06-0 2850 200
//@node 91E1D93F-0 2625 305
//@node 39726CAA-0 3130 360
//@node 61143B3A-0 2905 465
//@node 5DA4C064-0 3410 520
//@node CF9CB569-0 40 40
//@node F185D02A-0 330 40
//@node C86247D8-0 125 145
//@node 44307461-0 610 40
//@node 68FE56BA-0 890 40
//@node C92F8571-0 450 145
//@node 063E9121-0 680 145
//@node 91E541D0-0 1170 200
//@node 3B609EE7-0 1450 200
//@node 0F6B2FD1-0 1730 40
//@node 3447F589-0 40 40
//@node 19EA3AC4-0 330 40
//@node 13D16988-0 105 145
//@node A00937D9-0 610 40
//@node F36DA852-0 890 40
//@node 955132CD-0 665 145
//@node 8E3B3AAE-0 460 245
//@node 873A85FF-0 255 245
//@node 337AD0BD-0 1170 40
//@node 3F4385A7-0 1450 40
//@node 3D8BEDD3-0 1730 40
//@node 8A7A4572-0 2010 40
//@node FF8E2316-0 2290 40
//@node D79D88AC-0 2570 40
//@node F6960F97-0 2850 40
//@node F49A40DB-0 2625 145
//@node 876D68B2-0 2420 245
//@node EE32D37F-0 2215 245
//@node 1F7EBDAE-0 3130 40
//@node 000FE386-0 3410 40
//@node 0CC67038-0 3690 40
//@node 48FAABA2-0 3970 40
//@node 206E0D25-0 4250 40
//@node 98123C9A-0 4530 40
//@node EF3BDD0F-0 4325 145
//@node E0440E07-0 4810 40
//@node 2829CF5F-0 4605 145
//@node 2E6DEBB7-0 5090 40
//@node BF3B89D6-0 5370 40
//@node 80C13420-0 5650 40
//@node 657C2B58-0 5445 145
//@node 55F79459-0 5930 40
//@node 16C68202-0 6210 40
//@node 7990ABF4-0 5985 145
//@node 23D08F10-0 6490 40
//@node B552C83B-0 6770 40
//@node 54E1019C-0 7050 40
//@node B4606FD9-0 40 40
//@node 2E75B5FD-0 330 40
//@node 8C9E1D2C-0 610 40
//@node 7B91C2B5-0 890 40
//@node 4E178405-0 40 40
//@node 8F80319A-0 330 40
//@node DC55C601-0 125 145
//@node E9955F93-0 -80 145
//@node 50FBE9D9-0 610 200
//@node 93820F20-0 890 200
//@node 5DF1E66A-0 685 305
//@node A78436A8-0 480 305
//@node 5B020C28-0 1170 200
//@node 269B136B-0 1450 200
//@node FF945986-0 1245 305
//@node C0DCFA4E-0 1040 305
//@node 66D2C07B-0 1730 200
//@node 8D81415B-0 2290 200
//@node 9AE5C198-0 40 40
//@node 0E507836-0 330 40
//@node F23DB71C-0 125 145
//@node 8B5E7AEC-0 610 40
//@node 54BFB168-0 890 40
//@node AAF00873-0 1170 40
//@node B8DBBC3E-0 1450 40
//@node 91AF2553-0 40 40
//@node A661021D-0 330 40
//@node D836E633-0 105 145
//@node FEBCB395-0 610 200
//@node 8694F808-0 890 40
//@node 5EA5F893-0 665 145
//@node FEBCB395-1 1170 200
//@node C48979E3-0 1450 40
//@node AE93B43A-0 1225 145
//@node FEBCB395-2 1730 200
//@node 979C0FBE-0 2010 40
//@node 414DD925-0 40 40
//@node 4175AB5E-0 330 40
//@node 796F71A2-0 125 145
//@node 6E505B0C-0 610 40
//@node 551AFAD6-0 890 40
//@node 73E5FC40-0 1170 40
//@node 975097CF-0 1450 40
//@node E548AFF5-0 1730 40
//@node 87861D54-0 1505 145
//@node 83DB7773-0 2010 200
//@node A5DD5E57-0 2290 40
//@node CE1988F9-0 2065 145
//@node 879AFF75-0 2570 40
//@node A6592561-0 2365 145
//@node 5A524168-0 2160 145
//@node E93AFC34-0 2850 200
//@node 8D0ACCB9-0 2645 300
//@node 975097CF-1 3130 40
//@node E548AFF5-1 3410 40
//@node 07B6D9CB-0 3185 145
//@node 83DB7773-1 3690 200
//@node 071ADA29-0 3970 40
//@node 2AD2A15F-0 3765 145
//@node 35CDE20F-0 3560 145
//@node 92347AE1-0 4250 200
//@node 425F71BD-0 4045 300
//@node 975097CF-2 4530 40
//@node E548AFF5-2 4810 40
//@node 33E099FE-0 4585 145
//@node 83DB7773-2 5090 200
//@node 64F8FC81-0 5370 40
//@node 73111D9E-0 5165 145
//@node 05A23205-0 4960 145
//@node 9EE6AE2E-0 5650 200
//@node D8A7B2E1-0 5445 300
//@node B1F4E60E-0 5930 40
//@node 4415121F-0 6210 40
//@node BEA1C73F-0 6005 145
//@node D8CA20A1-0 6490 40
//@node 726B56DB-0 40 40
//@node 6EA71544-0 330 40
//@node 0B740A3C-0 105 145
//@node 1AB932D1-0 610 200
//@node B3775F1C-0 890 200
//@node F9CDE809-0 685 300
//@node 0134C5FF-0 1170 200
//@node 286E1604-0 965 305
//@node 717B967F-0 1450 360
//@node D18D7311-0 1245 465
//@node 26502320-0 1730 360
//@node BED5E9DD-0 2010 200
//@node F07B038E-0 2290 200
//@node 89C30ADC-0 2570 200
//@node A3C1D2C3-0 2850 40
//@node 0F9B5FFE-0 3130 40
//@node 91EB6B16-0 3410 40
//@node C7BBBCA0-0 3205 145
//@node 6B78303A-0 3690 40
//@node 28605619-0 3970 40
//@node F685A432-0 4250 40
//@node 8026DA8E-0 4025 145
//@node 1A1D5580-0 4530 40
//@node C2198C38-0 40 40
//@node FDC75241-0 330 40
//@node 85A2180C-0 610 40
//@node 05A9E82F-0 890 40
//@node DCCEE074-0 1170 40
//@node 94B2F2B9-0 965 145
//@node 4C176419-0 1450 40
//@node DA6381BC-0 1730 40
//@node 120D4391-0 2010 40
//@node DB6F0E36-0 2290 40
//@node 26326D09-0 40 40
//@node 0552FF20-0 330 40
//@node 6E209EE2-0 125 145
//@node 4158537D-0 610 200
//@node BE1950DE-0 405 305
//@node 09B965E6-0 890 360
//@node EE146698-0 1170 360
//@node 2D440140-0 1450 200
//@node 789A0F6D-0 1225 305
//@node ACFDBB30-0 1730 360
//@node 83F952E2-0 2010 360
//@node FB0941CB-0 1785 465
//@node 5581BA91-0 2290 520
//@node 1C5BF037-0 2570 360
//@node 423AF701-0 2850 200
//@node E85B477E-0 2625 305
//@node 73319C21-0 3130 360
//@node 04878D04-0 2925 465
//@node 1C5BF037-1 3410 520
//@node EE146698-1 3690 520
//@node 83F952E2-1 3970 360
//@node 6641E6B6-0 3745 465
//@node 5581BA91-1 4250 520
//@node 4E82816D-0 4530 360
//@node A3893B62-0 4810 360
//@node 842D58C4-0 4370 465
//@node AA2C7B34-0 4600 465
//@node 10B5FAB7-0 5090 520
//@node 420E2242-0 4885 625
//@node C48849D3-0 4680 625
//@node 1CBF42FE-0 4680 625
//@node 97A2B237-0 5370 680
//@node 40DF6AE3-0 5165 785
//@node CDFC80BB-0 5650 840
//@node C7B80F1C-0 5425 945
//@node E3EA13C9-0 5930 1000
//@node 1C5BF037-2 6210 1000
//@node EE146698-2 6490 1000
//@node BDC00BFF-0 6770 680
//@node 89FF013A-0 6565 785
//@node CDFC80BB-1 7050 680
//@node 2619908B-0 6825 785
//@node B1866C46-0 7330 840
//@node 1C5BF037-3 7610 840
//@node EE146698-3 7890 840
//@node 9EAE6535-0 8170 360
//@node DE373BF5-0 7965 465
//@node 2C401AF3-0 7760 465
//@node 40472C6E-0 8450 520
//@node 1C5BF037-4 8730 360
//@node 90B4A164-0 40 40
//@node 47D55F99-0 330 40
//@node 8B18A399-0 610 40
//@node 54234FA6-0 890 40
//@node 4774D2F6-0 665 145
//@node 2BF0DEB0-0 1170 200
//@node 5BE20D2D-0 40 40
//@node 057C9B88-0 330 40
//@node 307A39C4-0 610 40
//@node D978F734-0 890 40
//@node C0781F2E-0 1170 40
//@node 77DEA8B8-0 945 145
//@node 384B2D2B-0 1450 200
//@node 9D18E79C-0 1730 40
//@node A81CEDB3-0 1505 145
//@node 7880D8B4-0 40 40
//@node 5FD3AFFD-0 330 40
//@node 8369449B-0 125 145
//@node 672C77BA-0 610 40
//@node B736748E-0 890 40
//@node 914C98E0-0 685 145
//@node 00194C18-0 1170 200
//@node 56FE0101-0 1450 40
//@node 9CBC3CF4-0 1730 40
//@node 65AD8496-0 1525 145
//@node D6BC9BB6-0 40 40
//@node 6AAA8DD9-0 330 40
//@node E6E1FF1A-0 105 145
//@node 16938E33-0 610 40
//@node 177570FC-0 385 145
//@node 51D7FEAB-0 180 245
//@node 0566A7B5-0 890 40
//@node 57345388-0 685 140
//@node 432048BB-0 685 416
//@node 01609B8A-0 1170 40
//@node C77C0104-0 945 145
//@node 18F094BF-0 1450 40
//@node 37D86F61-0 1225 145
//@node 95DBD8AD-0 1020 245
//@node 2D8BD239-0 1730 40
//@node 60FF943F-0 1525 140
//@node 8F802450-0 1320 140
//@node 58B857B6-0 2010 40
//@node 7D6EF6AA-0 2290 40
//@node 6CF08D01-0 2570 40
//@node 02BADA30-0 40 40
//@node 87A1C493-0 330 40
//@node 46DFEF88-0 105 145
//@node F39BE43D-0 610 40
//@node 0510B43A-0 385 145
//@node 03438D8D-0 180 245
//@node 9C0E7BC7-0 890 40
//@node 131E21D4-0 685 140
//@node A5C24C1F-0 685 416
//@node FCE14F90-0 1170 40
//@node 9517B78C-0 945 145
//@node 46BEF58F-0 1450 40
//@node FFD404D4-0 1245 145
//@node 5023953F-0 1040 145
//@node 8877A80B-0 1730 200
//@node FBE5F10D-0 1525 305
//@node 1C348D07-0 2010 200
//@node 5163551A-0 1805 300
//@node C8DFA1DB-0 1805 392
//@node 79287363-0 2290 40
//@node 2EF1C2B8-0 40 40
//@node 83CE1928-0 330 40
//@node E370A20D-0 40 40
//@node 44DA0C9D-0 330 40
//@node 14306979-0 40 40
//@node 3B2C0557-0 610 40
//@node F8D9E47D-0 890 40
//@node B43F0DCD-0 890 40
//@node 18EB84A5-0 665 145
//@node 2A266E8F-0 1170 40
//@node 786A1EB5-0 945 145
//@node 360ED7DB-0 740 245
//@node FC157F87-0 1450 40
//@node 65C6A88A-0 1225 145
//@node 6A62B0E2-0 1730 40
//@node 256DD36F-0 1505 145
//@node 455C32E0-0 1300 245
//@node CE3B8074-0 2010 40
//@node 2F918AEC-0 1805 145
//@node 9877E452-0 1600 145
//@node 9777E2BF-0 1600 229
//@node CE60A95F-0 2290 40
//@node 37722B8A-0 2065 145
//@node 54C52C1E-0 2570 40
//@node 2A020925-0 2365 145
//@node DD638EA4-0 2160 145
//@node C7598C1C-0 2850 200
//@node E3FEDEA0-0 2645 305
//@node 486DC6D0-0 3410 200
//@node 7553ABC0-0 2925 300
//@node 58420295-0 2925 392
//@doomscript-blueprint end
