/***********************************************************************

ai_monster_boss_cyberdemon.script

monster_boss_cyberdemon

***********************************************************************/

#define CYBER_ATTACK_RATE			5
#define	CYBER_PAIN_DELAY			0.25
#define CYBER_NOFOVTIME				4

// anim blend times
#define	CYBER_PAIN_TO_IDLE			2
#define CYBER_PAIN_TO_PAIN			0
#define	CYBER_MELEE_TO_IDLE			4
#define CYBER_RANGE_TO_IDLE			4
#define CYBER_IDLE_TO_PAIN			0
#define CYBER_IDLE_TO_WALK			4
#define CYBER_WALK_TO_IDLE			4
#define CYBER_WALK_TO_RANGEATTACK	4
#define CYBER_WALK_TO_MELEE			4

object monster_boss_cyberdemon : monster_base {
	float		nextAttack;
	string		range_attack_anim;
	entity		kick_entity;
	float		nextNoFOVAttack;

	// ai state
	void		init();
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_boss_cyberdemon::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	while( !AI_SPECIAL_DAMAGE ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", CYBER_IDLE_TO_PAIN );
}

void monster_boss_cyberdemon::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + CYBER_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_TORSO, CYBER_PAIN_TO_IDLE ) ) {
		if ( AI_SPECIAL_DAMAGE ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", CYBER_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", CYBER_PAIN_TO_IDLE );
}

void monster_boss_cyberdemon::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !AI_SPECIAL_DAMAGE && !animDone( ANIMCHANNEL_TORSO, CYBER_MELEE_TO_IDLE ) ) {
		lookAtEnemy( 0.1 );
		waitFrame();
	}

	finishAction( "melee_attack" );

	if ( AI_SPECIAL_DAMAGE ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Pain", CYBER_IDLE_TO_PAIN );
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", CYBER_MELEE_TO_IDLE );
}

void monster_boss_cyberdemon::Torso_RangeAttack() {
	disablePain();

	playAnim( ANIMCHANNEL_TORSO, range_attack_anim );
	while( !AI_SPECIAL_DAMAGE && !animDone( ANIMCHANNEL_TORSO, CYBER_RANGE_TO_IDLE ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}

	allowMovement( true );
	finishAction( "range_attack" );

	if ( AI_SPECIAL_DAMAGE ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Pain", CYBER_IDLE_TO_PAIN );
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", CYBER_RANGE_TO_IDLE );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_boss_cyberdemon::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	while( !AI_FORWARD ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Walk", CYBER_IDLE_TO_WALK );
}

void monster_boss_cyberdemon::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD )	{
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", CYBER_WALK_TO_IDLE );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_boss_cyberdemon::init
=====================
*/
void monster_boss_cyberdemon::init() {
	nextNoFOVAttack = 0;
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_boss_cyberdemon::state_Begin
=====================
*/
void monster_boss_cyberdemon::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_boss_cyberdemon::state_Idle
=====================
*/
void monster_boss_cyberdemon::state_Idle() {
	wait_for_enemy();

	nextAttack	= 0;

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_boss_cyberdemon::do_attack
=====================
*/
void monster_boss_cyberdemon::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + CYBER_NOFOVTIME;
	if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_boss_cyberdemon::check_attacks
=====================
*/
float monster_boss_cyberdemon::check_attacks() {
	float currentTime;
	float attack_flags;
	vector org;
	
	attack_flags = 0;

	if ( AI_ENEMY_VISIBLE ) {
		org = getOrigin();
		kick_entity = findActorsInBounds( org + '-65 -65 0', org + '65 65 300' );
		if ( kick_entity ) {
			attack_flags |= ATTACK_MELEE;
		}
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		currentTime = sys.getTime();
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			range_attack_anim = chooseAnim( ANIMCHANNEL_LEGS, "range_attack" );
			if ( canHitEnemyFromAnim( range_attack_anim ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_boss_cyberdemon::combat_range
=====================
*/
void monster_boss_cyberdemon::combat_range() {
	faceEnemy();
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", CYBER_WALK_TO_RANGEATTACK );
	waitAction( "range_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( CYBER_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + CYBER_NOFOVTIME;
}

/*
=====================
monster_boss_cyberdemon::combat_melee
=====================
*/
void monster_boss_cyberdemon::combat_melee() {
	kickObstacles( kick_entity, 200 );
	sys.wait( 0.5 );
	directDamage( kick_entity, "melee_cyberdemon_kick" );
}

//@doomscript-blueprint begin 6
//@source 81B8D9D9
//@catalog 0C260740
//@node 660F254A-0 40 40
//@node A9A403E9-0 330 40
//@node 1E6F2173-0 610 40
//@node 1BE079D9-0 405 145
//@node 095E41A9-0 200 145
//@node 0BB7ABDE-0 890 200
//@node 6893A6AD-0 1170 40
//@node 1C05DBA8-0 40 40
//@node BEFF1B87-0 330 40
//@node 2775DBD0-0 105 145
//@node F124C683-0 610 40
//@node D850A43C-0 405 232
//@node 30BB906C-0 890 40
//@node 9B9EBA12-0 685 145
//@node 167BCD6A-0 1170 40
//@node 57CB149F-0 730 145
//@node 4DC2730F-0 960 145
//@node 3D2B35B8-0 1450 200
//@node 5C238747-0 1245 305
//@node 3EB15EDE-0 1730 360
//@node 730B2583-0 1505 465
//@node CA4BAE2F-0 2010 360
//@node 7B5EFC64-0 1805 465
//@node 8685AD59-0 1600 465
//@node EF76C864-0 1600 549
//@node 9FC34D41-0 2290 520
//@node 7FDCDC94-0 2570 200
//@node E46F9E51-0 2850 40
//@node 4651C959-0 3130 40
//@node 3522D490-0 40 40
//@node 19C11284-0 330 40
//@node 2B98F6E5-0 610 40
//@node 98BDA888-0 170 145
//@node 35BCD2D8-0 400 145
//@node 2993E56F-0 890 200
//@node F2981214-0 1170 200
//@node 7B747B0C-0 1450 40
//@node 08272C60-0 1730 40
//@node 241876EE-0 1525 145
//@node 55BFB897-0 2010 200
//@node 9F4E79DD-0 2290 40
//@node 2A0F6235-0 40 40
//@node 9C5EE19D-0 330 40
//@node B0E1C178-0 610 40
//@node A1231369-0 405 232
//@node A0295B8B-0 890 40
//@node 03E75EB7-0 450 145
//@node 27B813A7-0 680 145
//@node BB4BD5E0-0 1170 200
//@node CD5F0063-0 1450 200
//@node 413A5A0D-0 1730 40
//@node 5C2356BE-0 2010 40
//@node 63050EC7-0 2290 40
//@node C32624FE-0 2085 145
//@node 2B23E23A-0 2570 200
//@node 32B604F9-0 2850 40
//@node 5C53B67C-0 40 40
//@node 175E6BE1-0 330 40
//@node 79DADCAF-0 610 40
//@node BC2DEC97-0 405 145
//@node E83C4761-0 200 145
//@node 23DD9D58-0 890 200
//@node 2F61483B-0 1170 40
//@node 292857E3-0 40 40
//@node 2B888AFE-0 330 40
//@node B8EDE449-0 610 40
//@node 844AAB26-0 405 145
//@node EAC6B5B9-0 890 200
//@node D0022B3F-0 1170 40
//@node 98B78F2E-0 40 40
//@node FD110F98-0 330 40
//@node 14BDB939-0 125 145
//@node AFABB65A-0 610 40
//@node 0E9C8CCF-0 40 40
//@node B6BA775B-0 330 40
//@node C9232D95-0 610 40
//@node 20C77E33-0 890 40
//@node F912FBA1-0 1170 40
//@node 7B50625A-0 1450 40
//@node A9601AAC-0 40 40
//@node FEF1FB18-0 330 40
//@node B019E144-0 610 40
//@node 4314B706-0 405 145
//@node 10E2CA23-0 890 40
//@node 70E155CA-0 40 40
//@node D5B41B41-0 330 40
//@node E12C911B-0 125 145
//@node F9AFFA41-0 610 40
//@node DD477AC6-0 405 145
//@node 43F16C85-0 890 200
//@node E42F0A46-0 1170 200
//@node 4E98E72E-0 965 305
//@node 91E965CE-0 1450 200
//@node 4007612E-0 40 40
//@node 190B3D33-0 330 40
//@node CCB32D6D-0 125 145
//@node 9AD48142-0 610 40
//@node F017F101-0 405 145
//@node 84B81444-0 890 200
//@node EDA8F15B-0 665 305
//@node E7EA47F4-0 1170 200
//@node 19B2CFBE-0 945 305
//@node 20000AE8-0 740 405
//@node 0927C8E6-0 535 405
//@node CE9AA99E-0 740 497
//@node B37CD39D-0 535 497
//@node 15B25078-0 1450 200
//@node 510BE508-0 1245 305
//@node 8ECB5CAE-0 1730 360
//@node 1320D225-0 2010 40
//@node 20AD087D-0 1805 145
//@node B608C2D3-0 1600 145
//@node A1BE64A8-0 1600 229
//@node A8247F6C-0 1600 145
//@node E9ACB98A-0 2290 200
//@node 2C04F12F-0 2065 305
//@node CB5C873E-0 2570 200
//@node 098F2A19-0 2365 305
//@node 03C4C048-0 2160 305
//@node 72669935-0 2160 389
//@node 8F8D40A0-0 2850 360
//@node D44030B7-0 2625 465
//@node 3046F7AF-0 3130 360
//@node B0038C07-0 2905 465
//@node 32F9D2AF-0 2700 565
//@node 09709A1E-0 3410 520
//@node 9CDD33BD-0 3690 40
//@node B479620E-0 40 40
//@node A473CAF5-0 330 40
//@node AEEC5B1B-0 610 40
//@node BB1BAD88-0 890 40
//@node 1EF4DFBB-0 1170 40
//@node 41761CC4-0 1450 40
//@node 4D4C18B7-0 1225 145
//@node 13A5B767-0 1730 40
//@node 8E9F1E7C-0 1525 145
//@node 2F782FA7-0 40 40
//@node A5BCD235-0 330 40
//@node EC75E748-0 125 140
//@node 41BF37C0-0 610 40
//@node 93F44905-0 890 40
//@node 619F0C91-0 685 140
//@doomscript-blueprint end
