/***********************************************************************

ai_monster_base.script

base class for all monsters.  implements common behavior.

***********************************************************************/

//
// attack flags
//
#define ATTACK_DODGE_LEFT	1
#define ATTACK_DODGE_RIGHT	2
#define ATTACK_COMBAT_NODE	4
#define ATTACK_MELEE		8
#define ATTACK_LEAP			16
#define ATTACK_MISSILE		32
#define ATTACK_SPECIAL1		64
#define ATTACK_SPECIAL2		128
#define ATTACK_SPECIAL3		256
#define ATTACK_SPECIAL4		512


#define AI_NOT_ACTIVATED	0
#define AI_CHASING_ENEMY	1
#define AI_LOST				2
#define AI_PATH_FOLLOWING	3
#define AI_ATTACK_NODE		4

/***********************************************************************

	base class for monsters

***********************************************************************/

object monster_base : ai {
	// common state variables
	float		run_distance;			// distance to trigger running when chasing enemy
	float		walk_turn;				// max turn amount allowed when running
	boolean		run;
	boolean		ambush;
	boolean		ignoreEnemies;			// used to disable enemy checks during attack_path
	boolean		stay_on_attackpath;		// used to disable enemy checks during attack_path
	boolean		idle_sight_fov;	
	float		customBlendOut;
	entity		current_path;
	entity		next_path;
	boolean		resurrect;
	boolean		ignore_lostcombat;
	boolean		blocked;
	boolean		ignore_sight;
	
	// common animation functions
	void		Torso_CustomCycle();
	void		Torso_CustomAnim();
	void		Torso_Sight();
	void		Torso_Death();
	void		Legs_Idle();
	void		Legs_Death();

	// attack checks
	// these functions are meant to be implemented by subclasses.
	// by default, they do nothing.
	float		check_attacks();
	void		do_attack( float attack_flags );
	boolean		checkTurretAttack();				// tests if monster can still do a turret attack from current location

	// common functions
	void		init();
	void		state_Begin();
	void		monster_begin();
	void		archvile_minion();
	boolean		can_resurrect();
	void		monster_resurrect( entity enemy );
	void		wait_for_enemy();
	void		state_Killed();
	void		state_Dead();
	void		wake_on_enemy();
	void		wake_on_trigger();
	void		walk_on_trigger();
	void		wake_on_attackcone();
	void		sight_enemy();
	void		enemy_dead();
	void		state_Combat();
	void		state_LostCombat();
	void		state_Spawner();
	void		monster_base_lost_combat();
	boolean		check_blocked();
	boolean		combat_chase();
	void		combat_turret_node( entity node );
	void		combat_attack_cone( entity node );
	void		combat_ainode( entity node );
	void		combat_lost();
	void		combat_wander();
	void		playCustomCycle( string animname, float blendTime );
	void		playCustomAnim( string animname, float blendIn, float blendOut );
	void		checkNodeAnim( entity node, string prefix, string anim );
	void		trigger_wakeup_targets();
	boolean		checkForEnemy( float use_fov );
	void 		state_FollowAlternatePath();
	void 		follow_alternate_path1();
	void 		follow_alternate_path2();
	void 		follow_alternate_path3();

	// path following
	void 		idle_followPathEntities( entity pathnode );
	void 		path_corner();
	void 		path_anim();
	void 		path_cycleanim();
	void 		path_turn();
	void 		path_wait();
	void 		path_waitfortrigger();
	void 		path_hide();
	void 		path_show();
	void		path_attack();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_base::Torso_CustomCycle() {
	eachFrame {
		;
	}
}

void monster_base::Torso_CustomAnim() {
	while( !animDone( ANIMCHANNEL_TORSO, customBlendOut ) ) {
		waitFrame();
	}
	
	finishAction( "customAnim" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", customBlendOut );
}

void monster_base::Torso_Sight() {
	string animname;
	float blendFrames;
	
	if ( !getIntKey( "walk_on_sight" ) ) {
		overrideAnim( ANIMCHANNEL_LEGS );
	}

	animname = self.getKey( "on_activate" );
	if ( self.getKey( "on_activate_blend" ) ) {
		blendFrames = self.getIntKey( "on_activate_blend" );
	} else {
		blendFrames = 4;
	}

	if ( animname != "" ) {
		if ( hasAnim( ANIMCHANNEL_TORSO, animname ) ) {
			playAnim( ANIMCHANNEL_TORSO, animname );
		
			while( !animDone( ANIMCHANNEL_TORSO, blendFrames ) ) {
				waitFrame();
			}
		}
	}
	
	finishAction( "sight" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", blendFrames );
}

void monster_base::Torso_Death() {
	finishAction( "dead" );
}

void monster_base::Legs_Idle() {
	// implemented by subclasses
}

void monster_base::Legs_Death() {
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_base::init
=====================
*/
void monster_base::init() {
	ignoreEnemies		= false;
	run_distance		= 0;
	walk_turn			= 360;
	ambush				= getIntKey( "ambush" );
	ignore_lostcombat	= getIntKey( "ignore_lostcombat" );
	stay_on_attackpath	= getIntKey( "stay_on_attackpath" );
	idle_sight_fov		= true;
	run					= false;
}

/*
=====================
monster_base::state_Begin

Initial state for monsters.  Called after spawn and when monster is resurrected.
=====================
*/
void monster_base::state_Begin() {
}

/*
=====================
monster_base::do_attack

Performs an attack based on which bits are set on the attack_flags.

Implemented by subclasses
=====================
*/
void monster_base::do_attack( float attack_flags ) {
}

/*
=====================
monster_base::check_attacks

Returns flags stating which attacks can be performed this frame.

Implemented by subclasses
=====================
*/
float monster_base::check_attacks() {
	return 0;
}

/*
=====================
monster_base::playCustomCycle
=====================
*/
void monster_base::playCustomCycle( string animname, float blendTime ) {
	animState( ANIMCHANNEL_TORSO, "Torso_CustomCycle", blendTime );
	overrideAnim( ANIMCHANNEL_LEGS );
	playCycle( ANIMCHANNEL_TORSO, animname );
}

/*
=====================
monster_base::playCustomAnim
=====================
*/
void monster_base::playCustomAnim( string animname, float blendIn, float blendOut ) {
	customBlendOut = blendOut;
	animState( ANIMCHANNEL_TORSO, "Torso_CustomAnim", blendIn );
	overrideAnim( ANIMCHANNEL_LEGS );
	playAnim( ANIMCHANNEL_TORSO, animname );
}

/*
=====================
monster_base::trigger_wakeup_targets
=====================
*/
void monster_base::trigger_wakeup_targets() {
	string key;
	string name;
	entity ent;

	key = getNextKey( "wakeup_target", "" );
	while( key != "" ) {
		name = getKey( key );
		ent = sys.getEntity( name );
		if ( !ent ) {
			sys.warning( "Unknown wakeup_target '" + name + "' on entity '" + getName() + "'" );
		} else {
			sys.trigger( ent );
		}
		key = getNextKey( "wakeup_target", key );
	}
}

/*
=====================
monster_base::checkForEnemy
=====================
*/
boolean	monster_base::checkForEnemy( float use_fov ) {
	entity enemy;
	vector size;
	float dist;

	if ( sys.influenceActive() ) {
		return false;
	}

	if ( AI_PAIN ) {
		// get out of ambush mode when shot
		ambush = false;
	}

	if ( ignoreEnemies ) {
		// while we're following paths, we only respond to enemies on pain, or when close enough to them
		if ( stay_on_attackpath ) {
			// don't exit attack_path when close to enemy
			return false;
		}

		enemy = getEnemy();
		if ( !enemy ) {
			enemy = findEnemy( false );
		}
	
		if ( !enemy ) {
			return false;
		}

		size = getSize();
		dist = ( size_x * 1.414 ) + 16;  // diagonal distance plus 16 units
		if ( enemyRange() > dist ) {
			return false;
		}
	} else {
		if ( getEnemy() ) {
			// we were probably triggered (which sets our enemy)
			return true;
		}

		if ( !ignore_sight ) {
			enemy = findEnemy( use_fov );
		}
		
		if ( !enemy ) {
			if ( ambush ) {
				return false;
			}

			enemy = heardSound( true );
			if ( !enemy ) {
				return false;
			}
		}
	}

	ignoreEnemies = false;

	// once we've woken up, get out of ambush mode
	ambush = false;
		
	// don't use the fov for sight anymore
	idle_sight_fov = false;

	setEnemy( enemy );
	return true;
}

/*
=====================
monster_base::state_Spawner
=====================
*/
void monster_base::state_Spawner() {
	entity	ent;
	float	triggerCount;
	float	maxSpawn;
	float	i;
	string	name;

	maxSpawn = getIntKey( "spawner" );
	name = getName();

	hide();

	triggerCount = 0;
	AI_ACTIVATED = false;
	while( 1 ) {
		if ( AI_ACTIVATED ) {
			triggerCount++;
			AI_ACTIVATED = false;
		}

		if ( triggerCount ) {
			if ( canBecomeSolid() ) {
				for( i = 0; i < maxSpawn; i++ ) {
					ent = sys.getEntity( name + i );
					if ( !ent ) {
						break;
					}
				}

				if ( i < maxSpawn ) {
					triggerCount--;
					sys.copySpawnArgs( self );
					sys.setSpawnArg( "spawner", "0" );
					sys.setSpawnArg( "name", name + i );
					if ( getKey( "spawn_target" ) != "" ) {
						sys.setSpawnArg( "target", getKey( "spawn_target" ) );
					}
					ent = sys.spawn( getKey( "classname" ) );
					sys.trigger( ent );
				}
			}
		}
		waitFrame();
	}
}

/*
=====================
monster_base::monster_begin
=====================
*/
void monster_base::monster_begin() {
	float	teleportType;
	string	triggerAnim;
	float	waittime;
	boolean start_active;
	entity  path;
	float	movetype;
	entity	enemy;

	run	= false;
	ignore_sight = getIntKey( "no_sight" );

	if ( !getIntKey( "ignore_flashlight" ) ) {
		// allow waking up from the flashlight
		wakeOnFlashlight( true );
	}

	start_active = false;

	if ( resurrect ) {
		teleportType = 4;
		triggerAnim = "";
		AI_ACTIVATED = true;
	} else {
		teleportType = getIntKey( "teleport" );
		triggerAnim = getKey( "trigger_anim" );
	}

	if ( getIntKey( "spawner" ) ) {
		setState( "state_Spawner" );
	}

	if ( triggerAnim != "" ) {
		//
		// hide until triggered and then play a special animation
		//
		checkAnim( ANIMCHANNEL_TORSO, triggerAnim );
		hide();
		waitUntil( AI_ACTIVATED );
		waitUntil( canBecomeSolid() );

		// don't go dormant during trigger_anim anims since they
		// may end up floating in air during no gravity anims.
		setNeverDormant( true );

		show();
		trigger_wakeup_targets();
		playCustomAnim( triggerAnim, 0, 4 );
		waitAction( "customAnim" );
		setNeverDormant( getFloatKey( "neverdormant" ) );
		locateEnemy();
		start_active = true;
	} else if ( teleportType > 0 ) {
		//
		// teleport in when triggered
		//
		hide();
		waitUntil( AI_ACTIVATED );
		waitUntil( canBecomeSolid() );
		becomeSolid();
		movetype = getMoveType();
		setMoveType( MOVETYPE_STATIC );

		// don't go dormant during teleport anims since they
		// may end up floating in air during no gravity anims.
		setNeverDormant( true );

		trigger_wakeup_targets();
		if ( teleportType == 1 ) {
			startFx( getKey( "fx_teleport1" ) );
			wait( 1.6 );
		} else if ( teleportType == 2 ) {
			startFx( getKey( "fx_teleport2" ) );
			wait( 2.6 );
		} else if ( teleportType == 3 ) {
			startFx( getKey( "fx_teleport3" ) );
			wait( 3.6 );
		} else {
			startFx( getKey( "fx_teleport" ) );
			wait( 0.6 );
		}
		show();
		playCustomAnim( "teleport", 0, 4 );
		waitAction( "customAnim" );
		setNeverDormant( getFloatKey( "neverdormant" ) );
		locateEnemy();
		setMoveType( movetype );
		start_active = true;
	} else if ( getIntKey( "hide" ) ) {
		//
		// hide until triggered
		//
		hide();
		waitUntil( AI_ACTIVATED );
		if ( ( getIntKey( "hide" ) == 1 ) || ambush ) {
			AI_ACTIVATED = false;
			clearEnemy();
		}
		waitUntil( canBecomeSolid() );
		show();
	}

	waittime = getFloatKey( "wait" );
	if ( waittime > 0 ) {
		sys.wait( waittime );
	}

	enemy = getEntityKey( "enemy" );	
	if ( enemy ) {
		setEnemy( enemy );
	}

	if ( !start_active ) {
		if ( getIntKey( "wake_on_attackcone" ) ) {
			wake_on_attackcone();
		} else if ( getIntKey( "walk_on_trigger" ) ) {
			walk_on_trigger();
		} else if ( getIntKey( "trigger" ) ) {
			wake_on_trigger();
		} else {
			wake_on_enemy();
		}
	} else if ( getIntKey( "attack_path" ) ) {
		// follow a path and fight player at end
		path = randomPath();
		if ( path ) {
			run = true;
			ignoreEnemies = true;
			idle_followPathEntities( path );
			ignoreEnemies = false;
		}
	}

	// allow him to see after he's woken up
	ignore_sight = false;

	// ignore the flashlight from now on
	wakeOnFlashlight( false );
}

/*
=====================
monster_base::archvile_minion
=====================
*/
void monster_base::archvile_minion() {
	hide();
	resurrect = true;
	AI_DEAD = true;
}

/*
=====================
monster_base::can_resurrect
=====================
*/
boolean monster_base::can_resurrect() {
	if ( !AI_DEAD ) {
		return false;
	}

	if ( !isHidden() ) {
		return false;
	}

    if ( !canBecomeSolid() ) {
		return false;
	}
	
	return true;
}

/*
=====================
monster_base::state_Resurrect
=====================
*/
void monster_base::state_Resurrect() {
	float health;
	vector ang;

	AI_DEAD = false;

	stopMove();
	hide();
	stopRagdoll();
	restorePosition();

	waitUntil( canBecomeSolid() );

	health = getFloatKey( "health" );
	setHealth( health );

	ang_y = getFloatKey( "angle" );
	setAngles( ang );
	turnTo( ang_y );

	clearBurn();
	allowDamage();

	setState( "state_Begin" );
}

/*
=====================
monster_base::monster_resurrect
=====================
*/
void monster_base::monster_resurrect( entity enemy ) {
	// mark them as not dead so we don't get resurrected twice this frame
	AI_DEAD = false;
	if ( enemy ) {
		setEnemy( enemy );
	} else {
		setEnemy( $player1 );
	}
	setState( "state_Resurrect" );
}

/*
=====================
monster_base::wait_for_enemy
=====================
*/
void monster_base::wait_for_enemy() {
	// prevent an infinite loop when in notarget
	AI_PAIN = false;

	stopMove();
	
	while( !AI_PAIN && !getEnemy() ) {
		if ( checkForEnemy( idle_sight_fov ) ) {
			break;
		}
		waitFrame();
	}
}

/*
=====================
monster_base::state_Killed
=====================
*/
void monster_base::state_Killed() {
	stopMove();

	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );

	waitAction( "dead" );
	setState( "state_Dead" );
}

/*
=====================
monster_base::state_Dead
=====================
*/
void monster_base::state_Dead() {

	float burnDelay = getFloatKey( "burnaway" );
	if ( burnDelay != 0 ) {
		preBurn();
		sys.wait( burnDelay );
		burn();
		startSound( "snd_burn", SND_CHANNEL_BODY, false );
	}
	
	sys.wait( 3 );
	
	if ( resurrect ) {
		hide();
		stopRagdoll();
		restorePosition();

		// wait until we're resurrected
		waitUntil( 0 );
	}
	remove();
}
/*
=====================
monster_base::sight_enemy
=====================
*/
void monster_base::sight_enemy() {
	string animname;

	faceEnemy();
	animname = self.getKey( "on_activate" );
	if ( animname != "" ) {
		// don't go dormant during on_activate anims since they
		// may end up floating in air during no gravity anims.
		setNeverDormant( true );
		if ( getIntKey( "walk_on_sight" ) ) {
			moveToEnemy();
		}
		animState( ANIMCHANNEL_TORSO, "Torso_Sight", 4 );
		waitAction( "sight" );
		setNeverDormant( getFloatKey( "neverdormant" ) );
	}
}

/*
=====================
monster_base::enemy_dead
=====================
*/
void monster_base::enemy_dead() {
	AI_ENEMY_DEAD = false;
	checkForEnemy( false );
	if ( !getEnemy() ) {
		waitFrame();  // avoid infinite loops
		setState( "state_Idle" );
	} else {
		setState( "state_Combat" );
	}
}

/*
=====================
monster_base::walk_on_trigger
=====================
*/
void monster_base::walk_on_trigger() {
	string animname;
	entity path;

	allowMovement( false );

	// sit in our idle anim till we're activated
	animname = self.getKey( "anim" );
	playCustomCycle( animname, 4 );
	waitUntil( AI_ACTIVATED || AI_PAIN );
	
	if ( AI_ACTIVATED ) {
		clearEnemy();
		AI_ACTIVATED = false;
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	allowMovement( true );
	
	// follow a path
	path = randomPath();
	if ( path ) {
		idle_followPathEntities( path );
	}
	
	if ( !getEnemy() && !AI_ACTIVATED && !AI_PAIN ) {
		// sit in our idle anim till we're activated
		allowMovement( false );
		playCustomCycle( animname, 4 );
		while( !AI_PAIN && !AI_ACTIVATED ) {
			if ( checkForEnemy( true ) ) {
				break;
			}
			waitFrame();
		}
		allowMovement( true );
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	}
	
	trigger_wakeup_targets();
	sight_enemy();
}

/*
=====================
monster_base::wake_on_trigger
=====================
*/
void monster_base::wake_on_trigger() {
	string	animname;
	entity path;

	if ( !getIntKey( "attack_path" ) ) {
		path = randomPath();
		if ( path ) {
			idle_followPathEntities( path );
		}
	}

	if ( !getEnemy() && !AI_ACTIVATED && !AI_PAIN ) {
		// sit in our idle anim till we're activated
		allowMovement( false );
		
		animname = self.getKey( "anim" );
		playCustomCycle( animname, 4 );
		
		waitUntil( AI_ACTIVATED || AI_PAIN );
		
		allowMovement( true );
		
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	}
	
	trigger_wakeup_targets();
	if ( getIntKey( "attack_path" ) ) {
		// follow a path and fight player at end
		path = randomPath();
		if ( path ) {
			ignoreEnemies = true;
			run = true;
			idle_followPathEntities( path );
			ignoreEnemies = false;
		}
	} else {
		sight_enemy();
	}
}

/*
=====================
monster_base::wake_on_enemy
=====================
*/
void monster_base::wake_on_enemy() {
	string animname;
	entity path;

	if ( !getIntKey( "attack_path" ) ) {
		path = randomPath();
		if ( path ) {
			idle_followPathEntities( path );
		}
	}

	if ( !getEnemy() && !AI_ACTIVATED && !AI_PAIN ) {
		// sit in our idle anim till we're activated
		allowMovement( false );
		animname = self.getKey( "anim" );
		playCustomCycle( animname, 4 );

		while( !AI_PAIN && !AI_ACTIVATED ) {
			if ( checkForEnemy( true ) ) {
				break;
			}
			waitFrame();
		}
	}
	
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	
	trigger_wakeup_targets();

	if ( getIntKey( "attack_path" ) ) {
		// follow a path and fight player at end
		path = randomPath();
		if ( path ) {
			run = true;
			ignoreEnemies = true;
			idle_followPathEntities( path );
			ignoreEnemies = false;
		}
	} else {
		sight_enemy();
	}
}

/*
=====================
monster_base::wake_on_attackcone
=====================
*/
void monster_base::wake_on_attackcone() {
	string animname;
	entity path;
	entity enemy;

	if ( !getIntKey( "attack_path" ) ) {
		path = randomPath();
		if ( path ) {
			idle_followPathEntities( path );
			run = path.getIntKey( "run" );
			while( !AI_MOVE_DONE && !AI_ACTIVATED && !AI_PAIN ) {
				enemy = findEnemyInCombatNodes();
				if ( enemy ) {
					setEnemy( enemy );
					break;
				}
				waitFrame();
			}
		}
	}

	if ( !getEnemy() && !AI_ACTIVATED && !AI_PAIN ) {
		// sit in our idle anim till we're activated
		allowMovement( false );
		
		animname = self.getKey( "anim" );
		playCustomCycle( animname, 4 );
		
		while( !AI_ACTIVATED && !AI_PAIN ) {
			enemy = findEnemyInCombatNodes();
			if ( enemy ) {
				setEnemy( enemy );
				break;
			}
			waitFrame();
		}
				
		allowMovement( true );
		
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	}

	trigger_wakeup_targets();
	
	if ( getIntKey( "attack_path" ) ) {
		// follow a path and fight player at end
		path = randomPath();
		if ( path ) {
			run = true;
			ignoreEnemies = true;
			idle_followPathEntities( path );
			ignoreEnemies = false;
		}
	} else {
		sight_enemy();
	}
}

/*
=====================
monster_base::idle_followPathEntities
=====================
*/
void monster_base::idle_followPathEntities( entity pathnode ) {
	string nodeaction;
	string triggername;
	entity triggerent;
	
	current_path = pathnode;
	do {
		next_path = current_path.randomPath();
		nodeaction = current_path.getKey( "classname" );
		if ( hasFunction( nodeaction ) ) {
			callFunction( nodeaction );
		} else {
			sys.warning( "'" + getName() + "' encountered an unsupported path entity '" + nodeaction + "' on entity '" + current_path.getName() + "'\n" );
			return;
		}

		if ( checkForEnemy( true ) ) {
			return;
		}
		
		// trigger any entities the path had targeted
		triggername = current_path.getKey( "trigger" );
		if ( triggername != "" ) {
			triggerent = sys.getEntity( triggername );
			if ( triggerent ) {
				triggerent.activate( self );
			}
		}

		current_path = next_path;
	} while( !( !current_path ) );
}

/***********************************************************************

	path functions

***********************************************************************/

/*
=====================
monster_base::path_corner
=====================
*/
void monster_base::path_corner() {
	string customAnim;

	if ( current_path.getKey( "run" ) != "" ) {
		run = current_path.getIntKey( "run" );
	}
	customAnim = current_path.getKey( "anim" );

	while( 1 ) {
		if ( customAnim != "" ) {
			playCustomCycle( customAnim, 4 );
		}
		moveToEntity( current_path );
		waitFrame();
		while( !AI_MOVE_DONE ) {
			if ( sys.influenceActive() ) {
				break;
			}
			if ( checkForEnemy( true ) ) {
				break;
			}
			waitFrame();
		}

		if ( customAnim != "" ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
		}

		if ( sys.influenceActive() ) {
			stopMove();
			while( sys.influenceActive() ) {
				waitFrame();
			}
			continue;
		}
		break;
	}

	if ( AI_DEST_UNREACHABLE ) {
		// Can't reach
		sys.warning( "entity '" + getName() + "' couldn't reach path_corner '" + current_path.getName() + "'" );
		waitFrame();
	}
}

/*
=====================
monster_base::path_anim
=====================
*/
void monster_base::path_anim() {
	string animname;
	float  ang;
	float  blend_in;
	float  blend_out;

	animname = current_path.getKey( "anim" );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );

	if ( current_path.getKey( "angle" ) != "" ) {
		ang = current_path.getFloatKey( "angle" );
		turnTo( ang );
		while( !facingIdeal() ) {
			if ( checkForEnemy( true ) ) {
				return;
			}
			waitFrame();
		}
	}

	playCustomAnim( animname, blend_in, blend_out );
	while( !animDone( ANIMCHANNEL_TORSO, blend_out ) ) {
		if ( checkForEnemy( true ) ) {
			break;
		}
		waitFrame();
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", blend_out );
}

/*
=====================
monster_base::path_cycleanim
=====================
*/
void monster_base::path_cycleanim() {
	string animname;
	vector ang;
	float  blend_in;
	float  blend_out;
	float  waittime;

	animname = current_path.getKey( "anim" );
	blend_in = current_path.getIntKey( "blend_in" );
	blend_out = current_path.getIntKey( "blend_out" );
	ang = current_path.getAngles();
	turnTo( ang_y );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}
	playCustomCycle( animname, blend_in );

	waittime = current_path.getFloatKey( "wait" );
	if ( waittime ) {
		waittime += sys.getTime();
		while( sys.getTime() < waittime ) {
			if ( checkForEnemy( true ) ) {
				return;
			}
			waitFrame();
		}
	} else {
		AI_ACTIVATED = false;
		while( !AI_ACTIVATED ) {
			if ( checkForEnemy( true ) ) {
				return;
			}
			waitFrame();
		}
	}
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", blend_out );
}

/*
=====================
monster_base::path_turn
=====================
*/
void monster_base::path_turn() {
	vector ang;

	ang = current_path.getAngles();
	turnTo( ang_y );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}
}

/*
=====================
monster_base::path_wait
=====================
*/
void monster_base::path_wait() {
	float waittime;

	waittime = current_path.getFloatKey( "wait" );
	waittime += sys.getTime();
	while( sys.getTime() < waittime ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}
}

/*
=====================
monster_base::path_waitfortrigger
=====================
*/
void monster_base::path_waitfortrigger() {
	AI_ACTIVATED = false;
	while( !AI_ACTIVATED ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}
	AI_ACTIVATED = false;
}
			
/*
=====================
monster_base::path_hide
=====================
*/
void monster_base::path_hide() {
	hide();
}

/*
=====================
monster_base::path_show
=====================
*/
void monster_base::path_show() {
	waitUntil( canBecomeSolid() );
	show();
}

/*
=====================
monster_base::path_attack
=====================
*/
void monster_base::path_attack() {
	entity	enemy;
	float	delta;
	boolean do_run;
	float	range;
	float	attack_flags;

	enemy = current_path.getEntityKey( "enemy" );	
	if ( !enemy ) {
		return;
	}

	setEnemy( enemy );
	locateEnemy();

	AI_ACTIVATED = false;
	while( !AI_ACTIVATED && !( !enemy ) ) {
		stopMove();
		while( sys.influenceActive() ) {
			waitFrame();
		}
		if ( enemyRange() > run_distance ) {
			do_run = true;
		} else {
			do_run = false;
		}

		// set our enemy again in case we were shot by the player
		setEnemy( enemy );
		if ( AI_ENEMY_DEAD ) {
			break;
		}
		moveToEnemy();
		if ( AI_MOVE_DONE ) {
			locateEnemy();
			moveToEnemy();
			if ( AI_MOVE_DONE ) {
				// prevent runaway loops if monster can't reach enemy
				waitFrame();
			}
		}
		while( !AI_ACTIVATED && !AI_MOVE_DONE && !AI_DEST_UNREACHABLE && !( !enemy ) ) {
			// set our enemy again in case we were shot by the player
			setEnemy( enemy );
			if ( AI_ENEMY_DEAD ) {
				break;
			}

			moveToEnemy();

			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}

			if ( sys.influenceActive() ) {
				break;
			}
			attack_flags = check_attacks();
			if ( attack_flags ) {
				do_attack( attack_flags );
			}
			
			range = enemyRange();
			if ( range > run_distance ) {
				do_run = true;
			}
			
			delta = getTurnDelta();
			if ( ( delta > walk_turn ) || ( delta < -walk_turn ) ) {
				run = false;
			} else {
				run = do_run;
			}

			waitFrame();
		}
		stopMove();
	}
}

/***********************************************************************

	Combat

***********************************************************************/

/*
=====================
monster_base::state_Combat
=====================
*/
void monster_base::state_Combat() {
	float attack_flags;

	eachFrame {
		faceEnemy();
		if ( AI_ENEMY_IN_FOV ) {
			lookAtEnemy( 1 );
		}

		if ( sys.influenceActive() ) {
			waitFrame();
			continue;
		}

		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
		}

		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			continue;
		}

		if ( !combat_chase() ) {
			locateEnemy();
			if ( !combat_chase() ) {
				combat_lost();
			}
		}

		waitFrame();
	}
}

/*
=====================
monster_base::check_blocked

returns true when an attack was called, since the move command may be different from when entering the function.
=====================
*/
boolean monster_base::check_blocked() {
	entity	obstacle;
	float	attack_flags;
	monster_base monster;
	float	endTime;
	boolean oldrun;

	oldrun = run;
	if ( AI_BLOCKED ) {
		//sys.print( sys.getTime() + " : " + getName() + " is stuck in place\n" );
		saveMove();
		run = true;
		wander();
		endTime = sys.getTime() + 2;
		while( sys.getTime() < endTime ) {
			attack_flags = check_attacks();
			if ( attack_flags ) {
				restoreMove();
				do_attack( attack_flags );
				run = oldrun;
				return true;
			}
			waitFrame();
		}
		restoreMove();
	} else if ( moveStatus() == MOVE_STATUS_BLOCKED_BY_OBJECT ) {
		float force = getFloatKey( "kick_force" );
		if ( !force ) {
			force = 60;
		}
		kickObstacles( getObstacle(), force );
	} else if ( moveStatus() > MOVE_STATUS_BLOCKED_BY_OBJECT ) {
		// just wait for the path to be clear
		obstacle = getObstacle();
		monster = obstacle;
		if ( monster ) {
			if ( monster.blocked ) {
				run = oldrun;
				return false;
			}
		}
		blocked = true;
		saveMove();
		while( moveStatus() > MOVE_STATUS_BLOCKED_BY_OBJECT ) {
			run = true;
			wander();
			endTime = sys.getTime() + 1;
			while( sys.getTime() < endTime ) {
				if ( AI_MOVE_DONE ) {
					faceEnemy();
				}
				attack_flags = check_attacks();
				if ( attack_flags ) {
					blocked = false;
					restoreMove();
					do_attack( attack_flags );
					run = oldrun;
					return true;
				}
				waitFrame();
			}
			restoreMove();
		}
		blocked = false;
	}

	run = oldrun;
	return false;
}

/*
=====================
monster_base::combat_chase
=====================
*/
boolean monster_base::combat_chase() {
	float	delta;
	boolean do_run;
	float	range;
	float	attack_flags;
	
	if ( !AI_ENEMY_VISIBLE || ( enemyRange() > run_distance ) ) {
		do_run = true;
	} else {
		do_run = false;
	}

	moveToEnemy();
	if ( AI_MOVE_DONE ) {
		return false;
	}

	waitFrame();
	if ( AI_MOVE_DONE ) {
		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			return true;
		}
		return false;
	}
	while( !AI_MOVE_DONE && !AI_DEST_UNREACHABLE ) {
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
		}

		if ( sys.influenceActive() ) {
			return true;
		}
		
		if ( AI_ENEMY_IN_FOV ) {
			lookAtEnemy( 1 );
		}

		attack_flags = check_attacks();
		if ( attack_flags ) {
			do_attack( attack_flags );
			return true;
		}

		if ( check_blocked() ) {
			return true;
		}

		range = enemyRange();
		if ( !AI_ENEMY_VISIBLE || ( range > run_distance ) ) {
			do_run = true;
		}
		
		delta = getTurnDelta();
		if ( ( delta > walk_turn ) || ( delta < -walk_turn ) ) {
			run = false;
		} else {
			run = do_run;
		}

		waitFrame();
	}

	return true;
}

/*
=====================
monster_base::checkTurretAttack

tests if monster can still do a turret attack from current location
=====================
*/
boolean monster_base::checkTurretAttack() {
	return canHitEnemy();
}

/*
=====================
monster_base::combat_turret_node
=====================
*/
void monster_base::combat_turret_node( entity node ) {
	vector	pos;
	float	min_wait;
	float	max_wait;
	float	num_shots;
	float	wait_end;
	float	current_time;
	float	count;
	boolean	exit;
	boolean do_melee;

	min_wait = node.getFloatKey( "min_wait" );
	max_wait = node.getFloatKey( "max_wait" );
	num_shots = node.getFloatKey( "num_shots" );

	pos = node.getOrigin();

	exit = false;
	while( !AI_ENEMY_DEAD ) {
		if ( !node ) {
			// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
			break;
		}
		// run to the combat node
		allowMovement( true );
		run = true;

		moveToEntity( node );
		while( !AI_MOVE_DONE ) {
			if ( sys.influenceActive() ) {
				stopMove();
				while( sys.influenceActive() ) {
                    waitFrame();
				}
				moveToEntity( node );
			}

			if ( !node ) {
				// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
				break;
			}

			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}
			// exit out if we can't get there or we can do a melee attack
			do_melee = testMeleeAttack();
			if ( AI_DEST_UNREACHABLE || do_melee ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
				return;
			}
			waitFrame();
		}

		if ( !AI_ENEMY_VISIBLE ) {
			waitFrame();
			continue;
		}

		if ( !checkTurretAttack() ) {
			waitFrame();
			continue;
		}

		if ( !node ) {
			// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
			break;
		}

		faceEnemy();
		allowMovement( false );

		// make sure he's precisely at the node
		slideTo( pos, 0.25 );
		waitUntil( AI_MOVE_DONE );
		faceEnemy();
	
		// do our attack
		allowMovement( false );
		
		count = int( sys.random( num_shots ) ) + 1;
		while( count > 0 ) {
			if ( sys.influenceActive() ) {
				break;
			}
			if ( !node ) {
				// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
				exit = true;
				break;
			}
			animState( ANIMCHANNEL_TORSO, "Torso_TurretAttack", 4 );
			while( inAnimState( ANIMCHANNEL_TORSO, "Torso_TurretAttack" ) ) {
				if ( AI_ENEMY_IN_FOV ) {
					lookAtEnemy( 1 );
				}
				waitFrame();
			}
			if ( testMeleeAttack() || AI_ENEMY_DEAD ) {
				exit = true;
				break;
			}
			count--;
		}

		if ( exit ) {
			break;
		}
		
		faceEnemy();
		current_time = sys.getTime();
		wait_end = current_time + min_wait + sys.random( max_wait - min_wait );
		while( sys.influenceActive() || ( sys.getTime() < wait_end ) ) {
			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}
			// exit out if we can do a melee attack or enemy is dead
			// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
			if ( testMeleeAttack() || AI_ENEMY_DEAD || !node ) {
				exit = true;
				break;
			}
			waitFrame();
		}
		
		if ( exit ) {
			break;
		}
	}
	
	if ( node ) {
		// we're done with the node, so get rid of it so we don't use it again
		node.remove();
	}
	
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/*
=====================
monster_base::checkNodeAnim
=====================
*/
void monster_base::checkNodeAnim( entity node, string prefix, string anim ) {
	if ( !hasAnim( ANIMCHANNEL_TORSO, prefix + "_" + anim ) ) {
		sys.error( "AI node '" + node.getName() + "' specifies missing anim '" + prefix + "_" + anim + "' on monster '" + getName() + "'" );
	}
}

/*
=====================
monster_base::combat_attack_cone
=====================
*/
void monster_base::combat_attack_cone( entity node ) {
	vector	ang;
	vector	pos;
	float	min_wait;
	float	max_wait;
	float	num_shots;
	float	wait_end;
	float	current_time;
	float	count;
	boolean	exit;
	boolean	attack;
	boolean do_melee;
	boolean dont_wait;
	string	prefix;

	// run to the combat node
	run = true;
	moveToEntity( node );
	while( !AI_MOVE_DONE ) {
		if ( AI_ENEMY_IN_FOV ) {
			lookAtEnemy( 1 );
		}
		// exit out if we can't get there or we can do a melee attack
		do_melee = testMeleeAttack();
		if ( AI_DEST_UNREACHABLE || do_melee || !enemyInCombatCone( node, false ) || AI_ENEMY_DEAD || !node ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
			return;
		}
		waitFrame();
	}

	if ( !node ) {
		// level designers sometimes remove the combat node, so check for it so the thread doesn't get killed
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
		return;
	}

	// set our anim prefix
	prefix = node.getKey( "anim" );
	if ( prefix == "" ) {
		sys.error( "Missing 'anim' key on entity '" + node.getName() + "'" );
	}
	setAnimPrefix( prefix );
	checkNodeAnim( node, prefix, "out" );
	checkNodeAnim( node, prefix, "fire" );
	checkNodeAnim( node, prefix, "in" );
	checkNodeAnim( node, prefix, "wait" );
	
	min_wait = node.getFloatKey( "min_wait" );
	max_wait = node.getFloatKey( "max_wait" );
	num_shots = node.getFloatKey( "num_shots" );
	dont_wait = getIntKey( "wake_on_attackcone" );
	if ( dont_wait ) {
		setKey( "wake_on_attackcone", "0" );
	}

	// face the direction the node points
	ang = node.getAngles();
	turnTo( ang_y );
	
	exit = false;
	attack = false;
	pos = node.getOrigin();
	while( !( !node ) && enemyInCombatCone( node, true ) ) {
		allowMovement( false );

		// play the wait animation
		playCustomCycle( "wait", 4 );
		
		// make sure he's precisely at the node
		slideTo( pos, 0.5 );
		current_time = sys.getTime();
		if ( dont_wait ) {
			dont_wait = false;
			wait_end = current_time + 0.5;
		} else {
			wait_end = current_time + min_wait + sys.random( max_wait - min_wait );
		}
		while( sys.influenceActive() || !AI_MOVE_DONE || !facingIdeal() || ( current_time < wait_end ) ) {
			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}
			// exit out if we can do a melee attack or enemy has left the combat cone
			if ( testMeleeAttack() ) {
				exit = true;
				break;
			}
			if ( !node || !enemyInCombatCone( node, false ) ) {
				exit = true;
				break;
			}
			waitFrame();
			current_time = sys.getTime();
		}
		
		if ( exit ) {
			break;
		}

		// do our attack
		allowMovement( true );
		playCustomAnim( "out", 4, 0 );
		while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}
			if ( testMeleeAttack() ) {
				exit = true;
				break;
			}
			if ( !node || !enemyInCombatCone( node, true ) ) {
				exit = true;
				break;
			}				
			waitFrame();
		}
		
		if ( exit ) {
			break;
		}

		AI_DAMAGE = false;
		allowMovement( false );
		count = int( sys.random( num_shots ) ) + 1;
		while( !AI_DAMAGE && ( count > 0 ) ) {
			if ( sys.influenceActive() ) {
				break;
			}
			playCustomAnim( "fire", 0, 0 );
			while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
				if ( sys.influenceActive() ) {
					break;
				}
				if ( AI_ENEMY_IN_FOV ) {
					lookAtEnemy( 1 );
				}
				if ( testMeleeAttack() ) {
					exit = true;
					break;
				}
				if ( !node || !enemyInCombatCone( node, true ) ) {
					exit = true;
					break;
				}				
				waitFrame();
			}
			attack = true;
			
			if ( testMeleeAttack() ) {
				exit = true;
				break;
			}
			if ( !node || !enemyInCombatCone( node, true ) ) {
				exit = true;
				break;
			}				
			count--;
		}
		AI_DAMAGE = false;
		
		if ( exit ) {
			break;
		}

		allowMovement( true );
		playCustomAnim( "in", 0, 4 );
		while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
			if ( AI_ENEMY_IN_FOV ) {
				lookAtEnemy( 1 );
			}
			if ( testMeleeAttack() ) {
				exit = true;
				break;
			}
			if ( !node || !enemyInCombatCone( node, true ) ) {
				exit = true;
				break;
			}				
			waitFrame();
		}
		
		if ( exit ) {
			break;
		}
	}
	
	if ( !( !node ) && attack ) {
		// mark the node as used in case it's single use
		node.markUsed();
	}
	
	allowMovement( true );
	setAnimPrefix( "" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

/*
=====================
monster_base::combat_ainode
=====================
*/
void monster_base::combat_ainode( entity node ) {
	if ( node.getKey( "classname" ) == "ai_attackcone_turret" ) {
		combat_turret_node( node );
	} else {
		combat_attack_cone( node );
	}
}

/*
=====================
monster_base::combat_lost
=====================
*/
void monster_base::combat_lost() {
	if ( !ignore_lostcombat ) {
		setState( "state_LostCombat" );
	}
}

/*
=====================
monster_base::state_LostCombat
=====================
*/
void monster_base::state_LostCombat() {
	monster_base_lost_combat();
}

/*
=====================
monster_base::monster_base_lost_combat
=====================
*/
void monster_base::monster_base_lost_combat() {
	entity node;
	vector ang;
	float dist;
	float yaw;
	float attack_flags;
	entity possibleEnemy;
	float allow_attack;
	float lost_time;

	lost_time = sys.getTime() + sys.getFrameTime();
	allow_attack = sys.getTime() + 4;
	
	node = getClosestHiddenTarget( "ai_lostcombat" );
	if ( node ) {
		dist = distanceTo( node );
		if ( dist < 40 ) {
			// fixes infinite loops when close to lost combat node
			waitFrame();
		} else {
			run = true;
			moveToEntity( node );
			while( !AI_MOVE_DONE ) {
				if ( sys.influenceActive() ) {
					break;
				}
				possibleEnemy = heardSound( true );
				if ( possibleEnemy ) {
					if ( canReachEntity( possibleEnemy ) ) {
						setEnemy( possibleEnemy );
						break;
					}
				}
				if ( canReachEnemy() ) {
					if ( AI_ENEMY_IN_FOV || AI_PAIN ) {
						break;
					}
				}
				if ( check_blocked() ) {
					break;
				}
				waitFrame();

				// allow attacks when enemy is outside of fov
				if ( sys.getTime() > allow_attack ) {
					AI_ENEMY_IN_FOV = AI_ENEMY_VISIBLE;
				}
				attack_flags = check_attacks();
				if ( attack_flags ) {
					do_attack( attack_flags );
					setState( "state_Combat" );
				}
			}
			ang = node.getAngles();
			turnTo( ang_y );
			while( !AI_MOVE_DONE ) {
				if ( canReachEnemy() ) {
					if ( heardSound( true ) ) {
						break;
					}
					if ( AI_ENEMY_IN_FOV || AI_PAIN ) {
						break;
					}
				}
				waitFrame();
			}
		}
	} else {
		run = true;
		moveToCover();
		if ( AI_DEST_UNREACHABLE ) {
			combat_wander();
		}
		
		// if we're not already in cover
		if ( !AI_MOVE_DONE ) {
			while( !AI_MOVE_DONE ) {
				if ( sys.influenceActive() ) {
					break;
				}
				// allow attacks when enemy is outside of fov
				if ( sys.getTime() > allow_attack ) {
					AI_ENEMY_IN_FOV = AI_ENEMY_VISIBLE;
				}
				attack_flags = check_attacks();
				if ( attack_flags ) {
					do_attack( attack_flags );
					setState( "state_Combat" );
				}
				
				possibleEnemy = heardSound( true );
				if ( possibleEnemy ) {
					if ( canReachEntity( possibleEnemy ) ) {
						setEnemy( possibleEnemy );
						break;
					}
				}
				if ( canReachEnemy() ) {
					if ( AI_ENEMY_IN_FOV || AI_PAIN ) {
						break;
					}
				}
				
				if ( check_blocked() ) {
					break;
				}
				waitFrame();
			}

			
			if ( !sys.influenceActive() ) {
				if ( AI_ENEMY_VISIBLE ) {
					faceEnemy();
				} else if ( AI_MOVE_DONE ) {
					// turn around to face the way we came
					yaw = getCurrentYaw();
					turnTo( yaw + 180 );
				}
			}
		}
	}

	// wait at least 1 frame to avoid loops
	waitFrame();

	if ( lost_time >= sys.getTime() ) {
		combat_wander();
	}

	if ( AI_ENEMY_VISIBLE || sys.influenceActive() ) {
		setState( "state_Combat" );
	} else {
		clearEnemy();
		setState( "state_Idle" );
	}
}

/*
=====================
monster_base::combat_wander
=====================
*/
void monster_base::combat_wander() {
	float endtime;
	float mintime;

	mintime = sys.getTime() + 0.2;
	endtime = sys.getTime() + 3;
	wander();
	while( sys.getTime() < endtime ) {
		if ( sys.influenceActive() ) {
			break;
		}
		if ( check_attacks() ) {
			break;
		}
		if ( sys.getTime() > mintime ) {
			if ( canReachEnemy() ) {
				if ( heardSound( true ) ) {
					break;
				}
				if ( AI_ENEMY_IN_FOV || AI_PAIN ) {
					break;
				}
			}
		}

		waitFrame();
	}

	// wait at least 1 frame to avoid loops
	waitFrame();
	setState( "state_Combat" );
}

/*
=====================
monster_base::state_FollowAlternatePath
=====================
*/
void monster_base::state_FollowAlternatePath() {
	if ( inAnimState( ANIMCHANNEL_TORSO, "Torso_CustomCycle" ) || inAnimState( ANIMCHANNEL_TORSO, "Torso_CustomAnim" ) ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
	}

	ignoreEnemies = true;
	idle_followPathEntities( current_path );
	ignoreEnemies = false;
	setState( "state_Idle" );
}

/*
=====================
monster_base::follow_alternate_path1
=====================
*/
void monster_base::follow_alternate_path1() {
	current_path = getEntityKey( "alt_path1" );
	setState( "state_FollowAlternatePath" );
}

/*
=====================
monster_base::follow_alternate_path2
=====================
*/
void monster_base::follow_alternate_path2() {
	current_path = getEntityKey( "alt_path2" );
	setState( "state_FollowAlternatePath" );
}

/*
=====================
monster_base::follow_alternate_path3
=====================
*/
void monster_base::follow_alternate_path3() {
	current_path = getEntityKey( "alt_path2" );
	setState( "state_FollowAlternatePath" );
}

//@doomscript-blueprint begin 6
//@source 06DA43EE
//@catalog 0C260740
//@node 4FA8FA12-0 40 40
//@node A3FA6755-0 330 40
//@node 2B943D1A-0 610 200
//@node 7D639861-0 40 40
//@node A4ABA354-0 330 40
//@node 6705789D-0 -110 145
//@node 1EC92E48-0 -315 337
//@node E5B47AED-0 120 145
//@node 7B0989DB-0 610 200
//@node 2940AD6E-0 890 40
//@node EEB4C269-0 685 140
//@node 193D7370-0 480 140
//@node F19EE9DD-0 1170 40
//@node 5219BBEE-0 965 324
//@node 1E586734-0 40 40
//@node CC44251D-0 330 40
//@node 002851EC-0 -110 145
//@node 8071F8DC-0 120 145
//@node 1A3D4771-0 610 200
//@node A8950894-0 890 40
//@node E997B1A3-0 665 145
//@node 26CDFD87-0 1170 40
//@node 99430969-0 945 145
//@node 5E9F7338-0 1450 200
//@node F608011A-0 1225 305
//@node 69500B52-0 2010 200
//@node 70C0AFED-0 1805 305
//@node 0F0912E8-0 2290 40
//@node 09F25BF2-0 2085 145
//@node 9AC7E017-0 1880 145
//@node 3E290CDE-0 2570 200
//@node 3722B598-0 2345 305
//@node 61C69C73-0 2140 497
//@node 3E7776AB-0 2850 360
//@node 3B08546D-0 2645 552
//@node 698A1DF0-0 3130 360
//@node 67850EB0-0 2690 465
//@node 7EB36941-0 2485 657
//@node A2C1BA20-0 2920 465
//@node 0983D54C-0 3410 520
//@node 760DFED2-0 3690 40
//@node B3FE11B9-0 3970 40
//@node DE7BB19C-0 3765 324
//@node F3FDDF83-0 40 40
//@node 826FB6EC-0 330 40
//@node EE152C69-0 40 40
//@node F8257A27-0 40 40
//@node 5D88E7D9-0 40 40
//@node A9DCFF8F-0 330 40
//@node 71953F4F-0 125 145
//@node 310F044F-0 610 40
//@node 308AAC05-0 405 145
//@node 3A927406-0 890 40
//@node 9DFC6DE4-0 685 145
//@node 68260B75-0 1170 40
//@node DF80ADCF-0 945 145
//@node 9DD94E22-0 740 245
//@node 628E055B-0 535 245
//@node 1DB74CFF-0 1450 40
//@node B3D1C108-0 1225 145
//@node A2D74C7F-0 1020 245
//@node 2BC46CC2-0 815 245
//@node 86FCAF4B-0 1730 40
//@node C3024FFB-0 1505 145
//@node BFA506C3-0 1300 245
//@node 65CBA828-0 1095 245
//@node FE4B3E72-0 2010 40
//@node ABD46859-0 1805 145
//@node 54EAA58E-0 2290 40
//@node CD612CBC-0 2085 145
//@node 4CD0B4C6-0 40 40
//@node E8402B47-0 40 40
//@node 8D1006AF-0 40 40
//@node EDD8E524-0 330 40
//@node A8DF94D8-0 40 40
//@node 8298C2EB-0 330 40
//@node C6AAC16D-0 610 40
//@node 6093F730-0 890 40
//@node BE147D6F-0 40 40
//@node 7762E3D5-0 330 40
//@node C5DF66B7-0 610 40
//@node 76DEEB36-0 890 40
//@node 2D3AF876-0 1170 40
//@node 19A863E6-0 40 40
//@node 6D5AB0E6-0 330 40
//@node C77CB249-0 105 145
//@node 2751167F-0 610 40
//@node 85A9A535-0 405 145
//@node BB8754C0-0 200 145
//@node 40FDCFD9-0 890 200
//@node F1B9A281-0 665 305
//@node 4802E231-0 460 405
//@node 2E29528A-0 1170 200
//@node ECE7D0D1-0 945 305
//@node DD69CBAC-0 740 405
//@node 4ECD8216-0 1450 200
//@node ED337FC6-0 1245 305
//@node E42F887C-0 1040 305
//@node F45DDE2B-0 1730 360
//@node E21AEFE1-0 1525 460
//@node 6DE49825-0 1320 460
//@node 6A65ACFF-0 1320 538
//@node 28157514-0 2290 360
//@node BAE4ABCE-0 2085 460
//@node 9DE067EF-0 2570 200
//@node 473B5336-0 2345 305
//@node 91478E83-0 2140 497
//@node E8850E48-0 40 40
//@node 255C47AB-0 330 40
//@node F99BF524-0 105 145
//@node A25FE2C6-0 610 200
//@node 8D9B3379-0 890 40
//@node EB163E5E-0 685 145
//@node F0DC114A-0 1170 200
//@node ADD2A3DD-0 965 305
//@node 9E1539A8-0 1450 40
//@node 0DE8DD6F-0 1245 145
//@node 1DA6B5E7-0 1730 200
//@node 4BCA4046-0 1525 305
//@node A25FE2C6-1 2010 360
//@node 578132D4-0 2290 200
//@node 2B9410DC-0 2065 305
//@node C834E6E1-0 2570 200
//@node BD652811-0 2365 305
//@node CF523C65-0 2160 305
//@node 495AA5A0-0 2850 360
//@node 07039019-0 2625 465
//@node C834E6E1-1 3130 200
//@node 690D176C-0 2925 305
//@node 86BAF64A-0 2720 305
//@node A25FE2C6-2 3410 360
//@node BD5B4CAA-0 3690 200
//@node 4A8A7E05-0 3465 305
//@node 23520554-0 3970 200
//@node C3E83552-0 3765 305
//@node 9F97EFB2-0 4250 200
//@node 1FB44BB9-0 4045 305
//@node 89463570-0 3840 305
//@node A25FE2C6-3 4530 360
//@node FED3E497-0 5090 200
//@node 6BA35B45-0 4865 305
//@node 72FC475F-0 5370 360
//@node 153794B5-0 5650 200
//@node 0D7AC3EE-0 5445 305
//@node C2398BA8-0 5240 305
//@node DEE9FB60-0 5930 360
//@node C772BAC8-0 5705 465
//@node C834E6E1-2 6210 200
//@node 4E2A0397-0 6005 305
//@node 1912D6EB-0 5800 305
//@node AB9E8080-0 6490 360
//@node 12519DD7-0 6285 465
//@node A25FE2C6-4 6770 520
//@node 655CF001-0 7050 360
//@node 2E261AB9-0 6825 465
//@node C834E6E1-3 7330 360
//@node DDFE50CA-0 7125 465
//@node DD62F070-0 6920 465
//@node A25FE2C6-5 7610 520
//@node D57BE5A6-0 7890 40
//@node 3F4B4F78-0 7685 145
//@node F0DC114A-1 8170 40
//@node 74AE2146-0 7965 145
//@node 0B275832-0 8450 40
//@node BA4327AE-0 8245 145
//@node 495F8B16-0 8730 40
//@node 0DDB253B-0 8525 140
//@node 72FC475F-1 9010 40
//@node 29507EE7-0 40 40
//@node DDE98142-0 330 40
//@node ACE6B8E0-0 105 145
//@node AFD857DE-0 -100 245
//@node 076BFEAB-0 -305 245
//@node A0EB26FD-0 610 40
//@node 3D968EDC-0 385 145
//@node 7C3E8F75-0 890 40
//@node EDF92881-0 1170 40
//@node 2099F4F8-0 965 145
//@node 87593713-0 1450 40
//@node 45786797-0 1245 145
//@node 8F77495E-0 1730 40
//@node BCA90503-0 1525 145
//@node 132A10C1-0 2010 200
//@node 94388CED-0 1805 305
//@node 54914FCA-0 2290 360
//@node 89BD020A-0 2085 465
//@node DF0E21B7-0 1880 465
//@node 87593713-1 2570 360
//@node 87557C00-0 2365 465
//@node 66FA4818-0 2850 200
//@node 3E720A8C-0 2645 305
//@node 6525DB96-0 3130 360
//@node DD6A0C68-0 2905 465
//@node 175C440A-0 3410 520
//@node 54A32530-0 3205 625
//@node 41AFB5AF-0 3000 625
//@node B3D637F5-0 3000 709
//@node ADFC51BD-0 3690 680
//@node 2991B24A-0 3465 785
//@node C486AE47-0 3260 885
//@node 5E67ACD4-0 3055 885
//@node A0F83356-0 3055 963
//@node 92D5B523-0 3970 680
//@node 6455F4B2-0 3765 785
//@node 2D446432-0 3560 785
//@node 06ACA820-0 4250 840
//@node 1DD55A87-0 4530 520
//@node 42E8A377-0 4325 625
//@node 5299DC35-0 4120 625
//@node D3B78EE3-0 4120 709
//@node F37B7DEE-0 4810 680
//@node 99EC0FDA-0 4605 785
//@node 9D9D7A65-0 4400 785
//@node 3041C57F-0 5090 680
//@node 292456C1-0 5370 680
//@node 544C069E-0 5165 780
//@node 8BE7767B-0 4960 780
//@node 0FBFDB8D-0 5650 680
//@node 28A6A29F-0 5445 780
//@node 312C9662-0 5240 780
//@node A044BB52-0 5445 872
//@node D31981CB-0 5240 872
//@node 213FA703-0 5240 950
//@node 35C13AFE-0 5930 680
//@node 6DEBC6AA-0 5725 785
//@node C2E98FC9-0 6210 840
//@node 3C9EAA9B-0 6490 680
//@node 9CBA2DA1-0 6265 785
//@node ED40E329-0 6770 680
//@node 320A87A2-0 6565 780
//@node 1344EE8D-0 7050 200
//@node 28B4426D-0 40 40
//@node A7DBE1D0-0 330 40
//@node 0C9CF670-0 125 145
//@node DD4FDDF6-0 610 40
//@node C517D683-0 385 145
//@node FAFC09DA-0 890 40
//@node F8B82DF7-0 450 145
//@node 1C6A5687-0 680 145
//@node E666F376-0 1170 200
//@node E81B7E7E-0 1450 40
//@node BF67C76A-0 1245 145
//@node 5B30987A-0 1730 40
//@node 7E01DCD1-0 1525 145
//@node D00BC547-0 2010 200
//@node D8B2EA28-0 1805 305
//@node 52935E95-0 2290 200
//@node 87923F88-0 2085 305
//@node E73FDA7A-0 2570 200
//@node 0D63308F-0 2365 305
//@node C3251A01-0 3130 200
//@node 45C4A3AB-0 2905 305
//@node A7005C05-0 3410 200
//@node FA227D4D-0 3185 305
//@node 60B3C01E-0 3690 40
//@node B4747FC5-0 3465 145
//@node 49AC07C8-0 3260 245
//@node 7985ABB9-0 3055 245
//@node C646B22E-0 3970 200
//@node 6218248A-0 4250 40
//@node E6E3D429-0 4045 145
//@node C7E987CE-0 3840 145
//@node D41FD8E5-0 4530 200
//@node 9A8B851A-0 4325 392
//@node 9ACD43BF-0 4810 200
//@node 11993162-0 5090 200
//@node BDC2E8B1-0 4885 300
//@node 4321497B-0 5370 200
//@node 371E310C-0 5650 200
//@node F9F978F0-0 5930 200
//@node D5A82D74-0 6210 200
//@node 0D81BC42-0 6490 200
//@node 731CB4B6-0 6285 300
//@node E81B399C-0 6770 200
//@node ECF35C44-0 6565 300
//@node 62C12097-0 6360 300
//@node 3CF0A525-0 7050 200
//@node 914E2BD7-0 7330 200
//@node 64113EB7-0 7610 200
//@node C8AB2CB8-0 7405 305
//@node 5A9EAD47-0 7890 200
//@node C7951BBB-0 7685 305
//@node 4EE26BA6-0 7480 305
//@node 9ACD43BF-1 8170 200
//@node 11993162-1 8450 200
//@node C0E9AF00-0 8245 300
//@node 4321497B-1 8730 200
//@node 5B422651-0 9010 200
//@node CEE8D4D3-0 9290 200
//@node 1413A790-0 9065 305
//@node CDAD52D2-0 9570 200
//@node 371E310C-1 9850 200
//@node D5A82D74-1 10130 200
//@node 8A124351-0 10410 200
//@node 6F0B8A29-0 10205 305
//@node 8032A843-0 10000 305
//@node CEA60330-0 10690 360
//@node C51BAD95-0 10970 360
//@node BC2FE1E9-0 11250 360
//@node 92246AE0-0 11045 465
//@node 8A26CF1B-0 10840 465
//@node 20D71A2D-0 11530 360
//@node 56F0097E-0 11810 360
//@node 89B5457E-0 12090 360
//@node 9793E905-0 11885 465
//@node 76B7B849-0 11680 465
//@node A9EC0D96-0 12370 360
//@node 964F666B-0 12650 360
//@node 7BD9D8CF-0 13210 360
//@node 305D0910-0 13490 360
//@node F9F978F0-1 13770 200
//@node 8FBC2634-0 14050 200
//@node E81B399C-1 14330 200
//@node 0C3798D5-0 14125 300
//@node E3A60ADA-0 13920 300
//@node 3CF0A525-1 14610 200
//@node 914E2BD7-1 14890 200
//@node 6822D769-0 15170 200
//@node B2ECF188-0 14965 300
//@node 64113EB7-1 15450 200
//@node C9EABE51-0 15245 305
//@node 14C8612F-0 15730 200
//@node 551BA1CE-0 15505 305
//@node 9ACD43BF-2 16010 200
//@node 11993162-2 16290 200
//@node DE52C467-0 16085 300
//@node A0CAA8EA-0 16570 200
//@node CCAECC03-0 16365 305
//@node 7543926B-0 16160 305
//@node 6F9F44D9-0 16850 360
//@node 0FD9E46C-0 16645 465
//@node 06851C32-0 17130 360
//@node 4321497B-2 17410 200
//@node F9F978F0-2 17690 200
//@node B0EAF155-0 17970 40
//@node 42805B9B-0 17745 145
//@node BC56FD77-0 18250 40
//@node C5D28D9C-0 18045 145
//@node E0FEB225-0 17840 145
//@node EBBB08BF-0 18530 200
//@node 888E29B2-0 18325 300
//@node 49217A9D-0 18810 40
//@node 8AFF7F6C-0 18585 145
//@node A752259D-0 18380 245
//@node 967D89C0-0 18175 245
//@node 4BC609A1-0 19090 40
//@node 3B4AD0F9-0 18885 145
//@node 2BBF5F99-0 19370 200
//@node 03926A64-0 19165 300
//@node BFE3D781-0 19650 40
//@node 996B2798-0 19445 145
//@node 81519B70-0 19240 145
//@node C0BB1F04-0 19930 200
//@node 09D19D21-0 19705 305
//@node EC17D981-0 20210 360
//@node 3ADA7B31-0 20490 360
//@node BBD956B3-0 20265 465
//@node 361AA555-0 20770 360
//@node 97F10D31-0 21050 360
//@node CCF68F68-0 20825 465
//@node 72B43D58-0 21330 360
//@node 6598B828-0 21890 360
//@node C19A2DAF-0 22170 200
//@node 387798FE-0 21945 305
//@node 87FAB81E-0 22450 200
//@node 49CB382F-0 22225 305
//@node 87ADC7A6-0 22730 200
//@node 1E7B3F91-0 22525 305
//@node 3B3764B1-0 23010 360
//@node 4D7733A1-0 22805 465
//@node 3BA11742-0 23290 360
//@node 2E39C2DE-0 23085 465
//@node CD474682-0 23570 360
//@node B40A061A-0 23365 460
//@node 46DEC5E1-0 23850 360
//@node D4D94C93-0 23645 465
//@node 8B45E817-0 24130 40
//@node 1489143C-0 23925 145
//@node 5AA0FD37-0 24410 40
//@node 7B571684-0 40 40
//@node D44374A2-0 330 40
//@node 0F4F1DCA-0 610 40
//@node 9144BCD7-0 405 145
//@node CBC04868-0 890 40
//@node 6AFC45FC-0 685 145
//@node 02247CC7-0 40 40
//@node 60C381FF-0 330 40
//@node 5F665651-0 125 145
//@node 29A26BC3-0 -80 145
//@node E98263B9-0 610 200
//@node C56B5417-0 890 40
//@node A36111D2-0 450 145
//@node 5AFFF462-0 680 145
//@node E98263B9-1 1170 200
//@node F4EC73B1-0 1450 40
//@node C173722C-0 1010 145
//@node E874C2BC-0 1240 145
//@node E98263B9-2 1730 200
//@node 7E02D25A-0 2010 40
//@node 5D88F918-0 40 40
//@node D8DAC72B-0 330 40
//@node 4E627EC2-0 125 145
//@node CD0BDAF1-0 610 40
//@node BADD74D6-0 890 40
//@node 94FE0F77-0 1170 40
//@node A50F3815-0 1450 40
//@node E756E214-0 1730 40
//@node 42003A89-0 2010 40
//@node A0917DEE-0 1785 145
//@node 68AF6575-0 1580 245
//@node 4A2834FA-0 1375 245
//@node 934DBB62-0 2290 40
//@node E442AFA4-0 2085 140
//@node AF2D95E2-0 2570 40
//@node B553F48F-0 2345 145
//@node 7B16AC16-0 2850 40
//@node E217CE47-0 2645 140
//@node 50CF5BE0-0 3130 40
//@node A4F39B9E-0 3410 40
//@node FB0423E2-0 3690 40
//@node C0EE0288-0 3970 40
//@node F4E10533-0 40 40
//@node A2C530C2-0 330 40
//@node 4501A7EF-0 125 145
//@node 6565FD03-0 610 40
//@node 6541735B-0 890 200
//@node C67CAF05-0 1450 200
//@node 6405394F-0 1730 40
//@node AA40F779-0 40 40
//@node E2DBB534-0 330 40
//@node 1687D4F5-0 125 145
//@node 3AC38A3C-0 610 40
//@node DDE32FAD-0 890 40
//@node BBF901C6-0 450 145
//@node 4D221476-0 680 145
//@node 59D249D3-0 1170 200
//@node 79D4A6D0-0 945 305
//@node 8BD93628-0 740 405
//@node CF32F9B8-0 1450 360
//@node 9E53B2A3-0 1730 200
//@node 5C241368-0 40 40
//@node 723FAC8D-0 330 40
//@node DA65112A-0 610 40
//@node 39526E10-0 890 40
//@node FC0FBF55-0 1170 40
//@node 87916055-0 1450 40
//@node 17892BFF-0 40 40
//@node 36942D89-0 330 40
//@node 7F867C5D-0 125 145
//@node F008EC26-0 -80 145
//@node F19D4AF7-0 890 200
//@node 78FD90E7-0 1170 200
//@node 5594B9B9-0 685 300
//@node 1C8D399A-0 1450 200
//@node FDD2D9D6-0 1730 200
//@node 917B256C-0 2010 40
//@node 9B5DC954-0 2010 40
//@node 33570BDF-0 1805 145
//@node 5AE249F1-0 2570 200
//@node D57E750E-0 2850 200
//@node 828F6F50-0 3130 200
//@node 6354377E-0 3410 200
//@node D73BA6A5-0 3690 40
//@node 5B808F6F-0 40 40
//@node 3869845A-0 330 40
//@node A2CA3849-0 610 40
//@node 2F44F773-0 385 145
//@node 13A712C3-0 890 40
//@node B8AB682B-0 685 145
//@node F0BEE23A-0 480 145
//@node E9D3ADB6-0 1170 200
//@node 0CDC3E4B-0 1450 200
//@node 9D34330D-0 1225 305
//@node EF1406AF-0 1730 360
//@node 82E9467C-0 2010 200
//@node DC0999DD-0 2290 200
//@node 9F4F857F-0 2570 200
//@node 03CB3804-0 40 40
//@node 35891ABE-0 330 40
//@node 1204E271-0 125 145
//@node 82690F36-0 610 40
//@node FD4FFAFE-0 890 40
//@node 58C9B294-0 450 145
//@node 7D552A24-0 680 145
//@node 99925B1C-0 1170 200
//@node C8DC9839-0 1450 200
//@node 0F8C59FF-0 2010 200
//@node E0D145E1-0 40 40
//@node B38FFD22-0 330 40
//@node FED79629-0 610 40
//@node E2B51CEA-0 385 145
//@node 155335C4-0 890 40
//@node 77ED88E6-0 685 140
//@node AC6B678F-0 1170 40
//@node 01555060-0 965 140
//@node 93B74EBF-0 760 140
//@node 57F3E616-0 760 218
//@node C123C133-0 1450 40
//@node C96F14B8-0 1245 145
//@node CCA082FE-0 1730 200
//@node CFB1C305-0 2010 200
//@node 342675F5-0 1805 305
//@node 531F7A41-0 2290 40
//@node 28642FE5-0 2570 40
//@node 0440D3EA-0 2850 40
//@node 87016CEE-0 2625 145
//@node 1C267A2A-0 3130 40
//@node C6624845-0 2925 145
//@node F8D110DE-0 3410 200
//@node 8FD2DEED-0 3205 300
//@node DE92B81A-0 3690 40
//@node 6AD71531-0 3485 145
//@node 61956CF4-0 3280 145
//@node 04D2CACB-0 3280 229
//@node B38FFD22-1 3970 200
//@node 155335C4-1 4250 200
//@node B6AE6FEB-0 4045 300
//@node F47E953C-0 4530 200
//@node 685D56F3-0 4325 305
//@node D5F3CB8E-0 4120 305
//@node 8D3BAB15-0 4120 389
//@node 685CF317-0 4810 360
//@node 8FA45AB5-0 4585 465
//@node 57D65FF6-0 5090 520
//@node 0D3B016B-0 5370 360
//@node 28642FE5-1 5650 200
//@node 531F7A41-1 5930 200
//@node FF2D24B8-0 6210 40
//@node 23F2B7AF-0 6490 40
//@node 4D8C1492-0 40 40
//@node 855FF5C2-0 330 40
//@node 81949288-0 -110 145
//@node 538CF238-0 120 145
//@node A1917E6B-0 610 200
//@node B442EA10-0 385 305
//@node 9EDCB1AD-0 890 200
//@node 6BCD9DAC-0 685 305
//@node 69408173-0 1170 360
//@node 202B181F-0 965 460
//@node E9D1A989-0 1450 40
//@node 90889226-0 1245 145
//@node E1FC8785-0 1040 145
//@node E436CBAC-0 1040 229
//@node F4132755-0 1730 200
//@node 3573023E-0 2010 200
//@node 07E38BFF-0 1785 305
//@node D79B70B7-0 2290 200
//@node 7AFC967C-0 2085 300
//@node 96618B94-0 2570 200
//@node D0FE5EB5-0 2365 300
//@node 12C3AE42-0 2160 300
//@node 859FD301-0 2160 378
//@node DEAB16E4-0 2850 200
//@node 7D0AF624-0 3130 200
//@node 3698759B-0 3410 40
//@node E88D00D3-0 3690 40
//@node EA3FBF8C-0 3465 145
//@node A1917E6B-1 3970 200
//@node 1FB2953D-0 3745 305
//@node 9EDCB1AD-1 4250 200
//@node D04EB699-0 4045 305
//@node 394FE719-0 4530 360
//@node 7C4637AE-0 4325 465
//@node 0091D5BE-0 4810 360
//@node 6138427A-0 4605 465
//@node 69408173-1 5090 360
//@node 5CD6F706-0 4885 460
//@node FCFDBDD8-0 5370 360
//@node B2632582-0 5165 465
//@node 7EABE846-0 5930 200
//@node 8C4228FE-0 40 40
//@node C2A2C0D2-0 330 40
//@node DE2E483B-0 -110 145
//@node 915B498B-0 120 145
//@node 17851EBF-0 610 200
//@node 1CFBA5B7-0 385 305
//@node 36C7B19D-0 890 200
//@node 6FBACF30-0 685 305
//@node 36961573-0 1170 360
//@node 04DBAA41-0 965 460
//@node 5298DCB9-0 1450 40
//@node 3E56B078-0 1245 145
//@node 9913945F-0 1040 145
//@node CD218B76-0 1040 229
//@node 11AC4355-0 1730 200
//@node 9B8248F2-0 2010 200
//@node 4266AF3C-0 1785 305
//@node 15BC0CB7-0 2290 200
//@node 82A5581F-0 2085 300
//@node DE8BCB51-0 2570 200
//@node 49E9287E-0 2365 305
//@node F58A2AB3-0 2160 305
//@node 280581C2-0 2160 389
//@node 7E58FA0E-0 2850 360
//@node 3B5B7A36-0 2625 465
//@node B4EE2A1B-0 3130 520
//@node 039FDCA2-0 3410 360
//@node 85CF0AE4-0 3690 40
//@node B0ED8A24-0 3970 40
//@node 89BCF19B-0 4250 40
//@node B90AB143-0 4530 40
//@node F6F718E2-0 4305 145
//@node 17851EBF-1 4810 200
//@node E74DA982-0 4585 305
//@node 36C7B19D-1 5090 200
//@node AAC80A7D-0 4885 305
//@node 2FB045F2-0 5370 360
//@node 7714AFF9-0 5165 465
//@node 7C2DC1B5-0 5650 360
//@node 64D61789-0 5445 465
//@node 36961573-1 5930 360
//@node C5099F98-0 5725 460
//@node 1FAEDCAC-0 6210 360
//@node C4FD62A9-0 6005 465
//@node 12955C46-0 6770 200
//@node 0E93C3C5-0 40 40
//@node DEAC120B-0 330 40
//@node FB40E3E1-0 -110 145
//@node 7523E151-0 120 145
//@node 11509940-0 610 200
//@node 9F5A1572-0 385 305
//@node 94D245C6-0 890 200
//@node 063302C7-0 685 305
//@node ACB6C05A-0 1170 360
//@node 9DC416F1-0 965 460
//@node B876FEFE-0 1450 360
//@node 8A66D4E0-0 1225 465
//@node EEF6BAF9-0 1020 565
//@node 37ACA0FC-0 815 565
//@node 1985F3B0-0 1730 360
//@node EE6E9721-0 1525 465
//@node ECC9F622-0 1320 465
//@node 7DAAB96C-0 1320 549
//@node 39227EA1-0 1320 633
//@node 34198786-0 2010 520
//@node E89D8AFC-0 1785 625
//@node 3DE86F41-0 2290 520
//@node 4CC8150C-0 2085 625
//@node D0FB8BF1-0 2570 680
//@node C397BBC0-0 2365 780
//@node C066C86C-0 2850 680
//@node B951ACC7-0 3130 520
//@node FD6D9B66-0 3410 40
//@node 703C29B4-0 3205 145
//@node 8BCC0505-0 3000 145
//@node A791E42C-0 3000 229
//@node 7AE750A6-0 3690 200
//@node 6EA000F7-0 3970 200
//@node 4503F963-0 3745 305
//@node 4CA7F310-0 4250 200
//@node 71FF582E-0 4045 300
//@node 5DF39B10-0 4530 200
//@node FC7F34A5-0 4325 305
//@node 41131DB6-0 4120 305
//@node 99051F9D-0 4120 389
//@node 34198786-1 4810 360
//@node 743AE9F1-0 4585 465
//@node 3DE86F41-1 5090 360
//@node B2C49737-0 4885 465
//@node D0FB8BF1-1 5370 520
//@node 020DFAD7-0 5165 620
//@node C066C86C-1 5650 520
//@node B951ACC7-1 5930 360
//@node 94396ED1-0 6210 200
//@node D71BEC2D-0 6490 200
//@node D9BFA55C-0 6770 40
//@node ABC7DE44-0 7050 40
//@node 10CC08ED-0 6825 145
//@node 11509940-1 7330 200
//@node 8E638D27-0 7105 305
//@node 94D245C6-1 7610 200
//@node 9E025C12-0 7405 305
//@node 904ECB9F-0 7890 360
//@node B49384C7-0 7685 465
//@node 71C05F50-0 8170 360
//@node 91B42250-0 7965 465
//@node ACB6C05A-1 8450 360
//@node D67BEDC8-0 8245 460
//@node 6A2C6017-0 8730 360
//@node 73293E2A-0 8525 465
//@node 7ADCCF2B-0 9290 200
//@node 4C933CF7-0 40 40
//@node 58D770CE-0 330 40
//@node 703393A8-0 610 40
//@node 20FA7979-0 890 200
//@node 8AD460C4-0 665 305
//@node 5449FB44-0 1170 200
//@node C06CB624-0 945 305
//@node 8F0D152A-0 1450 200
//@node 98672392-0 1225 305
//@node 26E2B715-0 1020 405
//@node 4BEA51AF-0 1730 360
//@node 6A29B284-0 1525 460
//@node 115A2AF1-0 2290 360
//@node E61312B3-0 2085 460
//@node 4511F4F3-0 1880 460
//@node 22C9431C-0 1880 538
//@node 79DFD2A4-0 1880 616
//@node EDE62D34-0 2570 360
//@node B03482B1-0 2850 200
//@node F6A118D4-0 2625 305
//@node EDE62D34-1 3130 360
//@node AA59AA4A-0 3410 200
//@node 42389951-0 3185 305
//@node 84440AFA-0 3690 200
//@node 55F6DCF3-0 3485 305
//@node 63F3232C-0 3280 305
//@node 987A8FBB-0 3970 360
//@node CB94FDEB-0 3745 465
//@node 5D2864C1-0 3540 565
//@node 7604E0C2-0 4250 360
//@node 0FCA2AF5-0 4045 465
//@node 118ADCAD-0 4530 520
//@node 3C7F30EC-0 4810 200
//@node 6862FCCC-0 4605 305
//@node 22471302-0 5090 200
//@node B423C251-0 4885 305
//@node 6CA7D057-0 4680 305
//@node 1A63A890-0 40 40
//@node 9B6BF108-0 330 40
//@node 23EFA2F9-0 125 145
//@node FE60AF13-0 -80 145
//@node 14728033-0 -80 229
//@node 7D9676C1-0 610 200
//@node 270438F7-0 385 305
//@node E269E4E7-0 180 405
//@node D2F50398-0 -25 405
//@node 525DE517-0 890 40
//@node 8306FAC1-0 665 145
//@node F6E552EB-0 1170 40
//@node C1F7DECD-0 965 145
//@node C236F634-0 1450 200
//@node 3763BF0E-0 1245 305
//@node C011B64B-0 1040 305
//@node 2559E771-0 1730 360
//@node 5F53DAF1-0 1525 460
//@node 81CA107C-0 2010 200
//@node EE778F7F-0 1805 300
//@node 7E88ACD4-0 2290 200
//@node F82BBE28-0 2570 200
//@node 57719A1C-0 2365 305
//@node 78B2241C-0 2160 305
//@node 0C173EF7-0 2850 360
//@node 03794F25-0 2625 465
//@node 79B1E44D-0 3130 520
//@node F899BCF4-0 3410 360
//@node 0528FFA6-0 3185 465
//@node 79B1E44D-1 3690 520
//@node 7E88ACD4-1 3970 360
//@node C236F634-1 4250 200
//@node A5E9987F-0 4045 305
//@node 804053A2-0 3840 305
//@node 2C6A8ABA-0 4530 360
//@node 0C173EF7-1 4810 200
//@node FD15A092-0 4585 305
//@node 0DEE956D-0 5090 360
//@node 0270D1A5-0 5370 360
//@node 60E15413-0 5145 465
//@node 7E88ACD4-2 5650 520
//@node F528B7ED-0 5930 360
//@node 79B1E44D-2 6210 200
//@node F58391B0-0 6490 40
//@node 8B66DB2A-0 6285 145
//@node 2F561725-0 6770 200
//@node 69E90F3D-0 6565 300
//@node FED28439-0 6360 300
//@node 7E88ACD4-3 7050 200
//@node B08B7590-0 40 40
//@node 93D0CDB3-0 330 40
//@node D5D603C1-0 105 145
//@node 98452FCF-0 610 40
//@node 7BAC20F5-0 385 145
//@node 6C434D6E-0 180 245
//@node 540393E3-0 -25 245
//@node 941A22D3-0 890 40
//@node 87B49540-0 665 145
//@node 443A7022-0 460 245
//@node EBCC9A4B-0 255 245
//@node C594F666-0 1170 40
//@node 0CA48EFE-0 965 145
//@node 156DEBB2-0 760 145
//@node 36A744AD-0 1450 200
//@node C1F70783-0 1225 305
//@node 12C34FC8-0 1730 200
//@node A863E526-0 1525 300
//@node 190C1DA3-0 2010 200
//@node 9C7C234B-0 1570 305
//@node 1B8C1DFB-0 1800 305
//@node 117CD084-0 2290 360
//@node C44FB7DF-0 2065 465
//@node 300036F7-0 2570 520
//@node A3E9B50C-0 2850 360
//@node EB8BBBAB-0 3130 40
//@node B6E0ED16-0 2925 140
//@node 8BE270C2-0 2925 232
//@node 43CD7ABE-0 2925 324
//@node 84025FC5-0 3410 40
//@node A58D335C-0 2970 145
//@node 86E27AB5-0 2765 337
//@node 795FF1CC-0 3200 145
//@node 117CD084-1 3690 200
//@node 91B1BE4C-0 3465 305
//@node 9383C92D-0 3970 360
//@node A3E9B50C-1 4250 200
//@node AB20CFEE-0 4530 40
//@node 05283B76-0 4325 324
//@node 48B40B0C-0 40 40
//@node 5396D7B9-0 330 40
//@node AA901C46-0 105 145
//@node E32C17C9-0 610 40
//@node BCB48D77-0 385 145
//@node 2E62FE45-0 180 245
//@node 3B3F350A-0 -25 245
//@node 29D9C7B5-0 890 40
//@node 60CEEFA1-0 665 145
//@node 45B09958-0 460 245
//@node AC725963-0 255 245
//@node FD99CBAB-0 1170 40
//@node 8F0A4796-0 945 145
//@node 984479E4-0 1450 40
//@node F57643DF-0 1730 40
//@node 3586A8BC-0 1290 145
//@node 4E74FEEC-0 1520 145
//@node 31FDFDD4-0 2010 200
//@node EF58FA01-0 1785 305
//@node 70C40DF3-0 2290 360
//@node C338A6D4-0 2570 200
//@node 29848F5A-0 2850 40
//@node 98BDCC95-0 2645 140
//@node A81C7799-0 2645 232
//@node 7C2EE587-0 3130 40
//@node 33262351-0 2905 145
//@node CB6B6260-0 3410 40
//@node 731BEF9F-0 3205 145
//@node 9D271015-0 3690 200
//@node 08521C63-0 3485 305
//@node BD497AA1-0 3280 305
//@node CE703589-0 3970 200
//@node 41F0071C-0 3765 305
//@node 972041DA-0 3560 305
//@node 31FDFDD4-1 4250 360
//@node 48F3D9CE-0 4025 465
//@node 70C40DF3-1 4530 520
//@node C338A6D4-1 4810 360
//@node 810B5EDA-0 5370 200
//@node A4708029-0 5165 305
//@node E0AA701D-0 5650 200
//@node D0CDE33D-0 5445 305
//@node 0B38871B-0 5240 305
//@node 31FDFDD4-2 5930 360
//@node 07C5A543-0 5705 465
//@node 70C40DF3-2 6210 520
//@node C338A6D4-2 6490 360
//@node CFA88016-0 6770 40
//@node D78ECAD9-0 6565 324
//@node 7BF922BA-0 40 40
//@node C9D498AB-0 330 40
//@node 8B316AA2-0 105 145
//@node 81772F3A-0 610 40
//@node 689BFA29-0 890 40
//@node 6537DCCA-0 450 145
//@node F7E882DA-0 680 145
//@node C5A33BB2-0 1170 200
//@node 9C842774-0 945 305
//@node DDADD1D1-0 1450 360
//@node D326BDCE-0 1730 200
//@node 73DB9CE0-0 40 40
//@node D5A11BAD-0 330 40
//@node 9796B3D0-0 105 145
//@node 4AA7F3DB-0 610 40
//@node 7714660E-0 405 145
//@node 659200EA-0 200 145
//@node 2421C4D5-0 890 40
//@node 08621945-0 685 145
//@node B24E2A65-0 480 145
//@node C7423304-0 1170 200
//@node 70EF602D-0 945 305
//@node 09E45B47-0 1450 360
//@node 1E71865C-0 1730 200
//@node 21347391-0 40 40
//@node 4A183831-0 330 40
//@node 5ADA35CD-0 125 145
//@node 5FF3E13E-0 610 40
//@node F751E5A1-0 405 145
//@node 89EAC059-0 200 145
//@node F394CAE3-0 890 200
//@node 3888CA06-0 665 305
//@node D5C3B33E-0 1170 360
//@node 1C4625D7-0 1450 200
//@node 4A183831-1 1730 40
//@node 9E144336-0 1525 145
//@node 2FC7F4ED-0 40 40
//@node F49E4323-0 330 40
//@node 93F5327C-0 40 40
//@node EA08AB5C-0 330 40
//@node F46D7919-0 610 40
//@node 9469103D-0 40 40
//@node 7078C08E-0 330 40
//@node B0A428BD-0 105 145
//@node 70CEA603-0 -100 245
//@node 99F921CE-0 -305 245
//@node D3CF0F98-0 610 40
//@node DB9BDCCA-0 405 145
//@node 33577730-0 200 145
//@node B2066B42-0 890 200
//@node A747F71D-0 1170 40
//@node E98E6046-0 965 140
//@node A22B357B-0 1450 40
//@node 7B023635-0 1730 40
//@node 4BA27F2E-0 1525 145
//@node 390B8E35-0 2010 40
//@node 99CC4A37-0 1805 145
//@node 3C5B4BCE-0 1600 145
//@node 6F31AED4-0 1600 229
//@node CCC29244-0 2290 200
//@node 2D471A06-0 2570 200
//@node D4EABA83-0 2345 305
//@node BE2E7EAB-0 2850 360
//@node 51ACBA04-0 3130 200
//@node 588CFBAC-0 2925 305
//@node 5CC48B4D-0 2720 305
//@node 3B38F777-0 3410 360
//@node EA4F4F48-0 3205 465
//@node B31E5D3E-0 3970 360
//@node 72FAD67C-0 3765 465
//@node A747F71D-1 4250 200
//@node BD44B115-0 4045 300
//@node 00B0C989-0 4530 200
//@node B88186EA-0 4325 305
//@node 37CE6A46-0 4530 360
//@node 78647299-0 5090 200
//@node 2DAAF9C6-0 5370 200
//@node 0B61F2DA-0 5165 305
//@node A22B357B-1 5650 360
//@node 78647299-1 5930 360
//@node 2DAAF9C6-1 6210 360
//@node FE637793-0 6005 465
//@node BE2E7EAB-1 6490 520
//@node 8E266B1E-0 6770 200
//@node 603A096E-0 6565 305
//@node F7B16C62-0 6360 305
//@node 1821A511-0 6360 389
//@node E37BBFC0-0 6360 473
//@node 36F8C3A4-0 6360 557
//@node A747F71D-2 7050 360
//@node 6ADFA420-0 6845 460
//@node 00B0C989-1 7330 360
//@node 6B58B699-0 7125 465
//@node 37CE6A46-1 7330 520
//@node 78647299-2 7890 360
//@node FFA7BEA0-0 8170 360
//@node 4E1AEE76-0 7965 465
//@node C95F8EC8-0 8450 520
//@node B345DFD0-0 8730 360
//@node 191E3FB2-0 8505 465
//@node 37CE6A46-2 8730 520
//@node A2987B39-0 9290 360
//@node E91A4B9C-0 9065 465
//@node C4F9FC09-0 9570 360
//@node F6A6A4AB-0 9365 465
//@node 850B3CCB-0 9850 520
//@node 7CA514A1-0 9645 620
//@node 47731D67-0 10130 360
//@node 543B8DE5-0 9905 465
//@node 2717C8DD-0 10410 360
//@node E10C500A-0 10205 465
//@node 28029302-0 10000 465
//@node 2F66F958-0 10000 549
//@node 3B38F777-1 10690 520
//@node 46C319E1-0 10485 625
//@node E00DD066-0 10970 360
//@node 4F684E87-0 10745 465
//@node E5D55FD2-0 11250 360
//@node 41F81A71-0 11045 465
//@node 82F4E595-0 10840 465
//@node 5DCEDEA6-0 10840 549
//@node 27D56FE4-0 11530 520
//@node 44B34C9D-0 11325 625
//@node 191B3FCC-0 12090 520
//@node 265242E8-0 11885 625
//@node BE2E7EAB-2 12370 360
//@node CCC29244-1 12650 200
//@node D9766119-0 40 40
//@node 8435BB98-0 330 40
//@node 9856D120-0 610 200
//@node 24D0CD58-0 890 200
//@node FC974DF4-0 685 305
//@node 722CE1D0-0 1170 360
//@node B7E72658-0 1450 200
//@node EB996A70-0 1225 305
//@node E70FB633-0 1730 360
//@node 9439A4C2-0 2010 360
//@node 08B21CE1-0 2290 200
//@node 7B7AA79F-0 2085 305
//@node 3CF13222-0 2570 360
//@node 89EF38D3-0 2850 200
//@node 1DF01187-0 2625 305
//@node 731CE001-0 3130 200
//@node 23D2887B-0 2925 305
//@node 825D1DB3-0 3410 360
//@node EED49372-0 3205 460
//@node 9439A4C2-1 3690 360
//@node 3E0B45A4-0 3970 200
//@node AAEA0120-0 3530 305
//@node 47CBD6B0-0 3760 305
//@node DD8EE373-0 4250 360
//@node 3E0B45A4-1 4530 360
//@node 845AF22D-0 4090 465
//@node 0CDF09FD-0 4320 465
//@node 582B1B78-0 4810 520
//@node E70FB633-1 5090 200
//@node D6ABA0AE-0 40 40
//@node 3844BF44-0 330 40
//@node 407383E0-0 125 145
//@node 8CEC0A9B-0 610 40
//@node C165EBB4-0 405 145
//@node 8BFFAAB0-0 890 200
//@node 05496D3E-0 1170 200
//@node 84CBEA8C-0 965 305
//@node 7EF1AFAB-0 1450 200
//@node 5E5B95C9-0 1730 200
//@node BE850B52-0 1525 305
//@node E0AE1B47-0 2010 200
//@node 00A30133-0 1805 305
//@node 2BEE7367-0 1600 305
//@node 250B0812-0 2290 360
//@node 336D22B6-0 2065 465
//@node 2F5072C6-0 2570 360
//@node A3DFF125-0 2365 465
//@node F4EC1769-0 2850 520
//@node C73526BA-0 3130 520
//@node 34E3D2C5-0 2925 620
//@node 279EEF40-0 3410 520
//@node 367106DE-0 3205 625
//@node B3E48E7D-0 3690 520
//@node FD1A1ACE-0 3970 360
//@node F4EC1769-1 4250 200
//@node 30522AAC-0 4530 200
//@node BA50EDAD-0 4325 305
//@node 452DEA44-0 4810 200
//@node D5186C72-0 4605 305
//@node 3B3E6E32-0 4400 305
//@node 2A682E6E-0 5090 360
//@node CBEA3EE1-0 4885 465
//@node 20D3E22B-0 5650 200
//@node 6A1AD980-0 5165 392
//@node C7896F58-0 5650 200
//@node 559A233A-0 5445 305
//@node FC58817C-0 5930 200
//@node 5451414A-0 5705 305
//@node 97372642-0 6210 200
//@node 4C6B19DF-0 6005 305
//@node 379689E6-0 6490 200
//@node 780AF985-0 6285 305
//@node CD963040-0 6770 360
//@node 131B8034-0 6565 465
//@node 02D79DEB-0 6360 465
//@node 27FB807D-0 6360 549
//@node 279EEF40-1 7050 520
//@node E3D944BF-0 6845 625
//@node 734A8074-0 7610 520
//@node D624E237-0 7610 200
//@node 3809CE01-0 7405 305
//@node 8BFFAAB0-1 8170 200
//@node 66A9DC1B-0 8170 200
//@node BDCF5AA6-0 7965 305
//@node 05496D3E-1 8450 360
//@node 7EC92835-0 8245 465
//@node 7EF1AFAB-1 9010 360
//@node DE631B0E-0 9010 360
//@node 08FC19F0-0 8805 465
//@node E0AE1B47-1 9290 360
//@node 3CC17F90-0 9085 465
//@node C81E39E4-0 8880 465
//@node 2AC96F81-0 9570 520
//@node 5D02499F-0 9365 625
//@node BB8B09E9-0 10130 680
//@node 250B0812-1 10130 520
//@node 3885D0CD-0 9905 625
//@node 2F5072C6-1 10410 520
//@node EEB4A290-0 10205 625
//@node FD05E0FE-0 10690 680
//@node C368D230-0 10485 785
//@node F4EC1769-2 11250 680
//@node C73526BA-1 11530 680
//@node B148C56C-0 11045 780
//@node 279EEF40-2 11530 680
//@node C8591DD4-0 11325 785
//@node B3E48E7D-1 12090 680
//@node FD1A1ACE-1 12370 520
//@node F4EC1769-3 12650 360
//@node FD05E0FE-1 12650 200
//@node 8AE88047-0 12445 305
//@node 279EEF40-3 12930 40
//@node 7E2DB3CD-0 12725 145
//@node 734A8074-1 13490 40
//@node 4D2BCA06-0 40 40
//@node 4564A7BD-0 330 40
//@node 1C648A07-0 125 145
//@node 15B81F7D-0 -80 145
//@node BF42C930-0 -80 145
//@node C6674918-0 610 200
//@node F87F3090-0 405 305
//@node A1BCB61F-0 1170 200
//@node 898386F1-0 965 305
//@node 7B6FBDE0-0 1450 40
//@node EEEC198D-0 1730 40
//@node 2169DFCB-0 1525 145
//@node E8F3F5BC-0 2010 200
//@node 58AAA9E2-0 2290 40
//@node EEEC198D-1 2570 40
//@node 3923E452-0 2365 145
//@node E47B6B40-0 2850 200
//@node FCA8DF7C-0 2625 305
//@node C8A598F2-0 3130 200
//@node 0A5F2DD8-0 2925 305
//@node 0E2A1F8E-0 3410 360
//@node 5AB63BE8-0 3205 460
//@node 4B22E9A5-0 3690 360
//@node E8F3F5BC-1 3970 200
//@node 8FEAD0D9-0 4250 40
//@node 76BEE313-0 4045 145
//@node EFD404DA-0 3840 145
//@node 62EBF291-0 3840 229
//@node 5D8620E4-0 4530 200
//@node 8A9F9540-0 4325 305
//@node A8A8A351-0 4810 360
//@node 0E92BD5D-0 5090 200
//@node AEA1F50C-0 4865 305
//@node 4B22E9A5-1 5370 360
//@node 87701FFD-0 5650 200
//@node 1DB5C1EA-0 5445 305
//@node E7B10C9F-0 5930 360
//@node E47B6B40-1 6210 200
//@node DAB14E53-0 5985 305
//@node C8A598F2-1 6490 200
//@node FB447CCD-0 6285 305
//@node 0E2A1F8E-1 6770 360
//@node 0AA1DD71-0 6565 460
//@node 4B22E9A5-2 7050 360
//@node AFB7B6BC-0 7330 200
//@node 17B35ACE-0 7105 305
//@node 4B22E9A5-3 7610 360
//@node 67CDC876-0 7890 200
//@node C0453DBD-0 7665 305
//@node 0FCA6D90-0 8170 200
//@node 59963096-0 7965 305
//@node 20D628C4-0 7760 305
//@node 94476297-0 7760 389
//@node 26A59D32-0 7760 389
//@node C6674918-1 8450 360
//@node 56CD91A9-0 8245 465
//@node 0D0526EB-0 8730 200
//@node 10AC8491-0 8505 305
//@node F5769243-0 9010 200
//@node 54EC43A6-0 8805 305
//@node 56A5D4C4-0 8600 305
//@node 6FFAD3A3-0 8600 389
//@node 80489883-0 9290 360
//@node 55EF277F-0 9085 465
//@node ED645845-0 9850 360
//@node 1A6FD5A0-0 9645 465
//@node 58AAA9E2-1 10130 200
//@node 4B22E9A5-4 10410 40
//@node 9C6AEE7B-0 40 40
//@node D242877A-0 330 40
//@node D27D7A27-0 40 40
//@node 0D9EFC40-0 330 40
//@node 424AC619-0 105 145
//@node CF0361A4-0 -100 245
//@node FEDC3A95-0 -305 245
//@node C760C1D4-0 610 40
//@node 99C20DD0-0 385 145
//@node CBDFCC09-0 180 245
//@node 44D2CC70-0 -25 245
//@node C552667C-0 890 40
//@node F6CEC441-0 665 145
//@node A5EAAAC0-0 460 245
//@node 3994B4A3-0 255 245
//@node B1D00F77-0 1170 40
//@node C989AAF2-0 945 145
//@node 779984A7-0 1450 40
//@node 27E3D6E4-0 1245 145
//@node 58D81B3C-0 1730 40
//@node 072A96E9-0 1525 145
//@node 25974867-0 1320 145
//@node 8C09A630-0 2010 200
//@node BA7FB85D-0 1805 305
//@node 1201F15A-0 2290 360
//@node B766F6DB-0 2570 200
//@node F4CDE681-0 2850 200
//@node 9B6B7882-0 2645 305
//@node ACC324A0-0 3130 200
//@node AA548425-0 3410 200
//@node CA81E9C6-0 3205 305
//@node BBDA1FFC-0 3000 305
//@node DDAFA1B2-0 3690 360
//@node 15827321-0 3465 465
//@node 04853F56-0 3970 520
//@node C18F73E4-0 4250 520
//@node 88E4A12D-0 4025 625
//@node 31B3540D-0 4530 680
//@node ACC324A0-1 4810 520
//@node 8C09A630-1 5090 360
//@node 8F94722E-0 4885 465
//@node 1201F15A-1 5370 520
//@node 83DAE72E-0 5650 360
//@node DA31B4A9-0 5445 465
//@node C332C602-0 5930 520
//@node 0CF3FAD9-0 6210 360
//@node BFAD4FA9-0 5985 465
//@node 1057FF8B-0 6490 360
//@node 871F9863-0 6285 465
//@node A718EFF6-0 6080 465
//@node 4AEDBDF2-0 6080 549
//@node 34C54277-0 6770 520
//@node 8DFED264-0 7050 520
//@node 31B3540D-1 7330 360
//@node 02F9ECE0-0 7610 200
//@node 4BF0CDB1-0 7405 305
//@node 999BCCE7-0 7200 305
//@node 31B3540D-2 7890 360
//@node 1255CE88-0 8170 360
//@node 2443039F-0 8450 200
//@node E3682AEA-0 8010 305
//@node 440A5DFA-0 8240 305
//@node 31B3540D-3 8730 360
//@node 1255CE88-1 9010 360
//@node 8C09A630-2 9290 200
//@node DA62F947-0 9085 305
//@node 1201F15A-2 9570 360
//@node B5ABA35A-0 9850 200
//@node 3D8822D8-0 10130 200
//@node 4A780956-0 10410 200
//@node 84DF22EF-0 10205 300
//@node EF902B27-0 10690 200
//@node E9DEAB5B-0 10485 300
//@node B5ABA35A-1 10970 200
//@node 3D8822D8-1 11250 200
//@node A6B60D5C-0 11530 200
//@node 9D753A94-0 11325 305
//@node 3CFFBB42-0 11120 305
//@node 92A6DBCC-0 11810 200
//@node D46EB07D-0 11605 305
//@node C8A1B25C-0 11400 305
//@node DDAFA1B2-1 12090 360
//@node FB76FBAE-0 11865 465
//@node 1201F15A-3 12370 520
//@node 8C09A630-3 12650 360
//@node 0A7DF388-0 12445 465
//@node 831BE680-0 12930 520
//@node 584C6F3A-0 12725 625
//@node 1201F15A-4 13210 520
//@node 1968F91B-0 13490 360
//@node 7C06E4ED-0 13770 360
//@node 15E2D95E-0 13545 465
//@node 83DAE72E-1 14050 520
//@node D41316DA-0 13845 625
//@node C332C602-1 14330 680
//@node 31B3540D-4 14610 520
//@node D0582DAA-0 14890 360
//@node 56A63B5A-0 14685 465
//@node 0EB2CEBA-0 14480 465
//@node 831BE680-1 15170 520
//@node 74CB576B-0 14965 625
//@node 1201F15A-5 15450 520
//@node 3F26FFB4-0 15730 360
//@node 3336AB14-0 15525 465
//@node 1979A2DB-0 15320 465
//@node C79C58DB-0 16010 200
//@node 1398B3BA-0 15805 305
//@node 1201F15A-6 16290 360
//@node B5ABA35A-2 16570 200
//@node 9543FE98-0 16850 200
//@node 5BA0FBA7-0 16625 305
//@node 98512C90-0 17130 200
//@node FB832253-0 16905 305
//@node A2A46290-0 16700 405
//@node 35474D54-0 16495 405
//@node D960A51A-0 16495 483
//@node A92D0093-0 17410 200
//@node 4A30B186-0 17205 305
//@node E6B88976-0 17000 305
//@node 83DAE72E-2 17690 360
//@node 8EA0026F-0 17485 465
//@node C332C602-2 17970 520
//@node 63BF0D23-0 18250 360
//@node 98E5E8F4-0 18045 465
//@node 5D15E36F-0 17840 549
//@node 831BE680-2 18530 520
//@node 2F37EC2C-0 18325 625
//@node 1201F15A-7 18810 520
//@node 31B3540D-5 19090 360
//@node C79C58DB-1 19370 200
//@node D59DFB03-0 19165 305
//@node 1201F15A-8 19650 360
//@node BDB3BA77-0 19930 40
//@node 1A992CB5-0 20210 200
//@node B766F6DB-1 20490 40
//@node 34C54277-1 20770 40
//@node B5CC57C4-0 40 40
//@node 45C67E6F-0 330 40
//@node 560B3FB1-0 -110 145
//@node 27C3C67D-0 -315 337
//@node 399E85E1-0 120 145
//@node 81C1122A-0 610 200
//@node 0F0E85A3-0 405 300
//@node 6C09DEE0-0 200 534
//@node E747A15E-0 40 40
//@node 6DA4ED4C-0 330 40
//@node 8755DB85-0 125 145
//@node C8BC4FC5-0 610 40
//@node 6B7499C6-0 890 40
//@node 852C266F-0 685 145
//@node B854D773-0 480 145
//@node EE20D0B5-0 1170 200
//@node DF17FD60-0 965 305
//@node D036B8BF-0 1450 360
//@node B09394CC-0 1730 200
//@node B8FD07AF-0 1505 305
//@node 4B1BA806-0 2010 200
//@node F6F89F3F-0 1805 305
//@node B672A174-0 1600 305
//@node 343B43CA-0 1600 473
//@node DE509B40-0 1600 557
//@node 1BD2E044-0 2290 360
//@node 5E8642AD-0 2570 360
//@node C6213A42-0 2850 200
//@node 74BF30C7-0 3130 40
//@node 7C6A7036-0 2925 145
//@node 1BD2E044-1 3410 200
//@node 5E8642AD-1 3690 200
//@node 8E630104-0 3970 40
//@node FF16EF2C-0 3745 145
//@node 75823500-0 4250 40
//@node 035A9F9D-0 4045 145
//@node 649B599A-0 3840 145
//@node 1655C941-0 4530 200
//@node 6102DBE3-0 4325 300
//@node B7E82281-0 4120 378
//@node 9B2BCC0B-0 4810 40
//@node C0BAC463-0 4605 140
//@node E6B57F7D-0 5090 40
//@node 881A5427-0 4885 232
//@node BA6C061F-0 5370 40
//@node 1D43E86A-0 5165 232
//@node BB120430-0 5165 324
//@node C2002FB9-0 4960 324
//@node 49DFD5EC-0 5650 40
//@node 74C8EAFD-0 5445 232
//@node 77EDBA9E-0 5930 40
//@node CAB4AE0F-0 5725 232
//@node 4F9EC223-0 6210 40
//@node 3F67828D-0 5985 145
//@node 01C7D313-0 5780 245
//@node B18C031E-0 5575 245
//@node 8B28EDE7-0 6490 40
//@node 1D5D7F1A-0 6265 145
//@node 6C295A88-0 6060 245
//@node CECEEF51-0 5855 245
//@node 10A15093-0 6770 40
//@node 0C311A29-0 6545 145
//@node 7663B021-0 6340 245
//@node 178BB912-0 6135 245
//@node E5E65B0D-0 7050 40
//@node DCE58E5C-0 6825 145
//@node 504DBC01-0 7330 40
//@node A428AC14-0 7125 145
//@node 99954A19-0 7610 200
//@node BA45234A-0 7890 40
//@node 9490F068-0 7665 145
//@node 25E2DC66-0 8170 40
//@node 1CA1809E-0 8450 40
//@node C36D23EB-0 8245 145
//@node 55B1BB06-0 8730 40
//@node 05E0E02A-0 8525 145
//@node D654D9A2-0 9010 40
//@node 691D6197-0 8785 145
//@node CB3661EA-0 9290 40
//@node 537FA490-0 9085 145
//@node 73733375-0 9570 200
//@node 0B1C66AA-0 9850 200
//@node C1392CBD-0 10130 200
//@node B251B831-0 9925 300
//@node 7A4AC651-0 10410 200
//@node 3D053323-0 10185 305
//@node 504DBC01-1 10690 200
//@node 63D328DB-0 10485 305
//@node FA11667B-0 10970 360
//@node EF9809A5-0 10765 465
//@node 90D4D9D9-0 11250 360
//@node FC279C09-0 11045 465
//@node 61236798-0 10840 465
//@node BCFEA845-0 11810 360
//@node 1D470D0D-0 11585 465
//@node 8399D98E-0 11380 565
//@node 76FA1432-0 11175 565
//@node C7D9FCAC-0 11175 643
//@node BBBC3A59-0 12090 200
//@node 5126B769-0 11885 305
//@node 906A8388-0 11680 305
//@node 2F3A0ABC-0 11680 389
//@node AD55B510-0 11680 473
//@node EE20D0B5-1 12370 360
//@node 685EA437-0 12165 465
//@node D036B8BF-1 12650 520
//@node 8B5DA6D7-0 12930 360
//@node 45B00547-0 12705 465
//@node 6184E257-0 13210 520
//@node F5592882-0 13005 625
//@node B51BD741-0 13210 520
//@node FF33BE40-0 13770 360
//@node 38C25D25-0 13330 465
//@node 44DC0895-0 13560 465
//@node 6184E257-1 14050 520
//@node 4AEDB233-0 13845 625
//@node B51BD741-1 14050 520
//@node C6213A42-1 14610 360
//@node 7A4AC651-1 14890 360
//@node 986D09F8-0 14665 465
//@node EA978D7E-0 15170 200
//@node 91648C16-0 14965 305
//@node B51BD741-2 15170 360
//@node 51DA0584-0 15730 200
//@node A5A69FA0-0 16010 200
//@node 3D093A83-0 16290 200
//@node F3D42F14-0 15850 305
//@node 92A07264-0 16080 305
//@node EE20D0B5-2 16570 360
//@node 7AC4C4A2-0 16365 465
//@node D036B8BF-2 16850 520
//@node 8B5DA6D7-1 17130 360
//@node 872AA3E4-0 16905 465
//@node 6184E257-2 17410 520
//@node F17656F4-0 17205 625
//@node B51BD741-3 17410 520
//@node 796FE65D-0 17970 360
//@node EB453CE4-0 17530 465
//@node 54210734-0 17760 465
//@node 6184E257-3 18250 520
//@node C90BFDFD-0 18045 625
//@node B51BD741-4 18250 520
//@node C6213A42-2 18810 360
//@node EA978D7E-1 19090 200
//@node 30E5D93F-0 18885 305
//@node B51BD741-5 19090 360
//@node 26AD0F02-0 19650 200
//@node 6CB6882E-0 19445 305
//@node 73733375-1 19930 200
//@node 9B768151-0 20210 200
//@node 8E4D5F31-0 20005 305
//@node 3B65FEC5-0 19800 305
//@node 4BF843A1-0 20490 200
//@node 5A9FA57F-0 20285 305
//@node EC62C558-0 20080 305
//@node 6F69021D-0 20080 389
//@node 3B40EEA5-0 20770 360
//@node A9F64236-0 20545 465
//@node B51BD741-6 20770 520
//@node 65D5435C-0 21330 360
//@node 76F185C2-0 21125 460
//@node A291BC77-0 20920 460
//@node 3D093A83-1 21610 360
//@node 1B44C171-0 21170 465
//@node 97DA0701-0 21400 465
//@node 3B40EEA5-1 21890 520
//@node CC7CB8E9-0 21665 625
//@node B51BD741-7 21890 680
//@node EE20D0B5-3 22450 520
//@node 83214A51-0 22245 625
//@node D036B8BF-3 22730 680
//@node 8B5DA6D7-2 23010 520
//@node 162AAC41-0 22785 625
//@node 6184E257-4 23290 680
//@node 648308B6-0 23085 785
//@node B51BD741-8 23290 680
//@node 796FE65D-1 23850 520
//@node DA5558DF-0 23410 625
//@node 01141D6F-0 23640 625
//@node 6184E257-5 24130 680
//@node B3A3B4E7-0 23925 785
//@node B51BD741-9 24130 680
//@node C6213A42-3 24690 520
//@node 49FBFF9F-0 24970 360
//@node DD70A2B8-0 24765 465
//@node 8B5DA6D7-3 25250 360
//@node 4F8E6DD6-0 25025 465
//@node 6184E257-6 25530 520
//@node A55D6288-0 25325 625
//@node B51BD741-10 25530 520
//@node 796FE65D-2 26090 360
//@node 36D46342-0 25650 465
//@node 5BBBD212-0 25880 465
//@node 6184E257-7 26370 520
//@node FF56C421-0 26165 625
//@node B51BD741-11 26370 520
//@node F0BE9C23-0 26930 360
//@node 3F628508-0 26725 465
//@node B48C7CB7-0 26520 465
//@node 26AD0F02-1 27210 200
//@node 7646D905-0 27005 305
//@node EA978D7E-2 27490 200
//@node 9D6085E4-0 27285 305
//@node B51BD741-12 27490 360
//@node 51DA0584-1 28050 200
//@node 783DDB9F-0 28330 200
//@node 90B4920F-0 28610 200
//@node F8D0FAE1-0 28170 305
//@node 07D7A071-0 28400 305
//@node EE20D0B5-4 28890 360
//@node 402E83D4-0 28685 465
//@node D036B8BF-4 29170 520
//@node 8B5DA6D7-4 29450 360
//@node 474A9983-0 29225 465
//@node 6184E257-8 29730 520
//@node ECF631BA-0 29525 625
//@node B51BD741-13 29730 520
//@node 796FE65D-3 30290 360
//@node D9D5F5C5-0 29850 465
//@node DF7FA5D5-0 30080 465
//@node 6184E257-9 30570 520
//@node 097519EB-0 30365 625
//@node B51BD741-14 30570 520
//@node C6213A42-4 31130 360
//@node EA978D7E-3 31410 200
//@node 417091FD-0 31205 305
//@node B51BD741-15 31410 360
//@node 5B6D4CF3-0 31970 40
//@node AC895EE1-0 31765 145
//@node 18C973CD-0 31560 145
//@node DFA44566-0 32250 200
//@node 51DA0584-2 32530 40
//@node 4CB43E2F-0 32810 40
//@node 1BD2E044-2 33090 40
//@node 16B3C3FE-0 33370 40
//@node 4A8E7C92-0 40 40
//@node 8D74FDCC-0 330 40
//@node BFC90E72-0 125 145
//@node 0EF04970-0 610 200
//@node 33790C23-0 1170 200
//@node 5D4E2BFE-0 40 40
//@node 6BA3628A-0 330 40
//@node D6A3323C-0 125 145
//@node 261A9438-0 -80 145
//@node 633884E7-0 610 200
//@node 61E550A3-0 40 40
//@node 11F15C37-0 330 40
//@node BCF7575D-0 40 40
//@node 13532D9A-0 330 40
//@node 6AFBA22C-0 125 145
//@node 518BE6A2-0 610 40
//@node 942C97CE-0 405 145
//@node 048338AE-0 890 40
//@node 2CA5E0F3-0 665 145
//@node CEFCAE5D-0 1170 40
//@node F1D9BF2B-0 965 145
//@node A8B94C9D-0 1450 200
//@node 856652DF-0 1225 305
//@node 5EDB2927-0 1020 405
//@node 37603D41-0 1730 200
//@node C50E216E-0 1525 305
//@node 007D6D73-0 1320 305
//@node 41A1DFBB-0 2010 360
//@node 6D2C247F-0 2570 360
//@node 3C654D95-0 2365 465
//@node D749EE3E-0 2850 360
//@node E5780695-0 2645 460
//@node D7B0A64B-0 3130 360
//@node 5CD80698-0 2925 465
//@node 1D9FACF6-0 2720 465
//@node 3893C630-0 3410 520
//@node 52E9E677-0 3185 625
//@node E30FF8EC-0 3410 680
//@node 9F808713-0 3970 520
//@node 58805264-0 3745 625
//@node CBC10048-0 4250 520
//@node 1C3C4909-0 4045 625
//@node B1F3B59D-0 4530 680
//@node 30C82729-0 4305 785
//@node 08837D6C-0 4100 885
//@node 5914552A-0 4810 840
//@node EEC79312-0 4605 940
//@node E30FF8EC-1 4810 840
//@node 10D4F755-0 5370 520
//@node 8807FEC0-0 5145 625
//@node DC78774D-0 5650 680
//@node 516F230A-0 5445 785
//@node 58014726-0 5240 785
//@node 4AD0498C-0 5240 869
//@node E30FF8EC-2 5650 840
//@node 9F9BD095-0 6210 520
//@node 3752C43E-0 5985 625
//@node E30FF8EC-3 6210 680
//@node 41A1DFBB-1 6770 520
//@node 6F0CA7B2-0 7050 520
//@node 403D5892-0 6845 625
//@node FC1660FA-0 6640 625
//@node 48CDDD53-0 7330 680
//@node 4A106026-0 7125 785
//@node 1F0F16B3-0 7610 520
//@node 340640C0-0 7385 625
//@node 98149D69-0 7890 520
//@node 1EE7DBEF-0 7685 625
//@node 73225D1B-0 8170 680
//@node CD874B35-0 7965 780
//@node B38EA5AE-0 8450 680
//@node 518686D1-0 8730 360
//@node DB603422-0 8505 465
//@node F7966247-0 9010 360
//@node D7B0A64B-1 9290 360
//@node F0F696E7-0 9085 465
//@node 756289FF-0 8880 465
//@node 10D4F755-1 9570 520
//@node AA45D4E7-0 9345 625
//@node 35022699-0 9850 680
//@node 31EBFB0A-0 9625 785
//@node E30FF8EC-4 9850 840
//@node DC78774D-1 10410 680
//@node 8A7C26DB-0 10205 785
//@node 1820A039-0 10000 785
//@node 7EDEF953-0 10000 869
//@node E30FF8EC-5 10410 840
//@node 41A1DFBB-2 10970 520
//@node 6D2C247F-1 11530 200
//@node 593A5BEC-0 11325 305
//@node 1BCE6460-0 11810 200
//@node FD0C49E7-0 12090 200
//@node B4FA5D0F-0 11885 305
//@node 4FD9CF55-0 12370 360
//@node 1070CCD9-0 12650 200
//@node 2BF5ACF5-0 12445 305
//@node 4BF43455-0 12240 305
//@node D7B0A64B-2 12930 360
//@node 2C6BDF5E-0 12725 465
//@node C7FD6B60-0 12520 465
//@node 3893C630-1 13210 520
//@node 1F668AEC-0 12985 625
//@node E30FF8EC-6 12930 680
//@node 6F0CA7B2-1 13770 520
//@node 25A7C5FF-0 13565 625
//@node 1776F467-0 13360 625
//@node 48CDDD53-1 14050 680
//@node 4DC7C3E3-0 13845 785
//@node 1F0F16B3-1 14330 520
//@node 78D69327-0 14105 625
//@node 98149D69-1 14610 520
//@node 0B6E5A1A-0 14405 625
//@node 73225D1B-1 14890 680
//@node 09CA4F9C-0 14685 780
//@node B38EA5AE-1 15170 680
//@node 9F808713-1 15450 520
//@node 0CBEFFF1-0 15225 625
//@node CBC10048-1 15730 520
//@node 44E16EB6-0 15525 625
//@node B1F3B59D-1 16010 680
//@node 6FAF3E10-0 15785 785
//@node FBBE4394-0 15580 885
//@node 5914552A-1 16290 840
//@node 9D2681D1-0 16085 940
//@node E30FF8EC-7 16010 840
//@node 10D4F755-2 16850 520
//@node C1370B62-0 16625 625
//@node DC78774D-2 17130 680
//@node FC0C5D18-0 16925 785
//@node FC8B6B30-0 16720 785
//@node 3047307E-0 16720 869
//@node E30FF8EC-8 16850 840
//@node 9F9BD095-1 17690 520
//@node ABD3D6ED-0 17465 625
//@node E30FF8EC-9 17410 680
//@node 41A1DFBB-3 18250 520
//@node 537AD9E9-0 18530 360
//@node B6C0AC0B-0 18090 465
//@node 961412DB-0 18320 465
//@node E424E88D-0 18810 520
//@node F45AB5B9-0 18605 625
//@node F2ABEED8-0 19090 680
//@node D6204F65-0 19370 680
//@node F0DABD15-0 19165 785
//@node 45EE5148-0 19650 680
//@node 333AE7F0-0 19425 785
//@node A1E21884-0 19930 680
//@node 199E5655-0 19725 780
//@node C4128158-0 19520 780
//@node 41A1DFBB-4 20210 40
//@node 9D58E6C3-0 20490 40
//@node 326B9E53-0 20265 145
//@node 4FD9CF55-1 20770 200
//@node 07CABF3C-0 21050 40
//@node 9D631711-0 20825 145
//@node B38EA5AE-2 21330 200
//@node 402BAFCE-0 21890 200
//@node 48AB0FF0-0 22170 200
//@node A82B2199-0 40 40
//@node 6EB489B1-0 330 40
//@node 7D03057F-0 125 145
//@node 2308B901-0 610 40
//@node 654944FA-0 405 145
//@node AD4D7C30-0 890 40
//@node 175C1FDA-0 1170 40
//@node 30F72BE3-0 965 145
//@node DA1F908F-0 760 145
//@node D36C0284-0 1450 200
//@node 2F725FA8-0 1225 305
//@node 4015770E-0 1730 360
//@node 07F74A6C-0 2010 200
//@node 3F37D9C1-0 1785 305
//@node 4015770E-1 2290 360
//@node 3569C177-0 2570 200
//@node 3755451B-0 2365 305
//@node F2BE07D5-0 2160 305
//@node ECE35221-0 2850 360
//@node 9CC73758-0 2625 465
//@node 4DCCF8B5-0 3130 520
//@node A784480B-0 2905 625
//@node 4015770E-2 3410 680
//@node CC09CAE9-0 3690 520
//@node FA9F67A7-0 3485 625
//@node E1586AC3-0 3280 625
//@node 28CDD075-0 3280 709
//@node 4015770E-3 3970 680
//@node 7C8806B7-0 4250 200
//@node 7C8806B7-1 4530 40
//@node EC86179A-0 4810 40
//@node 5E89F525-0 40 40
//@node 05792CB0-0 330 40
//@node 7D13F535-0 125 145
//@node BCFD78F9-0 610 200
//@node 88A78836-0 890 40
//@node C2A6F022-0 685 145
//@node 69694F34-0 1170 40
//@node 60C2F481-0 965 140
//@node 76B20F8D-0 1450 40
//@node 5AA69397-0 1245 145
//@node 3FD9E6C4-0 1730 40
//@node FE845DA6-0 40 40
//@node 8F9346F1-0 330 40
//@node 7E2E1017-0 105 145
//@node 1B122A25-0 610 40
//@node FD845C13-0 40 40
//@node 6657A5F5-0 330 40
//@node D574E064-0 105 145
//@node 3E713B6E-0 610 40
//@node FC845A80-0 40 40
//@node 703E53D6-0 330 40
//@node 4BBAEA79-0 105 145
//@node C174ECAB-0 610 40
//@doomscript-blueprint end
