/***********************************************************************

ai_monster_demon_imp.script

monster_demon_imp
monster_demon_imp_crawler

***********************************************************************/

#define IMP_RUNDISTANCE		192
#define IMP_WALKTURN		65
#define IMP_ATTACK_RATE		1
#define IMP_LEAP_RATE		7
#define IMP_LEAP_SPEED		650
#define IMP_LEAP_MAXHEIGHT	48
#define IMP_DODGE_RATE		8
#define IMP_LEAP_RANGE_MIN	200
#define IMP_LEAP_RANGE_MAX	480
#define IMP_NOFOVTIME		4

object monster_demon_imp : monster_base {
	float		nextDodge;
	float		nextAttack;
	float		nextLeap;
	float		nextNoFOVAttack;
	vector		jumpVelocity;
	entity		combat_node;

	string		range_attack_anim;
	
	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_leap();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();
	void		path_jump();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	void		Torso_TurretAttackIdle();
	void		Torso_LeapAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_imp::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	eachFrame {
		if ( AI_PAIN ) { animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 ); }
	}
}

void monster_demon_imp::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 6 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 6 );
}

void monster_demon_imp::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_imp::Torso_RangeAttack() {
	disablePain();

	playAnim( ANIMCHANNEL_TORSO, range_attack_anim );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}

	allowMovement( true );
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_imp::Torso_TurretAttack() {
	allowMovement( false );
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "turret_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		waitFrame();
	}

	finishAction( "turret_attack" );
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_TurretAttackIdle", 0 );
}

void monster_demon_imp::Torso_TurretAttackIdle() {
	faceEnemy();
	idleAnim( ANIMCHANNEL_TORSO, "turret_idle" );
	while( 1 ) {
		waitFrame();
	}
}

void monster_demon_imp::Torso_LeapAttack() {
	overrideAnim( ANIMCHANNEL_LEGS );
	disablePain();
	playAnim( ANIMCHANNEL_TORSO, "jump_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		waitFrame();
	}
	
	setBlendFrames( ANIMCHANNEL_TORSO, 2 );
	attackBegin( "melee_impLeapAttack" );
	setLinearVelocity( jumpVelocity );
	
	playCycle( ANIMCHANNEL_TORSO, "jump_loop" );
	do {
		waitFrame();
	} while( !AI_ONGROUND );
	
	attackEnd();
	playAnim( ANIMCHANNEL_TORSO, "jump_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "leap_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_imp::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_demon_imp::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_imp::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_imp::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void monster_demon_imp::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_imp::init
=====================
*/
void monster_demon_imp::init() {
	run_distance	= IMP_RUNDISTANCE;
	walk_turn		= IMP_WALKTURN;
	
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_imp::state_Begin
=====================
*/
void monster_demon_imp::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );	
	monster_begin();
	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_demon_imp::state_Idle
=====================
*/
void monster_demon_imp::state_Idle() {
	wait_for_enemy();

	nextLeap		= RandomTime( IMP_LEAP_RATE );
	nextAttack		= 0;
	nextDodge		= RandomTime( IMP_DODGE_RATE );
	nextNoFOVAttack = 0;
	
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_imp::do_attack
=====================
*/
void monster_demon_imp::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + IMP_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_LEAP ) {
		combat_leap();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_demon_imp::check_attacks
=====================
*/
float monster_demon_imp::check_attacks() {
	float range;
	float currentTime;
	float canMelee;
	float attack_flags;
	float checkLeap;
	vector vel;
	float t;
	string anim;
	vector jumpTarget;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}

	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		range = enemyRange();
		if ( ( range >= IMP_LEAP_RANGE_MIN ) && ( range < IMP_LEAP_RANGE_MAX ) && ( currentTime >= nextLeap ) ) {
			if ( canHitEnemy() ) {
				t = animLength( ANIMCHANNEL_TORSO, "jump_start" );
				jumpTarget = predictEnemyPos( t );
				jumpVelocity = getJumpVelocity( jumpTarget, IMP_LEAP_SPEED, IMP_LEAP_MAXHEIGHT );
				if ( jumpVelocity != '0 0 0' ) {
					attack_flags |= ATTACK_LEAP;
				} else {
					// check if we can leap again in 2 seconds
					nextLeap = DelayTime( 2 );
				}
			}
		}
		
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			range_attack_anim = chooseAnim( ANIMCHANNEL_LEGS, "turret_attack" );
			if ( canHitEnemyFromAnim( range_attack_anim ) ) {
				attack_flags |= ATTACK_MISSILE;
			}

			anim = chooseAnim( ANIMCHANNEL_LEGS, "range_attack" );
			if ( testAnimMoveTowardEnemy( anim ) ) {
				if ( canHitEnemyFromAnim( anim ) ) {
					range_attack_anim = anim;
					attack_flags |= ATTACK_MISSILE;
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_imp::combat_range
=====================
*/
void monster_demon_imp::combat_range() {
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
	waitAction( "range_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( IMP_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + IMP_NOFOVTIME;
}

/*
=====================
monster_demon_imp::combat_leap
=====================
*/
void monster_demon_imp::combat_leap() {
	stopMove();
	turnToPos( getOrigin() + jumpVelocity );
	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );
	nextLeap = DelayTime( IMP_LEAP_RATE );
}

/*
=====================
monster_demon_imp::combat_melee
=====================
*/
void monster_demon_imp::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
	stopMove();
}

/*
=====================
monster_demon_imp::combat_dodge_left
=====================
*/
void monster_demon_imp::combat_dodge_left() {
	faceEnemy();
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( IMP_DODGE_RATE );
}

/*
=====================
monster_demon_imp::combat_dodge_right
=====================
*/
void monster_demon_imp::combat_dodge_right() {
	faceEnemy();
	stopMove();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( IMP_DODGE_RATE );
}

/*
=====================
monster_demon_imp::path_jump
=====================
*/
void monster_demon_imp::path_jump() {
	entity target;
	vector dir;
	vector jumpTarget;

	// walk to the path entity first
	path_corner();

	if ( checkForEnemy( true ) ) {
		return;
	}

	target = current_path.randomPath();
	if ( !target ) {
		sys.error( "missing target for '" + current_path.getName() + "'" );
	}
	jumpTarget = target.getOrigin();
	if ( !current_path.getKey( "up" ) ) {
		jumpVelocity = getJumpVelocity( jumpTarget, IMP_LEAP_SPEED, 1024 );
		if ( jumpVelocity == '0 0 0' ) {
			sys.error( "Monster '" + getName() + "' couldn't make jump from '" + current_path.getName() + "' to '" + target.getName() + "'" );
		}
	} else {
		float forward = current_path.getFloatKey( "forward" );
		if ( forward <= 0 ) {
			sys.error( "Invalid forward velocity on path_jump entity '" + current_path.getName() + "'\n" );
		}
		dir = jumpTarget - getOrigin();
		dir_z = 0;
		dir = sys.vecNormalize( dir );
		dir = dir * forward;
		dir_z = current_path.getFloatKey( "up" );
		jumpVelocity = dir;
	}
	
	stopMove();
	turnToPos( jumpTarget );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}

	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );

	stopMove();
}

//@doomscript-blueprint begin 6
//@source 9C3939AA
//@catalog 0C260740
//@node C6BDDF96-0 40 40
//@node 48C60FB1-0 330 40
//@node 071A830D-0 610 40
//@node B706BC9C-0 890 200
//@node 042E56C7-0 685 305
//@node 83280A6B-0 480 305
//@node 316D7414-0 40 40
//@node D1E7A467-0 330 40
//@node 5B20A1E6-0 105 145
//@node 34E84B6B-0 610 40
//@node 0451A5C9-0 405 232
//@node 84170EC7-0 890 40
//@node 8E0CDF87-0 685 145
//@node A22B6ECF-0 1170 40
//@node F46BB3FA-0 730 145
//@node 6EAA85AA-0 960 145
//@node 8D9398D5-0 1450 200
//@node 1F9634B1-0 1245 305
//@node 9951117E-0 1730 360
//@node BC887BC1-0 1505 465
//@node 24E188CF-0 2010 360
//@node 44B21FB7-0 1805 465
//@node CF8B94F6-0 1600 465
//@node AEE72AFD-0 1600 549
//@node E705B3E3-0 2290 520
//@node 1530080C-0 2570 200
//@node E96C4169-0 2850 40
//@node 6D6A5B54-0 3130 40
//@node 232CD334-0 40 40
//@node E9A1181C-0 330 40
//@node C22F68B5-0 610 40
//@node EADF0517-0 170 145
//@node 66E9EA87-0 400 145
//@node 305EE46C-0 890 200
//@node ABB03624-0 1170 40
//@node FBFE87D2-0 1450 40
//@node B18AB909-0 40 40
//@node 28F6D6C5-0 330 40
//@node 19DC4B40-0 610 40
//@node C1E68CD3-0 405 232
//@node 1447F28E-0 890 40
//@node 319483C9-0 450 145
//@node 53700DB9-0 680 145
//@node F0C12668-0 1170 200
//@node 8263448B-0 1450 200
//@node D40E3785-0 1730 40
//@node FD4434B6-0 2010 40
//@node 493417E1-0 2290 40
//@node 79C6B3A2-0 40 40
//@node 83AEE29D-0 330 40
//@node C9F77504-0 610 40
//@node 11E64B9D-0 890 40
//@node A4E13F3E-0 1170 40
//@node E8BE973D-0 1450 40
//@node BE0B699C-0 1010 145
//@node 4DCF1DAC-0 1240 145
//@node 4885555A-0 1730 200
//@node 0B73C662-0 2010 40
//@node 694283AC-0 2290 40
//@node 9D16EAF2-0 2570 40
//@node 19C45574-0 40 40
//@node 3AA4F1C3-0 330 40
//@node 71CEB376-0 610 40
//@node D48BCE87-0 890 40
//@node 8E2137FC-0 685 145
//@node F4CF27D0-0 1170 200
//@node EC534E9A-0 40 40
//@node B0B9415F-0 330 40
//@node ED5C2074-0 610 40
//@node 1DC54348-0 890 40
//@node DD7F6F15-0 1170 40
//@node 60770C4C-0 730 145
//@node AA59F65C-0 960 145
//@node 3617C36A-0 1450 200
//@node DD555355-0 1730 40
//@node 93E64B5A-0 2010 40
//@node F6E17223-0 2290 40
//@node 0F5A94FF-0 2085 140
//@node 44D551D7-0 2570 40
//@node 8FCFD1BF-0 2850 40
//@node 3617C36A-1 3130 200
//@node C081E049-0 3410 200
//@node 55415753-0 3205 305
//@node 3DAB63D5-0 3000 305
//@node 40BD15C7-0 3690 40
//@node D8CD443D-0 3970 40
//@node 00A32003-0 4250 40
//@node 50425B80-0 3810 145
//@node 59C5D170-0 4040 145
//@node 3617C36A-2 4530 200
//@node F9E1984E-0 4810 40
//@node A8574E8C-0 5090 40
//@node 6A72DFB0-0 40 40
//@node A13F8629-0 330 40
//@node 39F3D18D-0 610 40
//@node FF95DC9E-0 890 200
//@node 20687214-0 685 305
//@node 66C034A9-0 480 305
//@node B5BB8B26-0 480 389
//@node 3CCDBF83-0 1170 200
//@node F609BC40-0 965 305
//@node DF025D3A-0 760 305
//@node A64F7E2F-0 40 40
//@node 98062EF6-0 330 40
//@node BA81B976-0 610 40
//@node 9539B587-0 890 200
//@node 858AE482-0 685 305
//@node EE70000F-0 480 305
//@node C07DF708-0 480 389
//@node 0017874A-0 1170 200
//@node 19AAC059-0 965 305
//@node FE3CC4D3-0 760 305
//@node B53251DF-0 40 40
//@node 97D82244-0 330 40
//@node 1F114506-0 125 232
//@node D90C0365-0 -80 232
//@node 2171FD24-0 610 40
//@node 58EB788E-0 890 200
//@node E19913F9-0 685 305
//@node CB20EDC9-0 480 305
//@node DFBBC446-0 480 389
//@node F33344F6-0 1170 200
//@node C0D798CA-0 965 305
//@node 65E470A8-0 760 305
//@node D09A68BC-0 40 40
//@node 4A1531EC-0 330 40
//@node 242C59FB-0 610 40
//@node 560F268E-0 170 145
//@node EFE8F67E-0 400 145
//@node 0C2EF064-0 890 200
//@node D31D380A-0 1170 40
//@node 5063B9DC-0 1450 40
//@node 06600789-0 40 40
//@node 8EE0E0EA-0 330 40
//@node 8C57EF5A-0 610 40
//@node 101B8F7C-0 170 145
//@node 6FED4A0C-0 400 145
//@node 1402B087-0 890 200
//@node A31F9CB7-0 1170 40
//@node D3B91BC7-0 1450 40
//@node 7AA7F422-0 40 40
//@node 290E7363-0 330 40
//@node 13DDF25F-0 125 145
//@node 1E225061-0 610 40
//@node 01AEB6AA-0 405 145
//@node 5F3DAFC2-0 890 40
//@node 2963B6E3-0 40 40
//@node 537C78E3-0 330 40
//@node 3AF0361D-0 610 40
//@node ED28CEBB-0 890 40
//@node 1F145C79-0 1170 40
//@node 882BF902-0 1450 40
//@node BE07A0E8-0 40 40
//@node F0CBF290-0 330 40
//@node 2954F92D-0 610 40
//@node 00CD82B1-0 385 145
//@node 5862C7A4-0 890 40
//@node ACD52896-0 685 145
//@node 74B85921-0 1170 40
//@node 8F509252-0 945 145
//@node 0FB8F4EA-0 1450 40
//@node C7D63680-0 1245 145
//@node 9A46DA7B-0 1730 40
//@node BE0DF1DE-0 40 40
//@node 150C7E54-0 330 40
//@node 1E755F33-0 125 145
//@node 75E302FC-0 610 40
//@node DA2D1B4C-0 405 145
//@node 44D5080C-0 890 200
//@node F05F8864-0 1170 200
//@node CBA5F8AF-0 965 305
//@node 152C5F7F-0 1450 200
//@node 86DF57F7-0 1730 200
//@node 6FB1B318-0 1525 305
//@node 41C61D70-0 2010 200
//@node BA0344D3-0 1805 300
//@node 1D3999B6-0 2290 200
//@node 49EB3941-0 2085 305
//@node CAA4226D-0 2570 200
//@node 68A63122-0 2850 200
//@node DBE72637-0 2645 305
//@node 6DE971A5-0 3130 200
//@node 18CFA7A6-0 3410 200
//@node 8B8D7851-0 3205 305
//@node 85A35E66-0 3690 200
//@node 1B60476A-0 40 40
//@node 4D9110D3-0 330 40
//@node 7DF95DE2-0 125 145
//@node 5ABA2428-0 610 40
//@node BEDA2165-0 385 145
//@node 21C1AC6A-0 890 40
//@node 69B04AC3-0 665 145
//@node 1C707F71-0 1170 40
//@node 88906B28-0 965 145
//@node A3787548-0 760 145
//@node C93EA2E1-0 1450 200
//@node 857EAB9B-0 1245 305
//@node E2B14DD9-0 1040 305
//@node E2A41D9E-0 1040 389
//@node 8FCF0B79-0 1040 389
//@node 15610C60-0 1730 360
//@node 6B08000E-0 1505 465
//@node B7C88E77-0 2010 520
//@node 8A152207-0 2290 360
//@node BE6DD1DA-0 2065 465
//@node AEA0FED0-0 2570 520
//@node F25D7F4C-0 2850 520
//@node B2D1E214-0 2645 625
//@node 7C5B2C67-0 2440 625
//@node 51B60709-0 3130 680
//@node A61B4106-0 2925 785
//@node 25965688-0 3410 840
//@node 6165B9CF-0 3970 840
//@node 1CDCC29B-0 4250 200
//@node C973B311-0 4025 305
//@node 9EFAA4F1-0 4530 200
//@node DE6E4272-0 4325 305
//@node 439A4611-0 4810 360
//@node F32E02D8-0 5090 40
//@node E6A17AA2-0 4885 145
//@node D625709A-0 5370 200
//@node 6F67AD05-0 5650 40
//@node 9697EED5-0 5445 145
//@node 34E45C67-0 5240 145
//@node CD5DE734-0 5240 229
//@node EBF6CED0-0 5240 145
//@node E9F5AFA6-0 5930 200
//@node 84AD1E32-0 5705 305
//@node D4ABFC80-0 6210 200
//@node E4EC40BF-0 6005 305
//@node F625534D-0 5800 305
//@node 89AA20BC-0 5800 389
//@node BB3837D7-0 5800 473
//@node FB4A8DE6-0 6490 360
//@node 8D32C523-0 6265 465
//@node 65919C56-0 6770 520
//@node 57F25EBB-0 6545 625
//@node EE86F1B0-0 7050 520
//@node AAA6446A-0 6825 625
//@node B6FCC2C6-0 6620 725
//@node 7ACDA437-0 7330 520
//@node 5D5A09D5-0 7105 625
//@node 2AE0BA52-0 6900 725
//@node 646C6443-0 7610 520
//@node 361DA196-0 7405 625
//@node 77C95659-0 7200 625
//@node 946A1DDE-0 7890 680
//@node B105D529-0 8450 680
//@node 82244D88-0 8225 785
//@node 7D258E5E-0 8730 200
//@node A2FC7502-0 8525 305
//@node 19DDCE8B-0 8320 305
//@node F40621C4-0 8320 389
//@node 696A373D-0 9010 360
//@node 8B0E98AD-0 8785 465
//@node 3EF745CF-0 9290 360
//@node 879DFFF3-0 9065 465
//@node 5CC8B617-0 8860 565
//@node B36D39EA-0 9570 520
//@node 1628B8CD-0 9850 360
//@node 6287BF6A-0 9625 465
//@node 88711303-0 10130 360
//@node 27CECD42-0 9905 465
//@node 179CBCE1-0 9700 565
//@node 997ED75A-0 10410 520
//@node E7C0A34F-0 10185 625
//@node 0DDD4B38-0 9980 725
//@node E7A1DD00-0 10690 680
//@node 66545C57-0 10485 785
//@node B36D39EA-1 10970 680
//@node E0F5E131-0 11250 40
//@node 493F1A2A-0 40 40
//@node 0531E00D-0 330 40
//@node CD5C1029-0 610 40
//@node B64D8263-0 890 40
//@node 0E0AD425-0 1170 40
//@node 61FBD503-0 945 145
//@node CED8BAFE-0 1450 40
//@node B0525BBD-0 1245 145
//@node 7EAE62DB-0 40 40
//@node 263B6542-0 330 40
//@node C7B36106-0 610 40
//@node 7339981B-0 405 140
//@node 6E632F32-0 200 140
//@node C8FA2173-0 890 40
//@node 0BD3AE23-0 1170 40
//@node 193F2950-0 1450 40
//@node 2D358390-0 1225 145
//@node 6AAC44A3-0 40 40
//@node 8AE78BBA-0 330 40
//@node E7D92FF2-0 610 40
//@node 69FF9DC6-0 890 40
//@node 37FB0265-0 1170 40
//@node 817593AA-0 1450 40
//@node 2C32147E-0 1730 40
//@node 5FC29100-0 40 40
//@node 04E530B7-0 330 40
//@node 677AC505-0 610 40
//@node EA5ECCCA-0 890 40
//@node 47D8E1D4-0 1170 40
//@node C5F2E59F-0 1450 40
//@node 71B8C413-0 1225 145
//@node 335DA535-0 40 40
//@node EA557404-0 330 40
//@node C5C38FA8-0 610 40
//@node 05E04F62-0 890 40
//@node 0493EDA5-0 1170 40
//@node C429FD46-0 1450 40
//@node 56944759-0 1225 145
//@node 0B3ADEB4-0 40 40
//@node 11CF2A85-0 330 40
//@node 5154EB30-0 610 40
//@node 2E46EE22-0 385 145
//@node B763428B-0 890 200
//@node 9CCEC56C-0 1170 40
//@node 7A67E56D-0 945 145
//@node 0CB283C8-0 1450 40
//@node 845C66B8-0 1245 145
//@node 5DB83B8A-0 1040 145
//@node 78776298-0 1730 200
//@node 99B1CA56-0 1525 300
//@node C32A5775-0 1320 300
//@node B0D6E1C1-0 1320 378
//@node F607854A-0 2010 40
//@node E9A66D53-0 1785 145
//@node 43EFC79B-0 2290 40
//@node DAFE5F7E-0 1850 145
//@node F2C5712E-0 2080 145
//@node 206C36E9-0 2570 200
//@node 15015525-0 2345 305
//@node BB765D0B-0 2140 405
//@node D0632485-0 2850 200
//@node 45828160-0 2645 305
//@node D24DF1A3-0 2440 305
//@node C66741C4-0 3130 360
//@node 1922E33C-0 2925 460
//@node 904697F3-0 2720 460
//@node 2BE17CF3-0 2720 538
//@node 01538A44-0 3690 200
//@node 71B1DC6B-0 3485 305
//@node 91119487-0 3280 305
//@node A2BD9CE3-0 4250 360
//@node 60B61B46-0 3765 460
//@node E7469D5C-0 3560 460
//@node C2B7930E-0 3560 538
//@node 6310D32A-0 3560 616
//@node 864EF1E1-0 4250 200
//@node C03B7FBC-0 4025 305
//@node 6AF84FCD-0 4530 200
//@node 4AA434C4-0 4325 305
//@node D2BED0B6-0 4810 200
//@node B4F78FB0-0 4585 305
//@node 755F42D2-0 4380 405
//@node 535E23E2-0 5090 200
//@node 5E42DC17-0 4885 305
//@node 0989404B-0 4680 305
//@node 2D5E8FB9-0 4680 389
//@node 2EB15C0B-0 5370 200
//@node DF05C74B-0 5145 305
//@node 7268F2D1-0 5650 200
//@node E877C9ED-0 5445 305
//@node 3A699209-0 6210 40
//@node 6D277135-0 6490 40
//@node 86D33432-0 6005 140
//@node 16CAB0F7-0 6490 40
//@node 9DDC5AC5-0 6050 145
//@node 3F914C55-0 6280 145
//@node 5154EB30-1 6770 200
//@node 10CE0C75-0 6545 305
//@node B763428B-1 7330 360
//@node 3D3BCA20-0 7610 200
//@node 156F9C62-0 7890 40
//@node AAAFD542-0 8170 40
//@node 3A699209-1 8450 40
//@doomscript-blueprint end
