/***********************************************************************

monster_flying_cacodemon.script

monster_flying_cacodemon

***********************************************************************/

#define CACO_ATTACK_RATE	3
#define CACO_NOFOVTIME		4

object monster_flying_cacodemon : monster_base {
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;

	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();

	void		init();
	
	// anim states
	void		Torso_Idle();
	void		Torso_Fly();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_flying_cacodemon::Torso_Idle() {
	playCycle( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN )		{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 ); }
		if ( AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Fly", 4 ); }
	}
}

void monster_flying_cacodemon::Torso_Fly() {
	playCycle( ANIMCHANNEL_TORSO, "fly" );
	
	eachFrame {
		if ( AI_PAIN )		{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 ); }	
		if ( !AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_flying_cacodemon::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_flying_cacodemon::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );
	
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_flying_cacodemon::Torso_RangeAttack() {
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		faceEnemy();
		waitFrame();
	}

	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_flying_cacodemon::Torso_TurretAttack() {
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		faceEnemy();
		waitFrame();
	}

	finishAction( "turret_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_flying_cacodemon::init
=====================
*/
void monster_flying_cacodemon::init() {
	setState( "state_Begin" );
}

/*
=====================
monster_flying_cacodemon::state_Begin
=====================
*/
void monster_flying_cacodemon::state_Begin() {
	setMoveType( MOVETYPE_FLY );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	monster_begin();
	setState( "state_Idle" );
}

/*
=====================
monster_flying_cacodemon::state_Idle
=====================
*/
void monster_flying_cacodemon::state_Idle() {
	wait_for_enemy();
	
	nextAttack		= 0;
	nextNoFOVAttack = 0;
	
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_flying_cacodemon::do_attack
=====================
*/
void monster_flying_cacodemon::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + CACO_NOFOVTIME;
	if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_flying_cacodemon::check_attacks
=====================
*/
float monster_flying_cacodemon::check_attacks() {
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			if ( canHitEnemyFromAnim( "range_attack" ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_flying_cacodemon::combat_range
=====================
*/
void monster_flying_cacodemon::combat_range() {
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
	waitAction( "range_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( CACO_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + CACO_NOFOVTIME;
}

/*
=====================
monster_flying_cacodemon::combat_melee
=====================
*/
void monster_flying_cacodemon::combat_melee() {
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 4 );
	waitAction( "melee_attack" );
}

//@doomscript-blueprint begin 6
//@source DCAD077A
//@catalog 0C260740
//@node 6FF7CC05-0 40 40
//@node 59EB6B1D-0 330 40
//@node CE17868C-0 610 40
//@node F050BE7E-0 890 200
//@node 78C47505-0 685 305
//@node F4A795E4-0 480 305
//@node C177B81E-0 1170 200
//@node 97827E7D-0 965 305
//@node 29641599-0 760 305
//@node 647E418C-0 40 40
//@node 45382B6B-0 330 40
//@node DB885667-0 610 40
//@node BF20D34F-0 890 200
//@node 35DE3E71-0 685 305
//@node C128F18A-0 480 305
//@node C0B16CCB-0 1170 200
//@node 512AE6B0-0 965 305
//@node 7AB2B7CC-0 760 305
//@node F62314E3-0 40 40
//@node DB2E3B46-0 330 40
//@node 0E264E8C-0 105 145
//@node 8ACFE24E-0 610 40
//@node 472932CA-0 405 232
//@node 82707E6C-0 890 40
//@node C49FC851-0 685 145
//@node BD49C9FA-0 1170 40
//@node 64F2B4BE-0 730 145
//@node 07A2500E-0 960 145
//@node 2736AA90-0 1450 200
//@node E5E853D9-0 1245 305
//@node 045E0A81-0 1730 360
//@node 59F74A1A-0 1505 465
//@node 252213EC-0 2010 360
//@node D334BFD4-0 1805 465
//@node 13FBD317-0 1600 465
//@node F99532D6-0 1600 549
//@node E4A13B2B-0 2290 520
//@node 3A96CA49-0 2570 200
//@node 2209228A-0 2850 40
//@node 196743E9-0 3130 40
//@node 0997A181-0 40 40
//@node C03998D3-0 330 40
//@node 9F75C3E6-0 610 40
//@node 93B29FF4-0 170 145
//@node A5EE7C44-0 400 145
//@node 9874C033-0 890 200
//@node 508E5C99-0 1170 40
//@node 10D3F6A9-0 1450 40
//@node 0D9BC6E8-0 40 40
//@node 8297F98A-0 330 40
//@node 8D0E149B-0 610 40
//@node A7BFD2AB-0 890 40
//@node 46536BB1-0 1170 40
//@node 7ADA0E36-0 730 145
//@node F1DD6786-0 960 145
//@node 8D0E149B-1 1450 200
//@node EC26C1B8-0 1730 200
//@node 98E1B703-0 2010 40
//@node 436BE87E-0 2290 40
//@node 2BAB5259-0 40 40
//@node E90AD299-0 330 40
//@node 614EB55C-0 610 40
//@node D06268E0-0 890 40
//@node CC39DFBE-0 1170 40
//@node 155CA203-0 730 145
//@node DCFF0273-0 960 145
//@node 614EB55C-1 1450 200
//@node EFFBD197-0 1730 200
//@node 676AF0B7-0 2010 40
//@node 983D48DD-0 2290 40
//@node 38E34BF1-0 40 40
//@node 5CB99AA7-0 330 40
//@node 172170CE-0 40 40
//@node DDAA2612-0 330 40
//@node F2B6AF6C-0 610 40
//@node 2828DF38-0 890 40
//@node 3609B8D3-0 1170 40
//@node 84D8EB43-0 40 40
//@node 6330087B-0 330 40
//@node 2C317A29-0 610 40
//@node 7D648E51-0 405 145
//@node 357E3E91-0 890 40
//@node F80FB331-0 685 145
//@node DE264338-0 1170 40
//@node 60E5F1AF-0 40 40
//@node E20E1CC5-0 330 40
//@node 60845E16-0 125 145
//@node 91C662E3-0 610 40
//@node 0DF7742B-0 405 145
//@node EDDAC195-0 890 200
//@node 516DD50A-0 685 300
//@node B87B668F-0 1170 200
//@node E136621C-0 965 305
//@node 966A3208-0 1450 200
//@node AAE54E3B-0 1730 200
//@node 6EE7E583-0 1525 305
//@node 9299D43F-0 2010 200
//@node 88EEC4A7-0 40 40
//@node 0EAEBD74-0 330 40
//@node CD1098BD-0 125 145
//@node 2DA09AA7-0 610 40
//@node 526E32B6-0 385 145
//@node 662EFF77-0 890 40
//@node 149C1815-0 665 145
//@node 079A41C6-0 1170 40
//@node BA0A8B58-0 965 145
//@node 3A2586EA-0 760 145
//@node 914CFD36-0 1450 200
//@node F12EA517-0 1225 305
//@node 39487A32-0 1730 200
//@node 1DDAA811-0 1525 305
//@node 2AF47E12-0 2010 360
//@node DD781615-0 2290 40
//@node E52AE187-0 2085 145
//@node 62A222ED-0 2570 200
//@node AA9779DC-0 2850 40
//@node 2F947AE2-0 2645 145
//@node 6BCB1F22-0 2440 145
//@node E6C55723-0 2440 229
//@node 2F49495B-0 2440 145
//@node 901BC111-0 3130 200
//@node 4256A08A-0 2925 305
//@node 1A52D8F9-0 2720 305
//@node 09E2F4CA-0 2720 389
//@node EC13FA02-0 3410 360
//@node 68464934-0 3185 465
//@node AD8E8441-0 3690 520
//@node 601001BE-0 3970 40
//@node FD2B8145-0 40 40
//@node 3A2B7800-0 330 40
//@node D7D5B11E-0 610 40
//@node BA12E440-0 890 40
//@node 536357EE-0 1170 40
//@node 52FBD074-0 945 145
//@node E1C0B451-0 1450 40
//@node 4748AAA3-0 1245 145
//@node 6638ED6C-0 40 40
//@node 7F87A5CB-0 330 40
//@node 933DF44C-0 610 40
//@node 779DB952-0 890 40
//@doomscript-blueprint end
