/***********************************************************************

monster_demon_wraith.script

monster_demon_wraith

***********************************************************************/

#define WRAITH_ATTACK_RATE			1.5
#define WRAITH_DODGE_RATE			5
#define	WRAITH_PAIN_DELAY			0.25
#define WRAITH_RUNDISTANCE			192
#define WRAITH_WALKTURN				65
#define WRAITH_INVISIBLE_DIST_MIN	140
#define WRAITH_INVISIBLE_DIST_MAX	256
#define WRAITH_INVISIBLE_DELAY_MIN	0.6
#define WRAITH_INVISIBLE_DELAY_MAX	1.5
#define WRAITH_VISIBLE_DELAY_MIN	1.3
#define WRAITH_VISIBLE_DELAY_MAX	2.2

// anim blend times
#define	WRAITH_PAIN_TO_IDLE			2
#define WRAITH_PAIN_TO_PAIN			0
#define WRAITH_SIGHT_TO_IDLE		4
#define	WRAITH_MELEE_TO_IDLE		4
#define WRAITH_DODGE_LEFT_TO_IDLE	4
#define	WRAITH_DODGE_RIGHT_TO_IDLE	4
#define WRAITH_WAIT_TO_OUT			4
#define	WRAITH_IN_TO_WAIT			4
#define	WRAITH_WALK_TO_WAIT			4
#define WRAITH_WALK_TO_ACTION		4
#define WRAITH_ACTION_TO_IDLE		4
#define WRAITH_WALK_TO_DODGE_LEFT	4
#define WRAITH_WALK_TO_DODGE_RIGHT	4
#define WRAITH_IDLE_TO_PAIN			0
#define WRAITH_IDLE_TO_WALK			4
#define WRAITH_IDLE_TO_SIGHT		4
#define WRAITH_WALK_TO_IDLE			4
#define WRAITH_WALK_TO_MELEE		4
#define WRAITH_IDLE_TO_RUN			4
#define WRAITH_WALK_TO_RUN			4
#define WRAITH_RUN_TO_WALK			4
#define WRAITH_RUN_TO_IDLE			4

#define	ATTACK_BECOME_INVISIBLE		ATTACK_SPECIAL1
#define	ATTACK_BECOME_VISIBLE		ATTACK_SPECIAL2

object monster_demon_wraith : monster_base {
	float		nextDodge;
	float		nextInvisible;
	entity		combat_node;
	entity		spawn_effect;

	boolean		invisible;
	
	// States
	void		state_Begin();
	void		state_Idle();
	void		state_LostCombat();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();
	void		combat_become_visible();
	void		combat_become_invisible();

	void		spawn_fx();

	void		init();
	void		destroy();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_wraith::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", WRAITH_IDLE_TO_PAIN );
}

void monster_demon_wraith::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + WRAITH_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_TORSO, WRAITH_PAIN_TO_IDLE ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", WRAITH_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", WRAITH_PAIN_TO_IDLE );
}

void monster_demon_wraith::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, WRAITH_MELEE_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", WRAITH_MELEE_TO_IDLE );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_wraith::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", WRAITH_IDLE_TO_RUN ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", WRAITH_IDLE_TO_WALK ); }
	}
}

void monster_demon_wraith::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", WRAITH_WALK_TO_RUN ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", WRAITH_WALK_TO_IDLE ); }
	}
}

void monster_demon_wraith::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", WRAITH_RUN_TO_WALK ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", WRAITH_RUN_TO_IDLE ); }
	}
}

void monster_demon_wraith::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, WRAITH_DODGE_LEFT_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", WRAITH_DODGE_LEFT_TO_IDLE );
}

void monster_demon_wraith::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, WRAITH_DODGE_RIGHT_TO_IDLE ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", WRAITH_DODGE_RIGHT_TO_IDLE );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_wraith::init
=====================
*/
void monster_demon_wraith::init() {
	setState( "state_Begin" );
}

/*
=====================
monster_demon_wraith::destroy
=====================
*/
void monster_demon_wraith::destroy() {
	if ( spawn_effect ) {
		spawn_effect.remove();
	}
}

/*
=====================
monster_demon_wraith::state_Begin
=====================
*/
void monster_demon_wraith::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );		
	setState( "state_Idle" );
}

/*
=====================
monster_demon_wraith::state_Idle
=====================
*/
void monster_demon_wraith::state_Idle() {
	wait_for_enemy();

	nextDodge		= RandomTime( WRAITH_DODGE_RATE );
	nextInvisible	= 0;

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_wraith::do_attack
=====================
*/
void monster_demon_wraith::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_BECOME_VISIBLE ) {
		combat_become_visible();
	} else if ( attack_flags & ATTACK_BECOME_INVISIBLE ) {
		combat_become_invisible();
	} else if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	}
}

/*
=====================
monster_demon_wraith::check_attacks
=====================
*/
float monster_demon_wraith::check_attacks() {
	float range;
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	range = enemyRange();
	currentTime = sys.getTime();

	if ( invisible ) {
		if ( ( range < WRAITH_INVISIBLE_DIST_MIN ) || ( currentTime >= nextInvisible ) ) {
			if ( canBecomeSolid() ) {
				attack_flags |= ATTACK_BECOME_VISIBLE;
			}
		}

		return attack_flags;
	}
	
	canMelee = testMeleeAttack();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	range = enemyRange();
	if ( AI_ONGROUND && ( range > WRAITH_INVISIBLE_DIST_MAX ) && ( currentTime >= nextInvisible ) ) {
		attack_flags |= ATTACK_BECOME_INVISIBLE;
	}
	
	return attack_flags;
}

/***********************************************************************

	Combat

***********************************************************************/

/*
=====================
monster_demon_wraith::combat_melee
=====================
*/
void monster_demon_wraith::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", WRAITH_WALK_TO_MELEE );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_wraith::combat_dodge_left
=====================
*/
void monster_demon_wraith::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", WRAITH_WALK_TO_DODGE_LEFT );
	waitAction( "strafe" );
	nextDodge = DelayTime( WRAITH_DODGE_RATE );
}

/*
=====================
monster_demon_wraith::combat_dodge_right
=====================
*/
void monster_demon_wraith::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", WRAITH_WALK_TO_DODGE_RIGHT );
	waitAction( "strafe" );
	nextDodge = DelayTime( WRAITH_DODGE_RATE );
}

/*
=====================
monster_demon_wraith::spawn_fx
=====================
*/
void monster_demon_wraith::spawn_fx() {
	if ( !spawn_effect ) {
		spawn_effect = sys.spawn( "wraith_spawneffect" );
	}

	spawn_effect.setOrigin( getOrigin() );
	spawn_effect.show();
	spawn_effect.setShaderParm( SHADERPARM_TIMEOFFSET, -sys.getTime() );
}

/*
=====================
monster_demon_wraith::combat_become_visible
=====================
*/
void monster_demon_wraith::combat_become_visible() {
	float endTime;

	stopMove();

	if ( invisible ) {
		// don't allow movement so that he stays in the same place where we checked if he could become solid
		allowMovement( false );

		// check again just to make sure
		while( !canBecomeSolid() ) {
			waitFrame();
		}

		becomeSolid();
		allowHiddenMovement( false );
		allowMovement( true );

		animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );

		startSound( "snd_fade_in", SND_CHANNEL_VOICE2, false );
		spawn_fx();
		sys.wait( 0.65 );

		show();
		endTime = sys.getTime() + 0.5;
		while( endTime > sys.getTime() ) {
			setShaderParm( SHADERPARM_TIME_OF_DEATH, sys.getTime() - ( endTime - sys.getTime() ) * 8 );
			waitFrame();
		}

		clearBurn();
		sys.wait( 0.10 );
		spawn_effect.hide();

		invisible = false;
	}

	nextInvisible = RandomDelay( WRAITH_INVISIBLE_DELAY_MIN, WRAITH_INVISIBLE_DELAY_MAX );
}

/*
=====================
monster_demon_wraith::combat_become_invisible
=====================
*/
void monster_demon_wraith::combat_become_invisible() {
	float endTime;
	float startTime;

	stopMove();

	if ( !invisible ) {
		// wait a bit incase we're blending from a run/walk
		sys.wait( 0.167 );

		invisible = true;

		startSound( "snd_fade_out", SND_CHANNEL_VOICE2, false );
		spawn_fx();
		sys.wait( 0.65 );

		preBurn();
		startTime = sys.getTime();
		endTime = sys.getTime() + 0.5;
		while( endTime > sys.getTime() ) {
			setShaderParm( SHADERPARM_TIME_OF_DEATH, sys.getTime() - ( sys.getTime() - startTime ) * 8 );
			waitFrame();
		}

		sys.wait( 0.10 );

		hide();
		spawn_effect.hide();
	}

	allowHiddenMovement( true );
	setShaderParm( SHADERPARM_TIME_OF_DEATH, sys.getTime() - 100 );
	nextInvisible = RandomDelay( WRAITH_VISIBLE_DELAY_MIN, WRAITH_VISIBLE_DELAY_MAX );
}

/*
=====================
monster_demon_wraith::state_LostCombat
=====================
*/
void monster_demon_wraith::state_LostCombat() {
	combat_become_invisible();
	sys.wait( nextInvisible - sys.getTime() );

	stopMove();
	while( !canReachEnemy() ) {
		waitFrame();
	}

	sys.wait( 2 );

	combat_become_visible();
	
	setState( "state_Combat" );
}

//@doomscript-blueprint begin 6
//@source 3B7EB0E4
//@catalog 0C260740
//@node 09897EDF-0 40 40
//@node 1510ABE6-0 330 40
//@node B9272597-0 610 40
//@node 8D3C1EF7-0 405 145
//@node 8EE14F7F-0 200 145
//@node C11529D1-0 890 200
//@node C6ADD518-0 1170 40
//@node 965F3131-0 40 40
//@node B6B74314-0 330 40
//@node EBE35A55-0 105 145
//@node 334A2BEC-0 610 40
//@node 8E944509-0 405 232
//@node F677735F-0 890 40
//@node 7ACF88A1-0 685 145
//@node 8F992E29-0 1170 40
//@node 4EDAD5F8-0 730 145
//@node C57E4A68-0 960 145
//@node ED40EFCE-0 1450 200
//@node AC94D558-0 1245 305
//@node 10D92D0F-0 1730 360
//@node 8034DB94-0 1505 465
//@node 32FDFF02-0 2010 360
//@node 40CAAF7E-0 1805 465
//@node 465F4345-0 1600 465
//@node D3188150-0 1600 549
//@node 68CAB490-0 2290 520
//@node B660156B-0 2570 200
//@node EA6B4CF0-0 2850 40
//@node B37C2C9C-0 3130 40
//@node 5ACCA8B7-0 40 40
//@node 0CD4A19D-0 330 40
//@node 7D59B5AF-0 610 40
//@node 069E5CF1-0 170 145
//@node AAE2D421-0 400 145
//@node 274BFAC5-0 890 200
//@node 24C65B0F-0 1170 40
//@node AB378E40-0 1450 40
//@node F871A6C7-0 40 40
//@node E8211D1A-0 330 40
//@node 0EBD9904-0 610 40
//@node AE323B43-0 890 200
//@node 703E6B33-0 685 305
//@node A3C028EA-0 480 305
//@node 11914E2B-0 480 389
//@node 36FC2B64-0 1170 200
//@node D48B5C45-0 965 305
//@node 184435C3-0 760 305
//@node 476E49FC-0 40 40
//@node 1489733B-0 330 40
//@node 3367D137-0 610 40
//@node 45CB028F-0 890 200
//@node 30068192-0 685 305
//@node D4C2E37A-0 480 305
//@node 3488989B-0 480 389
//@node A4DCDD6B-0 1170 200
//@node 9AC46988-0 965 305
//@node D007CD20-0 760 305
//@node 84E9021E-0 40 40
//@node E8E9573D-0 330 40
//@node 5706B969-0 125 232
//@node E50D2F18-0 -80 232
//@node 922B2643-0 610 40
//@node 7765D56E-0 890 200
//@node 52E6BD2E-0 685 305
//@node 1FF4A103-0 480 305
//@node 22ACC32C-0 480 389
//@node D5BB6A11-0 1170 200
//@node 2E54870A-0 965 305
//@node C0F0757C-0 760 305
//@node FE9FB3AD-0 40 40
//@node B6CA8059-0 330 40
//@node 5E23ADA8-0 610 40
//@node A0935113-0 170 145
//@node D187C283-0 400 145
//@node 2E06D35F-0 890 200
//@node ECA80FCF-0 1170 40
//@node 0D969A75-0 1450 40
//@node D5BA7CE6-0 40 40
//@node 3CA96D37-0 330 40
//@node A359A76E-0 610 40
//@node CACB2CE4-0 170 145
//@node 9ED7F934-0 400 145
//@node 2621A97E-0 890 200
//@node 0425D260-0 1170 40
//@node 40C4E0FD-0 1450 40
//@node 785CA59B-0 40 40
//@node 06D32765-0 330 40
//@node C792B6AD-0 40 40
//@node 24B07ADC-0 330 40
//@node 46ECA9E3-0 125 145
//@node E9A47AC6-0 610 200
//@node 48A558D4-0 40 40
//@node C3AC822A-0 330 40
//@node F79BC8EC-0 610 40
//@node 1AA18C86-0 890 40
//@node 87FFB656-0 1170 40
//@node B6102E3D-0 1450 40
//@node 56763FC9-0 40 40
//@node CFF04B81-0 330 40
//@node DEDFD671-0 610 40
//@node 7E44360E-0 385 145
//@node 6B18D284-0 890 40
//@node B6B5FE22-0 685 145
//@node F6E6D9FE-0 1170 40
//@node 331FEC41-0 40 40
//@node 5E339DDA-0 330 40
//@node 0B9FB95F-0 125 145
//@node 516DEDBA-0 610 200
//@node 8C26AA78-0 890 200
//@node 539A30CC-0 685 305
//@node AC908E19-0 1170 200
//@node D44FFF44-0 1450 200
//@node D279BE8E-0 1245 305
//@node 30D6EC4D-0 1730 200
//@node 037E7FF3-0 2010 200
//@node 3FB97586-0 1805 305
//@node 539E84A8-0 2290 200
//@node 7B7383FC-0 2570 200
//@node 5879C1B3-0 2365 305
//@node 14C3DE9B-0 2850 200
//@node DE0DF8EF-0 2645 300
//@node C67A3DA9-0 3130 200
//@node 95CEE1B3-0 2925 305
//@node 24E1CDA6-0 3410 200
//@node BF02820D-0 40 40
//@node 34242846-0 330 40
//@node 47AFB3A6-0 125 145
//@node DDE73A7F-0 610 40
//@node 8A9111F5-0 385 145
//@node B46C9D75-0 890 40
//@node BFF4FF8C-0 665 145
//@node A37827A6-0 1170 40
//@node 388A7D2B-0 965 145
//@node 3D6A24EA-0 1450 200
//@node 0E11B08F-0 1245 305
//@node 8DCEA20C-0 1040 305
//@node B2234EC1-0 1040 389
//@node 19C1D405-0 1040 473
//@node 356C68F4-0 1730 360
//@node D5C85994-0 1505 465
//@node 94E600AF-0 2010 520
//@node 48B5C950-0 2290 200
//@node 0A9792B5-0 2570 40
//@node 456D6ADC-0 2345 145
//@node 968B1CCC-0 2850 40
//@node 744B8828-0 2645 145
//@node 14CE9A0E-0 2440 145
//@node EA38117C-0 3130 200
//@node 94E3EC02-0 2925 305
//@node 3906845A-0 2720 305
//@node D54A8C4D-0 2720 389
//@node 12CE87D6-0 2720 389
//@node 70AC956F-0 3410 360
//@node 81F45CCC-0 3185 465
//@node 17D916D0-0 3690 520
//@node A5B15EEE-0 3970 360
//@node 72AFE4C6-0 3745 465
//@node F1A9789D-0 4250 520
//@node 730E4A8F-0 4530 520
//@node D78F3950-0 4325 625
//@node 91D49A75-0 4120 625
//@node EFA6381A-0 4810 680
//@node 5167F166-0 4605 785
//@node 87C8ABC7-0 5090 840
//@node 8924BEE2-0 5650 840
//@node 14869834-0 5930 200
//@node AE424E70-0 5705 305
//@node B61E90E0-0 6210 200
//@node 799FAA94-0 6005 305
//@node 3FC24020-0 6490 360
//@node 0CAADCAF-0 6770 40
//@node 17E47E1C-0 6565 145
//@node E430E19B-0 7050 200
//@node DDE73A7F-1 7330 40
//@node F02C3AD0-0 7105 145
//@node D8F39EC5-0 7610 40
//@node 4712CFBD-0 7405 145
//@node C2CF0247-0 7200 145
//@node 5E53AD72-0 7200 229
//@node F5A80B6B-0 7200 313
//@node 5D730B5E-0 7200 313
//@node 16893034-0 7890 200
//@node 48B5C950-1 8170 40
//@node 73F5463A-0 40 40
//@node 61A23417-0 330 40
//@node 43B344D5-0 610 40
//@node E00F10F6-0 890 40
//@node A2A5B0C0-0 1170 40
//@node C9924D7F-0 1450 40
//@node 663C08C3-0 40 40
//@node 4ECF3E5E-0 330 40
//@node 11932FD2-0 610 40
//@node 46253888-0 890 40
//@node 93230A67-0 1170 40
//@node D07AEA27-0 1450 40
//@node 419E4220-0 1225 145
//@node FDE798CC-0 40 40
//@node 68FE6A25-0 330 40
//@node 70885757-0 610 40
//@node D990B7A3-0 890 40
//@node C9AF9E74-0 1170 40
//@node 57261BAA-0 1450 40
//@node DAD8117B-0 1225 145
//@node 400CF53B-0 40 40
//@node C0040BE1-0 330 40
//@node 2104BC85-0 125 145
//@node 5FEDABB5-0 -80 145
//@node BC61DB42-0 610 200
//@node D686D30C-0 385 305
//@node 8A04461D-0 890 40
//@node 650A8EC3-0 1170 40
//@node 4B0F5A65-0 1450 40
//@node B9EB1856-0 40 40
//@node AFB5035F-0 330 40
//@node 0E973523-0 610 40
//@node 70E60A05-0 405 145
//@node 63FE7851-0 890 200
//@node 19C99480-0 1170 200
//@node 856EA74F-0 730 305
//@node 1D9A3CDF-0 960 305
//@node C0480BF6-0 1450 360
//@node E86FA628-0 1730 200
//@node 62DE127D-0 2010 200
//@node 424BBCC8-0 2290 200
//@node 0030192E-0 2570 200
//@node 18BE7FC4-0 2850 200
//@node BC5A2E3A-0 3130 200
//@node 8CC4B105-0 3410 200
//@node 82CEF56B-0 3690 200
//@node 609687E0-0 3970 200
//@node B03F75BF-0 3765 305
//@node C0A89FF5-0 4250 200
//@node 320994E1-0 4025 305
//@node CD2006F6-0 4530 360
//@node 7C154D78-0 4325 552
//@node 0B0C7408-0 4120 552
//@node C0480BF6-1 4810 360
//@node 8D7B0D0C-0 5090 200
//@node EA7A6C05-0 5370 200
//@node F6CBAFBF-0 5650 200
//@node 7059E65F-0 5930 200
//@node B8DD9F2C-0 5725 305
//@node 0742D85E-0 6210 40
//@node D1A0ED43-0 5985 145
//@node 06CD0F0F-0 40 40
//@node 7491017A-0 330 40
//@node 827F33F9-0 610 40
//@node 147A08E6-0 405 145
//@node 37807ADA-0 200 145
//@node AC2BD2D5-0 890 200
//@node 6AB75759-0 1170 200
//@node 54118797-0 965 305
//@node ED39D4AA-0 1450 200
//@node 2D73E3FB-0 1730 200
//@node C0DD3270-0 2010 200
//@node 26AA94BF-0 2290 200
//@node 20E7EA58-0 2570 200
//@node 1434A157-0 2345 305
//@node 87C51523-0 2850 200
//@node 495051A5-0 2645 305
//@node 137BB34A-0 3130 200
//@node B738D72F-0 2905 305
//@node 06C989FC-0 3410 360
//@node 7AE6946B-0 3205 552
//@node 819CE0AB-0 3000 552
//@node 7D2D8391-0 3690 360
//@node 63277770-0 3970 200
//@node 48B74319-0 4250 200
//@node C9B1DF38-0 4530 200
//@node C9EB70C3-0 4810 40
//@node B2FF0A4F-0 5090 40
//@node 02CD3ECD-0 5370 40
//@node F3E5FBC3-0 5145 145
//@node 9F42BB15-0 40 40
//@node E6A8EEDD-0 330 40
//@node EF09BC6F-0 610 40
//@node 27C5AC95-0 405 140
//@node BE3CC1B0-0 200 140
//@node 891BDCCC-0 890 40
//@node ACCD5FE6-0 1170 40
//@node 39AEEB17-0 730 145
//@node FF66B5A7-0 960 145
//@node DD8A5733-0 1450 200
//@node FE3F2847-0 1730 40
//@node 8CBEF4C6-0 2010 40
//@node 46CEA3A6-0 2290 40
//@doomscript-blueprint end
