/***********************************************************************

ai_monster_demon_hellknight.script

monster_demon_hellknight

***********************************************************************/

#define HELLKNIGHT_ATTACK_RATE			3
#define	HELLKNIGHT_PAIN_DELAY			0.25
#define HELLKNIGHT_NOFOVTIME			6

// anim blend times
#define	HELLKNIGHT_PAIN_TO_IDLE			2
#define HELLKNIGHT_PAIN_TO_PAIN			0
#define HELLKNIGHT_SIGHT_TO_IDLE		4
#define	HELLKNIGHT_MELEE_TO_IDLE		4
#define HELLKNIGHT_RANGE_TO_IDLE		4
#define HELLKNIGHT_WAIT_TO_OUT			4
#define	HELLKNIGHT_IN_TO_WAIT			4
#define	HELLKNIGHT_WALK_TO_WAIT			4
#define HELLKNIGHT_WALK_TO_ACTION		4
#define HELLKNIGHT_ACTION_TO_IDLE		4
#define HELLKNIGHT_IDLE_TO_PAIN			0
#define HELLKNIGHT_IDLE_TO_WALK			4
#define HELLKNIGHT_IDLE_TO_SIGHT		4
#define HELLKNIGHT_WALK_TO_IDLE			4
#define HELLKNIGHT_WALK_TO_RANGEATTACK	4
#define HELLKNIGHT_IDLE_TO_RANGEATTACK	4
#define HELLKNIGHT_WALK_TO_MELEE		4
#define HELLKNIGHT_IDLE_TO_TURRETATTACK	4
#define HELLKNIGHT_TURRETATTACK_TO_IDLE	4

object monster_demon_hellknight : monster_base {
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;
	string		range_attack_anim;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_hellknight::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", HELLKNIGHT_IDLE_TO_PAIN );
}

void monster_demon_hellknight::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + HELLKNIGHT_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_TORSO, HELLKNIGHT_PAIN_TO_IDLE ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", HELLKNIGHT_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", HELLKNIGHT_PAIN_TO_IDLE );
}

void monster_demon_hellknight::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, HELLKNIGHT_MELEE_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", HELLKNIGHT_MELEE_TO_IDLE );
}

void monster_demon_hellknight::Torso_RangeAttack() {
	string anim;
	
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, range_attack_anim );
	while( !animDone( ANIMCHANNEL_TORSO, HELLKNIGHT_RANGE_TO_IDLE ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}

	allowMovement( true );
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", HELLKNIGHT_RANGE_TO_IDLE );
}

void monster_demon_hellknight::Torso_TurretAttack() {
	allowMovement( false );
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "turret_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "turret_attack" );
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_hellknight::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_demon_hellknight::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_hellknight::init
=====================
*/
void monster_demon_hellknight::init() {
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_hellknight::state_Begin
=====================
*/
void monster_demon_hellknight::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );		
	setState( "state_Idle" );
}

/*
=====================
monster_demon_hellknight::state_Idle
=====================
*/
void monster_demon_hellknight::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_hellknight::do_attack
=====================
*/
void monster_demon_hellknight::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + HELLKNIGHT_NOFOVTIME;
	if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_demon_hellknight::check_attacks
=====================
*/
float monster_demon_hellknight::check_attacks() {
	float	currentTime;
	float	canMelee;
	float	attack_flags;
	vector	vel;
	float	t;
	vector	jumpTarget;
	string	anim;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}
	
	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			range_attack_anim = chooseAnim( ANIMCHANNEL_LEGS, "turret_attack" );
			if ( canHitEnemyFromAnim( range_attack_anim ) ) {
				attack_flags |= ATTACK_MISSILE;
			}

			anim = chooseAnim( ANIMCHANNEL_LEGS, "range_attack" );
			if ( testAnimMoveTowardEnemy( anim ) ) {
				if ( canHitEnemyFromAnim( anim ) ) {
					range_attack_anim = anim;
					attack_flags |= ATTACK_MISSILE;
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_hellknight::combat_range
=====================
*/
void monster_demon_hellknight::combat_range() {
	faceEnemy();
	if ( !AI_ENEMY_IN_FOV ) {
		sys.wait( 0.4 );
	}

	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", HELLKNIGHT_WALK_TO_RANGEATTACK );
	waitAction( "range_attack" );

	// don't attack for a bit
	nextAttack = DelayTime( HELLKNIGHT_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + HELLKNIGHT_NOFOVTIME;
}

/*
=====================
monster_demon_hellknight::combat_melee
=====================
*/
void monster_demon_hellknight::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", HELLKNIGHT_WALK_TO_MELEE );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

//@doomscript-blueprint begin 6
//@source 27D5686D
//@catalog 0C260740
//@node D103CD92-0 40 40
//@node B44C767D-0 330 40
//@node F83B7E0A-0 610 40
//@node 2E6529B3-0 405 145
//@node 673D736F-0 200 145
//@node 1170BE0A-0 890 200
//@node BE1A00AE-0 1170 40
//@node C576CEF0-0 40 40
//@node 9AEC090D-0 330 40
//@node 9B27844C-0 105 145
//@node 1B8437EF-0 610 40
//@node 7F21BAE1-0 405 232
//@node 67265A4B-0 890 40
//@node 7D26EFE1-0 685 145
//@node 0309D8ED-0 1170 40
//@node F92552E8-0 730 145
//@node 92E3A5F8-0 960 145
//@node 43B3FAC9-0 1450 200
//@node 627BAF02-0 1245 305
//@node 7DDCF57C-0 1730 360
//@node FC5EF9D4-0 1505 465
//@node A177E96B-0 2010 360
//@node BAD94476-0 1805 465
//@node 37276AA9-0 1600 465
//@node 8F4AFED4-0 1600 549
//@node 0D52326A-0 2290 520
//@node AE9711F0-0 2570 200
//@node 0A49ED2D-0 2850 40
//@node 249D5F82-0 3130 40
//@node EC2DAFB8-0 40 40
//@node 76529A30-0 330 40
//@node 3030C591-0 610 40
//@node 92B8D9F9-0 170 145
//@node FF30D0C9-0 400 145
//@node 5058ACB8-0 890 200
//@node 41CA0778-0 1170 40
//@node A5760DD4-0 1450 40
//@node 004DA46D-0 40 40
//@node DED46BC9-0 330 40
//@node EDB2116C-0 610 40
//@node 965B4B14-0 890 40
//@node 23513BDB-0 685 232
//@node 19414775-0 1170 40
//@node DCB8AB76-0 730 145
//@node 755C1046-0 960 145
//@node 857A51C4-0 1450 200
//@node 41525227-0 1730 200
//@node B07610B1-0 2010 40
//@node 0F37C68A-0 2290 40
//@node F7BAEE3A-0 2570 40
//@node A2AD9656-0 40 40
//@node 48BC5931-0 330 40
//@node B7D73798-0 610 40
//@node D8AE1441-0 890 40
//@node A3DEFDB2-0 1170 40
//@node ABF9E6F7-0 1450 40
//@node F6236E11-0 1010 145
//@node C4194961-0 1240 145
//@node 1DF28956-0 1730 200
//@node FD4C5016-0 2010 40
//@node 3F88F2A8-0 2290 40
//@node C9AFA068-0 2570 40
//@node 97BCC1E4-0 40 40
//@node 9B3EAEA5-0 330 40
//@node F8323CDF-0 610 40
//@node C6F3D83F-0 890 200
//@node AFD73CE5-0 685 305
//@node DF39D6E5-0 480 305
//@node FC043D8B-0 40 40
//@node 4FAEA682-0 330 40
//@node CB5FEA28-0 610 40
//@node 1C79E97E-0 890 200
//@node 08D63845-0 685 305
//@node 1EC1E1F1-0 480 305
//@node CD596456-0 40 40
//@node 3FA665D6-0 330 40
//@node 50E2BC47-0 40 40
//@node D014A9C7-0 330 40
//@node 0BD07B11-0 610 40
//@node 9B5B1E37-0 890 40
//@node A630B9FD-0 1170 40
//@node AF2D441E-0 1450 40
//@node ED2947F4-0 40 40
//@node 60AD59A4-0 330 40
//@node CFF39202-0 610 40
//@node 2C9C7471-0 405 145
//@node 4B7C5D20-0 890 40
//@node E32AE6D9-0 685 145
//@node 12BB047F-0 1170 40
//@node E2717B82-0 40 40
//@node 401392E8-0 330 40
//@node 547CEFE1-0 125 145
//@node 3CF0E1B0-0 610 40
//@node 35D0B553-0 405 145
//@node 3AFFC42C-0 890 200
//@node D0B6D635-0 685 300
//@node 9EBCAA9A-0 1170 200
//@node 6E1A4B17-0 965 305
//@node 86A76DE1-0 1450 200
//@node E239AF0A-0 1730 200
//@node 79484AD5-0 1525 305
//@node 19210DFA-0 2010 200
//@node 45DFC9B6-0 40 40
//@node F5C82B7D-0 330 40
//@node 4BD1A50F-0 125 145
//@node 2B0C0516-0 610 40
//@node F972EDC9-0 385 145
//@node 5A245AE0-0 890 40
//@node FD986836-0 665 145
//@node 9D1F46E5-0 1170 40
//@node 1ABD2824-0 965 145
//@node 4A4247D6-0 760 145
//@node 0362C671-0 1450 200
//@node 5238BEE0-0 1225 305
//@node 8EB4C195-0 1730 200
//@node 681DB070-0 1525 305
//@node 0C8F9CC7-0 2010 360
//@node CB642DD4-0 2290 40
//@node 65CF5987-0 2085 145
//@node 6ED54770-0 2570 200
//@node 14385C41-0 2850 40
//@node 3373B001-0 2645 145
//@node 519E5AE1-0 2440 145
//@node 66074A02-0 2440 229
//@node DB56B3DE-0 2440 145
//@node 07B1E3E2-0 3130 200
//@node 6946071A-0 2925 305
//@node 98E7E1E5-0 2720 305
//@node 796716BE-0 2720 389
//@node ACAB8ACF-0 3410 360
//@node F0774973-0 3185 465
//@node 30399C9B-0 3690 360
//@node 4756D908-0 3465 465
//@node D7FCEEA3-0 3260 565
//@node 7ABCAC18-0 3970 520
//@node 44BE07E7-0 4250 360
//@node 7A594BC0-0 4025 465
//@node BFFDCADF-0 4530 360
//@node 373B1EA5-0 4305 465
//@node A39D0684-0 4100 565
//@node FE8D5946-0 4810 520
//@node BFDA0035-0 4585 625
//@node 391D5614-0 4380 725
//@node 1377453E-0 5090 680
//@node 991C3AAC-0 4885 785
//@node 7ABCAC18-1 5370 680
//@node 6FB5571D-0 5650 40
//@node 965128E6-0 40 40
//@node 1E51C019-0 330 40
//@node 1A11869A-0 610 40
//@node 95A40AD5-0 405 145
//@node 9656D455-0 200 145
//@node C273C316-0 890 200
//@node 3D1DA1F7-0 1170 40
//@node 03E9FA3F-0 1450 40
//@node 12125461-0 1730 40
//@node 537C8DA4-0 1505 145
//@node 150B73C2-0 2010 40
//@node FD433CA6-0 1805 145
//@node 0E9FE40F-0 40 40
//@node 2A83B7FE-0 330 40
//@node B5D3D5DE-0 610 40
//@node B77BE1DE-0 890 40
//@node 1848A391-0 1170 40
//@node EB7B998E-0 1450 40
//@doomscript-blueprint end
