/***********************************************************************

ai_monster_demon_maggot.script

monster_demon_maggot

***********************************************************************/

#define MAGGOT_RUNDISTANCE		192
#define MAGGOT_ATTACK_RATE		1
#define MAGGOT_LEAP_RATE		7
#define MAGGOT_LEAP_SPEED		650
#define MAGGOT_LEAP_MAXHEIGHT	48
#define MAGGOT_DODGE_RATE		8
#define MAGGOT_LEAP_RANGE_MIN	200
#define MAGGOT_LEAP_RANGE_MAX	480

object monster_demon_maggot : monster_base {
	float		nextDodge;
	float		nextLeap;
	vector		jumpVelocity;
	entity		combat_node;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_leap();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();

	void		init();
	void		path_jump();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_LeapAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_maggot::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN ) { animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 ); }
	}
}

void monster_demon_maggot::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 2 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_maggot::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_maggot::Torso_LeapAttack() {
	overrideAnim( ANIMCHANNEL_LEGS );
	disablePain();
	playAnim( ANIMCHANNEL_TORSO, "jump_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		waitFrame();
	}
	
	attackBegin( "melee_maggotLeapAttack" );
	setLinearVelocity( jumpVelocity );
	
	playCycle( ANIMCHANNEL_TORSO, "jump_loop" );
	do {
		waitFrame();
	} while( !AI_ONGROUND );
	
	attackEnd();
	playAnim( ANIMCHANNEL_TORSO, "jump_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "leap_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_maggot::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_demon_maggot::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_maggot::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_maggot::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 2 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 );
}

void monster_demon_maggot::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 2 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_maggot::init
=====================
*/
void monster_demon_maggot::init() {
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_maggot::state_Begin
=====================
*/
void monster_demon_maggot::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );	

	monster_begin();

	run_distance	= MAGGOT_RUNDISTANCE;

	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_demon_maggot::state_Idle
=====================
*/
void monster_demon_maggot::state_Idle() {
	wait_for_enemy();

	nextLeap	= RandomTime( MAGGOT_LEAP_RATE );
	nextDodge	= RandomTime( MAGGOT_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_maggot::do_attack
=====================
*/
void monster_demon_maggot::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_LEAP ) {
		combat_leap();
	}
}

/*
=====================
monster_demon_maggot::check_attacks
=====================
*/
float monster_demon_maggot::check_attacks() {
	float range;
	float currentTime;
	float canMelee;
	float attack_flags;
	float checkLeap;
	vector vel;
	float t;
	vector jumpTarget;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}
	
	if ( AI_ENEMY_IN_FOV ) {
		range = enemyRange();
		if ( ( range >= MAGGOT_LEAP_RANGE_MIN ) && ( range < MAGGOT_LEAP_RANGE_MAX ) && ( currentTime >= nextLeap ) ) {
			if ( canHitEnemy() ) {
				t = animLength( ANIMCHANNEL_TORSO, "jump_start" );
				jumpTarget = predictEnemyPos( t );
				jumpVelocity = getJumpVelocity( jumpTarget, MAGGOT_LEAP_SPEED, MAGGOT_LEAP_MAXHEIGHT );
				if ( jumpVelocity != '0 0 0' ) {
					attack_flags |= ATTACK_LEAP;
				} else {
					// check if we can leap again in 2 seconds
					nextLeap = DelayTime( 2 );
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_maggot::combat_leap
=====================
*/
void monster_demon_maggot::combat_leap() {
	stopMove();
	turnToPos( getOrigin() + jumpVelocity );
	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );
	nextLeap = DelayTime( MAGGOT_LEAP_RATE );
}

/*
=====================
monster_demon_maggot::combat_melee
=====================
*/
void monster_demon_maggot::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_maggot::combat_dodge_left
=====================
*/
void monster_demon_maggot::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( MAGGOT_DODGE_RATE );
	moveToEnemy();
}

/*
=====================
monster_demon_maggot::combat_dodge_right
=====================
*/
void monster_demon_maggot::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( MAGGOT_DODGE_RATE );
	moveToEnemy();
}

/*
=====================
monster_demon_maggot::path_jump
=====================
*/
void monster_demon_maggot::path_jump() {
	entity target;
	vector dir;
	vector jumpTarget;

	// walk to the path entity first
	path_corner();

	if ( checkForEnemy( true ) ) {
		return;
	}

	target = current_path.randomPath();
	if ( !target ) {
		sys.error( "missing target for '" + current_path.getName() + "'" );
	}
	jumpTarget = target.getOrigin();
	if ( !current_path.getKey( "up" ) ) {
		jumpVelocity = getJumpVelocity( jumpTarget, MAGGOT_LEAP_SPEED, 1024 );
		if ( jumpVelocity == '0 0 0' ) {
			sys.error( "Monster '" + getName() + "' couldn't make jump from '" + current_path.getName() + "' to '" + target.getName() + "'" );
		}
	} else {
		float forward = current_path.getFloatKey( "forward" );
		if ( forward <= 0 ) {
			sys.error( "Invalid forward velocity on path_jump entity '" + current_path.getName() + "'\n" );
		}
		dir = jumpTarget - getOrigin();
		dir_z = 0;
		dir = sys.vecNormalize( dir );
		dir = dir * forward;
		dir_z = current_path.getFloatKey( "up" );
		jumpVelocity = dir;
	}
	
	stopMove();
	turnToPos( jumpTarget );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}

	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );

	stopMove();
}

//@doomscript-blueprint begin 6
//@source 17C52988
//@catalog 0C260740
//@node 0C43CA53-0 40 40
//@node 7BCBB3B6-0 330 40
//@node 7C354536-0 610 40
//@node 686F67A4-0 890 200
//@node 61E81135-0 685 305
//@node 9EFFA524-0 480 305
//@node CF0BFF55-0 40 40
//@node B6F3556C-0 330 40
//@node 7FF3118C-0 105 145
//@node A2E5C7DC-0 610 40
//@node 509FB528-0 405 232
//@node 3AA0589E-0 890 40
//@node 72F8B233-0 685 145
//@node E0835912-0 1170 40
//@node 8D38B903-0 730 145
//@node 0857E513-0 960 145
//@node ABB6C1B6-0 1450 200
//@node CD835105-0 1245 305
//@node 2FB507E7-0 1730 360
//@node 1D175596-0 1505 465
//@node 1D32D05A-0 2010 360
//@node 856E2BAB-0 1805 465
//@node 0E2B98DC-0 1600 465
//@node F42A891F-0 1600 549
//@node 1314FD59-0 2290 520
//@node 43FC83FB-0 2570 200
//@node CD521520-0 2850 40
//@node 5C88A0F1-0 3130 40
//@node DB8CB1C3-0 40 40
//@node F4843C6D-0 330 40
//@node EBB0E838-0 610 40
//@node 9B1A1F85-0 170 145
//@node FC0E25F5-0 400 145
//@node 65DEA655-0 890 200
//@node 48D84C3F-0 1170 40
//@node 50C46F9F-0 1450 40
//@node A0AE0C8B-0 40 40
//@node E3F898CE-0 330 40
//@node 14021A5B-0 610 40
//@node 855D20E7-0 890 40
//@node 0BD62DC2-0 1170 40
//@node 7460CFE3-0 730 145
//@node 81438D13-0 960 145
//@node 793624A9-0 1450 200
//@node CACED104-0 1730 40
//@node 804DE4DC-0 2010 40
//@node FF1C3DEC-0 1805 140
//@node A89AE44C-0 2290 40
//@node B17AF01C-0 2570 40
//@node 793624A9-1 2850 200
//@node 6CCCE842-0 3130 200
//@node 9C8278F6-0 2925 305
//@node 6256DCE8-0 2720 305
//@node FF6B1608-0 3410 40
//@node 422D58FE-0 3690 40
//@node 18DA5630-0 3970 40
//@node 6BDD4AB8-0 3530 145
//@node 31FC49A8-0 3760 145
//@node 793624A9-2 4250 200
//@node CCD57221-0 4530 40
//@node FC115E23-0 4810 40
//@node 8CCA4273-0 40 40
//@node 7C23BDAA-0 330 40
//@node B0B86C28-0 610 40
//@node A4FFEAAB-0 890 200
//@node 47B9F8F8-0 685 305
//@node 274E0017-0 480 305
//@node 86E1D680-0 480 389
//@node 3477FCDE-0 1170 200
//@node 14487930-0 965 305
//@node 865CB5E8-0 760 305
//@node 69EE94F0-0 40 40
//@node 0A10960B-0 330 40
//@node 5F38F503-0 610 40
//@node CD964396-0 890 200
//@node D5430451-0 685 305
//@node 6F62E42A-0 480 305
//@node F6658C6B-0 480 389
//@node 993CE401-0 1170 200
//@node D1867590-0 965 305
//@node AD7293DA-0 760 305
//@node F3B3F32A-0 40 40
//@node 4654358D-0 330 40
//@node BE17DF46-0 125 232
//@node D9D56FC3-0 -80 232
//@node 037C0837-0 610 40
//@node DF5CBA75-0 890 200
//@node A33DA387-0 685 305
//@node 3E1F04D5-0 480 305
//@node ACB95A22-0 480 389
//@node 9BC8B023-0 1170 200
//@node 21FFA241-0 965 305
//@node FAEC6A8B-0 760 305
//@node D561C251-0 40 40
//@node FFAD0C49-0 330 40
//@node D70EF8B0-0 610 40
//@node 0A2DBFFA-0 170 145
//@node 23974D6A-0 400 145
//@node F61B57EF-0 890 200
//@node 7A012CBF-0 1170 40
//@node 138950CD-0 1450 40
//@node B87FE672-0 40 40
//@node F1034DA7-0 330 40
//@node BDE6D6AB-0 610 40
//@node C6845869-0 170 145
//@node B86036D9-0 400 145
//@node 06DC328E-0 890 200
//@node 20E25850-0 1170 40
//@node 6A987668-0 1450 40
//@node DA46E207-0 40 40
//@node ABED20F5-0 330 40
//@node C06FCA20-0 40 40
//@node DD395B1A-0 330 40
//@node 351F3FDC-0 610 40
//@node A49248F6-0 890 40
//@node 64464200-0 1170 40
//@node 31B76257-0 965 145
//@node AC235E46-0 1450 40
//@node 73A35F2D-0 1730 40
//@node CB2C994D-0 40 40
//@node 9708FB71-0 330 40
//@node 74BDF4F9-0 610 40
//@node 23F6E9D5-0 385 145
//@node 30497731-0 890 40
//@node F2591CFD-0 665 145
//@node 60D67FEE-0 1170 40
//@node 833E955D-0 40 40
//@node FECE9697-0 330 40
//@node C9B76226-0 125 145
//@node 3E7DEF5D-0 610 200
//@node AC7CDABB-0 890 200
//@node 0A8602E8-0 685 305
//@node 57CB5DB8-0 1170 200
//@node 7AB4B354-0 1450 200
//@node 1BC40B8A-0 1245 305
//@node D549498B-0 1730 200
//@node 19493FAD-0 1525 300
//@node 710C7071-0 2010 200
//@node 8D447AF5-0 1805 305
//@node 0A622B56-0 2290 200
//@node CAE73DC3-0 2570 200
//@node 926E8070-0 2365 305
//@node 8C6422F0-0 2850 200
//@node 47730391-0 40 40
//@node 7DC2FE8E-0 330 40
//@node 6D05E12F-0 125 145
//@node 55CB862D-0 610 40
//@node D0D3141E-0 385 145
//@node 80621E4D-0 890 40
//@node E1525812-0 665 145
//@node D184A184-0 1170 40
//@node F77E412E-0 965 145
//@node D22F45F4-0 760 145
//@node 3B495564-0 1450 200
//@node 002CF1E1-0 1245 305
//@node 288899D1-0 1040 305
//@node 947A4146-0 1040 389
//@node 9AB61AB1-0 1040 389
//@node B9B56BF7-0 1730 360
//@node 4A4E9A32-0 1505 465
//@node C5F5805C-0 2010 520
//@node EB7C2316-0 2290 360
//@node 2FC443F0-0 2065 465
//@node 86E16C01-0 2570 520
//@node F2B70907-0 2850 520
//@node 12D5978F-0 2645 625
//@node 3CFFB24A-0 2440 625
//@node 4656D792-0 3130 680
//@node 35BB94E4-0 2925 785
//@node E552B9EB-0 3410 840
//@node 24356D3E-0 3970 840
//@node 0D0693CC-0 4250 200
//@node BD84A231-0 4025 305
//@node 608A0EB8-0 4530 200
//@node E08F5EAE-0 4325 305
//@node C93A0ED4-0 4810 360
//@node E5144277-0 5090 40
//@node 52085DC6-0 4885 145
//@node 925BEFC7-0 5370 200
//@node A31B73B4-0 5650 40
//@node F32FF05D-0 5445 145
//@node D602C327-0 5930 200
//@node 747940E1-0 5705 305
//@node 6EB29B25-0 6210 200
//@node B7835DB7-0 6005 305
//@node B5E74F3D-0 5800 305
//@node 1B1BEA2C-0 5800 389
//@node D8793067-0 5800 473
//@node 8943DDFB-0 6490 360
//@node 2B932122-0 6265 465
//@node 84782279-0 6770 520
//@node F5B5E8AB-0 6545 625
//@node 39E0AB37-0 7050 520
//@node 32660EBE-0 6825 625
//@node B34A8C76-0 6620 725
//@node 05DD52E2-0 7330 520
//@node CA227E41-0 7105 625
//@node 8B77B33F-0 6900 725
//@node 35E4E51E-0 7610 520
//@node 2B98134C-0 7405 625
//@node F0ADB2A9-0 7200 625
//@node 6A754039-0 7890 680
//@node 6EEEEEF2-0 8450 680
//@node 9C4A73E2-0 8225 785
//@node B47F118C-0 8730 40
//@node 06A4CDA0-0 40 40
//@node BDC62125-0 330 40
//@node 2623BAD7-0 610 40
//@node 5F57B3F3-0 405 140
//@node C8A6BEA4-0 200 140
//@node 16281C46-0 890 40
//@node 016BDB66-0 1170 40
//@node 59FCBE22-0 1450 40
//@node A34CB1D0-0 1225 145
//@node A9ECA66E-0 40 40
//@node 36538EA7-0 330 40
//@node DA272C45-0 610 40
//@node 6EBB3F0F-0 890 40
//@node 15F764F0-0 1170 40
//@node 2CF2F0CF-0 1450 40
//@node F40BD937-0 40 40
//@node 466BB1AE-0 330 40
//@node 9F376622-0 610 40
//@node E44B63C1-0 890 40
//@node 81B5E177-0 1170 40
//@node 648733FB-0 1450 40
//@node B8C72008-0 1225 145
//@node 001230C7-0 1730 40
//@node 3E04FC28-0 40 40
//@node C49F7A75-0 330 40
//@node 2EF87427-0 610 40
//@node 4308C1E1-0 890 40
//@node 98B84E04-0 1170 40
//@node 52A317B2-0 1450 40
//@node 0AC064A9-0 1225 145
//@node 7F1143E6-0 1730 40
//@node 823849F3-0 40 40
//@node 0EE54274-0 330 40
//@node A434A1B1-0 610 40
//@node 88FF5E27-0 385 145
//@node 54796828-0 890 200
//@node FE537F09-0 1170 40
//@node B150C270-0 945 145
//@node 8E9AFF85-0 1450 40
//@node 35498E6C-0 1245 145
//@node 39BDD498-0 1040 145
//@node FCCAA773-0 1730 200
//@node 4C526AD2-0 1525 300
//@node 22FE1117-0 1320 300
//@node 9816CFE7-0 1320 378
//@node FB52F1C1-0 2010 40
//@node 85EEFDE7-0 1785 145
//@node 14BF4794-0 2290 40
//@node FB3A6D89-0 1850 145
//@node 223D4B59-0 2080 145
//@node C1E24A19-0 2570 200
//@node 21FEB112-0 2345 305
//@node 95C81422-0 2140 405
//@node 33CDBFC0-0 2850 200
//@node C17B7315-0 2645 305
//@node 47AEC9FE-0 2440 305
//@node A0CA7A51-0 3130 360
//@node D4E311C8-0 2925 460
//@node E57C3E69-0 2720 460
//@node E86E2705-0 2720 538
//@node 6239282B-0 3690 200
//@node 377EFF02-0 3485 305
//@node 41EF9CAE-0 3280 305
//@node 0F2053B0-0 4250 360
//@node 2A7E675C-0 3765 460
//@node E794DCF0-0 3560 460
//@node 72A37CCA-0 3560 538
//@node 9D6A0F66-0 3560 616
//@node FA1A7670-0 4250 200
//@node 9F8D7BBC-0 4025 305
//@node E6ECD832-0 4530 200
//@node 9DF93887-0 4325 305
//@node C5125009-0 4810 200
//@node 5AED07EB-0 4585 305
//@node 2731AEB5-0 4380 405
//@node F585A6CD-0 5090 200
//@node 3CB68C96-0 4885 305
//@node 50B1E5D0-0 4680 305
//@node 332E252E-0 4680 389
//@node 1A161F8E-0 5370 200
//@node 571A1937-0 5145 305
//@node EE65F2D4-0 5650 200
//@node 3FEA7259-0 5445 305
//@node 56467F2A-0 6210 40
//@node DD650950-0 6490 40
//@node 4EDAD911-0 6005 140
//@node 2BFADCE0-0 6490 40
//@node E9526119-0 6050 145
//@node F3A34849-0 6280 145
//@node A434A1B1-1 6770 200
//@node 3CB55A14-0 6545 305
//@node 54796828-1 7330 360
//@node 499B8DC1-0 7610 200
//@node EE7FAABB-0 7890 40
//@node F12FF5BB-0 8170 40
//@node 56467F2A-1 8450 40
//@doomscript-blueprint end
