/***********************************************************************

ai_monster_zombie_commando_cgun.script

monster_zombie_commando_cgun

***********************************************************************/

#define ZOMBIE_CGUN_RUNDISTANCE					192
#define ZOMBIE_CGUN_WALKTURN					65
#define ZOMBIE_CGUN_DODGE_RATE					3
#define ZOMBIE_CGUN_ATTACK_DELAY_MIN			0.5
#define ZOMBIE_CGUN_ATTACK_DELAY_MAX			2
#define ZOMBIE_CGUN_ATTACK_MAX_LENGTH			2.5
#define ZOMBIE_CGUN_ATTACK_MIN_LENGTH			1
#define ZOMBIE_CGUN_WAIT_MIN_LENGTH				0.3
#define ZOMBIE_CGUN_WAIT_MAX_LENGTH				1.5
#define ZOMBIE_CGUN_CROUCH_ATTACK_MAX_LENGTH	15
#define ZOMBIE_CGUN_CROUCH_ATTACK_MIN_LENGTH	3
#define ZOMBIE_CGUN_STAND_ATTACK_MAX_LENGTH		15
#define ZOMBIE_CGUN_STAND_ATTACK_MIN_LENGTH		3
#define ZOMBIE_CGUN_MIN_SHOT_TIME				0.5
#define ZOMBIE_CGUN_NOFOVTIME					4

#define ATTACK_ZCC_CROUCHFIRE					ATTACK_SPECIAL1

object monster_zombie_commando_cgun : monster_base {
	boolean		fire;
	boolean		crouch_fire;
	boolean		step_left;
	boolean		step_right;
	float		nextDodge;
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;

	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		crouch_attack();
	void		stand_attack();
	void		combat_dodge_left();
	void		combat_dodge_right();
	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_RangeAttack();
	void		Torso_CrouchAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
	void		Legs_StepLeft();
	void		Legs_StepRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_zombie_commando_cgun::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "range_attack_aim" );
	
	eachFrame {
		if ( AI_PAIN ) {
			Torso_Pain();
			idleAnim( ANIMCHANNEL_TORSO, "range_attack_aim" );
		}
		if ( fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 8 );
		}
		if ( crouch_fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_CrouchAttack", 8 );
		}
	}
}

void monster_zombie_commando_cgun::Torso_Pain() {
	string animname;

	animname = getPainAnim();
	setBlendFrames( ANIMCHANNEL_TORSO, 3 );
	playAnim( ANIMCHANNEL_TORSO, animname );

	while( !animDone( ANIMCHANNEL_TORSO, 12 ) ) {
		waitFrame();
	}

	preventPain( 0.6 );
	
	finishAction( "pain" );
	setBlendFrames( ANIMCHANNEL_TORSO, 12 );
}

void monster_zombie_commando_cgun::Torso_RangeAttack() {
	float endtime;
	float mintime;
	
	setAnimPrefix( "" );
		
	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 12 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	mintime = sys.getTime() + ZOMBIE_CGUN_MIN_SHOT_TIME;
	while( fire || ( sys.getTime() < mintime ) ) {
		playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
		while( ( fire || ( sys.getTime() < mintime ) ) && !animDone( ANIMCHANNEL_TORSO, 12 ) ) {
			if ( sys.influenceActive() ) {
				fire = false;
				mintime = 0;
				break;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	if ( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		setBlendFrames( ANIMCHANNEL_TORSO, 8 );
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 12 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 12 );
}

void monster_zombie_commando_cgun::Torso_TurretAttack() {
	float endtime;
	
	setAnimPrefix( "" );

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	endtime = RandomDelay( ZOMBIE_CGUN_ATTACK_MIN_LENGTH, ZOMBIE_CGUN_ATTACK_MAX_LENGTH );
	while( ( sys.getTime() < endtime ) && canHitEnemyFromAnim( "range_attack_loop" ) ) {
		playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
		while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
			if ( sys.influenceActive() ) {
				endtime = 0;
				break;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	if ( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		setBlendFrames( ANIMCHANNEL_TORSO, 8 );
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}

	finishAction( "turret_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

void monster_zombie_commando_cgun::Torso_CrouchAttack() {
	float endtime;
	float mintime;
	
	overrideAnim( ANIMCHANNEL_LEGS );
	
	setAnimPrefix( "crouch" );

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	mintime = sys.getTime() + ZOMBIE_CGUN_MIN_SHOT_TIME;
	while( crouch_fire || ( sys.getTime() < mintime ) ) {
		endtime = RandomDelay( ZOMBIE_CGUN_ATTACK_MIN_LENGTH, ZOMBIE_CGUN_ATTACK_MAX_LENGTH );
		while( ( crouch_fire || ( sys.getTime() < mintime ) ) && ( sys.getTime() < endtime ) ) {
			playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
			while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
				if ( sys.influenceActive() ) {
					crouch_fire = false;
					endtime = 0;
					break;
				}

				if ( AI_PAIN ) {
					Torso_Pain();
				}
				waitFrame();
			}
		}

		if ( !crouch_fire ) {
			break;
		}

		playCycle( ANIMCHANNEL_TORSO, "range_attack_aim" );
		endtime = RandomDelay( ZOMBIE_CGUN_WAIT_MIN_LENGTH, ZOMBIE_CGUN_WAIT_MAX_LENGTH );
		while( crouch_fire && ( sys.getTime() < endtime ) ) {
			if ( sys.influenceActive() ) {
				crouch_fire = false;
				endtime = 0;
				break;
			}
			if ( AI_PAIN ) {
				Torso_Pain();
			}
			waitFrame();
		}
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		if ( AI_PAIN ) {
			Torso_Pain();
		}
		waitFrame();
	}
	
	finishAction( "crouch_attack" );
	setAnimPrefix( "" );
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_zombie_commando_cgun::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "range_attack_aim" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
		if ( step_left )			{ animState( ANIMCHANNEL_LEGS, "Legs_StepLeft", 8 ); }
		if ( step_right )			{ animState( ANIMCHANNEL_LEGS, "Legs_StepRight", 8 ); }
	}
}

void monster_zombie_commando_cgun::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void monster_zombie_commando_cgun::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void monster_zombie_commando_cgun::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void monster_zombie_commando_cgun::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void monster_zombie_commando_cgun::Legs_StepLeft() {
	playAnim( ANIMCHANNEL_LEGS, "step_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}
	
	step_left = false;
	finishAction( "sidestep" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void monster_zombie_commando_cgun::Legs_StepRight() {
	playAnim( ANIMCHANNEL_LEGS, "step_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 8 ) ) {
		waitFrame();
	}

	step_right = false;
	finishAction( "sidestep" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_zombie_commando_cgun::init
=====================
*/
void monster_zombie_commando_cgun::init() {
	run_distance	= ZOMBIE_CGUN_RUNDISTANCE;
	walk_turn		= ZOMBIE_CGUN_WALKTURN;
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_zombie_commando_cgun::state_Begin
=====================
*/
void monster_zombie_commando_cgun::state_Begin() {
	fire = false;
	crouch_fire = false;
	step_left = false;
	step_right = false;	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_zombie_commando_cgun::state_Idle
=====================
*/
void monster_zombie_commando_cgun::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;
	nextDodge		= RandomTime( ZOMBIE_CGUN_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_zombie_commando_cgun::do_attack
=====================
*/
void monster_zombie_commando_cgun::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + ZOMBIE_CGUN_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MISSILE ) {
		stand_attack();
	} else if ( attack_flags & ATTACK_ZCC_CROUCHFIRE ) {
		crouch_attack();
	}
}

/*
=====================
monster_zombie_commando_cgun::check_attacks
=====================
*/
float monster_zombie_commando_cgun::check_attacks() {
	float currentTime;
	float attack_flags;
	boolean try_attack;
	boolean reachable;

	attack_flags = 0;
	
	currentTime = sys.getTime();
	if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
		if ( testAnimMove( "evade_left" ) ) {
			attack_flags |= ATTACK_DODGE_LEFT;
		}
		if ( testAnimMove( "evade_right" ) ) {
			attack_flags |= ATTACK_DODGE_RIGHT;
			
			// if we can dodge either direction, pick one
			if ( attack_flags & ATTACK_DODGE_LEFT ) {
				if ( sys.random( 100 ) < 50 ) {
					attack_flags &= ~ATTACK_DODGE_RIGHT;
				} else {
					attack_flags &= ~ATTACK_DODGE_LEFT;
				}
			}
		}
	}
	
	combat_node = getCombatNode();
	if ( combat_node ) {
		attack_flags |= ATTACK_COMBAT_NODE;
	}

    reachable = canReachEnemy();
	if ( AI_ENEMY_IN_FOV && ( !reachable || ( currentTime >= nextAttack ) ) ) {
		try_attack = true;
	} else if ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE && ( !reachable || ( currentTime >= nextAttack ) ) ) {
		try_attack = true;
	} else if ( touches( getEnemy() ) ) {
		try_attack = true;
	} else {
		try_attack = false;
	}

	if ( try_attack ) {
		if ( sys.random( 1 ) < 0.5 ) {
			if ( canHitEnemyFromAnim( "crouch_range_attack_loop" ) ) {
				attack_flags |= ATTACK_ZCC_CROUCHFIRE;
			} else if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		} else if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
			attack_flags |= ATTACK_MISSILE;
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_zombie_commando_cgun::stand_attack
=====================
*/
void monster_zombie_commando_cgun::stand_attack() {
	float attackTime;
	float endtime;
	float attack_flags;

	faceEnemy();

	attackTime = RandomDelay( ZOMBIE_CGUN_STAND_ATTACK_MIN_LENGTH, ZOMBIE_CGUN_STAND_ATTACK_MAX_LENGTH );
	while( AI_ENEMY_VISIBLE && !sys.influenceActive() ) {
		fire = true;
		endtime = RandomDelay( 2, 5 );
		while( sys.getTime() < endtime ) {
			if ( sys.influenceActive() ) {
				break;
			}

			if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
				break;
			}
			if ( AI_PAIN ) {
				attack_flags = check_attacks();
				if ( attack_flags & ( ATTACK_DODGE_LEFT | ATTACK_DODGE_RIGHT ) ) {
					fire = false;
					do_attack( attack_flags );
					return;
				}
			}
			
			waitFrame();
		}

		fire = false;
		while( !inAnimState( ANIMCHANNEL_TORSO, "Torso_Idle" ) ) {
			lookAtEnemy( 1 );
			waitFrame();
		}

		if ( sys.influenceActive() ) {
			break;
		}
		
		if ( sys.getTime() > attackTime ) {
			break;
		}

		if ( !AI_ENEMY_VISIBLE || !canHitEnemyFromAnim( "range_attack_loop" ) ) {
			break;
		}
		
		step_left = testAnimMove( "step_left" );
		step_right = testAnimMove( "step_right" );
		if ( step_left && step_right ) {
			if ( sys.random( 100 ) < 50 ) {
				step_left = false;
			} else {
				step_right = false;
			}
		}
		
		while( step_left || step_right ) {
			lookAtEnemy( 1 );
			waitFrame();
		}
	}
	
	fire = false;
	while( !inAnimState( ANIMCHANNEL_TORSO, "Torso_Idle" ) ) {
		waitFrame();
	}

	// don't attack for a bit
	nextAttack = RandomDelay( ZOMBIE_CGUN_ATTACK_DELAY_MIN, ZOMBIE_CGUN_ATTACK_DELAY_MAX );
	nextNoFOVAttack = sys.getTime() + ZOMBIE_CGUN_NOFOVTIME;
}
	
/*
=====================
monster_zombie_commando_cgun::crouch_attack
=====================
*/
void monster_zombie_commando_cgun::crouch_attack() {
	float attackTime;
	float attack_flags;

	faceEnemy();
	crouch_fire = true;
	
	attackTime = RandomDelay( ZOMBIE_CGUN_CROUCH_ATTACK_MIN_LENGTH, ZOMBIE_CGUN_CROUCH_ATTACK_MAX_LENGTH );
	while( AI_ENEMY_VISIBLE ) {
		if ( sys.influenceActive() ) {
			break;
		}
		if ( sys.getTime() > attackTime ) {
			break;
		}
		if ( AI_PAIN ) {
			attack_flags = check_attacks();
			if ( attack_flags & ( ATTACK_DODGE_LEFT | ATTACK_DODGE_RIGHT ) ) {
				crouch_fire = false;
				setAnimPrefix( "" );
				do_attack( attack_flags );
				return;
			}
		}
		
		lookAtEnemy( 1 );
		if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
			break;
		}
		waitFrame();
	}
	
	crouch_fire = false;
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_CrouchAttack" ) ) {
		waitFrame();
	}

	// don't attack for a bit
	nextAttack = RandomDelay( ZOMBIE_CGUN_ATTACK_DELAY_MIN, ZOMBIE_CGUN_ATTACK_DELAY_MAX );
	nextNoFOVAttack = sys.getTime() + ZOMBIE_CGUN_NOFOVTIME;
}

/*
=====================
monster_zombie_commando_cgun::combat_dodge_left
=====================
*/
void monster_zombie_commando_cgun::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 8 );
	waitAction( "strafe" );
	nextDodge = DelayTime( ZOMBIE_CGUN_DODGE_RATE );
}

/*
=====================
monster_zombie_commando_cgun::combat_dodge_right
=====================
*/
void monster_zombie_commando_cgun::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 8 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( ZOMBIE_CGUN_DODGE_RATE );
}

//@doomscript-blueprint begin 6
//@source 108BE85E
//@catalog 0C260740
//@node 66857B03-0 40 40
//@node 4A01D894-0 330 40
//@node B093547A-0 610 40
//@node 22C19A80-0 890 200
//@node 30AE6BFE-0 685 305
//@node 9507C835-0 1170 360
//@node 4A01D894-1 1450 360
//@node 89E837C3-0 1730 200
//@node 120F1ABB-0 1525 305
//@node 237F2C64-0 2010 360
//@node 3CC20538-0 2290 200
//@node 2FA489A3-0 2085 305
//@node FF6E93B7-0 2570 360
//@node 502CE265-0 40 40
//@node 59186038-0 330 40
//@node C6704D18-0 105 145
//@node C1D7B89B-0 610 40
//@node EE474C1C-0 890 40
//@node 30FE24B4-0 685 232
//@node DFF98C81-0 1170 40
//@node 602EDE8F-0 730 145
//@node 3D6DC07F-0 960 145
//@node 261A243B-0 1450 200
//@node 600FD575-0 1730 40
//@node C137D160-0 2010 40
//@node 7C6C771D-0 2290 40
//@node E491EA2E-0 40 40
//@node 3364A9FB-0 330 40
//@node C529E4BD-0 610 40
//@node 2F5D03C6-0 890 40
//@node A7194F5A-0 450 145
//@node 8D9A970A-0 680 145
//@node 4D055E5B-0 1170 200
//@node 6942BB47-0 965 305
//@node E56486E8-0 1450 360
//@node 4CA6C496-0 1730 200
//@node 2FE6E7A6-0 2010 40
//@node 9DE4573D-0 1805 145
//@node 4BF99EE1-0 2290 40
//@node D7FABF2F-0 2085 145
//@node F41F513C-0 1880 145
//@node D7517FA7-0 1880 229
//@node E86E2BCC-0 2570 200
//@node FBCB3FD0-0 2850 200
//@node 3604B5CD-0 2645 305
//@node 944E1507-0 2440 305
//@node 1D1EE87E-0 2440 389
//@node D9FDD079-0 3130 360
//@node 38D94E48-0 2905 465
//@node F301B650-0 3410 520
//@node 267F8BCC-0 3205 625
//@node 124D12B8-0 3690 520
//@node 0B4A0D18-0 3485 625
//@node A5F45F4F-0 3970 520
//@node 4D055E5B-1 4250 360
//@node 0899AD0C-0 4045 465
//@node E56486E8-1 4530 520
//@node 4CA6C496-1 4810 360
//@node 25AEAC01-0 5090 40
//@node D3C91FE9-0 4650 145
//@node 88A1FB39-0 4880 145
//@node D87006CF-0 5370 200
//@node 8A5A5D6B-0 5650 40
//@node 2F5D03C6-1 5930 40
//@node 779D3BBF-0 5490 145
//@node F8516F2F-0 5720 145
//@node 4D055E5B-2 6210 200
//@node 734D6605-0 6005 305
//@node E56486E8-2 6490 360
//@node 4CA6C496-2 6770 200
//@node A272E331-0 7050 40
//@node 9AB09945-0 7330 40
//@node BC31D68F-0 40 40
//@node 4833EE08-0 330 40
//@node 4B49EB7A-0 610 40
//@node 9723F268-0 890 40
//@node 55D70FF9-0 450 145
//@node 82B9BE49-0 680 145
//@node BE18A8E4-0 1170 200
//@node 969D6E60-0 965 305
//@node 85E00F49-0 1450 360
//@node EC05B3ED-0 1730 200
//@node 91985681-0 2010 40
//@node ED6AD1D4-0 1785 145
//@node 7335880F-0 2290 40
//@node D59AAC5A-0 2085 145
//@node 5E734247-0 1880 145
//@node C7B5A665-0 2570 200
//@node 9723F268-1 2850 200
//@node C81090FC-0 2410 305
//@node D5BFBF8C-0 2640 305
//@node 1A0BAD22-0 3130 360
//@node 4261116D-0 2905 465
//@node F73E990E-0 3410 520
//@node D74A74FD-0 3205 625
//@node C070C322-0 3690 520
//@node BE18A8E4-1 3970 360
//@node 4F133FCB-0 3765 465
//@node 85E00F49-1 4250 520
//@node EC05B3ED-1 4530 360
//@node FF863802-0 4810 40
//@node C64EAB47-0 4370 145
//@node 98A4C737-0 4600 145
//@node 039B1E22-0 5090 200
//@node 25F0125C-0 5370 40
//@node 9723F268-2 5650 40
//@node 7EDED537-0 5210 145
//@node 51C9F287-0 5440 145
//@node BE18A8E4-2 5930 200
//@node 60DBB556-0 5725 305
//@node 85E00F49-2 6210 360
//@node EC05B3ED-2 6490 200
//@node AD8D1825-0 6770 40
//@node 04A4BD23-0 7050 40
//@node 4E7A00C3-0 40 40
//@node 5D470986-0 330 40
//@node 1BBE255A-0 610 40
//@node 1417EB36-0 890 40
//@node 5C1ED7EC-0 1170 40
//@node C25EC557-0 730 145
//@node D11EC907-0 960 145
//@node 9CE05F68-0 1450 200
//@node 129AB6D0-0 1245 305
//@node 0C501645-0 1730 360
//@node DCB73671-0 2010 200
//@node 62584013-0 2290 40
//@node B761491F-0 2085 145
//@node 2EC14C77-0 2570 40
//@node 5592178C-0 2365 145
//@node 7BEC16BC-0 2160 145
//@node 9142CAFE-0 2160 229
//@node 464AF52D-0 2850 200
//@node 5B0BDE35-0 2625 305
//@node 65467488-0 3130 200
//@node 13EDBF95-0 2925 305
//@node BB9D2533-0 2720 305
//@node D7313EEE-0 2720 389
//@node F3C2D408-0 2720 473
//@node B14E6AD9-0 3410 360
//@node 5C1ED7EC-1 3690 360
//@node 8F353FD2-0 3250 465
//@node D0CC0142-0 3480 465
//@node 0FC1C50E-0 3970 520
//@node EAD55209-0 3745 625
//@node 4A1AB362-0 4250 680
//@node CF6B1286-0 4045 785
//@node 59559892-0 4530 680
//@node 158A7431-0 4325 785
//@node 06F80986-0 4810 680
//@node 9CE05F68-1 5090 520
//@node 535900FB-0 4885 625
//@node 0C501645-1 5370 680
//@node DCB73671-1 5650 520
//@node B662AF05-0 5930 200
//@node 4C9F6F8A-0 5725 305
//@node 215566FC-0 5520 305
//@node 06F80986-1 6210 360
//@node 0723BB41-0 6490 200
//@node 06050F6F-0 6770 200
//@node 074A43BC-0 6545 305
//@node E50234EE-0 7050 200
//@node 9E149F1C-0 6845 305
//@node 5ADD43FE-0 6640 305
//@node 0CD40C29-0 6640 389
//@node 0FC1C50E-1 7330 360
//@node DE87E856-0 7105 465
//@node 4A1AB362-1 7610 520
//@node 2FCE141D-0 7405 625
//@node 59559892-1 7890 520
//@node A706AEEE-0 7685 625
//@node 06F80986-2 8170 520
//@node 9CE05F68-2 8450 360
//@node A1D966C6-0 8245 465
//@node 0C501645-2 8730 520
//@node DCB73671-2 9010 360
//@node 01E6EAA8-0 9290 40
//@node 5C1ED7EC-2 9570 40
//@node 55FC5019-0 9130 145
//@node 020E94C9-0 9360 145
//@node 9CE05F68-3 9850 200
//@node D0D08559-0 9645 305
//@node 0C501645-3 10130 360
//@node DCB73671-3 10410 200
//@node F36F0ACD-0 10690 40
//@node 47DCB934-0 10970 40
//@node B996C66F-0 11250 40
//@node EF419203-0 40 40
//@node AD25F7B0-0 330 40
//@node A1F8DB84-0 610 40
//@node 29098ADF-0 890 200
//@node 70AF9189-0 685 305
//@node B4D97F9E-0 480 305
//@node 3D430DAF-0 480 389
//@node AD2A47F2-0 1170 200
//@node 019C2480-0 965 305
//@node 9E736B34-0 760 305
//@node DE53F3FE-0 1450 200
//@node 3D3B8D06-0 1245 305
//@node B4C597BA-0 1040 305
//@node C23FAD3A-0 1730 200
//@node 8A9E85B2-0 1525 305
//@node 4B29C5AF-0 1320 305
//@node D3839360-0 40 40
//@node F903DE4B-0 330 40
//@node C6A313B7-0 610 40
//@node EF70E49A-0 890 200
//@node 215C5AAA-0 685 305
//@node C8BFABDD-0 480 305
//@node 04F0CA5A-0 480 389
//@node CC65B9F5-0 1170 200
//@node B222E3D5-0 965 305
//@node 5479C815-0 760 305
//@node F388ADDA-0 40 40
//@node 397989CD-0 330 40
//@node ECC92FE1-0 125 232
//@node B23DA0D4-0 -80 232
//@node 7AB669C3-0 610 40
//@node 0FAFC9A1-0 890 200
//@node 89ACF64B-0 685 305
//@node 7C48EAD1-0 480 305
//@node 4D212EDE-0 480 389
//@node 573F6697-0 1170 200
//@node 7E31EBD9-0 965 305
//@node FEEDBCC3-0 760 305
//@node 75500DA1-0 40 40
//@node DA041189-0 330 40
//@node F08F5C4E-0 610 40
//@node 59E99441-0 170 145
//@node 6D9180F1-0 400 145
//@node 0D3AF02F-0 890 200
//@node 41DBA7FF-0 1170 40
//@node 8C9A01EB-0 1450 40
//@node 302AC5C2-0 40 40
//@node FAABCDE7-0 330 40
//@node ED2189D9-0 610 40
//@node 542FBE71-0 170 145
//@node 085E18C1-0 400 145
//@node 8F0803CE-0 890 200
//@node 400F4A90-0 1170 40
//@node 375F1FBE-0 1450 40
//@node 8D3CDA96-0 40 40
//@node 2C57AAD9-0 330 40
//@node 0521E8CE-0 125 232
//@node E65F2A2F-0 -80 232
//@node 33A94805-0 610 40
//@node 8867CA5C-0 170 145
//@node F003A66C-0 400 145
//@node E65A73AA-0 890 200
//@node 1366E634-0 1170 40
//@node 94579F49-0 965 145
//@node 8B194A5A-0 1450 40
//@node 0F647AB2-0 1730 40
//@node E625E74B-0 40 40
//@node D05D027B-0 330 40
//@node 9484A8D0-0 125 232
//@node B97B5B47-0 -80 232
//@node 98AF3394-0 610 40
//@node AC46790D-0 170 145
//@node EAE7D3BD-0 400 145
//@node D2CE4B15-0 890 200
//@node 2210DF6E-0 1170 40
//@node 4CFFA2EA-0 965 145
//@node CC7FD5B7-0 1450 40
//@node 125C8115-0 1730 40
//@node 9C5C4BD7-0 40 40
//@node DE527530-0 330 40
//@node F7C2FA44-0 125 145
//@node DE94B182-0 610 40
//@node 6306540E-0 405 145
//@node 0F908C35-0 890 40
//@node 07B0CE70-0 40 40
//@node F9C2CBFE-0 330 40
//@node 383BDBD3-0 125 145
//@node 8A177895-0 610 40
//@node 41D75A85-0 405 145
//@node BB1B91A6-0 890 40
//@node BBE42929-0 685 145
//@node CE74721F-0 1170 40
//@node 02AE3C9A-0 965 145
//@node 29CF5752-0 1450 40
//@node E9B900D4-0 1730 40
//@node 169B8836-0 2010 40
//@node 68264186-0 2290 40
//@node 8707366D-0 2570 40
//@node 6258CF3D-0 40 40
//@node 650C37B1-0 330 40
//@node 86D7898B-0 610 40
//@node F84483F7-0 405 145
//@node D5D6F20B-0 890 40
//@node 9941CD22-0 685 145
//@node 34F80F56-0 1170 40
//@node 88CE36D3-0 945 145
//@node 29B1662E-0 1450 40
//@node 027231CD-0 40 40
//@node CD967213-0 330 40
//@node 1EC45071-0 125 145
//@node 27D59B5F-0 610 40
//@node BE6F4B40-0 405 145
//@node 5C61A69D-0 890 200
//@node 67205CA3-0 1170 200
//@node DAA64E40-0 965 305
//@node 392D55F8-0 1450 200
//@node 5D36724C-0 1730 200
//@node 2B9F36D2-0 1525 305
//@node 233066CB-0 2010 200
//@node 5AC0BC99-0 1805 300
//@node 681E0CAD-0 2290 200
//@node 2319EB8B-0 2085 305
//@node 2A574C5C-0 2570 200
//@node AD70462E-0 2850 200
//@node 71915B55-0 2645 305
//@node 4D8BA2E4-0 3130 200
//@node 844E9F61-0 40 40
//@node AC82A932-0 330 40
//@node DA7CD4F6-0 125 145
//@node 9510A819-0 610 40
//@node B8E0B758-0 385 145
//@node 1B7B542C-0 890 40
//@node A00F3DC3-0 685 145
//@node F181631B-0 480 145
//@node 47C8EF90-0 480 229
//@node A1DEC607-0 480 229
//@node 4F3696BF-0 1170 200
//@node 915BA207-0 945 305
//@node E6D08E50-0 1450 360
//@node B74D30FE-0 1730 200
//@node 33FDF688-0 1505 305
//@node 413A971D-0 2010 360
//@node 529EF01F-0 2290 360
//@node 0D782C7C-0 2085 465
//@node 804EE799-0 1880 465
//@node A457740A-0 2570 520
//@node 26CAC152-0 2365 625
//@node 493BAF47-0 2850 680
//@node D8B5DD62-0 3410 680
//@node 6896AB38-0 3690 40
//@node 00B25950-0 3465 145
//@node C453BBF0-0 3970 40
//@node DE405843-0 3765 145
//@node 8F535EA0-0 4250 200
//@node E11D7847-0 4530 40
//@node 31AA4513-0 4305 145
//@node EFFAFD5A-0 4810 40
//@node D19C1B77-0 4605 145
//@node B548C37D-0 4400 145
//@node F3C46266-0 4400 229
//@node FCB30308-0 4400 313
//@node 9853A486-0 4400 313
//@node B4266126-0 5090 200
//@node CE8692B8-0 4885 305
//@node 8118A735-0 5370 200
//@node 092C9AEB-0 5165 305
//@node D94B1879-0 4960 305
//@node 1180C182-0 4960 389
//@node 4433AE37-0 4960 473
//@node CD0F674A-0 4960 473
//@node 64712E40-0 4960 557
//@node B4266126-1 5650 200
//@node CFC62451-0 5445 305
//@node CD3EF21F-0 5930 200
//@node 2CF5838A-0 5705 305
//@node B4266126-2 6210 200
//@node 08B4EAE6-0 6005 305
//@node B129499D-0 6770 200
//@node 218FB662-0 6565 305
//@node 1C22C523-0 7050 40
//@node 70544EC6-0 6845 145
//@node 73EBAD22-0 7330 200
//@node 4300858D-0 7125 305
//@node AFDDFE2E-0 7610 360
//@node B3E1C502-0 7385 465
//@node 4FBF55D2-0 7890 520
//@node 33CD24B2-0 8170 520
//@node 47400B8A-0 7945 625
//@node 196F62F7-0 8450 520
//@node 33CD24B2-1 8730 360
//@node 28933A05-0 8505 465
//@node 196F62F7-1 9010 360
//@node BE8FC9D4-0 9290 40
//@node 95552FA4-0 40 40
//@node 084AC35B-0 330 40
//@node FFC63E9F-0 610 40
//@node 2C516EBC-0 385 145
//@node 60B1541E-0 890 40
//@node 4777C609-0 665 145
//@node 6ADC1D4D-0 1170 200
//@node 69EC5F45-0 965 305
//@node 878FE5AB-0 1450 200
//@node A5CCB460-0 1225 305
//@node F63B06A9-0 1730 200
//@node E7A456F9-0 1525 305
//@node 83842D17-0 1320 305
//@node 5A09375B-0 2010 360
//@node 6C1719F1-0 1785 465
//@node 3EAFD143-0 2290 520
//@node 26C3A019-0 2570 360
//@node 56E57331-0 2130 465
//@node 27784861-0 2360 465
//@node 3EAFD143-1 2850 520
//@node FD012CA9-0 3130 360
//@node A4504E55-0 2925 465
//@node B4CA2B66-0 3410 520
//@node 4248090C-0 3185 625
//@node CB601C52-0 3690 520
//@node AA11F8B1-0 3485 625
//@node DFECE542-0 3280 625
//@node E2DB5164-0 3970 680
//@node 3A6ADC10-0 3765 785
//@node 2C129A10-0 4250 680
//@node 0342AA3D-0 4045 780
//@node 38044333-0 4530 680
//@node FF033C78-0 4810 360
//@node E2DB5164-1 5090 200
//@node 4774BD27-0 4885 305
//@node 8DB95B6F-0 5370 200
//@node 02F12AB9-0 4930 305
//@node 810308E9-0 5160 305
//@node 68A76375-0 5650 360
//@node FF033C78-1 5930 360
//@node 5A09375B-1 6210 200
//@node 3A51C87E-0 5985 305
//@node 3EAFD143-2 6490 360
//@node 290802B0-0 6770 200
//@node 68A3CE98-0 6565 305
//@node 9ACA0E38-0 6360 305
//@node 3EAFD143-3 7050 360
//@node 571DBA32-0 7330 200
//@node 645E34AD-0 6890 305
//@node 5BC4A3FD-0 7120 305
//@node 3EAFD143-4 7610 360
//@node 97B55306-0 7890 200
//@node CD489805-0 7665 305
//@node FA94B8A0-0 7460 405
//@node D304C80F-0 7255 405
//@node E655CE94-0 8170 200
//@node 689E866C-0 7945 305
//@node 5124A4C3-0 7740 405
//@node FF9017B4-0 7535 405
//@node F12A14E3-0 8450 200
//@node 16B1AA35-0 8245 305
//@node FBD052C1-0 8040 305
//@node E563E762-0 8040 389
//@node ECCA4F1B-0 8730 360
//@node 1C37761B-0 8525 465
//@node C854EA4C-0 9010 520
//@node 11B19C30-0 8805 625
//@node 836B5475-0 9570 520
//@node 5250CFC1-0 9365 625
//@node 6963CB09-0 9850 200
//@node CD2F7E14-0 9645 305
//@node 7E8A4C74-0 9440 305
//@node 3FA19321-0 9440 389
//@node 68A76375-1 10130 360
//@node FF033C78-2 10410 360
//@node E2DB5164-2 10690 40
//@node B9B3E4BE-0 10485 145
//@node 8DB95B6F-1 10970 40
//@node 58055492-0 10530 145
//@node CEA3F942-0 10760 145
//@node FF033C78-3 11250 200
//@node 7E760D9F-0 11530 40
//@node 7CD1484C-0 11305 145
//@node 2EAC64BE-0 11810 40
//@node 84A33A95-0 11605 145
//@node 6DDF0B0C-0 40 40
//@node C8DAD937-0 330 40
//@node 76C5595E-0 610 40
//@node 59026883-0 405 145
//@node 279FFB7D-0 890 40
//@node B851859B-0 665 145
//@node 3345DE2A-0 1170 40
//@node 1C49207D-0 965 145
//@node 84E76487-0 1450 200
//@node B8AE63BC-0 1225 305
//@node 955B8265-0 1730 360
//@node 9150C254-0 2010 200
//@node 7A97276A-0 1805 305
//@node A7991630-0 1600 305
//@node 955B8265-1 2290 360
//@node 8836CDFD-0 2570 200
//@node 02DD086F-0 2365 305
//@node AE47D084-0 2850 360
//@node 76A531EF-0 2625 465
//@node AECF3816-0 3130 360
//@node F22CD24A-0 2925 465
//@node 46D0144D-0 2720 465
//@node AB7E0135-0 3410 520
//@node CA0BC903-0 3205 625
//@node E4E147F5-0 3690 520
//@node F3C72034-0 3970 520
//@node F5C42CC2-0 3765 620
//@node 1F316CBB-0 4250 520
//@node 1F4495F9-0 4530 200
//@node 5111E665-0 4810 200
//@node CFC21FF8-0 4370 305
//@node D905E3E8-0 4600 305
//@node 955B8265-2 5090 360
//@node 63085B0C-0 5370 200
//@node AB7E0135-1 5650 40
//@node E0FFB8DC-0 5445 145
//@node 51258B32-0 5930 40
//@node 10EAA0C5-0 5705 145
//@node 63085B0C-1 6210 200
//@node C74445D5-0 6490 40
//@node 2D981596-0 6265 145
//@node 9E098574-0 6770 40
//@node 140EAD6E-0 6565 145
//@node B31B9007-0 40 40
//@node 815DC4EE-0 330 40
//@node 06083362-0 610 40
//@node 2CFECE9F-0 890 40
//@node A96050B7-0 1170 40
//@node C9A24734-0 1450 40
//@node 1CFBA3A8-0 1225 145
//@node 64EA8D38-0 40 40
//@node 5BAB67B5-0 330 40
//@node F767AE67-0 610 40
//@node 64998E3F-0 890 40
//@node DAD45A44-0 1170 40
//@node F6713533-0 1450 40
//@node DE78F7DC-0 1225 145
//@doomscript-blueprint end
