/***********************************************************************

ai_monster_zombie.script

monster_zombie_chainsaw
monster_zombie_jumpsuit
monster_zombie_morgue
monster_zombie_civilian
monster_zombie_scientist1
monster_zombie_scientist2
monster_zombie_scientist3
monster_zombie_maint
monster_zombie_fat
monster_zombie_fat2
monster_zombie_fat3
monster_zombie_zfem

***********************************************************************/

#define ZOMBIE_RUNDISTANCE		192
#define ZOMBIE_WALKTURN			65

object monster_zombie : monster_zombie_base {
	boolean		can_run;

	void		state_Begin();
	void		state_Idle();
	void		combat_melee();
	void		init();
		
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_zombie::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
}

void monster_zombie::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 8 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

void monster_zombie::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_zombie::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( can_run && run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( AI_FORWARD )					{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
	}
}

void monster_zombie::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( can_run && run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
		if ( !AI_FORWARD )					{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void monster_zombie::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 8 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_zombie::init
=====================
*/
void monster_zombie::init() {
	run_distance	= ZOMBIE_RUNDISTANCE;
	walk_turn		= ZOMBIE_WALKTURN;

	can_run = hasAnim( ANIMCHANNEL_LEGS, "run" );
	setState( "state_Begin" );
}

/*
=====================
monster_zombie::state_Begin
=====================
*/
void monster_zombie::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );		
	setState( "state_Idle" );
}

/*
=====================
monster_zombie::state_Idle
=====================
*/
void monster_zombie::state_Idle() {
	wait_for_enemy();
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_zombie::do_attack
=====================
*/
void monster_zombie::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	}
}

/*
=====================
monster_zombie::check_attacks
=====================
*/
float monster_zombie::check_attacks() {
	float attack_flags;

	attack_flags = 0;
	if ( testMeleeAttack() ) {
		attack_flags |= ATTACK_MELEE;
	}
	
	return attack_flags;
}

/*
=====================
monster_zombie::combat_melee
=====================
*/
void monster_zombie::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 8 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

//@doomscript-blueprint begin 6
//@source 885ECBDC
//@catalog 0C260740
//@node 07784E8A-0 40 40
//@node 4436D271-0 330 40
//@node B5C315D2-0 610 40
//@node DFC60786-0 405 145
//@node 0680303C-0 200 145
//@node 4D87AA66-0 890 200
//@node CC0C66B9-0 1170 40
//@node D6BD4CE8-0 40 40
//@node 48766709-0 330 40
//@node D0F460EC-0 105 145
//@node 7D871C9B-0 610 40
//@node 233CCDD8-0 405 232
//@node 8B46BD45-0 890 40
//@node 68DA8713-0 685 145
//@node 8845C334-0 1170 40
//@node D5CCFD1B-0 730 145
//@node AA8270CB-0 960 145
//@node CE7776ED-0 1450 200
//@node 644E6567-0 1245 305
//@node 79F4BFB8-0 1730 360
//@node 8A0BB199-0 1505 465
//@node 3ACF1917-0 2010 360
//@node 72B4A465-0 1805 465
//@node 5DFD9A3A-0 1600 465
//@node C3E78CD1-0 1600 549
//@node F1246AF4-0 2290 520
//@node 602E2E5C-0 2570 200
//@node D73F1C59-0 2850 40
//@node C2727716-0 3130 40
//@node 8E9005D0-0 40 40
//@node EAD1C12C-0 330 40
//@node BA97B19D-0 610 40
//@node A9F1128C-0 170 145
//@node 05D77F9C-0 400 145
//@node 5163183C-0 890 200
//@node 4220D514-0 1170 40
//@node 43D21976-0 1450 40
//@node 051B26BC-0 40 40
//@node 5E5DA3E9-0 330 40
//@node 1D70ECBF-0 610 40
//@node 679F2200-0 890 200
//@node A79F9325-0 685 305
//@node 5182D4F4-0 480 305
//@node A1B24281-0 480 389
//@node 6C2046FC-0 480 305
//@node CBCAD7D7-0 1170 200
//@node EE5FF4AF-0 965 305
//@node EF9A630B-0 760 305
//@node D4689E23-0 40 40
//@node 9EB8A786-0 330 40
//@node 18DF1E08-0 610 40
//@node 55870A4F-0 890 200
//@node 5067C836-0 685 305
//@node BEF2171D-0 480 305
//@node 7FAA1D9A-0 480 389
//@node 41D86B37-0 480 305
//@node 42280926-0 1170 200
//@node B631AE64-0 965 305
//@node D77BF8B6-0 760 305
//@node C0C237AB-0 40 40
//@node A68DB454-0 330 40
//@node F6782062-0 125 232
//@node 69961CBF-0 -80 232
//@node 1E382AAA-0 610 40
//@node 7CC19702-0 890 200
//@node 09CE1F27-0 685 305
//@node E82C86FD-0 480 305
//@node 03AB1A7A-0 480 389
//@node 397A771A-0 1170 200
//@node 1C30A293-0 965 305
//@node 2D9FAB89-0 760 305
//@node 833FA16E-0 40 40
//@node 1EC28D43-0 330 40
//@node 38415A3C-0 125 145
//@node 2DDE7489-0 610 40
//@node 30F7533B-0 405 145
//@node 45770698-0 890 40
//@node F7A7CAE1-0 665 145
//@node B875D1E8-0 460 337
//@node 07F6C78D-0 255 337
//@node B6E56852-0 1170 40
//@node 3A603A0F-0 40 40
//@node 224704EB-0 330 40
//@node C1BACFA5-0 610 40
//@node A5C4B62B-0 890 40
//@node 906A69A9-0 1170 40
//@node E8D9F5F2-0 1450 40
//@node F5DF00EC-0 40 40
//@node 35710CC0-0 330 40
//@node 5C1CF92B-0 610 40
//@node 90F7C70A-0 40 40
//@node 14B9AC19-0 330 40
//@node 7393403C-0 125 145
//@node FC7BF89D-0 610 200
//@node 5C7E436E-0 40 40
//@node 10D404F1-0 330 40
//@node A48BC0DE-0 125 145
//@node 7F9D0DEB-0 610 40
//@node 154B8E57-0 385 145
//@node 3A1626D0-0 890 200
//@node 0327328D-0 1170 40
//@node C71B0BE7-0 40 40
//@node 17BACBCA-0 330 40
//@node 74C61AA2-0 610 40
//@node 576CE77B-0 890 40
//@node 7B856395-0 1170 40
//@node 0220ADBA-0 1450 40
//@doomscript-blueprint end
