/***********************************************************************

ai_monster_zombie_commando_tentacle.script

monster_zombie_commando_tentacle

***********************************************************************/

#define ZCT_RUNDISTANCE			128
#define ZCT_WALKTURN			65
#define ZCT_ATTACK_RATE			5
#define ZCT_TENTACLE_RANGE_MAX	200
#define ZCT_NOFOVTIME			4

#define ATTACK_TENTACLE			ATTACK_SPECIAL1

object monster_zombie_commando_tentacle : monster_base {
	float		nextAttack;
	float		nextNoFOVAttack;
	boolean		tentacleDamage;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_tentacle();
	void		combat_melee();

	void		init();

	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_TentacleAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_zombie_commando_tentacle::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN ) { animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
	}
}

void monster_zombie_commando_tentacle::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_zombie_commando_tentacle::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_zombie_commando_tentacle::Torso_TentacleAttack() {
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "tentacle_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_zombie_commando_tentacle::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_zombie_commando_tentacle::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_zombie_commando_tentacle::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_zombie_commando_tentacle::init
=====================
*/
void monster_zombie_commando_tentacle::init() {
	run_distance	= ZCT_RUNDISTANCE;
	walk_turn		= ZCT_WALKTURN;

	setState( "state_Begin" );
}

/*
=====================
monster_zombie_commando_tentacle::state_Begin
=====================
*/
void monster_zombie_commando_tentacle::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_zombie_commando_tentacle::state_Idle
=====================
*/
void monster_zombie_commando_tentacle::state_Idle() {
	wait_for_enemy();
	
	tentacleDamage	= false;
	nextAttack		= 0;
	nextNoFOVAttack = 0;
	
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_zombie_commando_tentacle::do_attack
=====================
*/
void monster_zombie_commando_tentacle::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + ZCT_NOFOVTIME;
	if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_TENTACLE ) {
		combat_tentacle();
	}
}

/*
=====================
monster_zombie_commando_tentacle::check_attacks
=====================
*/
float monster_zombie_commando_tentacle::check_attacks() {
	float range;
	float currentTime;
	float attack_flags;
	
	attack_flags = 0;	

	if ( testMeleeAttack() ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		range = enemyRange();
		currentTime = sys.getTime();
		if ( ( range < ZCT_TENTACLE_RANGE_MAX ) && ( !canReachEnemy() || ( currentTime >= nextAttack ) ) ) {
			if ( canHitEnemy() ) {
				attack_flags |= ATTACK_TENTACLE;
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_zombie_commando_tentacle::tentacle_attack_start
=====================
*/
void monster_zombie_commando_tentacle::tentacle_attack_start() {
	tentacleDamage = true;
}

/*
=====================
monster_zombie_commando_tentacle::tentacle_attack_end
=====================
*/
void monster_zombie_commando_tentacle::tentacle_attack_end() {
	tentacleDamage = false;
}

/***********************************************************************

	Combat

***********************************************************************/

/*
=====================
monster_zombie_commando_tentacle::combat_tentacle
=====================
*/
void monster_zombie_commando_tentacle::combat_tentacle() {
	tentacleDamage = false;
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_TentacleAttack", 4 );
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_TentacleAttack" ) ) {
		if ( tentacleDamage ) {
			if ( meleeAttackToJoint( "joint13", "melee_commandoTentacle" ) ) {
				tentacleDamage = false;
			}
		}
		waitFrame();
	}
	
	tentacleDamage = false;

	// don't attack for a bit
	nextAttack = DelayTime( ZCT_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + ZCT_NOFOVTIME;
}

/*
=====================
monster_zombie_commando_tentacle::combat_melee
=====================
*/
void monster_zombie_commando_tentacle::combat_melee() {
	tentacleDamage = false;
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack" ) ) {
		lookAtEnemy( 1 );
		if ( tentacleDamage ) {
			if ( meleeAttackToJoint( "joint13", "melee_commandoTentacle" ) ) {
				tentacleDamage = false;
			}
		}
		waitFrame();
	}
	tentacleDamage = false;
}

//@doomscript-blueprint begin 6
//@source 8E7A3738
//@catalog 0C260740
//@node 58BDFADC-0 40 40
//@node 257AA323-0 330 40
//@node 516D1ED1-0 610 40
//@node 81D235B5-0 890 200
//@node E181A106-0 685 305
//@node E5FA3B6D-0 480 305
//@node 63663276-0 40 40
//@node 8825B867-0 330 40
//@node FD608DAB-0 105 145
//@node F3997FA9-0 610 40
//@node 60D30BBF-0 405 232
//@node 2624AAC7-0 890 40
//@node 182D08E4-0 685 145
//@node 5321CB61-0 1170 40
//@node 2A5BB8D0-0 730 145
//@node 3A9E7EE0-0 960 145
//@node 9C04C133-0 1450 200
//@node 88B53059-0 1245 305
//@node 5D7CED7E-0 1730 360
//@node 7F16AA4D-0 1505 465
//@node BCB1A57D-0 2010 360
//@node 5FE0D8DF-0 1805 465
//@node 3A63F2BC-0 1600 465
//@node BCEA967F-0 1600 549
//@node 4E4A0FFE-0 2290 520
//@node ADCB36FE-0 2570 200
//@node A47E9A0F-0 2850 40
//@node B55CE322-0 3130 40
//@node B589E1EE-0 40 40
//@node F9DBC3C6-0 330 40
//@node D9AF878F-0 610 40
//@node 841EEA80-0 170 145
//@node A0FFBDD0-0 400 145
//@node 9F4160B6-0 890 200
//@node 98E9393A-0 1170 40
//@node FF328EC8-0 1450 40
//@node 928CEAC4-0 40 40
//@node 9C38322E-0 330 40
//@node 1CC0667F-0 610 40
//@node D7D668EF-0 890 40
//@node EC4EA155-0 1170 40
//@node A0CF4D74-0 730 145
//@node DD1616A4-0 960 145
//@node 3F384AC4-0 1450 200
//@node CDF4A098-0 1730 40
//@node D6B425CA-0 2010 40
//@node 9F8FBCBA-0 40 40
//@node 4E01907B-0 330 40
//@node 9F0A1CE9-0 610 40
//@node 1004309C-0 890 200
//@node F9A8CE3F-0 685 305
//@node 86F10CA8-0 480 305
//@node 5895EAF5-0 480 389
//@node D1FE03E1-0 1170 200
//@node 2B48AB8D-0 965 305
//@node 5F348205-0 760 305
//@node B59802A9-0 40 40
//@node 64C50DD8-0 330 40
//@node 2373540A-0 610 40
//@node CFE2F3F5-0 890 200
//@node 0C18ACDE-0 685 305
//@node B9D10245-0 480 305
//@node 15D024F2-0 480 389
//@node 27CBC204-0 1170 200
//@node DDBD5D9E-0 965 305
//@node 471001A0-0 760 305
//@node D2BC5D7D-0 40 40
//@node F8B943AE-0 330 40
//@node 1672245C-0 125 232
//@node 187ADF39-0 -80 232
//@node 92C55110-0 610 40
//@node DFD7A770-0 890 200
//@node D54DC0A1-0 685 305
//@node 8E2076D7-0 480 305
//@node 2E0A7140-0 480 389
//@node AA232DF4-0 1170 200
//@node 3FA00230-0 965 305
//@node 8FFEF068-0 760 305
//@node 5E2E4528-0 40 40
//@node D80943C6-0 330 40
//@node 86E8937A-0 125 145
//@node D699BE1E-0 610 40
//@node 7C7048C6-0 405 145
//@node 2908A788-0 890 40
//@node 9647087D-0 40 40
//@node 25462299-0 330 40
//@node A8E0402B-0 610 40
//@node 19920E19-0 890 40
//@node 9C088A27-0 1170 40
//@node 51D0624C-0 1450 40
//@node B6276FDA-0 40 40
//@node 6F5384FE-0 330 40
//@node 1018088F-0 610 40
//@node B57E4745-0 405 145
//@node B30B3BA4-0 890 40
//@node 7A673B19-0 685 145
//@node 823550EA-0 1170 40
//@node C0D4DB21-0 965 145
//@node 950FF459-0 1450 40
//@node C1DF0A54-0 40 40
//@node 87C49E8D-0 330 40
//@node 10D06E8C-0 125 145
//@node 52EE6843-0 610 40
//@node 2A1A3BEE-0 405 145
//@node 788AD1A3-0 890 200
//@node E4187088-0 1170 200
//@node 2FCDB227-0 965 305
//@node 4AC24157-0 1450 200
//@node D59A2ED4-0 40 40
//@node C00D6CD3-0 330 40
//@node 77CDED1D-0 125 145
//@node 00F7F545-0 610 40
//@node 1F87307B-0 385 145
//@node 723D5D1E-0 890 200
//@node 71D2AD8B-0 1170 40
//@node C2D6FD9F-0 965 145
//@node EA9953EF-0 760 145
//@node 8450EA9C-0 760 229
//@node BBF59098-0 760 145
//@node EEDBCBA6-0 1450 200
//@node 92C04B8D-0 1225 305
//@node ED6F206A-0 1730 200
//@node 3A312DE5-0 1505 305
//@node CB9029EE-0 2010 200
//@node CAD04F32-0 1805 305
//@node F21B388E-0 1600 305
//@node AA654577-0 1600 389
//@node B834AB48-0 1600 473
//@node 0C0C8148-0 2290 360
//@node 9505223C-0 2065 465
//@node F219DD42-0 2570 520
//@node 970754E7-0 2850 40
//@node BA7F03BE-0 40 40
//@node 27E2AA62-0 330 40
//@node 5A202DB8-0 125 145
//@node A53852CB-0 40 40
//@node AD0AA920-0 330 40
//@node C70144DC-0 125 145
//@node 85A93C71-0 40 40
//@node 2F7FDF82-0 330 40
//@node F4E91269-0 125 145
//@node 8D0DB560-0 610 40
//@node 4A242BB5-0 890 40
//@node 00FCA7D3-0 1170 40
//@node CC01AF94-0 945 145
//@node D0C25706-0 1450 200
//@node 8967D033-0 1245 305
//@node F2D27340-0 1730 360
//@node D7E23550-0 1505 465
//@node 2F7FDF82-1 2010 520
//@node 74624A02-0 1805 625
//@node 1DE1A5A7-0 2290 200
//@node 2F7FDF82-2 2570 40
//@node 801E173B-0 2365 145
//@node 52CCB725-0 2850 40
//@node 375F8138-0 2625 145
//@node 9DA92D56-0 3130 40
//@node 3E298905-0 2925 145
//@node 79AD1C55-0 40 40
//@node 5BEC1098-0 330 40
//@node 3DDBF129-0 125 145
//@node 63A3E5C4-0 610 40
//@node DFA9CC18-0 890 40
//@node 203255F7-0 1170 40
//@node 0C886FA2-0 945 145
//@node 9613654C-0 1450 200
//@node 0E5BBCFE-0 1730 200
//@node 6B0F63CA-0 1525 305
//@node 8723E328-0 2010 360
//@node 2280749E-0 1785 465
//@node 5BEC1098-1 2290 520
//@node 51AA8FC2-0 2085 625
//@node 8A69080F-0 2570 200
//@node 5BEC1098-2 2850 40
//@node 62A109FB-0 2645 145
//@doomscript-blueprint end
