/***********************************************************************

ai_monster_boss_sabaoth.script

monster_boss_sabaoth

***********************************************************************/

#define SABAOTH_ATTACK_RATE			4
#define SABAOTH_ATTACK_RATE_MELEE	1
#define	SABAOTH_SLOW_DIST			64
#define SECTION_MOVE_DIST			190
#define CENTER_DIST					304
#define MELEE_INIT					290

object monster_boss_sabaoth : monster_base {
	float		nextAttack;
	float		movespeed;
	entity		projectile;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();
	void		state_Combat();
	void		state_Killed();

	// attacks
	float		check_attacks( float meleeOnly );
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();
	void		fire_bfg();

	void		init();
	
	void 		move_to_corner( entity path, boolean noslowtostop );
	void 		turn_to_corner( entity path );
	void 		closeSection( entity path );
	void 		openSection( entity path );

	// torso anim states
	void		Torso_Idle();
	void		Torso_RangeAttack();
	void		Torso_MeleeAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	
	void 		open_section_1();
	void 		close_section_1();
	void 		open_section_2();
	void 		close_section_2();
	void 		close_section_3();
	void 		open_section_3();
	void 		close_section_4();
	void 		open_section_4();
	void 		open_section_5();
	void 		close_section_5();
	void 		open_section_6();
	void 		close_section_6();
	void 		open_section_7();
	void 		close_section_7();
	void 		open_section_8();
	void 		close_section_8();

};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_boss_sabaoth::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
}

void monster_boss_sabaoth::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 6 );
}


void monster_boss_sabaoth::Torso_RangeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}
	finishAction( "range_attack" );
	nextAttack = DelayTime( SABAOTH_ATTACK_RATE );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 6 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_boss_sabaoth::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_boss_sabaoth::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "move_forward" );
	
	eachFrame {
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_boss_sabaoth::init
=====================
*/
void monster_boss_sabaoth::init() {
	open_section_2();
	open_section_3();
	open_section_4();
	open_section_5();
	open_section_6();
	open_section_7();
	open_section_8();
	
	// bring center section up	
	$func_mover_13.move( UP, CENTER_DIST );
	

	movespeed = getFloatKey( "fly_speed" );
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_boss_sabaoth::state_Killed
=====================
*/
void monster_boss_sabaoth::state_Killed() {
	stopMove();

	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );
	waitAction( "dead" );
	setState( "state_Dead" );
}

/*
=====================
monster_boss_sabaoth::state_Begin
=====================
*/
void monster_boss_sabaoth::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );	
	monster_begin();
	setMoveType( MOVETYPE_SLIDE );
	setState( "state_Idle" );
}

/*
=====================
monster_boss_sabaoth::state_Idle
=====================
*/
void monster_boss_sabaoth::state_Idle() {
	wait_for_enemy();

	nextAttack = 0;
	current_path = randomPath();
	setState( "state_Combat" );
}

/*
=====================
monster_boss_sabaoth::move_to_corner
=====================
*/
void monster_boss_sabaoth::move_to_corner( entity path, boolean noslowtostop ) {
	float attack_flags;
	float dist;
	float randomSpeed = sys.random ( 100 ) + 75;
	float currentMoveSpeed = movespeed + randomSpeed;
	setFlySpeed( currentMoveSpeed );
	
	startSound ("snd_move_start", SND_CHANNEL_BODY, false );
	startSound ("snd_move", SND_CHANNEL_BODY2, false );
	
	moveToEntity( path );
	while( !AI_MOVE_DONE ) {
		dist = distanceTo( path );
		if ( dist < SABAOTH_SLOW_DIST ) {
			if ( noslowtostop ) {
				return;
			}
			setFlySpeed( currentMoveSpeed * ( dist / SABAOTH_SLOW_DIST ) );
		}

		if ( AI_ENEMY_VISIBLE ) {
			lookAtEnemy( 1 );
		}
		
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
		}
		
		attack_flags = check_attacks( 0 );
		if ( attack_flags ) {
			do_attack( attack_flags );
			continue;
		}
		
		if ( !enemyPositionValid() ) {
			locateEnemy();
		}
		
		waitFrame();
	}
	if ( !noslowtostop ) {
		setFlySpeed( 0 );
	}
	startSound ("snd_move_stop", SND_CHANNEL_BODY2, false );
	stopMove();
}

/*
=====================
monster_boss_sabaoth::turn_to_corner
=====================
*/
void monster_boss_sabaoth::turn_to_corner( entity path ) {
	float attack_flags;

	startSound ("snd_move_start", SND_CHANNEL_BODY, false );
	startSound ("snd_move", SND_CHANNEL_BODY2, false );

	turnToEntity( path );
	while( !facingIdeal() ) {
		if ( AI_ENEMY_VISIBLE ) {
			lookAtEnemy( 1 );
		}
		
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
		}

		attack_flags = check_attacks( 1 );
		if ( attack_flags ) {
			do_attack( attack_flags );
			continue;
		}
		

		if ( !enemyPositionValid() ) {
			locateEnemy();
		}
		
		waitFrame();
	}
	stopMove();
}

/*
=====================
monster_boss_sabaoth::closeSection
=====================
*/
void monster_boss_sabaoth::closeSection( entity path ) {
	string func;

	func = path.getKey( "close" );
	if ( func != "" ) {
		callFunction( func );
	}
}

/*
=====================
monster_boss_sabaoth::openSection
=====================
*/
void monster_boss_sabaoth::openSection( entity path ) {
	string func;

	func = path.getKey( "open" );
	if ( func != "" ) {
		callFunction( func );
	}
}

/*
=====================
monster_boss_sabaoth::state_Combat
=====================
*/
void monster_boss_sabaoth::state_Combat() {
	entity next_path;
	entity prev_path;
	boolean no_turn;

	next_path = current_path.randomPath();
	no_turn = false;
	while( current_path ) {
		if ( !no_turn ) {
			turn_to_corner( current_path );
		} else {
			sys.print( "no turn to " + current_path.getName() + "\n" );
		}
		no_turn = current_path.getIntKey( "no_turn" );
		if ( no_turn ) {
			sys.print( "no slow to " + current_path.getName() + "\n" );
		}
		move_to_corner( current_path, no_turn );
		
		openSection( prev_path );

		prev_path = current_path;
		current_path = next_path;
		next_path = current_path.randomPath();

		closeSection( next_path );
	}
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_boss_sabaoth::do_attack
=====================
*/
void monster_boss_sabaoth::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	}
}

/*
=====================
monster_boss_sabaoth::check_attacks
=====================
*/
float monster_boss_sabaoth::check_attacks( float meleeOnly ) {
	float attack_flags;
	float checkMelee;
	
	attack_flags = 0;
	if ( !inAnimState( ANIMCHANNEL_TORSO, "Torso_Idle" ) ) {
		return attack_flags;
	}
	if ( AI_ENEMY_VISIBLE ) {
		if ( enemyRange() < MELEE_INIT ) {
			attack_flags |= ATTACK_MELEE;
		} else if ( !meleeOnly && ( !projectile || ( projectile.getProjectileState() != PROJECTILE_LAUNCHED ) ) && ( !canReachEnemy() || ( sys.getTime() >= nextAttack ) ) ) {
			if ( canHitEnemyFromJoint( "mech_bfg" ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		}
	}
	return attack_flags;
}

/*
=====================
monster_boss_sabaoth::combat_range
=====================
*/
void monster_boss_sabaoth::combat_range() {
	animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
	
	// animation will set the next attack time, so just delay it for a long time for now
	nextAttack = sys.getTime() + 10000;
}

/*
=====================
monster_boss_sabaoth::combat_melee
=====================
*/
void monster_boss_sabaoth::combat_melee() {
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 4 );
}

/*
=====================
monster_boss_sabaoth::fire_bfg
=====================
*/
void monster_boss_sabaoth::fire_bfg() {
	projectile = attackMissile( "mech_bfg" );
}

void monster_boss_sabaoth::open_section_1() {
    $func_mover_7.move( NORTH, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_1() {
    $func_mover_7.move( NORTH, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_2() {
    $func_mover_8.move( NORTH, SECTION_MOVE_DIST );
	$func_mover_9.move( EAST, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_2() {
    $func_mover_8.move( NORTH, -SECTION_MOVE_DIST );
	$func_mover_9.move( EAST, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_3() {
    $func_mover_10.move( EAST, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_3() {
    $func_mover_10.move( EAST, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_4() {
    $func_mover_11.move( EAST, SECTION_MOVE_DIST );
	$func_mover_12.move( SOUTH, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_4() {
    $func_mover_11.move( EAST, -SECTION_MOVE_DIST );
	$func_mover_12.move( SOUTH, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_5() {
    $func_mover_1.move( SOUTH, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_5() {
    $func_mover_1.move( SOUTH, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_6() {
    $func_mover_2.move( SOUTH, SECTION_MOVE_DIST );
	$func_mover_3.move( WEST, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_6() {
    $func_mover_2.move( SOUTH, -SECTION_MOVE_DIST );
	$func_mover_3.move( WEST, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_7() {
    $func_mover_4.move( WEST, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_7() {
    $func_mover_4.move( WEST, -SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::open_section_8() {
    $func_mover_5.move( WEST, SECTION_MOVE_DIST );
	$func_mover_6.move( NORTH, SECTION_MOVE_DIST );
}

void monster_boss_sabaoth::close_section_8() {
    $func_mover_5.move( WEST, -SECTION_MOVE_DIST );
	$func_mover_6.move( NORTH, -SECTION_MOVE_DIST );
}

//@doomscript-blueprint begin 6
//@source FF8B18BB
//@catalog 0C260740
//@node B9EBC5AC-0 40 40
//@node 3B57353B-0 330 40
//@node 23A18FDE-0 40 40
//@node A80EA9BA-0 330 40
//@node C5B23E06-0 610 40
//@node EF809E93-0 170 145
//@node 641E83C3-0 400 145
//@node 8E9B31DF-0 890 200
//@node C452B7A2-0 1170 200
//@node DCD5857E-0 1450 40
//@node 785A6A42-0 1730 40
//@node 9F1C65EF-0 40 40
//@node E4208102-0 330 40
//@node 4B5392C9-0 610 40
//@node F484FB2B-0 170 145
//@node 818CEFDB-0 400 145
//@node 08D049DA-0 890 200
//@node 88118C45-0 1170 200
//@node 75852FF0-0 1450 40
//@node AF25BD16-0 1730 40
//@node 08FDEEEA-0 1505 145
//@node BE3F69B9-0 2010 40
//@node 7621156A-0 40 40
//@node A93704C3-0 330 40
//@node 86594589-0 610 40
//@node F5FF7075-0 890 200
//@node 52ECC464-0 685 305
//@node 27AA7510-0 480 305
//@node 4563DFF9-0 40 40
//@node 3FCA67B2-0 330 40
//@node 393999AA-0 610 40
//@node 64A8D940-0 890 200
//@node 10AFFEF9-0 685 305
//@node E5CA624D-0 480 305
//@node EE14A4D8-0 40 40
//@node F525186D-0 330 40
//@node F48272FC-0 610 40
//@node 39DA4E8F-0 890 40
//@node 0C49C2D6-0 1170 40
//@node 52DED2E9-0 1450 40
//@node 519E5CB8-0 1730 40
//@node B2B7E23B-0 2010 40
//@node 24CD1721-0 2290 40
//@node F370E442-0 2570 40
//@node 473C45BA-0 2345 145
//@node 6904A015-0 2140 245
//@node 697842E0-0 1935 245
//@node 753291EC-0 2850 40
//@node E299E299-0 40 40
//@node 739BE89C-0 330 40
//@node E22B13F7-0 610 40
//@node C3911345-0 890 40
//@node 440E2024-0 1170 40
//@node FF75A364-0 1450 40
//@node A74BAEAD-0 40 40
//@node B5344BFD-0 330 40
//@node 2FA645DF-0 610 40
//@node A1B7D435-0 890 40
//@node 576D666B-0 1170 40
//@node E5D28148-0 1450 40
//@node 5B72492A-0 40 40
//@node 0012B322-0 330 40
//@node 75399000-0 610 40
//@node 4D228D41-0 405 145
//@node 9DC9B93F-0 890 40
//@node DAA034ED-0 665 145
//@node B4EAECBD-0 1170 40
//@node 7B97C8F3-0 40 40
//@node B16E327A-0 890 40
//@node 8077A357-0 125 140
//@node 263F7BFF-0 1170 40
//@node DA8DE5C6-0 1450 40
//@node F5A1A611-0 1730 40
//@node 0AB9C899-0 1450 40
//@node 173F5CD7-0 1245 145
//@node 26D4FF87-0 1040 145
//@node 47DDD362-0 1730 200
//@node 460EAF51-0 1505 305
//@node E235BAFC-0 2010 200
//@node 33B4213C-0 1805 305
//@node 16096852-0 1600 305
//@node 9ED01AD8-0 2290 360
//@node C078D480-0 3130 520
//@node 2689DA43-0 3410 360
//@node 5624AA8D-0 2645 460
//@node 656063C4-0 2440 460
//@node 70B54F1B-0 2440 538
//@node 19A312A7-0 3130 200
//@node BDB27816-0 2925 305
//@node 7E697262-0 3970 360
//@node 9A6DF3EB-0 3690 200
//@node E5C01877-0 3485 305
//@node 7DFAB26C-0 4530 360
//@node 109492D7-0 4250 200
//@node 29314031-0 4025 305
//@node D45130A3-0 4530 200
//@node 8DA8E20A-0 4325 305
//@node A240BEC9-0 5370 360
//@node 181A9F9D-0 4605 460
//@node 7CE9756C-0 5090 360
//@node 72FD02D8-0 5370 200
//@node EED38D0B-0 4930 305
//@node 2573E2FB-0 5160 305
//@node 6C04CA6D-0 6210 360
//@node E82ACAAD-0 6490 200
//@node E2E9C687-0 6210 40
//@node 896BC211-0 6005 145
//@node 966C014D-0 7050 200
//@node FC554FC5-0 7330 40
//@node C185DD76-0 7610 40
//@node 7E64E20D-0 40 40
//@node DE0AC941-0 330 40
//@node C9EB883C-0 610 40
//@node 77748BA5-0 890 40
//@node FAE2B5FE-0 1170 40
//@node 750DF576-0 730 145
//@node 49B8E5C6-0 960 145
//@node EAC720D5-0 1450 200
//@node C92AFF64-0 1245 305
//@node B8A701E0-0 1730 360
//@node A7ABC951-0 2010 200
//@node 68F0E71C-0 1805 305
//@node 69FA1F52-0 2290 360
//@node 909FADA0-0 2570 200
//@node 3E225847-0 2345 305
//@node F2B160F1-0 2850 200
//@node 4B454675-0 2645 305
//@node 08A5AD63-0 3130 360
//@node D86C3A31-0 2925 460
//@node 4A16D8DE-0 3410 360
//@node F4BF8812-0 3690 200
//@node 4CD52421-0 3250 305
//@node 241F3D51-0 3480 305
//@node 325B4703-0 3970 360
//@node B0906463-0 4250 200
//@node 60E753FC-0 4530 40
//@node C20DA9B1-0 40 40
//@node 888BAB39-0 330 40
//@node 2B2C264D-0 105 145
//@node 0081743D-0 610 40
//@node 4F1B456B-0 405 145
//@node 074CED68-0 200 145
//@node 0AACF5CD-0 890 200
//@node 9CDF1FE0-0 685 300
//@node D6074A35-0 40 40
//@node AFECA135-0 330 40
//@node E0779EF3-0 105 145
//@node 7293BAB1-0 610 40
//@node 7B78C075-0 405 145
//@node A63A8D6C-0 200 145
//@node 184D7C69-0 890 200
//@node 9CDF847F-0 685 300
//@node FCB02108-0 40 40
//@node 8DA4BDB2-0 330 40
//@node 8DB34325-0 105 145
//@node E938259F-0 610 40
//@node 7FB9AE96-0 405 145
//@node 9578B567-0 890 40
//@node 67949E8A-0 685 145
//@node 7038847A-0 1170 200
//@node E06E1765-0 965 305
//@node 658968B9-0 760 305
//@node 35FC58F8-0 1450 360
//@node 2C302569-0 1245 460
//@node 96673CFC-0 2010 360
//@node 1A8D9040-0 1805 460
//@node 00115F9E-0 1600 460
//@node 83C3219F-0 2290 200
//@node A87BAFF1-0 2065 305
//@node 0912B518-0 1860 405
//@node A8BBBCC1-0 1655 405
//@node 6725D0CD-0 2570 200
//@node E2857BF0-0 2365 305
//@node B872AFB2-0 2850 360
//@node 6F148F23-0 2645 460
//@node B79AC5C5-0 2440 460
//@node 10299D8B-0 3130 200
//@node C3A616D8-0 2925 300
//@node 6D594C93-0 2925 392
//@node 5F9E672E-0 3410 200
//@node 2B54F31E-0 3205 300
//@node D92182B1-0 3690 200
//@node 8E6E63F8-0 3485 305
//@node E3210A8D-0 3970 200
//@node 863C420D-0 3765 305
//@node 8DA4BDB2-1 4250 200
//@node 12DF8C18-0 4025 305
//@node 4079990A-0 4530 200
//@node CB86D9D0-0 4325 300
//@node F4036BE4-0 40 40
//@node 4790702B-0 330 40
//@node 43304AEF-0 125 145
//@node 0593ACC4-0 610 200
//@node DB27570C-0 890 200
//@node 88AF2034-0 685 305
//@node CE29A4A7-0 1170 200
//@node 81397584-0 40 40
//@node 4FE9EA57-0 330 40
//@node A1927946-0 125 145
//@node 8C73D7D5-0 610 40
//@node 56E5F18C-0 170 145
//@node 9E00AABC-0 400 145
//@node D080B8BF-0 890 200
//@node 446FE280-0 1170 40
//@node 4074A3DD-0 965 145
//@node 9F9F042B-0 1450 200
//@node 6CB0956C-0 1245 305
//@node 3A36A7BE-0 1730 360
//@node 6898034E-0 2010 360
//@node 94C0048B-0 1805 465
//@node B416411A-0 1600 549
//@node FDCBFC14-0 1600 633
//@node A4DFF89D-0 2290 360
//@node 34D338C1-0 2065 465
//@node 85CA246E-0 2570 520
//@node D080B8BF-1 2850 40
//@node D26574E8-0 40 40
//@node 81C09C57-0 330 40
//@node 01B07EF7-0 610 40
//@node B92F760C-0 405 145
//@node 719C6BA5-0 40 40
//@node 80F9C425-0 330 40
//@node 16B829C0-0 40 40
//@node 94286A0A-0 330 40
//@node 292994C9-0 105 145
//@node 44C0F6AA-0 40 40
//@node 41E74EEA-0 330 40
//@node B1A5326E-0 40 40
//@node 7A851AFD-0 330 40
//@node 43C0F517-0 40 40
//@node 42C2D272-0 330 40
//@node CE9FF867-0 610 40
//@node B0A530DB-0 40 40
//@node C23619DD-0 330 40
//@node 0048F126-0 610 40
//@node 42C0F384-0 40 40
//@node 228BAF8A-0 330 40
//@node AFA52F48-0 40 40
//@node EFAEEA0D-0 330 40
//@node 41C0F1F1-0 40 40
//@node 37998A6E-0 330 40
//@node 955D41C5-0 610 40
//@node B6A53A4D-0 40 40
//@node 5BDC35F9-0 330 40
//@node 5A0B5E18-0 610 40
//@node 40C0F05E-0 40 40
//@node 528AF2D6-0 330 40
//@node B5A538BA-0 40 40
//@node 945F7B29-0 330 40
//@node 3FC0EECB-0 40 40
//@node 98001952-0 330 40
//@node C6386BD7-0 610 40
//@node B4A53727-0 40 40
//@node 7E6E5635-0 330 40
//@node C8C0DEA6-0 610 40
//@node 3EC0ED38-0 40 40
//@node 33549D7D-0 330 40
//@node B3A53594-0 40 40
//@node 92C3C6C8-0 330 40
//@node 3DC0EBA5-0 40 40
//@node 965BF75F-0 330 40
//@node 9D0567DE-0 610 40
//@node AAA52769-0 40 40
//@node 59E05ECE-0 330 40
//@node 6FC63731-0 610 40
//@doomscript-blueprint end
