/***********************************************************************

ai_monster_zombie_sawyer.script

monster_zombie_sawyer

***********************************************************************/

#define SAWYER_SMOKE_PARTICLES	0
#define SAWYER_BLOOD_PARTICLES	1

object monster_zombie_sawyer : monster_zombie_base {
	boolean		attack;

	void		state_Begin();
	void		state_Idle();
	void		init();

	void		start_smoke();
		
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Run();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_melee();
	void		start_attack();
	void		end_attack();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_zombie_sawyer::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", 4 );
}

void monster_zombie_sawyer::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 4 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

void monster_zombie_sawyer::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_zombie_sawyer::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
	}
}

void monster_zombie_sawyer::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_zombie_sawyer::init
=====================
*/
void monster_zombie_sawyer::init() {
	setSmokeVisibility( ALL_PARTICLES, 0 );
	setState( "state_Begin" );
}

/*
=====================
monster_zombie_sawyer::start_smoke
=====================
*/
void monster_zombie_sawyer::start_smoke() {
	setSmokeVisibility( SAWYER_SMOKE_PARTICLES, 1 );
}

/*
=====================
monster_zombie_sawyer::state_Begin
=====================
*/
void monster_zombie_sawyer::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );

	monster_begin();
	setMoveType( MOVETYPE_ANIM );		
	setState( "state_Idle" );
}

/*
=====================
monster_zombie_sawyer::state_Idle
=====================
*/
void monster_zombie_sawyer::state_Idle() {
	wait_for_enemy();
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_zombie_sawyer::do_attack
=====================
*/
void monster_zombie_sawyer::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	}
}

/*
=====================
monster_zombie_sawyer::check_attacks
=====================
*/
float monster_zombie_sawyer::check_attacks() {
	float attack_flags;

	attack_flags = 0;
	if ( testMeleeAttack() ) {
		attack_flags |= ATTACK_MELEE;
	}
	
	return attack_flags;
}

/*
=====================
monster_zombie_sawyer::combat_melee
=====================
*/
void monster_zombie_sawyer::combat_melee() {
	float next_hit_time;
	float smoke_frames;

	lookAtEnemy( 100 );
	faceEnemy();

	next_hit_time = 0;
	attack = false;
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 8 );
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack" ) ) {
		if ( attack && ( sys.getTime() > next_hit_time ) ) {
			if ( attackMelee( "melee_zombie_chainsaw" ) ) {
				next_hit_time = sys.getTime() + 0.025;
				setSmokeVisibility( SAWYER_BLOOD_PARTICLES, 1 );
				smoke_frames = 4;
			}
		}

		if ( smoke_frames ) {
			smoke_frames--;
			if ( !smoke_frames ) {
				setSmokeVisibility( SAWYER_BLOOD_PARTICLES, 0 );
			}
		}

		waitFrame();
	}

	setSmokeVisibility( SAWYER_BLOOD_PARTICLES, 0 );
	attack = false;
	lookAtEnemy( 1 );
}

/*
=====================
monster_zombie_sawyer::start_attack
=====================
*/
void monster_zombie_sawyer::start_attack() {
	attack = true;
}

/*
=====================
monster_zombie_sawyer::end_attack
=====================
*/
void monster_zombie_sawyer::end_attack() {
	attack = false;
}

//@doomscript-blueprint begin 6
//@source 4F532D34
//@catalog 0C260740
//@node BAAA7010-0 40 40
//@node 1219F5FF-0 330 40
//@node 423E4D14-0 610 40
//@node B3558F90-0 405 145
//@node E9082C84-0 200 145
//@node 6D02F83C-0 890 200
//@node E56CD888-0 1170 40
//@node C1A8911A-0 40 40
//@node 8417D919-0 330 40
//@node 77B0EA64-0 105 145
//@node B9964729-0 610 40
//@node 1B0147F1-0 405 232
//@node 20C08255-0 890 40
//@node 923422F9-0 685 145
//@node 6C41C123-0 1170 40
//@node 01724A50-0 730 145
//@node A8387F60-0 960 145
//@node D9D6ECD3-0 1450 200
//@node E7CCBF21-0 1245 305
//@node 5A3F98E8-0 1730 360
//@node F2A8EADE-0 1505 465
//@node 5C6A765D-0 2010 360
//@node E031BDF5-0 1805 465
//@node D1E78F7C-0 1600 465
//@node 9321D83F-0 1600 549
//@node EFCE2252-0 2290 520
//@node AAB7367E-0 2570 200
//@node 69A9C48F-0 2850 40
//@node 7D5CB5CC-0 3130 40
//@node F56B793A-0 40 40
//@node 27C48A46-0 330 40
//@node DFB37617-0 610 40
//@node 0D6816D3-0 170 145
//@node 71EEC583-0 400 145
//@node 3FF6E336-0 890 200
//@node 503BD4BA-0 1170 40
//@node A7C9DC14-0 1450 40
//@node 57800AC6-0 40 40
//@node BA7EA677-0 330 40
//@node 696CFD23-0 610 40
//@node 29C7A3C3-0 890 200
//@node E0738429-0 685 305
//@node 44EB2CCB-0 480 305
//@node 73FA0819-0 40 40
//@node 5694662E-0 330 40
//@node CB92A5BB-0 125 232
//@node E91D7CF0-0 -80 232
//@node E9AB1F6E-0 610 40
//@node EB1A1E70-0 890 200
//@node 1C350B61-0 685 305
//@node D4AAB9A1-0 480 305
//@node 8F60A4F4-0 40 40
//@node 14F397CA-0 330 40
//@node A6C51708-0 610 40
//@node 537F7774-0 40 40
//@node 8AF1AED7-0 330 40
//@node E3D427B9-0 40 40
//@node F4EC9571-0 330 40
//@node F4C68DD3-0 610 40
//@node E1B22C99-0 890 40
//@node 8D2135A7-0 1170 40
//@node 732D55CC-0 1450 40
//@node 13960ECE-0 40 40
//@node 3773A37E-0 330 40
//@node 9A6346D9-0 610 40
//@node 4F927820-0 40 40
//@node 50D50663-0 330 40
//@node 9F530A8F-0 125 145
//@node AC199D23-0 610 200
//@node 7D162BA8-0 40 40
//@node 93A324E1-0 330 40
//@node 2A2C5BDE-0 125 145
//@node 2F1BF3A5-0 610 40
//@node D06670BA-0 385 145
//@node 5284EB1C-0 890 200
//@node 47DCE0AB-0 1170 40
//@node 8C6B27F9-0 40 40
//@node F9DF4B4C-0 330 40
//@node 9732B144-0 610 40
//@node E0F76A39-0 890 40
//@node 91FD970C-0 685 145
//@node 2D9A69FF-0 1170 40
//@node F09C8775-0 965 145
//@node 2C6EEB35-0 1450 40
//@node D08090B3-0 1730 40
//@node DA56581C-0 1505 145
//@node 2167514C-0 2010 200
//@node DACB817A-0 1805 305
//@node 58C2AA87-0 1600 305
//@node 7A5867FE-0 1600 389
//@node 83864CA4-0 2290 360
//@node 51DEF96A-0 2065 465
//@node F166C4F0-0 2570 520
//@node 3F960751-0 2365 625
//@node AAB4F569-0 2850 520
//@node C1C77ABE-0 3130 520
//@node 6802F384-0 2925 625
//@node 20EA3349-0 3410 200
//@node 822B8762-0 3205 305
//@node 62D2E375-0 3690 360
//@node CBCE8CF0-0 3485 465
//@node 6BAD0123-0 3280 465
//@node 585AE462-0 3970 360
//@node 1BC5F273-0 3765 465
//@node 14632F3B-0 3560 465
//@node A9747F38-0 4250 520
//@node BDF7D38F-0 4530 200
//@node A9747F38-1 4810 40
//@node 2D9A69FF-1 5090 40
//@node DB1E57DE-0 4885 145
//@node 36C8E7CC-0 5370 40
//@node 3ACAF04B-0 40 40
//@node 7311C68E-0 330 40
//@node 73B331D9-0 125 145
//@node 0B816A58-0 40 40
//@node 3AD231AA-0 330 40
//@node 68549E4B-0 125 145
//@doomscript-blueprint end
