/***********************************************************************

ai_monster_demon_cherub.script

monster_demon_cherub

***********************************************************************/

#define CHERUB_RUNDISTANCE		192
#define CHERUB_WALKTURN			65
#define CHERUB_LEAP_RATE		2
#define CHERUB_DODGE_RATE		2
#define CHERUB_LEAP_RANGE		1024
#define CHERUB_LEAP_SPEED		650
#define CHERUB_LEAP_MAXHEIGHT	48

object monster_demon_cherub : monster_base {
	float		nextDodge;
	float		nextLeap; 			// don't do a range attack until this time
	vector		jumpVelocity;
	
	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		path_jump();
	void		combat_leap();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();
	void		path_jump();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_LeapAttack();
	void		Torso_Walk();
	void		Torso_Run();
	void		Torso_DodgeLeft();
	void		Torso_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_cherub::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Walk", 4 ); }
	}
}

void monster_demon_cherub::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_cherub::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_cherub::Torso_LeapAttack() {
	overrideAnim( ANIMCHANNEL_LEGS );
	disablePain();
	playAnim( ANIMCHANNEL_TORSO, "jump_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	
	attackBegin( "melee_cherubLeapAttack" );
	setLinearVelocity( jumpVelocity );
	
	playCycle( ANIMCHANNEL_TORSO, "jump_loop" );
	do {
		waitFrame();
	} while( !AI_ONGROUND );
	
	attackEnd();
	playAnim( ANIMCHANNEL_TORSO, "jump_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "leap_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_cherub::Torso_Walk() {
	playCycle( ANIMCHANNEL_TORSO, "walk" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_demon_cherub::Torso_Run() {
	playCycle( ANIMCHANNEL_TORSO, "run" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_demon_cherub::Torso_DodgeLeft() {
	playAnim( ANIMCHANNEL_TORSO, "evade_left" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_cherub::Torso_DodgeRight() {
	playAnim( ANIMCHANNEL_TORSO, "evade_right" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_cherub::init
=====================
*/
void monster_demon_cherub::init() {
	run_distance	= CHERUB_RUNDISTANCE;
	walk_turn		= CHERUB_WALKTURN;

	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_cherub::state_Begin
=====================
*/
void monster_demon_cherub::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	monster_begin();	
	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_demon_cherub::state_Idle
=====================
*/
void monster_demon_cherub::state_Idle() {
	wait_for_enemy();

	nextLeap		= RandomTime( CHERUB_LEAP_RATE );
	nextDodge		= RandomTime( CHERUB_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_cherub::do_attack
=====================
*/
void monster_demon_cherub::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_LEAP ) {
		combat_leap();
	}
}

/*
=====================
monster_demon_cherub::check_attacks
=====================
*/
float monster_demon_cherub::check_attacks() {
	float range;
	float currentTime;
	float canMelee;
	float attack_flags;
	float checkLeap;
	vector vel;
	float t;
	vector jumpTarget;
	
	attack_flags = 0;
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();

	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	}

	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( AI_ENEMY_IN_FOV ) {
		range = enemyRange();
		if ( ( range < CHERUB_LEAP_RANGE ) && ( currentTime >= nextLeap ) ) {
			if ( canHitEnemy() ) {
				t = animLength( ANIMCHANNEL_TORSO, "jump_start" );
				jumpTarget = predictEnemyPos( t );
				jumpVelocity = getJumpVelocity( jumpTarget, CHERUB_LEAP_SPEED, CHERUB_LEAP_MAXHEIGHT );
				if ( jumpVelocity != '0 0 0' ) {
					attack_flags |= ATTACK_LEAP;
				} else {
					// check if we can leap again in 2 seconds
					nextLeap = DelayTime( 2 );
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_cherub::path_jump
=====================
*/
void monster_demon_cherub::path_jump() {
	entity target;
	vector dir;
	vector jumpTarget;

	// walk to the path entity first
	path_corner();

	if ( checkForEnemy( true ) ) {
		return;
	}

	target = current_path.randomPath();
	if ( !target ) {
		sys.error( "missing target for '" + current_path.getName() + "'" );
	}
	jumpTarget = target.getOrigin();
	if ( !current_path.getKey( "up" ) ) {
		jumpVelocity = getJumpVelocity( jumpTarget, CHERUB_LEAP_SPEED, 1024 );
		if ( jumpVelocity == '0 0 0' ) {
			sys.error( "Monster '" + getName() + "' couldn't make jump from '" + current_path.getName() + "' to '" + target.getName() + "'" );
		}
	} else {
		float forward = current_path.getFloatKey( "forward" );
		if ( forward <= 0 ) {
			sys.error( "Invalid forward velocity on path_jump entity '" + current_path.getName() + "'\n" );
		}
		dir = jumpTarget - getOrigin();
		dir_z = 0;
		dir = sys.vecNormalize( dir );
		dir = dir * forward;
		dir_z = current_path.getFloatKey( "up" );
		jumpVelocity = dir;
	}
	
	stopMove();
	turnToPos( jumpTarget );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}

	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );

	stopMove();
}

/*
=====================
monster_demon_cherub::combat_leap
=====================
*/
void monster_demon_cherub::combat_leap() {
	stopMove();
	turnToPos( getOrigin() + jumpVelocity );
	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );
	nextLeap = DelayTime( CHERUB_LEAP_RATE );
}

/*
=====================
monster_demon_cherub::combat_melee
=====================
*/
void monster_demon_cherub::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_cherub::combat_dodge_left
=====================
*/
void monster_demon_cherub::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( CHERUB_DODGE_RATE );
}

/*
=====================
monster_demon_cherub::combat_dodge_right
=====================
*/
void monster_demon_cherub::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( CHERUB_DODGE_RATE );
}

//@doomscript-blueprint begin 6
//@source 09E0BC53
//@catalog 0C260740
//@node CF395D27-0 40 40
//@node 4340CA82-0 330 40
//@node 8D5B8746-0 610 40
//@node 31EA157A-0 890 200
//@node 69732073-0 685 305
//@node 7A6956E4-0 480 305
//@node 9878568D-0 1170 200
//@node 134B9919-0 965 305
//@node E9CC5C7E-0 760 305
//@node 481EBB8F-0 760 389
//@node B0FD0134-0 1450 200
//@node B1225D3D-0 1245 305
//@node 1E62E7F1-0 1040 305
//@node 4285EE99-0 40 40
//@node B508C614-0 330 40
//@node 91CB30CB-0 105 145
//@node 38F808C8-0 610 40
//@node 6FC31CE8-0 405 232
//@node BA963E56-0 890 40
//@node EF2A7746-0 685 145
//@node 53826194-0 1170 40
//@node A6A985F6-0 730 145
//@node E0752B06-0 960 145
//@node EA462D7A-0 1450 200
//@node BD3DD260-0 1245 305
//@node 43538E0F-0 1730 360
//@node E74E418A-0 1505 465
//@node E6F69AE6-0 2010 360
//@node 25A60C5B-0 1805 465
//@node 31C2A7C0-0 1600 465
//@node 5EF540C3-0 1600 549
//@node BFA5A4E3-0 2290 520
//@node 290BA7F7-0 2570 200
//@node 2599FC9C-0 2850 40
//@node 7333AB1F-0 3130 40
//@node DA92033F-0 40 40
//@node EBA6EA49-0 330 40
//@node 5FDF55FC-0 610 40
//@node D11D2844-0 170 145
//@node 066D7F74-0 400 145
//@node 54D1AAA9-0 890 200
//@node B46B8EBB-0 1170 40
//@node 044A4423-0 1450 40
//@node 6C129807-0 40 40
//@node DE6E926A-0 330 40
//@node A9DF5CB7-0 610 40
//@node 0E0B22FB-0 890 40
//@node BCFD4468-0 1170 40
//@node F31F8937-0 730 145
//@node 79187887-0 960 145
//@node BCEB6D8D-0 1450 200
//@node 97035418-0 1730 40
//@node 295A06D0-0 2010 40
//@node 1C40BB37-0 1805 140
//@node 45340228-0 2290 40
//@node DD5AB438-0 2570 40
//@node BCEB6D8D-1 2850 200
//@node B40C92E6-0 3130 200
//@node 8ECD4545-0 2925 305
//@node 4F5C1FFD-0 2720 305
//@node 86FB4E1C-0 3410 40
//@node 450AFEDA-0 3690 40
//@node 11E5D074-0 3970 40
//@node F5A9E23F-0 3530 145
//@node B653F54F-0 3760 145
//@node BCEB6D8D-2 4250 200
//@node 386329AD-0 4530 40
//@node 21BC33F7-0 4810 40
//@node 3509DF5C-0 40 40
//@node 0E07A857-0 330 40
//@node A9E064B1-0 610 40
//@node 83027D99-0 890 200
//@node 99388624-0 685 305
//@node 98604F97-0 480 305
//@node 0318C680-0 1170 200
//@node 3987A07A-0 965 305
//@node 2B1611C1-0 760 305
//@node E428BA6E-0 760 389
//@node D6D34387-0 1450 200
//@node 704B02AF-0 1245 305
//@node 99AB84CB-0 1040 305
//@node 9EC5EEFE-0 40 40
//@node D50D661D-0 330 40
//@node 3C67544B-0 125 232
//@node 767F27EC-0 -80 232
//@node 37FDDAE1-0 610 40
//@node 05DA6F0F-0 890 200
//@node 2699F5CE-0 685 305
//@node D07FD39B-0 480 305
//@node 953A9AEB-0 1170 200
//@node 8B849C75-0 965 305
//@node 28D05107-0 760 305
//@node DB6E8CD0-0 760 389
//@node 88BE1639-0 1450 200
//@node 896E8FCC-0 1245 305
//@node 410E99B8-0 1040 305
//@node E3BE564D-0 40 40
//@node 04743EDD-0 330 40
//@node 7E9C9B3A-0 610 40
//@node D2DEC387-0 170 145
//@node 8C3036F7-0 400 145
//@node 5831C217-0 890 200
//@node 7730D567-0 1170 40
//@node B9A8015D-0 1450 40
//@node B8B50906-0 40 40
//@node 915A240D-0 330 40
//@node 36811907-0 610 40
//@node EC6E0B70-0 170 145
//@node 988D5D60-0 400 145
//@node 2DE714B6-0 890 200
//@node 47FF8CB8-0 1170 40
//@node 890982C8-0 1450 40
//@node 2CF81503-0 40 40
//@node 28308123-0 330 40
//@node E3CB63C9-0 125 145
//@node FF5B58DB-0 610 40
//@node BB063E62-0 405 145
//@node 98EE1B41-0 890 40
//@node 934D88EC-0 40 40
//@node 48B1BE76-0 330 40
//@node ED0A68FA-0 610 40
//@node 99EC8EE2-0 890 40
//@node 7B2C7381-0 1170 40
//@node 06002B31-0 40 40
//@node 2CAB0B6D-0 330 40
//@node A6F5BA65-0 610 40
//@node 784998DD-0 385 145
//@node AE44D1B1-0 890 40
//@node C6BE34B3-0 665 145
//@node 569D231A-0 1170 40
//@node 68428759-0 40 40
//@node AE6B78DB-0 330 40
//@node AD741551-0 125 145
//@node E6FF1B09-0 610 200
//@node 47CC4377-0 890 200
//@node 05B6843D-0 685 305
//@node 7697756C-0 1170 200
//@node 8DAC9785-0 1450 200
//@node 38E69788-0 1245 305
//@node 1B4753A2-0 1730 200
//@node B64B44E7-0 2010 200
//@node F10E0149-0 1805 305
//@node 7A6BB9DC-0 2290 200
//@node A9FB7315-0 40 40
//@node C2176946-0 330 40
//@node 48249E09-0 125 145
//@node 2E9703B5-0 610 40
//@node 5B0645C8-0 385 145
//@node 361A0875-0 890 40
//@node 85E07C6F-0 665 145
//@node FCDD0728-0 1170 40
//@node 118644D3-0 965 145
//@node 7B3448DB-0 760 145
//@node 24FA8800-0 1450 200
//@node F4AFF580-0 1245 305
//@node 509CCBE4-0 1040 305
//@node 6B5F6137-0 1040 389
//@node 78F84DFC-0 1040 389
//@node 82683CD3-0 1730 360
//@node 2EF312AA-0 1505 465
//@node 0E91AD0C-0 2010 520
//@node 6A20391A-0 2290 360
//@node A2DE4B3C-0 2065 465
//@node 102016B1-0 2570 520
//@node 94B8FE93-0 2850 520
//@node 490F9122-0 2645 625
//@node F6CDF8A7-0 2440 625
//@node D99D6DF6-0 3130 680
//@node 4AC49C69-0 2925 785
//@node BE68F33B-0 3410 840
//@node 22CCE54E-0 3970 840
//@node 26A19063-0 4250 40
//@node 2FE9812B-0 4045 145
//@node CBE80997-0 4530 200
//@node 8EB99760-0 4810 40
//@node 1088EEBE-0 4605 145
//@node 540D8B7F-0 5090 200
//@node 547D87C4-0 4865 305
//@node 09853A88-0 5370 200
//@node 647C9EB7-0 5165 305
//@node A1FFCF22-0 4960 305
//@node 99EEE98B-0 4960 389
//@node C07567BA-0 4960 473
//@node 5FE2F0FF-0 5650 360
//@node 4E572ADA-0 5425 465
//@node 1E7FA4D1-0 5930 520
//@node 4C979C09-0 5705 625
//@node 5FC8B67F-0 6210 520
//@node 39CE7683-0 5985 625
//@node 0F2C0271-0 5780 725
//@node 8CACE432-0 6490 520
//@node 311AE393-0 6265 625
//@node D5524044-0 6060 725
//@node 4E8D7DE2-0 6770 520
//@node 872A8A6E-0 6565 625
//@node 3A6FA047-0 6360 625
//@node 6F9DF509-0 7050 680
//@node 21B2B5DA-0 7610 680
//@node D98D839C-0 7385 785
//@node 641CB888-0 7890 40
//@node 1554B877-0 40 40
//@node 5BCB3080-0 330 40
//@node A78BB385-0 610 40
//@node 7200ED98-0 385 145
//@node FB8A862C-0 890 200
//@node 06C14391-0 1170 40
//@node DE80E6EE-0 945 145
//@node 17801629-0 1450 40
//@node 5EBC6604-0 1245 145
//@node 25CD3854-0 1040 145
//@node F2BA0E27-0 1730 200
//@node 89257CDA-0 1525 300
//@node 3B0589EB-0 1320 300
//@node 20AF41FB-0 1320 378
//@node E7979EC9-0 2010 40
//@node 79A1BF97-0 1785 145
//@node D718B8F0-0 2290 40
//@node 596BBEAA-0 1850 145
//@node 6E93BB7A-0 2080 145
//@node 59C9F18D-0 2570 200
//@node 83F8BFEB-0 2345 305
//@node FE39B214-0 2140 405
//@node 9AD5D2BC-0 2850 200
//@node E7D68B07-0 2645 305
//@node A6A32958-0 2440 305
//@node 76003CC5-0 3130 360
//@node 5E319000-0 2925 460
//@node 2E4C5B99-0 2720 460
//@node 58AE9BB5-0 2720 538
//@node EB5340C7-0 3690 200
//@node BECA7F3B-0 3485 305
//@node 770258DD-0 3280 305
//@node CB81D884-0 4250 360
//@node E1A25A2C-0 3765 460
//@node 2E0C0998-0 3560 460
//@node 9C0D5BE2-0 3560 538
//@node 6B9C298E-0 3560 616
//@node BB988638-0 4250 200
//@node 0A06C505-0 4025 305
//@node 446C19DA-0 4530 200
//@node CCE83D6B-0 4325 305
//@node C5C9A7A1-0 4810 200
//@node 34851406-0 4585 305
//@node 3D2E066F-0 4380 405
//@node 9FDA7945-0 5090 200
//@node 60CCEC23-0 4885 305
//@node D1494AB5-0 4680 305
//@node 9DA3A803-0 4680 389
//@node DE67E206-0 5370 200
//@node 59F49267-0 5145 305
//@node 46A0842C-0 5650 200
//@node 32E3EBEE-0 5445 305
//@node 4BE8ED46-0 6210 40
//@node 39BE50C4-0 6490 40
//@node DC08F83D-0 6005 140
//@node 429C64E4-0 6490 40
//@node 07B5686D-0 6050 145
//@node A8980D3D-0 6280 145
//@node A78BB385-1 6770 200
//@node 359ADD4B-0 6545 305
//@node FB8A862C-1 7330 360
//@node A7A40A3D-0 7610 200
//@node 9957E07F-0 7890 40
//@node 5FAB95CF-0 8170 40
//@node 4BE8ED46-1 8450 40
//@node 0C6F9324-0 40 40
//@node 542252E1-0 330 40
//@node 2EE296B3-0 610 40
//@node AECCF32C-0 405 140
//@node 2EC6621F-0 200 140
//@node 962DE2DA-0 890 40
//@node D6C2552A-0 1170 40
//@node 5A52AF62-0 1450 40
//@node D6E02E8A-0 1225 145
//@node 0097E402-0 40 40
//@node 940F4033-0 330 40
//@node B39FC8F9-0 610 40
//@node 0F77AFD3-0 890 40
//@node AA7B7BC4-0 1170 40
//@node 9A20305B-0 1450 40
//@node 3916E3EB-0 40 40
//@node ADE64EBA-0 330 40
//@node 92108886-0 610 40
//@node 14F64907-0 890 40
//@node BEE67873-0 1170 40
//@node FC37537B-0 1450 40
//@node AC4D10CD-0 1225 145
//@node 08C47B74-0 40 40
//@node 61E91FB9-0 330 40
//@node 5A446043-0 610 40
//@node 7C56046F-0 890 40
//@node AFACF468-0 1170 40
//@node 53B686EE-0 1450 40
//@node 404140C2-0 1225 145
//@doomscript-blueprint end
