/***********************************************************************

ai_monster_flying_lostsoul.script

monster_flying_lostsoul

***********************************************************************/

#define LOSTSOUL_CHARGE_SPEED		440
#define LOSTSOUL_NORMAL_SPEED		140
#define LOSTSOUL_ATTACK_RATE		2
#define LOSTSOUL_CHARGE_RANGE_MAX	768
#define LOSTSOUL_CHARGE_RANGE_MIN	64
#define LOSTSOUL_NOFOVTIME			4

#define ATTACK_LOSTSOUL_CHARGE	ATTACK_SPECIAL1
#define ATTACK_LOSTSOUL_RETREAT	ATTACK_SPECIAL2

object monster_flying_lostsoul : monster_base {
	float		nextAttack;
	float		nextNoFOVAttack;
	float		noMeleeTime;
	float		fly_offset;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_charge();
	void		combat_melee();
	void		combat_retreat();

	void		init();
	
	// anim states
	void		Torso_Idle();
	void		Torso_Fly();
	void		Torso_Charge();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_flying_lostsoul::Torso_Idle() {
	playCycle( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
		}
		if ( AI_FORWARD ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fly", 4 );
		}
	}
}

void monster_flying_lostsoul::Torso_Fly() {
	playCycle( ANIMCHANNEL_TORSO, "fly" );
	
	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
		}
		if ( !AI_FORWARD ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
		}
	}
}

void monster_flying_lostsoul::Torso_Charge() {
	float dist;
	float endtime;
	
	playCycle( ANIMCHANNEL_TORSO, "charge" );	
	
	fadeSound ( SND_CHANNEL_VOICE2, 0, 0 );
	startSound( "snd_charge", SND_CHANNEL_VOICE2, false );
	
	dist = distanceTo( getEnemy() ) + 256;
	endtime = sys.getTime() + dist / LOSTSOUL_CHARGE_SPEED;
	while( !AI_PAIN && ( sys.getTime() < endtime ) ) {
		if ( sys.influenceActive() ) {
			break;
		}
		if ( testMeleeAttack() ) {
			attackMelee( "melee_lostsoul_charge" );
			break;
		}
		waitFrame();
	}
	
	attackEnd();
	fadeSound ( SND_CHANNEL_VOICE2, -60, 1 );
	finishAction( "charge_attack" );

	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_flying_lostsoul::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_flying_lostsoul::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_flying_lostsoul::init
=====================
*/
void monster_flying_lostsoul::init() {
	fly_offset = getFloatKey( "fly_offset" );
	setState( "state_Begin" );
}

/*
=====================
monster_flying_lostsoul::state_Begin
=====================
*/
void monster_flying_lostsoul::state_Begin() {
	setMoveType( MOVETYPE_FLY );
	noMeleeTime	= 0;
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );

	monster_begin();
	setState( "state_Idle" );
}

/*
=====================
monster_flying_lostsoul::state_Idle
=====================
*/
void monster_flying_lostsoul::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;
	
	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_flying_lostsoul::do_attack
=====================
*/
void monster_flying_lostsoul::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + LOSTSOUL_NOFOVTIME;
	if ( attack_flags & ATTACK_LOSTSOUL_RETREAT ) {
		combat_retreat();
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_LOSTSOUL_CHARGE ) {
		combat_charge();
	}
}

/*
=====================
monster_flying_lostsoul::check_attacks
=====================
*/
float monster_flying_lostsoul::check_attacks() {
	float range;
	float currentTime;
	float attack_flags;
	
	attack_flags = 0;	
	currentTime = sys.getTime();

	if ( currentTime >= noMeleeTime ) {
		if ( testMeleeAttack() ) {
			attack_flags |= ATTACK_MELEE;
		}
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		range = enemyRange2D();
		if ( range < 40 ) {
			attack_flags |= ATTACK_LOSTSOUL_RETREAT;
		}

		if ( ( range < LOSTSOUL_CHARGE_RANGE_MAX ) && ( !canReachEnemy() || ( currentTime >= nextAttack ) ) ) {
			if ( testChargeAttack() ) {
				attack_flags |= ATTACK_LOSTSOUL_CHARGE;
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_flying_lostsoul::combat_charge
=====================
*/
void monster_flying_lostsoul::combat_charge() {
	vector vel;

	// rise up a bit
	setFlyOffset( fly_offset + 200 );
	sys.wait( 0.5 );
	faceEnemy();

	// determin direction to enemy
	vector pos = getEnemyEyePos();
	vector org = getOrigin();
	vector forward = pos - org;
	forward_z = 0;
	forward = sys.vecNormalize( forward );

	animState( ANIMCHANNEL_TORSO, "Torso_Charge", 4 );

	// set speed and height
	vel = forward * LOSTSOUL_CHARGE_SPEED;
	setFlyOffset( fly_offset );
	setFlySpeed( LOSTSOUL_CHARGE_SPEED );

	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_Charge" ) ) {
		// do a dive bomb run
		org = getOrigin();
		vel_z = -( org_z - pos_z + 16 ) * 3;
		setLinearVelocity(vel);
		waitFrame();
	}

	// restore the fly speed
	setFlySpeed( LOSTSOUL_NORMAL_SPEED );

	// don't attack for a bit
	nextAttack = DelayTime( LOSTSOUL_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + LOSTSOUL_NOFOVTIME;
	
	// don't allow melee for a bit so that charge attacks don't cause double damage
	noMeleeTime = sys.getTime() + 1;
}

/*
=====================
monster_flying_lostsoul::combat_melee
=====================
*/
void monster_flying_lostsoul::combat_melee() {
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 4 );
	waitAction( "melee_attack" );
}

/*
=====================
monster_flying_lostsoul::combat_retreat
=====================
*/
void monster_flying_lostsoul::combat_retreat() {
	float endtime;

	moveOutOfRange( getEnemy(), enemyRange2D() + 256 );
	endtime = sys.getTime() + 1;
	while( endtime < sys.getTime() ) {
		if ( AI_MOVE_DONE ) {
			break;
		}
		waitFrame();
	}
}

//@doomscript-blueprint begin 6
//@source 4D18504F
//@catalog 0C260740
//@node 3E0AE6AD-0 40 40
//@node 8D317F1D-0 330 40
//@node 03FD32A6-0 610 40
//@node 27521106-0 890 200
//@node EED7C984-0 685 305
//@node 496AEE37-0 1170 360
//@node B41C2C99-0 1450 200
//@node 56350370-0 1245 305
//@node AD9DD442-0 1730 360
//@node 0F4BFBE4-0 40 40
//@node 0FC31F6B-0 330 40
//@node AC6CC2F9-0 610 40
//@node 8361FE7D-0 890 200
//@node A44B64AB-0 685 305
//@node E5BB94C4-0 1170 360
//@node 3C050901-0 1450 200
//@node 1E043C0F-0 1245 305
//@node 676CCE51-0 1040 305
//@node 209F894A-0 1730 360
//@node BECFF4FF-0 40 40
//@node BEAA98F5-0 330 40
//@node 14E9C7E6-0 125 232
//@node A04CB1CD-0 -80 232
//@node A36CD970-0 610 40
//@node 837CDC79-0 890 40
//@node 9CC1FC54-0 1170 40
//@node 013B0D64-0 965 145
//@node C488F693-0 1450 40
//@node 9FB85896-0 1245 145
//@node 796DC676-0 1040 145
//@node 49B47FFD-0 1730 40
//@node BD8B70D2-0 1525 145
//@node CC67A727-0 1320 145
//@node 241A351C-0 1320 229
//@node 46FF3D62-0 2010 200
//@node 450BDC83-0 1785 305
//@node C69C01AC-0 2290 360
//@node E87F66BC-0 2570 200
//@node 43046320-0 2345 305
//@node E5D61D50-0 2850 360
//@node C69C01AC-1 3130 360
//@node C94D1FBD-0 3410 200
//@node ED4586EC-0 3690 40
//@node FAC99BE0-0 3970 40
//@node F8BB5677-0 4250 40
//@node 9BEAE907-0 4530 40
//@node 3045C08B-0 40 40
//@node 55CB5B50-0 330 40
//@node 3D688D07-0 105 145
//@node 42215E4E-0 610 40
//@node 3675BEB0-0 405 232
//@node 1EDD1E5A-0 890 40
//@node ED5E41E5-0 685 145
//@node 62AE7B82-0 1170 40
//@node D92AED57-0 730 145
//@node 9B196A87-0 960 145
//@node EAE02238-0 1450 200
//@node 1551AF8E-0 1245 305
//@node A2E5EAAB-0 1730 360
//@node 3E7D7342-0 1505 465
//@node 5FDE7804-0 2010 360
//@node CA354FC2-0 1805 465
//@node D3C1D9E7-0 1600 465
//@node D817FF06-0 1600 549
//@node 19BFD265-0 2290 520
//@node 74360649-0 2570 200
//@node C6E2368A-0 2850 40
//@node F3EC3FE9-0 3130 40
//@node 1447DE29-0 40 40
//@node 79698CD3-0 330 40
//@node B287454E-0 610 40
//@node 1B2F3EF3-0 170 145
//@node CB2471C3-0 400 145
//@node 3D249433-0 890 200
//@node 294C7899-0 1170 40
//@node C7C70AA9-0 1450 40
//@node 17295E79-0 40 40
//@node 9FA2123E-0 330 40
//@node E124F467-0 105 145
//@node EB652F54-0 -100 245
//@node 4D9F911D-0 -305 245
//@node 9D8456A7-0 610 40
//@node CC8ECC66-0 40 40
//@node 4B1A9A12-0 330 40
//@node 7A144539-0 610 40
//@node 512048F2-0 405 145
//@node F20F636C-0 890 40
//@node 5A179338-0 1170 40
//@node 429E94D3-0 1450 40
//@node ACBFCA6B-0 40 40
//@node 951EBC7B-0 330 40
//@node E57E8393-0 610 40
//@node D801C7DE-0 405 145
//@node 7EF4C333-0 890 40
//@node 98F48FDB-0 685 145
//@node AC7C9738-0 1170 40
//@node C19F3727-0 40 40
//@node 082E71E6-0 330 40
//@node FA7F50FB-0 125 145
//@node 926A9FB1-0 610 40
//@node D606F70E-0 405 145
//@node 5AC58A95-0 890 200
//@node 35BD11B7-0 1170 200
//@node 5D99C7A2-0 965 305
//@node 9351CE08-0 1450 200
//@node 1A4855BD-0 1730 200
//@node 0F7064D9-0 1525 305
//@node B8AB1DC8-0 2010 200
//@node B6C8CE0F-0 40 40
//@node 975ADB9A-0 330 40
//@node FF708B2D-0 125 145
//@node 86F7B691-0 610 40
//@node 15100D37-0 385 145
//@node FA56A6AA-0 890 40
//@node 643A369C-0 685 145
//@node E898596C-0 480 145
//@node 11287AA0-0 480 229
//@node A2DF93B4-0 1170 200
//@node 46C3BBC6-0 945 305
//@node DE9F8D77-0 1450 360
//@node 0914FC54-0 1730 40
//@node 698828D3-0 1525 145
//@node 21DA56D1-0 1320 145
//@node 5C5175D2-0 1320 229
//@node 9C78A6EE-0 1320 145
//@node DE905E59-0 2010 200
//@node 47559F2A-0 1785 305
//@node E877AECC-0 2290 200
//@node 59A3D582-0 2085 305
//@node AC1EDDFD-0 1880 305
//@node 48758678-0 2570 360
//@node 011F924F-0 2850 200
//@node BE88A233-0 2645 305
//@node 63E067DF-0 2440 305
//@node 43C2062A-0 2440 389
//@node 054B70A7-0 2440 473
//@node 6A384F34-0 3130 360
//@node D26910FA-0 2905 465
//@node 2A5FBC2D-0 3410 520
//@node D010600E-0 3690 40
//@node 1B9AFE04-0 40 40
//@node 1C331F7E-0 330 40
//@node FFB08184-0 125 140
//@node 66E51C16-0 -80 140
//@node 808E70B9-0 610 40
//@node 3BA96A63-0 890 40
//@node 92A29487-0 1170 40
//@node 9E091A9E-0 965 145
//@node 14D87946-0 1450 40
//@node 62B45174-0 1225 145
//@node 14238DF2-0 1020 245
//@node CC3B9718-0 2570 40
//@node 48957255-0 2010 40
//@node BC87C64D-0 1805 145
//@node 70BDCE3A-0 1600 145
//@node BE595197-0 3130 40
//@node D630089A-0 2085 140
//@node A9FC20E8-0 3410 40
//@node A2E46838-0 2850 40
//@node 9E4A9E08-0 2625 145
//@node A899BAEE-0 3130 200
//@node CC809A82-0 2905 305
//@node AA6B9AD3-0 3410 200
//@node C53AFDFE-0 3205 305
//@node 221E65E7-0 4530 200
//@node 24E5ACDC-0 3485 300
//@node CF71D570-0 4810 200
//@node F1CB3591-0 5090 40
//@node E28E378E-0 4530 40
//@node FCA65DFB-0 4305 145
//@node 4D7F113D-0 4810 40
//@node BC447956-0 4605 145
//@node 835F659A-0 5090 40
//@node 50B22113-0 4885 145
//@node 3E273D34-0 40 40
//@node 7C6F41CB-0 330 40
//@node 9C79284C-0 610 40
//@node DA054D52-0 890 40
//@node 61A990B3-0 40 40
//@node E0F2F1E1-0 330 40
//@node 503835B9-0 610 40
//@node 3B956938-0 405 145
//@node 5D9AD084-0 890 40
//@node 6F4AB929-0 665 145
//@node 72C65E74-0 1170 200
//@node 8BB8A51F-0 965 305
//@node C78443FC-0 1450 360
//@node 546890A1-0 1730 200
//@doomscript-blueprint end
