/***********************************************************************

ai_monster_demon_pinky.script

monster_demon_pinky

***********************************************************************/

#define PINKY_ROAR_RATE			5
#define PINKY_DODGE_RATE		5

object monster_demon_pinky : monster_base {
	float		nextDodge;
	float		nextRoar;
	entity		combat_node;
	
	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_roar();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_Roar();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_Run();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_pinky::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	eachFrame {
		if ( AI_PAIN ) { animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
	}
}

void monster_demon_pinky::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_pinky::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_pinky::Torso_Roar() {
	disablePain();

	playAnim( ANIMCHANNEL_TORSO, "roar" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "roar" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_pinky::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "idle" );

	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
	}
}

void monster_demon_pinky::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_pinky::Legs_Run() {
	playCycle( ANIMCHANNEL_LEGS, "run" );
	
	eachFrame {
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 ); }
	}
}

void monster_demon_pinky::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void monster_demon_pinky::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_pinky::init
=====================
*/
void monster_demon_pinky::init() {
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_pinky::state_Begin
=====================
*/
void monster_demon_pinky::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );

	monster_begin();

	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_demon_pinky::state_Idle
=====================
*/
void monster_demon_pinky::state_Idle() {
	wait_for_enemy();

	nextRoar	= RandomTime( PINKY_ROAR_RATE );
	nextDodge	= RandomTime( PINKY_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_pinky::do_attack
=====================
*/
void monster_demon_pinky::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_roar();
	}
}

/*
=====================
monster_demon_pinky::check_attacks
=====================
*/
float monster_demon_pinky::check_attacks() {
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( AI_ENEMY_IN_FOV ) {
		if ( currentTime >= nextRoar ) {
			attack_flags |= ATTACK_MISSILE;
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_pinky::combat_roar
=====================
*/
void monster_demon_pinky::combat_roar() {
	faceEnemy();
	stopMove();

	animState( ANIMCHANNEL_TORSO, "Torso_Roar", 4 );
	waitAction( "roar" );

	// don't roar for a bit
	nextRoar = DelayTime( PINKY_ROAR_RATE );
}

/*
=====================
monster_demon_pinky::combat_melee
=====================
*/
void monster_demon_pinky::combat_melee() {
	stopMove();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
}

/*
=====================
monster_demon_pinky::combat_dodge_left
=====================
*/
void monster_demon_pinky::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( PINKY_DODGE_RATE );
}

/*
=====================
monster_demon_pinky::combat_dodge_right
=====================
*/
void monster_demon_pinky::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( PINKY_DODGE_RATE );
}

//@doomscript-blueprint begin 6
//@source 8B6A26E7
//@catalog 0C260740
//@node F7B8CCD7-0 40 40
//@node 4D735E4C-0 330 40
//@node ADE547C8-0 610 40
//@node 91E00052-0 890 200
//@node 34B6B3AB-0 685 305
//@node F9CA669E-0 480 305
//@node F1C9AB69-0 40 40
//@node 1BAEF8FE-0 330 40
//@node 866A5CAA-0 105 145
//@node F072A460-0 610 40
//@node 09DE0720-0 405 232
//@node 010EBC94-0 890 40
//@node 32B969F3-0 685 145
//@node 886466E4-0 1170 40
//@node 5A425D8B-0 730 145
//@node E7D4771B-0 960 145
//@node 74595632-0 1450 200
//@node 1350896F-0 1245 305
//@node D5233F39-0 1730 360
//@node FF5EBAC9-0 1505 465
//@node 38F526EE-0 2010 360
//@node CB023C99-0 1805 465
//@node 2050E4D8-0 1600 465
//@node 4422D5FB-0 1600 549
//@node 97E1B5AB-0 2290 520
//@node 2E95C51F-0 2570 200
//@node D39C07C4-0 2850 40
//@node DDF51D47-0 3130 40
//@node 50EAA28F-0 40 40
//@node 14553F71-0 330 40
//@node 48985FCC-0 610 40
//@node 6D5CF286-0 170 145
//@node B6B0E4D6-0 400 145
//@node 4B392F71-0 890 200
//@node 65FAC223-0 1170 40
//@node 1BACE72B-0 1450 40
//@node 4733ACC1-0 40 40
//@node ED4134A1-0 330 40
//@node 375395E2-0 610 40
//@node 8C605FD6-0 890 40
//@node 8FD26530-0 450 145
//@node 69BECE20-0 680 145
//@node BA04C55F-0 1170 200
//@node E3C6C0B8-0 1450 40
//@node 5506A725-0 1730 40
//@node A83B189F-0 40 40
//@node 592DE32E-0 330 40
//@node 7CC54AC6-0 610 40
//@node C29308AF-0 890 200
//@node 78B216AE-0 685 305
//@node B9E05893-0 480 305
//@node 34F71A9C-0 480 389
//@node 7300AA42-0 1170 200
//@node E37DBEA9-0 965 305
//@node 9ABBFFB7-0 760 305
//@node 25687194-0 40 40
//@node 7508AB67-0 330 40
//@node 994A2831-0 610 40
//@node 85250942-0 890 200
//@node 478C18BA-0 685 305
//@node 9D4726CB-0 480 305
//@node E74655A4-0 480 389
//@node 2745943D-0 1170 200
//@node FD0B8E44-0 965 305
//@node 1A935ED4-0 760 305
//@node 18AFD796-0 40 40
//@node 3AF5C489-0 330 40
//@node B17ECF6C-0 125 232
//@node 8B1B148B-0 -80 232
//@node E6F53961-0 610 40
//@node D3B06A89-0 890 200
//@node 14241311-0 685 305
//@node D7086DC9-0 480 305
//@node C7DA4446-0 480 389
//@node 7892B837-0 1170 200
//@node 31B08F50-0 965 305
//@node 21625526-0 760 305
//@node BF93DD75-0 40 40
//@node D5B2FDD5-0 330 40
//@node B1FFBE16-0 610 40
//@node D062AABB-0 170 145
//@node A230C44B-0 400 145
//@node 8B344E23-0 890 200
//@node A9FBB1C3-0 1170 40
//@node BD492293-0 1450 40
//@node 9468AC8E-0 40 40
//@node 90FC22B3-0 330 40
//@node 3C58DCF9-0 610 40
//@node 0641C99E-0 170 145
//@node 72ABD14E-0 400 145
//@node EFFC167A-0 890 200
//@node AEF66E0C-0 1170 40
//@node 3DA20096-0 1450 40
//@node D1084313-0 40 40
//@node 417063D9-0 330 40
//@node BE6070FC-0 40 40
//@node 33EABD4E-0 330 40
//@node 0A5D7B00-0 610 40
//@node 52038AD2-0 890 40
//@node F3F69D6A-0 1170 40
//@node C954CE39-0 1450 40
//@node D9D6EDA1-0 40 40
//@node E136F875-0 330 40
//@node 54B2EDEF-0 610 40
//@node DE2B7720-0 385 145
//@node C3766D2D-0 890 40
//@node 96508D00-0 665 145
//@node 39927182-0 1170 40
//@node 301F2649-0 40 40
//@node 86F18B33-0 330 40
//@node 05362A1D-0 125 145
//@node 6DEDE9C1-0 610 200
//@node DC608DEF-0 890 200
//@node 24EE12F1-0 685 305
//@node 018A9964-0 1170 200
//@node 76F04FB8-0 1450 200
//@node 936513D9-0 1245 305
//@node D7219D77-0 1730 200
//@node F8A10EED-0 1525 300
//@node B703DB7D-0 2010 200
//@node BD9F7D64-0 1805 305
//@node 50D9AFBA-0 2290 200
//@node 8D4AF6F1-0 2570 200
//@node 9DF7BCD1-0 2365 305
//@node A018F932-0 2850 200
//@node D3BDC5E5-0 40 40
//@node 13D13B3C-0 330 40
//@node 78E0E855-0 125 145
//@node F8504EBF-0 610 40
//@node BD6C609F-0 385 145
//@node 32F9D56F-0 890 40
//@node F0DE580D-0 665 145
//@node 655275F0-0 1170 40
//@node 7270505B-0 965 145
//@node 9836F491-0 760 145
//@node 8FE162F8-0 1450 200
//@node 673F0E09-0 1245 305
//@node C7B50BCB-0 1040 305
//@node E2972C20-0 1040 389
//@node 21C9E4D7-0 1040 389
//@node 05D5A52B-0 1730 360
//@node 8F28EE5B-0 1505 465
//@node B33579C2-0 2010 520
//@node FE2314D2-0 2290 360
//@node 13FB0292-0 2065 465
//@node ED97F6E7-0 2570 520
//@node CD0AF85B-0 2850 520
//@node 9303D69B-0 2645 625
//@node BE206608-0 2440 625
//@node A3529F7E-0 3130 680
//@node AAFFF111-0 2925 785
//@node DCEC97BD-0 3410 840
//@node 3C3FCF30-0 3970 840
//@node FAB4E02E-0 4250 200
//@node 0BA02520-0 4025 305
//@node D504E2D4-0 4530 200
//@node 100072D0-0 4325 305
//@node 137B86E6-0 4810 360
//@node CFFAD4FB-0 5090 40
//@node 280DBD65-0 4885 145
//@node 50ED4349-0 5370 200
//@node 5263A918-0 5650 40
//@node ACA48D9B-0 5445 145
//@node 60259A13-0 5930 200
//@node F99A5A8D-0 5725 305
//@node 2A6F7D1C-0 5520 305
//@node 79D1FA99-0 5520 389
//@node B43CDB1D-0 6210 360
//@node 9A1DFAE8-0 6490 40
//@node 7A8F2EAA-0 40 40
//@node 697D95B1-0 330 40
//@node 30DE766F-0 610 40
//@node 323290B6-0 890 40
//@node A91B7EC1-0 1170 40
//@node 99EC5C7C-0 1450 40
//@node 2864F060-0 1225 145
//@node AD5B76B2-0 40 40
//@node 828A522F-0 330 40
//@node 02F05DDB-0 610 40
//@node F9E8C7DC-0 890 40
//@node F72BEABB-0 40 40
//@node 939A3EA2-0 330 40
//@node FDBF88BE-0 610 40
//@node 3C4C7355-0 890 40
//@node 9C133DAB-0 1170 40
//@node 0C02039B-0 1450 40
//@node AA8408BA-0 1225 145
//@node 92903F84-0 40 40
//@node 7018EA61-0 330 40
//@node 71F071DB-0 610 40
//@node 5FBCCC35-0 890 40
//@node 28CBA740-0 1170 40
//@node 179AFB64-0 1450 40
//@node D666EEB4-0 1225 145
//@doomscript-blueprint end
