/***********************************************************************

ai_monster_demon_mancubus.script

monster_demon_mancubus

***********************************************************************/

#define MANC_WALKTURN			65
#define MANC_ATTACK_RATE		1
#define MANC_MAX_SHOTS			5
#define MANC_MIN_SHOTS			1
#define MANC_NOFOVTIME			8

object monster_demon_mancubus : monster_base {
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;
	float		fire;
	
	// States
	void		state_Begin();
	void		state_Idle();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_mancubus::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	eachFrame {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
		}
		if ( fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_RangeAttack", 4 );
		}
	}
}

void monster_demon_mancubus::Torso_Pain() {
	string animname;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	while( !animDone( ANIMCHANNEL_TORSO, 8 ) ) {
		preventPain( 2 );
		waitFrame();
	}

	finishAction( "pain" );

	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 8 );
}

void monster_demon_mancubus::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_mancubus::Torso_RangeAttack() {
	float endtime;
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
		}
		waitFrame();
	}
	
	while( fire > 0 ) {
		playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
		while( ( fire > 0 ) && !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
			if ( AI_PAIN ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
			}
			waitFrame();
		}
		fire = fire - 1;
	}

	fire = 0;
	
	if ( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		setBlendFrames( ANIMCHANNEL_TORSO, 4 );
	}
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
		}
		waitFrame();
	}
	
	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
}

void monster_demon_mancubus::Torso_TurretAttack() {
	float endtime;
	
	playAnim( ANIMCHANNEL_TORSO, "range_attack_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
		}
		waitFrame();
	}
	
	fire = MANC_MIN_SHOTS + int( sys.random( MANC_MAX_SHOTS - MANC_MIN_SHOTS ) );
	while( fire > 0 ) {
		fire = fire - 1;
		playAnim( ANIMCHANNEL_TORSO, "range_attack_loop" );
		while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
			if ( AI_PAIN ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
			}
			waitFrame();

			if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
				break;
			}
		}
	}

	fire = 0;

	if ( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		setBlendFrames( ANIMCHANNEL_TORSO, 4 );
	}

	playAnim( ANIMCHANNEL_TORSO, "range_attack_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 3 );
		}
		waitFrame();
	}

	finishAction( "turret_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_demon_mancubus::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	eachFrame {
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk", 2 ); }
	}
}

void monster_demon_mancubus::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 2 ); }
	}
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_mancubus::init
=====================
*/
void monster_demon_mancubus::init() {
	walk_turn = MANC_WALKTURN;
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_mancubus::state_Begin
=====================
*/
void monster_demon_mancubus::state_Begin() {
	fire = 0;
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );
	setState( "state_Idle" );
}

/*
=====================
monster_demon_mancubus::state_Idle
=====================
*/
void monster_demon_mancubus::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_mancubus::do_attack
=====================
*/
void monster_demon_mancubus::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + MANC_NOFOVTIME;
	if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_demon_mancubus::check_attacks
=====================
*/
float monster_demon_mancubus::check_attacks() {
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			if ( canHitEnemyFromAnim( "range_attack_loop" ) ) {
				attack_flags |= ATTACK_MISSILE;
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_mancubus::combat_range
=====================
*/
void monster_demon_mancubus::combat_range() {
	float attack_flags;

	faceEnemy();
	if ( !AI_ENEMY_IN_FOV ) {
		sys.wait( 0.4 );
	}

	fire = MANC_MIN_SHOTS + int( sys.random( MANC_MAX_SHOTS - MANC_MIN_SHOTS ) );
	while( fire > 0 ) {
		if ( !canHitEnemyFromAnim( "range_attack_loop" ) ) {
			break;
		}
		if ( AI_PAIN ) {
			attack_flags = check_attacks();
			if ( attack_flags & ATTACK_MELEE ) {
				break;
			}
		}
		
		waitFrame();
	}

	fire = 0;
	while( !inAnimState( ANIMCHANNEL_TORSO, "Torso_Idle" ) ) {
		waitFrame();
	}

	// don't attack for a bit
	nextAttack = DelayTime( MANC_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + MANC_NOFOVTIME;
}

/*
=====================
monster_demon_mancubus::combat_melee
=====================
*/
void monster_demon_mancubus::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

//@doomscript-blueprint begin 6
//@source 42460EF7
//@catalog 0C260740
//@node 95D6050A-0 40 40
//@node 66ED2709-0 330 40
//@node 21C2432F-0 610 40
//@node 8BB170CB-0 890 200
//@node 2D901186-0 685 305
//@node D37FE341-0 1170 360
//@node D01F5A86-0 1450 200
//@node DAACCDAD-0 1245 305
//@node 647CF255-0 1730 360
//@node 651B0368-0 40 40
//@node 14EF0E45-0 330 40
//@node B82E7563-0 105 145
//@node 3699E433-0 610 40
//@node AE30A76B-0 405 232
//@node 75A920B5-0 890 40
//@node 33417C1E-0 450 145
//@node 6169A68E-0 680 145
//@node 7944C35A-0 1170 200
//@node 657E4EA4-0 1450 200
//@node F6455C41-0 1730 40
//@node 1093914E-0 2010 40
//@node 6A87F550-0 40 40
//@node 02A52714-0 330 40
//@node E1E6F52F-0 610 40
//@node 840FB64F-0 170 145
//@node F92C557F-0 400 145
//@node 760C66E4-0 890 200
//@node 6EFED8BC-0 1170 40
//@node 310A40F8-0 1450 40
//@node 887EE3F5-0 40 40
//@node 9DEEF41F-0 330 40
//@node A320BDB6-0 610 40
//@node D24650C2-0 170 145
//@node C1264012-0 400 145
//@node 1EC2070E-0 890 200
//@node A0934155-0 685 305
//@node 13E67040-0 1170 360
//@node 691A0653-0 1450 200
//@node 6D4E9ED5-0 1730 40
//@node 9BDE6F48-0 1525 145
//@node C7A83481-0 1320 145
//@node 355C47FF-0 2010 200
//@node 1F514271-0 2290 200
//@node 5424760F-0 2085 305
//@node 87CBABB0-0 1880 305
//@node 1EC2070E-1 2570 360
//@node 377D85D2-0 2365 465
//@node 13E67040-1 2850 520
//@node 691A0653-1 3130 360
//@node 11122AF0-0 3410 200
//@node 4524E44C-0 3205 305
//@node 613FD0F7-0 3000 305
//@node C7D42D5E-0 3690 40
//@node ED68FF91-0 3485 145
//@node 42D890CC-0 3970 40
//@node 19099E41-0 3530 145
//@node BDD24B71-0 3760 145
//@node 26C964D8-0 4250 200
//@node 8D9EA906-0 4530 40
//@node A320BDB6-1 4810 40
//@node D2991887-0 4370 145
//@node 3C75BA97-0 4600 145
//@node 1EC2070E-2 5090 200
//@node F4CE1ED7-0 4885 305
//@node 13E67040-2 5370 360
//@node 691A0653-2 5650 200
//@node F0522F6E-0 5930 40
//@node 6A1EF75D-0 6210 40
//@node B597ADBE-0 40 40
//@node 00111D56-0 330 40
//@node D6F4C073-0 610 40
//@node 86281598-0 170 145
//@node 9BECD468-0 400 145
//@node 62F4D6B7-0 890 200
//@node 930F6D1C-0 685 305
//@node 7271C0FD-0 1170 360
//@node 1EABC7A2-0 1450 200
//@node 9E1859C4-0 1730 40
//@node AA29DC59-0 1505 145
//@node 89BB575E-0 2010 40
//@node E3DB9BB8-0 1805 145
//@node 1FF5D36F-0 1600 145
//@node 9E2801C3-0 2290 200
//@node 8D6E3656-0 2085 305
//@node BDB6050B-0 1880 305
//@node 0D366448-0 2570 200
//@node D6F4C073-1 2850 200
//@node 67F60B35-0 2410 305
//@node DB142445-0 2640 305
//@node 62F4D6B7-1 3130 360
//@node 5AC52817-0 2925 465
//@node 7271C0FD-1 3410 520
//@node 1EABC7A2-1 3690 360
//@node 679B254F-0 3970 360
//@node 54BFFE21-0 3530 465
//@node 7A2DCED1-0 3760 465
//@node F26056C5-0 4250 520
//@node DC0ACFAF-0 4530 40
//@node 1C635F0C-0 4325 145
//@node 40EC2FFD-0 4810 40
//@node 7360ED5D-0 4370 145
//@node 8444FCAD-0 4600 145
//@node 9384665F-0 5090 200
//@node 69615CEF-0 5370 40
//@node 42F4D0FF-0 5650 40
//@node 096C2687-0 5210 145
//@node 37D27E37-0 5440 145
//@node 62F4D6B7-2 5930 200
//@node 67BE0512-0 5725 305
//@node 7271C0FD-2 6210 360
//@node 1EABC7A2-2 6490 200
//@node 986F4D3A-0 6770 40
//@node AB76A524-0 7050 40
//@node D252A63C-0 40 40
//@node C86ECCA1-0 330 40
//@node 8747E2DB-0 610 40
//@node 5D20CA2D-0 890 200
//@node 1F8C238D-0 685 305
//@node EA3E2933-0 480 305
//@node A1A01DA3-0 40 40
//@node 171E648E-0 330 40
//@node EDFF468C-0 610 40
//@node 1AE54FDC-0 890 200
//@node 082A79A6-0 685 305
//@node D7B4572E-0 480 305
//@node C901ABEE-0 40 40
//@node CBBBD54A-0 330 40
//@node 4C93C3AA-0 125 145
//@node 4A60F8EA-0 610 40
//@node D7E6858F-0 40 40
//@node 5924B3D4-0 330 40
//@node 4649A78A-0 125 145
//@node 66E2DE0B-0 610 40
//@node FFEBD405-0 890 40
//@node 1998DDE3-0 1170 40
//@node 2DB5EE91-0 1450 40
//@node D14D51CA-0 1730 40
//@node 843CB76C-0 40 40
//@node FAA65C08-0 330 40
//@node 2CE9572A-0 610 40
//@node 9129BC62-0 405 145
//@node 298356E8-0 890 40
//@node 28FFBB74-0 685 145
//@node 614D4C53-0 1170 40
//@node 5E2F468A-0 40 40
//@node EBD82705-0 330 40
//@node 099B43BD-0 125 145
//@node 2B181B8C-0 610 40
//@node C7BE2CD4-0 405 145
//@node 935B5A18-0 890 200
//@node 25A67841-0 685 300
//@node 274BF4AE-0 1170 200
//@node A5213027-0 965 305
//@node B969A1F5-0 1450 200
//@node 57C44E5E-0 1730 200
//@node 36571578-0 1525 305
//@node 748C98DE-0 2010 200
//@node 8F8E3AEE-0 40 40
//@node 4AEB6845-0 330 40
//@node 83928473-0 125 145
//@node 7220C9CE-0 610 40
//@node A8F601A3-0 385 145
//@node BE953ED8-0 890 40
//@node 3805C722-0 665 145
//@node 0F5A33F9-0 1170 40
//@node 52F06135-0 965 145
//@node 8BE486ED-0 760 145
//@node C273D949-0 1450 200
//@node B8FDC66F-0 1225 305
//@node 3E338AD9-0 1730 200
//@node 51AB81F5-0 1525 305
//@node DAED2823-0 2010 360
//@node 933197B0-0 2290 40
//@node 99ED15FE-0 2085 145
//@node 35596034-0 2570 200
//@node 7A94012D-0 2850 40
//@node DB6DDDDA-0 2645 145
//@node A688F4CA-0 2440 145
//@node F22E75CB-0 2440 229
//@node 4B7F7CA3-0 2440 145
//@node 9FC6A266-0 3130 200
//@node 98D968E4-0 2925 305
//@node E7705E23-0 2720 305
//@node AB61E9EC-0 2720 389
//@node C7F0CD52-0 3410 360
//@node C6C1D118-0 3185 465
//@node 3C6B1CAC-0 3690 520
//@node 1B3FBAD5-0 3970 40
//@node C4091CCE-0 40 40
//@node D82C8705-0 330 40
//@node 1BB9E9EE-0 610 40
//@node 165F8C7F-0 405 145
//@node 5AF4B30F-0 200 145
//@node 02AC1A4A-0 890 200
//@node 3338AC10-0 1170 40
//@node CBD7993B-0 945 145
//@node B90B2B4E-0 1450 40
//@node 42DFED7B-0 1245 145
//@node FC59DB20-0 1040 145
//@node 44953117-0 1730 200
//@node BD781E0C-0 1290 305
//@node B8C073FC-0 1520 305
//@node 68808A61-0 2010 360
//@node B429433F-0 2290 200
//@node A075163C-0 2085 305
//@node 47FB29B8-0 2570 360
//@node 781A5516-0 2345 465
//@node 50BBD0CD-0 2850 360
//@node 5F59B620-0 2645 465
//@node 55830FD6-0 2440 465
//@node 68808A61-1 3130 520
//@node CB6C7872-0 3410 200
//@node 5B5F7063-0 3690 40
//@node BAEFE1D8-0 3485 145
//@node 38F3FC35-0 3970 40
//@node 7406D8F6-0 3530 145
//@node 60853386-0 3760 145
//@node CB6C7872-1 4250 200
//@node B99EA420-0 4530 40
//@node F751297C-0 4305 145
//@node A6CC9473-0 4810 40
//@node 6BD11BC6-0 4605 145
//@node 4183E667-0 40 40
//@node D6557132-0 330 40
//@node 3922511A-0 610 40
//@node 44D1FDBE-0 890 40
//@node 91E2BA2D-0 1170 40
//@node EB375A42-0 1450 40
//@doomscript-blueprint end
