/***********************************************************************

ai_monster_turret.script

monster_turret

***********************************************************************/

#define TURRET_FIRE_RATE		0.1
#define TURRET_MIN_ATTACK_TIME	1.5
#define TURRET_SHUTDOWN_TIME	4

object monster_turret : monster_base {
	boolean		fire;
	boolean		attack_monsters;
	entity		light;
	boolean		light_is_on;
	float		attackTime;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();
	void		state_Combat();
	void		state_Killed();
	boolean		checkForEnemy( float use_fov );

	//
	// actions
	//
	void		combat_attack();

	void		init();
	void		destory();

	void		spawn_light();
	void		light_off();
	void		light_on();
	
	// anim states
	void		Torso_Death();
	void		Torso_Idle();
	void		Torso_Attack();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_turret::Torso_Death() {
	finishAction( "dead" );

	// never exit
	waitUntil( 0 );
}

void monster_turret::Torso_Idle() {
	playCycle( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Attack", 0 );
		}
	}
}

void monster_turret::Torso_Attack() {
	float soundLen;

	playCycle( ANIMCHANNEL_TORSO, "idle" );

	soundLen = startSound( "snd_windup", SND_CHANNEL_BODY, false );
	soundLen += sys.getTime();
	while( sys.getTime() < soundLen ) {
		waitFrame();
	}

	attackTime = sys.getTime() + TURRET_MIN_ATTACK_TIME;
	while( fire || ( sys.getTime() < attackTime ) ) {
		if ( sys.influenceActive() ) {
			break;
		}
		startSound( "snd_fire", SND_CHANNEL_WEAPON, false );
		attackMissile( "barrel" );
		sys.wait( TURRET_FIRE_RATE );
	}
	
	soundLen = startSound( "snd_winddown", SND_CHANNEL_BODY2, false );
	soundLen += sys.getTime();
	while( sys.getTime() < soundLen ) {
		waitFrame();
	}

	finishAction( "attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_turret::init
=====================
*/
void monster_turret::init() {
	float team;

	// don't take damage
	ignoreDamage();

	// can't move, so only fire on sight
	ambush = true;

	team = getFloatKey( "team" );
	if ( team != 1  ) {
		attack_monsters = true;
	}

	if ( getIntKey( "light" ) ) {
		spawn_light();
	}

	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	setState( "state_Begin" );
}

/*
=====================
monster_turret::destory
=====================
*/
void monster_turret::destory() {
	light.remove();
}

/*
=====================
monster_turret::spawn_light
=====================
*/
void monster_turret::spawn_light() {
	string texture;
	float distance;

	distance = getFloatKey( "light_distance" );
	if ( !distance ) {
		distance = 640;
	}
	
	// spot light
	sys.setSpawnArg( "light_target", "1 0 0" );
	sys.setSpawnArg( "light_up", "0 0 .5" );
	sys.setSpawnArg( "light_right", "0 -.5 0" );	
	sys.setSpawnArg( "light_end", distance + " 0 0" );

	texture = getKey( "mtr_light" );
	sys.setSpawnArg( "texture", texture );

	sys.setSpawnArg( "name", getName() + "_light" );
	light = sys.spawn( "light" );
	light.setAngles( getAngles() );
	//light.bindToJoint( self, "light", true );
	light.bindToJoint( self, "flash", true );
	light.setOrigin( '0 0 0' );

	light_off();
}

/*
=====================
monster_turret::light_off
=====================
*/
void monster_turret::light_off() {
	string skin;

	if ( light ) {
		light.Off();
		skin = getKey( "skin_light_off" );
		setSkin( skin );
		light_is_on = false;
	}
}
	
/*
=====================
monster_turret::light_on
=====================
*/
void monster_turret::light_on() {
	string skin;

	if ( light ) {
		light.On();
		skin = getKey( "skin_light_on" );
		setSkin( skin );
		light_is_on = true;
	}
}

/*
=====================
monster_turret::state_Begin
=====================
*/
void monster_turret::state_Begin() {
	setMoveType( MOVETYPE_STATIC );

	if ( getIntKey( "trigger" ) ) {
		setState( "state_Disabled" );
	} else {
		wait_for_enemy();
		setState( "state_Combat" );
	}
}

/*
=====================
monster_turret::state_Idle
=====================
*/
void monster_turret::state_Idle() {
	startSound( "snd_shutdown", SND_CHANNEL_VOICE, false );
	light_off();
	wait_for_enemy();
	setState( "state_Combat" );
}

/*
=====================
monster_turret::state_Disabled
=====================
*/
void monster_turret::state_Disabled() {
	entity enemy;

	startSound( "snd_shutdown", SND_CHANNEL_VOICE, false );

	lookAtEnemy( 0 );

	// wait till we stop firing and bullets are out of the air
	attackTime = 0;
	fire = false;
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_Attack" ) ) {
		waitFrame();
	}
	sys.wait( 0.2 );

	// tell all enemies to forget about us
	enemy = nextEnemy( $null_entity );
	while( !( !enemy ) ) {
		sys.print( sys.getTime() + ": clear enemy: " + enemy.getName() + "\n" );
		enemy.clearEnemy();
		enemy = nextEnemy( $null_entity );
	}

	// clear our enemy
	clearEnemy();

	// wait for trigger
	AI_ACTIVATED = false;
	while( !AI_ACTIVATED ) {
		waitFrame();
	}
	AI_ACTIVATED = false;

	setState( "state_Combat" );
}

/*
=====================
monster_turret::state_Killed
=====================
*/
void monster_turret::state_Killed() {
	stopMove();

	light_off();

	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	waitAction( "dead" );
	stopThinking();
}

/*
=====================
monster_turret::checkForEnemy
=====================
*/
boolean	monster_turret::checkForEnemy( float use_fov ) {
	entity enemy;

	enemy = findEnemy( false );
	if ( !enemy ) {
		if ( !attack_monsters ) {
			return false;
		}
        
		enemy = findEnemyAI( false );
		if ( !enemy ) {
			return false;
		}
	}

	setEnemy( enemy );
	return true;
}

/***********************************************************************

	Combat

***********************************************************************/

/*
=====================
monster_turret::state_Combat
=====================
*/
void monster_turret::state_Combat() {
	float shutdownTime;

	startSound( "snd_wakeup", SND_CHANNEL_VOICE, false );
	
	light_on();
	shutdownTime = sys.getTime() + TURRET_SHUTDOWN_TIME;
	eachFrame {
		lookAtEnemy( 1 );
		if ( AI_ENEMY_DEAD ) {
			enemy_dead();
			continue;
		}

		if ( AI_ACTIVATED ) {
			setState( "state_Disabled" );
			break;
		}

		if ( AI_ENEMY_VISIBLE ) {
			if ( canHitEnemyFromJoint( "barrel" ) ) {
				combat_attack();
			} else {
				checkForEnemy( false );
			}
			shutdownTime = sys.getTime() + TURRET_SHUTDOWN_TIME;
		} else if ( !checkForEnemy( false ) ) {
			if ( shutdownTime < sys.getTime() ) {
				lookAtEnemy( 0 );
				clearEnemy();
				setState( "state_Idle" );
			}
		}
	}
}

/*
=====================
monster_turret::combat_attack
=====================
*/
void monster_turret::combat_attack() {
	faceEnemy();

	fire = true;
	while( AI_ENEMY_VISIBLE && canHitEnemyFromJoint( "barrel" ) ) {
		lookAtEnemy( 1 );
		waitFrame();
		if ( sys.influenceActive() ) {
			break;
		}
		if ( AI_ACTIVATED ) {
			setState( "state_Disabled" );
			break;
		}
	}
	fire = false;
}

//@doomscript-blueprint begin 6
//@source 0A5B1068
//@catalog 0C260740
//@node 2E43EAC6-0 40 40
//@node 90A41725-0 330 40
//@node C96B6D77-0 610 40
//@node 06ED408E-0 40 40
//@node D4293D0A-0 330 40
//@node B33DBE93-0 610 40
//@node C3C00106-0 890 200
//@node 51D41564-0 685 305
//@node 7379CB5A-0 1170 360
//@node 7A874630-0 40 40
//@node 2E009B04-0 330 40
//@node AE1060F5-0 610 40
//@node 60D0A7C3-0 385 145
//@node 9F35BCAB-0 890 40
//@node A7E983F7-0 685 145
//@node 25B637F1-0 480 145
//@node 666895BF-0 1170 40
//@node DC7DE146-0 965 145
//@node 94A1FD04-0 760 145
//@node C9668E2C-0 1450 200
//@node A18895DA-0 1730 40
//@node 0F9DE1FC-0 1525 145
//@node 18917D17-0 2010 40
//@node 93E4F6F6-0 1805 145
//@node 8E96BEDE-0 1600 145
//@node 3790F2CF-0 1600 229
//@node EF66D547-0 2290 200
//@node 127AA104-0 2065 305
//@node EF8ACC5F-0 2570 360
//@node 182E7550-0 2850 200
//@node BC56D6B2-0 3130 200
//@node A2D3A4C4-0 3410 200
//@node 03A90472-0 3690 40
//@node ABE95845-0 3465 145
//@node 9F35BCAB-1 3970 40
//@node 424EFB9E-0 3765 145
//@node A4B60998-0 3560 145
//@node 666895BF-1 4250 40
//@node CC925F8F-0 4045 145
//@node F1C842BD-0 3840 145
//@node C9668E2C-1 4530 200
//@node 9B524E25-0 4810 40
//@node DF075BF7-0 4605 140
//@node 7C6869AE-0 4400 140
//@node 9144703E-0 5090 40
//@node 7C15DEBA-0 40 40
//@node CFFE75AD-0 330 40
//@node 3243C1EF-0 610 40
//@node CA42D095-0 405 145
//@node 8B2F3A07-0 890 40
//@node 95EAF360-0 665 145
//@node 7F7D5677-0 460 245
//@node 8244D650-0 255 245
//@node 0E0D351A-0 1170 40
//@node 35175664-0 965 145
//@node 4BC2F8BA-0 760 145
//@node 0E3CEAD7-0 1450 200
//@node 49F56352-0 1245 305
//@node D10F622D-0 1730 40
//@node D1B7D25D-0 1505 145
//@node 669D376E-0 1300 245
//@node 3DB556E9-0 1095 245
//@node 59BDEE74-0 2010 200
//@node 2BD84C38-0 2290 40
//@node 7C3F891A-0 2570 40
//@node 420FD128-0 40 40
//@node C287603C-0 330 40
//@node 35C31E2C-0 40 40
//@node D2058212-0 330 40
//@node 71347F87-0 105 145
//@node E84510B2-0 610 40
//@node 932C9E72-0 405 145
//@node 8AE473EE-0 200 145
//@node 5335A870-0 890 200
//@node FE771ADC-0 685 305
//@node 13EACD07-0 1170 40
//@node 0675DB81-0 1450 40
//@node ABDBE46D-0 1730 40
//@node 6EF97D58-0 2010 40
//@node 8C9CEE78-0 1805 232
//@node 4DA8219E-0 1600 232
//@node BBDFAA6C-0 2290 40
//@node 614CEA48-0 2065 145
//@node E2D899AC-0 2570 40
//@node BEC591CB-0 2365 140
//@node F801F9C0-0 2160 140
//@node A02B6DA3-0 2365 232
//@node 96B0036D-0 2850 40
//@node B1A9DAA0-0 3130 40
//@node 88ECB234-0 2905 145
//@node 0CC60340-0 2700 245
//@node BA617ABD-0 2495 245
//@node 587C836D-0 3410 40
//@node C519F16E-0 3690 40
//@node A7E9C28E-0 3970 40
//@node 146FBD18-0 4250 40
//@node 3E56913E-0 40 40
//@node C42D2188-0 330 40
//@node 1FBD0052-0 125 145
//@node F97D82C1-0 610 200
//@node 7788F9A0-0 890 200
//@node 7E8AE631-0 665 305
//@node B3EE2E4C-0 1170 200
//@node 74CAEA32-0 965 300
//@node 7EDF1C3F-0 1450 200
//@node 506A7AF2-0 1245 305
//@node 1CC67584-0 40 40
//@node 04B1AFF2-0 330 40
//@node 7FA82930-0 125 145
//@node CB4C24D7-0 610 200
//@node 264E6852-0 890 200
//@node CA1A3DE1-0 665 305
//@node 06874AB6-0 1170 200
//@node DC553A11-0 965 300
//@node E6D4A62C-0 1450 200
//@node FAC5D80B-0 1245 305
//@node A0A1828B-0 40 40
//@node 7194B6B8-0 330 40
//@node 349DAC08-0 610 40
//@node 67C8BF3D-0 385 145
//@node F69B4E10-0 890 200
//@node 86A39CF7-0 1450 200
//@node 06BA6F54-0 1730 200
//@node 37547160-0 40 40
//@node A4AE7CAE-0 330 40
//@node 275AC7E4-0 610 40
//@node 542CA4D8-0 890 40
//@node 5B9F50E3-0 1170 40
//@node E728964E-0 40 40
//@node 1C2C6668-0 330 40
//@node AD3B1806-0 610 40
//@node 0C5C46AC-0 890 40
//@node 66D992F3-0 685 145
//@node 76404A86-0 1170 40
//@node 4EBB91C7-0 965 145
//@node 00516C8E-0 1450 40
//@node 82F0C3E7-0 1225 145
//@node A4055DB2-0 1730 200
//@node 95C47918-0 2010 40
//@node ADDE8E42-0 2290 40
//@node BF70F182-0 2065 145
//@node 1AAFAF2B-0 2570 40
//@node 822232DC-0 2365 145
//@node 1F9F7E5A-0 2160 145
//@node 1381E64B-0 2850 200
//@node BC1C4D5C-0 2645 300
//@node 839FB89C-0 2440 300
//@node BAED07BB-0 3130 200
//@node ADDE8E42-1 3410 200
//@node 8C27E0D9-0 3185 305
//@node 4B8C3F21-0 3690 40
//@node B4BD207C-0 3970 40
//@node A91522CB-0 3765 145
//@node 4BBC6223-0 4250 40
//@node 0E5DA124-0 4045 145
//@node 0661614C-0 3840 145
//@node A4055DB2-1 4530 200
//@node B4BD207C-1 4810 40
//@node DA836C84-0 4605 145
//@node 5734E5E1-0 5090 40
//@node 04A2254B-0 40 40
//@node 620115EA-0 330 40
//@node DA79F2A9-0 610 40
//@node BEFC3FED-0 890 40
//@node 831C99A2-0 1170 40
//@node 009B8339-0 1450 40
//@node 8595557D-0 40 40
//@node 88F70591-0 330 40
//@node 5A8CAC4E-0 105 145
//@node 1BA5E8E0-0 610 40
//@node 246C4490-0 405 145
//@node 398BDE82-0 200 145
//@node DD691046-0 890 200
//@node E8AA811B-0 685 305
//@node 3B40216F-0 480 305
//@node 4D6B4447-0 1170 360
//@node F6FEF6AB-0 1450 200
//@node DF48A7B4-0 1225 305
//@node 1BA5E8E0-1 1730 200
//@node 00E4F315-0 1525 305
//@node 4FB03EBD-0 1320 305
//@node 4D6B4447-1 2010 360
//@node E89A6B75-0 2290 40
//@node 8608F5C6-0 2085 140
//@node 1580A2A0-0 2570 40
//@node 9327375A-0 40 40
//@node 3296D337-0 330 40
//@node FD825684-0 610 40
//@node F5018B85-0 890 40
//@node 941DEA9B-0 685 145
//@node 1CB291E7-0 1170 40
//@node A202A3CF-0 1450 200
//@node 054E9BAC-0 1730 200
//@node 3050B9B7-0 1525 305
//@node ABAB19A1-0 2010 360
//@node 2A78F6A5-0 2290 360
//@node 2392FBB8-0 2570 200
//@node 8A7F64CC-0 2365 305
//@node B58EF601-0 2850 360
//@node 53BF7515-0 3130 360
//@node 303A8636-0 3410 200
//@node 3638D000-0 3205 305
//@node F872893A-0 3690 360
//@node 85948791-0 3465 465
//@node EEBCB5AB-0 3970 520
//@node B32BAA20-0 4530 520
//@node F5018B85-1 4810 360
//@node 58A2E0E6-0 4605 465
//@node 6F2A4113-0 5090 360
//@node A00DB249-0 4650 465
//@node 707FFB39-0 4880 465
//@node FFD6A020-0 5370 360
//@node 24F09E02-0 5145 465
//@node 26A5B006-0 5650 520
//@node F8FD5721-0 5930 520
//@node 95CA661F-0 6210 520
//@node 746B76DD-0 40 40
//@node E774F674-0 330 40
//@node A49E7360-0 610 40
//@node 42F35D24-0 405 145
//@node E389487F-0 890 40
//@node 08EFF78A-0 665 145
//@node 8C9A939C-0 1170 200
//@node 1A37697F-0 1450 200
//@node 7E123774-0 1730 200
//@node 2212A036-0 1505 305
//@node 4E509036-0 2010 360
//@node 1A45A9C7-0 2290 200
//@node 480F6030-0 2085 305
//@node EAC3E3E2-0 2570 360
//@node 4E509036-1 2850 360
//@node 581DAE07-0 3130 40
//@node 71E2BD3F-0 2925 145
//@doomscript-blueprint end
