/***********************************************************************

ai_monster_boss_vagary.script

monster_boss_vagary

***********************************************************************/

#define VAGARY_ATTACK_RATE			1.5
#define VAGARY_DODGE_RATE			4
#define	VAGARY_PAIN_DELAY			0.25
#define	VAGARY_TURRET_TO_IDLE		4
#define	VAGARY_THROW_SPEED			1200
#define VAGARY_THROW_SPEED2			( VAGARY_THROW_SPEED + 300 )
#define	VAGARY_THROW_DIST			200
#define VAGARY_THROW_MIN			'-512 -512 -512'
#define	VAGARY_THROW_MAX			'512 512 512'
#define VAGARY_THROW_OFFSET			64
#define VAGARY_NOFOVTIME			4

// anim blend times
#define	VAGARY_PAIN_TO_IDLE			2
#define VAGARY_PAIN_TO_PAIN			0
#define VAGARY_SIGHT_TO_IDLE		4
#define	VAGARY_MELEE_TO_IDLE		4
#define VAGARY_RANGE_TO_IDLE		4
#define VAGARY_DODGE_LEFT_TO_IDLE	4
#define	VAGARY_DODGE_RIGHT_TO_IDLE	4
#define VAGARY_WAIT_TO_OUT			4
#define	VAGARY_IN_TO_WAIT			4
#define	VAGARY_WALK_TO_WAIT			4
#define VAGARY_WALK_TO_ACTION		4
#define VAGARY_ACTION_TO_IDLE		4
#define VAGARY_WALK_TO_DODGE_LEFT	4
#define VAGARY_WALK_TO_DODGE_RIGHT	4
#define VAGARY_IDLE_TO_PAIN			0
#define VAGARY_IDLE_TO_WALK			4
#define VAGARY_IDLE_TO_SIGHT		4
#define VAGARY_WALK_TO_IDLE			4
#define VAGARY_WALK_TO_RANGEATTACK	4
#define VAGARY_IDLE_TO_RANGEATTACK	4
#define VAGARY_WALK_TO_MELEE		4
#define VAGARY_IDLE_TO_TURRETATTACK	4
#define VAGARY_TURRETATTACK_TO_IDLE	4

object monster_boss_vagary : monster_base {
	float		nextDodge;
	float		nextAttack;
	float		nextNoFOVAttack;
	entity		combat_node;
	entity		throwEntity;

	//
	// States
	//
	void		state_Begin();
	void		state_Idle();

	void		init();
	
	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_range();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();

	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_RangeAttack();
	void		Torso_TurretAttack();
	
	// legs anim states
	void		Legs_Idle();
	void		Legs_Walk();
	void		Legs_DodgeLeft();
	void		Legs_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_boss_vagary::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "stand" );
	
	while( !AI_PAIN ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Pain", VAGARY_IDLE_TO_PAIN );
}

void monster_boss_vagary::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + VAGARY_PAIN_DELAY;
	
	while( !animDone( ANIMCHANNEL_TORSO, VAGARY_PAIN_TO_IDLE ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", VAGARY_PAIN_TO_PAIN );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", VAGARY_PAIN_TO_IDLE );
}

void monster_boss_vagary::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, VAGARY_MELEE_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", VAGARY_MELEE_TO_IDLE );
}

void monster_boss_vagary::Torso_RangeAttack() {
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, VAGARY_RANGE_TO_IDLE ) ) {
		lookAtEnemy( 1 );	
		waitFrame();
	}

	finishAction( "range_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", VAGARY_RANGE_TO_IDLE );
}

void monster_boss_vagary::Torso_TurretAttack() {
	allowMovement( false );
	disablePain();
	faceEnemy();

	playAnim( ANIMCHANNEL_TORSO, "range_attack" );
	while( !animDone( ANIMCHANNEL_TORSO, VAGARY_TURRET_TO_IDLE ) ) {
		waitFrame();
	}

	finishAction( "turret_attack" );
	allowMovement( true );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void monster_boss_vagary::Legs_Idle() {
	idleAnim( ANIMCHANNEL_LEGS, "stand" );

	while( !AI_FORWARD ) {
	//while( 1 ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Walk", VAGARY_IDLE_TO_WALK );
}

void monster_boss_vagary::Legs_Walk() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	while( AI_FORWARD )	{
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", VAGARY_WALK_TO_IDLE );
}

void monster_boss_vagary::Legs_DodgeLeft() {
	playAnim( ANIMCHANNEL_LEGS, "evade_left" );

	while( !animDone( ANIMCHANNEL_LEGS, VAGARY_DODGE_LEFT_TO_IDLE ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", VAGARY_DODGE_LEFT_TO_IDLE );
}

void monster_boss_vagary::Legs_DodgeRight() {
	playAnim( ANIMCHANNEL_LEGS, "evade_right" );

	while( !animDone( ANIMCHANNEL_LEGS, VAGARY_DODGE_RIGHT_TO_IDLE ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", VAGARY_DODGE_RIGHT_TO_IDLE );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_boss_vagary::init
=====================
*/
void monster_boss_vagary::init() {
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_boss_vagary::state_Begin
=====================
*/
void monster_boss_vagary::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );		
	setState( "state_Idle" );
}

/*
=====================
monster_boss_vagary::state_Idle
=====================
*/
void monster_boss_vagary::state_Idle() {
	wait_for_enemy();

	nextAttack		= 0;
	nextNoFOVAttack = 0;
	nextDodge		= RandomTime( VAGARY_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_boss_vagary::do_attack
=====================
*/
void monster_boss_vagary::do_attack( float attack_flags ) {
	nextNoFOVAttack = sys.getTime() + VAGARY_NOFOVTIME;
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_MISSILE ) {
		combat_range();
	}
}

/*
=====================
monster_boss_vagary::check_attacks
=====================
*/
float monster_boss_vagary::check_attacks() {
	float currentTime;
	float canMelee;
	float attack_flags;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( ( ( sys.getTime() > nextNoFOVAttack ) && AI_ENEMY_VISIBLE ) || AI_ENEMY_IN_FOV ) {
		if ( !canReachEnemy() || ( currentTime >= nextAttack ) ) {
			if ( canHitEnemy() ) {
				throwEntity = vagary_ChooseObjectToThrow( VAGARY_THROW_MIN, VAGARY_THROW_MAX, VAGARY_THROW_SPEED, VAGARY_THROW_DIST, VAGARY_THROW_OFFSET );
				if ( throwEntity ) {
					attack_flags |= ATTACK_MISSILE;
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_boss_vagary::throw_object
=====================
*/
void monster_boss_vagary::throw_object( entity ent ) {
	vector	pos;
	float	waitTime;
	float	t;
	vector	offset;
	vector	vel;
	float	start_offset;

	pos = ent.getWorldOrigin();
	pos_z += VAGARY_THROW_OFFSET;

	startSound( "snd_pickup", SND_CHANNEL_WEAPON, false );

	ent.setAngularVelocity( '30 30 0' );
	waitTime = sys.getTime() + 0.5;
	start_offset = sys.getTime() + sys.random( 360 );
	while( sys.getTime() < waitTime ) {
		t = sys.getTime() - start_offset * 360 * 2;
		offset_z = sys.sin( t ) * 8;
		vel = ( pos - ent.getWorldOrigin() + offset) * 5;
		ent.setLinearVelocity( vel );
		sys.wait( GAME_FRAMETIME );
	}
	vagary_ThrowObjectAtEnemy( ent, VAGARY_THROW_SPEED2 );
}

/*
=====================
monster_boss_vagary::combat_range
=====================
*/
void monster_boss_vagary::combat_range() {
	float num;
	float i;

	faceEnemy();
	lookAt( throwEntity, 3 );
	sys.wait( 0.3 );

	thread throw_object( throwEntity );
	
	// throw up to 3 more
	num = sys.random( 4 );
	for( i = 1; i < num; i++ ) {
		throwEntity = vagary_ChooseObjectToThrow( VAGARY_THROW_MIN, VAGARY_THROW_MAX, VAGARY_THROW_SPEED, VAGARY_THROW_DIST, VAGARY_THROW_OFFSET );
		if ( !throwEntity ) {
			break;
		}
		thread throw_object( throwEntity );
	}

	sys.wait( 1 );

	lookAtEnemy( 1 );

	// don't attack for a bit
	nextAttack = DelayTime( VAGARY_ATTACK_RATE );
	nextNoFOVAttack = sys.getTime() + VAGARY_NOFOVTIME;
}

/*
=====================
monster_boss_vagary::combat_melee
=====================
*/
void monster_boss_vagary::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", VAGARY_WALK_TO_MELEE );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_boss_vagary::combat_dodge_left
=====================
*/
void monster_boss_vagary::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeLeft", VAGARY_WALK_TO_DODGE_LEFT );
	waitAction( "strafe" );
	nextDodge = DelayTime( VAGARY_DODGE_RATE );
}

/*
=====================
monster_boss_vagary::combat_dodge_right
=====================
*/
void monster_boss_vagary::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_LEGS, "Legs_DodgeRight", VAGARY_WALK_TO_DODGE_RIGHT );
	waitAction( "strafe" );
	nextDodge = DelayTime( VAGARY_DODGE_RATE );
}

//@doomscript-blueprint begin 6
//@source 21CDB099
//@catalog 0C260740
//@node 15E1770E-0 40 40
//@node 636AF63D-0 330 40
//@node 0AAAD946-0 610 40
//@node 44D26A87-0 405 145
//@node 9CF55F1D-0 200 145
//@node 0390CCCA-0 890 200
//@node D2C082A4-0 1170 40
//@node 2176BD6C-0 40 40
//@node 4EB5990F-0 330 40
//@node 8A5B1FC5-0 105 145
//@node 33BB17AF-0 610 40
//@node 3E845202-0 405 232
//@node 001E11DF-0 890 40
//@node 472F6AA2-0 685 145
//@node 71398573-0 1170 40
//@node 9491C8C4-0 730 145
//@node D4323154-0 960 145
//@node 63913081-0 1450 200
//@node B185805E-0 1245 305
//@node 50B488A6-0 1730 360
//@node A25FBC0F-0 1505 465
//@node C7124D33-0 2010 360
//@node 6CE8BAA1-0 1805 465
//@node FE107890-0 1600 465
//@node 471179F3-0 1600 549
//@node 5503AC24-0 2290 520
//@node 7963BEB0-0 2570 200
//@node E506C0ED-0 2850 40
//@node 61E49EE8-0 3130 40
//@node 7520BCCC-0 40 40
//@node 392593F0-0 330 40
//@node AE006C4F-0 610 40
//@node 2788CBD4-0 170 145
//@node EFD4D3A4-0 400 145
//@node 2A486778-0 890 200
//@node 61188B38-0 1170 40
//@node 7CBBB97A-0 1450 40
//@node C5321EB1-0 40 40
//@node CAC0AF89-0 330 40
//@node 0C24032C-0 610 40
//@node 9AB43C50-0 890 40
//@node 615274F3-0 1170 40
//@node 8E2BF976-0 730 145
//@node 8D3DA306-0 960 145
//@node DDEF3D04-0 1450 200
//@node 9A31B7E7-0 1730 200
//@node 13F7C84A-0 2010 40
//@node CBA07A48-0 2290 40
//@node DFE8310A-0 40 40
//@node A50294F1-0 330 40
//@node 20443058-0 610 40
//@node 430A0F01-0 890 40
//@node 802FBD3D-0 1170 40
//@node 98CE267B-0 1450 40
//@node 9928AA71-0 1010 145
//@node 83BE22A1-0 1240 145
//@node E0F18916-0 1730 200
//@node 21E405D6-0 2010 40
//@node 10F7FB68-0 2290 40
//@node FBC457A8-0 2570 40
//@node F3BA6588-0 40 40
//@node D2C5F865-0 330 40
//@node 13B91EAB-0 610 40
//@node 1D75966E-0 405 145
//@node 163CE966-0 200 145
//@node FDAEE21C-0 890 200
//@node B1591A84-0 1170 40
//@node 07EB7207-0 40 40
//@node DD083842-0 330 40
//@node 8B97E7A5-0 610 40
//@node 347767C5-0 405 145
//@node B4AC57F5-0 890 200
//@node 1C749398-0 1170 40
//@node 996E5D84-0 40 40
//@node 28BE3D78-0 330 40
//@node 676B54C8-0 610 40
//@node 4890DF70-0 170 145
//@node F1ABFA40-0 400 145
//@node 9320DE18-0 890 200
//@node FD356D3E-0 1170 40
//@node 19426529-0 1450 40
//@node 461F9371-0 40 40
//@node 0CD4B4E6-0 330 40
//@node 5F8C4F68-0 610 40
//@node C5CFAE92-0 170 145
//@node 6F095EC2-0 400 145
//@node EB0C8463-0 890 200
//@node C9731E03-0 1170 40
//@node 4806EE47-0 1450 40
//@node 35C2693A-0 40 40
//@node DF07E896-0 330 40
//@node AB134E0B-0 40 40
//@node 65EB4207-0 330 40
//@node ED26E351-0 610 40
//@node C767DEF7-0 890 40
//@node 98C2D9BD-0 1170 40
//@node 45F962DE-0 1450 40
//@node 4648A7E0-0 40 40
//@node 3B91A964-0 330 40
//@node B3CDF1FC-0 610 40
//@node E3441AAA-0 405 145
//@node 04342D22-0 890 40
//@node D21E0FD5-0 685 145
//@node 14CC5843-0 1170 40
//@node 57BC9241-0 945 145
//@node EF04773F-0 1450 40
//@node ECA0E9A6-0 40 40
//@node 64C9ECCC-0 330 40
//@node D9BA36F9-0 125 145
//@node 41AEC9C8-0 610 40
//@node 2C7C5D6D-0 405 145
//@node 4FBAC840-0 890 200
//@node 6F660C98-0 1170 200
//@node 828C7ACC-0 965 305
//@node E44B7DFB-0 1450 200
//@node AA44BE0B-0 1730 200
//@node 35206D4A-0 1525 305
//@node 385223EC-0 2010 200
//@node 9333D8E8-0 1805 300
//@node E96FA8D2-0 2290 200
//@node 9CC2BE53-0 2085 305
//@node F6628AA1-0 2570 200
//@node 3E66BBE2-0 2850 200
//@node 480ECA31-0 2645 305
//@node 070603BA-0 3130 200
//@node 7CA9EE82-0 40 40
//@node 7132E4EB-0 330 40
//@node 8C320B8F-0 125 145
//@node BEDDDA90-0 610 40
//@node ADFE826D-0 385 145
//@node 961DBBF2-0 890 40
//@node 22ACD021-0 665 145
//@node 6EB2604D-0 1170 40
//@node 59C4211D-0 965 145
//@node E304AA2F-0 760 145
//@node 109BF1E5-0 1450 200
//@node CAB878CF-0 1245 305
//@node A051BC55-0 1040 305
//@node 03305832-0 1040 389
//@node 95AE524D-0 1040 389
//@node 84AB5FA4-0 1730 360
//@node 34880C39-0 1505 465
//@node DFF0EAAB-0 2010 520
//@node 011652E3-0 2290 360
//@node 79596CD7-0 2065 465
//@node 1BB79C0C-0 2570 520
//@node 246FB500-0 2850 520
//@node 5FBFEE12-0 2645 625
//@node ADE131E9-0 2440 625
//@node 3E87BC15-0 3130 680
//@node 58A867EA-0 2925 785
//@node E8AFB034-0 3410 840
//@node 923347F3-0 3970 840
//@node 31CEA5E3-0 4250 200
//@node B6BCB6AC-0 4025 305
//@node CA9FD3DD-0 4530 200
//@node C96BCC9B-0 4325 305
//@node A08011FD-0 4810 360
//@node 4F02826C-0 5090 40
//@node 4998E9DD-0 4885 145
//@node 39D862FE-0 5370 200
//@node 0F1382E9-0 5650 40
//@node F685FF24-0 5445 145
//@node 9C31602E-0 5240 145
//@node D6D76457-0 5240 229
//@node 65F1A927-0 5240 145
//@node 1062A04A-0 5930 200
//@node 526772A2-0 5725 305
//@node EC1D3237-0 5520 305
//@node DD965508-0 5520 389
//@node 30E8FD92-0 6210 360
//@node 50D696D0-0 5985 465
//@node 0767592F-0 6490 520
//@node 148FC62C-0 6265 625
//@node F9E58D67-0 6770 520
//@node 02AE57C7-0 6565 625
//@node 58C1D8AE-0 7050 680
//@node B627CC01-0 7330 40
//@node ADD424F2-0 40 40
//@node DA713BD5-0 330 40
//@node 5D56E401-0 105 145
//@node 2BF2AEFE-0 610 40
//@node CD651C6E-0 405 145
//@node 580FB866-0 890 40
//@node DA88ED5E-0 1170 40
//@node C64BF04E-0 1450 40
//@node 6FA98140-0 1245 145
//@node 750A3625-0 1730 40
//@node A0B246CA-0 1525 145
//@node 6A205AE7-0 2010 40
//@node 2E5C102D-0 1805 145
//@node 2C60312D-0 1600 145
//@node CF727F84-0 2290 200
//@node 1E783293-0 2085 305
//@node 5D4A730F-0 1880 305
//@node CD88D6F9-0 2570 200
//@node 32B1286F-0 2365 305
//@node 09131206-0 2160 305
//@node B87A636B-0 2850 200
//@node 9DAB025B-0 2645 305
//@node 67B68921-0 2440 305
//@node C1B0F0F2-0 2440 389
//@node 58296024-0 3130 200
//@node 8A7EABAF-0 2925 300
//@node CC072AF3-0 3410 200
//@node C3739199-0 3690 40
//@node F619CCB2-0 40 40
//@node 2C665FD9-0 330 40
//@node 05961F5A-0 610 40
//@node 8744EDC2-0 405 140
//@node AAC9F57D-0 890 40
//@node FFB7BCA3-0 1170 40
//@node 4B16FE90-0 1450 40
//@node FD3E3D48-0 1225 145
//@node E3DF9EC9-0 1730 40
//@node CAEF5C66-0 1525 145
//@node 06F399C2-0 1320 145
//@node FCBB1A99-0 1320 229
//@node F1979B15-0 2010 200
//@node 5D51AFCE-0 1785 305
//@node D8A64D84-0 2290 200
//@node D879EFA6-0 2085 305
//@node A1B9B72A-0 1880 305
//@node 792F10A3-0 2570 360
//@node FFB7BCA3-1 2850 200
//@node 69691DBD-0 3130 40
//@node 270DF4FB-0 3410 40
//@node 00D09D1D-0 3690 40
//@node 25F78346-0 3465 145
//@node 887A1E96-0 3970 40
//@node 2839F032-0 3765 145
//@node 857E835B-0 40 40
//@node 1D0F4F3E-0 330 40
//@node 98C8D99E-0 610 40
//@node A14FCDB8-0 890 40
//@node C65BED51-0 1170 40
//@node 2E3F0ECE-0 1450 40
//@node 53A60938-0 40 40
//@node 17B4D389-0 330 40
//@node 24D43B53-0 610 40
//@node 4E4F107C-0 890 40
//@node A04A9838-0 1170 40
//@node C838BA41-0 1450 40
//@node 90B47F04-0 1225 145
//@node 2B3B9D8D-0 40 40
//@node 4F942F24-0 330 40
//@node D58304E8-0 610 40
//@node 24F67EA7-0 890 40
//@node 3E1AFB21-0 1170 40
//@node 3F63048E-0 1450 40
//@node 16047D5A-0 1225 145
//@doomscript-blueprint end
