/***********************************************************************

ai_monster_demon_trite.script

monster_demon_trite

***********************************************************************/

#define TRITE_RUNDISTANCE		192
#define TRITE_WALKTURN			65
#define TRITE_LEAP_RATE			2
#define TRITE_DODGE_RATE		2
#define TRITE_LEAP_RANGE_MIN	64
#define TRITE_LEAP_RANGE_MAX	1024
#define TRITE_LEAP_SPEED		650
#define TRITE_LEAP_MAXHEIGHT	48

#define TRITE_EXPLOSION_RADIUS	200		// based on value in entitydef damage_trite_explode

object monster_demon_trite : monster_base {
	boolean		explode;
	float		nextDodge;
	float		nextLeap; 			// don't do a range attack until this time
	vector		jumpVelocity;
	entity		combat_node;
	
	// States
	void		state_Begin();
	void		state_Idle();
	void		state_Killed();
	void		state_LostCombat();

	// attacks
	float		check_attacks();
	void		do_attack( float attack_flags );
	void		combat_explode();
	void		combat_leap();
	void		combat_melee();
	void		combat_dodge_left();
	void		combat_dodge_right();
	void		path_jump();

	void		init();
	
	// torso anim states
	void		Torso_Idle();
	void		Torso_Pain();
	void		Torso_MeleeAttack();
	void		Torso_LeapAttack();
	void		Torso_Walk();
	void		Torso_Run();
	void		Torso_DodgeLeft();
	void		Torso_DodgeRight();
};

/***********************************************************************

	Torso animation control

***********************************************************************/

void monster_demon_trite::Torso_Idle() {
	idleAnim( ANIMCHANNEL_TORSO, "idle" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Run", 4 ); }
		if ( AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Walk", 4 ); }
	}
}

void monster_demon_trite::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	
	while( !animDone( ANIMCHANNEL_TORSO, 2 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}

	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 2 );
}

void monster_demon_trite::Torso_MeleeAttack() {
	playAnim( ANIMCHANNEL_TORSO, "melee_attack" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "melee_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_trite::Torso_LeapAttack() {
	overrideAnim( ANIMCHANNEL_LEGS );
	disablePain();
	playAnim( ANIMCHANNEL_TORSO, "jump_start" );
	while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
		waitFrame();
	}
	
	finishAction( "leap_attack_start" );

	attackBegin( "melee_triteLeapAttack" );
	setLinearVelocity( jumpVelocity );
	
	playCycle( ANIMCHANNEL_TORSO, "jump_loop" );
	do {
		waitFrame();
	} while( !AI_ONGROUND );
	
	attackEnd();
	playAnim( ANIMCHANNEL_TORSO, "jump_end" );
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "leap_attack" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_trite::Torso_Walk() {
	playCycle( ANIMCHANNEL_TORSO, "walk" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Run", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_demon_trite::Torso_Run() {
	playCycle( ANIMCHANNEL_TORSO, "run" );
	
	eachFrame {
		if ( AI_PAIN )				{ animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 ); }
		if ( !run && AI_FORWARD )	{ animState( ANIMCHANNEL_TORSO, "Torso_Walk", 4 ); }
		if ( !AI_FORWARD )			{ animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 ); }
	}
}

void monster_demon_trite::Torso_DodgeLeft() {
	playAnim( ANIMCHANNEL_TORSO, "evade_left" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}
	
	finishAction( "strafe" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void monster_demon_trite::Torso_DodgeRight() {
	playAnim( ANIMCHANNEL_TORSO, "evade_right" );

	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		waitFrame();
	}

	finishAction( "strafe" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

/***********************************************************************

	AI

***********************************************************************/

/*
=====================
monster_demon_trite::init
=====================
*/
void monster_demon_trite::init() {
	explode = !getIntKey( "no_explode" );
	setState( "state_Begin" );
}

/***********************************************************************

	States

***********************************************************************/

/*
=====================
monster_demon_trite::state_Killed
=====================
*/
void monster_demon_trite::state_Killed() {
	stopMove();

	animState( ANIMCHANNEL_TORSO, "Torso_Death", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Death", 0 );
	
	waitAction( "dead" );
	setState( "state_Dead" );
}

/*
=====================
monster_demon_trite::state_Begin
=====================
*/
void monster_demon_trite::state_Begin() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	monster_begin();
	setMoveType( MOVETYPE_ANIM );	
	setState( "state_Idle" );
}

/*
=====================
monster_demon_trite::state_Idle
=====================
*/
void monster_demon_trite::state_Idle() {
	wait_for_enemy();

	nextLeap		= RandomTime( TRITE_LEAP_RATE );
	nextDodge		= RandomTime( TRITE_DODGE_RATE );

	setState( "state_Combat" );
}

/***********************************************************************

	attacks

***********************************************************************/

/*
=====================
monster_demon_trite::do_attack
=====================
*/
void monster_demon_trite::do_attack( float attack_flags ) {
	if ( attack_flags & ATTACK_DODGE_LEFT ) {
		combat_dodge_left();
	} else if ( attack_flags & ATTACK_DODGE_RIGHT ) {
		combat_dodge_right();
	} else if ( attack_flags & ATTACK_COMBAT_NODE ) {
		combat_ainode( combat_node );
	} else if ( attack_flags & ATTACK_MELEE ) {
		combat_melee();
	} else if ( attack_flags & ATTACK_LEAP ) {
		combat_leap();
	}
}

/*
=====================
monster_demon_trite::check_attacks
=====================
*/
float monster_demon_trite::check_attacks() {
	float range;
	float currentTime;
	float canMelee;
	float attack_flags;
	float checkLeap;
	vector vel;
	float t;
	vector jumpTarget;
	
	attack_flags = 0;
	
	canMelee = testMeleeAttack();
	currentTime = sys.getTime();
	if ( !canMelee ) {
		if ( AI_PAIN && ( currentTime >= nextDodge ) ) {
			if ( testAnimMove( "evade_left" ) ) {
				attack_flags |= ATTACK_DODGE_LEFT;
			}
			if ( testAnimMove( "evade_right" ) ) {
				attack_flags |= ATTACK_DODGE_RIGHT;
				
				// if we can dodge either direction, pick one
				if ( attack_flags & ATTACK_DODGE_LEFT ) {
					if ( sys.random( 100 ) < 50 ) {
						attack_flags &= ~ATTACK_DODGE_RIGHT;
					} else {
						attack_flags &= ~ATTACK_DODGE_LEFT;
					}
				}
			}
		}
	
		combat_node = getCombatNode();
		if ( combat_node ) {
			attack_flags |= ATTACK_COMBAT_NODE;
		}
	}
	
	if ( canMelee ) {
		attack_flags |= ATTACK_MELEE;
	}

	if ( AI_ENEMY_IN_FOV ) {
		range = enemyRange();

		if ( ( range >= TRITE_LEAP_RANGE_MIN ) && ( range < TRITE_LEAP_RANGE_MAX ) && ( currentTime >= nextLeap ) ) {
			if ( canHitEnemy() ) {
				t = animLength( ANIMCHANNEL_TORSO, "jump_start" );
				jumpTarget = predictEnemyPos( t );
				jumpVelocity = getJumpVelocity( jumpTarget, TRITE_LEAP_SPEED, TRITE_LEAP_MAXHEIGHT );
				if ( jumpVelocity != '0 0 0' ) {
					attack_flags |= ATTACK_LEAP;
				} else {
					// check if we can leap again in 2 seconds
					nextLeap = DelayTime( 2 );
				}
			}
		}
	}
	
	return attack_flags;
}

/*
=====================
monster_demon_trite::combat_explode
=====================
*/
void monster_demon_trite::combat_explode() {
	float	t;
	vector	org;
	vector	vel;
	vector	enemyOrg;
	float	maxHeight;
	
	t = animLength( ANIMCHANNEL_TORSO, "jump_start" );

	enemyOrg = predictEnemyPos( t );
	org = getOrigin();

	maxHeight = enemyOrg_z;
	if ( maxHeight < org_z + 32 ) {
		maxHeight = org_z + 32;
	}
	vel = enemyOrg - org;
	vel = sys.vecNormalize( vel ) * 320;
	vel_z = sys.sqrt( 2 * ( maxHeight - org_z ) * 1066 );
	jumpVelocity = vel;

	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack_start" );
	while( inAnimState( ANIMCHANNEL_TORSO, "Torso_LeapAttack" ) ) {
		org = getOrigin();
		enemyOrg = getEnemyPos();
		vel = getLinearVelocity();
		if ( ( org_z > enemyOrg_z ) || ( org_z > maxHeight ) || ( vel_z <= -10 ) ) {
			setState( "state_Explode" );
		}

		waitFrame();
	}

	setState( "state_Explode" );
}

/*
=====================
monster_demon_trite::combat_leap
=====================
*/
void monster_demon_trite::combat_leap() {
	stopMove();
	turnToPos( getOrigin() + jumpVelocity );
	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );
	nextLeap = DelayTime( TRITE_LEAP_RATE );
}

/*
=====================
monster_demon_trite::combat_melee
=====================
*/
void monster_demon_trite::combat_melee() {
	lookAtEnemy( 100 );
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_MeleeAttack", 5 );
	waitAction( "melee_attack" );
	lookAtEnemy( 1 );
}

/*
=====================
monster_demon_trite::combat_dodge_left
=====================
*/
void monster_demon_trite::combat_dodge_left() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_DodgeLeft", 2 );
	waitAction( "strafe" );
	nextDodge = DelayTime( TRITE_DODGE_RATE );
}

/*
=====================
monster_demon_trite::combat_dodge_right
=====================
*/
void monster_demon_trite::combat_dodge_right() {
	stopMove();
	faceEnemy();
	animState( ANIMCHANNEL_TORSO, "Torso_DodgeRight", 2 );	
	waitAction( "strafe" );
	nextDodge = DelayTime( TRITE_DODGE_RATE );
}

/*
=====================
monster_demon_trite::path_jump
=====================
*/
void monster_demon_trite::path_jump() {
	entity target;
	vector dir;
	vector jumpTarget;

	// walk to the path entity first
	path_corner();

	if ( checkForEnemy( true ) ) {
		return;
	}

	target = current_path.randomPath();
	if ( !target ) {
		sys.error( "missing target for '" + current_path.getName() + "'" );
	}
	jumpTarget = target.getOrigin();
	if ( !current_path.getKey( "up" ) ) {
		jumpVelocity = getJumpVelocity( jumpTarget, TRITE_LEAP_SPEED, 1024 );
		if ( jumpVelocity == '0 0 0' ) {
			sys.error( "Monster '" + getName() + "' couldn't make jump from '" + current_path.getName() + "' to '" + target.getName() + "'" );
		}
	} else {
		float forward = current_path.getFloatKey( "forward" );
		if ( forward <= 0 ) {
			sys.error( "Invalid forward velocity on path_jump entity '" + current_path.getName() + "'\n" );
		}
		dir = jumpTarget - getOrigin();
		dir_z = 0;
		dir = sys.vecNormalize( dir );
		dir = dir * forward;
		dir_z = current_path.getFloatKey( "up" );
		jumpVelocity = dir;
	}
	
	stopMove();
	turnToPos( jumpTarget );
	while( !facingIdeal() ) {
		if ( checkForEnemy( true ) ) {
			return;
		}
		waitFrame();
	}

	animState( ANIMCHANNEL_TORSO, "Torso_LeapAttack", 4 );	
	waitAction( "leap_attack" );

	stopMove();
}

/*
=====================
monster_demon_trite::state_LostCombat
=====================
*/
void monster_demon_trite::state_LostCombat() {
	float attack_flags;
	float endtime;

	if ( !explode ) {
		monster_base_lost_combat();
		return;
	}

	moveToEnemy();
	while( !AI_MOVE_DONE ) {
		if ( canReachEnemy() ) {
			setState( "state_Combat" );
		}

		if ( enemyRange() < TRITE_EXPLOSION_RADIUS ) {
			combat_explode();
		}

		attack_flags = check_attacks();
		if ( attack_flags & ATTACK_LEAP ) {
			combat_explode();
		} else if ( attack_flags ) {
			setState( "state_Combat" );
		}

		waitFrame();
	}

	endtime = sys.getTime() + 1.5;
	wander();

	// this helps prevent infinite loops since we can actually wind up rapidly switching between combat and lost
	waitFrame();

	while( sys.getTime() < endtime ) {
		if ( canReachEnemy() ) {
			setState( "state_Combat" );
		}

		if ( enemyRange() < TRITE_EXPLOSION_RADIUS ) {
			combat_explode();
			setState( "state_Combat" );
		}

		attack_flags = check_attacks();
		if ( attack_flags & ATTACK_LEAP ) {
			combat_explode();
		} else if ( attack_flags ) {
			setState( "state_Combat" );
		}

		waitFrame();
	}

	setState( "state_Combat" );
}

/*
=====================
monster_demon_trite::state_Explode
=====================
*/
void monster_demon_trite::state_Explode() {
	string fx;
	string damageName;
	entity ent;

	// spawn the explosion
	fx = getKey( "model_explode" );
	sys.setSpawnArg( "model", fx );
	ent = sys.spawn( "func_emitter" );
	ent.show();
	ent.setOrigin( getOrigin() );
	ent.setShaderParm( SHADERPARM_TIMEOFFSET, -sys.getTime() );
	ent.setShaderParm( SHADERPARM_DIVERSITY, sys.random( 1 ) );

	damageName = getKey( "def_explode_damage" );
	sys.radiusDamage( getOrigin(), self, self, self, damageName, 1.0 );

	startSound( "snd_explode", SND_CHANNEL_BODY, false );

	// disappear and activate any targets
	activateTargets( self );
	hide();

	// wait a bit for sounds to finish, then go away
	sys.wait( 5 );
	ent.remove();
	remove();
}

//@doomscript-blueprint begin 6
//@source 34C1113E
//@catalog 0C260740
//@node 1631529A-0 40 40
//@node E95DC0F1-0 330 40
//@node F91BE9FD-0 610 40
//@node 2F663E5B-0 890 200
//@node B665FE93-0 685 305
//@node 545CF686-0 480 305
//@node A5E73EA2-0 1170 200
//@node 766BF320-0 965 305
//@node 6EFC3579-0 760 305
//@node D8EBF496-0 760 389
//@node 383942DB-0 1450 200
//@node 7F49A2C1-0 1245 305
//@node F9B228B7-0 1040 305
//@node EC39D498-0 40 40
//@node 7C909A8B-0 330 40
//@node A8E7CDF0-0 105 145
//@node A527EF1B-0 610 40
//@node 5CF6E646-0 405 232
//@node E0B09553-0 890 40
//@node 1407AE93-0 685 145
//@node D9068827-0 1170 40
//@node 9F861F9D-0 730 145
//@node 97E4970D-0 960 145
//@node 76E523C5-0 1450 200
//@node ACD31577-0 1245 305
//@node D54D9D12-0 1730 360
//@node 3FE7EFAE-0 1505 465
//@node 3EEC76FF-0 2010 360
//@node A8A47537-0 1805 465
//@node 0015FAEA-0 1600 465
//@node 50D65061-0 1600 549
//@node 8863B43C-0 2290 520
//@node 12FA68DC-0 2570 200
//@node C0BCAFD9-0 2850 40
//@node C2E515F0-0 3130 40
//@node C2553080-0 40 40
//@node E8E708AC-0 330 40
//@node 9B2C07B9-0 610 40
//@node 1D7B4A6D-0 170 145
//@node 313BC7DD-0 400 145
//@node 712673BC-0 890 200
//@node E747C394-0 1170 40
//@node CC777D02-0 1450 40
//@node 7106AD46-0 40 40
//@node 56ADB68F-0 330 40
//@node 848BDFA4-0 610 40
//@node 0C6692D8-0 890 40
//@node 1F4CF93B-0 1170 40
//@node C43F6783-0 730 145
//@node 0E94F813-0 960 145
//@node C7E557FA-0 1450 200
//@node DAF4C115-0 1730 40
//@node E9DF0B1A-0 2010 40
//@node 611436F3-0 2290 40
//@node 060429F9-0 2085 140
//@node 202EEC27-0 2570 40
//@node A1A1A17B-0 2850 40
//@node C7E557FA-1 3130 200
//@node 4613374D-0 3410 200
//@node D0DB8BF9-0 3205 305
//@node 238EE5DB-0 3000 305
//@node 8DB27FB7-0 3690 40
//@node E6F7998D-0 3970 40
//@node FF9EAB47-0 4250 40
//@node 10A18341-0 3810 145
//@node 0D701531-0 4040 145
//@node C7E557FA-2 4530 200
//@node C7A8DEBE-0 4810 40
//@node 2AE84FFC-0 5090 40
//@node 45864D89-0 40 40
//@node B96CABB6-0 330 40
//@node BBF3B386-0 610 40
//@node D488EE20-0 890 200
//@node AC5A496D-0 685 305
//@node 77E4F0E0-0 480 305
//@node 548212E3-0 1170 200
//@node 936B16A8-0 965 305
//@node 89E7D489-0 760 305
//@node 1102AF06-0 760 389
//@node 9BC1D25E-0 1450 200
//@node C1839734-0 1245 305
//@node 22C04FD8-0 1040 305
//@node 46E32EDD-0 40 40
//@node 58783DE0-0 330 40
//@node 5CC490A8-0 125 232
//@node 24CE8621-0 -80 232
//@node 8E0B2E34-0 610 40
//@node 991CE218-0 890 200
//@node 05742AC9-0 685 305
//@node 9B59078E-0 480 305
//@node F8AE4D62-0 1170 200
//@node 056B223B-0 965 305
//@node A5BD4473-0 760 305
//@node E96641FC-0 760 389
//@node FF7F2966-0 1450 200
//@node E027B317-0 1245 305
//@node F2BA9673-0 1040 305
//@node 67D0D62E-0 40 40
//@node FA591084-0 330 40
//@node 4E6B414F-0 610 40
//@node 8D5B275D-0 170 145
//@node 427DD02D-0 400 145
//@node D813BAAA-0 890 200
//@node A86833DC-0 1170 40
//@node 185B954C-0 1450 40
//@node 01ACA503-0 40 40
//@node DCE1F4E4-0 330 40
//@node 6609DC28-0 610 40
//@node 6593C3DC-0 170 145
//@node 241CB80C-0 400 145
//@node 59791015-0 890 200
//@node E0B65DB9-0 1170 40
//@node FE60D2DF-0 1450 40
//@node A641FF9E-0 40 40
//@node A351F731-0 330 40
//@node 3DCFF8DD-0 -110 145
//@node C5FDDBAD-0 120 145
//@node 376E72D2-0 610 40
//@node 8CE09BFF-0 40 40
//@node 71D880F2-0 330 40
//@node 0E3F24B5-0 610 40
//@node D4D1D29B-0 890 40
//@node 53672DDA-0 1170 40
//@node 372A015A-0 1450 40
//@node C656C07F-0 40 40
//@node 29AB8793-0 330 40
//@node A50EC5AB-0 610 40
//@node 990C0829-0 890 40
//@node A3C6AC72-0 1170 40
//@node 72CBD5BC-0 40 40
//@node 34BB1C40-0 330 40
//@node C90E8031-0 610 40
//@node 241141DD-0 385 145
//@node F0BD08B9-0 890 40
//@node C20D73F7-0 665 145
//@node 1EC044AB-0 1170 40
//@node FDA7C15A-0 40 40
//@node 7036110C-0 330 40
//@node B20A0E6C-0 125 145
//@node 4CE36CDC-0 610 200
//@node 5A527B34-0 890 200
//@node ACFB8E13-0 685 305
//@node 87688DCF-0 1170 200
//@node 77CC2FA7-0 1450 200
//@node A864AAAF-0 1245 305
//@node 02CFFCA0-0 1730 200
//@node 7632A81E-0 1525 300
//@node 54B36D66-0 2010 200
//@node 9E7127CE-0 1805 305
//@node 1B20F71D-0 2290 200
//@node E83C77D2-0 2570 200
//@node 192FC461-0 2365 305
//@node 4034C8D5-0 2850 200
//@node BC1E525E-0 40 40
//@node 3BF86B9F-0 330 40
//@node 0CE8DD58-0 125 145
//@node A35867D4-0 610 40
//@node F8ABC01C-0 385 145
//@node 5306A36E-0 890 40
//@node 388A68C8-0 665 145
//@node 20C74FA1-0 1170 40
//@node 16A79F46-0 965 145
//@node 7F580B3E-0 760 145
//@node C7A5ED31-0 1450 200
//@node 7D99CB03-0 1245 305
//@node 3ED5D571-0 1040 305
//@node 679663E6-0 1040 389
//@node BDCCF851-0 1040 389
//@node 3B48ECD0-0 1730 360
//@node 80C4535D-0 1505 465
//@node 4BFF2647-0 2010 520
//@node E4C5BCF7-0 2290 360
//@node 82EFF87D-0 2065 465
//@node C5B7A020-0 2570 520
//@node 34B9D47C-0 2850 520
//@node 07C67FEB-0 2645 625
//@node B4901E24-0 2440 625
//@node EDB59FD9-0 3130 680
//@node 7A5B7C02-0 2925 785
//@node 78616478-0 3410 840
//@node E97C9D7F-0 3970 840
//@node 448FAD3F-0 4250 200
//@node 12246C84-0 4025 305
//@node E4FFCF21-0 4530 200
//@node 8E235C9C-0 4325 305
//@node B8C3F181-0 4810 360
//@node 56851768-0 5090 40
//@node 374C5730-0 4885 145
//@node B092B28A-0 5370 200
//@node 343CF519-0 5650 40
//@node 8198E2BF-0 5445 145
//@node 4EFD1842-0 5930 200
//@node 44B25AF5-0 5705 305
//@node 4CB85970-0 6210 200
//@node ECDAECDD-0 6005 305
//@node 28DE96EB-0 5800 305
//@node 838F80C6-0 5800 389
//@node 0743C131-0 5800 473
//@node FFCFE096-0 6490 360
//@node AA4F8910-0 6265 465
//@node B932732A-0 6770 520
//@node EF06172E-0 6545 625
//@node 2874AD8C-0 7050 520
//@node 90E79E28-0 6825 625
//@node D37264EF-0 6620 725
//@node 09E6123B-0 7330 520
//@node 4555297F-0 7105 625
//@node E567B920-0 6900 725
//@node FE6AA693-0 7610 520
//@node A854C1C3-0 7405 625
//@node C6FEE126-0 7200 625
//@node 84FF2A8E-0 7890 680
//@node 08E55115-0 8450 680
//@node 3427A696-0 8225 785
//@node 59BED145-0 8730 40
//@node 2067D842-0 40 40
//@node 1E368C98-0 330 40
//@node 981FEAB8-0 105 145
//@node 75A5E069-0 610 40
//@node A415BF81-0 385 145
//@node BA138DEC-0 180 245
//@node 12F087BE-0 890 40
//@node 7D2A5B27-0 665 145
//@node 3E2E8D43-0 1170 40
//@node 1A5FE6BA-0 965 145
//@node 7941F566-0 1450 40
//@node DC8A28DF-0 1245 145
//@node 38113AF5-0 1040 145
//@node BE33C2FB-0 1730 200
//@node 835FC19C-0 1525 305
//@node FEA64565-0 2010 40
//@node 9F7A0B96-0 1805 145
//@node AA4B4864-0 1600 145
//@node BEAD90B0-0 1600 229
//@node F70ECFE1-0 2290 40
//@node C0D89891-0 2085 145
//@node 7B98D652-0 1880 145
//@node CAB25802-0 2570 40
//@node 4AACEEAF-0 2345 145
//@node A0248B38-0 2140 245
//@node B5D50ABB-0 1935 245
//@node 3C3F4629-0 2850 40
//@node 3DF89361-0 2645 145
//@node CCF14977-0 3130 40
//@node C57F9929-0 3410 40
//@node 216A9214-0 3690 40
//@node 9E8531A3-0 3970 40
//@node 18599C24-0 4250 40
//@node 09D98D9E-0 4025 145
//@node 12F087BE-1 4530 200
//@node E9A3CEB8-0 4305 305
//@node 2E217898-0 4810 200
//@node BB8C62D0-0 4585 305
//@node 8D8DBFC5-0 5090 200
//@node 476FD3FE-0 4865 305
//@node 1DBA1A12-0 5370 200
//@node 6F60BBB4-0 5165 305
//@node AF657B7A-0 4960 305
//@node 019C2F76-0 5650 360
//@node 4F49D70E-0 5930 200
//@node 019C2F76-1 6210 40
//@node C5DEBDAF-0 40 40
//@node 49F52272-0 330 40
//@node 7E06EF76-0 610 40
//@node 2593F931-0 405 140
//@node 6594BBB4-0 200 140
//@node C2B03963-0 890 40
//@node 525F5093-0 1170 40
//@node 6B30E4A4-0 1450 40
//@node 5EAE0CBC-0 1225 145
//@node CC1AAF77-0 40 40
//@node EF76534A-0 330 40
//@node 936B1922-0 610 40
//@node A5A595B6-0 890 40
//@node 91F1E715-0 1170 40
//@node 21E4093A-0 1450 40
//@node 33E44A74-0 40 40
//@node B6E652D5-0 330 40
//@node 5BCA2107-0 610 40
//@node BEF0FBAC-0 890 40
//@node FEF65564-0 1170 40
//@node BAE894A3-0 1450 40
//@node 21849E6F-0 1225 145
//@node BC4C6D21-0 40 40
//@node 3EFAAF38-0 330 40
//@node 284BD5D4-0 610 40
//@node 2EB0E4CC-0 890 40
//@node 6D2F2C35-0 1170 40
//@node 3CFC4B5E-0 1450 40
//@node E67EBAC6-0 1225 145
//@node ED016588-0 40 40
//@node 59C4A8B5-0 330 40
//@node 12B26AE0-0 610 40
//@node 1BFD921A-0 385 145
//@node 2510D047-0 890 200
//@node 8266B168-0 1170 40
//@node E0C7ABBB-0 945 145
//@node 6BF14278-0 1450 40
//@node 66DCA4F3-0 1245 145
//@node 9166080B-0 1040 145
//@node 07B71608-0 1730 200
//@node EFBE09F3-0 1525 300
//@node A59FEAC6-0 1320 300
//@node D22BDF52-0 1320 378
//@node 70D052C6-0 2010 40
//@node AC1F05F3-0 1785 145
//@node 868456EB-0 2290 40
//@node AC88A6A1-0 1850 145
//@node F40C46D1-0 2080 145
//@node 4217ED55-0 2570 200
//@node 55D0024E-0 2345 305
//@node 5C67926C-0 2140 405
//@node E4D24E55-0 2850 200
//@node 6A467054-0 2645 305
//@node 2BF0084F-0 2440 305
//@node 7CE146D4-0 3130 360
//@node 276DE3BC-0 2925 460
//@node 15A54CB3-0 2720 460
//@node 834BE7B3-0 2720 538
//@node 006729F4-0 3690 200
//@node 363AD99F-0 3485 305
//@node A8C80A9B-0 3280 305
//@node 41B96213-0 4250 360
//@node A764E009-0 3765 460
//@node F90E0463-0 3560 460
//@node B22AB38F-0 3560 538
//@node D0A73697-0 3560 616
//@node 8911D52D-0 4250 200
//@node ADD5477E-0 4025 305
//@node B641DD81-0 4530 200
//@node 6B848B1E-0 4325 305
//@node 1D04F72A-0 4810 200
//@node 891766B8-0 4585 305
//@node D4FAEA06-0 4380 405
//@node 6A4BF0E6-0 5090 200
//@node D03C7ABF-0 4885 305
//@node CFEBB927-0 4680 305
//@node 15E938DD-0 4680 389
//@node 38188777-0 5370 200
//@node A84EA9D4-0 5145 305
//@node F9B57B2D-0 5650 200
//@node FA18C016-0 5445 305
//@node ABF62839-0 6210 40
//@node FA2F40A5-0 6490 40
//@node 9A7305D4-0 6005 140
//@node B0328F0B-0 6490 40
//@node FFA537EC-0 6050 145
//@node 9C8CC8DC-0 6280 145
//@node 12B26AE0-1 6770 200
//@node 45DF81AD-0 6545 305
//@node 2510D047-1 7330 360
//@node 26F2F7D0-0 7610 200
//@node EF53A552-0 7890 40
//@node 660AEC32-0 8170 40
//@node ABF62839-1 8450 40
//@node 31F314C8-0 40 40
//@node 869860EC-0 330 40
//@node 29339E30-0 125 145
//@node 7B7B61D0-0 -80 145
//@node BC504154-0 610 200
//@node 0ABFE32F-0 890 200
//@node 16ECADEA-0 1170 40
//@node 224D1000-0 1450 40
//@node 1BF44ACC-0 1245 145
//@node 081BD354-0 1040 145
//@node 74652B4E-0 1730 200
//@node 01DE2748-0 1505 305
//@node A372619B-0 2010 360
//@node 041F5969-0 2290 200
//@node B5C3D89A-0 2085 305
//@node E3567C38-0 2570 360
//@node EA7C9720-0 2850 200
//@node F1F01ADA-0 2625 305
//@node 2E678145-0 3130 200
//@node 48580DD4-0 2925 305
//@node E0F864EE-0 2720 305
//@node E3567C38-1 3410 360
//@node CE2338CD-0 3690 360
//@node D77798D5-0 3485 465
//@node A372619B-1 3970 360
//@node AAB09208-0 4250 200
//@node 9FC3E3CB-0 4530 40
//@node B6C0E5DB-0 4325 145
//@node E9F615B9-0 4810 40
//@node AAB09208-1 5090 40
//@node FD777D95-0 5370 40
//@node 67737B61-0 5165 145
//@node 3B807925-0 4960 145
//@node 74652B4E-1 5650 200
//@node 5B804D0F-0 5425 305
//@node A372619B-2 5930 360
//@node 041F5969-1 6210 200
//@node A726E081-0 6005 305
//@node E3567C38-2 6490 360
//@node A372619B-3 6770 360
//@node EA7C9720-1 7050 200
//@node 754DFBD1-0 6825 305
//@node 2E678145-1 7330 200
//@node CCD08D1D-0 7125 305
//@node B013B2D3-0 6920 305
//@node E3567C38-3 7610 360
//@node CE2338CD-1 7890 360
//@node 378D7480-0 7685 465
//@node A372619B-4 8170 360
//@node AAB09208-2 8450 200
//@node A372619B-5 8730 40
//@node A9549C5F-0 40 40
//@node D443BA95-0 330 40
//@node 922264B6-0 105 145
//@node D102A6D0-0 610 40
//@node 3E3565AE-0 405 232
//@node DE99F0F7-0 890 40
//@node F104C06E-0 665 145
//@node CA482FF1-0 1170 40
//@node 3CBB4537-0 1450 40
//@node 780F9B3F-0 1730 40
//@node 7B8B2928-0 2010 40
//@node 928F05CD-0 2290 40
//@node 6C2F8F13-0 2065 145
//@node 5C372ABD-0 2570 40
//@node B6BFEBA6-0 2365 508
//@node C5FA6D16-0 2850 40
//@node BAD6197A-0 3130 40
//@node AEAEAC9D-0 3410 40
//@node E1C28E8A-0 3690 40
//@node BDB3016A-0 3970 40
//@node 068AC6B9-0 4250 40
//@doomscript-blueprint end
