/***********************************************************************

doom_player.script

This script contains any player specific code.

***********************************************************************/

object player : player_base {
	weapon_base weapon;
	boolean		weapon_changed;
	boolean		start_fire;
	
	void		init();

				// called by player code
	void		EnterCinematic();
	void		ExitCinematic();
	void		LowerWeapon();
	void		RaiseWeapon();
	void		ReloadWeapon();
	void		NetCatchup();
	
				// torso anims
	void		Torso_Teleport();
	void		Torso_Death();
	void		Torso_Idle();
	void		Torso_Reload();
	void		Torso_Fire_StartFire();
	void		Torso_Fire();
	void		Torso_Fire_Aim();
	void		Torso_RaiseWeapon();
	void		Torso_LowerWeapon();
	
				// leg anims
	void		Legs_Death();
	void		Legs_Idle();
	void		Legs_Crouched();
	void		Legs_Uncrouch();
	void		Legs_Turn_Left();
	void		Legs_Turn_Right();
	void		Legs_Walk();
	void		Legs_Walk_Forward();
	void		Legs_Walk_Backward();
	void		Legs_Walk_Left();
	void		Legs_Walk_Right();
	void		Legs_Run();
	void		Legs_Run_Forward();
	void		Legs_Run_Backward();
	void		Legs_Run_Left();
	void		Legs_Run_Right();
	void		Legs_CrouchWalk();
	void		Legs_CrouchWalk_Backward();
	void		Legs_Jump();
	void		Legs_Fall();
	void		Legs_Land_Hard();
	void		Legs_Land_Soft();
};

/*
=====================
player::init
=====================
*/
void player::init() {
	weapon_changed = false;
	start_fire = false;
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
}

/*
=====================
player::EnterCinematic

Required by game code for cinematics
=====================
*/
void player::EnterCinematic() {
}

/*
=====================
player::ExitCinematic

Required by game code for cinematics
=====================
*/
void player::ExitCinematic() {
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
}

/*
=====================
player::LowerWeapon

Required by game code for weapon switches
=====================
*/
void player::LowerWeapon() {
	animState( ANIMCHANNEL_TORSO, "Torso_LowerWeapon", 3 );
}

/*
=====================
player::RaiseWeapon

Required by game code for weapon switches
=====================
*/
void player::RaiseWeapon() {
	weapon = getWeaponEntity();
	animState( ANIMCHANNEL_TORSO, "Torso_RaiseWeapon", 2 );
}

/*
=====================
player::ReloadWeapon

Required by game code for weapon reloading
=====================
*/
void player::ReloadWeapon() {
	animState( ANIMCHANNEL_TORSO, "Torso_Reload", 4 );
}

/*
=====================
player::NetCatchup

Required by game code for networking
=====================
*/
void player::NetCatchup() {
	weapon = getWeaponEntity();
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
}

/***********************************************************************

	Torso animation control

***********************************************************************/

void player::Torso_Death() {
	waitUntil( !AI_DEAD );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 0 );
}

void player::Torso_Teleport() {
	AI_TELEPORT = false;
	overrideAnim( ANIMCHANNEL_LEGS );
	playAnim( ANIMCHANNEL_TORSO, "teleport" );
	waitUntil( animDone( ANIMCHANNEL_TORSO, 4 ) );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void player::Torso_Idle() {
	playCycle( ANIMCHANNEL_TORSO, "idle" );

	eachFrame {
		if ( AI_TELEPORT ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Teleport", 0 );
		}
		if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fire", 2 );
		}
		if ( AI_ATTACK_HELD && start_fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fire_StartFire", 2 );
		}
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
		}
	}
}

void player::Torso_Pain() {
	string animname;
	float nextpain;
	float currenttime;
	
	animname = getPainAnim();
	playAnim( ANIMCHANNEL_TORSO, animname );

	nextpain = sys.getTime() + 0.25;
	while( !animDone( ANIMCHANNEL_TORSO, 4 ) ) {
		if ( AI_PAIN ) {
			currenttime = sys.getTime();
			if ( currenttime > nextpain ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
			}
		}
		waitFrame();
	}
	
	finishAction( "pain" );
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 4 );
}

void player::Torso_Reload() {
	if ( hasAnim( ANIMCHANNEL_TORSO, "reload_start" ) ) {
		playAnim( ANIMCHANNEL_TORSO, "reload_start" );
		while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
			if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Fire", 3 );
			}
			waitFrame();
		}
		
		while( AI_RELOAD ) {
			playAnim( ANIMCHANNEL_TORSO, "reload_loop" );
			while( !animDone( ANIMCHANNEL_TORSO, 0 ) ) {
				if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
					animState( ANIMCHANNEL_TORSO, "Torso_Fire", 3 );
				}
				waitFrame();
			}
		}

		playAnim( ANIMCHANNEL_TORSO, "reload_end" );
		while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
			if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Fire", 3 );
			}
			waitFrame();
		}
	} else {
		playAnim( ANIMCHANNEL_TORSO, "reload" );
		while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
			if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
				animState( ANIMCHANNEL_TORSO, "Torso_Fire", 3 );
			}
			waitFrame();
		}
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 3 );
}

void player::Torso_Fire_StartFire() {
	playAnim( ANIMCHANNEL_TORSO, "startfire" );

	while( AI_ATTACK_HELD && !( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) ) {
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
		}
		waitFrame();
	}

	boolean held = AI_ATTACK_HELD;

	setBlendFrames( ANIMCHANNEL_TORSO, 2 );

	playAnim( ANIMCHANNEL_TORSO, weapon.GetFireAnim() );

	weapon.WEAPON_START_FIRING = false;
	AI_WEAPON_FIRED = false;
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		waitFrame();
	}
	
	if ( !held && AI_ATTACK_HELD ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Fire_StartFire", 2 );
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Fire_Aim", 3 );
}

void player::Torso_Fire() {
	playAnim( ANIMCHANNEL_TORSO, weapon.GetFireAnim() );

	weapon.WEAPON_START_FIRING = false;
	AI_WEAPON_FIRED = false;
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fire", 2 );
		}
		waitFrame();
	}
	
	if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Fire", 2 );
	}
	
	animState( ANIMCHANNEL_TORSO, "Torso_Fire_Aim", 3 );
}

void player::Torso_Fire_Aim() {
	playAnim( ANIMCHANNEL_TORSO, "aim" );

	while( !animDone( ANIMCHANNEL_TORSO, 12 ) ) {
		if ( AI_ATTACK_HELD && start_fire ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fire_StartFire", 2 );
		}
		if ( AI_WEAPON_FIRED || weapon.WEAPON_START_FIRING ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Fire", 2 );
		}
		if ( AI_PAIN ) {
			animState( ANIMCHANNEL_TORSO, "Torso_Pain", 0 );
		}
		waitFrame();
	}
	
	if ( AI_ATTACK_HELD && start_fire ) {
		animState( ANIMCHANNEL_TORSO, "Torso_Fire_StartFire", 2 );
	} else {
		animState( ANIMCHANNEL_TORSO, "Torso_Idle", 12 );
	}
}

void player::Torso_RaiseWeapon() {
	playAnim( ANIMCHANNEL_TORSO, "raise" );
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		waitFrame();
	}

	start_fire = hasAnim( ANIMCHANNEL_TORSO, "startfire" );
	weapon_changed = true;

	animState( ANIMCHANNEL_TORSO, "Torso_Idle", 3 );
}

void player::Torso_LowerWeapon() {
	weapon_changed = true;
	playAnim( ANIMCHANNEL_TORSO, "lower" );
	while( !animDone( ANIMCHANNEL_TORSO, 3 ) ) {
		waitFrame();
	}
}

/***********************************************************************

	Legs animation control

***********************************************************************/

void player::Legs_Death() {
	waitUntil( !AI_DEAD );
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 0 );
}

void player::Legs_Idle() {
	weapon_changed = false;
	idleAnim( ANIMCHANNEL_LEGS, "idle" );
	
	eachFrame {
		if ( AI_JUMP ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 );
		}
		if ( !AI_ONGROUND )	{
			animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 );
		}
		if ( AI_FORWARD || AI_BACKWARD || AI_STRAFE_LEFT || AI_STRAFE_RIGHT ) {
			Legs_Walk();
		}
		if ( AI_TURN_LEFT ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Turn_Left", 4 );
		}
		if ( AI_TURN_RIGHT ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Turn_Right", 4 );
		}
		if ( AI_CROUCH ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Crouch", 4 );
		}
		if ( weapon_changed ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
		}
	}
}

void player::Legs_Crouch() {
	playAnim( ANIMCHANNEL_LEGS, "crouch_down" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( !AI_CROUCH ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Uncrouch", 4 );
		}
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Crouched", 4 );
}

void player::Legs_Crouched() {
	weapon_changed = false;
	playCycle( ANIMCHANNEL_LEGS, "crouch" );

	eachFrame {
		if ( !AI_CROUCH ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Uncrouch", 4 );
		}
		if ( AI_FORWARD ) {
			animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 );
		}
		if ( AI_BACKWARD ) {
			animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk_Backward", 4 );
		}
		if ( AI_STRAFE_LEFT ) {
			animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 );
		}
		if ( AI_STRAFE_RIGHT ) {
			animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 );
		}
		if ( AI_JUMP ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 );
		}
		if ( !AI_ONGROUND ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 );
		}
		if ( weapon_changed ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Crouched", 4 );
		}
	}
}

void player::Legs_Uncrouch() {
	playAnim( ANIMCHANNEL_LEGS, "crouch_up" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void player::Legs_Turn_Left() {
	playAnim( ANIMCHANNEL_LEGS, "turn_left" );
	
	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( AI_FORWARD || AI_BACKWARD || AI_STRAFE_LEFT || AI_STRAFE_RIGHT ) {
			Legs_Walk();
		}
		waitFrame();
	}
	
	AI_TURN_LEFT = false;
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void player::Legs_Turn_Right() {
	playAnim( ANIMCHANNEL_LEGS, "turn_right" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( AI_FORWARD || AI_BACKWARD || AI_STRAFE_LEFT || AI_STRAFE_RIGHT ) {
			Legs_Walk();
		}
		waitFrame();
	}
	
	AI_TURN_RIGHT = false;
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void player::Legs_Walk() {
	weapon_changed = false;
	if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }
	if ( AI_RUN )								{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
	if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
	if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Forward", 4 ); }
	if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Backward", 4 ); }
	if ( AI_STRAFE_LEFT && !AI_STRAFE_RIGHT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Left", 2 ); }
	if ( AI_STRAFE_RIGHT && !AI_STRAFE_LEFT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Right", 2 ); }

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void player::Legs_Walk_Forward() {
	playCycle( ANIMCHANNEL_LEGS, "walk" );
	
	eachFrame {
		if ( AI_JUMP )						{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }
		if ( !AI_ONGROUND )					{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( AI_RUN )						{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_CROUCH )					{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }
		if ( AI_BACKWARD || !AI_FORWARD || weapon_changed )	{ Legs_Walk(); }
	}
}

void player::Legs_Walk_Backward() {
	playCycle( ANIMCHANNEL_LEGS, "walk_backwards" );
	
	eachFrame {
		if ( AI_JUMP )						{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }
		if ( !AI_ONGROUND )					{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( AI_RUN )						{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_CROUCH && AI_BACKWARD )		{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk_Backward", 4 ); }
		if ( AI_CROUCH )					{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }
		if ( !AI_BACKWARD || AI_FORWARD || weapon_changed )	{ Legs_Walk(); }
	}
}

void player::Legs_Walk_Left() {
	playCycle( ANIMCHANNEL_LEGS, "walk_strafe_left" );
	
	eachFrame {
		if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }
		if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( AI_RUN )								{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_CROUCH )							{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }
		if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Forward", 4 ); }
		if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Backward", 4 ); }
		if ( !AI_STRAFE_LEFT || AI_STRAFE_RIGHT || weapon_changed )	{ Legs_Walk(); }
	}
}

void player::Legs_Walk_Right() {
	playCycle( ANIMCHANNEL_LEGS, "walk_strafe_right" );
	
	eachFrame {
		if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }
		if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( AI_RUN )								{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 4 ); }
		if ( AI_CROUCH )							{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }
		if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Forward", 4 ); }
		if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Walk_Backward", 4 ); }
		if ( AI_STRAFE_LEFT || !AI_STRAFE_RIGHT || weapon_changed )	{ Legs_Walk(); }
	}
}

void player::Legs_Run() {
	weapon_changed = false;
	if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 8 ); }
	if ( !AI_RUN )								{ Legs_Walk(); }
	if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 8 ); }
	if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Forward", 2 ); }
	if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Backward", 2 ); }
	if ( AI_STRAFE_LEFT && !AI_STRAFE_RIGHT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Left", 2 ); }
	if ( AI_STRAFE_RIGHT && !AI_STRAFE_LEFT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Right", 2 ); }

	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 );
}

void player::Legs_Run_Forward() {
	playCycle( ANIMCHANNEL_LEGS, "run_forward" );
	
	eachFrame {
		if ( AI_JUMP )						{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 8 ); }
		if ( !AI_ONGROUND )					{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 8 ); }
		if ( !AI_RUN )						{ Legs_Walk(); }
		if ( AI_CROUCH )					{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 8 ); }
		if ( AI_BACKWARD || !AI_FORWARD || weapon_changed )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
	}
}

void player::Legs_Run_Backward() {
	playCycle( ANIMCHANNEL_LEGS, "run_backwards" );
	
	eachFrame {
		if ( AI_JUMP )						{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 8 ); }
		if ( !AI_ONGROUND )					{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 8 ); }
		if ( !AI_RUN )						{ Legs_Walk(); }
		if ( AI_CROUCH && AI_BACKWARD )		{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk_Backward", 4 ); }
		if ( AI_CROUCH )					{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 8 ); }
		if ( !AI_BACKWARD || AI_FORWARD || weapon_changed )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run", 8 ); }
	}
}

void player::Legs_Run_Left() {
	playCycle( ANIMCHANNEL_LEGS, "run_strafe_left" );
	
	eachFrame {
		if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 8 ); }
		if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 8 ); }
		if ( !AI_RUN )								{ Legs_Walk(); }
		if ( AI_CROUCH )							{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 8 ); }
		if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Forward", 8 ); }
		if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Backward", 8 ); }
		if ( AI_STRAFE_RIGHT && !AI_STRAFE_LEFT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Right", 2 ); }
		if ( !AI_STRAFE_LEFT || AI_STRAFE_RIGHT || weapon_changed )	{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void player::Legs_Run_Right() {
	playCycle( ANIMCHANNEL_LEGS, "run_strafe_right" );
	
	eachFrame {
		if ( AI_JUMP )								{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 8 ); }
		if ( !AI_ONGROUND )							{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 8 ); }
		if ( !AI_RUN )								{ Legs_Walk(); }
		if ( AI_CROUCH )							{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 8 ); }
		if ( AI_FORWARD && !AI_BACKWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Forward", 8 ); }
		if ( AI_BACKWARD && !AI_FORWARD )			{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Backward", 8 ); }
		if ( AI_STRAFE_LEFT && !AI_STRAFE_RIGHT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Run_Left", 2 ); }
		if ( !AI_STRAFE_RIGHT || AI_STRAFE_LEFT || weapon_changed )	{ animState( ANIMCHANNEL_LEGS, "Legs_Idle", 8 ); }
	}
}

void player::Legs_CrouchWalk() {
	weapon_changed = false;
	playCycle( ANIMCHANNEL_LEGS, "crouch_walk" );
	
	eachFrame {
		if ( AI_JUMP )		{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }	
		if ( !AI_ONGROUND )	{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( !AI_CROUCH )	{ Legs_Walk(); }
		if ( AI_BACKWARD && !AI_FORWARD ) { animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk_Backward", 4 ); }
		if ( !AI_FORWARD && !AI_STRAFE_LEFT && !AI_STRAFE_RIGHT ) { animState( ANIMCHANNEL_LEGS, "Legs_Crouched", 4 ); }
		if ( weapon_changed ) { animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }	
	}
}

void player::Legs_CrouchWalk_Backward() {
	weapon_changed = false;
	playCycle( ANIMCHANNEL_LEGS, "crouch_walk_backwards" );
	
	eachFrame {
		if ( AI_JUMP )		{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 ); }	
		if ( !AI_ONGROUND )	{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 ); }
		if ( !AI_CROUCH )	{ Legs_Walk(); }
		if ( AI_FORWARD && !AI_BACKWARD )	{ animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }
		if ( !AI_BACKWARD && !AI_STRAFE_LEFT && !AI_STRAFE_RIGHT )	{ animState( ANIMCHANNEL_LEGS, "Legs_Crouched", 4 ); }
		if ( weapon_changed ) { animState( ANIMCHANNEL_LEGS, "Legs_CrouchWalk", 4 ); }	
	}
}

void player::Legs_Jump() {
	if ( AI_RUN ) {
		playAnim( ANIMCHANNEL_LEGS, "run_jump" );
	} else {
		playAnim( ANIMCHANNEL_LEGS, "jump" );
	}

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( AI_JUMP ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Jump", 4 );
		}
		
		if ( AI_ONGROUND ) {
			if ( AI_HARDLANDING ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Land_Hard", 2 );
			}
			if ( AI_SOFTLANDING ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Land_Soft", 2 );
			}
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
		}
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Fall", 4 );
}

void player::Legs_Fall() {
	playCycle( ANIMCHANNEL_LEGS, "fall" );

	eachFrame {
		if ( AI_JUMP ) {
			animState( ANIMCHANNEL_LEGS, "Legs_Jump", 2 );
		}
		
		if ( AI_ONGROUND ) {
			if ( AI_HARDLANDING ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Land_Hard", 2 );
			}
			if ( AI_SOFTLANDING ) {
				animState( ANIMCHANNEL_LEGS, "Legs_Land_Soft", 2 );
			}
			animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
		}
	}
}

void player::Legs_Land_Hard() {
	playAnim( ANIMCHANNEL_LEGS, "hard_land" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( AI_CROUCH )			{ animState( ANIMCHANNEL_LEGS, "Legs_Crouch", 2 ); }
		if ( AI_JUMP )				{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 2 ); }
		if ( !AI_ONGROUND )			{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 2 ); }
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

void player::Legs_Land_Soft() {
	playAnim( ANIMCHANNEL_LEGS, "soft_land" );

	while( !animDone( ANIMCHANNEL_LEGS, 4 ) ) {
		if ( AI_CROUCH )			{ animState( ANIMCHANNEL_LEGS, "Legs_Crouch", 2 ); }
		if ( AI_JUMP )				{ animState( ANIMCHANNEL_LEGS, "Legs_Jump", 2 ); }
		if ( !AI_ONGROUND )			{ animState( ANIMCHANNEL_LEGS, "Legs_Fall", 2 ); }
		waitFrame();
	}
	
	animState( ANIMCHANNEL_LEGS, "Legs_Idle", 4 );
}

//@doomscript-blueprint begin 6
//@source 4434DEEA
//@catalog 0C260740
//@node CC1FCBB6-0 40 40
//@node 11CDE3F3-0 330 40
//@node A70ACB09-0 125 145
//@node 7AEBBD89-0 610 40
//@node 71291C85-0 405 145
//@node 67E8C9D4-0 890 40
//@node FF2AE0A6-0 1170 40
//@node 55D6BF87-0 40 40
//@node 79A67871-0 40 40
//@node 45A173B9-0 330 40
//@node 0EAC028B-0 610 40
//@node 5B6FC4BD-0 40 40
//@node 7DD05DA1-0 330 40
//@node 2F120928-0 40 40
//@node E17A26AB-0 330 40
//@node 7B238BA0-0 105 145
//@node 1926DB4E-0 610 40
//@node 5D7F5F35-0 40 40
//@node E9164E0C-0 330 40
//@node D1802E27-0 40 40
//@node 4935BA7A-0 330 40
//@node 4B925530-0 105 145
//@node EDD0EABB-0 610 40
//@node 4BF724B5-0 890 40
//@node 6AE9D242-0 40 40
//@node 06C13C45-0 330 40
//@node 66CA49E6-0 125 140
//@node DC598F2E-0 -80 140
//@node D94821C4-0 610 40
//@node 864DB0EB-0 40 40
//@node B0A020EB-0 330 40
//@node F9C55F32-0 125 145
//@node CF5E5ED6-0 610 40
//@node 10C48637-0 890 40
//@node AAA07B28-0 1170 40
//@node F83CE5BB-0 1450 40
//@node 5824DCB2-0 40 40
//@node FF85E2AE-0 330 40
//@node 60B0EADB-0 610 40
//@node CD382D9C-0 890 200
//@node 11B25636-0 685 305
//@node FB81A457-0 1170 360
//@node F16DE6E5-0 1450 200
//@node 40E3C990-0 1245 305
//@node CD92046E-0 1040 305
//@node 6CC4F77A-0 1040 305
//@node 2713FB85-0 1040 473
//@node FA245490-0 1730 360
//@node 8DB284A0-0 2010 200
//@node 966E027C-0 1805 305
//@node 44674520-0 1600 305
//@node AC886A06-0 1600 305
//@node 1E6B697D-0 2290 360
//@node 630A2BE7-0 2570 200
//@node B54D5E0B-0 2365 305
//@node 86C1AA52-0 2850 360
//@node 4F124710-0 40 40
//@node 0A50986D-0 330 40
//@node FFFCEF28-0 105 145
//@node 4024722F-0 610 40
//@node F6AB789E-0 405 232
//@node 5E720081-0 890 40
//@node B07C97D0-0 685 145
//@node 96A32EA9-0 1170 40
//@node 0344F295-0 730 145
//@node 83C1D105-0 960 145
//@node 0014D739-0 1450 200
//@node 5FD99C1D-0 1245 305
//@node EFA4C21C-0 1730 360
//@node DFF8002A-0 1505 465
//@node D5F8751B-0 2010 360
//@node 492D286E-0 1805 465
//@node 23A9311D-0 1600 465
//@node 001D1AC8-0 1600 549
//@node ED8DBD08-0 2290 520
//@node 7FD50130-0 2570 200
//@node 8A48AC6D-0 2850 40
//@node 446A57F6-0 3130 40
//@node 028DEDE5-0 40 40
//@node 19800CDF-0 330 40
//@node 6357C81F-0 105 145
//@node E8B6C194-0 610 200
//@node FE6DBEB6-0 890 200
//@node 8DCF552E-0 450 305
//@node 11792D3E-0 680 305
//@node 5F283CD0-0 1170 360
//@node F4A27400-0 965 465
//@node 179CC72E-0 760 465
//@node F03B773A-0 760 465
//@node 65603645-0 760 633
//@node F02ACF0C-0 1450 520
//@node E0E017B7-0 1730 360
//@node 12997F41-0 2010 200
//@node F7F8AB50-0 1805 305
//@node CD22AF4A-0 2290 360
//@node FE6DBEB6-1 2570 360
//@node 2E28CB83-0 2130 465
//@node 09388FD3-0 2360 465
//@node 5F283CD0-1 2850 520
//@node 44B9B443-0 2645 625
//@node 3B8E0011-0 2440 625
//@node 5DD8769B-0 2440 625
//@node 6091E5A2-0 2440 793
//@node F02ACF0C-1 3130 680
//@node E0E017B7-1 3410 520
//@node A69C3E71-0 3690 200
//@node D90156B3-0 3970 200
//@node 5BA2DE9C-0 3530 305
//@node 6EDDFA6C-0 3760 305
//@node 5F283CD0-2 4250 360
//@node 73B49E9A-0 4045 465
//@node 3DB83164-0 3840 465
//@node C267E4D4-0 3840 465
//@node 43CA4133-0 3840 633
//@node F02ACF0C-2 4530 520
//@node E0E017B7-2 4810 360
//@node 073EF103-0 5370 200
//@node D90156B3-1 5650 200
//@node EF50FE99-0 5210 305
//@node 0832D9A9-0 5440 305
//@node 5F283CD0-3 5930 360
//@node ACF81CC5-0 5725 465
//@node 8A770767-0 5520 465
//@node CEEBAB05-0 5520 465
//@node 58BF42E8-0 5520 633
//@node F02ACF0C-3 6210 520
//@node E0E017B7-3 6490 360
//@node 453A0356-0 6770 40
//@node 425A805F-0 40 40
//@node 9FC10118-0 330 40
//@node 2D237DD9-0 610 40
//@node 86CC35BF-0 405 145
//@node FE34878D-0 200 145
//@node CA6F4B66-0 200 229
//@node B119A042-0 200 145
//@node E6FC084D-0 200 397
//@node 8E1500E8-0 890 200
//@node 90AD8A74-0 685 305
//@node FAE13F75-0 1170 360
//@node A1645819-0 1450 200
//@node 8F009FC8-0 2010 40
//@node 779560E4-0 2290 40
//@node 1876871E-0 1805 232
//@node C467D29B-0 1600 232
//@node F0B6CCA2-0 2570 40
//@node A4DD23CB-0 2570 40
//@node E0126D9F-0 2365 145
//@node A9737D39-0 2850 40
//@node 3DD3E627-0 2410 145
//@node CF10AAB7-0 2640 145
//@node A1645819-1 3410 200
//@node E3B179D4-0 3410 40
//@node 5106C1AA-0 3205 145
//@node 450C3229-0 3000 145
//@node 0B8055ED-0 3000 229
//@node 0DB1E32A-0 3970 200
//@node BBFC2E14-0 4250 40
//@node E44FEC04-0 40 40
//@node 0883AEB9-0 330 40
//@node B974D566-0 125 232
//@node C700B2E3-0 -80 232
//@node E816F1D5-0 610 40
//@node 078FBE2E-0 890 40
//@node CD382CEE-0 685 145
//@node 1285B690-0 1170 40
//@node 807937D2-0 730 145
//@node D6774902-0 960 145
//@node 71036A9F-0 1450 200
//@node 6D02F903-0 1245 305
//@node D9E084A5-0 1040 305
//@node 5C4012BF-0 1040 305
//@node E8D5C6E6-0 1040 473
//@node B04EFD26-0 1730 360
//@node DB645AD8-0 2010 200
//@node 71036A9F-1 2290 40
//@node B596EEC0-0 2085 145
//@node AABD4EB2-0 1880 145
//@node 9D052A7E-0 1880 145
//@node 237138A9-0 1880 313
//@node B04EFD26-1 2570 200
//@node 7A491F39-0 2850 40
//@node 5D8D8BD2-0 40 40
//@node EA058874-0 330 40
//@node 65124512-0 610 40
//@node 303E0E95-0 170 145
//@node C2AA07C5-0 400 145
//@node C22AA00C-0 890 200
//@node 6E18AC73-0 685 305
//@node 2D0B1827-0 480 305
//@node 842EF4F1-0 480 305
//@node EC2A7F31-0 1170 360
//@node DD47B541-0 1450 200
//@node 55E6B001-0 1245 305
//@node 617F71BB-0 1040 305
//@node 15D0C6E9-0 1040 305
//@node F5A3BEEC-0 1040 473
//@node 0D38FEFC-0 1730 360
//@node 9257027B-0 2010 200
//@node 2769DDA3-0 1805 305
//@node 9D0A1E06-0 2290 360
//@node 34C74A86-0 2570 200
//@node C22AA00C-1 2850 40
//@node B8AC295E-0 2645 145
//@node 360401EA-0 2440 145
//@node B88B25F4-0 2440 145
//@node EC2A7F31-1 3130 200
//@node 8FB00315-0 3690 200
//@node 037A4B54-0 40 40
//@node D537C0DB-0 330 40
//@node A54D3A10-0 610 40
//@node 33063F02-0 170 145
//@node 9E0FD7F2-0 400 145
//@node B6035118-0 890 200
//@node 905F7EC6-0 1170 40
//@node 49E497C4-0 945 145
//@node 8E873C78-0 1450 40
//@node F9E3633D-0 1245 145
//@node AE295BE5-0 1730 40
//@node F62FE281-0 40 40
//@node 04AA3117-0 330 40
//@node 034072FB-0 125 145
//@node 8192792B-0 610 40
//@node 3DDB992F-0 890 40
//@node 7F49779F-0 450 145
//@node 6018546F-0 680 145
//@node 539DB55F-0 1170 200
//@node D4364040-0 40 40
//@node B59477EB-0 330 40
//@node 0229F986-0 125 140
//@node 9D96F4A4-0 -80 140
//@node E553C8F0-0 610 40
//@node AF4E8904-0 40 40
//@node 008E23BF-0 330 40
//@node C4FB2E3F-0 125 145
//@node 5663702D-0 610 40
//@node D0019EBF-0 890 40
//@node 0F6D9EF1-0 1170 200
//@node AAE4BA60-0 965 305
//@node 0896D932-0 1450 360
//@node E1B3BF94-0 1730 200
//@node C92147DF-0 1525 305
//@node 836E9D59-0 1320 305
//@node 6402304D-0 2010 360
//@node C93FCF5F-0 2290 200
//@node F71285D1-0 2085 305
//@node 7F7A8D9D-0 1880 305
//@node 5AB1EB59-0 1880 389
//@node 734BFC15-0 1880 473
//@node 1795690E-0 1880 557
//@node 31B8ACEF-0 2570 360
//@node 802C1598-0 2850 200
//@node ACD36418-0 2645 305
//@node 752801C5-0 3130 360
//@node 7122CE9F-0 3410 200
//@node 0459607E-0 3205 305
//@node 66ECAB9C-0 3690 360
//@node 2EFEAD4F-0 3970 200
//@node 7C6E4F5A-0 3765 305
//@node 225F65A8-0 4250 360
//@node 29365873-0 4530 200
//@node 5A35D8CA-0 4325 305
//@node 5DD6D514-0 4810 360
//@node 47860E78-0 40 40
//@node 67CD582E-0 330 40
//@node AB20C4D7-0 610 40
//@node 9787380A-0 170 145
//@node 9BA3C65A-0 400 145
//@node 7F378B90-0 890 200
//@node 73E090B3-0 685 305
//@node A0778B01-0 480 305
//@node D9B2F279-0 1170 360
//@node 8AA36168-0 1450 200
//@node E5C1CC5B-0 1730 40
//@node BEEFC7F9-0 40 40
//@node F4B43C9E-0 330 40
//@node 90B7364C-0 125 145
//@node 174A4007-0 610 40
//@node 9319E79E-0 890 40
//@node DDF68B95-0 1170 200
//@node 217180F6-0 965 305
//@node 8E89CD4E-0 760 305
//@node 15EEC56A-0 1450 360
//@node A67CE26D-0 1730 200
//@node 53061F39-0 1525 305
//@node FA0ACD24-0 2010 360
//@node 1C0EB7F7-0 2290 200
//@node 08362F06-0 2085 305
//@node 151678FC-0 2570 360
//@node 234746DD-0 2850 200
//@node 3657AE69-0 2645 305
//@node FA0ACD24-1 3130 360
//@node 84E8749C-0 3410 200
//@node 76BBA608-0 3205 305
//@node FA0ACD24-2 3690 360
//@node 0C5389E2-0 3970 200
//@node 6FEEF08D-0 3765 305
//@node A267BA1D-0 4250 360
//@node 9E13AAC1-0 4530 200
//@node 93326B76-0 4325 305
//@node C294AEEE-0 4120 305
//@node A0B2C42A-0 4810 360
//@node 62301E62-0 5090 200
//@node 3B3FC505-0 4885 305
//@node E09DA810-0 5370 360
//@node 5188E037-0 40 40
//@node F72C477E-0 330 40
//@node 929D1C4C-0 610 40
//@node 69279A6D-0 170 145
//@node 7E4B0B3D-0 400 145
//@node 6DF2149D-0 890 200
//@node A875DAB1-0 1170 40
//@node E89E2B77-0 40 40
//@node C1AE701D-0 330 40
//@node 96C0765C-0 610 40
//@node CAAC60B1-0 170 145
//@node BBC255C1-0 400 145
//@node BD3FFD60-0 890 200
//@node 8A22276E-0 685 305
//@node 38FF28FC-0 480 305
//@node 798B2752-0 480 389
//@node 06603C8C-0 480 473
//@node C5FC9879-0 480 557
//@node 8EDCC20E-0 1170 360
//@node D97ED845-0 1450 200
//@node 05BBD513-0 1730 40
//@node 012D5744-0 1525 145
//@node C5D2F939-0 2010 40
//@node EFE54D68-0 40 40
//@node 89CD39C5-0 330 40
//@node 312B00E7-0 610 40
//@node CD956DCB-0 170 145
//@node 1D23C2DB-0 400 145
//@node 754E3D97-0 890 200
//@node 26B78B50-0 685 305
//@node 37396AA8-0 480 305
//@node 8444D136-0 480 389
//@node 4DB5EF08-0 480 473
//@node E4F6257D-0 480 557
//@node 0E24786F-0 1170 360
//@node DC57F11C-0 1450 200
//@node 7BE48733-0 1730 40
//@node 7578F634-0 1525 145
//@node 941A0C94-0 2010 40
//@node 111A08AB-0 40 40
//@node 3F5D5824-0 330 40
//@node 52DA2C69-0 125 145
//@node 977FD354-0 610 40
//@node E1184EC0-0 405 145
//@node CF15A18F-0 200 145
//@node 67E6A33E-0 890 40
//@node DE362E9F-0 685 145
//@node 1884CFFB-0 480 145
//@node EB4D3156-0 1170 40
//@node ADE9CBB7-0 965 145
//@node F7245F40-0 760 145
//@node E33E5149-0 1450 40
//@node 9D155A91-0 1245 145
//@node 738C10B8-0 1040 145
//@node 2A4862C6-0 1040 229
//@node 53C94DA5-0 1730 40
//@node A827BFBC-0 1525 145
//@node C82B1A9D-0 1320 145
//@node C89FE259-0 1320 229
//@node 317502BE-0 2010 40
//@node A0E4FFF8-0 1805 145
//@node 9B5A6C86-0 1600 145
//@node 330BAD1B-0 1600 229
//@node 51927EAF-0 2290 40
//@node F978CFB6-0 2085 145
//@node C28FE45D-0 1880 145
//@node C1C2D376-0 1880 229
//@node 04E66AC9-0 2570 40
//@node CEE8D0C1-0 40 40
//@node 753C7D44-0 330 40
//@node FC691446-0 610 40
//@node 033BB85A-0 890 200
//@node 90DB2D43-0 685 305
//@node C22067CC-0 480 305
//@node 1FBF641C-0 1170 200
//@node A2D51C42-0 965 305
//@node 144F767F-0 760 305
//@node F72E762C-0 1450 200
//@node 4E623E0D-0 1245 305
//@node 0237B91D-0 1040 305
//@node 8A7910D9-0 1730 200
//@node F624AB97-0 1525 305
//@node 8C4D8B7B-0 1320 305
//@node E2E6811C-0 2010 200
//@node DDCC0784-0 1805 305
//@node 0CD079B8-0 1600 305
//@node 70F9ADC6-0 1600 389
//@node EF6FE05F-0 1600 305
//@node 405AE775-0 40 40
//@node 05381915-0 330 40
//@node 788BFA70-0 610 40
//@node 49428F62-0 890 200
//@node DF3A655C-0 685 305
//@node 6060A2ED-0 480 305
//@node ADA5FF74-0 1170 200
//@node AFDE95CD-0 965 305
//@node BD293694-0 760 305
//@node 3CA8C594-0 1450 200
//@node BDAB1E5F-0 1245 305
//@node 9C3ECCD9-0 1040 305
//@node 2C2461BD-0 1730 200
//@node 6AC3326C-0 1525 305
//@node 00B6AF19-0 1320 305
//@node 5C3C1AA6-0 1320 389
//@node 7E9A56A1-0 2010 200
//@node BC9074D5-0 1805 305
//@node AF3BD6BF-0 1600 305
//@node E8908D4E-0 2290 200
//@node 51CC729A-0 2085 305
//@node 5B37A442-0 1880 305
//@node 2FF6CA7C-0 1880 389
//@node 0A566A35-0 1880 305
//@node 0C5687AD-0 40 40
//@node 2B5F762E-0 330 40
//@node 06260F4C-0 610 40
//@node EB8632A2-0 890 200
//@node C598CE2C-0 685 305
//@node F30142ED-0 480 305
//@node FA158334-0 1170 200
//@node 9A18E1BA-0 965 305
//@node F58618CD-0 760 305
//@node 422023D4-0 1450 200
//@node 3C1B5A3A-0 1245 305
//@node 1CEE2D02-0 1040 305
//@node 41B698E1-0 1730 200
//@node 2EBBF056-0 1525 305
//@node 18F96CE0-0 1320 305
//@node C0E0CAB7-0 2010 200
//@node C30CA163-0 1805 305
//@node 87BF9BAC-0 1600 305
//@node B33185C2-0 1600 389
//@node 3EA44CDF-0 2290 200
//@node D73B213E-0 2085 305
//@node 10AF9EC1-0 1880 305
//@node C6337A95-0 1880 389
//@node 099FC063-0 2570 200
//@node ACA5A614-0 2365 305
//@node A527A647-0 2160 305
//@node 3A89D458-0 2160 389
//@node 4E0BFDA4-0 2160 305
//@node 6C8A38E6-0 40 40
//@node 055C3908-0 330 40
//@node 18E5BDC1-0 610 40
//@node F3301D55-0 890 200
//@node C5A08625-0 685 305
//@node 7F08A762-0 480 305
//@node E0D44F15-0 1170 200
//@node 9E82042D-0 965 305
//@node C0F2EA3A-0 760 305
//@node CC7EAB03-0 1450 200
//@node 86E9C588-0 1245 305
//@node 9FB399B6-0 1040 305
//@node C6076142-0 1730 200
//@node CC608694-0 1525 305
//@node 15C1E320-0 1320 305
//@node ABD34B86-0 2010 200
//@node 2AC5E2E9-0 1805 305
//@node 9E7C711C-0 1600 305
//@node 48DEC332-0 1600 389
//@node 02D69EC0-0 2290 200
//@node 89CB6B44-0 2085 305
//@node B26A454D-0 1880 305
//@node CCE3AEC9-0 1880 389
//@node 48E9267A-0 2570 200
//@node E244053B-0 2365 305
//@node 427DC6BC-0 2160 305
//@node 2FEA9FE9-0 2160 389
//@node E55458C3-0 2160 305
//@node B5367073-0 40 40
//@node 40E1A91E-0 330 40
//@node 3F09D80E-0 125 145
//@node 359B4C34-0 610 40
//@node 469CEA58-0 405 145
//@node D715F04D-0 200 145
//@node F9687099-0 890 40
//@node F68EB5C4-0 685 145
//@node 97CF76DF-0 480 145
//@node A47E5CBE-0 1170 40
//@node EEB886AF-0 965 145
//@node 16A3357E-0 760 145
//@node E9622509-0 1450 40
//@node 7540A9E6-0 1245 145
//@node C55E757D-0 1040 145
//@node 0CA93CF9-0 1040 229
//@node 67918EC5-0 1730 40
//@node 9E81AA18-0 1525 145
//@node 76BC8BBF-0 1320 145
//@node C25B206F-0 1320 229
//@node 5106653E-0 2010 40
//@node 26DD2720-0 1805 145
//@node F66A3152-0 1600 145
//@node D4658F5F-0 1600 229
//@node CD32B487-0 2290 40
//@node D1CCE0C9-0 2085 145
//@node A72C2E26-0 1880 145
//@node 6D02477B-0 1880 229
//@node 0FDCB659-0 2570 40
//@node 468E4F29-0 40 40
//@node 3E033160-0 330 40
//@node 5357BE28-0 610 40
//@node 5E5F79BA-0 890 200
//@node 4505B137-0 685 305
//@node 8F8EEB36-0 480 305
//@node 3E23759C-0 1170 200
//@node 0614643C-0 965 305
//@node 10D43DF7-0 760 305
//@node 181A3AEB-0 1450 200
//@node 7492D2CC-0 1245 305
//@node E712E003-0 1040 305
//@node FC969AD1-0 1730 200
//@node 1223209B-0 1525 305
//@node 48928F29-0 1320 305
//@node 3AB02566-0 2010 200
//@node EF5B1790-0 1805 305
//@node 5A866986-0 1600 305
//@node 76A713D8-0 1600 389
//@node 74D120A9-0 1600 305
//@node 5A036C2D-0 40 40
//@node DDEC522B-0 330 40
//@node 46B911CE-0 610 40
//@node 49FD81EA-0 890 200
//@node A5E05377-0 685 305
//@node 0C89AA1C-0 480 305
//@node 837ADCAC-0 1170 200
//@node 140495F5-0 965 305
//@node BD05322E-0 760 305
//@node D4250FBB-0 1450 200
//@node AFAB5351-0 1245 305
//@node 73B353E8-0 1040 305
//@node 18ABE9F9-0 1730 200
//@node 12C77E73-0 1525 305
//@node 045450F4-0 1320 305
//@node C58CD23B-0 1320 389
//@node 1162D561-0 2010 200
//@node 1605E10A-0 1805 305
//@node 6C1FC326-0 1600 305
//@node 4C8A6A10-0 2290 200
//@node 86E17477-0 2085 305
//@node C9DF587F-0 1880 305
//@node 0CBDFD2F-0 1880 389
//@node 040E9E14-0 1880 305
//@node 4C8EC485-0 40 40
//@node 9939AAC8-0 330 40
//@node 582D88F2-0 610 40
//@node 68E7AB8A-0 890 200
//@node 4A794275-0 685 305
//@node 49D768FA-0 480 305
//@node A6E8CCCC-0 1170 200
//@node B2CFF5B3-0 965 305
//@node 3F16AACC-0 760 305
//@node 3324E9DB-0 1450 200
//@node D7BDC0F4-0 1245 305
//@node 18249689-0 1040 305
//@node FDCE65C1-0 1730 200
//@node 0D5B4FF9-0 1525 305
//@node 173A4A0D-0 1320 305
//@node 2608FB45-0 2010 200
//@node 4EAFEEA1-0 1805 305
//@node BCC49E84-0 1600 305
//@node 73810F8A-0 1600 389
//@node 026329AD-0 2290 200
//@node 9E21F409-0 2085 305
//@node 28B8F9DA-0 1880 305
//@node D3D668E4-0 1880 389
//@node BAB7B995-0 2570 200
//@node 34B11353-0 2365 305
//@node 72A50942-0 2160 305
//@node F5EEF38F-0 2160 389
//@node 98D2B344-0 2850 200
//@node 27F2A439-0 2645 305
//@node A82C0209-0 2440 305
//@node BAA1110A-0 2440 389
//@node 974CA332-0 2440 305
//@node 089A7DDE-0 40 40
//@node B6A9F134-0 330 40
//@node 385E856F-0 610 40
//@node A2032425-0 890 200
//@node E7537E4F-0 685 305
//@node 44CDD1BE-0 480 305
//@node 4E9451DD-0 1170 200
//@node 24F8DEF2-0 965 305
//@node 3AC20EB1-0 760 305
//@node 0098B384-0 1450 200
//@node 884B71AD-0 1245 305
//@node 1F3B72AE-0 1040 305
//@node 280E77E2-0 1730 200
//@node 22E2B2F3-0 1525 305
//@node C89A8165-0 1320 305
//@node A9D745AE-0 2010 200
//@node 122EF205-0 1805 305
//@node 708D8562-0 1600 305
//@node FA69A5DC-0 1600 389
//@node C17A8F4C-0 2290 200
//@node C38AA2D0-0 2085 305
//@node 65CFE7F9-0 1880 305
//@node FC7E5C9D-0 1880 389
//@node ACFBEBE1-0 2570 200
//@node 1E3C9C4D-0 2365 305
//@node A96806B3-0 2160 305
//@node 0F38139C-0 2160 389
//@node B591EEF1-0 2850 200
//@node A7548B1E-0 2645 305
//@node 562B6078-0 2440 305
//@node 17F2546D-0 2440 389
//@node D025527F-0 2440 305
//@node 7C05C4B9-0 40 40
//@node 45ED16AA-0 330 40
//@node 345D4557-0 125 145
//@node 3F9544D9-0 610 40
//@node 73A2EDAA-0 890 40
//@node E0728BFA-0 1170 200
//@node 02BD19E8-0 965 305
//@node F3997177-0 760 305
//@node 45A12A3C-0 1450 200
//@node 5CBDB85F-0 1245 305
//@node BFDF2820-0 1040 305
//@node B2D22122-0 1730 200
//@node FCE674A6-0 1525 305
//@node AA021F39-0 1320 305
//@node 1ACA7E4D-0 2010 200
//@node C6DD6C94-0 1805 305
//@node 2107FBFB-0 1600 305
//@node 846BA053-0 1600 389
//@node DFCDA220-0 2290 200
//@node 9592D4D5-0 2085 305
//@node 7E5A8C75-0 1880 305
//@node 93C8605D-0 1880 389
//@node 1DAE0776-0 1880 473
//@node F8BF49CF-0 2570 200
//@node 65F605D4-0 2365 305
//@node 09481CCA-0 2160 305
//@node CAF0A3DF-0 40 40
//@node A633BAA2-0 330 40
//@node 2A353D37-0 125 145
//@node 97883432-0 610 40
//@node 1C9B38CE-0 890 40
//@node 7D07053C-0 1170 200
//@node 08DDF4A2-0 965 305
//@node CBE9F72F-0 760 305
//@node E422A42E-0 1450 200
//@node 0F57FDFC-0 1245 305
//@node C143260F-0 1040 305
//@node AFCDB9CC-0 1730 200
//@node 002211C0-0 1525 305
//@node E44F2E89-0 1320 305
//@node 89ED1D4D-0 2010 200
//@node 22617F0B-0 1805 305
//@node BA565278-0 1600 305
//@node 749E1186-0 1600 389
//@node 986AAE86-0 2290 200
//@node B7DD9CF7-0 2085 305
//@node 7A0AE1E9-0 1880 305
//@node 4574C925-0 1880 389
//@node 708DE35E-0 1880 473
//@node 297D29C5-0 2570 200
//@node 8F48420B-0 2365 305
//@node 72EAB383-0 2160 305
//@node 5F47540A-0 40 40
//@node B6B7DD46-0 330 40
//@node D2680D41-0 125 145
//@node A8332003-0 610 200
//@node 926ED529-0 1170 200
//@node 8B25FAF5-0 1450 40
//@node 9864CA68-0 1010 145
//@node 0091D738-0 1240 145
//@node 9A47C333-0 1730 200
//@node BF0DF012-0 1525 305
//@node EE234BB8-0 2010 360
//@node 11211B79-0 2290 200
//@node 2F87C84B-0 2085 305
//@node 668B0FA3-0 2570 360
//@node 84B5631F-0 2365 465
//@node 1073605B-0 2850 520
//@node 3FD883B4-0 3130 360
//@node 23C388BE-0 2925 465
//@node C4DE382C-0 3410 520
//@node 7280296E-0 3690 360
//@node F37C0212-0 3970 200
//@node AB105C9B-0 4250 40
//@node A2FBA3E7-0 40 40
//@node A4E228F2-0 330 40
//@node 6C71C7CC-0 610 40
//@node 1A7821FC-0 890 200
//@node 31B1FE31-0 685 305
//@node 9B58C391-0 1170 360
//@node 0A5C7BAE-0 1450 200
//@node E2F8B994-0 1245 305
//@node 09611F8E-0 1730 360
//@node 3E274134-0 1525 465
//@node CE4CEB6E-0 2010 520
//@node 20C01249-0 2290 360
//@node F45F47B2-0 2085 465
//@node 10A5B1A1-0 2570 520
//@node 168BA8A1-0 2850 360
//@node 0635E8E1-0 40 40
//@node CB9C33B1-0 330 40
//@node 3EA8DC72-0 610 40
//@node 7BB21967-0 170 145
//@node C8660817-0 400 145
//@node D6AEEAB8-0 890 200
//@node 93F4C96D-0 685 305
//@node C1B50B3C-0 480 305
//@node E9B3AEF4-0 1170 200
//@node 360D4C24-0 965 305
//@node 759E39DB-0 760 305
//@node DBC675C2-0 1450 200
//@node BF0BD4F1-0 1245 305
//@node BC8B913E-0 1040 305
//@node 42EC67CF-0 1730 200
//@node 8A24718F-0 2010 40
//@node 696B3F5C-0 40 40
//@node CF82D1E1-0 330 40
//@node 57D8E44B-0 610 40
//@node 31DB9E54-0 170 145
//@node C6AE40C4-0 400 145
//@node 3989872D-0 890 200
//@node D9AB3492-0 685 305
//@node A3F3AF97-0 480 305
//@node 3BD03919-0 1170 200
//@node 3495E1B1-0 965 305
//@node FF676102-0 760 305
//@node BA678FA9-0 1450 200
//@node 5B0A35D4-0 1245 305
//@node 127835C5-0 1040 305
//@node 38049FF4-0 1730 200
//@node 1E99014C-0 2010 40
//@doomscript-blueprint end
