/***********************************************************************

doom_util.script

This defines utility functions for scripts

***********************************************************************/

/*
==================
setShaderTime

Frame command for setting the shader time to begin an effect.
==================
*/
void setShaderTime( entity self ) {
	self.setShaderParm( 4, -sys.getTime() );
}

/*
==================
clearSmoke

Clears smoke particles on monsters
==================
*/
void clearSmoke( entity self ) {
	self.setSmokeVisibility( ALL_PARTICLES, 0 );
}

/*
==================
headlook_on

Turns on Bone modification for looking.
==================
*/
void headlook_on( entity self ) {
	self.setBoneMod( true );
}

/*
==================
headlook_off

Turns off Bone modification for looking.

==================
*/
void headlook_off( entity self ) {
	self.setBoneMod( false );
}

/*
==================
overrideLegs

Used to make monster attack anims use the full body
==================
*/
void overrideLegs( entity self ) {
	self.overrideAnim( ANIMCHANNEL_LEGS );
}

/*
==================
overrideTorso

Used to make monster attack anims use the full body
==================
*/
void overrideTorso( entity self ) {
	self.overrideAnim( ANIMCHANNEL_TORSO );
}

/*
==================
waitForButtonPress

Waits for the user to press a button
==================
*/
void waitForButtonPress() {
	float buttons;

	do {
		buttons = $player1.getButtons();
		sys.wait( 0.01 );
	} while( !buttons );
}

/*
==================
abs

Returns the absolute value of a number
==================
*/
float abs( float value ) {
	if ( value < 0 ) {
		return value * -1;
	}

	return value;
}

/*
==================
unpause

Utility function that works with onSignal to unpause a script
==================
*/
void unpause() {
}

/*
==================
anglemod360

Puts angles into the range of 0 to 360
==================
*/
vector anglemod360( vector ang ) {
	while( ang_x < 0 ) {
		ang_x += 360;
	}
	while( ang_x >= 360 ) {
		ang_x -= 360;
	}
	while( ang_y < 0 ) {
		ang_y += 360;
	}
	while( ang_y >= 360 ) {
		ang_y -= 360;
	}
	while( ang_z < 0 ) {
		ang_z += 360;
	}
	while( ang_z >= 360 ) {
		ang_z -= 360;
	}

	return ang;
}

/*
==================
anglemod180

Puts angles into the range of -180 to 180
==================
*/
vector anglemod180( vector ang ) {
	while( ang_x < -180 ) {
		ang_x += 360;
	}
	while( ang_x >= 180 ) {
		ang_x -= 360;
	}
	while( ang_y < -180 ) {
		ang_y += 360;
	}
	while( ang_y >= 180 ) {
		ang_y -= 360;
	}
	while( ang_z < -180 ) {
		ang_z += 360;
	}
	while( ang_z >= 180 ) {
		ang_z -= 360;
	}

	return ang;
}

/*
==================
delayRemoveThread

Service thread for delayRemove.
==================
*/
void delayRemoveThread( entity ent, float mytime ) {
	sys.wait( mytime );
	ent.remove();
}

/*
==================
delayRemove

Causes an entity to be removed after a specified amount of time.
==================
*/
void delayRemove( entity ent, float mytime ) {
	thread delayRemoveThread( ent, mytime );
}


/*
==================
fadeOutEnt

Causes a entity to fade to black
==================
*/
void fadeOutEnt( entity ent, vector color, float totalTime ) {
	float i;
	vector c;
	float frac;
	float numTics;
	
	// convert to the total number of game tics
	numTics = totalTime * sys.getTicsPerSecond();

	for( i = 0; i < numTics; i++ ) {
		frac = ( numTics - i ) / numTics;
		c = color * frac;
		ent.setColor( c_x, c_y, c_z );
		
		// wait one game frame
		sys.waitFrame();
	}
	
	// make sure we are set to exactly black
	ent.setColor( 0, 0, 0  );
}

/*
==================
fadeInEnt

Causes a entity to from black to color
==================
*/
void fadeInEnt( entity ent, vector color, float totalTime ) {
	float i;
	vector c;
	float frac;
	float numTics;
	
	// convert to the total number of game tics
	numTics = totalTime * sys.getTicsPerSecond();	

	for( i = 0; i < numTics; i++ ) {
		frac = i / numTics;
		c = color * frac;
		ent.setColor( c_x, c_y, c_z  );
		
		// wait one game frame
		sys.waitFrame();
	}
	
	// make sure we are set to exactly the color
	ent.setColor( color_x, color_y, color_z );
}

/*
==================
crossFadeEnt

Causes a entity to from one color to another
==================
*/
void crossFadeEnt( entity ent, vector source, vector dest, float totalTime ) {
	float i;
	vector c;
	float frac;
	float numTics;
	
	// convert to the total number of game tics
	numTics = totalTime * sys.getTicsPerSecond();

	for( i = 0; i < numTics; i++ ) {
		frac = i / numTics;
		c = dest * frac + source * ( 1 - frac );
		ent.setColor( c_x, c_y, c_z  );
		
		// wait one game frame
		sys.waitFrame();
	}
	
	// make sure we are set to exactly the destination color
	ent.setColor( dest_x, dest_y, dest_z );
}

/*
==================
interpolateShaderParm

Interpolates a single shader parm on an entity over a specified amount of time
==================
*/
void interpolateShaderParm( entity ent, float parm, float fromValue, float toValue, float totalTime ) {
	float i;
	float value;
	float frac;
	float numTics;
	
	// convert to the total number of game tics
	numTics = totalTime * sys.getTicsPerSecond();

	for( i = 0; i < numTics; i++ ) {
		frac = i / numTics;
		value = toValue * frac + fromValue * ( 1 - frac );
		ent.setShaderParm( parm, value );
		ent.setLightParm( parm, value );
		
		// wait one game frame
		sys.waitFrame();
	}
	
	// make sure we are set to exactly the destination value
	ent.setShaderParm( parm, toValue );
	ent.setLightParm( parm, toValue );
}

/*
==================
CalcTimeForRotationAroundEntity

Calculates the time to perform a rotation of an entity around an entity it is bound to given
the angles to rotate and the desired speed.
==================
*/
float CalcTimeForRotationAroundEntity( float distanceFromCenter, float angles, float desiredSpeed ) {
	float distance;
	
	if ( desiredSpeed <= 0 ) {
		return 0;
	}
	
	distance = DEG2RAD( angles ) * distanceFromCenter;
	
	return distance / desiredSpeed;
}

/*
==================
func_clipmodel spawn function
==================
*/
void func_clipmodel() {
	// do nothing
}

/*
==================
RandomDelay
==================
*/
float RandomDelay( float min, float max ) {
	float t;
	
	t = sys.getTime();
	t += min + sys.random( max - min );
	
	return t;
}

/*
==================
RandomTime
==================
*/
float RandomTime( float delay ) {
	float t;
	
	t = sys.getTime();
	t += sys.random( delay );
	
	return t;
}

/*
==================
DelayTime
==================
*/
float DelayTime( float delay ) {
	float t;
	
	t = sys.getTime();
	t += delay;
	t += sys.random( 2 ) - 1;
	
	return t;
}

//@doomscript-blueprint begin 6
//@source 82DB519F
//@catalog 0C260740
//@node B3F0049F-0 40 40
//@node C15BE294-0 330 40
//@node B95024F3-0 40 40
//@node 306628E7-0 330 40
//@node EA085650-0 40 40
//@node 2DA60218-0 330 40
//@node 9133258A-0 40 40
//@node B36FA42F-0 330 40
//@node E1861D3C-0 40 40
//@node F6C48099-0 330 40
//@node A2644FD4-0 40 40
//@node 1AC71C1F-0 330 40
//@node 8DB3F82E-0 40 40
//@node E482C9E3-0 330 40
//@node 6941F9C6-0 610 200
//@node 2F5708F5-0 385 305
//@node B023C20F-0 890 200
//@node EDF925D5-0 1170 200
//@node 219935FF-0 965 305
//@node 9BFDC68B-0 760 305
//@node 0EDF3463-0 40 40
//@node CE900D2A-0 330 40
//@node 2AFBA871-0 125 145
//@node 6500D55B-0 610 200
//@node B868ABDF-0 890 40
//@node 02BCE3C4-0 40 40
//@node F72A612B-0 40 40
//@node DF99F99E-0 330 40
//@node BA211120-0 125 145
//@node E1C14F6B-0 610 200
//@node AB01565A-0 405 305
//@node 6CF06056-0 890 40
//@node 180C3F3F-0 685 145
//@node 4C109C95-0 1170 200
//@node 6EF727B6-0 965 305
//@node 27BB53C9-0 1450 40
//@node D6881F53-0 1245 145
//@node D3E2DEFC-0 1730 200
//@node 7A3B02CB-0 1525 305
//@node EC46C707-0 2010 40
//@node A0FB2A29-0 1805 145
//@node 16F33546-0 2290 200
//@node 03E2A121-0 2085 305
//@node 978631C8-0 2570 40
//@node 1AA754B4-0 2365 145
//@node 0E183ED1-0 2850 200
//@node 0EE15129-0 2645 305
//@node 4B6272D8-0 3130 40
//@node AC4BCC90-0 2925 145
//@node 7616A1EF-0 3410 200
//@node 7443B0A1-0 3205 305
//@node 8D19F35C-0 3690 40
//@node 163C683F-0 40 40
//@node 54158E32-0 330 40
//@node 9DD3F898-0 125 145
//@node F43CEBFB-0 610 200
//@node F49B75F9-0 405 305
//@node 7654E016-0 890 40
//@node 67C3A339-0 685 145
//@node A10716A5-0 1170 200
//@node BB0A60C2-0 965 305
//@node E664ACAB-0 1450 40
//@node 6E423460-0 1245 145
//@node 6A7D9D0C-0 1730 200
//@node B94DB4E3-0 1525 305
//@node F5759A33-0 2010 40
//@node 5C3A3F29-0 1805 145
//@node EEA97856-0 2290 200
//@node A9D30BDB-0 2085 305
//@node DD2778C0-0 2570 40
//@node 459BA6BC-0 2365 145
//@node 8ADBF4E1-0 2850 200
//@node 0034372D-0 2645 305
//@node 284408E8-0 3130 40
//@node 67547AA4-0 2925 145
//@node E63333FF-0 3410 200
//@node 323ADE01-0 3205 305
//@node 81D08730-0 3690 40
//@node 6A3DF348-0 40 40
//@node A998C79F-0 330 40
//@node 54F69E41-0 610 40
//@node F353AB48-0 40 40
//@node BE48373B-0 330 40
//@node 960EBC92-0 40 40
//@node 635B387F-0 330 40
//@node 872A1E34-0 105 145
//@node 6AFE6665-0 610 40
//@node 9030D86F-0 405 145
//@node 8462D34E-0 200 145
//@node 889E7C70-0 200 229
//@node 9CF0CB71-0 890 200
//@node B887724A-0 685 305
//@node 9819B710-0 480 305
//@node E87E750E-0 480 389
//@node 075A22DD-0 1170 200
//@node B6C121B7-0 965 305
//@node 4561A43D-0 760 305
//@node D741DFA5-0 1450 200
//@node 70A03F97-0 1730 200
//@node 3F33145E-0 2010 40
//@node 639CEE0D-0 40 40
//@node 396168E6-0 330 40
//@node C475160F-0 105 145
//@node 771FBEB8-0 610 40
//@node 12A735D9-0 405 145
//@node D784F48E-0 200 145
//@node 644400B0-0 200 229
//@node 3829AABF-0 890 200
//@node C471B2AD-0 685 305
//@node B88D9C70-0 480 305
//@node E37453AE-0 480 389
//@node C448A5A8-0 1170 200
//@node 26B38B6D-0 965 305
//@node 903C7F1D-0 760 305
//@node 344ECB1C-0 1450 200
//@node 4C0386A6-0 1730 200
//@node 00B1DD0E-0 2010 40
//@node 2E8AD4D2-0 40 40
//@node 52E06BBB-0 330 40
//@node 331CF140-0 105 145
//@node 96C23F05-0 610 40
//@node 849A8CBE-0 405 145
//@node 54B30A77-0 200 145
//@node F4A237F1-0 200 229
//@node 7A61C3A6-0 890 200
//@node 6A677C88-0 685 305
//@node 062C4513-0 480 305
//@node 72F3C4BD-0 480 389
//@node FD9125D9-0 1170 200
//@node 4843EF98-0 965 305
//@node 72F4BA9A-0 760 305
//@node 75092855-0 1450 200
//@node 67FA75C7-0 1730 200
//@node 7001D2AC-0 2010 40
//@node F9AA599B-0 40 40
//@node 4B661C24-0 330 40
//@node F1D053DD-0 105 145
//@node 09019792-0 610 40
//@node 2AF01316-0 405 145
//@node 124316C5-0 200 145
//@node 1FCFF05B-0 200 229
//@node 15C9FCE1-0 890 200
//@node ED888C98-0 685 305
//@node 7A19897D-0 480 305
//@node 1DE7D513-0 480 389
//@node B21502B4-0 1170 200
//@node C979159B-0 965 305
//@node 9AB0FA15-0 760 305
//@node 6F427DF0-0 1450 200
//@node 65F6B206-0 1245 392
//@node 19245585-0 1730 200
//@node DA52E5A4-0 1525 392
//@node EDEBD220-0 2010 200
//@node 25EA2485-0 2290 40
//@node 90A74C80-0 2570 40
//@node 8225AB1C-0 40 40
//@node 858F68CA-0 330 40
//@node EC443566-0 125 145
//@node 3AACA3EB-0 610 200
//@node 7D6B24F2-0 890 40
//@node 9B90D716-0 685 145
//@node 5CD3C8F2-0 1170 40
//@node 0EAD2483-0 40 40
//@node 5DD4BD6D-0 40 40
//@node FDAFD15D-0 330 40
//@node 939BE5E3-0 105 145
//@node 240EB130-0 610 40
//@node BD6EB2DE-0 405 145
//@node B594B874-0 200 145
//@node 35640626-0 890 40
//@node AFE3B10B-0 40 40
//@node FBCAD9E5-0 330 40
//@node B89E5295-0 105 145
//@node CD31BC09-0 610 40
//@node EED9640F-0 405 145
//@node CD6ACBC8-0 200 145
//@node FCD38764-0 890 40
//@node E22B3619-0 40 40
//@node 41F84C4D-0 330 40
//@node B99AC798-0 105 145
//@node 0555623A-0 610 40
//@node D1379F1E-0 405 145
//@node C51F989E-0 200 145
//@node 5C5F2E3E-0 890 40
//@node 342B4C1D-0 685 145
//@node 4C009519-0 480 145
//@node 74D2B24A-0 1170 40
//@doomscript-blueprint end
