namespace map_recycling1 {

        //this variable tracks which door is the entrance
        float airlock_state = 0;
        float airlock2_state = 0;

	void mover_startsound (entity ent) {
		ent.startSoundShader ("m1_start", SND_CHANNEL_VOICE);
		sys.wait (0.75);
		ent.startSoundShader ("m1_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound (entity ent) {
		ent.startSoundShader ("m1_stop", SND_CHANNEL_VOICE2);
		ent.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_ITEM );
	}

	void setup_objects ()
	{

        //set airlock door guis initial states to 1
		$airlock_door1_gui.setGuiParm ( "gui_parm1" , 1);
        $airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
        $airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);
                    
	    //airlock door1 times            
		$airlock_door1_left.time (1.2);
		$airlock_door1_right.time (1.2);
		$airlock_door1_left.accelTime (.2);
		$airlock_door1_left.decelTime (1);
		$airlock_door1_right.accelTime (.2);
		$airlock_door1_right.decelTime (1);

		$airlock_door1_top_lock.time (.25);
		$airlock_door1_bottom_lock.time (.25);
		
		$airlock_door1_left_lock.time (.75);
		$airlock_door1_right_lock.time (.75);
		$airlock_door1_left_lock.accelTime (.1);
		$airlock_door1_left_lock.decelTime (.65);
		$airlock_door1_right_lock.accelTime (.1);
		$airlock_door1_right_lock.decelTime (.65);

		//airlock door2 times
		$airlock_door2_left.time (1.2);
		$airlock_door2_right.time (1.2);
		$airlock_door2_left.accelTime (.2);
		$airlock_door2_left.decelTime (1);
		$airlock_door2_right.accelTime (.2);
		$airlock_door2_right.decelTime (1);

		$airlock_door2_top_lock.time (.25);
		$airlock_door2_bottom_lock.time (.25);
		
		$airlock_door2_left_lock.time (.75);
		$airlock_door2_right_lock.time (.75);
		$airlock_door2_left_lock.accelTime (.1);
		$airlock_door2_left_lock.decelTime (.65);
		$airlock_door2_right_lock.accelTime (.1);
		$airlock_door2_right_lock.decelTime (.65);

        //airlock2 door1 times
		$airlock2_door1_left.time (1.2);
		$airlock2_door1_right.time (1.2);
		$airlock2_door1_left.accelTime (.2);
		$airlock2_door1_left.decelTime (1);
		$airlock2_door1_right.accelTime (.2);
		$airlock2_door1_right.decelTime (1);

		$airlock2_door1_top_lock.time (.25);
		$airlock2_door1_bottom_lock.time (.25);
		
		$airlock2_door1_left_lock.time (.75);
		$airlock2_door1_right_lock.time (.75);
		$airlock2_door1_left_lock.accelTime (.1);
		$airlock2_door1_left_lock.decelTime (.65);
		$airlock2_door1_right_lock.accelTime (.1);
		$airlock2_door1_right_lock.decelTime (.65);

		//airlock2 door2 times
		$airlock2_door2_left.time (1.2);
		$airlock2_door2_right.time (1.2);
		$airlock2_door2_left.accelTime (.2);
		$airlock2_door2_left.decelTime (1);
		$airlock2_door2_right.accelTime (.2);
		$airlock2_door2_right.decelTime (1);

		$airlock2_door2_top_lock.time (.25);
		$airlock2_door2_bottom_lock.time (.25);
		
		$airlock2_door2_left_lock.time (.75);
		$airlock2_door2_right_lock.time (.75);
		$airlock2_door2_left_lock.accelTime (.1);
		$airlock2_door2_left_lock.decelTime (.65);
		$airlock2_door2_right_lock.accelTime (.1);
		$airlock2_door2_right_lock.decelTime (.65);

		//leaking pump room
		$bpipes.bind ($bpipes_anchor);
		$arm_pivot.bind ($arm_pivot_anchor);
		$arm_top.bind ($arm_top_anchor);
		$arm_bottom.bind ($arm_bottom_anchor);
		$arm_bottom_anchor.bind ($arm_top_anchor);
		$arm_top_anchor.bind ($arm_pivot_anchor);
                     
                //revenant room
                $walkway1.bind ($walkway1_anchor);
                $walkway2.bind ($walkway2_anchor);
                $walkway3.bind ($walkway3_anchor);
                    
                $walkway1_anchor.accelTime (1);
                //$walkway2_anchor.accelTime (.5);
                $walkway3_anchor.accelTime (.5);
                 
                $walkway1_anchor.time (1);
                $walkway2_anchor.time (.5);
                $walkway3_anchor.time (.8);
              
	        
	}

    ////////////////
	//misc
	////////////////


        void walkway2_fall ()
       { 
                 sys.wait (7.8);

                 $walkway1_anchor.rotateOnce ('-80 0 0');
                 sys.waitFor ($walkway1_anchor);
                                
                 $walkway3_anchor.rotateOnce ('0 0 -45');
                 sys.waitFor ($walkway3_anchor);

                 sys.wait (4.7);

               //sys.trigger ($walkway2_explosion);
         
                 $walkway2_anchor.rotateOnce ('-56 0 0');
                 sys.waitFor ($walkway2_anchor);
                                                                                
        }

	void skcube_fall ()
	{
		$skcube_mover.accelTime (.4);
                $skcube_mover.time (.5);
                $skcube_mover.rotateOnce ('0 0 90');
                sys.waitFor ($skcube_mover);

                sys.trigger ($skcube_dust);
                
                $skcube_mover.accelTime (.05);
                $skcube_mover.time (.05);
                $skcube_mover.rotateOnce ('0 0 -4');
                sys.waitFor ($skcube_mover);
                $skcube_mover.rotateOnce ('0 0 4');
                sys.waitFor ($skcube_mover);
 
                $skcube_mover.time (.05);
                $skcube_mover.rotateOnce ('0 0 -2');
                sys.waitFor ($skcube_mover);
                $skcube_mover.rotateOnce ('0 0 2');
                        
	}

        void skcube2_fall ()
	{
		$skcube2_mover.accelTime (.4);
                $skcube2_mover.time (.5);
                $skcube2_mover.rotateOnce ('0 0 90');
                sys.waitFor ($skcube2_mover);

                sys.trigger ($skcube2_dust);
                
                $skcube2_mover.accelTime (.05);
                $skcube2_mover.time (.05);
                $skcube2_mover.rotateOnce ('0 0 -4');
                sys.waitFor ($skcube2_mover);
                $skcube2_mover.rotateOnce ('0 0 4');
                sys.waitFor ($skcube2_mover);

                $skcube2_mover.time (.05);
                $skcube2_mover.rotateOnce ('0 0 -2');
                sys.waitFor ($skcube2_mover);
                $skcube2_mover.rotateOnce ('0 0 2');
                        
	}
        void skcube3_fall ()
	{
		$skcube3_mover.accelTime (.4);
        $skcube3_mover.time (.5);
        $skcube3_mover.rotateOnce ('0 0 90');
        sys.waitFor ($skcube3_mover);

        sys.trigger ($skcube3_dust);
        
        $skcube3_mover.accelTime (.05);
        $skcube3_mover.time (.05);
        $skcube3_mover.rotateOnce ('0 0 -4');
        sys.waitFor ($skcube3_mover);
        $skcube3_mover.rotateOnce ('0 0 4');
        sys.waitFor ($skcube3_mover);

        $skcube3_mover.time (.05);
        $skcube3_mover.rotateOnce ('0 0 -2');
        sys.waitFor ($skcube3_mover);
        $skcube3_mover.rotateOnce ('0 0 2');
                        
	}

        void ceilingpipe_mover1_rumble()
	{
		$ceilingpipe_mover1.time (.1);
		
		while(1){
			$ceilingpipe_mover1.rotateOnce ( '0.5 1 0' );
			sys.waitFor ($ceilingpipe_mover1);
			$ceilingpipe_mover1.rotateOnce ( '-0.5 -1 0' );
			sys.waitFor ($ceilingpipe_mover1);
					
		}
	}

        void ladder1_lower()
	{		
		$ladder1.time(2);
		sys.trigger ($speaker_ladder1);
		$ladder1.moveTo ($ladder_down);
	}

        void pipesteam1_cycle ()
        {
	while (1)
	{                        
                sys.trigger ($pipesteam1);
                sys.trigger ($pipesteam1_speaker);
                sys.wait (2);
                sys.trigger ($pipesteam1);
                sys.wait (3);                                               
	}                 
	}

	////////////////
	//break skywalk
	////////////////

	void skywalk_fall ()
	{
        sys.trigger ($recycling1_skybridge);
	}

     

	////////////////
	//big tank pump room
	////////////////

	void bigtank_pumps_on1 ()
	{
		while (1)
		{        
			$piston_left.accelTime (.4);
			$piston_left.time (1.2);
			thread mover_startsound ($piston_left);
			$piston_left.move (DOWN,128);
			$piston_left.rotateOnce ('0 20 0');
			sys.waitFor ($piston_left);
			mover_stopsound ($piston_left);
			
			sys.wait (0.5);
			
			$piston_left.time (1.6);
			thread mover_startsound ($piston_left);
			$piston_left.move (UP,128);
			$piston_left.rotateOnce ('0 -20 0');
			sys.waitFor ($piston_left);
			mover_stopsound ($piston_left);
			
			sys.wait (0.5);
			
		}
	}

	void bigtank_pumps_on2 ()
	{
		while (1)
		{ 
			$piston_right.accelTime (.4); 
			thread mover_startsound ($piston_right);
			$piston_right.time (1);
			$piston_right.move (DOWN,128);
			$piston_right.rotateOnce ('0 -20 0');
			sys.waitFor ($piston_right);
			mover_stopsound ($piston_right);
			
			sys.wait (0.5);
		   
			$piston_right.time (1.5);
			thread mover_startsound ($piston_right);
			$piston_right.move (UP,128);
			$piston_right.rotateOnce ('0 20 0');
			sys.waitFor ($piston_right);
			mover_stopsound ($piston_right);
			
			sys.wait (0.5);
		}
	}

	void bigtank_pumps_on3 ()
	{
		while (1)
			{  
				$piston_center.time (3);
				$piston_center.startSoundShader ("rec1_3s_piston", SND_CHANNEL_VOICE );
				$piston_center.move (EAST,96);
				$piston_center.rotateOnce ('0 0 360');
				sys.waitFor ($piston_center);

				$bigtank_smoke.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE );
				sys.trigger ($bigtank_smoke);
				sys.wait (2);
				$bigtank_smoke.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
				sys.trigger ($bigtank_smoke);

				$piston_center.time (3);
				$piston_center.startSoundShader ("rec1_3s_piston", SND_CHANNEL_VOICE );
				$piston_center.move (WEST,96);
				$piston_center.rotateOnce ('0 0 -360');
				sys.waitFor ($piston_center);
			        
				$piston_center.startSoundShader ("rec1_2s_rotation", SND_CHANNEL_VOICE2 );
				$piston_center.time (2);
				$piston_center.rotateOnce ('0 0 360');
				sys.waitFor ($piston_center);
			}                                    
	}

	void bigtank_pumps_off ()
	{

			sys.killthread ( "map_recycling1::bigtank_pumps_on1" );
			sys.killthread ( "map_recycling1::bigtank_pumps_on2" );
			sys.killthread ( "map_recycling1::bigtank_pumps_on3" );
	        
	}

	////////////////
	//pump1 room
	////////////////

	void pump1apiston_start ()
	{
	while (1)
	{          
            $pump1apiston.accelTime (.3);
            $pump1apiston.decelTime (.3);
			$pump1apiston.startSoundShader ("rec1_pump_movement_1_5s", SND_CHANNEL_VOICE );
			$pump1apiston.time (1);
			$pump1apiston.moveTo ($pump1aspot1);
			$pump1apiston.rotateOnce ('0 20 0');
			sys.waitFor ($pump1apiston);
			$pump1apiston.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_VOICE2 );
            
            $pump1apiston_steam.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE );
            sys.trigger ($pump1apiston_steam);

			$pump1apiston.time (.5);
			$pump1apiston.startSoundShader ("rec1_pump_movement_0_5s", SND_CHANNEL_VOICE );
			$pump1apiston.moveTo ($pump1aspot2);
			$pump1apiston.rotateOnce ('0 -20 0');
			sys.waitFor ($pump1apiston);
			$pump1apiston.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_VOICE2 );

            sys.trigger ($pump1apiston_steam);                        
	}                 
	}

	void pump1bpiston_start ()
	{
	while (1)
	{   
            $pump1bpiston.accelTime (.3);
            $pump1bpiston.decelTime (.3);     
			$pump1bpiston.startSoundShader ("rec1_pump_movement_1_5s", SND_CHANNEL_VOICE );
			$pump1bpiston.time (1.2);
			$pump1bpiston.moveTo ($pump1bspot1);
			$pump1bpiston.rotateOnce ('0 -15 0');
			$pump1bpiston.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_VOICE2 );
			sys.waitFor ($pump1bpiston);

            $pump1bpiston_steam.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE );
            sys.trigger ($pump1bpiston_steam);

			$pump1bpiston.time (.4);
			$pump1bpiston.startSoundShader ("rec1_pump_movement_0_4s", SND_CHANNEL_VOICE );
			$pump1bpiston.moveTo ($pump1bspot2);
			
			$pump1bpiston.rotateOnce ('0 15 0');
			sys.waitFor ($pump1bpiston);
			$pump1bpiston.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_VOICE2 );
			
            sys.trigger ($pump1bpiston_steam);
	}                 
	}

	///////////////////
	//leaking pump room
	///////////////////

	void bpump_on ()
	{ 
	while (1)
		{  
		        
				
				$bpipes_anchor.time (.5);       
				$bpipes_anchor.startSoundShader ("rec1_1_rotation", SND_CHANNEL_VOICE );
				$bpipes_anchor.rotateOnce ('0 0 -120');       
		       
				sys.waitFor ($bpipes_anchor);
		       
				$arm_pivot_anchor.time (1.2);
				$arm_pivot_anchor.startSoundShader ("rec1_1_2s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot2); 
				
				$arm_top_anchor.time (.3);
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.rotateOnce ('-30 0 0');
				sys.waitFor ($arm_pivot_anchor);
				
				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 -180 0');
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.time (.3);
				$arm_top_anchor.rotateOnce ('30 0 0');
				sys.waitFor ($arm_pivot_anchor);
				
				$arm_bottom_anchor.time (.8);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_8s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('90 0 0');
				sys.waitFor ($arm_bottom_anchor);
				
				sys.trigger ($pipefill);
				sys.trigger ($speaker_pipefill);
				sys.wait (3.5);
				
				sys.trigger ($pipefill);
				
				$arm_bottom_anchor.time (.4);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_4s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('-90 0 0');
				sys.waitFor ($arm_bottom_anchor);
				
				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 180 0');
				sys.waitFor ($arm_pivot_anchor);
				
				$arm_pivot_anchor.time (1.5);
				$arm_pivot_anchor.startSoundShader ("rec1_1_5s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot1);
				sys.waitFor ($arm_pivot_anchor);
		        
				sys.wait (.5);
		        
				$bpipes_anchor.time (1);       
				$bpipes_anchor.startSoundShader ("rec1_2_rotation", SND_CHANNEL_VOICE );
				$bpipes_anchor.rotateOnce ('0 0 240');
		        
				sys.waitFor ($bpipes_anchor);
		      
				$arm_pivot_anchor.time (1.2);
				$arm_pivot_anchor.startSoundShader ("rec1_1_2s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot2); 
				$arm_top_anchor.time (.3);
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.rotateOnce ('-30 0 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 -180 0');
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.time (.3);
				$arm_top_anchor.rotateOnce ('30 0 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_bottom_anchor.time (.8);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_8s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('90 0 0');
				sys.waitFor ($arm_bottom_anchor);

				sys.trigger ($speaker_pipefill);
				sys.trigger ($pipefill);

				sys.wait (3.5);

				sys.trigger ($pipefill);
				
				$arm_bottom_anchor.time (.4);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_4s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('-90 0 0');
				sys.waitFor ($arm_bottom_anchor);

				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 180 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_pivot_anchor.time (1.5);
				$arm_pivot_anchor.startSoundShader ("rec1_1_5s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot1);
				sys.waitFor ($arm_pivot_anchor);

				sys.wait (.5);

				$bpipes_anchor.time (2);       
				$bpipes_anchor.startSoundShader ("rec1_3_rotation", SND_CHANNEL_VOICE );
				$bpipes_anchor.rotateOnce ('0 0 -480');
		        
				sys.waitFor ($bpipes_anchor);

				$arm_pivot_anchor.time (1.2);
				$arm_pivot_anchor.startSoundShader ("rec1_1_2s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot2); 
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.time (.3);
				$arm_top_anchor.rotateOnce ('-30 0 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 -180 0');
				$arm_top_anchor.startSoundShader ("rec1_pivot_0_3s", SND_CHANNEL_VOICE );
				$arm_top_anchor.time (.3);
				$arm_top_anchor.rotateOnce ('30 0 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_bottom_anchor.time (.8);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_8s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('90 0 0');
				sys.waitFor ($arm_bottom_anchor);

				sys.trigger ($speaker_pipefill);
				sys.trigger ($pipefill);

				sys.wait (3.5);

				sys.trigger ($pipefill);

				$arm_bottom_anchor.time (.4);
				$arm_bottom_anchor.startSoundShader ("rec1_pivot_0_4s", SND_CHANNEL_VOICE );
				$arm_bottom_anchor.rotateOnce ('-90 0 0');
				sys.waitFor ($arm_bottom_anchor);

				$arm_pivot_anchor.time (.7);
				$arm_pivot_anchor.startSoundShader ("rec1_pivot_0_7s", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.rotateOnce ('0 180 0');
				sys.waitFor ($arm_pivot_anchor);

				$arm_pivot_anchor.time (1.5);
				$arm_pivot_anchor.startSoundShader ("rec1_1_5s_movement", SND_CHANNEL_VOICE );
				$arm_pivot_anchor.moveTo ($arm_spot1);
				sys.waitFor ($arm_pivot_anchor);
		 
				sys.wait (.5);        
		}                             
	}

	void bpump_off ()
	{
			sys.killthread ( "map_recycling1::bpump_on" );
	        sys.trigger ($func_remove_2);
	}

	////////////////////////////////////////////////////
	//
	//	Open airlock door1
	//
	////////////////////////////////////////////////////
	void airlock_door1_open()
	{
		entity ent;

        //disable the gui on door1		
		$airlock_door1_gui.setGuiParm ( "gui_parm1" , 0);

		//turn door1 light on and door2 light off
		thread crossFadeEnt ($door2_light, '.82 .76 .56', '0.4 0 0', 1);
		sys.wait(1);
		thread crossFadeEnt ($door1_light, '0.4 0 0', '.82 .76 .56', 1);

		//move the 4 locks to unlock position
		
		sys.trigger ($speaker_airlock_door1_bottom_lock);	// SOUND
		
		$airlock_door1_top_lock.move ( UP, 15 );
		$airlock_door1_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock_door1_bottom_lock);

		sys.trigger ($speaker_airlock_door1_right_lock);	// SOUND
		sys.trigger ($speaker_airlock_door1_left_lock);		// SOUND

		$airlock_door1_left_lock.move ( NORTH, -16 );
		$airlock_door1_right_lock.move ( NORTH, -16 );
		sys.waitFor ($airlock_door1_right_lock);

		//open doors
		
		sys.trigger ($speaker_airlock_door1_open);			// SOUND
		
		$airlock_door1_left.rotateOnce ( '0 45 0' );
		$airlock_door1_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		sys.trigger ($airlock_door1_portal);

		sys.waitFor ($airlock_door1_right);
		sys.waitFor ($airlock_door1_left);
				
		//set airlock state to door 1
		ent=sys.getEntity( "airlock_door1_portal" );
		ent.setKey( "state", 1 );
	}


	////////////////////////////////////////////////////
	//
	//	Open airlock door2
	//
	////////////////////////////////////////////////////
	void airlock_door2_open()
	{
		entity ent;

		//turn door2 light on and door1 light off
		thread crossFadeEnt ($door1_light, '.82 .76 .56', '0.4 0 0', 1);
		sys.wait(1);
		thread crossFadeEnt ($door2_light, '0.4 0 0', '.82 .76 .56', 1);

		//move the 4 locks to unlock position
				
		sys.trigger ($speaker_airlock_door2_bottom_lock);		// SOUND
		
		$airlock_door2_top_lock.move ( UP, 15 );
		$airlock_door2_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock_door2_bottom_lock);

		sys.trigger ($speaker_airlock_door2_right_lock);		// SOUND
		sys.trigger ($speaker_airlock_door2_left_lock);			// SOUND

		$airlock_door2_left_lock.move ( NORTH, 16 );
		$airlock_door2_right_lock.move ( NORTH, 16 );
		sys.waitFor ($airlock_door2_right_lock);

		//open doors
		
		sys.trigger ($speaker_airlock_door2_open);				// SOUND
		
		$airlock_door2_left.rotateOnce ( '0 45 0' );
		$airlock_door2_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		sys.trigger ($airlock_door2_portal);

		sys.waitFor ($airlock_door2_right);
		sys.waitFor ($airlock_door2_left);

		//set airlock state
		ent=sys.getEntity( "airlock_door1_portal" );
		ent.setKey( "state", 2 );

	}


	////////////////////////////////////////////////////
	//
	//	Close airlock door1
	//
	////////////////////////////////////////////////////
	void airlock_door1_close()
	{
		//close doors
		
		sys.trigger ($speaker_airlock_door1_close);			// SOUND
		
		$airlock_door1_left.rotateOnce ( '0 -45 0' );
		$airlock_door1_right.rotateOnce ( '0 45 0' );
		sys.waitFor ($airlock_door1_right);

		//trigger the portal
		sys.trigger ($airlock_door1_portal);

		//fire sound trigger
		sys.trigger ($airlock_speaker);

		//move the 4 locks to lock position
		sys.trigger ($speaker_airlock_door1_right_lock);	// SOUND
		sys.trigger ($speaker_airlock_door1_left_lock);		// SOUND

		$airlock_door1_left_lock.move ( NORTH, 16 );
		$airlock_door1_right_lock.move ( NORTH, 16 );
		sys.waitFor ($airlock_door1_right_lock);

		sys.trigger ($speaker_airlock_door1_bottom_lock);	// SOUND

		$airlock_door1_top_lock.move ( DOWN, 15 );
		$airlock_door1_bottom_lock.move ( UP, 15 );
		sys.waitFor ($airlock_door1_top_lock);
	}


	////////////////////////////////////////////////////
	//
	//	Close airlock door2
	//
	////////////////////////////////////////////////////
	void airlock_door2_close()
	{
		//close doors
		
		sys.trigger ($speaker_airlock_door2_close);				// SOUND
		
		$airlock_door2_left.rotateOnce ( '0 -45 0' );
		$airlock_door2_right.rotateOnce ( '0 45 0' );
		sys.waitFor ($airlock_door2_right);

		//trigger the portal
		sys.trigger ($airlock_door2_portal);

		//fire sound trigger
		sys.trigger ($airlock_speaker);

		//move the 4 locks to lock position
		sys.trigger ($speaker_airlock_door2_right_lock);	// SOUND
		sys.trigger ($speaker_airlock_door2_left_lock);		// SOUND

		$airlock_door2_left_lock.move ( NORTH, -16 );
		$airlock_door2_right_lock.move ( NORTH, -16 );
		sys.waitFor ($airlock_door2_right_lock);

		sys.trigger ($speaker_airlock_door2_bottom_lock);	// SOUND
		
		$airlock_door2_top_lock.move ( DOWN, 15 );
		$airlock_door2_bottom_lock.move ( UP, 15 );
		sys.waitFor ($airlock_door2_top_lock);

	}

	////////////////////////////////////////////////////
	//
	//	Main Activate airlock
	//	conditionally chooses based on entrance
	//
	////////////////////////////////////////////////////
	void airlock_main_activate()
	{
		entity ent;
		
		//check to see which way the player entered by checking the airlock_state
		//if 1 then close 1 and open 2

		ent=sys.getEntity ("airlock_door1_portal" );

		if (ent.getFloatKey ("state")==1) {
			airlock_door1_close();
			airlock_door2_open();
			
		} else { //else close 2 and open 1
			airlock_door2_close();
			airlock_door1_open();
		}
	}


	////////////////////////////////////////////////////
	//
	//	AIRLOCK main activation
	//	
	////////////////////////////////////////////////////
	void airlock1_activate()
	{
		//disable the guis on the doors
		$airlock_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock_innerguiholder.setGuiParm ( "gui_parm11" , 0);
	
		airlock_main_activate();

		//check the airlock state and enable the guis on the closed door
		if ($airlock_door1_portal.getFloatKey ("state")==1) {
			$airlock_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}


//////////////////////////
////////////airlock2
//////////////////////////

    ////////////////////////////////////////////////////
	//
	//	Open airlock2 door1
	//
	////////////////////////////////////////////////////
	void airlock2_door1_open()
	{
		entity ent;

        //disable the gui on door1		
		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 0);

		//turn door1 light on and door2 light off
		thread crossFadeEnt ($airlock2_door2_light, '.82 .76 .56', '0.4 0 0', 1);
		sys.wait(1);
		thread crossFadeEnt ($airlock2_door1_light, '0.4 0 0', '.82 .76 .56', 1);

		//move the 4 locks to unlock position
		sys.trigger ($speaker_airlock2_door1_bottom_lock);	// SOUND
		$airlock2_door1_top_lock.move ( UP, 15 );
		$airlock2_door1_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock2_door1_bottom_lock);

		sys.trigger ($speaker_airlock2_door1_left_lock);	// SOUND
		sys.trigger ($speaker_airlock2_door1_right_lock);	// SOUND
		$airlock2_door1_left_lock.move ( WEST, -16 );
		$airlock2_door1_right_lock.move ( WEST, -16 );
		sys.waitFor ($airlock2_door1_right_lock);

		//open doors
		
		sys.trigger ($speaker_airlock2_door1_open);
		
		$airlock2_door1_left.rotateOnce ( '0 45 0' );
		$airlock2_door1_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		sys.trigger ($airlock2_door1_portal);

		sys.waitFor ($airlock2_door1_right);
		sys.waitFor ($airlock2_door1_left);
				
		//set airlock state
		ent=sys.getEntity( "airlock2_door1_portal" );
		ent.setKey( "state", 1 );
	}


	////////////////////////////////////////////////////
	//
	//	Open airlock2 door2
	//
	////////////////////////////////////////////////////
	void airlock2_door2_open()
	{
		entity ent;

        //disable the gui on door2		
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 0);

		//turn door2 light on and door1 light off
		thread crossFadeEnt ($airlock2_door1_light, '.82 .76 .56', '0.4 0 0', 1);
		sys.wait(1);
		thread crossFadeEnt ($airlock2_door2_light, '0.4 0 0', '.82 .76 .56', 1);

		//move the 4 locks to unlock position
		
		sys.trigger ($speaker_airlock2_door2_bottom_lock);
		
		$airlock2_door2_top_lock.move ( UP, 15 );
		$airlock2_door2_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock2_door2_bottom_lock);
	
		sys.trigger ($speaker_airlock2_door2_left_lock);		// SOUND
		sys.trigger ($speaker_airlock2_door2_right_lock);		// SOUND

		$airlock2_door2_left_lock.move ( WEST, 16 );
		$airlock2_door2_right_lock.move ( WEST, 16 );
		sys.waitFor ($airlock2_door2_right_lock);

		//open doors
		
		sys.trigger ($speaker_airlock2_door2_open);
		
		$airlock2_door2_left.rotateOnce ( '0 45 0' );
		$airlock2_door2_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		sys.trigger ($airlock2_door2_portal);

		sys.waitFor ($airlock2_door2_right);
		sys.waitFor ($airlock2_door2_left);

		//set airlock state
		ent=sys.getEntity( "airlock2_door1_portal" );
		ent.setKey( "state", 2 );

	}


	////////////////////////////////////////////////////
	//
	//	Close airlock2 door1
	//
	////////////////////////////////////////////////////
	void airlock2_door1_close()
	{
		//close doors
		
		sys.trigger ($speaker_airlock2_door1_close);		// SOUND
		
		$airlock2_door1_left.rotateOnce ( '0 -45 0' );
		$airlock2_door1_right.rotateOnce ( '0 45 0' );
		sys.waitFor ($airlock2_door1_right);

		//trigger the portal
		sys.trigger ($airlock2_door1_portal);

		//fire sound trigger
		sys.trigger ($airlock2_speaker);

		sys.trigger ($speaker_airlock2_door1_left_lock);	// SOUND
		sys.trigger ($speaker_airlock2_door1_right_lock);	// SOUND

		//move the 4 locks to lock position
		$airlock2_door1_left_lock.move ( WEST, 16 );
		$airlock2_door1_right_lock.move ( WEST, 16 );
		sys.waitFor ($airlock2_door1_right_lock);

		sys.trigger ($speaker_airlock2_door1_bottom_lock);	// SOUND
		
		$airlock2_door1_top_lock.move ( DOWN, 15 );
		$airlock2_door1_bottom_lock.move ( UP, 15 );
		sys.waitFor ($airlock2_door1_top_lock);
 	}


	////////////////////////////////////////////////////
	//
	//	Close airlock2 door2
	//
	////////////////////////////////////////////////////
	void airlock2_door2_close()
	{
		//close doors
		
		sys.trigger ($speaker_airlock2_door2_close);
		
		$airlock2_door2_left.rotateOnce ( '0 -45 0' );
		$airlock2_door2_right.rotateOnce ( '0 45 0' );
		sys.waitFor ($airlock2_door2_right);

		//trigger the portal
		sys.trigger ($airlock2_door2_portal);

		//fire sound trigger
		sys.trigger ($airlock2_speaker);

		//move the 4 locks to lock position
		
		sys.trigger ($speaker_airlock2_door2_left_lock);
		sys.trigger ($speaker_airlock2_door2_right_lock);
		
		$airlock2_door2_left_lock.move ( WEST, -16 );
		$airlock2_door2_right_lock.move ( WEST, -16 );
		sys.waitFor ($airlock2_door2_right_lock);

		sys.trigger ($speaker_airlock2_door2_bottom_lock);

		$airlock2_door2_top_lock.move ( DOWN, 15 );
		$airlock2_door2_bottom_lock.move ( UP, 15 );
		sys.waitFor ($airlock2_door2_top_lock);
	}


	////////////////////////////////////////////////////
	//
	//	Main Activate airlock
	//	conditionally chooses based on entrance
	//
	////////////////////////////////////////////////////
	void airlock2_main_activate()
	{
		entity ent;
		
		//check to see which way the player entered by checking the airlock_state
		//if 1 then close 1 and open 2

		ent=sys.getEntity ("airlock2_door1_portal" );

		if (ent.getFloatKey ("state")==1) {
			airlock2_door1_close();
			airlock2_door2_open();
			
		} else { //else close 2 and open 1
			airlock2_door2_close();
			airlock2_door1_open();
		}
	}


	////////////////////////////////////////////////////
	//
	//	AIRLOCK main activation
	//	
	////////////////////////////////////////////////////
	void airlock2_activate()
	{
		//disable the guis on the doors
		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 0);
	
		airlock2_main_activate();

		//check the airlock state and enable the guis on the closed door
		if ($airlock2_door1_portal.getFloatKey ("state")==1) {
			$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}

	void cache_sounds() {
		sys.cacheSoundShader ("rec1_1_2s_movement");
		sys.cacheSoundShader ("rec1_1_5s_movement");
		sys.cacheSoundShader ("rec1_pivot_0_8s");
		sys.cacheSoundShader ("rec1_pivot_0_7s");
		sys.cacheSoundShader ("rec1_pivot_0_4s");
		sys.cacheSoundShader ("rec1_pivot_0_3s");
		sys.cacheSoundShader ("rec1_3_rotation");
		sys.cacheSoundShader ("rec1_2_rotation");
		sys.cacheSoundShader ("rec1_1_rotation");
		sys.cacheSoundShader ("rec1_pump_endclack_01");
		sys.cacheSoundShader ("rec1_pump_movement_0_4s");
		sys.cacheSoundShader ("rec1_pump_movement_1_5s");
		sys.cacheSoundShader ("rec1_2s_rotation");
		sys.cacheSoundShader ("rec1_steamchuff");
		sys.cacheSoundShader ("rec1_3s_piston");
		sys.cacheSoundShader ("m1_start");
		sys.cacheSoundShader ("m1_stop");
		sys.cacheSoundShader ("m1_loop");
	}

	void main ()
	{
		cache_sounds();
		setup_objects();
		thread map_recycling1::pump1apiston_start();
		thread map_recycling1::pump1bpiston_start();

		//setup the airlocks in the correct states
		thread map_recycling1::airlock_door2_open();
		thread map_recycling1::airlock2_door1_open();
	}
}



//James's Rev Rockets

void rev_rocketa( entity self ) {
	self.launchMissiles( "projectile_rev_rocket_cinematic", "snd_fire", "Lmissile", "target1", 1, 0 );
}

void rev_rocketb( entity self ) {
	self.launchMissiles( "projectile_rev_rocket_cinematic", "snd_fire", "Rmissile", "target2", 1, 0 );
}

//@doomscript-blueprint begin 6
//@source 073D2867
//@catalog 0C260740
//@node F466D044-0 40 40
//@node CA5263B4-0 330 40
//@node 46F65A20-0 610 40
//@node 4B63AAC8-0 890 40
//@node 3FC7A4DE-0 40 40
//@node CFDF7FE8-0 330 40
//@node 314B301A-0 610 40
//@node 7AEA71C1-0 40 40
//@node E7BD4461-0 330 40
//@node 95E8E03B-0 610 40
//@node 92C27E74-0 890 40
//@node 6ABDBC08-0 1170 40
//@node 9B056681-0 1450 40
//@node C3FF5FFD-0 1730 40
//@node 192001F7-0 2010 40
//@node E5C98CD8-0 2290 40
//@node D70B06F4-0 2570 40
//@node 0CB9A80E-0 2850 40
//@node 37CF7DFC-0 3130 40
//@node 3810188F-0 3410 40
//@node 4C5D5860-0 3690 40
//@node E061CA1E-0 3970 40
//@node 00557E55-0 4250 40
//@node 9FED8DA1-0 4530 40
//@node 50310600-0 4810 40
//@node 74931A67-0 5090 40
//@node AC128C44-0 5370 40
//@node 64E0F06E-0 5650 40
//@node DD3D8C7A-0 5930 40
//@node 660E9489-0 6210 40
//@node 8F973433-0 6490 40
//@node C9D8B1B9-0 6770 40
//@node 21D7F2B1-0 7050 40
//@node 8CEFA45A-0 7330 40
//@node D765342B-0 7610 40
//@node 8BD666D7-0 7890 40
//@node 71705B0A-0 8170 40
//@node D434DB0A-0 8450 40
//@node 92A59D59-0 8730 40
//@node A5A237EA-0 9010 40
//@node DF9DEFF3-0 9290 40
//@node 1D83A7D7-0 9570 40
//@node 8DD72689-0 9850 40
//@node 7F04E99A-0 10130 40
//@node BDB634B6-0 10410 40
//@node F41BD170-0 10690 40
//@node 5782A7B2-0 10970 40
//@node 19095D8D-0 11250 40
//@node 63DF25D6-0 11530 40
//@node E6621840-0 11810 40
//@node 454C0913-0 12090 40
//@node E6916053-0 12370 40
//@node 838F747E-0 12650 40
//@node 5E3EDE2D-0 12930 40
//@node 38215C82-0 13210 40
//@node 98934C34-0 13490 40
//@node 8265C4C0-0 13770 40
//@node 05953D9F-0 14050 40
//@node 33995691-0 14330 40
//@node 1060CCB7-0 14610 40
//@node 5C555363-0 14890 40
//@node 5DC99B7C-0 15170 40
//@node 8231D6B5-0 15450 40
//@node 8D4E699D-0 15730 40
//@node 65FA4DE4-0 16010 40
//@node C567D3F8-0 16290 40
//@node 6B19143B-0 16570 40
//@node 8EFE2780-0 16850 40
//@node 7DC6CE78-0 17130 40
//@node 13F7C356-0 17410 40
//@node 6848BE94-0 17690 40
//@node 258F4538-0 17970 40
//@node 961F2159-0 18250 40
//@node FF548960-0 18530 40
//@node A868D7C4-0 18810 40
//@node 140FD960-0 19090 40
//@node D332FDB6-0 19370 40
//@node 02465E90-0 19650 40
//@node BB8DDEEA-0 19930 40
//@node 33B35467-0 20210 40
//@node CD2DCFAB-0 20490 40
//@node BF4C3699-0 40 40
//@node E5817BF8-0 330 40
//@node 33028839-0 610 40
//@node 290BB1D1-0 890 40
//@node F43E1BD2-0 1170 40
//@node 97CF1403-0 1450 40
//@node 02B8D258-0 1730 40
//@node 7B32B2EF-0 2010 40
//@node 401B29C2-0 2290 40
//@node 1FAF36C2-0 40 40
//@node 12C45200-0 330 40
//@node 964B3601-0 610 40
//@node CE5792A6-0 890 40
//@node 33545788-0 1170 40
//@node 2AA0029F-0 1450 40
//@node 4E4E0247-0 1730 40
//@node 4C60935D-0 2010 40
//@node 2EC2A8DE-0 2290 40
//@node 33545788-1 2570 40
//@node 3F943441-0 2850 40
//@node 33545788-2 3130 40
//@node 4C60935D-1 3410 40
//@node C295A840-0 3690 40
//@node 33545788-3 3970 40
//@node 655575A7-0 4250 40
//@node 5830F8BC-0 40 40
//@node AD7C40FE-0 330 40
//@node 7D870E3B-0 610 40
//@node 9BAE46F8-0 890 40
//@node 52954B28-0 1170 40
//@node 933632C7-0 1450 40
//@node CBFBB591-0 1730 40
//@node 3AD9066B-0 2010 40
//@node EDC862A0-0 2290 40
//@node 52954B28-1 2570 40
//@node 1A49E9A7-0 2850 40
//@node 52954B28-2 3130 40
//@node 3AD9066B-1 3410 40
//@node 4E8B73BE-0 3690 40
//@node 52954B28-3 3970 40
//@node F488A841-0 4250 40
//@node 5EF3DFF9-0 40 40
//@node 769FE792-0 330 40
//@node C2183227-0 610 40
//@node 992E3E34-0 890 40
//@node 9C08D58A-0 1170 40
//@node 09547391-0 1450 40
//@node 55AF3A6D-0 1730 40
//@node 32E617BF-0 2010 40
//@node A67C66EC-0 2290 40
//@node 9C08D58A-1 2570 40
//@node 16122503-0 2850 40
//@node 9C08D58A-2 3130 40
//@node 32E617BF-1 3410 40
//@node 97045622-0 3690 40
//@node 9C08D58A-3 3970 40
//@node 3ACF3725-0 4250 40
//@node 1858F59B-0 40 40
//@node C250DC65-0 330 40
//@node 7F29B538-0 610 40
//@node 3D9B7E88-0 405 145
//@node 48BBD7E3-0 890 200
//@node B141733E-0 1170 200
//@node 229B9387-0 1450 200
//@node B141733E-1 1730 200
//@node A7589772-0 40 40
//@node E6E9A738-0 330 40
//@node 4D5767B6-0 610 40
//@node 222DD866-0 890 40
//@node 7428B0BF-0 40 40
//@node C8B9DBD0-0 330 40
//@node 490A3728-0 125 145
//@node E8A69E11-0 610 200
//@node 165267D7-0 890 200
//@node A1C4874F-0 1170 200
//@node E8A69E11-1 1450 200
//@node ACE2C5B0-0 1730 200
//@node 76AAE8F1-0 40 40
//@node BDBB5782-0 330 40
//@node B8E2BB8E-0 40 40
//@node D7091A0D-0 330 40
//@node 0091F9D1-0 125 145
//@node 1E56E7CE-0 610 200
//@node 8CA32709-0 890 200
//@node 7A0AC426-0 1170 200
//@node F3EADA83-0 1450 200
//@node 15025989-0 1730 200
//@node 611576B8-0 2010 200
//@node E556F7CE-0 2290 200
//@node 9AF51481-0 2570 200
//@node C815B685-0 2850 200
//@node 7A0AC426-1 3130 200
//@node 8F909272-0 3410 200
//@node ACD74E04-0 3690 200
//@node 611576B8-1 3970 200
//@node E556F7CE-1 4250 200
//@node 9AF51481-1 4530 200
//@node B7E2B9FB-0 40 40
//@node B7870ABC-0 330 40
//@node B0DB9530-0 125 145
//@node 2396E610-0 610 200
//@node 670705FC-0 890 200
//@node 28BDC313-0 1170 200
//@node BC6D5A0D-0 1450 200
//@node 4F4DA55A-0 1730 200
//@node BDA4391E-0 2010 200
//@node BFF90760-0 2290 200
//@node 93CE7C48-0 2570 200
//@node 97311326-0 2850 200
//@node 670705FC-1 3130 200
//@node EA051548-0 3410 200
//@node 40A6D1E3-0 3690 200
//@node BDA4391E-1 3970 200
//@node BFF90760-1 4250 200
//@node 93CE7C48-1 4530 200
//@node B6E2B868-0 40 40
//@node B4C84493-0 330 40
//@node 1C896F82-0 125 145
//@node 7E59078D-0 610 200
//@node DC7DC845-0 890 200
//@node C60276C4-0 1170 200
//@node 887766A0-0 1450 200
//@node D810ADDE-0 1730 200
//@node FDFBD160-0 2010 200
//@node 8647EF2D-0 2290 200
//@node A75366D4-0 2570 200
//@node AB9DCFCE-0 2850 200
//@node 8647EF2D-1 3130 200
//@node 7E59078D-1 3410 200
//@node DC7DC845-1 3690 200
//@node 0EF03A6A-0 3970 200
//@node 9FAD4ED3-0 4250 200
//@node D810ADDE-1 4530 200
//@node CF09BDE1-0 4810 200
//@node 0A15E02E-0 5090 200
//@node 887766A0-1 5370 200
//@node D810ADDE-2 5650 200
//@node 7BCED3CF-0 40 40
//@node 0A017B75-0 330 40
//@node A6ADC7C8-0 610 40
//@node E2C5B603-0 890 40
//@node 571C87A7-0 40 40
//@node 61A2F798-0 330 40
//@node 41FE6400-0 125 145
//@node E502B354-0 610 200
//@node 60F4E921-0 890 200
//@node B393BEF5-0 1170 200
//@node DD0CD396-0 1450 200
//@node 074E7195-0 1730 200
//@node D4354E84-0 2010 200
//@node 4BB215D3-0 2290 200
//@node 43958DEC-0 2570 200
//@node B89192F1-0 2850 200
//@node 5501E640-0 3130 200
//@node 36111E6E-0 3410 200
//@node A69142EA-0 3690 200
//@node C0C69E14-0 3970 200
//@node 1954F477-0 4250 200
//@node 4BB215D3-1 4530 200
//@node 43958DEC-1 4810 200
//@node 5501E640-1 5090 200
//@node E99C5662-0 40 40
//@node CBE9F761-0 330 40
//@node A73984DA-0 125 145
//@node D1539B84-0 610 200
//@node 59575151-0 890 200
//@node C0D8BC65-0 1170 200
//@node 04182756-0 1450 200
//@node 79B046C2-0 1730 200
//@node 82F3320F-0 2010 200
//@node 45DBB45C-0 2290 200
//@node D601BF29-0 2570 200
//@node C64F6741-0 2850 200
//@node 0C418C7A-0 3130 200
//@node DFF0F6DD-0 3410 200
//@node 063D8D0D-0 3690 200
//@node 8CC4045F-0 3970 200
//@node 921514F8-0 4250 200
//@node D601BF29-1 4530 200
//@node 45DBB45C-1 4810 200
//@node 0C418C7A-1 5090 200
//@node 47497D7D-0 40 40
//@node 599E6222-0 330 40
//@node 0342E6A2-0 125 145
//@node D6F14406-0 610 200
//@node C3DCA582-0 890 200
//@node 2610F4CA-0 1170 200
//@node 36C4A4C1-0 1450 200
//@node 0DC72F92-0 1730 200
//@node 9DC65E83-0 2010 200
//@node 55C65BE1-0 2290 200
//@node AA7709BF-0 2570 200
//@node 286C47F3-0 2850 200
//@node 62C9AEC5-0 3130 200
//@node 8ADB9D67-0 3410 200
//@node 7F93D7B8-0 3690 200
//@node 276761FA-0 3970 200
//@node F038D97C-0 4250 200
//@node 286C47F3-1 4530 200
//@node AA7709BF-1 4810 200
//@node 51BE34A8-0 5090 200
//@node 8ADB9D67-1 5370 200
//@node D2262A02-0 5650 200
//@node 5944360A-0 5930 200
//@node 1F8DB29A-0 6210 200
//@node 028D34D0-0 6490 200
//@node 563531F1-0 6770 200
//@node DA754A83-0 7050 200
//@node 32AC83B7-0 7330 200
//@node 563531F1-1 7610 200
//@node E56D8536-0 7890 200
//@node 65C3DE2E-0 8170 200
//@node BA479CF3-0 8450 200
//@node 028D34D0-1 8730 200
//@node 7F93D7B8-1 9010 200
//@node 276761FA-1 9290 200
//@node 028A7D61-0 9570 200
//@node 8ADB9D67-2 9850 200
//@node CCED90BB-0 10130 200
//@node 85F64A88-0 10410 200
//@node 0F3E8860-0 10690 200
//@node 8ADB9D67-3 10970 200
//@node AA4126B4-0 11250 200
//@node E58365EE-0 11530 200
//@node A9A9AAA3-0 11810 200
//@node B8A3348A-0 12090 200
//@node 36C4A4C1-1 12370 200
//@node 0DC72F92-1 12650 200
//@node 9DC65E83-1 12930 200
//@node 55C65BE1-1 13210 200
//@node AA7709BF-2 13490 200
//@node 286C47F3-2 13770 200
//@node 62C9AEC5-1 14050 200
//@node 8ADB9D67-4 14330 200
//@node 7F93D7B8-2 14610 200
//@node 276761FA-2 14890 200
//@node F038D97C-1 15170 200
//@node 286C47F3-3 15450 200
//@node AA7709BF-3 15730 200
//@node 51BE34A8-1 16010 200
//@node 8ADB9D67-5 16290 200
//@node D2262A02-1 16570 200
//@node 5944360A-1 16850 200
//@node 1F8DB29A-1 17130 200
//@node 028D34D0-2 17410 200
//@node DA754A83-1 17690 200
//@node 563531F1-2 17970 200
//@node 32AC83B7-1 18250 200
//@node 563531F1-3 18530 200
//@node E56D8536-1 18810 200
//@node 65C3DE2E-1 19090 200
//@node BA479CF3-1 19370 200
//@node 028D34D0-3 19650 200
//@node 7F93D7B8-3 19930 200
//@node 276761FA-3 20210 200
//@node 028A7D61-1 20490 200
//@node 8ADB9D67-6 20770 200
//@node CCED90BB-1 21050 200
//@node 85F64A88-1 21330 200
//@node 0F3E8860-1 21610 200
//@node 8ADB9D67-7 21890 200
//@node AA4126B4-1 22170 200
//@node 77D179DB-0 22450 200
//@node 6EA6BCD4-0 22730 200
//@node A086642D-0 23010 200
//@node 36C4A4C1-2 23290 200
//@node 0DC72F92-2 23570 200
//@node 9DC65E83-2 23850 200
//@node 55C65BE1-2 24130 200
//@node 286C47F3-4 24410 200
//@node AA7709BF-4 24690 200
//@node 62C9AEC5-2 24970 200
//@node 8ADB9D67-8 25250 200
//@node 7F93D7B8-4 25530 200
//@node 276761FA-4 25810 200
//@node F038D97C-2 26090 200
//@node 286C47F3-5 26370 200
//@node AA7709BF-5 26650 200
//@node 51BE34A8-2 26930 200
//@node 8ADB9D67-9 27210 200
//@node D2262A02-2 27490 200
//@node 5944360A-2 27770 200
//@node 1F8DB29A-2 28050 200
//@node 028D34D0-4 28330 200
//@node DA754A83-2 28610 200
//@node 563531F1-4 28890 200
//@node 32AC83B7-2 29170 200
//@node 563531F1-5 29450 200
//@node E56D8536-2 29730 200
//@node 65C3DE2E-2 30010 200
//@node BA479CF3-2 30290 200
//@node 028D34D0-5 30570 200
//@node 7F93D7B8-5 30850 200
//@node 276761FA-5 31130 200
//@node 028A7D61-2 31410 200
//@node 8ADB9D67-10 31690 200
//@node CCED90BB-2 31970 200
//@node 85F64A88-2 32250 200
//@node 0F3E8860-2 32530 200
//@node 8ADB9D67-11 32810 200
//@node AA4126B4-2 33090 200
//@node 239C1E39-0 40 40
//@node B7CCA642-0 330 40
//@node C40FE6A2-0 610 40
//@node DBB764A9-0 40 40
//@node 14E1A2D6-0 330 40
//@node 4F128780-0 610 40
//@node 2F746B26-0 890 40
//@node 639F003F-0 1170 40
//@node 44901E9D-0 1450 40
//@node 85F0C27E-0 1730 40
//@node 96F1A5EB-0 2010 40
//@node 0B0E14C3-0 2290 40
//@node 41EABFC6-0 2570 40
//@node 52E19AE3-0 2850 40
//@node 0668A2AC-0 3130 40
//@node 8A871FD5-0 3410 40
//@node 067D75EC-0 3690 40
//@node D8BE1FF6-0 3970 40
//@node E47AA09F-0 4250 40
//@node A17BF86B-0 4530 40
//@node DE315C76-0 4810 40
//@node C957BD5A-0 5090 40
//@node 91C4549D-0 5370 40
//@node 9D2C82F6-0 5650 40
//@node 691FCACC-0 5425 145
//@node 48DF875F-0 5930 40
//@node A6193C52-0 40 40
//@node 1667F856-0 330 40
//@node 8DD71DFF-0 610 40
//@node 86C9ACA1-0 890 40
//@node E268B663-0 1170 40
//@node F840CE86-0 1450 40
//@node 0EEA6B03-0 1730 40
//@node 23610281-0 2010 40
//@node 54DFF98C-0 2290 40
//@node 7DDA0351-0 2570 40
//@node 357E7AE5-0 2850 40
//@node B64CD0B6-0 3130 40
//@node 0BDF8E2A-0 3410 40
//@node EC92E2B4-0 3690 40
//@node 4AACF167-0 3970 40
//@node CB1EBE53-0 4250 40
//@node 24B5F8B0-0 4530 40
//@node F7F6B674-0 4810 40
//@node AB34CE87-0 5090 40
//@node B9569BC3-0 5370 40
//@node C5095162-0 5145 145
//@node BBAB636B-0 5650 40
//@node B0DB1383-0 40 40
//@node B46BADA4-0 330 40
//@node EAA535B8-0 610 40
//@node 1956E3C2-0 890 40
//@node BE67EB50-0 1170 40
//@node 7E299218-0 1450 40
//@node E97F287B-0 1730 40
//@node B7150F00-0 2010 40
//@node 6C946CBD-0 2290 40
//@node CFF78D1B-0 2570 40
//@node 17867E7C-0 2850 40
//@node 7B8230F6-0 3130 40
//@node 57371957-0 3410 40
//@node 4B39C57F-0 3690 40
//@node 3AD7FC8A-0 3970 40
//@node 7BE28FE1-0 4250 40
//@node 04423876-0 40 40
//@node 6C55CEEC-0 330 40
//@node 09A3461E-0 610 40
//@node DDF9D96C-0 890 40
//@node 8DBC01C8-0 1170 40
//@node B3802264-0 1450 40
//@node 1332E2D2-0 1730 40
//@node A6643438-0 2010 40
//@node DCC44155-0 2290 40
//@node A898AF90-0 2570 40
//@node 74FF0EE1-0 2850 40
//@node EF7B157E-0 3130 40
//@node A557C12F-0 3410 40
//@node 731650F1-0 3690 40
//@node FCBED35C-0 3970 40
//@node 45FE7A59-0 4250 40
//@node 16319330-0 40 40
//@node 18BF81F3-0 330 40
//@node F45F8418-0 105 145
//@node 79C716BB-0 610 40
//@node 79679DD9-0 405 145
//@node 2CAE6ED8-0 200 145
//@node 5DB69A4A-0 890 200
//@node A52784DB-0 1170 200
//@node 2D287FAD-0 1730 200
//@node 6F262E06-0 2010 200
//@node 3829492D-0 40 40
//@node C8C9A596-0 330 40
//@node 668CAC3B-0 610 40
//@node C394F8CC-0 890 40
//@node 2AADD54D-0 1170 40
//@node E5F14C08-0 965 145
//@node A4AC4342-0 1450 200
//@node 3E4A0175-0 2010 200
//@node 01AA3A4C-0 2290 40
//@node 9AD9FE77-0 40 40
//@node 17D7038E-0 330 40
//@node 227830B6-0 610 40
//@node F47A4874-0 890 40
//@node 2185F201-0 1170 40
//@node 4E9BCD53-0 1450 40
//@node 26BF0DD6-0 1730 40
//@node 5D8DD513-0 2010 40
//@node 58614F91-0 2290 40
//@node 41BAB421-0 2570 40
//@node CE186D5C-0 2850 40
//@node 2616B446-0 3130 40
//@node 0B1FC299-0 3410 40
//@node 8AA4F41A-0 3690 40
//@node 3FB1AD84-0 3970 40
//@node 12E27037-0 4250 40
//@node 9A41B643-0 4530 40
//@node D577F43C-0 4810 40
//@node 592ED864-0 5090 40
//@node 2C667177-0 5370 40
//@node 2BB5401E-0 5650 40
//@node 979B3CDF-0 5425 145
//@node DA9B7845-0 5930 40
//@node EBCE5B94-0 40 40
//@node 467BE64C-0 330 40
//@node 409AD31E-0 610 40
//@node 05D42849-0 890 40
//@node C7313D09-0 1170 40
//@node 9AD126BF-0 1450 40
//@node A6F15C58-0 1730 40
//@node 2DAC1AF5-0 2010 40
//@node 61C21CAD-0 2290 40
//@node 70855D85-0 2570 40
//@node 886AB328-0 2850 40
//@node FE8C13CD-0 3130 40
//@node 7ED05A3C-0 3410 40
//@node D1496276-0 3690 40
//@node 9AE05120-0 3970 40
//@node 920298DD-0 4250 40
//@node 7B987D2D-0 4530 40
//@node 5CFB1C84-0 4810 40
//@node 72D25BD0-0 5090 40
//@node 51AB400B-0 5370 40
//@node FCA42E21-0 5650 40
//@node B68AF33F-0 5425 145
//@node 9F3A6FE9-0 5930 40
//@node 1EAD0411-0 40 40
//@node 56AD8622-0 330 40
//@node A33A5878-0 610 40
//@node 487A9F02-0 890 40
//@node 9F326EDA-0 1170 40
//@node 4C204DB6-0 1450 40
//@node E6BDE919-0 1730 40
//@node AB14F03B-0 2010 40
//@node 980068DE-0 2290 40
//@node 6BF3E3F1-0 2570 40
//@node E0A18B28-0 2850 40
//@node 5DCD2A6C-0 3130 40
//@node BDA338B5-0 3410 40
//@node 13D6E6BF-0 3690 40
//@node 01F9DACA-0 3970 40
//@node 63CF5B6B-0 4250 40
//@node CCC0C308-0 40 40
//@node 16287300-0 330 40
//@node 8B295E88-0 610 40
//@node E123C0F2-0 890 40
//@node 219BC004-0 1170 40
//@node 0B3FD218-0 1450 40
//@node E9DB0BE6-0 1730 40
//@node 37BB6A69-0 2010 40
//@node ED01D684-0 2290 40
//@node 8F144BF0-0 2570 40
//@node EC2652B3-0 2850 40
//@node 07BABEFA-0 3130 40
//@node FAEA04FB-0 3410 40
//@node 6BD0414F-0 3690 40
//@node 801300DA-0 3970 40
//@node B1F83705-0 4250 40
//@node 6AF71DA2-0 40 40
//@node 792086A1-0 330 40
//@node 83601123-0 105 145
//@node 28BB2885-0 610 40
//@node C21AFF91-0 405 145
//@node AB02638A-0 200 145
//@node C5771574-0 890 200
//@node 3650ECF1-0 1170 200
//@node 5A4FFB8B-0 1730 200
//@node 9A0D9520-0 2010 200
//@node 96369CDE-0 40 40
//@node 7FB6C619-0 330 40
//@node E72509EE-0 610 40
//@node 281DBAE8-0 890 40
//@node CEB64B59-0 1170 40
//@node 914832A0-0 1450 40
//@node 2D72E2E0-0 1245 145
//@node 5B68314D-0 1730 200
//@node 9B4BDEFA-0 2290 200
//@node 9D9E16C7-0 2570 40
//@node B832CE32-0 40 40
//@node 148A962C-0 330 40
//@node FD601287-0 610 40
//@node 050F5512-0 890 40
//@node E8453D37-0 1170 40
//@node 797B3DE6-0 1450 40
//@node FD10DC8B-0 1730 40
//@node CB2D0C6D-0 2010 40
//@node 93A975C2-0 2290 40
//@node BCC82D0B-0 2570 40
//@node 1E8D027F-0 2850 40
//@node C5143F54-0 3130 40
//@node 68B2545C-0 3410 40
//@node D203E8F5-0 3690 40
//@node D96BA8A7-0 3970 40
//@node 16EBA905-0 4250 40
//@node F53CAC1E-0 4530 40
//@node 93661762-0 4810 40
//@node 72954FBC-0 5090 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 67C3ED48-0 610 40
//@node E301CD4A-0 890 40
//@node FA9B6FA5-0 1170 40
//@node E8410DDD-0 1450 40
//@node B4F9A6D4-0 1730 40
//@node BD42A57A-0 40 40
//@node 8865A6A1-0 330 40
//@node BC42A3E7-0 40 40
//@node E7090D05-0 330 40
//@doomscript-blueprint end
