namespace map_alphalabs3 {

#define CRANE_NONE		0
#define CRANE_FORWARD	1
#define CRANE_BACK		2
#define CRANE_LEFT		3
#define CRANE_RIGHT		4
#define CRANE_UP		5
#define CRANE_DOWN		6
#define CRANE_DROP		7
#define CRANE_PICKUP	8
#define CRANE_TRANSFER	9

vector	crane_mins = '2072 -56 -184';
vector	crane_maxs = '2352 296 -48';
vector	crane_pos;

float	command				= CRANE_NONE;
float	bad_object_count	= 0;			// How many bad objects have we disposed of so far ?
float	crane_have_object	= false;		// Is the crane currently holding an object ?
float	crane_light_state	= false;

entity	bindEntity;
entity	laserEntity;
entity	tracestopEntity;

/***********************************************************************

	Sounds

***********************************************************************/

void cache_crane_sounds() {
	sys.cacheSoundShader( "al3_crane_fingers_open" );
	sys.cacheSoundShader( "al3_crane_fingers_close" );
	sys.cacheSoundShader( "al3_crane_loop" );
	sys.cacheSoundShader( "al3_crane_end" );
	sys.cacheSoundShader( "al3_crane_updown_loop" );
	sys.cacheSoundShader( "al3_crane_updown_end" );
}

void sound_crane_fingers_open() {
	$crane.startSoundShader ("al3_crane_fingers_open", SND_CHANNEL_VOICE2 );
}

void sound_crane_fingers_close() {
	$crane.startSoundShader ("al3_crane_fingers_close", SND_CHANNEL_VOICE2 );
}

void sound_crane_loop() {
	$crane_carrier.startSoundShader ("al3_crane_loop", SND_CHANNEL_VOICE2 );
}

void sound_crane_stop() {
	$crane_carrier.startSoundShader ("al3_crane_end", SND_CHANNEL_VOICE2 );
}

void sound_crane_updown_loop() {
	$crane_carrier.startSoundShader ("al3_crane_updown_loop", SND_CHANNEL_VOICE2 );
}

void sound_crane_updown_end() {
	$crane_carrier.startSoundShader ("al3_crane_updown_end", SND_CHANNEL_VOICE2 );
}

/***********************************************************************

	Crane

***********************************************************************/

/*
============
update_laser

updates laser color and checks if we can pick up an object
============
*/
void update_laser() {
	vector begin = $crane_trace_start.getWorldOrigin();
	vector send = $crane_stoptrace_end.getWorldOrigin();
	vector lend = $laser_trace_end.getWorldOrigin();

	sys.trace( begin, send, '0 0 0', '0 0 0', MASK_SOLID|CONTENTS_RENDERMODEL, $crane_hang );
	tracestopEntity = sys.getTraceEntity();
	
	sys.trace( begin, lend, '0 0 0', '0 0 0', MASK_SOLID|CONTENTS_RENDERMODEL, $crane_hang );
	laserEntity = sys.getTraceEntity();
	if ( !( !laserEntity ) && ( laserEntity != $world ) ) {
		// can't move down further once the laser detects an object
		if ( !( !tracestopEntity ) && ( tracestopEntity != $world ) && ( command == CRANE_DOWN ) ) {
			command = CRANE_NONE;
		}

		if ( !crane_light_state ) {
			$crane_light.setColor( .9, .25, .25 );
			$cg_right.setGuiParm ( "gui_parm1" , 1);
			$cg_left.setGuiParm ( "gui_parm1" , 1);

			sys.trigger( $crane_speaker );
			crane_light_state = true;
		}
	
	} else if ( crane_light_state ) {
		$crane_light.setColor( .2, .8, .9 );
		$cg_right.setGuiParm ( "gui_parm1" , 0);
		$cg_left.setGuiParm ( "gui_parm1" , 0);

		sys.trigger( $crane_speaker );
		crane_light_state = false;
	}
}

/*
============
crane_move
============
*/
void crane_move( entity part, float dir, float amount, float stopOnCommand ) {
	float cmd;

	if ( amount < 0.01 ) {
		return;
	}

	if ( ( dir == UP ) || ( dir == DOWN ) ) {
		sound_crane_updown_loop();
	} else {
		sound_crane_loop();
	}
	
	part.move( dir, amount );

	if ( !stopOnCommand ) {
		sys.waitFor( part );
	} else {
		cmd = command;
		while( command == cmd ) {
			sys.waitFrame();
			update_laser();
			if ( !part.isMoving() ) {
				break;
			}
		}
		part.stopMoving();
	}

	if ( ( dir == UP ) || ( dir == DOWN ) ) {
		sound_crane_updown_end();
	} else {
		sound_crane_stop();
	}

	crane_pos = $crane_position.getWorldOrigin();
}

/*
============
crane_cmd_drop

unbind and open the claw
============
*/
void crane_cmd_drop() {
	sound_crane_fingers_open();
	
	$crane.setFingerAngle( -60 );

	bindEntity.unbind();
	bindEntity = $null_entity;
	crane_have_object = false;

	update_laser();

	$main_control_gui.setGuiParm ( "gui_parm1" , 0);
}

/*
============
crane_pickup

close the claw and bind
============
*/
void crane_cmd_pickup() {
	vector begin, end;
	string bindJoint, bindBody;

	if ( !( !bindEntity ) ) {
		return;
	}

	crane_have_object = false;
	bindJoint = bindBody = "";

	sound_crane_fingers_close();
	
	$crane.setFingerAngle( 20 );
	sys.wait( 2.0f );
	$crane.stopFingers();

	begin = $crane_trace_start.getWorldOrigin();
	end = $crane_trace_end.getWorldOrigin();

	sys.trace( begin, end, '0 0 0', '0 0 0', MASK_SOLID|CONTENTS_RENDERMODEL, $crane_hang );
	bindEntity = sys.getTraceEntity();
	if ( !( !bindEntity ) && ( bindEntity != $world ) ) {
		bindJoint = sys.getTraceJoint();

		if ( bindJoint ) {
			bindBody = sys.getTraceBody();
			if ( bindBody ) {
				bindEntity.setKey( "bindConstraint bind1", "fixed " + bindBody + " " + bindJoint );
				bindEntity.bindToJoint( $crane, "crane", 1 );
				crane_have_object = true;
			}
		} else {
			bindEntity.bindToJoint( $crane, "crane", 1 );
			crane_have_object = true;
		}
	}

	// automatically move up
	crane_move( $crane_hang, UP, crane_maxs_z - crane_pos_z, false );

	if ( !crane_have_object ) {
		sound_crane_fingers_open();
		$crane.setFingerAngle( -60 );
		bindEntity = $null_entity;
	} else {
		$main_control_gui.setGuiParm ( "gui_parm1" , 1);
	}
}

/*
============
kill_lastobject
============
*/
void kill_lastobject( entity lastobject ) {
	$main_control_gui.setGuiParm( "gui_parm1" , 1 );

	//sys.print( "kill_lastobject: " + lastobject.getName() + "\n" );

	if ( ( lastobject != $bad_object_1 ) && ( lastobject != $bad_object_2 ) ) {
		// deleting the player != smart
		if ( lastobject.getKey( "spawnclass" ) != "idPlayer" ) {
			lastobject.remove();
		}
		return;
	}

	lastobject.remove();
	bad_object_count++;

	if ( bad_object_count == 1 ) {

		thread crossFadeEnt ($puke_light, '0 0.52 0.07', '0 0.26 0.035', 5.0);
		sys.wait (5);
		sys.trigger ($cranewarning_2);
	
	} else if ( bad_object_count == 2 ) {

		sys.trigger ($crane_fog);
		thread crossFadeEnt ($puke_light, '0 0.26 0.035', '0 0 0', 5.0);
		sys.wait (5);
		sys.trigger ($cranewarning_3);

		// Get rid of the trigger_once for the computer voice, if they
		// haven't triggered it yet.
		$toxin_trigger.remove();
		
		sys.trigger ($disposal_door);
		sys.trigger ($disposal_setshaderparm);
		sys.trigger ($cgdoors_setshaderparm);
		sys.trigger ($clear_colorchange);

		$disposal_outer_gui.setGuiParm( "gui_parm1", 1 );
		$disposal_inner_gui.setGuiParm( "gui_parm1", 1 );

		$dd_light1.setColor (0.0, 0.5, 0.0);
		$dd_light2.setColor (0.0, 0.5, 0.0);

		$dd_green_dec.show ();
		$dd_red_dec.hide ();

		sys.trigger ($trigger_relay_262);
		sys.wait (5);
		sys.trigger ($alpha3_sarge1);
		sys.wait (7);
		sys.trigger ($trigger_relay_264);
	}
}

/*
============
crane_cmd_transfer

move crane to the drop off point
only if it has an object bound 
drop the bound object

eventually this will send the object to the new area
============
*/
void crane_cmd_transfer() {
	float move_x, move_y, move_z;
	float xdir, ydir, zdir;
	float xrdir, yrdir, zrdir;
	vector drop_point;

	if ( !crane_have_object ) {
		return;
	}

	$crane_carrier.speed( 40 );
	$crane_top.speed( 40 );

	//
	// How are we going to get to the receptible ?
	//
	drop_point = $crane_drop.getWorldOrigin();

	// Calculate X movement
	if ( crane_pos_x >= drop_point_x ) {
		move_x = crane_pos_x - drop_point_x;
		xdir = WEST;
		xrdir = EAST;
	} else {
		move_x = drop_point_x - crane_pos_x;
		xdir = EAST;
		xrdir = WEST;
	}

	// Calculate Y movement
	if ( crane_pos_y >= drop_point_y ) {
		move_y = crane_pos_y - drop_point_y;
		ydir = SOUTH;
		yrdir = NORTH;
	} else {
		move_y = drop_point_y - crane_pos_y; 
		ydir = NORTH;
		yrdir = SOUTH;
	}

	sound_crane_loop();
	$crane_carrier.move( ydir, move_y );
	sys.waitFor( $crane_carrier );
	sound_crane_stop();
	
	sound_crane_loop();
	$crane_top.move( xdir, move_x );
	sys.waitFor( $crane_top );
	sound_crane_stop();

	sys.wait( 1 );
	crane_cmd_drop();

	sys.wait( 0.5 );

	sound_crane_loop();
	$crane_top.move( xrdir, move_x );
	sys.waitFor( $crane_top );
	sound_crane_stop();

	sound_crane_loop();
	$crane_carrier.move( yrdir, move_y );
	sys.waitFor( $crane_carrier );
	sound_crane_stop();

	$crane_top.speed( 30 );
	$crane_carrier.speed( 30 );
}

/*
============
crane_update_loop
============
*/
void crane_update_loop() {
	while( 1 ) {
		command = CRANE_NONE;
		while( command == CRANE_NONE ) {
			update_laser();
			sys.waitFrame();
		}

		if ( command == CRANE_FORWARD ) {
			if ( crane_pos_x > crane_mins_x ) {
				crane_move( $crane_top, WEST, crane_pos_x - crane_mins_x, true );
			}

		} else if ( command == CRANE_BACK ) {
			if ( crane_pos_x < crane_maxs_x ) {
				crane_move( $crane_top, EAST, crane_maxs_x - crane_pos_x, true );
			}

		} else if ( command == CRANE_LEFT ) {
			if ( crane_pos_y > crane_mins_y ) {
				crane_move( $crane_carrier, SOUTH, crane_pos_y - crane_mins_y, true );
			}

		} else if ( command == CRANE_RIGHT ) {
			if ( crane_pos_y < crane_maxs_y ) {
				crane_move( $crane_carrier, NORTH, crane_maxs_y - crane_pos_y, true );
			}
		} else if ( command == CRANE_UP ) {
			if ( crane_pos_z < crane_maxs_y ) {
				crane_move( $crane_hang, UP, crane_maxs_z - crane_pos_z, true );
			}

		} else if ( command == CRANE_DOWN ) {
			if ( ( crane_pos_z > crane_mins_z ) && !bindEntity && ( !tracestopEntity || ( tracestopEntity == $world ) ) ) {
				crane_move( $crane_hang, DOWN, crane_pos_z - crane_mins_z, true );
			}
		} else if ( command == CRANE_DROP ) {
			crane_cmd_drop();

		} else if ( command == CRANE_PICKUP ) {
			crane_cmd_pickup();

		} else if ( command == CRANE_TRANSFER ) {
			crane_cmd_transfer();
		}
	}
}

/***********************************************************************

	User interface

***********************************************************************/

void crane_forward() {
	command = CRANE_FORWARD;
}

void crane_back() {
	command = CRANE_BACK;
}

void crane_left() {
	command = CRANE_LEFT;
}

void crane_right() {
	command = CRANE_RIGHT;
}

void crane_up() {
	command = CRANE_UP;
}

void crane_down() {
	command = CRANE_DOWN;
}

void crane_stop() {
	command = CRANE_NONE;
}

void crane_drop() {
	command = CRANE_DROP;
}

void crane_pickup() {
	command = CRANE_PICKUP;
}

void crane_transfer() {
	command = CRANE_TRANSFER;
}

/***********************************************************************

	initialization

***********************************************************************/

/*
============
init_crane
============
*/
void init_crane() {
	cache_crane_sounds();

	crane_pos = $crane_position.getWorldOrigin();

	$crane_light.bindToJoint( $crane, "crane", 1 );

	// crane_position
	$crane_trace_start.bindToJoint( $crane, "crane", 1 );
	$crane_trace_end.bindToJoint( $crane, "crane", 1 );
	$crane_stoptrace_end.bindToJoint( $crane, "crane", 1 );
	$laser_trace_end.bindToJoint( $crane, "crane", 1 );

	$crane_carrier.speed( 30 );
	$crane_top.speed( 30 );
	$crane_hang.speed( 45 );
	$crane_top.bind( $crane_carrier );
	$crane_hang.bind( $crane_top );

	$crane.bind( $crane_hang );
	$crane.setFingerAngle( -60 );

	thread crane_update_loop();
}

/* namespace map_alphalabs3 */ }

//@doomscript-blueprint begin 6
//@source DA330BEA
//@catalog 0C260740
//@node 499FF318-0 40 40
//@node E291DEFB-0 330 40
//@node 49263145-0 610 40
//@node 2ADCB872-0 890 40
//@node BF708849-0 1170 40
//@node 0C620D3C-0 1450 40
//@node AA57481B-0 1730 40
//@node FE49D9E8-0 40 40
//@node B8B83FB1-0 330 40
//@node 9E3BF204-0 40 40
//@node 350B21FB-0 330 40
//@node 6ED6D92D-0 40 40
//@node 8B891BF4-0 330 40
//@node 89B7BEDF-0 40 40
//@node F07D7201-0 330 40
//@node 2DB0B605-0 40 40
//@node 7EF18E02-0 330 40
//@node 9D9722FC-0 40 40
//@node FB3F23CE-0 330 40
//@node 1A656FE8-0 40 40
//@node 472228BF-0 1170 40
//@node 43197DBA-0 125 140
//@node 8C9FEAE6-0 125 232
//@node 55EC2F01-0 610 40
//@node 81FE5CA9-0 385 145
//@node 8059AEC2-0 1730 40
//@node 488BA390-0 685 140
//@node 8A51DDF3-0 685 232
//@node 9387156B-0 1170 40
//@node 3CDB5D5F-0 945 145
//@node C55487FA-0 1450 40
//@node 5FB1A8C6-0 1245 145
//@node 5B9C5FEB-0 1040 145
//@node A6333DAA-0 1730 200
//@node 5ECE10DD-0 1525 305
//@node D151C863-0 1320 305
//@node BDE02000-0 1320 389
//@node 9EB3ECE2-0 2010 360
//@node F00E3CA9-0 1805 465
//@node 96E6644D-0 2290 200
//@node 0C729484-0 2085 305
//@node 0CE7A644-0 1880 305
//@node B2B633C2-0 3410 360
//@node A7A3169C-0 3690 360
//@node 549FA67B-0 3970 360
//@node 02B264DA-0 4250 360
//@node 50C6AD63-0 3690 360
//@node B99A4CBC-0 3485 465
//@node 80A9DC0D-0 3970 200
//@node 6820DEE1-0 3765 305
//@node A6B84EF6-0 5090 200
//@node 0D23594B-0 5370 200
//@node EFBD348C-0 5650 200
//@node 02B264DA-1 5930 200
//@node A06A52F2-0 5370 200
//@node BDAC606A-0 5165 305
//@node AD80179A-0 40 40
//@node C9C4E9DD-0 330 40
//@node 5944F62F-0 125 145
//@node F3E896F1-0 610 200
//@node 7AF957B1-0 890 40
//@node DA363BEA-0 685 145
//@node B8C1A776-0 1170 200
//@node 1A6388EC-0 1730 200
//@node 6177F665-0 2010 40
//@node 8A905CE1-0 2290 40
//@node 3101AEBE-0 2085 145
//@node A2AB1D82-0 2570 200
//@node B4EA34C6-0 3130 200
//@node 5543F0FF-0 2925 305
//@node FC8B7831-0 3410 200
//@node 8216A182-0 3205 305
//@node 8E253482-0 3000 305
//@node BE4FD03B-0 3000 389
//@node 7D8E92DB-0 3690 360
//@node DD3FA29F-0 3970 360
//@node 77013073-0 4250 360
//@node D97209FC-0 3810 465
//@node 4F3860AC-0 4040 465
//@node C3E80BAD-0 3970 520
//@node C6B36E51-0 4810 200
//@node 7AF957B1-1 5090 40
//@node 5C638837-0 4885 145
//@node 3EF31ADB-0 5370 200
//@node 13ADB7DE-0 5930 200
//@node 4EE8C201-0 6210 40
//@node B4CF9560-0 5985 145
//@node BFB7CE07-0 40 40
//@node B8C36902-0 330 40
//@node C54BCAE7-0 610 40
//@node 1180D1B5-0 890 40
//@node 5BC91C2F-0 1170 40
//@node F899820D-0 965 145
//@node BC9223DD-0 1450 40
//@node 282F8B17-0 1245 145
//@node 9D97B99E-0 1730 40
//@node C0A8289A-0 2010 40
//@node 815CFF16-0 40 40
//@node 7F46F28B-0 330 40
//@node 792446DF-0 125 145
//@node F960E8D7-0 -80 145
//@node C6A482B5-0 1170 200
//@node 42572E3A-0 890 40
//@node 9AE4089C-0 685 145
//@node 756D289E-0 1170 40
//@node FD1C8149-0 965 145
//@node E434ADD1-0 760 145
//@node 34DEB3F9-0 2010 40
//@node 6C87040D-0 2290 40
//@node 03FDEFDE-0 2570 40
//@node 90A62117-0 2850 40
//@node 412B6433-0 2570 40
//@node 6CC0DF45-0 2345 145
//@node AA54A91A-0 2850 40
//@node 5ACF331D-0 2625 145
//@node 6CC255D2-0 3690 40
//@node 6EE3D55D-0 2925 140
//@node D6FA2EF6-0 2925 232
//@node 1AEB18D7-0 3410 40
//@node 4EE0FACB-0 3185 145
//@node 8C384C46-0 3690 40
//@node 5016BFA2-0 3485 145
//@node 9F3E7DB7-0 3280 145
//@node 2115FCCF-0 3970 200
//@node B24CF154-0 3745 305
//@node 0B1A30A5-0 4250 200
//@node 80216B5C-0 4045 305
//@node 74D56845-0 4530 360
//@node AD02D9C4-0 4305 465
//@node 966E6BED-0 4810 360
//@node 65DF14CE-0 4605 465
//@node DA690552-0 5650 520
//@node 76F16DDB-0 4885 712
//@node 7CE27E62-0 4680 712
//@node A6831B2A-0 4680 790
//@node 50952F59-0 5930 520
//@node 0D29ACAB-0 5650 520
//@node 4E5488EA-0 5445 625
//@node 50952F59-1 6770 360
//@node 0D29ACAB-1 6490 360
//@node 521A05DB-0 6285 465
//@node 74A80C01-0 7330 40
//@node 8D0BDC99-0 7050 40
//@node AC5B6E9D-0 6845 145
//@node 525B8BE7-0 6640 145
//@node A48CE3FF-0 7890 200
//@node B6569DDE-0 8170 200
//@node 4CC89308-0 7890 200
//@node 24570A2F-0 7685 305
//@node AB6FD2E2-0 9010 200
//@node 24D1EB6D-0 40 40
//@node 6C343C93-0 330 40
//@node 770FAC56-0 610 40
//@node 17E43D2C-0 405 145
//@node 28387487-0 890 200
//@node A3EA0423-0 685 305
//@node C386D13C-0 1170 360
//@node 1963367A-0 1450 200
//@node C386D13C-1 1730 40
//@node F418A720-0 2010 40
//@node CB23B570-0 1805 145
//@node 5F903AF9-0 1600 145
//@node 59C54C49-0 2290 40
//@node AD735A3A-0 2085 145
//@node B7612A7A-0 1880 145
//@node 6D85B40B-0 2570 200
//@node AAE7D158-0 2850 200
//@node 944B9FB6-0 3130 200
//@node 0DD872B1-0 3410 200
//@node 06D5325F-0 3205 305
//@node 178BA0F6-0 3000 305
//@node 18B18116-0 3690 200
//@node BEDE022B-0 3970 200
//@node AAE7D158-1 4250 200
//@node 088EC715-0 4530 200
//@node 12B74654-0 4810 200
//@node 8E4AA0D0-0 5090 200
//@node 2BE30C5F-0 5370 200
//@node B318C59B-0 5650 200
//@node 44D35005-0 5930 200
//@node FC8E0757-0 6210 200
//@node 1C207518-0 6490 200
//@node ED5DEC9F-0 6770 200
//@node 65B2DBAE-0 7050 200
//@node 1376B98F-0 7330 200
//@node F7B5274E-0 7610 200
//@node CF684B97-0 7890 200
//@node AAE7D158-2 8170 200
//@node 23B4950B-0 8450 200
//@node 0C173B1A-0 8730 200
//@node 5CD09ED5-0 9010 200
//@node 86BA5199-0 40 40
//@node 401007D6-0 330 40
//@node 3E8B0727-0 125 145
//@node 7E0CCEA1-0 -80 145
//@node FC8EDDA6-0 1450 200
//@node 84939A42-0 1730 40
//@node DB0796E3-0 2010 40
//@node 5E2011F4-0 1450 40
//@node 36A369EF-0 1225 145
//@node 6048DD7A-0 1730 40
//@node 89001F7B-0 1525 145
//@node 4AF11061-0 2010 200
//@node D1A53BAB-0 1805 305
//@node 347B2904-0 2290 200
//@node 1601A16C-0 2085 305
//@node 1D9E1820-0 2570 200
//@node 2FEB33AB-0 2365 305
//@node FC99C9FD-0 3130 200
//@node 50D72C1C-0 2925 305
//@node FA20D082-0 3410 200
//@node 4A53E00C-0 3205 305
//@node 59E90066-0 3690 200
//@node 59FF65A5-0 3485 305
//@node 00524FA2-0 3970 40
//@node 65BA8C27-0 3765 145
//@node 3F8D67B8-0 4250 200
//@node 67176177-0 4045 305
//@node 54126D25-0 4530 200
//@node 0103F7FA-0 4325 305
//@node 49A11773-0 4810 200
//@node D8C13C2A-0 4605 305
//@node D621ECFE-0 5370 200
//@node E57B69C7-0 5165 305
//@node 835D9FA3-0 5650 200
//@node 6FE05A6A-0 5445 305
//@node 36783A55-0 5930 200
//@node 48879937-0 5725 305
//@node C681453F-0 7050 40
//@node 274B075F-0 7330 40
//@node 51739ED2-0 6285 140
//@node A0B4559C-0 6285 232
//@node E76FF19A-0 7610 40
//@node E2483B39-0 7890 40
//@node C681453F-1 8170 40
//@node ED218E3E-0 8450 40
//@node 51AAD02F-0 7405 140
//@node 9E5C1F07-0 7405 232
//@node 67C49E43-0 8730 40
//@node E2483B39-1 9010 40
//@node 7CE10B9C-0 9290 40
//@node E70DC9A1-0 9570 40
//@node 8ECF27FA-0 9850 40
//@node C681453F-2 10130 40
//@node 4E467C96-0 10410 40
//@node EC31F902-0 9365 140
//@node A67C0BCA-0 9365 232
//@node 67C49E43-1 10690 40
//@node E2483B39-2 10970 40
//@node C681453F-3 11250 40
//@node 83124247-0 11530 40
//@node D4CD96B4-0 10485 140
//@node D142A456-0 10485 232
//@node E76FF19A-1 11810 40
//@node E2483B39-3 12090 40
//@node 2F8EA312-0 12370 40
//@node F65EF1D3-0 12650 40
//@node D761CD7D-0 40 40
//@node 434EF13C-0 330 40
//@node 531885B5-0 125 145
//@node 04988F09-0 610 200
//@node 91127A5A-0 405 305
//@node 51F54574-0 890 200
//@node 518A7EAA-0 685 305
//@node 0B157381-0 480 305
//@node DCF1A654-0 1170 360
//@node D1EFCECE-0 1450 360
//@node 5C8098CF-0 1730 200
//@node C0427054-0 1525 305
//@node E9A6014A-0 1320 305
//@node A870816E-0 2010 360
//@node 23679A75-0 1805 465
//@node C82D6F5C-0 2290 520
//@node 4988A9AE-0 2570 360
//@node 5F34591F-0 2365 465
//@node E15619CD-0 2160 465
//@node 34928E22-0 2850 360
//@node 4BA93C4C-0 2645 465
//@node B1DBC268-0 3130 520
//@node D9DD3BDC-0 3410 360
//@node 5F002949-0 3205 465
//@node 7A3955E5-0 3000 465
//@node 318560F4-0 3690 360
//@node B1FCD38E-0 3485 465
//@node 07D0C0A9-0 3970 520
//@node 38C497EB-0 4250 360
//@node 0496955E-0 4045 465
//@node 85A17AB5-0 3840 465
//@node 86DFD968-0 4530 360
//@node 7A467128-0 4325 465
//@node 03C7DFFF-0 4810 520
//@node C464DF8C-0 5090 360
//@node 6A9E0D80-0 4885 465
//@node 418FCCD8-0 4680 465
//@node F5FEF85B-0 5370 360
//@node EB8E5807-0 5165 465
//@node 8CF18E81-0 5650 520
//@node 4377C285-0 5930 360
//@node 72BA995E-0 5725 465
//@node 1785AA9B-0 5520 465
//@node 4AEFDA01-0 6210 360
//@node 0BD57222-0 6005 465
//@node 5BF8903D-0 5800 465
//@node 831D77C5-0 5800 549
//@node 117315CC-0 6490 520
//@node D2852F14-0 6770 360
//@node 9A5EFA5A-0 6565 465
//@node 43E5A17E-0 6360 465
//@node DF687C41-0 7050 360
//@node 45C82281-0 7330 360
//@node 0958046C-0 7125 465
//@node 7B8A4C89-0 6920 465
//@node AB4BAEFA-0 7610 360
//@node 633FEC06-0 7890 360
//@node AC3B5E28-0 7685 465
//@node A02E9EDA-0 7480 465
//@node 8A7940BB-0 8170 360
//@node 02E1D138-0 40 40
//@node 0E6663FB-0 330 40
//@node BD604B62-0 125 145
//@node AE51839C-0 40 40
//@node D41C12A9-0 330 40
//@node 5FC14B11-0 125 145
//@node 1ED1516A-0 40 40
//@node 65279A49-0 330 40
//@node 3632F36B-0 125 145
//@node 3BF02637-0 40 40
//@node C2741703-0 330 40
//@node F2AF0353-0 125 145
//@node 5E40E7C6-0 40 40
//@node F8589AA9-0 330 40
//@node 65A70B5B-0 125 145
//@node CEEECA4F-0 40 40
//@node CF90CC0B-0 330 40
//@node E2D8260A-0 125 145
//@node A293A09B-0 40 40
//@node 8BE17611-0 330 40
//@node 4191FE95-0 125 145
//@node B521F34A-0 40 40
//@node F1B7DD15-0 330 40
//@node 383A1B3E-0 125 145
//@node 946FD4BB-0 40 40
//@node 095970F3-0 330 40
//@node 4C51CC05-0 125 145
//@node 12F47278-0 40 40
//@node A4456565-0 330 40
//@node C98F7424-0 125 145
//@node D296D311-0 40 40
//@node 71D60824-0 330 40
//@node 22393B6E-0 610 40
//@node F2726683-0 385 145
//@node 8D15EE3C-0 890 40
//@node F579DB32-0 1170 40
//@node 2D4EABA5-0 1450 40
//@node D7216515-0 1730 40
//@node EF329F2F-0 2010 40
//@node 84379643-0 2290 40
//@node 8C031AA2-0 2570 40
//@node 07E1F899-0 2850 40
//@node A0B8BEB1-0 3130 40
//@node 754F5695-0 3410 40
//@node 6A9FBC67-0 3690 40
//@node 12693CB9-0 3970 40
//@node 10B949ED-0 4250 40
//@doomscript-blueprint end
