namespace map_alphalabs4 {
	
	// Start Globals
	
	// Alphapuzzle
	float g_fConveyDoorRefCount	= 0.0;
	float g_fWeldDoorRefCount	= 0.0;

	// End Globals

	///////////////////////////////////////////////
	//	blinky eyes
	///////////////////////////////////////////////

	void cache_sounds() {
		sys.cacheSoundShader ("al4_openslats_2s");
		sys.cacheSoundShader ("al4_support_05s");
		sys.cacheSoundShader ("small_mover_impact");
		sys.cacheSoundShader ("al4_plat_movement");
		sys.cacheSoundShader ("al4_slide_3s");
		sys.cacheSoundShader ("jacob");
		sys.cacheSoundShader ("al4_plat_start");
		sys.cacheSoundShader ("al4_plat_loop");
		sys.cacheSoundShader ("al4_plat_stop");
	}

	void eKillSound (entity ent, float eTime) {
		sys.wait (eTime);
		ent.stopSound( SND_CHANNEL_ANY, false );
	}

	void end_vagscene() {
		$speaker_vagfight.fadeSound (SND_CHANNEL_ANY, -60, 5);			// Fade out after the fight
	}
	
	void start_vagscene() {
		sys.wait (22.5);
		sys.trigger ($speaker_vagfight);
	
	}

	///////////////////////////////////////////////
	//	blinky eyes
	///////////////////////////////////////////////

	void eyesbegone()
	{
		$eyes1.time(.5);
		$eyes1.accelTime(0.1);
		$eyes1.decelTime(0.1);
		$eyes1.move(DOWN, 32);
		sys.waitFor($eyes1);
		sys.trigger($eye1_light);
	}

	void bind_objects() {

		$frontroom_door2.bind($frontroom_door1);
		$frontroom_door3.bind($frontroom_door2);
		$frontroom_door4.bind($frontroom_door3);

		$ambush_door_2.bind($ambush_door_1);
		$ambush_door_3.bind($ambush_door_2);
		$ambush_door_4.bind($ambush_door_3);

		$scissor_door_2.bind($scissor_door_1);
		$scissor_door_3.bind($scissor_door_2);
		$scissor_door_4.bind($scissor_door_3);

		$back_scissor_door_2.bind($back_scissor_door_1);
		$back_scissor_door_3.bind($back_scissor_door_2);
		$back_scissor_door_4.bind($back_scissor_door_3);
		
		}

	void frontroom_door_open()
	{

		$frontroom_door1.startSoundShader ("al4_openslats_2s", SND_CHANNEL_VOICE );
		$frontroom_door1.time(2);
		$frontroom_door1.accelTime(.5);
		$frontroom_door1.decelTime(.5);
		$frontroom_door1.rotateOnce('-90 0 0');
		$frontroom_door2.time(2);
		$frontroom_door2.accelTime(.5);
		$frontroom_door2.decelTime(.5);
		$frontroom_door2.rotateOnce('180 0 0');
		$frontroom_door3.time(2);
		$frontroom_door3.accelTime(.5);
		$frontroom_door3.decelTime(.5);
		$frontroom_door3.rotateOnce('-180 0 0');
		$frontroom_door4.time(2);
		$frontroom_door4.accelTime(.5);
		$frontroom_door4.decelTime(.5);
		$frontroom_door4.rotateOnce('180 0 0');
	}
		
	void ambush_door_open()
	{

		$ambush_door_1.startSoundShader ("al4_openslats_2s", SND_CHANNEL_VOICE );
		$ambush_door_1.time(2);
		$ambush_door_1.accelTime(.5);
		$ambush_door_1.decelTime(.5);
		$ambush_door_1.rotateOnce('0 0 -90');
		$ambush_door_2.time(2);
		$ambush_door_2.accelTime(.5);
		$ambush_door_2.decelTime(.5);
		$ambush_door_2.rotateOnce('0 0 180');
		$ambush_door_3.time(2);
		$ambush_door_3.accelTime(.5);
		$ambush_door_3.decelTime(.5);
		$ambush_door_3.rotateOnce('0 0 -180');
		$ambush_door_4.time(2);
		$ambush_door_4.accelTime(.5);
		$ambush_door_4.decelTime(.5);
		$ambush_door_4.rotateOnce('0 0 180');
	}
	
	void scissor_door_open()
	{
		$scissor_door_1.startSoundShader ("al4_openslats_2s", SND_CHANNEL_VOICE );
		$scissor_door_1.time(2);
		$scissor_door_1.accelTime(.5);
		$scissor_door_1.decelTime(.5);
		$scissor_door_1.rotateOnce('0 0 90');
		$scissor_door_2.time(2);
		$scissor_door_2.accelTime(.5);
		$scissor_door_2.decelTime(.5);
		$scissor_door_2.rotateOnce('0 0 -180');
		$scissor_door_3.time(2);
		$scissor_door_3.accelTime(.5);
		$scissor_door_3.decelTime(.5);
		$scissor_door_3.rotateOnce('0 0 180');
		$scissor_door_4.time(2);
		$scissor_door_4.accelTime(.5);
		$scissor_door_4.decelTime(.5);
		$scissor_door_4.rotateOnce('0 0 -180');
	}

	void back_scissor_door1_open()
	{

		$back_scissor_door_1.startSoundShader ("al4_openslats_2s", SND_CHANNEL_VOICE );
		$back_scissor_door_1.time(2);
		$back_scissor_door_1.accelTime(.5);
		$back_scissor_door_1.decelTime(.5);
		$back_scissor_door_1.rotateOnce('-90 0 0');
		$back_scissor_door_2.time(2);
		$back_scissor_door_2.accelTime(.5);
		$back_scissor_door_2.decelTime(.5);
		$back_scissor_door_2.rotateOnce('180 0 0');
		$back_scissor_door_3.time(2);
		$back_scissor_door_3.accelTime(.5);
		$back_scissor_door_3.decelTime(.5);
		$back_scissor_door_3.rotateOnce('-180 0 0');
		$back_scissor_door_4.time(2);
		$back_scissor_door_4.accelTime(.5);
		$back_scissor_door_4.decelTime(.5);
		$back_scissor_door_4.rotateOnce('180 0 0');
	}
	/*

	A l p h a p u z z l e    c o d e    s t a r t s   h e r e 

	*/


	void ExtendPlatform1()
	{
		$jump_platform1.time(3);
		sys.trigger ($speaker_jump_platform);
		$jump_platform1.move( NORTH, 232 );
		sys.waitFor( $jump_platform1 );
	}


	void SetupRotatingBridge()
	{
		$rotating_bridge.bind( $rotating_bridge_joint );

		$bridge_right_bottom_joint.bind( $rotating_bridge );
		$bridge_left_bottom_joint.bind( $rotating_bridge );

//		$rotating_bridge_railing_right.bind( $rotating_bridge );
//		$rotating_bridge_railing_left.bind( $rotating_bridge );

		$bridge_right_top_hydro_machine.bind( $rotating_bridge_spinner );
		$bridge_left_top_hydro_machine.bind( $rotating_bridge_spinner );

		$bridge_right_top_hydro.bind( $bridge_right_top_hydro_machine );
		$bridge_left_top_hydro.bind( $bridge_left_top_hydro_machine );

		$bridge_right_bottom_hydro.bind( $bridge_right_top_hydro );
		$bridge_left_bottom_hydro.bind( $bridge_left_top_hydro );

		$rotating_bridge.time( 0.1 );
		$rotating_bridge.rotateOnce( '-60 0 0' );
		sys.waitFor( $rotating_bridge );

		$bridge_right_top_hydro.time( 0.1 );
		$bridge_left_top_hydro.time( 0.1 );
		$bridge_right_top_hydro.rotateOnce( '-30 0 0' );
		$bridge_left_top_hydro.rotateOnce( '-30 0 0' );
		sys.waitFor( $bridge_left_top_hydro );

		$bridge_right_bottom_hydro.time( 0.1 );
		$bridge_left_bottom_hydro.time( 0.1 );
		$bridge_right_bottom_hydro.move( REL_UP, 272 );
		$bridge_left_bottom_hydro.move( REL_UP, 272 );
		sys.waitFor( $bridge_left_bottom_hydro );

		$bridge_right_bottom_joint.time( 0.1 );
		$bridge_left_bottom_joint.time( 0.1 );
		$bridge_right_bottom_joint.move( REL_FORWARD, 16 );
		$bridge_left_bottom_joint.move( REL_FORWARD, 16 );
		sys.waitFor( $bridge_left_bottom_hydro );
	}


	void RotatingBridgeStart()
	{
		$bridge_right_bottom_hydro.time( 5.0 );
		$bridge_left_bottom_hydro.time( 5.0 );
		$bridge_right_bottom_joint.time( 5.0 );
		$bridge_left_bottom_joint.time( 5.0 );
		$rotating_bridge.time( 5.0 );
		$bridge_right_bottom_hydro.move( REL_DOWN, 272 );
		$bridge_left_bottom_hydro.move( REL_DOWN, 272 );
		$bridge_right_bottom_joint.move( REL_BACK, 16 );
		$bridge_left_bottom_joint.move( REL_BACK, 16 );
		sys.trigger ($speaker_rotating_bridge);
		$rotating_bridge.rotateOnce( '60 0 0' );
		sys.waitFor( $rotating_bridge );
	}


	void RotatingBridgeLoop()
	{
		while( true )
		{
			$rotating_bridge_spinner.accelTime( 1.0 );
			$rotating_bridge_spinner.time( 5.0 );
			$rotating_bridge_spinner.decelTime( 1.0 );
			$rotating_bridge_joint.accelTime( 1.0 );
			$rotating_bridge_joint.time( 5.0 );
			$rotating_bridge_joint.decelTime( 1.0 );
			sys.trigger ($speaker_rotating_bridge);
			$rotating_bridge_spinner.rotateOnce( '0 90 0' );
			sys.trigger ($speaker_rotbridge_tech);
			$rotating_bridge_joint.rotateOnce( '0 90 0' );
			sys.waitFor( $rotating_bridge_joint );

			sys.wait( 2.0 );
		}
	}


	void SectionBridgeGuardSequence( entity eLeftGuard, entity eRightGuard, float nOrient )
	{
		if( nOrient == NORTH )
		{
			eLeftGuard.time( 0.5 );
			eLeftGuard.decelTime( 0.25 );

			eRightGuard.time( 0.5 );
			eRightGuard.decelTime( 0.25 );

			eLeftGuard.startSoundShader ("al4_support_05s", SND_CHANNEL_ANY);
			
			eLeftGuard.rotateOnce( '-90 0 0' );
			eRightGuard.rotateOnce( '90 0 0' );
			sys.wait( 0.5 );
			return;
		}

		if( nOrient == SOUTH )
		{
			eLeftGuard.time( 0.5 );
			eLeftGuard.decelTime( 0.25 );

			eRightGuard.time( 0.5 );
			eRightGuard.decelTime( 0.25 );

			eLeftGuard.startSoundShader ("al4_support_05s", SND_CHANNEL_ANY);
			eLeftGuard.rotateOnce( '-90 0 0' );
			eRightGuard.rotateOnce( '90 0 0' );
			sys.wait( 0.5 );
			return;
		}

		if( nOrient == EAST )
		{
			eLeftGuard.time( 0.5 );
			eLeftGuard.decelTime( 0.25 );

			eRightGuard.time( 0.5 );
			eRightGuard.decelTime( 0.25 );

			eLeftGuard.startSoundShader ("al4_support_05s", SND_CHANNEL_ANY);
			eLeftGuard.rotateOnce( '0 0 -90' );
			eRightGuard.rotateOnce( '0 0 90' );
			sys.wait( 0.5 );
			return;
		}

		if( nOrient == WEST )
		{
			eLeftGuard.time( 0.5 );
			eLeftGuard.decelTime( 0.25 );

			eRightGuard.time( 0.5 );
			eRightGuard.decelTime( 0.25 );

			eLeftGuard.startSoundShader ("al4_support_05s", SND_CHANNEL_ANY);
			eLeftGuard.rotateOnce( '0 0 90' );
			eRightGuard.rotateOnce( '0 0 -90' );
			sys.wait( 0.5 );
			return;
		}
	}

	void stop_platsound (entity ent, float fTime) {
		sys.wait (fTime);
		ent.startSoundShader ("small_mover_impact", SND_CHANNEL_ANY);
	}

	void SectionBridgePartsSequence( string strBaseName, float nOrient, float nCount )
	{
		string strTemp;

		entity	eSection;
		entity	eLight;
		entity	eLeftGuard;
		entity	eRightGuard;
		float	fTime;
		string	sTemp;

		float ii;

		for( ii = nCount ; ii > 0; ii-- )
		{
			strTemp = strBaseName + "_part" + ii;
			eSection = sys.getEntity( strTemp );
			sTemp = strTemp;

			//strTemp = strBaseName + "_guard_left" + ii;
			//eLeftGuard = sys.getEntity( strTemp );

			//strTemp = strBaseName + "_guard_right" + ii;
			//eRightGuard = sys.getEntity( strTemp );

			//eLeftGuard.bind( eSection );
			//eRightGuard.bind( eSection );

			eSection.accelTime( 0.25 );
			fTime = ( 1.0 + ((ii - 1) / 2) );
			eSection.time( fTime );
			eSection.decelTime( 0.25 );

			
			
//	void eKillSound (entity ent, float eTime) {			

// This sounds crappy. Killing the mover sound is enough...
//			thread stop_platsound (eSection, fTime);
			
			eSection.move( nOrient, (128 + ((ii - 1) * 64) ) );
			thread eKillSound (eSection, fTime);
			eSection.startSoundShader ("al4_plat_movement", SND_CHANNEL_ANY);
			sys.wait( 0.9 );

			//thread SectionBridgeGuardSequence( eLeftGuard, eRightGuard, nOrient);

			strTemp = strBaseName + "_light" + ii + "_left";
			eLight = sys.getEntity( strTemp );

			if( eLight )
			{
				eLight.On();
			}

			strTemp = strBaseName + "_light" + ii + "_right";
			eLight = sys.getEntity( strTemp );

			if( eLight )
			{
				eLight.On();
			}
		}
	}

	void SectionBridgeRailsSequence( string strBaseName, float nDirection, float nCount )
	{
		string strRightRail;
		string strLeftRail;

		entity eRightRail;
		entity eLeftRail;

		strRightRail = strBaseName + "_rail_right";
		eRightRail = sys.getEntity( strRightRail );

		strLeftRail = strBaseName + "_rail_left";
		eLeftRail = sys.getEntity( strLeftRail );

		eRightRail.time( 3.0 );
		eRightRail.accelTime( 0.5 );
		eRightRail.decelTime( 0.5 );
		eLeftRail.time( 3.0 );
		eLeftRail.accelTime( 0.5 );
		eLeftRail.decelTime( 0.5 );
		
		eRightRail.move( nDirection, ((nCount + 1) * 64) );
		
		eRightRail.startSoundShader ("al4_slide_3s", SND_CHANNEL_ANY);
		
		eLeftRail.move( nDirection, ((nCount + 1) * 64) );
		sys.waitFor( eLeftRail );
	}


	void ExtendSectionBridges()
	{
		SectionBridgeRailsSequence( "sectionbridge1", WEST, 6 );
		SectionBridgePartsSequence( "sectionbridge1", WEST, 6 );
		sys.trigger($bridge1_aas_block);

		SectionBridgeRailsSequence( "sectionbridge2", NORTH, 6 );
		SectionBridgePartsSequence( "sectionbridge2", NORTH, 6 );
		sys.trigger($bridge2_aas_block);

		SectionBridgeRailsSequence( "sectionbridge3", SOUTH, 6 );
		SectionBridgePartsSequence( "sectionbridge3", SOUTH, 6 );
		sys.trigger($bridge3_aas_block);

		SectionBridgeRailsSequence( "sectionbridge4", SOUTH, 8 );
		SectionBridgePartsSequence( "sectionbridge4", SOUTH, 8 );
		sys.trigger($bridge4_aas_block);

		SectionBridgeRailsSequence( "sectionbridge5", SOUTH, 8 );
		SectionBridgePartsSequence( "sectionbridge5", SOUTH, 8 );
		sys.trigger($bridge5_aas_block);

		SectionBridgeRailsSequence( "sectionbridge6", SOUTH, 6 );
		SectionBridgePartsSequence( "sectionbridge6", SOUTH, 6 );
		sys.trigger($bridge6_aas_block);
	}


	void SectionBridgeRemoveOne( float nBridge )
	{
		string strRemove;
		entity eRemove;
		float ii;

		strRemove = "sectionbridge" + nBridge + "_rail_right";
		eRemove = sys.getEntity( strRemove );
		eRemove.remove();

		strRemove = "sectionbridge" + nBridge + "_rail_left";
		eRemove = sys.getEntity( strRemove );
		eRemove.remove();

		for( ii = 1; ii > 0; ii++ )
		{
			strRemove = "sectionbridge" + nBridge + "_part" + ii;
			eRemove = sys.getEntity( strRemove );

			if( !eRemove )
				break;

			eRemove.remove();

			//strRemove = "sectionbridge" + nBridge + "_guard_right" + ii;
			//eRemove = sys.getEntity( strRemove );
			//eRemove.remove();

			//strRemove = "sectionbridge" + nBridge + "_guard_left" + ii;
			//eRemove = sys.getEntity( strRemove );
			//eRemove.remove();
		}
	}


	void SectionBridgeRemoveAll()
	{
		float ii;

		for( ii = 1; ii <= 6; ii++ )
		{
			SectionBridgeRemoveOne( ii );
		}
	}


	void SetupRideOfDeathObjects()
	{
		entity eParent;
		entity eChild;

		float ii;

		for( ii = 1; ii < 7; ii++ )
		{
			eParent = sys.getEntity( "ride_of_death" + ii + "_parent" );
			eChild = sys.getEntity( "ride_of_death" + ii );
			eChild.bind( eParent );

			eParent = eChild;
			eChild = sys.getEntity( "ride_of_death" + ii + "_front_support" );
			eChild.bind( eParent );

			eChild = sys.getEntity( "ride_of_death" + ii + "_rear_support" );
			eChild.bind( eParent );

			eChild.time( 0.1 );
			eChild.move( SOUTH, 64 );
			sys.waitFor( eChild );

			eChild = sys.getEntity( "ride_of_death" + ii + "_light1" );
			eChild.bind( eParent );
			eChild.Off();

			eChild = sys.getEntity( "ride_of_death" + ii + "_light2" );
			eChild.bind( eParent );
			eChild.Off();
		}
	}

	void ROD_startSound (entity ent) {
		ent.startSoundShader ("al4_plat_start", SND_CHANNEL_VOICE);
		sys.wait (0.55);
		ent.startSoundShader ("al4_plat_loop", SND_CHANNEL_VOICE2);
	}
	
	void ROD_stopSound (entity ent) {
		ent.startSoundShader ("al4_plat_stop", SND_CHANNEL_VOICE2);
	}

	void ROD_stopSound_time (entity ent, float fTime) {
		sys.wait (fTime);
		ent.startSoundShader ("al4_plat_stop", SND_CHANNEL_VOICE2);
	}

	
	void RideOfDeathPath( string strRideName )
	{
		entity eRide;
		entity eRideBase;
		entity eFrontSupport;
		entity eRearSupport;
		entity eLight1;
		entity eLight2;

		eRide = sys.getEntity( strRideName + "_parent" );
		eRideBase = sys.getEntity (strRideName);

		eFrontSupport = sys.getEntity( strRideName + "_front_support" );
		eRearSupport = sys.getEntity( strRideName + "_rear_support" );
		eLight1 = sys.getEntity( strRideName + "_light1" );
		eLight2 = sys.getEntity( strRideName + "_light2" );

		eLight1.fadeInLight( 2.0 );
		eLight2.fadeInLight( 2.0 );

		// west 2112
		thread ROD_startSound (eRideBase);
		eRide.time( 33.0 ); // 64u/sec
		eRide.accelTime( 0.0 );
		eRide.decelTime( 0.5 );
		eRide.move( WEST, 2112 );

		sys.waitFor( eRide );

		eRearSupport.time( 1.0 );
		eRearSupport.move( NORTH, 64 );
				
		sys.waitFor( eRearSupport );
		
		ROD_stopSound (eRideBase);
		
		sys.wait( 1.0 );

		eFrontSupport.time( 1.0 );
		eFrontSupport.move( NORTH, 64 );
		sys.waitFor( eFrontSupport );

		thread ROD_startSound (eRideBase);

		// west 64
		eRide.time( 1.0 ); // 64u/sec
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.0 );
		eRide.move( WEST, 64 );
		sys.waitFor( eRide );

		// turn C 90deg
		eRide.time( 4.0 ); // 22.5deg/sec
		eRide.accelTime( 0.0 );
		eRide.decelTime( 0.0 );
		eRide.rotateOnce( '0 -90 0' );
		sys.waitFor( eRide );

	// 41s

		// north 64
		eRide.time( 1.0 );
		eRide.accelTime( 0.0 );
		eRide.decelTime( 0.5 );
		eRide.move( NORTH, 64 );
		
		sys.waitFor( eRide );
		
		ROD_stopSound (eRideBase);

		eFrontSupport.time( 1.0 );
		eFrontSupport.move( EAST, 64 );

		sys.waitFor( eFrontSupport );
		sys.wait( 1.0 );

		eRearSupport.time( 1.0 );
		eRearSupport.move( EAST, 64 );

		sys.waitFor( eRearSupport );

		thread ROD_startSound (eRideBase);

		// north 352
		eRide.time( 5.5 );
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.5 );
		eRide.move( NORTH, 352 );

		sys.waitFor( eRide );

		// down 320
		eRide.time( 5.0 );
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.5 );
		eRide.move( DOWN, 320 );

		sys.waitFor( eRide );

		// north 480
		eRide.time( 7.5 );
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.0 );
		eRide.move( NORTH, 480 );

		sys.waitFor( eRide );

	// 22s

		// bind to origin 1
		eRide.bind( $ride_of_death_origin1 );

		// turn CC 90deg
		$ride_of_death_origin1.time( 4.0 );
		$ride_of_death_origin1.accelTime( 0.0 );
		$ride_of_death_origin1.decelTime( 0.0 );
		$ride_of_death_origin1.rotateOnce( '0 90 0' );
		
		sys.waitFor( $ride_of_death_origin1 );

		// unbind from origin 1
		eRide.unbind();
		$ride_of_death_origin1.restorePosition();

		// 896
		eRide.time( 14.0 );
		eRide.accelTime( 0.0 );
		eRide.decelTime( 0.0 );
		eRide.move( WEST, 896 );

		sys.waitFor( eRide );

		// bind to origin 2
		eRide.bind( $ride_of_death_origin2 );

		// turn CC 90deg
		$ride_of_death_origin2.time( 4.0 );
		$ride_of_death_origin2.accelTime( 0.0 );
		$ride_of_death_origin2.decelTime( 0.0 );
		$ride_of_death_origin2.rotateOnce( '0 90 0' );

		sys.waitFor( $ride_of_death_origin2 );

		// unbind from origin 2
		eRide.unbind();
				
		$ride_of_death_origin2.restorePosition();

	// 22s

		// south 480
		eRide.time( 7.5 );
		eRide.accelTime( 0.0 );
		eRide.decelTime( 0.5 );
		eRide.move( SOUTH, 480 );

		sys.waitFor( eRide );

		// up 320
		eRide.time( 5.0 );
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.5 );
		eRide.move( UP, 320 );

		sys.waitFor( eRide );

		// south 1182
		thread ROD_stopSound_time (eRideBase, 17);
		eRide.time( 18.5 );
		eRide.accelTime( 0.5 );
		eRide.decelTime( 0.0 );
		eRide.move( SOUTH, 1182 );
		
		sys.waitFor( eRide );
		//ROD_stopSound (eRideBase);
		eRide.restorePosition();

	// 31s
	}
	// 116s


	void RideOfDeathLoop()
	{
		while( true )
		{
			thread RideOfDeathPath( "ride_of_death1" );
			sys.wait( 20.0 );

			thread RideOfDeathPath( "ride_of_death2" );
			sys.wait( 20.0 );

			thread RideOfDeathPath( "ride_of_death3" );
			sys.wait( 20.0 );

			thread RideOfDeathPath( "ride_of_death4" );
			sys.wait( 20.0 );

			thread RideOfDeathPath( "ride_of_death5" );
			sys.wait( 20.0 );

			thread RideOfDeathPath( "ride_of_death6" );
			sys.wait( 20.0 );
		}
	}


	void RemoveRideOfDeathObjects()
	{
		entity eObject;
		float ii;

		for( ii = 1; ii < 7; ii++ )
		{
			eObject = sys.getEntity( "ride_of_death" + ii + "_parent" );
			eObject.remove();

			eObject = sys.getEntity( "ride_of_death" + ii );
			eObject.remove();

			eObject = sys.getEntity( "ride_of_death" + ii + "_front_support" );
			eObject.remove();

			eObject = sys.getEntity( "ride_of_death" + ii + "_rear_support" );
			eObject.remove();

			eObject = sys.getEntity( "ride_of_death" + ii + "_light1" );
			eObject.remove();

			eObject = sys.getEntity( "ride_of_death" + ii + "_light2" );
			eObject.remove();
		}
	}


	void SetupWeldingMachine( string strBaseName )
	{
		// the cover object is not bound in this function
		entity eParent;
		entity eChild;

		eParent = sys.getEntity( strBaseName + "_support" );
		eChild = sys.getEntity( strBaseName + "_right_grip" );
		eChild.bind( eParent );

		eChild = sys.getEntity( strBaseName + "_left_grip" );
		eChild.bind( eParent );

		eChild = sys.getEntity( strBaseName + "_base" );
		eChild.bind( eParent );

		eParent = eChild;
		eChild = sys.getEntity( strBaseName + "_arm" );
		eChild.bind( eParent );

		eParent = eChild;
		eChild = sys.getEntity( strBaseName + "_light" );
		eChild.bind( eParent );
		eChild.Off();

		eChild = sys.getEntity( strBaseName + "_arm" );
		eChild.time( 0.1 );
		eChild.rotateOnce( '135 0 0' );
		sys.waitFor( eChild );
	}


	void SetupRideOfDeathTrap1()
	{
		SetupWeldingMachine( "weld1_front" );
		SetupWeldingMachine( "weld1_rear" );
		SetupWeldingMachine( "weld2_front" );
		SetupWeldingMachine( "weld2_rear" );

		$weld1_rear_support.time( 0.1 );
		$weld2_rear_support.time( 0.1 );
		$weld1_rear_support.rotateOnce( '0 180 0' );
		$weld2_rear_support.rotateOnce( '0 180 0' );
		sys.waitFor( $weld2_rear_support );
	}


	void WeldingMachineSequence( string strBaseName, string strConveyName )
	{
		entity eSupport;
		entity eSupport_speaker;
		entity eSupport_05s_speaker;
		
		entity eCover;
		entity eLeftGrip;
		entity eRightGrip;
		
		entity eBase;
		entity eBase_speaker;
		
		entity eArm;
		entity eArm_speaker;
		entity eArm_weld_speaker;
		
		entity eLight;
		entity eSpark;

		eSupport = sys.getEntity( strBaseName + "_support" );
		eSupport_speaker = sys.getEntity( strBaseName + "_support_speaker" );
		eSupport_05s_speaker = sys.getEntity( strBaseName + "_support_05s_speaker" );
		eCover = sys.getEntity( strBaseName + "_cover" );
		
		eLeftGrip = sys.getEntity( strBaseName + "_left_grip" );
		
		eRightGrip = sys.getEntity( strBaseName + "_right_grip" );
		
		eBase = sys.getEntity( strBaseName + "_base" );
		
		eArm = sys.getEntity( strBaseName + "_arm" );
		eArm_weld_speaker = sys.getEntity ( strBaseName + "_arm_speaker" );
		eArm_speaker = sys.getEntity ( strBaseName + "_arm_rot_speaker" );
		
		eLight = sys.getEntity( strBaseName + "_light" );
		eSpark = sys.getEntity( strBaseName + "_sparks" );

		eCover.bind( eSupport );

		eSupport.time( 2.0 );
		eSupport.accelTime( 0.25 );
		eSupport.decelTime( 0.25 );
		sys.trigger (eSupport_speaker);
		eSupport.move( DOWN, 192 );
		sys.waitFor( eSupport );

		eSupport.time( 0.5 );
		eSupport.accelTime( 0.0 );
		eSupport.decelTime( 0.0 );
		sys.trigger (eSupport_05s_speaker);
		eSupport.move( REL_BACK, 12 );
		sys.waitFor( eSupport );

		eBase.time( 1.0 );
		eArm.time( 1.0 );
		eBase.move( UP, 48 );
		sys.trigger (eArm_speaker);
		eArm.rotateOnce( '-135 0 0' );
		sys.waitFor( eArm );

		// turn on sparks
		eLight.On();
		sys.trigger (eSpark);
		

		eBase.time( 2.0 );
		sys.trigger ( eArm_weld_speaker );
		eBase.move( DOWN, 48 );
		sys.waitFor( eBase );

		// turn off sparks
		eLight.Off();
		sys.trigger (eSpark);

		eCover.unbind();
		eCover.bind( sys.getEntity( strConveyName ) );

		eArm.time( 1.0 );
		sys.trigger (eArm_speaker);
		eArm.rotateOnce( '135 0 0' );
		sys.waitFor( eArm );

		eLeftGrip.time( 0.25 );
		eRightGrip.time( 0.25 );
		eLeftGrip.rotateOnce( '0 15 0' );
		eRightGrip.rotateOnce( '0 -15 0' );
		sys.waitFor( eRightGrip );

		eSupport.time( 1.0 );
		eSupport.accelTime( 0.0 );
		eSupport.decelTime( 0.0 );
		sys.trigger (eSupport_05s_speaker);
		eSupport.move( REL_FORWARD, 12 );
		sys.waitFor( eSupport );

		eSupport.time( 2.0 );
		eSupport.accelTime( 0.25 );
		eSupport.decelTime( 0.25 );
		sys.trigger (eSupport_speaker);
		eSupport.move( UP, 192 );
		sys.waitFor( eSupport );

		eLeftGrip.time( 0.25 );
		eRightGrip.time( 0.25 );
		eLeftGrip.rotateOnce( '0 -15 0' );
		eRightGrip.rotateOnce( '0 15 0' );
		sys.waitFor( eRightGrip );
	}
	// 10s TOTAL


	void ConveyDoorsOpen()
	{
		if( g_fConveyDoorRefCount < 1 )
		{
			$convey_left_door.open();
			$convey_right_door.open();
		}

		g_fConveyDoorRefCount++;
	}


	void ConveyDoorsClose()
	{
		g_fConveyDoorRefCount--;

		if( g_fConveyDoorRefCount < 1 )
		{
			$convey_left_door.close();
			$convey_right_door.close();
		}
	}


	void WeldDoorsOpen()
	{
		if( g_fWeldDoorRefCount < 1 )
		{
			$weld_left_door.open();
			$weld_right_door.open();
		}

		g_fWeldDoorRefCount++;
	}


	void WeldDoorsClose()
	{
		g_fWeldDoorRefCount--;

		if( g_fWeldDoorRefCount < 1 )
		{
			$weld_left_door.close();
			$weld_right_door.close();
		}
	}


	void Convey1ShortPathSequence()
	{
		thread ConveyDoorsOpen();

		$convey1_base.time( 2.0 );
		$convey1_base.accelTime( 0.25 );
		$convey1_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_1_2s);
		$convey1_base.move( SOUTH, 520 );
		sys.waitFor( $convey1_base );

		thread ConveyDoorsClose();
		thread WeldDoorsOpen();

		thread WeldingMachineSequence( "weld1_front", "convey1_base" );
		thread WeldingMachineSequence( "weld1_rear", "convey1_base" );
		sys.wait( 11.0 );

		thread WeldDoorsClose();
		thread ConveyDoorsOpen();

		$convey1_base.time( 2.0 );
		$convey1_base.accelTime( 0.25 );
		$convey1_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_1_2s);
		$convey1_base.move( NORTH, 520 );
		sys.waitFor( $convey1_base );

		thread ConveyDoorsClose();
	}
	// 15s


	void Convey1LongPathSequence()
	{
		thread ConveyDoorsOpen();

		$convey1_base.time( 2.5 );
		$convey1_base.accelTime( 0.25 );
		$convey1_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_1_2p5s);
		$convey1_base.move( SOUTH, 632 );
		sys.waitFor( $convey1_base );

		thread ConveyDoorsClose();
		thread WeldDoorsOpen();

		thread WeldingMachineSequence( "weld1_front", "convey1_base" );
		thread WeldingMachineSequence( "weld1_rear", "convey1_base" );
		sys.wait( 11.0 );

		thread WeldDoorsClose();
		thread ConveyDoorsOpen();

		$convey1_base.time( 2.5 );
		$convey1_base.accelTime( 0.25 );
		$convey1_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_1_2p5s);
		$convey1_base.move( NORTH, 632 );
		sys.waitFor( $convey1_base );

		thread ConveyDoorsClose();
	}
	// 16s


	void Convey2ShortPathSequence()
	{
		thread ConveyDoorsOpen();

		$convey2_base.time( 2.0 );
		$convey2_base.accelTime( 0.25 );
		$convey2_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_2_2s);
		$convey2_base.move( SOUTH, 520 );
		sys.waitFor( $convey2_base );

		thread ConveyDoorsClose();
		thread WeldDoorsOpen();

		thread WeldingMachineSequence( "weld2_front", "convey2_base" );
		thread WeldingMachineSequence( "weld2_rear", "convey2_base" );
		sys.wait( 11.0 );

		thread WeldDoorsClose();
		thread ConveyDoorsOpen();

		$convey2_base.time( 1.5 );
		$convey2_base.accelTime( 0.25 );
		sys.trigger ($speaker_convey_2_1p5s);
		$convey2_base.move( NORTH, 520 );
		sys.waitFor( $convey2_base );

		thread ConveyDoorsClose();
	}
	// 15s


	void Convey2LongPathSequence()
	{
		thread ConveyDoorsOpen();

		$convey2_base.time( 2.5 );
		$convey2_base.accelTime( 0.25 );
		$convey2_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_2_2p5s);
		$convey2_base.move( SOUTH, 632 );
		sys.waitFor( $convey2_base );

		thread ConveyDoorsClose();
		thread WeldDoorsOpen();

		thread WeldingMachineSequence( "weld2_front", "convey2_base" );
		thread WeldingMachineSequence( "weld2_rear", "convey2_base" );
		sys.wait( 11.0 );

		thread WeldDoorsClose();
		thread ConveyDoorsOpen();

		$convey2_base.time( 2.5 );
		$convey2_base.accelTime( 0.25 );
		$convey2_base.decelTime( 0.25 );
		sys.trigger ($speaker_convey_2_2p5s);
		$convey2_base.move( NORTH, 632 );
		sys.waitFor( $convey2_base );

		thread ConveyDoorsClose();
	}
	// 16s


	void RideOfDeathTrap1Loop()
	{
		float fTemp;

		sys.wait( 4.0 );

		while( true )
		{
			$weld1_front_cover.unbind();
			$weld1_rear_cover.unbind();
			$weld2_front_cover.unbind();
			$weld2_rear_cover.unbind();
			$weld1_front_cover.restorePosition();
			$weld1_rear_cover.restorePosition();
			$weld2_front_cover.restorePosition();
			$weld2_rear_cover.restorePosition();

			fTemp = sys.random( 3.0 );

			if( fTemp < 1 )
			{
				// 1 goes long, 2 goes short
				$weld1_front_support.time( 0.1 );
				$weld1_front_cover.time( 0.1 );
				$weld1_rear_support.time( 0.1 );
				$weld1_rear_cover.time( 0.1 );
				$weld2_front_support.time( 0.1 );
				$weld2_front_cover.time( 0.1 );
				$weld2_rear_support.time( 0.1 );
				$weld2_rear_cover.time( 0.1 );
				$weld1_front_support.moveTo( $weld1_front_long_origin );
				$weld1_front_cover.moveTo( $weld1_front_long_origin );
				$weld1_rear_support.moveTo( $weld1_rear_long_origin );
				$weld1_rear_cover.moveTo( $weld1_rear_long_origin );
				$weld2_front_support.moveTo( $weld2_front_short_origin );
				$weld2_front_cover.moveTo( $weld2_front_short_origin );
				$weld2_rear_support.moveTo( $weld2_rear_short_origin );
				$weld2_rear_cover.moveTo( $weld2_rear_short_origin );
				sys.waitFor( $weld2_rear_cover );

				fTemp = sys.random( 3.0 );
				if( fTemp < 1 )
				{
					// early/early
					thread Convey1LongPathSequence();
					thread Convey2ShortPathSequence();
					sys.wait( 30.0 );
				}
				else if( fTemp < 2 )
				{
					// late/early
					sys.wait( 2.0 );

					thread Convey2ShortPathSequence();
					sys.wait( 8.0 );

					thread Convey1LongPathSequence();
					sys.wait( 20.0 );
				}
				else
				{
					// early/late
					sys.wait( 10.0 );

					thread Convey1LongPathSequence();
					sys.wait( 2.0 );

					thread Convey2ShortPathSequence();
					sys.wait( 18.0 );
				}
			}
			else if( fTemp < 2 )
			{
				// 1 goes short, 2 goes long
				$weld1_front_support.time( 0.1 );
				$weld1_front_cover.time( 0.1 );
				$weld1_rear_support.time( 0.1 );
				$weld1_rear_cover.time( 0.1 );
				$weld2_front_support.time( 0.1 );
				$weld2_front_cover.time( 0.1 );
				$weld2_rear_support.time( 0.1 );
				$weld2_rear_cover.time( 0.1 );
				$weld1_front_support.moveTo( $weld1_front_short_origin );
				$weld1_front_cover.moveTo( $weld1_front_short_origin );
				$weld1_rear_support.moveTo( $weld1_rear_short_origin );
				$weld1_rear_cover.moveTo( $weld1_rear_short_origin );
				$weld2_front_support.moveTo( $weld2_front_long_origin );
				$weld2_front_cover.moveTo( $weld2_front_long_origin );
				$weld2_rear_support.moveTo( $weld2_rear_long_origin );
				$weld2_rear_cover.moveTo( $weld2_rear_long_origin );
				sys.waitFor( $weld2_rear_cover );

				fTemp = sys.random( 3.0 );
				if( fTemp < 1 )
				{
					// early/early
					thread Convey1ShortPathSequence();
					thread Convey2LongPathSequence();
					sys.wait( 30.0 );
				}
				else if( fTemp < 2 )
				{
					// late/early
					sys.wait( 2.0 );

					thread Convey2LongPathSequence();
					sys.wait( 8.0 );

					thread Convey1ShortPathSequence();
					sys.wait( 20.0 );
				}
				else
				{
					// early/late
					sys.wait( 10.0 );

					thread Convey1ShortPathSequence();
					sys.wait( 2.0 );

					thread Convey2LongPathSequence();
					sys.wait( 18.0 );
				}
			}
			else
			{
				$weld1_front_support.time( 0.1 );
				$weld1_front_cover.time( 0.1 );
				$weld1_rear_support.time( 0.1 );
				$weld1_rear_cover.time( 0.1 );
				$weld2_front_support.time( 0.1 );
				$weld2_front_cover.time( 0.1 );
				$weld2_rear_support.time( 0.1 );
				$weld2_rear_cover.time( 0.1 );
				$weld1_front_support.moveTo( $weld1_front_long_origin );
				$weld1_front_cover.moveTo( $weld1_front_long_origin );
				$weld1_rear_support.moveTo( $weld1_rear_long_origin );
				$weld1_rear_cover.moveTo( $weld1_rear_long_origin );
				$weld2_front_support.moveTo( $weld2_front_long_origin );
				$weld2_front_cover.moveTo( $weld2_front_long_origin );
				$weld2_rear_support.moveTo( $weld2_rear_long_origin );
				$weld2_rear_cover.moveTo( $weld2_rear_long_origin );
				sys.waitFor( $weld2_rear_cover );

				// 1 goes long, 2 goes long
				fTemp = sys.random( 3.0 );
				if( fTemp < 1 )
				{
					// early/early
					thread Convey1LongPathSequence();
					sys.wait( 2.0 );

					thread Convey2LongPathSequence();
					sys.wait( 28.0 );
				}
				else if( fTemp < 2 )
				{
					// late/early
					sys.wait( 2.0 );

					thread Convey2LongPathSequence();
					sys.wait( 8.0 );

					thread Convey1LongPathSequence();
					sys.wait( 20.0 );
				}
				else
				{
					// late/late
					sys.wait( 10.0 );

					thread Convey1LongPathSequence();
					sys.wait( 2.0 );

					thread Convey2LongPathSequence();
					sys.wait( 18.0 );
				}
			}
		}
	}


	void SetupRideOfDeathTrap2()
	{
		$spinner_top.time( 0.1 );
		$spinner_bottom.time( 0.1 );
		$spinner_top.rotateOnce( '0 -45 0' );
		$spinner_bottom.rotateOnce( '0 -45 0' );
		sys.waitFor( $spinner_bottom );
	}


	void TopSpinnerRotate()
	{
		$spinner_top.time( 2.0 );
		$spinner_top.accelTime( 0.25 );
		$spinner_top.decelTime( 0.25 );
		sys.trigger ($speaker_spinner_top);
		$spinner_top.rotateOnce( '0 -90 0' );
		sys.waitFor( $spinner_top );

		// do some effects stuff
		sys.wait( 3.0 );
	}


	void BottomSpinnerRotate()
	{
		$spinner_bottom.time( 2.0 );
		$spinner_bottom.accelTime( 0.25 );
		$spinner_bottom.decelTime( 0.25 );
		$spinner_bottom.rotateOnce( '0 -90 0' );
		sys.trigger ($speaker_spinner_bottom);
		sys.waitFor( $spinner_bottom );

		// do some effects stuff
		sys.wait( 3.0 );
	}


	void RideOfDeathTrap2Loop()
	{
		while( true )
		{
			thread BottomSpinnerRotate();
			sys.wait( 0.5 );

			thread TopSpinnerRotate();
			sys.wait( 4.5 );
		}
	}


	void SetupRideOfDeathTrap3()
	{
	}


	void RideOfDeathTrap3Loop()
	{
		sys.trigger($trap3_impspawn);

		//bring everything else out 160
		$discharge_arm_1.bind ($discharge_stack_1);
		$discharge_arm_2.bind ($discharge_stack_2);

		$spin_pooperplat1.move (WEST, 24);
		$spin_pooperplat2.move (EAST, 24);
		
		sys.trigger ($discharge_stack_1_speaker);
		$discharge_stack_1.move (NORTH, 160);
		sys.wait (1);
		sys.trigger ($discharge_stack_2_speaker);
		$discharge_stack_2.move (NORTH, 160);
		sys.waitFor ($discharge_stack_2);

		$discharge_arm_1.unbind ();
		$discharge_arm_2.unbind ();

		sys.trigger ($discharge_arm_1_speaker);
		$discharge_arm_1.move (NORTH, 112);
		sys.wait (0.5);
		sys.trigger ($discharge_arm_2_speaker);
		$discharge_arm_2.move (NORTH, 112);
		sys.waitFor ($discharge_arm_2);

		sys.trigger ($discharge_lens_1_speaker);
		$discharge_lens_1.rotateOnce ('0 0 90');
		sys.wait (0.33);
		sys.trigger ($discharge_lens_2_speaker);
		$discharge_lens_2.rotateOnce ('0 0 90');
		//sys.wait(.5);

		//bring to ready position
		sys.trigger ($speaker_pooper1);			// Who the hell named this "pooper" anyway ?
		$spin_pooper1.move (DOWN, 96);			// Ahh.. the scatological humor runs rampant... -Xian
		sys.wait (1.5);
		sys.trigger ($speaker_pooper2);
		$spin_pooper2.move (DOWN, 96);

		//bring the nipples up
		$discharge_nipple_1.time (2);
		$discharge_nipple_2.time (2);
		
		sys.trigger ($discharge_nipple_1_speaker);
		$discharge_nipple_1.move (UP, 176);
		sys.wait (0.48);
		$discharge_nipple_2.move (UP, 176);
		sys.trigger ($discharge_nipple_2_speaker);
		sys.waitFor($discharge_nipple_2);

		//initial movement to make sure the particles are on correctly
		$spin_paddle1.time( 1.2 );
		$spin_paddle1.accelTime( 0.25 );
		$spin_paddle1.decelTime( 0.25 );
		sys.trigger ($speaker_paddle1);
		$spin_paddle1.rotateOnce( '0 180 0' );
		sys.waitFor( $spin_paddle1 );
		
		
		//trigger the lightning on

		$dbuzz1.startSoundShader ("jacob", SND_CHANNEL_VOICE );

		sys.trigger ($dbuzz1);
		sys.trigger ($dbuzz1_light);
		sys.wait( 1.0 );

		$spin_paddle2.time( 1.2 );
		$spin_paddle2.accelTime( 0.25 );
		$spin_paddle2.decelTime( 0.25 );
		sys.trigger ($speaker_paddle2);
		$spin_paddle2.rotateOnce( '0 -180 0' );
		sys.waitFor( $spin_paddle2 );
		
		//trigger the lightning on
		$dbuzz2.startSoundShader ("jacob", SND_CHANNEL_VOICE );
		sys.trigger ($dbuzz2);
		sys.trigger ($dbuzz2_light);
		
		sys.wait( 1.0 );

		while( true ) {
			//trigger the lightning off
			sys.trigger ($dbuzz1);
			sys.trigger ($dbuzz1_light);
			$spin_paddle1.time( 1.2 );
			$spin_paddle1.accelTime( 0.25 );
			$spin_paddle1.decelTime( 0.25 );
			sys.trigger ($speaker_paddle1);
			$spin_paddle1.rotateOnce( '0 180 0' );
			sys.waitFor( $spin_paddle1 );
			//trigger the lightning on
			$dbuzz1.startSoundShader ("jacob", SND_CHANNEL_VOICE );
			sys.trigger ($dbuzz1);
			sys.trigger ($dbuzz1_light);
			sys.wait( 1.0 );

		    //trigger the lightning off
			sys.trigger ($dbuzz2);
			sys.trigger ($dbuzz2_light);
			$spin_paddle2.time( 1.2 );
			$spin_paddle2.accelTime( 0.25 );
			$spin_paddle2.decelTime( 0.25 );
			sys.trigger ($speaker_paddle2);
			$spin_paddle2.rotateOnce( '0 -180 0' );
			sys.waitFor( $spin_paddle2 );
			//trigger the lightning on
			$dbuzz2.startSoundShader ("jacob", SND_CHANNEL_VOICE );
			sys.trigger ($dbuzz2);
			sys.trigger ($dbuzz2_light);
			sys.wait( 1.0 );
		}
	}



	void SetupRideOfDeathTrap5()
	{
		$pounder1_left_base.time( 0.1 );
		$pounder1_left_cushion.time( 0.1 );
		$pounder1_left_inside.time( 0.1 );
		$pounder1_left_outside.time( 0.1 );
		$pounder2_left_base.time( 0.1 );
		$pounder2_left_cushion.time( 0.1 );
		$pounder2_left_inside.time( 0.1 );
		$pounder2_left_outside.time( 0.1 );
		$pounder1_right_base.time( 0.1 );
		$pounder1_right_cushion.time( 0.1 );
		$pounder1_right_inside.time( 0.1 );
		$pounder1_right_outside.time( 0.1 );
		$pounder2_right_base.time( 0.1 );
		$pounder2_right_cushion.time( 0.1 );
		$pounder2_right_inside.time( 0.1 );
		$pounder2_right_outside.time( 0.1 );
		$pounder1_left_base.rotateOnce( '-30 0 0' );
		$pounder1_left_cushion.rotateOnce( '-30 0 0' );
		$pounder1_left_inside.rotateOnce( '-30 0 0' );
		$pounder1_left_outside.rotateOnce( '-30 0 0' );
		$pounder2_left_base.rotateOnce( '-30 0 0' );
		$pounder2_left_cushion.rotateOnce( '-30 0 0' );
		$pounder2_left_inside.rotateOnce( '-30 0 0' );
		$pounder2_left_outside.rotateOnce( '-30 0 0' );
		$pounder1_right_base.rotateOnce( '30 0 0' );
		$pounder1_right_cushion.rotateOnce( '30 0 0' );
		$pounder1_right_inside.rotateOnce( '30 0 0' );
		$pounder1_right_outside.rotateOnce( '30 0 0' );
		$pounder2_right_base.rotateOnce( '30 0 0' );
		$pounder2_right_cushion.rotateOnce( '30 0 0' );
		$pounder2_right_inside.rotateOnce( '30 0 0' );
		$pounder2_right_outside.rotateOnce( '30 0 0' );
		sys.waitFor( $pounder2_right_outside );

		$pounder1_left_inside.time( 0.1 );
		$pounder1_left_outside.time( 0.1 );
		$pounder2_left_inside.time( 0.1 );
		$pounder2_left_outside.time( 0.1 );
		$pounder1_right_inside.time( 0.1 );
		$pounder1_right_outside.time( 0.1 );
		$pounder2_right_inside.time( 0.1 );
		$pounder2_right_outside.time( 0.1 );
		$pounder1_left_inside.move( REL_FORWARD, 288 );
		$pounder1_left_outside.move( REL_FORWARD, 256 );
		$pounder2_left_inside.move( REL_FORWARD, 288 );
		$pounder2_left_outside.move( REL_FORWARD, 256 );
		$pounder1_right_inside.move( REL_BACK, 288 );
		$pounder1_right_outside.move( REL_BACK, 256 );
		$pounder2_right_inside.move( REL_BACK, 288 );
		$pounder2_right_outside.move( REL_BACK, 256 );
		sys.waitFor( $pounder2_right_outside );
	}


	void Pounder1Sequence()
	{
		float fRandom;

		fRandom = sys.random( 2.0 );

		if( fRandom < 1.0 )
		{
			// extending out
			
			$pounder1_left_inside.time( 0.5 );
			$pounder1_left_inside.accelTime( 0.0 );
			$pounder1_left_inside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder1_halfsecond);
			$pounder1_left_inside.move( REL_BACK, 288 );
			sys.waitFor( $pounder1_left_inside );
			sys.wait( 0.25 );

			$pounder1_left_outside.time( 0.2 );
			$pounder1_left_outside.accelTime( 0.0 );
			$pounder1_left_outside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder1_left_outside_p2);
			$pounder1_left_outside.move( REL_BACK, 256 );
			sys.waitFor( $pounder1_left_outside );

			$pounder1_left_outside.time( 0.1 );
			$pounder1_left_outside.accelTime( 0.0 );
			$pounder1_left_outside.decelTime( 0.1 );
			$pounder1_left_cushion.time( 0.1 );
			$pounder1_left_cushion.accelTime( 0.0 );
			$pounder1_left_cushion.decelTime( 0.1 );
			$pounder1_left_outside.move( REL_BACK, 16 );
			sys.trigger ($speaker_pounder1_left_cushion);
			$pounder1_left_cushion.move( REL_BACK, 16 );
			sys.waitFor( $pounder1_left_cushion );

			$pounder1_left_outside.time( 0.2 );
			$pounder1_left_outside.accelTime( 0.0 );
			$pounder1_left_outside.decelTime( 0.0 );
			$pounder1_left_cushion.time( 0.2 );
			$pounder1_left_cushion.accelTime( 0.0 );
			$pounder1_left_cushion.decelTime( 0.0 );
			$pounder1_left_outside.move( REL_FORWARD, 16 );
			$pounder1_left_cushion.move( REL_FORWARD, 16 );
			sys.waitFor( $pounder1_left_cushion );

			sys.wait( 2.0 );

			// Sucking back in

			$pounder1_left_outside.time( 1.0 );
			$pounder1_left_outside.accelTime( 0.25 );
			$pounder1_left_outside.decelTime( 0.25 );
			$pounder1_left_inside.time( 2.0 );
			$pounder1_left_inside.accelTime( 0.5 );
			$pounder1_left_inside.decelTime( 0.5 );
			sys.trigger ($speaker_pounder1_left_outside_1s);
			$pounder1_left_outside.move( REL_FORWARD, 256 );
			sys.trigger ($speaker_pounder1_left_inside);
			$pounder1_left_inside.move( REL_FORWARD, 288 );
			sys.waitFor( $pounder1_left_inside );
		}
		else
		{
			$pounder1_right_inside.time( 0.5 );
			$pounder1_right_inside.accelTime( 0.0 );
			$pounder1_right_inside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder1_halfsecond);
			$pounder1_right_inside.move( REL_FORWARD, 288 );
			sys.waitFor( $pounder1_right_inside );
			sys.wait( 0.25 );

			$pounder1_right_outside.time( 0.2 );
			$pounder1_right_outside.accelTime( 0.0 );
			$pounder1_right_outside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder1_right_outside_p2);
			$pounder1_right_outside.move( REL_FORWARD, 256 );
			sys.waitFor( $pounder1_right_outside );

			$pounder1_right_outside.time( 0.1 );
			$pounder1_right_outside.accelTime( 0.0 );
			$pounder1_right_outside.decelTime( 0.1 );
			$pounder1_right_cushion.time( 0.1 );
			$pounder1_right_cushion.accelTime( 0.0 );
			$pounder1_right_cushion.decelTime( 0.1 );
			$pounder1_right_outside.move( REL_FORWARD, 16 );
			sys.trigger ($speaker_pounder1_right_cushion);
			$pounder1_right_cushion.move( REL_FORWARD, 16 );
			sys.waitFor( $pounder1_right_cushion );

			$pounder1_right_outside.time( 0.2 );
			$pounder1_right_outside.accelTime( 0.0 );
			$pounder1_right_outside.decelTime( 0.0 );
			$pounder1_right_cushion.time( 0.2 );
			$pounder1_right_cushion.accelTime( 0.0 );
			$pounder1_right_cushion.decelTime( 0.0 );
			$pounder1_right_outside.move( REL_BACK, 16 );
			$pounder1_right_cushion.move( REL_BACK, 16 );
			sys.waitFor( $pounder1_right_cushion );

			sys.wait( 2.0 );

			$pounder1_right_outside.time( 1.0 );
			$pounder1_right_outside.accelTime( 0.25 );
			$pounder1_right_outside.decelTime( 0.25 );
			$pounder1_right_inside.time( 2.0 );
			$pounder1_right_inside.accelTime( 0.5 );
			$pounder1_right_inside.decelTime( 0.5 );
			sys.trigger ($speaker_pounder1_right_outside_1s);
			$pounder1_right_outside.move( REL_BACK, 256 );
			sys.trigger ($speaker_pounder1_right_inside);
			$pounder1_right_inside.move( REL_BACK, 288 );
			sys.waitFor( $pounder1_left_inside );
		}
	}


	void Pounder2Sequence()
	{
		float fRandom;

		fRandom = sys.random( 2.0 );

		if( fRandom < 1.0 )
		{
			$pounder2_left_inside.time( 0.5 );
			$pounder2_left_inside.accelTime( 0.0 );
			$pounder2_left_inside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder2_halfsecond);
			$pounder2_left_inside.move( REL_BACK, 288 );
			sys.waitFor( $pounder2_left_inside );
			sys.wait( 0.25 );

			$pounder2_left_outside.time( 0.2 );
			$pounder2_left_outside.accelTime( 0.0 );
			$pounder2_left_outside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder2_left_outside_p2);
			$pounder2_left_outside.move( REL_BACK, 256 );
			sys.waitFor( $pounder2_left_outside );

			$pounder2_left_outside.time( 0.1 );
			$pounder2_left_outside.accelTime( 0.0 );
			$pounder2_left_outside.decelTime( 0.1 );
			$pounder2_left_cushion.time( 0.1 );
			$pounder2_left_cushion.accelTime( 0.0 );
			$pounder2_left_cushion.decelTime( 0.1 );
			$pounder2_left_outside.move( REL_BACK, 16 );
			$pounder2_left_cushion.move( REL_BACK, 16 );
			sys.waitFor( $pounder2_left_cushion );

			$pounder2_left_outside.time( 0.2 );
			$pounder2_left_outside.accelTime( 0.0 );
			$pounder2_left_outside.decelTime( 0.0 );
			$pounder2_left_cushion.time( 0.2 );
			$pounder2_left_cushion.accelTime( 0.0 );
			$pounder2_left_cushion.decelTime( 0.0 );
			$pounder2_left_outside.move( REL_FORWARD, 16 );
			sys.trigger ($speaker_pounder2_left_cushion);
			$pounder2_left_cushion.move( REL_FORWARD, 16 );
			sys.waitFor( $pounder2_left_cushion );

			sys.wait( 2.0 );

			$pounder2_left_outside.time( 1.0 );
			$pounder2_left_outside.accelTime( 0.25 );
			$pounder2_left_outside.decelTime( 0.25 );
			$pounder2_left_inside.time( 2.0 );
			$pounder2_left_inside.accelTime( 0.5 );
			$pounder2_left_inside.decelTime( 0.5 );
			sys.trigger ($speaker_pounder2_left_outside_1s);
			$pounder2_left_outside.move( REL_FORWARD, 256 );
			sys.trigger ($speaker_pounder2_left_inside);
			$pounder2_left_inside.move( REL_FORWARD, 288 );
			sys.waitFor( $pounder2_left_inside );
		}
		else
		{
			$pounder2_right_inside.time( 0.5 );
			$pounder2_right_inside.accelTime( 0.0 );
			$pounder2_right_inside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder2_halfsecond);
			$pounder2_right_inside.move( REL_FORWARD, 288 );
			sys.waitFor( $pounder2_right_inside );
			sys.wait( 0.25 );

			$pounder2_right_outside.time( 0.2 );
			$pounder2_right_outside.accelTime( 0.0 );
			$pounder2_right_outside.decelTime( 0.0 );
			sys.trigger ($speaker_pounder2_right_outside_p2);
			$pounder2_right_outside.move( REL_FORWARD, 256 );
			sys.waitFor( $pounder2_right_outside );

			$pounder2_right_outside.time( 0.1 );
			$pounder2_right_outside.accelTime( 0.0 );
			$pounder2_right_outside.decelTime( 0.1 );
			$pounder2_right_cushion.time( 0.1 );
			$pounder2_right_cushion.accelTime( 0.0 );
			$pounder2_right_cushion.decelTime( 0.1 );
			$pounder2_right_outside.move( REL_FORWARD, 16 );
			sys.trigger ($speaker_pounder2_right_cushion);
			$pounder2_right_cushion.move( REL_FORWARD, 16 );
			sys.waitFor( $pounder2_right_cushion );

			$pounder2_right_outside.time( 0.2 );
			$pounder2_right_outside.accelTime( 0.0 );
			$pounder2_right_outside.decelTime( 0.0 );
			$pounder2_right_cushion.time( 0.2 );
			$pounder2_right_cushion.accelTime( 0.0 );
			$pounder2_right_cushion.decelTime( 0.0 );
			$pounder2_right_outside.move( REL_BACK, 16 );
			$pounder2_right_cushion.move( REL_BACK, 16 );
			sys.waitFor( $pounder2_right_cushion );

			sys.wait( 2.0 );

			$pounder2_right_outside.time( 1.0 );
			$pounder2_right_outside.accelTime( 0.25 );
			$pounder2_right_outside.decelTime( 0.25 );
			$pounder2_right_inside.time( 2.0 );
			$pounder2_right_inside.accelTime( 0.5 );
			$pounder2_right_inside.decelTime( 0.5 );
			sys.trigger ($speaker_pounder2_right_outside_1s);
			$pounder2_right_outside.move( REL_BACK, 256 );
			sys.trigger ($speaker_pounder2_right_inside);
			$pounder2_right_inside.move( REL_BACK, 288 );
			sys.waitFor( $pounder2_left_inside );
		}
	}


	void RideOfDeathTrap5Loop()
	{
		// FIXME: add a light cue where the rods come out to let the player
		// know which one is about to fire
		sys.wait( 7.5 );

		while( true )
		{
			thread Pounder1Sequence();
			sys.wait( 2.0 );

			thread Pounder2Sequence();
			sys.wait( 8.0 );
		}
	}



	void SetupRideOfDeathTraps()
	{
		SetupRideOfDeathObjects();

		SetupRideOfDeathTrap1();
		SetupRideOfDeathTrap2();
		SetupRideOfDeathTrap3();
		SetupRideOfDeathTrap5();
	
		thread RideOfDeathTrap1Loop();
		thread RideOfDeathTrap2Loop();
		thread RideOfDeathTrap5Loop();
	}


	void LightGroup1Sequence()
	{
		$lightgroup1_swing_light1.accelTime( 0.25 );
		$lightgroup1_swing_light1.time( 1.0 );
		$lightgroup1_swing_light1.decelTime( 0.25 );
		$lightgroup1_swing_light2.accelTime( 0.25 );
		$lightgroup1_swing_light2.time( 1.0 );
		$lightgroup1_swing_light2.decelTime( 0.25 );
		$lightgroup1_swing_light1.rotateOnce( '0 0 135' );
		$lightgroup1_swing_light2.rotateOnce( '0 0 135' );
		sys.waitFor( $lightgroup1_swing_light2 );

		$lightgroup1_swing_light1_light.On();
		$lightgroup1_swing_light2_light.On();

		$lightgroup1_lighta.On();
		$lightgroup1_lightb.On();
		$lightgroup1_lightc.On();
	}


	void GlideLight1Loop()
	{
		float fTime;

		while( true )
		{
			fTime = sys.random( 2.0 );

			$glide_light1.time( fTime + 1.0 );
			$glide_light1.accelTime( fTime / 4 );
			$glide_light1.decelTime( fTime / 4 );
			$glide_light1.move( NORTH, 448 );
			sys.waitFor( $glide_light1 );

			fTime = sys.random( 2.0 );
			sys.wait( fTime + 1.0 );

			fTime = sys.random( 2.0 );

			$glide_light1.time( fTime + 1.0 );
			$glide_light1.accelTime( fTime / 4 );
			$glide_light1.decelTime( fTime / 4 );
			$glide_light1.move( SOUTH, 448 );
			sys.waitFor( $glide_light1 );

			fTime = sys.random( 2.0 );
			sys.wait( fTime + 1.0 );
		}
	}


	void GlideLight2Loop()
	{
		float fTime;

		while( true )
		{
			fTime = sys.random( 1.5 );

			$glide_light2.time( fTime + 0.5 );
			$glide_light2.accelTime( fTime / 4 );
			$glide_light2.decelTime( fTime / 4 );
			$glide_light2.move( WEST, 256 );
			sys.waitFor( $glide_light2 );

			fTime = sys.random( 1.25 );
			sys.wait( fTime + 0.5 );

			fTime = sys.random( 1.5 );

			$glide_light2.time( fTime + 0.5 );
			$glide_light2.accelTime( fTime / 4 );
			$glide_light2.decelTime( fTime / 4 );
			$glide_light2.move( EAST, 256 );
			sys.waitFor( $glide_light2 );

			fTime = sys.random( 1.25 );
			sys.wait( fTime + 0.5 );
		}
	}


	void CargoObjectLoop( string strObject )
	{
		entity eObject;
		entity eLight;

		eObject = sys.getEntity( strObject );
		eLight = sys.getEntity( strObject + "_light" );

		eObject.time( 3.0 );
		eObject.move( SOUTH, 176 );
		sys.waitFor( eObject );

		eObject.bind( $cargo_object_origin1 );

		$cargo_object_origin1.time( 1.75 );
		$cargo_object_origin1.rotateOnce( '0 90 0' );
		sys.waitFor( $cargo_object_origin1 );

		eObject.unbind();
		$cargo_object_origin1.restorePosition();

		eObject.time( 0.6 );
		eObject.move( EAST, 48 );
		sys.waitFor( eObject );

		eLight.On();

		eObject.bind( $cargo_object_origin2 );

		$cargo_object_origin2.time( 1.75 );
		$cargo_object_origin2.rotateOnce( '0 90 0' );
		sys.waitFor( $cargo_object_origin2 );

		eObject.unbind();
		$cargo_object_origin2.restorePosition();

		eObject.time( 4.25 );
		eObject.move( NORTH, 304 );
		sys.waitFor( eObject );

		eObject.bind( $cargo_object_origin3 );

		$cargo_object_origin3.time( 6.0 );
		$cargo_object_origin3.rotateOnce( '0 -90 0' );
		sys.waitFor( $cargo_object_origin3 );

		eObject.unbind();
		$cargo_object_origin3.restorePosition();

		eObject.time( 14.0 );
		eObject.move( EAST, 896 );
		sys.waitFor( eObject );

		eObject.bind( $cargo_object_origin4 );

		$cargo_object_origin4.time( 6.0 );
		$cargo_object_origin4.rotateOnce( '0 -90 0' );
		sys.waitFor( $cargo_object_origin4 );

		eObject.unbind();
		$cargo_object_origin4.restorePosition();

		eObject.time( 1.0 );
		eObject.move( SOUTH, 64 );
		sys.waitFor( eObject );

		eObject.bind( $cargo_object_origin5 );

		$cargo_object_origin5.time( 4.0 );
		$cargo_object_origin5.rotateOnce( '0 -90 0' );
		sys.waitFor( $cargo_object_origin5 );

		eObject.unbind();
		$cargo_object_origin5.restorePosition();

		eLight.Off();

		eObject.time( 2.0 );
		eObject.move( WEST, 128 );
		sys.waitFor( eObject );

		eObject.restorePosition();
	}
	// 46s


	void CargoObjectSequence()
	{
		string strObject;
		float ii;

		while( true )
		{
			for( ii = 1; ii < 5; ii++ )
			{
				strObject = "cargo_object" + ii;
				thread CargoObjectLoop( strObject );
				sys.wait( 15.0 );
			}
		}
	}



	void LightsOffThread()
	{
		sys.trigger($dark_door_open);
		sys.trigger($dark_backstab);
		sys.trigger($dark_b2);
		sys.trigger($dark_triteclimb);
		sys.trigger($rod_doortrig);
		sys.trigger($lightsoff_lock);

		thread ExtendSectionBridges();

		SetupRideOfDeathTraps();
		RemoveRideOfDeathObjects();
	}


	void LightsOnThread()
	{
		sys.trigger($lights_on_doortrig);
		sys.trigger($lightside_lock_1);
		thread SectionBridgeRemoveAll();

		thread ExtendPlatform1();
		thread RotatingBridgeStart();

		thread LightGroup1Sequence();
		sys.wait( 5.0 );

		thread RotatingBridgeLoop();
	}


	void RideOfDeathThread()
	{
		sys.trigger($rod_doortrig);
		SetupRideOfDeathTraps();
		RideOfDeathLoop();
	}

	/*--------------------------------------------------------------------
		
		F r a g c h a m b e r    scripting START
		
	--------------------------------------------------------------------*/


	// -------------------------------------------------
	// Chamber Core DOWN
	// -------------------------------------------------
	void chamber_core_down()
	{
		$chamber_core.time(5);
		$chamber_core.accelTime(1);
		$chamber_core.decelTime(1.5);
		$chamber_core.moveTo($chamber_core_down);

		sys.trigger ($chamber_core_down_speaker);
		sys.wait (4);
		//no turning back... remove cancel option
		$guicon1.setGuiParm ( "gui_parm9" , 0);
		sys.trigger ($speaker_juicer);
		sys.waitFor ($chamber_core);
	
	}

	// -------------------------------------------------
	// Chamber Core UP
	// -------------------------------------------------
	void chamber_core_up()
	{
		$chamber_core.time(3);
		$chamber_core.accelTime(2.5);
		$chamber_core.decelTime(.5);
		$chamber_core.moveTo($chamber_core_up);

		sys.trigger ($chamber_core_up_speaker);

		sys.waitFor ($chamber_core);
	}

	// -------------------------------------------------
	// Chamber Rods DOWN
	// -------------------------------------------------
	void chamber_rods_down()
	{
		$chamber_rods.time(4);
		$chamber_rods.accelTime(1);
		$chamber_rods.decelTime(.5);
		$chamber_rods.moveTo($chamber_rod_down);

		sys.trigger ($chamber_rods_down_speaker);

		sys.waitFor ($chamber_rods);
	}

	// -------------------------------------------------
	// Chamber Rods UP
	// -------------------------------------------------
	void chamber_rods_up()
	{
		$chamber_rods.time(3);
		$chamber_rods.accelTime(1);
		$chamber_rods.decelTime(.5);
		$chamber_rods.moveTo($chamber_rod_up);

		sys.trigger ($chamber_rods_up_speaker);

		sys.waitFor ($chamber_rods);
	}


	// -------------------------------------------------
	// Chamber Sockets OUT
	// -------------------------------------------------
	void chamber_sockets_out()
	{
		$chamber_socket1.time(2);
		$chamber_socket1.moveTo($chamber_socket1_out);
		$chamber_socket2.time(2);
		$chamber_socket2.moveTo($chamber_socket2_out);
		$chamber_socket3.time(2);
		$chamber_socket3.moveTo($chamber_socket3_out);
		$chamber_socket4.time(2);
		$chamber_socket4.moveTo($chamber_socket4_out);

		sys.trigger ($chamber_sockets_out_speaker);

		sys.waitFor ($chamber_socket4);
	}

	// -------------------------------------------------
	// Chamber Sockets IN
	// -------------------------------------------------
	void chamber_sockets_in()
	{
		$chamber_socket1.time(2);
		$chamber_socket1.moveTo($chamber_socket1_in);
		$chamber_socket2.time(2);
		$chamber_socket2.moveTo($chamber_socket2_in);
		$chamber_socket3.time(2);
		$chamber_socket3.moveTo($chamber_socket3_in);
		$chamber_socket4.time(2);
		$chamber_socket4.moveTo($chamber_socket4_in);

		sys.trigger ($chamber_sockets_in_speaker);

		sys.waitFor ($chamber_socket4);
	}

	// -------------------------------------------------
	// Close the chamber doors
	// -------------------------------------------------
	void chamber_closedoors()
	{
		$chamber_door2a.close();
		$chamber_door2b.close();
		$chamber_door4a.close();
		$chamber_door4b.close();

		$chamber_door2a.lock(1);
		$chamber_door2b.lock(1);
		$chamber_door4a.lock(1);
		$chamber_door4b.lock(1);

		$fragchamber_door1_gui.setGuiParm ("gui_parm3", 0);
		$fragchamber_door2_gui.setGuiParm ("gui_parm3", 0);

		$fragchamber_door1_gui.setShaderParm (7, 0);
		$fragchamber_door2_gui.setShaderParm (7, 0);

		$fragchamber_door1_blinky_red.show();
		$fragchamber_door1_blinky_green.hide();
		$fragchamber_door2_blinky_red.show();
		$fragchamber_door2_blinky_green.hide();

		$fragchamber_door1_bl1.setColor (1, 0, 0);
		$fragchamber_door1_bl2.setColor (1, 0, 0);
		$fragchamber_door2_bl1.setColor (1, 0, 0);
		$fragchamber_door2_bl2.setColor (1, 0, 0);
	}

	// -------------------------------------------------
	// Trigger the Chamber into action!
	// -------------------------------------------------
	void chamber_trigger()
	{
		float moverthread;

		$guicon1.setGuiParm ("gui_parm9", 1);

		//bridge times
		$chamber_bridge1.time(.5);
		$chamber_bridge2.time(.5);
		$chamber_bridge3.time(.5);
		$chamber_bridge4.time(.5);

		//doors CLOSE and LOCK
		thread chamber_closedoors();
		
		//bridges up
		sys.trigger ($bridge_up_speaker);
		$chamber_bridge1.rotateOnce( '0 0 -61' );
		$chamber_bridge2.rotateOnce( '100 0 0' );
		$chamber_bridge3.rotateOnce( '0 0 61' );
		$chamber_bridge4.rotateOnce( '-100 0 0' );
		
		//core DOWN

		thread chamber_core_down();

		//trigger the NPC to panic
		sys.trigger ($fragchamber_npc_panic);
		
		//sockets OUT
		sys.waitFor($chamber_bridge1);

		moverthread = thread chamber_sockets_out();
		sys.waitForThread ( moverthread );
		
		//rods DOWN

		moverthread = thread chamber_rods_down();
		sys.waitForThread ( moverthread );
		sys.wait(1);
		
		//kill npc
		$fragchamber_npc.kill();
		sys.trigger ($skeleton_spawn);
		sys.trigger ($punish_lock);
		//thread frontroom_door_open();
		
		//kill the 2nd scientist standing at the door
		$alphalabs3_fragchamber_scientist2_2.remove();

		sys.trigger ($speaker_warmup);
		sys.wait (2.5);
		
		//...Dramatic pause and doing stuff sound
		sys.trigger ($fragchamber_active);
		sys.wait (1);
		sys.trigger ($punish_relay);
		sys.wait (1);

		//rods up and sockets in
		thread chamber_rods_up();
		sys.wait (1);
		moverthread = thread chamber_sockets_in();
		sys.waitForThread ( moverthread );
		
		//bridges DOWN
		sys.trigger ($bridge_down_speaker);
		$chamber_bridge1.rotateOnce( '0 0 61' );
		$chamber_bridge2.rotateOnce( '-100 0 0' );
		$chamber_bridge3.rotateOnce( '0 0 -61' );
		$chamber_bridge4.rotateOnce( '100 0 0' );

		//core up

		moverthread = thread chamber_core_up();
		sys.waitForThread ( moverthread );
		
		//doors OPEN and unlock
		sys.wait(1);
		$chamber_door2a.open();
		$chamber_door2b.open();
		$chamber_door4a.open();
		$chamber_door4b.open();

		$chamber_door2a.lock(0);
		$chamber_door2b.lock(0);
		$chamber_door4a.lock(0);
		$chamber_door4b.lock(0);

		$fragchamber_door1_gui.setGuiParm ("gui_parm3", 1);
		$fragchamber_door2_gui.setGuiParm ("gui_parm3", 1);

		$fragchamber_door1_gui.setShaderParm (7, 1);
		$fragchamber_door2_gui.setShaderParm (7, 1);

		$fragchamber_door1_blinky_red.hide();
		$fragchamber_door1_blinky_green.show();
		$fragchamber_door2_blinky_red.hide();
		$fragchamber_door2_blinky_green.show();

		$fragchamber_door1_bl1.setColor (0, 1, 0);
		$fragchamber_door1_bl2.setColor (0, 1, 0);
		$fragchamber_door2_bl1.setColor (0, 1, 0);
		$fragchamber_door2_bl2.setColor (0, 1, 0);

		//trigger control gui to reset it
		$guicon1.setGuiParm ("gui_parm8", 1);
		$guicon1.setGuiParm ("gui_parm9", 1);
	}

	// -------------------------------------------------
	// Cancel the Chamber
	// -------------------------------------------------
	void chamber_cancel()
	{
		float moverthread;

		sys.print ("chamber_cancel\n");
		sys.killthread ("map_alphalabs4::chamber_trigger");
		sys.killthread ("map_alphalabs4::chamber_core_down");
		sys.trigger($npc_backup);

		//rods up and sockets in
		thread chamber_rods_up();
		thread chamber_sockets_in();
	
		//core up
		moverthread = thread chamber_core_up();
		//sys.waitForThread ( moverthread );

		//trigger the NPC relief
		sys.wait( 1 );
		sys.trigger ($fragchamber_npc_relief );
		
		//bridges DOWN
		sys.trigger ($bridge_down_speaker);
		$chamber_bridge1.rotateOnce( '0 0 61' );
		$chamber_bridge2.rotateOnce( '-100 0 0' );
		$chamber_bridge3.rotateOnce( '0 0 -61' );
		$chamber_bridge4.rotateOnce( '100 0 0' );
		sys.waitFor ($chamber_bridge4);

		//doors OPEN and unlock
		sys.wait(1);
		$chamber_door2a.open();
		$chamber_door2b.open();
		$chamber_door4a.open();
		$chamber_door4b.open();

		$chamber_door2a.lock(0);
		$chamber_door2b.lock(0);
		$chamber_door4a.lock(0);
		$chamber_door4b.lock(0);

		$fragchamber_door1_gui.setGuiParm ("gui_parm3", 1);
		$fragchamber_door2_gui.setGuiParm ("gui_parm3", 1);

		$fragchamber_door1_gui.setShaderParm (7, 1);
		$fragchamber_door2_gui.setShaderParm (7, 1);

		$fragchamber_door1_blinky_red.hide();
		$fragchamber_door1_blinky_green.show();
		$fragchamber_door2_blinky_red.hide();
		$fragchamber_door2_blinky_green.show();

		$fragchamber_door1_bl1.setColor (0, 1, 0);
		$fragchamber_door1_bl2.setColor (0, 1, 0);
		$fragchamber_door2_bl1.setColor (0, 1, 0);
		$fragchamber_door2_bl2.setColor (0, 1, 0);

		sys.wait (1);

		//trigger control gui to reset it
		$guicon1.setGuiParm ("gui_parm8", 3);
		$guicon1.setGuiParm ("gui_parm9", 1);

		//trigger the NPC to leave
		sys.print ("trigger\n");
		sys.trigger ($fragchamber_npc);

		// keep the doors open for a few seconds
		float end_time = sys.getTime() + 7;
		while( sys.getTime() < end_time ) {
			sys.trigger( $chamber_door2a );
			sys.trigger( $chamber_door2b );
			sys.trigger( $chamber_door4a );
			sys.trigger( $chamber_door4b );
			sys.wait( 0.5 );
		}
	}

	// -------------------------------------------------
	// Open the chamber doors
	// -------------------------------------------------
	void chamber_opendoors()
	{
		// doors OPEN and unlock
		sys.wait(1);
		sys.trigger($npc_backup);
		$chamber_door2a.open();
		$chamber_door2b.open();
		$chamber_door4a.open();
		$chamber_door4b.open();

		$chamber_door2a.lock(0);
		$chamber_door2b.lock(0);
		$chamber_door4a.lock(0);
		$chamber_door4b.lock(0);

		$fragchamber_door1_gui.setGuiParm ("gui_parm3", 1);
		$fragchamber_door2_gui.setGuiParm ("gui_parm3", 1);

		$fragchamber_door1_gui.setShaderParm (7, 1);
		$fragchamber_door2_gui.setShaderParm (7, 1);

		$fragchamber_door1_blinky_red.hide();
		$fragchamber_door1_blinky_green.show();
		$fragchamber_door2_blinky_red.hide();
		$fragchamber_door2_blinky_green.show();

		$fragchamber_door1_bl1.setColor (0, 1, 0);
		$fragchamber_door1_bl2.setColor (0, 1, 0);
		$fragchamber_door2_bl1.setColor (0, 1, 0);
		$fragchamber_door2_bl2.setColor (0, 1, 0);
		
		sys.wait (0.5);

		//trigger the NPC to leave
		sys.trigger ($fragchamber_npc_leave);

		//trigger control gui to reset it
		$guicon1.setGuiParm ("gui_parm8", 2);
		$guicon1.setGuiParm ("gui_parm9", 1);

		// keep the doors open for a few seconds
		float end_time = sys.getTime() + 7;
		while( sys.getTime() < end_time ) {
			sys.trigger( $chamber_door2a );
			sys.trigger( $chamber_door2b );
			sys.trigger( $chamber_door4a );
			sys.trigger( $chamber_door4b );
			sys.wait( 0.5 );
		}
	}

	/*--------------------------------------------------------------------
		
		F r a g c h a m b e r    scripting END
		
	--------------------------------------------------------------------*/


/* ***********************************************************************************

Please place non-init code and functions above these init functions

*********************************************************************************** */

	/*
	 Pre-init state. Define starting state of key entities
	*/
	
	void setup_objects() {
		g_fConveyDoorRefCount = 0;
		g_fWeldDoorRefCount = 0;
	}
	

	void init_world() {
		// -- Start Alphapuzzle
		thread SetupRotatingBridge();

		thread GlideLight1Loop();
		thread GlideLight2Loop();
		thread CargoObjectSequence();
		// -- End Alphapuzzle
	}
	
	void main() {
		cache_sounds();
		bind_objects();
		setup_objects();	
		init_world();
	}
}

//@doomscript-blueprint begin 6
//@source 9538F0FE
//@catalog 0C260740
//@node B832CE32-0 40 40
//@node 565244C8-0 330 40
//@node B97F72EB-0 610 40
//@node 93871FDD-0 890 40
//@node FC5F414E-0 1170 40
//@node 1D7DD181-0 1450 40
//@node 13C805AA-0 1730 40
//@node 843EACEF-0 2010 40
//@node 4313D303-0 2290 40
//@node C43DAEE1-0 2570 40
//@node 4C233DA7-0 40 40
//@node 4C5D3097-0 330 40
//@node 7EF2F5A0-0 610 40
//@node 7F5AAD51-0 40 40
//@node F967B380-0 330 40
//@node 15E8D062-0 40 40
//@node AB903AF9-0 330 40
//@node 25E90BEF-0 610 40
//@node 71AD7F7D-0 40 40
//@node E62374E4-0 330 40
//@node 3805CB8E-0 610 40
//@node B84CDDA7-0 890 40
//@node 1918C1E8-0 1170 40
//@node 6CA408E9-0 1450 40
//@node 6338339F-0 1730 40
//@node D27276D9-0 40 40
//@node 34220BEF-0 330 40
//@node 18F3AAF9-0 610 40
//@node 88565BBB-0 890 40
//@node 755A5C57-0 1170 40
//@node 5497DA01-0 1450 40
//@node 474E4D17-0 1730 40
//@node 7A5421A9-0 2010 40
//@node 16CD53B1-0 2290 40
//@node 27262911-0 2570 40
//@node 82CD7413-0 2850 40
//@node F36E2781-0 3130 40
//@node 2BCD0127-0 3410 40
//@node F73090A5-0 40 40
//@node 657A412C-0 330 40
//@node CA0F545A-0 610 40
//@node 5316712F-0 890 40
//@node C21F35DC-0 1170 40
//@node 5D2C3AB9-0 1450 40
//@node A2F37525-0 1730 40
//@node A8941378-0 2010 40
//@node D69A751F-0 2290 40
//@node 5293C185-0 2570 40
//@node 43CB0984-0 2850 40
//@node 8D2FEEA9-0 3130 40
//@node 3C7075A2-0 3410 40
//@node 2354F8C7-0 3690 40
//@node 75414DDF-0 3970 40
//@node 1BCD577A-0 4250 40
//@node CD8F5435-0 4530 40
//@node 59772947-0 4810 40
//@node 778B71FF-0 40 40
//@node 40B3D0B1-0 330 40
//@node DD7E5517-0 610 40
//@node D44FEA92-0 890 40
//@node 7D3E9C8D-0 1170 40
//@node 027595AC-0 1450 40
//@node D2061F38-0 1730 40
//@node 5ED039AD-0 2010 40
//@node D11A6446-0 2290 40
//@node 9F8CB264-0 2570 40
//@node 37372DD9-0 2850 40
//@node EDC25DBC-0 3130 40
//@node 488F2823-0 3410 40
//@node FB31C8BC-0 3690 40
//@node 077C04B2-0 3970 40
//@node F56A9E07-0 4250 40
//@node CF0235F4-0 4530 40
//@node 4F9EA946-0 4810 40
//@node 4341B39F-0 40 40
//@node 504661A5-0 330 40
//@node 29A5859B-0 610 40
//@node 62B07596-0 890 40
//@node F6B674F1-0 1170 40
//@node 43C76917-0 1450 40
//@node 2E6A187C-0 1730 40
//@node DD560681-0 2010 40
//@node 97FD719A-0 2290 40
//@node D5D4505F-0 2570 40
//@node 310FCF9D-0 2850 40
//@node F9908ED0-0 3130 40
//@node 84CF0C57-0 3410 40
//@node 483E800D-0 3690 40
//@node A1D0D9FE-0 3970 40
//@node 3AD72B93-0 4250 40
//@node 9F414430-0 4530 40
//@node A2986B15-0 4810 40
//@node 2F286BE4-0 40 40
//@node 139D30E4-0 330 40
//@node 8C937402-0 610 40
//@node 7573C957-0 890 40
//@node 809C9404-0 1170 40
//@node 5661D791-0 1450 40
//@node 191ED5ED-0 1730 40
//@node F32FB560-0 2010 40
//@node 6EE91B67-0 2290 40
//@node 63A2A0ED-0 2570 40
//@node 02FD978C-0 2850 40
//@node 62D62D51-0 3130 40
//@node CED8D26A-0 3410 40
//@node 832AFC8F-0 3690 40
//@node 75F7F3A7-0 3970 40
//@node AB977962-0 4250 40
//@node 1A8D92DD-0 4530 40
//@node 0A778BEF-0 4810 40
//@node C2341DD5-0 40 40
//@node 53BF44B8-0 330 40
//@node 29CE3450-0 610 40
//@node FE803A45-0 890 40
//@node 495325FB-0 1170 40
//@node B4892E3F-0 40 40
//@node 3DC5F865-0 330 40
//@node 67DB1FDD-0 610 40
//@node 00F3FEB2-0 890 40
//@node AE6FCD03-0 1170 40
//@node 9831B0F2-0 1450 40
//@node 67C80D40-0 1730 40
//@node B6AA0166-0 2010 40
//@node 49EB0E72-0 2290 40
//@node 93B8C272-0 2570 40
//@node 2B51A1F9-0 2850 40
//@node FFFA98F4-0 3130 40
//@node EAF6CD86-0 3410 40
//@node 3273EA78-0 3690 40
//@node A5B54EDB-0 3970 40
//@node 2BC6DC58-0 4250 40
//@node 991A0217-0 4530 40
//@node 8CA01304-0 4810 40
//@node 88DCC6FC-0 5090 40
//@node 04FEB615-0 5370 40
//@node 24B7EAAB-0 5650 40
//@node 32C2E1EE-0 5930 40
//@node B0642150-0 6210 40
//@node 49008D7E-0 6490 40
//@node 015F544B-0 6770 40
//@node 550D7297-0 7050 40
//@node 200D0DE6-0 7330 40
//@node B0642150-1 7610 40
//@node 1DCC8D3C-0 40 40
//@node 2EB73457-0 330 40
//@node 56B0C738-0 610 40
//@node 94FCDD49-0 890 40
//@node 37DDA95A-0 1170 40
//@node 63B263AE-0 1450 40
//@node CCEAF489-0 1730 40
//@node C22CEDE6-0 2010 40
//@node E34E077E-0 2290 40
//@node 80241B7B-0 2570 40
//@node FC93487F-0 2850 40
//@node 628B0BB6-0 3130 40
//@node 6CE41107-0 3410 40
//@node 4F838B3E-0 40 40
//@node 7EE9114C-0 330 40
//@node 60F80803-0 125 145
//@node B43BF412-0 610 200
//@node EBF3DCB6-0 890 200
//@node 2AFA8FF7-0 1170 200
//@node 2E873D13-0 1450 200
//@node 499ED4BD-0 1730 200
//@node 310D65E2-0 2010 200
//@node BF23D88D-0 2290 200
//@node 20F3003D-0 2570 200
//@node 925AA902-0 2850 200
//@node 38EDDF50-0 3130 200
//@node F6775EA0-0 3410 200
//@node 2BE448C8-0 3690 200
//@node 94EEDCA3-0 40 40
//@node B5C7522B-0 330 40
//@node 463D77B0-0 125 145
//@node E4B82124-0 610 200
//@node 1C23BA1B-0 890 200
//@node 7BF81B2B-0 1170 200
//@node 79CC30E4-0 1450 200
//@node 62E9FEAA-0 1730 200
//@node E7EE7FC6-0 2010 200
//@node 2C4E353E-0 2290 200
//@node 4569F54C-0 2570 200
//@node 73A28F00-0 2850 200
//@node 8F893A51-0 3130 40
//@node C0C6F0E3-0 2925 145
//@node E4B82124-1 3410 200
//@node 1C23BA1B-1 3690 200
//@node 7BF81B2B-1 3970 200
//@node 79CC30E4-1 4250 200
//@node 62E9FEAA-1 4530 200
//@node E7EE7FC6-1 4810 200
//@node 2C4E353E-1 5090 200
//@node 4569F54C-1 5370 200
//@node 73A28F00-1 5650 200
//@node A1121963-0 5930 40
//@node C60F5B44-0 5725 145
//@node E4B82124-2 6210 200
//@node 1C23BA1B-2 6490 200
//@node 7BF81B2B-2 6770 200
//@node 79CC30E4-2 7050 200
//@node 62E9FEAA-2 7330 200
//@node BB67FCE6-0 7610 200
//@node 01BB30CE-0 7890 200
//@node 4569F54C-2 8170 200
//@node 73A28F00-2 8450 200
//@node 7D92999D-0 8730 40
//@node 21110075-0 8525 145
//@node E4B82124-3 9010 200
//@node 1C23BA1B-3 9290 200
//@node 7BF81B2B-3 9570 200
//@node 79CC30E4-3 9850 200
//@node 62E9FEAA-3 10130 200
//@node 5328DB8B-0 10410 200
//@node 57B77755-0 10690 200
//@node 4569F54C-3 10970 200
//@node 73A28F00-3 11250 200
//@node 2B34B296-0 40 40
//@node 2311CEDB-0 330 40
//@node CE67546F-0 610 40
//@node 260C396C-0 40 40
//@node 237AEC26-0 330 40
//@node D0E72BCC-0 125 145
//@node 973ACCD1-0 -80 145
//@node DCC69859-0 610 200
//@node 8C50A1FB-0 405 305
//@node 9EAB8AA1-0 200 305
//@node AD54E745-0 890 200
//@node E4BAABC0-0 665 305
//@node B57D43C5-0 460 405
//@node 3B6C54C5-0 1170 200
//@node 300ABF48-0 965 305
//@node 40473994-0 1450 200
//@node 8B67C58E-0 1730 200
//@node D517AAAF-0 1525 305
//@node 7C1FBB5E-0 1320 305
//@node 74F468BE-0 2010 200
//@node 6E62BDF9-0 1805 300
//@node 820E9ADF-0 2290 200
//@node 8CF03C91-0 2570 200
//@node B583EBD4-0 2365 392
//@node F9D80742-0 2160 392
//@node 0531448D-0 2850 200
//@node 22C4F1B9-0 3130 200
//@node 8E85F955-0 3410 200
//@node E9895531-0 3690 200
//@node 81A47081-0 3485 305
//@node AB21675D-0 3280 305
//@node FA79DB42-0 3970 200
//@node F341E51E-0 3745 305
//@node 8598AC31-0 3540 405
//@node 919F1B0F-0 4250 200
//@node FB885EE7-0 4045 305
//@node 76B6D922-0 4530 360
//@node 8CA43D94-0 4810 200
//@node BD52D3E7-0 4605 305
//@node 3E2E96B2-0 4400 305
//@node FA79DB42-1 5090 200
//@node 62F45119-0 4865 305
//@node 8DE14DEB-0 4660 405
//@node 919F1B0F-1 5370 200
//@node EA91529E-0 5165 305
//@node 76B6D922-1 5650 360
//@node 9261FE33-0 40 40
//@node 7ECB2D27-0 330 40
//@node 78AB6D80-0 125 145
//@node 8FAFED67-0 610 40
//@node D813DD81-0 385 145
//@node 70AFA8F1-0 180 245
//@node 2F091945-0 890 40
//@node F00267FF-0 685 145
//@node E744D635-0 1170 40
//@node B9B1B890-0 945 145
//@node 22E0FF50-0 740 245
//@node 44C39BBE-0 1450 40
//@node 82D5565C-0 1730 40
//@node 79C82B5D-0 2010 40
//@node 1EA048EB-0 2290 40
//@node 2607E017-0 2570 40
//@node 743BC38E-0 2850 40
//@node 4CC1058F-0 3130 40
//@node 1EF4504C-0 2925 232
//@node 44946346-0 3410 40
//@node 565337BE-0 3690 40
//@node AAAFE5C0-0 3485 232
//@node C841FA88-0 3970 40
//@node 97B457CA-0 3765 140
//@node EF1D4662-0 40 40
//@node 5BB4499C-0 330 40
//@node FF28B837-0 610 40
//@node BCA6CBE3-0 890 40
//@node C8BDDBA3-0 1170 40
//@node 0036873A-0 1450 40
//@node 72022ADA-0 1730 40
//@node 6A3BA866-0 2010 40
//@node 2B436E37-0 2290 40
//@node 6623DAD5-0 2570 40
//@node F6796B59-0 2850 40
//@node 39FF6140-0 3130 40
//@node D3CDE124-0 3410 40
//@node 276ED796-0 3690 40
//@node CC4AAC3B-0 3970 40
//@node 04D0AA3F-0 4250 40
//@node 8C548FD1-0 4530 40
//@node 36CA42BC-0 4810 40
//@node 3D7F16F6-0 5090 40
//@node EE94B60B-0 40 40
//@node 69297E04-0 330 40
//@node 509F4D31-0 125 145
//@node 629344BF-0 610 40
//@node 37585362-0 385 145
//@node 8503A269-0 180 245
//@node 1A754130-0 890 40
//@node 3BCB9861-0 1170 40
//@node 5839F3C6-0 965 145
//@node 629344BF-1 1450 40
//@node 0938E22D-0 1225 145
//@node E91D0FE3-0 1020 245
//@node 1A754130-1 1730 40
//@node 59F654A5-0 2010 40
//@node 70DC2D15-0 1805 145
//@node DB7AE8E0-0 1600 145
//@node CDE5C3E9-0 2290 200
//@node 130A1FA5-0 2085 305
//@node 3A3E29C4-0 1880 305
//@node 629344BF-2 2570 200
//@node A4DD079C-0 2345 305
//@node 94C91EDE-0 2140 405
//@node F7C0CB55-0 2850 200
//@node 24191263-0 2645 305
//@node 464BD9F7-0 2440 305
//@node 8836E412-0 3130 200
//@node 1A754130-2 3410 200
//@node F1232998-0 40 40
//@node 78B4A82D-0 330 40
//@node 58E412C0-0 125 145
//@node B0AA9546-0 -80 145
//@node 922E463A-0 610 200
//@node 8121CF4A-0 405 300
//@node 6A2D6453-0 40 40
//@node 2A6062BA-0 330 40
//@node 77BFFC17-0 125 145
//@node A1A6BF6B-0 -80 145
//@node 87C2E904-0 610 200
//@node 4918A34A-0 385 305
//@node F69A9EA1-0 180 405
//@node ACE3828C-0 -25 405
//@node B719AFEA-0 890 200
//@node 93C38A5C-0 665 305
//@node 25134BEF-0 460 405
//@node 20AB9578-0 255 405
//@node 42E48C6C-0 1170 200
//@node 0CC2A031-0 965 300
//@node CC9119C8-0 1450 200
//@node BC94E19F-0 1245 305
//@node 3122293F-0 1730 200
//@node 0EEDD0E0-0 1505 305
//@node 41EA7CBC-0 1300 405
//@node DFA6AF5E-0 1095 405
//@node 42E48C6C-1 2010 200
//@node 5CEA5B12-0 1805 300
//@node 75AABD12-0 2290 200
//@node EE16077B-0 2065 305
//@node CDAE56CB-0 1860 405
//@node 8C1937AC-0 1655 405
//@node 42E48C6C-2 2570 200
//@node 07CE1A3F-0 2365 300
//@node 0720BDE4-0 2850 200
//@node E2582026-0 3130 200
//@node B78909DB-0 3410 200
//@node A6114A85-0 3205 300
//@node F27A3FC7-0 3690 200
//@node C01DAC3B-0 3465 305
//@node F021D65A-0 3260 405
//@node 87A673CA-0 3055 405
//@node 42E48C6C-3 3970 200
//@node 35276718-0 3765 300
//@node 01A85C6D-0 4250 200
//@node 7BEA15E6-0 4530 200
//@node 9640230A-0 4305 305
//@node 7B108C31-0 4100 405
//@node DDE1797A-0 3895 405
//@node 42E48C6C-4 4810 200
//@node 30FFBBAD-0 4605 300
//@node 01A85C6D-1 5090 200
//@node 95EB8310-0 40 40
//@node 7BD598F7-0 330 40
//@node 704010F2-0 610 40
//@node 37EFA96B-0 890 40
//@node D75EC122-0 40 40
//@node 0465474F-0 330 40
//@node AD2C19D6-0 40 40
//@node B825094F-0 330 40
//@node FA1FD243-0 610 40
//@node 994FF24F-0 40 40
//@node 0E96F766-0 330 40
//@node AA37BE9F-0 105 145
//@node 458CBD70-0 -100 245
//@node 40FCF613-0 610 40
//@node AB10481F-0 385 145
//@node DD1B7ADD-0 890 40
//@node 1B52915F-0 665 145
//@node 2FE9ABC4-0 460 245
//@node 859F10E5-0 1170 40
//@node 0770BBC3-0 945 145
//@node D4EC2C28-0 740 245
//@node 52C1BAC4-0 1450 40
//@node D1B69D7D-0 1225 145
//@node D6C4316E-0 1020 245
//@node B5A34394-0 1730 40
//@node D2B7F3CD-0 1505 145
//@node EF55BB61-0 1300 245
//@node CE001AE4-0 2010 40
//@node F2EDE9A1-0 2290 40
//@node F99794A8-0 2570 40
//@node 3CD504E1-0 2850 40
//@node D1B86BBD-0 3130 40
//@node 6BFFEB09-0 3410 40
//@node D07DA872-0 3690 40
//@node 535B2729-0 3970 40
//@node C7F2BC37-0 3765 140
//@node B71836C1-0 4250 40
//@node E1FCB5D5-0 4530 40
//@node A1DD1282-0 4810 40
//@node 65EF70EC-0 4605 140
//@node 0FC43B78-0 5090 40
//@node A67EFF34-0 4885 140
//@node 5B9EE408-0 5370 40
//@node 18C07384-0 5650 40
//@node 5F058A34-0 5930 40
//@node 5AB83731-0 6210 40
//@node 39C4B438-0 6005 140
//@node F99794A8-1 6490 40
//@node EB4CC90C-0 6770 40
//@node E06547F8-0 7050 40
//@node 2261BAAC-0 7330 40
//@node 9DF058BA-0 7610 40
//@node 535B2729-1 7890 40
//@node 833AB63C-0 7685 140
//@node 0EB30BFD-0 8170 40
//@node D1B86BBD-1 8450 40
//@node 2261BAAC-1 8730 40
//@node 086B1ADE-0 9010 40
//@node 535B2729-2 9290 40
//@node 4F633619-0 9085 140
//@node EB4CC90C-1 9570 40
//@node D1B86BBD-2 9850 40
//@node 6BFFEB09-1 10130 40
//@node F8F6FC6C-0 10410 40
//@node 535B2729-3 10690 40
//@node 2DF7BA3E-0 10485 140
//@node 0FC43B78-1 10970 40
//@node 57690393-0 10765 140
//@node 18C07384-1 11250 40
//@node 66367280-0 11530 40
//@node 5AB83731-1 11810 40
//@node 32F46AEB-0 11605 140
//@node 5B9EE408-1 12090 40
//@node B71836C1-1 12370 40
//@node 97C6003F-0 12650 40
//@node A1DD1282-1 12930 40
//@node 001863F9-0 12725 140
//@node F99794A8-2 13210 40
//@node 602B0625-0 13490 40
//@node E06547F8-1 13770 40
//@node 6BFFEB09-2 14050 40
//@node BDCDDF34-0 14330 40
//@node 535B2729-4 14610 40
//@node 39954F73-0 14405 140
//@node EF26CAC0-0 14890 40
//@node E06547F8-2 15170 40
//@node 6BFFEB09-3 15450 40
//@node 8A96584A-0 15730 40
//@node 535B2729-5 16010 40
//@node 7BFBE868-0 15805 140
//@node 87A0C73B-0 16290 40
//@node E06547F8-3 16570 40
//@node 2261BAAC-2 16850 40
//@node 1308280E-0 17130 40
//@node 535B2729-6 17410 40
//@node 2387D455-0 17205 140
//@node D45430FC-0 17690 40
//@node 7CC4C3FF-0 17970 40
//@node E45F28BB-0 18250 40
//@node 3252E536-0 18530 40
//@node 5732DAF9-0 18810 40
//@node 58969D25-0 19090 40
//@node 9226026E-0 19370 40
//@node 0E01F2EB-0 19650 40
//@node 111A447C-0 19930 40
//@node D1B86BBD-3 20210 40
//@node 2261BAAC-3 20490 40
//@node EFE6F03D-0 20770 40
//@node 535B2729-7 21050 40
//@node 234A57DA-0 20845 140
//@node FAFBD573-0 21330 40
//@node 480E4968-0 21610 40
//@node E4F6CF16-0 21890 40
//@node A632655F-0 22170 40
//@node 42E3BB38-0 22450 40
//@node CC9BE272-0 22730 40
//@node 9226026E-1 23010 40
//@node F43A8B24-0 23290 40
//@node 87A0C73B-1 23570 40
//@node D1B86BBD-4 23850 40
//@node 6BFFEB09-4 24130 40
//@node 8A6A2CF4-0 24410 40
//@node 535B2729-8 24690 40
//@node 40C762EF-0 24485 140
//@node EF26CAC0-1 24970 40
//@node E06547F8-4 25250 40
//@node 6BFFEB09-5 25530 40
//@node D286975F-0 25810 40
//@node 535B2729-9 26090 40
//@node 31299374-0 25885 140
//@node BD31596E-0 26370 40
//@node 6902B19D-0 26650 40
//@node E06547F8-5 26930 40
//@node 2261BAAC-4 27210 40
//@node 16068070-0 27490 40
//@node 535B2729-10 27770 40
//@node 4B9B299E-0 27565 140
//@node 26AB3185-0 28050 40
//@node 2E235EC6-0 40 40
//@node 2B338BB4-0 330 40
//@node 8A9AC0AC-0 125 145
//@node 31F65D42-0 610 200
//@node A8D0CC08-0 890 200
//@node 0D75E033-0 1170 200
//@node A8D0CC08-1 1450 200
//@node FF5C6638-0 1730 200
//@node A8D0CC08-2 2010 200
//@node D34A9809-0 2290 200
//@node A8D0CC08-3 2570 200
//@node 53136886-0 2850 200
//@node A8D0CC08-4 3130 200
//@node 48659467-0 3410 200
//@node A8D0CC08-5 3690 200
//@node 63109CFC-0 40 40
//@node F66E31ED-0 330 40
//@node AB79A162-0 125 145
//@node 0DE733BC-0 -80 145
//@node 23DFEC42-0 610 200
//@node 70C9707C-0 385 305
//@node 45518FEB-0 180 405
//@node 2A4B5290-0 -25 405
//@node D5648194-0 890 200
//@node E784C538-0 1170 200
//@node 685964D4-0 945 305
//@node 4807AA29-0 740 405
//@node A508D2AC-0 535 405
//@node D5648194-1 1450 200
//@node D0B23611-0 1730 200
//@node 00DC0BF0-0 1505 305
//@node 6E2FA9BF-0 1300 405
//@node 3E991695-0 1095 405
//@node D5648194-2 2010 200
//@node 19BD15B0-0 2290 200
//@node F07516FB-0 2065 305
//@node B1F5C404-0 1860 405
//@node 8DCFFF2D-0 1655 405
//@node D5648194-3 2570 200
//@node 3D1B6AB1-0 2850 200
//@node EDBE4DB7-0 2625 305
//@node 29347D8D-0 2420 405
//@node D51B2FEF-0 2215 405
//@node D5648194-4 3130 200
//@node BAB336E4-0 3410 200
//@node 5C23E309-0 3185 305
//@node 6729F677-0 2980 405
//@node 864803C6-0 2775 405
//@node D5648194-5 3690 200
//@node 596C5687-0 40 40
//@node 12169028-0 330 40
//@node D98F79FF-0 105 145
//@node C6A78BD9-0 -100 245
//@node AF58B75E-0 610 40
//@node 9620F24B-0 385 145
//@node 177B39F7-0 180 245
//@node 251D65AC-0 890 40
//@node 5EA0AE61-0 685 140
//@node 55E6DF11-0 1170 40
//@node 7B654F09-0 945 145
//@node 6892E7F6-0 740 245
//@node 251D65AC-1 1450 40
//@node 8CAD6002-0 1245 140
//@node 9FC1B3B0-0 1730 40
//@node 161AA24E-0 1505 145
//@node FAC53967-0 1300 245
//@node 251D65AC-2 2010 40
//@node 8021E62F-0 1805 140
//@node C558F2E0-0 2290 40
//@node 9784DBD8-0 2085 145
//@node 65E4ADDD-0 2570 40
//@node 1BE9479D-0 2345 145
//@node 81F6A8DE-0 2140 245
//@node 251D65AC-3 2850 40
//@node 20C3C788-0 2645 140
//@node C558F2E0-1 3130 40
//@node 16D5EE6D-0 2925 145
//@node AA436F2F-0 3410 40
//@node 6830E62F-0 3185 145
//@node 161D6D39-0 2980 245
//@node 251D65AC-4 3690 40
//@node CBC9775D-0 3485 140
//@node B2B64DAD-0 3970 40
//@node 65E4ADDD-1 4250 40
//@node 5F884352-0 4025 145
//@node D739BEC6-0 3820 245
//@node 766300A4-0 4530 40
//@node 73E4B633-0 4810 40
//@node 7F3E571B-0 5090 40
//@node 6236296C-0 4885 140
//@node 6D2732F1-0 40 40
//@node B0FBB08C-0 330 40
//@node 0384F783-0 610 40
//@node DED6E325-0 890 40
//@node D229462C-0 1170 40
//@node D0DA2A9B-0 1450 40
//@node E516D736-0 1730 40
//@node FC4B3D4C-0 2010 40
//@node 526F4191-0 2290 40
//@node BE9853AF-0 2570 40
//@node 11526B69-0 40 40
//@node CB9B4EC7-0 330 40
//@node B1DE1907-0 105 145
//@node E946C6C3-0 -100 245
//@node 935B5F37-0 610 40
//@node C6A3C022-0 385 145
//@node A367CE94-0 180 245
//@node 5A1AE1D1-0 890 40
//@node 912A4351-0 665 145
//@node 2B930953-0 460 245
//@node 4361808B-0 1170 40
//@node A87EABCE-0 945 145
//@node D8700A72-0 740 245
//@node 810570FA-0 1450 40
//@node 6EBCA53E-0 1225 145
//@node 664BE46B-0 1020 245
//@node 99247F1E-0 1730 40
//@node 80A8F9DB-0 1505 145
//@node E603B330-0 1300 245
//@node 39F8CF15-0 2010 40
//@node C67634D9-0 1785 145
//@node 392A9BEC-0 1580 245
//@node B8436E31-0 2290 40
//@node 64CA0996-0 2065 145
//@node 3EAEF201-0 1860 245
//@node B5F8E71E-0 2570 40
//@node C0648945-0 2345 145
//@node 978D5D6E-0 2140 245
//@node 819BE307-0 2850 40
//@node 998D52E1-0 2625 145
//@node A7AF6402-0 2420 245
//@node 8918CCD9-0 3130 40
//@node 1C916197-0 2905 145
//@node 88262F60-0 2700 245
//@node 774C8C50-0 3410 40
//@node 20AA7E0F-0 3185 145
//@node 40C30FCF-0 2980 245
//@node CEFC802A-0 3690 40
//@node E93FD9C5-0 3485 140
//@node 1B751C7E-0 3970 40
//@node 61EC3DA1-0 4250 40
//@node F10AE67E-0 4530 40
//@node E246DB98-0 4810 40
//@node 27A07D97-0 4605 140
//@node E97CA55A-0 5090 40
//@node 004897C6-0 5370 40
//@node 267A7CBC-0 5165 140
//@node B0A76BB5-0 5650 40
//@node D73E4F9A-0 5930 40
//@node EFC7C673-0 6210 40
//@node C5EC30C3-0 6490 40
//@node 3C917971-0 6285 140
//@node 807AC502-0 6770 40
//@node 004897C6-1 7050 40
//@node D66DFE81-0 6845 140
//@node C046437B-0 7330 40
//@node B410846A-0 7610 40
//@node A99AF35B-0 7890 40
//@node 5E9E8C55-0 8170 40
//@node F1F75359-0 7965 140
//@node 10F73F4A-0 8450 40
//@node EFC1F511-0 8730 40
//@node C5AC505A-0 8525 140
//@node 75634565-0 9010 40
//@node F50E18E0-0 9290 40
//@node 23DF2EC3-0 9085 140
//@node 04ED4568-0 9570 40
//@node AB9EF67E-0 9850 40
//@node 38D16CD0-0 9645 140
//@node DBE1348C-0 10130 40
//@node 33D4E486-0 10410 40
//@node 3699F4D8-0 10205 140
//@node BAA527B1-0 10690 40
//@node F50E18E0-1 10970 40
//@node D2698F9A-0 10765 140
//@node 7B9C44A5-0 11250 40
//@node 1A52C2F5-0 11530 40
//@node 0FEE8074-0 11325 140
//@node B410846A-1 11810 40
//@node 5E9E8C55-1 12090 40
//@node 98F23EAC-0 11885 140
//@node CDBB66B9-0 12370 40
//@node EFC1F511-1 12650 40
//@node A66B9897-0 12445 140
//@node F45BF769-0 12930 40
//@node B2DCABFE-0 13210 40
//@node 27D2A365-0 13490 40
//@node 1C3EC5B3-0 13770 40
//@node 036BB80D-0 14050 40
//@node 09D0C49B-0 13845 140
//@node DB57EB4D-0 14330 40
//@node D73E4F9A-1 14610 40
//@node EFC7C673-1 14890 40
//@node C5EC30C3-1 15170 40
//@node 7A81131C-0 14965 140
//@node 85448B34-0 15450 40
//@node 004897C6-2 15730 40
//@node B016F862-0 15525 140
//@node 1B751C7E-1 16010 40
//@node 61EC3DA1-1 16290 40
//@node F10AE67E-1 16570 40
//@node E246DB98-1 16850 40
//@node 3E2F1982-0 16645 140
//@node 41514B63-0 17130 40
//@node 004897C6-3 17410 40
//@node B1D18187-0 17205 140
//@node F45BF769-1 17690 40
//@node B2DCABFE-1 17970 40
//@node E8B8DC76-0 18250 40
//@node 326E19E6-0 18530 40
//@node 036BB80D-1 18810 40
//@node 14E5995E-0 18605 140
//@node DF7FE59E-0 40 40
//@node A75EC121-0 330 40
//@node 2E3D312B-0 125 145
//@node 97601DCD-0 -80 145
//@node 5B25CAE3-0 610 200
//@node 7DBBCE38-0 890 200
//@node 6BA840BC-0 1170 40
//@node 36027E0F-0 965 145
//@node 48DCE75C-0 760 145
//@node EE4EE72A-0 40 40
//@node 1E5A2176-0 330 40
//@node 1CDEDB97-0 125 145
//@node 798A0AA0-0 -80 145
//@node 06C058C5-0 610 40
//@node 46C98670-0 405 145
//@node CF88B7C4-0 200 145
//@node 93171679-0 890 200
//@node F6F0A828-0 1170 200
//@node 27F6EB3A-0 40 40
//@node 09E9EBF5-0 330 40
//@node 3CE7E607-0 125 145
//@node AE73847D-0 -80 145
//@node 7E2A5C23-0 610 200
//@node 3BAF3F78-0 890 200
//@node 71717340-0 1170 40
//@node CA1343E3-0 965 145
//@node B649CBFC-0 760 145
//@node BD8168EE-0 40 40
//@node C1720D96-0 330 40
//@node B66419E5-0 125 145
//@node 9D02D0B2-0 -80 145
//@node 1E7476F9-0 610 40
//@node A09BCEBD-0 405 145
//@node CECC5279-0 200 145
//@node C02B25A9-0 890 200
//@node 8CFD6DD8-0 1170 200
//@node 27B819F0-0 40 40
//@node A4F496B1-0 330 40
//@node BC41A1DE-0 610 40
//@node 689119C1-0 890 40
//@node 52CB869E-0 1170 40
//@node 6F4609E5-0 1450 40
//@node 43B11F78-0 1730 40
//@node 92BB5E12-0 2010 40
//@node 5B78BF4B-0 2290 40
//@node 65FCD21D-0 2570 40
//@node B1CD7890-0 2850 40
//@node 849A05D5-0 3130 40
//@node 1DF842D6-0 3410 40
//@node 2678508F-0 3690 40
//@node A4F496B1-1 3970 40
//@node BC41A1DE-1 4250 40
//@node 689119C1-1 4530 40
//@node 52CB869E-1 4810 40
//@node 6F4609E5-1 5090 40
//@node 38D33C86-0 5370 40
//@node 92BB5E12-1 5650 40
//@node 5B78BF4B-1 5930 40
//@node 56CA12B4-0 40 40
//@node B8ED02D9-0 330 40
//@node 3CFA06E3-0 610 40
//@node CE52BA69-0 890 40
//@node 46AA5986-0 1170 40
//@node C9DA4AA8-0 1450 40
//@node E54DD4F2-0 1730 40
//@node 180CE07A-0 2010 40
//@node 530CEF83-0 2290 40
//@node CCE27505-0 2570 40
//@node 1C6387F8-0 2850 40
//@node BCD2F96D-0 3130 40
//@node F7CDBB9E-0 3410 40
//@node 198C9A87-0 3690 40
//@node B8ED02D9-1 3970 40
//@node 3CFA06E3-1 4250 40
//@node CE52BA69-1 4530 40
//@node 46AA5986-1 4810 40
//@node C9DA4AA8-1 5090 40
//@node CDC45028-0 5370 40
//@node 180CE07A-1 5650 40
//@node 530CEF83-1 5930 40
//@node FD0A61A7-0 40 40
//@node 88C7FF72-0 330 40
//@node 9731617A-0 610 40
//@node 7590C025-0 890 40
//@node C3A84AE2-0 1170 40
//@node 17488C69-0 1450 40
//@node AD799AD4-0 1730 40
//@node 96841868-0 2010 40
//@node 4BDCCABE-0 2290 40
//@node 2C095F86-0 2570 40
//@node 887AA605-0 2850 40
//@node DED5BD0C-0 3130 40
//@node 513B6CCD-0 3410 40
//@node 375D86CA-0 3690 40
//@node 88C7FF72-1 3970 40
//@node 981D20EC-0 4250 40
//@node 7590C025-1 4530 40
//@node A7F72B0F-0 4810 40
//@node 62207652-0 5090 40
//@node 96841868-1 5370 40
//@node 4BDCCABE-1 5650 40
//@node 9F762309-0 40 40
//@node C99ED720-0 330 40
//@node 24E00449-0 610 40
//@node E59944FF-0 890 40
//@node D26F7968-0 1170 40
//@node 11B1B7B6-0 1450 40
//@node 99A92038-0 1730 40
//@node 15FDF6F6-0 2010 40
//@node A721FB74-0 2290 40
//@node 991F6850-0 2570 40
//@node 5EFE3E0F-0 2850 40
//@node DB9954D2-0 3130 40
//@node F4DF503B-0 3410 40
//@node FB778AC4-0 3690 40
//@node C99ED720-1 3970 40
//@node 24E00449-1 4250 40
//@node E59944FF-1 4530 40
//@node D26F7968-1 4810 40
//@node 11B1B7B6-1 5090 40
//@node 55F9184A-0 5370 40
//@node 15FDF6F6-1 5650 40
//@node A721FB74-1 5930 40
//@node EF2C90B4-0 40 40
//@node EF1C9B50-0 330 40
//@node 53DE2B92-0 610 40
//@node 40938A3A-0 405 145
//@node C50016CB-0 890 200
//@node 30DD4E0A-0 1170 200
//@node 4CD19E32-0 1450 200
//@node C61A3C09-0 1730 200
//@node F8DA9A8A-0 2010 200
//@node 3D47AF29-0 2290 200
//@node 8CFF9531-0 2570 200
//@node 7BFDD4D0-0 2850 200
//@node E9D6BF35-0 3130 200
//@node CB9F86EB-0 2905 305
//@node 8933802F-0 3410 200
//@node A68F42FB-0 3205 305
//@node 2640477F-0 3000 305
//@node 70EC4E37-0 3690 360
//@node A0F05D87-0 3970 360
//@node 75219DB4-0 4250 360
//@node 235D9EEC-0 4530 360
//@node 2C10900C-0 4810 360
//@node B4362204-0 5090 360
//@node A92A887D-0 5370 360
//@node 8F85CA11-0 5650 360
//@node 0FF4D798-0 5930 360
//@node 2FC4E028-0 6210 360
//@node 8944B7CA-0 6490 360
//@node 7544FF92-0 6770 360
//@node A709B644-0 7050 360
//@node 29725FBC-0 7330 360
//@node DFBCD3D8-0 7610 360
//@node A0254DE4-0 7890 360
//@node 7BEDEF26-0 8170 360
//@node E9D6BF35-1 8450 360
//@node 02DD649A-0 8225 465
//@node 8933802F-1 8730 360
//@node 9DB8E904-0 8525 465
//@node 4A666F78-0 8320 465
//@node 21978727-0 9010 520
//@node 91E38890-0 9290 520
//@node 85ACA3A1-0 9570 520
//@node 148301D7-0 9850 360
//@node 04394629-0 9645 465
//@node 3D78929C-0 9440 465
//@node 40136E0A-0 10130 520
//@node 91E38890-1 10410 520
//@node 3C106B04-0 10690 520
//@node 21978727-1 10970 520
//@node EB2EAAA2-0 11250 520
//@node 6B022F3F-0 11810 520
//@node 21978727-2 12090 520
//@node 40136E0A-1 12370 520
//@node 91E38890-2 12650 520
//@node D161A7E7-0 12930 520
//@node 148301D7-1 13210 200
//@node 02D9500A-0 13005 305
//@node 9D71D173-0 12800 305
//@node 70EC4E37-1 13490 360
//@node A0F05D87-1 13770 360
//@node 75219DB4-1 14050 360
//@node 235D9EEC-1 14330 360
//@node 2C10900C-1 14610 360
//@node B4362204-1 14890 360
//@node A92A887D-1 15170 360
//@node 8F85CA11-1 15450 360
//@node 1402B0DE-0 15730 360
//@node 83FA1C2E-0 16010 360
//@node ED3C21B4-0 16290 360
//@node 2AE3F91C-0 16570 360
//@node 23ACA65A-0 16850 360
//@node 3F8DD7B2-0 17130 360
//@node FADF3976-0 17410 360
//@node D87515FA-0 17690 360
//@node 7BEDEF26-1 17970 360
//@node E9D6BF35-2 18250 360
//@node 58050B89-0 18025 465
//@node 8933802F-2 18530 360
//@node B479E00D-0 18325 465
//@node E5895441-0 18120 465
//@node 87BFBDBD-0 18810 520
//@node 4E1DA72C-0 19090 520
//@node 85ACA3A1-1 19370 520
//@node 148301D7-2 19650 360
//@node BC134D07-0 19445 465
//@node 73001E56-0 19240 465
//@node 40136E0A-2 19930 520
//@node 4E1DA72C-1 20210 520
//@node 3C106B04-1 20490 520
//@node 87BFBDBD-1 20770 520
//@node EB2EAAA2-1 21050 520
//@node 6B022F3F-1 21610 520
//@node 87BFBDBD-2 21890 520
//@node 40136E0A-3 22170 520
//@node 4E1DA72C-2 22450 520
//@node D161A7E7-1 22730 520
//@node 70EC4E37-2 23290 360
//@node A0F05D87-2 23570 360
//@node 75219DB4-2 23850 360
//@node 235D9EEC-2 24130 360
//@node 2C10900C-2 24410 360
//@node B4362204-2 24690 360
//@node A92A887D-2 24970 360
//@node 8F85CA11-2 25250 360
//@node 0FF4D798-1 25530 360
//@node 2FC4E028-1 25810 360
//@node 8944B7CA-1 26090 360
//@node 7544FF92-1 26370 360
//@node 23ACA65A-1 26650 360
//@node 3F8DD7B2-1 26930 360
//@node FADF3976-1 27210 360
//@node D87515FA-1 27490 360
//@node 7BEDEF26-2 27770 360
//@node E9D6BF35-3 28050 360
//@node 72CC4080-0 27825 465
//@node 8933802F-3 28330 360
//@node 7B9DB1EE-0 28125 465
//@node 163DEBE2-0 27920 465
//@node 21978727-3 28610 520
//@node 40136E0A-4 28890 520
//@node 4E1DA72C-3 29170 520
//@node 0343151A-0 29450 520
//@node 148301D7-3 29730 360
//@node 8120C220-0 29525 465
//@node 6E8A97B5-0 29320 465
//@node 40136E0A-5 30010 520
//@node 4E1DA72C-4 30290 520
//@node 3C106B04-2 30570 520
//@node 21978727-4 30850 520
//@node EB2EAAA2-2 31130 520
//@node 6B022F3F-2 31690 520
//@node 21978727-5 31970 520
//@node 40136E0A-6 32250 520
//@node 4E1DA72C-5 32530 520
//@node D161A7E7-2 32810 520
//@node 6A272E38-0 40 40
//@node 81FAD1A5-0 330 40
//@node 08C34F2D-0 610 40
//@node AA28F899-0 890 40
//@node 3BD37591-0 1170 40
//@node A5972162-0 1450 40
//@node 43BB68CE-0 40 40
//@node 96F1FBF8-0 330 40
//@node CC3ABC33-0 610 40
//@node C451399C-0 890 40
//@node 8A6BB1E8-0 1170 40
//@node 226AE10D-0 1450 40
//@node 541CDA56-0 1730 40
//@node AC819BB5-0 2010 40
//@node 5B70A268-0 40 40
//@node BA77187E-0 330 40
//@node A0FE59A1-0 610 40
//@node 301D027E-0 890 40
//@node 5D26AEEF-0 1170 40
//@node 4F348D2C-0 1450 40
//@node 6E8ADA5E-0 1730 40
//@node 80A5AD63-0 2010 40
//@node FB2ABC79-0 40 40
//@node EEB79953-0 330 40
//@node D29A11F2-0 125 145
//@node 92FE8232-0 610 200
//@node D1FCEA22-0 890 200
//@node BFA2A544-0 1170 200
//@node D3AE7C2E-0 1450 200
//@node 6B272FCB-0 40 40
//@node A475FF96-0 40 40
//@node C88C635F-0 330 40
//@node 1A464F91-0 610 40
//@node 80FDE417-0 890 40
//@node 4D28A996-0 1170 40
//@node 41DB7427-0 1450 40
//@node F22C2DEA-0 1730 40
//@node 8B26B2E2-0 2010 40
//@node 2516EFAF-0 2290 40
//@node D1CB0DBB-0 2570 40
//@node FD885CB9-0 2850 40
//@node DD924711-0 3130 40
//@node 801B9CA9-0 3410 40
//@node 1AA66AAE-0 3690 40
//@node 9B049AC4-0 3970 40
//@node 7493A7AD-0 4250 40
//@node F4B80035-0 4530 40
//@node 32907D79-0 4810 40
//@node 2051CF1A-0 5090 40
//@node 255AD3F7-0 5370 40
//@node F40AE51E-0 5650 40
//@node 810B039E-0 5930 40
//@node A56F9028-0 6210 40
//@node 54ECB30F-0 6490 40
//@node 960E5959-0 6770 40
//@node 7B7CB4B9-0 7050 40
//@node 25A105BD-0 7330 40
//@node A8E68042-0 7610 40
//@node B4A5F8D8-0 7890 40
//@node A4809766-0 8170 40
//@node 70530504-0 8450 40
//@node 2C58FD91-0 8730 40
//@node DF6BB210-0 9010 40
//@node 1FC22C1F-0 9290 40
//@node 7645D992-0 9570 40
//@node 8A6FF99E-0 9850 40
//@node E5E2CF25-0 10130 40
//@node AB7918E1-0 10410 40
//@node DFDD15BE-0 10690 40
//@node B008E624-0 10970 40
//@node 1003EBAF-0 11250 40
//@node AE0895D6-0 11530 40
//@node 02DEA507-0 11810 40
//@node 5D8CE73B-0 12090 40
//@node 4F87D90F-0 12370 40
//@node 776F5B65-0 12650 40
//@node 234F3D66-0 12930 40
//@node A0F1B99B-0 13210 40
//@node FB1D9859-0 13490 40
//@node DD09139F-0 13770 40
//@node FF04BF88-0 14050 40
//@node C144F5E3-0 14330 40
//@node 1665CCA5-0 14610 40
//@node 369590E4-0 14890 40
//@node 8B4B253E-0 15170 40
//@node B048EDA4-0 15450 40
//@node 3C205487-0 15730 40
//@node A0F1B99B-1 16010 40
//@node 18D66674-0 16290 40
//@node CD7AF0A8-0 16085 145
//@node 776F5B65-1 16570 200
//@node 234F3D66-1 16850 200
//@node DFDD15BE-1 17130 200
//@node B008E624-1 17410 200
//@node 1003EBAF-1 17690 200
//@node AE0895D6-1 17970 200
//@node 02DEA507-1 18250 200
//@node 5D8CE73B-1 18530 200
//@node 4F87D90F-1 18810 200
//@node 776F5B65-2 19090 200
//@node 234F3D66-2 19370 200
//@node A0F1B99B-2 19650 200
//@node B048EDA4-1 19930 200
//@node 3C205487-1 20210 200
//@node FB1D9859-1 20490 200
//@node DD09139F-1 20770 200
//@node FF04BF88-1 21050 200
//@node C144F5E3-1 21330 200
//@node 1665CCA5-1 21610 200
//@node 369590E4-1 21890 200
//@node 8B4B253E-1 22170 200
//@node B048EDA4-2 22450 200
//@node 3C205487-2 22730 200
//@node A0F1B99B-3 23010 200
//@node 7127393D-0 40 40
//@node 07B6B66D-0 330 40
//@node 36BD3CB7-0 610 40
//@node 11C39666-0 890 40
//@node C82A6CFB-0 1170 40
//@node B1AEDA96-0 1450 40
//@node C4116AE2-0 1730 40
//@node B18F9D11-0 2010 40
//@node 45E74C5E-0 2290 40
//@node BE9A532A-0 2570 40
//@node 78476FFE-0 2850 40
//@node 6705D445-0 3130 40
//@node AE1272EA-0 3410 40
//@node 4DD74BDF-0 3690 40
//@node E36E49AD-0 3970 40
//@node 8A207850-0 4250 40
//@node E3CF9EA9-0 4530 40
//@node 29DA5F6D-0 4810 40
//@node 2E0DB1E3-0 5090 40
//@node 5DF24412-0 5370 40
//@node F457F577-0 5650 40
//@node 67A73E82-0 5930 40
//@node 940EEB7E-0 6210 40
//@node 30E96081-0 6490 40
//@node 8BCFFBDA-0 6770 40
//@node 456C11EF-0 7050 40
//@node 04EEFAF3-0 7330 40
//@node 52219F86-0 7610 40
//@node 8EADA62F-0 7890 40
//@node 9E8D3F10-0 8170 40
//@node 8B807EDE-0 8450 40
//@node B21C7B2D-0 8730 40
//@node 8135D85A-0 9010 40
//@node 0B924524-0 9290 40
//@node 11C39666-1 9570 40
//@node C82A6CFB-1 9850 40
//@node B18F9D11-1 10130 40
//@node 45E74C5E-1 10410 40
//@node 6705D445-1 10690 40
//@node AE1272EA-1 10970 40
//@node 8A207850-1 11250 40
//@node E3CF9EA9-1 11530 40
//@node 215AC65C-0 11810 40
//@node 65A94912-0 12090 40
//@node 6FA689F9-0 12370 40
//@node C54C40AD-0 12650 40
//@node 80FAA67F-0 12930 40
//@node FA2E8F31-0 13210 40
//@node B686B2DA-0 13490 40
//@node DF8A2812-0 13770 40
//@node 0B924524-1 14050 40
//@node ADBDA400-0 40 40
//@node 7812F8CF-0 330 40
//@node CB66C162-0 105 145
//@node 14A96AA4-0 610 40
//@node EB716E42-0 405 145
//@node EC2818A4-0 200 145
//@node 9449D1C1-0 890 200
//@node D5D87546-0 1170 200
//@node 8ADEBD4F-0 1450 200
//@node CA554A5F-0 1730 200
//@node F00D1C2F-0 2010 200
//@node 86A3AFB2-0 2290 200
//@node 3F2174CF-0 2570 200
//@node 665B182D-0 2850 200
//@node 3B5ABC2B-0 3130 200
//@node 0A1726A6-0 3410 200
//@node AE00642E-0 3690 200
//@node 4F410E81-0 3970 200
//@node 0B6B9627-0 4250 200
//@node 1FC6081A-0 4530 200
//@node 3B5ABC2B-1 4810 200
//@node 935872EF-0 5090 200
//@node CB5D8BCE-0 5370 200
//@node C622CAE7-0 5650 200
//@node 557D22DB-0 5930 200
//@node 1EC7435B-0 6210 200
//@node DC86062B-0 6490 200
//@node A5C8A7EF-0 6770 200
//@node 7F2D686B-0 7050 200
//@node 665B182D-1 7330 200
//@node 3B5ABC2B-2 7610 200
//@node 0A1726A6-1 7890 200
//@node CB4FBCC1-0 8170 200
//@node C622CAE7-1 8450 200
//@node 6A6F30A2-0 8730 200
//@node 65A89B0B-0 9010 200
//@node 45DC9147-0 9290 200
//@node 7F2D686B-1 9570 200
//@node 727EC6D6-0 9850 200
//@node EE33FF2E-0 10130 200
//@node 801E8486-0 10410 200
//@node 6BECE66D-0 10690 200
//@node E2A83992-0 10970 200
//@node 328531F3-0 11250 200
//@node FF94771A-0 11530 200
//@node E0ABCC5C-0 11810 200
//@node 4A99D171-0 12090 200
//@node E2901F28-0 12370 200
//@node 92369BD5-0 12650 200
//@node 86A3AFB2-1 12930 200
//@node 2ED30BC8-0 13490 200
//@node 293131B9-0 13770 200
//@node F5F59B58-0 14050 200
//@node CA554A5F-1 14330 200
//@node DEAB4F0A-0 14610 200
//@node 947F9A21-0 14890 200
//@node 3F2174CF-1 15170 200
//@node 2A66437A-0 15450 200
//@node ED9D6D3E-0 15730 200
//@node B2C3FCC7-0 16010 200
//@node AE1671EB-0 16290 200
//@node 2478DB58-0 16570 200
//@node A6E4ED0E-0 16850 200
//@node 6FBE1F0D-0 17130 200
//@node ED9D6D3E-1 17410 200
//@node B678BCDE-0 17690 200
//@node 7FA8B091-0 17970 200
//@node 17DDE8AA-0 18250 200
//@node A16363AA-0 18530 200
//@node B865B584-0 18810 200
//@node 52DE180C-0 19090 200
//@node 19B572F0-0 19370 200
//@node 1C7376DA-0 19650 200
//@node 2A66437A-1 19930 200
//@node ED9D6D3E-2 20210 200
//@node B2C3FCC7-1 20490 200
//@node BA01EC9E-0 20770 200
//@node 17DDE8AA-1 21050 200
//@node D3B205C3-0 21330 200
//@node 4AAD1D1A-0 21610 200
//@node C5C2AA7E-0 21890 200
//@node 1C7376DA-1 22170 200
//@node 727EC6D6-1 22450 200
//@node 063B0DD9-0 22730 200
//@node EB6CF055-0 23010 200
//@node 7D1F84D2-0 23290 200
//@node 9AFC74C3-0 23570 200
//@node DEF5309C-0 23850 200
//@node 5AA2649D-0 24130 200
//@node 81F2BE6D-0 24410 200
//@node 86D54CD6-0 24690 200
//@node 89546C29-0 24970 200
//@node 145B4686-0 25250 200
//@node 86A3AFB2-2 25530 200
//@node 6FDC5A29-0 40 40
//@node 5012F6E4-0 330 40
//@node 8A563E97-0 105 145
//@node CE327639-0 610 40
//@node 59232562-0 405 145
//@node CFCFE6F4-0 200 145
//@node 3C4F0045-0 890 200
//@node EBED268A-0 1170 200
//@node C516B523-0 1450 200
//@node DDC49105-0 1730 200
//@node BE62A03B-0 2010 200
//@node 03635CAC-0 2290 200
//@node 2DDFE34A-0 2570 200
//@node FB96A5F1-0 2850 200
//@node 8F523D37-0 3130 200
//@node B78E7C32-0 3410 200
//@node 63B092CC-0 3690 200
//@node 305E9225-0 3970 200
//@node A8DBC025-0 4250 200
//@node B5EF187E-0 4530 200
//@node 8F523D37-1 4810 200
//@node E8EF9BAB-0 5090 200
//@node 86B16E02-0 5370 200
//@node 394E2013-0 5650 200
//@node 061C6477-0 5930 200
//@node 9E14B4BF-0 6210 200
//@node 6341F623-0 6490 200
//@node 0B982E71-0 6770 200
//@node FB96A5F1-1 7050 200
//@node 8F523D37-2 7330 200
//@node B78E7C32-1 7610 200
//@node 1349F975-0 7890 200
//@node 394E2013-1 8170 200
//@node 437EC0CE-0 8450 200
//@node 8F860D97-0 8730 200
//@node FC136C5D-0 9010 200
//@node CF2AFBC3-0 9290 200
//@node 0B982E71-1 9570 200
//@node 98561E89-0 9850 200
//@node 1F7229B2-0 10130 200
//@node 4C418802-0 10410 200
//@node 0FE49349-0 10690 200
//@node B3C3D50E-0 10970 200
//@node BE29FDBF-0 11250 200
//@node 5C623836-0 11530 200
//@node 7657E2BA-0 11810 200
//@node B8CCC90D-0 12090 200
//@node 6EE6BFFE-0 12370 200
//@node 8E0C49D9-0 12650 200
//@node 03635CAC-1 12930 200
//@node 95AF4D04-0 13490 200
//@node FA2AFA55-0 13770 200
//@node 6E2EB024-0 14050 200
//@node DDC49105-1 14330 200
//@node 1E675AC6-0 14610 200
//@node B7BC48CB-0 14890 200
//@node 2DDFE34A-1 15170 200
//@node 2973BEB6-0 15450 200
//@node A75C3682-0 15730 200
//@node A33BAFDB-0 16010 200
//@node DC9D7BB1-0 16290 200
//@node 13D8B26C-0 16570 200
//@node 3E8D5E04-0 16850 200
//@node 6ECB9A49-0 17130 200
//@node A75C3682-1 17410 200
//@node B82DBDA2-0 17690 200
//@node 7A74834D-0 17970 200
//@node 86FD1B7E-0 18250 200
//@node 1EEA7B1E-0 18530 200
//@node C1D98198-0 18810 200
//@node 24E51356-0 19090 200
//@node D4978D44-0 19370 200
//@node FF27E628-0 19650 200
//@node 2973BEB6-1 19930 200
//@node A75C3682-2 20210 200
//@node A33BAFDB-1 20490 200
//@node 351CA7BA-0 20770 200
//@node 86FD1B7E-1 21050 200
//@node 1B35BB07-0 21330 200
//@node 2E673BD6-0 21610 200
//@node C5DF34DA-0 21890 200
//@node FF27E628-1 22170 200
//@node 98561E89-1 22450 200
//@node 9520C955-0 22730 200
//@node 33F7B619-0 23010 200
//@node D623BCB6-0 23290 200
//@node 287CAF27-0 23570 200
//@node CF79EC30-0 23850 200
//@node 377DF821-0 24130 200
//@node 5035E693-0 24410 200
//@node AE066FB2-0 24690 200
//@node 99B1760F-0 24970 200
//@node CB0097FA-0 25250 200
//@node 03635CAC-2 25530 200
//@node 0FAF32E8-0 40 40
//@node CE709F2A-0 330 40
//@node 4386A07E-0 610 40
//@node CC149374-0 405 145
//@node E651EE41-0 890 200
//@node 517E1E3E-0 1170 200
//@node BA65B626-0 1450 200
//@node 819B99B8-0 1730 200
//@node 2B26CB0B-0 40 40
//@node 19E97503-0 330 40
//@node 17C54919-0 610 40
//@node 18C09AC6-0 890 40
//@node 8CA453BF-0 1170 40
//@node BAA95F5D-0 1450 40
//@node BCD8DE84-0 1730 40
//@node F0858A4F-0 2010 40
//@node 4B861A20-0 2290 40
//@node C5AF3080-0 40 40
//@node DF31625B-0 330 40
//@node 033666A3-0 610 40
//@node AF8BE7E4-0 890 40
//@node 2414B650-0 1170 40
//@node DE0A5D94-0 1450 40
//@node 628D344B-0 1730 40
//@node 625AB2A4-0 2010 40
//@node 419DE8CF-0 2290 40
//@node 8CF21BF7-0 2570 40
//@node 6549C2D3-0 2850 40
//@node B2D354B2-0 3130 40
//@node 62C4CB0B-0 3410 40
//@node E5C358FE-0 3690 40
//@node CD92FA1D-0 3970 40
//@node 58370D33-0 40 40
//@node C6FB4F15-0 330 40
//@node C4545BB8-0 125 145
//@node 33F467FE-0 610 200
//@node 1FB3C154-0 385 305
//@node 9E9867EA-0 890 200
//@node 5782B82F-0 685 300
//@node 97B80456-0 480 300
//@node A31EDEB9-0 1170 200
//@node 5713960C-0 965 300
//@node C132A5F4-0 760 300
//@node DD6DA7F0-0 1450 200
//@node D4071D30-0 1245 300
//@node EABFD9A4-0 1040 300
//@node 91D6E31A-0 1730 200
//@node 749A2355-0 2010 200
//@node 33F467FE-1 2290 200
//@node 550B200D-0 2065 305
//@node 489DE28E-0 2570 200
//@node 97CED0CC-0 2365 300
//@node AB73AE21-0 2160 300
//@node 33F467FE-2 2850 200
//@node BC51E2EE-0 2625 305
//@node 9E9867EA-1 3130 200
//@node 94950F80-0 2925 300
//@node 398DEE81-0 2720 300
//@node A31EDEB9-1 3410 200
//@node 3D2C14B7-0 3205 300
//@node C3DBE8BF-0 3000 300
//@node DD6DA7F0-1 3690 200
//@node 1E83F86B-0 3485 300
//@node 2554966F-0 3280 300
//@node 951C66B0-0 3970 200
//@node 749A2355-1 4250 200
//@node 33F467FE-3 4530 200
//@node 13112BFF-0 4305 305
//@node 489DE28E-1 4810 200
//@node 4C1F5D5B-0 4605 300
//@node 44B88CF6-0 4400 300
//@node 9F0AD29A-0 40 40
//@node C5977690-0 330 40
//@node 3E01943E-0 125 145
//@node 5003C8FB-0 610 200
//@node 28039E36-0 385 305
//@node D0080686-0 890 200
//@node 95C22FB2-0 685 300
//@node DE428A6F-0 480 300
//@node 10E13DFD-0 1170 200
//@node A7B8763D-0 965 300
//@node 62431E25-0 760 300
//@node 26176794-0 1450 200
//@node B7798C3D-0 1245 300
//@node 6AC93F05-0 1040 300
//@node A9925297-0 1730 200
//@node 50960C7B-0 2010 200
//@node 5631AC05-0 2290 200
//@node 7FA1D0AF-0 2065 305
//@node 6FC39645-0 2570 200
//@node A3AF4680-0 2365 300
//@node E422AFB1-0 2160 300
//@node 5003C8FB-1 2850 200
//@node F2165A87-0 2625 305
//@node D0080686-1 3130 200
//@node 73378F31-0 2925 300
//@node A3ADCDA4-0 2720 300
//@node 10E13DFD-1 3410 200
//@node 27D426C2-0 3205 300
//@node 65F343AA-0 3000 300
//@node 26176794-1 3690 200
//@node 37953CC2-0 3485 300
//@node F857C00A-0 3280 300
//@node EA91073D-0 3970 200
//@node 50960C7B-1 4250 200
//@node 5631AC05-1 4530 200
//@node 28700DDE-0 4305 305
//@node 6FC39645-1 4810 200
//@node 4C4D57BF-0 4605 300
//@node 4028BD46-0 4400 300
//@node 03D4A542-0 40 40
//@node 3D026A66-0 330 40
//@node 3B72068F-0 105 145
//@node A08680E5-0 610 40
//@node 715118A2-0 385 145
//@node D3B136CD-0 180 245
//@node 0CBA9416-0 890 40
//@node BF262492-0 1170 40
//@node D3F694B7-0 1450 40
//@node C0D44857-0 1245 140
//@node 3F43D8D9-0 1730 40
//@node 273CC1A4-0 2010 40
//@node 82FC897B-0 2290 40
//@node 41E45B77-0 2570 40
//@node 3ECC2FE2-0 2850 40
//@node 05D63945-0 3130 40
//@node 43CE1B07-0 3410 40
//@node 593687BA-0 3690 40
//@node D3F694B7-1 3970 40
//@node 7CD347C4-0 3765 140
//@node A4074504-0 4250 40
//@node 403F2A86-0 4530 40
//@node 20827325-0 4810 40
//@node 660A112E-0 5090 40
//@node 449A8830-0 5370 40
//@node 3ECC2FE2-1 5650 40
//@node 0715E532-0 5930 40
//@node 32E64F9C-0 6210 40
//@node 5AD4823D-0 6490 40
//@node D3F694B7-2 6770 40
//@node 3E918019-0 6565 140
//@node BB9C1E4F-0 7050 40
//@node 441EBF45-0 7330 40
//@node 52FC0274-0 7610 40
//@node 7F38E8C1-0 7890 40
//@node 3ECC2FE2-2 8170 40
//@node BE5DD07F-0 8450 40
//@node E01A2778-0 8730 40
//@node 9DBEBC73-0 9010 40
//@node D3F694B7-3 9290 40
//@node 01E2A206-0 9085 140
//@node 764442BC-0 9570 40
//@node ED41388E-0 9850 40
//@node D83E595B-0 10130 40
//@node F095D062-0 10410 40
//@node 3ECC2FE2-3 10690 40
//@node 4FB516AC-0 10970 40
//@node 6A964428-0 11250 40
//@node 85BCE2B6-0 11530 40
//@node D3F694B7-4 11810 40
//@node 12A32523-0 11605 140
//@node 76E6E82D-0 12090 40
//@node 115C8EF9-0 12370 40
//@node 61049592-0 12650 40
//@node DBA3C29B-0 12930 40
//@node 3ECC2FE2-4 13210 40
//@node 14DAEA79-0 13490 40
//@node 8E11531E-0 13770 40
//@node 25EF423B-0 14050 40
//@node F4FD4153-0 14330 40
//@node D3F694B7-5 14610 40
//@node 1759F6C0-0 14405 140
//@node 2EE76AC1-0 14890 40
//@node F39E42A1-0 40 40
//@node 100B74CB-0 330 40
//@node 2B9371FA-0 125 145
//@node C36F3D92-0 610 200
//@node FA59FB9B-0 405 305
//@node B6CEC4F1-0 200 305
//@node 973E2603-0 890 360
//@node 4950EBA0-0 685 465
//@node 0746CFB0-0 480 465
//@node 92755CA0-0 1170 360
//@node 11025D8F-0 1450 360
//@node E73E3645-0 40 40
//@node CB4E76E2-0 330 40
//@node 2AB66EDA-0 610 40
//@node 1605C249-0 890 40
//@node BB880E0E-0 1170 40
//@node 383B1BF4-0 1450 40
//@node 2566E270-0 1730 40
//@node F44D006C-0 2010 40
//@node 17FBCA21-0 2290 40
//@node 72B9902C-0 2570 40
//@node B94CFF51-0 40 40
//@node 532D6D52-0 330 40
//@node F7B1EF63-0 610 40
//@node 11FA1AD2-0 890 40
//@node A68B0381-0 1170 40
//@node 449E22D6-0 1450 40
//@node DAAB93F2-0 1730 40
//@node 86117D4E-0 2010 40
//@node 413806CC-0 2290 40
//@node 75E7E0F8-0 40 40
//@node 217F1349-0 330 40
//@node 582710F2-0 610 40
//@node 210133A9-0 890 40
//@node F2D87E06-0 40 40
//@node C0781B28-0 330 40
//@node 6799EFF0-0 610 40
//@node C1A98A40-0 890 40
//@node 225D94FF-0 1170 40
//@node 3A366FFC-0 1450 40
//@node D3B06018-0 1730 40
//@node DCBF0EA4-0 2010 40
//@node 88593689-0 2290 40
//@node CF18FD3D-0 2570 40
//@node 54D786D3-0 40 40
//@node 60D46F7D-0 330 40
//@node 90FBD731-0 610 40
//@node 2C0E2850-0 890 40
//@node DD087E03-0 1170 40
//@node F1137E78-0 1450 40
//@node 5A29B12A-0 1730 40
//@node DBCC6085-0 40 40
//@node 8890E1C5-0 330 40
//@node 6809E6B2-0 610 40
//@node 69150FBD-0 890 40
//@node 28B9DD11-0 1170 40
//@node CAF13864-0 1450 40
//@node 70977319-0 1730 40
//@node 0E96D0F0-0 40 40
//@node D427A5DB-0 330 40
//@node 2D7E3953-0 610 40
//@node 65B5540A-0 890 40
//@node CCD0E6AF-0 1170 40
//@node 7882F9A8-0 1450 40
//@node 0324C79E-0 1730 40
//@node E195B12F-0 40 40
//@node 6BF9EAEB-0 330 40
//@node 84B9A5A2-0 610 40
//@node FD3E18CC-0 890 40
//@node 9BBD4972-0 1170 40
//@node 1EC67F2D-0 1450 40
//@node 8D0EF4F2-0 1730 40
//@node C0FC87CE-0 2010 40
//@node 53CAD64A-0 2290 40
//@node 677DD6C4-0 2570 40
//@node CD019718-0 2850 40
//@node 115CDB0E-0 40 40
//@node 5BA3F42E-0 330 40
//@node 960419F4-0 610 40
//@node 53455989-0 890 40
//@node AC9D3C04-0 1170 40
//@node 13E548E8-0 1450 40
//@node E1348864-0 1730 40
//@node 7767E04B-0 2010 40
//@node C0E6440C-0 2290 40
//@node 8FAFC850-0 2570 40
//@node 03CEA041-0 2850 40
//@node 9B695B33-0 40 40
//@node B8EEB7AB-0 330 40
//@node DC80F10C-0 610 40
//@node 7C7354A9-0 890 40
//@node 16E48DA6-0 1170 40
//@node AC9C6097-0 1450 40
//@node 40015FDC-0 1730 40
//@node 3308E145-0 2010 40
//@node 5393C0DE-0 2290 40
//@node 3E46A0CB-0 2570 40
//@node A0F52CB4-0 2850 40
//@node B595C21F-0 3130 40
//@node 70620206-0 3410 40
//@node B2C7F6BA-0 3690 40
//@node 3EE74D51-0 3970 40
//@node 62948DF1-0 4250 40
//@node 8A932CA6-0 4530 40
//@node 03EBC1E3-0 4810 40
//@node B4CFB692-0 5090 40
//@node 237E4936-0 5370 40
//@node A991AD27-0 5650 40
//@node 843391E2-0 40 40
//@node 647CAB0D-0 330 40
//@node AD5BDAB5-0 610 40
//@node 57BF583C-0 890 40
//@node B6B88383-0 1170 40
//@node 979A2EFA-0 1450 40
//@node 7F7D9222-0 1730 40
//@node A60AD8CA-0 2010 40
//@node 779E482D-0 2290 40
//@node 4A21DECB-0 2570 40
//@node 9BCB8310-0 2850 40
//@node 39CB951E-0 3130 40
//@node 4879505B-0 3410 40
//@node 141BD141-0 3690 40
//@node E9890F78-0 3970 40
//@node 2DAB6A0B-0 4250 40
//@node 5ECDA43A-0 4025 145
//@node 6F5CE7F2-0 4530 40
//@node 10D67AD1-0 4325 140
//@node EF772979-0 4810 40
//@node AFACD77E-0 4585 145
//@node 6F5CE7F2-1 5090 40
//@node 51CAD7B6-0 4885 140
//@node BBC91133-0 5370 40
//@node C2E9DFEC-0 5650 40
//@node EABB033E-0 5930 40
//@node 667289CA-0 6210 40
//@node 0C9F43CA-0 6490 40
//@node A1CE1D07-0 6770 40
//@node 3565CBAF-0 7050 40
//@node 968D9F60-0 7330 40
//@node 9D5FCD5B-0 7610 40
//@node 5B85EBA2-0 7890 40
//@node 9D5FCD5B-1 8170 40
//@node 49C78B65-0 8450 40
//@node 9D5FCD5B-2 8730 40
//@node 90477160-0 9010 40
//@node B2B4CC45-0 8785 145
//@node 6F5CE7F2-2 9290 40
//@node 2F7B0D3B-0 9085 140
//@node 5BD210E7-0 9570 40
//@node 158BCF66-0 9850 40
//@node 24F68DA0-0 10130 40
//@node 8E367E4B-0 10410 40
//@node 31887FC5-0 10690 40
//@node B3C9D1F3-0 10970 40
//@node 3ADE8B67-0 10745 145
//@node 6F5CE7F2-3 11250 40
//@node A9B08C28-0 11045 140
//@node BBC91133-1 11530 40
//@node 8ABA11B4-0 11810 40
//@node CB09F8AD-0 12090 40
//@node 0499465A-0 12370 40
//@node 767319BF-0 12650 40
//@node 41BAD4F7-0 12930 40
//@node 0A37F4D4-0 13210 40
//@node BD37EE0D-0 13490 40
//@node 1A35E8F6-0 13770 40
//@node 75BE0539-0 14050 40
//@node 270CBCFE-0 14330 40
//@node 5553BDF7-0 14610 40
//@node 6B4035E6-0 14890 40
//@node A7F18100-0 15170 40
//@node ABB3BDF7-0 15450 40
//@node AE85812B-0 15730 40
//@node 1C0C6358-0 16010 40
//@node 1D6DED5E-0 16290 40
//@node B453E337-0 16570 40
//@node BB0B2A63-0 16850 40
//@node 8706FD6A-0 17130 40
//@node 5F949702-0 17410 40
//@node 647CAB0D-1 17690 40
//@node 950C41B0-0 40 40
//@node 91B7ACEB-0 330 40
//@node FD0B4F29-0 610 40
//@node 80AC0049-0 890 40
//@node 392F95E3-0 1170 40
//@node D46F08B3-0 1450 40
//@node A46A8E9F-0 1730 40
//@node 4740808B-0 2010 40
//@node E7048FFF-0 1785 145
//@node A2FB1EFB-0 2290 40
//@node 57631837-0 2570 40
//@node 43D33A89-0 2850 40
//@node 8073FC04-0 3130 40
//@node 10CE84D6-0 3410 40
//@node 074CC0F1-0 3690 40
//@node 731E14A3-0 3970 40
//@node E051B3B7-0 4250 40
//@node 81ABB751-0 4530 40
//@node DC4B00F2-0 4810 40
//@node 5E7955D7-0 5090 40
//@node 510EE30C-0 5370 40
//@node 7915EBE5-0 5650 40
//@node D6BDBD85-0 5930 40
//@node DDD8D28E-0 6210 40
//@node 7E2AAB2F-0 6490 40
//@node 5DC76E2C-0 6770 40
//@node 58559583-0 7050 40
//@node 406B74BC-0 7330 40
//@node 1CB6A805-0 7610 40
//@node 493B2620-0 7890 40
//@node 470F2B66-0 8170 40
//@node 1AE0B271-0 8450 40
//@node 4898B6CD-0 8730 40
//@node 4ED8C22E-0 9010 40
//@node A67FE38C-0 9290 40
//@node E1A8D179-0 9570 40
//@node F599D025-0 9850 40
//@node 1FB3DD48-0 10130 40
//@node 24A8759D-0 10410 40
//@node 2F874ABA-0 10690 40
//@node 888A8C1B-0 10970 40
//@node C26D46B4-0 11250 40
//@node 6987D4BB-0 11530 40
//@node 1096B37A-0 11810 40
//@node 00042EAC-0 11605 145
//@node 075792DE-0 11400 145
//@node 3B8810CF-0 12370 200
//@node 84E11CA8-0 12650 200
//@node CC8D0909-0 12930 200
//@node 87352D76-0 13210 200
//@node 0772BA41-0 13490 200
//@node 703C392F-0 40 40
//@node C55601CC-0 330 40
//@node B2C6C2FC-0 610 40
//@node D82639AD-0 890 40
//@node 97D652B4-0 1170 40
//@node 35FC68F3-0 1450 40
//@node 57F4A96E-0 1730 40
//@node ADB247D4-0 2010 40
//@node E53527F7-0 2290 40
//@node 0723404A-0 2570 40
//@node 11AE2031-0 2850 40
//@node F68CC7C8-0 3130 40
//@node E7A3BFEF-0 3410 40
//@node 4CB540EC-0 3690 40
//@node 72572891-0 3970 40
//@node A2D39981-0 4250 40
//@node 2BD6B332-0 4530 40
//@node 27112C3A-0 4810 40
//@node 357B71A5-0 5090 40
//@node FAE30489-0 5370 40
//@node 124DA25C-0 5650 40
//@node D4A21990-0 5930 40
//@node 9A6459CD-0 6210 40
//@node DAF3ED94-0 6490 40
//@node 3B0E56FC-0 6770 40
//@node DEFF9592-0 7050 40
//@node 901F683C-0 7330 40
//@node B22D9DDD-0 7610 40
//@node CBD13C45-0 7405 145
//@node C90DFEC5-0 7200 145
//@node B47CC99C-0 8170 200
//@node 5B23A493-0 8450 200
//@node C580F856-0 8730 200
//@node 0C160869-0 9010 200
//@node B157A28C-0 9290 200
//@node 7AEA71C1-0 40 40
//@node 500E5E0E-0 330 40
//@node 46635634-0 125 145
//@node F8B10B32-0 610 40
//@node 751A5F97-0 405 145
//@node 8846F578-0 40 40
//@node 326A6082-0 330 40
//@node E4B70C26-0 610 40
//@node 6D81B11D-0 890 40
//@node 63843048-0 1170 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node EA8245C2-0 610 40
//@node 67C3ED48-0 890 40
//@node 5531D4DD-0 1170 40
//@doomscript-blueprint end
