namespace map_mc_underground {

	// global state variables
	float saftey_bridge_state = 1;
	float underarm_work_state = 1;
	float underarm_fingers_state = -64;

	// variable to track crane movement state
	float crane_main_state = 0;
	float crane_dir = 0;
	
	// Start Xian Stuff

	void cache_sounds() {
		sys.cacheSoundShader ("mset1_movement");
		sys.cacheSoundShader ("mset1_stop");
		sys.cacheSoundShader ("mset2_movement");
		sys.cacheSoundShader ("mset2_stop");

		sys.cacheSoundShader ("m1_start");
		sys.cacheSoundShader ("m1_loop");
		sys.cacheSoundShader ("m1_stop");		
		
		sys.cacheSoundShader ("mcu_support_2s");
		sys.cacheSoundShader ("mcu_safteybridge_02");
		sys.cacheSoundShader ("mcu_safteybridge_01");
		sys.cacheSoundShader ("msmall_pounder");
		sys.cacheSoundShader ("servo_1s_01");
		sys.cacheSoundShader ("servo_1s_02");
		sys.cacheSoundShader ("mech_fingers_1_5s");
		sys.cacheSoundShader ("airwhomp");
		sys.cacheSoundShader ("something_interesting");
		sys.cacheSoundShader ("something_interesting_2");
		sys.cacheSoundShader ("metalbounce_1");
		sys.cacheSoundShader ("metalbounce_2");
		sys.cacheSoundShader ("guisounds_pingup");
	
		sys.cacheSoundShader ("steelswing_01");
		sys.cacheSoundShader ("steelswing_02");
		sys.cacheSoundShader ("steelswing_03");
		sys.cacheSoundShader ("steelswing_04");
		sys.cacheSoundShader ("steelswing_05");
		sys.cacheSoundShader ("wiresnap");
		sys.cacheSoundShader ("mc_hellblast_explosion");
		sys.cacheSoundShader ("mc_leatherface");
		sys.cacheSoundShader ("mc_invasion_stuff");
		sys.cacheSoundShader ("mc_substing_01");
		sys.cacheSoundShader ("mc_substing_02");
	}
	
	// This function triggers sounds to alter the soundscape after the invasion
	void post_invasion_sounds() {
		sys.trigger ($hspeaker_1);
		sys.trigger ($hspeaker_2);
		sys.trigger ($hspeaker_3);
		sys.trigger ($hspeaker_4);
		sys.trigger ($hspeaker_5);
		sys.trigger ($hspeaker_6);
		sys.trigger ($hspeaker_7);
		sys.trigger ($hspeaker_8);
	}

	void mover_startsound (entity ent) {
		ent.startSoundShader ("m1_start", SND_CHANNEL_VOICE);
		sys.wait (0.75);
		ent.startSoundShader ("m1_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound (entity ent) {
		ent.startSoundShader ("m1_stop", SND_CHANNEL_VOICE2);
	}

	// End Xian Stuff


	////////////////////////////////////////////////////
	//
	//	Setup binds and times etc...
	//
	////////////////////////////////////////////////////
	void setup_objects()
	{
		//rotate crane initially
		$crane_main.rotateOnce('0 80 0');

		//set initial crane times
		$crane_main.time (6);
		$crane_main.accelTime (3);
		$crane_main.decelTime (2);

		$crane_carrier.bind ($crane_main);
		$crane_carrier_load.bind ($crane_carrier);
		$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
		$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
		$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);

		//rotate the two klaxon lights
		$emrredlight1_mover.rotateOnce('0 0 45');
		$emrredlight2_mover.rotateOnce('0 0 45');

		//set airlock door guis initial states to 1
		$airlock1_door1_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock1_door2_gui.setGuiParm ( "gui_parm1" , 1);

		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);

		//underarm setup
		$underarm_top.bind ($underarm_carrier);
		$underarm_upper.bind ($underarm_top);
		$underarm_lower.bind ($underarm_upper);
		$underarm_fingers.bind ($underarm_lower);
		$underarm_tube.bind ($underarm_lower);
		$underarm_tube_light.bind ($underarm_tube);

		$underarm_upper.accelTime (.2);
		$underarm_lower.accelTime (.2);
		$underarm_upper.decelTime (.2);
		$underarm_lower.decelTime (.2);

		$underarm_carrier.speed (150);
		$underarm_carrier.accelTime (.25);
		$underarm_carrier.decelTime (.25);

		$underarm_fingers.time (.01);

		$underarm_tube.setColor ( 1, 0, 0 );
		$underarm_tube_light.setColor ( 1, 0, 0 );
		$underarm_can_1.setColor ( 1, 0, 0 );
		$underarm_can_1_light.setColor ( 1, 0, 0 );
		$underarm_can_2.setColor ( 1, 0, 0 );
		$underarm_can_2_light.setColor ( 1, 0, 0 );

		//fingers to up pose
		while ( underarm_fingers_state < 0 ){
			$underarm_fingers.move ( UP, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state += 1;
		}
		
		//arm to storage pose
		$underarm_upper.rotateOnce ( '0 0 90' );
		$underarm_lower.rotateOnce ( '0 0 -90' );
		sys.waitFor ($underarm_lower);


		//howitzer setup
		$how1_barrel.bind ($how1_base);
		$how1_recep.bind ($how1_base);
		$how1_catcher.bind ($how1_base);
		$how1_base.rotateOnce ( '0 0 45' );

		$how2_barrel.bind ($how2_base);
		$how2_recep.bind ($how2_base);
		$how2_catcher.bind ($how2_base);
		$how2_base.rotateOnce ( '0 0 45' );

		$how3_barrel.bind ($how3_base);
		$how3_recep.bind ($how3_base);
		$how3_catcher.bind ($how3_base);
		$how3_base.rotateOnce ( '0 0 45' );

		sys.waitFor($how1_base);

		//crankshaft initial bind and rotate
		$mc_pistrod1.bind ($mc_assembly_midpoint);
		$mc_pistrod2.bind ($mc_assembly_midpoint);
		$mc_pistrod3.bind ($mc_assembly_midpoint);

		$mc_piston1.bind ($mc_assembly_midpoint);
		$mc_piston2.bind ($mc_assembly_midpoint);
		$mc_piston3.bind ($mc_assembly_midpoint);

		$mc_crankshaft.bind ($mc_assembly_midpoint);

		$mc_assembly_midpoint.rotateOnce ( '-135 0 0' );
		sys.waitFor ($mc_assembly_midpoint);

		//crankshaft binds and times 
		$mc_pistrod1.bind ($mc_piston1);
		$mc_pistrod2.bind ($mc_piston2);
		$mc_pistrod3.bind ($mc_piston3);

		$mc_piston1.time (.125);
		$mc_pistrod1.time (.125);
		$mc_piston2.time (.125);
		$mc_pistrod2.time (.125);
		$mc_piston3.time (.125);
		$mc_pistrod3.time (.125);
		$mc_crankshaft.time (.125);

		//little piston machine binds and times
		$pistrod1.bind ($piston1);
		$pistrod2.bind ($piston2);
		$pistrod3.bind ($piston3);

		$piston1.time (.125);
		$pistrod1.time (.125);
		$piston2.time (.125);
		$pistrod2.time (.125);
		$piston3.time (.125);
		$pistrod3.time (.125);
		$crankshaft.time (.125);
	}


	void safety_rails_down ()
	{
		//set rail 1 times
		$safety_rail_1.time( 1 );
		$safety_rail_1.accelTime( .25 );
		$safety_rail_1.decelTime( .25 );

		//rails down
		$safety_rail_1.move( DOWN, 40 );
	}

	void safety_rails_up ()
	{
		//set rail 1 times
		$safety_rail_1.time( 1 );
		$safety_rail_1.accelTime( .25 );
		$safety_rail_1.decelTime( .25 );

		//rails up
		$safety_rail_1.move( UP, 40 );
	}



	////////////////////////////////////////////////////
	//
	//	Saftey Bridge AWAY PAIR
	//	this will put the bridge piece and it's partner
	//	in the away position
	//
	////////////////////////////////////////////////////
	void saftey_bridge_away_pair(float bridge_number)
	{
		entity bh1, bh2, bf1, bf2;

		bh1=sys.getEntity ("saftey_bridge_holder_" + bridge_number );
		bh2=sys.getEntity ("saftey_bridge_holder_" + (bridge_number+1) );

		bf1=sys.getEntity ("saftey_bridge_floorpiece_" + bridge_number );
		bf2=sys.getEntity ("saftey_bridge_floorpiece_" + (bridge_number+1) );

		bf1.bind (bh1);
		bf2.bind (bh2);
		
		bh1.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2);
	
		bh1.rotateOnce ( '45 0 0' );
		bh2.rotateOnce ( '-45 0 0' );
		sys.waitFor (bh1);
			
		bf1.unbind ();
		bf2.unbind ();
		
		bf1.startSoundShader ("mcu_safteybridge_02", SND_CHANNEL_VOICE2 );
		
		bf1.move ( REL_FORWARD, 256 );
		bf2.move ( REL_BACK, 256 );
		sys.waitFor (bf1);

		bh1.startSoundShader ("mcu_safteybridge_01", SND_CHANNEL_VOICE );
		bh1.rotateOnce ( '-135 0 0' );
		bh2.rotateOnce ( '135 0 0' );
		sys.waitFor (bh1);

		if (bridge_number==7){
			//sys.print( "\nlast bridge is done\n" );
			saftey_bridge_state = 0;
			$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 1);
			//sys.print( "setting bridge gui parm \n" );
			$underarm_centralight2.fadeInLight (1);
			$underarm_centralight1.fadeInLight (1);
		}

	}


	////////////////////////////////////////////////////
	//
	//	Saftey Bridge FORTH_PAIR
	//	this will put the bridge piece and it's partner
	//	in the traversable position
	//
	////////////////////////////////////////////////////
	void saftey_bridge_forth_pair(float bridge_number)
	{
		entity bh1, bh2, bf1, bf2;

		bh1=sys.getEntity ("saftey_bridge_holder_" + bridge_number );
		bh2=sys.getEntity ("saftey_bridge_holder_" + (bridge_number+1) );

		bf1=sys.getEntity ("saftey_bridge_floorpiece_" + bridge_number );
		bf2=sys.getEntity ("saftey_bridge_floorpiece_" + (bridge_number+1) );

		
		
		bh1.startSoundShader ("mcu_safteybridge_01", SND_CHANNEL_VOICE );
		bh1.rotateOnce ( '135 0 0' );
		bh2.rotateOnce ( '-135 0 0' );
		sys.waitFor (bh1);

		bf1.unbind ();
		bf2.unbind ();
				
		bf1.startSoundShader ("mcu_safteybridge_02", SND_CHANNEL_VOICE2 );
		bf1.move ( REL_BACK, 256 );
		bf2.move ( REL_FORWARD, 256 );
		
		sys.waitFor (bf1);

		bf1.bind (bh1);
		bf2.bind (bh2);
		bh1.time ( 2 );
		bh2.time ( 2 );
		bh1.accelTime ( 1 );
		bh2.accelTime ( 1 );
		bh1.decelTime ( 0 );
		bh2.decelTime ( 0 );
		
		bh1.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2);
		
		bh1.rotateOnce ( '-45 0 0' );
		bh2.rotateOnce ( '45 0 0' );
		sys.waitFor (bh1);
			
		//bounce it
		bh1.time( .15 );
		bh2.time( .15 );
		bh1.accelTime( 0 );
		bh2.accelTime( 0 );
		bh1.decelTime( .15 );
		bh2.decelTime( .15 );
		bh1.startSoundShader ("metalbounce_1", SND_CHANNEL_VOICE );
		bh1.rotateOnce( '.75 0 0' );
		bh2.rotateOnce( '-.75 0 0' );
		sys.waitFor (bh1);

		bh1.time( .15 );
		bh2.time( .15 );
		bh1.accelTime( .15 );
		bh2.accelTime( .15 );
		bh1.decelTime( 0 );
		bh2.decelTime( 0 );
		//bh1.startSoundShader ("metalbounce_2", SND_CHANNEL_VOICE2 );
		bh1.rotateOnce( '-.75 0 0' );
		bh2.rotateOnce( '.75 0 0' );
		sys.waitFor (bh1);

		bh1.time ( 2 );
		bh2.time ( 2 );
		bh1.accelTime ( .5 );
		bh2.accelTime ( .5 );
		bh1.decelTime ( .5 );
		bh2.decelTime ( .5 );
		bf1.unbind ();
		bf2.unbind ();

		if (bridge_number==1){
			saftey_bridge_state = 1;
			$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 2);
			$underarm_centralight2.fadeOutLight (1);
			$underarm_centralight1.fadeOutLight (1);
		}
	}

	////////////////////////////////////////////////////
	//
	//	Saftey Bridge AWAY
	//	this will put the bridge in the away position
	//
	////////////////////////////////////////////////////
	void saftey_bridge_away()
	{
		float thread1;

		if (saftey_bridge_state == 1){
			//set the bridge state to prevent reuse
			$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 0);
			saftey_bridge_state = 9;

			thread saftey_bridge_away_pair(1);
			sys.wait (1);

			thread saftey_bridge_away_pair(3);
			sys.wait (1);

			thread saftey_bridge_away_pair(5);
			sys.wait (1);

			thread1 = thread saftey_bridge_away_pair(7);
			sys.waitForThread( thread1);

			//trigger the aas
			sys.trigger ($bridge_aas);

			//rails up
			safety_rails_up ();

		}	else {
			  //sys.print ("bridge already away\n");
			;
		}
	}



	////////////////////////////////////////////////////
	//
	//	Saftey Bridge FORTH
	//	this will put the bridge in the traversalbe position
	//
	////////////////////////////////////////////////////
	void saftey_bridge_forth()
	{
		float thread1;
		//sys.print( "saftey_bridge_state = " + saftey_bridge_state + "\n" );
		if (saftey_bridge_state == 0){

			//rails down
			safety_rails_down ();

			//set the bridge state to prevent reuse
			$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 0);
			saftey_bridge_state = 9;

			thread saftey_bridge_forth_pair(7);
			sys.wait (1);
			
			thread saftey_bridge_forth_pair(5);
			sys.wait (1);
			
			thread saftey_bridge_forth_pair(3);
			sys.wait (1);

			thread1 = thread saftey_bridge_forth_pair(1);
			sys.waitForThread( thread1);
			
			//trigger the aas
			sys.trigger ($bridge_aas);
			//sys.print ("bridge aas should be on\n");

		}	else {
			  //sys.print ("bridge already out\n");
			;
		}
	}


	////////////////////////////////////////////////////
	//
	//	Rotary movement - the two big rotating
	//  light chambers
	//
	////////////////////////////////////////////////////
	void rotary()
	{
		$fly_around_light.bind ($fly_around_main);
		$fly_around_speaker.bind ($fly_around_main);
		$fly_around_end.bind ($fly_around_main);

		$fly_around_main.rotate ( '0 100 0' );
		$fly_around_middle.rotate ( '0 100 0' );

		$fly_around2_light.bind ($fly_around2_main);
		$fly_around2_speaker.bind ($fly_around2_main);
		$fly_around2_end.bind ($fly_around2_main);

		$fly_around2_main.rotate ( '0 -100 0' );
		$fly_around2_middle.rotate ( '0 -100 0' );
	}



	////////////////////////////////////////////////////
	//
	//	howitzer #1 movement ... this is the 1st of 
	//  the big piston like rods 
	//
	////////////////////////////////////////////////////
	void howitzer_1()
	{
		//random numbers to keep howitzers unsynced
		float ran1,ran2;
		ran1=sys.random(1);
		ran2=sys.random(1);

		while (1){
			//move the catcher up 8 for the recoil action
			$how1_catcher.time (.4);
			$how1_catcher.accelTime (.2);
			$how1_catcher.decelTime (.2);

			$how1_barrel.time (.4);
			$how1_barrel.accelTime (.2);
			$how1_barrel.decelTime (.2);
			
			$how1_barrel.move ( UP, 10 );
			$how1_catcher.move ( UP, 10 );
			sys.waitFor ($how1_barrel);
			sys.wait (ran1+1);

			//move the barrel upwards slowly
			$how1_barrel.time (3+ran2);
			$how1_barrel.accelTime (0);
			$how1_barrel.decelTime (2);

			$how1_barrel.startSoundShader ("mset2_movement", SND_CHANNEL_VOICE);
			$how1_barrel.move ( UP, 128 );
			sys.waitFor ($how1_barrel);
			$how1_barrel.stopSound ( SND_CHANNEL_VOICE, false );
			$how1_barrel.startSoundShader ("mset2_stop", SND_CHANNEL_VOICE2);

			//fire the barrel backwards quickly
			$how1_barrel.time (.25);
			$how1_barrel.accelTime (.2);
			$how1_barrel.decelTime (0);

			
			$how1_barrel.move ( DOWN, 128 );
			sys.waitFor ($how1_barrel);

			$how1_barrel.startSoundShader ("msmall_pounder", SND_CHANNEL_ANY);


			//catch the barrel in the catcher... down 8
			$how1_catcher.time (.1);
			$how1_catcher.accelTime (0);
			$how1_catcher.decelTime (.1);

			$how1_barrel.time (.1);
			$how1_barrel.accelTime (0);
			$how1_barrel.decelTime (.1);

			$how1_barrel.move ( DOWN, 10 );
			$how1_catcher.move ( DOWN, 10 );
			//sys.trigger ($how1_steam_1);
			sys.waitFor ($how1_barrel);
		}
	}


	////////////////////////////////////////////////////
	//
	//	howitzer #2 movement ... this is the 2nd of 
	//  the big piston like rods 
	//
	////////////////////////////////////////////////////
	void howitzer_2()
	{
		//random numbers to keep howitzers unsynced
		float ran1,ran2;
		ran1=sys.random(1);
		ran2=sys.random(1);

		while (1){
			//move the catcher up 8 for the recoil action
			$how2_catcher.time (.4);
			$how2_catcher.accelTime (.2);
			$how2_catcher.decelTime (.2);

			$how2_barrel.time (.4);
			$how2_barrel.accelTime (.2);
			$how2_barrel.decelTime (.2);

			$how2_barrel.move ( UP, 10 );
			$how2_catcher.move ( UP, 10 );
			sys.waitFor ($how2_barrel);
			sys.wait (ran1+1);

			//move the barrel upwards slowly
			$how2_barrel.time (3+ran2);
			$how2_barrel.accelTime (0);
			$how2_barrel.decelTime (2);

			$how2_barrel.startSoundShader ("mset1_movement", SND_CHANNEL_VOICE);
			$how2_barrel.move ( UP, 128 );
			sys.waitFor ($how2_barrel);
			$how2_barrel.stopSound ( SND_CHANNEL_VOICE, false );
			$how2_barrel.startSoundShader ("mset1_stop", SND_CHANNEL_VOICE2);

			//fire the barrel backwards quickly
			$how2_barrel.time (.25);
			$how2_barrel.accelTime (.2);
			$how2_barrel.decelTime (0);

			$how2_barrel.startSoundShader ("msmall_pounder", SND_CHANNEL_ANY);
			$how2_barrel.move ( DOWN, 128 );
			sys.waitFor ($how2_barrel);

			//catch the barrel in the catcher... down 8
			$how2_catcher.time (.1);
			$how2_catcher.accelTime (0);
			$how2_catcher.decelTime (.1);

			$how2_barrel.time (.1);
			$how2_barrel.accelTime (0);
			$how2_barrel.decelTime (.1);

			$how2_barrel.move ( DOWN, 10 );
			$how2_catcher.move ( DOWN, 10 );
			//sys.trigger ($how2_steam_1);
			sys.waitFor ($how2_barrel);
		}
	}


	////////////////////////////////////////////////////
	//
	//	howitzer #3 movement ... this is the 3rd of 
	//  the big piston like rods 
	//
	////////////////////////////////////////////////////
	void howitzer_3()
	{
		//random numbers to keep howitzers unsynced
		float ran1,ran2;
		ran1=sys.random(.5);
		ran2=sys.random(.35);

		while (1){
			//move the catcher up 8 for the recoil action
			$how3_catcher.time (.4);
			$how3_catcher.accelTime (.2);
			$how3_catcher.decelTime (.2);

			$how3_barrel.time (.4);
			$how3_barrel.accelTime (.2);
			$how3_barrel.decelTime (.2);

			$how3_barrel.move ( UP, 10 );
			$how3_catcher.move ( UP, 10 );
			sys.waitFor ($how3_barrel);
			sys.wait (ran1+1);

			//move the barrel upwards slowly
			$how3_barrel.time (3+ran2);
			$how3_barrel.accelTime (0);
			$how3_barrel.decelTime (2);

			$how3_barrel.startSoundShader ("mset2_movement", SND_CHANNEL_VOICE);
			$how3_barrel.move ( UP, 128 );
			sys.waitFor ($how3_barrel);
			$how3_barrel.stopSound ( SND_CHANNEL_VOICE, false );
			$how3_barrel.startSoundShader ("mset2_stop", SND_CHANNEL_VOICE2);

			//fire the barrel backwards quickly
			$how3_barrel.time (.25);
			$how3_barrel.accelTime (.2);
			$how3_barrel.decelTime (0);

			$how3_barrel.startSoundShader ("msmall_pounder", SND_CHANNEL_ANY);
			$how3_barrel.move ( DOWN, 128 );
			sys.waitFor ($how3_barrel);

			//catch the barrel in the catcher... down 8
			$how3_catcher.time (.1);
			$how3_catcher.accelTime (0);
			$how3_catcher.decelTime (.1);

			$how3_barrel.time (.1);
			$how3_barrel.accelTime (0);
			$how3_barrel.decelTime (.1);

			$how3_barrel.move ( DOWN, 10 );
			$how3_catcher.move ( DOWN, 10 );
			//sys.trigger ($how3_steam_1);
			sys.waitFor ($how3_barrel);
		}
	}



	////////////////////////////////////////////////////
	//
	//	point to point pipe piston movement
	//
	////////////////////////////////////////////////////
	void pipe_piston_move()
	{
		//setup 
		$pipe_piston_p2p.time (.4);
		$pipe_piston_p2p.accelTime (.1);
		$pipe_piston_p2p.decelTime (.15);
		$pipe_piston_p1p.time (.7);
		$pipe_piston_p1p.accelTime (.1);
		$pipe_piston_p1p.decelTime (.15);
		$pipe_piston_p3p.time (.35);
		$pipe_piston_p3p.accelTime (.1);
		$pipe_piston_p3p.decelTime (.15);

		while (1){
			$pipe_piston_p1p.moveTo ( $p1p1 );
			$pipe_piston_p2p.moveTo ( $p2p2 );
			$pipe_piston_p3p.moveTo ( $p3p1 );
			sys.waitFor($pipe_piston_p2p);

			$pipe_piston_p1p.moveTo ( $p1p2 );
			$pipe_piston_p2p.moveTo ( $p2p1 );
			$pipe_piston_p3p.moveTo ( $p3p2 );
			sys.waitFor($pipe_piston_p2p);
		}
	}



	////////////////////////////////////////////////////
	//
	//	piston movement
	//
	////////////////////////////////////////////////////
	void crankshaft_move ()
	{
		while (1) //begin while
		{
		$mc_piston1.move ( REL_UP, 30 );
		$mc_pistrod1.rotateOnce ( '26.56 0 0' );
		$mc_piston2.move ( REL_DOWN, 30 );
		$mc_pistrod2.rotateOnce ( '-26.56 0 0' );
		$mc_piston3.move ( REL_UP, 30 );
		$mc_pistrod3.rotateOnce ( '26.56 0 0' );
		$mc_crankshaft.rotateOnce ( '90 0 0' );
		sys.waitFor ($mc_piston1);

		$mc_piston1.move ( REL_UP, 30 );
		$mc_pistrod1.rotateOnce ( '-26.56 0 0' );
		$mc_piston2.move ( REL_DOWN, 30 );
		$mc_pistrod2.rotateOnce ( '26.56 0 0' );
		$mc_piston3.move ( REL_UP, 30 );
		$mc_pistrod3.rotateOnce ( '-26.56 0 0' );
		$mc_crankshaft.rotateOnce ( '90 0 0' );
		sys.waitFor ($mc_piston1);

		$mc_piston1.move ( REL_DOWN, 30 );
		$mc_pistrod1.rotateOnce ( '-26.56 0 0' );
		$mc_piston2.move ( REL_UP, 30 );
		$mc_pistrod2.rotateOnce ( '26.56 0 0' );
		$mc_piston3.move ( REL_DOWN, 30 );
		$mc_pistrod3.rotateOnce ( '-26.56 0 0' );
		$mc_crankshaft.rotateOnce ( '90 0 0' );
		sys.waitFor ($mc_piston1);

		$mc_piston1.move ( REL_DOWN, 30 );
		$mc_pistrod1.rotateOnce ( '26.56 0 0' );
		$mc_piston2.move ( REL_UP, 30 );
		$mc_pistrod2.rotateOnce ( '-26.56 0 0' );
		$mc_piston3.move ( REL_DOWN, 30 );
		$mc_pistrod3.rotateOnce ( '26.56 0 0' );
		$mc_crankshaft.rotateOnce ( '90 0 0' );
		sys.waitFor ($mc_pistrod1);
		} //end while
	}



	////////////////////////////////////////////////////
	//
	//	little first room machine
	//
	////////////////////////////////////////////////////
	void lilfrm_move ()
	{
		$lilfrm_part1.time (.25);
		$lilfrm_part2.time (.4);
		$lilfrm_part3.time (.3);
		$lilfrm_part4.time (.35);
		$lilfrm_part5.time (.4);

		while (1) //begin main while
		{
		$lilfrm_part1.rotateOnce ( '0 0 2' );
		$lilfrm_part2.rotateOnce ( '0 0 2' );
		$lilfrm_part3.rotateOnce ( '0 0 -2' );
		$lilfrm_part4.rotateOnce ( '0 0 -2' );
		$lilfrm_part5.rotateOnce ( '0 0 -2' );
		sys.waitFor ($lilfrm_part1);
		$lilfrm_part1.rotateOnce ( '0 0 -2' );
		$lilfrm_part2.rotateOnce ( '0 0 -2' );
		$lilfrm_part3.rotateOnce ( '0 0 2' );
		$lilfrm_part4.rotateOnce ( '0 0 2' );
		$lilfrm_part5.rotateOnce ( '0 0 2' );
		sys.waitFor ($lilfrm_part1);
		} //end main while
	}



	////////////////////////////////////////////////////
	//
	//	red light thing 
	//
	////////////////////////////////////////////////////
	void redthing_move ()
	{
		$redthing_mover.time ( 1 );
		$redthing_mover.accelTime ( .25 );
		$redthing_mover.decelTime ( .25 );

		float ran1;

		while (1) //begin main while
		{
		ran1=sys.random(3);
		
		if (ran1<1){
			$redthing_mover.moveTo ($redlightpoint_1);
			sys.waitFor ($redthing_mover);
		} else if (ran1<2) {
			$redthing_mover.moveTo ($redlightpoint_2);
			sys.waitFor ($redthing_mover);
		} else {
			$redthing_mover.moveTo ($redlightpoint_3);
			sys.waitFor ($redthing_mover);
		}

		} //end main while
	}


	////////////////////////////////////////////////////
	//
	//	underarm_can_1_manip
	//
	////////////////////////////////////////////////////
	void underarm_can_1_manip()
	{
		if (underarm_work_state == 0){
			return;
		}

		//move to sopt can 1
		
		thread mover_startsound ($underarm_carrier);
		
		$underarm_carrier.moveTo ($underarm_spot_can1);
		sys.waitFor ($underarm_carrier);
		mover_stopsound ($underarm_carrier);


		if (underarm_work_state == 0){
			return;
		}

		//arm down 
		$underarm_upper.startSoundShader ("servo_1s_01", SND_CHANNEL_VOICE );
		$underarm_upper.rotateOnce ( '0 0 -90' );
		$underarm_lower.startSoundShader ("servo_1s_02", SND_CHANNEL_VOICE );
		$underarm_lower.rotateOnce ( '0 0 90' );
		sys.waitFor ($underarm_lower);

		//fingers to down pose
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state > -64 ){
			$underarm_fingers.move ( DOWN, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state -= 1;
		}

		//bind can 1 to fingers
		$underarm_can_1.bind ($underarm_fingers);

		//fingers to up pose
		$underarm_tube.startSoundShader ("airwhomp", SND_CHANNEL_VOICE2 );
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state < 0 ){
			$underarm_fingers.move ( UP, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state += 1;
		}

		//do something interesting
		$underarm_tube.startSoundShader ("something_interesting", SND_CHANNEL_VOICE );
		thread crossFadeEnt ($underarm_tube, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_tube_light, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_can_1, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_can_1_light, '1 0 0', '.5 1 1', 1.75);
		
		sys.wait (2);

		//fingers to down pose
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		$underarm_tube.startSoundShader ("something_interesting_2", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state > -64 ){
			$underarm_fingers.move ( DOWN, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state -= 1;
		}

		//unbind can 1 from fingers
		$underarm_can_1.unbind ();

		
		//fingers to up pose
		
		
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state < 0 ){
			$underarm_fingers.move ( UP, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state += 1;
		}

		//turn tube back to red
		
		thread crossFadeEnt ($underarm_tube, '.5 1 1', '1 0 0', 1.75);
		thread crossFadeEnt ($underarm_tube_light, '.5 1 1', '1 0 0', 1.75);
		thread crossFadeEnt ($underarm_can_1, '.5 1 1', '1 0 0', 2);
		thread crossFadeEnt ($underarm_can_1_light, '.5 1 1', '1 0 0', 2);
		
		//arm up
		$underarm_upper.startSoundShader ("servo_1s_01", SND_CHANNEL_VOICE );
		$underarm_upper.rotateOnce ( '0 0 90' );
		$underarm_lower.startSoundShader ("servo_1s_02", SND_CHANNEL_VOICE );
		$underarm_lower.rotateOnce ( '0 0 -90' );
		sys.waitFor ($underarm_lower);
	}



	////////////////////////////////////////////////////
	//
	//	underarm_can_2_manip
	//
	////////////////////////////////////////////////////
	void underarm_can_2_manip()
	{
		if (underarm_work_state == 0){
			return;
		}

		//move to sopt can 2

		thread mover_startsound ($underarm_carrier);

		$underarm_carrier.moveTo ($underarm_spot_can2);
		sys.waitFor ($underarm_carrier);
		mover_stopsound ($underarm_carrier);
		
		if (underarm_work_state == 0){
			return;
		}

		//arm down 
		$underarm_upper.startSoundShader ("servo_1s_01", SND_CHANNEL_VOICE );
		$underarm_upper.rotateOnce ( '0 0 -90' );
		$underarm_lower.startSoundShader ("servo_1s_02", SND_CHANNEL_VOICE );
		$underarm_lower.rotateOnce ( '0 0 90' );
		sys.waitFor ($underarm_lower);

		//fingers to down pose
		while ( underarm_fingers_state > -64 ){
			$underarm_fingers.move ( DOWN, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state -= 1;
		}

		//bind can 2 to fingers
		$underarm_can_2.bind ($underarm_fingers);

		//fingers to up pose
		$underarm_tube.startSoundShader ("airwhomp", SND_CHANNEL_VOICE2 );
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state < 0 ){
			$underarm_fingers.move ( UP, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state += 1;
		}

		//do something interesting
		$underarm_tube.startSoundShader ("something_interesting", SND_CHANNEL_VOICE );
		thread crossFadeEnt ($underarm_tube, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_tube_light, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_can_2, '1 0 0', '.5 1 1', 1.75);
		thread crossFadeEnt ($underarm_can_2_light, '1 0 0', '.5 1 1', 1.75);

		sys.wait (2);

		//fingers to down pose
		$underarm_fingers.startSoundShader ( "mech_fingers_1_5s", SND_CHANNEL_VOICE );
		$underarm_tube.startSoundShader ( "something_interesting_2", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state > -64 ){
			$underarm_fingers.move ( DOWN, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state -= 1;
		}

		//unbind can 2 from fingers
		$underarm_can_2.unbind ();

		//fingers to up pose
		
		
		$underarm_fingers.startSoundShader ("mech_fingers_1_5s", SND_CHANNEL_VOICE );
		while ( underarm_fingers_state < 0 ){
			$underarm_fingers.move ( UP, 1 );
			sys.waitFor ($underarm_fingers);
			underarm_fingers_state += 1;
		}

		//turn tube back to red
		
		thread crossFadeEnt ($underarm_tube, '.5 1 1', '1 0 0', 1.75);
		thread crossFadeEnt ($underarm_tube_light, '.5 1 1', '1 0 0', 1.75);
		thread crossFadeEnt ($underarm_can_2, '.5 1 1', '1 0 0', 2);
		thread crossFadeEnt ($underarm_can_2_light, '.5 1 1', '1 0 0', 2);
		
		//arm up
		$underarm_upper.startSoundShader ("servo_1s_01", SND_CHANNEL_VOICE );
		$underarm_upper.rotateOnce ( '0 0 90' );
		$underarm_lower.startSoundShader ("servo_1s_02", SND_CHANNEL_VOICE );
		$underarm_lower.rotateOnce ( '0 0 -90' );
		sys.waitFor ($underarm_lower);
	}

	////////////////////////////////////////////////////
	//
	//	underarm_store
	//	stops underarm from doing it's thing and
	//	then moves it away to it's store spot
	//
	////////////////////////////////////////////////////
	void underarm_store ()
	{
		//move to corner spot
		$underarm_carrier.moveTo ($underarm_spot_corner);
		sys.waitFor ($underarm_carrier);

		//rotate around corner
		$underarm_carrier.rotateOnce ( '0 90 0' );
		sys.waitFor ($underarm_carrier);

		//move to storage spot
		$underarm_carrier.moveTo ($underarm_spot_store);
		sys.waitFor ($underarm_carrier);
	}



	////////////////////////////////////////////////////
	//
	//	underarm_work
	//	arm moves from spot to spot and does it's thing
	//
	////////////////////////////////////////////////////
	void underarm_work ()
	{
		while ( underarm_work_state == 1 ){
			map_mc_underground::underarm_can_1_manip();
			sys.wait(.1);
			map_mc_underground::underarm_can_2_manip();
			sys.wait(.1);
		}
		//sys.print ("Underarm finishing it's work before storage...\n");

		map_mc_underground::underarm_store ();
		map_mc_underground::saftey_bridge_forth();
	}



	////////////////////////////////////////////////////
	//
	//	underarm_work_state_off
	//	state that tells underarm to stop working
	//
	////////////////////////////////////////////////////
	void underarm_work_state_off ()
	{
		sys.wait( 1 );
		underarm_work_state = 0;

		sys.wait( 2 );
		sys.trigger( $computer_bridgeext7sec_speaker );
	}

	////////////////////////////////////////////////////
	//
	//	underarm_work_state_on
	//	state that tells underarm to stop working
	//
	////////////////////////////////////////////////////
	void underarm_work_state_on ()
	{
		//bridge away
		map_mc_underground::saftey_bridge_away ();

		//bring arm back around the bend
		//move to corner spot
		$underarm_carrier.moveTo ($underarm_spot_corner);
		sys.waitFor ($underarm_carrier);

		//rotate around corner
		$underarm_carrier.rotateOnce ( '0 -90 0' );
		sys.waitFor ($underarm_carrier);

		//underarm back to work
		underarm_work_state = 1;
		map_mc_underground::underarm_work();
	}

	
	////////////////////////////////////////////////////
	//
	//	Crane load damage off
	//
	////////////////////////////////////////////////////
	void crane_load_damage_off ()
	{
	//turn the damage off the movers
		$crane_box1.enableDamage( 0 );
		$crane_box2.enableDamage( 0 );
		$crane_box3.enableDamage( 0 );
		$crane_box4.enableDamage( 0 );
		$crane_beam1.enableDamage( 0 );
		$crane_beam2.enableDamage( 0 );
		$crane_beam3.enableDamage( 0 );
		$crane_beam4.enableDamage( 0 );
		$crane_beam5.enableDamage( 0 );
	}


	////////////////////////////////////////////////////
	//
	//	Crane drop the load
	//
	////////////////////////////////////////////////////
	void crane_drop ()
	{
		$platform.startSoundShader ("wiresnap", SND_CHANNEL_BODY );
		$breaking_wires.remove();
		
		sys.trigger ($speaker_crane_fall);
		
		$platform.time( 1.0 );
		$platform.accelTime( 0.1 );
		$platform.decelTime( 0.5 );
		
		$platform.startSoundShader ("steelswing_01", SND_CHANNEL_VOICE );
		
		$platform.rotateOnce( '-150 0 0' );					// Swing Sound
		sys.waitFor( $platform );

		//trigger the rail to break
		sys.trigger($pi_cave_rail);
		
		$wires.time( 1.5 );
		$wires.accelTime( 0.25 );
		$wires.decelTime( 0.25 );
		$platform.time( 1.5 );
		$platform.accelTime( 0.25 );
		$platform.decelTime( 0.25 );
		$wires.rotateOnce( '50 0 0' );
		
		$platform.startSoundShader ("steelswing_02", SND_CHANNEL_VOICE2 );
		
		$platform.rotateOnce( '105 0 0' );					// Swing Sound
		sys.waitFor( $platform );

		$wires.time( 1.1 );
		$wires.accelTime( 0.2 );
		$wires.decelTime( 0.2 );
		$platform.time( 1.1 );
		$platform.accelTime( 0.2 );
		$platform.decelTime( 0.2 );
		$wires.rotateOnce( '-30 0 0' );
		
		$platform.startSoundShader ("steelswing_03", SND_CHANNEL_BODY2 );
		
		$platform.rotateOnce( '-75 0 0' );					// Swing sound
		
		sys.waitFor( $platform );

		$wires.time( 0.8 );
		$wires.accelTime( 0.15 );
		$wires.decelTime( 0.15 );
		$platform.time( 0.6 );
		$platform.accelTime( 0.1 );
		$platform.decelTime( 0.1 );
		$wires.rotateOnce( '10 0 0' );
		
		$platform.startSoundShader ("steelswing_04", SND_CHANNEL_VOICE );
		
		$platform.rotateOnce( '30 0 0' );					// Swing sound
		sys.waitFor( $platform );

		//turn the damage off the movers
		thread map_mc_underground::crane_load_damage_off();

		$platform.time( 1.0 );
		$platform.accelTime( 0.2 );
		$platform.decelTime( 0.2 );
		
		$platform.startSoundShader ("steelswing_05", SND_CHANNEL_VOICE );
		
		$platform.rotateOnce( '-30 0 0' );					// Swing sound
		sys.waitFor( $platform );

	}


	////////////////////////////////////////////////////
	//
	//	Open airlock door
	//
	////////////////////////////////////////////////////
	void airlock_door_open( float airlock, float doornum )
	{
		entity ent;
		entity entdoorr, entdoorl;
		entity speaker;
		string door1;
		string door2;
		float  portalstate;
		float  movedist;

		if ( doornum == 2 ) {
			door1 = "airlock" + airlock + "_door2";
			door2 = "airlock" + airlock + "_door1";
			portalstate = 2;
			movedist = -16;
		} else {
			door1 = "airlock" + airlock + "_door1";
			door2 = "airlock" + airlock + "_door2";
			portalstate = 1;
			movedist = 16;
		}

		//turn door1 light on and door2 light off
		ent=sys.getEntity( door2 + "_light" );
		thread crossFadeEnt( ent, '.84 .84 .9', '0.37 0.05 0.01', 1 );
		
		sys.wait(1);

		ent=sys.getEntity( door1 + "_light" );
		thread crossFadeEnt( ent, '0.37 0.05 0.01', '.84 .84 .9', 1 );

		//move the 4 locks to unlock position
		ent=sys.getEntity( door1 + "_top_lock" );
		ent.time( 0.25 );
		ent.move( UP, 15 );

		speaker=sys.getEntity( "speaker_" + door1 + "_bottom_lock" );
		sys.trigger( speaker );
 
		ent=sys.getEntity( door1 + "_bottom_lock" );
		ent.time( 0.25 );
		ent.move( DOWN, 15 );

		sys.waitFor( ent );

		speaker=sys.getEntity( "speaker_" + door1 + "_left_lock" );
		sys.trigger( speaker );

		ent=sys.getEntity( door1 + "_left_lock" );
		ent.time( 0.75 );
		ent.move( SOUTH, movedist );

		speaker=sys.getEntity( "speaker_" + door1 + "_right_lock" );
		sys.trigger( speaker );

		ent=sys.getEntity( door1 + "_right_lock" );
		ent.time( 0.75 );
		ent.move( SOUTH, movedist );

		sys.waitFor( ent );

		//open doors
		speaker=sys.getEntity( "speaker_" + door1 + "_open" );
		sys.trigger( speaker );

		entdoorl=sys.getEntity( door1 + "_left" );
		entdoorl.time( 1.2 );
		entdoorl.rotateOnce( '0 45 0' );

		entdoorr=sys.getEntity( door1 + "_right" );
		entdoorr.time( 1.2 );
		entdoorr.rotateOnce( '0 -45 0' );

		//trigger the portal
		ent=sys.getEntity( door1 + "_portal" );
		sys.trigger( ent );

		sys.waitFor( entdoorr );
		sys.waitFor( entdoorl );

		//set airlock state
		ent=sys.getEntity( "airlock" + airlock + "_door1_portal" );
		ent.setKey( "state", portalstate );

	}


	////////////////////////////////////////////////////
	//
	//	Close airlock door
	//
	////////////////////////////////////////////////////
	void airlock_door_close(float airlock, float doornum )
	{
		entity ent;
		entity entdoorr, entdoorl;
		entity speaker;
		string door;
		float  movedist;

		if ( doornum == 2 ) {
			door = "airlock" + airlock + "_door2";
			movedist = 16;
		} else {
			door = "airlock" + airlock + "_door1";
			movedist = -16;
		}

		//close doors

		speaker= sys.getEntity( "speaker_" + door + "_close" );
		sys.trigger (speaker);

		entdoorl=sys.getEntity ( door + "_left" );
		entdoorl.time (1.2);
		entdoorl.rotateOnce ( '0 -45 0' );

		entdoorr=sys.getEntity ( door + "_right" );
		entdoorr.time (1.2);
		entdoorr.rotateOnce ( '0 45 0' );

		sys.waitFor (entdoorr);
		sys.waitFor (entdoorl);

		//trigger the portal
		ent=sys.getEntity ( door + "_portal" );
		sys.trigger (ent);

		//move the 4 locks to unlock position
		ent=sys.getEntity ( door + "_top_lock" );
		ent.time (0.25);
		ent.move ( DOWN, 15 );

		speaker=sys.getEntity ("speaker_" + door + "_bottom_lock");
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_bottom_lock" );
		ent.time (0.25);
		ent.move ( UP, 15 );
		
		speaker=sys.getEntity ("speaker_" + door + "_left_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_left_lock" );
		ent.time (0.75);
		ent.move ( SOUTH, movedist );

		speaker=sys.getEntity ("speaker_" + door + "_right_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_right_lock" );
		ent.time (0.75);
		ent.move ( SOUTH, movedist );

		sys.waitFor (ent);

}


	////////////////////////////////////////////////////
	//
	//	Main Activate airlock
	//	conditionally chooses based on entrance
	//
	////////////////////////////////////////////////////
	void airlock_main_activate(float airlock)
	{
		entity ent;

		//check to see which way the palyer entered by checking the airlock_state
		//if 1 then close 1 and open 2

		ent=sys.getEntity ("airlock" + airlock + "_door1_portal" );
			
		if (ent.getFloatKey ("state")==1) {
			airlock_door_close( airlock, 1 );
			airlock_door_open( airlock, 2 );

		} else { //else close 2 and open 1
			airlock_door_close( airlock, 2 );
			airlock_door_open( airlock, 1 );
		}
	}



	////////////////////////////////////////////////////
	//
	//	AIRLOCK main activation
	//	
	////////////////////////////////////////////////////
	void airlock1_activate()
	{
		//disable the guis on the doors
		$airlock1_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock1_door2_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock1_innerguiholder.setGuiParm ( "gui_parm11" , 0);
	
		airlock_main_activate(1);

		//check the airlock state and enable the guis on the closed door
		if ($airlock1_door1_portal.getFloatKey ("state")==1) {
			$airlock1_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock1_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock1_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}
	
	void airlock2_activate()
	{
		//disable the guis on the doors
		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 0);

		airlock_main_activate(2);

		//check the airlock state and enable the guis on the closed door
		if ($airlock2_door1_portal.getFloatKey ("state")==1) {
			$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}


	////////////////////////////////////////////////////
	//
	//	AIRLOCK doors opening
	//	
	////////////////////////////////////////////////////
	void airlock1_door1_open()
	{
		airlock_door_open(1, 1);
	}

	void airlock1_door2_open()
	{
		airlock_door_open(1, 2);
	}

	void airlock2_door1_open()
	{
		airlock_door_open(2, 1);
	}

	void airlock2_door2_open()
	{
		airlock_door_open(2, 2);
	}



	////////////////////////////////////////////////////
	//
	//	Break Zombie airlock door
	//
	////////////////////////////////////////////////////
	void airlock1_break()
	{
		//unhide the clip that will prevent the player from getting outside
		//once the gui is pressed
		sys.trigger( $airlock_break_clip );

		airlock_door_close( 1, 2 );
		
		//disable the gui on door1
		$airlock1_door1_gui.setGuiParm ( "gui_parm1" , 0);

		//turn door1 light on and door2 light off
		thread crossFadeEnt ($airlock1_door2_light, '.84 .84 .9', '0.37 0.05 0.01', 1);
		sys.wait(1);
		thread crossFadeEnt ($airlock1_door1_light, '0.37 0.05 0.01', '.84 .84 .9', 1);

		//move the 4 locks to unlock position
		$airlock1_door1_top_lock.time (0.25);
		$airlock1_door1_top_lock.move ( UP, 15 );
		
		$airlock1_door1_bottom_lock.time (0.25);
		sys.trigger ($speaker_airlock1_door1_bottom_lock);
		$airlock1_door1_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock1_door1_bottom_lock);

		$airlock1_door1_left_lock.time (0.75);
		sys.trigger ($speaker_airlock1_door1_left_lock);
		
		$airlock1_door1_left_lock.move ( SOUTH, 16 );
		$airlock1_door1_right_lock.time (0.75);
		
		sys.trigger ($speaker_airlock1_door1_right_lock);
		$airlock1_door1_right_lock.move ( SOUTH, 16 );
		
		sys.waitFor ($airlock1_door1_right_lock);

		//trigger the portal
		sys.trigger ($airlock1_door1_portal);

		//lightswitch to sound flicker light
		sys.trigger ($airlock1_door1_light);
		//sys.trigger ($airlockzombielight);

		//trigger anim shit
		sys.trigger ($airlockzombietrigger);

		//spark
		sys.trigger ($airlockzombiespark1);

		//doors open a bit then stutter a bit leaving the crack in the door
		$airlock1_door1_left.time(.4);
		$airlock1_door1_right.time(.4);
		sys.trigger ($speaker_malfunction_1);
		$airlock1_door1_left.rotateOnce ( '0 4 0' );
		$airlock1_door1_right.rotateOnce ( '0 -4 0' );
		sys.waitFor ($airlock1_door1_right);
		
		$airlock1_door1_left.time(.3);
		$airlock1_door1_right.time(.3);
		sys.trigger ($speaker_malfunction_2);
		$airlock1_door1_left.rotateOnce ( '0 -3 0' );
		$airlock1_door1_right.rotateOnce ( '0 3 0' );
		sys.waitFor ($airlock1_door1_right);
		
		$airlock1_door1_left.time(.3);
		$airlock1_door1_right.time(.3);
		sys.trigger ($speaker_malfunction_2a);
		$airlock1_door1_left.rotateOnce ( '0 10 0' );
		$airlock1_door1_right.rotateOnce ( '0 -3 0' );
		sys.waitFor ($airlock1_door1_right);
		
		$airlock1_door1_left.time(.25);
		$airlock1_door1_right.time(.25);
		sys.trigger ($speaker_malfunction_3);
		$airlock1_door1_left.rotateOnce ( '0 -5 0' );
		$airlock1_door1_right.rotateOnce ( '0 -3 0' );
		sys.waitFor ($airlock1_door1_right);

		//spark
		sys.trigger ($airlockzombiespark2);
		sys.trigger ($airlockzombiespark1);

		//trigger light to go off completely 
		//sys.trigger ($airlockzombielight);

		sys.wait( 2 );

		//trigger garage skull fly through
		sys.trigger( $garagelight_break_relay );
		sys.trigger( $garageskulltrigger );

		//wait 
		sys.wait( 4 );

		//spark
		sys.trigger( $airlockzombiespark2 );
		sys.trigger( $airlockzombiespark1 );

		//wait 
		sys.wait(1);

		//open one door fully to allow the player to exit the airlock
		$airlock1_door1_right.time(1.2);
		sys.trigger ($speaker_airlock1_door1_open);
		
		$airlock1_door1_right.rotateOnce ( '0 -38 0' );

	}


	////////////////////////////////////////////////////
	//
	//	piston movement
	//
	////////////////////////////////////////////////////
	void piston_move ()
	{
		while (1) //begin while
		{
		
		$piston1.move ( DOWN, 6 );
		$pistrod1.rotateOnce ( '0 0 -26.56' );
		$piston2.move ( UP, 6 );
		$pistrod2.rotateOnce ( '0 0 26.56' );
		$piston3.move ( DOWN, 6 );
		$pistrod3.rotateOnce ( '0 0 -26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( DOWN, 6 );
		$pistrod1.rotateOnce ( '0 0 26.56' );
		$piston2.move ( UP, 6 );
		$pistrod2.rotateOnce ( '0 0 -26.56' );
		$piston3.move ( DOWN, 6 );
		$pistrod3.rotateOnce ( '0 0 26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( UP, 6 );
		$pistrod1.rotateOnce ( '0 0 26.56' );
		$piston2.move ( DOWN, 6 );
		$pistrod2.rotateOnce ( '0 0 -26.56' );
		$piston3.move ( UP, 6 );
		$pistrod3.rotateOnce ( '0 0 26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( UP, 6 );
		$pistrod1.rotateOnce ( '0 0 -26.56' );
		$piston2.move ( DOWN, 6 );
		$pistrod2.rotateOnce ( '0 0 26.56' );
		$piston3.move ( UP, 6 );
		$pistrod3.rotateOnce ( '0 0 -26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		} //end while

	}



	////////////////////////////////////////////////////
	//
	//	canister mover
	//
	////////////////////////////////////////////////////
	void canister_mover ()
	{
		sys.wait (2);
		$canismover_rdoor.time (1);
		$canismover_ldoor.time (1);

		while (1) //begin while
		{
			//back into recess 192
			sys.trigger ($speaker_can1_move);					// SOUND
			$canismover_anchor.time (2);
			$canismover_anchor.accelTime (2);
			$canismover_anchor.decelTime (0);
			
			$canismover_anchor.move ( WEST, 192 );
			sys.waitFor ($canismover_anchor);
			
			//close doors (move 24)
			sys.trigger ($speaker_candoor1_close);				// SOUND
			$canismover_rdoor.move (NORTH, -24);
			$canismover_ldoor.move (NORTH, 24);
			sys.waitFor ($canismover_ldoor);

			//hide it all
			$canismover.hide ();
			$func_static_5240.hide ();
			$func_static_5239.hide ();
			$light_5120.Off ();
			$func_static_5252.hide ();
			$light_5121.Off ();
			$func_static_5233.hide ();
			$light_5118.Off ();
			$light_5116.Off ();
			$func_static_5248.hide ();

			//wait after it goes behind the closed doors
			sys.wait (3);

			//bring it forward 192
			$canismover_anchor.time (.1);
			$canismover_anchor.accelTime (0);
			$canismover_anchor.decelTime (0);
			
			$canismover_anchor.move ( WEST, -192 );
			sys.waitFor ($canismover_anchor);
			
			//rotate it quickly 90 degs to down position
			$canismover_anchor.time (.1);
			$canismover_anchor.accelTime (0);
			$canismover_anchor.decelTime (0);

			
			$canismover_anchor.rotateOnce ( '90 0 0' );
			sys.waitFor ($canismover_anchor);

			//unhide it all
			$canismover.show ();
			$func_static_5240.show ();
			$func_static_5239.show ();
			$light_5120.On ();
			$func_static_5252.show ();
			$light_5121.On ();
			$func_static_5233.show ();
			$light_5118.On ();
			$light_5116.On ();
			$func_static_5248.show ();

			//open doors (move 24)
			sys.trigger ($speaker_candoor2_open);				// SOUND

			$canismover_rdoor.move (NORTH, 24);
			$canismover_ldoor.move (NORTH, -24);
			sys.waitFor ($canismover_ldoor);

			//rotate it up -90 degs 
			$canismover_anchor.time (2);
			$canismover_anchor.accelTime (2);
			$canismover_anchor.decelTime (0);
			
			sys.trigger ($speaker_can1_updown);					// SOUND
			
			$canismover_anchor.rotateOnce ( '-90 0 0' );
			sys.waitFor ($canismover_anchor);
	
			//bounce
			$canismover_anchor.time (.15);
			$canismover_anchor.accelTime (.15);
			$canismover_anchor.decelTime (0);
			$canismover_anchor.rotateOnce ( '1.5 0 0' );
			sys.waitFor ($canismover_anchor);

			$canismover_anchor.time (.15);
			$canismover_anchor.accelTime (0);
			$canismover_anchor.decelTime (.15);
			$canismover_anchor.rotateOnce ( '-1.5 0 0' );
			sys.waitFor ($canismover_anchor);

			$canismover_anchor.time (.10);
			$canismover_anchor.accelTime (.10);
			$canismover_anchor.decelTime (0);
			$canismover_anchor.rotateOnce ( '.5 0 0' );
			sys.waitFor ($canismover_anchor);

			$canismover_anchor.time (.10);
			$canismover_anchor.accelTime (0);
			$canismover_anchor.decelTime (.10);
			$canismover_anchor.rotateOnce ( '-.5 0 0' );
			sys.waitFor ($canismover_anchor);
					
			//twist it up 
			$canismover_anchor.time (4.5);
			$canismover_anchor.accelTime (1.5);
			$canismover_anchor.decelTime (1);

			sys.trigger ($speaker_can1_rot);					// SOUND
			$canismover_anchor.rotateOnce ( '0 0 540' );
			sys.waitFor ($canismover_anchor);

			sys.wait (0.5);

			sys.trigger ($speaker_can1_rot);					// SOUND
			$canismover_anchor.rotateOnce ( '0 0 -540' );
			sys.waitFor ($canismover_anchor);

		} //end while

	}


	////////////////////////////////////////////////////
	//
	//	canister2 mover 
	//
	////////////////////////////////////////////////////
	void canister2_mover ()
	{
		sys.wait (6);
		$canismover2_rdoor.time (1);
		$canismover2_ldoor.time (1);
		while (1) //begin while
		{
			//back into recess 192
			$canismover2_anchor.time (2);
			$canismover2_anchor.accelTime (2);
			$canismover2_anchor.decelTime (0);
			
			sys.trigger ($speaker_can2_move);					// SOUND
			$canismover2_anchor.move ( WEST, 192 );
			sys.waitFor ($canismover2_anchor);
			
			//close doors (move 24)
			sys.trigger ($speaker_candoor2_close);				// SOUND
			$canismover2_rdoor.move (NORTH, -24);
			$canismover2_ldoor.move (NORTH, 24);
			sys.waitFor ($canismover2_ldoor);

			//hide it all
			$canismover2.hide ();
			$func_static_52402.hide ();
			$func_static_52392.hide ();
			$light_51202.Off ();
			$func_static_52522.hide ();
			$light_51212.Off ();
			$func_static_52332.hide ();
			$light_51182.Off ();
			$light_51162.Off ();
			$func_static_52482.hide ();

			//wait after it goes behind the closed doors
			sys.wait (3);

			//bring it forward 192
			$canismover2_anchor.time (.1);
			$canismover2_anchor.accelTime (0);
			$canismover2_anchor.decelTime (0);
			
			$canismover2_anchor.move ( WEST, -192 );
			sys.waitFor ($canismover2_anchor);
			
			//rotate it quickly 90 degs to down position
			$canismover2_anchor.time (.1);
			$canismover2_anchor.accelTime (0);
			$canismover2_anchor.decelTime (0);

			$canismover2_anchor.rotateOnce ( '90 0 0' );
			sys.waitFor ($canismover2_anchor);

			//unhide it all
			$canismover2.show ();
			$func_static_52402.show ();
			$func_static_52392.show ();
			$light_51202.On ();
			$func_static_52522.show ();
			$light_51212.On ();
			$func_static_52332.show ();
			$light_51182.On ();
			$light_51162.On ();
			$func_static_52482.show ();

			//open doors (move 24)
			$canismover2_rdoor.move (NORTH, 24);
			$canismover2_ldoor.move (NORTH, -24);
			sys.trigger ($speaker_candoor2_open);				// SOUND
			
			sys.waitFor ($canismover2_ldoor);

			//rotate it up -90 degs 
			$canismover2_anchor.time (2);
			$canismover2_anchor.accelTime (2);
			$canismover2_anchor.decelTime (0);
			
			sys.trigger ($speaker_can2_updown);					// SOUND
			$canismover2_anchor.rotateOnce ( '-90 0 0' );
			sys.waitFor ($canismover2_anchor);
	
			//bounce
			$canismover2_anchor.time (.15);
			$canismover2_anchor.accelTime (.15);
			$canismover2_anchor.decelTime (0);
			$canismover2_anchor.rotateOnce ( '1.5 0 0' );
			sys.waitFor ($canismover2_anchor);

			$canismover2_anchor.time (.15);
			$canismover2_anchor.accelTime (0);
			$canismover2_anchor.decelTime (.15);
			$canismover2_anchor.rotateOnce ( '-1.5 0 0' );
			sys.waitFor ($canismover2_anchor);

			$canismover2_anchor.time (.10);
			$canismover2_anchor.accelTime (.10);
			$canismover2_anchor.decelTime (0);
			$canismover2_anchor.rotateOnce ( '.5 0 0' );
			sys.waitFor ($canismover2_anchor);

			$canismover2_anchor.time (.10);
			$canismover2_anchor.accelTime (0);
			$canismover2_anchor.decelTime (.10);
			$canismover2_anchor.rotateOnce ( '-.5 0 0' );
			sys.waitFor ($canismover2_anchor);
					
			//twist it up 
			
			$canismover2_anchor.time (4.5);
			$canismover2_anchor.accelTime (1.5);
			$canismover2_anchor.decelTime (.3);

			sys.trigger ($speaker_can2_rot);
			$canismover2_anchor.rotateOnce ( '0 0 540' );
			sys.waitFor ($canismover2_anchor);

			sys.wait (0.5);

			sys.trigger ($speaker_can2_rot);
			$canismover2_anchor.rotateOnce ( '0 0 -540' );
			sys.waitFor ($canismover2_anchor);

		} //end while
	}



	////////////////////////////////////////////////////
	//
	//	After invasion
	//  Things that are triggered after the invasion
	//
	////////////////////////////////////////////////////
	void after_invasion ()
	{
		//unhide the exit elevator
		$light_51518.show();
        
		//steps busted by steam
		$preinvasion_steps.hide();
		$postinvasion_steps.show();

		$pi_steps_steamlight1.On();
		$pi_steps_steamlight2.On();

		sys.trigger ($pi_steps_steam1);
		sys.trigger ($pi_steps_steam2);

		sys.trigger($pi_stepsteamsound);

		//turn on the hazard lights
		$pi_hazlight_proj1.On();
		$pi_hazlight_proj2.On();
		$pi_hazlight_sml1.On();
		$pi_hazlight_sml2.On();

		$func_rotating_5.show();
		$func_rotating_6.show();

		sys.trigger($pi_hazspeaker);

		//impclawdoors
		$impclawdoor1.open();
		$impclawdoor2.open();
		$impclawdoor1.remove();
		$impclawdoor2.remove();

		$underground_impcrawl_door_3.show();
		$impclawdoorclip.show();

		//restore position of crane
		$crane_main.restorePosition();
		
		//crane load unbind so it can fall
		$crane_box1.unbind();
		$crane_box2.unbind();
		$crane_box3.unbind();
		$crane_box4.unbind();
		$crane_beam1.unbind();
		$crane_beam2.unbind();
		$crane_beam3.unbind();
		$crane_beam4.unbind();
		$crane_beam5.unbind();

		//unhide the cave railing
		$pi_cave_rail.show();

		//enable the bridge gui
		$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 1);
		
	}



	////////////////////////////////////////////////////
	//
	//	Fred stuff
	//
	////////////////////////////////////////////////////
	void guard_switch_head_to_zombie( entity self ) {
		self.setModel( "underground_invasion_zsechead" );
		//sys.print( "Swapping Head\n");
	}

	void sci_switch_head_to_stump( entity self ) {
		self.setModel( "underground_crazy_stump" );
		//sys.print( "Swapping Head\n");
	}

	void killzombie()
	{
		$monster_zombie_maint_1.kill();
	}

	////////////////////////////////////////////////////
	//
	//	swing the swinglight
	//
	////////////////////////////////////////////////////
	void swinglight_move ()
	{
		$swinglight_mover.sway( 120, 0, '0 0 60' );
	}

	////////////////////////////////////////////////////
	//
	//	drop_floor
	//
	////////////////////////////////////////////////////
	void drop_floor_down ()
	{
		//trigger the initial speaker
		sys.trigger ($speaker_drop_floor);

		$drop_floor.time(1);
		$drop_floor.accelTime(1);
		$drop_floor.decelTime(.2);

		//move drop_floor down
		$drop_floor.move (DOWN, 176);

		//trigger the weird sound
		sys.trigger($drop_floor_weird_speaker);
	}



	////////////////////////////////////////////////////
	//
	//	close security door
	//
	////////////////////////////////////////////////////
	void close_secdoor ()
	{
		$func_door_46.close ();
	}

	////////////////////////////////////////////////////
	//
	//	spooky_postinvasion1
	//
	//	Scenario that happens immediately after invasion
	//  cinematic.
	//
	////////////////////////////////////////////////////
	void postinvasion_spooky01_speakers_off ()
	{
		float j;
		entity ent;
		for (j=1; j<=11; j++)
		{
			ent = sys.getEntity ( "comm_speaker_" + j );
			ent.fadeSound ( SND_CHANNEL_ANY, -60, 2.5 );
		}
	}

	void postinvasion_spooky01_speakers_on ()
	{
		float j;
		entity ent;
		for (j=1; j<=11; j++)
		{
			ent = sys.getEntity ( "comm_speaker_" + j );
			ent.fadeSound ( SND_CHANNEL_ANY, 0, 2.5 );
		}
	}

	void postinvasion_spooky01_lights_off ()
	{
		float j;
		entity ent;
		for (j=1; j<=7; j++)
		{
			ent = sys.getEntity ( "comm_light_" + j );
			ent.fadeOutLight ( 2.5 );
		}
	}

	void postinvasion_spooky01_lights_on ()
	{
		float j;
		entity ent;
		for (j=1; j<=7; j++)
		{
			ent = sys.getEntity ( "comm_light_" + j );
			ent.fadeInLight ( 2.5 );
		}
	}

	void postinvasion_spooky01 ()
	{
		/* stuff I gotta trigger
		invasion_spectrum_relay
		invasion_floorskull_relay
		underground_crazy_zombie
		*/

		// XIAN: Inserted speaker function here...
		thread post_invasion_sounds();
		
		//close and lock the door
        $func_door_74.close ();
		sys.trigger ($invasion_door_lock_relay);

		//power out
		sys.trigger ($comm_speaker_powerout);
		thread postinvasion_spooky01_speakers_off();
		thread postinvasion_spooky01_lights_off();
		
		//wait for fades
		sys.wait (2.5);

		//trigger the suspense trigger
		
		sys.trigger ($comm_speaker_suspense);
		
		sys.wait (1);
		
		sys.trigger ($speaker_airush2);
		
		sys.wait (0.5);
		
		sys.trigger ($speaker_substing1);
		sys.trigger ($speaker_seq_invasion);			// comm chatter stuff from other people
														// on the base
		sys.wait (1);

		sys.trigger ($speaker_invasion_buildup);		// Trigger the 5 second buildup speaker
		sys.wait (4.8);

		// 5 second buildup here

		//trigger the skull from the floor
		sys.trigger ($invasion_floorskull_relay);
		
		sys.trigger ($speaker_appear);					// White column appearing in middle of room stinger
		sys.trigger ($speaker_hellblast_stinger);
		
		sys.wait (0.5);
		
		$speaker_appear.startSoundShader ("mc_hellblast_explosion", SND_CHANNEL_VOICE2);
		
		sys.wait (0.5);
		
		sys.trigger ($speaker_hellwind);
		
		//trigger spectrum bang
		sys.trigger ($invasion_spectrum_relay);
		
		sys.wait (2);					// Was 18 -Xian
		
		sys.trigger ($speaker_spookything);
		
		sys.wait (3);
		
		sys.trigger ($speaker_betruger_laugh);
		
		sys.wait (5);

		//trigger transformation
		//skull from wall transforms asian guy into zombie
		sys.trigger ($crazysci_relay_nextthing);
		
		sys.trigger ($speaker_leatherface);
		
		sys.wait (2);
		
		sys.trigger ($speaker_substing2);
		
		sys.wait (1);
		
		sys.trigger ($speaker_stereothing);
		
		sys.wait (1);

		//trigger the spooky looping sound that remains in the room after the invasion
		sys.trigger ($invasionspookyremain_speaker);

		//power back on
		sys.trigger ($comm_speaker_poweron);
		sys.wait (1);
		thread postinvasion_spooky01_lights_on();
		thread postinvasion_spooky01_speakers_on();	
		

		//trigger the gui that can be triggered on the middle desk
		sys.trigger ($func_static_4730);

		//trigger zombie security banging
		sys.trigger ($zsec_bang);

		//trigger first radio chatter
		sys.trigger ($rchat_1);
				
		sys.wait (2);
		
		$speaker_spookything.startSoundShader ("mc_substing_02", SND_CHANNEL_VOICE2 );
		
		sys.wait(2);
		sys.trigger ($rchat_7);
		sys.wait(3);

		//unlock and open door
		sys.trigger ($invasion_door_unlock_relay);
		
		//trigger zombie to come on in
		sys.trigger ($comm_zombie);

		//break light near guis
		sys.wait(3);
		sys.trigger ($comm_light_6);
	}

	void init_howitzer() {
		//howitzer setup
		$how1_barrel.bind ($how1_base);
		$how1_recep.bind ($how1_base);
		$how1_catcher.bind ($how1_base);
		$how1_base.rotateOnce ( '0 0 45' );

		$how2_barrel.bind ($how2_base);
		$how2_recep.bind ($how2_base);
		$how2_catcher.bind ($how2_base);
		$how2_base.rotateOnce ( '0 0 45' );

		$how3_barrel.bind ($how3_base);
		$how3_recep.bind ($how3_base);
		$how3_catcher.bind ($how3_base);
		$how3_base.rotateOnce ( '0 0 45' );

		sys.waitFor($how1_base);

		thread howitzer_1 ();
		thread howitzer_2 ();
		thread howitzer_3 ();

	}


	////////////////////////////////////////////////////
	//
	//	brooks gui triggers
	//
	////////////////////////////////////////////////////
	void brooks_guitouch ()
	{
		sys.trigger ($secpanel1);
	}

	void brooks_guiopen ()
	{
		$secpanel1.setGuiParm ( "gui_parm1" , 2);
	}


	////////////////////////////////////////////////////
	//
	//	Crane start sound 
	//
	////////////////////////////////////////////////////
	void crane_start_thread() {
		sys.trigger ($crane_start_speaker);
		sys.wait (1);
		$crane_main_speaker.On();
	}
	
	////////////////////////////////////////////////////
	//
	//	Crane Main Move Right
	//
	////////////////////////////////////////////////////
	void crane_main_right()
	{
		vector	delta,deltatest;
		vector	deltadif;

		sys.killthread ( "map_mc_underground::crane_main_left" );

		//set the dir state for correct stopping
		crane_dir = 1;

		//set crane times back to normal
		$crane_main.time (6);
		$crane_main.accelTime (3);
		$crane_main.decelTime (2);

		if ( crane_main_state < 90 ) {
			//start sound
			thread crane_start_thread();

			//start movement
			$crane_main.rotateOnce ( '0 -90 0' );
		
			while ( 1 ) {
				delta = anglemod360( $crane_main.getAngles() );
				deltatest = $crane_main.getAngles();
				crane_main_state = (270 - (int( delta_y )));
				//sys.print ("crane_main_state = " + crane_main_state + " " + deltatest +" \n");
				$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
				if (crane_main_state >= 89) {
					break;
				}
				sys.waitFrame();
			}
			
			//*****
			//stop movement
			//*****

			//stop sound
			$crane_main_speaker.Off();
			sys.trigger ($crane_end_speaker);

			//set crane times to accomodate stopping
			$crane_main.time (.5);
			$crane_main.accelTime (0);
			$crane_main.decelTime (.5);

			//the final move
			$crane_main.rotateOnce ( '0 -1 0' );
			sys.waitFor ($crane_main);
			
			//set crane times back to normal
			$crane_main.time (6);
			$crane_main.accelTime (3);
			$crane_main.decelTime (2);

			//set crane status and update guis
			crane_main_state = 90;
			//sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);

		}
	}

	////////////////////////////////////////////////////
	//
	//	Crane Main Move Left
	//	this should be redone for smoother movement
	//	especially since the player can remotely opperate
	//	the crane and see the jerky movement easily
	//
	////////////////////////////////////////////////////
	void crane_main_left()
	{
		vector	delta;
		vector	deltadif;

		sys.killthread ( "map_mc_underground::crane_main_right" );

		//set the dir state for correct stopping
		crane_dir = -1;

		//set crane times back to normal
		$crane_main.time (6);
		$crane_main.accelTime (3);
		$crane_main.decelTime (2);
		
		if ( crane_main_state > 0 ) {
			//start sound
			thread crane_start_thread();

			//start movement
			$crane_main.rotateOnce ( '0 90 0' );
		
			while ( 1 ) {
				delta = anglemod360( $crane_main.getAngles() );
				crane_main_state = (270 - (int( delta_y )));
				//sys.print ("crane_main_state = " + crane_main_state + " \n");
				$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
				if (crane_main_state <= 1) {
					break;
				}
				sys.waitFrame();
			}

			//*****
			//stop movement
			//*****

			//stop sound
			$crane_main_speaker.Off();
			sys.trigger ($crane_end_speaker);

			//set crane times to accomodate stopping
			$crane_main.time (.5);
			$crane_main.accelTime (0);
			$crane_main.decelTime (.5);

			//the final move
			$crane_main.rotateOnce ( '0 1 0' );
			sys.waitFor ($crane_main);
				
			//set crane times back to normal
			$crane_main.time (6);
			$crane_main.accelTime (3);
			$crane_main.decelTime (2);

			//update guis
			crane_main_state = 0;
			//sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
		}
	}


	////////////////////////////////////////////////////
	//
	//	Crane stop
	//
	////////////////////////////////////////////////////
	void crane_main_stop()
	{
		//sys.print ("enter crane_main_stop \n");
		vector	delta;

		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		
		//set crane times to accomodate stopping
		$crane_main.time (.3);
		$crane_main.accelTime (0);
		$crane_main.decelTime (.3);
		
		//stop movement
		if ( (crane_dir < 0) && (crane_main_state > 0) && (crane_main_state < 90) ) {
			$crane_main.rotateOnce ( '0 1 0' );
			sys.waitFor ($crane_main);
			delta = anglemod360( $crane_main.getAngles() );
			crane_main_state = (270 - (int( delta_y )));
			//sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
		} else if ( (crane_main_state > 0) && (crane_main_state < 90) ){
			$crane_main.rotateOnce ( '0 -1 0' );
			sys.waitFor ($crane_main);
			delta = anglemod360( $crane_main.getAngles() );
			crane_main_state = (270 - (int( delta_y )));
			//sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_remote_panel.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
		}

		//stop sound
		$crane_main_speaker.Off();
		sys.trigger ($crane_end_speaker);

		//set crane times back to normal
		$crane_main.time (6);
		$crane_main.accelTime (3);
		$crane_main.decelTime (2);
	}


	////////////////////////////////////////////////////
	//
	//	return radio chatter 1
	//
	////////////////////////////////////////////////////
	void radio_chat_1()
	{
		float ran1;

		ran1 = (3 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_8);
		ran1 = (3 + sys.random(5));
		sys.wait (ran1);

		sys.trigger ($rchat_2);
		ran1 = (8 + sys.random(6));
		sys.wait (ran1);

		sys.trigger ($rchat_3);
		ran1 = (15 + sys.random(6));
		sys.wait (ran1);

		sys.trigger ($rchat_4);
		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_5);
		ran1 = (12 + sys.random(6));
		sys.wait (ran1);

		sys.trigger ($rchat_6);
		ran1 = (8 + sys.random(8));
		sys.wait (ran1);

		sys.trigger ($rchat_7);
		ran1 = (15 + sys.random(3));
		sys.wait (ran1);
	}

	void radio_chat_2()
	{
		float ran1;

		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_9);
		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_10);
		ran1 = (8 + sys.random(6));
		sys.wait (ran1);

		sys.trigger ($rchat_11);
		ran1 = (8 + sys.random(8));
		sys.wait (ran1);

		sys.trigger ($rchat_12);
		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_13);
		ran1 = (8 + sys.random(5));
		sys.wait (ran1);
	}

	void radio_chat_3()
	{
		float ran1;

		ran1 = (0 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_14);
		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_15);
		ran1 = (8 + sys.random(5));
		sys.wait (ran1);

		sys.trigger ($rchat_2);
		ran1 = (8 + sys.random(8));
		sys.wait (ran1);
	}
	
	void radio_chat_4()
	{
		float ran1;

		ran1 = (4 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_1);
		ran1 = (8 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_3);
		ran1 = (8 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_4);
		ran1 = (12 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_5);
		ran1 = (15 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_6);
		ran1 = (8 + sys.random(9));
		sys.wait (ran1);
	}

	void radio_chat_5()
	{
		float ran1;

		ran1 = (4 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_7);
		ran1 = (4 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_8);
		ran1 = (4 + sys.random(4));
		sys.wait (ran1);

		sys.trigger ($rchat_9);
		ran1 = (8 + sys.random(5));
		sys.wait (ran1);

		sys.trigger ($rchat_10);
		ran1 = (3 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_11);
		ran1 = (8 + sys.random(3));
		sys.wait (ran1);

		sys.trigger ($rchat_12);
		ran1 = (12 + sys.random(5));
		sys.wait (ran1);

		sys.trigger ($rchat_13);
		ran1 = (8 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_14);
		ran1 = (2 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_15);
		ran1 = (12 + sys.random(5));
		sys.wait (ran1);

		sys.trigger ($rchat_1);
		ran1 = (4 + sys.random(9));
		sys.wait (ran1);

		sys.trigger ($rchat_3);
		ran1 = (8 + sys.random(4));
		sys.wait (ran1);

		sys.trigger ($rchat_4);
		ran1 = (4 + sys.random(9));
		sys.wait (ran1);
	}

	void radio_chat_stop()
	{
		sys.killthread ("map_mc_underground::radio_chat_1");
		sys.killthread ("map_mc_underground::radio_chat_2");
		sys.killthread ("map_mc_underground::radio_chat_3");
		sys.killthread ("map_mc_underground::radio_chat_4");
		sys.killthread ("map_mc_underground::radio_chat_5");
	}

	void fade_blinkypre_sound ()
	{
		$speaker_101.fadeSound ( SND_CHANNEL_ANY, -60, 3 );
	}

	void fade_scotty_sound ()
	{
		$scotty1.fadeSound ( SND_CHANNEL_ANY, -60, .1 );
	}

	void crazy_sci_becomeZombie( entity self ) {
		self.setTalkState( TALK_NEVER );
		self.setHealth( self.getFloatKey( "normal_health" ) );
		self.setKey( "snd_chatter_combat", self.getKey( "snd_chatter_combat_precache" ) );

		// causes the monster to reset his chatter sound.  hacky, but it does the job.
		self.show();
	}

	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void main ()
	{
		thread cache_sounds();
		thread canister_mover ();
		thread canister2_mover ();

		setup_objects ();
		thread saftey_bridge_away ();
		thread lilfrm_move ();
		thread rotary ();
		thread howitzer_1 ();
		thread howitzer_2 ();
		thread howitzer_3 ();
		thread pipe_piston_move ();
		thread crankshaft_move ();
		thread redthing_move ();
		thread underarm_work ();
		thread piston_move ();
		thread swinglight_move();

		//setup the airlocks in the correct states
		thread airlock1_door2_open();
		thread airlock2_door2_open();

		sys.wait(20);
		//disable the bridge gui
		$saftey_bridge_gui.setGuiParm ( "gui_parm1" , 0);

	}

}// namespace

//@doomscript-blueprint begin 6
//@source 87D31869
//@catalog 0C260740
//@node B832CE32-0 40 40
//@node 83A3378D-0 330 40
//@node F21913EA-0 610 40
//@node 795E90B4-0 890 40
//@node FA673F23-0 1170 40
//@node F53CAC1E-0 1450 40
//@node 72954FBC-0 1730 40
//@node 93661762-0 2010 40
//@node E6216550-0 2290 40
//@node 2D2D3157-0 2570 40
//@node 2DD8D124-0 2850 40
//@node D8283389-0 3130 40
//@node 79E45B37-0 3410 40
//@node 6DEA6A04-0 3690 40
//@node A9AA3F14-0 3970 40
//@node EB84EABE-0 4250 40
//@node E50EC844-0 4530 40
//@node DBE384AF-0 4810 40
//@node DB8ED66E-0 5090 40
//@node 583A0F75-0 5370 40
//@node 7DB0A95E-0 5650 40
//@node 0F36DF82-0 5930 40
//@node B5B6AB09-0 6210 40
//@node 962010DC-0 6490 40
//@node 3CC6EBD3-0 6770 40
//@node 705ECF76-0 7050 40
//@node 7A585EAA-0 7330 40
//@node 52FD4095-0 7610 40
//@node 84DD2670-0 7890 40
//@node DA83639A-0 8170 40
//@node 73666A41-0 8450 40
//@node CCE69EBA-0 8730 40
//@node 995158E8-0 40 40
//@node D085FAFE-0 330 40
//@node 62D40EEB-0 610 40
//@node FE9100BC-0 890 40
//@node 89A57B41-0 1170 40
//@node A44D1182-0 1450 40
//@node B760CF1F-0 1730 40
//@node 431DA7C0-0 2010 40
//@node 2BD79415-0 2290 40
//@node F466D044-0 40 40
//@node CA5263B4-0 330 40
//@node 46F65A20-0 610 40
//@node 4B63AAC8-0 890 40
//@node 3FC7A4DE-0 40 40
//@node CFDF7FE8-0 330 40
//@node 7AEA71C1-0 40 40
//@node 082FFFBE-0 330 40
//@node 1C36B19F-0 610 40
//@node C739E530-0 890 40
//@node C33F7D1C-0 1170 40
//@node 2B6FB777-0 1450 40
//@node 1A4142EB-0 1730 40
//@node B2729208-0 2010 40
//@node 4E65825D-0 1805 232
//@node AEFFEFEA-0 2290 40
//@node 350E3F8E-0 2085 232
//@node 41A8158D-0 2570 40
//@node 397EE64F-0 2365 232
//@node 05034B86-0 2850 40
//@node 2271A133-0 3130 40
//@node 9FADCD30-0 3410 40
//@node 90ADDF17-0 3690 40
//@node 95E8E03B-0 3970 40
//@node 92C27E74-0 4250 40
//@node 58FCBD37-0 4530 40
//@node B81E336F-0 4810 40
//@node E4BC2CCD-0 5090 40
//@node D30A21AB-0 5370 40
//@node 4FC1B827-0 5650 40
//@node 3BEB2335-0 5930 40
//@node 2EBC9823-0 6210 40
//@node 9C0D46E2-0 6490 40
//@node 3C471C02-0 6770 40
//@node 29C82937-0 7050 40
//@node A6932A8D-0 7330 40
//@node B22FCD22-0 7610 40
//@node B9C8D551-0 7890 40
//@node 8EF4EA26-0 8170 40
//@node E04BEA28-0 8450 40
//@node 373D48E3-0 8730 40
//@node 4E144040-0 9010 40
//@node 1C34F15B-0 9290 40
//@node D90DBB85-0 9570 40
//@node E199EFF6-0 9850 40
//@node 9D6B3A04-0 10130 40
//@node 23A01F6A-0 9925 145
//@node A629F7E9-0 9720 145
//@node E0DB56B3-0 10410 200
//@node D75CB87D-0 10690 200
//@node 5FD60441-0 10970 200
//@node A054380E-0 10765 305
//@node 135B6964-0 10560 305
//@node 0539413B-0 11250 40
//@node 8B48C4FF-0 11530 40
//@node 99897E8E-0 11810 40
//@node 791C57EF-0 12090 40
//@node 1AB9CD6C-0 12370 40
//@node BB7017BD-0 12650 40
//@node 33C59637-0 12930 40
//@node CB2FF6ED-0 13210 40
//@node FD3B0AB8-0 13490 40
//@node 927C0D35-0 13770 40
//@node 19C5023E-0 14050 40
//@node 56417D6F-0 14330 40
//@node C78ABCE0-0 14610 40
//@node 0535E26D-0 14890 40
//@node 43C61A41-0 15170 40
//@node 79EE8FFF-0 15450 40
//@node A4335521-0 15730 40
//@node CA148F10-0 16010 40
//@node 426412CF-0 16290 40
//@node 7E572ADD-0 16570 40
//@node 9A123C9C-0 16850 40
//@node 811AE4CB-0 17130 40
//@node B68D2418-0 17410 40
//@node 2ED1DA5F-0 17690 40
//@node DEFBC4EA-0 17970 40
//@node CC2683A8-0 18250 40
//@node 5D46AE44-0 18530 40
//@node 5E1F2588-0 18810 40
//@node 5A2CFDDB-0 19090 40
//@node A93D6BBF-0 19370 40
//@node 2DDFDD18-0 19650 40
//@node 261B1D0C-0 19930 40
//@node 5BFA6CB5-0 20210 40
//@node B0E2FF99-0 20490 40
//@node B1098744-0 20770 40
//@node D83A3A14-0 21050 40
//@node 6E82371A-0 21330 40
//@node 6FF82690-0 21610 40
//@node CF75B518-0 21890 40
//@node ECDAD9B2-0 22170 40
//@node FBC2D5DB-0 22450 40
//@node 493C2BD1-0 22730 40
//@node 991AF036-0 23010 40
//@node 273887E4-0 23290 40
//@node FE61B825-0 23570 40
//@node 02EC4D82-0 40 40
//@node 1F21BB7B-0 330 40
//@node 6C22FFDD-0 610 40
//@node 42D1C1E4-0 890 40
//@node 36F2A8B6-0 1170 40
//@node 689AC547-0 40 40
//@node 21CAF612-0 330 40
//@node 3F091516-0 610 40
//@node F97A321F-0 890 40
//@node 7E95BE9E-0 1170 40
//@node EBF40333-0 40 40
//@node 7DF8AF82-0 330 40
//@node CBDAD76C-0 105 145
//@node 8C231F48-0 -100 245
//@node 7222CEC0-0 610 40
//@node 36AA518A-0 385 145
//@node BD66A3AB-0 180 245
//@node 83DCE48A-0 890 40
//@node 6FD344C6-0 665 145
//@node 7016E1CE-0 460 245
//@node D54E4A2C-0 1170 40
//@node 4211F320-0 945 145
//@node 1230D5C2-0 740 245
//@node 4897B814-0 1730 40
//@node 15CB88C1-0 1245 140
//@node F11A97F0-0 2010 40
//@node 42778036-0 1525 140
//@node FC1A9B25-0 2290 40
//@node D6EE81E9-0 2570 40
//@node CBCAD04D-0 2850 40
//@node 73123EB3-0 3130 40
//@node C93E7FAC-0 2645 140
//@node F033430C-0 3410 40
//@node 091ABEBB-0 3690 40
//@node D53EC6BA-0 3970 40
//@node 6CE56807-0 4250 40
//@node 2CA5AF92-0 4530 40
//@node 742C1A55-0 4810 40
//@node D399C154-0 4325 140
//@node 058A5D11-0 5090 40
//@node ED0ED9A4-0 5370 40
//@node A18FD952-0 5650 40
//@node 73123EB3-1 5930 40
//@node 02EAA5D3-0 5445 140
//@node 75347715-0 5930 40
//@node FF9AD533-0 5725 145
//@node 214FC192-0 6210 200
//@node DC6433B9-0 6005 305
//@node 7D838B46-0 6770 200
//@node E5BA6861-0 7050 200
//@node EA98B06E-0 7330 200
//@node 5964B7FC-0 40 40
//@node 33E37103-0 330 40
//@node 5B91B274-0 105 145
//@node 1201FB0B-0 -100 245
//@node EE28F325-0 610 40
//@node 848145F1-0 385 145
//@node 6A26DD2D-0 180 245
//@node 915821E3-0 890 40
//@node 62A22029-0 665 145
//@node 10C7E7B3-0 460 245
//@node 1FE10B71-0 1170 40
//@node 05EC9F30-0 945 145
//@node BFDE0F01-0 740 245
//@node 8256DE02-0 1730 40
//@node AAE394FC-0 2010 40
//@node 57907AC6-0 2290 40
//@node 3F41C0F6-0 2570 40
//@node 64F11298-0 2085 140
//@node E9DC6DFD-0 2850 40
//@node BA6B3BD2-0 3130 40
//@node 77432D0F-0 3410 40
//@node D2878F68-0 3690 40
//@node 76764965-0 3970 40
//@node 1C724480-0 4250 40
//@node E33FD83A-0 3765 140
//@node 7E722147-0 4530 40
//@node 63826090-0 4045 140
//@node 968AE34B-0 4810 40
//@node C687D6A2-0 4325 140
//@node AE351D24-0 5090 40
//@node EDFC9A9D-0 5370 40
//@node 7AB272BD-0 5650 40
//@node CF3FAAFA-0 5930 40
//@node E8391977-0 6210 40
//@node BFFFEC7C-0 6490 40
//@node 56C5852C-0 6770 40
//@node A02D5F2B-0 7050 40
//@node 371E6107-0 7330 40
//@node 3F41C0F6-1 7610 40
//@node C8D41D6F-0 7125 140
//@node 25BF8506-0 7890 40
//@node 6B9760E5-0 8170 40
//@node F6DC43A4-0 8450 40
//@node 340EC4F5-0 8730 40
//@node 1455CAC1-0 9010 40
//@node 5799CA18-0 9290 40
//@node 25F4D06C-0 9570 40
//@node 95E04D77-0 9850 40
//@node 2C8384D7-0 10130 40
//@node 3F41C0F6-2 10410 40
//@node 2C3470CA-0 9925 140
//@node 25BF8506-1 10690 40
//@node 6B9760E5-1 10970 40
//@node 9ABB9CE8-0 11250 40
//@node 8DFB9355-0 11530 40
//@node ECEDEC41-0 11810 40
//@node BBF8A274-0 12090 40
//@node 97C61EA6-0 12370 40
//@node A4BCEC30-0 12650 40
//@node 3F41C0F6-3 12930 40
//@node 3D9E96B1-0 12445 140
//@node AE351D24-1 13210 40
//@node EDFC9A9D-1 13490 40
//@node 5CABA857-0 13770 40
//@node 2510F222-0 14050 40
//@node E3AE5BBE-0 14330 40
//@node 7792C167-0 14610 40
//@node E9DC6DFD-1 14890 40
//@node BA6B3BD2-1 15170 40
//@node 30A56BCC-0 15170 40
//@node 7F482016-0 14965 145
//@node 8DBDD384-0 15450 200
//@node D307D88A-0 15245 305
//@node B3AE865C-0 16010 200
//@node 3D245F29-0 16290 200
//@node 81B4C1A8-0 16570 200
//@node 7670939E-0 40 40
//@node ACF6B0DF-0 330 40
//@node 60451CE6-0 125 145
//@node 60DE4CCA-0 -80 145
//@node 28985F40-0 610 200
//@node BCE7A332-0 890 200
//@node B4A6FA91-0 685 305
//@node FC92B4A7-0 1170 200
//@node 359952EB-0 1450 200
//@node 4F264929-0 1730 200
//@node 359952EB-1 2010 200
//@node 2854DCD3-0 2290 200
//@node 359952EB-2 2570 200
//@node 7A87EA20-0 2850 200
//@node 35E1ED43-0 2625 305
//@node 0195A692-0 3130 200
//@node 1E424998-0 2925 300
//@node C7724308-0 3410 200
//@node A6FFCE6C-0 3690 200
//@node 0E5AE3F8-0 4250 200
//@node B2198007-0 40 40
//@node 52A591A3-0 330 40
//@node 6AC0BF95-0 125 145
//@node FA868CC0-0 -80 145
//@node CEFAB290-0 610 200
//@node 0CD36A41-0 890 200
//@node CEE0CE27-0 1170 200
//@node 29C06F9C-0 965 305
//@node 4514E02D-0 1450 200
//@node 32D0490E-0 1730 200
//@node 631FCCBB-0 2010 200
//@node 32D0490E-1 2290 200
//@node 08B33B11-0 2570 200
//@node 32D0490E-2 2850 200
//@node 1718C446-0 3130 200
//@node CDB92FCC-0 2905 305
//@node C0051B99-0 3410 200
//@node 72E8946D-0 3205 300
//@node 49F1C5DF-0 3690 200
//@node CB1D125B-0 4250 200
//@node 7C7CAB44-0 40 40
//@node 6B7F7E5A-0 330 40
//@node 3B082B0D-0 610 40
//@node 4B0073C1-0 890 40
//@node 86DDBF47-0 1170 40
//@node 89AB2723-0 1450 40
//@node DBE07608-0 1730 40
//@node 930F00B5-0 2010 40
//@node 8AC02BE1-0 2290 40
//@node 44A07F04-0 2570 40
//@node AD2CB910-0 2850 40
//@node 23AF5739-0 40 40
//@node 24F4CAAE-0 330 40
//@node 054330F8-0 105 145
//@node 5004ED15-0 610 40
//@node 6C999BD0-0 385 145
//@node CFBF9BBE-0 890 40
//@node E4D9A7B5-0 685 145
//@node 76152F1A-0 1450 200
//@node BE3782B6-0 1730 200
//@node 30BB7A7B-0 2010 200
//@node A0311FA4-0 2290 200
//@node C9F57578-0 2570 200
//@node 3B690EC9-0 2850 200
//@node 1B062F72-0 3130 200
//@node 63DF098C-0 3410 200
//@node 0A23F1D6-0 3690 200
//@node 58C305A9-0 3970 200
//@node D21BC1BA-0 3485 300
//@node 7F927AAB-0 3280 300
//@node 29033285-0 4250 200
//@node DA10F5FD-0 3765 300
//@node 227B995A-0 3560 300
//@node 5314AD20-0 4530 200
//@node E2AF2895-0 4810 200
//@node 010DB042-0 5090 200
//@node 90CE2064-0 5370 200
//@node 0A23F1D6-1 5650 200
//@node 31B4E1F5-0 5930 200
//@node 60BFA19F-0 6210 200
//@node 678BC969-0 6490 200
//@node C9F57578-1 6770 200
//@node 01A797C3-0 7050 200
//@node C5022C85-0 7330 200
//@node 0A23F1D6-2 7610 200
//@node AF022F95-0 7890 200
//@node 972FDA35-0 8170 200
//@node 9033885A-0 8450 200
//@node 9D30320E-0 8730 200
//@node 59509FE7-0 9010 200
//@node 5314AD20-1 9290 200
//@node 749252E8-0 9570 200
//@node 55C1FA4D-0 9850 200
//@node 4DA48A63-0 10130 200
//@node 0A23F1D6-3 10410 200
//@node 20AF5280-0 40 40
//@node 234D0EA7-0 330 40
//@node 4971A93F-0 105 145
//@node 2852F69C-0 610 40
//@node A374A118-0 385 145
//@node BB2D05EB-0 890 40
//@node 5AFED963-0 685 145
//@node FECBEE86-0 1450 200
//@node 03623E02-0 1730 200
//@node ADD7C2D7-0 2010 200
//@node 4F0680C8-0 2290 200
//@node 6B4AB8CC-0 2570 200
//@node 60CF117D-0 2850 200
//@node D1D0418E-0 3130 200
//@node 52F52F80-0 3410 200
//@node ED78C3A8-0 3690 200
//@node 7B91F19A-0 3970 200
//@node 63CF92F9-0 3485 300
//@node EDABF844-0 3280 300
//@node 81B25281-0 4250 200
//@node FFF7F0AB-0 3765 300
//@node ECD78C84-0 3560 300
//@node AD1D5D04-0 4530 200
//@node 931BC299-0 4810 200
//@node 370D0941-0 5090 200
//@node D952A4C8-0 5370 200
//@node ED78C3A8-1 5650 200
//@node 75177731-0 5930 200
//@node 743B5B52-0 6210 200
//@node A837BCD5-0 6490 200
//@node 6B4AB8CC-1 6770 200
//@node C126C857-0 7050 200
//@node 2FC3ED59-0 7330 200
//@node 4BE95F41-0 7610 200
//@node ED78C3A8-2 7890 200
//@node 383A5729-0 8170 200
//@node 80588756-0 8450 200
//@node 9B61D5FA-0 8730 200
//@node EF0BD053-0 9010 200
//@node AD1D5D04-1 9290 200
//@node 99F8559C-0 9570 200
//@node 01149A41-0 9850 200
//@node EF9838BF-0 10130 200
//@node ED78C3A8-3 10410 200
//@node 21AF5413-0 40 40
//@node F65CCD00-0 330 40
//@node 9BA96C85-0 105 145
//@node 98C2D2BA-0 610 40
//@node E2B886F5-0 385 145
//@node 1091A0B4-0 890 40
//@node 0D3FE508-0 685 145
//@node 082AB356-0 1450 200
//@node 7DADD672-0 1730 200
//@node D1275247-0 2010 200
//@node F0D22538-0 2290 200
//@node 6576059C-0 2570 200
//@node A3DA6D4D-0 2850 200
//@node C6B9EB9E-0 3130 200
//@node 6033C5B0-0 3410 200
//@node 1655FE2A-0 3690 200
//@node 68133DA3-0 3970 200
//@node E2097EC1-0 3485 300
//@node 3B0D3680-0 3280 300
//@node 7B615BB1-0 4250 200
//@node 1078FFE3-0 3765 300
//@node 85F75B74-0 3560 300
//@node 0103D1F4-0 4530 200
//@node B4FA1589-0 4810 200
//@node E7FA3076-0 5090 200
//@node 0FF09498-0 5370 200
//@node 1655FE2A-1 5650 200
//@node F25ABB01-0 5930 200
//@node C33AC1DB-0 6210 200
//@node 88521E45-0 6490 200
//@node 6576059C-1 6770 200
//@node 63A3B587-0 7050 200
//@node 84C24A89-0 7330 200
//@node 2D5B6AB1-0 7610 200
//@node 1655FE2A-2 7890 200
//@node C237B639-0 8170 200
//@node 3853E026-0 8450 200
//@node 3E12CB2A-0 8730 200
//@node 9214A943-0 9010 200
//@node 0103D1F4-1 9290 200
//@node DD03B16C-0 9570 200
//@node 37950FF1-0 9850 200
//@node 4E11D9CF-0 10130 200
//@node 1655FE2A-3 10410 200
//@node 58DB07C9-0 40 40
//@node 1857364D-0 330 40
//@node 37B810F6-0 610 40
//@node 9B55837E-0 890 40
//@node F52E0129-0 1170 40
//@node 62A76BAD-0 1450 40
//@node CF03A367-0 1730 40
//@node 10314AB6-0 2010 40
//@node 4CD4D4FF-0 2290 40
//@node 6805A8B9-0 2570 40
//@node 8B36A29E-0 2850 40
//@node 76D65090-0 2645 145
//@node A93F0689-0 3130 200
//@node 90F5EDC2-0 3410 200
//@node 652B27B5-0 3690 200
//@node 0EF676A5-0 3970 200
//@node 63E72AF6-0 4250 200
//@node 1D8E7935-0 4530 200
//@node D8929C42-0 4810 200
//@node 0EF676A5-1 5090 200
//@node B100079C-0 40 40
//@node 593E1737-0 330 40
//@node 8BB0FCC7-0 125 145
//@node 34689A9E-0 610 200
//@node 23AD3686-0 890 200
//@node 67EC026E-0 1170 200
//@node D3EE931C-0 1450 200
//@node FC140D28-0 1730 200
//@node C497F968-0 2010 200
//@node 187BF0E5-0 2290 200
//@node 9EB37A28-0 2570 200
//@node 34689A9E-1 2850 200
//@node B6294BF7-0 3130 200
//@node 67EC026E-1 3410 200
//@node 9C14604B-0 3690 200
//@node FC140D28-1 3970 200
//@node 797A665D-0 4250 200
//@node 187BF0E5-1 4530 200
//@node 9EB37A28-1 4810 200
//@node 947408C5-0 5090 200
//@node B6294BF7-1 5370 200
//@node B95CF661-0 5650 200
//@node 9C14604B-1 5930 200
//@node 4B2AA853-0 6210 200
//@node 797A665D-1 6490 200
//@node 187BF0E5-2 6770 200
//@node 9EB37A28-2 7050 200
//@node 947408C5-1 7330 200
//@node 23AD3686-1 7610 200
//@node B95CF661-1 7890 200
//@node D3EE931C-1 8170 200
//@node 4B2AA853-1 8450 200
//@node C497F968-1 8730 200
//@node 187BF0E5-3 9010 200
//@node B62AA544-0 9290 200
//@node DA212E07-0 40 40
//@node 93B507EC-0 330 40
//@node C3DEF1C8-0 610 40
//@node 35C4A8F8-0 890 40
//@node 38F8D752-0 1170 40
//@node 01E6CE0F-0 1450 40
//@node FFB4A028-0 1730 40
//@node 0FD2ECA3-0 1525 145
//@node B2BBEAD0-0 2010 200
//@node 120CB615-0 2290 200
//@node 71A63585-0 2570 200
//@node BB61FF5A-0 2850 200
//@node 86220843-0 3130 200
//@node 31EAD355-0 3410 200
//@node 9A99F82F-0 3690 200
//@node 3652B21C-0 3970 200
//@node 48CFC1BA-0 4250 200
//@node F060EEAF-0 4530 200
//@node B57FBB64-0 4810 200
//@node 31EAD355-1 5090 200
//@node D56F3B7C-0 40 40
//@node 31228115-0 330 40
//@node 1F3DB3CF-0 610 40
//@node 78D7F128-0 890 40
//@node 856C8B37-0 1170 40
//@node 0B5C73EF-0 965 145
//@node C973ABDF-0 1450 200
//@node 49A6BB14-0 1225 305
//@node 1F667061-0 1730 200
//@node 0DB2459F-0 1525 305
//@node 15BC2C9B-0 1320 305
//@node 004BF564-0 2010 360
//@node D8926338-0 2290 360
//@node BC427F73-0 2570 360
//@node 1D9A6D93-0 2365 465
//@node 4CB38DA6-0 2160 465
//@node C7726325-0 2850 360
//@node D8926338-1 3130 360
//@node D290A186-0 3690 360
//@node D8926338-2 3970 360
//@node 30B1EDCE-0 40 40
//@node 25157F06-0 330 40
//@node D22BA22D-0 125 145
//@node 31386FE2-0 -80 145
//@node 5E56BFBD-0 610 200
//@node 067D5CDC-0 890 40
//@node C7E9E55E-0 1170 40
//@node 7DBE3FB6-0 1450 40
//@node FAE693DC-0 1730 40
//@node 25157F06-1 2010 40
//@node 38FED794-0 1805 145
//@node 01C0ACB1-0 1600 145
//@node 5E56BFBD-1 2290 200
//@node 51FAD71D-0 2570 40
//@node 57B65689-0 2850 40
//@node AA59DAC7-0 3130 40
//@node A1CDCBC5-0 3410 40
//@node B582DF33-0 3690 40
//@node 38EA44F0-0 3970 40
//@node B08DA13E-0 4250 40
//@node 8A6C8825-0 4045 145
//@node EDF8C777-0 3840 145
//@node 11B4475D-0 4530 200
//@node F70FF790-0 4810 200
//@node B61FDFB8-0 5090 200
//@node 913BE09C-0 4885 305
//@node 4DC242E2-0 4680 305
//@node 9371A593-0 5370 40
//@node 648CB0BE-0 5650 40
//@node 38EA44F0-1 5930 40
//@node D21DAC55-0 6210 40
//@node C1624FE9-0 6005 145
//@node F15EB044-0 5800 145
//@node 4591B6DC-0 6490 200
//@node F70FF790-1 6770 200
//@node EEACB5BA-0 7050 200
//@node 87BA2551-0 6845 305
//@node 91499385-0 6640 305
//@node 4ECBDF66-0 7330 40
//@node 4E0EBE47-0 7610 40
//@node 58B033C6-0 7890 40
//@node 832AD95B-0 8170 40
//@node 878C2B4A-0 8450 40
//@node A68BBE5A-0 8730 40
//@node 38EA44F0-2 9010 40
//@node 33E9E52D-0 9290 40
//@node B08DA13E-1 9570 40
//@node F7337188-0 9365 145
//@node C4E28362-0 9160 145
//@node 11B4475D-1 9850 200
//@node F70FF790-2 10130 200
//@node B61FDFB8-1 10410 200
//@node FA879B0D-0 10205 305
//@node 76D886F7-0 10000 305
//@node 145C50C1-0 10690 40
//@node 38EA44F0-3 10970 40
//@node D21DAC55-1 11250 40
//@node D9318804-0 11045 145
//@node 75AA6811-0 10840 145
//@node 4591B6DC-1 11530 200
//@node F70FF790-3 11810 200
//@node EEACB5BA-1 12090 200
//@node CA931CEC-0 11885 305
//@node C7C94878-0 11680 305
//@node 36FFE2D1-0 12370 40
//@node E91D2E10-0 12650 40
//@node BE4DF864-0 12930 40
//@node 731466CB-0 13210 40
//@node 51FAD71D-1 13490 40
//@node 2D7B7F92-0 13770 40
//@node AA59DAC7-1 14050 40
//@node 67507454-0 14330 40
//@node B582DF33-1 14610 40
//@node 4F52DCFF-0 40 40
//@node BB61186B-0 330 40
//@node 09633320-0 125 145
//@node B1AA0445-0 -80 145
//@node 75D8CC34-0 610 200
//@node 32CD07DB-0 890 40
//@node 02CC09BA-0 1170 40
//@node 44F7EB05-0 1450 40
//@node 1082DCA7-0 1730 40
//@node BB61186B-1 2010 40
//@node 86293539-0 1805 145
//@node 4A0C0336-0 1600 145
//@node 75D8CC34-1 2290 200
//@node 7FE4C454-0 2570 40
//@node D2100E5C-0 2850 40
//@node 40A32C82-0 3130 40
//@node BE618D56-0 3410 40
//@node 07C64DDC-0 3690 40
//@node 55355351-0 3970 40
//@node FE08D088-0 3765 145
//@node 7735FA76-0 3560 145
//@node DFBCB9A8-0 4250 200
//@node 30B12EEB-0 4530 200
//@node B0EF480F-0 4810 200
//@node 85974B6D-0 4605 305
//@node 0C6EB3AB-0 4400 305
//@node FBA49B7F-0 5090 40
//@node 160F3B15-0 5370 40
//@node 37303A65-0 5650 40
//@node CF29A786-0 5930 40
//@node 859B9AE5-0 5725 145
//@node 0166A0AC-0 5520 145
//@node ED678D35-0 6210 200
//@node 30B12EEB-1 6490 200
//@node 93E7B4A1-0 6770 200
//@node CE11AD7E-0 6565 305
//@node EA412A36-0 6360 305
//@node C704937D-0 7050 40
//@node E9694B70-0 7330 40
//@node 19316565-0 7610 40
//@node 5DA1B20D-0 7890 40
//@node 728DEB1C-0 8170 40
//@node 2DCFE40F-0 8450 40
//@node 39AB79DD-0 8730 40
//@node 4DEAD26A-0 9010 40
//@node 55355351-1 9290 40
//@node 9141E725-0 9085 145
//@node 561F856B-0 8880 145
//@node DFBCB9A8-1 9570 200
//@node 30B12EEB-2 9850 200
//@node B0EF480F-1 10130 200
//@node 87ABAAFC-0 9925 305
//@node 3F5706B6-0 9720 305
//@node 195850ED-0 10410 40
//@node 37303A65-1 10690 40
//@node CF29A786-1 10970 40
//@node CCDD2540-0 10765 145
//@node 6758BB39-0 10560 145
//@node ED678D35-1 11250 200
//@node 30B12EEB-3 11530 200
//@node 93E7B4A1-1 11810 200
//@node 183E5703-0 11605 305
//@node B758D72B-0 11400 305
//@node D454198A-0 12090 40
//@node 648851FF-0 12370 40
//@node E581C12E-0 12650 40
//@node 1EB9D175-0 12930 40
//@node 7FE4C454-1 13210 40
//@node 920113CD-0 13490 40
//@node 40A32C82-1 13770 40
//@node D9A3293D-0 14050 40
//@node 07C64DDC-1 14330 40
//@node AE8EC08F-0 40 40
//@node 52E12C73-0 330 40
//@node 3517A0A9-0 610 40
//@node 3EB59A5D-0 890 40
//@node 3517A0A9-1 1170 40
//@node 88BA929B-0 1450 40
//@node 3517A0A9-2 1730 40
//@node D337F163-0 40 40
//@node FC65E99A-0 330 40
//@node 6155145D-0 125 145
//@node 2C848AED-0 -80 145
//@node 87F768DB-0 610 200
//@node 78F88D1C-0 890 200
//@node A9D359E0-0 1170 200
//@node 78F88D1C-1 1450 200
//@node D7A30648-0 1730 40
//@node E2DDABB2-0 2010 40
//@node CAA48C3F-0 40 40
//@node 9DB5E622-0 330 40
//@node F317C1BA-0 610 40
//@node 0CB52353-0 405 145
//@node 1C6BAC15-0 890 40
//@node 484F53F0-0 1170 40
//@node F045B2DB-0 40 40
//@node FB0EFFBD-0 330 40
//@node 36860F1F-0 610 40
//@node BE6A3225-0 890 40
//@node CA36ED58-0 1170 40
//@node BE6A3225-1 1450 40
//@node 0F4AA531-0 1730 40
//@node D7A972BF-0 1525 145
//@node 5F42B772-0 2010 40
//@node 9394E4FB-0 40 40
//@node 121DB165-0 330 40
//@node 79B350CE-0 610 40
//@node D4E935B3-0 890 40
//@node F94A9BC4-0 1170 40
//@node A0C1D8ED-0 1450 40
//@node E8613676-0 1730 40
//@node D461CA7B-0 2010 40
//@node 766FAD8C-0 2290 40
//@node CA4D6301-0 2570 40
//@node B521F34A-0 40 40
//@node 6FC32D92-0 330 40
//@node 44DD82F6-0 610 40
//@node 0B20C928-0 890 40
//@node 4E18208D-0 1170 40
//@node D67426F3-0 1450 40
//@node F18BDE06-0 1730 40
//@node 85C38EA8-0 2010 40
//@node 6587B892-0 2290 40
//@node 151BF826-0 2570 40
//@node 5A629915-0 2850 40
//@node 4B76EC3B-0 3130 40
//@node 6CB11C46-0 3410 40
//@node E073962D-0 3690 40
//@node 6A09F188-0 3970 40
//@node 6D287A61-0 4250 40
//@node DCA9073E-0 4530 40
//@node 9F008B4D-0 4810 40
//@node 1B14FA23-0 5090 40
//@node 768E1735-0 5370 40
//@node 151BF826-1 5650 40
//@node 23D3F617-0 5930 40
//@node FC0538A5-0 6210 40
//@node 89EC1E88-0 6490 40
//@node 5A1C9F1C-0 6770 40
//@node AFCC827C-0 7050 40
//@node 28339BAD-0 7330 40
//@node F8CC2106-0 7610 40
//@node CF56E6C2-0 7890 40
//@node F57D512A-0 8170 40
//@node 151BF826-2 8450 40
//@node F5687CCB-0 8730 40
//@node 9B2B93EB-0 9010 40
//@node 5A15DAB4-0 9290 40
//@node 96CF1582-0 9570 40
//@node D67426F3-1 9850 40
//@node E19E8B9A-0 10130 40
//@node 8E0252B9-0 10410 40
//@node 4C65E0CD-0 10690 40
//@node 2A5BAF42-0 10970 40
//@node 151BF826-3 11250 40
//@node 5DCAFA41-0 11530 40
//@node 4E18208D-1 11810 40
//@node AFCC827C-1 12090 40
//@node 28339BAD-1 12370 40
//@node 42F620BC-0 12650 40
//@node 41E7D9D1-0 12930 40
//@node 151BF826-4 13210 40
//@node CEED78FA-0 40 40
//@node E1ECBC76-0 330 40
//@node 6BABC571-0 125 145
//@node 691A87AF-0 610 200
//@node E6C1AFFF-0 405 305
//@node 626032BB-0 890 200
//@node 1C1EE256-0 685 305
//@node AE645514-0 1170 200
//@node ECB3C5A3-0 965 305
//@node 2DEA993A-0 1450 200
//@node 0116FF6C-0 1245 305
//@node 27CEA4B6-0 2010 200
//@node 8F78EB09-0 1805 305
//@node B1139F72-0 2290 200
//@node 7C7AEAA5-0 2085 305
//@node A6668713-0 2570 200
//@node C99407A3-0 2365 305
//@node 19182951-0 2850 200
//@node 19FEECD5-0 2645 305
//@node 287A8B23-0 3130 40
//@node DBADF844-0 2905 145
//@node 44AAB530-0 2700 245
//@node 1FA250E7-0 2495 245
//@node 8E92AB60-0 3690 40
//@node 42C6665F-0 3970 40
//@node 736EFA2E-0 3970 40
//@node 575F5F34-0 3745 145
//@node BA0D4C41-0 3540 245
//@node A5AA04DC-0 3335 245
//@node B73A78B0-0 4530 40
//@node 4339F6B5-0 4530 40
//@node 8B2EDEEF-0 4305 145
//@node 8CEAA59E-0 4100 245
//@node 6D61E5B8-0 3895 245
//@node D4E1D4C5-0 5090 40
//@node 5DAE202D-0 5370 40
//@node 7A60360C-0 5370 40
//@node 791EF929-0 5145 145
//@node D8CC9338-0 4940 245
//@node C0AEF25D-0 4735 245
//@node 91E0CEC8-0 5930 40
//@node 95EE2761-0 5445 140
//@node 41E239BD-0 5930 40
//@node 4FE92505-0 5705 145
//@node 007F9E53-0 5500 245
//@node 5C2AA7C5-0 5295 245
//@node D4E1D4C5-1 6490 40
//@node 33B49F92-0 6770 40
//@node BA43CD3C-0 7050 40
//@node 08B935FC-0 6565 140
//@node 5B7C7A0E-0 7050 40
//@node F2DFAD85-0 6825 145
//@node E00AA89C-0 6620 245
//@node AC0BD5F3-0 6415 245
//@node 91E0CEC8-1 7610 40
//@node 6EDC7522-0 7125 140
//@node 9060A5D7-0 7610 40
//@node C5532F2F-0 7385 145
//@node B32A483F-0 7180 245
//@node 351EE0E3-0 6975 245
//@node BF3C3416-0 8170 40
//@node 2BE3F32C-0 8450 40
//@node 43F420BC-0 7965 232
//@node 34E660F5-0 8450 40
//@node F7509D50-0 8225 145
//@node 022AAA33-0 8020 245
//@node 85EB15C5-0 7815 245
//@node 91E0CEC8-2 9010 40
//@node 9C6CEFF7-0 8525 140
//@node 3170CE92-0 9010 40
//@node 891B6E5F-0 8785 145
//@node 8452601E-0 8580 245
//@node 326CF295-0 8375 245
//@node BF3C3416-1 9570 40
//@node 2BE3F32C-1 9850 40
//@node 35FE6239-0 9365 232
//@node BA43CD3C-1 10130 40
//@node 2A04789F-0 9645 140
//@node 9C106025-0 10130 40
//@node A3FD2559-0 9905 145
//@node 3CC9ACF2-0 9700 245
//@node C01D2E76-0 9495 245
//@node 91E0CEC8-3 10690 40
//@node 7D8391D0-0 10205 140
//@node C6C78E67-0 10690 40
//@node 5E2427E0-0 10465 145
//@node 819BF0E9-0 10260 245
//@node 60548BB1-0 10055 245
//@node 27CEFF23-0 11250 40
//@node FB15E90E-0 11530 40
//@node 162AECC2-0 11530 40
//@node EF24F2D8-0 11305 145
//@node 19BCB5AD-0 11100 245
//@node 88994902-0 10895 245
//@node D2C0E319-0 12090 40
//@node 3B2BB48F-0 12370 40
//@node D5088218-0 12370 40
//@node B3B2DD3F-0 12145 145
//@node 86033FB8-0 11940 245
//@node 396FC7F9-0 11735 245
//@node DFDEE1E8-0 12930 40
//@node AD8A4EA7-0 12445 140
//@node E6E74BAA-0 13210 40
//@node 38FA1F10-0 12725 140
//@node 991BE3E0-0 13490 40
//@node 444939AF-0 13005 140
//@node BEAE3828-0 13490 40
//@node C3C9A905-0 13265 145
//@node 6713C839-0 13060 245
//@node 02E84504-0 14050 40
//@node DA6BFAF4-0 13565 232
//@node A4E9DDAE-0 40 40
//@node DA4FD222-0 330 40
//@node 5335ECA8-0 125 145
//@node 891FA2EC-0 610 200
//@node FB759959-0 405 305
//@node 1840AF73-0 890 200
//@node 7862AB9B-0 685 305
//@node EE069209-0 1450 200
//@node 952B83FF-0 1245 305
//@node 4A346F48-0 1730 200
//@node F6D4F29C-0 1525 305
//@node 06D9A4BC-0 2010 40
//@node AC3A99EE-0 1785 145
//@node C5987DC2-0 1580 245
//@node 917E0B42-0 1375 245
//@node 42C42724-0 2570 40
//@node 337A728B-0 2085 140
//@node FC280D84-0 2570 40
//@node 6B5CC12C-0 2345 145
//@node 1F1E96B3-0 2140 245
//@node 5B5F313B-0 1935 245
//@node F9F65C09-0 3130 40
//@node 3293E1E7-0 3410 40
//@node 73FD66A7-0 3410 40
//@node 6FE52F81-0 3185 145
//@node C1B29000-0 2980 245
//@node 7DD3A3BD-0 2775 245
//@node A13D3753-0 3970 40
//@node 496925D6-0 4250 40
//@node A16299AA-0 4530 40
//@node F9344E45-0 4045 140
//@node E26548BC-0 4810 40
//@node 7C7F39BA-0 4325 140
//@node 6BB32997-0 4810 40
//@node 4F38FBA7-0 4585 145
//@node 7B756570-0 4380 245
//@node 59FD172D-0 4175 245
//@node 671274EC-0 5370 40
//@node 2D8ED6C4-0 4885 140
//@node C2C0D076-0 5370 40
//@node 1813B352-0 5145 145
//@node 40D2378F-0 4940 245
//@node D9EE39BD-0 4735 245
//@node 384F89B7-0 5930 40
//@node 316546A6-0 6210 40
//@node 16755E2B-0 6210 40
//@node 9E8855F0-0 5985 145
//@node A65EA5E1-0 5780 245
//@node B51C2B30-0 5575 245
//@node 42C42724-1 6770 40
//@node 568D8CB4-0 6285 140
//@node 2F1CE0D4-0 6770 40
//@node 5B7A824C-0 6545 145
//@node A5572946-0 6340 245
//@node 19C43DCA-0 6135 245
//@node 384F89B7-1 7330 40
//@node F2EACD39-0 7610 40
//@node 30A7037F-0 7610 40
//@node 811E9CAE-0 7385 145
//@node D45DAF54-0 7180 245
//@node 91A65863-0 6975 245
//@node 42C42724-2 8170 40
//@node BB508A45-0 7685 140
//@node 57C09E16-0 8170 40
//@node 492FA4B3-0 7945 145
//@node A7F328E5-0 7740 245
//@node B866A6E5-0 7535 245
//@node 71EB324E-0 8730 40
//@node 59DB8BA8-0 9010 40
//@node 667B42B7-0 8525 232
//@node 020E4D7A-0 9010 40
//@node 15F26050-0 8785 145
//@node 30EDC187-0 8580 245
//@node E158AC31-0 8375 245
//@node 42C42724-3 9570 40
//@node 4230D346-0 9085 140
//@node 0EF0F15D-0 9570 40
//@node F17BADCC-0 9345 145
//@node FD223248-0 9140 245
//@node EE602F03-0 8935 245
//@node 71EB324E-1 10130 40
//@node 59DB8BA8-1 10410 40
//@node A2974A3A-0 9925 232
//@node EEC07F98-0 10690 40
//@node 58AE82A2-0 10205 140
//@node 16319330-0 40 40
//@node FF496C56-0 330 40
//@node 28D9DF62-0 105 145
//@node 87D4AE9B-0 -100 245
//@node 79C716BB-0 610 40
//@node 79679DD9-0 405 145
//@node 2CAE6ED8-0 200 145
//@node DF5089D1-0 890 200
//@node 39718B80-0 1170 200
//@node 19A9C5DE-0 1730 200
//@node EFCA60C7-0 2010 200
//@node 3829492D-0 40 40
//@node 79C5F63B-0 330 40
//@node 18F7C184-0 610 40
//@node FFC65F36-0 890 40
//@node 09172D03-0 1170 40
//@node 07374436-0 1450 40
//@node 51F34EF8-0 1245 145
//@node FDD969F3-0 1730 200
//@node 14E3844C-0 2290 200
//@node 74098695-0 2570 40
//@node 96369CDE-0 40 40
//@node 7FB6C619-0 330 40
//@node E72509EE-0 610 40
//@node 281DBAE8-0 890 40
//@node 1B34B511-0 1170 40
//@node 914832A0-0 1450 40
//@node 2D72E2E0-0 1245 145
//@node 5B68314D-0 1730 200
//@node 9B4BDEFA-0 2290 200
//@node 9D9E16C7-0 2570 40
//@node F16520C8-0 40 40
//@node E68F583F-0 330 40
//@node F923BC5B-0 40 40
//@node E347AC07-0 330 40
//@node 9AD9FE77-0 40 40
//@node 13DDBD21-0 330 40
//@node EBCE5B94-0 40 40
//@node F0E636ED-0 330 40
//@node C1B7314B-0 40 40
//@node B44636CC-0 330 40
//@node AD04A4E9-0 610 40
//@node 9BFD27DD-0 890 40
//@node 25B6BECA-0 1170 40
//@node 798B9B94-0 1450 40
//@node AB34CEDD-0 1730 40
//@node 584D37ED-0 2010 40
//@node DE2311B7-0 2290 40
//@node 375313B5-0 2570 40
//@node E3704AB6-0 2850 40
//@node C20B2AE0-0 3130 40
//@node E1320158-0 3410 40
//@node 95649A7A-0 3690 40
//@node 7A52A504-0 3970 40
//@node E2B4C146-0 4250 40
//@node 24861C91-0 4530 40
//@node 987348EF-0 4810 40
//@node EAB0C2CF-0 5090 40
//@node A228C301-0 5370 40
//@node A19DB867-0 5650 40
//@node 612FD0CB-0 5930 40
//@node 4A24F58D-0 6210 40
//@node 13E5C23F-0 6490 40
//@node E937DA9A-0 6770 40
//@node 3DC522AD-0 7050 40
//@node D6F34016-0 7330 40
//@node 0AC894E9-0 7610 40
//@node 3B51FE09-0 7890 40
//@node 2E68E26D-0 8170 40
//@node A80E89E3-0 8450 40
//@node BB7B0DD0-0 8730 40
//@node EA2FA023-0 9010 40
//@node 1A8DF279-0 9290 40
//@node AAF83C6F-0 9570 40
//@node 2E68E26D-1 9850 40
//@node A80E89E3-1 10130 40
//@node BB7B0DD0-1 10410 40
//@node 92D703CE-0 10690 40
//@node 152210B8-0 10970 40
//@node 02C6FE38-0 11250 40
//@node 2E68E26D-2 11530 40
//@node DE56ACCF-0 11810 40
//@node 6C1973AE-0 12090 40
//@node 85EC91F4-0 12370 40
//@node B4868687-0 12650 40
//@node 02C6FE38-1 12930 40
//@node 2E68E26D-3 13210 40
//@node 80D13B22-0 13490 40
//@node 13E5C23F-1 13770 40
//@node 307369F5-0 14050 40
//@node 08120A9D-0 14330 40
//@node FA7B7EA0-0 14610 40
//@node F5296997-0 14890 40
//@node 88BD936E-0 15170 40
//@node 9419B3E1-0 15450 40
//@node 798B9B94-1 15730 40
//@node EA820E26-0 16010 40
//@node 93E476BF-0 16290 40
//@node 55218A4E-0 16570 40
//@node 61759C34-0 40 40
//@node AA716E8F-0 330 40
//@node 927A693A-0 125 145
//@node 849AD7A1-0 610 200
//@node C555D9C0-0 890 200
//@node 8E3DB735-0 1170 200
//@node B143CF0A-0 1450 200
//@node CB253FC3-0 1730 200
//@node 61F9B53A-0 2010 200
//@node 6EB465F2-0 2290 200
//@node 19AE1375-0 2570 200
//@node 849AD7A1-1 2850 200
//@node 4CDFC84F-0 3130 200
//@node 8E3DB735-1 3410 200
//@node 40E95B7B-0 3690 200
//@node CB253FC3-1 3970 200
//@node 85934A15-0 4250 200
//@node 6EB465F2-1 4530 200
//@node 19AE1375-1 4810 200
//@node BE8E7308-0 5090 200
//@node 4CDFC84F-1 5370 200
//@node A1012CA8-0 5650 200
//@node 40E95B7B-1 5930 200
//@node C4A4B0DE-0 6210 200
//@node 85934A15-1 6490 200
//@node 6EB465F2-2 6770 200
//@node 19AE1375-2 7050 200
//@node BE8E7308-1 7330 200
//@node C555D9C0-1 7610 200
//@node A1012CA8-1 7890 200
//@node B143CF0A-1 8170 200
//@node C4A4B0DE-1 8450 200
//@node 61F9B53A-1 8730 200
//@node 6EB465F2-3 9010 200
//@node 19AE1375-3 9290 200
//@node 8F09B122-0 40 40
//@node D79DDE42-0 330 40
//@node 7686FA14-0 610 40
//@node 5216E646-0 890 40
//@node 8342DE41-0 1170 40
//@node 8863C584-0 965 145
//@node B992010E-0 1450 200
//@node AF2D163E-0 1730 200
//@node C84D5768-0 2010 200
//@node 6C48A731-0 2290 200
//@node 7E66622F-0 2570 200
//@node 0451AF26-0 2850 200
//@node 001FFF89-0 3130 200
//@node A518C145-0 3410 200
//@node 45B81060-0 3690 200
//@node 8A2C8F09-0 3970 200
//@node 3781CFAF-0 4250 200
//@node 8C10BEF9-0 4530 200
//@node 678370C9-0 4810 200
//@node FC52DB6E-0 5090 200
//@node 9E1C7794-0 5370 200
//@node 83F201E5-0 5650 200
//@node 1AED085F-0 5930 200
//@node A65D3679-0 6210 200
//@node 9D12C523-0 6490 200
//@node 16C50571-0 6770 200
//@node BCF64801-0 7050 200
//@node D940F785-0 7330 200
//@node AAB92C2A-0 7610 200
//@node 6C48A731-1 7890 200
//@node EFA14002-0 8170 200
//@node 0451AF26-1 8450 200
//@node D940F785-1 8730 200
//@node AAB92C2A-1 9010 200
//@node 6C48A731-2 9290 200
//@node BB201960-0 9570 200
//@node 0451AF26-2 9850 200
//@node F203578A-0 10130 200
//@node F606A438-0 10410 200
//@node 13FA0848-0 10690 200
//@node 53B38708-0 10970 200
//@node F62BB1AD-0 11250 200
//@node 8FA49D19-0 11530 200
//@node 00F083FA-0 11810 200
//@node 3318A91D-0 12090 200
//@node 3DF0A9CF-0 12370 200
//@node FE6B3910-0 12650 200
//@node 981ED294-0 12930 200
//@node 039C98DE-0 13210 200
//@node 60827F6B-0 13490 200
//@node 8A2C8F09-1 13770 200
//@node AF2D163E-1 14050 200
//@node C84D5768-1 14330 200
//@node 6C48A731-3 14610 200
//@node 72F3DDB2-0 14890 200
//@node 4BD20693-0 15170 200
//@node 0451AF26-3 15450 200
//@node 1D367988-0 15730 200
//@node 89416C72-0 16010 200
//@node 6C48A731-4 16290 200
//@node 5C9102EF-0 16570 200
//@node 0451AF26-4 16850 200
//@node 1D367988-1 17130 200
//@node AAB92C2A-2 17410 200
//@node 57CDC1DD-0 17690 200
//@node 0C4F45A6-0 17970 200
//@node 0451AF26-5 18250 200
//@node BD3BC913-0 18530 200
//@node 291FAC8D-0 18810 200
//@node 6C48A731-5 19090 200
//@node E3D8BC90-0 19370 200
//@node 0451AF26-6 19650 200
//@node BD3BC913-1 19930 200
//@node AAB92C2A-3 20210 200
//@node 36B316C2-0 20490 200
//@node 6CEE6EA3-0 20770 200
//@node 0451AF26-7 21050 200
//@node 12314F85-0 21330 200
//@node 5F63E778-0 21610 200
//@node 878E0E32-0 21890 200
//@node CD02AD88-0 22170 200
//@node 45AB557E-0 22450 200
//@node 0451AF26-8 22730 200
//@node 0D621D05-0 23010 200
//@node CD02AD88-1 23290 200
//@node F8B20F43-0 23570 200
//@node 0451AF26-9 23850 200
//@node 52C03988-0 40 40
//@node 0B3C2E44-0 330 40
//@node 06C83B7E-0 610 40
//@node 26A7515C-0 890 40
//@node FB7CF243-0 1170 40
//@node DCE7DAD0-0 965 145
//@node 6EFB5B98-0 1450 200
//@node 9B1E6716-0 1730 200
//@node ACB79C87-0 2010 200
//@node CD10D04F-0 2290 200
//@node 82BEE3D1-0 2570 200
//@node 9521C9EA-0 2850 200
//@node 8E7E630A-0 3130 200
//@node 6D4EE0A3-0 3410 200
//@node 314348C6-0 3690 200
//@node 9D1B2B05-0 3970 200
//@node 27A87139-0 4250 200
//@node 6D36C203-0 4530 200
//@node 3FFBEABF-0 4810 200
//@node 2CBDBAB4-0 5090 200
//@node EF3EBDAC-0 5370 200
//@node AF1471AD-0 5650 200
//@node 8D886931-0 5930 200
//@node 52017D1D-0 6210 200
//@node DDA20363-0 6490 200
//@node 0D8E295B-0 6770 200
//@node C45BAE87-0 7050 200
//@node 03A82043-0 7330 200
//@node 4A17B8F4-0 7610 200
//@node ACB79C87-1 7890 200
//@node 573C90B8-0 8170 200
//@node 9521C9EA-1 8450 200
//@node 03A82043-1 8730 200
//@node 4A17B8F4-1 9010 200
//@node ACB79C87-2 9290 200
//@node 3F37307E-0 9570 200
//@node 9521C9EA-2 9850 200
//@node 919E5678-0 10130 200
//@node 8BA8B86E-0 10410 200
//@node 24C231DA-0 10690 200
//@node 6A0A065E-0 10970 200
//@node F6C69465-0 11250 200
//@node A7214F41-0 11530 200
//@node 74939ED0-0 11810 200
//@node 34940D11-0 12090 200
//@node A653E30F-0 12370 200
//@node D7108F46-0 12650 200
//@node 83BB0518-0 12930 200
//@node 371B1A6D-0 13210 200
//@node C426E566-0 13490 200
//@node 9D1B2B05-1 13770 200
//@node 6EFB5B98-1 14050 200
//@node 9B1E6716-1 14330 200
//@node ACB79C87-3 14610 200
//@node 64362EB3-0 14890 200
//@node 72762C15-0 15170 200
//@node 9521C9EA-3 15450 200
//@node 754ACC02-0 15730 200
//@node D4FBA690-0 16010 200
//@node ACB79C87-4 16290 200
//@node AF831735-0 16570 200
//@node 9521C9EA-4 16850 200
//@node 754ACC02-1 17130 200
//@node 4A17B8F4-2 17410 200
//@node 094268B7-0 17690 200
//@node 8AC79DF8-0 17970 200
//@node 9521C9EA-5 18250 200
//@node 9665771D-0 18530 200
//@node 7550A7FB-0 18810 200
//@node ACB79C87-5 19090 200
//@node 40606272-0 19370 200
//@node 9521C9EA-6 19650 200
//@node 9665771D-1 19930 200
//@node 4A17B8F4-3 20210 200
//@node D023B1F4-0 20490 200
//@node 9C4CF389-0 20770 200
//@node 9521C9EA-7 21050 200
//@node 6C5BE767-0 21330 200
//@node 4D4DEA96-0 21610 200
//@node 39EBEAEE-0 21890 200
//@node 6124C223-0 22170 200
//@node 02F42978-0 22450 200
//@node 9521C9EA-8 22730 200
//@node DD957EDB-0 23010 200
//@node 6124C223-1 23290 200
//@node 690F1479-0 23570 200
//@node 9521C9EA-9 23850 200
//@node A9E68D01-0 40 40
//@node 5EFC10AF-0 330 40
//@node D4123035-0 610 40
//@node 2B36F8B7-0 890 40
//@node 3795EB59-0 1170 40
//@node A231F298-0 1450 40
//@node C8B48367-0 1730 40
//@node 359FFC4A-0 2010 40
//@node 31D4AE0D-0 2290 40
//@node E22C7F80-0 2570 40
//@node 42E511E1-0 2850 40
//@node 2ACABA7B-0 3130 40
//@node 82CD4BEE-0 3410 40
//@node 730F6D47-0 3690 40
//@node 610A9852-0 3970 40
//@node 88A5895C-0 4250 40
//@node 6426C0F1-0 4530 40
//@node 712B2E68-0 4810 40
//@node A1B534B1-0 5090 40
//@node A8389E28-0 5370 40
//@node AEF7BBB6-0 5650 40
//@node 55BB1027-0 5930 40
//@node 638B67B5-0 6210 40
//@node B2D88B83-0 6490 40
//@node 1B4B227E-0 6770 40
//@node EC248B91-0 7050 40
//@node 1F645814-0 7330 40
//@node D553A09B-0 7610 40
//@node 0AB97216-0 7890 40
//@node FE7E98A9-0 8170 40
//@node A4FBD08C-0 8450 40
//@node 97ED1217-0 8730 40
//@node 955E08D4-0 9010 40
//@node 9054C798-0 9290 40
//@node D95C41F1-0 40 40
//@node 908264F5-0 330 40
//@node D16D8786-0 40 40
//@node F7140D6E-0 330 40
//@node D90C5B83-0 40 40
//@node 3CE8E1E6-0 330 40
//@node 9C5DBE59-0 40 40
//@node 8ECCF9FC-0 330 40
//@node 6FA340B2-0 40 40
//@node 1E27E223-0 330 40
//@node 9066F104-0 610 40
//@node 015E8930-0 890 40
//@node 03409ADE-0 1170 40
//@node 9C46611B-0 1450 40
//@node AC34E3F3-0 1730 40
//@node 5D593CDD-0 40 40
//@node EFBC0A5B-0 330 40
//@node 3AF5F1FC-0 40 40
//@node 596B9785-0 330 40
//@node 3771F39B-0 125 145
//@node 1F4F4439-0 -80 145
//@node F50EF00F-0 610 200
//@node C5EDFD59-0 385 305
//@node A09B7B8C-0 180 405
//@node 374EBD07-0 -25 405
//@node 96E98352-0 890 200
//@node B0C0808A-0 40 40
//@node B7008A5B-0 330 40
//@node FAAC2497-0 125 145
//@node 1C70545B-0 -80 145
//@node 5F3A0E2B-0 610 200
//@node 0B4D2D8F-0 385 305
//@node 82355A15-0 180 405
//@node 7B5FBDE0-0 -25 405
//@node D2A1BBF9-0 890 200
//@node CC4C494F-0 40 40
//@node BBE8FC3D-0 330 40
//@node AD806CB5-0 125 145
//@node 8BB61914-0 -80 145
//@node 5E4A3CC9-0 610 200
//@node AFA1B0A5-0 385 305
//@node 0DDA5E0C-0 180 405
//@node FCFB40C2-0 -25 405
//@node 6F6B6C59-0 890 200
//@node 04CD6B4B-0 40 40
//@node D6538AE9-0 330 40
//@node 385F90AF-0 125 145
//@node 788A6084-0 -80 145
//@node 7A2959B3-0 610 200
//@node B1198BFC-0 385 305
//@node A36FCA2F-0 180 405
//@node 2C1AF39B-0 -25 405
//@node D6B53ED6-0 890 200
//@node C9B4A91B-0 40 40
//@node A27328F8-0 330 40
//@node C5488020-0 610 40
//@node EEC21A4E-0 890 40
//@node 5FF5E0AE-0 1170 40
//@node 18DB3694-0 1450 40
//@node 866856A5-0 1730 40
//@node 7035C71A-0 2010 40
//@node C6750B15-0 2290 40
//@node 1959FA1A-0 2570 40
//@node 070CB5F2-0 2850 40
//@node A0C109C8-0 3130 40
//@node 3D8A83C2-0 3410 40
//@node 24675757-0 3690 40
//@node 1959FA1A-1 3970 40
//@node 5D040349-0 4250 40
//@node B9B4F98F-0 4530 40
//@node 47EF4657-0 4810 40
//@node 2A1FFC09-0 5090 40
//@node 46FAD33E-0 5370 40
//@node A0C109C8-1 5650 40
//@node 565FF076-0 5930 40
//@node A0C109C8-2 6210 40
//@node 49EECD51-0 6490 40
//@node 3E8D9E77-0 6770 40
//@node AD0C51F7-0 7050 40
//@node 6819020B-0 7330 40
//@node B82A9058-0 7610 40
//@node FD326872-0 7890 40
//@node C4F44956-0 8170 40
//@node 1D2B5D9A-0 8450 40
//@node D90853DC-0 8730 40
//@node AD0C51F7-1 9010 40
//@node 509E415F-0 9290 40
//@node 1959FA1A-2 9570 40
//@node 34BF1250-0 9850 40
//@node 1959FA1A-3 10130 40
//@node 0E5935E6-0 10410 40
//@node 0FDF70C3-0 10690 40
//@node 1959FA1A-4 10970 40
//@node EE0B3269-0 11250 40
//@node A0FEE48A-0 11530 40
//@node F8AF40A2-0 11810 40
//@node 3D22CAD0-0 12090 40
//@node 910C1A26-0 12370 40
//@node AD0C51F7-2 12650 40
//@node 05EB8437-0 12930 40
//@node B8FBAC19-0 13210 40
//@node 83A49068-0 13490 40
//@node D490C4FA-0 13770 40
//@node 193EB069-0 14050 40
//@node DF90FF29-0 14330 40
//@node D490C4FA-1 14610 40
//@node 6F5FD490-0 14890 40
//@node 6CDF910C-0 40 40
//@node B013EAF6-0 330 40
//@node 9C620973-0 610 40
//@node 9B72DB3E-0 890 40
//@node 16753DDE-0 1170 40
//@node 1433C214-0 1450 40
//@node 68BE34A7-0 1730 40
//@node B0A66706-0 2010 40
//@node 884BCBD7-0 2290 40
//@node 102C325A-0 2570 40
//@node B00E62D7-0 2850 40
//@node 90EF07C6-0 3130 40
//@node 711A3DE4-0 3410 40
//@node BC01FD04-0 3690 40
//@node C33858C6-0 3970 40
//@node 5B30C1CB-0 4250 40
//@node BB1F88D4-0 4530 40
//@node A4907348-0 40 40
//@node 2AA23DAD-0 330 40
//@node 797D74B9-0 40 40
//@node 26D6C1B9-0 330 40
//@node CA14745E-0 40 40
//@node AF2758EB-0 330 40
//@node B7C07A33-0 610 40
//@node D4453490-0 890 40
//@node D87B33E3-0 40 40
//@node F3C43B80-0 610 40
//@node 36F75F04-0 610 40
//@node AE7CF11D-0 405 145
//@node 6BF2A1E9-0 1170 40
//@node 4D5D68D6-0 1450 40
//@node FEF5F046-0 1730 40
//@node 9E72E5F1-0 1730 40
//@node 846BFB22-0 1525 145
//@node 8554A9B4-0 1320 145
//@node CBD3AC1A-0 2290 200
//@node 1A9B8850-0 2570 200
//@node 6555BD36-0 2570 200
//@node 48083FD8-0 2365 305
//@node 79888309-0 2850 360
//@node A853E75F-0 2625 465
//@node C5DB0B1A-0 3130 360
//@node 623D7C47-0 2905 465
//@node 3592FC4B-0 3410 360
//@node 0F27D410-0 3205 465
//@node 0123B2EE-0 3970 360
//@node C75053D5-0 3485 552
//@node F8F7098C-0 4250 360
//@node 7998B3D6-0 3765 552
//@node 4E770E0F-0 4530 360
//@node 24377B4F-0 4045 552
//@node E55EE52C-0 4530 360
//@node 3782451A-0 4325 465
//@node 0712545F-0 4120 465
//@node CF924782-0 4810 520
//@node 9132124C-0 5370 360
//@node 18A403B1-0 5650 200
//@node D25040FB-0 5930 200
//@node FC1467F4-0 6210 200
//@node 6099C8E3-0 6490 200
//@node 202CAF31-0 6770 200
//@node 60F38A6E-0 7050 200
//@node 4E39A725-0 7330 200
//@node 6BF2A1E9-1 7610 200
//@node 4D5D68D6-1 7890 200
//@node FEF5F046-1 8170 200
//@node FD4E7DBE-0 8170 200
//@node 2309A541-0 7965 305
//@node 0123B2EE-1 8730 200
//@node 75B74EB0-0 8245 392
//@node F8F7098C-1 9010 200
//@node C33AE1E3-0 8525 392
//@node 4E770E0F-1 9290 200
//@node AF98B062-0 8805 392
//@node C5566A8E-0 40 40
//@node E98900F2-0 330 40
//@node 24102580-0 610 40
//@node C6E0EE42-0 405 145
//@node F9C8D174-0 890 40
//@node 763B43F5-0 1170 40
//@node 63AA7D89-0 1450 40
//@node 04E1DF45-0 1730 40
//@node 21C632F7-0 1525 145
//@node 32060C22-0 1320 145
//@node F60BDD6D-0 2010 200
//@node 2781FA56-0 2290 200
//@node 16FDE6A3-0 2570 200
//@node 54EC45E7-0 2365 305
//@node AFB08F5E-0 2850 360
//@node ECFB2045-0 2625 465
//@node 04CBC1B6-0 3130 360
//@node 868A6B4C-0 2925 465
//@node 455392D7-0 3410 360
//@node 3106D2E7-0 3205 552
//@node 336B1179-0 3690 360
//@node F15DB76C-0 3485 552
//@node 9FC71A36-0 3970 360
//@node AE4C6806-0 3765 552
//@node CD14EF29-0 4250 360
//@node C55C2BA4-0 4045 465
//@node 63B7F19F-0 3840 465
//@node 46A05BFF-0 4530 520
//@node ED24E347-0 4810 360
//@node 6C28F9DA-0 5090 200
//@node 0FC8613A-0 5370 200
//@node 44ADCED7-0 5650 200
//@node AFB439F4-0 5930 200
//@node 21441070-0 6210 200
//@node 0F59C2E0-0 6490 200
//@node 77990D9E-0 6770 200
//@node F9C8D174-1 7050 200
//@node 763B43F5-1 7330 200
//@node 63AA7D89-1 7610 200
//@node 8B94FB56-0 7890 200
//@node 045C72AA-0 7685 305
//@node 455392D7-1 8170 200
//@node 53BA2C3A-0 7965 392
//@node 336B1179-1 8450 200
//@node 3FEA5681-0 8245 392
//@node 9FC71A36-1 8730 200
//@node CC1C95D3-0 8525 392
//@node 3F42CD7F-0 40 40
//@node B762DF9A-0 330 40
//@node 099864BF-0 610 40
//@node B0315ADA-0 890 40
//@node 3EBF9CE3-0 1170 40
//@node AEE7FEDB-0 1450 40
//@node A25C1150-0 1730 40
//@node 94BB96DF-0 1525 145
//@node 96C96BFE-0 1320 145
//@node 4EBA5D4C-0 1320 229
//@node 9A9C5985-0 2010 200
//@node 2C5F7B25-0 2290 200
//@node EB4F019F-0 2570 200
//@node EBAA441A-0 2345 305
//@node A4C6BD25-0 2850 200
//@node C4D3892B-0 2645 305
//@node 3D390EEE-0 3130 200
//@node E303D3AB-0 2925 392
//@node 80DBE58C-0 3410 200
//@node 2DE8F0BA-0 3205 392
//@node D65BEA0F-0 3690 200
//@node 55C7EEAA-0 3485 392
//@node A9757809-0 3970 200
//@node 97062E95-0 3765 305
//@node 27324100-0 3560 305
//@node 2289FE6E-0 4250 200
//@node 2C5F7B25-1 4530 200
//@node EB4F019F-1 4810 200
//@node E229EF79-0 4585 305
//@node A4C6BD25-1 5090 200
//@node 1AC238A6-0 4885 305
//@node 3D390EEE-1 5370 200
//@node A1C0FA3E-0 5165 392
//@node 80DBE58C-1 5650 200
//@node 0B359767-0 5445 392
//@node D65BEA0F-1 5930 200
//@node 448FF717-0 5725 392
//@node F6C9D7B1-0 6210 40
//@node 9D971CFB-0 6490 40
//@node 682C3DE9-0 6770 40
//@node 2B833CD6-0 7050 40
//@node DD1BC446-0 7330 40
//@node 9170609B-0 40 40
//@node A3EBE8E1-0 330 40
//@node B3C4797C-0 105 145
//@node 2D1C2887-0 610 40
//@node 2C5E2C18-0 405 140
//@node 616DE6E5-0 890 40
//@node 88B6638F-0 1170 40
//@node 7A9B29F7-0 945 145
//@node 2D1C2887-1 1450 40
//@node 9DF3F485-0 1245 140
//@node 186B2B3B-0 1730 40
//@node 4A5D1199-0 2010 40
//@node 54E849A2-0 1785 145
//@node 2D1C2887-2 2290 40
//@node B0FEBB7E-0 2085 140
//@node B388B94C-0 2570 40
//@node F804C20D-0 2850 40
//@node 26CA78F9-0 2625 145
//@node 2D1C2887-3 3130 40
//@node F44A51FB-0 2925 140
//@node BDFE9991-0 3410 40
//@node 7442DA00-0 3690 40
//@node 5B50FD56-0 3465 145
//@node 2D1C2887-4 3970 40
//@node BC41AB64-0 3765 140
//@node 5944CA12-0 4250 40
//@node CF3B7AE0-0 4530 40
//@node 90873BE3-0 4305 145
//@node 2D1C2887-5 4810 40
//@node 50079F91-0 4605 140
//@node 6CF7EB6F-0 5090 40
//@node BF3C1C3F-0 5370 40
//@node 6AA4D7E9-0 5145 145
//@node 2D1C2887-6 5650 40
//@node 6B2AFC9A-0 5445 140
//@node 781629D0-0 5930 40
//@node 87E3578C-0 6210 40
//@node B2A75210-0 5985 145
//@node 2D1C2887-7 6490 40
//@node F9613177-0 6285 140
//@node 9270622E-0 40 40
//@node E36981C1-0 330 40
//@node 95DF0B4B-0 105 145
//@node 87EBA144-0 610 40
//@node 3E2F881A-0 405 140
//@node CB53C73F-0 890 40
//@node E36981C1-1 1170 40
//@node 4EB8F4FA-0 945 145
//@node 87EBA144-1 1450 40
//@node CC65BCF7-0 1245 140
//@node 993B7B89-0 1730 40
//@node EFDAAB48-0 2010 40
//@node 255E02C8-0 1785 145
//@node 87EBA144-2 2290 40
//@node 8F4636E4-0 2085 140
//@node B4D0946A-0 2570 40
//@node 43EF738E-0 2850 40
//@node C2AC3154-0 2625 145
//@node 87EBA144-3 3130 40
//@node 230C2B11-0 2925 140
//@node 47E51B87-0 3410 40
//@node E36981C1-2 3690 40
//@node F9D701E9-0 3465 145
//@node 87EBA144-4 3970 40
//@node 840346FE-0 3765 140
//@node D264BFA8-0 4250 40
//@node D4DB206F-0 4530 40
//@node 606FD529-0 4305 145
//@node 87EBA144-5 4810 40
//@node C74EDD7B-0 4605 140
//@node 937063C1-0 40 40
//@node 4D193C9E-0 330 40
//@node A6B2C3D8-0 105 145
//@node 96746F69-0 610 40
//@node C716BA46-0 405 140
//@node 0F88C3E0-0 890 40
//@node 6C875946-0 1170 40
//@node AC979F14-0 945 145
//@node 96746F69-1 1450 40
//@node F931A323-0 1245 140
//@node 85091FBF-0 1730 40
//@node 313D58E8-0 2010 40
//@node C76EA45B-0 1785 145
//@node 96746F69-2 2290 40
//@node BF9A9C60-0 2085 140
//@node B974F7A5-0 2570 40
//@node AF4188E9-0 2850 40
//@node 344BE370-0 2625 145
//@node 96746F69-3 3130 40
//@node C695C8ED-0 2925 140
//@node 94706554-0 40 40
//@node 12B2E2B3-0 330 40
//@node DE916B5E-0 105 145
//@node 4ED6A376-0 610 40
//@node 2E3ADB28-0 405 140
//@node 05F26FAD-0 890 40
//@node 69DBE155-0 1170 40
//@node C05B8A42-0 945 145
//@node 4ED6A376-1 1450 40
//@node A6F13895-0 1245 140
//@node 23FD5C3B-0 1730 40
//@node 69DBE155-1 2010 40
//@node C2E6CCB3-0 1785 145
//@node 4ED6A376-2 2290 40
//@node 0D74464E-0 2085 140
//@node 64D6FB12-0 2570 40
//@node 58FFDE5A-0 2850 40
//@node 7D5D11A7-0 2625 145
//@node 4ED6A376-3 3130 40
//@node 79FC150B-0 2925 140
//@node C990CA91-0 3410 40
//@node D104CA97-0 3690 40
//@node 8ED918A6-0 3465 145
//@node 4ED6A376-4 3970 40
//@node E4AA46B4-0 3765 140
//@node 83A85AD0-0 4250 40
//@node 69DBE155-2 4530 40
//@node 8D0055E8-0 4305 145
//@node 4ED6A376-5 4810 40
//@node 7C538A61-0 4605 140
//@node 957066E7-0 40 40
//@node 08324FE8-0 330 40
//@node E2431582-0 105 145
//@node 35371603-0 610 40
//@node 6E9CCFC3-0 405 140
//@node D60A3EFC-0 890 40
//@node 08324FE8-1 1170 40
//@node 114783F3-0 945 145
//@node 35371603-1 1450 40
//@node 7C8580E6-0 1245 140
//@node 47DD7959-0 1730 40
//@node 1CECC6C3-0 2010 40
//@node 74BCE44D-0 1785 145
//@node 35371603-2 2290 40
//@node 2017DA0D-0 2085 140
//@node 6372923A-0 2570 40
//@node A6D5EEA2-0 2850 40
//@node 38E86D0F-0 2625 145
//@node 35371603-3 3130 40
//@node BF950480-0 2925 140
//@node 2F09CB8E-0 3410 40
//@node D7B13DE7-0 3690 40
//@node AF34CF59-0 3465 145
//@node 35371603-4 3970 40
//@node F39FB97F-0 3765 140
//@node A48A276D-0 4250 40
//@node 03B789CC-0 4530 40
//@node BFFEBA41-0 4305 145
//@node 35371603-5 4810 40
//@node 777A5B62-0 4605 140
//@node 5DB2A20C-0 5090 40
//@node 37230153-0 5370 40
//@node 893779B2-0 5145 145
//@node 35371603-6 5650 40
//@node 3F13A319-0 5445 140
//@node C29513FB-0 5930 40
//@node 3586D60E-0 6210 40
//@node F936B2B5-0 5985 145
//@node 35371603-7 6490 40
//@node 2B0BE3CC-0 6285 140
//@node 036EB2D2-0 6770 40
//@node 72420F6C-0 7050 40
//@node 8B70B77A-0 6825 145
//@node 35371603-8 7330 40
//@node 5A69F7FB-0 7125 140
//@node 68288251-0 7610 40
//@node 37230153-1 7890 40
//@node FF1EC423-0 7665 145
//@node 35371603-9 8170 40
//@node 171E617E-0 7965 140
//@node 7BC64FC2-0 8450 40
//@node 4B16476A-0 8730 40
//@node C351464B-0 8505 145
//@node 35371603-10 9010 40
//@node DDC3DF6E-0 8805 140
//@node 1A96E600-0 9290 40
//@node C67282EF-0 9570 40
//@node FCA373EF-0 9345 145
//@node 35371603-11 9850 40
//@node 33597AAB-0 9645 140
//@node 9CE0FADD-0 10130 40
//@node 4B16476A-1 10410 40
//@node 7C2B2FFA-0 10185 145
//@node 35371603-12 10690 40
//@node 0CCB2848-0 10485 140
//@node 10B6AE10-0 40 40
//@node 1E00FBE2-0 330 40
//@node C480C769-0 610 40
//@node 1843D2BC-0 890 40
//@node 3EEB7733-0 1170 40
//@node 7DEBB756-0 1450 40
//@node 5841471E-0 40 40
//@node F80B492F-0 330 40
//@node 2ADD85BE-0 40 40
//@node BAF25E04-0 330 40
//@node 4BD6AEA2-0 40 40
//@node F68B911C-0 330 40
//@node 54EA85D0-0 610 40
//@node 9C8FB9DB-0 405 140
//@node 8CAE85F3-0 890 40
//@node 814B64EF-0 685 232
//@node 0635FE57-0 1170 40
//@node 32687650-0 40 40
//@node 661149AF-0 330 40
//@node 95AA0545-0 610 40
//@node A31C6B1D-0 890 40
//@node DC4C0128-0 1170 40
//@node 5B2B34E5-0 1450 40
//@node B912962E-0 1730 40
//@node 7B29D1CF-0 2010 40
//@node 3318DAC2-0 2290 40
//@node A3A172B7-0 2570 40
//@node 56BA1BF0-0 2850 40
//@node 47D43FF6-0 3130 40
//@node 39AF0375-0 3410 40
//@node 66DEB8B5-0 3690 40
//@node DAAFCA56-0 3970 40
//@node B8BA0CDD-0 4250 40
//@node 772658C0-0 4530 40
//@node 86933AAE-0 4810 40
//@node 3304E427-0 5090 40
//@node E3A58D00-0 5370 40
//@node CA5B36E6-0 5650 40
//@doomscript-blueprint end
