void make_player_cough() {

	$player1.startSoundShader ("player_cough", SND_CHANNEL_VOICE);
}

namespace map_recycling2 {

	void mover_startsound (entity ent) {
		ent.startSoundShader ("m1_start", SND_CHANNEL_VOICE);
		sys.wait (0.75);
		ent.startSoundShader ("m1_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound (entity ent) {
		ent.startSoundShader ("m1_stop", SND_CHANNEL_VOICE2);
		ent.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_ITEM );
	}
	
	void mover_startsound2 (entity ent) {
		ent.startSoundShader ("m2_start", SND_CHANNEL_VOICE);
		sys.wait (0.75);
		ent.startSoundShader ("m2_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound2 (entity ent) {
		ent.startSoundShader ("m2_stop", SND_CHANNEL_VOICE2);
	}

	void mover_startsound3 (entity ent) {
		ent.startSoundShader ("m3_start", SND_CHANNEL_VOICE);
		sys.wait (1);
		ent.startSoundShader ("m3_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound3 (entity ent) {
		ent.startSoundShader ("m3_stop", SND_CHANNEL_VOICE2);
	}


	void setup_objects ()
	{
			$pump1nozzle1.bind ($pump1axis);
			$pump1_tubecap.bind ($pump1_tube);
			$pump1_tube.bind ($pump1_tube_anchor);
			$cyl_1.bind ($cyl_1_anchor);
			$elev2_light.bind ($elev1);
			//$elev2_speaker.bind ($elev1);			
			$walkway.bind ($walkway_anchor);
			$light_warning_spin.bind ($light_warning_anchor);
			$light_warning_2.bind ($light_warning_anchor);
			$light_warning_flare.bind ($light_warning_anchor);
			$light_warning_off.bind ($light_warning_anchor);
			$light_warning_on.bind ($light_warning_anchor);
                        
	}

	///////////////////
	// first pump room
	//////////////////

	void pump1piston1_start ()
	{
		while (1)
		{ 
				$pump1piston1.accelTime (.5);
				$pump1piston1.decelTime (.2);
				$pump1piston1.time (1);
				thread mover_startsound ($pump1piston1);
				$pump1piston1.moveTo ($pump1piston1_btm);
				sys.waitFor ($pump1piston1);
				mover_stopsound ($pump1piston1);
		        
				sys.wait (1);
		        
				$pump1piston1.accelTime (.5);
				$pump1piston1.decelTime (.8);
				
				thread mover_startsound ($pump1piston1);
				
				$pump1piston1.time (1.6);
				$pump1piston1.moveTo ($pump1piston1_top);
				sys.waitFor ($pump1piston1);
				
				mover_stopsound ($pump1piston1);
		}
	}

	void pump1piston2_start ()
	{
		while (1)
		{              
				$pump1piston2.time (1.5);
				thread mover_startsound3 ($pump1piston2);
				$pump1piston2.move (DOWN ,96);
				sys.waitFor ($pump1piston2);
				mover_stopsound2 ($pump1piston2);

				sys.wait (.5);

				$pump1piston2.time (2);
				thread mover_startsound3 ($pump1piston2);
				$pump1piston2.move (UP ,96);
				sys.waitFor ($pump1piston2);
				mover_stopsound3 ($pump1piston2);
				sys.wait (.5);
		}
	}

	void pump1machine_start ()
	{
		while (1)
		{ 
				$pump1axis.decelTime (.5);                        
				$pump1axis.time (1);
				$pump1axis.rotateOnce ('0 180 0');
				sys.waitFor ($pump1axis);

				sys.trigger ($pump1_bubbles);

				$pump1_tube_anchor.time (.5);
				$pump1_tube_anchor.rotateOnce ('0 0 90');
				sys.waitFor ($pump1_tube_anchor);
	                        
				$pump1_tubecap.unbind ();
				$pump1_tubecap.time (.5);
				$pump1_tubecap.moveTo ($pump1_tubecap_spot2);
				sys.waitFor ($pump1_tubecap);
				$pump1_tubecap.bind ($pump1nozzle1);

				$pump1speaker.startSoundShader("sact1_vent_1s", SND_CHANNEL_ANY );
		   
				$pump1nozzle1.time (.5);
				$pump1nozzle1.rotateOnce ('0 0 360');
				sys.waitFor ($pump1nozzle1);
				$pump1_tubecap.unbind ();

				sys.trigger ($pump1_bubbles);

				sys.wait (1.5);
	                        
				$pump1_tubecap.time (.5);
				$pump1_tubecap.moveTo ($pump1_tubecap_spot1);
				sys.waitFor ($pump1_tubecap);
				$pump1_tubecap.bind ($pump1_tube);
	                        	        
				$pump1_tube_anchor.time (.5);
				$pump1_tube_anchor.rotateOnce ('0 0 -90');
				sys.waitFor ($pump1_tube_anchor);
		       
				$pump1axis.decelTime (.5);                        
				$pump1axis.time (1);
				$pump1axis.rotateOnce ('0 180 0');
				sys.waitFor ($pump1axis);

							sys.trigger ($pump1_bubbles);

				$pump1_tube_anchor.time (.5);
				$pump1_tube_anchor.rotateOnce ('0 0 90');
				sys.waitFor ($pump1_tube_anchor);

				$pump1_tubecap.unbind ();
				$pump1_tubecap.time (.5);
				$pump1_tubecap.moveTo ($pump1_tubecap_spot2);
				sys.waitFor ($pump1_tubecap);
				$pump1_tubecap.bind ($pump1nozzle1);

							$pump1speaker.startSoundShader("sact1_vent_1s", SND_CHANNEL_ANY );
		   
				$pump1nozzle1.time (.5);
				$pump1nozzle1.rotateOnce ('0 0 360');
				sys.waitFor ($pump1nozzle1);
				$pump1_tubecap.unbind ();

							sys.trigger ($pump1_bubbles);

							sys.wait (1.5);
	                        
				$pump1_tubecap.time (.5);
				$pump1_tubecap.moveTo ($pump1_tubecap_spot1);
				sys.waitFor ($pump1_tubecap);
				$pump1_tubecap.bind ($pump1_tube);

	                        
		        
				$pump1_tube_anchor.time (.5);
				$pump1_tube_anchor.rotateOnce ('0 0 -90');
				sys.waitFor ($pump1_tube_anchor);
		                       
		}
	}

        void block_door ()
        {
                                             
                        sys.trigger ($block_door);
                          
        }

         void bust_window ()
        {
                        
                        sys.trigger ($imp_1);
                        sys.wait (1);
                        sys.trigger ($bustfield1);
                        sys.trigger ($bustout1);
                 
                        sys.wait (4);
                        sys.trigger ($imp_2);
                        sys.wait (1);
                        sys.trigger ($bustfield2);
                        sys.trigger ($bustout2);                                                                                                                                   
        }
	
	void light_warning_on ()
	{ 
	             
			$light_warning_off.hide ();
			$light_warning_on.show (); 
			$light_warning_flare.show ();
			$light_warning_anchor.rotate ('0 200 0');	
			sys.trigger ($speaker_alarm1);			             
	}
        
        void change1 ()
        { 
               $btrigger2.remove ();
               $firstroom_on2.remove ();         
               $speaker_290.remove();
        }
        void change2 ()
        {      
               $btrigger1.remove ();
               $firstroom_on1.remove ();
               $mainscreen.setGuiParm ( "gui_parm1" , 2);
               $screen2.setGuiParm ( "gui_parm1" , 2);
               $screen4.setGuiParm ( "gui_parm1" , 2);
               $speaker_291.remove();
        }
        

	///////////////////
	// first gas room
	//////////////////

	void ventgas_off ()
	{              	       
      		sys.trigger ($ventgas1);
			sys.trigger ($ventgas2);
            sys.wait (.5);
            sys.trigger ($ventgas1_in);
		    sys.trigger ($ventgas2_in);
            sys.wait (4);
            sys.trigger ($ventgas1_in);
		    sys.trigger ($ventgas2_in);               
	}	

	///////////////////
	// exit gas room
	//////////////////

	void exitgas1_off ()
	{              
	       sys.trigger ($exitgas1);
               sys.wait (.5);
               sys.trigger ($exitgas1_in);
	                    
	}
	void exitgas2_off ()
	{              
	        sys.trigger ($exitgas2);
            sys.wait (.5);
            sys.trigger ($exitgas2_in);
	                   
	}
	void exitgas3_off ()
	{              
	        sys.trigger ($exitgas3);
            sys.wait (.5);
            sys.trigger ($exitgas3_in);
	                    
	}
    
    void exitgas_in ()
	{              	   
		sys.wait (4);
		sys.trigger ($exitgas1_in);
		sys.trigger ($exitgas2_in);
		sys.trigger ($exitgas3_in);
		        
	}
                                             

	/////////////////
	// misc
	////////////////


	void pump2piston_start ()
	{
	while (1)
	{        
		$pump2piston.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE );
		$pump2piston.time (1);
		$pump2piston.moveTo ($pump2piston_spot1);
		sys.waitFor ($pump2piston);

		$pump2piston.startSoundShader ("rec2_pump_05s_01", SND_CHANNEL_VOICE2 );
		$pump2piston.time (0.5);
		$pump2piston.moveTo ($pump2piston_spot2);
		sys.waitFor ($pump2piston);

	}                 
	}

	void cyl1_start ()
	{
	while (1)
	{    
            sys.trigger ($cyl1_gas);
           
			$vent1.time (.5);       
			$vent1.rotateOnce ('0 -100 0');
			$vent2.time (.5);       
			$vent2.rotateOnce ('0 -70 0');
			$vent3.time (.5);       
			$vent3.rotateOnce ('0 -70 0');
			$thingspeaker.startSoundShader("sact1_vent_05s_close", SND_CHANNEL_ANY );
			sys.wait (.5); 
	     
			$cyl_1_anchor.time (1);
			$cyl_1_anchor.rotateOnce ('0 -150 0');
			$thingspeaker.startSoundShader("sact1_vent_1s", SND_CHANNEL_ANY );
			sys.waitFor ($cyl_1_anchor);
                         
			sys.wait (2);

			$cyl_1_anchor.time (1);
			$cyl_1_anchor.rotateOnce ('0 150 0');   
			$thingspeaker.startSoundShader("sact1_vent_1s", SND_CHANNEL_ANY );
			sys.waitFor ($cyl_1_anchor);

			sys.wait (.5);

			$vent1.time (.5);       
			$vent1.rotateOnce ('0 100 0');
			$vent2.time (.5);       
			$vent2.rotateOnce ('0 70 0');
			$vent3.time (.5);       
			$vent3.rotateOnce ('0 70 0');
			$thingspeaker.startSoundShader("sact1_vent_05s_open", SND_CHANNEL_ANY );

			sys.trigger ($cyl1_gas);

			sys.wait (3);
	        
	}
	}


	void lamp_sway1 ()
	{

			$storageswing_lamp1.sway( 25, 0, '20 10 10' );

	}

        void wallbox1_turn ()
	{

                        $wallbox1.time (.3);
			$wallbox1.rotateOnce ('0 0 -8');
                        $wallbox1_speaker.startSoundShader("smallpanel_impact", SND_CHANNEL_ANY );

	}

        void underhall_lights ()
	{
	while (1)
	{ 
			sys.trigger ($underhall_fadein1);
                        sys.trigger ($underhall_fadein2);
			
			sys.wait (.7);

                        sys.trigger ($underhall_fadeout1);
                        sys.trigger ($underhall_fadeout2);
			
			sys.wait (.3);
        }
        }

        void elev_crash ()
	{

			$elev1.bind ($elev_mover);
                        $elev_mover.accelTime (.4);
                        $elev_mover.time (1.5);
                        $elev_mover.move (DOWN , 612);

	}
        
	/////////////////////
	// mancubusroom
	////////////////////	

	void walkway_fall ()
	{              
			$walkway_anchor.startSoundShader ("rec1_bridge_fall", SND_CHANNEL_VOICE );
			$walkway_anchor.time (.6);
			$walkway_anchor.accelTime (.4);
			$walkway_anchor.rotateOnce ('18 0 0');
            $walkway_speaker.startSoundShader("smallpanel_impact", SND_CHANNEL_ANY );

			sys.waitFor ($walkway_anchor);

			$walkway_anchor.time (.2);
			$walkway_anchor.decelTime (.1);
			$walkway_anchor.rotateOnce ('-5 0 0');
			$walkway_anchor.time (.1);
			$walkway_anchor.rotateOnce ('5 0 0');
	             
	}

	void cache_sounds() {
		sys.cacheSoundShader ("player_cough");
		sys.cacheSoundShader ("m1_start");
		sys.cacheSoundShader ("m1_stop");
		sys.cacheSoundShader ("m1_loop");
		sys.cacheSoundShader ("m2_start");
		sys.cacheSoundShader ("m2_stop");
		sys.cacheSoundShader ("m2_loop");
		sys.cacheSoundShader ("m3_start");
		sys.cacheSoundShader ("m3_stop");
		sys.cacheSoundShader ("m3_loop");
		sys.cacheSoundShader ("sact1_vent_1s");
		sys.cacheSoundShader ("sact1_vent_05s_close");
		sys.cacheSoundShader ("sact1_vent_05s_open");
		sys.cacheSoundShader ("rec2_pump_1s_01");
		sys.cacheSoundShader ("rec2_pump_05s_01");
		sys.cacheSoundShader ("smallpanel_impact");
		sys.cacheSoundShader ("rec1_bridge_fall");
	}

	 
	void main ()
	{
		cache_sounds();
		setup_objects();
		pump2piston_start();

	}
}

//@doomscript-blueprint begin 6
//@source 8E1142BB
//@catalog 0C260740
//@node CC4213E0-0 40 40
//@node 00647D3C-0 330 40
//@node F466D044-0 40 40
//@node CA5263B4-0 330 40
//@node 46F65A20-0 610 40
//@node 4B63AAC8-0 890 40
//@node 3FC7A4DE-0 40 40
//@node CFDF7FE8-0 330 40
//@node 314B301A-0 610 40
//@node 33DA29C2-0 40 40
//@node BCB6EFCF-0 330 40
//@node 81F95EB6-0 610 40
//@node 288C79D3-0 890 40
//@node 53489F84-0 40 40
//@node 5F309A0F-0 330 40
//@node 34DA2B55-0 40 40
//@node 8E5EE9DF-0 330 40
//@node 327B6418-0 610 40
//@node 7649E7E3-0 890 40
//@node 5448A117-0 40 40
//@node 125C1897-0 330 40
//@node 7AEA71C1-0 40 40
//@node BEDBDAD0-0 330 40
//@node 36FBE38E-0 610 40
//@node 73709EAC-0 890 40
//@node 48B68ED6-0 1170 40
//@node AA787962-0 1450 40
//@node DD41A262-0 1730 40
//@node 564A87B1-0 2010 40
//@node 643D99CD-0 2290 40
//@node FDDE3573-0 2570 40
//@node 6CAB46DA-0 2850 40
//@node 1828E650-0 3130 40
//@node 8D1B5AB5-0 40 40
//@node 87A05BEA-0 330 40
//@node 3EA85003-0 125 145
//@node 9F960D1E-0 610 200
//@node A780EF4E-0 890 200
//@node 9A350ABA-0 1170 200
//@node 0E0EB84D-0 1450 200
//@node 1980760B-0 1730 200
//@node D22FD13F-0 2010 200
//@node 4A79822D-0 2290 200
//@node 12E7C04C-0 2570 200
//@node 9F960D1E-1 2850 200
//@node BCE885A4-0 3130 200
//@node 0E0EB84D-1 3410 200
//@node F92F5EDE-0 3690 200
//@node 77ECA719-0 3970 200
//@node D22FD13F-1 4250 200
//@node 4A79822D-1 4530 200
//@node EDE4E754-0 40 40
//@node 59169E8F-0 330 40
//@node A507C45C-0 125 145
//@node AC44E71F-0 610 200
//@node F4EF6E9A-0 890 200
//@node 810331A0-0 1170 200
//@node 293635B1-0 1450 200
//@node 2E9611AF-0 1730 200
//@node D5D9C74F-0 2010 200
//@node 57DD302B-0 2290 200
//@node F4EF6E9A-1 2570 200
//@node 6845586D-0 2850 200
//@node 293635B1-1 3130 200
//@node 9F6D8516-0 3410 200
//@node D5D9C74F-1 3690 200
//@node EA0D8C9C-0 40 40
//@node D8F5AFE7-0 330 40
//@node 141E0D77-0 125 145
//@node B420A931-0 610 200
//@node 9A35D724-0 890 200
//@node D071430F-0 1170 200
//@node 57F7DF1D-0 1450 200
//@node 75A06E3C-0 1730 200
//@node D02E0C38-0 2010 200
//@node 4DEC4CB7-0 2290 200
//@node 0052B8ED-0 2570 200
//@node 4A85F1D0-0 2850 200
//@node 31F913F4-0 3130 200
//@node C0F17BC1-0 3410 200
//@node CC5131E1-0 3690 200
//@node 385AFCF1-0 3970 200
//@node 359BB30D-0 4250 200
//@node 7143EEC8-0 4530 200
//@node C3C78363-0 4810 200
//@node FED040A7-0 5090 200
//@node 4A85F1D0-1 5370 200
//@node 75A06E3C-1 5650 200
//@node EFFC1708-0 5930 200
//@node 31F913F4-1 6210 200
//@node 7A69A840-0 6490 200
//@node CC5131E1-1 6770 200
//@node 22255261-0 7050 200
//@node D02E0C38-1 7330 200
//@node E1277088-0 7610 200
//@node 0052B8ED-1 7890 200
//@node B420A931-1 8170 200
//@node 9A35D724-1 8450 200
//@node D071430F-1 8730 200
//@node 57F7DF1D-1 9010 200
//@node 75A06E3C-2 9290 200
//@node D02E0C38-2 9570 200
//@node 4DEC4CB7-1 9850 200
//@node 0052B8ED-2 10130 200
//@node 4A85F1D0-2 10410 200
//@node 31F913F4-2 10690 200
//@node C0F17BC1-1 10970 200
//@node CC5131E1-2 11250 200
//@node 385AFCF1-1 11530 200
//@node 359BB30D-1 11810 200
//@node 7143EEC8-1 12090 200
//@node C3C78363-1 12370 200
//@node FED040A7-1 12650 200
//@node 4A85F1D0-3 12930 200
//@node 75A06E3C-3 13210 200
//@node EFFC1708-1 13490 200
//@node 31F913F4-3 13770 200
//@node 7A69A840-1 14050 200
//@node CC5131E1-3 14330 200
//@node 22255261-1 14610 200
//@node D02E0C38-3 14890 200
//@node E1277088-1 15170 200
//@node 0052B8ED-3 15450 200
//@node 21D03EF7-0 40 40
//@node 70C418E4-0 330 40
//@node 27BEE0AC-0 40 40
//@node 1D1D1FB7-0 330 40
//@node 3B1F6D25-0 610 40
//@node 698CD8DA-0 890 40
//@node E530EA8A-0 1170 40
//@node 9A03F88A-0 1450 40
//@node 896AC7DA-0 1730 40
//@node 3B1F6D25-1 2010 40
//@node FD3F30B7-0 2290 40
//@node 784571A7-0 2570 40
//@node 9CF40D9C-0 40 40
//@node E210F4AF-0 330 40
//@node F02C2766-0 610 40
//@node FB14B925-0 890 40
//@node 19251EFE-0 1170 40
//@node 826CCB7D-0 1450 40
//@node 7916840C-0 40 40
//@node 7D234EB8-0 330 40
//@node F1E7641D-0 610 40
//@node ECF8F99D-0 890 40
//@node 7C1688C5-0 40 40
//@node 0701B77E-0 330 40
//@node 3CECD32F-0 610 40
//@node 7ED14214-0 890 40
//@node EDC9E5BF-0 1170 40
//@node CF5A6BE1-0 1450 40
//@node 43F69B55-0 1730 40
//@node 6D4F8B25-0 40 40
//@node E93FDADF-0 330 40
//@node D62C1D42-0 610 40
//@node 968ECE40-0 890 40
//@node 916BA727-0 1170 40
//@node 19CC9368-0 1450 40
//@node 536AC263-0 1730 40
//@node 916BA727-1 2010 40
//@node 19CC9368-1 2290 40
//@node 9F5BFA77-0 40 40
//@node 60A2DBC6-0 330 40
//@node 41F9BC62-0 610 40
//@node 14165B14-0 890 40
//@node 0425003A-0 40 40
//@node 467E341C-0 330 40
//@node 2E8C0AA9-0 610 40
//@node CD8EBEF6-0 890 40
//@node 3AADC371-0 40 40
//@node AE860892-0 330 40
//@node 76FED0A4-0 610 40
//@node 9769FEB8-0 890 40
//@node FC3347F4-0 40 40
//@node 3DEA1E42-0 330 40
//@node 08B553B7-0 610 40
//@node DB78E338-0 890 40
//@node E36A6425-0 1170 40
//@node 6812795D-0 40 40
//@node 27502C22-0 330 40
//@node C52E14E5-0 125 145
//@node 578F1134-0 610 200
//@node 97547DAA-0 890 200
//@node 9458D01B-0 1170 200
//@node 5925D2B9-0 1450 200
//@node B3C5C37A-0 1730 200
//@node 12EF54F8-0 2010 200
//@node 020ABC2E-0 2290 200
//@node 5925D2B9-1 2570 200
//@node 3DB4AC15-0 40 40
//@node DC8B98CA-0 330 40
//@node 21BBB7F0-0 125 145
//@node CC313FE1-0 610 200
//@node F552F973-0 890 200
//@node 4B3D890D-0 1170 200
//@node BA1086D0-0 1450 200
//@node AB2AE076-0 1730 200
//@node 07984A49-0 2010 200
//@node 5B393FBD-0 2290 200
//@node 7DE60680-0 2570 200
//@node 1BBAB354-0 2850 200
//@node 3E0EBF5D-0 3130 200
//@node 468F7BA2-0 3410 200
//@node 18967ECF-0 3690 200
//@node E535D420-0 3970 200
//@node 4A5DE9C5-0 4250 200
//@node 3E0EBF5D-1 4530 200
//@node 5104FA7D-0 4810 200
//@node 18967ECF-1 5090 200
//@node E535D420-1 5370 200
//@node 1BBAB354-1 5650 200
//@node F552F973-1 5930 200
//@node E05750D2-0 6210 200
//@node BA1086D0-1 6490 200
//@node 12773C5D-0 6770 200
//@node 07984A49-1 7050 200
//@node 0A8C2F80-0 7330 200
//@node BF856FB4-0 7610 200
//@node CC313FE1-1 7890 200
//@node 557C2826-0 8170 200
//@node A8B56BDF-0 40 40
//@node 6D52DCC3-0 330 40
//@node BB508DD9-0 40 40
//@node 06912205-0 330 40
//@node F775DB70-0 610 40
//@node CC33C8DB-0 890 40
//@node 1196AB86-0 40 40
//@node BE578055-0 330 40
//@node 52E798F8-0 125 145
//@node 0A0848C1-0 610 200
//@node C3807540-0 890 200
//@node CE82A33B-0 1170 200
//@node BE2DEBAA-0 1450 200
//@node 514272C7-0 1730 200
//@node 230F636F-0 2010 200
//@node C7E7A78B-0 40 40
//@node 4E9BB629-0 330 40
//@node D58332D0-0 610 40
//@node F26E2866-0 890 40
//@node 1A7F893D-0 1170 40
//@node DB8CDA51-0 40 40
//@node 57D9B958-0 330 40
//@node 5E40643E-0 610 40
//@node 7730380E-0 890 40
//@node C77940E8-0 1170 40
//@node 83124125-0 1450 40
//@node D113EA00-0 1730 40
//@node 32077AC2-0 2010 40
//@node 754F26C0-0 2290 40
//@node A2393481-0 2570 40
//@node 451B385F-0 2850 40
//@node 323B5E2E-0 3130 40
//@node B832CE32-0 40 40
//@node 46459F05-0 330 40
//@node F53CAC1E-0 610 40
//@node 93661762-0 890 40
//@node 72954FBC-0 1170 40
//@node 05E56F1D-0 1450 40
//@node 4A502E3B-0 1730 40
//@node D701E55D-0 2010 40
//@node 38E5367C-0 2290 40
//@node 056F2974-0 2570 40
//@node 2F20A2E6-0 2850 40
//@node 813EC724-0 3130 40
//@node 8E681029-0 3410 40
//@node 867952E3-0 3690 40
//@node 3E4C6039-0 3970 40
//@node 2F1BB127-0 4250 40
//@node 0CB8D5F9-0 4530 40
//@node 792BA2BE-0 4810 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 67C3ED48-0 610 40
//@node 5DDBDE74-0 890 40
//@doomscript-blueprint end
