namespace map_enpro {

	// Set up exit room sounds for after the battle sequence. Trigger all this stuff when the player
	// swaps out the rod.
	
	void xianstuff() {
		sys.trigger ($speaker_burn_1);			// flame1 in exit room
		sys.trigger ($speaker_burn_2);			// flame2 in exit room
		sys.trigger ($speaker_alarm_1);			// alarm sound in exit room
		sys.trigger ($speaker_badgen_1);		// Red sound for damaged core :: Turns it off
		sys.trigger ($speaker_goodgen_1);		// Blue sound for fixed core :: Turns it on 
		sys.trigger ($rflames);					// Turns off flame sounds for fixed rod 2
		sys.trigger ($speaker_fixed_rod);		// Turns on good sound for fixed rod 2
	}

	
	void setup_objects()
	{       
                //  ceiling room
                  $ceiling_cover.bind ($ceiling_cover_anchor);
                  $ceilingroom_pipe.bind ($ceilingroom_pipe_anchor);
              
                  $ceiling_cover_anchor.accelTime (.5);
                  $ceiling_cover_anchor.time (.5);
                  $ceilingroom_pipe_anchor.accelTime (.3);                  
                  $ceilingroom_pipe_anchor.time (.6);
                  
                  $ceiling_cover_anchor.rotateOnce ('120 0 0');
   
                //  bridge setup
                $bridge_toprailing_left.bind ($bridge_toprailing_left_anchor);
                $bridge_toprailing_left_anchor.bind ($bridge_floor);                 
                $bridge_toprailing_right.bind ($bridge_toprailing_right_anchor);
                $bridge_toprailing_right_anchor.bind ($bridge_floor);
                $bridge_btmrailing_left.bind ($bridge_btmrailing_left_anchor);
                $bridge_btmrailing_left_anchor.bind ($bridge_floor);                 
                $bridge_btmrailing_right.bind ($bridge_btmrailing_right_anchor);
                $bridge_btmrailing_right_anchor.bind ($bridge_floor);

                $bridge_toprailing_left_anchor.accelTime (.4);
                $bridge_toprailing_left_anchor.decelTime (.4);
                $bridge_toprailing_left_anchor.time (1);
                $bridge_toprailing_right_anchor.accelTime (.4);
                $bridge_toprailing_right_anchor.decelTime (.4);
                $bridge_toprailing_right_anchor.time (1);
                $bridge_btmrailing_left_anchor.accelTime (.4);
                $bridge_btmrailing_left_anchor.decelTime (.4);
                $bridge_btmrailing_left_anchor.time (1);
                $bridge_btmrailing_right_anchor.accelTime (.4);
                $bridge_btmrailing_right_anchor.decelTime (.4);
                $bridge_btmrailing_right_anchor.time (1);
             
                $bridge_toprailing_left_anchor.rotateOnce ('0 0 -88');
                $bridge_btmrailing_left_anchor.rotateOnce ('0 0 -45');
                $bridge_toprailing_right_anchor.rotateOnce ('0 0 88');
                $bridge_btmrailing_right_anchor.rotateOnce ('0 0 45');
                $bridge_floor.moveTo ($bridge_spot1);               

		// hall 1 emergency light
		$light_tunnel_1.bind ($tunnel_anchor_1);
		$light_tunnel_1_spin.bind ($tunnel_anchor_1);
		$tunnel_anchor_1.rotate ('0 -300 0');

		// chamber 2: spinny things
                $accelswayL.rotate ('0 -20 0');
		$accelspinL.rotate ('0 45 0');		
		$accelspinM.rotate ('0 -35 0');	
		$accelspinR.rotate ('0 50 0');
		$c2_spin_2.rotate ('0 -40 0');
		$c2_spin_3.rotate ('0 20 0');
				
		//  rod replacement setup 
                $rod_door.bind ($rod_replacer);
                $rod_door.time (1);
                $rod_door.accelTime (.3);
                $rod_door.decelTime (.5);

                $rod_fire_emitter1.bind ($rod);
                $rod_fire_emitter2.bind ($rod);     
		$rod_redlight1.bind ($rod);
                $rod_emitter3.bind ($rod);
                $rod_emitter4.bind ($rod);
                
                $rod_emitter1.bind ($rod_2);
                $rod_emitter2.bind ($rod_2);		
		$rod_2_bluelight1.bind ($rod_2);
		$rod_2_bluelight2.bind ($rod_2);
		$rod_2.hide ();

		$rod_replacer.time (1);
		$rod_replacer.decelTime (.5);
                $rod.time (.5);
		$rod.decelTime (.3);
                $rod_2.time (.5);
		$rod_2.decelTime (.3);

		//  machineroom binds
		$machineclaw1_carrier.bind ($machineclaw1_carrier_anchor);
		$machineclaw1_upperarm.bind ($machineclaw1_carrier);
		$machineclaw1_forearm.bind ($machineclaw1_upperarm);
		$machineclaw1_hand.bind ($machineclaw1_forearm);
		$machineclaw1_revolver.bind ($machineclaw1_hand);
		$machineclaw1_steam1.bind ($machineclaw1_hand);
		$machineclaw1_steam2.bind ($machineclaw1_hand);

		$reloader_light.bind ($reloader);

		$chamberpivot2.bind ($chamberpivot1);
		$filterchamber.bind ($chamberpivot1);

		$canspot1.bind ($machineclaw1_revolver);
		$canspot2.bind ($machineclaw1_revolver);
		$canspot3.bind ($machineclaw1_revolver);
		$canspot4.bind ($machineclaw1_revolver);

		$can_dirty1.bind ($filterchamber);
		$can_dirty2.bind ($filterchamber);
		$chamber_filterspot1.bind ($filterchamber);
		$chamber_filterspot2.bind ($filterchamber);

		$can_dirty4.bind ($cradle4);
		$can_dirty5.bind ($cradle5);
		$can_dirty6.bind ($cradle6);

                $cradle4_x.bind ($cradle4);
		$cradle5_x.bind ($cradle5);
		$cradle6_x.bind ($cradle6);

	//	setup mover times for machineroom
                
                
		$machineclaw1_carrier.time (2);	
		$machineclaw1_upperarm.time (1);
		$machineclaw1_forearm.time (1);
		$machineclaw1_hand.time (1);
		$machineclaw1_revolver.time (1);

		$machineclaw1_carrier.accelTime (.50);	
		$machineclaw1_upperarm.accelTime (.1);
		$machineclaw1_forearm.accelTime (.1);
		$machineclaw1_hand.accelTime (.1);
		$machineclaw1_revolver.accelTime (.1);

		$machineclaw1_carrier.decelTime (.50);	
		$machineclaw1_upperarm.decelTime (.1);
		$machineclaw1_forearm.decelTime (.1);
		$machineclaw1_hand.decelTime (.1);
		$machineclaw1_revolver.decelTime (.1);

		$reloader.time (.25);

               	//airlock door2 times
		$airlock_door2_left.time (1.2);
		$airlock_door2_right.time (1.2);
		$airlock_door2_left.accelTime (.2);
		$airlock_door2_left.decelTime (1);
		$airlock_door2_right.accelTime (.2);
		$airlock_door2_right.decelTime (1);

		$airlock_door2_top_lock.time (.25);
		$airlock_door2_bottom_lock.time (.25);
		
		$airlock_door2_left_lock.time (.75);
		$airlock_door2_right_lock.time (.75);
		$airlock_door2_left_lock.accelTime (.1);
		$airlock_door2_left_lock.decelTime (.65);
		$airlock_door2_right_lock.accelTime (.1);
		$airlock_door2_right_lock.decelTime (.65);
       

	}

        ///////////////////////////////////////////////
	//
	//  ceilingroom
	//
	//////////////////////////////////////////////

        void ceilingroom_start ()
	{         
                 sys.trigger ($explosion_1);
                $ceilingroom_pipe_anchor.rotateOnce ('-15 0 0');
                $ceilingroom_pipe_anchor.move (DOWN ,28);
                $ceilingroom_pipe_anchor.startSoundShader ("metalcrash_01", SND_CHANNEL_VOICE);
                
                  sys.waitFor ($ceilingroom_pipe_anchor);

                $ceilingroom_pipe_anchor.accelTime (.1);
                $ceilingroom_pipe_anchor.decelTime (.1);
                $ceilingroom_pipe_anchor.time (.2);
                
                $ceilingroom_pipe_anchor.move (UP ,4);
                $ceilingroom_pipe_anchor.rotateOnce ('3 0 0');

                  sys.waitFor ($ceilingroom_pipe_anchor);

                $ceilingroom_pipe_anchor.move (DOWN ,2);
                $ceilingroom_pipe_anchor.rotateOnce ('-3 0 0');
               
                $bloodsplat1.show ();
                 sys.wait (.1);
                $bloodsplat2.show ();
                 sys.wait (.1);
                $bloodsplat3.show ();
                 sys.wait (.1);
                $bloodsplat4.show ();
                 sys.wait (.05);
                $bloodsplat5.show ();
                 sys.wait (.1);
                $bloodsplat6.show ();
                 sys.wait (.05);

              $ceiling_cover_anchor.rotateOnce ('-120 0 0');
                sys.wait (.3);

                sys.trigger ($func_fracture_6);
                sys.trigger ($func_forcefield_6);
                $func_forcefield_6.startSoundShader ("glasscrash_01", SND_CHANNEL_VOICE);
                   sys.wait (.3);
                sys.trigger ($func_fracture_9);
                sys.trigger ($func_forcefield_12);
                $func_forcefield_6.startSoundShader ("glasscrash_01", SND_CHANNEL_VOICE);
                  sys.wait (.1);
                sys.trigger ($breakglass_again);           
        }


        ///////////////////////////////////////////////
	//
	//  bridge
	//
	//////////////////////////////////////////////

	void bridge_open ()
	{               
				$bridge_floor.time (2);
				
				$bridge_floor.startSoundShader ("enpro_bridge_2s", SND_CHANNEL_VOICE);
                
                $bridge_floor.moveTo ($bridge_spot2);
                 sys.waitFor ($bridge_floor);
                $bridge_toprailing_left_anchor.rotateOnce ('0 0 88');                
                $bridge_toprailing_right_anchor.startSoundShader ("enpro_bridge_rails_1s", SND_CHANNEL_VOICE);
                $bridge_toprailing_right_anchor.rotateOnce ('0 0 -88');
                 sys.waitFor ($bridge_toprailing_right_anchor);
                 
                $bridge_btmrailing_left_anchor.startSoundShader ("enpro_bridge_rails_2_1s", SND_CHANNEL_VOICE);
                $bridge_btmrailing_left_anchor.rotateOnce ('0 0 45');
                $bridge_btmrailing_right_anchor.rotateOnce ('0 0 -45');
                
        }

        ///////////////////////////////////////////////
	//
	//  zombie drop
	//
	//////////////////////////////////////////////

	void zombie_drop ()
	{        sys.trigger ($zombie_explosion_1);
                 sys.wait (.5);
                 sys.trigger ($zombie_explosion_2);
                 sys.wait (.2);
                 $zombie1.unbind ();                 
                 sys.wait (1);
               $zombie_splat.show ();                        
        }
      

	/////////////////////////////////////////////////
	//
	//  coolant rod replacement stuff
	//
	/////////////////////////////////////////////////

	void rod_replace ()
	{                              
			thread xianstuff();				// Swap out sounds during this sequence
			
			// grab red rod
            sys.wait (1);
			$rod_replacer.moveTo ($rod_replacer_spot2);
			sys.waitFor ($rod_replacer);
			sys.wait (1);
			$rod.bind ($rod_replacer);
			$rod_replacer.moveTo ($rod_replacer_spot1);
			sys.waitFor ($rod_replacer);
			$rod.unbind ();			

            $rod_door.rotateOnce ('0 180 0');
            
			sys.wait (.5);
             $rod_shimmer.hide ();
			$rod_fire_emitter1.hide ();
            $rod_fire_emitter2.hide ();
            $rod_emitter3.hide ();
            $rod_emitter4.hide ();
            sys.trigger ($cyl_smoke);

			sys.waitFor ($rod_door);
            sys.wait (1);

            $rod.moveTo ($rod_spot1);
            sys.waitFor ($rod);
	        
			// switch
			$rod.hide (); 
			$rod_2.show ();

            $rod_fire_emitter1.hide ();
            $rod_fire_emitter2.hide ();
            $rod_emitter3.hide ();
            $rod_emitter4.hide ();
            $cyl_smoke.hide ();           

			sys.trigger ($rod_redlight1);
			sys.trigger ($rod_2_bluelight1);
			sys.trigger ($rod_2_bluelight2);

			// blue rod

            $rod_2.moveTo ($rod_spot2);
            sys.waitFor ($rod_2);

			$rod_2.bind ($rod_replacer);
			$rod_replacer.moveTo ($rod_replacer_spot2);
			sys.waitFor ($rod_replacer);
            $rod_door.rotateOnce ('0 -180 0');
            sys.waitFor ($rod_door);
			$rod_2.unbind ();
			sys.wait (1);
	        
			$rod_replacer.moveTo ($rod_replacer_spot1);
			sys.waitFor ($rod_replacer);
	            
			// switch out colors by hazarddoor up on level 2

			sys.trigger ($hazard_redlight);
			sys.trigger ($hazard_bluelight);
                          
            $hazard_redemitter1.hide ();
            $hazard_redemitter2.hide ();
            $hazard_redemitter3.hide ();
            $hazard_redemitter4.hide ();

            $hazard_redtube1.hide ();
			$hazard_redtube2.hide ();

            $hazard_blueemitter1.show ();
            $hazard_blueemitter2.show ();
            $hazard_blueemitter3.show ();
            $hazard_blueemitter4.show ();

			$hazard_bluetube1.show ();
			$hazard_bluetube2.show ();

            sys.trigger ($cyl_lightrelay);
            sys.trigger ($cyltop_on);
            sys.trigger ($cyltop_off);
            sys.trigger ($cylbottom_on);
            sys.trigger ($cylbottom_off);
            sys.trigger ($func_emitter_68);
            sys.trigger ($func_emitter_69);
			
			sys.trigger ($hazdoortrigger);
            
            sys.trigger ($obj1complete);
            sys.trigger ($obj1complete_trigger);                              
	    
	}

	////////////////////////////////////////////////////
	//
	//	Rotate a cradle (machine room thing that -
	//	accepts dirty filters) around the ends
	//
	////////////////////////////////////////////////////
	void cradle_rotate( entity ent )
	{
		//whole thing (up, around, and down 
		//takes 1 second like almost all the moves
		ent.time ( .33 );
		ent.move ( UP, 16 );
		sys.waitFor (ent);
		
		ent.rotateOnce ( '0 0 180');
		sys.waitFor (ent);

		ent.move ( DOWN, 16 );
		ent.time (1);
	}


	void cache_sounds() {
		sys.cacheSoundShader ("rec1_steamchuff");
		sys.cacheSoundShader ("metalcrash_01");
		sys.cacheSoundShader ("glasscrash_01");
		sys.cacheSoundShader ("enpro_bridge_2s");
		sys.cacheSoundShader ("enpro_bridge_rails_1s");
		sys.cacheSoundShader ("enpro_bridge_rails_2_1s");
		sys.cacheSoundShader ("dc3_gui_panel_1");
		sys.cacheSoundShader ("tb_m3_loop");
		sys.cacheSoundShader ("tb_m4_stop");
		sys.cacheSoundShader ("mach_1s");
		sys.cacheSoundShader ("rotor_1s");
		sys.cacheSoundShader ("tb_m4_stop");
		sys.cacheSoundShader ("tb_arm1");
		sys.cacheSoundShader ("tb_arm2");
		sys.cacheSoundShader ("tb_arm3");
		sys.cacheSoundShader ("tb_whomp");
		sys.cacheSoundShader ("tb_whompout");
		sys.cacheSoundShader ("tb_reloader1");
		sys.cacheSoundShader ("tb_reloader2");
		sys.cacheSoundShader ("al4_welder_armrot_1s");		
	}

	////////////////////////////////////////////////////
	//
	//	Machineclaw movement
	//
	////////////////////////////////////////////////////
	void machineclaw1_move()
	{

	//	move machineclaw1 from initial position down and around track to filter pick up spot
		//1
		
		$sp_m2_carrier.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );
		
		$sp_m2_carrier.startSoundShader ("tb_m3_loop", SND_CHANNEL_VOICE );		// Start mover
		
		$machineclaw1_carrier_anchor.rotateOnce ( '0 -90 0' );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		//2
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint2 );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		//3
		
		$sp_m2_carrier.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );
		$machineclaw1_carrier_anchor.rotateOnce ( '0 -90 0' );
		sys.waitFor ($machineclaw1_carrier_anchor);

		//4
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint1 );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
	//	position machineclaw1 to receive filters
		//5
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint12 );
		
		$sp_m2_arm.startSoundShader ("mach_1s", SND_CHANNEL_VOICE2 );
		$machineclaw1_upperarm.rotateOnce ( '-30 0 35' );
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE2 );
		$machineclaw1_forearm.rotateOnce ( '80 0 0' );
		sys.waitFor ($machineclaw1_forearm);
		
		
		$sp_m2_carrier.startSoundShader ("tb_m4_stop", SND_CHANNEL_VOICE );				// Stop Mover
		
		
		//6
		
		$sp_m2_rev.startSoundShader ("tb_arm3", SND_CHANNEL_BODY );
		
		$machineclaw1_hand.rotateOnce ( '142.5 10 -90' );
		sys.waitFor ($machineclaw1_hand);
		sys.waitFor ($machineclaw1_upperarm);

		//7	
		
		$sp_m2_arm.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '-10 0 -43' );
		sys.wait (1);

	//	get 1st new filter
		
		//8
		
		$can_clean1.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		
		$can_clean1.moveTo ($canspot1);
		sys.waitFor ($can_clean1);
		$can_clean1.bind ($machineclaw1_revolver);

		//steam
		//9 
		
		$machineclaw1_steam1.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );

		//	swing machineclaw1 away from receive position
		
		//10
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '0 0 48' );
		
		$sp_m2_rev.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_forearm.rotateOnce ( '10 0 0' );
		sys.waitFor ($machineclaw1_upperarm);

	//	reload 2
		//11
		
		$sp_m2_reloader.startSoundShader ("tb_reloader1", SND_CHANNEL_VOICE );
		$reloader.move ( DOWN, 32 );
		sys.waitFor ($reloader);
		
		//12
		
		$sp_m2_reloader.startSoundShader ("tb_reloader2", SND_CHANNEL_VOICE2 );
		$reloader.move ( UP, 32 );

		$can_clean2.time (.25);
		$can_clean3.time (.25);
		
		//13
		
		$can_clean2.move ( UP, 32 );
		$can_clean3.move ( UP, 32 );
		
		//14
		$can_clean2.time (1);
		$can_clean3.time (1);

	//	swing machineclaw1 back into receive position
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '0 0 -48' );
		
		$sp_m2_rev.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_forearm.rotateOnce ( '-10 0 0' );
		sys.wait (.5);
		
	//	get 2nd new filter	
		//15
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_BODY );
		
		$machineclaw1_revolver.rotateOnce ( '0 -450 0');
		sys.waitFor ($machineclaw1_revolver);

		//steam
		//16
		
		$machineclaw1_steam2.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );

		$can_clean2.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		
		$can_clean2.moveTo ($canspot2);
		sys.waitFor ($can_clean2);
		
		$can_clean2.bind ($machineclaw1_revolver);

	//	machineclaw1 movement out of receive position

		//17
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		$machineclaw1_upperarm.rotateOnce ( '0 0 38' );
		sys.waitFor ($machineclaw1_upperarm);


		//18
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		$machineclaw1_hand.rotateOnce ( '-142.5 -10 90' );
		sys.waitFor ($machineclaw1_hand);

		//19
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		$machineclaw1_upperarm.rotateOnce ( '0 0 -20' );
		
		$sp_m2_carrier.startSoundShader ("tb_m3_loop", SND_CHANNEL_VOICE );		// Start mover
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint1 );
		sys.waitFor ($machineclaw1_upperarm);
		
		$sp_m2_carrier.startSoundShader ("tb_m4_stop", SND_CHANNEL_VOICE );				// Stop Mover
		
		//20
		
		$sp_m2_arm.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE );
		$machineclaw1_forearm.rotateOnce ( '25 0 0' );
		sys.wait (.5);
		
		//21
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		$machineclaw1_upperarm.rotateOnce ( '0 0 -10' );
		
	//	sys.waitFor ($machineclaw1_upperarm);

	//	reload 3
		$sp_m2_reloader.startSoundShader ("tb_reloader1", SND_CHANNEL_VOICE );
		$reloader.move ( DOWN, 32 );
		sys.waitFor ($reloader);
		
		//22
		$sp_m2_reloader.startSoundShader ("tb_reloader2", SND_CHANNEL_VOICE2 );
		$reloader.move ( UP, 32 );
		$can_clean3.time (.25);
		$can_clean3.move ( UP, 32 );
		$can_clean3.time (1);

	//	move machineclaw1 from filter pick up spot to filterpoint1
		//23
		
		$sp_m2_carrier.startSoundShader ("tb_m3_loop", SND_CHANNEL_VOICE );		// Start mover
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint2 );
		sys.waitFor ($machineclaw1_carrier_anchor);

		//24
		
		$machineclaw1_carrier_anchor.rotateOnce ( '0 90 0' );
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '0 -45 0' );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		//25
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_filterpoint1 );
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '-5 -45 -15' );
		
		$sp_m2_rev.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_forearm.rotateOnce ( '-15 0 0' );
		
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		$sp_m2_carrier.startSoundShader ("tb_m4_stop", SND_CHANNEL_VOICE );				// Stop Mover
		
	//	filterchamber movement up and rotate 45 degrees for filter removal
		//26
		
		$chamberpivot1.startSoundShader ("tb_arm3", SND_CHANNEL_VOICE2 );
		$chamberpivot1.move ( UP, 42 );
		sys.waitFor ($chamberpivot1);

		//26a
		
		$filterchamber.startSoundShader ("tb_arm3", SND_CHANNEL_VOICE2 );
		$filterchamber.rotateOnce ( '45 0 0');
		sys.waitFor ($filterchamber);
			
	//	exchange filter 1
		
		//27
		
		$sp_m2_arm.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '30 0 0' );
		
		$sp_m2_rev.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_forearm.rotateOnce ( '-20 0 0' );

	//	$machineclaw1_hand.rotateOnce ( '-5 0 0' );
		$machineclaw1_hand.rotateOnce ( '-12 0 0' );

		sys.waitFor ($machineclaw1_upperarm);
		
		//28
		
		$sp_m2_arm.startSoundShader ("tb_arm3", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '0 0 15' );
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		
		$machineclaw1_revolver.rotateOnce ( '0 90 0');
		
		sys.waitFor ($machineclaw1_upperarm);

		//get old filter
		//29
		
		$can_dirty1.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		$can_dirty1.moveTo ( $canspot3 );
		
		$machineclaw1_steam1.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );
		
		sys.waitFor ($can_dirty1);
		$can_dirty1.unbind ();
		$can_dirty1.bind ( $machineclaw1_revolver );

		
		sys.wait (.5);

		//30
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		$machineclaw1_revolver.rotateOnce ( '0 180 0');
		sys.waitFor ($machineclaw1_revolver);

		//steam
		sys.trigger ( $machineclaw1_steam1 );
                sys.trigger ( $machineclaw1_steam2 );
		$machineclaw1_steam2.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		
		
		//insert new filter
		//31
		
		$can_clean1.startSoundShader ("tb_whompout", SND_CHANNEL_VOICE2 );
		
		$can_clean1.moveTo ( $chamber_filterspot1 );
		sys.waitFor ($can_clean1);
		$can_clean1.unbind ();
		
		$can_clean1.bind ( $chamber_filterspot1 );
		
	//	move machineclaw1 from filterpoint1 to filterpoint2
		
		//32
		$sp_m2_carrier.startSoundShader ("tb_m3_loop", SND_CHANNEL_VOICE );		// Start mover
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_filterpoint2 );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		$sp_m2_carrier.startSoundShader ("tb_m4_stop", SND_CHANNEL_VOICE );				// Stop Mover

	//	exchange filter 2
		//33
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE2 );
		$machineclaw1_revolver.rotateOnce ( '0 -270 0');
		sys.waitFor ($machineclaw1_revolver);

		//steam
		
		//34
		
		$machineclaw1_steam1.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );

		//get old filter
		$can_ditry2.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		$can_dirty2.moveTo ( $canspot4 );
		sys.waitFor ($can_dirty2);
		$can_dirty2.unbind ();
		$can_dirty2.bind ( $machineclaw1_revolver );

		sys.wait (.5);
		
		//35
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		$machineclaw1_revolver.rotateOnce ( '0 180 0');
		sys.waitFor ($machineclaw1_revolver);

		//steam
		$machineclaw1_steam2.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );
		
		//insert new filter
		//36
		
		$can_clean2.startSoundShader ("tb_whompout", SND_CHANNEL_VOICE2 );
		
		$can_clean2.moveTo ( $chamber_filterspot2 );
		sys.waitFor ($can_clean2);
		$can_clean2.unbind ();
		$can_clean2.bind ( $chamber_filterspot2 );
		
		
		sys.wait (1);

		//	move machineclaw1 from filterpoint2 to dump spot
		//37
		
		$sp_m2_carrier.startSoundShader ("tb_m3_loop", SND_CHANNEL_VOICE );		// Start mover
		
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint3 );
		
		$sp_m2_arm.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE );
		
		$machineclaw1_forearm.rotateOnce ( '40 0 0' );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		//38
		
		$machineclaw1_carrier_anchor.rotateOnce ( '0 90 0' );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		//39
		
		$machineclaw1_carrier.rotateOnce ( '0 -90 0' );
		$machineclaw1_carrier_anchor.moveTo ( $machineclaw1_movepoint4 );
		
		$sp_m2_rev.startSoundShader ("tb_arm1", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_forearm.rotateOnce ( '-17 0 0' );
		
		$sp_m2_arm.startSoundShader ("tb_arm2", SND_CHANNEL_VOICE2 );
		
		$machineclaw1_upperarm.rotateOnce ( '-15 0 -18' );
		sys.waitFor ($machineclaw1_carrier_anchor);
		
		$sp_m2_carrier.startSoundShader ("tb_m4_stop", SND_CHANNEL_VOICE );				// Stop Mover

		//40
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		
		$machineclaw1_hand.rotateOnce ( '39 16 0' );
		sys.waitFor ($machineclaw1_hand);

		//	dump old filters
		//move cradles up,down and around
		
		//41
		
		$cradle4.startSoundShader ("al4_welder_armrot_1s", SND_CHANNEL_VOICE );
		
		$cradle4.rotateOnce ( '0 0 180' );
		$cradle5.move ( DOWN, 32 );
		$cradle6.move ( DOWN, 32 );
		thread cradle_rotate ( $cradle1 );
		$cradle2.move ( UP, 32 );
		$cradle3.move ( UP, 32 );
		sys.waitFor ($cradle2);
		sys.killthread ( "map_enpro::cradle_rotate" );
		
		$can_dirty4.unbind ();
		$can_dirty4.remove ();

		//put dirty1 on cradle1
		//42
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		$machineclaw1_revolver.rotateOnce ( '0 -90 0' );
		sys.waitFor ($machineclaw1_revolver);

		//steam
		//42a
		
		$machineclaw1_steam1.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );
		
		$can_dirty1.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		$can_dirty1.moveTo ( $cradlespot );
		
		sys.waitFor ($can_dirty1);
		$can_dirty1.unbind ();
		$can_dirty1.bind ( $cradle1 );

		
		//move cradles around again
		//43
		
		$cradle5.startSoundShader ("al4_welder_armrot_1s", SND_CHANNEL_VOICE );
		
		$cradle5.rotateOnce ( '0 0 180' );
		$cradle6.move ( DOWN, 32 );
		$cradle1.move ( DOWN, 32 );
		thread cradle_rotate ( $cradle2 );
		$cradle3.move ( UP, 32 );
		$cradle4.move ( UP, 32 );
		sys.waitFor ($cradle3);
		sys.killthread ( "map_enpro::cradle_rotate" );

		$can_dirty5.unbind ();
		$can_dirty5.remove ();

		//put dirty2 on cradle2
		//44
		
		$sp_m2_rev.startSoundShader ("rotor_1s", SND_CHANNEL_VOICE );
		$machineclaw1_revolver.rotateOnce ( '0 630 0' );
		sys.waitFor ($machineclaw1_revolver);
			
		//steam
		//44a
		
		$machineclaw1_steam2.startSoundShader ("rec1_steamchuff", SND_CHANNEL_VOICE2 );
		sys.trigger ( $machineclaw1_steam1 );
		sys.trigger ( $machineclaw1_steam2 );
		
		$can_dirty.startSoundShader ("tb_whomp", SND_CHANNEL_VOICE );
		$can_dirty2.moveTo ( $cradlespot );
		
		sys.waitFor ($can_dirty2);
		$can_dirty2.unbind ();
		$can_dirty2.bind ( $cradle2 );

		//move cradles around again - last time
		
		//45
		
		$cradle6.startSoundShader ("al4_welder_armrot_1s", SND_CHANNEL_VOICE );
		
		$cradle6.rotateOnce ( '0 0 180' );
		$cradle1.move ( DOWN, 32 );
		$cradle2.move ( DOWN, 32 );
		thread cradle_rotate ( $cradle3 );
		$cradle4.move ( UP, 32 );
		$cradle5.move ( UP, 32 );
		sys.waitFor ($cradle4);
		sys.killthread ( "map_enpro::cradle_rotate" );

		$can_dirty6.unbind ();
		$can_dirty6.remove ();
		

	//	filterchamber rotate 45 degrees and  movement down back to original position
		//46
		
		$filterchamber.startSoundShader ("tb_arm3", SND_CHANNEL_VOICE );
		
		$filterchamber.rotateOnce ( '-45 0 0');
		sys.waitFor ($filterchamber);

		//47
		
		$chamberpivot1.startSoundShader ("tb_arm3", SND_CHANNEL_VOICE );
		
		$chamberpivot1.move ( DOWN, 42 );
		sys.waitFor ($chamberpivot1);
                
        sys.trigger ($tube_particle_3);
        sys.trigger ($tube_particle_4);
        sys.trigger ($tube_particle_5);
        sys.trigger ($tube_particle_6);
        sys.trigger ($plasmacontrol_light2);
        sys.trigger ($plasmacontrol_light3);
	}

/////////////////////////////////////
/////////// exit airlock door
/////////////////////////////////////

        void exit_open()

        {       //disable the gui on door2		
		$airlock_door2_gui.setGuiParm ( "gui_parm1" , 0);

		//move the 4 locks to unlock position
		$airlock_door2_top_lock.move ( UP, 15 );
		
		sys.trigger ($speaker_airlock_door2_bottom_lock);				// sound
		
		$airlock_door2_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock_door2_bottom_lock);

		sys.trigger ($speaker_airlock_door2_left_lock);
		$airlock_door2_left_lock.move ( NORTH, 16 );
		sys.trigger ($speaker_airlock_door2_right_lock);
		$airlock_door2_right_lock.move ( NORTH, 16 );
		sys.waitFor ($airlock_door2_right_lock);

		//open doors
		sys.trigger ($speaker_airlock_door2_open);
		
		$airlock_door2_left.rotateOnce ( '0 45 0' );
		$airlock_door2_right.rotateOnce ( '0 -45 0' );

		sys.waitFor ($airlock_door2_right);
		sys.waitFor ($airlock_door2_left);		
        }
                
	void main()
	{
		cache_sounds();
		setup_objects();
		

	}
}

//@doomscript-blueprint begin 6
//@source 5E733064
//@catalog 0C260740
//@node 43AF560D-0 40 40
//@node F38FE373-0 330 40
//@node 5FB4E926-0 610 40
//@node 168F933F-0 890 40
//@node FC92D6D5-0 1170 40
//@node DADB7157-0 1450 40
//@node 45DE462A-0 1730 40
//@node 11B06706-0 2010 40
//@node 7AEA71C1-0 40 40
//@node 48FECDF4-0 330 40
//@node F2116124-0 610 40
//@node 9349D630-0 890 40
//@node D0719A58-0 1170 40
//@node D981D1FE-0 1450 40
//@node D8C3F5A9-0 1730 40
//@node D1F1FADD-0 2010 40
//@node 77573C58-0 2290 40
//@node DD338D69-0 2570 40
//@node F01EA9E6-0 2850 40
//@node 7C290D32-0 3130 40
//@node C54D0060-0 3410 40
//@node F2961D2B-0 3690 40
//@node 96B15466-0 3970 40
//@node 4A9637B4-0 4250 40
//@node 5F4F292F-0 4530 40
//@node 94AA2DFE-0 4810 40
//@node 7638F8D0-0 5090 40
//@node C4D61940-0 5370 40
//@node 7237C739-0 5650 40
//@node A2558743-0 5930 40
//@node EB7F2425-0 6210 40
//@node C4DF74B8-0 6490 40
//@node 6EFF2522-0 6770 40
//@node 186874EE-0 7050 40
//@node 00463B4B-0 7330 40
//@node 6882AB95-0 7610 40
//@node 9BADB7B7-0 7890 40
//@node 8408C19C-0 8170 40
//@node F39A4355-0 8450 40
//@node 4AFCA5DE-0 8730 40
//@node 42F7FAE4-0 9010 40
//@node 023DEE2F-0 9290 40
//@node A827008C-0 9570 40
//@node 7A44AC12-0 9850 40
//@node 0DEA8973-0 10130 40
//@node 7CDE5E8B-0 10410 40
//@node A00A4C6E-0 10690 40
//@node 53FF9FE3-0 10970 40
//@node DA474BCC-0 11250 40
//@node 44AB4992-0 11530 40
//@node 0A3D2832-0 11810 40
//@node 9E5D1A23-0 12090 40
//@node 8A3CC83D-0 12370 40
//@node C3FCDCBA-0 12650 40
//@node 5D376B41-0 12930 40
//@node 523FBADE-0 13210 40
//@node 4CCAEF41-0 13490 40
//@node F98D0CBA-0 13770 40
//@node E13C9859-0 14050 40
//@node F20711AD-0 14330 40
//@node EA21742E-0 14610 40
//@node 9EB3E8F2-0 14890 40
//@node 089B5971-0 15170 40
//@node 9701A681-0 15450 40
//@node BED1FCF5-0 15730 40
//@node 12AE453C-0 16010 40
//@node BB5F4772-0 16290 40
//@node D79965F5-0 16570 40
//@node C931C535-0 16850 40
//@node F9BD9868-0 17130 40
//@node C6EC06AC-0 17410 40
//@node 4DEB411C-0 17690 40
//@node 072F5536-0 17970 40
//@node 4B1501B3-0 18250 40
//@node 18C87262-0 18530 40
//@node C107F5AA-0 18810 40
//@node 26F3929D-0 19090 40
//@node 81CAA92F-0 19370 40
//@node 37EC90D7-0 19650 40
//@node B8DE7FD3-0 19930 40
//@node 4175E37E-0 20210 40
//@node 882E48DD-0 20490 40
//@node 7654D8DC-0 20770 40
//@node 36C3EF6B-0 21050 40
//@node A46AC640-0 21330 40
//@node 9A3FD8C3-0 21610 40
//@node 7CC2F39E-0 21890 40
//@node E902908D-0 22170 40
//@node 66D4E164-0 22450 40
//@node E40EAE4A-0 22730 40
//@node AE94F5FC-0 23010 40
//@node 8925B255-0 23290 40
//@node C3CD7247-0 23570 40
//@node 92840BB5-0 23850 40
//@node CC2009E2-0 24130 40
//@node 76B51683-0 24410 40
//@node F00E3187-0 24690 40
//@node 74240430-0 24970 40
//@node F980464E-0 25250 40
//@node 4B0A14C5-0 25530 40
//@node 86D9122B-0 25810 40
//@node B0FB5097-0 26090 40
//@node A378F0AC-0 26370 40
//@node 09DAD48E-0 26650 40
//@node 5D32703A-0 26930 40
//@node A5EAFC16-0 27210 40
//@node A9A51672-0 27490 40
//@node FC05ECE1-0 27770 40
//@node A39E1557-0 28050 40
//@node CC1526C3-0 28330 40
//@node 74931A67-0 28610 40
//@node AC128C44-0 28890 40
//@node 64E0F06E-0 29170 40
//@node DD3D8C7A-0 29450 40
//@node 660E9489-0 29730 40
//@node 8F973433-0 30010 40
//@node C9D8B1B9-0 30290 40
//@node 21D7F2B1-0 30570 40
//@node 8CEFA45A-0 30850 40
//@node D765342B-0 31130 40
//@node 8BD666D7-0 31410 40
//@node 71705B0A-0 31690 40
//@node D434DB0A-0 31970 40
//@node 92A59D59-0 32250 40
//@node 17CD22A0-0 40 40
//@node 9AA16FF6-0 330 40
//@node 1702E3D2-0 610 40
//@node 1E69718A-0 890 40
//@node 1A993BD5-0 1170 40
//@node 68F8109E-0 1450 40
//@node 62EAC663-0 1730 40
//@node 538C8BAE-0 2010 40
//@node CD90DB94-0 2290 40
//@node A081B85F-0 2570 40
//@node B6D87D06-0 2850 40
//@node 68F8109E-1 3130 40
//@node 14431ECE-0 3410 40
//@node B059C019-0 3690 40
//@node 2F05F054-0 3970 40
//@node C7F770A3-0 4250 40
//@node 29F6AB0B-0 4530 40
//@node C7F770A3-1 4810 40
//@node C5F887DE-0 5090 40
//@node C7F770A3-2 5370 40
//@node 79E975A5-0 5650 40
//@node D9F9ED0F-0 5930 40
//@node 87696F80-0 6210 40
//@node C7F770A3-3 6490 40
//@node 148121E7-0 6770 40
//@node D9F9ED0F-1 7050 40
//@node 8AD28DD3-0 7330 40
//@node 2A3B6C75-0 7610 40
//@node 3920EB25-0 7890 40
//@node 8C1509B2-0 8170 40
//@node 6632CB7E-0 8450 40
//@node 2A3B6C75-1 8730 40
//@node 4FC92E10-0 9010 40
//@node 06EB4353-0 9290 40
//@node 6632CB7E-1 9570 40
//@node C7F770A3-4 9850 40
//@node B24D441D-0 10130 40
//@node D678ACE9-0 40 40
//@node D33B43F8-0 330 40
//@node EBAD1C7B-0 610 40
//@node BE499A21-0 890 40
//@node 6673C744-0 1170 40
//@node 7CB9653C-0 1450 40
//@node F3F0FDF4-0 1730 40
//@node AED8A2CC-0 2010 40
//@node 1ECED1FA-0 2290 40
//@node B9E22A6C-0 2570 40
//@node B5893B5F-0 2850 40
//@node 14EFDB5B-0 3130 40
//@node 3E3D6835-0 40 40
//@node 3AD4E9D8-0 330 40
//@node 0DD3BD6F-0 610 40
//@node BD1EFEB5-0 890 40
//@node 6FA309CE-0 1170 40
//@node 46B1F930-0 1450 40
//@node B28B48AD-0 1730 40
//@node 43109045-0 40 40
//@node 5156B709-0 330 40
//@node 8F06302C-0 610 40
//@node BD23AE00-0 890 40
//@node 4B3BB524-0 1170 40
//@node 8F06302C-1 1450 40
//@node 21FC5767-0 1730 40
//@node 03AB8181-0 2010 40
//@node 4B3BB524-1 2290 40
//@node AA7A2482-0 2570 40
//@node 574BEFE8-0 2850 40
//@node 86B8E59C-0 3130 40
//@node 0996CE96-0 3410 40
//@node 362EC8CF-0 3690 40
//@node 8A5F5A7C-0 3970 40
//@node DE316780-0 4250 40
//@node CDB282DF-0 4530 40
//@node 8B0655FA-0 4810 40
//@node D271E78A-0 5090 40
//@node 8F06302C-2 5370 40
//@node 46ABE77F-0 5650 40
//@node 408881A1-0 5930 40
//@node A451AC2A-0 6210 40
//@node 535A622C-0 6490 40
//@node 362EC8CF-1 6770 40
//@node 8A5F5A7C-1 7050 40
//@node DE316780-1 7330 40
//@node CDB282DF-1 7610 40
//@node 1E73BA5B-0 7890 40
//@node BC75ACB2-0 8170 40
//@node C5028C5E-0 8450 40
//@node 588DD4CB-0 8730 40
//@node 472B391D-0 9010 40
//@node F6F99180-0 9290 40
//@node 7DEEA50A-0 9570 40
//@node BD23AE00-1 9850 40
//@node 4B3BB524-2 10130 40
//@node B9012BD7-0 10410 40
//@node D271E78A-1 10690 40
//@node C6841749-0 10970 40
//@node 8F06302C-3 11250 40
//@node 03AB8181-1 11530 40
//@node 4B3BB524-3 11810 40
//@node BAF787FC-0 12090 40
//@node 8B7706DF-0 12370 40
//@node 073A9A44-0 12650 40
//@node C95C2457-0 12930 40
//@node 46D40702-0 13210 40
//@node 230844CD-0 13490 40
//@node B8E9C862-0 13770 40
//@node 6A136039-0 14050 40
//@node AF87E374-0 14330 40
//@node 83197B2B-0 14610 40
//@node EACFD87E-0 14890 40
//@node A3DE2A45-0 15170 40
//@node 5EE5CC60-0 15450 40
//@node 4A74D047-0 15730 40
//@node 2AF4E594-0 16010 40
//@node 8972E99D-0 16290 40
//@node 088DFDA9-0 16570 40
//@node 160C34A5-0 16850 40
//@node 2DEE8871-0 17130 40
//@node 49DC6D4A-0 17410 40
//@node 2F8488E9-0 17690 40
//@node 8C8040A9-0 17970 40
//@node 03CAB8D3-0 18250 40
//@node A107E7B4-0 18530 40
//@node 8550C944-0 40 40
//@node DC77897A-0 330 40
//@node C07AFA38-0 610 40
//@node 715A2516-0 890 40
//@node 92E1AABC-0 1170 40
//@node 715A2516-1 1450 40
//@node 16613787-0 1730 40
//@node C584D0F5-0 2010 40
//@node B832CE32-0 40 40
//@node D96BA8A7-0 330 40
//@node 22275DC3-0 610 40
//@node C72A982E-0 890 40
//@node 4E44C09B-0 1170 40
//@node 050D0AD4-0 1450 40
//@node AF980A2D-0 1730 40
//@node 564BBF46-0 2010 40
//@node 03B0709B-0 2290 40
//@node 1697F5E8-0 2570 40
//@node 6A2FAFA1-0 2850 40
//@node 6CFD337A-0 3130 40
//@node 1697F5E8-1 3410 40
//@node 7922A2A1-0 3690 40
//@node D2A2D71A-0 3970 40
//@node 137ABE07-0 4250 40
//@node FCAC0EA5-0 4530 40
//@node 7E4C707B-0 4810 40
//@node C8A8242D-0 5090 40
//@node 92006686-0 5370 40
//@node 18637399-0 5650 40
//@node 8AB29510-0 40 40
//@node 58EF10BD-0 330 40
//@node 8FCDDA26-0 610 40
//@node AEB6185E-0 890 40
//@node 31107CAF-0 1170 40
//@node 785BC84B-0 1450 40
//@node 31107CAF-1 1730 40
//@node 58EF10BD-1 2010 40
//@node AEB6185E-1 2290 40
//@node 31107CAF-2 2570 40
//@node 5203D5B4-0 2850 40
//@node 31107CAF-3 3130 40
//@node 283C6DAA-0 3410 40
//@node 99D58F7E-0 3690 40
//@node 14C2AD34-0 3970 40
//@node CC001FB6-0 4250 40
//@node 79D53862-0 4530 40
//@node 3E562A51-0 4810 40
//@node 7FC86F45-0 5090 40
//@node 86208095-0 5370 40
//@node B1B13E92-0 5650 40
//@node 68858CF6-0 5930 40
//@node B70B7D9D-0 6210 40
//@node 5F3D4707-0 6490 40
//@node 29FBC52E-0 6770 40
//@node F3D43FB1-0 7050 40
//@node 7E5FFB0D-0 7330 40
//@node 1DA887A2-0 7610 40
//@node B8F3F07C-0 7890 40
//@node 8C6CDFFF-0 8170 40
//@node 21C8D059-0 8450 40
//@node 69C67FFE-0 8730 40
//@node AF6E0D71-0 9010 40
//@node A4DDC4FA-0 9290 40
//@node 2159A67C-0 9570 40
//@node AC5F4B96-0 9850 40
//@node 06E30CBB-0 10130 40
//@node B70B7D9D-1 10410 40
//@node 3BD99262-0 10690 40
//@node 20424D30-0 10970 40
//@node 3DBFD9A1-0 11250 40
//@node EEADC899-0 11530 40
//@node 3BC9FAF7-0 11810 40
//@node DEB0721E-0 12090 40
//@node 670C582D-0 12370 40
//@node 472F186F-0 12650 40
//@node C98188C2-0 12930 40
//@node 65C13C86-0 13210 40
//@node 6EF0A971-0 13490 40
//@node A4DDC4FA-1 13770 40
//@node 6F51FA3D-0 14050 40
//@node AC5F4B96-1 14330 40
//@node 570B46E6-0 14610 40
//@node 1CE092EF-0 14890 40
//@node 58DFABAA-0 15170 40
//@node 78A88781-0 15450 40
//@node BD1BDB08-0 15730 40
//@node 02980832-0 16010 40
//@node 69C67FFE-1 16290 40
//@node AF6E0D71-1 16570 40
//@node 4B95A6D2-0 16850 40
//@node 6DAC097E-0 17130 40
//@node 7FCAAC5D-0 17410 40
//@node FB0A744C-0 17690 40
//@node A4DDC4FA-2 17970 40
//@node 18DAABD7-0 18250 40
//@node B70B7D9D-2 18530 40
//@node 6F555FB8-0 18810 40
//@node 81A7D11D-0 19090 40
//@node 68858CF6-1 19370 40
//@node A4DDC4FA-3 19650 40
//@node 24B747B7-0 19930 40
//@node 8FCDDA26-1 20210 40
//@node 5203D5B4-1 20490 40
//@node B70B7D9D-3 20770 40
//@node 7FC86F45-1 21050 40
//@node 9975B4CF-0 21330 40
//@node 4ACA19C7-0 21610 40
//@node 1CE092EF-1 21890 40
//@node A4DDC4FA-4 22170 40
//@node ADC49D88-0 22450 40
//@node 3BD99262-1 22730 40
//@node 20424D30-1 23010 40
//@node 3DBFD9A1-1 23290 40
//@node EEADC899-1 23570 40
//@node 3BC9FAF7-1 23850 40
//@node 670C582D-1 24130 40
//@node C98188C2-1 24410 40
//@node 6EF0A971-1 24690 40
//@node 8FCDDA26-2 24970 40
//@node 785BC84B-1 25250 40
//@node 31107CAF-4 25530 40
//@node 692B1F3B-0 25810 40
//@node A4DDC4FA-5 26090 40
//@node 6F48138A-0 26370 40
//@node 31107CAF-5 26650 40
//@node D599D021-0 26930 40
//@node A4DDC4FA-6 27210 40
//@node C715B79B-0 27490 40
//@node AC5F4B96-2 27770 40
//@node D2AAA289-0 28050 40
//@node 31107CAF-6 28330 40
//@node 7FC86F45-2 28610 40
//@node 6D48A205-0 28890 40
//@node B77AFF73-0 29170 40
//@node 35A35898-0 29450 40
//@node BF611E76-0 29730 40
//@node 169B92AD-0 30010 40
//@node 98A7859D-0 30290 40
//@node A4DDC4FA-7 30570 40
//@node A872814F-0 30850 40
//@node AC5F4B96-3 31130 40
//@node 811E3FD1-0 31410 40
//@node DE178665-0 31690 40
//@node B70B7D9D-4 31970 40
//@node D58E3734-0 32250 40
//@node F16ACFA6-0 32530 40
//@node 6F555FB8-1 32810 40
//@node DB750C9E-0 33090 40
//@node B70B7D9D-5 33370 40
//@node A19E37EC-0 33650 40
//@node EE095731-0 33930 40
//@node 21C8D059-1 34210 40
//@node 69C67FFE-2 34490 40
//@node AF6E0D71-2 34770 40
//@node 8406682B-0 35050 40
//@node FC37F5EC-0 35330 40
//@node B32082BC-0 35610 40
//@node 1CE092EF-2 35890 40
//@node 6F555FB8-2 36170 40
//@node E5E6580C-0 36450 40
//@node BD1BDB08-1 36730 40
//@node 69C67FFE-3 37010 40
//@node AF6E0D71-3 37290 40
//@node 02980832-1 37570 40
//@node 9685EB9B-0 37850 40
//@node 77A72555-0 38130 40
//@node B8F3F07C-1 38410 40
//@node 0FA3755D-0 38690 40
//@node 21E95642-0 38970 40
//@node 8FCDDA26-3 39250 40
//@node CA3DAFAE-0 39530 40
//@node 31107CAF-7 39810 40
//@node 7FC86F45-3 40090 40
//@node CC001FB6-1 40370 40
//@node 3A526D3D-0 40650 40
//@node BD1BDB08-2 40930 40
//@node 21C8D059-2 41210 40
//@node 69C67FFE-4 41490 40
//@node AF6E0D71-4 41770 40
//@node 971EF8CF-0 42050 40
//@node A0E3AA1B-0 42330 40
//@node F1B8543E-0 42610 40
//@node D7518D9B-0 42890 40
//@node 887B335F-0 43170 40
//@node 1CE092EF-3 43450 40
//@node 6F555FB8-3 43730 40
//@node E5E6580C-1 44010 40
//@node BD1BDB08-3 44290 40
//@node 02980832-2 44570 40
//@node 69C67FFE-5 44850 40
//@node AF6E0D71-5 45130 40
//@node 82037044-0 45410 40
//@node DCEDBC19-0 45690 40
//@node 7FCAAC5D-1 45970 40
//@node D3963B32-0 46250 40
//@node 447B3F8E-0 46530 40
//@node F3D43FB1-1 46810 40
//@node 8FCDDA26-4 47090 40
//@node 45BD7452-0 47370 40
//@node 9975B4CF-1 47650 40
//@node 64A4C0A6-0 47930 40
//@node 31107CAF-8 48210 40
//@node 692B1F3B-1 48490 40
//@node 31107CAF-9 48770 40
//@node 95D6B6AA-0 49050 40
//@node 54FF26F1-0 49330 40
//@node 38061713-0 49610 40
//@node B60E5783-0 49890 40
//@node 5F3D4707-1 50170 40
//@node 5792B119-0 50450 40
//@node 31107CAF-10 50730 40
//@node 7FC86F45-4 51010 40
//@node 6F555FB8-4 51290 40
//@node E4A26C86-0 51570 40
//@node 68858CF6-2 51850 40
//@node E5130603-0 52130 40
//@node 6656ADA8-0 52410 40
//@node 6DB2E820-0 52690 40
//@node D0C3A6FF-0 52970 40
//@node 89743707-0 53250 40
//@node 094E4330-0 53530 40
//@node A07A80E5-0 53810 40
//@node 506EF7BE-0 54090 40
//@node EA818291-0 54370 40
//@node 16E7225D-0 54650 40
//@node 9A90E859-0 54930 40
//@node 6F555FB8-5 55210 40
//@node EE840B31-0 55490 40
//@node BD1BDB08-4 55770 40
//@node 21C8D059-3 56050 40
//@node 69C67FFE-6 56330 40
//@node AF6E0D71-6 56610 40
//@node A19E37EC-1 56890 40
//@node BEEE583D-0 57170 40
//@node 8406682B-1 57450 40
//@node FC37F5EC-1 57730 40
//@node A6CE0781-0 58010 40
//@node 573525F6-0 58290 40
//@node F2B5E243-0 58570 40
//@node D0C3A6FF-1 58850 40
//@node 0CF0ED4C-0 59130 40
//@node D31B61C0-0 59410 40
//@node A07A80E5-1 59690 40
//@node 3B9C947A-0 59970 40
//@node 4550B95D-0 60250 40
//@node EA818291-1 60530 40
//@node 7E11F7C8-0 60810 40
//@node 173D22EC-0 61090 40
//@node 6F555FB8-6 61370 40
//@node 6242B98A-0 61650 40
//@node BD1BDB08-5 61930 40
//@node 02980832-3 62210 40
//@node 69C67FFE-7 62490 40
//@node AF6E0D71-7 62770 40
//@node C7A10223-0 63050 40
//@node AF311C24-0 63330 40
//@node F1B8543E-1 63610 40
//@node D7518D9B-1 63890 40
//@node 60EA7A99-0 64170 40
//@node 9F48E375-0 64450 40
//@node 7FC67ECA-0 64730 40
//@node 0CF0ED4C-1 65010 40
//@node 84F1C05B-0 65290 40
//@node 52CFBB11-0 65570 40
//@node 3B9C947A-1 65850 40
//@node 0EB41747-0 66130 40
//@node C306A480-0 66410 40
//@node EA818291-2 66690 40
//@node 53F3C787-0 66970 40
//@node EBF0B92B-0 67250 40
//@node 8BBA9DF8-0 67530 40
//@node 7A1F0F6A-0 67810 40
//@node 98A7859D-1 68090 40
//@node 3783956D-0 68370 40
//@node 2BA5BFE4-0 68650 40
//@node 35A35898-1 68930 40
//@node 7B94DD12-0 69210 40
//@node 3ABB3E3B-0 69490 40
//@node D5D8CC4C-0 69770 40
//@node 1CB051AD-0 70050 40
//@node 3317E1A9-0 70330 40
//@node 4D6FC60A-0 70610 40
//@node D2D4BA26-0 40 40
//@node B84E41B2-0 330 40
//@node 2B1E6E12-0 610 40
//@node 40D2F4CF-0 890 40
//@node F24CAB57-0 1170 40
//@node 94100875-0 1450 40
//@node 9CF8E175-0 1730 40
//@node 85CFD7C1-0 2010 40
//@node 25538758-0 2290 40
//@node A30263CA-0 2570 40
//@node E566B39E-0 2850 40
//@node FE5094D0-0 3130 40
//@node 5A14ABCB-0 3410 40
//@node F2B65DBF-0 3690 40
//@node 5AB6ABA8-0 3970 40
//@node C79E31C3-0 4250 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 67C3ED48-0 610 40
//@doomscript-blueprint end
