namespace map_hell1 {

	float cage_instance = 0;

	void setup_objects ()
	{ 
               $brickdoor1.accelTime (.2);
               $brickdoor1.decelTime (.3);
               $brickdoor1.time (1);

               $alcove1_leftwall.accelTime (.5);
               $alcove1_leftwall.decelTime (.5);
               $alcove1_leftwall.time (4);
               $alcove1_rightwall.accelTime (.5);
               $alcove1_rightwall.decelTime (.5);
               $alcove1_rightwall.time (4);
               $alcove1_backwall.accelTime (.5);
               $alcove1_backwall.decelTime (.5);
               $alcove1_backwall.time (4);

               $alcove2_leftwall.accelTime (.5);
               $alcove2_leftwall.decelTime (.5);
               $alcove2_leftwall.time (4);
               $alcove2_rightwall.accelTime (.5);
               $alcove2_rightwall.decelTime (.5);
               $alcove2_rightwall.time (4);
               $alcove2_backwall.accelTime (.5);
               $alcove2_backwall.decelTime (.5);
               $alcove2_backwall.time (4);

               $brick1.time (1.5);
               $brick2.time (1);
               $brick3.time (1.2);
               $brick4.time (1);
               $brick5.time (1.5);
               $brick6.time (1.3);
               $brick7.time (1.4);
               $brick8.time (1);
               $brick9.time (1.5);
               $brick10.time (1);
               $brick11.time (1.5);
               $bricksleft_anchor.time (1.3);
               $bricksright_anchor.time (1.3);

               $bricksleft.bind ($bricksleft_anchor);
               $bricksright.bind ($bricksright_anchor);               

               $rock1.bind ($rock_rotating1);
               $rock2.bind ($rock_rotating2);
               $rock3.bind ($rock_rotating3);
               $rock4.bind ($rock_rotating4);
               $rock5.bind ($rock_rotating5);
               $rock6.bind ($rock_rotating6);
               $rock7.bind ($rock_rotating7);
               $rock8.bind ($rock_rotating8);
               $rock9.bind ($rock_rotating9);
               $rock10.bind ($rock_rotating10);
               $rock11.bind ($rock_rotating11);
               $rock12.bind ($rock_rotating12);
               
               $cageside1.bind ($cageside1_rotate); 
               $cageside2.bind ($cageside2_rotate);
               $cageside3.bind ($cageside3_rotate);
               $cageside4.bind ($cageside4_rotate);
               $cagebottom.bind ($cagebottom_rotate);

               $cage2side1.bind ($cage2side1_anchor);
               $cage2side2.bind ($cage2side2_anchor);
               $cage2side3.bind ($cage2side3_anchor);
               $cage2side4.bind ($cage2side4_anchor);

               $cageroom_mover.accelTime (.5);
               $cageroom_mover.decelTime (.5);
               $cageroom_mover.time (9);
               
               $wall1.bind ($wall1_anchor);
               $wall2.bind ($wall2_anchor);
               
               $step1.time (.5);
               $step2.time (.5);
               $step3.time (.5);
               $step4.time (.5);
               $step5.time (.5);
               $step6.time (.5);

               $doorblock1.time (.4);
               $doorblock1.decelTime (.1);			
	             	        
	}

    void telering_move ()
	{
		while (1)
		{ 
			$telering_anchor.accelTime (.4);
			$telering_anchor.decelTime (.4);
			$telering_anchor.time (1);
			$telering_anchor.rotateOnce ('-10 15 5');
			sys.waitFor ($telering_anchor);
			$telering_anchor.rotateOnce ('10 -15 -5');
			sys.waitFor ($telering_anchor);
	        
			$telering_anchor.accelTime (.5);
			$telering_anchor.decelTime (.5);
			$telering_anchor.time (2);
			$telering_anchor.rotateOnce ('20 10 0');
			sys.waitFor ($telering_anchor);
			$telering_anchor.rotateOnce ('-20 -10 0');                  
			sys.waitFor ($telering_anchor);
	        
			sys.wait (1);                   
        }
    }

    void telering_bob ()
	{
		while (1)
		{ 
            $telering_bobbing.accelTime (.5);
            $telering_bobbing.decelTime (.5);
            $telering_bobbing.time (4);
            $telering_bobbing.move (UP,32);
            sys.waitFor ($telering_bobbing);
            $telering_bobbing.move (DOWN,32);
            sys.waitFor ($telering_bobbing);
            sys.trigger ($telering_spark);
            
            $telering_spark.startSoundShader ("tp_electro", SND_CHANNEL_VOICE2 );
            
            sys.trigger ($telering_light1);
            sys.trigger ($telering_light2);
            sys.wait (1);
            sys.trigger ($telering_spark);
            sys.trigger ($telering_light1);
            sys.trigger ($telering_light2);                                 
        }
    }

    void cage_mover (entity ent, vector vec, float ftime, entity etarget) {
		cage_instance++;
		ent.time (ftime);
		ent.rotateOnce (vec);
		ent.moveTo (etarget);
		sys.waitFor (ent);
		
		if (cage_instance == 1 )
			ent.startSoundShader ("gateimpact_01", SND_CHANNEL_VOICE2 );
		if (cage_instance == 2 )
			ent.startSoundShader ("gateimpact_02", SND_CHANNEL_VOICE2 );		
		if (cage_instance == 3 )
			ent.startSoundShader ("gateimpact_03", SND_CHANNEL_VOICE2 );
		if (cage_instance == 4 )
			ent.startSoundShader ("gateimpact_04", SND_CHANNEL_VOICE2 );
		if (cage_instance == 5 )
			ent.startSoundShader ("gateimpact_05", SND_CHANNEL_VOICE2 );
    }


        //////////////////////////
	// fly hazmat
	//////////////////////////
    
    void StartSplineMover() {
		$hazmat_mover.time( 10 );
		$hazmat_mover.accelTime( 2 );
		
		sys.trigger ($speaker_corpsemover);			// On
		
		$hazmat_mover.startSpline( $func_splinemover_1 );
		$hazmat_mover.removeInitialSplineAngles();
		
		sys.waitFor ($hazmat_mover);
		
		sys.trigger ($speaker_corpsemover);			// Off
		
		sys.trigger ($hazmat_remove);
		sys.trigger ($hazmat_splash);
		sys.wait (2);
		sys.trigger ($hazmat_splash);
	}

    
         //////////////////////////
	// cage
	//////////////////////////

    //trap player in cage

	void cage_close () 
	{      
            $cageroom_mover.move (UP ,300);               


            $cageside1_rotate.time (4);
            $cageside2_rotate.time (4);
            $cageside3_rotate.time (4);
            $cageside4_rotate.time (4);
            $cagebottom_rotate.time (4);

            $cageside1_rotate.rotateOnce ('0 360 0');
            $cageside2_rotate.rotateOnce ('0 360 0');
            $cageside3_rotate.rotateOnce ('0 360 0');
            $cageside4_rotate.rotateOnce ('0 360 0');
            $cagebottom_rotate.rotateOnce ('360 720 360');


            sys.waitFor ($cageside1_rotate);

            $cageside1.unbind (); 
            $cageside2.unbind ();
            $cageside3.unbind ();
            $cageside4.unbind ();
            $cagebottom.unbind ();

            sys.waitFor ($cageside1);


			thread cage_mover ($cageside1, '0 -360 0', 3, $cageside1_spot1);
			sys.wait (1);
			thread cage_mover ($cageside2, '0 -360 0', 3, $cageside1_spot1);
			sys.wait (1);
			thread cage_mover ($cageside3, '0 -360 0', 3, $cageside1_spot1);
			sys.wait (1);
			thread cage_mover ($cageside4, '0 -360 0', 3, $cageside1_spot1);
			sys.wait (1);
			cage_mover ($cagebottom, '0 0 0', 3, $cagebottom_spot1);
			
			sys.wait (0.5);


/*
            $cageside1.time (3);
            $cageside2.time (3);
            $cageside3.time (3);
            $cageside4.time (3);
            $cagebottom.time (3);

            $cageside1.rotateOnce ('0 -360 0');
            $cageside2.rotateOnce ('0 -360 0');
            $cageside3.rotateOnce ('0 -360 0');
            $cageside4.rotateOnce ('0 -360 0');

            $cageside1.moveTo ($cageside1_spot1);
            $cageside2.moveTo ($cageside1_spot1);
            $cageside3.moveTo ($cageside1_spot1);
            $cageside4.moveTo ($cageside1_spot1);
            $cagebottom.moveTo ($cagebottom_spot1);
*/

            //sys.waitFor ($cageside1);

            sys.trigger ($soul_emitter_1);
                            
            sys.wait (2);

            sys.trigger ($light_trigger1);
            
            //move room and rocks up fast

            $rock1.unbind ();
            $rock2.unbind ();
            $rock3.unbind ();
            $rock4.unbind ();
            $rock5.unbind ();
            $rock6.unbind ();
            $rock7.unbind ();
            $rock8.unbind ();
            $rock9.unbind ();
            $rock10.unbind ();
            $rock11.unbind ();
            $rock12.unbind ();
            
            $rock1.bind ($cageroom_mover);
            $rock2.bind ($cageroom_mover);
            $rock3.bind ($cageroom_mover);
            $rock4.bind ($cageroom_mover);
            $rock5.bind ($cageroom_mover);
            $rock6.bind ($cageroom_mover);
            $rock7.bind ($cageroom_mover);
            $rock8.bind ($cageroom_mover);
            $rock9.bind ($cageroom_mover);
            $rock10.bind ($cageroom_mover);
            $rock11.bind ($cageroom_mover);
            $rock12.bind ($cageroom_mover);
            $rock13.bind ($cageroom_mover);
            $rock14.bind ($cageroom_mover);
            $rock15.bind ($cageroom_mover);
            $rock16.bind ($cageroom_mover);               
            $rock17.bind ($cageroom_mover);
            $rock18.bind ($cageroom_mover);
            $rock19.bind ($cageroom_mover);
            $rock20.bind ($cageroom_mover);

            $cageroom_tube.bind ($cageroom_mover);
            $cageroom_mover.accelTime (2);
            $cageroom_mover.time (4);
            
            $cageroom_mover.startSoundShader ("cage_decent", SND_CHANNEL_VOICE );
            
            $cageroom_mover.move (UP ,5000);

            sys.wait (4);

            sys.trigger ($cage_teleport);
			$cage2side1_anchor.startSoundShader ("gates_land", SND_CHANNEL_VOICE );
	               
        }

void cage_open () 

	{        
               //release player in new area
               
               $cage2side1_anchor.startSoundShader ("hell_revgate", SND_CHANNEL_VOICE2 );
               
               $cage2side1_anchor.time (.2);
               $cage2side2_anchor.time (.2);
               $cage2side3_anchor.time (.2);
               $cage2side4_anchor.time (.2);

               $cage2side1_anchor.rotateOnce ('3 0 0');
               $cage2side2_anchor.rotateOnce ('0 0 2');
               $cage2side3_anchor.rotateOnce ('-3 0 0');
               $cage2side4_anchor.rotateOnce ('0 0 -2');

               sys.waitFor ($cage2side1_anchor);

               $cage2side1_anchor.decelTime (.5);
               $cage2side2_anchor.decelTime (.5);
               $cage2side3_anchor.decelTime (.5);
               $cage2side4_anchor.decelTime (.5);

               $cage2side1_anchor.time (.6);
               $cage2side2_anchor.time (.8);
               $cage2side3_anchor.time (.6);
               $cage2side4_anchor.time (.8);
               
               $cage2side1_anchor.rotateOnce ('-40 0 0');
               $cage2side2_anchor.rotateOnce ('0 0 -40');
               $cage2side3_anchor.rotateOnce ('40 0 0');
               $cage2side4_anchor.rotateOnce ('0 0 40');
                                                        
               sys.waitFor ($cage2side1_anchor);

               $cage2side1_anchor.accelTime (1);
               $cage2side2_anchor.accelTime (1);
               $cage2side3_anchor.accelTime (1);
               $cage2side4_anchor.accelTime (1);

               $cage2side1_anchor.time (1);
               $cage2side2_anchor.time (1);
               $cage2side3_anchor.time (1);
               $cage2side4_anchor.time (1);

               sys.waitFor ($cage2side1_anchor);

               $cage2side1_anchor.moveTo ($cage2side1_spot1);
               $cage2side2_anchor.moveTo ($cage2side2_spot1);
               $cage2side3_anchor.moveTo ($cage2side3_spot1);
               $cage2side4_anchor.moveTo ($cage2side4_spot1);
                             
               sys.waitFor ($cage2side1_anchor);
               
                         
               $cage2side1_anchor.rotateOnce ('-300 0 0');
               $cage2side2_anchor.rotateOnce ('0 0 -300');
               $cage2side3_anchor.rotateOnce ('300 0 0');
               $cage2side4_anchor.rotateOnce ('0 0 300');

               $cage2side1_anchor.moveTo ($cage2side1_spot2);
               $cage2side2_anchor.moveTo ($cage2side2_spot2);
               $cage2side3_anchor.moveTo ($cage2side3_spot2);
               $cage2side4_anchor.moveTo ($cage2side4_spot2);

               sys.waitFor ($cage2side1_anchor);

               $cage2side1_anchor.time (.8);
               $cage2side2_anchor.time (.8);
               $cage2side3_anchor.time (.8);
               $cage2side4_anchor.time (.8);

               $cage2side1_anchor.rotateOnce ('-800 0 0');
               $cage2side2_anchor.rotateOnce ('0 0 -800');
               $cage2side3_anchor.rotateOnce ('800 0 0');
               $cage2side4_anchor.rotateOnce ('0 0 800');

               $cage2side1_anchor.moveTo ($cage2side1_spot3);
               $cage2side2_anchor.moveTo ($cage2side2_spot3);
               $cage2side3_anchor.moveTo ($cage2side3_spot3);
               $cage2side4_anchor.moveTo ($cage2side4_spot3);
             

           }

        //////////////////////////
	// wall open
	//////////////////////////

        //rearrange blocks

	void wall_open () 
	{        
                 $wall4_corner.time (.5);
                 $wall4_corner.accelTime (.5);
                 $wall1_1.time (.5);
                 $wall1_1.decelTime (.5);
                 $wall1_2.time (.5);
                 $wall1_2.decelTime (.5);
                 $wall1_3.time (.5);
                 $wall1_3.decelTime (.5);
                 $wall1_4.time (.5);
                 $wall1_4.decelTime (.5);
                 $wall1_5.time (.5);
                 $wall1_5.decelTime (.5);
                 $wall1_6.time (.6);
                 $wall1_6.decelTime (.5);

                 $wall2_1.time (1);
                 $wall2_1.decelTime (.5);
                 $wall2_2.time (.5);
                 $wall2_2.decelTime (.5);
                 $wall2_3.time (.5);
                 $wall2_3.decelTime (.5);
                 $wall2_4.time (.5);
                 $wall2_4.decelTime (.5);
                 $wall2_5.time (.6);
                 $wall2_5.decelTime (.5);
                 $wall2_6.time (.5);
                 $wall2_6.decelTime (.5);

                 $wall3_1.time (.6);
                 $wall3_1.decelTime (.5);
                 $wall3_2.time (.6);
                 $wall3_2.decelTime (.5);
                 $wall3_3.time (.6);
                 $wall3_3.decelTime (.5);
                 $wall3_4.time (.6);
                 $wall3_4.decelTime (.5);
                 $wall3_5.time (.6);
                 $wall3_5.decelTime (.5);
                 $wall3_6.time (.6);
                 $wall3_6.decelTime (.5);

                 $wall4_1.time (.8);
                 $wall4_1.decelTime (.5);
                 $wall4_2.time (.6);
                 $wall4_2.decelTime (.5);
                 $wall4_3.time (2);
                 $wall4_3.decelTime (.5);
                 $wall4_4.time (.5);
                 $wall4_4.decelTime (.5);
                 $wall4_5.time (1);
                 $wall4_5.decelTime (.5);

                 $wall1_anchor.rotateOnce ('0 -80 0');
                 $wall2_anchor.rotateOnce ('0 80 0');

                 $wall1_1.move (SOUTH ,320);
                 $wall1_1.rotateOnce ('0 -90 0');
                                
                 $wall1_corner.moveTo ($wall1_corner_spot1);
                 $wall1_2.moveTo ($wall1_2_spot1);
                 $wall1_3.moveTo ($wall1_3_spot1);
                 $wall1_4.moveTo ($wall1_4_spot1);
                 $wall1_5.moveTo ($wall1_5_spot1);
                 $wall1_6.moveTo ($wall1_6_spot1);

                 $wall2_2.moveTo ($wall2_2_spot1);
                 $wall2_3.moveTo ($wall2_3_spot1);
                 $wall2_4.moveTo ($wall2_4_spot1);
                 $wall2_5.moveTo ($wall2_5_spot1);
                 $wall2_6.moveTo ($wall2_6_spot1);

                 sys.waitFor ($wall1_anchor);

                 $wall1_corner.move (UP ,128);

                 $wall1_2.rotateOnce ('0 180 0');
                 $wall1_3.rotateOnce ('0 180 0');
                 $wall1_4.rotateOnce ('0 180 0');
                 $wall1_5.rotateOnce ('0 180 0');
                 $wall1_6.rotateOnce ('0 270 0');

                 $wall2_2.rotateOnce ('0 -180 0');
                 $wall2_3.rotateOnce ('0 -90 0');
                 $wall2_4.rotateOnce ('0 -180 0');
                 $wall2_5.rotateOnce ('0 90 0');
                 $wall2_6.rotateOnce ('0 -180 0');

                 $wall1_2.moveTo ($wall1_2_spot2);
                 $wall1_3.moveTo ($wall1_3_spot2);
                 $wall1_4.moveTo ($wall1_4_spot2);
                 $wall1_5.moveTo ($wall1_5_spot2);
                 $wall1_6.moveTo ($wall1_6_spot2);

                 $wall2_2.moveTo ($wall2_2_spot2);
                 $wall2_3.moveTo ($wall2_3_spot2);
                 $wall2_4.moveTo ($wall2_4_spot2);
                 $wall2_5.moveTo ($wall2_5_spot2);
                 $wall2_6.moveTo ($wall2_6_spot2);

                 $wall3_1.move (WEST ,320);

                 sys.waitFor ($wall3_1);
                 
                 $wall3_2.moveTo ($wall3_2_spot1);                 
                 $wall3_2.moveTo ($wall3_2_spot2);

                 $wall3_3.moveTo ($wall3_2_spot1);
                 $wall3_3.moveTo ($wall3_3_spot2);

                 $wall3_4.moveTo ($wall3_4_spot1);
                 $wall3_4.moveTo ($wall3_4_spot2);

                 $wall3_5.moveTo ($wall3_5_spot1);
                 $wall3_5.moveTo ($wall3_5_spot2);

                 $wall3_6.moveTo ($wall3_6_spot1);
                 $wall3_6.rotateOnce ('0 180 0');
                 $wall3_6.moveTo ($wall3_6_spot2);

                 $wall2_1.moveTo ($wall2_1_spot1);
                 sys.waitFor ($wall2_1);
                 $wall2_1.rotateOnce ('0 270 0');
                 $wall2_1.moveTo ($wall2_1_spot2);

                 $wall4_corner.moveTo ($wall4_corner_spot1);
                 sys.waitFor ($wall4_corner);
                 $wall4_corner.move (UP ,128);
                 
                 $wall4_1.move (EAST ,256);
                                  
                 $wall4_2.moveTo ($wall4_2_spot1);
                  sys.waitFor ($wall4_2);
                 $wall4_2.moveTo ($wall4_2_spot2);
                 
                 $wall4_3.moveTo ($wall4_3_spot1);
                  sys.waitFor ($wall4_3);
                 $wall4_3.moveTo ($wall4_3_spot2);

                 $wall4_4.moveTo ($wall4_4_spot1);
                  sys.waitFor ($wall4_4);
                 $wall4_4.moveTo ($wall4_4_spot2);

                 $wall4_5.moveTo ($wall4_5_spot1);
                  sys.waitFor ($wall4_5);
                 $wall4_5.rotateOnce ('0 0 360');
                 $wall4_5.moveTo ($wall4_5_spot2);
                              
        }

        //////////////////////////
	// form bridge
	//////////////////////////

        //rearrange blocks to make bridge

	void bridge_form () 
	{ 
                 sys.trigger ($bridgequake);

                 $wall1_corner.rotateOnce ('0 180 0');
                 $wall4_corner.rotateOnce ('0 -180 0');
                 $wall1_corner.moveTo ($wall1_corner_spot2);
                 $wall4_corner.moveTo ($wall4_corner_spot2);

                 sys.waitFor ($wall4_corner);

                 $wall1_corner.moveTo ($wall1_corner_spot3);
                 $wall4_corner.moveTo ($wall4_corner_spot3);

                 sys.waitFor ($wall4_corner);

                 $wall1_1.time (2);
                 $wall1_1.decelTime (.5);
                 $wall1_2.time (2.5);
                 $wall1_2.decelTime (.5);
                 $wall1_3.time (1.7);
                 $wall1_3.decelTime (.5);
                 $wall1_4.time (2.4);
                 $wall1_4.decelTime (.5);
                 $wall1_5.time (2.2);
                 $wall1_5.decelTime (.5);
                 $wall1_6.time (2.6);
                 $wall1_6.decelTime (.5);

                 $wall2_1.time (2.1);
                 $wall2_1.decelTime (.5);
                 $wall2_2.time (2);
                 $wall2_2.decelTime (.5);
                 $wall2_3.time (1.8);
                 $wall2_3.decelTime (.5);
                 $wall2_4.time (2.3);
                 $wall2_4.decelTime (.5);
                 $wall2_5.time (2.6);
                 $wall2_5.decelTime (.5);
                 $wall2_6.time (2.1);
                 $wall2_6.decelTime (.5);

                 $wall3_1.time (2.1);
                 $wall3_1.decelTime (.5);
                 $wall3_2.time (2.4);
                 $wall3_2.decelTime (.5);
                 $wall3_3.time (2.5);
                 $wall3_3.decelTime (.5);
                 $wall3_4.time (1.7);
                 $wall3_4.decelTime (.5);
                 $wall3_5.time (1.8);
                 $wall3_5.decelTime (.5);
                 $wall3_6.time (2);
                 $wall3_6.decelTime (.5);

                 $wall4_1.time (2);
                 $wall4_1.decelTime (.5);
                 $wall4_2.time (2.2);
                 $wall4_2.decelTime (.5);
                 $wall4_3.time (2.5);
                 $wall4_3.decelTime (.5);
                 $wall4_4.time (2.1);
                 $wall4_4.decelTime (.5);
                 $wall4_5.time (1.9);
                 $wall4_5.decelTime (.5);

                 $wall1_1.moveTo ($bridge1_1_spot1);
                 $wall1_2.moveTo ($bridge1_2_spot1);
                 $wall1_3.moveTo ($bridge1_3_spot1);
                 $wall1_4.moveTo ($bridge1_4_spot1);
                 $wall1_5.moveTo ($bridge1_5_spot1);
                 $wall1_6.moveTo ($bridge1_6_spot1);

                 $wall2_1.moveTo ($bridge2_1_spot1);
                 $wall2_2.moveTo ($bridge2_2_spot1);
                 $wall2_3.moveTo ($bridge2_3_spot1);
                 $wall2_4.moveTo ($bridge2_4_spot1);
                 $wall2_5.moveTo ($bridge2_5_spot1);
                 $wall2_6.moveTo ($bridge2_6_spot1);

                 $wall3_1.moveTo ($bridge3_1_spot1);
                 $wall3_2.moveTo ($bridge3_2_spot1);
                 $wall3_3.moveTo ($bridge3_3_spot1);
                 $wall3_4.moveTo ($bridge3_4_spot1);
                 $wall3_5.moveTo ($bridge3_5_spot1);
                 $wall3_6.moveTo ($bridge3_6_spot1);

                 $wall4_1.moveTo ($bridge4_1_spot1);
                 $wall4_2.moveTo ($bridge4_2_spot1);
                 $wall4_3.moveTo ($bridge4_3_spot1);
                 $wall4_4.moveTo ($bridge4_4_spot1);
                 $wall4_5.moveTo ($bridge4_5_spot1);

                 sys.waitFor ($wall4_5);

                 $wall1_1.moveTo ($bridge1_1_spot2);
                 $wall1_1.rotateOnce ('0 -180 360');
                 $wall1_2.moveTo ($bridge1_2_spot2);
                 $wall1_2.rotateOnce ('0 180 -360');
                 $wall1_3.moveTo ($bridge1_3_spot2);
                 $wall1_3.rotateOnce ('0 180 360');
                 $wall1_4.moveTo ($bridge1_4_spot2);
                 $wall1_4.rotateOnce ('0 180 -360');
                 $wall1_5.moveTo ($bridge1_5_spot2);
                 $wall1_5.rotateOnce ('0 180 360');
                 $wall1_6.moveTo ($bridge1_6_spot2);
                 $wall1_6.rotateOnce ('0 -180 360');

                 $wall2_1.moveTo ($bridge2_1_spot2);
                 $wall2_1.rotateOnce ('0 -180 360');
                 $wall2_2.moveTo ($bridge2_2_spot2);
                 $wall2_2.rotateOnce ('0 180 -360');
                 $wall2_3.moveTo ($bridge2_3_spot2);
                 $wall2_3.rotateOnce ('0 180 360');
                 $wall2_4.moveTo ($bridge2_4_spot2);
                 $wall2_4.rotateOnce ('0 -180 360');
                 $wall2_5.moveTo ($bridge2_5_spot2);
                 $wall2_5.rotateOnce ('0 180 -360');
                 $wall2_6.moveTo ($bridge2_6_spot2);
                 $wall2_6.rotateOnce ('0 -180 360');

                 $wall3_1.moveTo ($bridge3_1_spot2);
                 $wall3_1.rotateOnce ('0 -180 360');
                 $wall3_2.moveTo ($bridge3_2_spot2);
                 $wall3_2.rotateOnce ('0 -180 360');
                 $wall3_3.moveTo ($bridge3_3_spot2);
                 $wall3_3.rotateOnce ('0 180 -360');
                 $wall3_4.moveTo ($bridge3_4_spot2);
                 $wall3_4.rotateOnce ('0 180 360');
                 $wall3_5.moveTo ($bridge3_5_spot2);
                 $wall3_5.rotateOnce ('0 -180 360');
                 $wall3_6.moveTo ($bridge3_6_spot2);
                 $wall3_6.rotateOnce ('0 180 -360');

                 $wall4_1.moveTo ($bridge4_1_spot2);
                 $wall4_1.rotateOnce ('0 -180 360');
                 $wall4_2.moveTo ($bridge4_2_spot2);
                 $wall4_2.rotateOnce ('0 180 -360');
                 $wall4_3.moveTo ($bridge4_3_spot2);
                 $wall4_3.rotateOnce ('0 -180 360');
                 $wall4_4.moveTo ($bridge4_4_spot2);
                 $wall4_4.rotateOnce ('0 -180 360');
                 $wall4_5.moveTo ($bridge4_5_spot2);
                 $wall4_5.rotateOnce ('0 -180 360');

                 sys.waitFor ($wall4_5);
                 sys.trigger ($bridgequake);
                                                   
        }

         //////////////////////////
	// first hall with dust particles
	//////////////////////////
       
	//  turn dust particles on and off
 	
        void start_firstdust () 
	{ 
        while (1)
	{ 
                 sys.trigger ($pillardust1);    
                 sys.wait (1);
                 sys.trigger ($pillardust2);    
                 sys.wait (.8);
                 sys.trigger ($pillardust3);    
                 sys.wait (3);
                 sys.trigger ($pillardust1);    
                 sys.wait (1);
                 sys.trigger ($pillardust2);    
                 sys.wait (.8);
                 sys.trigger ($pillardust3);    
                 sys.wait (2);                
        }
        }
         void firstdust_off ()
	{

			sys.killthread ( "map_hell1::start_firstdust" );

	}

        //////////////////////////
	// steps
	//////////////////////////

        //lower steps in first hall
        
	void step_lower () 
	{
                                       			
			$step1.move ( DOWN , 7 );  
			sys.waitFor ($step1);
                        $step2.move ( DOWN , 15 );  
			sys.waitFor ($step2);
                        $step3.move ( DOWN , 23 );  
			sys.waitFor ($step3);
                        $step4.move ( DOWN , 31 );  
			sys.waitFor ($step4);
                        $step5.move ( DOWN , 39 );  
			sys.waitFor ($step5);
                        $step6.move ( DOWN , 47 );  
			sys.waitFor ($step6);
                        $step7.move ( DOWN , 55 );  
			sys.waitFor ($step7);			
	}
 
        //////////////////////////
	// first room
	//////////////////////////

        //wall in first room opens to let monster through

	void door_open () 
	{
               
        sys.trigger ($hk_wallbust_01);
        
        $bricksleft_anchor.rotateOnce ('0 30 0');
        $bricksright_anchor.rotateOnce ('0 -30 0');

        $bricksleft_anchor.moveTo ($bricksleft_spot2);
        $bricksright_anchor.moveTo ($bricksright_spot2);
                       
		$brick1.moveTo ($brick1_spot2);
        $brick2.moveTo ($brick2_spot2);
        $brick2.rotateOnce ('0 180 0');
        $brick3.moveTo ($brick3_spot2);
        $brick3.rotateOnce ('0 -180 0');
        $brick4.moveTo ($brick4_spot2);
        $brick4.rotateOnce ('0 180 0');
        $brick5.moveTo ($brick5_spot2);
        $brick6.moveTo ($brick6_spot2);
        $brick7.moveTo ($brick7_spot2);
        $brick8.moveTo ($brick8_spot2);
        $brick8.rotateOnce ('0 0 180');
        $brick9.moveTo ($brick9_spot2);
        $brick10.moveTo ($brick10_spot2);
        $brick10.rotateOnce ('0 180 0');
        $brick11.moveTo ($brick11_spot2);

        
        $brick1.moveTo ($brick1_spot3);
        $brick2.moveTo ($brick2_spot3);
        $brick3.moveTo ($brick3_spot3);
        $brick4.moveTo ($brick4_spot3);
        $brick5.moveTo ($brick5_spot3);
        $brick6.moveTo ($brick6_spot3);
        $brick7.moveTo ($brick7_spot3);
        $brick8.moveTo ($brick8_spot3);
        $brick9.moveTo ($brick9_spot3);
        $brick10.moveTo ($brick10_spot3);
        $brick11.moveTo ($brick11_spot3);
              
  		sys.waitFor ($brick11);
    }

        //wall in first room closes behind monster 

	void door_close () 
	{
                          
        $hk_wallbust_01.startSoundShader ("hk_revwallbust", SND_CHANNEL_VOICE2 );
        
        $brick1.moveTo ($brick1_spot2);
        $brick2.moveTo ($brick2_spot2);
        $brick2.rotateOnce ('0 180 0');
        $brick3.moveTo ($brick3_spot2);
        $brick3.rotateOnce ('0 -180 0');
        $brick4.moveTo ($brick4_spot2);
        $brick4.rotateOnce ('0 180 0');
        $brick5.moveTo ($brick5_spot2);
        $brick6.moveTo ($brick6_spot2);
        $brick7.moveTo ($brick7_spot2);
        $brick8.moveTo ($brick8_spot2);
        $brick8.rotateOnce ('0 0 180');
        $brick9.moveTo ($brick9_spot2);
        $brick10.moveTo ($brick10_spot2);
        $brick10.rotateOnce ('0 180 0');
        $brick11.moveTo ($brick11_spot2);

        $brick1.moveTo ($brick1_spot1);
        $brick2.moveTo ($brick2_spot1);
        $brick3.moveTo ($brick3_spot1);
        $brick4.moveTo ($brick4_spot1);
        $brick5.moveTo ($brick5_spot1);
        $brick6.moveTo ($brick6_spot1);
        $brick7.moveTo ($brick7_spot1);
        $brick8.moveTo ($brick8_spot1);
        $brick9.moveTo ($brick9_spot1);
        $brick10.moveTo ($brick10_spot1);
        $brick11.moveTo ($brick11_spot1);

        $bricksleft_anchor.moveTo ($bricksleft_spot1);
        $bricksright_anchor.moveTo ($bricksright_spot1);
        $bricksleft_anchor.rotateOnce ('0 -30 0');
        $bricksright_anchor.rotateOnce ('0 30 0');
        
        sys.waitFor ($bricksright_anchor);                
               	
	}

    //////////////////////////
	// alcoves
	//////////////////////////

	void alcove1_open () 
	{
                                
		$alcove1_leftwall.startSoundShader ("wallmover_01", SND_CHANNEL_VOICE2 );
		$alcove1_leftwall.moveTo ($alcove1_leftwall_2);
        $alcove1_rightwall.startSoundShader ("wallmover_01", SND_CHANNEL_VOICE2 );
        $alcove1_rightwall.moveTo ($alcove1_rightwall_2);
        $alcove1_backwall.startSoundShader ("wallmover_02", SND_CHANNEL_VOICE2 );
        $alcove1_backwall.moveTo ($alcove1_backwall_2);
                           
  		sys.waitFor ($alcove1_leftwall);
    }

	void alcove1_close () 
	{
                                
		$alcove1_leftwall.moveTo ($alcove1_leftwall_1);
        $alcove1_rightwall.moveTo ($alcove1_rightwall_1);
        $alcove1_backwall.moveTo ($alcove1_backwall_1);
                    
  		sys.waitFor ($alcove1_leftwall);
    }

	void alcove2_open () 
	{
        $alcove2_leftwall.startSoundShader ("wallmover_01", SND_CHANNEL_VOICE2 );                        
		$alcove2_leftwall.moveTo ($alcove2_leftwall_2);
        $alcove2_rightwall.startSoundShader ("wallmover_01", SND_CHANNEL_VOICE2 );
        $alcove2_rightwall.moveTo ($alcove2_rightwall_2);
        $alcove2_backwall.startSoundShader ("wallmover_02", SND_CHANNEL_VOICE2 );
        $alcove2_backwall.moveTo ($alcove2_backwall_2);
                    
  		sys.waitFor ($alcove2_leftwall);
    }

	void alcove2_close () 
	{
                                
		$alcove2_leftwall.moveTo ($alcove2_leftwall_1);
        $alcove2_rightwall.moveTo ($alcove2_rightwall_1);
        $alcove2_backwall.moveTo ($alcove2_backwall_1);
                    
  		sys.waitFor ($alcove2_leftwall);
    }

	//////////////////////////
	// pit
	//////////////////////////

	void pit_descent () 
	{
        sys.wait (1);
        $pit_plat1.accelTime (.1);
        $pit_plat1.decelTime (.5);
        $pit_plat1.time (2);               			
		
		$pit_plat1.startSoundShader ("hellride_lower_2s", SND_CHANNEL_VOICE );
		
		$pit_plat1.moveTo ( $pit1_spot1);
        $pit_plat1.rotateOnce ('0 40 0');  
		sys.waitFor ($pit_plat1);
        
        $pit_plat1.time (7.5);
        
        $pit_plat1.startSoundShader ("hell_rockride_8s", SND_CHANNEL_VOICE2 );
        
        $pit_plat1.moveTo ( $pit1_spot2);
        $pit_plat1.rotateOnce ('0 -40 0');  
		sys.waitFor ($pit_plat1);
		
        $pit_plat1.time (2);
        
        $pit_plat1.startSoundShader ("hellride_lower_2s", SND_CHANNEL_VOICE );
        
        $pit_plat1.move ( DOWN , 32 );
        sys.waitFor ($pit_plat1);

        sys.wait (6);

        $pit_plat1.decelTime (.1);
        $pit_plat1.time (.8);
        
        $pit_plat1.startSoundShader ("hellride_platrot", SND_CHANNEL_VOICE2 );
        
        $pit_plat1.move ( DOWN , 192 );
        $pit_plat1.rotateOnce ('0 0 -43');
        sys.waitFor ($pit_plat1);
        $pit_plat1.time (.2);
        $pit_plat1.move ( UP , 4 );
        sys.waitFor ($pit_plat1);
        $pit_plat1.move ( DOWN , 4 );
        sys.waitFor ($pit_plat1);
        sys.wait (.5);
        $pit_plat1.decelTime (.5);
        $pit_plat1.time (1.2);
        $pit_plat1.move ( DOWN , 32 );                          
	}

    //////////////////////////
	// basement pillar room
	//////////////////////////

	void bbrick1 () 
	{
        $bbrick1_mover1.time (.1);               			
        $bbrick1_mover2.time (.1);
        $bbrick1_mover3.time (.2);
        $bbrick1_mover4.time (.1);
        $bbrick1_mover5.time (.2);
        $bbrick1_mover6.time (.2);
        $bbrick1_mover1.rotateOnce ('-30 0 0');
        $bbrick1_mover2.rotateOnce ('0 -75 0');
        $bbrick1_mover3.rotateOnce ('0 -95 0');
        $bbrick1_mover4.rotateOnce ('0 85 0');
        $bbrick1_mover5.rotateOnce ('0 60 0');
        $bbrick1_mover5.move (NORTH , 32);
        $bbrick1_mover6.rotateOnce ('0 85 0');                         
	}

    void bbrick1_down () 
	{
        $bbrick1_moveable1.bind ($bbrick1_lower);
        $bbrick1_moveable2.bind ($bbrick1_lower);
        $bbrick1_moveable3.bind ($bbrick1_lower);
        $bbrick1_moveable4.bind ($bbrick1_lower);
        $bbrick1_moveable8.bind ($bbrick1_lower);
        
        sys.wait (.5);
        $bbrick1_lower.accelTime (.5);
        $bbrick1_lower.time (2);
        $bbrick1_lower.move (DOWN , 64);
        $bbrick1_lower.rotateOnce ('0 5 0');
	}

    void bbrick2 () 
	{
        $bbrick2_mover1.time (.1);               			
        $bbrick2_mover2.time (.1);
        $bbrick2_mover3.time (.1);
        $bbrick2_mover4.time (.1);
        $bbrick2_mover5.time (.1);
        $bbrick2_mover6.time (.1);
        $bbrick2_mover1.rotateOnce ('-35 0 0');
        $bbrick2_mover2.rotateOnce ('0 70 0');
        $bbrick2_mover3.rotateOnce ('0 85 0');
        $bbrick2_mover4.rotateOnce ('0 80 0');
        $bbrick2_mover5.rotateOnce ('0 -80 0');
        $bbrick2_mover6.rotateOnce ('0 -75 0');                         
	}

    void bbrick3 () 
	{
        $bbrick3_mover1.time (.5);               			
        $bbrick3_mover2.time (.5);
        
        $bbrick3_mover1.rotateOnce ('0 -70 0');
        $bbrick3_mover2.rotateOnce ('0 75 0');
	}

    //////////////////////////
	// mancubus plat room crusher
	//////////////////////////
        
    void stomp1 () 
	{   
        $stomp1.time (.6);
        $stomp1.accelTime (.5);
        $stomp1.decelTime (.05);
        $stomp1.move (DOWN ,256);
        sys.waitFor ($stomp1);

        sys.trigger ($stomp1_particle);
        sys.trigger ($stomp1_speaker);

        $stomp1.time (.08);
        $stomp1.accelTime (.05);
        $stomp1.decelTime (.02);
        $stomp1.move (UP ,4);
        sys.waitFor ($stomp1);
        $stomp1.move (DOWN ,4);                        
        sys.waitFor ($stomp1);
        
        sys.wait (3);

        $stomp1.time (2);
        $stomp1.accelTime (.5);
        $stomp1.decelTime (.2);
        $stomp1.move (UP ,256);
        sys.waitFor ($stomp1);                        
    }

	void start_stomp1 () 
	{
        while(1) {
            $stomp1.time (.6);
            $stomp1.accelTime (.5);
            $stomp1.decelTime (.05);
            $stomp1.move (DOWN ,256);
            sys.waitFor ($stomp1);

            sys.trigger ($stomp1_particle);
            sys.trigger ($stomp1_speaker);

            $stomp1.time (.08);
            $stomp1.accelTime (.05);
            $stomp1.decelTime (.02);
            $stomp1.move (UP ,4);
            sys.waitFor ($stomp1);
            $stomp1.move (DOWN ,4);                        
            sys.waitFor ($stomp1);
            
            sys.wait (.8);
            
            $stomp1.time (2);
            $stomp1.accelTime (.5);
            $stomp1.decelTime (.2);
            $stomp1.move (UP ,256);
            sys.waitFor ($stomp1);
            sys.wait (1);
		}                                       					
	}

    //////////////////////////
	// misc
	//////////////////////////


    void close_doorblock1 () 
	{
		sys.trigger ($doorblock1_dust);
	        sys.trigger ($doorblock1_speaker);
                $doorblock1.rotateOnce ('0 90 0');  
		sys.waitFor ($doorblock1);              
		$doorblock1.move ( SOUTH ,224);  
		sys.waitFor ($doorblock1);
                sys.trigger ($doorblock1_obstacle);
		sys.wait (1);
		sys.trigger ($doorblock1_dust);
	}

    void brickdoor1_open () 
	{
		$brickdoor1.rotateOnce ('0 80 0');  
		sys.waitFor ($brickdoor1);
	}
    
    void drop_corpse1 () 
	{
		$corpse1.unbind ();  			
	}

    void drop_corpse2 () 
	{
        $corpsedrop2.accelTime (.3);
        $corpsedrop2.time (.5);                       			
		$corpsedrop2.move ( DOWN,80);
        sys.waitFor ($corpsedrop2);
        $corpsedrop2.move ( DOWN,8);  						
	}

    void drop_corpse3 () 
	{
        $corpse3.unbind (); 						
	}
    void drop_corpse5 () 
	{
		$corpse5.unbind (); 						
	}
   
    void drop_corpse6 () 
	{
        $corpse6.unbind (); 						
	}
	        
	void cache_sounds() {
		sys.cacheSoundShader ("tp_electro");
		sys.cacheSoundShader ("gateimpact_01");
		sys.cacheSoundShader ("gateimpact_02");
		sys.cacheSoundShader ("gateimpact_03");
		sys.cacheSoundShader ("gateimpact_04");
		sys.cacheSoundShader ("gateimpact_05");
		sys.cacheSoundShader ("wallmover_01");
		sys.cacheSoundShader ("wallmover_02");
		sys.cacheSoundShader ("hell_rockride_8s");
		sys.cacheSoundShader ("hellride_lower_2s");
		sys.cacheSoundShader ("hellride_platrot");
		sys.cacheSoundShader ("hk_revwallbust");
		sys.cacheSoundShader ("hell_revgate");
		sys.cacheSoundShader ("cage_decent");
		sys.cacheSoundShader ("gates_land");
		sys.cacheSoundShader ("hell_corpsemover");
	}        
	
	void guardian_room_fadeout() {
		$hs_1.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_2.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_3.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_4.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_5.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_6.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_7.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_8.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_9.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_10.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_11.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$hs_12.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
	}

	void guardian_room_fadein() {
		$hs_1.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_2.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_3.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_4.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_5.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_6.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_7.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_8.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_9.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_10.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_11.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
		$hs_12.fadeSound ( SND_CHANNEL_ANY, -2, 5 );
	}


	// They are on by default...
	void toggle_guardianroom_sounds() {
		sys.trigger ($hs_1);
		sys.trigger ($hs_2);
		sys.trigger ($hs_3);
		sys.trigger ($hs_4);
		sys.trigger ($hs_5);
		sys.trigger ($hs_6);
		sys.trigger ($hs_7);
		sys.trigger ($hs_8);
		sys.trigger ($hs_9);
		sys.trigger ($hs_10);
		sys.trigger ($hs_11);
		sys.trigger ($hs_12);
	}

	
	void main ()
	{
		cache_sounds();
		setup_objects();
		guardian_room_fadeout();		// Fade guardian sounds out
		thread ( telering_move() );
        thread ( telering_bob() );
	}
}

//@doomscript-blueprint begin 6
//@source F53BE858
//@catalog 0C260740
//@node 7AEA71C1-0 40 40
//@node F710EDE4-0 330 40
//@node 49D386F6-0 610 40
//@node 92CAC741-0 890 40
//@node B74AFC3E-0 1170 40
//@node 128CE80F-0 1450 40
//@node 54E2A0B5-0 1730 40
//@node 162B55FF-0 2010 40
//@node 96F49F7A-0 2290 40
//@node DBB03D58-0 2570 40
//@node FF59EC60-0 2850 40
//@node C14CE92D-0 3130 40
//@node F4F5934B-0 3410 40
//@node 601794D9-0 3690 40
//@node C41BAFE8-0 3970 40
//@node CC19F2AE-0 4250 40
//@node B7684BDE-0 4530 40
//@node BB7E44AF-0 4810 40
//@node 353AA515-0 5090 40
//@node 007D7943-0 5370 40
//@node 2F63EF6E-0 5650 40
//@node 339FF504-0 5930 40
//@node 479A89F8-0 6210 40
//@node 5715D794-0 6490 40
//@node 32760A93-0 6770 40
//@node 1CD18BA2-0 7050 40
//@node BF25E63C-0 7330 40
//@node C93A699F-0 7610 40
//@node E87C334D-0 7890 40
//@node C6358EC6-0 8170 40
//@node 9381A870-0 8450 40
//@node 5326C50F-0 8730 40
//@node 7F2D5F11-0 9010 40
//@node F614758D-0 9290 40
//@node BEF92A56-0 9570 40
//@node A4AA8228-0 9850 40
//@node D9032E02-0 10130 40
//@node C4558F67-0 10410 40
//@node 146DE1EF-0 10690 40
//@node 94EAD57B-0 10970 40
//@node 14BA2DE3-0 11250 40
//@node B90D6DBF-0 11530 40
//@node 0E592F47-0 11810 40
//@node C352F3CB-0 12090 40
//@node 0836ABB3-0 12370 40
//@node 0AE6F717-0 12650 40
//@node DD8D4233-0 12930 40
//@node 492D78E5-0 13210 40
//@node B98E19BF-0 13490 40
//@node C24A56FC-0 13770 40
//@node 59F51286-0 14050 40
//@node D29416CC-0 14330 40
//@node 42019532-0 14610 40
//@node 3D0FA9B2-0 14890 40
//@node 98F3367C-0 15170 40
//@node 4BB9B76C-0 15450 40
//@node EB777510-0 15730 40
//@node 41A68FC0-0 16010 40
//@node B0DCE740-0 16290 40
//@node 58787D8D-0 16570 40
//@node D8EFE1B8-0 16850 40
//@node 288D5FF8-0 17130 40
//@node 66043AD2-0 17410 40
//@node 627B0792-0 17690 40
//@node 9AC44109-0 17970 40
//@node 2ADAF290-0 18250 40
//@node 557699C7-0 18530 40
//@node A165E896-0 18810 40
//@node EA78DBDD-0 19090 40
//@node A6D7E810-0 19370 40
//@node 98468684-0 19650 40
//@node A6F30259-0 40 40
//@node 8D411D1E-0 330 40
//@node 650B1B74-0 125 145
//@node 80B9FEF6-0 610 200
//@node BE9272F3-0 890 200
//@node E6514FDD-0 1170 200
//@node 538E4D86-0 1450 200
//@node B061B2AE-0 1730 200
//@node 15F7F679-0 2010 200
//@node B061B2AE-1 2290 200
//@node F4FD2655-0 2570 200
//@node D9B0CA84-0 2850 200
//@node 1F7A93FC-0 3130 200
//@node 290FE1BA-0 3410 200
//@node B061B2AE-2 3690 200
//@node 2B3318D2-0 3970 200
//@node B061B2AE-3 4250 200
//@node 1E02D7A4-0 4530 200
//@node 2A935B47-0 40 40
//@node 97D74018-0 330 40
//@node FAD5D0E4-0 125 145
//@node D0D8CCDF-0 610 200
//@node EFC3A75A-0 890 200
//@node BD2D00F8-0 1170 200
//@node 21DC2796-0 1450 200
//@node FFE433B2-0 1730 200
//@node 9B763935-0 2010 200
//@node FFE433B2-1 2290 200
//@node 0DBEC31E-0 2570 200
//@node 57F1FA0E-0 2850 200
//@node 6D3ACDBE-0 3130 200
//@node FF88E1AB-0 3410 200
//@node 47CE30B6-0 3690 200
//@node 0DBEC31E-1 3970 200
//@node 6D3ACDBE-1 4250 200
//@node FF88E1AB-1 4530 200
//@node A6ACC13B-0 40 40
//@node B0C9ADCF-0 330 40
//@node 6E46B26A-0 125 145
//@node D148AC5B-0 -80 145
//@node 3EE1580A-0 610 40
//@node 3C2D219E-0 890 40
//@node 3485DF58-0 1170 40
//@node 08096B5B-0 1450 40
//@node 2D4004F0-0 1730 40
//@node 27929823-0 1525 145
//@node 4A6CE1C5-0 1320 145
//@node 70E1CF71-0 2010 40
//@node 7E26D491-0 2290 40
//@node 72DF7614-0 2085 145
//@node AC092DD3-0 1880 145
//@node D295C1A8-0 2570 40
//@node 6BAC6A86-0 2850 40
//@node 282277B4-0 2645 145
//@node CF5EEE86-0 2440 145
//@node 06756AFB-0 3130 40
//@node 7C92D567-0 3410 40
//@node E71607AB-0 3205 145
//@node 24ED7248-0 3000 145
//@node 86B0D93A-0 3690 40
//@node 68DB36DC-0 3970 40
//@node C42309E3-0 3765 145
//@node 0AD3E085-0 3560 145
//@node 40E425FD-0 4250 40
//@node B79AD983-0 40 40
//@node E5ADD112-0 330 40
//@node 87A853F5-0 610 40
//@node EF521351-0 890 40
//@node 44714C36-0 1170 40
//@node AE6A5259-0 1450 40
//@node A744FD03-0 1730 40
//@node EF521351-1 2010 40
//@node D25F8B52-0 2290 40
//@node 719B2B71-0 2570 40
//@node FC1B22EF-0 2850 40
//@node 719B2B71-1 3130 40
//@node 4DD112EA-0 40 40
//@node E3F54502-0 330 40
//@node 22805CD9-0 610 40
//@node D4613A16-0 890 40
//@node 65A61EBB-0 1170 40
//@node 228F6C38-0 1450 40
//@node 5685CB8E-0 1730 40
//@node C6C22275-0 2010 40
//@node 4D1931EA-0 2290 40
//@node 110D70AB-0 2570 40
//@node 35371AA0-0 2850 40
//@node D20B4DEE-0 3130 40
//@node ABEABD29-0 3410 40
//@node DE814720-0 3690 40
//@node CC0B71DF-0 3970 40
//@node 6B205C6A-0 4250 40
//@node EFA62D89-0 4530 40
//@node E35920A7-0 4810 40
//@node EBF016C1-0 5090 40
//@node B31796D3-0 5370 40
//@node 43183B67-0 5650 40
//@node F13E49CC-0 5930 40
//@node 43183B67-1 6210 40
//@node CBCB5C1D-0 6490 40
//@node 43183B67-2 6770 40
//@node 6000EFF6-0 7050 40
//@node 43183B67-3 7330 40
//@node 6F0BF093-0 7610 40
//@node A8EB811D-0 7890 40
//@node 5054A18B-0 8170 40
//@node B003B44A-0 8450 40
//@node D7681003-0 8730 40
//@node CE45C65A-0 9010 40
//@node 938BB8E5-0 9290 40
//@node BF7A8790-0 9570 40
//@node 3C3D1AC3-0 9850 40
//@node 73EEC63E-0 10130 40
//@node 2DBDEDF9-0 10410 40
//@node A8B7E834-0 10690 40
//@node 59AE1017-0 10970 40
//@node 764EB102-0 11250 40
//@node 0BB49252-0 11530 40
//@node 5978B427-0 11810 40
//@node 5DB5F068-0 12090 40
//@node 150351D2-0 12370 40
//@node F8CC1C53-0 12650 40
//@node 6BD1C014-0 12930 40
//@node D7EC4705-0 13210 40
//@node EF1B6086-0 13490 40
//@node 20055017-0 13770 40
//@node B52D56D8-0 14050 40
//@node 3FD3AD59-0 14330 40
//@node 87C1C2FA-0 14610 40
//@node D9082ACA-0 14890 40
//@node B44E14E9-0 15170 40
//@node 137526EC-0 15450 40
//@node DD7B5DEB-0 15730 40
//@node 21B4BFBE-0 16010 40
//@node 6C9FB85D-0 16290 40
//@node 7E893CB0-0 16570 40
//@node 3FFE404F-0 16850 40
//@node 0C72E6A2-0 17130 40
//@node B0376CE1-0 17410 40
//@node 46A8F9B1-0 17690 40
//@node 7D974114-0 17970 40
//@node 16FF9C8C-0 18250 40
//@node 15AF3684-0 18530 40
//@node 7DF9AC9B-0 18810 40
//@node 13BCF9B4-0 19090 40
//@node 89F8BB24-0 19370 40
//@node A8FA1441-0 19650 40
//@node F7F1781A-0 19930 40
//@node 991D175E-0 40 40
//@node CBAA9AFA-0 330 40
//@node 858F4F63-0 610 40
//@node 0C66F846-0 890 40
//@node 55BFCCD5-0 1170 40
//@node CA055900-0 1450 40
//@node 5F206BB3-0 1730 40
//@node 47ED0BE5-0 2010 40
//@node A6315420-0 2290 40
//@node 2C222954-0 2570 40
//@node 9A5A5C5B-0 2850 40
//@node A416DEDF-0 3130 40
//@node B3B1E6E0-0 3410 40
//@node D6324E9D-0 3690 40
//@node ACA170AE-0 3970 40
//@node 5A6AF7F7-0 4250 40
//@node 53638C4C-0 4530 40
//@node 9A4C73D9-0 4810 40
//@node 12E1053A-0 5090 40
//@node 00FCC161-0 5370 40
//@node 639D53E6-0 5650 40
//@node 878AA0B4-0 5930 40
//@node E8E9040D-0 6210 40
//@node 9A5A5C5B-1 6490 40
//@node 3B30F5B6-0 6770 40
//@node 1E487433-0 7050 40
//@node 9AB3F1C8-0 7330 40
//@node AA747D2D-0 7610 40
//@node AEB086EA-0 7890 40
//@node DFA8F929-0 8170 40
//@node 22500FD0-0 8450 40
//@node 6AF0DF07-0 8730 40
//@node 9A5A5C5B-2 9010 40
//@node 4DE30E02-0 9290 40
//@node B2837A0C-0 9570 40
//@node 657D5856-0 9850 40
//@node 1DD539EC-0 10130 40
//@node 9A5A5C5B-3 10410 40
//@node 277C381E-0 10690 40
//@node 80B812AB-0 10970 40
//@node ADD27B29-0 11250 40
//@node 1DDA949A-0 11530 40
//@node 60F6CB9F-0 11810 40
//@node F95AFF6D-0 12090 40
//@node 78B9B863-0 12370 40
//@node E4ABF5CD-0 12650 40
//@node 9A5A5C5B-4 12930 40
//@node 002708BD-0 13210 40
//@node 53638C4C-1 13490 40
//@node 8CBC47AB-0 13770 40
//@node 12E1053A-1 14050 40
//@node 4EF62F55-0 14330 40
//@node 71046BB8-0 14610 40
//@node 796FFF42-0 14890 40
//@node DDE5F841-0 15170 40
//@node ECB3A440-0 15450 40
//@node 83DAA38E-0 15730 40
//@node 1476AA34-0 16010 40
//@node 7068CE6E-0 16290 40
//@node BC997AF6-0 40 40
//@node E9FF5AF6-0 330 40
//@node 440D61C2-0 610 40
//@node 13CBD347-0 890 40
//@node 994FA080-0 1170 40
//@node A18FACC4-0 1450 40
//@node 54904361-0 1730 40
//@node A8CE155D-0 2010 40
//@node 860F872E-0 2290 40
//@node 20D04112-0 2570 40
//@node F176B497-0 2850 40
//@node 17D696B3-0 3130 40
//@node E239C3E4-0 3410 40
//@node 2F189BD1-0 3690 40
//@node 853E7C15-0 3970 40
//@node 4AB36710-0 4250 40
//@node C3969A5D-0 4530 40
//@node 04FE2BDB-0 4810 40
//@node 6293CF0C-0 5090 40
//@node 1BEB179A-0 5370 40
//@node 7D2C655F-0 5650 40
//@node EE47DD25-0 5930 40
//@node C7E835B6-0 6210 40
//@node 5C33B78D-0 6490 40
//@node DE4E3D49-0 6770 40
//@node DAEFF84F-0 7050 40
//@node A6CD90C8-0 7330 40
//@node F04D2498-0 7610 40
//@node E7654E92-0 7890 40
//@node 406DEA1F-0 8170 40
//@node EF483DA7-0 8450 40
//@node DE7A3456-0 8730 40
//@node A7135A74-0 9010 40
//@node 9B26E3F5-0 9290 40
//@node 1D028531-0 9570 40
//@node C3AD8D2C-0 9850 40
//@node 32AC4B3E-0 10130 40
//@node 9F163893-0 10410 40
//@node E0B725E3-0 10690 40
//@node 2EDA8D6D-0 10970 40
//@node D25419EF-0 11250 40
//@node 7D9EF0E0-0 11530 40
//@node 02E897FA-0 11810 40
//@node 2E96D2A1-0 12090 40
//@node 51B5B4AD-0 12370 40
//@node 0435CD3F-0 12650 40
//@node D5B68F98-0 12930 40
//@node A4EC6D36-0 13210 40
//@node BEB053AB-0 13490 40
//@node 54029BCC-0 13770 40
//@node 54FA784C-0 14050 40
//@node 9444B74E-0 14330 40
//@node 0445D679-0 14610 40
//@node 125F55CA-0 14890 40
//@node 781A709E-0 15170 40
//@node F539DA8C-0 15450 40
//@node B02F34BE-0 15730 40
//@node 93165F90-0 16010 40
//@node ECCFFF86-0 16290 40
//@node 409313C8-0 16570 40
//@node 6D1F315E-0 16850 40
//@node 50514D1C-0 17130 40
//@node 89979CDE-0 17410 40
//@node 83CEB898-0 17690 40
//@node D5638434-0 17970 40
//@node 52983A02-0 18250 40
//@node 0D7C7DBF-0 18530 40
//@node 310DC500-0 18810 40
//@node FFB339D9-0 19090 40
//@node 5D46C42A-0 19370 40
//@node 8B65CBB5-0 19650 40
//@node E7C30E6D-0 19930 40
//@node 699B5D6E-0 20210 40
//@node 0D50DBF7-0 20490 40
//@node 7D2C0F43-0 20770 40
//@node EF0BB719-0 21050 40
//@node 0BA5B90B-0 21330 40
//@node 3C115FED-0 21610 40
//@node 427D48AB-0 21890 40
//@node D8FECF51-0 22170 40
//@node FF6CFBD3-0 22450 40
//@node 0769CFA9-0 22730 40
//@node 00AA79CB-0 23010 40
//@node 172808FD-0 23290 40
//@node 1D22E54B-0 23570 40
//@node 4AA57479-0 23850 40
//@node 481E7322-0 24130 40
//@node 75F7E7F2-0 24410 40
//@node F9AE255E-0 24690 40
//@node 8D396DCB-0 24970 40
//@node 6180E4DF-0 25250 40
//@node 852E0BB9-0 25530 40
//@node 0D85B35E-0 25810 40
//@node A110FBCB-0 26090 40
//@node 3C43A96C-0 26370 40
//@node 031A654D-0 26650 40
//@node 19D8E74E-0 26930 40
//@node 9615E495-0 27210 40
//@node AD642FBB-0 27490 40
//@node E223138E-0 27770 40
//@node 380FA2F9-0 28050 40
//@node 144AFC8D-0 28330 40
//@node 75AE5BFB-0 28610 40
//@node FA770E06-0 28890 40
//@node 192E1B6D-0 29170 40
//@node 6D1BE2A7-0 29450 40
//@node 6AEF82EB-0 29730 40
//@node 315AF634-0 30010 40
//@node 42C69AEA-0 30290 40
//@node F7E20035-0 30570 40
//@node 6A1F2226-0 30850 40
//@node 27318209-0 31130 40
//@node FDFA1C73-0 31410 40
//@node 3A998618-0 31690 40
//@node 1CBBA1C4-0 31970 40
//@node 017041F9-0 32250 40
//@node F0163C8E-0 32530 40
//@node 019D4A33-0 32810 40
//@node 0C71C77D-0 33090 40
//@node 83A184FB-0 33370 40
//@node 4372AF67-0 40 40
//@node 405202F0-0 330 40
//@node DD3383F9-0 610 40
//@node 8895853F-0 890 40
//@node 9FA44F8E-0 1170 40
//@node 3A175E4A-0 1450 40
//@node 004623AE-0 1730 40
//@node 1524AB6D-0 2010 40
//@node 1FBF79E9-0 2290 40
//@node 004623AE-1 2570 40
//@node 42DE149B-0 2850 40
//@node 7CDD11E3-0 3130 40
//@node 5A0E5F4B-0 3410 40
//@node CED2373E-0 3690 40
//@node 8E9246A7-0 3970 40
//@node B9287131-0 4250 40
//@node 14E3D6A2-0 4530 40
//@node 43394674-0 4810 40
//@node 7120694B-0 5090 40
//@node 8B6E29A7-0 5370 40
//@node E4A44BB2-0 5650 40
//@node 838B3A92-0 5930 40
//@node 3D77C083-0 6210 40
//@node 7A36C1CA-0 6490 40
//@node 9A3165E7-0 6770 40
//@node 11EF4FFF-0 7050 40
//@node 0888EF5F-0 7330 40
//@node A55471AC-0 7610 40
//@node AEC2FC22-0 7890 40
//@node 14CF58E9-0 8170 40
//@node F15336C6-0 8450 40
//@node 845ABED6-0 8730 40
//@node 399B4C6A-0 9010 40
//@node 5FEE09BB-0 9290 40
//@node F3AA9814-0 9570 40
//@node B6F49DB5-0 9850 40
//@node B1D7FD92-0 10130 40
//@node 542B6E84-0 10410 40
//@node ED01CD12-0 10690 40
//@node 1F3EF3B7-0 10970 40
//@node DE07E5A8-0 11250 40
//@node F9EBDFCE-0 11530 40
//@node 4FB6133E-0 11810 40
//@node 886E7801-0 12090 40
//@node 941F4488-0 12370 40
//@node 088126A0-0 12650 40
//@node C3D382B4-0 12930 40
//@node 928EF17C-0 13210 40
//@node DB8ECE3D-0 13490 40
//@node E1979B8D-0 13770 40
//@node 1032C3C7-0 14050 40
//@node C40AEFDA-0 14330 40
//@node 54B4BB1A-0 14610 40
//@node B2C79F0B-0 14890 40
//@node 6A9D3334-0 15170 40
//@node B3FB8E78-0 15450 40
//@node 21558AA6-0 15730 40
//@node 2485CFB0-0 16010 40
//@node FABFFA36-0 16290 40
//@node 55530E84-0 16570 40
//@node DF53ADFE-0 16850 40
//@node 366FFE08-0 17130 40
//@node 6FBA6E48-0 17410 40
//@node C5832BAE-0 17690 40
//@node 7ADD1764-0 17970 40
//@node 1CAE1726-0 18250 40
//@node 31C1DEA8-0 18530 40
//@node 5463398E-0 18810 40
//@node D44ED166-0 19090 40
//@node A6A796C4-0 19370 40
//@node A3915F1E-0 19650 40
//@node DA84F4A8-0 19930 40
//@node 98513FB6-0 20210 40
//@node 9554D19C-0 20490 40
//@node BE0ED764-0 20770 40
//@node 1A97E94E-0 21050 40
//@node 5249D350-0 21330 40
//@node DD620AAE-0 21610 40
//@node A083D8B4-0 21890 40
//@node 4703850E-0 22170 40
//@node B53084F3-0 22450 40
//@node 8B90D1E9-0 22730 40
//@node EBAC3D71-0 23010 40
//@node 49FE60D0-0 23290 40
//@node 8DFB90C3-0 23570 40
//@node D6CB0D1A-0 23850 40
//@node 9B3B7E45-0 24130 40
//@node 98247CEE-0 24410 40
//@node 71A1C1EB-0 24690 40
//@node 1B41D594-0 24970 40
//@node FD46B9E9-0 25250 40
//@node D5103CD6-0 25530 40
//@node 36912A29-0 25810 40
//@node 7E35E4AE-0 26090 40
//@node 57D13F9B-0 26370 40
//@node EA1761BF-0 26650 40
//@node 42038525-0 26930 40
//@node 4A2170E3-0 27210 40
//@node B0891173-0 27490 40
//@node F0778B4F-0 27770 40
//@node F8989A89-0 28050 40
//@node F7037708-0 28330 40
//@node E7EE81FB-0 28610 40
//@node EE116361-0 28890 40
//@node 6829CBB3-0 29170 40
//@node 88E03853-0 29450 40
//@node EC900685-0 29730 40
//@node F7E2A638-0 30010 40
//@node 371CA78B-0 30290 40
//@node D019C097-0 30570 40
//@node A15BB089-0 30850 40
//@node F20DA249-0 31130 40
//@node 2B8CD643-0 31410 40
//@node 37B21547-0 31690 40
//@node 5C2B8D7D-0 31970 40
//@node B1A3CD72-0 32250 40
//@node 85354525-0 32530 40
//@node 9CF663F0-0 32810 40
//@node AE2331BB-0 33090 40
//@node F8C7C76D-0 33370 40
//@node 98324311-0 33650 40
//@node B378851E-0 33930 40
//@node 6FB01E9B-0 34210 40
//@node 611518D1-0 34490 40
//@node 670AE2B5-0 34770 40
//@node EF1C24D4-0 35050 40
//@node 4703850E-1 35330 40
//@node 405202F0-1 35610 40
//@node F9D5D7BE-0 40 40
//@node 4645B8DD-0 330 40
//@node AD4CB30A-0 125 145
//@node 9083B0E4-0 610 200
//@node F9DB0433-0 890 200
//@node 57AA1EA5-0 1170 200
//@node 63A02D06-0 1450 200
//@node 62C85D06-0 1730 200
//@node 5AE1CB85-0 2010 200
//@node 9083B0E4-1 2290 200
//@node F9DB0433-1 2570 200
//@node 57AA1EA5-1 2850 200
//@node 63A02D06-1 3130 200
//@node 62C85D06-1 3410 200
//@node 660009E6-0 3690 200
//@node FD536087-0 40 40
//@node 05E7C592-0 330 40
//@node 657B957D-0 40 40
//@node 7F6EF4AC-0 330 40
//@node 4F5EC441-0 610 40
//@node 50EEA49E-0 890 40
//@node 08D6F0C0-0 1170 40
//@node B1C61E82-0 1450 40
//@node 7D1A181F-0 1730 40
//@node FC538FBA-0 2010 40
//@node 963F43FE-0 2290 40
//@node DAC4E48D-0 2570 40
//@node 8B21059D-0 2850 40
//@node 8BCCC5AF-0 3130 40
//@node C44A49BC-0 3410 40
//@node 29FA6161-0 3690 40
//@node 288D57EB-0 3970 40
//@node B220C5A2-0 40 40
//@node 6DCBB3C7-0 330 40
//@node 3D0966D4-0 610 40
//@node 22FA3A00-0 890 40
//@node 4F36EEC5-0 1170 40
//@node CCB85FEF-0 1450 40
//@node 62F262A3-0 1730 40
//@node 9338C7E7-0 2010 40
//@node E38F9DA0-0 2290 40
//@node F62A256F-0 2570 40
//@node 904A3D9E-0 2850 40
//@node 82C20123-0 3130 40
//@node 0B776B4A-0 3410 40
//@node 6DB48903-0 3690 40
//@node D3BC7A3F-0 3970 40
//@node A2510B47-0 4250 40
//@node 88E3CF23-0 4530 40
//@node 61386406-0 4810 40
//@node 36E8CEE3-0 5090 40
//@node 0B72E567-0 5370 40
//@node 5E4AE79D-0 5650 40
//@node 8C168F09-0 5930 40
//@node FEAF5474-0 6210 40
//@node 1EF5A088-0 6490 40
//@node 014863D0-0 6770 40
//@node 1E7EF2F4-0 7050 40
//@node 08344654-0 7330 40
//@node 5E3C1E60-0 7610 40
//@node 2CD0AF68-0 7890 40
//@node 24A0C0F4-0 8170 40
//@node D2A5C0B4-0 8450 40
//@node 972FBE08-0 8730 40
//@node A7ABA7EA-0 9010 40
//@node 96C097B0-0 9290 40
//@node 555F51E6-0 40 40
//@node CB8CCAC7-0 330 40
//@node 1174F757-0 610 40
//@node C40016DB-0 890 40
//@node C226FD0C-0 1170 40
//@node 481C6CE3-0 1450 40
//@node 36567ADA-0 1730 40
//@node 2B6E74D7-0 2010 40
//@node 4EFAD21E-0 2290 40
//@node F2EFC317-0 2570 40
//@node 0F905BE3-0 2850 40
//@node 3E82DA2B-0 3130 40
//@node 3830E797-0 3410 40
//@node AAEF7E52-0 3690 40
//@node 13C870B7-0 3970 40
//@node BE4E8EFB-0 4250 40
//@node 2CEEF5C1-0 4530 40
//@node E92D3EAD-0 4810 40
//@node FEFF0A7A-0 5090 40
//@node 31B202EE-0 5370 40
//@node 34E00CD6-0 5650 40
//@node 18F887FA-0 5930 40
//@node E079D63A-0 6210 40
//@node FC53FBD6-0 6490 40
//@node AC34C63E-0 6770 40
//@node 25BAFABA-0 7050 40
//@node 801618DA-0 7330 40
//@node 2AC3468E-0 7610 40
//@node A255B94C-0 7890 40
//@node 0CB570B8-0 8170 40
//@node 84338EA6-0 8450 40
//@node 1E1E6FAD-0 8730 40
//@node DEC20EC7-0 9010 40
//@node EEA8DCBD-0 9290 40
//@node 090EAA87-0 40 40
//@node CA8DCDEB-0 330 40
//@node 663F8BDE-0 610 40
//@node A72567C6-0 890 40
//@node AFA660F2-0 1170 40
//@node 074D50CC-0 1450 40
//@node C3237DEA-0 1730 40
//@node B82026C1-0 2010 40
//@node 2B747B81-0 40 40
//@node 1B0D234D-0 330 40
//@node 2B0B8A21-0 610 40
//@node FE407981-0 890 40
//@node 07FE77E7-0 1170 40
//@node 952C8F24-0 40 40
//@node 9326F1B7-0 330 40
//@node CC785DBD-0 610 40
//@node 759BA6DA-0 890 40
//@node 09705E77-0 1170 40
//@node 9DA9FBE8-0 1450 40
//@node FD337975-0 1730 40
//@node 6B898407-0 2010 40
//@node 2DDD5B38-0 40 40
//@node 5ED0D6F8-0 330 40
//@node 15363EB6-0 610 40
//@node 1D167000-0 890 40
//@node 1B8BE1DB-0 1170 40
//@node 9F082F37-0 40 40
//@node AC047176-0 330 40
//@node FAA61E5F-0 610 40
//@node C76B6F76-0 890 40
//@node A9696992-0 1170 40
//@node A1369B16-0 1450 40
//@node 2E6E7D89-0 1730 40
//@node 1EBE7395-0 2010 40
//@node 5FC35294-0 2290 40
//@node EA13144C-0 2570 40
//@node F1BF449C-0 2850 40
//@node 6797C1A8-0 3130 40
//@node 8A097500-0 3410 40
//@node 5FC35294-1 3690 40
//@node A9696992-1 3970 40
//@node A1369B16-1 4250 40
//@node 5803B4EF-0 4530 40
//@node 5FC35294-2 4810 40
//@node 92DF4597-0 5090 40
//@node 9BD056BA-0 5370 40
//@node 34BBBB12-0 5650 40
//@node 91521781-0 5930 40
//@node B69609FC-0 6210 40
//@node FE07666B-0 6490 40
//@node 5FC35294-3 6770 40
//@node BA9AC308-0 7050 40
//@node F326B873-0 7330 40
//@node 5FC35294-4 7610 40
//@node 0AFBAB54-0 7890 40
//@node 5FC35294-5 8170 40
//@node B14830CE-0 8450 40
//@node C76B6F76-1 8730 40
//@node 2436AAEB-0 9010 40
//@node 5803B4EF-1 9290 40
//@node 88F71A39-0 40 40
//@node DC50EF92-0 330 40
//@node E14967D9-0 610 40
//@node 5C7801E1-0 890 40
//@node C25F5ABF-0 1170 40
//@node D6751993-0 1450 40
//@node 662A411C-0 1730 40
//@node 2A974D18-0 2010 40
//@node D84B45FC-0 2290 40
//@node 404D8621-0 2570 40
//@node 78F7303A-0 2850 40
//@node EB6C1AAC-0 3130 40
//@node 2049604B-0 3410 40
//@node 172F9DA0-0 3690 40
//@node A4E8858A-0 40 40
//@node 47CB1316-0 330 40
//@node 5059EB99-0 610 40
//@node 511EE210-0 890 40
//@node 2FD0D8F3-0 1170 40
//@node BB9DBFDF-0 1450 40
//@node 04A05ED9-0 1730 40
//@node A80C1122-0 2010 40
//@node 75E693CB-0 2290 40
//@node 30C0C92F-0 2570 40
//@node 0CFFD489-0 2850 40
//@node 85F71580-0 40 40
//@node A1416368-0 330 40
//@node 3A9E23B3-0 610 40
//@node BB33211A-0 890 40
//@node 3A3F3745-0 1170 40
//@node ECB773CC-0 1450 40
//@node C0C52EC7-0 1730 40
//@node 9A532733-0 2010 40
//@node B7F708EA-0 2290 40
//@node 2F9C7F93-0 2570 40
//@node E65D2325-0 2850 40
//@node C13EB24F-0 3130 40
//@node D0E5AC6A-0 3410 40
//@node 86F71713-0 40 40
//@node 62FCCF16-0 330 40
//@node AC0FC25D-0 610 40
//@node 52BE464C-0 890 40
//@node B1400941-0 1170 40
//@node 1AEB16E9-0 40 40
//@node 823EFACA-0 330 40
//@node 50ADB1D1-0 610 40
//@node F76F75FA-0 890 40
//@node 157CCD6B-0 1170 40
//@node BF021A9C-0 1450 40
//@node 40D2077F-0 1730 40
//@node 0FD6B162-0 2010 40
//@node 27339474-0 2290 40
//@node C8E2F6AD-0 2570 40
//@node B6462543-0 2850 40
//@node D68DE795-0 3130 40
//@node BF021A9C-1 3410 40
//@node FAFC40CA-0 3690 40
//@node BF021A9C-2 3970 40
//@node DE7852F2-0 4250 40
//@node 87C121C8-0 4530 40
//@node 50ADB1D1-1 4810 40
//@node 794FBC3D-0 5090 40
//@node E8342994-0 5370 40
//@node BF021A9C-3 5650 40
//@node 79C287FC-0 40 40
//@node E13625A9-0 330 40
//@node 45DE94F5-0 125 145
//@node 0EFA29B9-0 610 200
//@node 09E670B0-0 890 200
//@node AA6E07B1-0 1170 200
//@node D4426D8A-0 1450 200
//@node 3D9E51F7-0 1730 200
//@node 1C5A7C0E-0 2010 200
//@node A2CE8C59-0 2290 200
//@node 948977B5-0 2570 200
//@node 8879A34A-0 2850 200
//@node 9EBAF2EC-0 3130 200
//@node 11E95B50-0 3410 200
//@node 3D9E51F7-1 3690 200
//@node 29C24B03-0 3970 200
//@node 3D9E51F7-2 4250 200
//@node D1353744-0 4530 200
//@node 677252F1-0 4810 200
//@node 09E670B0-1 5090 200
//@node D75EF260-0 5370 200
//@node 1996D601-0 5650 200
//@node 3D9E51F7-3 5930 200
//@node 762D7451-0 6210 200
//@node F7BDF264-0 40 40
//@node 79ED0FA4-0 330 40
//@node D18139A1-0 610 40
//@node E3275EBF-0 890 40
//@node 6A3819FF-0 1170 40
//@node 68E397EC-0 1450 40
//@node 6A3819FF-1 1730 40
//@node 0A00E2A9-0 2010 40
//@node F8D2EA41-0 2290 40
//@node 79ED0FA4-1 2570 40
//@node D8B037C6-0 40 40
//@node 78888856-0 330 40
//@node D48F0741-0 610 40
//@node DA6ED0E8-0 40 40
//@node 8271BA59-0 330 40
//@node DD6ED5A1-0 40 40
//@node B0CDC048-0 330 40
//@node 909EECD2-0 610 40
//@node D2F07D7F-0 890 40
//@node 6BFF1229-0 1170 40
//@node EB3F3E19-0 1450 40
//@node DC6ED40E-0 40 40
//@node D99A232D-0 330 40
//@node DE6ED734-0 40 40
//@node FFE6BB01-0 330 40
//@node E16EDBED-0 40 40
//@node 0DC68C03-0 330 40
//@node B832CE32-0 40 40
//@node B0309900-0 330 40
//@node 4717BD8C-0 610 40
//@node 461C6BDF-0 890 40
//@node C02E8C32-0 1170 40
//@node 56C1054D-0 1450 40
//@node A7522AE0-0 1730 40
//@node 59B9ADE2-0 2010 40
//@node 00397969-0 2290 40
//@node F83C7AB2-0 2570 40
//@node 5EA9E076-0 2850 40
//@node 3128B4B9-0 3130 40
//@node A648A8BA-0 3410 40
//@node AA18A783-0 3690 40
//@node 78146F3B-0 3970 40
//@node 85CDDF65-0 4250 40
//@node FCA554D6-0 4530 40
//@node 858A6839-0 40 40
//@node 6020CF71-0 330 40
//@node 5C461C96-0 610 40
//@node 5031D10B-0 890 40
//@node 41560A70-0 1170 40
//@node FA04504D-0 1450 40
//@node F5B56952-0 1730 40
//@node 43D281C7-0 2010 40
//@node 892A9A4C-0 2290 40
//@node FAE2FC69-0 2570 40
//@node A798187D-0 2850 40
//@node EC023320-0 3130 40
//@node C5A986B7-0 3410 40
//@node D747254C-0 40 40
//@node 95093224-0 330 40
//@node AFDF671D-0 610 40
//@node 3036DBE6-0 890 40
//@node 43BF6127-0 1170 40
//@node 7036DB50-0 1450 40
//@node D922EBC9-0 1730 40
//@node 18BF55A2-0 2010 40
//@node DE82F623-0 2290 40
//@node D412DECC-0 2570 40
//@node 1E507F8E-0 2850 40
//@node 63D73605-0 3130 40
//@node D2EEEA8C-0 3410 40
//@node 798774BF-0 40 40
//@node BC674F3F-0 330 40
//@node 2952C822-0 610 40
//@node 8D6EC6E1-0 890 40
//@node 025A4C5C-0 1170 40
//@node 67DA8F0B-0 1450 40
//@node D44F469E-0 1730 40
//@node C931083D-0 2010 40
//@node 2E9335D8-0 2290 40
//@node 2374F777-0 2570 40
//@node 66E5AC81-0 2850 40
//@node 818D42C2-0 3130 40
//@node 94A1005F-0 3410 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 67C3ED48-0 610 40
//@node ECF6B0EC-0 890 40
//@node 00931DF1-0 1170 40
//@node D8610FF1-0 1450 40
//@doomscript-blueprint end
