namespace map_delta3 
{
	
	// Sound precache stuff for script calls.
	
	void precache() {
		//sys.cacheSoundShader ("m5_start");
		//sys.cacheSoundShader ("m5_loop");
		//sys.cacheSoundShader ("m5_stop");
		sys.cacheSoundShader ("dc3_gui_panel_1");
		sys.cacheSoundShader ("dc3_gui_panel_2");
	}


	void bind_objects()
	{
		$mister1.bind ($mister1_anchor);
		$mister2.bind ($mister2_anchor);
		$mister3.bind ($mister3_anchor);
		$mister4.bind ($mister4_anchor);
		$mister5.bind ($mister5_anchor);
		$mister6.bind ($mister6_anchor);
/*
		$mister1_anchor.accelTime (0.25);
		$mister1_anchor.decelTime (0.25);
		$mister2_anchor.accelTime (0.25);
		$mister2_anchor.decelTime (0.25);
		$mister3_anchor.accelTime (0.25);
		$mister3_anchor.decelTime (0.25);
		$mister4_anchor.accelTime (0.25);
		$mister4_anchor.decelTime (0.25);
		$mister5_anchor.accelTime (0.25);
		$mister5_anchor.decelTime (0.25);
		$mister6_anchor.accelTime (0.25);
		$mister6_anchor.decelTime (0.25);
*/
	}


	void init_world()
	{
		float	i;
		entity	ent1, ent2;

		for ( i = 1; i <= 9; i++ )
		{
			ent1 = sys.getEntity ("lred_0" + i);
			ent1.Off();
		}

		for ( i = 1; i <= 6; i++ )
		{
			ent1 = sys.getEntity ("lleft_0" + i);
			ent2 = sys.getEntity ("lright_0" + i);
			ent1.Off();
			ent2.Off();
		}
		
		$teleporter1_controlpanel_gui.hide();
		$teleporter2_controlpanel_gui.hide();
		
		$teleport1_controlpanelarms.time (1.0);
		$teleport1_controlpanelarms.accelTime (.5 );
		$teleport1_controlpanelarms.decelTime (.5 );
		$teleport1_controlpanel.time (.75);
		$teleport1_controlpanel.accelTime (.25 );
		$teleport1_controlpanel.decelTime (.5 );
		$teleport1_shoulder.time (2.0);
		$teleport1_shoulder.accelTime (1.0 );
		$teleport1_shoulder.decelTime (1.0 );
		$teleport1_arm1.time (2.0);
		$teleport1_arm1.accelTime (1.25 );
		$teleport1_arm1.decelTime (.75 );
		$teleport1_arm2.time (2.0);
		$teleport1_arm2.accelTime (1.25 );
		$teleport1_arm2.decelTime (.75 );

		$teleport2_controlpanelarms.time (1.0);
		$teleport2_controlpanelarms.accelTime (.5 );
		$teleport2_controlpanelarms.decelTime (.5 );
		$teleport2_controlpanel.time (.75);
		$teleport2_controlpanel.accelTime (.25 );
		$teleport2_controlpanel.decelTime (.5 );
		$teleport2_shoulder.time (2.0);
		$teleport2_shoulder.accelTime (1.0 );
		$teleport2_shoulder.decelTime (1.0 );
		$teleport2_arm1.time (2.0);
		$teleport2_arm1.accelTime (1.25 );
		$teleport2_arm1.decelTime (.75 );
		$teleport2_arm2.time (2.0);
		$teleport2_arm2.accelTime (1.25 );
		$teleport2_arm2.decelTime (.75 );
		
		$teleport3_controlpanelarms.time (1.0);
		$teleport3_controlpanelarms.accelTime (.5 );
		$teleport3_controlpanelarms.decelTime (.5 );
		$teleport3_controlpanel.time (.75);
		$teleport3_controlpanel.accelTime (.25 );
		$teleport3_controlpanel.decelTime (.5 );
		$teleport3_shoulder.time (2.0);
		$teleport3_shoulder.accelTime (1.0 );
		$teleport3_shoulder.decelTime (1.0 );
		$teleport3_arm1.time (2.0);
		$teleport3_arm1.accelTime (1.25 );
		$teleport3_arm1.decelTime (.75 );
		$teleport3_arm2.time (2.0);
		$teleport3_arm2.accelTime (1.25 );
		$teleport3_arm2.decelTime (.75 );

	}
	
	//*************************
	// Teleporter 1
	//*************************
	void teleport1_machine_ready()
	{
		sys.wait (.5);
		//trigger tp sounds
		sys.trigger ($teleport1_machine_poweron);
		sys.trigger ($teleport1_machine_idle_delay);
		//turn on electrical lightning effect
		sys.trigger ($teleport1_lightningfx);
		sys.wait (1.95);
		$teleport1_shoulder.rotateOnce ('0 0 -35');
		//trigger sound for arms
		sys.trigger ($teleport1_shoulder_operate);
		sys.wait(.75);
		$teleport1_arm1.rotateOnce ('0 -30 0');
		$teleport1_arm2.rotateOnce ('0 30 0');
		sys.waitFor ($teleport1_arm2);
		sys.wait (.5);
		sys.trigger ($select_speaker);
		$klaxxon_speaker1.setKey ("klaxxon1_status", "0");
	}
		
	void teleport1_klaxxon_on()
	{
		if ($klaxxon_speaker1.getFloatKey ("klaxxon1_status") == 0) 
		{
			sys.wait (.25);
			$klaxxon1_light1.setColor(0.77,0.49,0.00);
			$klaxxon1_light2.setColor(0.77,0.49,0.00);
			$klaxxon1_light_base.setColor(0.77,0.49,0.00);
			$klaxxon1_light_base.rotate ('0 360 0');
			sys.wait ( .5 );
			sys.trigger ($klaxxon_speaker1);
			$klaxxon_speaker1.setKey ("klaxxon1_status", "1");
			
			//trigger sounds for fx
			sys.trigger ($t1_teleporterfx_startup);
			sys.wait ( 1.5 );
			sys.trigger ($t1_teleporterfx_loop);
			
			//turn on blinking blue tp light
			sys.trigger ($teleport1_blightblink);
			sys.wait (.25 );
			//turn on floor and arm fx
			sys.trigger ($teleport1_arm1_fx);
			sys.trigger ($teleport1_arm2_fx);
			sys.wait ( .5 );
			sys.trigger ($teleport1_warpfx);
			sys.trigger ($teleport1_floorfx);
		}
	}
	
	void teleport1_klaxxon_off()
	{
		if ($klaxxon_speaker1.getFloatKey ("klaxxon1_status") == 1) 
		{
			//reset teleport trigger
			$teleport_trigger1.setGuiParm ( "gui_parm1" , 0);
			//turn off blinking blue tp light
			sys.trigger ($teleport1_blightblink);
			
			//trigger off loop sound for fx
			sys.trigger ($t1_teleporterfx_loop);
			
			//turn off floor and arm fx
			sys.trigger ($teleport1_arm1_fx);
			sys.trigger ($teleport1_arm2_fx);
			sys.trigger ($teleport1_warpfx);
			sys.trigger ($teleport1_floorfx);
			//turn of klaxxon speaker
			sys.trigger ($klaxxon_speaker1);
			//fade klaxxon light off; player can see it winding down after tp
			thread crossFadeEnt ($klaxxon1_light1, $klaxxon1_light1.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon1_light2, $klaxxon1_light2.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon1_light_base, $klaxxon1_light_base.getColor(), '0 0 0', 6.0);
			sys.wait ( 6 );
			//stop klaxxon rotation
			$klaxxon1_light_base.rotate ('0 0 0');
			//reset klaxxon1 light and speaker
			$klaxxon_speaker1.setKey ("klaxxon1_status", "0");
			//trigger gui to make useable after teleportation
			sys.trigger ($teleporter1_controlpanel_gui);
		}
	}
	
	// NOTE: All teleport destinations work via a specifically named trigger_relay entity in the gui
	void teleport1_destination1()
	{
		sys.wait (.25);
		sys.trigger ($pad1select_speaker);
		
		thread crossFadeEnt ($destination1_floorlight1, $destination1_floorlight1.getColor(), '1 1 1', 2.0);
		thread crossFadeEnt ($destination1_floorlight2, $destination1_floorlight2.getColor(), '1 1 1', 2.0);
		sys.trigger ($dest1_fadein_1);
		sys.trigger($dest1_redlight_on);
		
		// turn off pad 2
		$teleport1_pad2_rotate.rotateOnce ('0 0 0');
		thread crossFadeEnt ($teleport1_pad1_light1a, $teleport1_pad1_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light1b, $teleport1_pad1_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light2a, $teleport1_pad1_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light2b, $teleport1_pad1_light2b.getColor(), '0 0 0', 2.0);
		
		//$destination2_redlight_base.rotateOnce ('0 0 0');
		//$destination2_redlight_flare.setColor (0,0,0);
		//$destination2_redlight.setColor (0,0,0);
	}
	
	void teleport1_destination2()
	{
		sys.wait (.25);
		sys.trigger ($pad2select_speaker);
		$teleport1_pad2_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport1_pad1_light1a, $teleport1_pad1_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light1b, $teleport1_pad1_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light2a, $teleport1_pad1_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport1_pad1_light2b, $teleport1_pad1_light2b.getColor(), '1 0 0', 2.0);
		
		//$destination2_redlight_base.rotate ('0 360 0');
		//$destination2_redlight_flare.setColor (1,0,0);
		//$destination2_redlight.setColor (1,0,0);
		
		// turn off pad 1
		sys.trigger($dest1_redlight_off);
		sys.trigger ($dest1_fadeout_1);
		thread crossFadeEnt ($destination1_floorlight1, $destination1_floorlight1.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($destination1_floorlight2, $destination1_floorlight2.getColor(), '0 0 0', 2.0);
		
	}
	
	//*************************
	// Teleporter 2
	//*************************
	void teleport2_machine_ready()
	{
		sys.wait (.25);
		sys.trigger ($teleport2_machine_poweron);
		sys.trigger ($teleport2_machine_idle_delay);
		//turn on electrical lightning effect
		sys.trigger ($teleport2_lightningfx);
		sys.wait (1.95);
		$teleport2_shoulder.rotateOnce ('0 0 -35');
		//trigger sound for arms
		sys.trigger($teleport2_shoulder_operate);
		sys.wait(.75);
		$teleport2_arm1.rotateOnce ('0 -30 0');
		$teleport2_arm2.rotateOnce ('0 30 0');
		sys.waitFor ($teleport2_arm2);
		sys.wait (.5);
		sys.trigger ($select_speaker2);
		$klaxxon_speaker2.setKey ("klaxxon2_status", "0");
	}
	
	void teleport2_klaxxon_on()
	{
		if ($klaxxon_speaker2.getFloatKey ("klaxxon2_status") == 0) 
		{
			sys.wait (.25);
			$klaxxon2_light1.setColor(0.77,0.49,0.00);
			$klaxxon2_light2.setColor(0.77,0.49,0.00);
			$klaxxon2_light_base.setColor(0.77,0.49,0.00);
			$klaxxon2_light_base.rotate ('0 360 0');
			sys.wait ( .5 );
			sys.trigger ($klaxxon_speaker2);
			$klaxxon_speaker2.setKey ("klaxxon2_status", "1");
			
			//trigger sounds for fx
			sys.trigger ($t2_teleporterfx_startup);
			sys.wait ( 1.5 );
			sys.trigger ($t2_teleporterfx_loop);
			
			//turn on blinking blue tp light
			sys.trigger ($teleport2_blightblink);
			sys.wait ( .25 );
			//turn on floor and arm fx
			sys.trigger ($teleport2_arm1_fx);
			sys.trigger ($teleport2_arm2_fx);
			sys.wait ( .5 );
			sys.trigger ($teleport2_warpfx);
			sys.trigger ($teleport2_floorfx);
		}
	}
	
	void teleport2_klaxxon_off()
	{
		if ($klaxxon_speaker2.getFloatKey ("klaxxon2_status") == 1) 
		{
			//reset teleport trigger
			$teleport_trigger2.setGuiParm ( "gui_parm1" , 0);
			//turn off blinking blue tp light
			sys.trigger ($teleport2_blightblink);
			
			//trigger off loop sound for fx
			sys.trigger ($t2_teleporterfx_loop);
			
			//turn off floor and arm fx
			sys.trigger ($teleport2_arm1_fx);
			sys.trigger ($teleport2_arm2_fx);
			sys.trigger ($teleport2_warpfx);
			sys.trigger ($teleport2_floorfx);
			
			sys.trigger ($klaxxon_speaker2);
			//fade klaxxon off; player can see it winding down after tp
			thread crossFadeEnt ($klaxxon2_light1, $klaxxon2_light1.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon2_light2, $klaxxon2_light2.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon2_light_base, $klaxxon2_light_base.getColor(), '0 0 0', 6.0);
			sys.wait ( 6 );
			//stop klaxxon rotation
			$klaxxon2_light_base.rotate ('0 0 0');
			//reset klaxxon light and speaker
			$klaxxon_speaker2.setKey ("klaxxon2_status", "0");
			//trigger gui to make useable after teleportation
			sys.trigger ($teleporter2_controlpanel_gui);
		}
	}
	
	void teleport2_destination1()
	{
		sys.wait (.25);
		sys.trigger ($pad1select_speaker2);
		thread crossFadeEnt ($tp2_dest1_floorlight1, $tp2_dest1_floorlight1.getColor(), '1 1 1', 2.0);
		thread crossFadeEnt ($tp2_dest1_floorlight2, $tp2_dest1_floorlight2.getColor(), '1 1 1', 2.0);
		thread crossFadeEnt ($tp2_dest1_roomlight1, $tp2_dest1_roomlight1.getColor(), '1 1 1', 2.0);
		sys.trigger ($tp2_dest1_fadein_1);
		sys.trigger($tp2_dest1_redlight_on);
		//turn off ambient room light while main light is on; for performance
		thread crossFadeEnt ($tp2_dest1_roomlightambient, $tp2_dest1_roomlightambient.getColor(), '0 0 0', 2.0);
		
		// turn off pad 2
		$teleport2_pad2_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport2_pad2_light1a, $teleport2_pad2_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light1b, $teleport2_pad2_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2a, $teleport2_pad2_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2b, $teleport2_pad2_light2b.getColor(), '0 0 0', 2.0);
		
		// turn off pad 3
		$teleport2_pad3_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport2_pad3_light1a, $teleport2_pad3_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light1b, $teleport2_pad3_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2a, $teleport2_pad3_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2b, $teleport2_pad3_light2b.getColor(), '0 0 0', 2.0);
	}
	
	void teleport2_destination2()
	{
		sys.wait (.25);
		sys.trigger ($pad2select_speaker2);
		
		$teleport2_pad2_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport2_pad2_light1a, $teleport2_pad2_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light1b, $teleport2_pad2_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2a, $teleport2_pad2_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2b, $teleport2_pad2_light2b.getColor(), '1 0 0', 2.0);
		
		// turn off pad 3
		$teleport2_pad3_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport2_pad3_light1a, $teleport2_pad3_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light1b, $teleport2_pad3_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2a, $teleport2_pad3_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2b, $teleport2_pad3_light2b.getColor(), '0 0 0', 2.0);
		
		// turn off pad 1
		sys.trigger($tp2_dest1_redlight_off);
		sys.trigger ($tp2_dest1_fadeout_1);
		thread crossFadeEnt ($tp2_dest1_floorlight1, $tp2_dest1_floorlight1.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($tp2_dest1_floorlight2, $tp2_dest1_floorlight2.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($tp2_dest1_roomlight1, $tp2_dest1_roomlight1.getColor(), '0 0 0', 2.0);
		// turn on room ambient light
		thread crossFadeEnt ($tp2_dest1_roomlightambient, $tp2_dest1_roomlightambient.getColor(), '.39 .39 .39', 2.0);
	}
	
	void teleport2_destination3()
	{
		sys.wait (.25);
		sys.trigger ($pad3select_speaker2);
		
		$teleport2_pad3_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport2_pad3_light1a, $teleport2_pad3_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light1b, $teleport2_pad3_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2a, $teleport2_pad3_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad3_light2b, $teleport2_pad3_light2b.getColor(), '1 0 0', 2.0);
		
		// turn off pad 1
		sys.trigger($tp2_dest1_redlight_off);
		sys.trigger ($tp2_dest1_fadeout_1);
		thread crossFadeEnt ($tp2_dest1_floorlight1, $tp2_dest1_floorlight1.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($tp2_dest1_floorlight2, $tp2_dest1_floorlight2.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($tp2_dest1_roomlight1, $tp2_dest1_roomlight1.getColor(), '0 0 0', 2.0);
		// turn on room ambient light
		thread crossFadeEnt ($tp2_dest1_roomlightambient, $tp2_dest1_roomlightambient.getColor(), '.39 .39 .39', 2.0);
		
		// turn off pad 2
		$teleport2_pad2_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport2_pad2_light1a, $teleport2_pad2_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light1b, $teleport2_pad2_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2a, $teleport2_pad2_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport2_pad2_light2b, $teleport2_pad2_light2b.getColor(), '0 0 0', 2.0);
	}
	
	//*************************
	// Teleporter 3
	//*************************
	void teleport3_machine_ready()
	{
		sys.wait (.25);
		//trigger tp sounds
		sys.trigger ($teleport3_machine_poweron);
		sys.trigger ($teleport3_machine_idle_delay);
		//turn on electrical lightning effect
		sys.trigger ($teleport3_lightningfx);
		sys.wait (1.95);
		$teleport3_shoulder.rotateOnce ('0 0 -35');
		//trigger sound for arms
		sys.trigger($teleport3_shoulder_operate);
		sys.wait(.75);
		$teleport3_arm1.rotateOnce ('0 -30 0');
		$teleport3_arm2.rotateOnce ('0 30 0');
		sys.waitFor ($teleport3_arm2);
		sys.wait (.5);
		sys.trigger ($select_speaker3);
		$klaxxon_speaker3.setKey ("klaxxon3_status", "0");
	}
	
	void teleport3_klaxxon_on()
	{
		if ($klaxxon_speaker3.getFloatKey ("klaxxon3_status") == 0) 
		{
			sys.wait (.25);
			$klaxxon3_light1.setColor(0.77,0.49,0.00);
			$klaxxon3_light2.setColor(0.77,0.49,0.00);
			$klaxxon3_light_base.setColor(0.77,0.49,0.00);
			$klaxxon3_light_base.rotate ('0 360 0');
			sys.wait ( .5 );
			sys.trigger ($klaxxon_speaker3);
			$klaxxon_speaker3.setKey ("klaxxon3_status", "1");
			//turn on blinking blue tp light
			sys.trigger ($teleport3_blightblink);
			sys.wait ( .25 );
			
			//trigger sounds for fx
			sys.trigger ($t3_teleporterfx_startup);
			sys.wait ( 1.5 );
			sys.trigger ($t3_teleporterfx_loop);
			
			//turn on floor and arm fx
			sys.trigger ($teleport3_arm1_fx);
			sys.trigger ($teleport3_arm2_fx);
			sys.wait ( .5 );
			sys.trigger ($teleport3_warpfx);
			sys.trigger ($teleport3_floorfx);
		}
	}
	
	void teleport3_klaxxon_off()
	{
		if ($klaxxon_speaker3.getFloatKey ("klaxxon3_status") == 1) 
		{
			//reset teleport trigger
			$teleport_trigger3.setGuiParm ( "gui_parm1" , 0);
			
			//turn off blinking blue tp light
 			sys.trigger ($teleport3_blightblink);
			
			//trigger off loop sound for fx
			sys.trigger ($t3_teleporterfx_loop);
			
			//turn off floor and arm fx
			sys.trigger ($teleport3_arm1_fx);
			sys.trigger ($teleport3_arm2_fx);
			sys.trigger ($teleport3_warpfx);
			sys.trigger ($teleport3_floorfx);
			//turn off klaxxon speaker
			sys.trigger ($klaxxon_speaker3);
			//fade klaxxon off; player can see it winding down after tp
			thread crossFadeEnt ($klaxxon3_light1, $klaxxon3_light1.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon3_light2, $klaxxon3_light2.getColor(), '0 0 0', 6.0);
			thread crossFadeEnt ($klaxxon3_light_base, $klaxxon3_light_base.getColor(), '0 0 0', 6.0);
			sys.wait ( 6 );
			//stop klaxxon rotation
			$klaxxon3_light_base.rotate ('0 0 0');
			//reset klaxxon light and speaker
			$klaxxon_speaker3.setKey ("klaxxon3_status", "0");
			//trigger gui to make useable after teleportation
			sys.trigger ($teleporter3_controlpanel_gui);
		}
	}
	
	void betruger_teleport_init()
	{
		teleport3_machine_ready();
		teleport3_klaxxon_on();
	}
	
	void betruger_teleport()
	{	
		//trigger engulf warp fx and remove betruger
		sys.wait (.75);
		sys.trigger ($teleport3_blackholefx);
		sys.wait (.75);
		sys.trigger ($teleport_betrugar_out);
		sys.wait (.5);
		sys.trigger ($teleport3_blackholefx);
		sys.wait (.25);
	
		thread teleport3_klaxxon_off();
	}
	
	void teleport3_destination1()
	{
		sys.wait (.25);
		sys.trigger ($pad1select_speaker3);
		$teleport3_pad1_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport3_pad1_light1a, $teleport3_pad1_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light1b, $teleport3_pad1_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2a, $teleport3_pad1_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2b, $teleport3_pad1_light2b.getColor(), '1 0 0', 2.0);
		// turn off pad 2
		$teleport3_pad2_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad2_light1a, $teleport3_pad2_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light1b, $teleport3_pad2_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2a, $teleport3_pad2_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2b, $teleport3_pad2_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 3
		$teleport3_pad3_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad3_light1a, $teleport3_pad3_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light1b, $teleport3_pad3_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2a, $teleport3_pad3_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2b, $teleport3_pad3_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 4
		$teleport3_pad4_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad4_light1a, $teleport3_pad4_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light1b, $teleport3_pad4_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2a, $teleport3_pad4_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2b, $teleport3_pad4_light2b.getColor(), '0 0 0', 2.0);
	}
	
	void teleport3_destination2()
	{
		sys.wait (.25);
		sys.trigger ($pad2select_speaker3);
		$teleport3_pad2_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport3_pad2_light1a, $teleport3_pad2_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light1b, $teleport3_pad2_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2a, $teleport3_pad2_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2b, $teleport3_pad2_light2b.getColor(), '1 0 0', 2.0);
		// turn off pad 1
		$teleport3_pad1_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad1_light1a, $teleport3_pad1_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light1b, $teleport3_pad1_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2a, $teleport3_pad1_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2b, $teleport3_pad1_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 3
		$teleport3_pad3_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad3_light1a, $teleport3_pad3_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light1b, $teleport3_pad3_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2a, $teleport3_pad3_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2b, $teleport3_pad3_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 4
		$teleport3_pad4_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad4_light1a, $teleport3_pad4_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light1b, $teleport3_pad4_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2a, $teleport3_pad4_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2b, $teleport3_pad4_light2b.getColor(), '0 0 0', 2.0);
	}
	
	void teleport3_destination3()
	{
		sys.wait (.25);
		sys.trigger ($pad3select_speaker3);
		sys.trigger ($tele3_pad3_swapdoortrigger);
		$teleport3_pad3_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport3_pad3_light1a, $teleport3_pad3_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light1b, $teleport3_pad3_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2a, $teleport3_pad3_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2b, $teleport3_pad3_light2b.getColor(), '1 0 0', 2.0);
		// turn off pad 1
		$teleport3_pad1_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad1_light1a, $teleport3_pad1_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light1b, $teleport3_pad1_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2a, $teleport3_pad1_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2b, $teleport3_pad1_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 2
		$teleport3_pad2_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad2_light1a, $teleport3_pad2_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light1b, $teleport3_pad2_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2a, $teleport3_pad2_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2b, $teleport3_pad2_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 4
		$teleport3_pad4_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad4_light1a, $teleport3_pad4_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light1b, $teleport3_pad4_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2a, $teleport3_pad4_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2b, $teleport3_pad4_light2b.getColor(), '0 0 0', 2.0);
	}
	
	void teleport3_destination4()
	{
		sys.wait (.25);
		sys.trigger ($pad4select_speaker3);
		sys.trigger ($tele3_pad4_swapdoortrigger);
		$teleport3_pad4_rotate.rotate ('0 -320 0');
		thread crossFadeEnt ($teleport3_pad4_light1a, $teleport3_pad4_light1a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light1b, $teleport3_pad4_light1b.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2a, $teleport3_pad4_light2a.getColor(), '1 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad4_light2b, $teleport3_pad4_light2b.getColor(), '1 0 0', 2.0);
		// turn off pad 1
		$teleport3_pad1_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad1_light1a, $teleport3_pad1_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light1b, $teleport3_pad1_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2a, $teleport3_pad1_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad1_light2b, $teleport3_pad1_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 2
		$teleport3_pad2_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad2_light1a, $teleport3_pad2_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light1b, $teleport3_pad2_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2a, $teleport3_pad2_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad2_light2b, $teleport3_pad2_light2b.getColor(), '0 0 0', 2.0);
		// turn off pad 3
		$teleport3_pad3_rotate.rotate ('0 0 0');
		thread crossFadeEnt ($teleport3_pad3_light1a, $teleport3_pad3_light1a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light1b, $teleport3_pad3_light1b.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2a, $teleport3_pad3_light2a.getColor(), '0 0 0', 2.0);
		thread crossFadeEnt ($teleport3_pad3_light2b, $teleport3_pad3_light2b.getColor(), '0 0 0', 2.0);
	}
	
	//*********************
	// Teleport Control panels
	//*********************
	void teleport1_control_up()
	{
		$teleporter1_controlpanel_gui.show();
		$teleport1_controlpanelarms.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE );
		$teleporter1_controlpanel_gui.show();
		$teleport1_controlpanelarms.move (UP, 33);
		sys.waitFor ($teleport1_controlpanelarms);
		$teleport1_controlpanelarms.startSoundShader ("dc3_gui_panel_2", SND_CHANNEL_VOICE2 );
		$teleport1_controlpanel.rotateOnce ('-20 0 0');
		sys.waitFor ($teleport1_controlpanel);
	}
	
	void teleport2_control_up()
	{
		$teleporter2_controlpanel_gui.show();
		$teleporter2_controlpanel_gui.show();
		$teleport2_controlpanelarms.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE );
		$teleport2_controlpanelarms.move (UP, 33);
		sys.waitFor ($teleport2_controlpanelarms);
		$teleport2_controlpanelarms.startSoundShader ("dc3_gui_panel_2", SND_CHANNEL_VOICE2 );
		$teleport2_controlpanel.rotateOnce ('0 0 -20');
		sys.waitFor ($teleport2_controlpanel);
	}
	
	void teleport3_control_up()
	{
		//$teleport3_controlpanelarms.move (UP, 33);
		//sys.waitFor ($teleport3_controlpanelarms);
		//$teleport3_controlpanel.rotateOnce ('20 0 0');
		//sys.waitFor ($teleport3_controlpanel);
		sys.wait (.05);
	}
	
	//********************
	// Lock and unlock doors in area after second decon chamber
	//********************
	void lock_door1()
	{
		$func_door_214.close ();
		$func_door_214.lock (1);
		$func_static_2576.setShaderParm (7, 0);
		$func_door_216.lock (1);
		$func_static_2577.setShaderParm (7, 0);
	}
	
	void unlock_door1()
	{
		$func_door_214.lock (0);
		$func_static_2576.setShaderParm (7, 1);
		$func_door_216.lock (0);
		$func_static_2577.setShaderParm (7, 1);
	}
	
	void lock_door2()
	{
		$door_lock2_playerclip.show();
		$func_door_220.close ();
		$func_door_220.lock (1);
		$func_static_2604.setShaderParm (7, 0);
	}
	
	void unlock_door2()
	{
		$door_lock2_playerclip.remove();
		$func_door_220.lock (0);
		$func_static_2604.setShaderParm (7, 1);
		$func_static_2604.setColor (1.0,1.0,1.0);
		$light_1768.setColor (1.0,1.0,1.0);
		$light_1752.setColor (1.0,1.0,1.0);
	}

	//************************
	// Decon Chamber #1
	//************************
	void decon_cycle_door1()
	{
		//initiate decon chamber computer voice
		sys.trigger ($decon_initiate_speaker);
		$decondoor1.lock (0);
		$decondoorframe1.setShaderParm (7, 1);
		$decondoorframe2.setShaderParm (7, 1);
		$decondoorframe4.setShaderParm (7, 1);
		sys.trigger($decon1_setcolor_green);
		
		//reset decon chamber stuff
		$decondoor3.lock (0);
		$decondoorframe3.setShaderParm (7, 1);
		$decondoor2_trigger.enable();
		$decondoor4_trigger.enable();
	}
		
	void decon_cycle()
	{
		$decon_trigger1.enable ();
	}
	
	void mister_move ()
	{
		$decondoor1.lock (1);
		$decondoor2.lock (1);
		
		//start decon1 computer voice
		sys.trigger ($decon1_start_speaker);
		sys.wait (1.5);
		
		thread crossFadeEnt ($misterlight_white, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decontop_fade, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decon_toplight_red, '0 0 0', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1_light, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe2, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe2_light, '1 1 1', '1 0 0', 1.0);
		
		sys.trigger ($decon1_mister1start_spkr);
		sys.trigger ($decon1_mister2start_spkr);
		sys.wait (.15);
		sys.trigger ($decon1_mister1loop_spkr);
		sys.trigger ($decon1_mister2loop_spkr);
		
		$mister1_anchor.moveTo ($mister1_spot2);
		$mister2_anchor.moveTo ($mister2_spot2);
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.rotateOnce ('60 0 0');
		$mister2_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.rotateOnce ('-60 0 0');
		$mister2_anchor.rotateOnce ('60 0 0');
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.moveTo ($mister1_spot1);
		$mister2_anchor.moveTo ($mister2_spot1);
		sys.waitFor ($mister1_anchor);
		
		sys.trigger ($decon1_mister1stop_spkr);
		sys.trigger ($decon1_mister2stop_spkr);
		//trigger looping speaker again to turn off
		sys.trigger ($decon1_mister1loop_spkr);
		sys.trigger ($decon1_mister2loop_spkr);
		
		//turn off emitter
		sys.trigger($mister1_emitter);
		sys.trigger($mister2_emitter);
		
		sys.wait (.5);
		thread crossFadeEnt ($misterlight_white, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decontop_fade, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decon_toplight_red, '1 0 0', '0 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe1_light, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe2, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe2_light, '1 0 0', '1 1 1', 1.0);
	}

	void mister1()
	{
		$decondoor1.close ();
		$decondoor2.close ();
		$decon_trigger1.disable ();
		
		//turn on emitter
		sys.trigger($mister1_emitter);
		sys.trigger($mister2_emitter);
			
		$decondoorframe1.setShaderParm (7, 0);
		$decondoorframe2.setShaderParm (7, 0);
		float i;
			i = thread mister_move();
			sys.waitForThread (i);
		
		//complete decon1 computer voice
		sys.trigger ($decon1_complete_speaker);
		
		sys.wait (.25);
		$decondoorframe2.setShaderParm (7, 1);
		$decondoor2.lock (0);
		
		//turn off emitter
		//sys.trigger($mister1_emitter);
		//sys.trigger($mister2_emitter);
	}
	
	void decon_cycle_door2()
	{
		$decondoor2_trigger.disable();
		$decondoor2.close();
		$decondoor2.lock(1);
		$decondoorframe2.setShaderParm (7, 0);
		sys.trigger($decon1_setcolor_red);
		
		//reset decon chamber trigger
		sys.trigger ($func_static_2885);
	}
		
	//***********************
	// Decon Chamber #2 //2nd chamber - not actual chamber #
	//***********************
	void decon_cycle2 ()
	{
		$decon_trigger2.enable ();
	}
	
	void mister_move2()
	{
		$decondoor3.lock (1);
		$decondoor4.lock (1);
		
		//start decon2 computer voice
		sys.trigger ($decon2_start_speaker);
		sys.wait (1.5);
		
		thread crossFadeEnt ($misterlight_white2, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decontop_fade2, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decon_toplight_red2, '0 0 0', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe3, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe3_light, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe4, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe4_light, '1 1 1', '1 0 0', 1.0);
		
		sys.trigger ($decon2_mister3start_spkr);
		sys.trigger ($decon2_mister4start_spkr);
		sys.wait (.15);
		sys.trigger ($decon2_mister3loop_spkr);
		sys.trigger ($decon2_mister4loop_spkr);
		
		$mister3_anchor.moveTo ($mister3_spot2);
		$mister4_anchor.moveTo ($mister4_spot2);
		sys.waitFor ($mister4_anchor);
		
		$mister3_anchor.rotateOnce ('60 0 0');
		$mister4_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($mister4_anchor);
		
		$mister3_anchor.rotateOnce ('-60 0 0');
		$mister4_anchor.rotateOnce ('60 0 0');
		sys.waitFor ($mister4_anchor);
		
		$mister3_anchor.moveTo ($mister3_spot1);
		$mister4_anchor.moveTo ($mister4_spot1);
		sys.waitFor ($mister4_anchor);
		
		sys.trigger ($decon2_mister3stop_spkr);
		sys.trigger ($decon2_mister4stop_spkr);
		//trigger looping speaker again to turn off
		sys.trigger ($decon2_mister3loop_spkr);
		sys.trigger ($decon2_mister4loop_spkr);
		
		//turn off emitter
		sys.trigger($mister3_emitter);
		sys.trigger($mister4_emitter);
		
		sys.wait (.5);
		thread crossFadeEnt ($misterlight_white2, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decontop_fade2, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decon_toplight_red2, '1 0 0', '0 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe3, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe3_light, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe4, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe4_light, '1 0 0', '1 1 1', 1.0);
	}
	
	void mister2()
	{
		$decondoor3.close ();
		$decondoor4.close ();
		$decon_trigger2.disable ();
		
		//turn on emitter
		sys.trigger($mister3_emitter);
		sys.trigger($mister4_emitter);
		
		$decondoorframe3.setShaderParm (7, 0);
		$decondoorframe4.setShaderParm (7, 0);
		float i;
			i = thread mister_move2();
			sys.waitForThread (i);
		
		//complete decon2 computer voice
		sys.trigger ($decon2_complete_speaker);
		
		sys.wait (.25);
		$decondoorframe4.setShaderParm (7, 1);
		$decondoor4.lock (0);
	}
		
	void decon_cycle_door4()
	{
		$decondoor4.close();
		$decondoor4.lock (1);
		$decondoorframe4.setShaderParm (7, 0);
		$decondoor4_trigger.disable();
	}
		
	//***********************
	// Decon Chamber #3
	//***********************
	 
	void decon_cycle_door5()
	{
		//initiate decon chamber #3 computer voice
		sys.trigger ($decon_initiate_speaker3);
		$decondoor5.lock (0);
		$decondoorframe5.setShaderParm (7, 1);
	}
	
	void mister_move3()
	{
		//start decon1 computer voice
		$decon_trigger3.disable ();
		sys.trigger ($decon3_start_speaker);
		$decondoor5.lock (1);
		$decondoor6.lock (1);
		sys.wait (1.5);
		
		thread crossFadeEnt ($misterlight_white3, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decontop_fade3, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decon_toplight_red3, '0 0 0', '1 0 0', 1.0);
		
		thread crossFadeEnt ($decondoorframe5, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe5_light, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe6, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe6_light, '1 1 1', '1 0 0', 1.0);
		
		$mister5_anchor.time (1);
		$mister5_anchor.accelTime (.5 );
		$mister5_anchor.decelTime (.5);
		sys.trigger ($decon3_cycle_speaker);
		$mister5_anchor.moveTo ($mister5_spot1_broke);
		$mister6_anchor.moveTo ($mister6_spot1_broke);
		sys.waitFor ($mister6_anchor);
		sys.trigger($mister5_emitter);
		sys.trigger($mister6_emitter);
		sys.wait (1.5);
		sys.trigger ($decon3_malfunction_speaker);
		sys.wait (1.85);
		sys.trigger ($decon3_shutdown_speaker);
		sys.wait (1.75);
		sys.trigger ($decon3_backup_speaker);
/*
		$mister5_anchor.moveTo ($mister5_spot2);
		$mister6_anchor.moveTo ($mister6_spot2);
		sys.waitFor ($mister6_anchor);
		
		$mister5_anchor.rotateOnce ('-60 0 0');
		$mister6_anchor.rotateOnce ('60 0 0');
		sys.waitFor ($mister6_anchor);
		
		$mister5_anchor.rotateOnce ('60 0 0');
		$mister6_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($mister6_anchor);
		
		$mister5_anchor.moveTo ($mister5_spot1);
		$mister6_anchor.moveTo ($mister6_spot1);
		sys.waitFor ($mister6_anchor);
*/		
		sys.wait (1.5);
		
		thread crossFadeEnt ($misterlight_white3, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decontop_fade3, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decon_toplight_red3, '1 0 0', '0 0 0', 1.0);
		
		thread crossFadeEnt ($decondoorframe5, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe5_light, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe6, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe6_light, '1 0 0', '1 1 1', 1.0);
	}
	
	void mister3()
	{
		$decondoor5.close ();
		$decondoor6.close ();
		$decon_trigger3.disable ();
		$decondoorframe5.setShaderParm (7, 0);
		$decondoorframe6.setShaderParm (7, 0);
		float i;
			i = thread mister_move3();
			sys.waitForThread (i);
		
		// complete decon computer voice
		//sys.trigger ($decon3_complete_speaker);
		sys.wait (.5);
		$decondoorframe5.setShaderParm (7, 1);
		$decondoor5.lock (0);
		$decondoorframe6.setShaderParm (7, 1);
		$decondoor6.lock (0);
		//sys.trigger($mister5_emitter);
		//sys.trigger($mister6_emitter);
	}
	
	void decon_cycle_door6()
	{
		//$decondoor6.close();
		//$decondoor6.lock(1);
		//$decondoorframe6.setShaderParm (7, 0);
		//sys.trigger($decon3_setcolor_red);
		//thread decon_cycle3();							//trigger enabled; inside chamber
		$decondoor6_trigger.disable();
		sys.wait (3);
		sys.trigger ($decon3_maint_need_speaker);
	}

	void scroll_red_lights()
	{
		float	i;
		entity	ent;
		while (1)
		{
			for ( i = 1; i <= 9; i++ )
			{
				ent = sys.getEntity ("lred_0" + i);
				ent.On();
				sys.wait ( 0.10 );
				ent.Off();
				sys.wait ( 0.10 );
			}
		}
	}

	void scroll_blue_lights()
	{
		float	i;
		entity	ent1, ent2;
		while (1)
		{
			for ( i = 1; i <= 6; i++ )
			{
				ent1 = sys.getEntity ("lleft_0" + i);
				ent2 = sys.getEntity ("lright_0" + i);
				ent1.On();
				ent2.On();
				sys.wait ( 0.2 );
				ent1.Off();
				ent2.Off();
				sys.wait ( 0.2 );
			}
		}
	}
	
	void start_world()
	{
		thread scroll_red_lights();
		thread scroll_blue_lights();
		thread betruger_teleport_init();
	}
	
	void main()
	{
		precache();
		bind_objects();
		init_world();
		start_world();
	}
}

//@doomscript-blueprint begin 6
//@source 6462EC1F
//@catalog 0C260740
//@node 7849D8EC-0 40 40
//@node 6DA2FF28-0 330 40
//@node 7A63638B-0 610 40
//@node D27276D9-0 40 40
//@node 4416C660-0 330 40
//@node 400E7772-0 610 40
//@node 14FD7A88-0 890 40
//@node 3E309ADE-0 1170 40
//@node E5228528-0 1450 40
//@node 283FE9DA-0 1730 40
//@node 8846F578-0 40 40
//@node 5A4DEB95-0 610 40
//@node 37A596BD-0 125 145
//@node 2DF7ADFA-0 -80 145
//@node 6ABE9102-0 610 200
//@node B70E04F7-0 385 305
//@node 9FC2A98A-0 180 405
//@node 7D5F1EF8-0 -25 405
//@node 57A3EFCB-0 1170 200
//@node 0582867A-0 1450 40
//@node 0C862FFE-0 965 145
//@node 717B29D2-0 760 145
//@node C06B1FE4-0 1450 200
//@node A47D1972-0 1225 305
//@node D3B89C46-0 1020 405
//@node C0A0FB0A-0 815 405
//@node 7A2D15E8-0 1730 200
//@node 56B528DE-0 1505 305
//@node 1E1D3FA1-0 1300 405
//@node 06C3AC68-0 1095 405
//@node 57A3EFCB-1 2290 200
//@node 1DEBA814-0 2570 200
//@node A4796BED-0 2850 40
//@node 5BD3A94E-0 3130 40
//@node 4FE2751B-0 3410 40
//@node 1BE8D96F-0 3690 40
//@node 6B71F818-0 3970 40
//@node 9CECDE67-0 4250 40
//@node 68AABECE-0 4530 40
//@node 78BAA175-0 4810 40
//@node 2292E5E0-0 5090 40
//@node 1B8E18F1-0 5370 40
//@node 0E794AFC-0 5650 40
//@node 425D4F79-0 5930 40
//@node 7DA3BC67-0 6210 40
//@node 0A2B4570-0 6490 40
//@node B72DA4F8-0 6770 40
//@node 16EBA694-0 7050 40
//@node 192DC391-0 7330 40
//@node E96F0754-0 7610 40
//@node EA2CF316-0 7890 40
//@node 8EF8B6F5-0 8170 40
//@node 6419207C-0 8450 40
//@node EADFE409-0 8730 40
//@node 104EE670-0 9010 40
//@node 0062A7C3-0 9290 40
//@node 4CFFD8F6-0 9570 40
//@node D9E2209B-0 9850 40
//@node 96E0A3D2-0 10130 40
//@node B7749CEA-0 10410 40
//@node 28C710A7-0 10690 40
//@node 0F3397D7-0 10970 40
//@node 67133D01-0 11250 40
//@node DC4BC6A2-0 11530 40
//@node 853CE2ED-0 11810 40
//@node FFB0A975-0 12090 40
//@node C9858C4A-0 12370 40
//@node 1B84BF4D-0 12650 40
//@node C56CD59C-0 12930 40
//@node A123F83F-0 13210 40
//@node B121BB52-0 13490 40
//@node 2C7E8CEF-0 13770 40
//@node A8E8EB9E-0 14050 40
//@node 6F8E75AB-0 14330 40
//@node 25D53565-0 14610 40
//@node 4ED5B5B6-0 14890 40
//@node A08E2916-0 15170 40
//@node 7EFB955E-0 15450 40
//@node E509A90B-0 15730 40
//@node 7AD4E36F-0 40 40
//@node 78E01E82-0 330 40
//@node FC4C038D-0 610 40
//@node A4C86B25-0 890 40
//@node 7ACE0DE7-0 1170 40
//@node 74920F6E-0 1450 40
//@node 6A760F2F-0 1730 40
//@node E400C752-0 2010 40
//@node D5927EE9-0 2290 40
//@node 27E62BB7-0 2570 40
//@node BE6FE3AD-0 2850 40
//@node 158B18C5-0 3130 40
//@node 78E01E82-1 3410 40
//@node D018D8A8-0 3690 40
//@node E79632EF-0 3970 40
//@node F014E8C3-0 40 40
//@node 7CCAE86C-0 330 40
//@node 7A4A4DDC-0 125 145
//@node 8AA41CBA-0 610 200
//@node 213DAF65-0 890 200
//@node 771F5A98-0 1170 200
//@node CAC25DBA-0 1450 200
//@node EF7007C2-0 1730 200
//@node 524E8AC0-0 2010 200
//@node C114FE62-0 2290 200
//@node A6CDE822-0 2570 200
//@node D1AF4C3A-0 2850 200
//@node 7EF6F4FB-0 3130 200
//@node 4F2B0A53-0 3410 200
//@node 18BBBD9F-0 3690 200
//@node BB587C26-0 3970 200
//@node 861C1733-0 4250 200
//@node 39062EE8-0 4530 200
//@node 524E8AC0-1 4810 200
//@node 469BE2C9-0 5090 200
//@node D182AD9F-0 5370 200
//@node C5FE0F07-0 40 40
//@node FBBFD01D-0 330 40
//@node D464F3DA-0 125 145
//@node A04D1C38-0 610 200
//@node EC8B6903-0 890 200
//@node 53A5474F-0 1170 200
//@node FDB691E7-0 1450 200
//@node 18AA756C-0 1730 200
//@node 86FA886D-0 2010 200
//@node 49A59F23-0 2290 200
//@node A3FF756E-0 2570 200
//@node BE01F048-0 2850 200
//@node 5A087538-0 3130 200
//@node 1DD6FF08-0 3410 200
//@node 15B73B67-0 3690 200
//@node DE606EF3-0 3970 200
//@node 2AE3F643-0 4250 200
//@node AD74C503-0 4530 200
//@node BCE8E7F9-0 40 40
//@node 31E953BC-0 330 40
//@node 6046BB46-0 610 40
//@node C5932587-0 890 40
//@node CD1C4FC9-0 1170 40
//@node 29598ABD-0 1450 40
//@node 8B5AACAB-0 1730 40
//@node 6367968D-0 2010 40
//@node 5A85856A-0 2290 40
//@node 9257783C-0 2570 40
//@node 85B9EA7C-0 2850 40
//@node A6A2E7F6-0 3130 40
//@node B9E8E340-0 40 40
//@node 96B0B075-0 330 40
//@node FDFF29F4-0 610 40
//@node 10009137-0 890 40
//@node 9ED4F5DE-0 1170 40
//@node 892BD4E8-0 1450 40
//@node E4B6DB98-0 1730 40
//@node 64E0F7E2-0 2010 40
//@node 32A4B756-0 2290 40
//@node 9FCE4C4B-0 2570 40
//@node 1AD91433-0 2850 40
//@node 7C86B5DD-0 3130 40
//@node B4AA04F6-0 40 40
//@node 136BAE4B-0 330 40
//@node F35F5E91-0 610 40
//@node E7F4D371-0 890 40
//@node 492E329B-0 1170 40
//@node 80BEF45D-0 1450 40
//@node 2D960ED9-0 1730 40
//@node 7BAF2A0C-0 2010 40
//@node 949DEECA-0 2290 40
//@node 1B19F9B1-0 2570 40
//@node AED98537-0 2850 40
//@node 981D358D-0 3130 40
//@node A15E7C8D-0 3410 40
//@node A47D05AB-0 3690 40
//@node FA78C430-0 3970 40
//@node 608C2298-0 40 40
//@node EF262CBD-0 330 40
//@node 7DAAD47F-0 125 145
//@node 918E6855-0 610 200
//@node 3D6B69A3-0 890 200
//@node AD719172-0 1170 200
//@node 762336E4-0 1450 200
//@node 0644264C-0 1730 200
//@node AB1CDC65-0 2010 200
//@node 284D8CCE-0 2290 200
//@node 455E58EB-0 2570 200
//@node 8079BFD2-0 2850 200
//@node 8B0746EC-0 3130 200
//@node 426B962B-0 3410 200
//@node 46478E35-0 3690 200
//@node 17BD64B7-0 3970 200
//@node FB0E6D11-0 4250 200
//@node E1E82062-0 4530 200
//@node AB1CDC65-1 4810 200
//@node 0E8C7983-0 5090 200
//@node 581BA7DD-0 5370 200
//@node CA874292-0 40 40
//@node BB02A89E-0 330 40
//@node AFC875D1-0 125 145
//@node 4016C6EA-0 610 200
//@node EFBAA1A3-0 890 200
//@node 18760A6D-0 1170 200
//@node 8BFFC447-0 1450 200
//@node 7A96BFCC-0 1730 200
//@node 44958A0D-0 2010 200
//@node E05A37C3-0 2290 200
//@node 5FEF3084-0 2570 200
//@node 34022BC3-0 2850 200
//@node ED2A31E7-0 3130 200
//@node 13EC8DF7-0 3410 200
//@node 5B97A60A-0 3690 200
//@node 2BF2A8EB-0 3970 200
//@node 7C8C01D0-0 4250 200
//@node F0B5DF0F-0 4530 200
//@node AD9E5CD6-0 40 40
//@node A4992967-0 330 40
//@node E706999B-0 610 40
//@node 9274EA2C-0 890 40
//@node 69AD509C-0 1170 40
//@node 7AF23D82-0 1450 40
//@node 364F4C6F-0 1730 40
//@node 2EA43047-0 2010 40
//@node 987155D7-0 2290 40
//@node 939E295A-0 2570 40
//@node C7DC454B-0 2850 40
//@node 6CC01609-0 3130 40
//@node 8D9F2F31-0 3410 40
//@node 6B58D997-0 3690 40
//@node 1D4A1FE7-0 3970 40
//@node C7B27BB9-0 4250 40
//@node E2F972F7-0 4530 40
//@node DED0711F-0 4810 40
//@node CAD64BBD-0 5090 40
//@node AC9E5B43-0 40 40
//@node EF130EAA-0 330 40
//@node 6497A961-0 610 40
//@node D45432BB-0 890 40
//@node C1C000AB-0 1170 40
//@node D23627D1-0 1450 40
//@node F5EFF639-0 1730 40
//@node C3E0289F-0 2010 40
//@node 584354BC-0 2290 40
//@node 98AD9052-0 2570 40
//@node 55C3E278-0 2850 40
//@node B6E08548-0 3130 40
//@node 2FA86D46-0 3410 40
//@node 49852BCE-0 3690 40
//@node 8BF7BBC9-0 3970 40
//@node 2A43C0B8-0 4250 40
//@node 5DA5E1C8-0 4530 40
//@node CE2C127A-0 4810 40
//@node CE5EE64A-0 5090 40
//@node AB9E59B0-0 40 40
//@node 46B7EFA9-0 330 40
//@node 13871CF7-0 610 40
//@node C4F918A3-0 890 40
//@node 590AC1DC-0 1170 40
//@node A18EEB5A-0 1450 40
//@node F5C51382-0 1730 40
//@node 4B405A90-0 2010 40
//@node 02E1F2D1-0 2290 40
//@node 3370B1A2-0 2570 40
//@node 823AECBD-0 2850 40
//@node 25F5194D-0 3130 40
//@node 0A3DEEA3-0 3410 40
//@node C702A007-0 3690 40
//@node D29B4A64-0 3970 40
//@node 4DA14C79-0 4250 40
//@node D6557F9F-0 4530 40
//@node 91F14ABF-0 4810 40
//@node 5E4998DD-0 5090 40
//@node A6069A6D-0 40 40
//@node 7AB1E908-0 330 40
//@node A85001E5-0 610 40
//@node EC28A0CD-0 890 40
//@node EDFEC4AF-0 1170 40
//@node 745632E4-0 1450 40
//@node F79F5083-0 1730 40
//@node 0E922222-0 2010 40
//@node DE2CEA93-0 2290 40
//@node 0555B233-0 2570 40
//@node 15BFC789-0 2850 40
//@node 726F7A55-0 3130 40
//@node AC522EA8-0 3410 40
//@node 20C5857F-0 3690 40
//@node BCE9CF35-0 3970 40
//@node 67C68F45-0 40 40
//@node BE47BE92-0 330 40
//@node E3B59158-0 125 145
//@node 6BC7ED04-0 610 200
//@node F1E310F1-0 890 200
//@node C1502844-0 1170 200
//@node 97F82DC6-0 1450 200
//@node 9544336E-0 1730 200
//@node 50F84F12-0 2010 200
//@node C53077B2-0 2290 200
//@node 1123BF1C-0 2570 200
//@node FA0AD75B-0 2850 200
//@node 32D800B2-0 3130 200
//@node 99C60D4E-0 3410 200
//@node D4093EB9-0 3690 200
//@node 23C1398F-0 3970 200
//@node D86303FF-0 4250 200
//@node D2FE24C4-0 4530 200
//@node 50F84F12-1 4810 200
//@node 2C134995-0 5090 200
//@node A561B76B-0 5370 200
//@node B0A72761-0 40 40
//@node 9CBA5A6B-0 330 40
//@node 9F7E9DFA-0 125 145
//@node 58DAF970-0 610 200
//@node BDB1A037-0 890 200
//@node 7CC85633-0 1170 200
//@node C27E4AEB-0 1450 200
//@node B788F780-0 1730 200
//@node 59EC0891-0 2010 200
//@node F68970C7-0 2290 200
//@node DA959E76-0 2570 200
//@node 6F09D7EA-0 2850 200
//@node 8D400CBE-0 3130 200
//@node 3A198BA2-0 3410 200
//@node B16D37A5-0 3690 200
//@node 5694527F-0 3970 200
//@node 4DDE7BC5-0 4250 200
//@node 79C1B31F-0 4530 200
//@node 6836CDDC-0 40 40
//@node 2EF8B7A8-0 330 40
//@node 122A0576-0 610 40
//@node 0A60717D-0 40 40
//@node 6582AD2D-0 330 40
//@node D4D1635C-0 610 40
//@node 6582AD2D-1 890 40
//@node 6DF30F1F-0 1170 40
//@node 3D65510C-0 1450 40
//@node D4D1635C-1 1730 40
//@node 5C964364-0 2010 40
//@node C8D18399-0 2290 40
//@node 937F1CC3-0 40 40
//@node 0AA4F4E6-0 330 40
//@node 8189B689-0 610 40
//@node 04182A77-0 890 40
//@node 757FD17F-0 1170 40
//@node 49322811-0 1450 40
//@node F046B7D5-0 1730 40
//@node DD580F7F-0 2010 40
//@node 6FF4531E-0 2290 40
//@node 2B42C48E-0 2570 40
//@node F907E67C-0 2850 40
//@node 3CFCA864-0 3130 40
//@node E2BB5512-0 3410 40
//@node 82CBC3CB-0 3690 40
//@node 488F9700-0 3970 40
//@node 4DA4F996-0 4250 40
//@node 7698A15E-0 4530 40
//@node 74FF662C-0 4810 40
//@node F7C78054-0 5090 40
//@node A541DFEE-0 5370 40
//@node B3511BB0-0 5650 40
//@node 37F795EC-0 5930 40
//@node A6ED14E6-0 6210 40
//@node 947F1E56-0 40 40
//@node 556B4933-0 330 40
//@node FCC29E6F-0 610 40
//@node BA23578F-0 890 40
//@node 9AA434B2-0 1170 40
//@node A6EB2F00-0 1450 40
//@node 7F840BA8-0 1730 40
//@node CB30BC3E-0 2010 40
//@node EF5D5AF6-0 2290 40
//@node 0493E81B-0 2570 40
//@node 5D9CFE2D-0 2850 40
//@node 6F3293B9-0 3130 40
//@node 26B9AEEB-0 3410 40
//@node 4CABF100-0 3690 40
//@node 0BBAF45B-0 3970 40
//@node 7B306871-0 4250 40
//@node B7143971-0 4530 40
//@node 40423C47-0 4810 40
//@node 6ED379EF-0 5090 40
//@node 5CC2D689-0 5370 40
//@node CBAAA8B3-0 5650 40
//@node 4E8F5177-0 5930 40
//@node 793D5861-0 6210 40
//@node 957F1FE9-0 40 40
//@node 4899029C-0 330 40
//@node 19A8F9B9-0 610 40
//@node 38263572-0 890 40
//@node 61C9ABA3-0 1170 40
//@node A988FFD5-0 1450 40
//@node E12FA393-0 1730 40
//@node D7F9C783-0 2010 40
//@node 33455B59-0 2290 40
//@node 27B0CF87-0 2570 40
//@node 34A8A0C6-0 2850 40
//@node F680E598-0 3130 40
//@node A2FAA87C-0 3410 40
//@node 420D7056-0 3690 40
//@node 635E2364-0 3970 40
//@node 25477458-0 4250 40
//@node 09BA4576-0 4530 40
//@node 0D8FCABE-0 4810 40
//@node 9D4EC27C-0 5090 40
//@node 4EEC242E-0 5370 40
//@node 55654878-0 5650 40
//@node 1F5C0BAA-0 5930 40
//@node 3AD1A0B6-0 6210 40
//@node 2973BEA0-0 6490 40
//@node 967F217C-0 40 40
//@node A3C2C489-0 330 40
//@node F3550593-0 610 40
//@node BF279900-0 890 40
//@node 743B7D9B-0 1170 40
//@node 5C590D40-0 1450 40
//@node 0A87DD42-0 1730 40
//@node 025C21F6-0 2010 40
//@node BA786548-0 2290 40
//@node E4388690-0 2570 40
//@node 5526833D-0 2850 40
//@node 43994C67-0 3130 40
//@node 70A60E83-0 3410 40
//@node C5EDAFBD-0 3690 40
//@node 633F55B3-0 3970 40
//@node 3BECCAAF-0 4250 40
//@node E4354B35-0 4530 40
//@node 2622CEDD-0 4810 40
//@node 0259DBCB-0 5090 40
//@node DE43CD86-0 5370 40
//@node E8CC0E1D-0 5650 40
//@node DBF43843-0 5930 40
//@node 55DF65EB-0 6210 40
//@node 176FC311-0 6490 40
//@node 161DB379-0 40 40
//@node 853D2797-0 330 40
//@node CF21521D-0 610 40
//@node 853D2797-1 890 40
//@node BC4297C6-0 1170 40
//@node BD5E23D9-0 1450 40
//@node 24217BAC-0 1730 40
//@node 1CBFCD2A-0 2010 40
//@node C3BE4C32-0 2290 40
//@node C435E592-0 40 40
//@node 0669232F-0 330 40
//@node 0669232F-1 610 40
//@node 8E27E4C1-0 890 40
//@node 44574A0A-0 1170 40
//@node 14ED7EC3-0 1450 40
//@node 75E67998-0 1730 40
//@node 26A00ADE-0 2010 40
//@node D3E16724-0 2290 40
//@node 1A00E323-0 40 40
//@node 3971DB0C-0 330 40
//@node 5A508882-0 40 40
//@node 4D5936A9-0 330 40
//@node B2B19863-0 610 40
//@node 36FE5EAC-0 890 40
//@node 0C355F85-0 1170 40
//@node 89296F17-0 1450 40
//@node E0AF0AC1-0 40 40
//@node B4436845-0 330 40
//@node 4BB76B3C-0 610 40
//@node 131E88AB-0 890 40
//@node 5D5039DF-0 1170 40
//@node 595086EF-0 40 40
//@node D23EBCA0-0 330 40
//@node 1289168D-0 610 40
//@node 030FACAF-0 890 40
//@node 7D98342D-0 1170 40
//@node DDAF0608-0 40 40
//@node B74A5592-0 330 40
//@node B5B6D141-0 610 40
//@node 95B6CE8D-0 890 40
//@node 0EAA5CD2-0 1170 40
//@node 74E03137-0 1450 40
//@node 39541F66-0 1730 40
//@node 41C65597-0 40 40
//@node 3EFFA8A9-0 330 40
//@node 6F5DC5C2-0 610 40
//@node 57B9836F-0 890 40
//@node 616B17E2-0 1170 40
//@node E9C6DEC8-0 1450 40
//@node 34F6F2C4-0 1730 40
//@node 40585F70-0 2010 40
//@node 13928135-0 2290 40
//@node EF573F78-0 2570 40
//@node 881C8C06-0 2850 40
//@node 3059C463-0 40 40
//@node FD817B21-0 330 40
//@node F245D291-0 40 40
//@node 8C62191B-0 330 40
//@node 6C45D78A-0 610 40
//@node 77DC8A69-0 890 40
//@node 67FE17B5-0 1170 40
//@node 5A96414F-0 1450 40
//@node ADE4B3A6-0 1730 40
//@node 2AB9DE2B-0 2010 40
//@node 79657E94-0 2290 40
//@node 0E640BCD-0 2570 40
//@node BF671F4B-0 2850 40
//@node 71324926-0 3130 40
//@node 8F33FC39-0 3410 40
//@node 0D364AE4-0 3690 40
//@node 0E8808AF-0 3970 40
//@node 2E2EC5EF-0 4250 40
//@node D9DD5384-0 4530 40
//@node DA1A65AA-0 4810 40
//@node E62A706E-0 5090 40
//@node 95D04E2B-0 5370 40
//@node 90B7D468-0 5650 40
//@node 29562050-0 5930 40
//@node 95D04E2B-1 6210 40
//@node D66A91CB-0 6490 40
//@node 81D1AA45-0 6770 40
//@node 95D04E2B-2 7050 40
//@node 6D2EECC7-0 7330 40
//@node 7878845B-0 7610 40
//@node 95D04E2B-3 7890 40
//@node F7645631-0 8170 40
//@node 3C20991E-0 8450 40
//@node 2E2EC5EF-1 8730 40
//@node D9DD5384-1 9010 40
//@node 20BCED3C-0 9290 40
//@node 6EF0D4A9-0 9570 40
//@node 2ED29138-0 9850 40
//@node E7B3D4DF-0 10130 40
//@node 57553696-0 10410 40
//@node BB878B7D-0 10690 40
//@node 21283044-0 10970 40
//@node 31D14ADD-0 11250 40
//@node 50FBED5B-0 11530 40
//@node 1AA2CC16-0 11810 40
//@node C099E9A6-0 40 40
//@node B72F3F2A-0 330 40
//@node 9DF7962F-0 610 40
//@node EAD264E3-0 890 40
//@node 14568B79-0 1170 40
//@node 6A27108C-0 1450 40
//@node 12B12FE3-0 1730 40
//@node F1B82B9E-0 2010 40
//@node 30DBB59B-0 2290 40
//@node 08A05F05-0 2065 145
//@node 70A5DB36-0 2570 40
//@node 5836EAE5-0 2365 140
//@node 0E93720B-0 2850 40
//@node 471CBA83-0 3130 40
//@node E699ED3D-0 3410 40
//@node 5724E84A-0 3690 40
//@node 42C6572A-0 40 40
//@node 0E9EB6A0-0 330 40
//@node 251C8E81-0 610 40
//@node 462AB3ED-0 890 40
//@node D6D0E746-0 1170 40
//@node D5680C37-0 1450 40
//@node 3B454B86-0 1730 40
//@node 6E500B83-0 40 40
//@node A4B4912A-0 330 40
//@node 06EA9699-0 40 40
//@node 0A36CE3D-0 330 40
//@node D423699C-0 610 40
//@node 2EFA4574-0 890 40
//@node 5EE51D55-0 1170 40
//@node 434029D1-0 1450 40
//@node C89D07F6-0 1730 40
//@node 98A16833-0 2010 40
//@node 14E4542A-0 2290 40
//@node 9C3CD353-0 2570 40
//@node 98F0FD99-0 2850 40
//@node FC6CB2C4-0 3130 40
//@node 489AA006-0 3410 40
//@node A0B4A36B-0 3690 40
//@node 856E44CF-0 3970 40
//@node A2DFE122-0 4250 40
//@node AF56075D-0 4530 40
//@node F95F000E-0 4810 40
//@node 69837EC2-0 5090 40
//@node 5CFB454E-0 5370 40
//@node F9D71AF2-0 5650 40
//@node 57B84126-0 5930 40
//@node 5CFB454E-1 6210 40
//@node F17841E1-0 6490 40
//@node C171A7BF-0 6770 40
//@node 5CFB454E-2 7050 40
//@node 8CEA487B-0 7330 40
//@node 7C973C5F-0 7610 40
//@node 5CFB454E-3 7890 40
//@node F72A6B44-0 8170 40
//@node 46ECF5EF-0 8450 40
//@node A2DFE122-1 8730 40
//@node AF56075D-1 9010 40
//@node FC92B97A-0 9290 40
//@node E5F431C7-0 9570 40
//@node 97B178D8-0 9850 40
//@node 636A3501-0 10130 40
//@node 857FC166-0 10410 40
//@node EA9024A5-0 10690 40
//@node 828A5D9A-0 10970 40
//@node 3DA6A723-0 11250 40
//@node E63AE189-0 11530 40
//@node 07CCCFF4-0 11810 40
//@node BF99E813-0 40 40
//@node 814CD5D5-0 330 40
//@node A8FFD8B0-0 610 40
//@node 37033CB3-0 890 40
//@node F93366E4-0 1170 40
//@node 7068D695-0 1450 40
//@node 76054BAE-0 1730 40
//@node A2A8793F-0 2010 40
//@node 24160118-0 2290 40
//@node 1603DE8C-0 2065 145
//@node 28E4138D-0 2570 40
//@node F8716C47-0 2365 140
//@node DEA4C545-0 2850 40
//@node EEACD976-0 3130 40
//@node 2D281D60-0 3410 40
//@node 171D5209-0 3690 40
//@node 3CC64DB8-0 40 40
//@node F32ECEF9-0 330 40
//@node FC324CA9-0 610 40
//@node 0F86A7F6-0 890 40
//@node 22D5EC78-0 1170 40
//@node 3DC64F4B-0 40 40
//@node BD04ACCE-0 330 40
//@node C7384C92-0 610 40
//@node D1F4DB3F-0 890 40
//@node 05EA9506-0 40 40
//@node 1CE799A9-0 330 40
//@node 37306C06-0 610 40
//@node 09006A64-0 890 40
//@node F6EAEAC1-0 1170 40
//@node 08F56CAE-0 1450 40
//@node D30CCC53-0 1730 40
//@node 14C1A238-0 2010 40
//@node ABA0B953-0 2290 40
//@node 964F2531-0 2570 40
//@node 0675C21C-0 2850 40
//@node 13CFDE2E-0 3130 40
//@node 8030FA97-0 3410 40
//@node 6336AD2D-0 3690 40
//@node 136C7843-0 3970 40
//@node 1F30E654-0 4250 40
//@node 52CE3B0C-0 4530 40
//@node 68CA0EFC-0 4810 40
//@node A6ADB088-0 5090 40
//@node FB4C72F1-0 5370 40
//@node 22528CD9-0 5650 40
//@node AD4321EC-0 5930 40
//@node 08F56CAE-1 6210 40
//@node D2377DBC-0 6490 40
//@node BD06064C-0 6770 40
//@node C1DF38C8-0 7050 40
//@node B539A9F7-0 7330 40
//@node F1F3AF0C-0 7610 40
//@node 08F56CAE-2 7890 40
//@node 7476A023-0 8170 40
//@node 9624FDC8-0 8450 40
//@node 866A7245-0 8730 40
//@node 67EF13E1-0 9010 40
//@node 376A5B0C-0 9290 40
//@node BAB994DE-0 9570 40
//@node 334221A7-0 9850 40
//@node BE99E680-0 40 40
//@node 7C4082D8-0 330 40
//@node 3376CC59-0 610 40
//@node F257302F-0 890 40
//@node E18B8695-0 1170 40
//@node B9677604-0 1450 40
//@node D02BC0F8-0 1730 40
//@node 20A45D26-0 1505 145
//@node 8A72B0A4-0 2010 40
//@node 4847D600-0 1805 140
//@node 994991B7-0 2290 40
//@node 6D485F36-0 2570 40
//@node CC6391E1-0 2850 40
//@node 9E491E73-0 3130 40
//@node ACF76AE4-0 3410 40
//@node 3EC650DE-0 40 40
//@node 6652D610-0 330 40
//@node 336F559D-0 610 40
//@node FCE0F6BA-0 890 40
//@node 2F016D3C-0 40 40
//@node 5D9524B7-0 330 40
//@node 94A41849-0 125 145
//@node 3058B911-0 610 200
//@node A10B223B-0 405 305
//@node 489F12C6-0 200 305
//@node E8E0E6D3-0 890 360
//@node 2C5EAC63-0 665 465
//@node 19439BD9-0 460 565
//@node D8418223-0 255 565
//@node 101BF9E2-0 1170 360
//@node E70510F7-0 1450 360
//@node AD20D4EC-0 1730 360
//@node E70510F7-1 2010 360
//@node 1AB6EBD7-0 40 40
//@node 195CCA88-0 610 40
//@node EAB8132E-0 125 145
//@node F5D5CB5B-0 890 200
//@node 85C73BB4-0 405 305
//@node 2CE2C244-0 200 305
//@node 4EDDB19B-0 890 360
//@node D9940533-0 665 465
//@node D9199359-0 460 565
//@node F796AC79-0 255 565
//@node 2B655C31-0 1170 360
//@node D3D635C7-0 945 465
//@node C9915834-0 740 565
//@node 94EC4FF3-0 535 565
//@node D6EE9FBA-0 1730 360
//@node F93117D7-0 2010 360
//@node 1A840411-0 2290 360
//@node D285F9E4-0 2570 360
//@node B8AAA8DB-0 2850 360
//@node 1A840411-1 3130 360
//@node 202C631C-0 40 40
//@node 351BBC2F-0 330 40
//@node 184B84EC-0 610 40
//@node 6A176DE1-0 890 40
//@node 32687650-0 40 40
//@node 828E5049-0 330 40
//@node EA8245C2-0 610 40
//@node 5531D4DD-0 890 40
//@node 30954697-0 1170 40
//@doomscript-blueprint end
