namespace map_commoutside {

	#define CMD_LIFT_NONE		0
	#define CMD_LIFT_UP			1
	#define CMD_LIFT_DOWN		2
	#define CMD_LIFT_FORWARD	3
	#define CMD_LIFT_RIGHT		4
	#define CMD_LIFT_LEFT		5
	#define CMD_LIFT_BACK		6
	#define CMD_LIFT_CALL1		7
	#define CMD_LIFT_CALL2		8
	#define CMD_LIFT_CALL3		9

	#define	LIFT_MOVE_SPEED		160
	#define	LIFT_TURN_TIME		2
	#define LIFT_UPDOWN_TIME	2

	// states for the lift
	float	lift_command;
	boolean	lift_plat_up;
	float	lift_dir;
	entity	lift_station;

	void	setup_lift();
	void	reset_guis();
	void	set_lift_location( entity position );
	float 	calc_lift_path_r( entity current_pos, entity previous, entity target, float depth );
	float 	get_lift_turn_dir( entity source, entity target );
	entity	check_lift_move_dir( entity current_pos, float dir );
	void	turn_lift_to_dir( float dir );
	void	move_lift_to( entity target );

	void 	cmd_lift_up();
	void 	cmd_lift_down();
	void 	cmd_lift_forward();
	void 	cmd_lift_right();
	void 	cmd_lift_left();
	void 	cmd_lift_back();
	void 	cmd_lift_call_1();
	void 	cmd_lift_call_2();
	void 	cmd_lift_call_3();
	void	lift_loop();

	void 	lift_up();
	void 	lift_down();
	void 	lift_forward();
	void 	lift_right();
	void 	lift_left();
	void 	lift_back();
	void 	lift_call_1();
	void 	lift_call_2();
	void 	lift_call_3();

	void 	callspot1_panel_up();
	void 	callspot1_panel_down();
	void 	callspot2_panel_up();
	void 	callspot2_panel_down();
	void 	callspot3_panel_up();
	void 	callspot3_panel_down();

	void 	lift_main();

	////////////////////////////////////////////////////
	//
	//	Setup binds and times etc...
	//
	////////////////////////////////////////////////////
	void setup_lift() {
		// initial variable assignments
		lift_command = CMD_LIFT_NONE;
		lift_plat_up = true;

		lift_station = $lift_bottom.getTarget( 0 );
		if ( !lift_station ) {
			sys.warning( "Entity 'lift_bottom' doesn't have a target." );
		}
		set_lift_location( lift_station );

		lift_dir = 2;

		// Lift binds, times, and speeds
		$lift_leg_11.bind($lift_bottom);
		$lift_light1.bind($lift_bottom);
		
		$lift_axle1.bind($lift_leg_11);
		$lift_axle2.bind($lift_leg_11);
		$lift_leg_12.bind($lift_axle2);
		$lift_axle4.bind($lift_leg_12);
		$lift_axle6.bind($lift_leg_12);
		$lift_leg_13.bind($lift_axle6);
		$lift_axle7.bind($lift_leg_13);

		$lift_leg_23.bind($lift_axle7);
		$lift_axle5.bind($lift_leg_23);
		$lift_leg_22.bind($lift_axle5);
		$lift_axle3.bind($lift_leg_22);
		$lift_leg_21.bind($lift_axle3);

		$lift_connection_top_move.bind($lift_leg_13);
		$lift_connection_top_static.bind($lift_leg_23);
		$lift_connection_bottom_move.bind($lift_leg_21);

		$lift_cage.bind($lift_connection_top_static);

		$lift_leg_11.time( LIFT_UPDOWN_TIME );
		$lift_leg_12.time( LIFT_UPDOWN_TIME );
		$lift_leg_13.time( LIFT_UPDOWN_TIME );
		$lift_connection_top_move.time( LIFT_UPDOWN_TIME );
		$lift_leg_21.time( LIFT_UPDOWN_TIME );
		$lift_connection_bottom_move.time( LIFT_UPDOWN_TIME );
		$lift_leg_22.time( LIFT_UPDOWN_TIME );
		$lift_leg_23.time( LIFT_UPDOWN_TIME );
		$lift_connection_top_static.time( LIFT_UPDOWN_TIME );

		$lift_leg_11.accelTime( .25 );
		$lift_leg_12.accelTime( .25 );
		$lift_leg_13.accelTime( .25 );
		$lift_connection_top_move.accelTime( .25 );
		$lift_leg_21.accelTime( .25 );
		$lift_connection_bottom_move.accelTime( .25);
		$lift_leg_22.accelTime( .25 );
		$lift_leg_23.accelTime( .25 );
		$lift_connection_top_static.accelTime( .25 );

		$lift_leg_11.decelTime( .25 );
		$lift_leg_12.decelTime( .25 );
		$lift_leg_13.decelTime( .25 );
		$lift_connection_top_move.decelTime( .25 );
		$lift_leg_21.decelTime( .25 );
		$lift_connection_bottom_move.decelTime( .25 );
		$lift_leg_22.decelTime( .25 );
		$lift_leg_23.decelTime( .25 );
		$lift_connection_top_static.decelTime( .25 );

		// Call spots panel stuff
		$callspot1_conpan_gui.bind($callspot1_conpan);
		$callspot1_conpan.time(.25);
		$callspot1_conpan.rotateOnce( '63.43 0 0' );
		$callspot1_conpan_trigger_down.disable();

		$callspot2_conpan_gui.bind($callspot2_conpan);
		$callspot2_conpan.time(.25);
		$callspot2_conpan.rotateOnce( '0 0 -63.43' );
		$callspot2_conpan_trigger_down.disable();

		$callspot3_conpan_gui.bind($callspot3_conpan);
		$callspot3_conpan.time(.25);
		$callspot3_conpan.rotateOnce( '0 0 -63.43' );
		$callspot3_conpan_trigger_down.disable();

		$lift_light1_mover.rotateOnce( '90 0 0' );
	}

	////////////////////////////////////////////////////
	//
	//  reset the gui's to an interactive state
	//
	////////////////////////////////////////////////////
	void reset_guis() {
		sys.trigger($callspot1_conpan);
		$callspot1_conpan.setGuiParm ( "gui_parm3", 0 );
		sys.trigger($callspot2_conpan);
		$callspot2_conpan.setGuiParm ( "gui_parm3", 0 );
		sys.trigger($callspot3_conpan);
		$callspot3_conpan.setGuiParm ( "gui_parm3", 0 );
	}

	////////////////////////////////////////////////////
	//
	//	keep track of the current path entity we're at and update the
	//  gui's on the call panels with our position.
	//
	////////////////////////////////////////////////////
	void set_lift_location( entity position ) {
		string	position_name;
		string	position_num;
		float	pos;

		lift_station = position;
		position_name = position.getName();
		if ( sys.strLeft( position_name, 10 ) != "lift_spot_" ) {
			sys.warning( "Invalid lift target name '" + position_name + "'.  Lift targets must be named 'lift_spot_#' (where # is a numeric value)" );
		}

		position_num = sys.strSkip( position_name, 10 );
		pos = sys.strToFloat( position_num );

		$lift_cage.setGuiParm( "gui_parm2", pos );
		$callspot1_conpan.setGuiParm ( "gui_parm2", pos );
		$callspot2_conpan.setGuiParm ( "gui_parm2", pos );
		$callspot3_conpan.setGuiParm ( "gui_parm2", pos );

		$callspot1_conpan.setGuiParm ( "gui_parm4", 0 );
		$callspot2_conpan.setGuiParm ( "gui_parm4", 0 );
		$callspot3_conpan.setGuiParm ( "gui_parm4", 0 );
		
		//sys.print("position" + pos + "\n");

		if ( ( pos == 13 ) && ( lift_dir == 0 ) && !lift_plat_up ) {
			$callspot1_conpan.setGuiParm ( "gui_parm4", 1 );
			reset_guis();
		} else if ( ( pos == 31 ) && ( lift_dir == 1 ) && !lift_plat_up ) {
			$callspot2_conpan.setGuiParm ( "gui_parm4", 1 );
			reset_guis();
		} else if ( ( pos == 83 ) && ( lift_dir == 1 ) && !lift_plat_up ) {
			$callspot3_conpan.setGuiParm ( "gui_parm4", 1 );
			reset_guis();
		}
	}

	////////////////////////////////////////////////////
	//
	//	Do a depth-first search of the "track" to find a path to the target entity.
	//  each path entity targets 1 or more other path entities.  Each path entity it
	//  targets must also target it, so the links are forward and back.  There must be
	//  no circular links and the longest possible path must never be more than the
	//  script stack can handle (around 62 path entities would be the limit, but possibly
	//  fewer).  This could be modified to handle circular links, and be made non-recursive
	//  so it's not dependent on the stack size, and possibly with a bit of effort could find
	//  the shortest path if multiple paths exist, but for our purposes, this does the job.
	//
	////////////////////////////////////////////////////
	float calc_lift_path_r( entity current_pos, entity previous, entity target, float depth ) {
		float num;
		float i;
		entity next;
		float  path_length;

		// have we reached the target?
		if ( current_pos == target ) {
            return depth;
		}

		// check each of the targets on this entity
		num = current_pos.numTargets();
		for( i = 0; i < num; i++ ) {
			next = current_pos.getTarget( i );
			if ( next == previous ) {
				// don't go back the way we came
				continue;
			}

			// check if a path exists through this target
			path_length = calc_lift_path_r( next, current_pos, target, depth + 1 );
			if ( path_length ) {
				// found the target, so as we recurse backwards, set the name of the next path entity to go to.
				// when we're done, going through the "path*" keys in order will give the order of entities
				// to follow to get to the target.
				$lift_bottom.setKey( "path" + depth, next.getName() );
				return path_length;
			}
		}

		// no path from this entity
		return 0;
	}

	////////////////////////////////////////////////////
	//
	//	calculate the direction to turn to the next target
	//
	////////////////////////////////////////////////////
	float get_lift_turn_dir( entity source, entity target ) {
		float	dir;
		vector	delta;
		vector	ang;

		delta = target.getOrigin();
		delta = delta - source.getOrigin();
		ang = sys.VecToAngles( delta );
		dir = ( ( ang_y + 45 ) / 90 ) & 3;

		return dir;
	}

	////////////////////////////////////////////////////
	//
	//	movement test
	//
	////////////////////////////////////////////////////
	entity check_lift_move_dir( entity current_pos, float dir ) {
		float	num;
		float	i;
		float	check_dir;
		entity	check_ent;

		num = current_pos.numTargets();
		for( i = 0; i < num; i++ ) {
			check_ent = current_pos.getTarget( i );
			check_dir = get_lift_turn_dir( current_pos, check_ent );
			if ( check_dir == dir ) {
				return check_ent;
			}
		}
		return current_pos;
	}

	////////////////////////////////////////////////////
	//
	//	rotates the lift back into position when blocked
	//
	////////////////////////////////////////////////////
	void lift_rotate_blocked() {
		vector	delta;
		vector	dest_angles;
		float	rotateTime;

		$lift_bottom.stopRotating();
		sys.wait( 0.1 );

		// rotate back
		dest_angles_y = ( lift_dir & 3 ) * 90 + 180;
		if ( dest_angles_y >= 180 ) {
			dest_angles_y -= 360;
		}
		delta = anglemod180( dest_angles - $lift_bottom.getAngles() );
		rotateTime = abs( delta_y / 90 )* LIFT_TURN_TIME + 0.5;
		$lift_bottom.time( rotateTime );
		$lift_bottom.accelTime( .5 );
		$lift_bottom.decelTime( .5 );
		$lift_bottom.rotateOnce( delta );
		sys.waitFor( $lift_bottom );

		reset_guis();

		// update our location on the guis
		set_lift_location( lift_station );

		lift_loop();
	}

	////////////////////////////////////////////////////
	//
	//	turns lift
	//
	////////////////////////////////////////////////////
	void turn_lift_to_dir( float dir ) {
		float	turn_diff;
		vector	delta;
		vector	dest_angles;
		float	rotateTime;
		
		turn_diff = ( dir - lift_dir ) & 3;
		if ( turn_diff == 0 ) {
			return;
		}

		dest_angles_y = ( dir & 3 ) * 90 + 180;
		if ( dest_angles_y >= 180 ) {
			dest_angles_y -= 360;
		}
		delta = anglemod180( dest_angles - $lift_bottom.getAngles() );
		rotateTime = abs( delta_y / 90 )* LIFT_TURN_TIME + 0.5;

		sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_rotate_blocked" );
		$lift_bottom.accelTime( .5 );
		$lift_bottom.decelTime( .5 );
		$lift_bottom.time( rotateTime );
		
		$lift_bottom.startSoundShader ("co_lift_rotation", SND_CHANNEL_VOICE );
				
		$lift_bottom.rotateOnce( delta );
		sys.waitFor ($lift_bottom);

		sys.clearSignalThread( SIG_BLOCKED, $lift_bottom );
		lift_dir = dir;

		// update our location on the guis
		set_lift_location( lift_station );
	}

	////////////////////////////////////////////////////
	//
	//	move lift to a specific spot
	//
	////////////////////////////////////////////////////
	void move_lift_to( entity target ) {
		float 	path_length;
		float 	i;
		float 	dir;
		float 	next_dir;
		string 	ent_name;
		entity 	path_ent;
		entity 	next_ent;

		if ( lift_station == target ) {
			// lower the platform if necessary
			if ( lift_plat_up ) {
				cmd_lift_down();
			}
			return;
		}

		// create a path to the target
		path_length = calc_lift_path_r( lift_station, lift_station, target, 0 );
		if ( !path_length ) {
			string currentname = lift_station.getName();
			string targetname = target.getName();
			sys.warning( "entity 'lift_bottom' can't find path from '" + currentname + "' to '" + targetname + "'" );
			return;
		}

		// lower the platform if necessary
		if ( lift_plat_up ) {
			cmd_lift_down();
		}

		// get the first point on the path
		ent_name = $lift_bottom.getKey( "path0" );
		next_ent = sys.getEntity( ent_name );
		if ( !next_ent ) {
			sys.warning( "entity 'lift_bottom' can't find path entity '" + ent_name + "' to get to '" + target.getName() + "'" );
			return;
		}
		dir = get_lift_turn_dir( lift_station, next_ent );

		// move to each point on the path
		for( i = 0; i < path_length; i++ ) {
			path_ent = next_ent;

			// get the next path entity, unless we're at the last one
			if ( i < path_length - 1 ) {
				ent_name = $lift_bottom.getKey( "path" + ( i + 1 ) );
				next_ent = sys.getEntity( ent_name );
				if ( !next_ent ) {
					sys.warning( "entity 'lift_bottom' can't find path entity '" + ent_name + "' to get to '" + target.getName() + "'" );
					return;
				}
			}

			// turn towards the new direction if it's different and accelerate
			if ( dir != lift_dir ) {
				turn_lift_to_dir( dir );
				$lift_bottom.accelTime( .5 );
			} else if ( i != 0 ) {
				$lift_bottom.accelTime( 0 );
			} else {
				// always accelerate on the first path entity
				$lift_bottom.accelTime( .5 );
			}

			// decelerate on the last path entity or if we have to turn
			if ( i < path_length - 1 ) {
				dir = get_lift_turn_dir( path_ent, next_ent );
				if ( dir != lift_dir ) {
					$lift_bottom.decelTime( .5 );
				} else {
					$lift_bottom.decelTime( 0 );
				}
			} else {
				$lift_bottom.decelTime( .5 );
			}
			
			// move to the next path entity
			sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_move_blocked" );
			$lift_bottom.speed( LIFT_MOVE_SPEED );
		
			$lift_bottom.moveTo( path_ent );
			sys.waitFor( $lift_bottom );
			sys.clearSignalThread( SIG_BLOCKED, $lift_bottom );

			// update our location on the guis
			set_lift_location( path_ent );
		}
	}

	////////////////////////////////////////////////////
	//
	//	if blocked when trying to go up, go back down
	//
	////////////////////////////////////////////////////
	void lift_up_blocked() {
		cmd_lift_down();
		lift_loop();
	}

	////////////////////////////////////////////////////
	//
	//	move lift up
	//
	////////////////////////////////////////////////////
	void cmd_lift_up() {
		if ( lift_plat_up ) { 
			return;
		}
		
		float rotation = 0;

		// set the amount of movment 
		// needed for the spots where the lift can't go up fully
		if ( lift_station == $lift_spot_31 ) {
			rotation = 25;
		} else if ( lift_station == $lift_spot_32 ) {
			rotation = 20;
		} else if ( lift_station == $lift_spot_44 ) {
			rotation = 20;
		} else if ( lift_station == $lift_spot_73 ) {
			rotation = 24;
		}

		lift_plat_up = true;

		$lift_leg_11.startSoundShader ("co_lift_up_2s", SND_CHANNEL_VOICE );
		
		$lift_leg_11.rotateUpTo ( 0, -rotation );
		$lift_leg_12.rotateDownTo ( 0, 2 * rotation );
		$lift_leg_13.rotateUpTo ( 0, -2 * rotation );
		$lift_connection_top_move.rotateDownTo ( 0, rotation );

		$lift_leg_21.rotateDownTo ( 0, 2 * rotation );
		$lift_connection_bottom_move.rotateUpTo ( 0, -rotation );
		$lift_leg_22.rotateUpTo ( 0, -2 * rotation );
		$lift_leg_23.rotateDownTo ( 0, 2 * rotation );
		$lift_connection_top_static.rotateUpTo ( 0, -rotation );
		
		sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_up_blocked" );
		sys.waitFor( $lift_leg_23 );
		sys.clearSignalThread( SIG_BLOCKED, $lift_bottom );

		// update our location on the guis
		set_lift_location( lift_station );
	}

	////////////////////////////////////////////////////
	//
	//	if blocked when trying to go down, go back up
	//
	////////////////////////////////////////////////////
	void lift_down_blocked() {
		cmd_lift_up();
		reset_guis();
		lift_loop();
	}

	////////////////////////////////////////////////////
	//
	//	move lift down
	//
	////////////////////////////////////////////////////
	void cmd_lift_down() {
		if ( !lift_plat_up ) { 
			return;
		}

		$lift_cage_control.disable();

		lift_plat_up = false;

		$lift_leg_11.startSoundShader ("co_lift_down_2s", SND_CHANNEL_VOICE );
		
		$lift_leg_11.rotateDownTo ( 0, 320 );
		$lift_leg_12.rotateUpTo ( 0, 80 );
		$lift_leg_13.rotateDownTo ( 0, 280 );
		$lift_connection_top_move.rotateUpTo ( 0, 40 );

		$lift_leg_21.rotateUpTo ( 0, 80 );
		$lift_connection_bottom_move.rotateDownTo ( 0, 320 );
		$lift_leg_22.rotateDownTo ( 0, 280 );
		$lift_leg_23.rotateUpTo ( 0, 80 );
		$lift_connection_top_static.rotateDownTo ( 0, 320 );

		sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_down_blocked" );
		sys.waitFor ($lift_leg_23);
		sys.clearSignalThread( SIG_BLOCKED, $lift_bottom );

		$lift_cage_control.enable();

		// update our location on the guis
		set_lift_location( lift_station );
	}

	////////////////////////////////////////////////////
	//
	//	moves the lift back into position when blocked
	//
	////////////////////////////////////////////////////
	void lift_move_blocked() {
		$lift_bottom.stopMoving();
		$lift_bottom.startSound( "snd_decel", SND_CHANNEL_BODY2, false );
		sys.wait( 0.1 );
		
		// move back
		$lift_bottom.accelTime( .5 );
		$lift_bottom.decelTime( .5 );
		$lift_bottom.speed( LIFT_MOVE_SPEED );
		$lift_bottom.moveTo( lift_station );
		sys.waitFor( $lift_bottom );
		$lift_cage_control.enable();

		reset_guis();

		// update our location on the guis
		set_lift_location( lift_station );

		lift_loop();
	}

	////////////////////////////////////////////////////
	//
	//	move lift forward
	//
	////////////////////////////////////////////////////
	void cmd_lift_forward() {
		entity path_ent;

		path_ent = check_lift_move_dir( lift_station, lift_dir );
		if ( path_ent == lift_station ) {
			return;
		}

		if ( lift_plat_up ) {
			cmd_lift_down();
		}

		$lift_cage_control.disable();

		sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_move_blocked" );
		$lift_bottom.accelTime( .5 );
		$lift_bottom.decelTime( .5 );
		$lift_bottom.speed( LIFT_MOVE_SPEED );
		$lift_bottom.moveTo( path_ent );
		sys.waitFor( $lift_bottom );
		sys.clearSignalThread( SIG_BLOCKED, $lift_bottom );
		set_lift_location( path_ent );
		$lift_cage_control.enable();
	}

	////////////////////////////////////////////////////
	//
	//	move lift back
	//
	////////////////////////////////////////////////////
	void cmd_lift_back() {
		entity path_ent;

		path_ent = check_lift_move_dir( lift_station, ( lift_dir + 2 ) & 3 );
		if ( path_ent == lift_station ) {
			return;
		}

		if ( lift_plat_up ) {
			cmd_lift_down();
		}

		$lift_cage_control.disable();

		sys.onSignal( SIG_BLOCKED, $lift_bottom, "map_commoutside::lift_move_blocked" );
		$lift_bottom.accelTime( .5 );
		$lift_bottom.decelTime( .5 );
		$lift_bottom.speed( LIFT_MOVE_SPEED );
		$lift_bottom.moveTo( path_ent );
		sys.waitFor( $lift_bottom );
		set_lift_location( path_ent );
		$lift_cage_control.enable();
	}

	////////////////////////////////////////////////////
	//
	//	move lift right
	//
	////////////////////////////////////////////////////
	void cmd_lift_right() {
		turn_lift_to_dir( ( lift_dir - 1 ) & 3 );
	}

	////////////////////////////////////////////////////
	//
	//	move lift left
	//
	////////////////////////////////////////////////////
	void cmd_lift_left() {
		turn_lift_to_dir( ( lift_dir + 1 ) & 3 );
	}

	////////////////////////////////////////////////////
	//
	//	call lift to call spot #1
	//	From anywhere in the grid the lift will find
	//	it's way to call spot #1
	//
	////////////////////////////////////////////////////
	void cmd_lift_call_1() {
		move_lift_to( $lift_spot_13 );
		turn_lift_to_dir( 0 );
	}

	////////////////////////////////////////////////////
	//
	//	call lift to call spot #2
	//	From anywhere in the grid the lift will find
	//	it's way to call spot #2
	//
	////////////////////////////////////////////////////
	void cmd_lift_call_2() {
		move_lift_to( $lift_spot_31 );
		turn_lift_to_dir( 1 );
	}

	////////////////////////////////////////////////////
	//
	//	call lift to call spot #3
	//	From anywhere in the grid the lift will find
	//	it's way to call spot #3
	//
	////////////////////////////////////////////////////
	void cmd_lift_call_3() {
		move_lift_to( $lift_spot_83 );
		turn_lift_to_dir( 1 );
	}

	////////////////////////////////////////////////////
	//
	//	command processing loop
	//
	////////////////////////////////////////////////////
	void lift_loop() {
		while( 1 ) {
			lift_command = CMD_LIFT_NONE;
			while( lift_command == CMD_LIFT_NONE ) {
				sys.waitFrame();
			}

			if ( lift_command == CMD_LIFT_UP ) {
				cmd_lift_up();
			} else if ( lift_command == CMD_LIFT_DOWN ) {
				cmd_lift_down();
			} else if ( lift_command == CMD_LIFT_FORWARD ) {
				cmd_lift_forward();
			} else if ( lift_command == CMD_LIFT_RIGHT ) {
				cmd_lift_right();
			} else if ( lift_command == CMD_LIFT_LEFT ) {
				cmd_lift_left();
			} else if ( lift_command == CMD_LIFT_BACK ) {
				cmd_lift_back();
			} else if ( lift_command == CMD_LIFT_CALL1 ) {
				cmd_lift_call_1();
			} else if ( lift_command == CMD_LIFT_CALL2 ) {
				cmd_lift_call_2();
			} else if ( lift_command == CMD_LIFT_CALL3 ) {
				cmd_lift_call_3();
			}
		}
	}

	////////////////////////////////////////////////////
	//
	//	Gui call back functions
	//
	////////////////////////////////////////////////////
	void lift_up() {
		lift_command = CMD_LIFT_UP;
	}
	void lift_down() {
		lift_command = CMD_LIFT_DOWN;
	}
	void lift_forward() {
		lift_command = CMD_LIFT_FORWARD;
	}
	void lift_right() {
		lift_command = CMD_LIFT_RIGHT;
	}
	void lift_left() {
		lift_command = CMD_LIFT_LEFT;
	}
	void lift_back() {
		lift_command = CMD_LIFT_BACK;
	}
	void lift_call_1() {
		lift_command = CMD_LIFT_CALL1;
	}
	void lift_call_2() {
		lift_command = CMD_LIFT_CALL2;
	}
	void lift_call_3() {
		lift_command = CMD_LIFT_CALL3;
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #1
	//
	////////////////////////////////////////////////////
	void callspot1_panel_up() {
		$callspot1_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot1_conpan.rotateOnce( '-63.43 0 0' );
		$callspot1_conpan_trigger_up.disable();
		sys.waitFor( $callspot1_conpan );

		$callspot1_conpan_trigger_down.enable();
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #1
	//
	////////////////////////////////////////////////////
	void callspot1_panel_down()	{
		$callspot1_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot1_conpan.rotateOnce( '63.43 0 0' );
		$callspot1_conpan_trigger_down.disable();
		sys.waitFor( $callspot1_conpan );

		$callspot1_conpan_trigger_up.enable();
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #2
	//
	////////////////////////////////////////////////////
	void callspot2_panel_up() {
		$callspot2_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot2_conpan.rotateOnce( '0 0 63.43' );
		$callspot2_conpan_trigger_up.disable();
		sys.waitFor( $callspot2_conpan );

		$callspot2_conpan_trigger_down.enable();
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #2
	//
	////////////////////////////////////////////////////
	void callspot2_panel_down() {
		$callspot2_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot2_conpan.rotateOnce( '0 0 -63.43' );
		$callspot2_conpan_trigger_down.disable();
		sys.waitFor( $callspot2_conpan );

		$callspot2_conpan_trigger_up.enable();
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #3
	//
	////////////////////////////////////////////////////
	void callspot3_panel_up() {
		$callspot3_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot3_conpan.rotateOnce( '0 0 63.43' );
		$callspot3_conpan_trigger_up.disable();
		sys.waitFor( $callspot3_conpan );

		$callspot3_conpan_trigger_down.enable();
	}

	////////////////////////////////////////////////////
	//
	//	raise panel for call spot #3
	//
	////////////////////////////////////////////////////
	void callspot3_panel_down() {
		$callspot3_conpan.startSoundShader ("co_conpanel", SND_CHANNEL_VOICE );
		$callspot3_conpan.rotateOnce( '0 0 -63.43' );
		$callspot3_conpan_trigger_down.disable();
		sys.waitFor( $callspot3_conpan );

		$callspot3_conpan_trigger_up.enable();
	}

	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void lift_main() {
		
		setup_lift();

		// turn lift to the left so it can illuminate the 2nd call station area
		cmd_lift_left();
		lift_loop();
	}
} // namespace

//@doomscript-blueprint begin 6
//@source D094780C
//@catalog 0C260740
//@node 62F442FE-0 40 40
//@node 818BACAB-0 330 40
//@node 0CEA2E2E-0 125 145
//@node FD40AE7A-0 610 40
//@node E948BE0C-0 405 145
//@node 0957F546-0 890 40
//@node C2283F57-0 665 145
//@node 281B423D-0 1170 40
//@node 8B9A3B76-0 965 145
//@node 68FAA7CA-0 760 145
//@node CB8B651D-0 1450 200
//@node 8748BEE8-0 1730 40
//@node 73C872C3-0 1525 140
//@node 7033D5D2-0 2010 40
//@node 3060BB26-0 1805 145
//@node 3FC095EF-0 2290 40
//@node 86EBB0AF-0 2570 40
//@node 6DFA0045-0 2850 40
//@node E08B2FDC-0 3130 40
//@node 51A5A48B-0 3410 40
//@node 776A5247-0 3690 40
//@node 9D885709-0 3970 40
//@node 334B3672-0 4250 40
//@node 83EC9F11-0 4530 40
//@node BD88F374-0 4810 40
//@node C8A88134-0 5090 40
//@node 89EF9B83-0 5370 40
//@node 75579F0D-0 5650 40
//@node 5DC5FC96-0 5930 40
//@node D51D1DFE-0 6210 40
//@node BA4E307A-0 6490 40
//@node 314CE6C1-0 6770 40
//@node F91611EE-0 7050 40
//@node EF96E6FF-0 7330 40
//@node E773FF2E-0 7610 40
//@node 2718D071-0 7890 40
//@node 34477248-0 8170 40
//@node 93B1DF50-0 8450 40
//@node E908592A-0 8730 40
//@node D719068D-0 9010 40
//@node 10D991BA-0 9290 40
//@node 99166367-0 9570 40
//@node 405E175F-0 9850 40
//@node 9F844B46-0 10130 40
//@node BEAD4839-0 10410 40
//@node 2B9E0C50-0 10690 40
//@node EB970438-0 10970 40
//@node AC858E86-0 11250 40
//@node EBB047ED-0 11530 40
//@node B3F81F9A-0 11810 40
//@node F3505867-0 12090 40
//@node FEBB2DD2-0 12370 40
//@node A305664F-0 12650 40
//@node 8C031700-0 12930 40
//@node BC9D3BE5-0 13210 40
//@node 642A7E8D-0 13490 40
//@node FAA833F3-0 13770 40
//@node 4A1B47B4-0 14050 40
//@node 2FC927A3-0 14330 40
//@node 5B8C0ADA-0 14610 40
//@node 68D785EB-0 14890 40
//@node 79A54E75-0 15170 40
//@node 0669D083-0 15450 40
//@node A655C44D-0 15730 40
//@node 8904F771-0 16010 40
//@node 7AF239BC-0 16290 40
//@node 67ED050D-0 16570 40
//@node 99E293F6-0 16850 40
//@node 59F8ED3B-0 17130 40
//@node 35A534CF-0 17410 40
//@node 9B431EB4-0 17690 40
//@node 26844C1F-0 17970 40
//@node 0BBE6B18-0 18250 40
//@node 75562499-0 40 40
//@node DA10C247-0 330 40
//@node EFB8D6F6-0 610 40
//@node F0993F8C-0 890 40
//@node C728F38B-0 1170 40
//@node 303D83E9-0 1450 40
//@node 9F99A1F0-0 1730 40
//@node A21F7961-0 40 40
//@node 1C82F0EF-0 330 40
//@node 6AE229A4-0 610 40
//@node AB76E268-0 385 145
//@node 8AE8F640-0 890 40
//@node 890BF8E1-0 685 145
//@node 695DE16E-0 480 145
//@node 66BA2813-0 1170 200
//@node 8043081A-0 965 300
//@node 1D583E85-0 760 300
//@node 8FFA1CB8-0 1450 40
//@node 67BC9BA0-0 1225 145
//@node 632AEC20-0 1020 245
//@node 9BBC1EF8-0 1730 40
//@node 084D2EA3-0 1505 145
//@node FDD17BB8-0 1300 245
//@node 3DF9B8D0-0 2010 40
//@node 07D79264-0 1805 232
//@node C9A43D45-0 2290 40
//@node 8F261955-0 2085 232
//@node 5CCE0F78-0 2570 40
//@node 17000B9D-0 2365 232
//@node 21749E1F-0 2850 40
//@node F353F27B-0 2645 232
//@node A58F2389-0 3130 40
//@node 3629D174-0 3410 40
//@node 518DC99F-0 3690 40
//@node 2B79B9DE-0 3970 40
//@node 0CC22C0F-0 3765 145
//@node 6B2F65F7-0 3560 145
//@node 6B6F4F6E-0 3560 229
//@node D81501EE-0 3560 313
//@node B23172D8-0 4250 200
//@node C8C8425B-0 4530 200
//@node 627E07B2-0 4810 200
//@node BAD97FB5-0 4605 305
//@node 0DAB2A10-0 4400 305
//@node 3950F993-0 4400 389
//@node DED906DB-0 4400 473
//@node A93706C5-0 5090 200
//@node C8C8425B-1 5370 200
//@node 1032FB07-0 5650 200
//@node 8DC29320-0 5445 305
//@node A84DB848-0 5240 305
//@node F7E2BE9B-0 5240 389
//@node C0F5FA53-0 5240 473
//@node 55923B96-0 5930 200
//@node C8C8425B-2 6210 200
//@node 7FB63CDB-0 40 40
//@node 87485D64-0 330 40
//@node 5C832561-0 125 145
//@node F53566D7-0 610 200
//@node 1740EA81-0 890 40
//@node 9F63592A-0 665 145
//@node 22189069-0 1170 40
//@node A7232EAF-0 965 145
//@node 46868EFA-0 760 145
//@node 0F2A6C01-0 760 229
//@node 3FAE64E6-0 1450 200
//@node 1833283A-0 1225 305
//@node 5DE4D6EB-0 1020 405
//@node 66448DC5-0 1730 200
//@node 1E4EF242-0 1525 305
//@node A6165168-0 1320 305
//@node BC426B3C-0 2010 360
//@node 50E1271C-0 2290 200
//@node 9D09B971-0 2065 305
//@node EFBC2457-0 1860 405
//@node 48FE20D3-0 1860 681
//@node 6671C097-0 2570 200
//@node A49FC270-0 2365 305
//@node DE49BE33-0 2850 360
//@node 638D606A-0 2645 460
//@node CE593F61-0 2645 552
//@node F1E4CFCA-0 2440 552
//@node 6603C68C-0 3130 360
//@node 85F16A38-0 3410 40
//@node 0E63F9D5-0 40 40
//@node 4C6B4B84-0 330 40
//@node 75D36FAC-0 105 145
//@node 7734C97D-0 610 40
//@node 83406111-0 385 145
//@node 4862552B-0 890 40
//@node 1C77CAB4-0 665 145
//@node 9295A2EF-0 460 245
//@node 09CAB562-0 1170 40
//@node 60F0F43B-0 965 145
//@node 4A1FF6AF-0 1450 40
//@node D1211243-0 40 40
//@node 9C0790A7-0 330 40
//@node 0CF7BCC7-0 105 145
//@node 81F007F1-0 610 40
//@node 48421443-0 405 145
//@node C32DC2C8-0 200 145
//@node 371667C3-0 200 229
//@node AEA70CCF-0 890 200
//@node D4DF6318-0 665 305
//@node A87A7E6C-0 460 405
//@node 04EEE699-0 1170 200
//@node 561152EE-0 945 305
//@node A9C38452-0 740 497
//@node D3FC0BAA-0 1450 200
//@node 08FCA4AB-0 1245 305
//@node E6F7F3EF-0 1040 305
//@node B37475D6-0 1730 360
//@node E08DCD18-0 2010 40
//@node 6A97A195-0 40 40
//@node 8C93F4D2-0 330 40
//@node 301DD4F6-0 610 40
//@node 93E83837-0 890 40
//@node 8426EBAC-0 685 145
//@node 9B4EA664-0 480 145
//@node 49F38F78-0 1170 40
//@node A111EF8C-0 965 145
//@node 8F412995-0 1450 200
//@node C6E6BF26-0 1245 305
//@node 2F562D53-0 1730 40
//@node B92925A8-0 1505 145
//@node 108008C6-0 1300 245
//@node 9E18F638-0 1095 245
//@node 4D2E0C6A-0 2010 40
//@node C5C32641-0 1805 145
//@node 9E5ECBE7-0 2290 40
//@node 16941E66-0 2085 140
//@node FEFC2F9A-0 2570 40
//@node E48FA429-0 2850 40
//@node 486D325E-0 3130 40
//@node 80F298D6-0 2925 140
//@node D9040E6F-0 3410 40
//@node 2889CECB-0 3690 40
//@node 01B97F4D-0 3970 40
//@node 0DDF0FA0-0 3765 140
//@node A3B9B2B9-0 4250 40
//@node EE890DFE-0 40 40
//@node A74E8C21-0 330 40
//@node 3290D13D-0 125 145
//@node DB6B0D20-0 -80 229
//@node 58CA02A5-0 610 40
//@node 80561B9D-0 405 145
//@node 12723E62-0 200 145
//@node A1119A85-0 890 200
//@node 65CA3214-0 1170 40
//@node FD294E5A-0 965 145
//@node EA67DB2F-0 1450 40
//@node 1063FB49-0 1245 145
//@node DF0F3D94-0 1730 200
//@node 5FE8D213-0 1525 305
//@node EA25D02C-0 2010 40
//@node 62C97482-0 1785 145
//@node 8EA325DA-0 1580 245
//@node 426A3022-0 1375 245
//@node 60F38793-0 2290 40
//@node 61941351-0 2085 145
//@node 29B962AD-0 2570 40
//@node E35B9A85-0 2850 40
//@node F4230E5A-0 3130 40
//@node 008742B6-0 3410 40
//@node E9DCBFE1-0 3205 140
//@node 4B2B8352-0 3690 40
//@node CF4CA8F1-0 3970 40
//@node 413DB490-0 3765 140
//@node D7000852-0 4250 40
//@node B960F82F-0 4530 40
//@node 3AF9A691-0 4810 40
//@node B4487CE4-0 5090 40
//@node 8FB71DBF-0 4885 140
//@node 2F054E74-0 40 40
//@node 95F66AB1-0 330 40
//@node 30B81AB0-0 125 145
//@node CC19E796-0 -80 229
//@node 13E82B71-0 610 200
//@node 15AFA744-0 405 305
//@node 54335ABD-0 890 360
//@node 99F3209B-0 1170 200
//@node 7AFC413D-0 1450 40
//@node 03632B7F-0 1225 145
//@node BF4F9CA7-0 1020 245
//@node E4799236-0 1020 337
//@node 0EB0B321-0 1730 40
//@node F8FFB863-0 1525 145
//@node A0DCAF11-0 1320 145
//@node 8D6D5647-0 2570 200
//@node A3133A11-0 1805 300
//@node AB61B92A-0 1600 300
//@node A771BFBE-0 1600 378
//@node 99F3209B-1 2850 200
//@node 13E82B71-1 2570 40
//@node 02FA1775-0 2365 145
//@node 54335ABD-1 3410 200
//@node 0CD70DC6-0 3130 40
//@node A9E05B14-0 2905 145
//@node 057C406E-0 3410 40
//@node 01A3247F-0 3185 145
//@node C90620A9-0 2980 245
//@node E02C658A-0 3690 40
//@node 90D9FAB9-0 3485 145
//@node 6590D2E1-0 3280 145
//@node A11BEE31-0 4530 200
//@node 670992B4-0 3765 300
//@node FC302290-0 3560 300
//@node 99F3209B-2 4810 200
//@node 63A8F3AE-0 4530 40
//@node 83BEF7D9-0 4305 145
//@node 234E5616-0 4100 245
//@node 548E7DA2-0 4100 337
//@node 32409B98-0 4810 40
//@node 0B6C26A0-0 4605 145
//@node 64FBD2FD-0 4400 145
//@node 697EC24A-0 4400 229
//@node B29DAD11-0 5090 200
//@node 7C65C897-0 4885 305
//@node 293E25FD-0 5370 200
//@node 18D3FDDC-0 5165 305
//@node 4D37D698-0 4960 305
//@node F1B5CEA7-0 4960 389
//@node 5EA620FF-0 5650 360
//@node D5309592-0 5425 465
//@node 722B9270-0 5220 565
//@node FDA07DD6-0 5015 565
//@node 057C406E-1 5930 360
//@node 4ABA9BEC-0 5705 465
//@node 6BB305DE-0 5500 565
//@node E02C658A-1 6210 360
//@node D4F1BE2E-0 6005 465
//@node 6B5B25D8-0 5800 465
//@node A11BEE31-1 7050 520
//@node 22A0756F-0 6285 620
//@node 28315DB9-0 6080 620
//@node 99F3209B-3 7330 520
//@node 24B2C376-0 7050 200
//@node 23677BB4-0 6845 305
//@node BC104838-0 6640 305
//@node 44AEFC64-0 6640 389
//@node 8FCB98F8-0 7890 360
//@node 3797DA7B-0 7125 460
//@node F35483BB-0 8170 360
//@node 76B04CCE-0 7890 360
//@node 2E95DE12-0 7685 465
//@node 52247667-0 7480 465
//@node B603CA88-0 8730 360
//@node F35483BB-1 9290 360
//@node 293E25FD-1 9010 200
//@node 3D18A29F-0 8805 305
//@node A6A34D9B-0 8600 305
//@node 5E4D187C-0 8600 389
//@node D576AB27-0 9290 360
//@node 6E75E7B4-0 9065 465
//@node 3BE9A7F4-0 8860 565
//@node CF50AD67-0 8860 657
//@node 24B2C376-1 9570 360
//@node 2220722F-0 9365 465
//@node E76CCB17-0 9160 465
//@node DF11A675-0 9160 549
//@node BBA80504-0 10410 520
//@node 01DB2DE5-0 10970 520
//@node BBA80504-1 11530 360
//@node 21AD73F9-0 11810 200
//@node 0F14C7E3-0 12090 200
//@node 74E5E57E-0 12370 200
//@node E0960F80-0 11605 300
//@node 5D2B598C-0 12650 200
//@node 728449E5-0 12930 200
//@node 177A6957-0 13210 200
//@node 87A73A1A-0 12445 300
//@node BE740527-0 40 40
//@node D4970174-0 330 40
//@node DB44597B-0 610 40
//@node C87EF197-0 40 40
//@node D582E8AE-0 330 40
//@node 177C5A48-0 125 145
//@node 4966A68C-0 610 200
//@node C5070A5C-0 890 40
//@node 4479085D-0 685 145
//@node AF0032DF-0 480 145
//@node 7176AE4B-0 1170 200
//@node 8F31329D-0 965 305
//@node 56943D90-0 1450 200
//@node 48E8E0D2-0 1245 305
//@node E62541C9-0 1040 305
//@node F16F2906-0 1730 200
//@node F3F5EC43-0 1525 305
//@node 2C869BBD-0 2010 200
//@node DB2A9443-0 1805 305
//@node 1E2DB1B9-0 1600 305
//@node F16F2906-1 2290 200
//@node 609FE432-0 2085 305
//@node 5A5E89AF-0 2570 200
//@node 5BDFF25D-0 2365 305
//@node F9A31DF9-0 2160 305
//@node 7978F97A-0 2850 200
//@node 25670F57-0 2645 305
//@node DC41C7E3-0 3130 40
//@node D96BAC23-0 2925 145
//@node C881D6CC-0 3690 40
//@node 91546B14-0 3970 40
//@node 6438BE72-0 3485 232
//@node 60931A24-0 3280 232
//@node 96A23349-0 4250 40
//@node EA7D406A-0 3765 232
//@node ED77E27D-0 3560 232
//@node A6B18116-0 4530 40
//@node 1B93EFA2-0 4045 232
//@node B49CF40C-0 3840 232
//@node 34ABD601-0 4810 40
//@node 843B23B9-0 4325 232
//@node C17360D3-0 5090 40
//@node E2561C8E-0 4605 232
//@node A1CCA449-0 4400 232
//@node A523A453-0 5370 40
//@node A128D790-0 4885 232
//@node EDC67CCA-0 4680 232
//@node 2E081822-0 5650 40
//@node F9579A80-0 5165 232
//@node AF2D5816-0 4960 232
//@node DBEE0B8D-0 5930 40
//@node 9748F1FB-0 5445 232
//@node 7A2AAE08-0 5240 232
//@node 3F836EE2-0 6210 40
//@node 20ABBBB2-0 5725 232
//@node 2B02AFA8-0 5520 232
//@node 0F062C58-0 6490 40
//@node F84BE3D2-0 6770 40
//@node 679AEE16-0 7050 40
//@node 7F3D53CF-0 7330 40
//@node 3E3F63FE-0 6845 140
//@node 21051CBE-0 40 40
//@node 84C16234-0 330 40
//@node 60D1BB08-0 610 40
//@node 55E9EFBC-0 890 40
//@node 68FCD032-0 40 40
//@node 66DF76FA-0 330 40
//@node 2F4229E3-0 125 145
//@node 3A9826D5-0 -80 145
//@node A5685161-0 610 200
//@node 0EA840DA-0 890 40
//@node 147E505B-0 1170 40
//@node 9C300DFA-0 965 145
//@node CB44EC5A-0 1450 40
//@node 5598D7B6-0 1730 40
//@node 042840F3-0 2010 40
//@node A5028F17-0 2290 40
//@node F7F5996D-0 2570 40
//@node 21976881-0 2850 40
//@node 41C98785-0 3130 40
//@node 85D00FA3-0 3410 40
//@node DE607B6F-0 3690 40
//@node 8BF231FE-0 3970 40
//@node 573735E6-0 4250 40
//@node D8E4AEA3-0 4530 40
//@node 841E171B-0 4810 40
//@node A0C4703F-0 5090 40
//@node 0360E168-0 5370 40
//@node 3E65EC6F-0 5165 140
//@node 8A33BA0B-0 40 40
//@node 39D41366-0 330 40
//@node 6B419E49-0 610 40
//@node C1AE8350-0 890 40
//@node 8DF83C60-0 1170 40
//@node 69A7D33B-0 1450 40
//@node 4FFC0E7A-0 1730 40
//@node E07E0FE6-0 2010 40
//@node 3BE2DF57-0 1805 140
//@node 5405FEC5-0 2290 40
//@node A74C9C4C-0 2570 40
//@node 126D4DA9-0 2850 40
//@node 008F7D97-0 3130 40
//@node 41A23E20-0 2925 140
//@node 04647F87-0 3410 40
//@node 84969117-0 40 40
//@node C2803D79-0 330 40
//@node 830ABF73-0 105 145
//@node 67319979-0 -100 245
//@node D3DB25F3-0 -100 337
//@node 384A2992-0 610 40
//@node D9A09813-0 405 145
//@node 4BF1E646-0 200 145
//@node FF7BFDA9-0 200 229
//@node 459F203C-0 890 200
//@node 2456C10E-0 1170 40
//@node 87054EF6-0 965 145
//@node 7B1997C8-0 1450 200
//@node 9167087B-0 1730 40
//@node AB15CFF8-0 2010 40
//@node 56A0F688-0 2290 40
//@node 9307DAA3-0 2570 40
//@node 178D8452-0 2850 40
//@node 08000B47-0 3130 40
//@node 24A1B683-0 2925 140
//@node D07185ED-0 3410 40
//@node 0E147EB6-0 3690 40
//@node BC555DE6-0 3970 40
//@node CA33D607-0 3765 140
//@node D0AB8D04-0 4250 40
//@node 7DCE29A9-0 40 40
//@node 5AA2F9D4-0 330 40
//@node 53BD87FD-0 105 145
//@node E3F28AA2-0 -100 245
//@node 85DD5578-0 -100 337
//@node 7F562824-0 -305 337
//@node E3266328-0 610 40
//@node F514F8F0-0 405 145
//@node 3648EE13-0 200 145
//@node 065C38E4-0 200 229
//@node 22AD6EA6-0 890 200
//@node 18ED0604-0 1170 40
//@node 383D758A-0 965 145
//@node 043F63BA-0 1450 200
//@node 8CCC3F99-0 1730 40
//@node C526A89E-0 2010 40
//@node 569359CE-0 2290 40
//@node 971B291D-0 2570 40
//@node F785688C-0 2850 40
//@node A66CF819-0 3130 40
//@node 74E54236-0 2925 140
//@node BC9FC153-0 3410 40
//@node B87D77A4-0 3690 40
//@node 5EC66DA0-0 3485 140
//@node 0D75721E-0 3970 40
//@node E6C33988-0 40 40
//@node 21C26AB8-0 330 40
//@node 2BAE36FD-0 125 140
//@node 27D51350-0 -80 140
//@node F082EB17-0 40 40
//@node B843E0C1-0 330 40
//@node C4682A8B-0 125 140
//@node 017A1C02-0 -80 140
//@node F9F80886-0 40 40
//@node CD594520-0 330 40
//@node 36DBBF1F-0 610 40
//@node F8F806F3-0 40 40
//@node 882B702B-0 330 40
//@node EFEA1D25-0 610 40
//@node F7F80560-0 40 40
//@node BBEC4DFD-0 330 40
//@node E37B5344-0 610 40
//@node 234F895F-0 40 40
//@node A1086D46-0 330 40
//@node 10FDAD30-0 125 145
//@node 2F1234E0-0 610 200
//@node DC675A36-0 405 305
//@node B6AE8529-0 890 200
//@node 4E3E92B0-0 685 305
//@node 09926530-0 480 305
//@node C91C3F8C-0 1170 360
//@node 0D572DC8-0 1450 200
//@node 33F9876A-0 1245 305
//@node 1BDB9887-0 1040 305
//@node FAE53F97-0 1730 360
//@node D5E0E344-0 2010 360
//@node D7576C24-0 1805 465
//@node D1A1BA06-0 1600 465
//@node 4363BA80-0 2290 360
//@node 32B872FB-0 2570 360
//@node 586F6A91-0 2365 465
//@node 8EA91662-0 2160 465
//@node 8859BC97-0 2850 360
//@node 41CB0B8C-0 3130 360
//@node 137342D3-0 2925 465
//@node 3301E1BB-0 2720 465
//@node 8149C0B6-0 3410 360
//@node D472C08D-0 3690 360
//@node 4373E47D-0 3485 465
//@node CFDC9A92-0 3280 465
//@node 105252EB-0 3970 360
//@node 47318A5F-0 4250 360
//@node 21C9FE24-0 4045 465
//@node 0A0D561F-0 3840 465
//@node C6DE7B65-0 4530 360
//@node 4BC809E9-0 4810 360
//@node BF28B1D9-0 4605 465
//@node F3DEAB70-0 4400 465
//@node C2638770-0 5090 360
//@node 5AE1D168-0 5370 360
//@node 34BE0F67-0 5165 465
//@node 1CAB006B-0 4960 465
//@node C7C5F947-0 5650 360
//@node 4E993D93-0 5930 360
//@node 74E4132D-0 5725 465
//@node 0D3C60BE-0 5520 465
//@node FD0FB70E-0 6210 360
//@node 70215ED4-0 40 40
//@node 6232355E-0 330 40
//@node 0256CB9E-0 125 145
//@node ED567F61-0 40 40
//@node 68CC93E8-0 330 40
//@node F269D882-0 125 145
//@node A011F29E-0 40 40
//@node 9DEA675E-0 330 40
//@node 1686B1B5-0 125 145
//@node E21D70C9-0 40 40
//@node 868D81FA-0 330 40
//@node 7B9EADCB-0 125 145
//@node 8F3C8FFC-0 40 40
//@node 87879C82-0 330 40
//@node 401F2FE7-0 125 145
//@node 803C115E-0 40 40
//@node 7E374AD2-0 330 40
//@node 488C0122-0 125 145
//@node E50F005D-0 40 40
//@node 69B9F0A7-0 330 40
//@node DE5594DC-0 125 145
//@node E20EFBA4-0 40 40
//@node 2CC40BD7-0 330 40
//@node 2615A38B-0 125 145
//@node E30EFD37-0 40 40
//@node C409C0C7-0 330 40
//@node 1A31E4A9-0 125 145
//@node 426164B3-0 40 40
//@node 48FF605F-0 330 40
//@node 8FFFFF3F-0 610 40
//@node 3C6A6943-0 890 40
//@node 2AFB3EA7-0 1170 40
//@node A95CC391-0 1450 40
//@node D0803DE6-0 40 40
//@node DECA996E-0 330 40
//@node 26B9006B-0 610 40
//@node BC56E455-0 890 40
//@node 25882EE6-0 1170 40
//@node 9E02A147-0 1450 40
//@node 1B521F30-0 40 40
//@node 71C50C4F-0 330 40
//@node 709AE758-0 610 40
//@node 35E466F3-0 890 40
//@node 3DCA411D-0 1170 40
//@node 26C1D521-0 1450 40
//@node DC5B41C5-0 40 40
//@node 43D17746-0 330 40
//@node 50D44D22-0 610 40
//@node 503CEEAD-0 890 40
//@node 5B5CAD7C-0 1170 40
//@node C2C4ACCF-0 1450 40
//@node 11B2C041-0 40 40
//@node A515CA1B-0 330 40
//@node 08085484-0 610 40
//@node 9F792917-0 890 40
//@node 3735DBF7-0 1170 40
//@node 024C428D-0 1450 40
//@node F33CECA8-0 40 40
//@node DB53A3FE-0 330 40
//@node EA256E7A-0 610 40
//@node B326CC85-0 890 40
//@node 3F92215E-0 1170 40
//@node 532EB497-0 1450 40
//@node D0A8F034-0 40 40
//@node 9B898E4F-0 330 40
//@node C86F8D72-0 610 40
//@node 84B545AE-0 890 40
//@doomscript-blueprint end
