namespace map_site3 {

	void setup_objects ()
	{	
		// Cache the sounds... -Xian

		sys.cacheSoundShader ("train_door_close");
		sys.cacheSoundShader ("train_door_open");
		
		$transport.accelTime (.5);
		$transport.decelTime (.5);

        $transport_door.accelTime (.2);
		$transport_door.decelTime (.1);
        $transport_door.time (.5);
		$transport_door.bind ($transport);
        $transport_door_open1.bind ($transport);
        $transport_door_close1.bind ($transport);
        $transport_door_close2.bind ($transport);
		$transport_activator_2.bind ($transport);

		$pistrod1.bind ($piston1);
		$pistrod2.bind ($piston2);
		$pistrod3.bind ($piston3);
 
		$piston1.time (.125);
		$pistrod1.time (.125);
		$piston2.time (.125);
		$pistrod2.time (.125);
		$piston3.time (.125);
		$pistrod3.time (.125);
		$crankshaft.time (.125);

        $arm_base.time (1);
        $arm_base.accelTime (.5);
        $arm_base.decelTime (.1);

        $metaldoor.time (.05);

        $finger1.bind ($hand);
        $finger2.bind ($hand);
        $hand.bind ($arm);
        $arm.bind ($arm_anchor);
        $arm_anchor.bind ($arm_base);

		$pipe_crash.bind ($pipe_crash_anchor);
		$pipe_crash_anchor.accelTime (.4);
		$pipe_crash_anchor.time (1);
		$skcube_crash.bind ($skcube_crash_anchor);
		$skcube_crash_anchor.accelTime (.4);
		$skcube_crash_anchor.time (.8);

        $walkway1_anchor.time (.5); 
        $walkway1_anchor.accelTime (.5);
        $walkway2_anchor.time (.5); 
        $walkway2_anchor.accelTime (.5);
        $walkway1edge_anchor.time (.3); 
        $walkway1edge_anchor.accelTime (.3);
        $walkway2edge_anchor.time (.3); 
        $walkway2edge_anchor.accelTime (.3);

        $walkway1.bind ($walkway1_anchor);
        $walkway1edge.bind ($walkway1edge_anchor);
        $walkway1edge_anchor.bind ($walkway1);
        $walkway2.bind ($walkway2_anchor);
        $walkway2edge.bind ($walkway2edge_anchor);
        $walkway2edge_anchor.bind ($walkway2);
	}

	////////////////////////////////////////////////////
	//
	//	transport
	//
	////////////////////////////////////////////////////

	void call_transport ()
	{
        sys.trigger ($door_block_trigger);
        sys.trigger ($trigger_objectivecomplete_2);
		$transport.time (10);
		$transport.moveTo ($transport_spot1);
		sys.waitFor ($transport);
		$transport_activator_2.unbind ();
		$transport_activator_1.bind ($transport);       
		$transport_door.unbind ();
        sys.trigger ($trans_trigger);
        sys.trigger ($trigger_objective_3);
	}

	void move_transport ()
	{
		sys.trigger ($airdoor1_lf);
		$transport.time (4);
		$transport.moveTo ($transport_spot1a);
		sys.waitFor ($transport);
		sys.wait (.5);
		sys.trigger ($airdoor1_lf);
		sys.wait (2);
		sys.trigger ($airdoor2_lf);
		sys.waitFor ($airdoor2_lf);
		sys.trigger ($airdoor2_relay);
		sys.trigger ($airdoor3_relay);
		$transport.time (7);
		$transport.moveTo ($transport_spot2);
		sys.waitFor ($transport);
		sys.trigger ($airdoor3_lf);
                sys.trigger ($trans_trigger2);
	}

    void transport_door_close ()
	{			
		$transport_door.startSoundShader ("train_door_close", SND_CHANNEL_VOICE);
		$transport_door.moveTo ($transport_door_close1);
		sys.waitFor ($transport_door);
                $transport_door.moveTo ($transport_door_close2);
                sys.waitFor ($transport_door);
                $transport_door.bind ($transport);
	}

    void transport_door_open ()
	{
		$transport_door.unbind ();	
		$transport_door.startSoundShader ("train_door_open", SND_CHANNEL_VOICE);
		$transport_door.moveTo ($transport_door_close1);
		sys.waitFor ($transport_door);
                $transport_door.moveTo ($transport_door_open1);
                sys.waitFor ($transport_door);
	}

	void airdoor1_open ()
	{
		sys.trigger ($airdoor1_lf);
	}
	void airdoor2_open ()
	{
		sys.trigger ($airdoor2_lf);
	}
	void airdoor3_open ()
	{
		sys.trigger ($airdoor3_lf);
	}
	void airdoor1_close ()
	{
		sys.trigger ($airdoor1_lf);
	}
	void airdoor2_close ()
	{
		sys.trigger ($airdoor2_lf);
	}
	void airdoor3_close ()
	{
		sys.trigger ($airdoor3_lf);
	}

    ////////////////////////////////////////////////////
	//
	//	archvile room
	//
	////////////////////////////////////////////////////



	void archvile_start ()
	{
        sys.trigger ($blight_trigger1);
        sys.wait (.7);
        sys.trigger ($blight_trigger3);
        sys.wait (.2);
        sys.trigger ($blight_trigger2);
        sys.wait (.6);
        sys.trigger ($alight_trigger1);
        sys.trigger ($alight_trigger2);
        sys.trigger ($alight_trigger3);
        sys.trigger ($alight_trigger4);
        sys.trigger ($alight_trigger5);
        sys.trigger ($alight_trigger6);       
                 
	    $walkway1_anchor.rotateOnce ('-88 0 0');
        $walkway1edge_anchor.rotateOnce ('84 0 0');
        $walkway2_anchor.rotateOnce ('0 0 -88');
        $walkway2edge_anchor.rotateOnce ('0 0 84');
        sys.waitFor ($walkway1_anchor);
        sys.wait (1);

        sys.trigger ($candles_trigger);
        sys.wait (.5);
		sys.trigger ($archvile_trigger);
        sys.wait (.5);
        sys.trigger ($fire_trigger);
        sys.trigger ($speaker_flames_1);
		sys.trigger ($speaker_flames_2);
		sys.trigger ($speaker_av_mood);
	}

	////////////////////////////////////////////////////
	//
	//	misc
	//
	////////////////////////////////////////////////////
	 
	void pipe_crash_trigger ()
	{
		$pipe_crash_anchor.rotateOnce ('-20 0 25');
		$skcube_crash_anchor.rotateOnce ('0 10 90');
	}

	////////////////////////////////////////////////////
	//
	// crane arm movement
	//
	////////////////////////////////////////////////////
	void crane_move ()
	{
		while (1) {
			
			$arm_base.startSoundShader ("s3_arm_back", SND_CHANNEL_ANY );
			$arm_base.move ( SOUTH, 256 );
			sys.waitFor ($arm_base);
			sys.trigger ($doorbang);
			sys.trigger ($doorspark);
			$metaldoor.move (SOUTH,1);

			$arm_anchor.time (.1);                
			$arm_anchor.decelTime (.05);

			$arm_anchor.rotateOnce ('0 0 -4');
			sys.waitFor ($arm_anchor);
			$metaldoor.move (NORTH,1);

			$arm_anchor.rotateOnce ('0 0 5');
			sys.waitFor ($arm_anchor);
			$arm_anchor.time (.08);                                
			$arm_anchor.rotateOnce ('0 0 -1.5');
			sys.waitFor ($arm_anchor);
			$arm_anchor.time (.04);
			$arm_anchor.rotateOnce ('0 0 0.5');
			sys.waitFor ($arm_anchor);

			// need sound here
			
			sys.trigger ($armsound1);
			$arm_base.move ( NORTH, 256 );
			sys.waitFor ($arm_base);

			$arm_anchor.time (.2);                
			$arm_anchor.decelTime (.1);

			$arm_anchor.rotateOnce ('0 0 6');
			sys.waitFor ($arm_anchor);
			$arm_anchor.rotateOnce ('0 0 -7');
			sys.waitFor ($arm_anchor);
			$arm_anchor.time (.15);                
			$arm_anchor.rotateOnce ('0 0 2');
			sys.waitFor ($arm_anchor);
			$arm_anchor.time (.08);
			$arm_anchor.rotateOnce ('0 0 -1');
			sys.waitFor ($arm_anchor);
		} 
	}

	////////////////////////////////////////////////////
	//
	//	piston movement
	//
	////////////////////////////////////////////////////
	void piston_move ()
	{
		while (1) 
		{
		
		$piston1.move ( DOWN, 6 );
		$pistrod1.rotateOnce ( '0 0 -26.56' );
		$piston2.move ( UP, 6 );
		$pistrod2.rotateOnce ( '0 0 26.56' );
		$piston3.move ( DOWN, 6 );
		$pistrod3.rotateOnce ( '0 0 -26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( DOWN, 6 );
		$pistrod1.rotateOnce ( '0 0 26.56' );
		$piston2.move ( UP, 6 );
		$pistrod2.rotateOnce ( '0 0 -26.56' );
		$piston3.move ( DOWN, 6 );
		$pistrod3.rotateOnce ( '0 0 26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( UP, 6 );
		$pistrod1.rotateOnce ( '0 0 26.56' );
		$piston2.move ( DOWN, 6 );
		$pistrod2.rotateOnce ( '0 0 -26.56' );
		$piston3.move ( UP, 6 );
		$pistrod3.rotateOnce ( '0 0 26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		$piston1.move ( UP, 6 );
		$pistrod1.rotateOnce ( '0 0 -26.56' );
		$piston2.move ( DOWN, 6 );
		$pistrod2.rotateOnce ( '0 0 26.56' );
		$piston3.move ( UP, 6 );
		$pistrod3.rotateOnce ( '0 0 -26.56' );
		$crankshaft.rotateOnce ( '0 0 90' );
		sys.waitFor ($piston1);

		} 
	}

	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void main ()
	{
		sys.cacheSoundShader ("s3_arm_back");
		setup_objects ();
        piston_move ();               
 
	}
}

//@doomscript-blueprint begin 6
//@source 24F65211
//@catalog 0C260740
//@node 7AEA71C1-0 40 40
//@node 13D0D004-0 330 40
//@node 140220F8-0 610 40
//@node 1E2F256E-0 890 40
//@node FC1E093F-0 1170 40
//@node 4CE68F66-0 1450 40
//@node 4E3A47BE-0 1730 40
//@node B3932B89-0 2010 40
//@node 93B105B7-0 2290 40
//@node 6FFAF88F-0 2570 40
//@node 4B2AA953-0 2850 40
//@node 192B06E8-0 3130 40
//@node 3B88EE87-0 3410 40
//@node D83A3A14-0 3690 40
//@node 6E82371A-0 3970 40
//@node 6FF82690-0 4250 40
//@node CF75B518-0 4530 40
//@node ECDAD9B2-0 4810 40
//@node FBC2D5DB-0 5090 40
//@node 493C2BD1-0 5370 40
//@node 991AF036-0 5650 40
//@node 273887E4-0 5930 40
//@node FE61B825-0 6210 40
//@node 98B325B3-0 6490 40
//@node 59433E8F-0 6770 40
//@node D669F946-0 7050 40
//@node CA58042E-0 7330 40
//@node 2FC5479F-0 7610 40
//@node 87806712-0 7890 40
//@node 1BEABFE5-0 8170 40
//@node 5C3A437E-0 8450 40
//@node E7531EE4-0 8730 40
//@node 5BBF8C6C-0 9010 40
//@node 5E667634-0 9290 40
//@node 049AE7A7-0 9570 40
//@node 4C4850A0-0 9850 40
//@node CC83DEE5-0 10130 40
//@node 4C747065-0 10410 40
//@node 072A281A-0 10690 40
//@node 9F8EF98E-0 10970 40
//@node 33B35467-0 11250 40
//@node 588C8951-0 11530 40
//@node 84B17E31-0 11810 40
//@node 27F0C77F-0 12090 40
//@node E8A08984-0 12370 40
//@node 9F125AC0-0 12650 40
//@node FF548960-0 12930 40
//@node 8248E858-0 13210 40
//@node 5EB8664B-0 13490 40
//@node A868D7C4-0 13770 40
//@node D3719540-0 14050 40
//@node BDFFD6A9-0 14330 40
//@node 8BC58D2F-0 40 40
//@node 72A365AB-0 330 40
//@node 47E71760-0 610 40
//@node E016D55C-0 890 40
//@node 688BBB71-0 1170 40
//@node 245A5B93-0 1450 40
//@node E4F0902F-0 1730 40
//@node 0B5A78BE-0 2010 40
//@node 4B3459DF-0 2290 40
//@node 6CDE8FEB-0 2570 40
//@node 8505723C-0 2850 40
//@node 784F491E-0 40 40
//@node 323C2C81-0 330 40
//@node 679ED2EC-0 610 40
//@node 2CA8B4B7-0 890 40
//@node 351EC01E-0 1170 40
//@node 368E46F9-0 1450 40
//@node 323C2C81-1 1730 40
//@node 2FAB4DCE-0 2010 40
//@node 17767F16-0 2290 40
//@node 748669DA-0 2570 40
//@node 1EDBD1AD-0 2850 40
//@node 88994C16-0 3130 40
//@node 2E758ECD-0 3410 40
//@node 120BB909-0 3690 40
//@node 351EC01E-1 3970 40
//@node 004DF5AB-0 4250 40
//@node 65E3A014-0 4530 40
//@node EC43384C-0 40 40
//@node E727DF26-0 330 40
//@node 430061C2-0 610 40
//@node DB6C1FCD-0 890 40
//@node 56141F5F-0 1170 40
//@node DB6C1FCD-1 1450 40
//@node 9C45F7AC-0 1730 40
//@node B801AF00-0 40 40
//@node BA4461F2-0 330 40
//@node 2931ABC6-0 610 40
//@node DD4F4C3E-0 890 40
//@node E0A82DF1-0 1170 40
//@node B482504C-0 1450 40
//@node E0A82DF1-1 1730 40
//@node C3892C0B-0 40 40
//@node 178F49F4-0 330 40
//@node 0BFC0CF8-0 40 40
//@node F0173D28-0 330 40
//@node 147E8045-0 40 40
//@node 613B2EA8-0 330 40
//@node 7804FA3D-0 40 40
//@node 7A8AC82E-0 330 40
//@node F9278FF4-0 40 40
//@node F2971C4C-0 330 40
//@node 13884677-0 40 40
//@node F3FA80DE-0 330 40
//@node 96031BF4-0 40 40
//@node D23A6C81-0 330 40
//@node FA91F125-0 610 40
//@node FFF5C05F-0 890 40
//@node 59767C8A-0 1170 40
//@node 8BB29900-0 1450 40
//@node 05B02F86-0 1730 40
//@node 932A9BBC-0 2010 40
//@node 5A01579D-0 2290 40
//@node 651F95FE-0 2570 40
//@node 4BFA6A1F-0 2850 40
//@node D7B742C0-0 3130 40
//@node 1E3F1641-0 3410 40
//@node B76CB8C2-0 3690 40
//@node DAFC4ED6-0 3970 40
//@node 0A3E1725-0 4250 40
//@node 421FCF53-0 4530 40
//@node C49E1838-0 4810 40
//@node 6A41391D-0 5090 40
//@node 79E202B8-0 5370 40
//@node 184D2BD3-0 5650 40
//@node 5EABB95A-0 5930 40
//@node 184D2BD3-1 6210 40
//@node C238FA98-0 6490 40
//@node 8B5EABBD-0 6770 40
//@node C487EFDC-0 7050 40
//@node FEB36E88-0 7330 40
//@node 633D60FE-0 40 40
//@node 4549E048-0 330 40
//@node B3CE592F-0 610 40
//@node AD80179A-0 40 40
//@node 0D265209-0 330 40
//@node F0BDBB3B-0 125 145
//@node 4F960BCD-0 610 200
//@node 600AB02F-0 890 200
//@node 4C2F1263-0 1170 200
//@node 730BFA63-0 1450 200
//@node 73176292-0 1730 200
//@node 59DA6058-0 2010 200
//@node 26460100-0 2290 200
//@node DBE62F65-0 2570 200
//@node F769553B-0 2850 200
//@node 0CC8B637-0 3130 200
//@node 00F8C46A-0 3410 200
//@node 01FFA373-0 3690 200
//@node 0CC8B637-1 3970 200
//@node DE2A0979-0 4250 200
//@node BD6BE8DD-0 4530 200
//@node 0CC8B637-2 4810 200
//@node B1F11FFD-0 5090 200
//@node D9E4B8C5-0 5370 200
//@node 0CC8B637-3 5650 200
//@node E2542FEB-0 5930 200
//@node 017FC3F9-0 6210 200
//@node 4C2F1263-1 6490 200
//@node 6CCDD481-0 6770 200
//@node F30B8335-0 7050 200
//@node 4C89E820-0 7330 200
//@node 0CC8B637-4 7610 200
//@node B54D3F68-0 7890 200
//@node 0CC8B637-5 8170 200
//@node F95A1E5B-0 8450 200
//@node D30E3AA4-0 8730 200
//@node 0CC8B637-6 9010 200
//@node DE2A0979-1 9290 200
//@node A2B6AB06-0 9570 200
//@node 0CC8B637-7 9850 200
//@node 61759C34-0 40 40
//@node AA716E8F-0 330 40
//@node 927A693A-0 125 145
//@node 849AD7A1-0 610 200
//@node C555D9C0-0 890 200
//@node 8E3DB735-0 1170 200
//@node B143CF0A-0 1450 200
//@node CB253FC3-0 1730 200
//@node 61F9B53A-0 2010 200
//@node 6EB465F2-0 2290 200
//@node 19AE1375-0 2570 200
//@node 849AD7A1-1 2850 200
//@node 4CDFC84F-0 3130 200
//@node 8E3DB735-1 3410 200
//@node 40E95B7B-0 3690 200
//@node CB253FC3-1 3970 200
//@node 85934A15-0 4250 200
//@node 6EB465F2-1 4530 200
//@node 19AE1375-1 4810 200
//@node BE8E7308-0 5090 200
//@node 4CDFC84F-1 5370 200
//@node A1012CA8-0 5650 200
//@node 40E95B7B-1 5930 200
//@node C4A4B0DE-0 6210 200
//@node 85934A15-1 6490 200
//@node 6EB465F2-2 6770 200
//@node 19AE1375-2 7050 200
//@node BE8E7308-1 7330 200
//@node C555D9C0-1 7610 200
//@node A1012CA8-1 7890 200
//@node B143CF0A-1 8170 200
//@node C4A4B0DE-1 8450 200
//@node 61F9B53A-1 8730 200
//@node 6EB465F2-3 9010 200
//@node 19AE1375-3 9290 200
//@node 32687650-0 40 40
//@node 7AD0A904-0 330 40
//@node DC4C0128-0 610 40
//@node 1FEC7425-0 890 40
//@doomscript-blueprint end
