namespace map_delta1 {
	float power = 0 ;
	float rgb_modifier = 0;

	// number of security lights(sl) and doors(dl)
	float sl_count = 5;
	float dl_count = 8;


	////////////////////////////////////////////////////
	//
	//	Initial movements etc...
	//
	////////////////////////////////////////////////////
	void init_world()
	{
		////////////////////////////////////////////////////
		//SENECA's HOLOGRAM INITS
		$hologram.hide();
        $hologram.setColor  (.3, .35, .45);	//inital medium blue
		$hologram.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram.setShaderParm(4,100);		//the bottom textures scale from the center of the faces out to the edges.
		$hologram.setShaderParm(5,0);		//the delta 1 ring's RGB defaults to 0
		$hologram.setShaderParm(6,100);		//the plane beneath the hologram starts infinitely small
		$hologram.setShaderParm(7,0);		//rgb of tops of rooms
		
		//the important rooms
		$hologram1.hide();
		$hologram1.bind ($hologram1_1_anchor);
		$hologram1.setColor  (.6, .7, .9);	//inital light blue
		$hologram1.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram1.setShaderParm(4,100);		//the bottom textures scale from the center of the faces out to the edges.
		$hologram1.setShaderParm(7,0);		//rgb of tops of rooms

		$hologram2.hide();
		$hologram2.bind ($hologram2_1_anchor);
		$hologram2.setColor  (.6, .7, .9);	
		$hologram2.setShaderParm(3,-0.6);	
		$hologram2.setShaderParm(4,100);		
		$hologram2.setShaderParm(7,0);		
		
		$hologram3.hide();
		$hologram3.bind ($hologram3_1_anchor);
		$hologram3.setColor  (.6, .7, .9);	
		$hologram3.setShaderParm(3,-0.6);	
		$hologram3.setShaderParm(4,100);		
		$hologram3.setShaderParm(7,0);		
		
		$hologram4.hide();
		$hologram4.bind ($hologram4_1_anchor);
		$hologram4.setColor  (.6, .7, .9);	
		$hologram4.setShaderParm(3,-0.6);	
		$hologram4.setShaderParm(4,100);		
		$hologram4.setShaderParm(7,0);		
		
		$hologram5.hide();
		$hologram5.bind ($hologram5_1_anchor);
		$hologram5.setColor  (.6, .7, .9);	
		$hologram5.setShaderParm(3,-0.6);	
		$hologram5.setShaderParm(4,100);		
		$hologram5.setShaderParm(7,0);		
		
		//the important rooms' glows
		$hologram1_1.hide();  
		$hologram1_1.bind ($hologram1);
		$hologram1_1.setShaderParm(3,0);		//RGB of the red boxes outside each hologram. starts at 100% transparent.
		$hologram1_1.setShaderParm(4,10);		//height of the red boxes outside each hologram.  starts real small
		$hologram1_1.setShaderParm(5,0);		//scale of the round disc
		$hologram1_1.setShaderParm(6,0);		//RGB of the round plate that grows when you select an important area.
		$hologram1_1.setShaderParm(7,0);		//RGB of the sprite round plate

		$hologram2_1.hide();  
		$hologram2_1.bind ($hologram2);
		$hologram2_1.setColor (.6, .7, .9);	
		$hologram2_1.setShaderParm(3,0);		
		$hologram2_1.setShaderParm(4,10);		
		$hologram2_1.setShaderParm(5,0);		
		$hologram2_1.setShaderParm(6,0);		

		$hologram3_1.hide();  
		$hologram3_1.bind ($hologram3);
		$hologram3_1.setColor (.6, .7, .9);	
		$hologram3_1.setShaderParm(3,0);		
		$hologram3_1.setShaderParm(4,10);		
		$hologram3_1.setShaderParm(5,0);		
		$hologram3_1.setShaderParm(6,0);		

		$hologram4_1.hide();  
		$hologram4_1.bind ($hologram4);
		$hologram4_1.setColor (.6, .7, .9);	
		$hologram4_1.setShaderParm(3,0);		
		$hologram4_1.setShaderParm(4,10);		
		$hologram4_1.setShaderParm(5,0);		
		$hologram4_1.setShaderParm(6,0);		

		$hologram5_1.hide();  
		$hologram5_1.bind ($hologram5);
		$hologram5_1.setColor (.6, .7, .9);	
		$hologram5_1.setShaderParm(3,0);		
		$hologram5_1.setShaderParm(4,10);		
		$hologram5_1.setShaderParm(5,0);		
		$hologram5_1.setShaderParm(6,0);		


		//END SENECA's HOLOGRAM INITS
		////////////////////////////////////////////////////

		$lobby_spawn_trigger.disable();
		$lobby_spawn_trigger2.disable();

		// scipull stuff
		$delta1_scipull_1.hide();
		$scipull_panel_end.hide();

		// sizzor lift binds
		$siz_axle_low.bind ($siz_lowlegr);
		$siz_axle_left.bind ($siz_lowlegr);
		$siz_toplegl.bind ($siz_axle_left);
		$siz_axle_top.bind ($siz_toplegl);
		$siz_toplegr.bind ($siz_axle_top);
		$siz_axle_right.bind ($siz_toplegr);
		$siz_lowlegl.bind ($siz_axle_right);
		
		$siz_topcr.bindPosition ($siz_toplegl);
		$siz_topcl.bindPosition ($siz_toplegr);

		$siz_lowcl.bindPosition ($siz_lowlegl);

		$siz_top.bind ($siz_topcr);
		$siz_control.bind ($siz_top);

		// sizzor accel and decel times
		$siz_toplegl.time ( 1.5 );
		$siz_toplegr.time ( 1.5 );
		$siz_lowlegl.time ( 1.5 );
		$siz_lowlegr.time ( 1.5 );

		$siz_toplegl.accelTime ( .5 );
		$siz_toplegl.decelTime ( .5 );
		$siz_toplegr.accelTime ( .5 );
		$siz_toplegr.decelTime ( .5 );

		$siz_lowlegl.accelTime ( .5 );
		$siz_lowlegl.decelTime ( .5 );
		$siz_lowlegr.accelTime ( .5 );
		$siz_lowlegr.decelTime ( .5 );

		// reactor setup
		$outerring_anchor.rotateOnce ('-45 0 0');
		$innerring_anchor.rotateOnce ('-30 0 0');
	}


	////////////////////////////////////////////////////
	//
	//	Global parm ramp up or down
	//
	////////////////////////////////////////////////////
	void light_ramp( float rgb_start, float rgb_end, float time_val ) 
	{
		float i, t, v;

		t = time_val * GAME_FPS;
		for ( i = 0; i < t; i++ ) {
			v = rgb_start + ( rgb_end - rgb_start ) * ( i / t );
			sys.setShaderParm( 0, v );
			sys.setShaderParm( 1, v );
			sys.setShaderParm( 2, v );
			sys.wait( GAME_FRAMETIME );
		}
		sys.setShaderParm( 0, rgb_end );
		sys.setShaderParm( 1, rgb_end );
		sys.setShaderParm( 2, rgb_end );
	}



	////////////////////////////////////////////////////
	//
	//	Power flux
	//
	////////////////////////////////////////////////////
	void power_flux()
	{
		float i;
		float ran_loop, ran_new, ran_time;
		float old;

		old = .2;
		ran_loop = (sys.random(10) + 5);

		for (i=1; i<=ran_loop; i++){
			ran_new = sys.random(1.5);
			ran_time = sys.random(1);
			light_ramp( old, ran_new, ran_time );

			old = ran_new;
		}

		light_ramp( old, .15, .3 );
	}



	////////////////////////////////////////////////////
	//
	//	Low Power Loop
	//  random power flucuations 
	//
	////////////////////////////////////////////////////
	void low_power_loop()
	{
		//sys.print ("begin low_power_loop\n");
		//sys.print ("power level =" + power + "\n");
		float ran;
		ran = sys.random (3);
		sys.wait (ran);

		while (power == 1){
			ran = (sys.random(4) + 12);
			//sys.print ("next power surge in " + ran + " seconds\n");
			sys.wait (ran);
			
			power_flux(); 
			}

		//sys.print ("made it to the end of low power loop\n");
		if (power==2){
			float ii;
			float rate;

			rate = GAME_FRAMETIME * 0.25;
			for( ii = rgb_modifier; ii <= 1; ii += rate ) {
				sys.setShaderParm(0,(ii*.65));
				sys.setShaderParm(1,(ii*.65));
				sys.setShaderParm(2,(ii*.75));

				sys.wait (GAME_FRAMETIME);
			}
		}
	}



	////////////////////////////////////////////////////
	//
	//	security lights on
	//
	////////////////////////////////////////////////////
	void seclights_on()
	{
		entity	sl_ent, ssl_ent1, bsl_ent1, ssl_ent2, bsl_ent2;
		float	i;
		
		for (i=1; i<=sl_count; i++){
			sl_ent=sys.getEntity ("sl_" + i);

			ssl_ent1=sys.getEntity ("ssl_" + i + "_a");
			ssl_ent2=sys.getEntity ("ssl_" + i + "_b");

			bsl_ent1=sys.getEntity ("bsl_" + i + "_a");
			bsl_ent2=sys.getEntity ("bsl_" + i + "_b");

			sl_ent.setColor( .627, .1, 0 );
			ssl_ent1.On();
			ssl_ent2.On();
			bsl_ent1.On();
			bsl_ent2.On();
		}
	}


	////////////////////////////////////////////////////
	//
	//	security lights off
	//
	////////////////////////////////////////////////////
	void seclights_off()
	{
		entity	sl_ent, ssl_ent1, bsl_ent1, ssl_ent2, bsl_ent2;
		float	i;
		
		for (i=1; i<=sl_count; i++){
			sl_ent=sys.getEntity ("sl_" + i);

			ssl_ent1=sys.getEntity ("ssl_" + i + "_a");
			ssl_ent2=sys.getEntity ("ssl_" + i + "_b");

			bsl_ent1=sys.getEntity ("bsl_" + i + "_a");
			bsl_ent2=sys.getEntity ("bsl_" + i + "_b");

			sl_ent.setColor( 0,0,0 );
			ssl_ent1.Off();
			ssl_ent2.Off();
			bsl_ent1.Off();
			bsl_ent2.Off();
		}
	}


	////////////////////////////////////////////////////
	//
	//	hologram on
	//
	////////////////////////////////////////////////////
	void hologram_on()
	{
		$hologram_light_big.setColor( .75, .8, .85 );

		// trigger the initial power up sound in control room
		// sys.trigger ($warning_speaker_initial);

		// sci stuff
		$delta1_scipull_1.show();
		$scipull_panel_end.show();

		$scidead.remove();
		$scipull_panel_start.remove();

		$lobby_spawn_trigger.enable();
		$lobby_spawn_trigger2.enable();

		// data linker show and move down
		$datalinker.startSoundShader ("hologram_datalinker", SND_CHANNEL_VOICE );
		$datalinker.time(.75);
		$datalinker.show();
		$datalinker.move ( DOWN, 8 );
	}


	////////////////////////////////////////////////////
	//
	//	hologram off
	//
	////////////////////////////////////////////////////
	void hologram_off()
	{
		$hologram_light_big.setColor( .75, .8, .85 );
	}

	////////////////////////////////////////////////////
	//
	//	door lights on
	//
	////////////////////////////////////////////////////
	void doorlights_on()
	{
		entity	dl_ent1, dl_ent2, dl_ent3 ;
		float	i;
		
		for (i=1; i<=dl_count; i++){
			dl_ent1=sys.getEntity ("dl_" + i);
			dl_ent2=sys.getEntity ("dl_" + i + "_a");
			dl_ent3=sys.getEntity ("dl_" + i + "_b");

			dl_ent1.setColor( .627, .1, 0 );
			dl_ent2.setColor( .627, .1, 0 );
			dl_ent3.setColor( .627, .1, 0 );
		}
	}


	///////////////////////////////////////////////////
	//
	//	door lights off
	//
	////////////////////////////////////////////////////
	void doorlights_off()
	{
		entity	dl_ent1, dl_ent2, dl_ent3 ;
		float	i;
		
		for (i=1; i<=dl_count; i++){
			dl_ent1=sys.getEntity ("dl_" + i);
			dl_ent2=sys.getEntity ("dl_" + i + "_a");
			dl_ent3=sys.getEntity ("dl_" + i + "_b");

			dl_ent1.setColor( 1, 1, 1 );
			dl_ent2.setColor( 1, 1, 1 );
			dl_ent3.setColor( 1, 1, 1 );
		}
	}


	////////////////////////////////////////////////////
	//
	//	Power is offline
	//	level 0
	//
	////////////////////////////////////////////////////
	void power_level_0()
	{
		float i;
		float rate;

		rate = GAME_FRAMETIME * 0.25;
		for( i = rgb_modifier; i >= 0; i -= rate ) {

			sys.setShaderParm(0,i);
			sys.setShaderParm(1,i);
			sys.setShaderParm(2,i);

			sys.wait (GAME_FRAMETIME);
		}

		// force all to 0,0,0 just incase there is a fraction left over...
		// to make sure the shadows are off
		sys.setShaderParm(0,0);
		sys.setShaderParm(1,0);
		sys.setShaderParm(2,0);

		// turn on the security lights
		// turn on door lights to red
		// turn the hologram light off
		thread seclights_on();
		thread doorlights_on();
		thread hologram_off();

		// set the rgb modifier tracking variable
		rgb_modifier = 0;

	//	sys.print ( "power offline\n" );
		power = 0;
	}


	////////////////////////////////////////////////////
	//
	//	Power to level 1
	//
	////////////////////////////////////////////////////
	void power_level_1()
	{
		// turn security lights off
		// doorlights back to white if red
		thread seclights_off();
		thread doorlights_off();
		sys.wait (1);

		float i;
		float rate;

		if ( power >= 1 ){
			rate = GAME_FRAMETIME * 0.25;
			for( i = rgb_modifier; i >= .25; i -= rate ) {

				sys.setShaderParm(0,i);
				sys.setShaderParm(1,i);
				sys.setShaderParm(2,i);

				sys.wait (GAME_FRAMETIME);
			}
		} else {
			rate = GAME_FRAMETIME * 0.25;
			for( i = rgb_modifier; i <= .25; i += rate ) {

				sys.setShaderParm(0,i);
				sys.setShaderParm(1,i);
				sys.setShaderParm(2,i);

				sys.wait (GAME_FRAMETIME);
			}
		}

		// set the rgb modifier tracking variable
		rgb_modifier = .25;

	//	sys.print ( "power 10%\n" );
		power = 1;

		low_power_loop();
	}


	////////////////////////////////////////////////////
	//
	//	Power to level 2
	//
	////////////////////////////////////////////////////
	void power_level_2()
	{
		// turn security lights off
		// doorlights back to white if red
		// turn the hologram on if off
		power = 2;
		seclights_off();
		doorlights_off();
		hologram_on();

		float i;
		float rate;

		rate = GAME_FRAMETIME * 0.25;
		for( i = rgb_modifier; i <= 1; i += rate ) {

			sys.setShaderParm(0,(i*.65));
			sys.setShaderParm(1,(i*.65));
			sys.setShaderParm(2,(i*.75));

			sys.wait (GAME_FRAMETIME);
		}

		// set the rgb modifier tracking variable
		rgb_modifier = 1;

	}


	////////////////////////////////////////////////////
	//
	//	Computer Voice Loop
	//
	////////////////////////////////////////////////////
	void computer_voice_loop()
	{
		sys.killthread ( "map_delta1::pre_computer_voice_loop" );
	
		sys.wait (35);

		while (1){
			sys.trigger($speaker_reactor_offline); // 3.110
			sys.wait (3.4);
			sys.trigger($speaker_follow_procedure_orage); // 3.165
			sys.wait (3.165);

			sys.wait (35);
		}
	}


	////////////////////////////////////////////////////
	//
	//	Computer Voice Loop
	//	This is the initial voice loop
	//
	////////////////////////////////////////////////////
	void pre_computer_voice_loop()
	{
		while (power==0){
			sys.trigger($speaker_emr_pwr_only); // 2.219 seconds
			sys.wait (2.4);
			sys.trigger($speaker_operations_suspended); // 2.816 seconds
			sys.wait (2.816);

			sys.wait (35);
		}
	}


	////////////////////////////////////////////////////
	//
	//	Zombie falls out of panel and stuff
	//
	////////////////////////////////////////////////////
	void zombie_fallout()
	{
		// make the panel bounce back down

		sys.trigger ($zombie_fallout_speaker);

		$rot_panel_1.time (.25);
		$rot_panel_1.decelTime (.01);
		$rot_panel_1.rotateOnce ( '-10 0 0' );
		sys.waitFor ( $rot_panel_1 );

		$rot_panel_1.time (.2);
		$rot_panel_1.decelTime (.2);
		$rot_panel_1.rotateOnce ( '10 0 0' );
		sys.waitFor ( $rot_panel_1 );

		$rot_panel_1.time (.2);
		$rot_panel_1.decelTime (.01);
		$rot_panel_1.rotateOnce ( '-5 0 0' );
		sys.waitFor ( $rot_panel_1 );

		$rot_panel_1.time (.15);
		$rot_panel_1.decelTime (.15);
		$rot_panel_1.rotateOnce ( '5 0 0' );
		sys.waitFor ( $rot_panel_1 );

		$rot_panel_1.time (.1);
		$rot_panel_1.decelTime (.1);
		$rot_panel_1.rotateOnce ( '-2 0 0' );
		sys.waitFor ( $rot_panel_1 );

		$rot_panel_1.time (.1);
		$rot_panel_1.decelTime (.1);
		$rot_panel_1.rotateOnce ( '1 0 0' );
		sys.waitFor ( $rot_panel_1 );

	}


	////////////////////////////////////////////////////
	//
	//	reactor move
	//
	////////////////////////////////////////////////////
	void reactor_move ()
	{
		float i,v,t,blendtime,velmult;
		vector rotvector;

		blendtime = 7;
		velmult = .5;

		t = blendtime * GAME_FPS;

		for ( i = 10; i < t; i++ ) {
			v = (i * velmult);

			rotvector_x=v ;rotvector_y=0 ; rotvector_z=0;
			$reactor_innerring.rotate ( rotvector );

			rotvector_x=-v ;rotvector_y=0 ; rotvector_z=0;
			$reactor_outerring.rotate ( rotvector );

			sys.wait( GAME_FRAMETIME );
		}
	}

	////////////////////////////////////////////////////
	//
	//	reactor startup sequence
	//
	////////////////////////////////////////////////////
	void reactor_startup ()
	{
		// this will eventually have things like:
		// reactor ramping up
		// lights doing something

		sys.trigger ($reactor_speaker_startup);
		sys.trigger ($speaker_driver);
		
		$end_control.setGuiParm( "gui_parm5" , 0 );
		
		//call reactor start function
		thread reactor_move();
		
		sys.killthread ( "map_delta1::computer_voice_loop" );
		sys.killthread ( "map_delta1::low_power_loop" );
		sys.killthread ( "map_delta1::power_flux" );
		thread power_level_2();

		sys.wait(2);
		sys.trigger ($reactor_comp_reactoronline);
		//sys.print ( "trigger objective complete\n" );
		sys.trigger($reactor_objective_complete_trigger);
		sys.wait(4);
		//sys.print ( "trigger last objective\n" );
		sys.trigger($elevator_objective_trigger);


		sys.wait(4);
		sys.trigger ($reactor_speaker_loop);

		// trigger the door sign guis and kiosk guis
		sys.trigger($doorsigns_gui_relay);
	}


	////////////////////////////////////////////////////
	//
	//	Sound moving #1
	//  Plays a sound on a moving speaker
	//
	////////////////////////////////////////////////////
	void spooky_sound_1 ()
	{
		$ms1_speaker.bind ($ms1_mover);
		$ms1_mover.time (7.2);
		
		sys.trigger ($ms1_speaker);
		$ms1_mover.moveTo ($ms1_movepoint);

		sys.waitFor ($ms1_mover);
		$ms1_speaker.Off();
	}


	////////////////////////////////////////////////////
	//
	//	Random Spooky sounds #2
	//
	////////////////////////////////////////////////////
	void spooky_sound_2 ()
	{
			sys.trigger ($ran_speaker_1_1);
			sys.wait (1);
			sys.trigger ($ran_speaker_1_2);
	}


	////////////////////////////////////////////////////
	//
	//	Random Spooky sounds #3
	//
	////////////////////////////////////////////////////
	void spooky_sound_3 ()
	{
		float	numran;
		numran = sys.random(3);
		
		if (numran>=2){
			sys.trigger ($ran_speaker_2_1);
			sys.wait (.5);
			sys.trigger ($ran_speaker_2_2);
		} else if (numran>=1){
			sys.trigger ($ran_speaker_2_2);
			sys.wait (.5);
			sys.trigger ($ran_speaker_2_3);
		} else {
			sys.trigger ($ran_speaker_2_3);
			sys.wait (.5);
			sys.trigger ($ran_speaker_2_2);
			sys.trigger ($ran_speaker_2_1);
		}
	}


	////////////////////////////////////////////////////
	//
	//	Random Spooky sounds #4
	//
	////////////////////////////////////////////////////
	void spooky_sound_4 ()
	{
		float	numran;
		numran = sys.random(3);
		
		if (numran>=2){
			sys.trigger ($ran_speaker_3_1);
			sys.wait (.5);
			sys.trigger ($ran_speaker_3_4);
		} else if (numran>=1){
			sys.trigger ($ran_speaker_3_2);
			sys.wait (.5);
			sys.trigger ($ran_speaker_3_3);
		} else {
			sys.trigger ($ran_speaker_3_3);
			sys.wait (.5);
			sys.trigger ($ran_speaker_3_2);
			sys.trigger ($ran_speaker_3_1);
		}
	}



	////////////////////////////////////////////////////
	//
	//	Seneca's hologram initial activation (unhiding)
	//
	////////////////////////////////////////////////////

	void hologram_start ()
	{
		//temp
		$hologram1.setColor  (.6, .7, .9);	//inital light blue
		$hologram1.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram1.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram1.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		//temp
		$hologram2.setColor  (.6, .7, .9);	//inital light blue
		$hologram2.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram2.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram2.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		//temp
		$hologram3.setColor  (.6, .7, .9);	//inital light blue
		$hologram3.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram3.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram3.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		//temp
		$hologram4.setColor  (.6, .7, .9);	//inital light blue
		$hologram4.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram4.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram4.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		//temp
		$hologram5.setColor  (.6, .7, .9);	//inital light blue
		$hologram5.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram5.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram5.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		//temp
		$hologram.setColor  (.3, .45, .45);	//inital medium blue
		$hologram.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram.setShaderParm(4,100);		//the bottom textures scale from the center of the faces out to the edges.
		$hologram.setShaderParm(5,0);		//the delta 1 ring's RGB defaults to 0
		$hologram.setShaderParm(6,100);		//the plane beneath the hologram starts infinitely small
		$hologram.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram.show();
		thread interpolateShaderParm( $hologram, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		thread interpolateShaderParm( $hologram, 5, 0, 1, 5 );		//RGB in delta cylinder
		sys.wait (1);
		thread interpolateShaderParm( $hologram, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram1_start ()
	{
		//temp
		$hologram1.setColor  (.6, .7, .9);	//inital light blue
		$hologram1.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram1.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram1.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram1.show();
		thread interpolateShaderParm( $hologram1, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram1, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram1, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		sys.wait (1);
		thread interpolateShaderParm( $hologram1, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram1, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram2_start ()
	{
		//temp
		$hologram2.setColor  (.6, .7, .9);	//inital light blue
		$hologram2.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram2.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram2.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram2.show();
		thread interpolateShaderParm( $hologram2, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram2, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram2, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		sys.wait (1);
		thread interpolateShaderParm( $hologram2, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram2, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram3_start ()
	{
		//temp
		$hologram3.setColor  (.6, .7, .9);	//inital light blue
		$hologram3.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram3.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram3.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram3.show();
		thread interpolateShaderParm( $hologram3, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram3, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram3, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		sys.wait (1);
		thread interpolateShaderParm( $hologram3, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram3, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram4_start ()
	{
		//temp
		$hologram4.setColor  (.6, .7, .9);	//inital light blue
		$hologram4.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram4.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram4.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram4.show();
		thread interpolateShaderParm( $hologram4, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram4, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram4, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		sys.wait (1);
		thread interpolateShaderParm( $hologram4, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram4, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram5_start ()
	{
		//temp
		$hologram5.setColor  (.6, .7, .9);	//inital light blue
		$hologram5.setShaderParm(3,-0.6);	//the side textures scroll from bottom to top.  
		$hologram5.setShaderParm(4,100);	//the bottom textures scale from the center of the faces out to the edges.
		$hologram5.setShaderParm(7,0);		//rgb of tops of rooms
		//temp
		$hologram5.show();
		thread interpolateShaderParm( $hologram5, 6, 100, 1, 1 );	//scale in bottom grid
		sys.wait (1);
		thread interpolateShaderParm( $hologram5, 4, 100, 5, .2 );	//bring in bottoms of rooms
		sys.wait (0.2);
		thread interpolateShaderParm( $hologram5, 4, 5, 0.85, 1 );	//scale up bottoms of rooms
		sys.wait (1);
		thread interpolateShaderParm( $hologram5, 3, -0.6, 0, 1 );	//bring up sides of rooms and cap off.
		sys.wait (1);
		thread interpolateShaderParm( $hologram5, 7, 0, 1, 0.05 );	//RGB of room tops
	}

	void hologram1_1 () //this is the animation that gets played when player clicks on Control Center
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			
			$hologram1_1.startSoundShader ("hologram_spawnout", SND_CHANNEL_VOICE );
			
			thread interpolateShaderParm( $hologram1_1, 7, 1, 0, .2 );	//fade out round spinny plane
			thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.15 .175 .22', 1);	//make the unselected room go back to default colors
		
			$hologram1_1_anchor.time(.15);
			$hologram1_1_anchor.rotateOnce ( '0 0 -30');
			$hologram1_1_anchor.move(WEST,30);
			sys.waitFor( $hologram1_1_anchor );
			$hologram1_1_anchor.move(NORTH,16);
			sys.waitFor( $hologram1_1_anchor );
			$hologram1_1_anchor.move(DOWN,40);
			sys.waitFor( $hologram1_1_anchor );
			$hologram1_1.hide();
			$hologram1_1.setKey ("state", "0");
		} else 	{
			$hologram1_1.show();
			$hologram1_1.setKey ("state", "1"); //sets it so that next time you run the script, it puts the objects back where it was.
			$hologram1_1.setShaderParm(7,0);
			$hologram1_1.setColor  (1, .1, 0);	//make little line red
			thread crossFadeEnt( $hologram, $hologram.getColor(), '.1 .2 .2', .5);	//make the base hologram darken a little.
			thread interpolateShaderParm( $hologram, 5, 1, .35, .5 ); //make the base hologram's matrix effect go darker.
			thread crossFadeEnt( $hologram1, $hologram1.getColor(), '1 .1 0', .5);	//make selected room go red.
			thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
			thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
			thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
			thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
			
			$hologram1_1.startSoundShader ("hologram_spawn", SND_CHANNEL_VOICE );
			
			thread interpolateShaderParm( $hologram1_1, 3, 0, 100, .1 ); //RGB in red boxes
			thread interpolateShaderParm( $hologram1_1, 4, 10, 1, 1 ); //scale up the sides of red boxes
			thread interpolateShaderParm( $hologram1_1, 5, 10, 1, 1 ); //scale up round plane
			sys.wait (.7);
			thread interpolateShaderParm( $hologram1_1, 6, 1, 0, 2 ); //RGB out round spinny plane
			thread interpolateShaderParm( $hologram1_1, 3, 1, 0, 1 );  //RGB out red boxes
			sys.wait(1);

			$hologram1_1_anchor.time(1);
			$hologram1_1_anchor.accelTime(.4);
			$hologram1_1_anchor.decelTime(.4);
			
			$hologram1_1_anchor.move(UP,40);
			$hologram1_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
			
			sys.waitFor( $hologram1_1_anchor );
			
			$hologram1_1_anchor.move(SOUTH,16);
			$hologram1_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
			
			sys.waitFor( $hologram1_1_anchor );
			
			$hologram1_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE2 );
			
			$hologram1_1_anchor.move(EAST,30);
			thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.5 .05 0', .5);
			thread interpolateShaderParm( $hologram1_1, 7, 0, 1, 1 );  //RGB in the red sprite round plate
			
			$hologram1_1.startSoundShader ("hologram_loop", SND_CHANNEL_VOICE );
			
			$hologram1_1_anchor.rotateOnce ( '0 0 30');
		}
	}

	void hologram2_1 () //this is the animation that gets played when player clicks on lobby/elevators
	{
		if ($hologram2_1.getFloatKey ("state")==1){
		
			$hologram2_1.startSoundShader ("hologram_spawnout", SND_CHANNEL_VOICE );
		
			thread interpolateShaderParm( $hologram2_1, 7, 1, 0, .2 );	//fade out round spinny plane
			thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.15 .175 .22', 1);	//make the unselected room go back to default colors
		
			$hologram2_1_anchor.time(.15);
			$hologram2_1_anchor.rotateOnce ( '0 0 -30');
			$hologram2_1_anchor.move(NORTH,64);
			sys.wait(.15);
			$hologram2_1_anchor.move(WEST,40);
			sys.wait(.15);
			$hologram2_1_anchor.move(DOWN,44);
			sys.wait(.15);
			$hologram2_1.hide();
			$hologram2_1.setKey ("state", "0");
		} else 	{
		$hologram2_1.show();
		$hologram2_1.setKey ("state", "1");
		$hologram2_1.setShaderParm(7,0);
		$hologram2_1.setColor  (1, .1, 0);	//make little line red
		thread crossFadeEnt( $hologram, $hologram.getColor(), '.1 .2 .2', .5);	//make the base hologram darken a little.
		thread interpolateShaderParm( $hologram, 5, 1, .35, .5 ); //make the base hologram's matrix effect go darker.
		thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram2, $hologram2.getColor(), '1 .1 0', .5);	//make selected room go red.
		thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		
		$hologram2_1.startSoundShader ("hologram_spawn", SND_CHANNEL_VOICE );
		
		thread interpolateShaderParm( $hologram2_1, 3, 0, 100, .1 ); //RGB in red boxes
		thread interpolateShaderParm( $hologram2_1, 4, 10, 1, 1 ); //scale up the sides of red boxes
		thread interpolateShaderParm( $hologram2_1, 5, 10, 1, 1 ); //scale up round plane
		sys.wait (.7);
		thread interpolateShaderParm( $hologram2_1, 6, 1, 0, 2 ); //RGB out round spinny plane
		thread interpolateShaderParm( $hologram2_1, 3, 1, 0, 1 );  //RGB out red boxes
		sys.wait(1);

		$hologram2_1_anchor.time(1);
		$hologram2_1_anchor.accelTime(.4);
		$hologram2_1_anchor.decelTime(.4);
		$hologram2_1_anchor.move(UP,44);
		$hologram2_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		
		sys.wait(1);
		$hologram2_1_anchor.move(EAST,40);
		$hologram2_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		sys.wait(1);
		$hologram2_1_anchor.move(SOUTH,64);
		$hologram2_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE2 );
		thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.5 .05 0', .5);
		thread interpolateShaderParm( $hologram2_1, 7, 0, 1, 1 );  //RGB in the red sprite round plate
		
		$hologram2_1.startSoundShader ("hologram_loop", SND_CHANNEL_VOICE );
		$hologram2_1_anchor.rotateOnce ( '0 0 30');
		}
	}


	void hologram3_1 () //this is the animation that gets played when player clicks on Control Center
	{
		if ($hologram3_1.getFloatKey ("state")==1){
			
			$hologram3_1.startSoundShader ("hologram_spawnout", SND_CHANNEL_VOICE );
			
			thread interpolateShaderParm( $hologram3_1, 7, 1, 0, .2 );	//fade out round spinny plane
			thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.15 .175 .22', 1);	//make the unselected room go back to default colors
		
			$hologram3_1_anchor.time(.15);
			$hologram3_1_anchor.rotateOnce ( '0 0 -30');
			$hologram3_1_anchor.move(NORTH,108);
			sys.wait(.15);
			$hologram3_1_anchor.move(WEST,36);
			sys.wait(.15);
			$hologram3_1_anchor.move(DOWN,36);
			sys.wait(.15);
			$hologram3_1.hide();
			$hologram3_1.setKey ("state", "0");
		} else 	{
		$hologram3_1.show();
		$hologram3_1.setKey ("state", "1");
		$hologram3_1.setShaderParm(7,0);
		$hologram3_1.setColor  (1, .1, 0);	//make little line red
		thread crossFadeEnt( $hologram, $hologram.getColor(), '.1 .2 .2', .5);	//make the base hologram darken a little.
		thread interpolateShaderParm( $hologram, 5, 1, .35, .5 ); //make the base hologram's matrix effect go darker.
		thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram3, $hologram3.getColor(), '1 .1 0', .5);	//make selected room go red.
		thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		
		$hologram3_1.startSoundShader ("hologram_spawn", SND_CHANNEL_VOICE );
		
		thread interpolateShaderParm( $hologram3_1, 3, 0, 100, .1 ); //RGB in red boxes
		thread interpolateShaderParm( $hologram3_1, 4, 10, 1, 1 ); //scale up the sides of red boxes
		thread interpolateShaderParm( $hologram3_1, 5, 10, 1, 1 ); //scale up round plane
		sys.wait (.7);
		thread interpolateShaderParm( $hologram3_1, 6, 1, 0, 2 ); //RGB out round spinny plane
		thread interpolateShaderParm( $hologram3_1, 3, 1, 0, 1 );  //RGB out red boxes
		sys.wait(1);

		$hologram3_1_anchor.time(1);
		$hologram3_1_anchor.accelTime(.4);
		$hologram3_1_anchor.decelTime(.4);
		$hologram3_1_anchor.move(UP,36);
		$hologram3_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		sys.wait(1);
		$hologram3_1_anchor.move(EAST,36);
		$hologram3_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		sys.wait(1);
		$hologram3_1_anchor.move(SOUTH,108);
		$hologram3_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE2 );
		thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.5 .05 0', .5);
		thread interpolateShaderParm( $hologram3_1, 7, 0, 1, 1 );  //RGB in the red sprite round plate
		$hologram3_1.startSoundShader ("hologram_loop", SND_CHANNEL_VOICE );
		$hologram3_1_anchor.rotateOnce ( '0 0 30');
		}
	}

		void hologram4_1 () //this is the animation that gets played when player clicks on Control Center
	{
		if ($hologram4_1.getFloatKey ("state")==1){
			
			$hologram4_1.startSoundShader ("hologram_spawnout", SND_CHANNEL_VOICE );
			
			thread interpolateShaderParm( $hologram4_1, 7, 1, 0, .2 );	//fade out round spinny plane
			thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.15 .175 .22', 1);	//make the unselected room go back to default colors
		
			$hologram4_1_anchor.time(.15);
			$hologram4_1_anchor.rotateOnce ( '0 0 -30');
			$hologram4_1_anchor.move(NORTH,200);
			sys.wait(.15);
			$hologram4_1_anchor.move(WEST,40);
			sys.wait(.15);
			$hologram4_1_anchor.move(DOWN,40);
			sys.wait(.15);
			$hologram4_1.hide();
			$hologram4_1.setKey ("state", "0");
		} else 	{
		$hologram4_1.show();
		$hologram4_1.setKey ("state", "1");
		$hologram4_1.setShaderParm(7,0);
		$hologram4_1.setColor  (1, .1, 0);	//make little line red
		thread crossFadeEnt( $hologram, $hologram.getColor(), '.1 .2 .2', .5);	//make the base hologram darken a little.
		thread interpolateShaderParm( $hologram, 5, 1, .35, .5 ); //make the base hologram's matrix effect go darker.
		thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram4, $hologram4.getColor(), '1 .1 0', .5);	//make selected room go red.
		thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		
		$hologram4_1.startSoundShader ("hologram_spawn", SND_CHANNEL_VOICE );
		
		thread interpolateShaderParm( $hologram4_1, 3, 0, 100, .1 ); //RGB in red boxes
		thread interpolateShaderParm( $hologram4_1, 4, 10, 1, 1 ); //scale up the sides of red boxes
		thread interpolateShaderParm( $hologram4_1, 5, 10, 1, 1 ); //scale up round plane
		sys.wait (.7);
		thread interpolateShaderParm( $hologram4_1, 6, 1, 0, 2 ); //RGB out round spinny plane
		thread interpolateShaderParm( $hologram4_1, 3, 1, 0, 1 );  //RGB out red boxes
		
		
		sys.wait(1);

		$hologram4_1_anchor.time(1);
		$hologram4_1_anchor.accelTime(.4);
		$hologram4_1_anchor.decelTime(.4);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		$hologram4_1_anchor.move(UP,40);
		sys.wait(1);
		$hologram4_1_anchor.move(EAST,40);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		sys.wait(1);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE2 );
		$hologram4_1_anchor.move(SOUTH,200);
		thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.5 .05 0', .5);
		thread interpolateShaderParm( $hologram4_1, 7, 0, 1, 1 );  //RGB in the red sprite round plate
		$hologram4_1.startSoundShader ("hologram_loop", SND_CHANNEL_VOICE );
		$hologram4_1_anchor.rotateOnce ( '0 0 30');
		}
	}

	void hologram5_1 () //this is the animation that gets played when player clicks on Control Center
	{
		if ($hologram5_1.getFloatKey ("state")==1){
			$hologram5_1.startSoundShader ("hologram_spawnout", SND_CHANNEL_VOICE );
			thread interpolateShaderParm( $hologram5_1, 7, 1, 0, .2 );	//fade out round spinny plane
			thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.15 .175 .22', 1);	//make the unselected room go back to default colors
		
			$hologram5_1_anchor.time(.15);
			$hologram5_1_anchor.rotateOnce ( '0 0 -30');
			$hologram5_1_anchor.move(NORTH,96);
			sys.wait(.15);
			$hologram5_1_anchor.move(EAST,88);
			sys.wait(.15);
			$hologram5_1_anchor.move(DOWN,36);
			sys.wait(.15);
			$hologram5_1.hide();
			$hologram5_1.setKey ("state", "0");
		} else 	{
		$hologram5_1.show();
		$hologram5_1.setKey ("state", "1");
		$hologram5_1.setShaderParm(7,0);
		$hologram5_1.setColor  (1, .1, 0);	//make little line red
		thread crossFadeEnt( $hologram, $hologram.getColor(), '.1 .2 .2', .5);	//make the base hologram darken a little.
		thread interpolateShaderParm( $hologram, 5, 1, .35, .5 ); //make the base hologram's matrix effect go darker.
		thread crossFadeEnt( $hologram1, $hologram1.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram2, $hologram2.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram3, $hologram3.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram4, $hologram4.getColor(), '.15 .175 .22', .5);	//make unselected room darken.
		thread crossFadeEnt( $hologram5, $hologram5.getColor(), '1 .1 0', .5);	//make selected room go red.
		
		$hologram5_1.startSoundShader ("hologram_spawn", SND_CHANNEL_VOICE );
		
		thread interpolateShaderParm( $hologram5_1, 3, 0, 100, .1 ); //RGB in red boxes
		thread interpolateShaderParm( $hologram5_1, 4, 10, 1, 1 ); //scale up the sides of red boxes
		thread interpolateShaderParm( $hologram5_1, 5, 10, 1, 1 ); //scale up round plane
		sys.wait (.7);
		thread interpolateShaderParm( $hologram5_1, 6, 1, 0, 2 ); //RGB out round spinny plane
		thread interpolateShaderParm( $hologram5_1, 3, 1, 0, 1 );  //RGB out red boxes
		sys.wait(1);

		$hologram5_1_anchor.time(1);
		$hologram5_1_anchor.accelTime(.4);
		$hologram5_1_anchor.decelTime(.4);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		$hologram5_1_anchor.move(UP,36);
		sys.wait(1);
		$hologram5_1_anchor.move(WEST,88);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE );
		sys.wait(1);
		$hologram5_1_anchor.move(SOUTH,96);
		$hologram4_1.startSoundShader ("hologram_movement", SND_CHANNEL_VOICE2 );
		thread crossFadeEnt( $hologram5, $hologram5.getColor(), '.5 .05 0', .5);
		thread interpolateShaderParm( $hologram5_1, 7, 0, 1, 1 );  //RGB in the red sprite round plate
		$hologram5_1.startSoundShader ("hologram_loop", SND_CHANNEL_VOICE );
		$hologram5_1_anchor.rotateOnce ( '0 0 30');
		}
	}

	void hologram_turnon ()//this is what's called when the hologram projector's turned on, and brings all the rooms in.
	{
		thread hologram_start ();
		sys.wait(1.5);
		thread hologram1_start ();
		sys.wait(.5);
		thread hologram2_start ();
		sys.wait(.5);
		thread hologram3_start ();
		thread hologram4_start ();
		thread hologram5_start ();
	}
	
	void hologram_selection_1()
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			thread hologram1_1();
		}
		if ($hologram2_1.getFloatKey ("state")==1){
			thread hologram2_1();
		}
		if ($hologram3_1.getFloatKey ("state")==1){
			thread hologram3_1();
		}
		if ($hologram4_1.getFloatKey ("state")==1){
			thread hologram4_1();
		}
		if ($hologram5_1.getFloatKey ("state")==1){
			thread hologram5_1();
		}
		{
			thread hologram1_1();
		}
	}

	void hologram_selection_2()
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			thread hologram1_1();
		}
		if ($hologram2_1.getFloatKey ("state")==1){
			thread hologram2_1();
		}
		if ($hologram3_1.getFloatKey ("state")==1){
			thread hologram3_1();
		}
		if ($hologram4_1.getFloatKey ("state")==1){
			thread hologram4_1();
		}
		if ($hologram5_1.getFloatKey ("state")==1){
			thread hologram5_1();
		}
		{
			thread hologram2_1();
		}
	}

	void hologram_selection_3()
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			thread hologram1_1();
		}
		if ($hologram2_1.getFloatKey ("state")==1){
			thread hologram2_1();
		}
		if ($hologram3_1.getFloatKey ("state")==1){
			thread hologram3_1();
		}
		if ($hologram4_1.getFloatKey ("state")==1){
			thread hologram4_1();
		}
		if ($hologram5_1.getFloatKey ("state")==1){
			thread hologram5_1();
		}
		{
			thread hologram3_1();
		}
	}

	void hologram_selection_4()
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			thread hologram1_1();
		}
		if ($hologram2_1.getFloatKey ("state")==1){
			thread hologram2_1();
		}
		if ($hologram3_1.getFloatKey ("state")==1){
			thread hologram3_1();
		}
		if ($hologram4_1.getFloatKey ("state")==1){
			thread hologram4_1();
		}
		if ($hologram5_1.getFloatKey ("state")==1){
			thread hologram5_1();
		}
		{
			thread hologram4_1();
		}
	}

	void hologram_selection_5()
	{
		if ($hologram1_1.getFloatKey ("state")==1){
			thread hologram1_1();
		}
		if ($hologram2_1.getFloatKey ("state")==1){
			thread hologram2_1();
		}
		if ($hologram3_1.getFloatKey ("state")==1){
			thread hologram3_1();
		}
		if ($hologram4_1.getFloatKey ("state")==1){
			thread hologram4_1();
		}
		if ($hologram5_1.getFloatKey ("state")==1){
			thread hologram5_1();
		}
		{
			thread hologram5_1();
		}
	}


	////////////////////////////////////////////////////
	//
	//	break the platform leading to the reactor
	//
	////////////////////////////////////////////////////
	void rplatform_break()
	{
		//first move down
		$rplatform.time ( 2.5 );
		$rplatform.accelTime ( .5 );
		$rplatform.decelTime ( 0 );
		sys.trigger ($lspeaker_1);
		$rplatform.move ( DOWN, 126 );

		sys.waitFor ($rplatform);

		//bounce a bit or something
		sys.trigger ($broke_spark);
		$al3_platform_break.time ( .2 );
		$al3_platform_break.accelTime ( .2 );
		$al3_platform_break.decelTime ( 0 );
		$al3_platform_break.move ( UP, 6 );

		sys.waitFor ($rplatform);

		$rplatform.time ( .2 );
		$rplatform.accelTime ( 0 );
		$rplatform.decelTime ( .2 );
		$rplatform.move ( DOWN, 8 );

		//rotate a about 24 degrees
		$rplatform.time ( .5 );
		$rplatform.accelTime ( .5 );
		$rplatform.decelTime ( 0 );
		$rplatform.rotateOnce ( '5 5 24' );
		sys.trigger ($broke_spark);

		sys.waitFor ($rplatform);

		$rplatform.time ( .1 );
		$rplatform.accelTime ( .1 );
		$rplatform.decelTime ( 0 );
		$rplatform.rotateOnce ( '1 0 0' );
		sys.trigger ($broke_spark);

		sys.waitFor ($rplatform);

		$rplatform.rotateOnce ( '-1 0 0' );
	}


	////////////////////////////////////////////////////
	//
	//	Corpse Move - quick move of deadbody 
	//
	////////////////////////////////////////////////////
	void corpse_move()
	{
		spooky_sound_3();

		$corpse_mover2.time (.4);
		$corpse_mover2.accelTime (0);
		$corpse_mover2.decelTime (0);

		$corpse_mover2.moveTo ( $corpse_mover2_movepoint );
		$corpse_mover2.rotateOnce ( '0 45 0' );
		sys.waitFor ($corpse_mover2);
		$corpse2.unbind();

		sys.trigger ( $breakglass );
		sys.trigger ( $func_fracture_2 );

		sys.wait (.5);
		sys.trigger ( $speaker_glassbreak );

		sys.wait (2);
		sys.trigger ( $speaker_tilefall2 );
		sys.trigger ($spooky_tilefall2);
			
	}


	////////////////////////////////////////////////////
	//
	//	spectrum hallway
	//
	////////////////////////////////////////////////////
	void spectrum_move() {
		sys.trigger ( $spectrum_speaker1 );
        $spectrumlight_mover.time( 3 );
		$spectrumlight_mover.accelTime( 0 );
		$spectrumlight_mover.decelTime( 0 );
		$spectrumlight_mover.startSpline( $spectrum_spline );

		sys.waitFor($spectrumlight_mover);
		//sys.wait(3);
		//$spectrumlight_mover.removeInitialSplineAngles();

		$spectrumlight_mover.remove();
		sys.trigger ( $spectrum_speaker1 );
		$spectrum_speaker1.remove();
		$speclight1.remove();
		$speclight2.remove();
	}


	////////////////////////////////////////////////////
	//
	//	bang tile moves 
	//
	//	moves the two tiles when the big bang happens
	//	in the crawlspace before datalinker
	//
	////////////////////////////////////////////////////
	void bang_tiles()
	{
		//set moves times for the two tiles
		$bang_tile1.time (.5);
		$bang_tile1.accelTime (.5);
		$bang_tile1.decelTime (0);

		$bang_tile2.time (.5);
		$bang_tile2.accelTime (.5);
		$bang_tile2.decelTime (0);

		$bang_tile1.rotateOnce ( '1 0 -2' );
		$bang_tile2.rotateOnce ( '2 0 3' );
	}


	////////////////////////////////////////////////////
	//
	//	Corpse pullunder
	//
	////////////////////////////////////////////////////
	void corpse_pullunder()
	{
		$corpse_mover3.time (1.25);
		$corpse_mover3.accelTime (.5);
		$corpse_mover3.decelTime (0);

		$corpse_mover3.moveTo ( $corpse_mover3_movepoint );
		sys.waitFor ($corpse_mover3);
		
		$corpse3.unbind();
		$corpse_mover3.remove ();
		$corpse3.remove ();
	}


	void fade_clop_sound ()
	{
		$clop_speaker.fadeSound ( SND_CHANNEL_ANY, -60, 30 );
	}

	
	void cache_sounds() {
		sys.cacheSoundShader ("hologram_datalinker");		
		sys.cacheSoundShader ("hologram_spawnout");	
		sys.cacheSoundShader ("hologram_spawn");
		sys.cacheSoundShader ("hologram_movement");
		sys.cacheSoundShader ("hologram_loop");
	}
		
	////////////////////////////////////////////////////
	//
	//	Main
	//
	////////////////////////////////////////////////////
	void main() 
	{
		thread cache_sounds();
		init_world();
		power_level_0();
	}
}

//@doomscript-blueprint begin 6
//@source 9F682331
//@catalog 0C260740
//@node 8846F578-0 40 40
//@node 0BB69A37-0 330 40
//@node D7A91222-0 610 40
//@node AA3D606A-0 890 40
//@node 285D75AF-0 1170 40
//@node 1256CB8F-0 1450 40
//@node D060CE49-0 1730 40
//@node 821CA211-0 2010 40
//@node 2EC5272E-0 2290 40
//@node BCF781D9-0 2570 40
//@node 0A7F495F-0 2850 40
//@node 06FA1DA5-0 3130 40
//@node DD7D92AE-0 3410 40
//@node E1FD0764-0 3690 40
//@node 190A3057-0 3970 40
//@node A9AA4327-0 4250 40
//@node 557EB1C4-0 4530 40
//@node 5EF9BE0A-0 4810 40
//@node 93C62CCF-0 5090 40
//@node 8EE7D7B1-0 5370 40
//@node 9854A8DC-0 5650 40
//@node 76D40FD9-0 5930 40
//@node 9E7DAF51-0 6210 40
//@node 5F84FE6B-0 6490 40
//@node 8ADA0C14-0 6770 40
//@node 0E585CA6-0 7050 40
//@node A842FE9D-0 7330 40
//@node 2EB24B93-0 7610 40
//@node 6C4AB3EE-0 7890 40
//@node 99505820-0 8170 40
//@node C4F36A65-0 8450 40
//@node 7C5C9DFB-0 8730 40
//@node E24750EA-0 9010 40
//@node AC02FC41-0 9290 40
//@node 1E5F6993-0 9570 40
//@node EF27F411-0 9850 40
//@node 17DBE582-0 10130 40
//@node F2EAEAB8-0 10410 40
//@node 5AD1C402-0 10690 40
//@node 9ACD17DB-0 10970 40
//@node 766F3A7C-0 11250 40
//@node D6479576-0 11530 40
//@node F0293B8A-0 11810 40
//@node B8EA7757-0 12090 40
//@node 52C2DBE0-0 12370 40
//@node 8C4AA3EF-0 12650 40
//@node 03416B61-0 12930 40
//@node 9F0C029C-0 13210 40
//@node 058D71D5-0 13490 40
//@node 29B714C1-0 13770 40
//@node 0889AD97-0 14050 40
//@node 3FC871CA-0 14330 40
//@node A35A160C-0 14610 40
//@node 3A16FB3F-0 14890 40
//@node FA744161-0 15170 40
//@node 6A4D8A9A-0 15450 40
//@node 950481BC-0 15730 40
//@node F229564C-0 16010 40
//@node BD56B5E5-0 16290 40
//@node 713EBB21-0 16570 40
//@node 800EF261-0 16850 40
//@node 5789FE5A-0 17130 40
//@node D141DDC3-0 17410 40
//@node 570C28AF-0 17690 40
//@node 221E94F9-0 17970 40
//@node 4B168AC0-0 18250 40
//@node 1549A786-0 18530 40
//@node 1A5A6713-0 18810 40
//@node 8E5C99F7-0 19090 40
//@node 684219B0-0 19370 40
//@node D1333EFA-0 19650 40
//@node 99A9AD56-0 19930 40
//@node 63FC42B3-0 20210 40
//@node 45BE880D-0 20490 40
//@node 2B31A2FD-0 20770 40
//@node F6FA1874-0 21050 40
//@node B9F0D81D-0 21330 40
//@node 123F79BE-0 21610 40
//@node 287215F7-0 21890 40
//@node 89F2D502-0 22170 40
//@node 2819D6B6-0 22450 40
//@node 3EAD2D08-0 22730 40
//@node 4811A41B-0 23010 40
//@node 901385B2-0 23290 40
//@node 4EF5D9AB-0 23570 40
//@node 19E3F353-0 23850 40
//@node 94A79C97-0 24130 40
//@node 78950EA6-0 24410 40
//@node 1BEF5C99-0 24690 40
//@node 5BD0A23F-0 24970 40
//@node 5A71BDF5-0 25250 40
//@node F52B41A6-0 25530 40
//@node C6F434B8-0 25810 40
//@node 2C234438-0 26090 40
//@node B1770F39-0 26370 40
//@node 8C28155E-0 26650 40
//@node 8349CEB3-0 26930 40
//@node F3574411-0 27210 40
//@node DA55B6FC-0 27490 40
//@node 5155C54B-0 27770 40
//@node B96E0F82-0 28050 40
//@node 31AD711D-0 28330 40
//@node A5C7351C-0 28610 40
//@node 63EA5120-0 40 40
//@node 00A69E9E-0 330 40
//@node FD78736D-0 125 145
//@node 378F134A-0 610 40
//@node 971F3EB0-0 405 145
//@node 3DEA63D6-0 200 145
//@node 3AEA5F1D-0 200 229
//@node A5296778-0 890 200
//@node 637A4A91-0 685 305
//@node BDA6F8CE-0 480 305
//@node AAA6DAE5-0 480 389
//@node 3C0696BC-0 1450 200
//@node 21FBFB01-0 965 392
//@node B6E1CB8F-0 1730 200
//@node C15E7834-0 1245 392
//@node A964EF36-0 2010 200
//@node 0D764A7F-0 1525 392
//@node 8735E039-0 2290 200
//@node 3F4F7641-0 2570 40
//@node 25BECC5E-0 2850 40
//@node ABF41A4B-0 3130 40
//@node DF877F14-0 40 40
//@node 7CB346E6-0 330 40
//@node A237EEDA-0 125 145
//@node 8E6507F0-0 610 40
//@node 77861C5F-0 405 145
//@node AC8FBD8A-0 890 40
//@node 043B8390-0 685 145
//@node 76E2389A-0 480 145
//@node 13BFCFF7-0 480 229
//@node D6F7DD7E-0 1170 200
//@node FB200B30-0 945 305
//@node C906F854-0 1450 200
//@node FCBFDCDC-0 1225 305
//@node B231C911-0 2010 200
//@node 97870B7F-0 1525 300
//@node 53100361-0 1525 392
//@node 6F6DA083-0 1525 484
//@node 343F7FA0-0 2010 200
//@node 1B417B98-0 1805 305
//@node 00650909-0 2570 40
//@node 2E85AB08-0 2085 140
//@node 0C00F8FA-0 40 40
//@node 9DF2A15E-0 330 40
//@node C3FB3982-0 105 145
//@node 1BABE22D-0 610 40
//@node 7DA5B74A-0 405 140
//@node D11922B8-0 890 40
//@node 46F5438A-0 685 145
//@node FC52965A-0 480 145
//@node B31769AE-0 1170 200
//@node F3A9CCEF-0 965 305
//@node 1BABE22D-1 1450 200
//@node 896ED48D-0 1245 300
//@node CCB1BD47-0 1730 200
//@node 5967DDA7-0 2010 40
//@node C3B8BE19-0 1805 145
//@node A5E29CF8-0 1600 145
//@node 52F92747-0 2290 200
//@node D5845C65-0 2085 305
//@node F64C1360-0 2570 200
//@node 65A7B66A-0 2365 305
//@node 98E62187-0 2160 305
//@node 94359217-0 2160 389
//@node 70F9EC8C-0 2160 473
//@node 6326438A-0 2850 360
//@node 5AA64AE3-0 2645 552
//@node 73333886-0 2440 552
//@node 85EED53B-0 3130 360
//@node B605C215-0 2925 552
//@node B1AE2F10-0 2720 552
//@node F9DDD7DF-0 3410 360
//@node 3EC0C7D9-0 3205 552
//@node 959C604F-0 3000 552
//@node 517F14A9-0 3690 360
//@node BC781C21-0 40 40
//@node 93DE9940-0 330 40
//@node 08CE678C-0 125 145
//@node 87B268A3-0 -80 145
//@node B02FCAA7-0 -80 229
//@node 54212AD6-0 610 200
//@node D71053EB-0 385 305
//@node 8E05E70D-0 180 405
//@node 84AC04A7-0 -25 405
//@node 2E123E08-0 890 200
//@node 79B9A166-0 665 305
//@node 67ED3295-0 460 405
//@node DDF50D8F-0 255 405
//@node 60748BC4-0 1170 200
//@node 5093CCD4-0 945 305
//@node B44FE106-0 740 405
//@node 2B143A3F-0 535 405
//@node DD851CB6-0 1450 200
//@node E71C80E3-0 1225 305
//@node 84AA0E43-0 1020 405
//@node AAA803B8-0 815 405
//@node 4B296662-0 1730 200
//@node C4FA8867-0 1505 305
//@node 92D27919-0 1300 405
//@node ED599231-0 1095 405
//@node 3923E8EF-0 2290 200
//@node 04112E03-0 2570 200
//@node E1C7A3F6-0 2850 200
//@node DC6C2312-0 3130 200
//@node 64ADD6AF-0 3410 200
//@node 0801153D-0 40 40
//@node 7F18D0EC-0 330 40
//@node 17D4D805-0 125 145
//@node 14832AD0-0 -80 145
//@node 7F53D6BA-0 -80 229
//@node AE233B00-0 610 200
//@node 2128D606-0 385 305
//@node C1942CD5-0 180 405
//@node C7B44C75-0 -25 405
//@node 8D9FB732-0 890 200
//@node 7EFEC74B-0 665 305
//@node 222FADFF-0 460 405
//@node 14AF2BA7-0 255 405
//@node EE28370E-0 1170 200
//@node 2A1E29C3-0 945 305
//@node B4141A55-0 740 405
//@node E577AC4E-0 535 405
//@node 6BF6F7A8-0 1450 200
//@node 39901A6C-0 1225 305
//@node 830747CF-0 1020 405
//@node 1E7AD88A-0 815 405
//@node 1511E6E4-0 1730 200
//@node FD46ECBC-0 1505 305
//@node 1968C297-0 1300 405
//@node EB607CB5-0 1095 405
//@node FE458631-0 2290 200
//@node E765BE9B-0 2570 200
//@node 040153A4-0 2850 200
//@node 65C2C0E0-0 3130 200
//@node 9E683AB7-0 3410 200
//@node 8EBCBA4A-0 40 40
//@node 44C18051-0 330 40
//@node E9CCC23D-0 610 40
//@node B2B2FF70-0 890 40
//@node D1F6A379-0 1170 40
//@node 11B03D0A-0 1450 40
//@node 2843033C-0 1730 40
//@node 929CEE74-0 2010 40
//@node BAADFAC8-0 2290 40
//@node 772A79D4-0 2570 40
//@node 2D2FEA6A-0 2850 40
//@node 6C655102-0 3130 40
//@node EF05A4BC-0 40 40
//@node 62C37613-0 330 40
//@node 2FE164A0-0 40 40
//@node 09D575DA-0 330 40
//@node 40865E90-0 125 145
//@node C64DCD8C-0 -80 145
//@node E0D8D8ED-0 -80 229
//@node 48745A04-0 610 200
//@node 4F841F04-0 385 305
//@node 0BC3CA17-0 180 405
//@node 34A022A4-0 -25 405
//@node F779680A-0 890 200
//@node A1018513-0 665 305
//@node 66B5A57B-0 460 405
//@node 52C932AF-0 255 405
//@node 84863952-0 1170 200
//@node 8345B7C8-0 945 305
//@node 38F64F40-0 740 405
//@node 36C30A03-0 535 405
//@node 80904A62-0 1730 200
//@node 739D4749-0 2010 200
//@node B3CA4DFC-0 2290 200
//@node 55E576FA-0 40 40
//@node D834F370-0 330 40
//@node CA387E6A-0 125 145
//@node 0A523784-0 -80 145
//@node BE16A1A5-0 -80 229
//@node A9F5B5A8-0 610 200
//@node 94DAA022-0 385 305
//@node 21A0E6D3-0 180 405
//@node FBB68F3E-0 -25 405
//@node 14267F4E-0 890 200
//@node 8EE83DDA-0 665 305
//@node 02125099-0 460 405
//@node 2F4E017F-0 255 405
//@node FAD0FF36-0 1170 200
//@node 06D17709-0 945 305
//@node 5FC4B01C-0 740 405
//@node 8D96E201-0 535 405
//@node C7B1EB8D-0 1730 200
//@node 923B5EF6-0 2010 200
//@node 86C024E7-0 2290 200
//@node 30B099CC-0 40 40
//@node 30981203-0 330 40
//@node 0956400B-0 125 145
//@node C3A3405A-0 610 40
//@node 25218231-0 405 145
//@node 84A2A82F-0 200 145
//@node 11D1116E-0 200 229
//@node 228BC839-0 200 313
//@node 198EE41D-0 890 200
//@node CECFA577-0 685 392
//@node 5D67430E-0 1170 200
//@node A29AF5D6-0 965 392
//@node A2B23113-0 1450 200
//@node 670736B1-0 1245 392
//@node 4F0CD65B-0 1730 200
//@node 83045B66-0 2010 40
//@node C20D1C35-0 2290 40
//@node EB32279C-0 2570 40
//@node 8AB0DD8A-0 2850 40
//@node 3FA05B23-0 3130 40
//@node F967DD7D-0 3410 40
//@node 17F625B8-0 3690 40
//@node 062AC74B-0 3485 145
//@node E1BE87CA-0 3970 40
//@node E5E59E26-0 3765 145
//@node 31B09B5F-0 40 40
//@node F2FF8127-0 330 40
//@node F7AE57E6-0 610 40
//@node 48662D1E-0 890 40
//@node BFDF7FC2-0 1170 40
//@node 8A20EB27-0 965 145
//@node 2CD09B82-0 760 145
//@node D0F8B584-0 1450 200
//@node 90BEAB1D-0 1245 305
//@node EE1076A2-0 1730 200
//@node 8C084DD4-0 1525 305
//@node 5E914D23-0 1320 305
//@node 2356F01A-0 1320 389
//@node 294156DD-0 1320 473
//@node A6C8DD06-0 2010 360
//@node 669CCB85-0 1805 552
//@node FAD3B275-0 2290 360
//@node EF0E293F-0 2085 552
//@node 40A880A4-0 2570 360
//@node 2D0C31AF-0 2365 552
//@node 6B7C9902-0 2850 360
//@node D0F8B584-1 3410 200
//@node 45F08A1E-0 3205 305
//@node 8C054E96-0 3690 200
//@node E958C213-0 3485 305
//@node 234C4AC4-0 3280 305
//@node 8AF8C367-0 3280 389
//@node 3855497C-0 3280 473
//@node A6C8DD06-1 3970 360
//@node D611C20E-0 3765 552
//@node FAD3B275-1 4250 360
//@node 1F6C5948-0 4045 552
//@node 40A880A4-1 4530 360
//@node 4EE42138-0 4325 552
//@node 6B7C9902-1 4810 360
//@node 6EA36A0E-0 5090 40
//@node C431554D-0 4885 145
//@node 1BB13A46-0 5370 40
//@node 356B5C92-0 5165 145
//@node DF4093FC-0 5650 40
//@node 32B09CF2-0 40 40
//@node CA2BFAB2-0 330 40
//@node 817E19ED-0 125 145
//@node 437E14BE-0 610 40
//@node 6C6D63B9-0 890 40
//@node E4F51C77-0 1170 40
//@node B962BB45-0 1450 40
//@node DFD978C7-0 1245 145
//@node 8CBEC335-0 1730 40
//@node 923B3BAC-0 1525 145
//@node 36CBEB53-0 1320 145
//@node C469FE2A-0 1320 229
//@node 4D9452CD-0 1320 313
//@node A8F114C1-0 2010 200
//@node 44234B9A-0 1805 392
//@node 2EC3EF75-0 1600 392
//@node A18F0A1E-0 2290 200
//@node D018575E-0 2085 392
//@node 7205F531-0 1880 392
//@node FE15E684-0 2570 200
//@node E74E2264-0 2365 392
//@node B0534228-0 2160 392
//@node 5321B7C5-0 2850 200
//@node 65FF6627-0 3130 40
//@node 21833FEB-0 2925 145
//@node 94398708-0 40 40
//@node 5A7BC9BE-0 330 40
//@node 904F0432-0 610 40
//@node 51D20303-0 890 40
//@node C44C7D43-0 685 145
//@node 35408A73-0 1170 200
//@node 4F851AA5-0 1450 200
//@node 06FBF127-0 1730 200
//@node 8764E2B3-0 2010 200
//@node 904F0432-1 2290 200
//@node C51ED32A-0 40 40
//@node E202CC69-0 330 40
//@node 914EA4DE-0 125 145
//@node 448EC0B5-0 -80 145
//@node 8134ABD8-0 610 200
//@node E9F841A0-0 890 200
//@node AA78C2C5-0 1170 200
//@node C1896727-0 1450 200
//@node B5124E50-0 1730 200
//@node 015DA3FB-0 40 40
//@node 6AF4E142-0 330 40
//@node C646AC45-0 610 40
//@node DBD55386-0 890 40
//@node FDCF895D-0 1170 40
//@node 16B35E6E-0 1450 40
//@node FFA30CB6-0 1730 40
//@node 5809DB4D-0 2010 40
//@node F59FCBF6-0 2290 40
//@node 16B35E6E-1 2570 40
//@node FFA30CB6-1 2850 40
//@node DBD55386-1 3130 40
//@node 762E0CDD-0 3410 40
//@node 16B35E6E-2 3690 40
//@node E81B0502-0 3970 40
//@node 6CACD3B7-0 4250 40
//@node CB0102A4-0 4530 40
//@node 16B35E6E-3 4810 40
//@node 92DEA343-0 5090 40
//@node 91331F6C-0 5370 40
//@node A78D4FDC-0 5650 40
//@node 16B35E6E-4 5930 40
//@node 92DEA343-1 6210 40
//@node 91331F6C-1 6490 40
//@node 04904058-0 6770 40
//@node 16B35E6E-5 7050 40
//@node 891E200F-0 40 40
//@node 4A232A93-0 330 40
//@node 7D35344B-0 125 145
//@node C2336BEE-0 610 40
//@node 2C2B4CE3-0 405 145
//@node EF6DA056-0 890 40
//@node 33C5B89F-0 685 145
//@node 938EA23A-0 480 145
//@node 0A91A3A4-0 1170 40
//@node 2C95B58B-0 965 145
//@node 4606116C-0 760 145
//@node 5B06327B-0 760 229
//@node 7C245019-0 1450 200
//@node F885DA28-0 1245 305
//@node CAA5719B-0 1040 305
//@node 4EBDC2DD-0 1040 389
//@node 4C16CAF0-0 1730 200
//@node DFF8B96D-0 1525 305
//@node 9E011221-0 1320 305
//@node E1CB90DD-0 2290 200
//@node 97B54259-0 1805 300
//@node 84AEF205-0 2290 200
//@node 340CFC8B-0 2085 305
//@node 0C9D1264-0 1880 305
//@node AAD25442-0 2850 200
//@node A0023240-0 2365 300
//@node B545DCCE-0 3130 200
//@node B3878727-0 40 40
//@node A972DC78-0 330 40
//@node 611AD2DA-0 610 40
//@node D5740CFE-0 890 40
//@node 885E3BDD-0 1170 40
//@node 8BB1A883-0 1450 40
//@node 893D9327-0 1730 40
//@node 69CE7D41-0 2010 40
//@node 1612B88A-0 2290 40
//@node C667AE91-0 2570 40
//@node 37B4BD38-0 2850 40
//@node E4BC4625-0 3130 40
//@node 20D4403B-0 3410 40
//@node B00F9E47-0 3690 40
//@node 20D4403B-1 3970 40
//@node 6EDE0695-0 4250 40
//@node 1CF6DC7E-0 4530 40
//@node EA553F74-0 40 40
//@node D6E00479-0 330 40
//@node 808D3FEF-0 610 40
//@node D6CEE590-0 890 40
//@node 834B782A-0 1170 40
//@node E013B97C-0 1450 40
//@node 5AEE79D4-0 1730 40
//@node ED55442D-0 40 40
//@node 9B005E8B-0 330 40
//@node D56F8DC4-0 610 40
//@node 0775161E-0 890 40
//@node EC55429A-0 40 40
//@node CB67ED8E-0 330 40
//@node 016D237D-0 105 145
//@node E0F28E26-0 610 40
//@node AF072107-0 405 145
//@node 503236EF-0 200 145
//@node CD85046D-0 890 200
//@node C4023CA5-0 1170 200
//@node 86AD7F0C-0 1450 200
//@node D23AF41A-0 1730 200
//@node 69C42BEE-0 1525 305
//@node 18EAC67F-0 1320 305
//@node 86AD7F0C-1 2010 200
//@node C4023CA5-1 2290 200
//@node EB8FF0FB-0 2570 200
//@node EB8FF0FB-1 3130 200
//@node C4023CA5-2 3410 200
//@node 86AD7F0C-2 3690 200
//@node CD85046D-1 3970 200
//@node E7553ABB-0 40 40
//@node 3FB8DFFB-0 330 40
//@node 80CF7C4F-0 105 145
//@node E7B28FD5-0 610 40
//@node 0246171B-0 405 145
//@node C46C4EDF-0 200 145
//@node D6600327-0 890 200
//@node BC70BE32-0 1170 200
//@node 1D4082E4-0 1450 200
//@node B1EF7A83-0 1730 200
//@node 9FAEC314-0 1525 305
//@node E7EC07C5-0 1320 305
//@node 434B7C0A-0 2010 200
//@node BC70BE32-1 2290 200
//@node 28F397A9-0 2570 200
//@node 28F397A9-1 3130 200
//@node BC70BE32-2 3410 200
//@node 434B7C0A-1 3690 200
//@node D6600327-1 3970 200
//@node EF6A1625-0 40 40
//@node 3F29C8DE-0 330 40
//@node 46462BF0-0 610 40
//@node 75A9AE75-0 890 40
//@node D33DEACB-0 1170 40
//@node AE45A3F5-0 1450 40
//@node 54BF5B37-0 1730 40
//@node C031EAF8-0 2010 40
//@node 7A373F8A-0 2290 40
//@node E8258668-0 2570 40
//@node A17D5CD6-0 2850 40
//@node 3946A093-0 3130 40
//@node 950C3AE5-0 3410 40
//@node 1696C84F-0 3690 40
//@node E7766635-0 3970 40
//@node C5C166BE-0 4250 40
//@node 88E35E34-0 4530 40
//@node 188EC32A-0 4810 40
//@node 86A0F114-0 5090 40
//@node 5B10D4E1-0 5370 40
//@node 61572267-0 5650 40
//@node 92FE6EA4-0 5930 40
//@node 9E922401-0 6210 40
//@node 4B033CB2-0 6490 40
//@node 5F645BF2-0 6770 40
//@node 1A974FA0-0 7050 40
//@node D3A269E8-0 7330 40
//@node 2A0E8395-0 7610 40
//@node 76C63089-0 7890 40
//@node 949CD628-0 8170 40
//@node 7AC4B426-0 8450 40
//@node B285C053-0 8730 40
//@node 12307503-0 9010 40
//@node 960D2D09-0 9290 40
//@node 949CD628-1 9570 40
//@node 58FCD629-0 9850 40
//@node 949CD628-2 10130 40
//@node 773939F5-0 10410 40
//@node A4F14962-0 40 40
//@node D534B855-0 330 40
//@node 429D6BD7-0 610 40
//@node 84F09D98-0 890 40
//@node 46F2E72A-0 1170 40
//@node 80D2858F-0 1450 40
//@node AD0F177B-0 1730 40
//@node CD07733F-0 2010 40
//@node 43B4F268-0 2290 40
//@node 6ED6EF88-0 2570 40
//@node 2FF2B7D1-0 2850 40
//@node CD07733F-1 3130 40
//@node D65661DF-0 3410 40
//@node CD07733F-2 3690 40
//@node 96A4238F-0 3970 40
//@node 185BE2CF-0 40 40
//@node AA887513-0 330 40
//@node 7B50FF91-0 610 40
//@node 5DC3DC02-0 890 40
//@node F6D35D38-0 1170 40
//@node 8B5262A5-0 1450 40
//@node C87E5A45-0 1730 40
//@node 6ABCA7C6-0 2010 40
//@node B31D426A-0 2290 40
//@node 20B88AD9-0 2570 40
//@node 507CFF6F-0 2850 40
//@node 6ABCA7C6-1 3130 40
//@node D6BC09AD-0 3410 40
//@node 6ABCA7C6-2 3690 40
//@node C124CC99-0 3970 40
//@node 67C08020-0 40 40
//@node 2A40FFF9-0 330 40
//@node E8EC1633-0 610 40
//@node 12C59DCC-0 890 40
//@node 5ABD85BE-0 1170 40
//@node 3E258D4B-0 1450 40
//@node BCA1899B-0 1730 40
//@node 65042485-0 2010 40
//@node E4CF5408-0 2290 40
//@node 471229F6-0 2570 40
//@node F54F4B71-0 2850 40
//@node 65042485-1 3130 40
//@node 7AF7C4FF-0 3410 40
//@node 65042485-2 3690 40
//@node 1062652F-0 3970 40
//@node 7C247515-0 40 40
//@node 811E357B-0 330 40
//@node CCA11D79-0 610 40
//@node F05F069A-0 890 40
//@node 74AE9410-0 1170 40
//@node D04DF30D-0 1450 40
//@node 265B9FB9-0 1730 40
//@node 5EA732AC-0 2010 40
//@node E62DFD36-0 2290 40
//@node A737B7DF-0 2570 40
//@node A4C1A453-0 2850 40
//@node 5EA732AC-1 3130 40
//@node D3695219-0 3410 40
//@node 5EA732AC-2 3690 40
//@node 808EC2C5-0 3970 40
//@node 7F10A8D6-0 40 40
//@node F2C2FA95-0 330 40
//@node 5AF07F97-0 610 40
//@node 197C92D8-0 890 40
//@node 4A7C0A6A-0 1170 40
//@node 44FD734F-0 1450 40
//@node 103855A3-0 1730 40
//@node BC1219DB-0 2010 40
//@node F0A3AA10-0 2290 40
//@node 0724B89C-0 2570 40
//@node 235E6F49-0 2850 40
//@node BC1219DB-1 3130 40
//@node 081DE9B7-0 3410 40
//@node BC1219DB-2 3690 40
//@node 5AF5D0D7-0 3970 40
//@node 49C5B971-0 40 40
//@node E55264F9-0 330 40
//@node F3365959-0 125 145
//@node 9F471EEE-0 610 200
//@node F971C493-0 890 200
//@node 3F73FC8C-0 1170 200
//@node E550C4C8-0 1450 200
//@node 434E9D63-0 1730 200
//@node 33117F1A-0 2010 200
//@node A4009C0E-0 2290 200
//@node 5BB14A4E-0 2570 200
//@node A4009C0E-1 2850 200
//@node 5168A070-0 3130 200
//@node A4009C0E-2 3410 200
//@node E0B107E1-0 3690 200
//@node 1666DBA5-0 3970 200
//@node 9812681E-0 4530 200
//@node 59B30C78-0 4810 200
//@node CA3E22F7-0 5090 200
//@node 2D4BD5AE-0 5370 200
//@node 7B84FA30-0 5650 200
//@node D66D327B-0 5930 200
//@node 5DB39469-0 6210 200
//@node 190C5FD8-0 6490 200
//@node 39932E10-0 6770 200
//@node A5269C2C-0 7050 200
//@node 27CD9364-0 7330 200
//@node 2E02F1C2-0 7610 200
//@node D7368B96-0 7890 200
//@node F76CF4FE-0 8170 200
//@node 3DACFADF-0 8450 200
//@node 28A932E2-0 8730 200
//@node BFCAB9C8-0 9010 200
//@node BBAB112C-0 9290 200
//@node 3B993F42-0 9570 200
//@node 7779336B-0 9850 200
//@node 05519CA4-0 10130 200
//@node 437F1F4F-0 10410 200
//@node 7D92523F-0 10690 200
//@node 245CB15E-0 10970 200
//@node A4009C0E-3 11250 200
//@node 130A2088-0 11530 200
//@node 245CB15E-1 11810 200
//@node A4009C0E-4 12090 200
//@node F1871484-0 12370 200
//@node 839F9994-0 12650 200
//@node E836C13D-0 12930 200
//@node CEA88EBE-0 13210 200
//@node B7A890CB-0 13490 200
//@node 615694B2-0 13770 200
//@node 75B1B62C-0 40 40
//@node 3E9ED2B7-0 330 40
//@node A2BEF5A8-0 125 145
//@node B18A1E38-0 610 200
//@node 41AA0891-0 890 200
//@node 82430A65-0 1170 200
//@node 92E5D4C2-0 1450 200
//@node 56B34731-0 1730 200
//@node C7D7AA19-0 2010 200
//@node BF039D9E-0 2290 200
//@node 90DD5CEF-0 2570 200
//@node BF039D9E-1 2850 200
//@node 7FAA88EE-0 3130 200
//@node BF039D9E-2 3410 200
//@node A2D66FFB-0 3690 200
//@node 343A6B17-0 3970 200
//@node 22F1FB1C-0 4530 200
//@node AE4C8B6A-0 4810 200
//@node B9EEB2ED-0 5090 200
//@node DE2B3BC4-0 5370 200
//@node 68C376C7-0 5650 200
//@node 1DF71BE6-0 5930 200
//@node CE5E5387-0 6210 200
//@node 6E25210A-0 6490 200
//@node B26243D3-0 6770 200
//@node 017900EF-0 7050 200
//@node BFF68A57-0 7330 200
//@node DAF2941C-0 7610 200
//@node 05BB4300-0 7890 200
//@node 97EB3750-0 8170 200
//@node 052EE659-0 8450 200
//@node 0BC31289-0 8730 200
//@node CB6B6DC6-0 9010 200
//@node 977EE9A6-0 9290 200
//@node EB99D8B5-0 9570 200
//@node 32EC4239-0 9850 200
//@node C904A92E-0 10130 200
//@node 3BFD9045-0 10410 200
//@node D41A3E31-0 10690 200
//@node 48FDCAA4-0 10970 200
//@node EB99D8B5-1 11250 200
//@node DF657BA1-0 11530 200
//@node 48FDCAA4-1 11810 200
//@node EB99D8B5-2 12090 200
//@node B598DF4F-0 12370 200
//@node C990651A-0 12650 200
//@node 525B82A6-0 12930 200
//@node 6322B8B0-0 13210 200
//@node A31B91CD-0 13490 200
//@node 09BB5CC4-0 13770 200
//@node F23A0EA7-0 40 40
//@node C34B88BD-0 330 40
//@node 94A6EC31-0 125 145
//@node 6CBCAD5E-0 610 200
//@node 24CCC7E7-0 890 200
//@node 459A6F76-0 1170 200
//@node 15829D78-0 1450 200
//@node 3852DB53-0 1730 200
//@node BB024008-0 2010 200
//@node 8BA0C48B-0 2290 200
//@node 483827C4-0 2570 200
//@node 8BA0C48B-1 2850 200
//@node F9AC5DC1-0 3130 200
//@node 8BA0C48B-2 3410 200
//@node BF9096B1-0 3690 200
//@node 59681CF5-0 3970 200
//@node 66A167EE-0 4530 200
//@node 63A61548-0 4810 200
//@node 57DF7B87-0 5090 200
//@node D42E919E-0 5370 200
//@node CDE06C1A-0 5650 200
//@node 3E481871-0 5930 200
//@node 059A2B42-0 6210 200
//@node 7130D706-0 6490 200
//@node 9DECD2CF-0 6770 200
//@node B9BBBD1A-0 7050 200
//@node 575676D2-0 7330 200
//@node A9571392-0 7610 200
//@node CF5AE482-0 7890 200
//@node 392DBC7A-0 8170 200
//@node 89C77CCB-0 8450 200
//@node A342920C-0 8730 200
//@node A805B75C-0 9010 200
//@node 19974E08-0 9290 200
//@node 65F77DDC-0 9570 200
//@node D35D3B7B-0 9850 200
//@node E57307F4-0 10130 200
//@node FCEE4D9F-0 10410 200
//@node C709FFC2-0 10690 200
//@node 69C1AC2E-0 10970 200
//@node 65F77DDC-1 11250 200
//@node 55947FEA-0 11530 200
//@node 69C1AC2E-1 11810 200
//@node 65F77DDC-2 12090 200
//@node 1B6BAE72-0 12370 200
//@node 6B0979D4-0 12650 200
//@node 8F7AC6DF-0 12930 200
//@node BD8A4F52-0 13210 200
//@node 475B263B-0 13490 200
//@node 2C202582-0 13770 200
//@node 96C0B32A-0 40 40
//@node 51D17217-0 330 40
//@node 25154B3B-0 125 145
//@node B7B94A8C-0 610 200
//@node 533C28F9-0 890 200
//@node 5BECD49F-0 1170 200
//@node 7AA7F3DE-0 1450 200
//@node 1CD39345-0 1730 200
//@node AF4FCCEB-0 2010 200
//@node 990C7B54-0 2290 200
//@node 1C855D9B-0 2570 200
//@node 990C7B54-1 2850 200
//@node AEB29666-0 3130 200
//@node 990C7B54-2 3410 200
//@node 4D1CF277-0 3690 200
//@node D4F87933-0 3970 200
//@node D002C7A8-0 4530 200
//@node 13F8B956-0 4810 200
//@node 86864AD1-0 5090 200
//@node 01D8D808-0 5370 200
//@node 0CBADFA9-0 5650 200
//@node 2E411EAC-0 5930 200
//@node 18FE0565-0 6210 200
//@node DBA7AE31-0 6490 200
//@node 9E584259-0 6770 200
//@node CF5B9538-0 7050 200
//@node 7E4B286D-0 7330 200
//@node BB6048D0-0 7610 200
//@node 118B6648-0 7890 200
//@node A5EBE9E8-0 8170 200
//@node 633B3B31-0 8450 200
//@node B752784B-0 8730 200
//@node 8A33A86E-0 9010 200
//@node 9435F5AE-0 9290 200
//@node FCCE5DC7-0 9570 200
//@node 596234F5-0 9850 200
//@node 92DAA97A-0 10130 200
//@node 43742BD1-0 10410 200
//@node 21A19150-0 10690 200
//@node 9A735B89-0 10970 200
//@node FCCE5DC7-1 11250 200
//@node 5C8EE405-0 11530 200
//@node 21A19150-1 11810 200
//@node FCCE5DC7-2 12090 200
//@node 1F618EBE-0 12370 200
//@node 1115D53D-0 12650 200
//@node B475A2E0-0 12930 200
//@node 63B0D338-0 13210 200
//@node CCED70B1-0 13490 200
//@node B98A7618-0 13770 200
//@node 73E77385-0 40 40
//@node 3342B259-0 330 40
//@node 587E1AC9-0 125 145
//@node 271DE11E-0 610 200
//@node 16FB368B-0 890 200
//@node 7107ED38-0 1170 200
//@node 80FF20B8-0 1450 200
//@node 96512493-0 1730 200
//@node 84689A86-0 2010 200
//@node 2295A751-0 2290 200
//@node 781730CB-0 2570 200
//@node 2295A751-1 2850 200
//@node F92EF301-0 3130 200
//@node 2295A751-2 3410 200
//@node C31A5971-0 3690 200
//@node EAC984B5-0 3970 200
//@node 96A456AE-0 4530 200
//@node F5077D08-0 4810 200
//@node 3B1357C7-0 5090 200
//@node A691E3DE-0 5370 200
//@node 759F6F44-0 5650 200
//@node 7FAC130F-0 5930 200
//@node 9CA71C08-0 6210 200
//@node 0D604944-0 6490 200
//@node 0728CCBC-0 6770 200
//@node 4389B7F8-0 7050 200
//@node 0586EAA5-0 7330 200
//@node 6F717E52-0 7610 200
//@node 4EE5F40E-0 7890 200
//@node E7FF1466-0 8170 200
//@node 7DF25887-0 8450 200
//@node D3EF0786-0 8730 200
//@node 82B87EA0-0 9010 200
//@node CEB6AE64-0 9290 200
//@node 653CC2C6-0 9570 200
//@node 2934BCBB-0 9850 200
//@node 97C8A7B4-0 10130 200
//@node B7EE8F5F-0 10410 200
//@node 4969D585-0 10690 200
//@node FC4D2302-0 10970 200
//@node 653CC2C6-1 11250 200
//@node FC50747D-0 11530 200
//@node 4969D585-1 11810 200
//@node 653CC2C6-2 12090 200
//@node 1E945650-0 12370 200
//@node 8C150F4D-0 12650 200
//@node 8DAFC621-0 12930 200
//@node 56084B36-0 13210 200
//@node 3B7F73FB-0 13490 200
//@node 838B7F42-0 13770 200
//@node 64845A35-0 40 40
//@node D44A1AA7-0 330 40
//@node 5803571F-0 610 40
//@node F0A08C6C-0 890 40
//@node 1CB9ED76-0 1170 40
//@node 68168DBD-0 1450 40
//@node 1CB9ED76-1 1730 40
//@node 13F5E83A-0 2010 40
//@node 7149C69B-0 2290 40
//@node 20C10E38-0 2570 40
//@node 4AE4B227-0 40 40
//@node 976C89C3-0 330 40
//@node DB8572ED-0 125 145
//@node 5CFA58D7-0 610 200
//@node 1D1CD57E-0 890 40
//@node 62AC0B6E-0 685 145
//@node 89B78B6C-0 1170 200
//@node 4B7509B9-0 1450 40
//@node A27CF07D-0 1245 145
//@node 228EE585-0 1730 200
//@node 2F741BDC-0 2010 40
//@node 100A38C3-0 1805 145
//@node D55744B2-0 2290 200
//@node 52EFE9D7-0 2570 40
//@node 9DC26FB4-0 2365 145
//@node 63D17A13-0 2850 200
//@node 5CFA58D7-1 3130 200
//@node 4BE4B3BA-0 40 40
//@node 3449B3EC-0 330 40
//@node E17EBA2B-0 125 145
//@node 140F1D56-0 610 200
//@node CE43D35D-0 890 40
//@node 788019A6-0 685 145
//@node 2A4251E5-0 1170 200
//@node 577BA762-0 1450 40
//@node 7C44F183-0 1245 145
//@node 2789B6CC-0 1730 200
//@node 2B79C1D3-0 2010 40
//@node 42DC7BC8-0 1805 145
//@node DEDE8BF3-0 2290 200
//@node F22E0958-0 2570 40
//@node 2F874E53-0 2365 145
//@node 4590E692-0 2850 200
//@node 2A4251E5-1 3130 200
//@node 4CE4B54D-0 40 40
//@node 5972A2D9-0 330 40
//@node 53871F66-0 125 145
//@node 97E567FD-0 610 200
//@node C41BD668-0 890 40
//@node 0C8FCCCE-0 685 145
//@node DB8B7CCE-0 1170 200
//@node 88300763-0 1450 40
//@node 0F55338A-0 1245 145
//@node CBEE5DCF-0 1730 200
//@node BB724572-0 2010 40
//@node EBDF8B0F-0 1805 145
//@node 55E79FE0-0 2290 200
//@node A3AD76AD-0 2570 40
//@node FE00885C-0 2365 145
//@node CA3A9919-0 2850 200
//@node CBEE5DCF-1 3130 200
//@node 45E4AA48-0 40 40
//@node 0085D34A-0 330 40
//@node 526E842F-0 125 145
//@node BCA9546C-0 610 200
//@node 4233214F-0 890 40
//@node D5F6DC4A-0 685 145
//@node 8FEC21D7-0 1170 200
//@node 167E5D94-0 1450 40
//@node 9C3CDA8F-0 1245 145
//@node FE0FD0F6-0 1730 200
//@node 7948CAB1-0 2010 40
//@node 7A9121C6-0 1805 145
//@node B47BD041-0 2290 200
//@node 33ABAB56-0 2570 40
//@node C866974B-0 2365 145
//@node 6B1B3FC8-0 2850 200
//@node B47BD041-1 3130 200
//@node 46E4ABDB-0 40 40
//@node 5B011FD7-0 330 40
//@node 51177135-0 125 145
//@node 37481E23-0 610 200
//@node BBF4B8D2-0 890 40
//@node 29C810BE-0 685 145
//@node DCB90518-0 1170 200
//@node 89FC1B0D-0 1450 40
//@node 154E20EA-0 1245 145
//@node 41FC37D1-0 1730 200
//@node 8AEADE48-0 2010 40
//@node FB609238-0 1805 145
//@node 64E70FC6-0 2290 200
//@node 9F7DBFC3-0 2570 40
//@node 3027B9C9-0 2365 145
//@node B42AAC27-0 2850 200
//@node B42AAC27-1 3130 200
//@node 5445F512-0 40 40
//@node D8BDD555-0 330 40
//@node E8D4A101-0 610 40
//@node 9BD0D94D-0 890 40
//@node 2764E5A8-0 1170 40
//@node 15388C05-0 1450 40
//@node E5E1D456-0 1730 40
//@node 64F42B94-0 2010 40
//@node 4E85DA6B-0 2290 40
//@node 53285757-0 2570 40
//@node C14F307A-0 2850 40
//@node B10FD66E-0 3130 40
//@node E5E1D456-1 3410 40
//@node 0C76B160-0 3690 40
//@node 3D8197AE-0 3970 40
//@node DE7B857F-0 4250 40
//@node FB1485A8-0 4530 40
//@node 241E860B-0 4810 40
//@node E8D4A101-1 5090 40
//@node 9BD0D94D-1 5370 40
//@node C3C31897-0 5650 40
//@node 64F42B94-1 5930 40
//@node E5E1D456-2 6210 40
//@node 42CEBD27-0 6490 40
//@node D8E74E95-0 6770 40
//@node 9BD0D94D-2 7050 40
//@node 31B6DC4A-0 7330 40
//@node 64F42B94-2 7610 40
//@node E5E1D456-3 7890 40
//@node FB01C127-0 8170 40
//@node FEF2BA4B-0 40 40
//@node D13C5F98-0 330 40
//@node B6245A14-0 610 40
//@node 981ED210-0 890 40
//@node 17FEA833-0 1170 40
//@node 6831A971-0 1450 40
//@node 7C226C8C-0 1730 40
//@node 1947816A-0 2010 40
//@node 11D0DFA3-0 2290 40
//@node A7252371-0 2570 40
//@node 60B81B42-0 2850 40
//@node 8C69400E-0 3130 40
//@node 679006A1-0 3410 40
//@node 3F5143C3-0 3690 40
//@node BECFB403-0 3970 40
//@node F0E49695-0 4250 40
//@node 7442A4AE-0 40 40
//@node 40FC17F7-0 330 40
//@node 082C14ED-0 610 40
//@node 107D1FC8-0 890 40
//@node CA1DF625-0 1170 40
//@node FE935CC7-0 1450 40
//@node CE7EAD4E-0 1730 40
//@node B524B011-0 2010 40
//@node 40FC17F7-1 2290 40
//@node 163521CA-0 2570 40
//@node 3FF1758E-0 2850 40
//@node 05BC661B-0 3130 40
//@node 32F9F8D1-0 40 40
//@node ACF90D3D-0 330 40
//@node BD625C23-0 610 40
//@node 62D28BD5-0 890 40
//@node D9BDD176-0 1170 40
//@node 027F2542-0 1450 40
//@node FDC41B1E-0 1730 40
//@node 73FB8593-0 2010 40
//@node 9369BBDB-0 2290 40
//@node E6C432B5-0 40 40
//@node 7855A04B-0 330 40
//@node 20C917F8-0 610 40
//@node 5DD547D0-0 890 40
//@node 4C26BB9F-0 1170 40
//@node 519FA113-0 1450 40
//@node 644DF34A-0 1730 40
//@node D208BDC0-0 2010 40
//@node 7582EDE2-0 2290 40
//@node A64D4E10-0 40 40
//@node 4A844FDB-0 330 40
//@node B832CE32-0 40 40
//@node C0A50EFE-0 330 40
//@node DDD88BF8-0 610 40
//@node 085FD2BC-0 890 40
//@node B5A19728-0 1170 40
//@node AF4A40D1-0 1450 40
//@node 32687650-0 40 40
//@node 661149AF-0 330 40
//@node 5531D4DD-0 610 40
//@node C6E6DF2F-0 890 40
//@doomscript-blueprint end
