#include "script/map_alphalabs3_crane.script"

namespace map_alphalabs3 {
	

	void fade_combat_speaker() {
		$xspeaker_1.fadeSound ( SND_CHANNEL_ANY, -60, 10 );
		$speaker_8.fadeSound ( SND_CHANNEL_ANY, -60, 10 );
	
	}
	
	////////////////////////////////////////////////////
	//
	//	activate waste lift
	//
	////////////////////////////////////////////////////
	void waste_lift_up()
	{
		//spawner
		sys.trigger ($deathsquad_spawn);

		//raises waste lift
		$waste_lift.time (3);
		$waste_lift.accelTime (.1);
		$waste_lift.decelTime (.1);
		$waste_lift.move (UP, 256);

		//opens waste lift doors
		sys.wait (1);
		sys.trigger ($waste_lift_door_l);
	}

	
	////////////////////////////////////////////////////
	//
	//	break the little al3_platform
	//
	////////////////////////////////////////////////////
	void al3_platform_break()
	{
		//set the bottom call gui to malfunction
		//so it can't be called twice
		$func_static_4685.setGuiParm("gui_parm5" , 2);
		$func_static_3921.setGuiParm("gui_parm5" , 2);
		$func_static_4685.setShaderParm(7 , 0);
		$func_static_3921.setShaderParm(7 , 0);


		//first move down
		$al3_platform_break.time ( 2.5 );
		$al3_platform_break.accelTime ( .5 );
		$al3_platform_break.decelTime ( 0 );
		sys.trigger ($lspeaker_1);
		
		$al3_platform.startSoundShader ("broken_plat_2_5s", SND_CHANNEL_VOICE2 );
		
		$al3_platform_break.move ( DOWN, 190 );

		sys.waitFor ($al3_platform_break);

		//bounce a bit or something
		sys.trigger ($broke_spark);
		$al3_platform_break.time ( .2 );
		$al3_platform_break.accelTime ( .2 );
		$al3_platform_break.decelTime ( 0 );
		$al3_platform_break.move ( UP, 6 );

		sys.waitFor ($al3_platform_break);

		$al3_platform_break.time ( .2 );
		$al3_platform_break.accelTime ( 0 );
		$al3_platform_break.decelTime ( .2 );
		$al3_platform_break.move ( DOWN, 8 );

		//rotate a about 24 degrees
		$al3_platform_break.time ( .6 );
		$al3_platform_break.accelTime ( .6 );
		$al3_platform_break.decelTime ( 0 );
		
		$al3_platform_break.startSoundShader ("platbreak_01", SND_CHANNEL_VOICE );
		
		$al3_platform_break.rotateOnce ( '-24 5 0' );

		sys.waitFor ($al3_platform_break);

		$al3_platform_break.time ( .1 );
		$al3_platform_break.accelTime ( .1 );
		$al3_platform_break.decelTime ( 0 );
		
		$al3_platform_break.startSoundShader ("platbreak_02", SND_CHANNEL_BODY );
		
		$al3_platform_break.rotateOnce ( '1 0 0' );

		sys.waitFor ($al3_platform_break);

		$al3_platform_break.rotateOnce ( '-1 0 0' );
	}

	void cache_sounds() {
		sys.cacheSoundShader ("broken_plat_2_5s");
		sys.cacheSoundShader ("platbreak_01");
		sys.cacheSoundShader ("platbreak_02");
	}


	//////////////////////////////////////////////////////////
	//
	//     Vent cover opener
	//
	//////////////////////////////////////////////////////////
	void open_vent_cover() {
		$ventcover1.rotateOnce('0 0 -120');
	}

	void main() {
		cache_sounds();
		init_crane();
	}
}

//@doomscript-blueprint begin 6
//@source DF71984D
//@catalog 0C260740
//@node 94F513E6-0 40 40
//@node 0A75B8A4-0 330 40
//@node 06B5FEF7-0 610 40
//@node 37F214B5-0 40 40
//@node 041CF890-0 330 40
//@node FBADA9CD-0 610 40
//@node 4BA6EEE3-0 890 40
//@node 3C48B42E-0 1170 40
//@node 44E11696-0 1450 40
//@node 87C7B484-0 1730 40
//@node 31ADCC48-0 2010 40
//@node CEAADD61-0 40 40
//@node AAA0832E-0 330 40
//@node B048714E-0 610 40
//@node 5961237C-0 890 40
//@node 97F71B5C-0 1170 40
//@node 716568CF-0 1450 40
//@node 6B488DAF-0 1730 40
//@node F3A2D88F-0 2010 40
//@node F2080D19-0 2290 40
//@node 30F1EE90-0 2570 40
//@node 6CC4B6B8-0 2850 40
//@node 5EBA3524-0 3130 40
//@node 3206415F-0 3410 40
//@node 29347C7E-0 3690 40
//@node 24B37D9C-0 3970 40
//@node F3A2D88F-1 4250 40
//@node 9F5D0461-0 4530 40
//@node 5EBA3524-1 4810 40
//@node 29347C7E-1 5090 40
//@node 0118B864-0 5370 40
//@node BFDA9ADD-0 5650 40
//@node 056CB84E-0 5930 40
//@node 5F9A5752-0 6210 40
//@node 34A0D008-0 6490 40
//@node F3A2D88F-2 6770 40
//@node 8E3295D1-0 7050 40
//@node 41D7AC11-0 7330 40
//@node 5EBA3524-2 7610 40
//@node 6EDC09F1-0 7890 40
//@node CB5A5893-0 8170 40
//@node F3A2D88F-3 8450 40
//@node 18D0DFF4-0 8730 40
//@node 847CEDE8-0 9010 40
//@node 5EBA3524-3 9290 40
//@node C7EDFE89-0 9570 40
//@node B832CE32-0 40 40
//@node 38E9278C-0 330 40
//@node 18351587-0 610 40
//@node 51EEEDD4-0 890 40
//@node EBB59E31-0 40 40
//@node 972D6424-0 330 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 3E9D370A-0 610 40
//@doomscript-blueprint end
