namespace map_admin1
{
	void archiver2_cycle( entity capsule )
	{
		capsule.time( 1.0 );
		capsule.decelTime( 0.25 );
		capsule.moveTo( $capsule_staging );
		//staging speaker - 1sec
		//capsule slides out to loading position
		sys.trigger ($speaker_archiver_staging);
		sys.waitFor( capsule );

		// receive a new capsule
		$archiver2_joint.time( 0.5 );
		$archiver2_joint.move( FORWARD, 24 );
		//loading speaker #1 - .5sec
		//carrier moves a bit to accept capsule
		sys.trigger ($speaker_archiver_loading1);
		sys.waitFor( $archiver2_joint );

		capsule.accelTime( 0.1 );
		capsule.time( 0.5 );
		capsule.decelTime( 0.1 );
		capsule.moveTo( $archiver2_carrier );
		//loading speaker #2 - .5sec
		//capsule moves into carrier
		sys.trigger ($speaker_archiver_loading2);
		sys.waitFor( capsule );

		capsule.bind( $archiver2_carrier );
		sys.wait( 0.5 );

		$archiver2_joint.time( 0.5 );
		$archiver2_joint.move( BACK, 24 );
		//loading speaker #1 - .5sec
		//carrier moves back after accepting capsule
		sys.trigger ($speaker_archiver_loading1);
		sys.waitFor( $archiver2_joint );

// 3.0s
		// rotate over to depository2
		$archiver2_arm.accelTime( 0.25 );
		$archiver2_arm.time( 0.5 );
		$archiver2_arm.decelTime( 0.25 );
		$archiver2_arm.rotateDownTo( Y_AXIS, 315 );
		//Arm2 short speaker  - .5sec
		//Arm2 moves
		sys.trigger ($speaker_archiver_arm2_short);
		sys.waitFor( $archiver2_arm );

		// place the capsule into the archiver
		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.rotateUpTo( X_AXIS, 75 );
		//depository2 speaker #1 - .5sec
		//carrier turns
		sys.trigger ($speaker_archiver_depository2_1);
		sys.waitFor( $archiver2_carrier );

		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.move( REL_FORWARD, 16 );
		//depository2 speaker #2 - .5sec
		//carrier moves a bit
		sys.trigger ($speaker_archiver_depository2_2);
		sys.waitFor( $archiver2_carrier );

		// time = 0.5
		capsule.move( LEFT, 44 );
		//depository2 speaker #3 - .5sec
		//capsule moves into/outof depository
		sys.trigger ($speaker_archiver_depository2_3);
		sys.waitFor( capsule );

		// trigger GUI to animate
		$func_static_2764.setGuiParm( "gui_parm1", 1 );
		sys.wait( 2.5 );

		$func_static_2764.setGuiParm( "gui_parm1", 0 );

		// time = 0.5
		capsule.move( RIGHT, 44 );
		//depository2 speaker #3 - .5sec
		//capsule moves into/outof depository
		sys.trigger ($speaker_archiver_depository2_3);
		sys.waitFor( capsule );

// 8.0s
		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.move( REL_BACK, 16 );
		//depository2 speaker #2 - .5sec
		//carrier moves a bit
		sys.trigger ($speaker_archiver_depository2_2);
		sys.waitFor( $archiver2_carrier );

		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.rotateDownTo( X_AXIS, 0 );
		//depository2 speaker #1 - .5sec
		//carrier turns
		sys.trigger ($speaker_archiver_depository2_1);
		sys.waitFor( $archiver2_carrier );

		// rotate over to dump2
		$archiver2_arm.time( 1.5 );
		$archiver2_arm.rotateDownTo( Y_AXIS, 180 );
		//Arm2 long speaker  - 1.5sec
		//Arm2 moves
		sys.trigger ($speaker_archiver_arm2_long);
		sys.waitFor( $archiver2_arm );

		// dispose of the capsule
		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.rotateUpTo( X_AXIS, 30 );
		//dump2 speaker #1 - .5sec
		//carrier turns
		sys.trigger ($speaker_archiver_dump2_1);
		sys.waitFor( $archiver2_carrier );

		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.move( REL_FORWARD, 16 );
		//dump2 speaker #2 - .5sec
		//carrier moves a bit
		sys.trigger ($speaker_archiver_dump2_2);
		sys.waitFor( $archiver2_carrier );

// 11.5s
		capsule.unbind();

		capsule.accelTime( 0.1 );
		capsule.time( 0.5 );
		capsule.decelTime( 0.1 );
		capsule.move( REL_LEFT, 128 );
		//dump1 speaker #3 - .5sec
		//capsule moves into dump
		sys.trigger ($speaker_archiver_dump2_3);
		sys.waitFor( capsule );

		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.move( REL_BACK, 16 );
		//dump2 speaker #2 - .5sec
		//carrier moves a bit
		sys.trigger ($speaker_archiver_dump2_2);
		sys.waitFor( $archiver2_carrier );

		$archiver2_carrier.time( 0.5 );
		$archiver2_carrier.rotateDownTo( X_AXIS, 0 );
		//dump2 speaker #1 - .5sec
		//carrier turns
		sys.trigger ($speaker_archiver_dump2_1);
		sys.waitFor( $archiver2_carrier );

		// rotate over to incomming capsules
		$archiver2_arm.time( 2.0 );
		$archiver2_arm.rotateDownTo( Y_AXIS, 0 );
		//Arm2 longer speaker  - 2sec
		//Arm2 moves
		sys.trigger ($speaker_archiver_arm2_longer);
		sys.waitFor( $archiver2_arm );

// 15.0s
		// reset the capsule
		capsule.restorePosition();
	}

	void archiver1_cycle( entity capsule )
	{
		while( true )
		{
			capsule.time( 1.0 );
			capsule.decelTime( 0.25 );
			capsule.moveTo( $capsule_staging );
			//staging speaker - 1sec
			//capsule slides out to loading position
			sys.trigger ($speaker_archiver_staging);
			sys.waitFor( capsule );

			// receive a new capsule
			$archiver1_joint.time( 0.5 );
			$archiver1_joint.move( FORWARD, 24 );
			//loading speaker #1 - .5sec
			//carrier moves a bit to accept capsule
			sys.trigger ($speaker_archiver_loading1);
			sys.waitFor( $archiver1_joint );

			capsule.accelTime( 0.1 );
			capsule.time( 0.5 );
			capsule.decelTime( 0.1 );
			capsule.moveTo( $archiver1_carrier );
			//loading speaker #2 - .5sec
			//capsule moves into carrier
			sys.trigger ($speaker_archiver_loading2);
			sys.waitFor( capsule );

			capsule.bind( $archiver1_carrier );
			sys.wait( 0.5 );

			$archiver1_joint.time( 0.5 );
			$archiver1_joint.move( BACK, 24 );
			//loading speaker #1 - .5sec
			//carrier moves back after accepting capsule
			sys.trigger ($speaker_archiver_loading1);
			sys.waitFor( $archiver1_joint );

// 3.0s
			// rotate over to depository1
			$archiver1_arm.accelTime( 0.25 );
			$archiver1_arm.time( 1.5 );
			$archiver1_arm.decelTime( 0.25 );
			$archiver1_arm.rotateDownTo( Y_AXIS, 45 );
			//Arm1 long speaker  - 1.5sec
			//Arm1 moves
			sys.trigger ($speaker_archiver_arm1_long);
			sys.waitFor( $archiver1_arm );

			// place the capsule into the archiver
			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.rotateUpTo( X_AXIS, 75 );
			//depository1 speaker #1 - .5sec
			//carrier turns
			sys.trigger ($speaker_archiver_depository1_1);
			sys.waitFor( $archiver1_carrier );

			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.move( REL_FORWARD, 16 );
			//depository1 speaker #2 - .5sec
			//carrier moves a bit
			sys.trigger ($speaker_archiver_depository1_2);
			sys.waitFor( $archiver1_carrier );

			// time = 0.5
			capsule.move( LEFT, 40 );
			//depository1 speaker #3 - .5sec
			//capsule moves into/outof depository
			sys.trigger ($speaker_archiver_depository1_3);
			sys.waitFor( capsule );

			//start the second arm mechanism
			thread archiver2_cycle( $capsule2 );

			// trigger GUI to animate
			$func_static_2767.setGuiParm( "gui_parm1", 1 );
			sys.wait( 2.5 );

			$func_static_2767.setGuiParm( "gui_parm1", 0 );

			// time = 0.5
			capsule.move( RIGHT, 40 );
			//depository1 speaker #3 - .5sec
			//capsule moves into/outof depository
			sys.trigger ($speaker_archiver_depository1_3);
			sys.waitFor( capsule );
// 9.0s
			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.move( REL_BACK, 16 );
			//depository1 speaker #2 - .5sec
			//carrier moves a bit
			sys.trigger ($speaker_archiver_depository1_2);
			sys.waitFor( $archiver1_carrier );

			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.rotateDownTo( X_AXIS, 0 );
			//depository1 speaker #1 - .5sec
			//carrier turns
			sys.trigger ($speaker_archiver_depository1_1);
			sys.waitFor( $archiver1_carrier );

			// rotate over to dump1
			$archiver1_arm.time( 1.5 );
			$archiver1_arm.rotateDownTo( Y_AXIS, 270 );
			//Arm1 long speaker  - 1.5sec
			//Arm1 moves
			sys.trigger ($speaker_archiver_arm1_long);
			sys.waitFor( $archiver1_arm );

			// dispose of the capsule
			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.rotateUpTo( X_AXIS, 30 );
			//dump1 speaker #1 - .5sec
			//carrier turns
			sys.trigger ($speaker_archiver_dump1_1);
			sys.waitFor( $archiver1_carrier );

			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.move( REL_FORWARD, 16 );
			//dump1 speaker #2 - .5sec
			//carrier moves a bit
			sys.trigger ($speaker_archiver_dump1_2);
			sys.waitFor( $archiver1_carrier );

// 12.5s
			capsule.unbind();

			capsule.accelTime( 0.1 );
			capsule.time( 0.5 );
			capsule.decelTime( 0.1 );
			capsule.move( REL_LEFT, 128 );
			//dump1 speaker #3 - .5sec
			//capsule moves into dump
			sys.trigger ($speaker_archiver_dump1_3);
			sys.waitFor( capsule );

			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.move( REL_BACK, 16 );
			//dump1 speaker #2 - .5sec
			//carrier moves a bit
			sys.trigger ($speaker_archiver_dump1_2);
			sys.waitFor( $archiver1_carrier );

			$archiver1_carrier.time( 0.5 );
			$archiver1_carrier.rotateDownTo( X_AXIS, 0 );
			//dump1 speaker #1 - .5sec
			//carrier turns
			sys.trigger ($speaker_archiver_dump1_1);
			sys.waitFor( $archiver1_carrier );

			// rotate over to incomming capsules
			$archiver1_arm.time( 1.0 );
			$archiver1_arm.rotateDownTo( Y_AXIS, 180 );
			//Arm1 short speaker  - 1sec
			//Arm1 moves
			sys.trigger ($speaker_archiver_arm1_short);
			sys.waitFor( $archiver1_arm );

// 15.0s
			// reset the capsule
			capsule.restorePosition();
		}
	}


	void archivers_setup()
	{
		// setup archiving unit 1
		$archiver1_carrier.bind( $archiver1_joint );

		$archiver1_joint.time( 0.1 );
		$archiver1_joint.rotateUpTo( Y_AXIS, 90 );
		sys.waitFor( $archiver1_joint );

		$archiver1_arm.time( 0.1 );
		$archiver1_arm.rotateUpTo( Y_AXIS, 180 );
		sys.waitFor( $archiver1_arm );

		$archiver1_joint.bind( $archiver1_arm );

		// bind the arm so that both arms stop when one is blocked
		$archiver1_arm.bind( $func_static_2683 );

		// setup archiving unit 2
		$archiver2_carrier.bind( $archiver2_joint );

		$archiver2_joint.time( 0.1 );
		$archiver2_joint.rotateUpTo( Y_AXIS, 90 );
		sys.waitFor( $archiver2_joint );

		$archiver2_arm.time( 0.1 );
		$archiver2_arm.rotateUpTo( Y_AXIS, 0 );
		sys.waitFor( $archiver2_arm );

		$archiver2_joint.bind( $archiver2_arm );

		// bind the arm so that both arms stop when one is blocked
		$archiver2_arm.bind( $func_static_2683 );

		// setup reader tube 1
		$archiver1_reader.bind( $archiver_reader_parent );

		$archiver_reader_parent.time( 0.1 );
		$archiver_reader_parent.rotateUpTo( Y_AXIS, 45 );
		sys.waitFor( $archiver_reader_parent );

		$archiver1_reader.time( 0.1 );
		$archiver1_reader.rotateUpTo( X_AXIS, 75 );
		sys.waitFor( $archiver1_reader );

		$archiver1_reader.move( REL_FORWARD, 64 );
		sys.waitFor( $archiver1_reader );

		$archiver1_reader.unbind();
		$archiver_reader_parent.restorePosition();

		// setup reader tube 2
		$archiver2_reader.bind( $archiver_reader_parent );

		$archiver_reader_parent.time( 0.1 );
		$archiver_reader_parent.rotateDownTo( Y_AXIS, 315 );
		sys.waitFor( $archiver_reader_parent );

		$archiver2_reader.time( 0.1 );
		$archiver2_reader.rotateUpTo( X_AXIS, 75 );
		sys.waitFor( $archiver2_reader );

		$archiver2_reader.move( REL_FORWARD, 64 );
		sys.waitFor( $archiver2_reader );

		$archiver2_reader.unbind();
		$archiver_reader_parent.restorePosition();

		// setup dump tube 1
		$archiver1_dump.bind( $archiver_reader_parent );

		$archiver_reader_parent.time( 0.1 );
		$archiver_reader_parent.rotateUpTo( Y_AXIS, 180 );
		sys.waitFor( $archiver_reader_parent );

		$archiver1_dump.time( 0.1 );
		$archiver1_dump.rotateUpTo( X_AXIS, 30 );
		sys.waitFor( $archiver1_dump );

		$archiver1_dump.move( REL_FORWARD, 64 );
		sys.waitFor( $archiver1_dump );

		$archiver1_dump.unbind();
		$archiver_reader_parent.restorePosition();

		// setup dump tube 2
		$archiver2_dump.bind( $archiver_reader_parent );

		$archiver_reader_parent.time( 0.1 );
		$archiver_reader_parent.rotateUpTo( Y_AXIS, 270 );
		sys.waitFor( $archiver_reader_parent );

		$archiver2_dump.time( 0.1 );
		$archiver2_dump.rotateUpTo( X_AXIS, 30 );
		sys.waitFor( $archiver2_dump );

		$archiver2_dump.move( REL_FORWARD, 64 );
		sys.waitFor( $archiver2_dump );

		$archiver2_dump.unbind();
		$archiver_reader_parent.remove();

		// run the loops
		thread archiver1_cycle( $capsule1 );
	}

	void kill_wounded_marine()
	{
		$tim_admin_wounded_marine_1.kill();
	}

	void main()
	{
		//$swinglight_mover.sway( 2, 0, '40 15 0' );
		$swinglight_mover.sway( 50, 0, '20 0 0' );
		$library_lamp1_swing_anchor.sway( 3, 0, '15 10 0' );
		$library_lamp1_swing_anchor2.sway( 3.5, 0, '7 5 5' );

		archivers_setup();
	}
}

//@doomscript-blueprint begin 6
//@source 695343F4
//@catalog 0C260740
//@node 4CB31498-0 40 40
//@node 53C658E7-0 330 40
//@node DCAEB710-0 610 40
//@node 8BD828B0-0 890 40
//@node D8149D9B-0 1170 40
//@node 4B5FA0B4-0 1450 40
//@node 1833751D-0 1730 40
//@node 3D4315A3-0 2010 40
//@node 9B75851D-0 2290 40
//@node F8FE0608-0 2570 40
//@node 678EC941-0 2850 40
//@node 06E458C7-0 3130 40
//@node 3EA70A54-0 3410 40
//@node 9E760DC8-0 3690 40
//@node D49EC93C-0 3970 40
//@node 4B5FA0B4-1 4250 40
//@node 20AA769D-0 4530 40
//@node A9418921-0 4810 40
//@node 1833751D-1 5090 40
//@node B0083151-0 5370 40
//@node 9B75851D-1 5650 40
//@node F8FE0608-1 5930 40
//@node 53CF5C0B-0 6210 40
//@node D00545FB-0 6490 40
//@node 8F11CA94-0 6770 40
//@node 6815CA1F-0 7050 40
//@node A0678CBB-0 7330 40
//@node B441CBBE-0 7610 40
//@node 4F1A6BCD-0 7890 40
//@node 1F75C244-0 8170 40
//@node FD080C12-0 8450 40
//@node DF4CE808-0 8730 40
//@node 4F1A6BCD-1 9010 40
//@node 51DED468-0 9290 40
//@node 10BB2D6F-0 9570 40
//@node DF4CE808-1 9850 40
//@node 4E496CBF-0 10130 40
//@node 1BD96BD0-0 10410 40
//@node 4B5FA0B4-2 10690 40
//@node B43EB0DA-0 10970 40
//@node 11293787-0 11250 40
//@node 20D8BFF3-0 11530 40
//@node A9EB1B32-0 11810 40
//@node 1BD96BD0-1 12090 40
//@node 4B5FA0B4-3 12370 40
//@node 4F1A6BCD-2 12650 40
//@node 84A52826-0 12930 40
//@node 10BB2D6F-1 13210 40
//@node DF4CE808-2 13490 40
//@node 4F1A6BCD-3 13770 40
//@node D0419FED-0 14050 40
//@node FD080C12-1 14330 40
//@node DF4CE808-3 14610 40
//@node A8807286-0 14890 40
//@node B412E5FF-0 15170 40
//@node 4B93FFA9-0 15450 40
//@node B441CBBE-1 15730 40
//@node 4F1A6BCD-4 16010 40
//@node C93DCBBD-0 16290 40
//@node CACCA0B2-0 16570 40
//@node DF4CE808-4 16850 40
//@node 4F1A6BCD-5 17130 40
//@node 51DED468-1 17410 40
//@node DD428D8F-0 17690 40
//@node DF4CE808-5 17970 40
//@node BD2FA3A7-0 18250 40
//@node 678EC941-1 18530 40
//@node 06E458C7-1 18810 40
//@node 3EA70A54-1 19090 40
//@node 117E8D32-0 19370 40
//@node E860CBF0-0 19650 40
//@node 4B5FA0B4-4 19930 40
//@node 4F1A6BCD-6 20210 40
//@node 84A52826-1 20490 40
//@node DD428D8F-1 20770 40
//@node DF4CE808-6 21050 40
//@node 4F1A6BCD-7 21330 40
//@node D0419FED-1 21610 40
//@node CACCA0B2-1 21890 40
//@node DF4CE808-7 22170 40
//@node 378B4980-0 22450 40
//@node 6A69B3A6-0 22730 40
//@node 2B3326E6-0 23010 40
//@node B441CBBE-2 23290 40
//@node E22FAC7E-0 23570 40
//@node B095B3E5-0 40 40
//@node BB975797-0 330 40
//@node 5F6F1DA5-0 125 145
//@node 50934C98-0 610 200
//@node 3F9A2837-0 890 200
//@node 979ACDA9-0 1170 200
//@node 95989A0C-0 1450 200
//@node DAEEC385-0 1730 200
//@node D665ECFF-0 2010 200
//@node 19EB0B21-0 2290 200
//@node D09EA880-0 2570 200
//@node B236ACB0-0 2850 200
//@node 0BCF2CD0-0 3130 200
//@node 3F951E30-0 3410 200
//@node 226558D1-0 3690 200
//@node 673BA2EE-0 3970 200
//@node 17267C01-0 4250 200
//@node DAEEC385-1 4530 200
//@node 45E15093-0 4810 200
//@node 83B7596A-0 5090 200
//@node D665ECFF-1 5370 200
//@node 9E2A17AB-0 5650 200
//@node D09EA880-1 5930 200
//@node B236ACB0-1 6210 200
//@node 9D2576E1-0 6490 200
//@node F152F208-0 6770 200
//@node 0CA603BE-0 7050 200
//@node EC0A64D5-0 7330 200
//@node F6EA0CC1-0 7610 200
//@node CE8600B6-0 7890 200
//@node 6823EB9B-0 8170 200
//@node 25168FA2-0 8450 200
//@node 4FBC860C-0 8730 200
//@node BD83F080-0 9010 200
//@node 6823EB9B-1 9290 200
//@node DE4DF0BA-0 9570 200
//@node 96940B6D-0 9850 200
//@node BD83F080-1 10130 200
//@node AEE50D16-0 10410 200
//@node 2113AF8E-0 10690 200
//@node DAEEC385-2 10970 200
//@node 6BA9824F-0 11250 200
//@node FFEDCF8E-0 11530 200
//@node 54418BBC-0 11810 200
//@node C28B7337-0 12090 200
//@node 7B0580E1-0 12370 200
//@node 2113AF8E-1 12650 200
//@node DAEEC385-3 12930 200
//@node 6823EB9B-2 13210 200
//@node 14C9ADEC-0 13490 200
//@node 96940B6D-1 13770 200
//@node BD83F080-2 14050 200
//@node 6823EB9B-3 14330 200
//@node E4462C07-0 14610 200
//@node 4FBC860C-1 14890 200
//@node BD83F080-3 15170 200
//@node F152F208-1 15450 200
//@node 82325513-0 15730 200
//@node F6EA0CC1-1 16010 200
//@node CE8600B6-1 16290 200
//@node 6823EB9B-4 16570 200
//@node BAD6CC43-0 16850 200
//@node ED6A4E8C-0 17130 200
//@node BD83F080-4 17410 200
//@node 6823EB9B-5 17690 200
//@node DE4DF0BA-1 17970 200
//@node 3441D3ED-0 18250 200
//@node BD83F080-5 18530 200
//@node B472A7F2-0 18810 200
//@node 0BCF2CD0-1 19090 200
//@node 3F951E30-1 19370 200
//@node 226558D1-1 19650 200
//@node F304622D-0 19930 200
//@node BEC1780E-0 20210 200
//@node DAEEC385-4 20490 200
//@node 6823EB9B-6 20770 200
//@node 14C9ADEC-1 21050 200
//@node 3441D3ED-1 21330 200
//@node BD83F080-6 21610 200
//@node 6823EB9B-7 21890 200
//@node E4462C07-1 22170 200
//@node ED6A4E8C-1 22450 200
//@node BD83F080-7 22730 200
//@node D561210D-0 23010 200
//@node 656D82B5-0 23290 200
//@node 6CDF6AF3-0 23570 200
//@node CE8600B6-2 23850 200
//@node 95CB80F1-0 24130 200
//@node FCB40A80-0 40 40
//@node 21642565-0 330 40
//@node D7693D1E-0 610 40
//@node 01A86469-0 890 40
//@node F86DCCB7-0 1170 40
//@node 7195DAB4-0 1450 40
//@node 072B0A75-0 1730 40
//@node 80716BAD-0 2010 40
//@node C9AB259F-0 2290 40
//@node 5728E4AC-0 2570 40
//@node 4BD9236B-0 2850 40
//@node B7F5C25D-0 3130 40
//@node 1338C210-0 3410 40
//@node 4FF15924-0 3690 40
//@node 5F9FCE9B-0 3970 40
//@node 308BF42F-0 4250 40
//@node 66D91D9A-0 4530 40
//@node 132A9C21-0 4810 40
//@node D16F1C3B-0 5090 40
//@node C7F5D3C3-0 5370 40
//@node B404DAA3-0 5650 40
//@node 357C3960-0 5930 40
//@node 66E814CC-0 6210 40
//@node 824D58E3-0 6490 40
//@node 3E64CF0E-0 6770 40
//@node 582D3BD8-0 7050 40
//@node 1F4D1565-0 7330 40
//@node 582D3BD8-1 7610 40
//@node A45786EF-0 7890 40
//@node 382DAAE6-0 8170 40
//@node 801866B2-0 8450 40
//@node B404DAA3-1 8730 40
//@node CDBBCE33-0 9010 40
//@node 66E814CC-1 9290 40
//@node 324A6D06-0 9570 40
//@node 655254F1-0 9850 40
//@node 6E50C971-0 10130 40
//@node 986BF83C-0 10410 40
//@node 6E50C971-1 10690 40
//@node 0E072190-0 10970 40
//@node 382DAAE6-1 11250 40
//@node FE409E30-0 11530 40
//@node B404DAA3-2 11810 40
//@node 923F38F6-0 12090 40
//@node 66E814CC-2 12370 40
//@node E367C550-0 12650 40
//@node 5E62CFCA-0 12930 40
//@node 1A5677DF-0 13210 40
//@node C94042CA-0 13490 40
//@node 1A5677DF-1 13770 40
//@node BA23F656-0 14050 40
//@node 382DAAE6-2 14330 40
//@node 394426A9-0 14610 40
//@node B404DAA3-3 14890 40
//@node EFD7D05C-0 15170 40
//@node 66E814CC-3 15450 40
//@node CEE38F35-0 15730 40
//@node 94D1EFC9-0 16010 40
//@node FA4A417E-0 16290 40
//@node 43C4ACB3-0 16570 40
//@node FA4A417E-1 16850 40
//@node B7B440E5-0 17130 40
//@node 871039FB-0 17410 40
//@node 9035F44E-0 17690 40
//@node 48F3910B-0 40 40
//@node D8C80AE5-0 330 40
//@node 32687650-0 40 40
//@node 4A7A6115-0 330 40
//@node 0A4A0D60-0 610 40
//@node DAD2186B-0 890 40
//@node A4A8A217-0 1170 40
//@doomscript-blueprint end
