namespace map_alphalabs1 {

float PLAYMUSIC = TRUE;
float monsterstatus = 1;
float	GATE_OPEN = 0;

void init_world()
{
	$epd_emlight.rotate ('0 -360 0');
	//$epd_light1.setColor (0,0,0);
	//$epd_light2.setColor (0,0,0);
	//$epd_light3.setColor (0,0,0);
	//$epd_light4.setColor (0,0,0);
	//$epd_emlight.setColor (0,0,0);
}

void epd_phantasm_fadeout() {
	$speaker_4.fadeSound ( SND_CHANNEL_ANY, -60, 1.5 );
	$speaker_6.fadeSound ( SND_CHANNEL_ANY, -60, 1.5 );
	$epd_alarm.fadeSound ( SND_CHANNEL_ANY, -60, 1.5 );
	$epd_speaker_blast.fadeSound ( SND_CHANNEL_ANY, -60, 1.5 );
	$epd_speaker_warmup.fadeSound ( SND_CHANNEL_ANY, -60, 1.5 );

	sys.wait (10);
	
	$speaker_4.fadeSound ( SND_CHANNEL_ANY, -5, 1.5 );
	$speaker_6.fadeSound ( SND_CHANNEL_ANY, -6, 1.5 );
	$epd_alarm.fadeSound ( SND_CHANNEL_ANY, 3, 1.5 );
	$epd_speaker_blast.fadeSound ( SND_CHANNEL_ANY, 0, 1.5 );
	$epd_speaker_warmup.fadeSound ( SND_CHANNEL_ANY, 0, 1.5 );
}




void seq_2() {
	monsterstatus = 2;
}

void seq_3() {
	monsterstatus = 3;
}

void seq_end() {
	monsterstatus = 4;
}


void music_engine() {
	return;
}

void fan_init ()
{
	$fan_01.bind ($fan_01_anchor);
	$fan_02.bind ($fan_02_anchor);
	$fan_03.bind ($fan_03_anchor);
	$fan_04.bind ($fan_04_anchor);

	$fan_01_anchor.rotateOnce ('0 0 25');
	$fan_02_anchor.rotateOnce ('0 0 25');
	$fan_03_anchor.rotateOnce ('0 0 25');
	$fan_04_anchor.rotateOnce ('0 0 25');

	sys.waitFor ($fan_04_anchor);

	$fan_01.rotate ('540 0 0');
	$fan_02.rotate ('360 0 0');
	$fan_03.rotate ('180 0 0');
	$fan_04.rotate ('552 0 0');
}

void laser_ambience()
{
	float	numRandomWait;

	numRandomWait = sys.random(2) + 1;
	sys.wait (numRandomWait);

	while (1)
	{
		sys.trigger ($e33_laser_rnd);
		numRandomWait = sys.random(2) + 1;
		sys.wait (numRandomWait);
	}
}

	void pumplight1_move()

	{
		$pumplight1.time(1.5);
		$pumplight1.accelTime(.1);
		$pumplight1.decelTime(.1);
		while (1){
			$pumplight1.move(DOWN,96);
			sys.trigger ($pumplight1_speaker);
			sys.waitFor ($pumplight1);
			$pumplight1.move(UP,96);
			sys.waitFor ($pumplight1);
		}
	}

		void pumplight2_move()

	{
		$pumplight2.time(1.45);
		$pumplight2.accelTime(.1);
		$pumplight2.decelTime(.1);
		while (1){
			$pumplight2.move(DOWN,96);
			sys.trigger ($pumplight2_speaker);
			sys.waitFor ($pumplight2);
			$pumplight2.move(UP,96);
			sys.waitFor ($pumplight2);
		}
	}

void turkey_klax_on()
{
		thread crossFadeEnt ($epd_light1, '0 0 0', '1 0.2 0', 2);
		thread crossFadeEnt ($epd_light2, '0 0 0', '1 0.2 0', 2);
		thread crossFadeEnt ($epd_light3, '0 0 0', '1 0.2 0', 2);
		thread crossFadeEnt ($epd_light4, '0 0 0', '1 0.2 0', 2);
		thread crossFadeEnt ($epd_emlight, '0 0 0', '1 0.2 0', 2);
}

void turkey_klax_off()
{
		thread crossFadeEnt ($epd_light1, '1 0.2 0', '0 0 0', 2);
		thread crossFadeEnt ($epd_light2, '1 0.2 0', '0 0 0', 2);
		thread crossFadeEnt ($epd_light3, '1 0.2 0', '0 0 0', 2);
		thread crossFadeEnt ($epd_light4, '1 0.2 0', '0 0 0', 2);
		thread crossFadeEnt ($epd_emlight, '1 0.2 0', '0 0 0', 2);
}

	// ***
	// New and improved UAC Turkey Baster v2.0
	// ***

	void turkey_baster() {
		while (1) {

			sys.wait (5);
			turkey_klax_on();
			sys.trigger ($epd_alarm);			// 8 seconds long
			sys.wait (2);
			
			sys.trigger ($epd_speaker_warmup);
			sys.wait (1);
			
			// Machine is on at this point...
			sys.trigger ($epd_speaker_blast);
			sys.trigger ($func_beam_1);
			sys.trigger ( $ep_endEmitter );
			sys.trigger ( $ep_emitter1 );
			sys.trigger ($turkey_hurt_1);
			sys.trigger ($tbbeam);
			$tbbeamlight.fadeInLight(.5);
			$ep_beam_source.fadeInLight( 0.2 );
			$ep_endlight.fadeInLight(.5);

			sys.wait (4);

			// ... and toggle stuff off..

			thread map_alphalabs1::turkey_klax_off();
			sys.trigger ($func_beam_1);
			sys.trigger ( $ep_endEmitter );
			sys.trigger ( $ep_emitter1 );
			sys.trigger ($turkey_hurt_1);
			sys.trigger ($tbbeam);
			$tbbeamlight.fadeOutLight(.5);
			$ep_beam_source.fadeOutLight( 0.5 );
			$ep_endlight.fadeOutLight(.5);
		}
	}

void toggle_gate() {
	if (GATE_OPEN == 0) {
		$gatedoor_left.open();
		$gatedoor_right.open();
		sys.waitFor ($gatedoor_right);
		GATE_OPEN = 1;
	}	
	else {
		$gatedoor_left.close();
		$gatedoor_right.close();
		sys.waitFor ($gatedoor_right);
		GATE_OPEN = 0;
	}
}

void hc_loop()
{
	//times for the can mover
	$hc_can.time (1);
	$hc_can.accelTime (.25);
	$hc_can.decelTime (.25);

	while (1) {
		//can move from start hole into door 176
		$hc_can.move ( NORTH, 176 );
		//sys.trigger ($speaker_hc_bolt);
		
		sys.waitFor ($hc_can);
		sys.wait (.25);

		//door move to down position 128
		$hc_door.time (.5);
		$hc_door.accelTime (.5);
		$hc_door.decelTime (0);

		$hc_can.bind ($hc_door);
		//
		sys.trigger ($speaker_hc_down);
		
		$hc_door.move ( DOWN, 128 );
		sys.waitFor ($hc_door);
		sys.wait (.25);

		//can move into final hole 176
		$hc_can.move ( NORTH, 176 );
		sys.trigger ($speaker_hc_bolt);
		sys.waitFor ($hc_can);
		sys.wait (.25);

		//door move to up position 128
		$hc_door.time (1);
		$hc_door.accelTime (.25);
		$hc_door.decelTime (.25);

		$hc_door.move ( UP, 128 );
		sys.trigger ($speaker_hc_up);
		sys.waitFor ($hc_door);
		sys.wait (.25);
		
		//restore can position
		$hc_can.unbind();
		$hc_can.restorePosition();
		sys.wait (.25);
	}//end while
}

////////////////////////////////////////////////////
//
//	Hydrocon1 move
//	
////////////////////////////////////////////////////
void hydrocon1_move()
{
	//bind ring
	$hydrocon1_ring.bind ($hydrocon1_main);
	
	//move hydrocon_main with ring up to top positioin
	$hydrocon1_main.time (1.5);
	$hydrocon1_main.accelTime (1);
	$hydrocon1_main.decelTime (.5);

	$hydrocon1_main.move ( UP, 216 );
	sys.trigger ($hydrocon1_main_speaker_up);
	sys.waitFor ($hydrocon1_main);
	
	
	//wait at top for the whole thing to start again
	sys.wait (1);

	//move hydrocon_ring down 64
	$hydrocon1_ring.move ( DOWN, 64 );
	sys.trigger ($hydrocon1_ring_speaker_down);
	sys.waitFor ($hydrocon1_ring);
	sys.wait (.25);

	//move hydrocon_main down with ring extended
	$hydrocon1_main.time (1.5);
	$hydrocon1_main.accelTime (1.5);
	$hydrocon1_main.decelTime (0);

	$hydrocon1_main.move ( DOWN, 216 );
	sys.trigger ($hydrocon1_main_speaker_down);
	sys.waitFor ($hydrocon1_main);
	
	//unbind ring
	$hydrocon1_ring.unbind();

	//move hydrocon_main with ring down the remaining distance to nipple
	$hydrocon1_main.time (1.5);
	$hydrocon1_main.accelTime (0);
	$hydrocon1_main.decelTime (1.5);

	$hydrocon1_main.move ( DOWN, 64 );
	sys.trigger ($hydrocon1_nipplemain_speaker_down);
	sys.waitFor ($hydrocon1_main);
	sys.wait (.25);

	//bind nipple to hydrocon_main
	$hydrocon1_nipple.bind ($hydrocon1_main);

	//move hydrocon_main with nipple up to ring extended position
	$hydrocon1_main.move ( UP, 64 );
	sys.trigger ($hydrocon1_nipplemain_speaker_up);
	sys.waitFor ($hydrocon1_main);
	sys.wait (.25);

	//activate effect
	sys.trigger ($hydrocon1_emitter);
	sys.trigger ($hydrocon1_emitter_speaker);
	sys.trigger ($hydrocon1_light);
	sys.wait (1);

	//unbind nipple
	$hydrocon1_nipple.unbind();
	
	//move nipple back down
	$hydrocon1_nipple.time (1);
	$hydrocon1_nipple.accelTime (.8);
	$hydrocon1_nipple.decelTime (.2);

	$hydrocon1_nipple.move ( DOWN, 64 );
	sys.trigger ($hydrocon1_nipple_speaker_down);
	sys.waitFor ($hydrocon1_nipple);
	//turn off effect
	sys.trigger ($hydrocon1_emitter);
	sys.trigger ($hydrocon1_emitter_speaker);
	sys.trigger ($hydrocon1_light);
	sys.wait (.25);

	//move hydrocon_ring up 64
	$hydrocon1_ring.move ( UP, 64 );
	sys.trigger ($hydrocon1_ring_speaker_up);
	sys.waitFor ($hydrocon1_ring);
	sys.wait (.25);
}

////////////////////////////////////////////////////
//
//	Hydrocon2 move
//	
////////////////////////////////////////////////////
void hydrocon2_move()
{
	//bind ring
	$hydrocon2_ring.bind ($hydrocon2_main);
	
	//move hydrocon_main with ring up to top positioin
	$hydrocon2_main.time (1.5);
	$hydrocon2_main.accelTime (1);
	$hydrocon2_main.decelTime (.5);

	$hydrocon2_main.move ( UP, 216 );
	sys.trigger ($hydrocon2_main_speaker_up);
	sys.waitFor ($hydrocon2_main);
	
	
	//wait at top for the whole thing to start again
	sys.wait (1);

	//move hydrocon_ring down 64
	$hydrocon2_ring.move ( DOWN, 64 );
	sys.trigger ($hydrocon2_ring_speaker_down);
	sys.waitFor ($hydrocon2_ring);
	sys.wait (.25);

	//move hydrocon_main down with ring extended
	$hydrocon2_main.time (1.5);
	$hydrocon2_main.accelTime (1.5);
	$hydrocon2_main.decelTime (0);

	$hydrocon2_main.move ( DOWN, 216 );
	sys.trigger ($hydrocon2_main_speaker_down);
	sys.waitFor ($hydrocon2_main);
	
	//unbind ring
	$hydrocon2_ring.unbind();

	//move hydrocon_main with ring down the remaining distance to nipple
	$hydrocon2_main.time (1.5);
	$hydrocon2_main.accelTime (0);
	$hydrocon2_main.decelTime (1.5);

	$hydrocon2_main.move ( DOWN, 64 );
	sys.trigger ($hydrocon2_nipplemain_speaker_down);
	sys.waitFor ($hydrocon2_main);
	sys.wait (.25);

	//bind nipple to hydrocon_main
	$hydrocon2_nipple.bind ($hydrocon2_main);

	//move hydrocon_main with nipple up to ring extended position
	$hydrocon2_main.move ( UP, 64 );
	sys.trigger ($hydrocon2_nipplemain_speaker_up);
	sys.waitFor ($hydrocon2_main);
	sys.wait (.25);

	//activate effect
	sys.trigger ($hydrocon2_emitter);
	sys.trigger ($hydrocon2_emitter_speaker);
	sys.trigger ($hydrocon2_light);
	sys.wait (1);

	//unbind nipple
	$hydrocon2_nipple.unbind();
	
	//move nipple back down
	$hydrocon2_nipple.time (1);
	$hydrocon2_nipple.accelTime (.8);
	$hydrocon2_nipple.decelTime (.2);

	$hydrocon2_nipple.move ( DOWN, 64 );
	sys.trigger ($hydrocon2_nipple_speaker_down);
	sys.waitFor ($hydrocon2_nipple);
	//turn off effect
	sys.trigger ($hydrocon2_emitter);
	sys.trigger ($hydrocon2_emitter_speaker);
	sys.trigger ($hydrocon2_light);
	sys.wait (.25);

	//move hydrocon_ring up 64
	$hydrocon2_ring.move ( UP, 64 );
	sys.trigger ($hydrocon2_ring_speaker_up);
	sys.waitFor ($hydrocon2_ring);
	sys.wait (.25);
}

////////////////////////////////////////////////////
//
//	Hydrocon Loop
//	
////////////////////////////////////////////////////
void hydrocon_loop()
{
	float hydrocon1_thread, hydrocon2_thread;
			
	while (1){
		hydrocon1_thread = thread map_alphalabs1::hydrocon1_move();
		hydrocon2_thread = thread map_alphalabs1::hydrocon2_move();

		sys.waitForThread( hydrocon1_thread );
		sys.waitForThread( hydrocon2_thread );
	}//end while
}

////////////////////////////////////////////////////
//
//	Kill Hydrocon Loop
//	
////////////////////////////////////////////////////
void kill_hydrocon_loop()
{
	sys.killthread ("map_alphalabs1::hydrocon_loop");
	sys.killthread ("map_alphalabs1::hydrocon1_move");
	sys.killthread ("map_alphalabs1::hydrocon2_move");
}

//---
// Fade out the creepy sounds after the maggots all die
//---

void fade_maggot_sounds() {
	$maggot_speaker_1.fadeSound (SND_CHANNEL_ANY, -60, 4);
	$maggot_speaker_2.fadeSound (SND_CHANNEL_ANY, -60, 4);
	$maggot_speaker_3.fadeSound (SND_CHANNEL_ANY, -60, 4);
	$maggot_speaker_4.fadeSound (SND_CHANNEL_ANY, -60, 4);
}

void main ()
{
	init_world();
	fan_init();
	//bathroom_init();
	//thread laser_ambience();
	thread pumplight1_move();
	thread pumplight2_move();
	thread hc_loop();
	thread hydrocon_loop();
	thread turkey_baster();
}



}

//@doomscript-blueprint begin 6
//@source 4FF1C092
//@catalog 0C260740
//@node 8846F578-0 40 40
//@node A4E67871-0 330 40
//@node A791D7F0-0 40 40
//@node 9FBEEBA4-0 330 40
//@node 6A00F616-0 610 40
//@node ABCEF1E9-0 890 40
//@node B04F71BE-0 1170 40
//@node BD73C318-0 1450 40
//@node 4E81C22F-0 1730 40
//@node 52950A79-0 2010 40
//@node BA2165AE-0 2290 40
//@node BE8A8549-0 2570 40
//@node 4D0FE57F-0 2850 40
//@node 7C12F52D-0 3130 40
//@node 7865E8A9-0 40 40
//@node 2A47E3C4-0 330 40
//@node 96BD8D82-0 125 145
//@node 7765E716-0 40 40
//@node A4815310-0 330 40
//@node 53DDADE8-0 125 145
//@node 90661EC6-0 40 40
//@node 3450D037-0 330 40
//@node 9EC986B2-0 125 145
//@node 0A4050A7-0 40 40
//@node 70B022C4-0 330 40
//@node F8312329-0 40 40
//@node 6ED21304-0 330 40
//@node 2C6AD308-0 610 40
//@node 178F53C8-0 890 40
//@node 750E29A4-0 1170 40
//@node 5E03F02B-0 1450 40
//@node 1ADD1A92-0 1730 40
//@node A109FA59-0 2010 40
//@node 2B6D9800-0 2290 40
//@node 15E00432-0 2570 40
//@node 82A08E94-0 2850 40
//@node 3EDE1E95-0 3130 40
//@node 0AF17796-0 3410 40
//@node 5B2D5142-0 3690 40
//@node 82589F59-0 40 40
//@node 261ED5E5-0 330 40
//@node 507657E0-0 125 145
//@node DFC39411-0 610 40
//@node 6852201A-0 405 140
//@node 9E44043E-0 890 40
//@node D79BC694-0 685 145
//@node FE2CC832-0 1170 200
//@node 261ED5E5-1 1450 200
//@node 2F86520F-0 1245 305
//@node DFC39411-1 1730 200
//@node 7013CA09-0 1525 300
//@node A08BCF20-0 40 40
//@node 7AD380E4-0 330 40
//@node D0450B35-0 610 40
//@node 2CC5382E-0 890 40
//@node D6FB5BBB-0 1170 40
//@node 94C1F28A-0 965 145
//@node 0061DA41-0 1450 200
//@node E6D80D44-0 1730 200
//@node 196F8B2A-0 2010 200
//@node 47046F6A-0 2290 200
//@node 196F8B2A-1 2570 200
//@node 5F6CDD53-0 40 40
//@node 837DE394-0 330 40
//@node EB355793-0 610 40
//@node 3CA19FF8-0 890 40
//@node F1A3E0C4-0 1170 40
//@node 3E414281-0 965 145
//@node BD3867DB-0 1450 200
//@node FC6DAA98-0 1730 200
//@node 20FADAC2-0 2010 200
//@node C059D430-0 2290 200
//@node 20FADAC2-1 2570 200
//@node C018BF26-0 40 40
//@node 7B678167-0 330 40
//@node 51D04B88-0 610 40
//@node A8567E0D-0 890 40
//@node 84BAA82E-0 1170 40
//@node E60FE27E-0 1450 40
//@node D708E508-0 40 40
//@node F78D1137-0 330 40
//@node 61EA9778-0 610 40
//@node 5F8529A1-0 890 40
//@node 3CAB077A-0 1170 40
//@node 6EDB311E-0 1450 40
//@node 4B702DDD-0 40 40
//@node 4A45AD62-0 330 40
//@node 566A73BD-0 125 145
//@node EF33B1CC-0 610 200
//@node 730BB816-0 890 200
//@node DB88A419-0 1170 200
//@node F9A99211-0 1450 200
//@node 69608E62-0 1730 200
//@node B3C12250-0 2010 200
//@node 70DCD29C-0 2290 200
//@node 73E83150-0 2570 200
//@node 5FC94169-0 2850 200
//@node 19740DED-0 3130 200
//@node 14EC48D2-0 3410 200
//@node 721B79E5-0 3690 200
//@node 9AE0F960-0 3970 200
//@node F7B460E5-0 4250 200
//@node B761242A-0 4530 200
//@node 541623BB-0 4810 200
//@node B74B5F56-0 5090 200
//@node 73E83150-1 5370 200
//@node 5FC94169-1 5650 200
//@node 19740DED-1 5930 200
//@node 14EC48D2-1 6210 200
//@node 721B79E5-1 6490 200
//@node E75075C7-0 6770 200
//@node 54D7172B-0 7050 200
//@node 5F9A7FED-0 7330 200
//@node C8CECA59-0 40 40
//@node 6B27FE3B-0 330 40
//@node D27CAA65-0 125 145
//@node 114A73B0-0 -80 145
//@node 0B5C4516-0 610 200
//@node 5B4E8D2F-0 890 200
//@node 9DAE5D36-0 1170 200
//@node E426C5E3-0 1450 200
//@node 430C2B79-0 1245 305
//@node 174FE53A-0 2010 200
//@node C6608289-0 2290 200
//@node 9DAE5D36-1 2570 200
//@node EC291112-0 2850 200
//@node 86D611D7-0 2645 305
//@node 3D89B22F-0 40 40
//@node 8B97DA73-0 330 40
//@node D85D81CD-0 610 40
//@node 650D7412-0 890 40
//@node ACA376B0-0 1170 40
//@node 8B5115E9-0 965 145
//@node 89BA6355-0 1450 200
//@node 3BD2462E-0 1730 200
//@node 7D4E28C6-0 2010 200
//@node 09AF2BD5-0 2290 200
//@node FEAC13FB-0 2570 200
//@node 1708464D-0 2850 200
//@node 770C2734-0 3130 200
//@node 9259D982-0 3410 200
//@node 67B56737-0 3690 200
//@node 8D6D4900-0 3970 200
//@node 7D4E28C6-1 4250 200
//@node 89BA6355-1 4530 200
//@node 23BBDE41-0 4810 200
//@node 3BD2462E-1 5090 200
//@node 7D4E28C6-2 5370 200
//@node 0C11D17F-0 5650 200
//@node 9B97C221-0 5930 200
//@node A95A0616-0 6210 200
//@node 00B1EC3A-0 6490 200
//@node 38E7C11F-0 6770 200
//@node 8D6D4900-1 7050 200
//@node 7D4E28C6-3 7330 200
//@node 036E9E0F-0 7610 200
//@node 47FEED86-0 7890 200
//@node 7D4E28C6-4 8170 200
//@node AAB4CEE2-0 40 40
//@node 190C010C-0 330 40
//@node C2C2A260-0 610 40
//@node 92E28E4B-0 890 40
//@node 693F92F8-0 1170 40
//@node C86894C4-0 1450 40
//@node 369E2C6C-0 1730 40
//@node A2EBEBA2-0 2010 40
//@node D229F947-0 2290 40
//@node 7F61C4C5-0 2570 40
//@node 43F38EEC-0 2850 40
//@node 1E79A491-0 3130 40
//@node 00FFEA9B-0 3410 40
//@node C2C2A260-1 3690 40
//@node FDF499CE-0 3970 40
//@node DA956A6F-0 4250 40
//@node 112B9615-0 4530 40
//@node B4A93751-0 4810 40
//@node A2EBEBA2-1 5090 40
//@node AB8A687E-0 5370 40
//@node C2C2A260-2 5650 40
//@node 2D624B9C-0 5930 40
//@node 2197D8F5-0 6210 40
//@node B559C858-0 6490 40
//@node AB0C5C0F-0 6770 40
//@node A2EBEBA2-2 7050 40
//@node 00FFEA9B-1 7330 40
//@node 99DA29F8-0 7610 40
//@node E869E533-0 7890 40
//@node DEF7DBAE-0 8170 40
//@node A2EBEBA2-3 8450 40
//@node 00FFEA9B-2 8730 40
//@node 7758E75F-0 9010 40
//@node 10992C4D-0 9290 40
//@node 61130CB5-0 9570 40
//@node D229F947-1 9850 40
//@node 08E62F2A-0 10130 40
//@node FDD7677A-0 10410 40
//@node FC11E579-0 10690 40
//@node F6F52A8E-0 10970 40
//@node 20112881-0 11250 40
//@node 001180AC-0 11530 40
//@node 0A24F559-0 11810 40
//@node 7758E75F-1 12090 40
//@node 10992C4D-1 12370 40
//@node 61130CB5-1 12650 40
//@node 00FFEA9B-3 12930 40
//@node 2ECE2E42-0 13210 40
//@node 158212B5-0 13490 40
//@node 1E79A491-1 13770 40
//@node 00FFEA9B-4 14050 40
//@node FF07C011-0 40 40
//@node 1F38DB1F-0 330 40
//@node B3B28ED4-0 610 40
//@node F27DC3C7-0 890 40
//@node 4F0BFFAC-0 1170 40
//@node 82D50DD8-0 1450 40
//@node EE28BEFA-0 1730 40
//@node 1232BC4C-0 2010 40
//@node 2249E5FC-0 2290 40
//@node 8C515001-0 2570 40
//@node 099EEBAE-0 2850 40
//@node E88219EB-0 3130 40
//@node C2488A64-0 3410 40
//@node B3B28ED4-1 3690 40
//@node EC4058CA-0 3970 40
//@node C00AC94B-0 4250 40
//@node E71AD9A1-0 4530 40
//@node 03D70E53-0 4810 40
//@node 1232BC4C-1 5090 40
//@node 8D4349AA-0 5370 40
//@node B3B28ED4-2 5650 40
//@node 7CFD67E8-0 5930 40
//@node 0B432BB1-0 6210 40
//@node DA5106A4-0 6490 40
//@node 09EC4A15-0 6770 40
//@node 1232BC4C-2 7050 40
//@node C2488A64-1 7330 40
//@node 017276B3-0 7610 40
//@node 50ED5427-0 7890 40
//@node 0A300548-0 8170 40
//@node 1232BC4C-3 8450 40
//@node C2488A64-2 8730 40
//@node 5003D3B1-0 9010 40
//@node DF72CB37-0 9290 40
//@node 28DBD9C7-0 9570 40
//@node 2249E5FC-1 9850 40
//@node 8E4054FE-0 10130 40
//@node 66465596-0 10410 40
//@node E478215D-0 10690 40
//@node 1C365C62-0 10970 40
//@node 27714245-0 11250 40
//@node 822CFD06-0 11530 40
//@node 70688773-0 11810 40
//@node 5003D3B1-1 12090 40
//@node DF72CB37-1 12370 40
//@node 28DBD9C7-1 12650 40
//@node C2488A64-3 12930 40
//@node 014669C6-0 13210 40
//@node 5ABD5153-0 13490 40
//@node E88219EB-1 13770 40
//@node C2488A64-4 14050 40
//@node F97B6D1A-0 40 40
//@node 9A29BAA9-0 330 40
//@node 7A908225-0 125 145
//@node 36696F67-0 610 200
//@node C258F9D6-0 385 305
//@node 5FF0E74F-0 890 200
//@node 51BD56FD-0 665 305
//@node 241D5103-0 1450 200
//@node B6BC0AFE-0 965 300
//@node 11CC5EBA-0 1730 200
//@node 84AD64D8-0 1245 300
//@node 3C84AF0B-0 40 40
//@node 24D3086D-0 330 40
//@node E7EBBC8B-0 610 40
//@node D1278FEE-0 890 40
//@node 39434A1C-0 40 40
//@node 61D63B0D-0 330 40
//@node 2830E37E-0 610 40
//@node 7FD98B33-0 890 40
//@node 964A4A4C-0 1170 40
//@node 32687650-0 40 40
//@node 5531D4DD-0 330 40
//@node A245D8E2-0 610 40
//@node 39BE6E0B-0 890 40
//@node 344D0C5E-0 1170 40
//@node A269BCE2-0 1450 40
//@node 6FCC2195-0 1730 40
//@node 7F089538-0 2010 40
//@doomscript-blueprint end
