namespace map_delta5 
{
	void init_world()
	{
		float	i;
		entity	ent1, ent2;

		for ( i = 1; i <= 9; i++ )
		{
			ent1 = sys.getEntity ("lred_0" + i);
			ent1.Off();
		}

		for ( i = 1; i <= 6; i++ )
		{
			ent1 = sys.getEntity ("lleft_0" + i);
			ent2 = sys.getEntity ("lright_0" + i);
			ent1.Off();
			ent2.Off();
		}
	}
	
	void scroll_red_lights()
	{
		float	i;
		entity	ent;
		while (1)
		{
			for ( i = 1; i <= 9; i++ )
			{
				ent = sys.getEntity ("lred_0" + i);
				ent.On();
				sys.wait ( 0.10 );
				ent.Off();
				sys.wait ( 0.10 );
			}
		}
	}

	void scroll_blue_lights()
	{
		float	i;
		entity	ent1, ent2;
		while (1)
		{
			for ( i = 1; i <= 6; i++ )
			{
				ent1 = sys.getEntity ("lleft_0" + i);
				ent2 = sys.getEntity ("lright_0" + i);
				ent1.On();
				ent2.On();
				sys.wait ( 0.2 );
				ent1.Off();
				ent2.Off();

				sys.wait ( 0.2 );
			}
		}
	}
	
	void open_vent_ladder()
	{
		$vent_panel.time (1);
		$vent_panel.accelTime (.5);
		$vent_panel.decelTime (.5);
		$vent_panel.startSoundShader ("dc5_panel_1s", SND_CHANNEL_VOICE);
		$vent_panel.moveTo ($vent_panel_pos1);
		sys.waitFor ($vent_panel);
		sys.wait (.5);
		$vent_panel.time (1.5);
		$vent_panel.accelTime (.75);
		$vent_panel.decelTime (.75);
		$vent_panel.startSoundShader ("dc5_panel_1_5s", SND_CHANNEL_VOICE2);
		$vent_panel.moveTo ($vent_panel_pos2);
		sys.waitFor ($vent_panel);
		sys.wait (.5);
		$vent_ladder.time (4);
		$vent_ladder.accelTime (1.25);
		$vent_ladder.decelTime (2.75);
		$vent_ladder.startSoundShader ("ladder_4s", SND_CHANNEL_VOICE );
		$vent_ladder.moveTo ($ladder_extended_pos);
	}

	void close_vent_ladder()
	{
		$vent_ladder_brush.remove();
		$vent_ladder.time (2);
		$vent_ladder.accelTime (1.25);
		$vent_ladder.decelTime (.75);
		$vent_ladder.startSoundShader ("ladder_4s", SND_CHANNEL_VOICE );
		$vent_ladder.moveTo ($ladder_retracted_pos);
		sys.waitFor ($vent_ladder);
		
		$vent_panel.time (1);
		$vent_panel.accelTime (.5);
		$vent_panel.decelTime (.5);
		$vent_panel.startSoundShader ("dc5_panel_1_5s", SND_CHANNEL_VOICE);
		$vent_panel.moveTo ($vent_panel_pos1);
		sys.waitFor ($vent_panel);
		
		sys.wait (.5);
		$vent_panel.time (1.5);
		$vent_panel.accelTime (.75);
		$vent_panel.decelTime (.75);
		$vent_panel.startSoundShader ("dc5_panel_1s", SND_CHANNEL_VOICE2);
		$vent_panel.moveTo ($vent_panel_startpos);
		sys.waitFor ($vent_panel);
		sys.wait (.5);
	}

	void start_world()
	{
		thread scroll_red_lights();
		thread scroll_blue_lights();
	}
	
	void cache_sounds() {
		sys.cacheSoundShader ("dc5_panel_1s");
		sys.cacheSoundShader ("dc5_panel_1_5s");
		sys.cacheSoundShader ("ladder_4s");
	}

	
	void main()
	{
		cache_sounds();
		init_world();
		start_world();
	}
}

//@doomscript-blueprint begin 6
//@source 7C17096A
//@catalog 0C260740
//@node 8846F578-0 40 40
//@node 5A4DEB95-0 610 40
//@node 37A596BD-0 125 145
//@node 2DF7ADFA-0 -80 145
//@node 6ABE9102-0 610 200
//@node B70E04F7-0 385 305
//@node 9FC2A98A-0 180 405
//@node 7D5F1EF8-0 -25 405
//@node 57A3EFCB-0 1170 200
//@node 0582867A-0 1450 40
//@node 0C862FFE-0 965 145
//@node 717B29D2-0 760 145
//@node C06B1FE4-0 1450 200
//@node A47D1972-0 1225 305
//@node D3B89C46-0 1020 405
//@node C0A0FB0A-0 815 405
//@node 7A2D15E8-0 1730 200
//@node 56B528DE-0 1505 305
//@node 1E1D3FA1-0 1300 405
//@node 06C3AC68-0 1095 405
//@node 57A3EFCB-1 2290 200
//@node 1DEBA814-0 2570 200
//@node 2F016D3C-0 40 40
//@node 5D9524B7-0 330 40
//@node 94A41849-0 125 145
//@node 3058B911-0 610 200
//@node A10B223B-0 405 305
//@node 489F12C6-0 200 305
//@node E8E0E6D3-0 890 360
//@node 2C5EAC63-0 665 465
//@node 19439BD9-0 460 565
//@node D8418223-0 255 565
//@node 101BF9E2-0 1170 360
//@node E70510F7-0 1450 360
//@node AD20D4EC-0 1730 360
//@node E70510F7-1 2010 360
//@node 1AB6EBD7-0 40 40
//@node 195CCA88-0 610 40
//@node EAB8132E-0 125 145
//@node F5D5CB5B-0 890 200
//@node 85C73BB4-0 405 305
//@node 2CE2C244-0 200 305
//@node 4EDDB19B-0 890 360
//@node D9940533-0 665 465
//@node D9199359-0 460 565
//@node F796AC79-0 255 565
//@node 2B655C31-0 1170 360
//@node D3D635C7-0 945 465
//@node C9915834-0 740 565
//@node 94EC4FF3-0 535 565
//@node D6EE9FBA-0 1730 360
//@node F93117D7-0 2010 360
//@node 1A840411-0 2290 360
//@node D285F9E4-0 2570 360
//@node B8AAA8DB-0 2850 360
//@node 1A840411-1 3130 360
//@node B5CCA52A-0 40 40
//@node AD30CCD0-0 330 40
//@node 63069B90-0 610 40
//@node 8225239D-0 890 40
//@node C7B3425E-0 1170 40
//@node 20D3F21A-0 1450 40
//@node 1B72738F-0 1730 40
//@node 13B8D081-0 2010 40
//@node DF139CF5-0 2290 40
//@node FBEC6D21-0 2570 40
//@node 0C07F15A-0 2850 40
//@node B99B2E3C-0 3130 40
//@node B48649F7-0 3410 40
//@node 1B72738F-1 3690 40
//@node 13B8D081-1 3970 40
//@node 4A9D06C9-0 4250 40
//@node 267554B1-0 4530 40
//@node F66D78F6-0 4810 40
//@node 58809016-0 5090 40
//@node E2ED3A8B-0 5370 40
//@node AA8CCCF0-0 40 40
//@node 7A59DCBB-0 330 40
//@node 6A5A68F1-0 610 40
//@node C7E725FB-0 890 40
//@node B37618FA-0 1170 40
//@node 627A0A08-0 1450 40
//@node 18FA2F52-0 1730 40
//@node 6EDCA795-0 2010 40
//@node EE3D27A6-0 2290 40
//@node 1B26414A-0 2570 40
//@node 03410D1B-0 2850 40
//@node E8F3A354-0 3130 40
//@node 5667DFB4-0 3410 40
//@node B05DDFA1-0 3690 40
//@node 1F3F9A33-0 3970 40
//@node B22B30D7-0 4250 40
//@node C0B3A5F3-0 4530 40
//@node B5A377A0-0 4810 40
//@node 1F3EDECE-0 5090 40
//@node A5460667-0 5370 40
//@node B05DDFA1-1 5650 40
//@node 1F3F9A33-1 5930 40
//@node 202C631C-0 40 40
//@node 351BBC2F-0 330 40
//@node 184B84EC-0 610 40
//@node B832CE32-0 40 40
//@node 64D952D7-0 330 40
//@node 33705BBB-0 610 40
//@node 3AC8EFD3-0 890 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 5531D4DD-0 610 40
//@node 30954697-0 890 40
//@doomscript-blueprint end
