namespace map_delta2b 
{
	float container2_position = 0;
	void monster_container2_run( entity container2 );
	void monster_conveyor_run( entity container );
	
	
	//******************
	// Telepad Rotating Doors         
	//******************
	void teleporter_exit_open()
	{
		$round_door_left.time( 1.5 );
		$round_door_left.accelTime( .1 );
		$round_door_left.decelTime( 1 );
		$round_door_right.time( 1.5 );		
		$round_door_right.accelTime( .1 );
		$round_door_right.decelTime( 1 );
		sys.trigger ($rot_left_door);
		$round_door_left.rotateOnce( '0 90 0' );
		sys.trigger ($rot_right_door);
		$round_door_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $round_door_left );
	}

	void start_conveyor_loop() 
	{
		sys.trigger ($container_speaker_start);
		sys.wait (1.8);
		sys.trigger ($container_speaker_loop);
	}
	
	void start_conveyor_loop2() 
	{
		sys.trigger ($container2_speaker_start);
		sys.wait (1.8);
		sys.trigger ($container2_speaker_loop);
	}

	void stop_conveyor_loop() 
	{
		sys.trigger ($container_speaker_stop);
		sys.trigger ($container_speaker_loop);
	}
	
	void stop_conveyor_loop2() 
	{
		sys.trigger ($container2_speaker_stop);
		sys.trigger ($container2_speaker_loop);
	}

	//************************************
	// Monster Conveyor System
	//************************************
	
/*	void turn_beam_on_off()
	{
		sys.trigger( $top_flare_fx);
		sys.trigger( $bottom_flare_fx);
		sys.trigger( $top_beam_fxr );
		sys.trigger( $top_beam_fxl );
		sys.trigger( $bottom_beam_fxr );
		sys.trigger( $bottom_beam_fxl );
		sys.trigger( $beam_kill_trigger );
	}
	
	void start_beam()
	{
		while ( 1 )
		{
			$top_beam_mover.move( DOWN, 92 );
			$bottom_beam_mover.move ( UP, 92 );
			sys.waitFor ($bottom_beam_mover);
			$top_beam_mover.move( UP, 92 );
			$bottom_beam_mover.move ( DOWN, 92 );
			sys.waitFor ($bottom_beam_mover);
		}
	}
*/	
	void monster_container2_run( entity container2 )
	{
		$container_clamp2.bind( $container2_clamphandle1 );
		$container2_clamphandle1.moveTo( $clamp_position_start );
		sys.waitFor( $container2_clamphandle1);
		
		$container_clamp2.unbind();
		$container_clamp2.bind($container_clamphandle1);
		$container2_clamphandle1.restorePosition();
		
		$monster_container2_contactpoint.move( UP, 164 );
		sys.waitFor( $monster_container2_contactpoint );
		//container2_position = 1;
		
		$container_clamphandle1.speed( 65 );
		$container_clamphandle2.speed( 65 );
		$container_clamphandle3.speed( 65 );
		$container_clamphandle_middle.speed( 65 );
		
		//small door operate open
		sys.trigger ($smalldoor_open);
		$monster_machinedoorsmall_left.move( WEST, 32 );
		$monster_machinedoorsmall_right.move( EAST, 32 );
		sys.waitFor( $monster_machinedoorsmall_right );
		
		//move container2 clamp into position while container moves up
		$container_clamphandle1.moveTo( $clamp_position_stop1 );
		
		//move container up and arms down for pickup
		container2.move( UP, 52 );
		sys.trigger ($speaker_liftarms1_down);			// SOUND
		$monster_container_liftarms1.move( DOWN, 152 );
		sys.waitFor( $monster_container_liftarms1 );
		sys.wait( .5 );
		
		//bind container to liftarms and move up
		container2.bind( $monster_container_liftarms1 );
		sys.trigger ($speaker_liftarms1_up);				// SOUND
		$monster_container_liftarms1.move( UP, 120 );
		sys.waitFor( $container_clamphandle1 );
		sys.waitFor( $monster_container_liftarms1 );
		
		//small door operate close
		sys.trigger ($smalldoor_close);
		$monster_machinedoorsmall_left.move( EAST, 32 );
		$monster_machinedoorsmall_right.move( WEST, 32 );
		
		//bind container to the clamp
		sys.wait( 1 ); //temp wait for clamp to engage
		container2.bind( $container_clamp2 );
		sys.trigger ($speaker_liftarms1_up);				// SOUND
		$monster_container_liftarms1.move( UP, 32 );
		sys.waitFor( $monster_container_liftarms1 );
		
		//move container along path
		thread start_conveyor_loop2();						// SOUND
		
		$container_clamphandle1.moveTo( $clamp_position_rotateright1 );
		sys.waitFor( $container_clamphandle1 );
		
		$container_clamphandle1.time( 2.5 );//set to time var for corner
		$container_clamphandle1.rotateOnce( '0 -90 0' );
		sys.waitFor( $container_clamphandle1 );
		
		$container_clamp2.unbind();
		$container_clamp2.bind( $container_clamphandle2 );
		$container_clamphandle1.restorePosition();//reset handle1 to starting position
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_rotateleft1 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.time( 2.5 );
		$container_clamphandle2.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_rotateleft2 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.time( 2.5 );
		$container_clamphandle2.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_stop2 );
		sys.waitFor( $container_clamphandle2 );
		
		thread stop_conveyor_loop2();						// SOUND
		
		sys.trigger ($speaker_machinedoor1);
		$monster_machinedoor1_left.rotateOnce( '0 90 0' );
		$monster_machinedoor1_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor1_left );
		
		sys.wait( 1 );//container wait to move into position
		
		thread start_conveyor_loop2();						// SOUND
		
		$container_clamphandle2.moveTo( $clamp_position_stop3 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamp2.unbind();
		$container_clamp2.bind( $container_clamphandle_middle );
		$container_clamphandle2.restorePosition();//reset handle2 to starting position
		
		thread stop_conveyor_loop2();						// SOUND
		
		sys.trigger ($speaker_machinedoor1);
		$monster_machinedoor1_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor1_right.rotateOnce( '0 90 0' );
		sys.waitFor( $monster_machinedoor1_left );
		
		//fade container 2 lights OUT, red lights IN
		thread crossFadeEnt ($container2_light1, '0.756863 0.976471 1', '0 0 0', 1.0);
		thread crossFadeEnt ($container2_light2, '0.756863 0.976471 1', '0 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight1, '0 0 0', '1 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight2, '0 0 0', '1 0 0', 1.0);
		
		sys.trigger ($chamber_fx1);
		sys.trigger ($chamber_fx2);
		sys.trigger ($chamber_fx_sound);
		sys.wait( 4 );//container wait inside chamber
		sys.trigger ($chamber_fx1);
		sys.trigger ($chamber_fx2);
		
		//fade container 2 lights IN, red lights OUT
		thread crossFadeEnt ($container2_light1, '0 0 0', '0.756863 0.976471 1', 1.0);
		thread crossFadeEnt ($container2_light2, '0 0 0', '0.756863 0.976471 1', 1.0);
		thread crossFadeEnt ($chamber_redlight1, '1 0 0', '0 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight2, '1 0 0', '0 0 0', 1.0);
		
		thread monster_conveyor_run( $monster_container1_contactpoint );
		
		thread start_conveyor_loop2();						// SOUND
		
		$container_clamphandle_middle.moveTo( $clamp_position_stop4 );
		sys.waitFor( $container_clamphandle_middle );
		
		thread stop_conveyor_loop2();						// SOUND
		
		sys.trigger ($speaker_machinedoor2);
		$monster_machinedoor2_left.rotateOnce( '0 90 0' );
		$monster_machinedoor2_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor2_left );
		sys.wait( 1 );//container wait outside chamber
		
		thread start_conveyor_loop2();						// SOUND
		
		$container_clamphandle_middle.moveTo( $clamp_position_rotateleft3 );
		sys.wait( 1.75 );
		sys.trigger ($speaker_machinedoor2);
		$monster_machinedoor2_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor2_right.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle_middle );
		$container_clamphandle_middle.time( 2.5 );
		$container_clamphandle_middle.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle_middle );
		
		$container_clamphandle_middle.speed( 65 );//reset to speed var
		
		$container_clamphandle_middle.moveTo( $clamp_position_rotateright2 );
		sys.waitFor( $container_clamphandle_middle );
		$container_clamp2.unbind();
		$container_clamp2.bind( $container_clamphandle3 );
		$container_clamphandle_middle.restorePosition();//reset handle_middle to starting position
		
		$container_clamphandle3.time( 2.5 );
		$container_clamphandle3.rotateOnce( '0 -90 0' );
		sys.waitFor( $container_clamphandle3 );
		
		$container_clamphandle3.speed( 65 );//reset to speed var
		
		$container_clamphandle3.moveTo( $clamp_position_end );
		sys.waitFor( $container_clamphandle3 );
		
		thread stop_conveyor_loop2();						// SOUND
		
		sys.trigger ($speaker_machinedoor3);
		
		$monster_machinedoor3_left.rotateOnce( '0 90 0' );
		$monster_machinedoor3_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor3_right );
		sys.wait( .25 );
		container2.unbind();
		$container_clamp2.unbind();
		$container_clamp2.restorePosition();
		$container_clamphandle3.restorePosition();
		
		$monster_container2.hide();//Bug - hide container before restorePos to avoid contact with player
		sys.wait(.25);
		container2.restorePosition();
		sys.wait(.25);
		$monster_container2.show();
		
		sys.wait( 1.5 );
		$monster_machinedoor3_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor3_right.rotateOnce( '0 90 0' );
		sys.waitFor( $monster_machinedoor3_right );
		sys.wait( .25 );
	}
		
	void monster_conveyor_run( entity container )
	{
		$container_clamphandle1.speed( 65 );
		$container_clamphandle2.speed( 65 );
		$container_clamphandle3.speed( 65 );
		$container_clamphandle_middle.speed( 65 );
		
		//small door operate open
		sys.trigger ($smalldoor_open);
		$monster_machinedoorsmall_left.move( WEST, 32 );
		$monster_machinedoorsmall_right.move( EAST, 32 );
		sys.waitFor( $monster_machinedoorsmall_right );
		
		//move container clamp into position while container moves up
		$container_clamphandle1.moveTo( $clamp_position_stop1 );
		
		//move container up and arms down for pickup
		container.move( UP, 52 );
		sys.trigger ($speaker_liftarms1_down);				// SOUND
		$monster_container_liftarms1.move( DOWN, 152 );
		sys.waitFor( $monster_container_liftarms1 );
		sys.wait( .5 );
		//bind container to liftarms and move up
		container.bind( $monster_container_liftarms1 );
		sys.trigger ($speaker_liftarms1_up);				// SOUND
		$monster_container_liftarms1.move( UP, 120 );
		sys.waitFor( $container_clamphandle1 );
		sys.waitFor( $monster_container_liftarms1 );
		
		//small door close
		sys.trigger ($smalldoor_close);
		$monster_machinedoorsmall_left.move( EAST, 32 );
		$monster_machinedoorsmall_right.move( WEST, 32 );
		
		//bind container to the clamp
		sys.wait( 1 ); //temp wait for clamp to engage
		container.bind( $container_clamp1 );
		sys.trigger ($speaker_liftarms1_up);				// SOUND
		$monster_container_liftarms1.move( UP, 32 );
		sys.waitFor( $monster_container_liftarms1 );
		
		//move container along path
		thread start_conveyor_loop();						// SOUND
		
		$container_clamphandle1.moveTo( $clamp_position_rotateright1 );
		sys.waitFor( $container_clamphandle1 );
		
		$container_clamphandle1.time( 2.5 );//set to time var for corner
		$container_clamphandle1.rotateOnce( '0 -90 0' );
		sys.waitFor( $container_clamphandle1 );
		
		$container_clamp1.unbind();
		$container_clamp1.bind( $container_clamphandle2 );
		$container_clamphandle1.restorePosition();//reset handle1 to starting position
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_rotateleft1 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.time( 2.5 );
		$container_clamphandle2.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_rotateleft2 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.time( 2.5 );
		$container_clamphandle2.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamphandle2.speed( 65 );//reset to speed var
		$container_clamphandle2.moveTo( $clamp_position_stop2 );
		sys.waitFor( $container_clamphandle2 );
		
		stop_conveyor_loop();									// SOUND
		
		sys.trigger ($speaker_machinedoor1);
		$monster_machinedoor1_left.rotateOnce( '0 90 0' );
		$monster_machinedoor1_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor1_left );
		
		sys.wait( 1 );//container wait to move into position
		
		thread start_conveyor_loop();						// SOUND
		
		$container_clamphandle2.moveTo( $clamp_position_stop3 );
		sys.waitFor( $container_clamphandle2 );
		
		$container_clamp1.unbind();
		$container_clamp1.bind( $container_clamphandle_middle );
		$container_clamphandle2.restorePosition();//reset handle2 to starting position
		
		stop_conveyor_loop();									// SOUND
		
		sys.trigger ($speaker_machinedoor1);
		$monster_machinedoor1_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor1_right.rotateOnce( '0 90 0' );
		sys.waitFor( $monster_machinedoor1_left );
		
		//fade container 1 lights OUT, red lights IN
		thread crossFadeEnt ($container1_light1, '0.756863 0.976471 1', '0 0 0', 1.0);
		thread crossFadeEnt ($container1_light2, '0.756863 0.976471 1', '0 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight1, '0 0 0', '1 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight2, '0 0 0', '1 0 0', 1.0);
		
		sys.trigger ($chamber_fx1);
		sys.trigger ($chamber_fx2);
		sys.trigger ($chamber_fx_sound);
		sys.wait( 4 );//container wait inside chamber
		sys.trigger ($chamber_fx1);
		sys.trigger ($chamber_fx2);
		
		//fade container 1 lights IN, red lights OUT
		thread crossFadeEnt ($container1_light1, '0 0 0', '0.756863 0.976471 1', 1.0);
		thread crossFadeEnt ($container1_light2, '0 0 0', '0.756863 0.976471 1', 1.0);
		thread crossFadeEnt ($chamber_redlight1, '1 0 0', '0 0 0', 1.0);
		thread crossFadeEnt ($chamber_redlight2, '1 0 0', '0 0 0', 1.0);
		
		//*********************************
		//start second container
		// ********************************
		thread monster_container2_run( $monster_container2_contactpoint );
		thread start_conveyor_loop();						// SOUND
		
		$container_clamphandle_middle.moveTo( $clamp_position_stop4 );
		sys.waitFor( $container_clamphandle_middle );
		thread stop_conveyor_loop();						// SOUND
		sys.trigger ($speaker_machinedoor2);
		$monster_machinedoor2_left.rotateOnce( '0 90 0' );
		$monster_machinedoor2_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor2_left );
		
		sys.wait( 1 );//container wait outside chamber
		thread start_conveyor_loop();						// SOUND
		$container_clamphandle_middle.moveTo( $clamp_position_rotateleft3 );
		sys.wait( 1.75 );
		
		sys.trigger ($speaker_machinedoor2);
		$monster_machinedoor2_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor2_right.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle_middle );
		
		$container_clamphandle_middle.time( 2.5 );
		$container_clamphandle_middle.rotateOnce( '0 90 0' );
		sys.waitFor( $container_clamphandle_middle );
		
		$container_clamphandle_middle.speed( 65 );//reset to speed var
		
		$container_clamphandle_middle.moveTo( $clamp_position_rotateright2 );
		sys.waitFor( $container_clamphandle_middle );
		$container_clamp1.unbind();
		$container_clamp1.bind( $container_clamphandle3 );
		$container_clamphandle_middle.restorePosition();//reset handle_middle to starting position
		
		$container_clamphandle3.time( 2.5 );
		$container_clamphandle3.rotateOnce( '0 -90 0' );
		sys.waitFor( $container_clamphandle3 );
		
		$container_clamphandle3.speed( 65 );//reset to speed var
		
		$container_clamphandle3.moveTo( $clamp_position_end );
		sys.waitFor( $container_clamphandle3 );
		stop_conveyor_loop();									// SOUND
		
		sys.trigger ($speaker_machinedoor3);
		
		$monster_machinedoor3_left.rotateOnce( '0 90 0' );
		$monster_machinedoor3_right.rotateOnce( '0 -90 0' );
		sys.waitFor( $monster_machinedoor3_right );
		sys.wait( .25 );
		container.unbind();
		$container_clamp1.unbind();
		$container_clamphandle3.restorePosition();
		$container_clamp1.restorePosition();
		
		$monster_container1.hide();//Bug - hide container before restorePos to avoid contact with player
		sys.wait(.25);
		container.restorePosition();
		sys.wait(.25);
		$monster_container1.show();
		
		sys.wait( 1.5 );
		$monster_machinedoor3_left.rotateOnce( '0 -90 0' );
		$monster_machinedoor3_right.rotateOnce( '0 90 0' );
		sys.waitFor( $monster_machinedoor3_right );
		$container_clamp1.bind( $container_clamphandle1 );
		sys.wait( .25 );
	}

	void monster_conveyor_start()
	{
		thread monster_conveyor_run( $monster_container1_contactpoint );
		//turn_beam_on_off();
		//start_beam();
	}

// ----------------------------
// Analyzer machine starts here
// ----------------------------
	
	void analyzer_fwdarms_operate()
	{
		$speaker_sc_piston_leftfront.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		
		$sc_piston_leftfront.move( DOWN, 84 );
		
		$speaker_sc_piston_rightfront.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		
		$sc_piston_rightfront.move( DOWN, 84 );
		sys.waitFor( $sc_piston_rightfront );
		
		$speaker_sc_rotater_leftfront.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );
		
		$sc_rotater_leftfront.rotateOnce( '0 -45 0' );
		
		$speaker_sc_rotater_rightfront.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );
		
		$sc_rotater_rightfront.rotateOnce( '0 45 0' );
		sys.wait( .25 );
		
		$speaker_sc_largearm_leftfront.startSoundShader ("mach_1s", SND_CHANNEL_VOICE2 );
		$sc_largearm_leftfront.rotateOnce( '-80 0 0' );

		$speaker_sc_largearm_rightfront.startSoundShader ("mach_1s", SND_CHANNEL_VOICE2 );		
		$sc_largearm_rightfront.rotateOnce( '-80 0 0' );
		sys.wait( .25 );
		
		$speaker_sc_smallarm_leftfront.startSoundShader ("mach_1_5s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_leftfront.rotateOnce( '-31.5 0 0' );
		$speaker_sc_rightarm_leftfront.startSoundShader ("mach_1_5s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_rightfront.rotateOnce( '-31.5 0 0' );
		sys.wait( .5 );
		
		$sc_4head_leftfront.rotateOnce( '-12 0 0' );
		$sc_4head_rightfront.rotateOnce( '-12 0 0' );
		sys.waitFor( $sc_4head_rightfront );
		
		//start analyzer fx
		$anal_main_fx.startSoundShader ("u1mach_on", SND_CHANNEL_VOICE );
		sys.trigger( $anal_head_fx1 );
		sys.trigger( $anal_head_fx2 );
		sys.trigger( $anal_head_fx3 );
		sys.trigger( $anal_head_fx4 );
		sys.trigger( $anal_head_fx5 );
		sys.trigger( $anal_head_fx6 );
		sys.wait( 1.4 );
		$anal_main_fx.startSoundShader ("u1mach_loop", SND_CHANNEL_VOICE2 );
		sys.trigger( $anal_main_fx );
		//turn on kill brush
		sys.trigger( $analyzeToDeath );
		
		sys.trigger( $analyzer_controlpanel);
	}
	
	void analyzer_operate()
	{
		$speaker_sc_piston_leftrear.startSoundShader ("mach_1_5s", SND_CHANNEL_VOICE2 );
		$sc_piston_leftrear.move( DOWN, 80 );
		$speaker_sc_piston_rightrear.startSoundShader ("mach_1_5s", SND_CHANNEL_VOICE2 );
		$sc_piston_rightrear.move( DOWN, 80 );
		
		sys.waitFor( $sc_piston_rightrear );
		thread analyzer_fwdarms_operate();
		
		$speaker_sc_rotater_leftrear.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );	
		$sc_rotater_leftrear.rotateOnce( '0 30 0' );
		$speaker_sc_rotater_rightrear.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );	
		$sc_rotater_rightrear.rotateOnce( '0 -30 0' );
		sys.wait( .25 );
		
		$speaker_sc_largearm_leftrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		
		$sc_largearm_leftrear.rotateOnce( '-90 0 0' );
		
		$speaker_sc_largearm_righttrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_largearm_rightrear.rotateOnce( '-90 0 0' );
		sys.wait( .325 );
		
		$speaker_sc_smallarm_leftrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_leftrear.rotateOnce( '-50 0 0' );
		$speaker_sc_smallarm_rightrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_rightrear.rotateOnce( '-50 0 0' );
		sys.wait( 1.25 );	
		
		$sc_3head_leftrear.rotateOnce( '-21.5 0 0' );
		$sc_3head_rightrear.rotateOnce( '-21.5 0 0' );
	}
	
	void analyzer_reararms_operate_off()
	{
		$sc_3head_leftrear.rotateOnce( '21.5 0 0' );
		$sc_3head_rightrear.rotateOnce( '21.5 0 0' );
		sys.wait( 1.25 );
		
		$speaker_sc_smallarm_leftrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_leftrear.rotateOnce( '50 0 0' );
		$speaker_sc_smallarm_rightrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_smallarm_rightrear.rotateOnce( '50 0 0' );
		//sys.wait( .325 );
		
		$speaker_sc_largearm_leftrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_largearm_leftrear.rotateOnce( '90 0 0' );
		$speaker_sc_largearm_rightrear.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_largearm_rightrear.rotateOnce( '90 0 0' );
		sys.wait( 1.25 );
			
		$speaker_sc_rotater_leftrear.startSoundShader ("mach_1s", SND_CHANNEL_VOICE2 );	
		$sc_rotater_leftrear.rotateOnce( '0 -30 0' );
		$speaker_sc_rotater_rightrear.startSoundShader ("mach_1s", SND_CHANNEL_VOICE2 );	
		$sc_rotater_rightrear.rotateOnce( '0 30 0' );
		sys.waitFor( $sc_rotater_rightrear );
		
		$speaker_sc_piston_leftrear.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		$sc_piston_leftrear.move( UP, 80 );
		
		$speaker_sc_piston_rightrear.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		$sc_piston_rightrear.move( UP, 80 );
		sys.waitFor( $sc_piston_rightrear );
		
		sys.trigger( $analyzer_controlpanel);
	}
	
	void analyzer_operate_off()
	{
		
		//stop analyzer fx
		$anal_main_fx.startSoundShader ("u1mach_off", SND_CHANNEL_VOICE2 );
		sys.trigger( $anal_main_fx );
		sys.wait( .5 );
		sys.trigger( $anal_head_fx1 );
		sys.trigger( $anal_head_fx2 );
		sys.trigger( $anal_head_fx3 );
		sys.trigger( $anal_head_fx4 );
		sys.trigger( $anal_head_fx5 );
		sys.trigger( $anal_head_fx6 );
		//turn off kill brush
		sys.trigger( $analyzeToDeath );
		sys.wait( .5 );
		
		
		$speaker_sc4head_leftfront.startSoundShader ("al4_conveyor_1_point5s", SND_CHANNEL_VOICE2 );
		$sc_4head_leftfront.rotateOnce( '12 0 0' );
		$speaker_sc4head_rightfront.startSoundShader ("al4_conveyor_1_point5s", SND_CHANNEL_VOICE2 );
		$sc_4head_rightfront.rotateOnce( '12 0 0' );
		sys.wait( .15 );
		
		$speaker_sc_largearm_leftfront.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_largearm_leftfront.rotateOnce( '80 0 0' );
		$speaker_sc_largearm_rightfront.startSoundShader ("mcu_support_2s", SND_CHANNEL_VOICE2 );
		$sc_largearm_rightfront.rotateOnce( '80 0 0' );
		
		$sc_smallarm_leftfront.rotateOnce( '31.5 0 0' );
		$sc_smallarm_rightfront.rotateOnce( '31.5 0 0' );
		sys.wait( .5 );
		
		thread analyzer_reararms_operate_off();

		$speaker_sc_rotater_leftfront.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );				
		
		$sc_rotater_leftfront.rotateOnce( '0 45 0' );
		
		$speaker_sc_rotater_rightfront.startSoundShader ("dc3_gui_panel_1", SND_CHANNEL_VOICE2 );				
		
		$sc_rotater_rightfront.rotateOnce( '0 -45 0' );
		
		sys.waitFor( $sc_rotater_rightfront );
		
		$speaker_sc_piston_leftfront.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		$sc_piston_leftfront.move( UP, 84 );
		$speaker_sc_piston_rightfront.startSoundShader ("rec2_pump_1s_01", SND_CHANNEL_VOICE2 );
		$sc_piston_rightfront.move( UP, 84 );
	}
	
	void cache_sounds() 
	{
		sys.cacheSoundShader ("rec2_pump_1s_01");
		sys.cacheSoundShader ("dc3_gui_panel_1");
		sys.cacheSoundShader ("mach_1s");
		sys.cacheSoundShader ("mach_1_5s");
		sys.cacheSoundShader ("mcu_support_2s");
		sys.cacheSoundShader ("al4_conveyor_1_point5s");
		sys.cacheSoundShader ("u1mach_on");
		sys.cacheSoundShader ("u1mach_off");
		sys.cacheSoundShader ("u1mach_loop");
	}
	
	void falling_floor_secret()
	{
		$drop_floor.time( 1 );
		$drop_floor.accelTime( .25 );
		$drop_floor.decelTime( .25 );
		$drop_floor.move( DOWN, 128 );
	}
	
	void main()
	{
		cache_sounds();
		//init
		$top_beam_mover.hide();
		$bottom_beam_mover.hide();
		
		$monster_container_liftarms1.time( 2 );
		$monster_container_liftarms1.accelTime( 0 );
		$monster_container_liftarms1.decelTime( 1 );
				
		$monster_machinedoorsmall_left.time( 1.5 );
		$monster_machinedoorsmall_left.accelTime( .5 );
		$monster_machinedoorsmall_left.decelTime( 1 );
		$monster_machinedoorsmall_right.time( 1.5 );
		$monster_machinedoorsmall_right.accelTime( .5 );
		$monster_machinedoorsmall_right.decelTime( 1 );
		
		$monster_container1_contactpoint.time( 1.5 );
		$monster_container1_contactpoint.accelTime( .5 );
		$monster_container1_contactpoint.decelTime( 1 );
		$monster_container2_contactpoint.time( 1.5 );
		$monster_container2_contactpoint.accelTime( .5 );
		$monster_container2_contactpoint.decelTime( 1 );
				
		$monster_machinedoor1_left.time( 2 );
		$monster_machinedoor1_left.accelTime( .5 );
		$monster_machinedoor1_left.decelTime( 1 );
		$monster_machinedoor1_right.time( 2 );
		$monster_machinedoor1_right.accelTime( .5 );
		$monster_machinedoor1_right.decelTime( 1 );
		$monster_machinedoor2_left.time( 2 );
		$monster_machinedoor2_left.accelTime( .5 );
		$monster_machinedoor2_left.decelTime( 1 );
		$monster_machinedoor2_right.time( 2 );
		$monster_machinedoor2_right.accelTime( .5 );
		$monster_machinedoor2_right.decelTime( 1 );
		
		$sc_piston_leftrear.time( 1.5 );
		$sc_piston_leftrear.accelTime( .5 );
		$sc_piston_leftrear.decelTime( 1 );
		$sc_piston_rightrear.time( 1.5 );
		$sc_piston_rightrear.accelTime( .5 );
		$sc_piston_rightrear.decelTime( 1 );
		
		$sc_rotater_leftrear.time( 1 );
		$sc_rotater_leftrear.accelTime( .25 );
		$sc_rotater_leftrear.decelTime( .75 );
		$sc_rotater_rightrear.time( 1 );
		$sc_rotater_rightrear.accelTime( .25 );
		$sc_rotater_rightrear.decelTime( .75 );
		
		$sc_largearm_leftrear.time( 2 );
		$sc_largearm_leftrear.accelTime( .75 );
		$sc_largearm_leftrear.decelTime( 1 );
		$sc_largearm_rightrear.time( 2 );
		$sc_largearm_rightrear.accelTime( .75 );
		$sc_largearm_rightrear.decelTime( 1 );
		
		$sc_smallarm_leftrear.time( 2 );
		$sc_smallarm_leftrear.accelTime( .5 );
		$sc_smallarm_leftrear.decelTime( 1.25 );
		$sc_smallarm_rightrear.time( 2 );
		$sc_smallarm_rightrear.accelTime( .5 );
		$sc_smallarm_rightrear.decelTime( 1.25 );
		
		$sc_3head_leftrear.time( 1.5 );
		$sc_3head_leftrear.accelTime( .5 );
		$sc_3head_leftrear.decelTime( 1 );
		$sc_3head_rightrear.time( 1.5 );
		$sc_3head_rightrear.accelTime( .5 );
		$sc_3head_rightrear.decelTime( 1 );
		
		$sc_piston_leftfront.time( 1.5 );
		$sc_piston_leftfront.accelTime( .5 );
		$sc_piston_leftfront.decelTime( 1 );
		$sc_piston_rightfront.time( 1.5 );
		$sc_piston_rightfront.accelTime( .5 );
		$sc_piston_rightfront.decelTime( 1 );
		
		$sc_rotater_leftfront.time( 1 );
		$sc_rotater_leftfront.accelTime( .25 );
		$sc_rotater_leftfront.decelTime( .75 );
		$sc_rotater_rightfront.time( 1 );
		$sc_rotater_rightfront.accelTime( .25 );
		$sc_rotater_rightfront.decelTime( .75 );
		
		$sc_largearm_leftfront.time( 2 );
		$sc_largearm_leftfront.accelTime( .75 );
		$sc_largearm_leftfront.decelTime( 1 );
		$sc_largearm_rightfront.time( 2 );
		$sc_largearm_rightfront.accelTime( .75 );
		$sc_largearm_rightfront.decelTime( 1 );
		
		$sc_smallarm_leftfront.time( 1.5 );
		$sc_smallarm_leftfront.accelTime( .5 );
		$sc_smallarm_leftfront.decelTime( 1 );
		$sc_smallarm_rightfront.time( 1.5 );
		$sc_smallarm_rightfront.accelTime( .5 );
		$sc_smallarm_rightfront.decelTime( 1 );
		
		$sc_4head_leftfront.time( 1.25 );
		$sc_4head_leftfront.accelTime( .5 );
		$sc_4head_leftfront.decelTime( .75 );
		$sc_4head_rightfront.time( 1.25 );
		$sc_4head_rightfront.accelTime( .5 );
		$sc_4head_rightfront.decelTime( .75 );
	}
}

//@doomscript-blueprint begin 6
//@source 66A0F391
//@catalog 0C260740
//@node F8DE1C1B-0 40 40
//@node 1D874275-0 330 40
//@node 6C46525E-0 610 40
//@node 30F3E9F7-0 890 40
//@node 6210C37E-0 1170 40
//@node AB44B471-0 1450 40
//@node C787E0D2-0 1730 40
//@node F1EDD342-0 2010 40
//@node 0865F8AF-0 2290 40
//@node E61EFEBB-0 2570 40
//@node 64327A0D-0 2850 40
//@node 4C00B2A3-0 3130 40
//@node 6961C0C4-0 40 40
//@node DD5590DB-0 330 40
//@node 6CB4E533-0 610 40
//@node EAD02EC7-0 890 40
//@node DAE2C342-0 40 40
//@node 4C6EB80F-0 330 40
//@node 39EBA7C9-0 610 40
//@node 3F05AF2B-0 890 40
//@node 4BDE0BBA-0 40 40
//@node FDC45E23-0 330 40
//@node CB25079D-0 610 40
//@node F68C2718-0 40 40
//@node 48E41107-0 330 40
//@node B173F309-0 610 40
//@node DE570A83-0 40 40
//@node 5372D85D-0 330 40
//@node 61ECDF6B-0 610 40
//@node 09F12DAE-0 890 40
//@node B13923D0-0 1170 40
//@node 79218C4F-0 1450 40
//@node 705B4A10-0 1730 40
//@node 09AAF499-0 2010 40
//@node ECEAD4AB-0 2290 40
//@node EE1B7CD3-0 2570 40
//@node 2BEA0BB4-0 2850 40
//@node EE6E8EE1-0 3130 40
//@node 9A6CF782-0 3410 40
//@node AA8EA8AA-0 3690 40
//@node 80C17909-0 3970 40
//@node ACCC43C6-0 4250 40
//@node BB7A6C64-0 4530 40
//@node 516B9D38-0 4810 40
//@node 4A3D871B-0 5090 40
//@node BDA54162-0 5370 40
//@node 6106E7FA-0 5650 40
//@node 56445FEE-0 5930 40
//@node 8F04507A-0 6210 40
//@node 46DD94C3-0 6490 40
//@node 25DE057F-0 6770 40
//@node 2D3C9F40-0 7050 40
//@node C6317DEA-0 7330 40
//@node 56445FEE-1 7610 40
//@node C6B4C3E6-0 7890 40
//@node 20009007-0 8170 40
//@node 37C49E24-0 8450 40
//@node 768AD6F2-0 8730 40
//@node 14D5EB78-0 9010 40
//@node 25DE057F-1 9290 40
//@node 647EA5FA-0 9570 40
//@node 56445FEE-2 9850 40
//@node 61A5AC0E-0 10130 40
//@node D5F51EB5-0 10410 40
//@node C6317DEA-1 10690 40
//@node C4381A59-0 10970 40
//@node D6F815F1-0 11250 40
//@node C6317DEA-2 11530 40
//@node B13923D0-1 11810 40
//@node 55E39970-0 12090 40
//@node BA32A986-0 12370 40
//@node 2BEA0BB4-1 12650 40
//@node B54FBF41-0 12930 40
//@node 51DC86BD-0 13210 40
//@node 972B3A96-0 13490 40
//@node F3E8552F-0 13770 40
//@node 51DC86BD-1 14050 40
//@node 2BEA0BB4-2 14330 40
//@node B55D8E4E-0 14610 40
//@node 51DC86BD-2 14890 40
//@node 972B3A96-1 15170 40
//@node F3E8552F-1 15450 40
//@node 51DC86BD-3 15730 40
//@node 2BEA0BB4-3 16010 40
//@node 22E2E1EC-0 16290 40
//@node 51DC86BD-4 16570 40
//@node D011D51C-0 16850 40
//@node 79608E9C-0 17130 40
//@node ACD3F33D-0 17410 40
//@node E3C726E7-0 17690 40
//@node 8F3C4091-0 17970 40
//@node 768AD6F2-1 18250 40
//@node 61A5AC0E-1 18530 40
//@node DDD02ADD-0 18810 40
//@node 51DC86BD-5 19090 40
//@node B13923D0-2 19370 40
//@node 4809D05A-0 19650 40
//@node 2A11D6D9-0 19930 40
//@node D011D51C-1 20210 40
//@node 79608E9C-1 20490 40
//@node FC49CF74-0 20770 40
//@node 070472BC-0 21050 40
//@node 8F3C4091-1 21330 40
//@node 8BD38964-0 21610 40
//@node 5634D99B-0 21890 40
//@node D8C9B0DF-0 22170 40
//@node CD9AEDE0-0 22450 40
//@node D2A91EC6-0 22730 40
//@node E5461B13-0 23010 40
//@node CFC570CB-0 23290 40
//@node 47DA2B87-0 23570 40
//@node D2A91EC6-1 23850 40
//@node E5461B13-1 24130 40
//@node A24DC8DC-0 24410 40
//@node DD4BA24F-0 24690 40
//@node 8E8BBD11-0 24970 40
//@node 410C9A1E-0 25250 40
//@node A8230853-0 25530 40
//@node 61A5AC0E-2 25810 40
//@node 2EBD8744-0 26090 40
//@node 20637C9B-0 26370 40
//@node D011D51C-2 26650 40
//@node 40374A7D-0 26930 40
//@node B74C873E-0 27210 40
//@node 72F52AC0-0 27490 40
//@node 7ECCDF44-0 27770 40
//@node 768AD6F2-2 28050 40
//@node 61A5AC0E-3 28330 40
//@node DD18FD5D-0 28610 40
//@node BBC6D51C-0 28890 40
//@node 40374A7D-1 29170 40
//@node F14A5ACD-0 29450 40
//@node 860349D9-0 29730 40
//@node 20637C9B-1 30010 40
//@node FFA5593C-0 30290 40
//@node 2E103405-0 30570 40
//@node 20637C9B-2 30850 40
//@node 9A6CF782-1 31130 40
//@node CB8A3C81-0 31410 40
//@node 20637C9B-3 31690 40
//@node B13923D0-3 31970 40
//@node 9081FA01-0 32250 40
//@node 43D11FF7-0 32530 40
//@node B650E6EF-0 32810 40
//@node 91231F3B-0 33090 40
//@node 182BA8CC-0 33370 40
//@node EE6E8EE1-1 33650 40
//@node 5F3C8A20-0 33930 40
//@node 182BA8CC-1 34210 40
//@node D011D51C-3 34490 40
//@node 4B5588DE-0 34770 40
//@node 637461E7-0 35050 40
//@node E44FE525-0 35330 40
//@node 58C61CAA-0 35610 40
//@node B0D5ACAA-0 35890 40
//@node 0C898506-0 36170 40
//@node B13923D0-4 36450 40
//@node 7F7808A7-0 36730 40
//@node 122FA10C-0 37010 40
//@node 4C82D823-0 37290 40
//@node 1133925C-0 37570 40
//@node D3B1327D-0 37850 40
//@node 1133925C-1 38130 40
//@node 6FF0B784-0 38410 40
//@node D1D38DD1-0 38690 40
//@node 76D849EA-0 38970 40
//@node 06CFB676-0 39250 40
//@node 58C61CAA-1 39530 40
//@node B0D5ACAA-1 39810 40
//@node B7FE7B6D-0 40 40
//@node 682750A1-0 330 40
//@node 7F5267B6-0 610 40
//@node 06953B93-0 890 40
//@node 0B667FD4-0 1170 40
//@node E3ED4FEC-0 1450 40
//@node EB36AEA3-0 1730 40
//@node 4F789294-0 2010 40
//@node CA7B7D56-0 2290 40
//@node DC88EAC6-0 2570 40
//@node E6DC9C3B-0 2850 40
//@node 303E9EFC-0 3130 40
//@node 9B06B8BC-0 3410 40
//@node FBCEAE2C-0 3690 40
//@node AB0FEC3C-0 3970 40
//@node 87B4A7E3-0 4250 40
//@node F7FA7525-0 4530 40
//@node 65FEE056-0 4810 40
//@node 899CBD6C-0 5090 40
//@node FBCEAE2C-1 5370 40
//@node 5D93DE20-0 5650 40
//@node 9DEBDE45-0 5930 40
//@node 984486D6-0 6210 40
//@node F38D134C-0 6490 40
//@node 739A5B7F-0 6770 40
//@node F7FA7525-1 7050 40
//@node 5A96B5D0-0 7330 40
//@node FBCEAE2C-2 7610 40
//@node BD0B6072-0 7890 40
//@node DC943977-0 8170 40
//@node 899CBD6C-1 8450 40
//@node 6877C22F-0 8730 40
//@node 9814C67B-0 9010 40
//@node 899CBD6C-2 9290 40
//@node 91946DB3-0 9570 40
//@node B6129565-0 9850 40
//@node A3E293CC-0 10130 40
//@node 7F5267B6-1 10410 40
//@node 819E3897-0 10690 40
//@node F6978F23-0 10970 40
//@node 4989B7E0-0 11250 40
//@node B20ECD31-0 11530 40
//@node F6978F23-1 11810 40
//@node 7F5267B6-2 12090 40
//@node 1237F450-0 12370 40
//@node F6978F23-2 12650 40
//@node 4989B7E0-1 12930 40
//@node B20ECD31-1 13210 40
//@node F6978F23-3 13490 40
//@node 7F5267B6-3 13770 40
//@node 5A967CE2-0 14050 40
//@node F6978F23-4 14330 40
//@node CE17983E-0 14610 40
//@node C97640F6-0 14890 40
//@node C7DDC127-0 15170 40
//@node C05E8FE5-0 15450 40
//@node 98BB9FF7-0 15730 40
//@node F38D134C-1 16010 40
//@node BD0B6072-1 16290 40
//@node 45A46F1B-0 16570 40
//@node F6978F23-5 16850 40
//@node 91946DB3-1 17130 40
//@node 56109E23-0 17410 40
//@node 990E5293-0 17690 40
//@node CE17983E-1 17970 40
//@node C97640F6-1 18250 40
//@node C8B93BAA-0 18530 40
//@node F60C18B6-0 18810 40
//@node 98BB9FF7-1 19090 40
//@node F393C1CF-0 19370 40
//@node 260A2068-0 19650 40
//@node 325945CD-0 19930 40
//@node 9E279A42-0 20210 40
//@node 68C6AEBC-0 20490 40
//@node 2F9D6A9D-0 20770 40
//@node DD650D35-0 21050 40
//@node 3D2B43A9-0 21330 40
//@node 68C6AEBC-1 21610 40
//@node 2F9D6A9D-1 21890 40
//@node 8DD9D523-0 22170 40
//@node 86EA2440-0 22450 40
//@node 7B3862FF-0 22730 40
//@node 9286FAE0-0 23010 40
//@node 99E47CA6-0 23290 40
//@node BD0B6072-2 23570 40
//@node 89950716-0 23850 40
//@node E3C98621-0 24130 40
//@node E2A42C9C-0 24410 40
//@node 5CB1D783-0 24690 40
//@node 0C8B232C-0 24970 40
//@node 97E4CF52-0 25250 40
//@node 5C9E7D5E-0 25530 40
//@node F38D134C-2 25810 40
//@node BD0B6072-3 26090 40
//@node 4B664BD7-0 26370 40
//@node 19E35D1A-0 26650 40
//@node 5CB1D783-1 26930 40
//@node E18FF177-0 27210 40
//@node 271CD98F-0 27490 40
//@node E3C98621-1 27770 40
//@node F7561336-0 28050 40
//@node 39AA6E0F-0 28330 40
//@node E3C98621-2 28610 40
//@node 0B667FD4-1 28890 40
//@node ACBFF36B-0 29170 40
//@node E3C98621-3 29450 40
//@node 91946DB3-2 29730 40
//@node 35210794-0 30010 40
//@node E7EBE439-0 30290 40
//@node 6AFFDE99-0 30570 40
//@node 6CF49E31-0 30850 40
//@node 4448238A-0 31130 40
//@node 06953B93-1 31410 40
//@node 314429E6-0 31690 40
//@node 4448238A-1 31970 40
//@node CE17983E-2 32250 40
//@node F73194D4-0 32530 40
//@node 3E4FF27D-0 32810 40
//@node 0440FEA7-0 33090 40
//@node EF0DCD74-0 33370 40
//@node 780B0854-0 33650 40
//@node E86B3326-0 33930 40
//@node 91946DB3-3 34210 40
//@node CF2FB946-0 34490 40
//@node D032C1B2-0 34770 40
//@node 2562E3EC-0 35050 40
//@node E25897EE-0 35330 40
//@node AA35505D-0 35610 40
//@node E25897EE-1 35890 40
//@node E29B9E13-0 36170 40
//@node D633855F-0 36450 40
//@node 427CA134-0 36730 40
//@node 471913FC-0 37010 40
//@node EF0DCD74-1 37290 40
//@node 2A17DAB2-0 37570 40
//@node 780B0854-1 37850 40
//@node 4D8E7C04-0 40 40
//@node 8B16062E-0 330 40
//@node 131DD5D5-0 40 40
//@node B0CE0498-0 330 40
//@node 1B0F4FB1-0 610 40
//@node 4F95D7AB-0 890 40
//@node 702506A0-0 1170 40
//@node 305454F2-0 1450 40
//@node F5CB1377-0 1730 40
//@node 1787AD82-0 2010 40
//@node DCAB4924-0 2290 40
//@node EEA8B1AE-0 2570 40
//@node C1F1D7B0-0 2850 40
//@node 838847AE-0 3130 40
//@node 713F345D-0 3410 40
//@node 0D304015-0 3690 40
//@node BC3EF1F2-0 3970 40
//@node C1F1D7B0-1 4250 40
//@node F086C966-0 4530 40
//@node DFBE568C-0 4810 40
//@node 168F5083-0 5090 40
//@node 2C935393-0 5370 40
//@node 732732E0-0 5650 40
//@node 34A5B5A9-0 5930 40
//@node F080ACE0-0 6210 40
//@node 081F8377-0 6490 40
//@node 2CBEC70F-0 6770 40
//@node 6F1AD8B9-0 7050 40
//@node E2329B66-0 7330 40
//@node 6B73E7AF-0 7610 40
//@node 24DED79C-0 7890 40
//@node 18DA590D-0 8170 40
//@node D3827D7A-0 8450 40
//@node 9B15B962-0 8730 40
//@node 070E4E74-0 9010 40
//@node 71204653-0 9290 40
//@node E44AE7F3-0 9570 40
//@node 8799C32A-0 9850 40
//@node 153AAD68-0 40 40
//@node 843F9096-0 330 40
//@node 1EBD0167-0 610 40
//@node CBA3DB95-0 890 40
//@node 88901E2A-0 1170 40
//@node C205C270-0 1450 40
//@node D570D13E-0 1730 40
//@node 0B0F79D3-0 2010 40
//@node 77639CDF-0 2290 40
//@node ECED246C-0 2570 40
//@node E86840A5-0 2850 40
//@node 4F2BA153-0 3130 40
//@node 920DB679-0 3410 40
//@node 0F60728A-0 3690 40
//@node 208F524A-0 3970 40
//@node B93757FD-0 4250 40
//@node 770F99B8-0 4530 40
//@node CC31D0B5-0 4810 40
//@node 7147C416-0 5090 40
//@node 07DCF490-0 5370 40
//@node 70CB9619-0 5650 40
//@node 353EBD88-0 5930 40
//@node 63918B81-0 6210 40
//@node 74F4BD12-0 6490 40
//@node 76746748-0 40 40
//@node 7FD6A0B8-0 330 40
//@node AD83C8C1-0 610 40
//@node C0ECBEE8-0 890 40
//@node 2DE79515-0 1170 40
//@node AB1CF1D3-0 1450 40
//@node 2C74AFF0-0 1730 40
//@node 0369871A-0 2010 40
//@node AA354859-0 2290 40
//@node 427D407F-0 2570 40
//@node F99ECA5C-0 2850 40
//@node 2A9ABA46-0 3130 40
//@node C0ECBEE8-1 3410 40
//@node E4C18402-0 3690 40
//@node 3CE43C7E-0 3970 40
//@node 9AEC30BD-0 4250 40
//@node BB6B7E1E-0 4530 40
//@node 5A13B9E2-0 4810 40
//@node 46975B52-0 5090 40
//@node 48A38194-0 5370 40
//@node 4DE0EDC9-0 5650 40
//@node 6C322B55-0 5930 40
//@node 48CD5010-0 6210 40
//@node EBA1E36F-0 6490 40
//@node 22DE0AFA-0 40 40
//@node 954D727C-0 330 40
//@node 7FAFDAF4-0 610 40
//@node 5D34113B-0 890 40
//@node 97D29704-0 1170 40
//@node 3D8BEF5B-0 1450 40
//@node 527DFD22-0 1730 40
//@node E1211581-0 2010 40
//@node A682B4F0-0 2290 40
//@node A3CC8837-0 2570 40
//@node 5F6D8F84-0 2850 40
//@node 5D34113B-1 3130 40
//@node C1C1C141-0 3410 40
//@node FECA1AB1-0 3690 40
//@node 04BEE566-0 3970 40
//@node D662C298-0 4250 40
//@node 185DF42C-0 4530 40
//@node D90F2896-0 4810 40
//@node 5F7CF9A1-0 5090 40
//@node 24EC66A9-0 5370 40
//@node 4AAB5122-0 5650 40
//@node B1CBED60-0 5930 40
//@node 7825F4D3-0 6210 40
//@node 5D34113B-2 6490 40
//@node A4E8F6E9-0 6770 40
//@node 2956CCB6-0 7050 40
//@node 05661994-0 7330 40
//@node 2657DE7B-0 7610 40
//@node 1CFD0C76-0 7890 40
//@node FF2AD1B3-0 8170 40
//@node A4904297-0 8450 40
//@node 9CCFB013-0 8730 40
//@node 2E1C142E-0 9010 40
//@node 90824928-0 9290 40
//@node B832CE32-0 40 40
//@node 3E4C6039-0 330 40
//@node 564BBF46-0 610 40
//@node 6A2FAFA1-0 890 40
//@node 3BC98199-0 1170 40
//@node E6216550-0 1450 40
//@node F8713605-0 1730 40
//@node 3CCA57A4-0 2010 40
//@node 032C7942-0 2290 40
//@node CEA5C171-0 2570 40
//@node DF6415D6-0 40 40
//@node 9F674A2E-0 330 40
//@node 2743D8FA-0 610 40
//@node 9C5F3C03-0 890 40
//@node EE94FFC0-0 1170 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 6BA11445-0 610 40
//@node C51CB791-0 890 40
//@node E7EF3EF3-0 1170 40
//@node 96A30C7D-0 1450 40
//@node 08E6EA0D-0 1730 40
//@node 923A5FF8-0 2010 40
//@node 84BCE217-0 2290 40
//@node 69492658-0 2570 40
//@node 3A27A7DD-0 2850 40
//@node 0DBF816A-0 3130 40
//@node 3461474F-0 3410 40
//@node BBFCD0A3-0 3690 40
//@node E2766D80-0 3970 40
//@node F6367059-0 4250 40
//@node CBC9E652-0 4530 40
//@node 41416629-0 4810 40
//@node 2551717E-0 5090 40
//@node DBFED700-0 5370 40
//@node 8A39962F-0 5650 40
//@node 188F6BF0-0 5930 40
//@node CF1515F9-0 6210 40
//@node D8F630A2-0 6490 40
//@node 211CE847-0 6770 40
//@node 7703FAA1-0 7050 40
//@node ED2B998A-0 7330 40
//@node 76F2B06F-0 7610 40
//@node 8FE77506-0 7890 40
//@node 198E271D-0 8170 40
//@node D91A91CA-0 8450 40
//@node 5A9B6AE7-0 8730 40
//@node C92303C4-0 9010 40
//@node C9A4BBB5-0 9290 40
//@node 35CD12D0-0 9570 40
//@node 86A60A7F-0 9850 40
//@node 62FC7FA0-0 10130 40
//@node F6D6257C-0 10410 40
//@node 7BB5FE94-0 10690 40
//@node 82B48312-0 10970 40
//@node 54F5B48F-0 11250 40
//@node BBFD3DD9-0 11530 40
//@node 2F43D987-0 11810 40
//@node A8007BE5-0 12090 40
//@node 59436425-0 12370 40
//@node E911974B-0 12650 40
//@node AB8549EA-0 12930 40
//@node 0861A51C-0 13210 40
//@node 1885A346-0 13490 40
//@node 964EB40D-0 13770 40
//@node 18ED0356-0 14050 40
//@node 3C6F6544-0 14330 40
//@node 2C2D6B92-0 14610 40
//@node 47379859-0 14890 40
//@node A996CBFF-0 15170 40
//@node F738E7C3-0 15450 40
//@node 1E7699E0-0 15730 40
//@node 2F3A3839-0 16010 40
//@node CEC628D4-0 16290 40
//@node 646B0FD3-0 16570 40
//@node 468B4EAC-0 16850 40
//@node 69BD6BF4-0 17130 40
//@node B61EB533-0 17410 40
//@node A826BA8C-0 17690 40
//@node 594FCC01-0 17970 40
//@node 5C110BDE-0 18250 40
//@node 19DBCDFB-0 18530 40
//@node 2FEEAA33-0 18810 40
//@node F21A76C5-0 19090 40
//@node CDF4C81B-0 19370 40
//@node 3CB3262A-0 19650 40
//@node 7CDEA43E-0 19930 40
//@node 55843A00-0 20210 40
//@node 6014BF62-0 20490 40
//@node F8F945A4-0 20770 40
//@node BC7EDAFE-0 21050 40
//@node 699D1783-0 21330 40
//@node 3C0CB093-0 21610 40
//@node 10F89ABD-0 21890 40
//@node 4443579A-0 22170 40
//@node E8743581-0 22450 40
//@node 4E1822D6-0 22730 40
//@node 4EFE6987-0 23010 40
//@node 3635C924-0 23290 40
//@node 2DFDDD95-0 23570 40
//@node E7DD6181-0 23850 40
//@node 1AAFDCFC-0 24130 40
//@node F7D18B12-0 24410 40
//@node 42F7B5E4-0 24690 40
//@node 12D81DDB-0 24970 40
//@node F1A48EBB-0 25250 40
//@doomscript-blueprint end
