namespace map_comm1 {
	float msg_state;
	entity pipe1, pipe2, pipe3, pipe4, pipe5, pipe6, pipe0;
	vector pipe_origin;

	void mover_startsound (entity ent) {
		//ent.startSoundShader ("m1_start", SND_CHANNEL_VOICE);
		//sys.wait (0.75);
		ent.startSoundShader ("m1_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound (entity ent) {
		ent.startSoundShader ("m1_stop", SND_CHANNEL_VOICE2);
		ent.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_ITEM );
	}

	void mover_startsound2 (entity ent) {
		//ent.startSoundShader ("m2_start", SND_CHANNEL_VOICE);
		//sys.wait (0.75);
		ent.startSoundShader ("m2_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound2 (entity ent) {
		ent.startSoundShader ("m2_stop", SND_CHANNEL_VOICE2);
		ent.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_ITEM );
	}

	void mover_startsound3 (entity ent) {
		//ent.startSoundShader ("m3_start", SND_CHANNEL_VOICE);
		//sys.wait (1);
		ent.startSoundShader ("m3_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound3 (entity ent) {
		ent.startSoundShader ("m3_stop", SND_CHANNEL_VOICE2);
		ent.startSoundShader ("rec1_pump_endclack_01", SND_CHANNEL_ITEM );
	}



	////////////////////////////////////////////////////
	//
	//	Setup binds and times etc...
	//
	////////////////////////////////////////////////////
	void setup_objects()
	{
		//power drill 1 and 2 binds and initial movements
		$pwrdrill_1.bind ($pwrdrill_1_anchor);
		$pwrdrill_2.bind ($pwrdrill_2_anchor);

		$pwrdrill_1_anchor.rotateOnce ( '0 0 -45' );
		$pwrdrill_2_anchor.rotateOnce ( '0 0 -45' );

		sys.waitFor ($pwrdrill_1_anchor);

		$pwrdrill_1.time (.20);
		$pwrdrill_1.time (.50);

		$pwrdrill_1.rotate ( '360 0 0' );
		$pwrdrill_2.rotate ( '360 0 0' );

		//oval binds and times/speeds
		$oval_spid_1.bind ($oval_main);
		$oval_spid_2.bind ($oval_main);

		$oval_main.speed (300);

		$oval_main.decelTime (.5);
		$oval_main.accelTime (.25);

		//snail 2 pole 1 binds and initial movements
		$snl2_pl1_recep.bind ($snl2_pl1_anc);
		$snl2_pl1.bind ($snl2_pl1_anc);
		$snl2_pl1_spin_anc.bind ($snl2_pl1_anc);

		$snl2_pl1_spin.bind ($snl2_pl1_spin_anc);	

		$snl2_pl1_spin_arm1.bind ($snl2_pl1_spin);
		$snl2_pl1_spin_arm2.bind ($snl2_pl1_spin);
		$snl2_pl1_spin_arm3.bind ($snl2_pl1_spin);
		$snl2_pl1_spin_arm4.bind ($snl2_pl1_spin);

		$snl2_pl1_wire1.bind ($snl2_pl1_spin);
		$snl2_pl1_wire2.bind ($snl2_pl1_spin);
		$snl2_pl1_wire3.bind ($snl2_pl1_spin);
		$snl2_pl1_wire4.bind ($snl2_pl1_spin);

		$snl2_pl1_spin.time (1);

		$snl2_pl1_spin_arm1.time (.6);
		$snl2_pl1_spin_arm2.time (.6);
		$snl2_pl1_spin_arm3.time (.6);
		$snl2_pl1_spin_arm4.time (.6);

		//initial position movements
		$snl2_pl1_anc.rotateOnce ( '67.5 0 0');
		sys.waitFor ($snl2_pl1_anc);

		$snl2_pl1.move ( DOWN, 192 );

		//snail 2 pole 2 binds and initial movements
		$snl2_pl2_recep.bind ($snl2_pl2_anc);
		$snl2_pl2.bind ($snl2_pl2_anc);
		$snl2_pl2_spin_anc.bind ($snl2_pl2_anc);

		$snl2_pl2_spin.bind ($snl2_pl2_spin_anc);	

		$snl2_pl2_spin_arm1.bind ($snl2_pl2_spin);
		$snl2_pl2_spin_arm2.bind ($snl2_pl2_spin);
		$snl2_pl2_spin_arm3.bind ($snl2_pl2_spin);
		$snl2_pl2_spin_arm4.bind ($snl2_pl2_spin);

		$snl2_pl2_wire1.bind ($snl2_pl2_spin);
		$snl2_pl2_wire2.bind ($snl2_pl2_spin);
		$snl2_pl2_wire3.bind ($snl2_pl2_spin);
		$snl2_pl2_wire4.bind ($snl2_pl2_spin);

		$snl2_pl2_spin.time (1);

		$snl2_pl2_spin_arm1.time (.6);
		$snl2_pl2_spin_arm2.time (.6);
		$snl2_pl2_spin_arm3.time (.6);
		$snl2_pl2_spin_arm4.time (.6);

		//initial position movements
		$snl2_pl2_anc.rotateOnce ( '22.5 0 0');
		sys.waitFor ($snl2_pl2_anc);

		$snl2_pl2.move ( DOWN, 208 );

		//snail 2 shell times and initial movements
		$snl2_shell1.time (.25);
		$snl2_shell2.time (.5);
		$snl2_shell3.time (.75);

		//misc pipe hall initial movements, rotations etc...
		$holder_1.rotateOnce ( '-45 0 0' );
		$holder_2.rotateOnce ( '-45 0 0' );
		$holder_3.rotateOnce ( '-45 0 0' );
		$holder_4.rotateOnce ( '-45 0 0' );
		$holder_5.rotateOnce ( '-45 0 0' );
		$holder_6.rotateOnce ( '-45 0 0' );

		$mcarrier.rotateOnce ( '-45 0 0' );

		$lcarrier.rotateOnce ( '-45 0 0' );
		$lcarrier.speed (100);

		//pipe hall pipe initial setups
		pipe1 = sys.spawn( "func_mover" );
		pipe1.setModel( "pipe1" );
		pipe_origin = $pipe1pos_1.getOrigin();
		pipe1.setOrigin (pipe_origin);
		pipe1.setAngles ( '-45 0 0' );

		pipe2 = sys.spawn( "func_mover" );
		pipe2.setModel( "pipe2" );
		pipe_origin = $pipe2pos_1.getOrigin();
		pipe2.setOrigin (pipe_origin);
		pipe2.setAngles ( '-45 0 0' );

		pipe3 = sys.spawn( "func_mover" );
		pipe3.setModel( "pipe3" );
		pipe_origin = $pipe3pos_1.getOrigin();
		pipe3.setOrigin (pipe_origin);
		pipe3.setAngles ( '-45 0 0' );

		pipe4 = sys.spawn( "func_mover" );
		pipe4.setModel( "pipe4" );
		pipe_origin = $pipe4pos_1.getOrigin();
		pipe4.setOrigin (pipe_origin);
		pipe4.setAngles ( '-45 0 0' );

		pipe5 = sys.spawn( "func_mover" );
		pipe5.setModel( "pipe5" );
		pipe_origin = $pipe5pos_1.getOrigin();
		pipe5.setOrigin (pipe_origin);
		pipe5.setAngles ( '-45 0 0' );

		pipe6 = sys.spawn( "func_mover" );
		pipe6.setModel( "pipe6" );
		pipe_origin = $pipe6pos_1.getOrigin();
		pipe6.setOrigin (pipe_origin);
		pipe6.setAngles ( '-45 0 0' );

	}



	////////////////////////////////////////////////////
	//
	//	oval movement 
	//
	////////////////////////////////////////////////////
	void oval_movement ()
	{
	float pick, pick_old, oval_dist ;
	$oval_main.setKey ("s_minDistance", "5");
	$oval_main.setKey ("s_maxDistance", "30");
	$oval_main.setKey ("s_unclamped", "1");
	$oval_main.setKey ("s_volume", "5");
	$oval_main.setKey ("snd_accel", "m5_start");
	$oval_main.setKey ("snd_move", "m4_loop");
	$oval_main.setKey ("snd_decel", "m4_stop");
	
	pick = 1;
	pick_old = 1;

		while (1)
		{
			while ( pick == pick_old )
			{
				pick = ( sys.random(4) + 1 );

				if ( pick < 2 )
				{
					pick = 1;
				}
				else if ( pick < 3 )
					{
						pick = 2;
					}
					else if ( pick < 4 )
						{
							pick = 3;
						}
						else
						{
							pick = 4;
						}
			}

		oval_dist = (( pick_old - pick ) * 192 );
		$oval_main.move ( WEST, oval_dist );

		sys.waitFor ($oval_main);
		sys.wait (2);

		pick_old = pick;
		}

	}

	void cache_sounds() {
		sys.cacheSoundShader ("m1_loop");
		sys.cacheSoundShader ("m1_stop");
		sys.cacheSoundShader ("m2_loop");
		sys.cacheSoundShader ("m2_stop");
		sys.cacheSoundShader ("m3_loop");
		sys.cacheSoundShader ("m3_stop");
		sys.cacheSoundShader ("rec1_pump_endclack_01");
		
		sys.cacheSoundShader ("c1_mcarrier");
		sys.cacheSoundShader ("c1_pipeupaway");
		sys.cacheSoundShader ("c1_pipedownbounce");
		sys.cacheSoundShader ("c1_pipeloader");
		sys.cacheSoundShader ("c1_pipeloader2");
		sys.cacheSoundShader ("c1_pipeloader3");
		sys.cacheSoundShader ("c1_mloop1");
		
		
	}

	////////////////////////////////////////////////////
	//
	//	move pipe up and away
	//
	////////////////////////////////////////////////////
	void pipe_upaway (entity pipeupaway)
	{
		pipeupaway.bind ($mcarrier);
		
		$mcarrier.startSoundShader ("c1_mcarrier", SND_CHANNEL_VOICE );

		$mcarrier.moveTo ($mcarrierpos_2);
		sys.waitFor ($mcarrier);

		pipeupaway.unbind ();

		$mcarrier.moveTo ($mcarrierpos_1);
		pipeupaway.time (2);
		pipeupaway.startSoundShader ("c1_pipeupaway", SND_CHANNEL_VOICE2 );
		pipeupaway.move ( UP , 128 );
		sys.waitFor (pipeupaway);
		pipeupaway.remove ();
	}


	////////////////////////////////////////////////////
	//
	//	move pipe to middle 
	//
	////////////////////////////////////////////////////
	void move_pipe (entity pipe, entity holder)
	{
		holder.speed (100);
		
		pipe.bind (holder);
		holder.startSoundShader ("c1_pipeloader2", SND_CHANNEL_VOICE );
		holder.move ( REL_BACK, 24 );
		sys.waitFor (holder);

		pipe.unbind ();
		pipe.bind ($lcarrier);

		holder.move ( REL_FORWARD, 24 );
		holder.startSoundShader ("c1_pipeloader3", SND_CHANNEL_VOICE2 );
		sys.waitFor (holder);

		holder.bind ($holder_rotate);
						
		$holder_rotate.rotateOnce ( '15 0 0' );

		$lcarrier.setKey ("snd_move", "c1_mloop1" );
		$lcarrier.moveTo ($lcarrierpos_middle);
		sys.waitFor ($lcarrier);

		$lcarrier.startSoundShader ("c1_pipeloader", SND_CHANNEL_VOICE);
		$lcarrier.move ( REL_FORWARD, 50 );
		sys.waitFor ($lcarrier);
		pipe.unbind ();
		sys.wait (.5);

		$lcarrier.startSoundShader ("c1_pipeloader2", SND_CHANNEL_VOICE);
		$lcarrier.move ( REL_BACK, 50 );
		sys.waitFor ($lcarrier);

		// thread pipe move up and away
		sys.killthread ( "map_comtower::pipe_upaway" );
		thread pipe_upaway ( pipe );

	}


	////////////////////////////////////////////////////
	//
	//	test stuff eventually will be pipe mover loop
	//
	////////////////////////////////////////////////////
	void move_hallpipes()
	{
		float rand;

		while (1)
		{
			sys.killthread ("map_comtower::move_pipe");
			rand = sys.random (5);

			if ( rand < 1 )
				{
					$lcarrier.moveTo ($lcarrierpos_1);
					sys.waitFor ($lcarrier);
					pipe0 = pipe1;
					thread move_pipe (pipe0, $holder_1);

					sys.wait (2);
					//move new pipe in
					pipe1 = sys.spawn( "func_mover" );
					pipe1.setModel( "pipe1" );
					pipe_origin = $pipe1pos_initial.getOrigin();
					pipe1.setOrigin (pipe_origin);
					pipe1.setAngles ( '-30 0 0' );

					pipe1.moveTo ($pipe1pos_1);
					sys.waitFor ( pipe1 );
					sys.wait (.5);
					$holder_1.bind (pipe1);
					$holder_1.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );
					

					pipe1.time (.5);
					pipe1.rotateOnce ( '-15 0 0' );
					sys.waitFor ( pipe1 );

					//bounce it
					pipe1.time( .15 );
					pipe1.accelTime( 0 );
					pipe1.decelTime( .15 );
					pipe1.rotateOnce( '1 0 0' );
					sys.waitFor (pipe1);

					pipe1.time( .15 );
					pipe1.accelTime( .15 );
					pipe1.decelTime( 0 );
					pipe1.rotateOnce( '-1 0 0' );
					sys.waitFor (pipe1);

					$holder_1.unbind ();

				}
			else if ( rand < 2 )
				{
					$lcarrier.moveTo ($lcarrierpos_2);
					sys.waitFor ($lcarrier);
					pipe0 = pipe2;
					thread move_pipe (pipe0, $holder_2);

					sys.wait (2);
					//move new pipe in
					pipe2 = sys.spawn( "func_mover" );
					pipe2.setModel( "pipe2" );
					pipe_origin = $pipe2pos_initial.getOrigin();
					pipe2.setOrigin (pipe_origin);
					pipe2.setAngles ( '-30 0 0' );

					pipe2.moveTo ($pipe2pos_1);
					sys.waitFor ( pipe2 );
					sys.wait (.5);
					$holder_2.bind (pipe2);
					$holder_2.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );

					pipe2.time (.5);
					pipe2.rotateOnce ( '-15 0 0' );
					sys.waitFor ( pipe2 );

					//bounce it
					pipe2.time( .15 );
					pipe2.accelTime( 0 );
					pipe2.decelTime( .15 );
					pipe2.rotateOnce( '1 0 0' );
					sys.waitFor (pipe2);

					pipe2.time( .15 );
					pipe2.accelTime( .15 );
					pipe2.decelTime( 0 );
					pipe2.rotateOnce( '-1 0 0' );
					sys.waitFor (pipe2);

					$holder_2.unbind ();
				}
				else if ( rand < 3 )
					{
						$lcarrier.moveTo ($lcarrierpos_3);
						sys.waitFor ($lcarrier);
						pipe0 = pipe3;
						thread move_pipe (pipe0, $holder_3);

						sys.wait (2);
						//move new pipe in
						pipe3 = sys.spawn( "func_mover" );
						pipe3.setModel( "pipe3" );
						pipe_origin = $pipe3pos_initial.getOrigin();
						pipe3.setOrigin (pipe_origin);
						pipe3.setAngles ( '-30 0 0' );

						pipe3.moveTo ($pipe3pos_1);
						sys.waitFor ( pipe3 );
						sys.wait (.5);
						$holder_3.bind (pipe3);
						$holder_3.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );

						pipe3.time (.5);
						pipe3.rotateOnce ( '-15 0 0' );
						sys.waitFor ( pipe3 );

						//bounce it
						pipe3.time( .15 );
						pipe3.accelTime( 0 );
						pipe3.decelTime( .15 );
						pipe3.rotateOnce( '1 0 0' );
						sys.waitFor (pipe3);

						pipe3.time( .15 );
						pipe3.accelTime( .15 );
						pipe3.decelTime( 0 );
						pipe3.rotateOnce( '-1 0 0' );
						sys.waitFor (pipe3);

						$holder_3.unbind ();
					}
					else if ( rand < 4 )
					{
						$lcarrier.moveTo ($lcarrierpos_4);
						sys.waitFor ($lcarrier);
						pipe0 = pipe4;
						thread move_pipe (pipe0, $holder_4);

						sys.wait (2);
						//move new pipe in
						pipe4 = sys.spawn( "func_mover" );
						pipe4.setModel( "pipe4" );
						pipe_origin = $pipe4pos_initial.getOrigin();
						pipe4.setOrigin (pipe_origin);
						pipe4.setAngles ( '-30 0 0' );

						pipe4.moveTo ($pipe4pos_1);
						sys.waitFor ( pipe4 );
						sys.wait (.5);
						$holder_4.bind (pipe4);
						$holder_4.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );

						pipe4.time (.5);
						pipe4.rotateOnce ( '-15 0 0' );
						sys.waitFor ( pipe4 );

						//bounce it
						pipe4.time( .15 );
						pipe4.accelTime( 0 );
						pipe4.decelTime( .15 );
						pipe4.rotateOnce( '1 0 0' );
						sys.waitFor (pipe4);

						pipe4.time( .15 );
						pipe4.accelTime( .15 );
						pipe4.decelTime( 0 );
						pipe4.rotateOnce( '-1 0 0' );
						sys.waitFor (pipe4);

						$holder_4.unbind ();
					}
						else if ( rand < 5 )
						{
							$lcarrier.moveTo ($lcarrierpos_5);
							sys.waitFor ($lcarrier);
							pipe0 = pipe5;
							thread move_pipe (pipe0, $holder_5);

							sys.wait (2);
							//move new pipe in
							pipe5 = sys.spawn( "func_mover" );
							pipe5.setModel( "pipe5" );
							pipe_origin = $pipe5pos_initial.getOrigin();
							pipe5.setOrigin (pipe_origin);
							pipe5.setAngles ( '-30 0 0' );

							pipe5.moveTo ($pipe5pos_1);
							sys.waitFor ( pipe5 );
							sys.wait (.5);
							$holder_5.bind (pipe5);
							$holder_5.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );

							pipe5.time (.5);
							pipe5.rotateOnce ( '-15 0 0' );
							sys.waitFor ( pipe5 );

							//bounce it
							pipe5.time( .15 );
							pipe5.accelTime( 0 );
							pipe5.decelTime( .15 );
							pipe5.rotateOnce( '1 0 0' );
							sys.waitFor (pipe5);

							pipe5.time( .15 );
							pipe5.accelTime( .15 );
							pipe5.decelTime( 0 );
							pipe5.rotateOnce( '-1 0 0' );
							sys.waitFor (pipe5);

							$holder_5.unbind ();
						}
						else
						{
							$lcarrier.moveTo ($lcarrierpos_6);
							sys.waitFor ($lcarrier);
							pipe0 = pipe6;
							thread move_pipe (pipe0, $holder_6);

							sys.wait (2);
							//move new pipe in
							pipe6 = sys.spawn( "func_mover" );
							pipe6.setModel( "pipe6" );
							pipe_origin = $pipe6pos_initial.getOrigin();
							pipe6.setOrigin (pipe_origin);
							pipe6.setAngles ( '-30 0 0' );

							pipe6.moveTo ($pipe6pos_1);
							sys.waitFor ( pipe6 );
							sys.wait (.5);
							$holder_6.bind (pipe6);
							$holder_6.startSoundShader ("c1_pipedownbounce", SND_CHANNEL_VOICE2 );

							pipe6.time (.5);
							pipe6.rotateOnce ( '-15 0 0' );
							sys.waitFor ( pipe6 );

							//bounce it
							pipe6.time( .15 );
							pipe6.accelTime( 0 );
							pipe6.decelTime( .15 );
							pipe6.rotateOnce( '1 0 0' );
							sys.waitFor (pipe6);

							pipe6.time( .15 );
							pipe6.accelTime( .15 );
							pipe6.decelTime( 0 );
							pipe6.rotateOnce( '-1 0 0' );
							sys.waitFor (pipe6);

							$holder_6.unbind ();
						}
		}//END WHILE
	}

	
	////////////////////////////////////////////////////
	//
	//	move snail 2 pole 1 things up
	//
	////////////////////////////////////////////////////
	void move_snail2_connect1_up()
	{
		$snl2_pl1.time (.5);
		$snl2_pl1.move ( UP, 192 );
		//pole1 move sound .5sec
		sys.trigger ($snail2_pole1_speaker);
		sys.waitFor ($snl2_pl1);

		$snl2_pl1_spin_anc.move ( UP, 144 );
		$snl2_pl1_spin.rotateOnce ( '0 540 0' );

		//pole1 guts moveup sound 1sec
		sys.trigger ($snail2_pole1guts_up_speaker);

		sys.wait (.5);
		$snl2_pl1_spin_arm1.rotateOnce ( '0 0 -180' );
		$snl2_pl1_spin_arm2.rotateOnce ( '0 0 -180' );
		$snl2_pl1_spin_arm3.rotateOnce ( '0 0 -180' );
		$snl2_pl1_spin_arm4.rotateOnce ( '0 0 -180' );

		sys.waitFor ($snl2_pl1_spin_arm4);
	}


	////////////////////////////////////////////////////
	//
	//	move snail 2 pole 1 things down
	//
	////////////////////////////////////////////////////
	void move_snail2_connect1_down()
	{
		//pole1 guts movedown sound 1sec
		sys.trigger ($snail2_pole1guts_down_speaker);

		$snl2_pl1_spin_anc.move ( DOWN, 144 );
		$snl2_pl1_spin.rotateOnce ( '0 -540 0' );

		$snl2_pl1_spin_arm1.rotateOnce ( '0 0 180' );
		$snl2_pl1_spin_arm2.rotateOnce ( '0 0 180' );
		$snl2_pl1_spin_arm3.rotateOnce ( '0 0 180' );
		$snl2_pl1_spin_arm4.rotateOnce ( '0 0 180' );

		sys.waitFor ($snl2_pl1_spin_anc);

		$snl2_pl1.time (.5);
		$snl2_pl1.move ( DOWN, 192 );
		//pole1 move sound .5sec
		sys.trigger ($snail2_pole1_speaker);
		sys.waitFor ($snl2_pl1);
	}


	////////////////////////////////////////////////////
	//
	//	move snail 2 pole 2 things up
	//
	////////////////////////////////////////////////////
	void move_snail2_connect2_up()
	{
		$snl2_pl2.time (.5);
		$snl2_pl2.move ( UP, 208 );
		//pole2 move sound .5sec
		sys.trigger ($snail2_pole2_speaker);
		sys.waitFor ($snl2_pl2);

		$snl2_pl2_spin_anc.move ( UP, 160 );
		$snl2_pl2_spin.rotateOnce ( '0 540 0' );

		//pole2 guts moveup sound 1sec
		sys.trigger ($snail2_pole2guts_up_speaker);

		sys.wait (.5);
		$snl2_pl2_spin_arm1.rotateOnce ( '0 0 -180' );
		$snl2_pl2_spin_arm2.rotateOnce ( '0 0 -180' );
		$snl2_pl2_spin_arm3.rotateOnce ( '0 0 -180' );
		$snl2_pl2_spin_arm4.rotateOnce ( '0 0 -180' );

		sys.waitFor ($snl2_pl2_spin_arm4);
	}


	////////////////////////////////////////////////////
	//
	//	move snail 2 pole 2 things down
	//
	////////////////////////////////////////////////////
	void move_snail2_connect2_down()
	{
		//pole2 guts movedown sound 1sec
		sys.trigger ($snail2_pole2guts_down_speaker);

		$snl2_pl2_spin_anc.move ( DOWN, 160 );
		$snl2_pl2_spin.rotateOnce ( '0 -540 0' );

		$snl2_pl2_spin_arm1.rotateOnce ( '0 0 180' );
		$snl2_pl2_spin_arm2.rotateOnce ( '0 0 180' );
		$snl2_pl2_spin_arm3.rotateOnce ( '0 0 180' );
		$snl2_pl2_spin_arm4.rotateOnce ( '0 0 180' );

		sys.waitFor ($snl2_pl2_spin_anc);

		$snl2_pl2.time (.5);
		$snl2_pl2.move ( DOWN, 208 );
		//pole2 move sound .5sec
		sys.trigger ($snail2_pole2_speaker);
		sys.waitFor ($snl2_pl2);
	}


	////////////////////////////////////////////////////
	//
	//	open shells for snail 2 
	//
	////////////////////////////////////////////////////
	void open_snail2_shells()
	{
		$snl2_shell3.rotateOnce ( '0 0 -135' );

		sys.wait (.125);
		$snl2_shell2.rotateOnce ( '0 0 -90' );

		sys.wait (.125);
		$snl2_shell1.rotateOnce ( '0 0 -45' );
		
		sys.waitFor ($snl2_shell1);
		sys.waitFor ($snl2_shell2);
		sys.waitFor ($snl2_shell3);
	}


	////////////////////////////////////////////////////
	//
	//	close shells for snail 2 
	//
	////////////////////////////////////////////////////
	void close_snail2_shells()
	{
		$snl2_shell3.rotateOnce ( '0 0 135' );

		sys.wait (.125);
		$snl2_shell2.rotateOnce ( '0 0 90' );

		sys.wait (.125);
		$snl2_shell1.rotateOnce ( '0 0 45' );
		
		sys.waitFor ($snl2_shell1);
		sys.waitFor ($snl2_shell2);
		sys.waitFor ($snl2_shell3);
	}




	////////////////////////////////////////////////////
	//
	//	Snail machine 2 LOOP
	//
	////////////////////////////////////////////////////
	void go_snail2()
	{
		float thread3, thread4;

		while (1)
		{
			thread3 = thread open_snail2_shells ();
			//Shells opening sound 1sec
			sys.trigger ($snail2_shells_open_speaker);
			sys.waitForThread( thread3 );

			thread3 = thread move_snail2_connect1_up ();
			thread4 = thread move_snail2_connect2_up ();
			sys.waitForThread( thread3 );
			sys.waitForThread( thread4 );

			sys.wait(1);
			
			thread3 = thread move_snail2_connect1_down ();
			thread4 = thread move_snail2_connect2_down ();
			sys.waitForThread( thread3 );
			sys.waitForThread( thread4 );

			thread3 = thread close_snail2_shells ();
			//Shells closing sound 1sec
			sys.trigger ($snail2_shells_close_speaker);
			sys.waitForThread( thread3 );

			sys.wait(1);
		}
	}
	

	////////////////////////////////////////////////////
	//
	//	send msg
	//
	////////////////////////////////////////////////////
	void send_message ()
	{
		if (msg_state != 99)
			{
			sys.trigger ($obj2);
			sys.wait (2);

			sys.trigger ($obj3);
			sys.wait (2);

			sys.trigger ($obj4);
		
			}

			else
			{
			sys.trigger ($obj5);
			}

		msg_state = 99;
	}



	////////////////////////////////////////////////////
	//
	//	Fluctuate the lobby lights
	//
	////////////////////////////////////////////////////
	void lobbylights_flux ()
	{
		
	}


	void airlock_door1_close() {
		sys.trigger ($speaker_airlock_door1_close);
		$airlock_door1_left.rotateOnce ( '0 -45 0' );
		$airlock_door1_right.rotateOnce ( '0 45 0' );
		sys.waitFor ($airlock_door1_left);

		$airlock_door1_top_lock.move ( DOWN, 15 );
		sys.trigger ($speaker_airlock_door1_bottom_lock);
		$airlock_door1_bottom_lock.move ( UP, 15 );
		sys.waitFor ($airlock_door1_bottom_lock);

		sys.trigger ($speaker_airlock_door1_left_lock);
		$airlock_door1_left_lock.move ( SOUTH, 16 );
		sys.trigger ($speaker_airlock_door1_right_lock);
		$airlock_door1_right_lock.move ( SOUTH, 16 );
		sys.waitFor ($airlock_door1_right_lock);

	}

	////////////////////////////////////////////////////
	//
	//	Open airlock door1
	//
	////////////////////////////////////////////////////
	void airlock_door1_open()
	{
		//airlock door1 times
		$airlock_door1_left.time (1.2);
		$airlock_door1_right.time (1.2);
		$airlock_door1_left.accelTime (.2);
		$airlock_door1_left.decelTime (1);
		$airlock_door1_right.accelTime (.2);
		$airlock_door1_right.decelTime (1);

		$airlock_door1_top_lock.time (.25);
		$airlock_door1_bottom_lock.time (.25);
		
		$airlock_door1_left_lock.time (.75);
		$airlock_door1_right_lock.time (.75);
		$airlock_door1_left_lock.accelTime (.1);
		$airlock_door1_left_lock.decelTime (.65);
		$airlock_door1_right_lock.accelTime (.1);
		$airlock_door1_right_lock.decelTime (.65);

		//turn door1 and door2 light on 
		//turn door2 light on
		thread crossFadeEnt ($door2_light, '0.37 0.05 0.01', '.84 .84 .9', 1);
			
		sys.wait(1);

		//move the 4 locks to unlock position
		$airlock_door1_top_lock.move ( UP, 15 );
		sys.trigger ($speaker_airlock_door1_bottom_lock);
		$airlock_door1_bottom_lock.move ( DOWN, 15 );
		sys.waitFor ($airlock_door1_bottom_lock);

		sys.trigger ($speaker_airlock_door1_left_lock);
		$airlock_door1_left_lock.move ( NORTH, -16 );
		sys.trigger ($speaker_airlock_door1_right_lock);
		$airlock_door1_right_lock.move ( NORTH, -16 );
		sys.waitFor ($airlock_door1_right_lock);

		//open doors
		sys.trigger ($speaker_airlock_door1_open);
		$airlock_door1_left.rotateOnce ( '0 45 0' );
		$airlock_door1_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		//sys.trigger ($airlock_door1_portal);

		sys.waitFor ($airlock_door1_right);
		sys.waitFor ($airlock_door1_left);
	}


	////////////////////////////////////////////////////
	//
	//	rb_tube loop
	//
	////////////////////////////////////////////////////
	void rb_tube_loop()
	{
		while (1){
			thread crossFadeEnt ($rb_tube_1_light, '.38 .86 .82', '.85 0 0', 2);
			thread crossFadeEnt ($rb_tube_1, '.38 .86 .82', '.85 0 0', 2);
			thread crossFadeEnt ($rb_tube_2_light, '.38 .86 .82', '.85 0 0', 2);
			thread crossFadeEnt ($rb_tube_2, '.38 .86 .82', '.85 0 0', 2);

			sys.wait (3);

			thread crossFadeEnt ($rb_tube_1_light, '.85 0 0', '.38 .86 .82', 2);
			thread crossFadeEnt ($rb_tube_1, '.85 0 0', '.38 .86 .82', 2);
			thread crossFadeEnt ($rb_tube_2_light, '.85 0 0', '.38 .86 .82', 2);
			thread crossFadeEnt ($rb_tube_2, '.85 0 0', '.38 .86 .82', 2);

			sys.wait (3);
		}
	}



	////////////////////////////////////////////////////
	//
	//	senpist loops
	//
	////////////////////////////////////////////////////
	void senpist1_loop()
	{
		
	
		while (1){
			$poopist1.time (1.5);
			
			thread mover_startsound3 ($poopist1);
			
			$poopist1.move (DOWN, 48);
			sys.waitFor ($poopist1);
			
			mover_stopsound2 ($poopist1);

			$poopist1.time (0.5);
			
			thread mover_startsound3 ($poopist1);
			
			$poopist1.move (UP, 48);
			sys.waitFor ($poopist1);
			
			mover_stopsound3 ($poopist1);
		}
	}

	void senpist2_loop()
	{
		while (1){
			$peepist.time (1);
			
			thread mover_startsound ($peepist);
			$peepist.move (DOWN, 48);
			sys.waitFor ($peepist);
			mover_stopsound ($peepist);
			
			$peepist.time (1.5);
			
			thread mover_startsound ($peepist);
			$peepist.move (UP, 48);
			sys.waitFor ($peepist);
			mover_stopsound ($peepist);
		}
	}

	void senpist3_loop()
	{
		
	
		while (1){
			
			$senpist3.time (1.5);	
			thread mover_startsound ($senpist3);
			
			$senpist3.move (DOWN, 48);
			sys.waitFor ($senpist3);
			
			mover_stopsound2 ($senpist3);

			$senpist3.time (1);
			
			thread mover_startsound2 ($senpist3);
			
			$senpist3.move (UP, 48);
			sys.waitFor ($senpist3);
			
			mover_stopsound ($senpist3);
		}
	}



	////////////////////////////////////////////////////
	//
	//	floor2 break
	//
	////////////////////////////////////////////////////
	void floor2_break()
	{
		$prebreak_main.hide();
		$prebreak_light1.hide();

		$postbreak_spark.show();
		$postbreak_main.show();
		$postbreak_light1.show();
		$postbreak_clip.show();
	}


	////////////////////////////////////////////////////
	//
	//	Corpse Move - quick move of deadbody 
	//
	////////////////////////////////////////////////////
	void corpse_move()
	{
		$corpse_mover.time (.5);
		$corpse_mover.accelTime (.5);
		$corpse_mover.decelTime (0);

		$corpse_mover.move ( UP, 96 );
		sys.waitFor ($corpse_mover);

		$corpse.unbind();
	}

	////////////////////////////////////////////////////
	//
	//	Corpse Move - quick move of deadbody 
	//
	////////////////////////////////////////////////////
	void corpse_move2()
	{
		$corpse_mover2.time (.8);
		$corpse_mover2.accelTime (.8);
		$corpse_mover2.decelTime (0);

		$corpse_mover2.moveTo ( $corpse_mover2_movepoint );
		sys.waitFor ($corpse_mover2);

		$light_5352.fadeOutLight(1.2);

		$corpse2.unbind();
	}


	////////////////////////////////////////////////////
	//
	//	make sure the secret panel is open on way back through
	//
	////////////////////////////////////////////////////
	void open_secretpanel()
	{
		$skyway_secret_panel.open();
	}


	////////////////////////////////////////////////////
	//
	//	door bang
	//
	////////////////////////////////////////////////////
	void door_bang ()
	{
		$helldoor1_mover.time (.2);
		$helldoor2_mover.time (.2);

		$helldoor1_mover.rotateOnce ( '0 2.5 0');
		$helldoor2_mover.rotateOnce ( '0 -2 0');
		sys.waitFor ($helldoor1_mover);

		//trigger speaker
		sys.trigger ($helldoor_speaker);
		sys.trigger ($door_bang_influence);

		$helldoor1_mover.rotateOnce ( '0 -2.5 0');
		$helldoor2_mover.rotateOnce ( '0 2 0');
		sys.waitFor ($helldoor1_mover);

		//Again
		sys.wait (.5);

		$helldoor1_mover.rotateOnce ( '0 2.5 0');
		$helldoor2_mover.rotateOnce ( '0 -2 0');
		sys.waitFor ($helldoor1_mover);

		//trigger speaker
		sys.trigger ($helldoor_speaker);
		sys.trigger ($door_bang_influence);

		$helldoor1_mover.rotateOnce ( '0 -2.5 0');
		$helldoor2_mover.rotateOnce ( '0 2 0');
		sys.waitFor ($helldoor1_mover);

		//And again
		sys.wait (.2);

		$helldoor1_mover.rotateOnce ( '0 2.5 0');
		$helldoor2_mover.rotateOnce ( '0 -2 0');
		sys.waitFor ($helldoor1_mover);

		//trigger speaker
		sys.trigger ( $helldoor_speaker );
		sys.trigger ( $door_bang_influence );

		$helldoor1_mover.rotateOnce ( '0 -2.5 0');
		$helldoor2_mover.rotateOnce ( '0 2 0');
		sys.waitFor ($helldoor1_mover);

		//trigger zsec shield guy
		sys.trigger ( $monster_zsec_shield_4 );
	}


	////////////////////////////////////////////////////
	//
	//	machine fall over
	//
	////////////////////////////////////////////////////
	void machine_fall ()
	{
		$machine_fall_mover.time (.8);
		$machine_fall_mover.accelTime (.8);
		$machine_fall_mover.decelTime (0);

		//trigger sound for falling
		sys.trigger ( $speaker_machine_fall_attention );
		//machine falls
		$machine_fall_mover.rotateOnce ( '-90 -15 0' );
		sys.waitFor ( $machine_fall_mover );

		//trigger sound
		sys.trigger ( $speaker_machine_fall );

		//trigger particles

		//wait then trigger sound
		sys.wait (.5);
		sys.trigger ($speaker_machine_fall_creepy);
		sys.trigger ($target_setinfluence_16);
		sys.wait (.5);

		//call corpse mover
		map_comm1::corpse_move2();

	}


	void close_swanncampdoor ()
	{
		$func_door_1670.open ();
	}



	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void main ()
	{

		thread cache_sounds();

		thread rb_tube_loop();
		setup_objects ();
		thread oval_movement ();
					
		sys.wait (2);
		thread move_hallpipes ();
		thread go_snail2 ();
		thread senpist1_loop ();
		thread senpist2_loop ();
		thread senpist3_loop ();
	}
}

//@doomscript-blueprint begin 6
//@source 7CE40305
//@catalog 0C260740
//@node F466D044-0 40 40
//@node 4B63AAC8-0 330 40
//@node 3FC7A4DE-0 40 40
//@node CFDF7FE8-0 330 40
//@node 314B301A-0 610 40
//@node 33DA29C2-0 40 40
//@node 288C79D3-0 330 40
//@node 53489F84-0 40 40
//@node 5F309A0F-0 330 40
//@node C6C057A4-0 610 40
//@node 34DA2B55-0 40 40
//@node 7649E7E3-0 330 40
//@node 5448A117-0 40 40
//@node 125C1897-0 330 40
//@node 8822AC39-0 610 40
//@node 7AEA71C1-0 40 40
//@node AE4CE310-0 330 40
//@node 57127680-0 610 40
//@node 9EB488A7-0 890 40
//@node 6C7B7CF0-0 1170 40
//@node 13B7C256-0 1450 40
//@node 56487064-0 1730 40
//@node B9649CB7-0 2010 40
//@node 6D751631-0 2290 40
//@node FC5C881C-0 2570 40
//@node B9BB4C2B-0 2850 40
//@node 661C5F54-0 3130 40
//@node CB610E39-0 3410 40
//@node 45CCC9B2-0 3690 40
//@node E28A94A5-0 3970 40
//@node 8597F953-0 4250 40
//@node BC02C33F-0 4530 40
//@node 7DF5582D-0 4810 40
//@node 6E77140D-0 5090 40
//@node 4FE1062C-0 5370 40
//@node DD8757F7-0 5650 40
//@node 78A2E9B2-0 5930 40
//@node F9C10C35-0 6210 40
//@node 96B65D50-0 6490 40
//@node D0B042DB-0 6770 40
//@node 43A64026-0 7050 40
//@node 2513E771-0 7330 40
//@node 501130C3-0 7610 40
//@node 1B3D8A72-0 7890 40
//@node AEF7368D-0 8170 40
//@node 79E4EE64-0 8450 40
//@node 0260EE77-0 8730 40
//@node AED6FAF7-0 9010 40
//@node D63D10D0-0 9290 40
//@node BDF44E71-0 9570 40
//@node 829EB453-0 9850 40
//@node 8CF20953-0 10130 40
//@node C7E2DDF7-0 10410 40
//@node 5BA865EB-0 10690 40
//@node 59F3FBA8-0 10970 40
//@node 534D9A9B-0 11250 40
//@node E0FACDA6-0 11530 40
//@node 93A6E2A1-0 11810 40
//@node 0188AC78-0 12090 40
//@node 79A4786B-0 12370 40
//@node 3CD36D76-0 12650 40
//@node AEB21631-0 12930 40
//@node 0C30676C-0 13210 40
//@node 43A39FCD-0 13490 40
//@node C88821B2-0 13770 40
//@node B4253D4B-0 14050 40
//@node BE8CFAF0-0 14330 40
//@node 9EE1EA2B-0 14610 40
//@node 86416931-0 14890 40
//@node ACA189BA-0 15170 40
//@node 5866ECC2-0 15450 40
//@node 3A830D91-0 15730 40
//@node B1D88E79-0 16010 40
//@node 0E81E2D5-0 16290 40
//@node 7058CE00-0 16570 40
//@node D542C1CB-0 16850 40
//@node F8188D8E-0 17130 40
//@node 92FC6B61-0 17410 40
//@node 5440C7BC-0 17690 40
//@node D0582E72-0 17970 40
//@node 91536D53-0 18250 40
//@node B4E9FD6D-0 18530 40
//@node F3840E76-0 18810 40
//@node BFEE98BF-0 18585 145
//@node 53AEEED4-0 19090 40
//@node 0243F799-0 18885 140
//@node D2C3836A-0 18680 140
//@node 29D249CB-0 19370 40
//@node A3C23B02-0 19145 145
//@node E78D8AFB-0 19650 40
//@node 77728EB1-0 19445 140
//@node 0DDA869A-0 19930 40
//@node 168DDDA1-0 20210 40
//@node DD0EEF73-0 19985 145
//@node 06A1C936-0 20490 40
//@node 1D3F5B5F-0 20285 140
//@node DFB5BF4A-0 20080 140
//@node 4F5C4A72-0 20770 40
//@node 468B8E8B-0 20545 145
//@node 0D05D06C-0 21050 40
//@node 824DC14A-0 20845 140
//@node 5CC6DF25-0 21330 40
//@node FA58BF64-0 21610 40
//@node A12D2148-0 21385 145
//@node F206C07C-0 21890 40
//@node 6671A3E4-0 21685 140
//@node 5455E08F-0 21480 140
//@node 4525A1C5-0 22170 40
//@node 46FDF5B3-0 21945 145
//@node 35DEDEAD-0 22450 40
//@node 8BA7EB13-0 22245 140
//@node D831C504-0 22730 40
//@node C179F4A7-0 23010 40
//@node F13D0DB8-0 22785 145
//@node 045002F2-0 23290 40
//@node 0F1CA927-0 23085 140
//@node 527C9F36-0 22880 140
//@node 93B99854-0 23570 40
//@node 28FC070A-0 23345 145
//@node 655E8F6E-0 23850 40
//@node B9F3892E-0 23645 140
//@node DBBA7497-0 24130 40
//@node 584FB87A-0 24410 40
//@node F156592B-0 24185 145
//@node BE3A1494-0 24690 40
//@node E7DCED1C-0 24485 140
//@node 07D5DE73-0 24280 140
//@node 1BC0F99F-0 24970 40
//@node FE0FD895-0 24745 145
//@node 50CD2CA7-0 25250 40
//@node 3F1C4C73-0 25045 140
//@node E69F0A7E-0 25530 40
//@node 0F9DBB15-0 25810 40
//@node EC6E1EEB-0 25585 145
//@node F7FE5C46-0 26090 40
//@node A1E7BA02-0 25885 140
//@node 068F8D8B-0 25680 140
//@node F1AFB276-0 26370 40
//@node E8D67868-0 26145 145
//@node 718647B8-0 26650 40
//@node 2AB4C9B7-0 26445 140
//@node 2141F169-0 26930 40
//@node 579A5D27-0 40 40
//@node 777A0A28-0 610 40
//@node F1C3B1D8-0 890 40
//@node 25404318-0 1170 40
//@node 96FBE865-0 1450 40
//@node CB0C98AB-0 1730 40
//@node D500D8B1-0 2010 40
//@node 5EEE028B-0 2290 40
//@node E8DAE9C6-0 2290 40
//@node C4C02B3F-0 2085 145
//@node E0825474-0 2570 40
//@node 5E00BEF7-0 2365 145
//@node 78B4A248-0 3130 40
//@node 1A7FD3A8-0 2645 145
//@node DCC820D1-0 3410 200
//@node 697C0C81-0 2925 305
//@node 1072980F-0 2720 305
//@node AD6B77B5-0 2720 389
//@node 4BA290CF-0 3410 360
//@node 9DCBDB99-0 3205 465
//@node 83374A88-0 3970 360
//@node 843102BF-0 3485 465
//@node 48A338CA-0 3280 465
//@node E8DAE9C6-1 3970 520
//@node 41578E44-0 3765 625
//@node 32098CF0-0 4530 360
//@node 8C814EC3-0 4045 465
//@node A7381525-0 3840 465
//@node 68D36481-0 4530 520
//@node 1E101269-0 4325 625
//@node 3F2A28BD-0 5090 360
//@node D9294CC9-0 4605 465
//@node 9BB146B6-0 4400 465
//@node 68D5A318-0 5090 520
//@node 11C80F68-0 4885 625
//@node 68E26F0B-0 5650 520
//@node 354EE2E6-0 5445 625
//@node 9B28E5C2-0 5930 200
//@node AE7F10E5-0 5725 305
//@node DD7274C8-0 5520 305
//@node C4C7C3A6-0 5520 389
//@node 550BBC1E-0 6490 200
//@node DF27AD84-0 6005 392
//@node 3EFAE44E-0 6770 200
//@node E089DA03-0 7050 200
//@node A7F87BFA-0 7050 200
//@node D5F6BDB8-0 6845 305
//@node B832CE32-0 40 40
//@node 72954FBC-0 330 40
//@node 93661762-0 610 40
//@node D701E55D-0 890 40
//@node 4A502E3B-0 1170 40
//@node 2F20A2E6-0 1450 40
//@node 056F2974-0 1730 40
//@node 1E8D027F-0 2010 40
//@node 6476496F-0 2290 40
//@node EB3D7D91-0 2570 40
//@node 9333B278-0 2850 40
//@node 456AC1E5-0 3130 40
//@node F53BB005-0 3410 40
//@node C66B6FD8-0 3690 40
//@node 202B5188-0 3970 40
//@node 38D8A749-0 40 40
//@node BB1526BC-0 330 40
//@node 73F95A00-0 610 40
//@node 8F7D4E40-0 890 40
//@node 0B23D2C1-0 1170 40
//@node 56B42928-0 1450 40
//@node D60521C1-0 1730 40
//@node F799643D-0 2010 40
//@node 5F48FF40-0 2290 40
//@node 7D006345-0 2570 40
//@node 472914DB-0 2850 40
//@node 7540C34C-0 3130 40
//@node 20990475-0 40 40
//@node 19BF3BD9-0 330 40
//@node 9357AF30-0 610 40
//@node 52FF28E3-0 890 40
//@node 7B8044E9-0 1170 40
//@node F5ADDF5A-0 1450 40
//@node 78584305-0 1730 40
//@node 013A46FE-0 2010 40
//@node 4AA365AB-0 2290 40
//@node F2ED40B0-0 2570 40
//@node F5ADDF5A-1 2850 40
//@node A8D943BC-0 3130 40
//@node F18356C3-0 3410 40
//@node 28E180A6-0 3690 40
//@node 13224F4F-0 3970 40
//@node E502E08C-0 4250 40
//@node 8C12643D-0 4530 40
//@node 55F936DE-0 4810 40
//@node E502E08C-1 5090 40
//@node 78584305-1 5370 40
//@node B941F374-0 5650 40
//@node 827BF165-0 5930 40
//@node 6FBF5B18-0 6210 40
//@node E502E08C-2 6490 40
//@node 06AF3765-0 6770 40
//@node CC27BDDF-0 7050 40
//@node 3C7DD683-0 40 40
//@node 755E3424-0 330 40
//@node 65FFDF67-0 125 145
//@node 53D9158D-0 610 200
//@node 6B438DCF-0 890 200
//@node C6D77DEC-0 665 305
//@node 4EEE7227-0 1170 200
//@node C2BDCB65-0 965 305
//@node 4E06FE57-0 760 305
//@node 3587EEAF-0 1450 360
//@node 99E9739E-0 1730 360
//@node 827F1CC7-0 2010 360
//@node B14F9C7D-0 1805 465
//@node FC65FA57-0 2290 360
//@node 27F55FBB-0 2570 360
//@node 34E4488E-0 2850 360
//@node 7BE552D7-0 2625 465
//@node 09E438AA-0 3130 360
//@node 2C6001E4-0 2925 460
//@node 6BF34411-0 2720 460
//@node 51470062-0 3410 360
//@node 03CC7B4C-0 3185 465
//@node 2EB01301-0 3690 360
//@node 995C900A-0 3485 460
//@node B14A0500-0 3970 360
//@node D5443C9B-0 4250 360
//@node 15B7F05F-0 4530 360
//@node 90AC3D46-0 4325 460
//@node BE368A66-0 4810 360
//@node 2C6D668B-0 5090 360
//@node 1475FC81-0 4885 460
//@node 9EE2E3A0-0 5370 360
//@node B95F7F34-0 5650 360
//@node 9E4BD03B-0 5930 360
//@node 15B7F05F-1 6210 360
//@node B1142D35-0 6005 460
//@node 1CA2502D-0 6490 360
//@node 2F7B2ECD-0 6770 360
//@node CA102A40-0 7050 360
//@node D821A711-0 7330 360
//@node BFE40EF5-0 7610 360
//@node CAEACEE1-0 7405 460
//@node 1CA2502D-1 7890 360
//@node C6E7CEFD-0 8170 360
//@node C773596C-0 8450 360
//@node 49D71872-0 8730 360
//@node BFE40EF5-1 9010 360
//@node BFCCD7D2-0 8805 460
//@node 8CF0CC1B-0 9290 360
//@node FADB43CD-0 9570 200
//@node 89282F0A-0 9365 305
//@node B8FA3DAD-0 9160 305
//@node 21D4CD52-0 9850 360
//@node 99E9739E-1 10130 360
//@node FA7C0818-0 10410 360
//@node 6412111F-0 10205 465
//@node E9F00D7A-0 10690 360
//@node 27F55FBB-1 10970 360
//@node A4D8AEB9-0 11250 360
//@node 9605ED24-0 11025 465
//@node DC84A634-0 11530 360
//@node D1056715-0 11325 460
//@node DB64691E-0 11120 460
//@node AFF6FD7B-0 11810 360
//@node 22DB59AB-0 11585 465
//@node 90C76CB6-0 12090 360
//@node 43A83A76-0 11885 460
//@node 1749507F-0 12370 360
//@node 9EA10161-0 12650 360
//@node 5F10FC38-0 12930 360
//@node 4D45FB51-0 12725 460
//@node BE368A66-1 13210 360
//@node 34EA46DF-0 13490 360
//@node 4DE1270E-0 13285 460
//@node 1662A597-0 13770 360
//@node 03F222F7-0 14050 360
//@node 6C0E6962-0 14330 360
//@node 5F10FC38-1 14610 360
//@node D2C5D4C2-0 14405 460
//@node A33F35CE-0 14890 360
//@node 10BBBB7C-0 15170 360
//@node 4EEF5029-0 15450 360
//@node 31925C12-0 15730 360
//@node F95D04F4-0 16010 360
//@node FBF8F101-0 15805 460
//@node A33F35CE-1 16290 360
//@node 265692F0-0 16570 360
//@node 4EAA65F9-0 16850 360
//@node A59A996F-0 17130 360
//@node F95D04F4-1 17410 360
//@node 7946FB72-0 17205 460
//@node B1D7346C-0 17690 360
//@node E723A542-0 17970 200
//@node A7D2E4AF-0 17765 305
//@node D99EA76B-0 17560 305
//@node 868E9CD1-0 18250 360
//@node 99E9739E-2 18530 360
//@node FA79C981-0 18810 360
//@node 01D1A4AC-0 18605 465
//@node CE5AF499-0 19090 360
//@node 27F55FBB-2 19370 360
//@node E12CE47C-0 19650 360
//@node D3935D74-0 19425 465
//@node 3971EE22-0 19930 360
//@node 68765037-0 19725 460
//@node 20C59A76-0 19520 460
//@node 22174038-0 20210 360
//@node D7340258-0 19985 465
//@node 9585A80F-0 20490 360
//@node 6497CAB4-0 20285 460
//@node 839D42C2-0 20770 360
//@node 1C1107E3-0 21050 360
//@node 60517269-0 21330 360
//@node 502D459C-0 21125 460
//@node BE368A66-2 21610 360
//@node CB4CB9CF-0 21890 360
//@node 607E49C4-0 21685 460
//@node 8EB6A3AE-0 22170 360
//@node A0B96586-0 22450 360
//@node 28E9ED39-0 22730 360
//@node 60517269-1 23010 360
//@node 4C54F36B-0 22805 460
//@node C3D974EF-0 23290 360
//@node 35DE2BA7-0 23570 360
//@node 2B0ED37A-0 23850 360
//@node E0B72313-0 24130 360
//@node 5DA01323-0 24410 360
//@node 7C40AE6F-0 24205 460
//@node C3D974EF-1 24690 360
//@node D250799B-0 24970 360
//@node 2A2BFF92-0 25250 360
//@node F1DBF670-0 25530 360
//@node 5DA01323-1 25810 360
//@node BC9CC580-0 25605 460
//@node CEDC16F1-0 26090 360
//@node 40D4DA8B-0 26370 200
//@node 7B64ACC0-0 26165 305
//@node 65069431-0 25960 305
//@node 7C18BC8C-0 26650 360
//@node 99E9739E-3 26930 360
//@node 028B1F3A-0 27210 360
//@node 4D8AA180-0 27005 465
//@node 43467A14-0 27490 360
//@node 27F55FBB-3 27770 360
//@node 0D4E9A1F-0 28050 360
//@node 8728BA6C-0 27825 465
//@node E9A6BFB0-0 28330 360
//@node 2F0A5159-0 28125 460
//@node 3BDD3DBE-0 27920 460
//@node 78E12161-0 28610 360
//@node B0886A02-0 28385 465
//@node 15CDA8F4-0 28890 360
//@node CE2959E4-0 28685 460
//@node 42405639-0 29170 360
//@node D5D067A5-0 29450 360
//@node C4B9172A-0 29730 360
//@node 4A64508E-0 29525 460
//@node BE368A66-3 30010 360
//@node 050F9D83-0 30290 360
//@node A4AB9260-0 30085 460
//@node 9B31D58D-0 30570 360
//@node FDC597B9-0 30850 360
//@node 3F737538-0 31130 360
//@node C4B9172A-1 31410 360
//@node B10F8B7D-0 31205 460
//@node 9F85C0A8-0 31690 360
//@node 08735A36-0 31970 360
//@node C688AC3B-0 32250 360
//@node 9C7046B4-0 32530 360
//@node 9EC963DA-0 32810 360
//@node D9CB5EBF-0 32605 460
//@node 9F85C0A8-1 33090 360
//@node 572606AE-0 33370 360
//@node D07BD7C7-0 33650 360
//@node E72C72A5-0 33930 360
//@node 9EC963DA-1 34210 360
//@node E1663878-0 34005 460
//@node 907926B2-0 34490 360
//@node 2DBB0CC0-0 34770 200
//@node 5CD1EFF0-0 34565 305
//@node 90D63802-0 34360 305
//@node E0FB2E7B-0 35050 360
//@node 99E9739E-4 35330 360
//@node FA88D40B-0 35610 360
//@node 40EF8C97-0 35405 465
//@node A8C6BCC3-0 35890 360
//@node 27F55FBB-4 36170 360
//@node 80DA6752-0 36450 360
//@node 521C56C5-0 36225 465
//@node 8437088A-0 36730 360
//@node 9AFA4DAA-0 36525 460
//@node 631B21D7-0 36320 460
//@node 2DC237FE-0 37010 360
//@node 029E64CF-0 36785 465
//@node CA7D0D75-0 37290 360
//@node C7BB4A95-0 37085 460
//@node 6ADA9AEC-0 37570 360
//@node F49A1513-0 37850 360
//@node F707B943-0 38130 360
//@node D002F120-0 37925 460
//@node BE368A66-4 38410 360
//@node 0C5BDF33-0 38690 360
//@node D485F314-0 38485 460
//@node B18D23EC-0 38970 360
//@node 471B9840-0 39250 360
//@node DAE9E60F-0 39530 360
//@node F707B943-1 39810 360
//@node 06615E2F-0 39605 460
//@node CD484EB9-0 40090 360
//@node 1ABB2CF1-0 40370 360
//@node 1E746D94-0 40650 360
//@node 766A345D-0 40930 360
//@node 0470B5F9-0 41210 360
//@node 05848549-0 41005 460
//@node CD484EB9-1 41490 360
//@node C986D911-0 41770 360
//@node 36438AC0-0 42050 360
//@node EEB58CFE-0 42330 360
//@node 0470B5F9-1 42610 360
//@node 4DE0A8F2-0 42405 460
//@node 09930607-0 42890 360
//@node 4D6FE60E-0 43450 360
//@node 99E9739E-5 43730 360
//@node 8285D88C-0 44010 360
//@node A3D72969-0 43805 465
//@node 158B2636-0 44290 360
//@node 27F55FBB-5 44570 360
//@node AF7EDACD-0 44850 360
//@node 72FE2DD1-0 44625 465
//@node 8C97142C-0 45130 360
//@node 6A2FE60B-0 44925 460
//@node 1910BEE4-0 44720 460
//@node 0E50AF37-0 45410 360
//@node 2B92E2E0-0 45185 465
//@node 1721219A-0 45690 360
//@node 336F3708-0 45485 460
//@node 0C8D62DB-0 45970 360
//@node 1E68BCF1-0 46250 360
//@node 16B3420C-0 46530 360
//@node 5DBD528C-0 46325 460
//@node BE368A66-5 46810 360
//@node 74F1524F-0 47090 360
//@node D40F4CCC-0 46885 460
//@node FA038A83-0 47370 360
//@node 05F6BDA3-0 47650 360
//@node 37D44E06-0 47930 360
//@node 16B3420C-1 48210 360
//@node 8633E0AB-0 48005 460
//@node D658FAFA-0 48490 360
//@node 69621A20-0 48770 360
//@node 1120ADAD-0 49050 360
//@node 9D87D28E-0 49330 360
//@node 3D99FA18-0 49610 360
//@node 4187200E-0 49405 460
//@node D658FAFA-1 49890 360
//@node A5FA36F4-0 50170 360
//@node A86A9D9D-0 50450 360
//@node D8E7027B-0 50730 360
//@node 3D99FA18-1 51010 360
//@node F8810455-0 50805 460
//@node 33B13648-0 51290 360
//@node F249CF14-0 40 40
//@node E27F0001-0 330 40
//@node F1F28945-0 610 40
//@node 0B0F3C7A-0 890 40
//@node 24D92C38-0 1170 40
//@node B03A79E0-0 1450 40
//@node BF437A35-0 1730 40
//@node D5E02839-0 2010 40
//@node A45E71AB-0 2290 40
//@node 34CD448E-0 2570 40
//@node 837B0C51-0 2850 40
//@node BB00ED18-0 3130 40
//@node E1F08023-0 3410 40
//@node ABA7AD30-0 3690 40
//@node 5B61E9A1-0 40 40
//@node 72C22279-0 330 40
//@node 275DBDEA-0 610 40
//@node 57A5B81F-0 890 40
//@node 4AB6C56C-0 1170 40
//@node 050B1699-0 1450 40
//@node 33360B7E-0 1730 40
//@node C1633C73-0 2010 40
//@node 49C8E9EB-0 2290 40
//@node 946048D6-0 2570 40
//@node 984C65BD-0 2850 40
//@node E06112B9-0 3130 40
//@node 7A5642DB-0 3410 40
//@node 9AC79DCB-0 40 40
//@node 8F2AE3A3-0 330 40
//@node E1185F71-0 610 40
//@node 22C503DA-0 890 40
//@node DC03BF70-0 1170 40
//@node 0DFF4208-0 1450 40
//@node 63FED7A3-0 1730 40
//@node 57ADC4D9-0 2010 40
//@node 6278D902-0 2290 40
//@node FD01857C-0 2570 40
//@node D7E382B3-0 2850 40
//@node AFC05CA2-0 3130 40
//@node 7024B0A1-0 3410 40
//@node DA39CA58-0 3690 40
//@node 0B7BFFDE-0 40 40
//@node F4B2D631-0 330 40
//@node 6FB1521A-0 610 40
//@node 982A35C9-0 890 40
//@node 37965846-0 1170 40
//@node 0A2127EF-0 1450 40
//@node 275C3FB4-0 1730 40
//@node 1B99A1ED-0 2010 40
//@node E807101B-0 2290 40
//@node 8475B2A8-0 2570 40
//@node 19049CCD-0 2850 40
//@node 1C81A151-0 3130 40
//@node 5546002B-0 3410 40
//@node 75B4211B-0 40 40
//@node 847C2438-0 330 40
//@node E872E3C3-0 610 40
//@node 377DCCA9-0 890 40
//@node E872E3C3-1 1170 40
//@node 0B92B10E-0 1450 40
//@node 62A1A9E7-0 1730 40
//@node CF8D22CA-0 2010 40
//@node B5353E69-0 2290 40
//@node C1BB9351-0 40 40
//@node 78C783B5-0 330 40
//@node BA4C62D9-0 610 40
//@node 7B560A8C-0 890 40
//@node BA4C62D9-1 1170 40
//@node 62DB9411-0 1450 40
//@node BBEE98D9-0 1730 40
//@node F517DCF8-0 2010 40
//@node E9F99E97-0 2290 40
//@node 4F09C5D5-0 40 40
//@node AED8E87A-0 610 40
//@node FF049877-0 125 145
//@node 678109F6-0 610 200
//@node 59BBF178-0 385 305
//@node 5B44D610-0 1170 200
//@node 6DF1B59B-0 1450 200
//@node C792C991-0 965 300
//@node C769AFAF-0 1450 200
//@node 771A31B1-0 1225 305
//@node 9C378973-0 1730 200
//@node 47D9D24A-0 1505 305
//@node 6DF1B59B-1 2290 200
//@node 10860366-0 1805 300
//@node D6E87B30-0 2570 200
//@node 54E57C68-0 2085 300
//@node ED53F2A2-0 2850 200
//@node 6433EB1A-0 2850 200
//@node 64B99086-0 2625 305
//@node 292A9706-0 3130 200
//@node 81E7434E-0 2905 305
//@node 6DF1B59B-2 3690 200
//@node 531293D3-0 3205 300
//@node D6E87B30-1 3970 200
//@node 4503A1E3-0 3485 300
//@node FE6471B2-0 3970 200
//@node D5ADD598-0 3745 305
//@node C60E06F4-0 4530 200
//@node 6DF1B59B-3 4810 200
//@node 0D20FA18-0 4325 300
//@node ED53F2A2-1 5090 200
//@node C1D4DD0F-0 40 40
//@node 394EADE6-0 330 40
//@node C7B49DAE-0 125 145
//@node 5FCE5EBD-0 -80 145
//@node DD31FD6F-0 610 200
//@node 6BC7D4A7-0 890 200
//@node E8503BD0-0 1170 200
//@node 6BC7D4A7-1 1450 200
//@node 6A9A50AD-0 1730 200
//@node F519F4CE-0 2290 200
//@node 55AFFF2D-0 2570 40
//@node D0BFBC6E-0 2365 145
//@node 76D2E4E0-0 40 40
//@node B0DB1383-0 40 40
//@node B46BADA4-0 330 40
//@node EAA535B8-0 610 40
//@node 1956E3C2-0 890 40
//@node C157228B-0 1170 40
//@node 4B39C57F-0 1450 40
//@node 57371957-0 1730 40
//@node 3AD7FC8A-0 2010 40
//@node D92F302D-0 2290 40
//@node 6C946CBD-0 2570 40
//@node 65D48069-0 2850 40
//@node B7150F00-0 3130 40
//@node E90BDC4E-0 3410 40
//@node 7B8230F6-0 3690 40
//@node DBB764A9-0 40 40
//@node E7C5ABAC-0 330 40
//@node D770F22D-0 610 40
//@node A3E0AA41-0 890 40
//@node C19212AB-0 1170 40
//@node 67D2A034-0 1450 40
//@node 000DA0C0-0 1730 40
//@node 804A7312-0 2010 40
//@node 1FF03F10-0 2290 40
//@node C6998E23-0 2570 40
//@node 9E7AD77C-0 2850 40
//@node 88E2DC32-0 3130 40
//@node A83F0F31-0 3410 40
//@node C6D7659D-0 3690 40
//@node F89F01E4-0 3970 40
//@node 6DF73773-0 4250 40
//@node 2F746B26-0 4530 40
//@node 85F0C27E-0 4810 40
//@node 44901E9D-0 5090 40
//@node 96F1A5EB-0 5370 40
//@node 0B0E14C3-0 5650 40
//@node 52E19AE3-0 5930 40
//@node 0668A2AC-0 6210 40
//@node 41EABFC6-0 6490 40
//@node 8A871FD5-0 6770 40
//@node 067D75EC-0 7050 40
//@node D8BE1FF6-0 7330 40
//@node E47AA09F-0 7610 40
//@node A17BF86B-0 7890 40
//@node C957BD5A-0 8170 40
//@node 91C4549D-0 8450 40
//@node C0FBC2D7-0 40 40
//@node 42988EC8-0 330 40
//@node 477BC0D3-0 125 145
//@node 7FDBCDFA-0 610 200
//@node 404B74D7-0 890 200
//@node 25E3B545-0 1170 200
//@node 45D9B254-0 1450 200
//@node 4229C294-0 1730 200
//@node D9626B6A-0 2010 200
//@node BC6348D3-0 2290 200
//@node 63D0AE91-0 2570 200
//@node 42EF980C-0 2850 200
//@node 4229C294-1 3130 200
//@node 20042D03-0 40 40
//@node CD8A65A4-0 330 40
//@node E0FBBA3A-0 125 145
//@node 49605E93-0 610 200
//@node D647CC5A-0 890 200
//@node 74E8B477-0 1170 200
//@node 9345E023-0 1450 200
//@node DC19938B-0 1730 200
//@node FE059FF0-0 2010 200
//@node D647CC5A-1 2290 200
//@node FC189426-0 2570 200
//@node 9345E023-1 2850 200
//@node 8F91EF0E-0 3130 200
//@node 84132090-0 40 40
//@node AA666D9B-0 330 40
//@node 2C844FC4-0 125 145
//@node B8D4E74A-0 610 200
//@node 462402E1-0 890 200
//@node 8BF1051F-0 1170 200
//@node BBF1F41F-0 1450 200
//@node E515DBDD-0 1730 200
//@node 8488F0BB-0 2010 200
//@node 462402E1-1 2290 200
//@node 98C60A6E-0 2570 200
//@node BBF1F41F-1 2850 200
//@node E515DBDD-1 3130 200
//@node FFA282D9-0 40 40
//@node F865D81E-0 330 40
//@node 2FD43729-0 125 145
//@node CD3B67AF-0 610 200
//@node C769AAB5-0 890 200
//@node 1A7BDC73-0 1170 200
//@node 2F2319FB-0 1450 200
//@node 3634151B-0 1730 200
//@node DE6EF56E-0 2010 200
//@node 2597EC33-0 2290 200
//@node 7DF3DBFA-0 2570 200
//@node 2F2319FB-1 2850 200
//@node 6EB1426D-0 3130 200
//@node 51CD7AA5-0 40 40
//@node B3D68CD3-0 330 40
//@node EF362AFD-0 610 40
//@node D829C97B-0 890 40
//@node 3D1CC9FD-0 1170 40
//@node 6098481B-0 1450 40
//@node 111908D2-0 1730 40
//@node FEF2BA4B-0 40 40
//@node EEF45793-0 330 40
//@node 1E5C58D5-0 610 40
//@node 35F29F43-0 890 40
//@node 9F33BE18-0 1170 40
//@node 0154A348-0 1450 40
//@node 146D3513-0 1730 40
//@node D11B8C7B-0 40 40
//@node F8D2A2B0-0 330 40
//@node 8F4D4F62-0 610 40
//@node ABA8D2E3-0 890 40
//@node FC6D24C1-0 1170 40
//@node 6D977BDA-0 1450 40
//@node 1691723E-0 1730 40
//@node F5FC2933-0 2010 40
//@node 11ADD138-0 40 40
//@node FFF1F7D4-0 330 40
//@node FAD9EF28-0 40 40
//@node A0F83CD5-0 330 40
//@node 81FEFAA2-0 610 40
//@node CBC3F7CF-0 890 40
//@node 6F2CC0F0-0 1170 40
//@node DF4D4AC9-0 1450 40
//@node DD14262A-0 1730 40
//@node E73D32B6-0 2010 40
//@node 1D9D07FA-0 2290 40
//@node FC92A21F-0 2570 40
//@node DF4D4AC9-1 2850 40
//@node 38043A57-0 3130 40
//@node CBC3F7CF-1 3410 40
//@node 6F2CC0F0-1 3690 40
//@node DF4D4AC9-2 3970 40
//@node DD14262A-1 4250 40
//@node E73D32B6-1 4530 40
//@node 1D9D07FA-1 4810 40
//@node FC92A21F-1 5090 40
//@node DF4D4AC9-3 5370 40
//@node 51296636-0 5650 40
//@node CBC3F7CF-2 5930 40
//@node 6F2CC0F0-2 6210 40
//@node DF4D4AC9-4 6490 40
//@node E0E4D378-0 6770 40
//@node 6FC4057C-0 7050 40
//@node 1D9D07FA-2 7330 40
//@node FC92A21F-2 7610 40
//@node DF4D4AC9-5 7890 40
//@node 9F215E14-0 8170 40
//@node D3034592-0 40 40
//@node 8DB1D59A-0 330 40
//@node 772153A0-0 610 40
//@node 307BCCD5-0 890 40
//@node 39637C45-0 1170 40
//@node E9FE4C32-0 1450 40
//@node 708439CA-0 1730 40
//@node 863518AE-0 2010 40
//@node EC7C1AAD-0 2290 40
//@node 30563A3D-0 2570 40
//@node F74AA77C-0 2850 40
//@node EC7C1AAD-1 3130 40
//@node BE61606C-0 3410 40
//@node EBEFF7AC-0 40 40
//@node 22B24C20-0 330 40
//@node 32687650-0 40 40
//@node 661149AF-0 330 40
//@node 3AAAFE04-0 610 40
//@node DC4C0128-0 890 40
//@node ED22D632-0 1170 40
//@node 87B52B3C-0 1450 40
//@node 909E8260-0 1730 40
//@node C2A85AE4-0 2010 40
//@node 09BB879A-0 2290 40
//@node DD5FE65D-0 2570 40
//@node E2DCD934-0 2850 40
//@doomscript-blueprint end
