namespace map_delta2a {
	#define NEG_ROT		'0 -120 0'
	#define POS_ROT		'0 120 0'
	#define HEAD_TIME	3
	#define LIFT_TIME   3
	#define JET_VENT_TIME	1.5			// How long do we want the lock vents to fire ?

	float	rotmult;					// Matt's lift	
	float	lift_state_updown;
	float	crate_number;				// Stored from identify_crate(slot);		
	float	deconPosition = 0;
	//***
	// Given the cranes position in front of a cage slot, find out which crate is in that space
	// Returns the cage number. bind "cage_" + value to the hand
	//***

	void set_crate_in_slot( float slot, float crate ) {
		$world.setKey( "slot_" + slot, crate );
	}
	
	float identify_crate (float slot) {
		float value;

		value = $world.getFloatKey( "slot_" + slot );
		//sys.print ("IDENTIFY_CRATE:: Found crate #" + value + " @ slot # " + slot + "\n");

		return value;
	}

	void setup_objects()
	{
		sys.trigger ($speaker_131);			// Turn this speaker in the tube off
											// Was screwing up the fadeout for teleport_end

		$mister1.bind ($mister1_anchor);
		$mister2.bind ($mister2_anchor);
		
		$tp_leftarm.bind ($tp_shoulder);
		$tp_rightarm.bind ($tp_shoulder);

		// name of array, index number, data
		set_crate_in_slot( 1, 1 );		// Cage 1 is occupied
		set_crate_in_slot( 2, 2 );
		set_crate_in_slot( 3, 3 );
		set_crate_in_slot( 4, 4 );
		set_crate_in_slot( 5, 5 );
		set_crate_in_slot( 6, 0 );		// Cage 6 is empty
		set_crate_in_slot( 7, 7 );
		set_crate_in_slot( 8, 0 );		// Cage 8 is empty
		set_crate_in_slot( 9, 9 );
		
		$crane_control.setGuiParm ("gui_parm11", 1 );
		$crane_control.setGuiParm ("gui_parm12", 1 );
		$crane_control.setGuiParm ("gui_parm13", 1 );
		$crane_control.setGuiParm ("gui_parm14", 1 );
		$crane_control.setGuiParm ("gui_parm15", 1 );
		$crane_control.setGuiParm ("gui_parm16", 0 );
		$crane_control.setGuiParm ("gui_parm17", 1 );
		$crane_control.setGuiParm ("gui_parm18", 0 );
		$crane_control.setGuiParm ("gui_parm19", 1 );
		
		$cagecrane_base.time (1);
		$crane_base.time (1);
		$teeth_anchor.time (1);
		$cagecrane_rod.time (1);	
		$cagecrane_teeth_teeth.time (0.5);
		
		$teeth_anchor.rotateOnce ('0 0 -90');
		$cagecrane_teeth_teeth.move (LEFT, 64);
		
		$cagecrane_armsupport.time (1);
	}

	void open_fingers() {
		sys.trigger ($finger_speaker_1);
		$finger_1b_anchor.rotateOnce (POS_ROT);
		$finger_1a_anchor.rotateOnce (NEG_ROT);
		sys.wait (0.75);
		//sys.waitFor ($finger_1a_anchor);
		
		sys.trigger ($finger_speaker_2);
		$finger_2a_anchor.rotateOnce (POS_ROT);
		$finger_2b_anchor.rotateOnce (NEG_ROT);
		sys.waitFor ($finger_2b_anchor);
	}
	
	void close_fingers() {
		sys.trigger ($finger_speaker_2);
		$finger_2a_anchor.rotateOnce (NEG_ROT);
		$finger_2b_anchor.rotateOnce (POS_ROT);
		sys.wait (0.75);
		//sys.waitFor ($finger_2b_anchor);
		
		sys.trigger ($finger_speaker_1);
		$finger_1b_anchor.rotateOnce (NEG_ROT);
		$finger_1a_anchor.rotateOnce (POS_ROT);
		sys.waitFor ($finger_1a_anchor);
	}

	void unlock_cage (float cage) {
		entity	ent;
		ent = sys.getEntity ("cagelock_" + cage);
		ent.time (0.5);
		ent.move (RIGHT, 16);
		sys.waitFor (ent);
	}

	void lock_cage (float cage) {
		entity	ent;
		ent = sys.getEntity ("cagelock_" + cage);
		ent.time (0.5);
		ent.move (LEFT, 16);
		sys.waitFor (ent);
	}

	void disable_crane_control() {
		$crane_control.setGuiParm ("gui_parm10", 1);
	}

	void enable_crane_control() {
		$crane_control.setGuiParm ("gui_parm10", 0);
	}

	void crane_alarm_on() {
		sys.trigger ($clight_1);
		sys.trigger ($clight_2);
		$crane_alarm_anchor.rotate ('0 270 0');
	}

	void crane_alarm_off() {
		sys.trigger ($clight_1);
		sys.trigger ($clight_2);
		$crane_alarm_anchor.stopRotating();
	}


	void init_claw() {
	
		disable_crane_control();
	
		$body.time (3);
		$shoulder_anchor.time (1);		
		// Compress fingers

		$finger_1a_anchor.time (1.5);
		$finger_1b_anchor.time (1.5);
		$finger_2a_anchor.time (1.5);
		$finger_2b_anchor.time (1.5);
		
		
		$finger_1b_anchor.rotateOnce ('0 -180 0');
		$finger_2b_anchor.rotateOnce ('0 180 0');
		
		$finger_1a_anchor.rotateOnce ('0 180 0');
		$finger_2a_anchor.rotateOnce ('0 -180 0');

		// rotate hand up
		$hand_anchor.time (1);
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-80 0 0');
		
		// rotate arm in
		$arm_anchor.time (1);
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('30 0 0');
		
		// Face the proper direction
		
		$body.rotateOnce ('0 -90 0');
		sys.waitFor ($body);
		$head.time (HEAD_TIME);
		$head.accelTime (0.5);
		$head.decelTime (0.5);
		
		$body.rotateOnce ('0 180 0');
		sys.trigger ($head_speaker);
		$head.move (LEFT, 100);
		
		crate_number = 0;
		
		enable_crane_control();
		
	}

/*

 M a t t ' s  L i f t  f r o m  C o m m O u t s i d e 

*/

	////////////////////////////////////////////////////
	//
	//	move lift down
	//
	////////////////////////////////////////////////////
	void lift_down ()
	{
		vector rot11, rot12;
		vector rot21, rot22;
		
		rot11_x = 0;
		rot11_y = 0;
		rot11_z = rotmult;

		rot12_x = 0;
		rot12_y = 0;
		rot12_z = (-1 * rotmult);

		rot21_x = 0;
		rot21_y = 0;
		rot21_z = (2 * rotmult);

		rot22_x = 0;
		rot22_y = 0;
		rot22_z = (-2 * rotmult);

		if ( lift_state_updown == 0 ){ 
			sys.trigger ($lift_speaker_down);
			$lift_leg_11.rotateOnce ( rot11 );
			$lift_leg_12.rotateOnce ( rot22 );
			$lift_leg_13.rotateOnce ( rot21 );
			$lift_connection_top_move.rotateOnce ( rot12 );

			$lift_leg_21.rotateOnce ( rot22 );
			$lift_connection_bottom_move.rotateOnce ( rot11 );
			$lift_leg_22.rotateOnce ( rot21 );
			$lift_leg_23.rotateOnce ( rot22 );
			$lift_connection_top_static.rotateOnce ( rot11 );
			
			sys.waitFor ($lift_leg_23);
			lift_state_updown = 1;
		}
		// else sys.print ( "lift is already up\n" );
	}


	////////////////////////////////////////////////////
	//
	//	move lift up
	//
	////////////////////////////////////////////////////
	void lift_up ()
	{
		vector rot11, rot12;
		vector rot21, rot22;

		rot11_x = 0;
		rot11_y = 0;
		rot11_z = rotmult;

		rot12_x = 0;
		rot12_y = 0;
		rot12_z = (-1 * rotmult);

		rot21_x = 0;
		rot21_y = 0;
		rot21_z = (2 * rotmult);

		rot22_x = 0;
		rot22_y = 0;
		rot22_z = (-2 * rotmult);

		if ( lift_state_updown == 1 ){ 
			sys.trigger ($lift_speaker_up);
			$lift_leg_11.rotateOnce ( rot12 );
			$lift_leg_12.rotateOnce ( rot21 );
			$lift_leg_13.rotateOnce ( rot22 );
			$lift_connection_top_move.rotateOnce ( rot11 );

			$lift_leg_21.rotateOnce ( rot21 );
			$lift_connection_bottom_move.rotateOnce ( rot12 );
			$lift_leg_22.rotateOnce ( rot22 );
			$lift_leg_23.rotateOnce ( rot21 );
			$lift_connection_top_static.rotateOnce ( rot12 );

			sys.waitFor ($lift_leg_23);
			lift_state_updown = 0;
		} 
		//else sys.print ( "lift is already down\n" );
	}

	void init_lift() {
		lift_state_updown = 0;
		rotmult = 40;

		//Lift binds, times, and speeds
		//$lift_leg_11.bind ($lift_bottom);
		//$lift_light1.bind ($lift_bottom);
		
		$lift_axle1.bind ($lift_leg_11);
		$lift_axle2.bind ($lift_leg_11);
		$lift_leg_12.bind ($lift_axle2);
		$lift_axle4.bind ($lift_leg_12);
		$lift_axle6.bind ($lift_leg_12);
		$lift_leg_13.bind ($lift_axle6);
		$lift_axle7.bind ($lift_leg_13);

		$lift_leg_23.bind ($lift_axle7);
		$lift_axle5.bind ($lift_leg_23);
		$lift_leg_22.bind ($lift_axle5);
		$lift_axle3.bind ($lift_leg_22);
		$lift_leg_21.bind ($lift_axle3);

		$lift_connection_top_move.bind ($lift_leg_13);
		$lift_connection_top_static.bind ($lift_leg_23);
		$lift_connection_bottom_move.bind ($lift_leg_21);

		$lift_cage.bind ($lift_connection_top_static);

		$lift_bottom.accelTime ( .5 );
		$lift_bottom.decelTime ( .5 );

		$lift_leg_11.time ( LIFT_TIME );
		$lift_leg_12.time ( LIFT_TIME );
		$lift_leg_13.time ( LIFT_TIME );
		$lift_connection_top_move.time ( LIFT_TIME );
		$lift_leg_21.time ( LIFT_TIME );
		$lift_connection_bottom_move.time ( LIFT_TIME );
		$lift_leg_22.time ( LIFT_TIME );
		$lift_leg_23.time ( LIFT_TIME );
		$lift_connection_top_static.time ( LIFT_TIME );

		$lift_leg_11.accelTime ( .25 );
		$lift_leg_12.accelTime ( .25 );
		$lift_leg_13.accelTime ( .25 );
		$lift_connection_top_move.accelTime ( .25 );
		$lift_leg_21.accelTime ( .25 );
		$lift_connection_bottom_move.accelTime ( .25);
		$lift_leg_22.accelTime ( .25 );
		$lift_leg_23.accelTime ( .25 );
		$lift_connection_top_static.accelTime ( .25 );

		$lift_leg_11.decelTime ( .25 );
		$lift_leg_12.decelTime ( .25 );
		$lift_leg_13.decelTime ( .25 );
		$lift_connection_top_move.decelTime ( .25 );
		$lift_leg_21.decelTime ( .25 );
		$lift_connection_bottom_move.decelTime ( .25 );
		$lift_leg_22.decelTime ( .25 );
		$lift_leg_23.decelTime ( .25 );
		$lift_connection_top_static.decelTime ( .25 );
	}

/*

	End CommOutside code.

*/
	
	//***
	// Kinda ugly, need to find the proper jet pair for the accompanying slot
	// I'd give my left nut for switch(value) functionality...
	//***
	
	float trigger_steamjets(float slot) {
		entity	ent1, ent2;
		entity  speaker1, speaker2;
		float	jet1, jet2;
		
		if ( slot == 1) {
			jet1 = 1;
			jet2 = 2;
		}
		if ( slot == 2) {
			jet1 = 2;
			jet2 = 3;
		}
		if ( slot == 3) {
			jet1 = 3;
			jet2 = 4;
		}
		if ( slot == 4) {
			jet1 = 5;
			jet2 = 6;
		}
		if ( slot == 5) {
			jet1 = 6;
			jet2 = 7;
		}
		if ( slot == 6) {
			jet1 = 7;
			jet2 = 8;
		}
		if ( slot == 7) {
			jet1 = 9;
			jet2 = 10;
		}
		if ( slot == 8) {
			jet1 = 10;
			jet2 = 11;
		}
		if ( slot == 9) {
			jet1 = 11;
			jet2 = 12;
		}
		ent1 = sys.getEntity ("steamjet_" + jet1);
		ent2 = sys.getEntity ("steamjet_" + jet2);
		speaker1 = sys.getEntity ("steamspeaker_" + jet1);
		speaker2 = sys.getEntity ("steamspeaker_" + jet2);
		
		// Turn 'em on
		sys.trigger (ent1);
		sys.trigger (ent2);
		
		sys.trigger (speaker1);
		sys.trigger (speaker2);
		
		sys.wait (JET_VENT_TIME);
		
		// Turn 'em off
		sys.trigger (ent1);
		sys.trigger (ent2);	
	}
	
	void update_control_gui (float slot, float status) {
		//sys.print ("Enterint update_control_gui :: Setting slot " + slot + " to " + status + "\n");
		
		if ( slot == 1 )
			$crane_control.setGuiParm ( "gui_parm11", status );
		if ( slot == 2 )
			$crane_control.setGuiParm ( "gui_parm12", status );
		if ( slot == 3 )
			$crane_control.setGuiParm ( "gui_parm13", status );
		if ( slot == 4 )
			$crane_control.setGuiParm ( "gui_parm14", status );
		if ( slot == 5 )
			$crane_control.setGuiParm ( "gui_parm15", status );
		if ( slot == 6 )
			$crane_control.setGuiParm ( "gui_parm16", status );
		if ( slot == 7 )
			$crane_control.setGuiParm ( "gui_parm17", status );
		if ( slot == 8 )
			$crane_control.setGuiParm ( "gui_parm18", status );
		if ( slot == 9 )
			$crane_control.setGuiParm ( "gui_parm19", status );

	
	}
	
	
	//***
	// Find the target vertical rung given a slot position.
	// Need for moving the crane vertically
	//***
	
	float find_rung (float slot) {
		if ( slot <= 3 )
			return 1;
		if ( slot <= 6 )
			return 2;
		if ( slot <= 9 )
			return 3;
	}

	//***
	// Workhorse #2
	// Pick up the crate off the platform and move it back into a slot
	//***

	void insert_crate (float slot) {
		entity	ent;
		entity  crate;
		float	thread1, thread2;
		vector	vec, vec2, diff;
		float	target_rung;		
//		sys.print ("*** ENTERING insert_crate (" + slot + ")\n");
		
		crane_alarm_on();

		sys.trigger ($movement_alarm);
		sys.wait (2);
		
		sys.trigger ($shoulder_speaker);
		$shoulder_anchor.move (DOWN, 64);
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('110 0 0');
		sys.waitFor ($hand_anchor);
		
		// Gameplay stuff here... delays so that the player can jump onto the crate
		// in time...
		
		sys.wait (0.5);
		
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($arm_anchor);

		sys.wait (0.5);

		lift_up();
		
		open_fingers();	
		
		// ****
		// Get the cage on the platform
		// Remember, that crate_number is stored as a global still from the removal function...
		// ****
		
//		sys.print ("Trying to bind cage_" + crate_number + " to $hand\n");
		ent = sys.getEntity ( "cage_" + crate_number );
		crate = ent;
		ent.bind ($hand);								// Bind crate to hand

		thread map_delta2a::lift_down();
		sys.waitFor ($shoulder_anchor);
		
		// Break here and sync up original rotation values.

		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-50 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('50 0 0');

		sys.waitFor ($arm_anchor);

		
		sys.trigger ($head_speaker);
		$head.move (RIGHT, 100);
		sys.trigger ($shoulder_speaker);	
		$shoulder_anchor.move (UP, 64);
		$body.time (5);
		sys.trigger ($body_speaker_5);
		$body.rotateOnce ('0 180 0');
		sys.waitFor ($body);
		$body.time (3);

		// Need to find vertical here...		

		target_rung = find_rung (slot);
		if ( target_rung == 3 ) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (DOWN, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (DOWN, 128);
			sys.waitFor ($body);
		}
		if ( target_rung == 2) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (DOWN, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (DOWN, 32);
			sys.waitFor ($body);
		}

		// Need lateral movement here.		
	
		ent = sys.getEntity ("pos" + slot);
		vec = ent.getWorldOrigin ();
		
		vec2 = $crane_guide.getWorldOrigin ();

		// ---
		// Calculate movement vectors and move accordingly
		// ---
		
		diff_x = ( vec2_x - vec_x );
		if ( diff_x < 0 ) {
			diff_x = abs ( diff_x );
			sys.trigger ($head_speaker);
			$head.move (FORWARD, diff_x);
		}
		else {
			sys.trigger ($head_speaker);
			 $head.move (BACK, diff_x);
		}

		sys.waitFor ($head);
	
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('60 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-60 0 0');
		
		trigger_steamjets(slot);
		thread1 = thread map_delta2a::unlock_cage(slot);
		sys.waitFor ($arm_anchor);
		
		trigger_steamjets(slot);
		
		sys.waitForThread (thread1);
		
		//thread map_delta2a::lock_cage(slot);
		
		lock_cage(slot);
		
		crate.unbind();									// Unbind the crate
		
		// ***
		// Paranoia case to ensure that the crate gets bound to it's absolute starting position
		// after it has been manipulated
		// ***
		
		crate.setOrigin (ent.getWorldOrigin () );
//		sys.print ("fixed the crate\n");
		
		close_fingers();
		
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-60 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('60 0 0');
		sys.waitFor ($hand_anchor);

		// ***
		// Lateral movement to center
		// ***
		
		ent = sys.getEntity ("pos5");
		vec = ent.getWorldOrigin ();
		vec2 = $crane_guide.getWorldOrigin ();
		diff_x = ( vec2_x - vec_x );
		if ( diff_x < 0 ) {
			diff_x = abs ( diff_x );
			sys.trigger ($head_speaker);
			$head.move (FORWARD, diff_x);
		}
		else {
			sys.trigger ($head_speaker);
			$head.move (BACK, diff_x);
		}

		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('50 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-50 0 0');		
		sys.waitFor ($arm_anchor);

		sys.waitFor ($head);

		// Reset rungs
		
		if ( target_rung == 3 ) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (UP, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (UP, 128);
			sys.waitFor ($body);
		}
		if ( target_rung == 2) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (UP, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (UP, 32);
			sys.waitFor ($body);
		}

		// Rotate around
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-110 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('60 0 0');
		sys.trigger ($head_speaker);
		$head.move (LEFT, 100);
		sys.trigger ($body_speaker_3);
		$body.rotateOnce ('0 180 0');
		sys.waitFor ($arm_anchor);
		sys.waitFor ($head);

		crane_alarm_off();

		// Ok, find my way back to the reset point...

		set_crate_in_slot( slot, crate_number );	
		crate_number = 0;											// All crates accounted for
//		sys.print ("*** EXITING insert_crate (" + slot + ")\n");
		update_control_gui (slot, 1);
	}
	
	//***
	// (In his best Ian Astbury voice... Xian bellows...)
	// "Talking 'bout crates ! CRATE REMOVAL MACHINE !!!"
	//
	// Workhorse #1
	// Grabs a crate from the desired slot, and moves it onto the platform.
	//***
	
	void remove_crate (float slot) {
		entity	ent;
		entity  crate;
		float	thread1, thread2;
		vector	vec, vec2, diff;
		float	target_rung;		
//		sys.print ("*** ENTERING insert_crate (" + slot + ")\n");

		crane_alarm_on();

		sys.trigger ($movement_alarm);
		sys.wait (2);
		
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('110 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-60 0 0');

		sys.trigger ($head_speaker);
		$head.move (RIGHT, 100);
		sys.trigger ($body_speaker_3);
		$body.rotateOnce ('0 180 0');
		sys.waitFor ($head);
		sys.waitFor ($body);

		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-50 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('50 0 0');

		sys.waitFor ($hand_anchor);

		// Need to find vertical here...		

		target_rung = find_rung (slot);
		if ( target_rung == 3 ) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (DOWN, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (DOWN, 128);
			sys.waitFor ($body);
		}
		if ( target_rung == 2) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (DOWN, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (DOWN, 32);
			sys.waitFor ($body);
		}

		// Need lateral movement here.		
	
		ent = sys.getEntity ("pos" + slot);
		vec = ent.getWorldOrigin ();
		
		vec2 = $crane_guide.getWorldOrigin ();

		// ---
		// Calculate movement vectors and move accordingly
		// ---
		
		diff_x = ( vec2_x - vec_x );
		if ( diff_x < 0 ) {
			diff_x = abs ( diff_x );
			sys.trigger ($head_speaker);
			$head.move (FORWARD, diff_x);
		}
		else {
			sys.trigger ($head_speaker);
			$head.move (BACK, diff_x);
		}

		sys.waitFor ($head);
	
		// This should put us in front of the crate we want to snag
		
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('60 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($arm_anchor);
		open_fingers();
		
		thread1 = thread map_delta2a::unlock_cage (slot);
		trigger_steamjets(slot);
		
		// Get the cage on the platform
		
		crate_number = identify_crate(slot);
		
//		sys.print ("Trying to bind cage_" + crate_number + " to $hand\n");
		crate = sys.getEntity ( "cage_" + crate_number );
		crate.bind ($hand);								// Bind crate to hand
		
		sys.waitForThread (thread1);
		thread map_delta2a::lock_cage(slot);
		
		// Ok, the crate is now bound to the crane
		
		sys.wait (0.5);
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-60 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('60 0 0');
		
		sys.waitFor ($arm_anchor);
		
		// ***
		// Lateral movement to center
		// ***
		
		ent = sys.getEntity ("pos5");
		vec = ent.getWorldOrigin ();
		vec2 = $crane_guide.getWorldOrigin ();
		diff_x = ( vec2_x - vec_x );
		if ( diff_x < 0 ) {
			diff_x = abs ( diff_x );
			sys.trigger ($head_speaker);
			$head.move (FORWARD, diff_x);
		}
		else {
			sys.trigger ($head_speaker);
			$head.move (BACK, diff_x);
		}
			
		sys.waitFor ($head);

		// Crane should be centered and ready to move toward the platform.		
	
		if ( target_rung == 3 ) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (UP, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (UP, 128);
		}
		if ( target_rung == 2) {
			sys.trigger ($shoulder_speaker);	
			$shoulder_anchor.move (UP, 64);
			sys.trigger ($body_vert_speaker);
			$body.move (UP, 32);
		}
		sys.waitFor ($body);
	
		// Ok, now it's centered and on the top rung...
		// Move toward the platform... for real this time...
		
		thread lift_up();
		
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('50 0 0');
		sys.trigger ($shoulder_speaker);	
		$shoulder_anchor.move (DOWN, 64);
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('-50 0 0');
		sys.trigger ($head_speaker);
		$head.move (LEFT, 100);
		sys.trigger ($body_speaker_3);
		$body.rotateOnce ('0 180 0');
		sys.waitFor ($head);

		// woop ! It's on the platform now...
		
		thread map_delta2a::close_fingers();
		
		crate.unbind();
		crate.bind ($lift_cage);
		sys.wait (0.5);
		
		thread map_delta2a::lift_down();
		
		sys.trigger ($hand_speaker);
		$hand_anchor.rotateOnce ('-110 0 0');
		sys.trigger ($arm_speaker);
		$arm_anchor.rotateOnce ('60 0 0');
		sys.trigger ($shoulder_speaker);	
		$shoulder_anchor.move (UP, 64);
		sys.waitFor ($shoulder_anchor);
		
		crane_alarm_off();
		// 
		set_crate_in_slot( slot, 0 );			// Set the cage as empty
		update_control_gui (slot, 0);
	}

	void process_cage (float slot) {
		float	value;
		entity	ent, ent2;
		vector  deb;
		vector	vec, vec2, diff;
		float	rod_rotation;
		float	shoulder_diff;
		float	body_diff;
		float	desired_rung;
		float	rung_thread;
		
		rotmult = 41;
		
		disable_crane_control();
		
		deb = $hand_anchor.getWorldOrigin ();
//		sys.print ("ENTER: process_cage: $hand_anchor @ (" + deb_x + ", " + deb_y + ", "+ deb_z + ")\n");
		
		// Load the state of the slot into value
		value = identify_crate(slot);
		
//		sys.print ("Target Slot Value :: " + value + "\n");
		
		// ---
		// First, check to see if there is anything on the platform. If there is,
		// we are going to move it to a slot instead of extracting a slot
		// ---
		
		if ( ( crate_number != 0) ) {				// No crate on the platform ?
//			sys.print ("Crate #" + crate_number + " is currently on the platform\n");
			if ( value == 0 ) {
//				sys.print ("It wants to go to position " + slot + ", which is free\n");
				insert_crate (slot);
			}
//			else {
//				sys.print ("It wants to go to position " + slot + ", which is *NOT* free\n");
//			}
		}
		// Nope, nothing on the platform, lets go get it...
		else {
//			sys.print ("Nothing on the platform. lets proceed with possible movement...\n");
			// Is there anything at the slot we are interested in ?
			if ( value > 0 ) {	
				remove_crate (slot);
			}
//			else if ( value == -1 ) {
//				sys.print ("That slot is broken\n");	
//			}
//			else
//				sys.print ("There is nothing at that location to move...\n");
		} 
			
		deb = $hand_anchor.getWorldOrigin ();
//		sys.print ("BEFORE: $hand_anchor @ (" + deb_x + ", " + deb_y + ", "+ deb_z + ")\n");
		enable_crane_control();
//		sys.print ("Leaving process_cage()\n");
		
	}
	
	// ---
	// Bumper functions for map gui calls
	// ---
	
	void proc_cage1() {
		process_cage (1);
	}

	void proc_cage2() {
		process_cage (2);
	}

	void proc_cage3() {
		process_cage (3);
	}

	void proc_cage4() {
		process_cage (4);
	}

	void proc_cage5() {
		process_cage (5);
	}

	void proc_cage6() {
		process_cage (6);
	}

	void proc_cage7() {
		process_cage (7);
	}
	
	void proc_cage8() {
		process_cage (8);
	}

	void proc_cage9() {
		process_cage (9);
	}
	
	// ---
	// **** End bumper functions
	// ---

	//************************
	// Decon Chamber 
 	//************************

	void decon_cycle1()
	{
		$decon_trigger1.enable ();
		deconPosition = 1;
	}
	
	void decon_cycle2()
	{
		$decon_trigger1.enable ();
		deconPosition = 0;
	}
	
	void mister_move ()
	{
		$decondoor1.lock (1);
		$decondoor2.lock (1);
		
		//start decon1 computer voice
		sys.trigger ($decon1_start_speaker);
		sys.wait (1.5);
		
		thread crossFadeEnt ($misterlight_white, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decontop_fade, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decon_toplight_red, '0 0 0', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1_light, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe2, '1 1 1', '1 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe2_light, '1 1 1', '1 0 0', 1.0);
		
			
		sys.trigger ($decon1_mister1start_spkr);
		sys.trigger ($decon1_mister2start_spkr);
		sys.wait (.15);
		sys.trigger ($decon1_mister1loop_spkr);
		sys.trigger ($decon1_mister2loop_spkr);
		
		$mister1_anchor.moveTo ($mister1_spot2);
		$mister2_anchor.moveTo ($mister2_spot2);
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.rotateOnce ('60 0 0');
		$mister2_anchor.rotateOnce ('-60 0 0');
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.rotateOnce ('-60 0 0');
		$mister2_anchor.rotateOnce ('60 0 0');
		sys.waitFor ($mister1_anchor);
		
		$mister1_anchor.moveTo ($mister1_spot1);
		$mister2_anchor.moveTo ($mister2_spot1);
		sys.waitFor ($mister1_anchor);
		
		sys.trigger ($decon1_mister1stop_spkr);
		sys.trigger ($decon1_mister2stop_spkr);
		//trigger looping speaker again to turn off
		sys.trigger ($decon1_mister1loop_spkr);
		sys.trigger ($decon1_mister2loop_spkr);
		
		//turn off emitter
		sys.trigger($mister1_emitter);
		sys.trigger($mister2_emitter);
		
		sys.wait (.5);
		thread crossFadeEnt ($misterlight_white, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decontop_fade, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decon_toplight_red, '1 0 0', '0 0 0', 1.0);
		thread crossFadeEnt ($decondoorframe1, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe1_light, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe2, '1 0 0', '1 1 1', 1.0);
		thread crossFadeEnt ($decondoorframe2_light, '1 0 0', '1 1 1', 1.0);
	}

	void mister1()
	{
		$decondoor1.close ();
		$decondoor2.close ();
		$decon_trigger1.disable ();
		
		$decondoorframe1.setShaderParm (7, 0);
		$decondoorframe2.setShaderParm (7, 0);
		
		//turn on emitter
		sys.trigger($mister1_emitter);
		sys.trigger($mister2_emitter);
		
		float i;
			i = thread mister_move();
			sys.waitForThread (i);
		
		//complete decon1 computer voice
		sys.trigger ($decon1_complete_speaker);
		
		sys.wait (.25);
		if (deconPosition == 0)
		{
			$decondoorframe1.setShaderParm (7, 1);
			$decondoor1.lock (0);
		}
		if (deconPosition == 1)
		{
			$decondoorframe2.setShaderParm (7, 1);
			$decondoor2.lock (0);
		}
	}
		
	
	void tp_1 ()
	{
		$tp_guard.time (2);
		$tp_guard.decelTime (1);
		$tp_guard.rotateOnce ('0 0 -67');
		sys.waitFor ($tp_guard);

		$tp_shoulder.time (1.5);
		$tp_shoulder.rotateOnce ('0 0 -30');
		sys.waitFor ($tp_shoulder);

		$tp_leftarm.rotateOnce ('0 35 0');
		$tp_rightarm.rotateOnce ('0 -35 0');
		sys.wait(5);

		$tp_shoulder.rotateOnce ('0 0 30');
		$tp_leftarm.rotateOnce ('0 -35 0');
		$tp_rightarm.rotateOnce ('0 35 0');
		sys.waitFor ($tp_shoulder);

		$tp_guard.rotateOnce ('0 0 67');
	}

	void show_chair ()
	{
	$delta2a_chair_2.show();
	$char_scientist_old_sitting_1.setBoneMod( false );
	}

	void set_scientist_skin ()
	{
		$char_scientist_old_sitting_1.setSkin( "skins/models/chars/labcoat/labcoat3nochair.skin");
	}

	void drag_corpse ()
	{
		$corpse_mover.time (6);
		$corpse_mover.move (WEST,352);
		sys.waitFor ($corpse_mover);
		$env_ragdoll_lab1_1.remove ();
	}

	void tproom_fadeout() {
		$speaker_79.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$speaker_130.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$speaker_77.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$speaker_116.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$speaker_115.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
		$speaker_1.fadeSound ( SND_CHANNEL_ANY, -60, 5 );
	}
	
	void main ()
	{
		setup_objects ();
		thread map_delta2a::init_claw();
		init_lift();
		lift_down();
		$delta2a_chair_2.hide();
	}
}

//@doomscript-blueprint begin 6
//@source AD5AB18B
//@catalog 0C260740
//@node 396B443C-0 40 40
//@node 47B64ED4-0 330 40
//@node 7D4B454D-0 125 140
//@node 2805EBCD-0 40 40
//@node 237E5C55-0 330 40
//@node 51A34287-0 105 145
//@node 6C985BF1-0 -100 245
//@node BE28C775-0 610 40
//@node 7AEA71C1-0 40 40
//@node 0D3F1045-0 330 40
//@node 6A240A78-0 610 40
//@node B52515CA-0 890 40
//@node 87AF193F-0 1170 40
//@node 2CC45988-0 1450 40
//@node D0207E06-0 1730 40
//@node C21A205C-0 2010 40
//@node ADDF77EE-0 2290 40
//@node 790FD408-0 2570 40
//@node 1F57802E-0 2850 40
//@node E730FBF6-0 3130 40
//@node 9E7FEB36-0 3410 40
//@node 608F6A88-0 3690 40
//@node AE3FC376-0 3970 40
//@node D4EBAFA4-0 4250 40
//@node F661837F-0 4530 40
//@node 7C7FFA32-0 4810 40
//@node 9ADB5A9D-0 5090 40
//@node 8E67D450-0 5370 40
//@node 20CE7502-0 5650 40
//@node 90B6D55E-0 5930 40
//@node 756157D8-0 6210 40
//@node 5B7D309C-0 6490 40
//@node 170AB1FE-0 6770 40
//@node 58E84BC6-0 7050 40
//@node D2D55F3F-0 7330 40
//@node 2E0E20A4-0 7610 40
//@node 55CE7410-0 7890 40
//@node 51D78EB3-0 8170 40
//@node 8B3BD280-0 8450 40
//@node 2BA69D06-0 8730 40
//@node 5CEB2C80-0 40 40
//@node AC898768-0 330 40
//@node D475EABD-0 610 40
//@node ADB10246-0 890 40
//@node 80DF94C0-0 1170 40
//@node 73604349-0 1450 40
//@node 91A72E77-0 1730 40
//@node C2BE116C-0 2010 40
//@node C21853AD-0 2290 40
//@node 8790BA92-0 40 40
//@node A59F38AF-0 330 40
//@node 3872CCBD-0 610 40
//@node 709585EA-0 890 40
//@node D1EBC3BA-0 1170 40
//@node 91EC1752-0 1450 40
//@node 1041686B-0 1730 40
//@node D5B705FC-0 2010 40
//@node 71582511-0 2290 40
//@node F8CF32B6-0 40 40
//@node BFD2765C-0 330 40
//@node 300E8F54-0 105 145
//@node 9EFC3EB9-0 -100 245
//@node 99F4A5D9-0 610 40
//@node 845810CD-0 890 40
//@node AC6D58D0-0 1170 40
//@node 738B2792-0 965 140
//@node 605D46D7-0 40 40
//@node AB6C1AC1-0 330 40
//@node 4F385866-0 105 145
//@node 269F2A49-0 -100 245
//@node 153C7E18-0 610 40
//@node 3E2D7F15-0 890 40
//@node 22401073-0 1170 40
//@node A34856C5-0 965 140
//@node 3F4D1F9F-0 40 40
//@node 2C91A2C9-0 330 40
//@node 71E69A8A-0 40 40
//@node CDEB1905-0 330 40
//@node 580F3CA8-0 40 40
//@node C0576CD8-0 330 40
//@node 872E28B9-0 610 40
//@node 7DC26673-0 890 40
//@node 7DE949C2-0 40 40
//@node 7D315CE2-0 330 40
//@node 1045E3FF-0 610 40
//@node 524FF793-0 890 40
//@node 764EEDE3-0 40 40
//@node 0BF0C303-0 330 40
//@node 408B6B2D-0 610 40
//@node CB25EEFD-0 890 40
//@node CAE512C6-0 1170 40
//@node CF98FA25-0 1450 40
//@node 51349273-0 1730 40
//@node 9C686870-0 2010 40
//@node FA00951A-0 2290 40
//@node 0B8D65EE-0 2570 40
//@node E3C8CBDC-0 2850 40
//@node 634CF5E4-0 3130 40
//@node E4740B32-0 3410 40
//@node B84227B5-0 3690 40
//@node 74AF0ACD-0 3970 40
//@node AD4E960D-0 4250 40
//@node 9B2FE7CE-0 4530 40
//@node 1E51B07A-0 4810 40
//@node 90515067-0 5090 40
//@node 13713F16-0 5370 40
//@node F3EBE440-0 5650 40
//@node D8757EE1-0 5930 40
//@node 3C092172-0 6210 40
//@node 48195744-0 6490 40
//@node 47C72ED6-0 6770 40
//@node AA6AB8DA-0 7050 40
//@node 05976E93-0 7330 40
//@node 3A6F8A17-0 7125 145
//@node 1248F1CC-0 7610 40
//@node ED567F61-0 40 40
//@node F922737E-0 330 40
//@node 665B1E38-0 125 145
//@node 6BBB886F-0 610 40
//@node 92E45027-0 405 145
//@node 35787F81-0 890 40
//@node 5FDB466D-0 685 145
//@node FE9772DD-0 1170 40
//@node CF16F7BF-0 965 145
//@node 804CCBC4-0 1450 40
//@node 35C0F26C-0 1245 145
//@node D678AF61-0 1730 40
//@node EC0FF691-0 1525 145
//@node 0D1EE4AB-0 1320 145
//@node 479F7BB3-0 2010 40
//@node 8E35A5FB-0 1805 145
//@node D52B9DF2-0 2290 40
//@node 8A2712E5-0 2085 145
//@node 7D7F78FF-0 2570 40
//@node 9377E521-0 2365 145
//@node 3760346D-0 2160 145
//@node A62BF6C8-0 2850 40
//@node 59DEE8FB-0 2645 145
//@node F9684221-0 3130 40
//@node 029283CF-0 2925 145
//@node E1602397-0 3410 40
//@node 99C30412-0 3205 145
//@node F9AA8FA7-0 3000 145
//@node 550F3C54-0 3690 40
//@node 0D82DAE2-0 3485 145
//@node A3EED135-0 3280 145
//@node 58ECD01C-0 4530 200
//@node C52477B1-0 4810 200
//@node 6796FAF7-0 4045 300
//@node 3F33BC4E-0 5090 200
//@node 4EC3945F-0 4325 300
//@node 7372CA86-0 5370 200
//@node 60FF7074-0 4605 300
//@node 28989ADF-0 5650 200
//@node FA5A335C-0 4885 300
//@node 43A791A4-0 5930 200
//@node C1B50776-0 5165 300
//@node 440BB390-0 6210 200
//@node 78BDD80A-0 5445 300
//@node 205E617E-0 6490 200
//@node 3D481314-0 5725 300
//@node D8681B06-0 6770 200
//@node FC082B97-0 6005 300
//@node A54FD1AF-0 7050 200
//@node EA5CDACA-0 6285 300
//@node CB720ED4-0 7330 200
//@node 4B816BFC-0 7050 200
//@node 131723D2-0 6845 305
//@node 70215ED4-0 40 40
//@node 22EF7DA1-0 330 40
//@node F3055E32-0 125 145
//@node CFB33248-0 610 40
//@node 99F0F793-0 405 145
//@node 88841022-0 890 40
//@node 176C769A-0 685 145
//@node B8B18822-0 1170 40
//@node E16BBCDF-0 965 145
//@node 703B5EA3-0 1450 40
//@node 2A9DC9FC-0 1245 145
//@node 78C5BD9C-0 1730 40
//@node 0C24838A-0 1525 145
//@node 72A8D6EA-0 1320 145
//@node 52F17F98-0 2010 40
//@node D4BAD166-0 1805 145
//@node 13B89731-0 2290 40
//@node 1500B50E-0 2085 145
//@node 83EC5BA0-0 2570 40
//@node CE205970-0 2365 145
//@node EAAFF2EC-0 2160 145
//@node 88923783-0 2850 40
//@node FF387CD4-0 2645 145
//@node 12479D02-0 3130 40
//@node 9161A765-0 2925 145
//@node 339F9022-0 3410 40
//@node 9985127A-0 3205 145
//@node ABE26027-0 3000 145
//@node 545BE1EE-0 3690 40
//@node 8ADCC35B-0 3485 145
//@node 8CA151F7-0 3280 145
//@node F2E40290-0 4530 200
//@node 14E3A8D1-0 4810 200
//@node AA096A0F-0 4045 300
//@node 7081403E-0 5090 200
//@node 62EA3B9A-0 4325 300
//@node 63D4BDC6-0 5370 200
//@node BA44485B-0 4605 300
//@node 61CB7A19-0 5650 200
//@node 4E31DFBB-0 4885 300
//@node 8EE41E98-0 5930 200
//@node B4D2575B-0 5165 300
//@node 86F93F4C-0 6210 200
//@node 9AC3D327-0 5445 300
//@node 81D29E0E-0 6490 200
//@node F406353F-0 5725 300
//@node 28014246-0 6770 200
//@node A8C6630F-0 6005 300
//@node 7AC480C5-0 7050 200
//@node 4D4A2FBB-0 6285 300
//@node FE32DBF1-0 7330 200
//@node C0D3834A-0 7050 200
//@node 22F315B8-0 6845 305
//@node 804964F9-0 40 40
//@node 2BDB0B29-0 330 40
//@node CD4096A2-0 125 145
//@node 3DAA915B-0 610 40
//@node 0BEF456D-0 405 145
//@node B0F0DECC-0 890 40
//@node 6F5A8CB3-0 1170 40
//@node C63ABC90-0 1450 40
//@node 4C357424-0 1730 40
//@node E159DB02-0 2010 40
//@node 5E330E53-0 2290 40
//@node D3246DD0-0 2570 40
//@node AF534123-0 2850 40
//@node 29FD3A81-0 3130 40
//@node F907CD0E-0 3410 40
//@node 4CB3C3D0-0 3690 40
//@node A84EDC65-0 3970 40
//@node 056C36C5-0 4250 40
//@node 1C5FAB93-0 4530 40
//@node 74968354-0 4810 40
//@node 3B327755-0 5090 40
//@node 87F0DFD8-0 5370 40
//@node 7D343859-0 5650 40
//@node D3DD0588-0 5930 40
//@node E9B0B33D-0 6210 40
//@node AE10067E-0 6490 40
//@node F30FD1ED-0 6770 40
//@node 6D9E6F57-0 7050 40
//@node 984CC365-0 7330 40
//@node 49D97C66-0 7610 40
//@node E4280685-0 7890 40
//@node 5E083192-0 8170 40
//@node F87182F8-0 8450 40
//@node FAEC0053-0 8730 40
//@node 76403052-0 9010 40
//@node 7C5BD5C3-0 9290 40
//@node E5622D71-0 9570 40
//@node 79A1986D-0 9850 40
//@node 7EAEB5DA-0 10130 40
//@node 10FE267B-0 10410 40
//@node 2275A716-0 10690 40
//@node 230CD903-0 10970 40
//@node 7122A4BC-0 11250 40
//@node 12E701F9-0 11530 40
//@node 5452FD6C-0 11810 40
//@node 18F9B15E-0 12090 40
//@node AAFFD144-0 12370 40
//@node 5A5DB421-0 12650 40
//@node 75126CE4-0 12930 40
//@node 932C999D-0 13210 40
//@node 6C527F08-0 40 40
//@node E66E66DB-0 330 40
//@node 8FA4C188-0 125 145
//@node F05CF7D0-0 610 200
//@node 0E650136-0 405 305
//@node 2CE0C9E0-0 890 200
//@node 4C211D85-0 685 305
//@node 4675B9C0-0 1170 40
//@node 61DAAC79-0 965 145
//@node F85F42FF-0 1450 200
//@node DEE19E1D-0 1245 305
//@node 2CDE8B49-0 1730 200
//@node 63667664-0 1525 305
//@node 7273C06D-0 2010 40
//@node AB563830-0 1805 145
//@node F06174FE-0 2290 200
//@node 97013304-0 2085 305
//@node 34EFE102-0 2570 200
//@node A77E0E54-0 2365 305
//@node D27B1352-0 2850 40
//@node CC60B29F-0 2645 145
//@node 7866C844-0 3130 200
//@node A6B90CD7-0 2925 305
//@node B4EA9A54-0 3410 200
//@node AB26E639-0 3205 305
//@node 6E78374F-0 3690 40
//@node FCB38BD6-0 3485 145
//@node 7068FA43-0 3970 200
//@node 44EF5473-0 3765 305
//@node B4E85BBD-0 4250 200
//@node 5E2F080B-0 4045 305
//@node EE7FBC94-0 4530 40
//@node 15B03EB4-0 4325 145
//@node 786B4572-0 4810 200
//@node 2E839354-0 4605 305
//@node 2CD1BF56-0 5090 200
//@node A927B297-0 4885 305
//@node CA7D4551-0 5370 40
//@node E54D40D8-0 5165 145
//@node 7048A698-0 5650 200
//@node 0160D07A-0 5445 305
//@node 6D901A93-0 5930 200
//@node 86AD0172-0 5725 305
//@node 6A84FCF6-0 6210 40
//@node 8619EB2D-0 6005 145
//@node CD7553EE-0 6490 200
//@node 941449EA-0 6285 305
//@node F5932F42-0 6770 200
//@node 754EBB93-0 6565 305
//@node 468285B3-0 7050 40
//@node 956F905C-0 6845 145
//@node D57321EF-0 7330 200
//@node EEEF88BB-0 7125 305
//@node 758BA9FD-0 7610 200
//@node ACFFDFED-0 7405 305
//@node A280F47B-0 7890 40
//@node 228BFC21-0 7665 145
//@node 70BB4D9C-0 7460 245
//@node 77E6DC24-0 7255 245
//@node 95B9F03B-0 8170 40
//@node CBA0B1FD-0 7945 145
//@node 69125FB8-0 7740 245
//@node 185C04AC-0 7535 245
//@node 07AA34D5-0 8450 40
//@node 13595216-0 8225 145
//@node F4178E48-0 8020 245
//@node 6465FB56-0 7815 245
//@node 1562BAFD-0 8730 40
//@node 2C758C68-0 8505 145
//@node A386B653-0 8300 245
//@node 5F14E3E5-0 8095 245
//@node E3058425-0 9850 40
//@node F95BDDC4-0 8805 140
//@node 1BDF1664-0 10130 40
//@node 3661FBF7-0 9085 140
//@node 4911B995-0 10410 40
//@node 1571D504-0 9365 140
//@node 0289E614-0 10690 40
//@node 98F500B2-0 9645 140
//@node D41806DB-0 10970 40
//@node E3058425-1 11250 40
//@node 7A106EE1-0 10205 140
//@node 1BDF1664-1 11530 40
//@node 27CF16EA-0 10485 140
//@node 93B572F2-0 40 40
//@node C9E51C91-0 330 40
//@node 620EBF0E-0 125 145
//@node 47B3C010-0 610 40
//@node 78FE4CF0-0 890 40
//@node B6877876-0 685 145
//@node 5872A319-0 1170 40
//@node 0CB6B4FB-0 1450 40
//@node 96181D5F-0 1245 145
//@node 5E8BF0C6-0 1730 40
//@node 73051AF2-0 2010 40
//@node 8DB9FD8E-0 1805 145
//@node E2502B17-0 2290 40
//@node 861EE8BD-0 2570 40
//@node 39442BF1-0 2365 145
//@node 49119204-0 2850 40
//@node B4997EDC-0 3130 40
//@node 659C62B2-0 2925 145
//@node 65396EAD-0 3410 40
//@node C8511D67-0 3690 40
//@node 2018CF23-0 3485 145
//@node C256902A-0 3970 40
//@node 3E01CBCE-0 4250 40
//@node 9D97680B-0 4045 145
//@node 30DEA7BB-0 4530 40
//@node 31B937F9-0 4810 40
//@node 48DBFB40-0 4605 145
//@node 9945B5C8-0 5090 40
//@node 694D6935-0 40 40
//@node DE5EDCA3-0 330 40
//@node 2353AE48-0 125 145
//@node DD548093-0 610 40
//@node 677EA8A4-0 890 40
//@node FFA11614-0 685 145
//@node E5524E94-0 1170 40
//@node 34F65D51-0 1450 40
//@node 4A204D3A-0 1245 145
//@node E5500FFD-0 1730 40
//@node 4BC52138-0 40 40
//@node EF48C1C5-0 890 40
//@node BF9A23E4-0 1170 40
//@node 7C2ED188-0 1450 40
//@node FF9BB5D9-0 1730 40
//@node 05F11313-0 2010 40
//@node 8F4A7AE4-0 2290 40
//@node 29ACFCE3-0 2570 40
//@node 7D28EE6E-0 2850 40
//@node 278ABF3B-0 3130 40
//@node A05604BD-0 3410 40
//@node A6DDC77F-0 3690 40
//@node 179133F9-0 3970 40
//@node 278ABF3B-1 4250 40
//@node 899948D7-0 4530 40
//@node 2D112C35-0 4810 40
//@node 2C62A05E-0 4530 40
//@node F68138D7-0 4305 145
//@node 621523BD-0 4100 245
//@node 790BCDEA-0 3895 245
//@node CC334F9D-0 4810 40
//@node 999D2030-0 4605 145
//@node 30F90149-0 5650 40
//@node 80BBA2CE-0 5930 40
//@node 10055305-0 6210 40
//@node 8F4A7AE4-1 6490 40
//@node 4F70E6C3-0 6770 40
//@node A05604BD-1 7050 40
//@node 26BFAB25-0 7330 40
//@node 179133F9-1 7610 40
//@node F8AFB507-0 7890 40
//@node B6AD31F2-0 8170 40
//@node FF9BB5D9-1 8450 40
//@node D5E810D6-0 8730 40
//@node 4BA5AEFC-0 9010 40
//@node 2566BEA1-0 9290 40
//@node 35FBCD3B-0 9570 40
//@node 73C25153-0 9850 40
//@node F161BFC2-0 10130 40
//@node 696739C4-0 9850 40
//@node DEF44D3B-0 9625 145
//@node F9FA20B7-0 10130 40
//@node BB314B6B-0 9925 145
//@node A024B127-0 9720 145
//@node FF9BB5D9-2 10970 200
//@node 05F11313-1 11250 200
//@node C07AFD39-0 11530 200
//@node A5EA1C16-0 11810 200
//@node 73C25153-1 12090 200
//@node BAA8D722-0 11810 40
//@node DC5C68BC-0 11605 145
//@node A2D947C7-0 11400 145
//@node FF9BB5D9-3 12650 200
//@node 05F11313-2 12930 200
//@node C07AFD39-1 13210 200
//@node 3FBACFAC-0 13490 200
//@node 73C25153-2 13770 200
//@node E3802942-0 13490 40
//@node F1069968-0 13265 145
//@node 539CEAB5-0 13060 245
//@node BE00A7D3-0 13770 40
//@node 4B48A9FE-0 13545 145
//@node 1193DD16-0 14050 40
//@node 2843D059-0 13825 145
//@node AABE29F7-0 14330 40
//@node 545EB042-0 14125 145
//@node 9AC77C20-0 14610 40
//@node 0A69B7C7-0 14405 145
//@node 2787A10C-0 14890 200
//@node F9920B61-0 14665 305
//@node F8AFB507-1 15730 200
//@node 95C3B024-0 16010 200
//@node F8AFB507-2 16570 200
//@node A218CA60-0 16850 200
//@node 87D52A4D-0 17130 40
//@node C8075DAE-0 16365 140
//@node 8841E85F-0 16160 140
//@node 8F4A7AE4-2 17410 40
//@node 7663F607-0 17690 40
//@node A05604BD-2 17970 40
//@node A6DDC77F-1 18250 40
//@node 90C817FF-0 18530 40
//@node 2799F1DA-0 18250 40
//@node 4E125262-0 18025 145
//@node 179133F9-2 19090 40
//@node 90C817FF-1 19370 40
//@node 6FDBF6C0-0 19650 40
//@node 0564F932-0 18885 140
//@node FE78AC8A-0 19930 40
//@node CF3D2CCF-0 20210 40
//@node 77A03893-0 20490 40
//@node 9786E555-0 19725 140
//@node C711FB85-0 19520 140
//@node 3049B9A9-0 20770 40
//@node 8F4A7AE4-3 21050 40
//@node 3B173DEE-0 21330 40
//@node A05604BD-3 21610 40
//@node DB925D5C-0 21890 40
//@node 7D28EE6E-1 22170 40
//@node 0AC36410-0 21890 40
//@node 8BAB048D-0 21665 145
//@node BE00A7D3-1 22170 40
//@node D4312DE7-0 21945 145
//@node 1193DD16-1 22450 40
//@node F493E658-0 22225 145
//@node AABE29F7-1 22730 40
//@node 1664FE37-0 22525 145
//@node 9AC77C20-1 23010 40
//@node 8295825E-0 22805 145
//@node 2787A10C-1 23290 200
//@node 93FF189A-0 23065 305
//@node F8AFB507-3 24130 200
//@node 95C3B024-1 24410 200
//@node F8AFB507-4 24970 200
//@node A218CA60-1 25250 200
//@node 8F4A7AE4-4 25530 40
//@node 0B05CC02-0 25810 40
//@node A05604BD-4 26090 40
//@node 3906129A-0 26370 40
//@node 179133F9-3 26650 40
//@node 87D52A4D-1 26930 40
//@node 7932D751-0 26165 140
//@node 822AEC96-0 25960 140
//@node F9FA20B7-1 26650 40
//@node E2A40AFA-0 26445 145
//@node 42E0DB40-0 26240 145
//@node FF9BB5D9-4 27490 200
//@node D5E810D6-1 27770 200
//@node C07AFD39-2 28050 200
//@node A7B8871D-0 28330 200
//@node 73C25153-3 28610 200
//@node BAA8D722-1 28330 40
//@node 93AE1E71-0 28125 145
//@node 9BC30660-0 27920 145
//@node FF9BB5D9-5 29170 200
//@node D5E810D6-2 29450 200
//@node C07AFD39-3 29730 200
//@node 3A20EBD5-0 30010 200
//@node 73C25153-4 30290 200
//@node 8F4A7AE4-5 30570 40
//@node 7A06234C-0 30850 40
//@node A05604BD-5 31130 40
//@node DB925D5C-1 31410 40
//@node F8AFB507-5 31690 40
//@node 49340D45-0 31970 40
//@node FFD286CB-0 32250 40
//@node 35FBCD3B-1 32530 40
//@node 179133F9-4 32810 40
//@node 87D52A4D-2 33090 40
//@node ADA5F788-0 32325 140
//@node 75AB4C55-0 32120 140
//@node BEE78E11-0 33370 40
//@node 8CC0278C-0 33650 40
//@node 02E944F0-0 32885 232
//@node 2527A9FE-0 33370 40
//@node 20F4D5B3-0 33165 145
//@node 198DEFF4-0 34210 40
//@node ED7C880D-0 40 40
//@node C846F00C-0 890 40
//@node 5C87750B-0 1170 40
//@node F3ED8BD5-0 1450 40
//@node B132462B-0 1730 40
//@node 10D04430-0 2010 40
//@node 7AFC3030-0 2290 40
//@node F8D461D6-0 2570 40
//@node DFDBFF18-0 2850 40
//@node 198AE5E5-0 3130 40
//@node D1E731F4-0 3410 40
//@node 25B5D446-0 3690 40
//@node 482F283A-0 3970 40
//@node 6F54FBCC-0 3205 140
//@node 60CE2A1D-0 3000 140
//@node 893C4038-0 4250 40
//@node B132462B-1 4530 40
//@node 791BC788-0 4810 40
//@node 7AFC3030-1 5090 40
//@node D1C44A2A-0 5370 40
//@node 14879113-0 5650 40
//@node C2D14BF5-0 5370 40
//@node 1D62D790-0 5145 145
//@node 24010BCA-0 5650 40
//@node 4F841018-0 5445 145
//@node CA258CB2-0 5240 145
//@node A08D7802-0 6490 200
//@node 76EE8ECE-0 6770 200
//@node 14A269E4-0 7050 200
//@node 360BD49B-0 7330 200
//@node 893C4038-1 7610 200
//@node E7D945F9-0 7330 40
//@node 90F1AA61-0 7125 145
//@node 4003AFFC-0 6920 145
//@node A08D7802-1 8170 200
//@node 76EE8ECE-1 8450 200
//@node 14A269E4-1 8730 200
//@node 7A57319B-0 9010 200
//@node 893C4038-2 9290 200
//@node 6D28B7E3-0 9010 40
//@node 7F7EBE7F-0 8785 145
//@node 0FB8AA86-0 8580 245
//@node 1F832144-0 9290 40
//@node A9C8A1F2-0 9065 145
//@node A60F6595-0 9570 40
//@node 80B7467D-0 9345 145
//@node 516AB210-0 9850 40
//@node CD1CCC52-0 9645 145
//@node 0F793C6D-0 10130 40
//@node B758DF5C-0 9925 145
//@node E52842BF-0 10410 200
//@node E9470C0D-0 10185 305
//@node DFDBFF18-1 11250 200
//@node E606B069-0 11530 200
//@node DFDBFF18-2 12090 200
//@node 636939EF-0 12370 200
//@node 482F283A-1 12650 40
//@node C3FABC3F-0 11885 140
//@node C050F1A4-0 11680 140
//@node B132462B-2 12930 40
//@node 5B1992C2-0 13210 40
//@node 7AFC3030-2 13490 40
//@node F8D461D6-1 13770 40
//@node ADC1DB2E-0 14050 40
//@node 37C006D4-0 14330 40
//@node 0B686AF7-0 14050 40
//@node 01547620-0 13825 145
//@node A99164D8-0 14890 40
//@node 1B3FDBC6-0 14610 40
//@node 8DA96E5A-0 14385 145
//@node B1BAEDB9-0 14890 40
//@node B2668EAC-0 14665 145
//@node 882D0756-0 14460 245
//@node CF15108D-0 14255 245
//@node 37C85A4E-0 15730 40
//@node D7D0C0EF-0 16010 40
//@node 803281D9-0 15245 140
//@node 5AF20C5F-0 16290 40
//@node BCD795F6-0 16570 40
//@node B132462B-3 16850 40
//@node 97951991-0 17130 40
//@node 7AFC3030-3 17410 40
//@node A9E4188F-0 17690 40
//@node ADC1DB2E-1 17970 40
//@node 90047D05-0 17690 40
//@node 2B759941-0 17465 145
//@node 1F832144-1 17970 40
//@node 9B68617B-0 17745 145
//@node A60F6595-1 18250 40
//@node 21912EDC-0 18025 145
//@node 516AB210-1 18530 40
//@node 5284FD87-0 18325 145
//@node 0F793C6D-1 18810 40
//@node ABCEAFB5-0 18605 145
//@node E52842BF-1 19090 200
//@node 9E9D24A6-0 18865 305
//@node DFDBFF18-3 19930 200
//@node E606B069-1 20210 200
//@node DFDBFF18-4 20770 200
//@node 636939EF-1 21050 200
//@node 482F283A-2 21330 40
//@node 23C2A062-0 20565 140
//@node 3B9BFCC7-0 20360 140
//@node 24010BCA-1 21050 40
//@node 006822F1-0 20845 145
//@node 0D455D81-0 20640 145
//@node A08D7802-2 21890 200
//@node CDA57C27-0 22170 200
//@node 14A269E4-2 22450 200
//@node 44A65A9C-0 22730 200
//@node E7D945F9-1 22450 40
//@node 5CBAF26C-0 22245 145
//@node 0D6768E3-0 22040 145
//@node A08D7802-3 23290 200
//@node CDA57C27-1 23570 200
//@node 14A269E4-3 23850 200
//@node 3B728E92-0 24130 200
//@node 893C4038-3 24410 40
//@node 10087842-0 24690 40
//@node B132462B-4 24970 40
//@node C677BCC7-0 25250 40
//@node A08D7802-4 25530 40
//@node 76EE8ECE-2 25810 40
//@node 7AFC3030-4 26090 40
//@node DD7CC50B-0 26370 40
//@node DFDBFF18-5 26650 40
//@node D8A8E044-0 26930 40
//@node D1E731F4-1 27210 40
//@node 25B5D446-1 27490 40
//@node 482F283A-3 27770 40
//@node FEA310F5-0 27005 140
//@node 816C5ADE-0 26800 140
//@node 4034BCFC-0 28050 40
//@node C01C2D96-0 28330 40
//@node F5160CAF-0 28610 40
//@node BCD795F6-1 28890 40
//@node 95257189-0 29170 40
//@node B132462B-5 29450 40
//@node AE526FE5-0 29730 40
//@node 7AFC3030-5 30010 40
//@node A9E4188F-1 30290 40
//@node A08D7802-5 30570 40
//@node CDA57C27-2 30850 40
//@node 32926618-0 31130 40
//@node DAA55666-0 31410 40
//@node 1D567C08-0 31690 40
//@node FDD41856-0 31970 40
//@node 4E2EE17F-0 40 40
//@node 49C9C4AE-0 330 40
//@node D7587E8C-0 125 145
//@node 7BEE476B-0 1170 40
//@node 3081466B-0 890 40
//@node CE61BD93-0 665 145
//@node 06D9E734-0 1170 40
//@node EC25B5D9-0 945 145
//@node 5D7EE6BF-0 1450 40
//@node BF5B4B2E-0 1245 145
//@node CC14CB8E-0 1040 145
//@node F44897B2-0 1730 200
//@node 7827E223-0 1525 305
//@node 76D01CE0-0 1320 305
//@node B5B0A95A-0 2570 360
//@node 8A9C86C4-0 2570 200
//@node A80A6C9D-0 2365 305
//@node 1768A628-0 2160 305
//@node C86EA18F-0 3410 360
//@node 3081466B-1 3130 40
//@node BCE4E94A-0 2905 145
//@node 8327E264-0 3970 40
//@node 4FBAC599-0 40 40
//@node 58A25F0E-0 330 40
//@node 4CBAC0E0-0 40 40
//@node EF87F706-0 330 40
//@node 4DBAC273-0 40 40
//@node 0E3254AA-0 330 40
//@node 52BACA52-0 40 40
//@node 96B0F612-0 330 40
//@node 53BACBE5-0 40 40
//@node 4471D096-0 330 40
//@node 50BAC72C-0 40 40
//@node 0CFDD78E-0 330 40
//@node 51BAC8BF-0 40 40
//@node E809C6EA-0 330 40
//@node 56BAD09E-0 40 40
//@node 537BA782-0 330 40
//@node 57BAD231-0 40 40
//@node 1E07B79E-0 330 40
//@node 6F500D16-0 40 40
//@node 72389B9A-0 330 40
//@node E8E01E02-0 610 40
//@node 690A9FDF-0 405 145
//@node 6E500B83-0 40 40
//@node 60C454E9-0 330 40
//@node 004453C8-0 610 40
//@node 5F9AD290-0 405 145
//@node F245D291-0 40 40
//@node 8C62191B-0 330 40
//@node 6C45D78A-0 610 40
//@node 77DC8A69-0 890 40
//@node 67FE17B5-0 1170 40
//@node 5A96414F-0 1450 40
//@node ADE4B3A6-0 1730 40
//@node 2AB9DE2B-0 2010 40
//@node 79657E94-0 2290 40
//@node 0E640BCD-0 2570 40
//@node BF671F4B-0 2850 40
//@node 71324926-0 3130 40
//@node 8F33FC39-0 3410 40
//@node 0D364AE4-0 3690 40
//@node 0E8808AF-0 3970 40
//@node 2E2EC5EF-0 4250 40
//@node D9DD5384-0 4530 40
//@node DA1A65AA-0 4810 40
//@node E62A706E-0 5090 40
//@node 95D04E2B-0 5370 40
//@node 90B7D468-0 5650 40
//@node 29562050-0 5930 40
//@node 95D04E2B-1 6210 40
//@node D66A91CB-0 6490 40
//@node 81D1AA45-0 6770 40
//@node 95D04E2B-2 7050 40
//@node 6D2EECC7-0 7330 40
//@node 7878845B-0 7610 40
//@node 95D04E2B-3 7890 40
//@node F7645631-0 8170 40
//@node 3C20991E-0 8450 40
//@node 2E2EC5EF-1 8730 40
//@node D9DD5384-1 9010 40
//@node 20BCED3C-0 9290 40
//@node 6EF0D4A9-0 9570 40
//@node 2ED29138-0 9850 40
//@node E7B3D4DF-0 10130 40
//@node 57553696-0 10410 40
//@node BB878B7D-0 10690 40
//@node 21283044-0 10970 40
//@node 31D14ADD-0 11250 40
//@node 50FBED5B-0 11530 40
//@node 1AA2CC16-0 11810 40
//@node C099E9A6-0 40 40
//@node B72F3F2A-0 330 40
//@node 9DF7962F-0 610 40
//@node EAD264E3-0 890 40
//@node 12B12FE3-0 1170 40
//@node F1B82B9E-0 1450 40
//@node 14568B79-0 1730 40
//@node 6A27108C-0 2010 40
//@node 30DBB59B-0 2290 40
//@node 08A05F05-0 2065 145
//@node 70A5DB36-0 2570 40
//@node 5836EAE5-0 2365 140
//@node 0E93720B-0 2850 40
//@node 471CBA83-0 3130 40
//@node 6163EE0A-0 3410 40
//@node FE07108C-0 3205 145
//@node 24F79163-0 3000 145
//@node AE6E21B4-0 3690 200
//@node BD32197B-0 3970 200
//@node 7D61DB87-0 4250 40
//@node F10659A5-0 4045 145
//@node C12BB709-0 3840 145
//@node E699ED3D-0 4530 200
//@node 5724E84A-0 4810 200
//@node B4DADF91-0 40 40
//@node 2236E7EE-0 330 40
//@node 88647542-0 610 40
//@node 08DB74F9-0 890 40
//@node 77C3D3A2-0 1170 40
//@node 127D65F7-0 1450 40
//@node CA76C0A8-0 1730 40
//@node 7A412C6D-0 2010 40
//@node 67E5787D-0 2290 40
//@node 096A80A1-0 2570 40
//@node 2FB2A442-0 2850 40
//@node 0CADE0BB-0 3130 40
//@node 58A49EE8-0 3410 40
//@node BC538A32-0 3690 40
//@node 7A412C6D-1 3970 40
//@node 549B4598-0 4250 40
//@node ECF0795E-0 40 40
//@node A9B6CB81-0 330 40
//@node 4D435729-0 610 40
//@node EC0BBD5E-0 40 40
//@node 0B8BA824-0 330 40
//@node 1AC951E0-0 40 40
//@node 5BE90253-0 330 40
//@node 20935852-0 610 40
//@node 06ADAC05-0 890 40
//@node D657AA66-0 1170 40
//@node DE2723F7-0 40 40
//@node AA867536-0 330 40
//@node 3A3B07DC-0 610 40
//@node 222F8288-0 890 40
//@node 677BEFE0-0 1170 40
//@node F81BC877-0 1450 40
//@node CF121B5D-0 1730 40
//@node 32687650-0 40 40
//@node DC4C0128-0 330 40
//@node 2546DD78-0 610 40
//@node 43C35CC0-0 890 40
//@node 28E031F4-0 1170 40
//@node 53639100-0 1450 40
//@doomscript-blueprint end
