namespace map_caves2 {

	// variable to track the open close state of caves2_shutters
	float cave2_shutter_state = 0;
	float cave2_ladder_state = 0;

	// variables to track crane movement states
	float crane_main_state = 15;
	float crane_carrier_state = 210;
	float crane_carrier_load_state = 0;
	float generator_on = FALSE;

	////////////////////////////////////////////////////
	//
	//	Setup objects
	//
	////////////////////////////////////////////////////
	void setup_objects()
	{

		//move super_ladder down for keycard puzzle
		$super_ladder.time(1);
		$super_ladder.move ( DOWN, 632 );

		$crane_carrier.bind ($crane_main);
		$crane_carrier_load.bind ($crane_carrier);
		$crane_main.setGuiParm ( "gui_parm3" , (crane_carrier_state / 4));
		$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
		$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);

		$crane_main.time (.05);
		$crane_carrier.time (.01);
		$crane_carrier_load.time (.02);
	}

	// Sound stuff for generator startup
	void toggle_generator() {
		if (generator_on) {
			sys.trigger ($speaker_generator_stop);	// Play Stop Sound
			sys.trigger ($speaker_generator_loop);	// Turn the loop off
			generator_on = FALSE;
		}
		else {
			sys.trigger ($speaker_generator_start);
			sys.wait (1);
			sys.trigger ($speaker_generator_loop);
			generator_on = TRUE;
		}
	}

	// This is so that we don't need one long 40 second looping sound for the ride down
	void lift_sound_thread() {
		sys.trigger ($lift_speaker_start);
		sys.wait (4.75);
		sys.trigger ($lift_speaker_loop);		// Turn on the loop
		sys.wait (35);
		sys.trigger ($lift_speaker_end);
		sys.wait (0.2);
		sys.trigger ($lift_speaker_loop);		// Turn off the loop
	}
	////////////////////////////////////////////////////
	//
	//	Cave2 Small ladder at the lift
	//
	////////////////////////////////////////////////////
	void lower_smallcave_ladder()
	{
		sys.wait( .5 );
		sys.trigger( $snd_ladder_move );
		$smallcave_ladder.move( DOWN, 120 );
	}

	void raise_smallcave_ladder()
	{
		sys.wait( .5 );
		sys.trigger( $snd_ladder_move );
		$smallcave_ladder.move( UP, 120 );
	}

	////////////////////////////////////////////////////
	//
	//	Cave2 1st Elevator
	//
	////////////////////////////////////////////////////
	void big_broke_start()
	{
		// times for big_broke mover
		$big_broke.time (40);
		$big_broke.accelTime (5);
		$big_broke.decelTime (.5);

		$big_broke.setKey ("snd_accel", "cav1_lift_start");
		$big_broke.setKey ("snd_move", "cav1_lift_loop");
		$big_broke.setKey ("snd_decel", "cav1_lift_stop");

		// move the big_broke
		//thread lift_sound_thread();
		$big_broke.moveTo ($big_broke_start);
		sys.waitFor ($big_broke);
		sys.trigger ($big_broke);
		sys.trigger ($func_aas_obstacle_1);
	}

void big_broke_end()
	{
		// times for big_broke mover

		$big_broke.setKey ("snd_accel", "cav1_lift_start");
		$big_broke.setKey ("snd_move", "cav1_lift_loop");
		$big_broke.setKey ("snd_decel", "cav1_lift_stop");


		$big_broke.time (40);
		$big_broke.accelTime (5);
		$big_broke.decelTime (.2);

		// move the big_broke
//		thread lift_sound_thread();
		$big_broke.moveTo ($big_broke_end);
		sys.trigger ($func_aas_obstacle_1);
	}


	////////////////////////////////////////////////////
	//	Cave2 key card objective call
	////////////////////////////////////////////////////
	void callcavekey1()
	{
		sys.trigger ($caverns2_obj1);
	}

	////////////////////////////////////////////////////
	//	Caverns2 Piston machine1 sream
	////////////////////////////////////////////////////

	void piston1steam()
	{
		sys.trigger ($piston_1_steamspeaker);
		sys.trigger ($pm1_steam1);
		sys.wait (1);
		sys.trigger ($pm1_steam1);
	}

	////////////////////////////////////////////////////
	//	Caverns2 Piston machine2 sream
	////////////////////////////////////////////////////

	void piston2steam()
	{
		sys.trigger ($piston_2_steamspeaker);
		sys.trigger ($pm2_steam1);
		sys.wait (1);
		sys.trigger ($pm2_steam1);
	}

	////////////////////////////////////////////////////
	//	Caverns2 Piston machine1
	////////////////////////////////////////////////////

	void cavepiston1()
	{
		while(1){
		$cave_piston1.accelTime (.2);
		$cave_piston1.decelTime	(.2);

		$cave_piston1.time (6);
		
		sys.trigger ($cave_piston_1_speaker_start);
		sys.trigger ($cave_piston_1_speaker_loop);		// Turn loop on
		
		$cave_piston1.move (SOUTH,64);
		sys.waitFor ($cave_piston1);
		
		sys.trigger ($cave_piston_1_speaker_loop);		// Turn loop off
		sys.trigger ($cave_piston_1_speaker_endclack);
		
		thread piston1steam();
		
		sys.wait (0.75);

		$cave_piston1.time (.5);
		sys.trigger ($cave_piston_1_speaker_back);
		$cave_piston1.move (NORTH,64);
		sys.wait (1.5);
		}
	}

	////////////////////////////////////////////////////
	//	Caverns2 Piston machine2
	////////////////////////////////////////////////////

	void cavepiston2()
	{
		while(1){
		$cave_piston2.accelTime (.2);
		$cave_piston2.decelTime	(.2);

		$cave_piston2.time (5.5);
		
		sys.trigger ($cave_piston_2_speaker_start);
		sys.trigger ($cave_piston_2_speaker_loop);		// Turn loop on
		
		$cave_piston2.move (SOUTH,64);
		sys.waitFor ($cave_piston2);
		
		sys.trigger ($cave_piston_2_speaker_loop);		// Turn loop off
		sys.trigger ($cave_piston_2_speaker_endclack);
		
		thread piston2steam();

		sys.wait (1);

		$cave_piston2.time (.5);
		
		sys.trigger ($cave_piston_2_speaker_back);
		$cave_piston2.move (NORTH,64);
		
		
		sys.wait (1.5);
		}
	}
	////////////////////////////////////////////////////
	//
	//	Cave2 v81 rumble
	//
	////////////////////////////////////////////////////
	void cave2_v81_rumble()
	{
		$c2_v81.time (.1);
		
		while(1){
			$c2_v81.rotateOnce ( '2 0 0' );
			sys.waitFor ($c2_v81);
			$c2_v81.rotateOnce ( '-2 0 0' );
			sys.waitFor ($c2_v81);
					
		}
	}

	////////////////////////////////////////////////////
	//
	//	Cave2 v82 rumble
	//
	////////////////////////////////////////////////////
	void cave2_v82_rumble()
	{
		$c2_v82.time (.1);

		while(1){
			$c2_v82.rotateOnce ( '2 0 0' );
			sys.waitFor ($c2_v82);
			$c2_v82.rotateOnce ( '-2 0 0' );
			sys.waitFor ($c2_v82);
		
		}
	}

	////////////////////////////////////////////////////
	//
	//	Cave2 cave eggs
	//
	////////////////////////////////////////////////////
//	void cave_egg1_bob()
//	{
//		$cave_egg1.rotate ( '0 15 0' );
//
//		$cave_egg1.time (.5);
//		$cave_egg1.accelTime (.25);
//		$cave_egg1.decelTime (.25);
//
//		while(1){
//			$cave_egg1.move ( DOWN, 2 );
//			sys.waitFor ($cave_egg1);
//			$cave_egg1.move ( UP, 2 );
//			sys.waitFor ($cave_egg1);
//					
//		}
//	}
//
//	void cave_egg2_bob()
//	{
//		$cave_egg2.rotate ( '0 16 0' );
//
//		$cave_egg2.time (.8);
//		$cave_egg2.accelTime (.25);
//		$cave_egg2.decelTime (.25);
//
//		while(1){
//			$cave_egg2.move ( DOWN, 2 );
//			sys.waitFor ($cave_egg2);
//			$cave_egg2.move ( UP, 2 );
//			sys.waitFor ($cave_egg2);
//					
//		}
//	}
//
//
//	void cave_egg3_bob()
//	{
//		$cave_egg3.rotate ( '0 15 0' );
//
//		$cave_egg3.time (.6);
//		$cave_egg3.accelTime (.25);
//		$cave_egg3.decelTime (.25);
//
//		while(1){
//			$cave_egg3.move ( DOWN, 2 );
//			sys.waitFor ($cave_egg3);
//			$cave_egg3.move ( UP, 2 );
//			sys.waitFor ($cave_egg3);
//					
//		}
//	}



	////////////////////////////////////////////////////
	//
	//	Cave2 shutter open close
	//
	////////////////////////////////////////////////////
	void cave2_shutter_openclose()
	{
		if (cave2_shutter_state==0){
			sys.trigger ($shutter_speaker);
			sys.trigger ($cave2_shutter_door);
			$cave2_shutter1.rotateOnce ( '0 0 -75' );
			$cave2_shutter2.rotateOnce ( '0 0 -75' );
			$cave2_shutter3.rotateOnce ( '0 0 -75' );
			sys.waitFor ($cave2_shutter1);
			cave2_shutter_state = 1;
		} else {
			sys.trigger ($shutter_speaker);
			sys.trigger ($cave2_shutter_door);
			$cave2_shutter1.rotateOnce ( '0 0 75' );
			$cave2_shutter2.rotateOnce ( '0 0 75' );
			$cave2_shutter3.rotateOnce ( '0 0 75' );
			sys.waitFor ($cave2_shutter1);
			cave2_shutter_state = 0;
		}
	}

	////////////////////////////////////////////////////
	//
	//	Cave2 ladder open close
	//
	////////////////////////////////////////////////////
	void cave2_ladder_openclose()
	{
		if (cave2_ladder_state==0){
			$cave2_dropladder.time (0.5);
			sys.trigger ($cave2_ladder_door);
			sys.trigger ($ladder_hinge_speaker);
			$cave2_dropladder.rotateOnce ( '0 0 -90' );
			sys.waitFor ($cave2_dropladder);
			$ladder_rotate_gui.setShaderParm ( 7 , 1 );
			cave2_ladder_state = 1;
		} else {
			sys.trigger ($cave2_ladder_door);
			sys.trigger ($ladder_hinge_speaker);
			$cave2_dropladder.time (0.5);
			$cave2_dropladder.rotateOnce ( '0 0 90' );
			sys.waitFor ($cave2_dropladder);
			$ladder_rotate_gui.setShaderParm ( 7 , 0 );
			cave2_ladder_state = 0;
		}
	}

	void crane_start_thread() {
		sys.trigger ($crane_start_speaker);
		sys.wait (1);
		$crane_main_speaker.On();
	
	}

	////////////////////////////////////////////////////
	//
	//	Crane Main Move Right
	//
	////////////////////////////////////////////////////
	void crane_main_right()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_carrier_forward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );

		//start the sound
//		sys.trigger ($crane_start_speaker);
//		$crane_main_speaker.On();

		thread crane_start_thread();

		while ( crane_main_state < 105 ) {
			$crane_main.rotateOnce ( '0 -1 0' );
			sys.waitFor ($crane_main);
			crane_main_state = crane_main_state + 1;
			sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
			sys.wait (.01);
		}
		sys.trigger ($crane_end_speaker);
		//stop the sound
		$crane_main_speaker.Off();
	}

	////////////////////////////////////////////////////
	//
	//	Crane Main Move Left
	//
	////////////////////////////////////////////////////
	void crane_main_left()
	{
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_forward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );

		//start the sound
		//sys.trigger ($crane_start_speaker);
		//$crane_main_speaker.On();

		thread crane_start_thread();

		while ( crane_main_state > 15 ) {
			$crane_main.rotateOnce ( '0 1 0' );
			sys.waitFor ($crane_main);
			crane_main_state = crane_main_state - 1;
			sys.print ("crane_main_state = " + crane_main_state + " \n");
			$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
			$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
			sys.wait (.01);
		}

		//stop the sound
		$crane_main_speaker.Off();
		sys.trigger ($crane_end_speaker);
	}

	////////////////////////////////////////////////////
	//
	//	Crane Reset
	//
	////////////////////////////////////////////////////
	void crane_main_reset()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_forward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );

		//start the sound
		$crane_main_speaker.On();

		if (crane_main_state > 15) {
			while ( crane_main_state > 15 ) {
				$crane_main.rotateOnce ( '0 1 0' );
				sys.waitFor ($crane_main);
				crane_main_state = crane_main_state - 1;
				sys.print ("crane_main_state = " + crane_main_state + " \n");
				$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
				sys.wait (.01);
			}
		} else if (crane_main_state < 15) {
			while ( crane_main_state < 15 ) {
				$crane_main.rotateOnce ( '0 -1 0' );
				sys.waitFor ($crane_main);
				crane_main_state = crane_main_state + 1;
				sys.print ("crane_main_state = " + crane_main_state + " \n");
				$crane_main.setGuiParm ( "gui_parm2" , crane_main_state);
				$crane_reset_button.setGuiParm ( "gui_parm2" , crane_main_state);
				sys.wait (.01);
			}
		}

		//stop the sound
		$crane_main_speaker.Off();
	}

	////////////////////////////////////////////////////
	//
	//	Crane Carrier Move Forward
	//
	////////////////////////////////////////////////////
	void crane_carrier_forward()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_back" );

		//start the sound
		$crane_carrier_speaker.On();

		while ( crane_carrier_state > 0 ) {
			$crane_carrier.move ( FORWARD, -1 );
			sys.waitFor ($crane_carrier);
			crane_carrier_state = crane_carrier_state - 1;
			sys.print ("crane_carrier_state = " + (crane_carrier_state / 4) + " \n");
			$crane_main.setGuiParm ( "gui_parm3" , (crane_carrier_state / 4));
			sys.wait (.01);
		}

		//stop the sound
		$crane_carrier_speaker.Off();
	}

	////////////////////////////////////////////////////
	//
	//	Crane Carrier Move Back
	//
	////////////////////////////////////////////////////
	void crane_carrier_back()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_foward" );

		//start the sound
		$crane_carrier_speaker.On();

		while ( crane_carrier_state < 360 ) {
			$crane_carrier.move ( FORWARD, 1 );
			sys.waitFor ($crane_carrier);
			crane_carrier_state = crane_carrier_state + 1;
			sys.print ("crane_carrier_state = " + (crane_carrier_state / 4) + " \n");
			$crane_main.setGuiParm ( "gui_parm3" , (crane_carrier_state / 4));
			sys.wait (.01);
		}

		//stop the sound
		$crane_carrier_speaker.Off();
	}

	////////////////////////////////////////////////////
	//
	//	Crane Carrier Load Move UP
	//
	////////////////////////////////////////////////////
	void crane_carrier_load_up()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_foward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );
		sys.killthread ( "map_caves2::crane_carrier_load_down" );

		while ( crane_carrier_load_state < 72 ) {
			$crane_carrier_load.move ( UP, 1 );
			sys.waitFor ($crane_carrier_load);
			crane_carrier_load_state = crane_carrier_load_state + 1;
			sys.print ("crane_carrier_load_state = " + crane_carrier_load_state + " \n");
			sys.wait (.01);
		}
	}

	////////////////////////////////////////////////////
	//
	//	Crane Carrier Load Move DOWN
	//
	////////////////////////////////////////////////////
	void crane_carrier_load_down()
	{
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_carrier_foward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );
		sys.killthread ( "map_caves2::crane_carrier_load_up" );

		while ( crane_carrier_load_state > -176 ) {
			$crane_carrier_load.move ( DOWN, 1 );
			sys.waitFor ($crane_carrier_load);
			crane_carrier_load_state = crane_carrier_load_state - 1;
			sys.print ("crane_carrier_load_state = " + crane_carrier_load_state + " \n");
			sys.wait (.01);
		}
	}

	////////////////////////////////////////////////////
	//
	//	stops all crane movement threads
	//
	////////////////////////////////////////////////////
	void crane_stop()
	{
		//turn off speakers
		$crane_carrier_speaker.Off();
		$crane_main_speaker.Off();

		sys.killthread ( "map_caves2::crane_main_right" );
		sys.killthread ( "map_caves2::crane_main_left" );
		sys.killthread ( "map_caves2::crane_carrier_forward" );
		sys.killthread ( "map_caves2::crane_carrier_back" );
		sys.killthread ( "map_caves2::crane_carrier_load_up" );
		sys.killthread ( "map_caves2::crane_carrier_load_down" );
	}


	////////////////////////////////////////////////////
	//
	//	show crane_carrier_load
	//
	////////////////////////////////////////////////////
	void crane_load_show()
	{
		//show crane_load
		$crane_carrier_load.show();
	}


	////////////////////////////////////////////////////
	//
	//	move super_ladder up
	//
	////////////////////////////////////////////////////
	void super_ladder_move()
	{
		//move super_ladder up for keycard puzzle
		sys.trigger ($super_ladder_speaker);
		$super_ladder.time(6);
		$super_ladder.move(UP,632);
	}

	void stone_movement (entity ent, float fdirection, float fdistance, float ftime) {
		ent.time (ftime);
		ent.startSoundShader ("stone_movement_loop", SND_CHANNEL_VOICE);
		ent.move (fdirection, fdistance);
		
		sys.wait (ftime - 0.25);
				
		ent.startSoundShader ( "stone_movement_end", SND_CHANNEL_VOICE2 );
		ent.stopSound ( SND_CHANNEL_VOICE, false );
	}

	////////////////////////////////////////////////////
	//
	//	Vag Stairs
	//
	////////////////////////////////////////////////////
	void raise_vag_stairs()
	{
		//raises stairs after vag fight

/*		float i;
		entity ent;
		
		for (i=8; i<=128; i+=8) {
			ent=sys.getEntity ("step" + i);
			
			thread stone_movement ( ent, UP, i, (i / 8) );
		}
*/		
		thread stone_movement ($step1, UP, 8, 1);
		thread stone_movement ($step2, UP, 16, 2);
		thread stone_movement ($step3, UP, 24, 3);
		thread stone_movement ($step4, UP, 32, 4);
		thread stone_movement ($step5, UP, 40, 5);
		thread stone_movement ($step6, UP, 48, 6);
		thread stone_movement ($step7, UP, 56, 7);
		thread stone_movement ($step8, UP, 64, 8);
		thread stone_movement ($step9, UP, 72, 9);
		thread stone_movement ($step10, UP, 80, 10);
		thread stone_movement ($step11, UP, 88, 11);
		thread stone_movement ($step12, UP, 96, 12);
		thread stone_movement ($step13, UP, 104, 13);
		thread stone_movement ($step14, UP, 112, 14);
		thread stone_movement ($step15, UP, 120, 15);
		thread stone_movement ($step16, UP, 128, 16);
		
/*
		$step1.time(1);
		$step1.move(UP,8);
		$step2.time(2);
		$step2.move(UP,16);
		$step3.time(3);
		$step3.move(UP,24);
		$step4.time(4);
		$step4.move(UP,32);
		$step5.time(5);
		$step5.move(UP,40);
		$step6.time(6);
		$step6.move(UP,48);
		$step7.time(7);
		$step7.move(UP,56);
		$step8.time(8);
		$step8.move(UP,64);
		$step9.time(9);
		$step9.move(UP,72);
		$step10.time(10);
		$step10.move(UP,80);
		$step11.time(11);
		$step11.move(UP,88);
		$step12.time(12);
		$step12.move(UP,96);
		$step13.time(13);
		$step13.move(UP,104);
		$step14.time(14);
		$step14.move(UP,112);
		$step15.time(15);
		$step15.move(UP,120);
		$step16.time(16);
		$step16.move(UP,128);
*/
}

	void cache_sounds() {
		sys.cacheSoundShader ( "stone_movement_loop" );
		sys.cacheSoundShader ( "stone_movement_end" );
	}


	////////////////////////////////////////////////////
	//
	//	Caverns 2 Main
	//
	////////////////////////////////////////////////////
	void main()
	{
		cache_sounds();
		setup_objects();
		//starts swinging lamp swinging
		$swingding.sway( 28, 0, '20 0 0' );
//		thread big_broke();
		thread cavepiston1();
		thread cavepiston2();
		thread cave2_v81_rumble();
		thread cave2_v82_rumble();
//		thread cave_egg1_bob();
//		thread cave_egg2_bob();
//		thread cave_egg3_bob();

	}

}// namespace


//Fred's Bridge thing
//
//void hk_fireball( entity self ) {
//	self.launchMissiles( "projectile_fireball_hellknight", "snd_fire", "rmissile", "target", 1, 0 );
//}

//@doomscript-blueprint begin 6
//@source A37F74CA
//@catalog 0C260740
//@node 7AEA71C1-0 40 40
//@node 18644219-0 330 40
//@node 21D323AF-0 610 40
//@node 2B6FB777-0 890 40
//@node 1A4142EB-0 1170 40
//@node 4F9CE0DE-0 1450 40
//@node 6A4ADBE7-0 1245 232
//@node 292C6CE6-0 1040 232
//@node B2729208-0 1730 40
//@node 4E65825D-0 1525 232
//@node 41A8158D-0 2010 40
//@node 397EE64F-0 1805 232
//@node 71FCC31C-0 2290 40
//@node D4B4067F-0 2570 40
//@node 8E1AEE8D-0 2850 40
//@node E9BA58BB-0 40 40
//@node 7289E122-0 330 40
//@node B2D44E1A-0 125 145
//@node BA6F5672-0 610 200
//@node D9D66534-0 890 200
//@node 5618449A-0 1170 200
//@node 754C8A9F-0 965 305
//@node B787D30A-0 1730 200
//@node 2234253A-0 2010 200
//@node D9D66534-1 2290 200
//@node B3A2B12B-0 2570 200
//@node 76784873-0 2365 305
//@node A85553C1-0 40 40
//@node 3A178184-0 330 40
//@node E52BD92F-0 610 40
//@node 78881CD2-0 890 40
//@node 772ED659-0 1170 40
//@node 158EA925-0 1450 40
//@node 33FCA9C3-0 1730 40
//@node 78881CD2-1 2010 40
//@node 549967B8-0 40 40
//@node 7E6C7EB5-0 330 40
//@node AA6CC457-0 610 40
//@node E218CAD3-0 890 40
//@node E01D4BBB-0 40 40
//@node 571BBCF2-0 330 40
//@node 3E5CBB8E-0 610 40
//@node 3A9A1F9F-0 890 40
//@node 707878D4-0 40 40
//@node EC5CC4A9-0 330 40
//@node 46C7C1E8-0 610 40
//@node C7CDB361-0 890 40
//@node E374B173-0 1170 40
//@node 405EEC1E-0 1450 40
//@node 0C8E2D7A-0 1730 40
//@node 98199587-0 2010 40
//@node 760FD781-0 2290 40
//@node E5207BDD-0 2570 40
//@node 4FC0F42B-0 2850 40
//@node B76FCB2D-0 40 40
//@node C2477D26-0 330 40
//@node 39E9301F-0 610 40
//@node 1CB617F1-0 890 40
//@node 6CDDCDF0-0 1170 40
//@node 942D9DC5-0 1450 40
//@node 899C122B-0 1730 40
//@node F71E995F-0 2010 40
//@node FA83586E-0 2290 40
//@node 17591016-0 40 40
//@node E529C762-0 330 40
//@node 252B75F1-0 40 40
//@node 88BFE2A3-0 330 40
//@node 6A1B4404-0 610 40
//@node A3916600-0 890 40
//@node 6A1B4404-1 1170 40
//@node AEB2E9A6-0 40 40
//@node 672892A3-0 330 40
//@node 8BB1F216-0 610 40
//@node 8832670F-0 890 40
//@node 8BB1F216-1 1170 40
//@node AC8D0A64-0 40 40
//@node C0915151-0 330 40
//@node A75DB95E-0 125 145
//@node 4894FA17-0 610 200
//@node 4C0A04E6-0 890 200
//@node CE2ABFBB-0 1170 200
//@node 500E006B-0 1450 200
//@node 73F27817-0 1730 200
//@node A89E5CA2-0 2010 200
//@node 9BB1D9C1-0 2290 200
//@node 73F27817-1 2570 200
//@node A6A1F84E-0 2850 200
//@node 0A1B8BF2-0 3130 200
//@node B9442BB4-0 3410 200
//@node D1A81622-0 3690 200
//@node 759170AE-0 3970 200
//@node 04E976CC-0 4250 200
//@node 492DF1BC-0 4530 200
//@node AF8D0F1D-0 40 40
//@node 3A2E541A-0 330 40
//@node AC1A9822-0 125 145
//@node 140DD35F-0 610 200
//@node A19A16EE-0 890 200
//@node 5A7104A7-0 1170 200
//@node 039CEE43-0 1450 200
//@node 6AFE340F-0 1730 200
//@node F33D0F0A-0 2010 200
//@node 9AFCA633-0 2290 200
//@node 6AFE340F-1 2570 200
//@node 0845B6E6-0 2850 200
//@node 2D05B708-0 3130 200
//@node 14115968-0 3410 200
//@node F10114EA-0 3690 200
//@node 9A3640A6-0 3970 200
//@node 39BBA5A4-0 4250 200
//@node DE7BDA7D-0 4530 200
//@node 01A9E410-0 40 40
//@node B44FF215-0 330 40
//@node 32A780E5-0 610 40
//@node AC96F2AE-0 405 145
//@node C28825BF-0 890 200
//@node 8350AD80-0 1170 200
//@node E03FECBA-0 1450 200
//@node 8350AD80-1 1730 200
//@node 89AC0323-0 40 40
//@node FBB320E3-0 330 40
//@node 60E70AE0-0 610 40
//@node 0F5CC358-0 405 145
//@node 9C025FC5-0 890 200
//@node C779A4EC-0 1170 200
//@node 2F2046BC-0 1450 200
//@node C779A4EC-1 1730 200
//@node 3F516DCB-0 40 40
//@node 11BC433C-0 330 40
//@node 4A7C0D3F-0 125 145
//@node 60E16172-0 -80 145
//@node E12C6B51-0 610 200
//@node 3D00D612-0 890 200
//@node 7015CE30-0 1170 200
//@node 76E1B551-0 1450 200
//@node D43402CE-0 1730 200
//@node 56147CD0-0 2010 200
//@node 0547269A-0 2290 200
//@node C3BF0866-0 2085 305
//@node E12C6B51-1 2850 200
//@node 3D00D612-1 3130 200
//@node 433C2D73-0 3410 200
//@node 8FF5236C-0 3690 200
//@node 250A7FB5-0 3970 200
//@node 56147CD0-1 4250 200
//@node 7D4411EB-0 4530 200
//@node 6561539F-0 4325 305
//@node 69F96BD8-0 40 40
//@node 27D51F80-0 330 40
//@node 88692DDC-0 125 145
//@node 175460B7-0 -80 145
//@node 73C3DD6D-0 610 200
//@node 5429322A-0 890 200
//@node 11FC3419-0 1170 200
//@node BC4EC2D7-0 1450 200
//@node 530A0304-0 1730 200
//@node F6BEBA21-0 2010 200
//@node ECD25938-0 2290 200
//@node 328ACA0E-0 2085 305
//@node 5429322A-1 2850 200
//@node 11FC3419-1 3130 200
//@node 73C3DD6D-1 3410 200
//@node 9EE77034-0 3690 200
//@node 530A0304-1 3970 200
//@node BD5D8E10-0 4250 200
//@node ECD01AA1-0 4530 200
//@node EF1CF002-0 4325 305
//@node CA14745E-0 40 40
//@node AF2758EB-0 330 40
//@node B7C07A33-0 610 40
//@node D4453490-0 890 40
//@node D87B33E3-0 40 40
//@node EAAD039A-0 330 40
//@node 985B652F-0 610 40
//@node 0448772D-0 890 40
//@node CBD3AC1A-0 1170 40
//@node 35D227E8-0 1450 40
//@node 6CA6F0D5-0 1245 145
//@node 0920C308-0 1040 145
//@node 60F38A6E-0 1730 200
//@node 4E39A725-0 2010 200
//@node 72FD1EBC-0 2290 200
//@node CFEA3179-0 2085 305
//@node 14AF4E52-0 1880 305
//@node 173958BE-0 2570 200
//@node 181E2C01-0 2365 300
//@node AB6AC1EA-0 2160 300
//@node 0123B2EE-0 2850 200
//@node C75053D5-0 2645 392
//@node 4E770E0F-0 3130 200
//@node 24377B4F-0 2925 392
//@node F8E9B630-0 3410 200
//@node D25040FB-0 3690 40
//@node 18A403B1-0 3970 40
//@node C5566A8E-0 40 40
//@node F0D15910-0 330 40
//@node CE1CB1FE-0 610 40
//@node 7186F942-0 890 40
//@node F60BDD6D-0 1170 40
//@node 2568ED47-0 1450 40
//@node CB29345B-0 1245 145
//@node A7031D4A-0 1040 145
//@node 0F59C2E0-0 1730 200
//@node 77990D9E-0 2010 200
//@node 21196BDF-0 2290 200
//@node B6B9065F-0 2085 305
//@node 89616CE8-0 1880 305
//@node 05EB7657-0 2570 200
//@node 54A84DE3-0 2365 300
//@node D4C00E46-0 2160 300
//@node 455392D7-0 2850 200
//@node 3106D2E7-0 2645 392
//@node 9FC71A36-0 3130 200
//@node AE4C6806-0 2925 392
//@node 3ECF1E01-0 3410 200
//@node 6C28F9DA-0 3690 40
//@node 0FC8613A-0 3970 40
//@node B661B126-0 40 40
//@node 8D866B07-0 330 40
//@node 1742C960-0 610 40
//@node 48CBEE2E-0 890 40
//@node 0E3952B2-0 1170 40
//@node EEE02D30-0 1450 40
//@node A22A102D-0 1730 40
//@node 856EA6B1-0 1525 145
//@node 34513662-0 1320 145
//@node 18E2E06F-0 2010 200
//@node 180893AF-0 1805 305
//@node 48AD5EA0-0 1600 305
//@node BB65C3F0-0 2290 360
//@node 4BA2A24E-0 2570 360
//@node 84E0344D-0 2850 360
//@node 08DA80B6-0 2645 465
//@node 229A0953-0 2440 465
//@node 95925327-0 3130 360
//@node B5B90CAE-0 2925 460
//@node 96C8A2AD-0 2720 460
//@node F40762E7-0 3410 360
//@node D0492357-0 3205 552
//@node 2E232726-0 3690 360
//@node 2728E0B5-0 3485 552
//@node 66F4DB71-0 3970 360
//@node 065686F8-0 4250 200
//@node F9F10553-0 4045 305
//@node AE62AF46-0 3840 305
//@node 821BD8ED-0 4530 200
//@node 5E55DF76-0 4325 305
//@node 24FA35C5-0 4120 305
//@node 11DC50F9-0 4810 360
//@node 4BA2A24E-1 5090 360
//@node D72A110F-0 5370 360
//@node B81FF0FE-0 5165 465
//@node 75F76EAD-0 4960 465
//@node 95925327-1 5650 360
//@node 637EFE2B-0 5445 460
//@node 21BCBAD0-0 5240 460
//@node F40762E7-1 5930 360
//@node 364C46EA-0 5725 552
//@node 2E232726-1 6210 360
//@node FC324A10-0 6005 552
//@node 66F4DB71-1 6490 360
//@node 3A13A9CA-0 6770 40
//@node 147ADFBF-0 40 40
//@node 7279D2CA-0 330 40
//@node 297A0BEF-0 610 40
//@node 57046EFD-0 890 40
//@node 80E00D3A-0 1170 40
//@node D2492ED7-0 1450 40
//@node 9D22D737-0 1245 145
//@node E95C6874-0 1040 145
//@node 121DA5C9-0 1730 200
//@node A638A3BC-0 2010 200
//@node 5DE29D3C-0 2290 200
//@node 1EDFD965-0 2085 305
//@node C568BABC-0 1880 305
//@node A4F02C7C-0 2570 200
//@node 40A04AA1-0 2365 300
//@node F8060F1D-0 2160 300
//@node A24DEAE0-0 2850 200
//@node 236C80ED-0 2645 392
//@node 55A42B90-0 2440 392
//@node 0268A880-0 3130 200
//@node D9955A64-0 3410 40
//@node 2EAAF041-0 40 40
//@node 8B195AD8-0 330 40
//@node 4BB62425-0 610 40
//@node 31527DB1-0 890 40
//@node 4EF906D4-0 1170 40
//@node DD86BB34-0 1450 40
//@node 0E4CF698-0 1245 145
//@node 832653D4-0 1040 145
//@node D1A7A73E-0 1730 200
//@node 6D68F0C2-0 2010 200
//@node 9D72E11A-0 2290 200
//@node 77A338AC-0 2085 305
//@node 8A34CC3D-0 1880 305
//@node 659ECFC2-0 2570 200
//@node F4C0FCB0-0 2365 300
//@node 5FABB870-0 2160 300
//@node 59B56776-0 2850 200
//@node C3D6532E-0 2645 392
//@node C1BAF521-0 2440 392
//@node F29D0246-0 3130 200
//@node FC82374E-0 3410 40
//@node 985A8FCA-0 40 40
//@node 45B8D423-0 330 40
//@node 75ACDCE4-0 610 40
//@node 3738265C-0 890 40
//@node EA2E997E-0 1170 40
//@node B795242A-0 1450 40
//@node 2D6028D6-0 1730 40
//@node D087CD69-0 1525 145
//@node AE6FA1BB-0 1320 145
//@node F0C397C2-0 2010 200
//@node EBF194BA-0 2290 200
//@node 5D9E8325-0 2570 200
//@node 1D9FB3D3-0 2365 305
//@node 6F92E60A-0 2160 305
//@node 19D37BF3-0 2850 200
//@node C2851117-0 2645 300
//@node 03D88A56-0 2440 300
//@node 956C530D-0 3130 200
//@node 227C5F2B-0 40 40
//@node 5D1E610E-0 330 40
//@node F881466B-0 610 40
//@node 71F2A163-0 890 40
//@node C0A5F761-0 1170 40
//@node 168E3FB2-0 1450 40
//@node 9830FAFB-0 1730 40
//@node F61704F1-0 1525 145
//@node 7FDD54BB-0 1320 145
//@node D70398C2-0 2010 200
//@node F2162A59-0 2290 200
//@node C12F8858-0 2570 200
//@node 2EA1071A-0 2365 305
//@node 475577F9-0 2160 305
//@node 918FA4EE-0 2850 200
//@node DD737FB8-0 2645 300
//@node A1337E69-0 2440 300
//@node 3F32BA24-0 3130 200
//@node A293A09B-0 40 40
//@node EC90BE34-0 330 40
//@node 81B23651-0 610 40
//@node 69CED25F-0 890 40
//@node 8BB6B0BA-0 1170 40
//@node 5B00024F-0 1450 40
//@node 6E09CA4D-0 1730 40
//@node 58CB906E-0 2010 40
//@node 49E7998B-0 2290 40
//@node 1658229D-0 40 40
//@node 43E3A039-0 330 40
//@node 986B1833-0 40 40
//@node 52ADD134-0 330 40
//@node 32DA2CCE-0 610 40
//@node D488DD86-0 890 40
//@node A84834FE-0 40 40
//@node C104B207-0 330 40
//@node 1366FF87-0 610 40
//@node EA0CE708-0 890 40
//@node D179F6F7-0 1170 40
//@node 463A71A4-0 965 140
//@node DE860CB2-0 1450 40
//@node D35956F3-0 1730 40
//@node C317E251-0 40 40
//@node 20992057-0 330 40
//@node 289B2520-0 610 40
//@node 8E9FE425-0 890 40
//@node 0C912572-0 1170 40
//@node 6C76243B-0 1450 40
//@node FE6C9E75-0 1730 40
//@node E6C89B4A-0 2010 40
//@node CC7C26CB-0 2290 40
//@node 051E6E3C-0 2570 40
//@node 0589DEC7-0 2850 40
//@node DDF682DF-0 3130 40
//@node 1E7AC0E8-0 3410 40
//@node 6FCB43BE-0 3690 40
//@node 1BB5FEAB-0 3970 40
//@node 6FAC81C8-0 4250 40
//@node 7DEEA28A-0 4530 40
//@node B832CE32-0 40 40
//@node 60BED821-0 330 40
//@node 971839E0-0 610 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 67C3ED48-0 610 40
//@node 5CB1A564-0 890 40
//@node 61FE2F57-0 1170 40
//@node 5DD8F200-0 1450 40
//@node 6BA3130D-0 1730 40
//@node 7BB419CC-0 2010 40
//@doomscript-blueprint end
