namespace map_cpuboss {
	#define PUMP_DISTANCE 90
	#define EXTEND_MID 64
	#define EXTEND_NUT 64
	#define FLOOR_SPEED 2			// Seconds

	float	bridge_down = 0;
	float	bridge_dir = 0;		
	float	bridge_moving = 0;
	float	PLAYMUSIC = TRUE;
	float	monsterstatus = 1;
	float	started_music = 0;
	float	bridge_rot_time = 6;	// How long will it take the bridge to rotate to it's place ?
			
	float stop_pumps = FALSE;
	float stop_floors = FALSE;
	float stop_lights = FALSE;
	
	float mach1_loc = 2;			// Which rung is it on ? starts in middle rung
									// 1 == bottom, 2 == middle, 3== top
	float mach1_loc_last = 0;		// Where were we last ? 


	void mover_startsound3 (entity ent) {
		ent.startSoundShader ("cpu_m3_start", SND_CHANNEL_VOICE);
		sys.wait (1);
		ent.startSoundShader ("cpu_m3_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound3 (entity ent) {
		ent.startSoundShader ("cpu_m3_stop", SND_CHANNEL_VOICE2);
	}

	void mover_startsound4 (entity ent) {
		ent.startSoundShader ("cpu_m4_start", SND_CHANNEL_VOICE);
		sys.wait (1);
		ent.startSoundShader ("cpu_m4_loop", SND_CHANNEL_VOICE2);
	}

	void mover_stopsound4 (entity ent) {
		ent.startSoundShader ("cpu_m4_stop", SND_CHANNEL_VOICE2);
	}

    //Sab room   -open and close the pillar shields

    void cpillar1_open() 
    {
		$cpillar1_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar1_shield1.moveTo ($cpillar1_shield_s1);
		$cpillar1_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar1_shield2.moveTo ($cpillar1_shield_s2);
	}

    void cpillar2_open() 
    {
		$cpillar2_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar2_shield1.moveTo ($cpillar2_shield_s1);
		$cpillar2_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar2_shield2.moveTo ($cpillar2_shield_s2);
	}

    void cpillar3_open() 
    {
		$cpillar3_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar3_shield1.moveTo ($cpillar3_shield_s1);
		$cpillar3_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar3_shield2.moveTo ($cpillar3_shield_s2);
	}

    void cpillar4_open() 
    {
		$cpillar4_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar4_shield1.moveTo ($cpillar4_shield_s1);
		$cpillar4_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar4_shield2.moveTo ($cpillar4_shield_s2);
	}

    void cpillar1_close() 
    {
		$cpillar1_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar1_shield1.moveTo ($cpillar1_shield_s0);
		$cpillar1_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar1_shield2.moveTo ($cpillar1_shield_s0);
	}

    void cpillar2_close() 
    {
		$cpillar2_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar2_shield1.moveTo ($cpillar2_shield_s0);
		$cpillar2_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar2_shield2.moveTo ($cpillar2_shield_s0);
	}

    void cpillar3_close() 
    {
		$cpillar3_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar3_shield1.moveTo ($cpillar3_shield_s0);
		$cpillar3_shield2.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar3_shield2.moveTo ($cpillar3_shield_s0);
	}

    void cpillar4_close() 
    {
		$cpillar4_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
		$cpillar4_shield1.moveTo ($cpillar4_shield_s0);
		$cpillar4_shield1.startSoundShader ("cpu_shields", SND_CHANNEL_VOICE2 );
        $cpillar4_shield2.moveTo ($cpillar4_shield_s0);
	}


        //

	// ---
	// Init base-state of world entities here
	// ---

	void init_world() {
                
        // Sabaoth room electrical pillar shield times
                
        $cpillar1_shield1.accelTime (.2);
        $cpillar1_shield2.accelTime (.2);
        $cpillar2_shield1.accelTime (.2);
        $cpillar2_shield2.accelTime (.2);
        $cpillar3_shield1.accelTime (.2);
        $cpillar3_shield2.accelTime (.2);
        $cpillar4_shield1.accelTime (.2);
        $cpillar4_shield2.accelTime (.2);
        $cpillar1_shield1.time (.5);
        $cpillar1_shield2.time (.5);
        $cpillar2_shield1.time (.5);
        $cpillar2_shield2.time (.5);
        $cpillar3_shield1.time (.5);
        $cpillar3_shield2.time (.5);
        $cpillar4_shield1.time (.5);
        $cpillar4_shield2.time (.5);

        // old boss room

		$tooth_1.sway (8, 0.2, '0 5 -4');
		$tooth_2.sway (7, 0.4, '0 -4 4');
		$tooth_3.sway (8, 0.6, '0 6 2');
		$tooth_4.sway (6, 0.32, '0 5 3');
		$tooth_5.sway (7, 0.9, '0 -3 2');
		$tooth_6.sway (7, 0.78, '0 2 5');
		$tooth_7.sway (5, 0.5, '0 4 -5');
		$tooth_8.sway (6, 0.6, '0 3 -2');
		
		$bm_arm1_anchor.time (3);
		$bm_arm1_anchor.accelTime (0.5);
		$bm_arm1_anchor.decelTime (1.5);

		$bm_mach1_wheel1_anchor.bind ($bm_mach1_support);
		$bm_mach1_wheel2_anchor.bind ($bm_mach1_support);
		$bm_mach1_wheel3_anchor.bind ($bm_mach1_support);
		$bm_mach1_wheel4_anchor.bind ($bm_mach1_support);
					
		$mach1_support_anchor.time (3);
		
		float	i;
		entity	ent, ent2, ent3;
		
		$pentagram.rotate ('0 20 0');
		
		for (i=1; i<=4; i++) {
			
			// Top pumps
			ent = sys.getEntity ("bm_pump" + i + "a");
			ent.time (5);
			ent.accelTime (0.75);
			ent.decelTime (1.5);
			
			ent = sys.getEntity ("bm_pump" + i + "a_anchor");
			ent.time (5);
			ent.accelTime (0.75);
			ent.decelTime (1.5);

			// Bottom pump
			
			ent = sys.getEntity ("bm_pump" + i + "b");
			ent.time (5);
			ent.accelTime (0.75);
			ent.decelTime (1.5);

			ent = sys.getEntity ("bm_pump" + i + "b_anchor");
			ent.time (5);
			ent.accelTime (0.75);
			ent.decelTime (1.5);
		}

		// bind sector 1
		for ( i = 1; i <= 3; i++ ) {
			ent=sys.getEntity ("s1_" + i);
			ent2=sys.getEntity ("s1_" + i + "_anchor");
			ent.time (FLOOR_SPEED);
			ent2.time (FLOOR_SPEED);
			ent.bind (ent2);
			ent2.bind ($sector_1);
		}

		// bind sector 2
		for ( i = 1; i <= 3; i++ ) {
			ent=sys.getEntity ("s2_" + i);
			ent2=sys.getEntity ("s2_" + i + "_anchor");
			ent.time (FLOOR_SPEED);
			ent2.time (FLOOR_SPEED);
			ent.bind (ent2);
			ent2.bind ($sector_2);
		}
		
		// bind sector 3
		for ( i = 1; i <= 9; i++ ) {
			ent=sys.getEntity ("s3_" + i);
			ent2=sys.getEntity ("s3_" + i + "_anchor");
			ent.time (FLOOR_SPEED);
			ent2.time (FLOOR_SPEED);
			ent.bind (ent2);
			ent2.bind ($sector_3);
		}
		
		$bm_arm1_bolt.time (2);
		$bm_arm1_bolt.accelTime (0.25);
		$bm_arm1_bolt.decelTime (0.75);
		
		$bm_arm1_mid.move (RIGHT, 40);
		$bm_arm1_nut.move (RIGHT, 40);
		
		sys.wait (1);
		
	}

	// ---
	// Init base position for the central bridge
	// ---

	void init_bridge() {
		$bridge_support.time (6);
		$bridge_support.accelTime (0.75);
		$bridge_support.decelTime (1);

		$cpubridge_anchor.time (6);
		$cpubridge_anchor.accelTime (2);
		$cpubridge_anchor.decelTime (3);
		
		$bridge_ramp_right.time (2);
		$bridge_ramp_left.time (2);

		$bridge_arm_anchor.time (2);

		$bridge_base.bind ($bridge_support);
		$bridge_arm_anchor.bind ($bridge_base);

		$bridge_rail_right.bind ($bridge_ramp_right);
		$bridge_rail_left.bind ($bridge_ramp_left);

		$bridge_ramp_right.bind ($bridge_arm_anchor);
		$bridge_ramp_left.bind ($bridge_arm_anchor);
		$bridge_gui.bind ($bridge_arm_anchor);

		$bridge_ramp_right.time (1);
		$bridge_ramp_left.time (1);	

		$bridge_ramp_right.rotateOnce ('0 0 -90');
		$bridge_ramp_left.rotateOnce ('0 0 90');
		$bridge_arm_anchor.rotateOnce ('-90 0 0');

		$bridge_support.move (UP, 1024);

	}

	void test_bridge() {
		float	i;

		if (bridge_down == 0) {
			sys.trigger ($bridge_vo_1);
			// Sound of bridge coming down
			$speaker_bridge_1.startSoundShader ("cpu_bridge_down_6s", SND_CHANNEL_BODY );		
			
			$bridge_support.move (DOWN, 1024);
			$bridge_support.rotateOnce ('0 -450 0');
			sys.waitFor ($bridge_support);
			
			
			
			$bridge_arm_anchor.time (5);
			// Sound of Arm rotating down
			$speaker_bridge_3.startSoundShader ("cpu_arm_down_5s", SND_CHANNEL_ITEM );
			$bridge_arm_anchor.rotateOnce ('90 0 0');			// Down
			sys.waitFor ($bridge_arm_anchor);
			
			$bridge_arm_anchor.time (2);

			// Bounce the bridge as it comes down

			$bridge_arm_anchor.time (0.3);
			$bridge_arm_anchor.rotateOnce ('-2 0 0');			// Up
			sys.waitFor ($bridge_arm_anchor);

			$bridge_arm_anchor.time (0.2);
			$bridge_arm_anchor.rotateOnce ('2 0 0');			// Down
			sys.waitFor ($bridge_arm_anchor);
			
			$bridge_ramp_right.startSoundShader ("cpu_bridge_rails", SND_CHANNEL_VOICE );
			$bridge_ramp_right.rotateOnce ('0 0 90');
			
			$bridge_ramp_left.startSoundShader ("cpu_bridge_rails", SND_CHANNEL_VOICE );	
			$bridge_ramp_left.rotateOnce ('0 0 -90');
			sys.waitFor ($bridge_ramp_left);

		//	$bridge_support.rotateOnce ('0 -90 0');
			//$bridge_ramp_right.rotateOnce ('-90 0 0');
			//$bridge_ramp_left.rotateOnce ('90 0 0');
			
			bridge_down = 1;
			bridge_dir = 3;
		}
	}

	vector bridge_getRotationAngles (float target_dir)
	{
		vector	vec;
		
		if ( (bridge_dir != 1) && (target_dir == 1) ) {
			$cpubridge_anchor.move (DOWN, 256);
		}
		
		else if ( (bridge_dir == 1) && (target_dir != 1) ) {
			$cpubridge_anchor.move (UP, 256);
		}

		//else {
		//	sys.print ("not moving up or down\n");
		//}

		if ( (bridge_dir - target_dir) == -3 )
			return '0 90 0';
		if ( (bridge_dir - target_dir) == 3 )
			return '0 -90 0';

		vec_x = 0;
		vec_z = 0;
		vec_y = (bridge_dir - target_dir) * 90;
		
		
		if ( ( vec_y == 90 ) || ( vec_y == -90 ) ) {
			$bridge_support.time (6);
			$cpubridge_anchor.time (6);
			bridge_rot_time = 6;
		}
		if ( ( vec_y == 180 ) || (vec_y == -180) ) {
			$bridge_support.time (10);
			$cpubridge_anchor.time (10);
			bridge_rot_time = 10;
		}
		if ( ( vec_y == 270 ) || (vec_y == -270) ) {
			$bridge_support.time (10);
			$cpubridge_anchor.time (10);
			bridge_rot_time = 10;
		}
		return vec;	
	}

	void bridge_rotation_sound() {
		
		if (bridge_rot_time == 6) {
			$speaker_bridge_2.startSoundShader ("bridge_rotation_6s", SND_CHANNEL_BODY );
			return;
		}
		else {
			$speaker_bridge_2.startSoundShader ("bridge_rotation_10s", SND_CHANNEL_BODY );
			return;
		}
	
	}

	void bridge_rotate_south()
	{
		
		vector	vec;
		
		if ( bridge_dir == 3 )
			return;						// Bridge is already at this location
		
		if (bridge_moving == 0) {
			bridge_moving = 1;
			$bridge_gui.disable();

			if (bridge_down == 0)
				test_bridge();	
			else
			{
				vec = bridge_getRotationAngles (3);
				
				thread bridge_rotation_sound();
				
				$bridge_support.rotateOnce (vec);
				sys.waitFor ($bridge_support);
				
				bridge_dir = 3;
			}
			$bridge_gui.enable();
			bridge_moving = 0;
		}
	}

	void bridge_rotate_east()
	{
		vector	vec;
		
		if (bridge_dir == 2)
			return;							// Bridge is already at this location
		
		if (bridge_moving == 0) {
			bridge_moving = 1;
			$bridge_gui.disable();
			vec = bridge_getRotationAngles (2);
			
			thread bridge_rotation_sound();
			
			sys.print ("rot time ==" + bridge_rot_time + "\n");
			$bridge_support.rotateOnce (vec);
			sys.waitFor ($bridge_support);
			
			bridge_dir = 2;
			$bridge_gui.enable();
			bridge_moving = 0;
		}
	}

	void bridge_rotate_west()
	{
		vector	vec;
		
		if (bridge_dir == 4)
			return;						// Bridge is already at this location
		
		if (bridge_moving == 0) {
			bridge_moving = 1;
			$bridge_gui.disable();
			vec = bridge_getRotationAngles (4);
			
			thread bridge_rotation_sound();
			
			sys.print ("rot time ==" + bridge_rot_time + "\n");
			$bridge_support.rotateOnce (vec);
			sys.waitFor ($bridge_support);
			
			bridge_dir = 4;
			$bridge_gui.enable();
			bridge_moving = 0;
		}
	}

	void bridge_rotate_north()
	{
		vector	vec;
		
		if (bridge_dir == 1)
			return;							// Bridge is already at this location
		
		if (bridge_moving == 0) {
			bridge_moving = 1;			
			$bridge_gui.disable();
			vec = bridge_getRotationAngles (1);
			
			thread bridge_rotation_sound();

			sys.trigger ($trigger_objectivecomplete);

			sys.print ("rot time ==" + bridge_rot_time + "\n");
			$bridge_support.rotateOnce (vec);
			sys.waitFor ($bridge_support);
                         
            
			
			bridge_dir = 1;
			$bridge_gui.enable();
			bridge_moving = 0;
		}
	}

	void init_running_lights() {
		entity	l1, l2, l3, l4;
		float	i;
		
		for ( i=1; i<=13; i++ ) {
			l1 = sys.getEntity ("rrun_" + i);
			l2 = sys.getEntity ("lrun_" + i);
			l3 = sys.getEntity ("trrun_" + i);
			l4 = sys.getEntity ("tlrun_" + i);
	
			l1.Off();
			l2.Off();
			l3.Off();
			l4.Off();
		}
	}

	void running_lights() {
		entity	l1, l2, l3, l4;
		float	i;
		
		for ( i=1; i<=13; i++ ) {
			l1 = sys.getEntity ("rrun_" + i);
			l2 = sys.getEntity ("lrun_" + i);
			l3 = sys.getEntity ("trrun_" + i);
			l4 = sys.getEntity ("tlrun_" + i);
	
			l1.On();
			l1.startSoundShader ("cpu_light_sounds", SND_CHANNEL_VOICE );
			l2.On();
			l2.startSoundShader ("cpu_light_sounds", SND_CHANNEL_VOICE );
			l3.On();
			l3.startSoundShader ("cpu_light_sounds", SND_CHANNEL_VOICE );
			l4.On();
			l4.startSoundShader ("cpu_light_sounds", SND_CHANNEL_VOICE );
			
			sys.wait (0.15);
			
			l1.Off();
			l2.Off();
			l3.Off();
			l4.Off();
			
			sys.wait (0.15);
		}
	
	}

	void running_lights_thread() {
		while (1) {
			thread running_lights();
			sys.wait (2);
		}
	}

	void cache_sounds() {
		sys.cacheSoundShader ("cpu_bridge_down_6s");
		sys.cacheSoundShader ("cpu_arm_down_5s");		
		sys.cacheSoundShader ("cpu_bridge_rails");
		sys.cacheSoundShader ("bridge_rotation_6s");		
		sys.cacheSoundShader ("bridge_rotation_10s");		
		sys.cacheSoundShader ("cpu_light_sounds");	
		sys.cacheSoundShader ("cpu_shields");	
		sys.cacheSoundShader ("cpu_m3_start");
		sys.cacheSoundShader ("cpu_m3_stop");
		sys.cacheSoundShader ("cpu_m3_loop");
		sys.cacheSoundShader ("cpu_m4_start");
		sys.cacheSoundShader ("cpu_m4_stop");
		sys.cacheSoundShader ("cpu_m4_loop");

	}

	void fadeout_endroom() {
		
		$cspeaker_1.remove();
		$cspeaker_2.remove();
		$cspeaker_3.remove();
		$cspeaker_4.remove();
		
		$trigger_multiple_1.remove();
		$trigger_multiple_2.remove();
		$trigger_multiple_3.remove();
		$trigger_multiple_4.remove();
		
		$ctrigger_hurt_1.remove();
		$ctrigger_hurt_2.remove();
		$ctrigger_hurt_3.remove();
		$ctrigger_hurt_4.remove();
		
		//$cspeaker_1.fadeSound ( SND_CHANNEL_ANY, -60, 1 );
		//$cspeaker_2.fadeSound ( SND_CHANNEL_ANY, -60, 1 );
		//$cspeaker_3.fadeSound ( SND_CHANNEL_ANY, -60, 1 );
		//$cspeaker_4.fadeSound ( SND_CHANNEL_ANY, -60, 1 );
	}

	void main() 
	{
		cache_sounds();
		init_world();
		
		// Exec all other required threads here

//		thread move_pumps();
//		thread move_arm1();
		
		init_bridge();
		init_running_lights();
		thread running_lights_thread();
	}
}

//@doomscript-blueprint begin 6
//@source 15E81692
//@catalog 0C260740
//@node 34DA2B55-0 40 40
//@node 83B96544-0 330 40
//@node 327B6418-0 610 40
//@node A980EC98-0 890 40
//@node 5448A117-0 40 40
//@node 03906614-0 330 40
//@node 2DDA2050-0 40 40
//@node CAB680EC-0 330 40
//@node 804C3899-0 610 40
//@node A845E2F0-0 890 40
//@node 51489C5E-0 40 40
//@node F595F604-0 330 40
//@node 81F77A42-0 40 40
//@node 6FEF6462-0 330 40
//@node B215B558-0 610 40
//@node 5EC93311-0 890 40
//@node 999C5E8C-0 1170 40
//@node CE70E299-0 40 40
//@node 4E1323FC-0 330 40
//@node 41D02F8F-0 610 40
//@node E795293F-0 890 40
//@node FF5B28CB-0 1170 40
//@node B5E6ACCC-0 40 40
//@node B46561DA-0 330 40
//@node 03DCD7D6-0 610 40
//@node B77C4369-0 890 40
//@node 1E8B9F2A-0 1170 40
//@node A2C69603-0 40 40
//@node CE0F67C0-0 330 40
//@node 42C23D35-0 610 40
//@node B2CCF2D3-0 890 40
//@node 3510A8A9-0 1170 40
//@node 9ED17F06-0 40 40
//@node 56563F7E-0 330 40
//@node 14CF3353-0 610 40
//@node 42BB626D-0 890 40
//@node A217CD0A-0 1170 40
//@node A1950693-0 40 40
//@node EAEA587E-0 330 40
//@node 259EDBFE-0 610 40
//@node D74F7B6D-0 890 40
//@node 424D8A1F-0 1170 40
//@node A0C06350-0 40 40
//@node 2D261346-0 330 40
//@node 3D3D23F1-0 610 40
//@node 93D06395-0 890 40
//@node 7AA24E44-0 1170 40
//@node ACD07165-0 40 40
//@node 311AD99E-0 330 40
//@node CF6597DC-0 610 40
//@node 311AD99E-1 890 40
//@node B7A117A9-0 1170 40
//@node 8846F578-0 40 40
//@node 5255C6C2-0 330 40
//@node 6C881153-0 610 40
//@node E2513CD7-0 890 40
//@node 977F1B96-0 1170 40
//@node 4E61CA8C-0 1450 40
//@node 5069A2B9-0 1730 40
//@node 21F39839-0 2010 40
//@node 1FEBC00C-0 2290 40
//@node 948379E5-0 2570 40
//@node F929095E-0 2850 40
//@node 424171E2-0 3130 40
//@node EE9F3059-0 3410 40
//@node 693B14E7-0 3690 40
//@node 0EC11464-0 3970 40
//@node C87570E4-0 4250 40
//@node 22EF7167-0 4530 40
//@node B1479708-0 4810 40
//@node 21D6FACD-0 5090 40
//@node 86D73FFC-0 5370 40
//@node D9A37702-0 5650 40
//@node AE543404-0 5930 40
//@node D0628AAA-0 6210 40
//@node 3647D628-0 6490 40
//@node 731F532B-0 6770 40
//@node A1EC8527-0 7050 40
//@node 4DEFD0C9-0 7330 40
//@node 46547D2D-0 7610 40
//@node C10AAFB8-0 7890 40
//@node C2FEC05F-0 8170 40
//@node 21C7AC02-0 8450 40
//@node 9000D991-0 8730 40
//@node 62B1CACE-0 9010 40
//@node 08CDF36E-0 9570 40
//@node 0F5B5B1C-0 9570 40
//@node 1B21F2FF-0 9365 145
//@node DA649A93-0 9160 145
//@node B7A4E16B-0 9850 200
//@node 74329CD3-0 9625 305
//@node D311C2E2-0 9420 405
//@node D1A33038-0 9215 405
//@node BB78AE09-0 10410 200
//@node 6992E01A-0 10690 200
//@node 5734F091-0 10970 200
//@node 99FC49F9-0 10970 200
//@node E3790130-0 10745 305
//@node 2374FF4B-0 10540 405
//@node 5B2839CB-0 10335 405
//@node BB78AE09-1 11530 200
//@node 6992E01A-1 11810 200
//@node 5734F091-1 12090 200
//@node 38C80C08-0 12090 200
//@node 0CE7E67E-0 11865 305
//@node 55564EF4-0 11660 405
//@node 395C4821-0 11455 405
//@node BB78AE09-2 12650 200
//@node 6992E01A-2 12930 200
//@node 5734F091-2 13210 200
//@node A100A79C-0 13210 200
//@node BF84C801-0 12985 305
//@node F57BD23E-0 12780 405
//@node FAED1767-0 12575 405
//@node BB78AE09-3 13770 200
//@node 6992E01A-3 14050 200
//@node 5734F091-3 14330 200
//@node CEA14587-0 14330 40
//@node 1C1274B6-0 14125 145
//@node D549DC91-0 13920 145
//@node 60C5FAC2-0 14610 200
//@node C3F02C95-0 14385 305
//@node 949AA60B-0 14180 405
//@node 8BEBEE72-0 13975 405
//@node 7DB39C5D-0 14890 200
//@node 08D8D41E-0 14665 305
//@node 6C31E6B1-0 14460 405
//@node DD0C1059-0 14255 405
//@node 4984A4F8-0 15450 200
//@node 0DDD8398-0 15730 200
//@node 619A0E35-0 16010 200
//@node 7B322D51-0 15525 300
//@node 7DD979A2-0 16290 200
//@node CEA14587-1 16290 40
//@node C9AAF73F-0 16085 145
//@node 61CDD10E-0 15880 145
//@node 2C7E3743-0 16570 200
//@node ADE79C93-0 16345 305
//@node E609CA0A-0 16140 405
//@node FB279C2E-0 15935 405
//@node 5060DF64-0 16850 200
//@node ED9AED14-0 16625 305
//@node 1BD28869-0 16420 405
//@node 9196F088-0 16215 405
//@node 4984A4F8-1 17410 200
//@node 0DDD8398-1 17690 200
//@node 619A0E35-1 17970 200
//@node DD54AB0C-0 17485 300
//@node 10EE00BF-0 18250 200
//@node 5A4DEB95-0 18250 40
//@node 37A596BD-0 18045 145
//@node 2DF7ADFA-0 17840 145
//@node A132324C-0 18530 200
//@node 17BAFD1C-0 18305 305
//@node 0F4C2077-0 18100 405
//@node EABEE898-0 17895 405
//@node 4C939CFB-0 18810 200
//@node CAA37712-0 18585 305
//@node 3D0B4F44-0 18380 405
//@node 87C794CE-0 18175 405
//@node 4984A4F8-2 19370 200
//@node 0DDD8398-2 19650 200
//@node 619A0E35-2 19930 200
//@node E3540AD7-0 19445 300
//@node 9B6DA4E0-0 20210 200
//@node 192CD29E-0 20490 40
//@node 9B633761-0 20770 40
//@node 443B7421-0 21050 40
//@node AAA62243-0 21330 40
//@node 807BE4BA-0 21610 40
//@node 08EEE5DD-0 21890 40
//@node C714A889-0 40 40
//@node 4FCB83F1-0 330 40
//@node A8F41637-0 610 40
//@node F38CFDDB-0 890 40
//@node D0664F71-0 1170 40
//@node E99A981D-0 1450 40
//@node 7A5B93CD-0 1730 40
//@node C8C9483D-0 2010 40
//@node 4156F69E-0 2290 40
//@node 4B87AC86-0 2570 40
//@node 1C194A10-0 2850 40
//@node 4EDB7CCD-0 3130 40
//@node F158B720-0 3410 40
//@node 143CB1B8-0 3690 40
//@node 1AAB2EFB-0 3970 40
//@node 933170CA-0 4250 40
//@node BEA78FBB-0 4530 40
//@node 01F28C5C-0 4810 40
//@node D4E23F0B-0 5090 40
//@node 564CFAFC-0 5370 40
//@node 453398BE-0 5650 40
//@node 30D939BF-0 5930 40
//@node 51A992C3-0 6210 40
//@node E9BF78EF-0 40 40
//@node B97DE8C3-0 330 40
//@node FF05C25F-0 125 145
//@node 900E229E-0 -80 145
//@node 4206FCB7-0 610 200
//@node 8320EF3D-0 890 200
//@node EA4F935C-0 1170 200
//@node 5FF3EC52-0 1450 200
//@node DE3F42B3-0 1730 200
//@node A71FAE01-0 2010 200
//@node D9EA36F8-0 2290 200
//@node B4766BF0-0 2570 200
//@node DC747E62-0 2850 200
//@node 1C0B337C-0 3130 200
//@node 5603021D-0 3410 200
//@node 874CFCF6-0 3690 200
//@node DC747E62-1 3970 200
//@node 6121407E-0 4250 200
//@node 460875C9-0 4530 200
//@node DC747E62-2 4810 200
//@node 7BC7E042-0 5090 200
//@node D835B445-0 5370 200
//@node DD25F84F-0 5650 200
//@node C93E74BD-0 5930 200
//@node 70B8B160-0 6210 200
//@node 942EC5A7-0 6490 200
//@node 97B1228E-0 6285 305
//@node 180A5A14-0 6770 200
//@node 579B7525-0 6565 305
//@node C4E61FC5-0 40 40
//@node B769879B-0 330 40
//@node 841D744C-0 125 145
//@node 96E05166-0 -80 229
//@node 2A871B1A-0 610 200
//@node 4C65DE0C-0 890 40
//@node 6340266A-0 685 145
//@node D8700244-0 480 229
//@node FC032771-0 1170 200
//@node C6F4E65D-0 1450 40
//@node 54F7FDAB-0 1245 145
//@node 1DCEC1A1-0 1040 229
//@node BB89A96B-0 1730 40
//@node 52331878-0 2010 40
//@node 61A51442-0 1805 145
//@node 4780E2B3-0 1600 229
//@node D8209158-0 2290 40
//@node AF019097-0 2570 40
//@node 2177C22C-0 2365 145
//@node CD3C5F51-0 2850 40
//@node ACF71339-0 2645 145
//@node 4AAB29DF-0 3130 40
//@node D9B81F22-0 2925 145
//@node 21B043FF-0 2720 229
//@node C8DD1A9E-0 3410 40
//@node 1978CDAA-0 3205 145
//@node 08BDEDA5-0 3690 200
//@node DDF4F5D5-0 3970 200
//@node 8C8CEA79-0 4250 200
//@node 7B7E8C71-0 4045 305
//@node 3B5148B4-0 4530 40
//@node 35BD5C3E-0 4325 145
//@node 46FCE528-0 4810 200
//@node 59C3E818-0 5090 200
//@node 063023E4-0 5370 200
//@node 03849E1F-0 5165 305
//@node BCBA9D1C-0 5650 40
//@node B0A387AC-0 5445 145
//@node 46FCE528-1 5930 200
//@node 59C3E818-1 6210 200
//@node 063023E4-1 6490 200
//@node 33EF9686-0 6285 305
//@node A7A68EE0-0 6770 40
//@node CDB8858F-0 40 40
//@node D8A47862-0 330 40
//@node CE68FAF1-0 125 145
//@node 6F4A73D6-0 -80 145
//@node 69141B25-0 610 200
//@node FA30AE74-0 890 200
//@node E7A8F5F4-0 1450 200
//@node FA30AE74-1 1730 200
//@node DECBC4D0-0 40 40
//@node 1C552126-0 330 40
//@node F9916A86-0 125 145
//@node 539DB588-0 -80 145
//@node A2B1A6EF-0 610 40
//@node 8BC8E376-0 890 40
//@node 68F934A5-0 685 145
//@node 985DDC84-0 480 145
//@node FD4102FC-0 1170 200
//@node 13617C9B-0 965 305
//@node 34862743-0 1450 200
//@node FA5488E4-0 1730 200
//@node 04D7DF5C-0 1525 305
//@node E65F4F4B-0 1320 305
//@node 5CA800BE-0 2010 200
//@node 082E3F63-0 2570 360
//@node 08B17A93-0 2345 465
//@node 34AB171E-0 2850 360
//@node 119ABAE5-0 3130 360
//@node 6A2CA9D3-0 2925 460
//@node 97EC1BE2-0 3410 360
//@node 13F7E523-0 3690 360
//@node 19537563-0 3485 465
//@node 53608B3C-0 3970 200
//@node FD3EC465-0 4250 200
//@node 92530630-0 4045 305
//@node 2AD0D42A-0 40 40
//@node 1B210A8D-0 330 40
//@node 3E5EE831-0 125 145
//@node EFE0F756-0 -80 145
//@node 8EED1141-0 610 40
//@node 20833304-0 890 40
//@node 4CD365C0-0 685 145
//@node E9FA6FA1-0 480 145
//@node EFC281D0-0 1170 200
//@node 10FC2796-0 965 305
//@node 4C778115-0 1450 200
//@node 35B4AF38-0 1730 200
//@node BD3C7314-0 1505 305
//@node C5675690-0 2010 200
//@node 7ECA91E1-0 2290 200
//@node 2DB8231A-0 2085 300
//@node AAC9E44F-0 1880 300
//@node 87189027-0 2570 200
//@node 83BAD57A-0 2365 300
//@node F4A05A8C-0 2850 200
//@node FFE6B34E-0 3130 200
//@node 11012A71-0 2925 305
//@node 82A6785A-0 3410 200
//@node 6FBF79B9-0 3690 200
//@node 90E5335D-0 3485 305
//@node B6C081C8-0 40 40
//@node 44C6EBB5-0 330 40
//@node 9A641CCF-0 125 145
//@node 7721F7DE-0 -80 145
//@node 443812DF-0 610 40
//@node 0D69385A-0 890 40
//@node F3641241-0 685 145
//@node 702E14B6-0 480 145
//@node 191EFEF6-0 1170 200
//@node 47695528-0 965 305
//@node 905CC29F-0 1450 200
//@node DFE53650-0 1730 200
//@node 76854BE4-0 1505 305
//@node 9E221422-0 2010 200
//@node 49D3CBE3-0 2290 200
//@node FFA4D055-0 2085 300
//@node B1F2200A-0 1880 300
//@node AF894A01-0 2570 200
//@node 3DDC4BC2-0 2365 300
//@node 12663E0E-0 2850 200
//@node 661F00B2-0 3130 200
//@node E1EFF0F9-0 2925 305
//@node 2A4AD028-0 3410 200
//@node A11C0377-0 3690 200
//@node E00814A3-0 3485 305
//@node 6FD552EE-0 40 40
//@node 683002D6-0 330 40
//@node 35E168A4-0 125 145
//@node 194F13F8-0 -80 145
//@node C04BC38D-0 610 40
//@node 1E6FEA5C-0 890 40
//@node 87DCB14F-0 685 145
//@node 1B0B048E-0 480 145
//@node 23D3C7CA-0 1170 200
//@node 1ACE6F75-0 965 305
//@node 3478E32D-0 1450 200
//@node 8DE8B60F-0 1730 200
//@node 84B34509-0 1505 305
//@node B3467AD8-0 2010 200
//@node 07229784-0 2290 200
//@node A4AC6279-0 2570 200
//@node 86E6A379-0 2365 300
//@node D0D78D84-0 2160 300
//@node AA0E5BBF-0 2850 200
//@node 01117494-0 2645 300
//@node BFF470B4-0 3130 200
//@node 37D18D9B-0 3410 200
//@node 8884A627-0 3205 305
//@node 3AF6F322-0 3690 200
//@node 1BD17C9B-0 3970 200
//@node 281BE29F-0 3765 305
//@node 2EEE3719-0 40 40
//@node 9024194F-0 330 40
//@node 355EEC67-0 125 145
//@node 172384A7-0 -80 145
//@node E568CCE8-0 610 200
//@node 8F1BE165-0 385 305
//@node 04637F20-0 180 405
//@node E4A34E9C-0 -25 405
//@node 378DAD35-0 890 200
//@node 362040C1-0 665 305
//@node 22ED2A23-0 460 405
//@node 84D5C7C1-0 255 405
//@node 73082A22-0 1170 200
//@node D33C6C1D-0 945 305
//@node CE69790D-0 740 405
//@node E03402FB-0 535 405
//@node D7FA1101-0 1450 200
//@node F8BCE967-0 1225 305
//@node 4C3C8150-0 1020 405
//@node 8C7688AA-0 815 405
//@node 4E97054F-0 2010 200
//@node BD447658-0 2290 200
//@node 50886799-0 2570 200
//@node 73E8D6B2-0 2850 200
//@node 43D6A3B8-0 40 40
//@node 99E55142-0 330 40
//@node CC328F4F-0 125 145
//@node 2D8657CD-0 -80 145
//@node 2854FD3B-0 610 200
//@node 15C47F5F-0 385 305
//@node 08CF0F36-0 180 405
//@node 84BB87AC-0 -25 405
//@node 0B9ED4CE-0 890 200
//@node 6761D99F-0 665 305
//@node 6CEFE8E5-0 460 405
//@node 9B9AD279-0 255 405
//@node 5B50D973-0 1170 200
//@node 5ED339DC-0 945 305
//@node 9E44ADE5-0 740 405
//@node 8527A801-0 535 405
//@node 0C8D03F0-0 1450 200
//@node 948CFB91-0 1225 305
//@node 91898017-0 1020 405
//@node EF50D365-0 815 405
//@node 0B5F5FE0-0 2010 200
//@node 153A168F-0 2290 200
//@node E0CB1041-0 2570 200
//@node 357C76D0-0 2850 200
//@node D783C7E2-0 3130 200
//@node D2D1E051-0 3410 200
//@node BF72CF43-0 3690 200
//@node 211F2CFA-0 3970 200
//@node 24C0B1DE-0 4250 200
//@node 5AF1FA9A-0 4530 200
//@node AA23857D-0 4810 200
//@node 958A1EEC-0 5090 200
//@node 97DBB657-0 5370 200
//@node 24C0B1DE-1 5650 200
//@node 39027751-0 40 40
//@node D969C556-0 330 40
//@node 4FD08E25-0 125 145
//@node F1240832-0 610 200
//@node C53166ED-0 890 200
//@node B832CE32-0 40 40
//@node 386F3DD8-0 330 40
//@node B9A75B4C-0 610 40
//@node B136BEF1-0 890 40
//@node 06D7E8EB-0 1170 40
//@node 7DA24710-0 1450 40
//@node 76CD5033-0 1730 40
//@node 5D3B9D1A-0 2010 40
//@node 5E2D1769-0 2290 40
//@node C98D140F-0 2570 40
//@node 63D862C9-0 2850 40
//@node 6B4F3CC6-0 3130 40
//@node 0FD6F52A-0 3410 40
//@node F24C5D64-0 3690 40
//@node 5E3A0FD4-0 40 40
//@node 1057419E-0 330 40
//@node 4C25EAEB-0 610 40
//@node B2804C58-0 890 40
//@node E31362FD-0 1170 40
//@node 88FFE7A1-0 1450 40
//@node DC3E8958-0 1730 40
//@node 75E427EB-0 2010 40
//@node 4FDB9C5A-0 2290 40
//@node BAC4E9D1-0 2570 40
//@node 8B5C1A48-0 2850 40
//@node 6DD3BDDB-0 3130 40
//@node 18AB83CA-0 3410 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node 5531D4DD-0 610 40
//@node 2B57867C-0 890 40
//@node 848A5B3C-0 1170 40
//@node 85A41754-0 1450 40
//@doomscript-blueprint end
