namespace map_alphalabs2 {
	#define XMACH_BASE_SPEED	2
	#define XMACH_JOINT_SPEED	2
	//#define DEBUG				1
	//#define VERBOSE				1
	//#define ENABLE_BEAM			1

	float	spawn_start_imp = 0;			// Is it ok to spawn in the first imp ?
	float	surprise_pinky_spawn = 0; 	// Did we kill the imp, to spawn in the surprise pinky at the CP ?
	float	surprise_pinky_dead = 0;  		// Did we kill the surprise pinky ? (Used to prevent retriggers)
	float	xmach_current = 0;				// Current rotation angle it's at
	float	xmach_value = 0;				// What is the current location of the machine ? (1-12)

	void bathroom_init() 
	{
		$bathroom_swinglamp_anchor.sway( 2.5, 1, '0 0 15' );
	}

	void entrance_door() 
	{
		$start_light1.Off();
		$start_light2.Off();
		sys.trigger ($start_light3);
		sys.trigger ($start_particle);
		sys.wait (1);
		$start_light2.On();
	}

	////////////////////////////////////////////////////
	//	Setup binds and times and initial movements etc...
	////////////////////////////////////////////////////
	void setup_objects()
	{
		vector	beam_dst;
	
		$mazelight_red_1.fadeOutLight (0.1);
		$mazelight_red_2.fadeOutLight (0.1);
		$mazelight_red_3.fadeOutLight (0.1);

		//$mfs_redlight1.fadeOutLight (0.1);
		//$mfs_redlight2.fadeOutLight (0.1);
		//$mfs_redlight3.fadeOutLight (0.1);


		$claw_arm_lower.time (0.75);
		$claw_arm_lower.accelTime (0.25);
		$claw_arm_lower.decelTime (0.25);
		$claw_arm_upper.time (0.75);
		$claw_arm_upper.accelTime (0.25);
		$claw_arm_upper.decelTime (0.25);
		$claw_arm_wrist.time (0.75);
		$claw_arm_wrist.accelTime (0.25);
		$claw_arm_wrist.decelTime (0.25);
		$claw_revolver.time (2);
		$claw_tooth_1.time (0.5);
		$claw_tooth_2.time (0.5);

		$claw_arm_upper.rotateOnce ('-40 0 0');
		$claw_arm_lower.rotateOnce ('50 0 0');
		$claw_arm_wrist.rotateOnce ('180 0 0');

		$ddoor_1_anchor.time (1);
		$ddoor_2_anchor.time (1);
		$ddoor_1_anchor.accelTime (0.25);
		$ddoor_2_anchor.accelTime (0.25);
		$ddoor_1_anchor.decelTime (0.25);
		$ddoor_2_anchor.decelTime (0.25);

		$lobby1left.disable();
		$lobby1right.disable();
		$mal_func_door_55.disable();
		$mal_func_door_56.disable();

		sys.wait( 1 );

		thread entrance_door();
		
		//$br_secretdoor.speed (96);
		$secret_door2.time (1.5);
		$secret_ladder.time (3);
		$secret_ladder.move (DOWN, 106);
		$exit_ladder.move(DOWN, 126);

		$elight.rotate ('0 -400 0');

		$deadmarine_mover.speed (128);
		$deadmarine_mover.moveTo ($deadmarine_path1);
		
		//break lights in machine room
		sys.trigger($light_4678);
		sys.trigger($light_4679);
		sys.trigger($light_4683);
		sys.trigger($light_4684);
	}

	void br_move_secret_door()
	{
		$br_secretdoor.time(.5);
		$br_secretdoor.accelTime(.25);
		$br_secretdoor.decelTime(.25);
		$br_secretdoor.moveTo ($br_secretdoor_path1);
		sys.waitFor ($br_secretdoor);
		sys.wait (0.5);
		$br_secretdoor.time(1.0);
		$br_secretdoor.accelTime(.5);
		$br_secretdoor.decelTime(.5);
		$br_secretdoor.moveTo ($br_secretdoor_path2);
		sys.waitFor ($br_secretdoor);
	}

	void emp_blast() 
	{
		float	i;
		entity emplight, empspeaker;
		
		for (i=1; i<=10; i++) 
		{
			emplight = sys.getEntity ("emplight_" + i);
			emplight.On();
			empspeaker = sys.getEntity ("empspeaker_" + i);
			sys.trigger (empspeaker);
			sys.wait (0.1);
			emplight.Off();
		}
	}

	void open_secrethatch()
	{
		sys.trigger ($mfs_secretdoor_open);
		$secret_door2.moveTo ($secret2_path1);
		sys.waitFor ($secret_door2);
		$secret_door2.moveTo ($secret2_path2);
		sys.waitFor ($secret_door2);
		$secret_ladder_door.open(); 
		sys.waitFor ($secret_ladder_door);
		sys.trigger ($mfs_speaker_secretladder);
		$secret_ladder.move (UP, 106);
	}

	///////////////////////
	// 	Mal's machine
	///////////////////////
	void spinner()
	{
		while (1)
		{
			$slidearm.bind ($slidearm_anchor);
			$can1.bind ($slidearm);
			$can2.bind ($maindrum);
			$slidearm_anchor.time (2);
			$slidearm.time (2);
			$can1.time (1);
			$can2.time (1);
			$maindrum.time (1);
			$plunger.time (1);
			
			//canister1 feed from main drum
			sys.trigger ($mfs_roller_speaker_in);
			$slidearm_anchor.moveTo ($slidearm_p2);
			sys.wait (.1);
			$slidearm.rotateOnce (' 0 0 -90 ');
			sys.waitFor ($slidearm_anchor);
			
			//canister1 feed into machine
			sys.wait (1.5);
			$can1.unbind();
			$can1.bind ($plunger);
			sys.trigger ($mfs_plunger_in);
			$plunger.move (FORWARD,96);
			sys.waitFor ($plunger);			// was $can1
			$can1.unbind();
			sys.trigger ($mfs_can1_speaker);
			$can1.moveTo ($can_target);
			sys.waitFor ($can1);
			
			//canister1 teleport
			$can1.time (.01);
			$can1.moveTo ($canspawn);
			sys.waitFor ($can1);
			$can1.bind ($maindrum);
			
			//slidearm reset
			sys.trigger ($mfs_roller_speaker_out);
			$slidearm_anchor.moveTo ($slidearm_p1);
			$slidearm.rotateOnce (' 0 0 90 ');
			sys.trigger ($mfs_plunger_out);
			$plunger.move (BACK,96);
			sys.waitFor ($slidearm_anchor);
			
			//main drum rotation
			sys.trigger ($mfs_drum_speaker);
			$maindrum.rotateOnce (' 0 0 -90 ');
			sys.waitFor ($maindrum);
			$can2.unbind();
			sys.wait (.1);
			
			//canister2 feed from main drum
			$can2.bind ($slidearm);
			sys.trigger ($mfs_roller_speaker_in);
			sys.trigger ($mfs_can2_speaker);
			$slidearm_anchor.moveTo ($slidearm_p2);
			sys.wait (.1);
			$slidearm.rotateOnce (' 0 0 -90 ');
			sys.waitFor ($slidearm_anchor);
			
			//canister2 feed into machine
			sys.wait (1.5);
			$can2.unbind();
			$can2.bind ($plunger);
			//$can2.move (FORWARD,232);
			sys.trigger ($mfs_plunger_in);
			$plunger.move (FORWARD,96);
			sys.waitFor ($plunger);
			$can2.unbind();
			sys.trigger ($mfs_can2_speaker);
			$can2.moveTo ($can_target);
			sys.waitFor ($can2);
			
			//canister2 teleport
			$can2.time (.01);
			$can2.moveTo ($canspawn);
			sys.waitFor ($can2);
			$can2.bind ($maindrum);
			
			//slidearm reset
			sys.trigger ($mfs_roller_speaker_out);
			$slidearm_anchor.moveTo ($slidearm_p1);
			$slidearm.rotateOnce (' 0 0 90 ');
			sys.trigger ($mfs_plunger_out);
			$plunger.move (BACK,96);
			sys.waitFor ($slidearm_anchor);
			
			//main drum rotation
			sys.trigger ($mfs_drum_speaker);
			$maindrum.rotateOnce (' 0 0 -90 ');
			sys.waitFor ($maindrum);
			$can1.unbind();
			sys.wait (.1);
		}
	}

	// The other half of the rotating tube-thingy machine...
	void mach2()
	{
		entity	ent, ent2;
		vector	bm_origin, bm_origin2;
		bm_origin = $mach2_path1.getOrigin();
		
		while (1)
		{
			$mach2_tube.time (2);
			$mach2_tube.setOrigin (bm_origin);
			sys.trigger ($mfs_speaker_tube);
			$mach2_tube.moveTo ($mach2_path2);
			sys.waitFor ($mach2_tube);
			sys.wait (1);
			
			$mach2_flap_left_anchor.time (1);
			$mach2_flap_right_anchor.time (1);
			
			sys.trigger ($mfs_speaker_flap_close);
			
			$mach2_flap_left_anchor.rotateOnce ('0 0 -90');
			$mach2_flap_right_anchor.rotateOnce ('0 0 90');
			sys.waitFor ($mach2_flap_right_anchor);
			sys.trigger ($mfs_speaker_decent);
			
			$mach2_tube.moveTo ($mach2_path3);
			sys.waitFor ($mach2_tube);
			sys.trigger ($mfs_speaker_flap_open);
			
			$mach2_flap_left_anchor.rotateOnce ('0 0 90');
			$mach2_flap_right_anchor.rotateOnce ('0 0 -90');
			sys.waitFor ($mach2_flap_right_anchor);
			sys.wait (0.2);
		}
	}
	
	///////////////////////
	// 	Jerry's machine
	///////////////////////
	void spawn_canister() 
	{
		vector startlocation;
		startlocation = $canister1.getWorldOrigin();
		
		$spinner1.time (1.5);
		$spinner1.accelTime (.75);
		$spinner1.decelTime (.75);
		$spinner2.time (1.5);
		$spinner2.accelTime (.75);
		$spinner2.decelTime (.75);
		$pivot_point.time (1.75);
		$pivot_point.accelTime (.75);
		$pivot_point.decelTime (.75);
		$body.time (1);
		$body.accelTime (.75);
		$body.decelTime (.25);
		$middle_arm.time (1.5);
		$middle_arm.accelTime (.75);
		$middle_arm.decelTime (.75);
		$clamp_arm.time (1.5);
		$clamp_arm.accelTime (.75);
		$clamp_arm.decelTime (.75);
		$can_door1.time (1);
		$can_door1.accelTime (.75);
		$can_door1.decelTime (.25);
		$can_door2.time (1);
		$can_door2.accelTime (.75);
		$can_door2.decelTime (.25);
		
		while (1) 
		{
			//NOTE - machine starts in lowered position
			$canister1.bind ($clamp_arm);
			//move arms up
			$spinner1.rotateOnce ('0 720 0');
			$spinner2.rotateOnce ('0 720 0');
			$clamp_arm.move (UP, 40 );
			$middle_arm.move (UP, 60);
			$pivot_point.moveTo ($p2);
			sys.waitFor ($pivot_point);
			//close doors
			$can_door1.rotateOnce ('0 0 90');
			$can_door2.rotateOnce ('0 0 90');
			//rotate machine
			$body.rotateOnce (' 0 0 90 ');
			sys.waitFor ($body);
			//move arms in
			$spinner1.rotateOnce ('0 -720 0');
			$spinner2.rotateOnce ('0 -720 0');
			$middle_arm.move (-90, 60);
			$clamp_arm.move (-90, 40 );
			sys.waitFor ($clamp_arm);
			//release canister
			$canister1.unbind();
			//move arms out
			$spinner1.rotateOnce ('0 720 0');
			$spinner2.rotateOnce ('0 720 0');
			$middle_arm.move (90, 60);
			$clamp_arm.move (90, 40 );
			sys.waitFor ($clamp_arm);
			$body.rotateOnce (' 0 0 -90 ');
			sys.waitFor ($body);
			//move canister back to start position
			$canister1.setWorldOrigin (startlocation);
			//move arms down
			$can_door1.rotateOnce ('0 0 -90');
			$can_door2.rotateOnce ('0 0 -90');
			$spinner1.rotateOnce ('0 -720 0');
			$spinner2.rotateOnce ('0 -720 0');
			$pivot_point.moveTo ($p1);
			$middle_arm.move (DOWN, 60);
			$clamp_arm.move (DOWN, 40 );
			sys.waitFor ($clamp_arm);
		}
	}

	void xmachroom() 
	{
		while (1) 
		{
			thread spawn_canister();
			sys.wait (2);
		}
	}

	void sci_kill_lights() 
	{
		$mazelight_1.Off();
		$mazelight_2.Off();
		sys.wait (.75);
		//sys.trigger ($mazeimp_1);
		//sys.trigger ($mazeimp_2);
		//sys.trigger ($mazeimp_3);
		sys.trigger ($open_impdoors);
		sys.trigger ($imp_maze_wakeup);
		
		//simulate lantern flash
		sys.wait ( .40 );
		$lantern_flash.On();
		sys.wait (.15);
		$lantern_flash.Off();
		
		sys.trigger ($maze_bloodpool);
		sys.trigger ($maze_bloodpool_1);
		sys.trigger ($maze_bloodpool_2);
		sys.trigger ($maze_bloodpool_3);
		sys.trigger ($maze_bloodpool_4);
		$mazelight_red_1.fadeInLight (4);
		$mazelight_red_2.fadeInLight (4);
		$mazelight_red_3.fadeInLight (4);
		sys.wait (4);
		$mazelight_1.fadeInLight (4);
		$mazelight_2.fadeInLight (4);
	}
/*
	void mfs_redlights()
	{
		$mfs_redlight1.fadeInLight (4);
		$mfs_redlight2.fadeInLight (4);
		$mfs_redlight3.fadeInLight (4);	
	}
*/
	// First posessed guy...
	void move_soldier() 
	{
		float	i;
		entity	ent;
		$wrist_mover.speed (128);
		
		sys.trigger ($start_fadeout_blue);
		sys.trigger ($start_fadeout_white);
		//sys.trigger ($start_fadeout_sky);
		
		for (i=1; i<=7; i++) 
		{
			ent = sys.getEntity ("soldier_path" + i);
			$wrist_mover.moveTo (ent);
			sys.waitFor ($wrist_mover);
			if (i == 1) 
			{
				sys.trigger ($explodinglight_trigger_1);
				sys.trigger ($explodinglight_trigger_1a);
				sys.trigger ($explodinglight_trigger_1b);
				sys.trigger ($explodinglight_trigger_1c);
				//$body_spinner.rotate ('-10 20 -25');
				sys.wait (1);
				$wrist_mover.speed (200);
			}
			if (i == 2) 
			{
				sys.trigger ($explodinglight_trigger_2);
				sys.trigger ($explodinglight_trigger_2a);
				sys.trigger ($explodinglight_trigger_2b);
				sys.trigger ($explodinglight_trigger_2c);
			}
			if (i == 3) 
			{
				sys.trigger ($explodinglight_trigger_3);
				sys.trigger ($explodinglight_trigger_3a);
				sys.trigger ($explodinglight_trigger_3b);
				sys.trigger ($explodinglight_trigger_3c);
				$tim_func_door_202.open();
				$tim_func_door_203.open();
			}
			if ( i == 4) 
			{
				$tim_func_door_202.close();
				$tim_func_door_203.close();
				$tim_func_door_203.lock(1);
				$tim_func_door_202.lock(1);
				
				//disable player forcefield
				$trigger_once_56.disable();
				
				$env_ragdoll_marine1_1.unbind();
				sys.trigger ($start_fadein_blue);
				sys.trigger ($start_fadein_white);
				//sys.trigger ($start_fadein_sky);
				spawn_start_imp = 1;
			}
		}
		$wrist_mover.remove();
		$env_ragdoll_marine1_1.remove();
	}

	void spawn_imp_entrance() 
	{
		while (1) 
		{
			if (spawn_start_imp == 1) 
			{
				sys.trigger ($entrance_relay);
				sys.trigger ($trigger_relay_45);
				sys.trigger ($trigger_relay_47);
				sys.trigger ($impstart_influence);
				sys.wait (1);
				sys.trigger ($start_imp_forcefield);
				sys.trigger ($blowout_window);
				sys.wait (1);
				//sys.trigger ($surprise_imp_1);
				return;
			}
			sys.wait (1);
		}
	}

	// Called when the first imp dies
	void unlock_start_door() 
	{
		$tim_func_door_202.lock(0);
		$tim_func_door_203.lock(0);	
	}
	
	// Guy getting pulled into the ceiling @ start of the map	
	void gank_deadsoldier()
	{
		sys.trigger ($impscream);
		sys.wait (1);
		$deadmarine_mover.moveTo ($deadmarine_path2);
		sys.trigger ($impscream_crunch_speaker);
		sys.wait (1.5);
		$deadmarine_mover.moveTo ($deadmarine_path3);
		sys.wait (1.75);
		$xenv_ragdoll_marine1_0.remove();
		//sys.trigger ($imp_scream);
		//sys.wait (1);
		sys.trigger ($bodypart_1);
		sys.wait (1);
		sys.trigger ($bodypart_2);
		sys.wait (1.25);
		sys.trigger ($bodypart_3);
		sys.wait (0.75);
		sys.trigger ($bodypart_4);
		sys.wait (1);
		sys.trigger ($bodypart_5);
		sys.wait (1.5);
		sys.trigger ($bodypart_6);
		sys.wait (5);
		sys.trigger ($bodypart_7);
	}

	// Trap door in ceiling that a dead scientist drops out of
	void open_cp_trapdoor() 
	{
		$trapdoor_1_anchor.time (0.5);
		$trapdoor_1_anchor.rotateOnce ('0 0 45');
	}
	
	void exit_ladder_move()
	{
		$exit_ladder.time(2);
		$exit_ladder.accelTime(.5);
		$exit_ladder.decelTime(1.5);
		sys.trigger ($speaker_up_2seconds);
		$exit_ladder.move(UP, 48);
		sys.waitFor($exit_ladder);
		sys.wait(4);
		$exit_ladder.time(2);
		$exit_ladder.accelTime(.5);
		$exit_ladder.decelTime(1.5);
		sys.trigger ($speaker_down_2seconds);
		$exit_ladder.move(DOWN, 48);
		sys.waitFor($exit_ladder);
		sys.wait(5);
		$exit_ladder.time(3);
		$exit_ladder.accelTime(1);
		$exit_ladder.decelTime(2);
		sys.trigger ($speaker_up_3seconds);
		$exit_ladder.move(UP, 64);
		sys.waitFor($exit_ladder);
		sys.wait(4);
		$exit_ladder.time(2);
		$exit_ladder.accelTime(.5);
		$exit_ladder.decelTime(1.5);
		sys.trigger ($speaker_down_2seconds);
		$exit_ladder.move(DOWN, 64);
		sys.waitFor($exit_ladder);
		sys.wait(20);
		$exit_ladder.time(4);
		$exit_ladder.accelTime(1);
		$exit_ladder.decelTime(3);
		sys.trigger ($speaker_up_4seconds);
		$exit_ladder.move(UP, 126);
		sys.waitFor($exit_ladder);
		$exit_ladder_clip.remove();
		//trigger gui
		sys.trigger( $func_static_5089);
		$func_static_5089.setShaderParm (7, 1);
		//turn on ladder lights
		sys.trigger( $ladder_lights_relay);
		
	}

	////////////////////////////////////////////////////
	//	Main
	////////////////////////////////////////////////////
	void main() 
	{
		setup_objects();
		thread bathroom_init();
		thread spinner();
		thread mach2();
		thread spawn_canister();
	}
}

//@doomscript-blueprint begin 6
//@source 2A1E03F8
//@catalog 0C260740
//@node 88633A1E-0 40 40
//@node 4909E9AF-0 330 40
//@node 25E0B944-0 40 40
//@node 18B03E6D-0 330 40
//@node 0699BF0A-0 610 40
//@node 198BD513-0 890 40
//@node 37D593B4-0 1170 40
//@node A452DDE9-0 1450 40
//@node 080DB070-0 1730 40
//@node 7AEA71C1-0 40 40
//@node 2B76D3BD-0 330 40
//@node BFC6C940-0 610 40
//@node 9D6C2A6B-0 890 40
//@node 537F4114-0 1170 40
//@node 1F0600F3-0 1450 40
//@node 68E08586-0 1730 40
//@node 311CC94F-0 2010 40
//@node 5A9139B6-0 2290 40
//@node F227BF8F-0 2570 40
//@node 26452DD6-0 2850 40
//@node F5B3F0E9-0 3130 40
//@node C6664068-0 3410 40
//@node A3136C09-0 3690 40
//@node 63DCC405-0 3970 40
//@node 060C10C4-0 4250 40
//@node BDBB5B37-0 4530 40
//@node 0ECCFC94-0 4810 40
//@node F9DA67C4-0 5090 40
//@node 68E4C4DD-0 5370 40
//@node D75D399E-0 5650 40
//@node E57669B3-0 5930 40
//@node B9A7A800-0 6210 40
//@node 76A47546-0 6490 40
//@node 2316341D-0 6770 40
//@node A75116D1-0 7050 40
//@node 800FE168-0 7330 40
//@node 77C99D40-0 7610 40
//@node 66EE617B-0 7890 40
//@node 1EA70F50-0 8170 40
//@node 2678B98E-0 8450 40
//@node 8ECD3BD1-0 8730 40
//@node A3FBCB68-0 9010 40
//@node BADE6470-0 9290 40
//@node 38C7B628-0 9570 40
//@node 80C4449E-0 9850 40
//@node DE2D095D-0 10130 40
//@node 162AB4A2-0 10410 40
//@node ACB5487C-0 10690 40
//@node 10F856AB-0 10970 40
//@node 7B5860B2-0 11250 40
//@node 39418D5B-0 11530 40
//@node 17B5D4C9-0 40 40
//@node B4E22A30-0 330 40
//@node 9FCD3544-0 610 40
//@node 3D854829-0 890 40
//@node 5C797C42-0 1170 40
//@node 101211C1-0 1450 40
//@node 83675442-0 1730 40
//@node 6E6B65E2-0 2010 40
//@node 4B2C0EEC-0 2290 40
//@node 55CD8653-0 2570 40
//@node 6F8D39DF-0 2850 40
//@node 101211C1-1 3130 40
//@node 5DB94DBC-0 40 40
//@node 067A26E3-0 610 40
//@node E0BF6E2E-0 125 145
//@node A9D7FC61-0 -80 145
//@node F73A9A0B-0 610 200
//@node 061946D6-0 385 305
//@node 3C1E28F8-0 180 405
//@node A8552D1D-0 -25 405
//@node 26004E41-0 1170 200
//@node 7930115D-0 1170 200
//@node E059032D-0 945 305
//@node 781F5665-0 740 405
//@node DB795661-0 535 405
//@node 9964E242-0 1730 200
//@node 3B52D822-0 1245 300
//@node B57C895B-0 2010 200
//@node 9CF41F7D-0 2290 200
//@node 9BEA2678-0 40 40
//@node DE0C8943-0 330 40
//@node DFEB8260-0 610 40
//@node 13534616-0 890 40
//@node 267355E1-0 1170 40
//@node 13534616-1 1450 40
//@node D26AB0DE-0 1730 40
//@node D1062ED1-0 2010 40
//@node F917A09C-0 2290 40
//@node 3A632480-0 2570 40
//@node 9E3B1E9E-0 40 40
//@node 7942080D-0 330 40
//@node EB7AE5CF-0 125 145
//@node 58DBCAED-0 610 200
//@node 44E48E7B-0 890 200
//@node 3CAB2D3A-0 1170 200
//@node E56101CC-0 1450 200
//@node 758EAC5E-0 1730 200
//@node 7EAB1AE7-0 2010 200
//@node 4948553E-0 2290 200
//@node 4C972A63-0 2570 200
//@node E68A13B5-0 2850 200
//@node 4A4D64E8-0 3130 200
//@node A94F99FB-0 3410 200
//@node 096D25E1-0 3690 200
//@node 23DDA653-0 3970 200
//@node 89842480-0 4250 200
//@node C0E2A26A-0 4530 200
//@node E8FF5D3B-0 4810 200
//@node 917346E9-0 5090 200
//@node 13EFC367-0 5370 200
//@node 30D38672-0 5650 200
//@node 8B41BF04-0 5930 200
//@node E8FF5D3B-1 6210 200
//@node 947FF483-0 6490 200
//@node 76FE78D5-0 6770 200
//@node 96BAD680-0 7050 200
//@node 11CF25CD-0 7330 200
//@node 1D47B542-0 7610 200
//@node 96BAD680-1 7890 200
//@node DC3BFB73-0 8170 200
//@node E2EA3945-0 8450 200
//@node 15C4518E-0 8730 200
//@node 8336BFAC-0 9010 200
//@node 1A47EC68-0 9290 200
//@node 6601C8C0-0 9570 200
//@node 89842480-1 9850 200
//@node FF775452-0 10130 200
//@node 3F97F4BB-0 10410 200
//@node 9DC69CCC-0 10690 200
//@node 377E68B6-0 10970 200
//@node 096D25E1-1 11250 200
//@node 6EF054D2-0 11530 200
//@node 4A4D64E8-1 11810 200
//@node 2D822472-0 12090 200
//@node A94F99FB-1 12370 200
//@node 096D25E1-2 12650 200
//@node 23DDA653-1 12930 200
//@node 89842480-2 13210 200
//@node C0E2A26A-1 13490 200
//@node 377E68B6-1 13770 200
//@node D7F3943A-0 14050 200
//@node 13EFC367-1 14330 200
//@node 30D38672-1 14610 200
//@node 8B41BF04-1 14890 200
//@node 377E68B6-2 15170 200
//@node 2D822472-1 15450 200
//@node 4B9BD964-0 15730 200
//@node DD42AA01-0 16010 200
//@node 031807E0-0 16290 200
//@node 31885FC7-0 16570 200
//@node DD42AA01-1 16850 200
//@node 3CAB2D3A-1 17130 200
//@node E2EA3945-1 17410 200
//@node 15C4518E-1 17690 200
//@node 8336BFAC-1 17970 200
//@node 1A47EC68-1 18250 200
//@node 6601C8C0-1 18530 200
//@node 89842480-3 18810 200
//@node FF775452-1 19090 200
//@node 3F97F4BB-1 19370 200
//@node 9DC69CCC-1 19650 200
//@node E8FF5D3B-2 19930 200
//@node 096D25E1-3 20210 200
//@node 09CA119E-0 40 40
//@node 6EB7C63E-0 330 40
//@node B887F2C5-0 105 145
//@node F9C0FE5D-0 1170 40
//@node B8BB5E47-0 405 145
//@node 03AF4D63-0 1450 200
//@node 58CCE38C-0 1730 200
//@node 56EBC33A-0 965 300
//@node 39F48D64-0 2010 200
//@node EB6E80CF-0 2290 200
//@node DCBCB9B5-0 2570 200
//@node DB7A43BF-0 2850 200
//@node 76DBDEEF-0 3130 200
//@node 351110A2-0 3410 200
//@node A80CB456-0 3690 200
//@node 98A66EC3-0 3970 200
//@node 807A8F19-0 4250 200
//@node C54160FF-0 4530 200
//@node 8E6584BF-0 4810 200
//@node F68CBF30-0 5090 200
//@node DCBCB9B5-1 5370 200
//@node 785F9F7A-0 5650 200
//@node A9EC7C1A-0 5930 200
//@node 80E55A26-0 6210 200
//@node C54160FF-1 6490 200
//@node B44B7408-0 6770 200
//@node 478F1248-0 40 40
//@node 05485937-0 330 40
//@node F9C52AC7-0 105 145
//@node 88B264E5-0 610 40
//@node 3E5679F1-0 890 40
//@node B6E8B32A-0 1170 40
//@node 2F7DEBE4-0 1450 40
//@node 879C2F4A-0 1730 40
//@node 6DEE53BD-0 2010 40
//@node 9FC07B11-0 2290 40
//@node D4B43EB6-0 2570 40
//@node E7249039-0 2850 40
//@node DF986EB8-0 3130 40
//@node 7EE0C9B9-0 3410 40
//@node 424BA213-0 3690 40
//@node 0D77C9A9-0 3970 40
//@node C714E295-0 4250 40
//@node 339CAECE-0 4530 40
//@node 5D953FFF-0 4810 40
//@node 12D8307B-0 5090 40
//@node 2BBC8368-0 5370 40
//@node 77C692BA-0 5650 40
//@node B28F46A7-0 5930 40
//@node 5556CF6D-0 6210 40
//@node 28C608E3-0 6490 40
//@node 17130C34-0 6770 40
//@node 59B70302-0 7050 40
//@node 09344F03-0 7330 40
//@node 0A592FBE-0 7125 145
//@node 5EE6A025-0 7610 200
//@node E4AA10A3-0 7890 200
//@node F75883E6-0 8170 200
//@node F4E272AE-0 8450 200
//@node F7DE7BF2-0 8730 200
//@node 73D19B5F-0 9010 200
//@node EE9C7088-0 9290 200
//@node 9A8F0561-0 9570 200
//@node D3770C46-0 9850 200
//@node FF24B369-0 10130 200
//@node F096164B-0 10410 200
//@node DE9E484E-0 10690 200
//@node 60F4C0A5-0 10970 200
//@node 2BC760F3-0 11250 200
//@node 2E66ADF9-0 11530 200
//@node 3099E85F-0 11810 200
//@node 07790644-0 12090 200
//@node E4AA10A3-1 12370 200
//@node F75883E6-1 12650 200
//@node 7B884BE6-0 12930 200
//@node 1DB95E8A-0 13210 200
//@node 3099E85F-1 13490 200
//@node 1284DEEC-0 13770 200
//@node F096164B-1 14050 200
//@node EA0E5B6D-0 14330 200
//@node 13C61337-0 14125 300
//@node 4B61DEAE-0 14610 200
//@node D160316F-0 14890 200
//@node DE9E484E-1 15170 200
//@node 60F4C0A5-1 15450 200
//@node 60BDDDC2-0 15730 200
//@node E8E792BF-0 16010 200
//@node F5593DE5-0 16290 200
//@node 3099E85F-2 16570 200
//@node 0A784615-0 40 40
//@node 7F1E104A-0 330 40
//@node DEC059AD-0 125 145
//@node 9F8C2176-0 610 200
//@node 75A2ABE1-0 890 200
//@node 89953079-0 40 40
//@node 90CAA239-0 330 40
//@node D998DD66-0 610 40
//@node 6E5FE229-0 890 40
//@node C4DD7756-0 1170 40
//@node 9BEA94EC-0 1450 40
//@node 39C4ADD9-0 1730 40
//@node 19FA2A85-0 2010 40
//@node 078EF5BF-0 2290 40
//@node 9E0FEBD1-0 2570 40
//@node 4E49CF22-0 2850 40
//@node FD02871A-0 3130 40
//@node 90B4DEF7-0 3410 40
//@node 9BD31D58-0 3690 40
//@node 1E1D3235-0 3970 40
//@node 3BD6E76F-0 4250 40
//@node 57387FB0-0 4530 40
//@node 1E96BDED-0 4810 40
//@node 845A5DEB-0 5090 40
//@node 6CDAE1A3-0 5370 40
//@node C6E96274-0 5650 40
//@node 91C48791-0 40 40
//@node 45D3F1F2-0 330 40
//@node A1F7745E-0 610 40
//@node DC34725B-0 890 40
//@node 53D9D462-0 1170 40
//@node 7F6C15BE-0 965 145
//@node 0668E4DD-0 760 145
//@node C401D5A8-0 1450 200
//@node D1CF0DDE-0 1225 305
//@node F0C2AA65-0 1020 405
//@node 7FFB20AD-0 815 405
//@node 28F6167B-0 1730 200
//@node 15308606-0 1525 300
//@node 850CE0C1-0 2010 200
//@node FD8FA6E1-0 2290 200
//@node 02207FE9-0 2085 305
//@node 1CA4E9D3-0 1880 305
//@node 338EBA99-0 2570 360
//@node 1E7189D0-0 2850 360
//@node 6459F991-0 3130 360
//@node FFA02A12-0 3410 360
//@node C6BAEAD8-0 3690 360
//@node 09A41635-0 3970 360
//@node 858CAB62-0 4250 200
//@node 5E6F67CC-0 4045 305
//@node F43E81C3-0 3840 305
//@node 6CB7FEB8-0 4530 360
//@node DD950FA7-0 4810 360
//@node 4A80888A-0 5090 360
//@node 3028A429-0 5370 360
//@node 618A341F-0 5650 200
//@node 47B98126-0 5445 305
//@node FBABADEC-0 5240 305
//@node 6199C057-0 5930 360
//@node 3DF944DA-0 6210 360
//@node D1AB9CB7-0 6490 360
//@node DCC9DB18-0 6770 360
//@node 18D78B02-0 7050 360
//@node BF80CAD9-0 7330 360
//@node 111DC744-0 7610 200
//@node D1859E0E-0 7405 305
//@node 04383C2B-0 7200 305
//@node 34EA9BEE-0 7890 360
//@node ADB0C783-0 8170 360
//@node 3D17311F-0 8450 360
//@node 41B48796-0 8730 360
//@node 7A003253-0 9010 360
//@node A0EFC0B2-0 9290 360
//@node D71BA581-0 9570 360
//@node 57673356-0 9850 360
//@node 4208AEE6-0 10130 360
//@node 2D123625-0 9925 465
//@node E85B7F16-0 10410 40
//@node EBAE69B6-0 10690 40
//@node 665D9B00-0 40 40
//@node 8EB9426B-0 330 40
//@node E7C3EA21-0 125 145
//@node 8D8FC146-0 610 200
//@node 69B157ED-0 405 305
//@node 04FA6A43-0 200 305
//@node 82F0C84B-0 890 360
//@node F00CF5E3-0 1170 360
//@node 5250F1B5-0 1450 360
//@node 88D24331-0 1730 360
//@node D45AE9A5-0 2010 360
//@node E0D1C7E8-0 2290 360
//@node B467608A-0 2570 360
//@node D45AE9A5-1 2850 360
//@node FC2AD567-0 3130 360
//@node D45AE9A5-2 3410 200
//@node 2FDA436B-0 40 40
//@node 352E4AE7-0 330 40
//@node 34EE40D2-0 610 40
//@node 3E84C91D-0 40 40
//@node 44DE886F-0 330 40
//@node FBF07750-0 610 40
//@node CE5B1B0F-0 890 40
//@node EFB28D37-0 1170 40
//@node D7F18B75-0 1450 40
//@node D9795970-0 1730 40
//@node 13D8BB62-0 2010 40
//@node 872AEA27-0 2290 40
//@node 483611A1-0 2570 40
//@node FBF07750-1 2850 40
//@node 01AE3E20-0 3130 40
//@node 63A65BC3-0 3410 40
//@node 772E99FF-0 3690 40
//@node 11F52C9B-0 3970 40
//@node 8F16915E-0 4250 40
//@node FBF07750-2 4530 40
//@node 83F852FD-0 4810 40
//@node D7F18B75-1 5090 40
//@node BD21971C-0 5370 40
//@node 376306CC-0 5650 40
//@node 22A1D9CB-0 5930 40
//@node DF052A3D-0 40 40
//@node 807D61C4-0 330 40
//@node 90A07E27-0 610 40
//@node 636B3C6A-0 40 40
//@node B94056C6-0 330 40
//@node 89AD6DDB-0 610 40
//@node 9F1CCE35-0 890 40
//@node E3847CF0-0 1170 40
//@node 55C5E0D9-0 1450 40
//@node B969A5D4-0 1730 40
//@node 080B4168-0 2010 40
//@node B94056C6-1 2290 40
//@node 89AD6DDB-1 2570 40
//@node 9F1CCE35-1 2850 40
//@node E89B6BCF-0 3130 40
//@node 9BDD2878-0 3410 40
//@node B969A5D4-1 3690 40
//@node 7D8B9D47-0 3970 40
//@node AE221865-0 4250 40
//@node 36234405-0 4530 40
//@node B7363BD1-0 4810 40
//@node 6DB449CD-0 5090 40
//@node 5CD6EB23-0 5370 40
//@node B969A5D4-2 5650 40
//@node 080B4168-1 5930 40
//@node B94056C6-2 6210 40
//@node 89AD6DDB-2 6490 40
//@node 9F1CCE35-2 6770 40
//@node E89B6BCF-1 7050 40
//@node 447E67E2-0 7330 40
//@node B969A5D4-3 7610 40
//@node 2997E8DA-0 7890 40
//@node 2BD80388-0 8170 40
//@node 36234405-1 8450 40
//@node 527C6C52-0 8730 40
//@node 64D1372E-0 9010 40
//@node 1817DFD4-0 9290 40
//@node B969A5D4-4 9570 40
//@node 742B148A-0 9850 40
//@node 782F5B85-0 10130 40
//@node BA1963E9-0 10410 40
//@node 712239D5-0 10690 40
//@node 32687650-0 40 40
//@node 67C3ED48-0 330 40
//@node E982EF55-0 610 40
//@node E2E2D8C5-0 890 40
//@node 57E4F361-0 1170 40
//@node 5E6D6B15-0 1450 40
//@doomscript-blueprint end
