namespace map_commoutside {

	////////////////////////////////////////////////////
	//
	//	Setup binds and times etc...
	//
	////////////////////////////////////////////////////
	void setup_objects()
	{
		//set airlock door guis initial states to 1
		$airlock1_door2_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock3_door1_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock3_door2_gui.setGuiParm ( "gui_parm1" , 1);
		$airlock4_door1_gui.setGuiParm ( "gui_parm1" , 1);

		//airlock1 times
		$airlock1_door1_left.time (1.2);
		$airlock1_door1_right.time (1.2);
		$airlock1_door1_left.accelTime (.2);
		$airlock1_door1_left.decelTime (1);
		$airlock1_door1_right.accelTime (.2);
		$airlock1_door1_right.decelTime (1);

		$airlock1_door1_top_lock.time (.25);
		$airlock1_door1_bottom_lock.time (.25);
		
		$airlock1_door1_left_lock.time (.75);
		$airlock1_door1_right_lock.time (.75);
		$airlock1_door1_left_lock.accelTime (.1);
		$airlock1_door1_left_lock.decelTime (.65);
		$airlock1_door1_right_lock.accelTime (.1);
		$airlock1_door1_right_lock.decelTime (.65);

		$airlock1_door2_left.time (1.2);
		$airlock1_door2_right.time (1.2);
		$airlock1_door2_left.accelTime (.2);
		$airlock1_door2_left.decelTime (1);
		$airlock1_door2_right.accelTime (.2);
		$airlock1_door2_right.decelTime (1);

		$airlock1_door2_top_lock.time (.25);
		$airlock1_door2_bottom_lock.time (.25);
		
		$airlock1_door2_left_lock.time (.75);
		$airlock1_door2_right_lock.time (.75);
		$airlock1_door2_left_lock.accelTime (.1);
		$airlock1_door2_left_lock.decelTime (.65);
		$airlock1_door2_right_lock.accelTime (.1);
		$airlock1_door2_right_lock.decelTime (.65);

		//airlock2 times
		$airlock2_door1_left.time (1.2);
		$airlock2_door1_right.time (1.2);
		$airlock2_door1_left.accelTime (.2);
		$airlock2_door1_left.decelTime (1);
		$airlock2_door1_right.accelTime (.2);
		$airlock2_door1_right.decelTime (1);

		$airlock2_door1_top_lock.time (.25);
		$airlock2_door1_bottom_lock.time (.25);
		
		$airlock2_door1_left_lock.time (.75);
		$airlock2_door1_right_lock.time (.75);
		$airlock2_door1_left_lock.accelTime (.1);
		$airlock2_door1_left_lock.decelTime (.65);
		$airlock2_door1_right_lock.accelTime (.1);
		$airlock2_door1_right_lock.decelTime (.65);

		$airlock2_door2_left.time (1.2);
		$airlock2_door2_right.time (1.2);
		$airlock2_door2_left.accelTime (.2);
		$airlock2_door2_left.decelTime (1);
		$airlock2_door2_right.accelTime (.2);
		$airlock2_door2_right.decelTime (1);

		$airlock2_door2_top_lock.time (.25);
		$airlock2_door2_bottom_lock.time (.25);
		
		$airlock2_door2_left_lock.time (.75);
		$airlock2_door2_right_lock.time (.75);
		$airlock2_door2_left_lock.accelTime (.1);
		$airlock2_door2_left_lock.decelTime (.65);
		$airlock2_door2_right_lock.accelTime (.1);
		$airlock2_door2_right_lock.decelTime (.65);

		//airlock3 times
		$airlock3_door1_left.time (1.2);
		$airlock3_door1_right.time (1.2);
		$airlock3_door1_left.accelTime (.2);
		$airlock3_door1_left.decelTime (1);
		$airlock3_door1_right.accelTime (.2);
		$airlock3_door1_right.decelTime (1);

		$airlock3_door1_top_lock.time (.25);
		$airlock3_door1_bottom_lock.time (.25);
		
		$airlock3_door1_left_lock.time (.75);
		$airlock3_door1_right_lock.time (.75);
		$airlock3_door1_left_lock.accelTime (.1);
		$airlock3_door1_left_lock.decelTime (.65);
		$airlock3_door1_right_lock.accelTime (.1);
		$airlock3_door1_right_lock.decelTime (.65);

		$airlock3_door2_left.time (1.2);
		$airlock3_door2_right.time (1.2);
		$airlock3_door2_left.accelTime (.2);
		$airlock3_door2_left.decelTime (1);
		$airlock3_door2_right.accelTime (.2);
		$airlock3_door2_right.decelTime (1);

		$airlock3_door2_top_lock.time (.25);
		$airlock3_door2_bottom_lock.time (.25);
		
		$airlock3_door2_left_lock.time (.75);
		$airlock3_door2_right_lock.time (.75);
		$airlock3_door2_left_lock.accelTime (.1);
		$airlock3_door2_left_lock.decelTime (.65);
		$airlock3_door2_right_lock.accelTime (.1);
		$airlock3_door2_right_lock.decelTime (.65);

		//airlock4 times
		$airlock4_door1_left.time (1.2);
		$airlock4_door1_right.time (1.2);
		$airlock4_door1_left.accelTime (.2);
		$airlock4_door1_left.decelTime (1);
		$airlock4_door1_right.accelTime (.2);
		$airlock4_door1_right.decelTime (1);

		$airlock4_door1_top_lock.time (.25);
		$airlock4_door1_bottom_lock.time (.25);
		
		$airlock4_door1_left_lock.time (.75);
		$airlock4_door1_right_lock.time (.75);
		$airlock4_door1_left_lock.accelTime (.1);
		$airlock4_door1_left_lock.decelTime (.65);
		$airlock4_door1_right_lock.accelTime (.1);
		$airlock4_door1_right_lock.decelTime (.65);

		//goofy arm binds
		$goofyarm_4.bind ($goofyarm_3);
		$goofyarm_3.bind ($goofyarm_2);
		$goofyarm_2.bind ($goofyarm_1);

		$goofyarm_1.time (.5);
		$goofyarm_2.time (.5);
		$goofyarm_3.time (.5);
		$goofyarm_4.time (.5);

		$goofy_light_1.setColor( .62, .62, .72);
		$goofy_light_2.setColor( .62, .62, .72);

		$goofy_flare_1.setColor( .62, .62, .72);
		$goofy_flare_2.setColor( .62, .62, .72);
	}

	////////////////////////////////////////////////////
	//
	//	goofy arm ambient movement
	//
	////////////////////////////////////////////////////
	void goofyarm_move ()
	{
		while (1){
			$goofyarm_1.startSoundShader ("co_05s_machinery_01", SND_CHANNEL_VOICE );
			$goofyarm_1.rotateOnce ( '0 -35 0' );
			$goofyarm_2.rotateOnce ( '0 20 0' );
			$goofyarm_3.rotateOnce ( '0 15 0' );
			sys.wait (2);

			$goofyarm_1.startSoundShader ("co_goofy_updown", SND_CHANNEL_VOICE );
			$goofyarm_1.move ( DOWN, 32 );
			sys.waitFor ($goofyarm_1);

			$goofyarm_1.startSoundShader ("co_05s_machinery_01", SND_CHANNEL_VOICE );
			$goofyarm_1.rotateOnce ( '0 35 0' );
			$goofyarm_2.rotateOnce ( '0 -20 0' );
			$goofyarm_3.rotateOnce ( '0 -15 0' );
			sys.waitFor ($goofyarm_1);

			$goofy_light_1.startSoundShader ("al4_welding_2s", SND_CHANNEL_VOICE );
			$goofy_light_1.setColor( .86, .86, 1 );
			$goofy_flare_1.setColor( .86, .86, 1 );
			sys.wait (2);

			thread crossFadeEnt ($goofy_light_1, '.86 .86 1', '.3 .3 .5', 2);
			thread crossFadeEnt ($goofy_flare_1, '.86 .86 1', '.3 .3 .5', 2);
						
			$goofyarm_1.startSoundShader ("co_05s_machinery_01", SND_CHANNEL_VOICE );
			$goofyarm_1.rotateOnce ( '0 -35 0' );
			$goofyarm_2.rotateOnce ( '0 20 0' );
			$goofyarm_3.rotateOnce ( '0 15 0' );
			sys.wait (2);

			$goofyarm_1.startSoundShader ("co_goofy_updown", SND_CHANNEL_VOICE );
			$goofyarm_1.move ( UP, 32 );
			sys.waitFor ($goofyarm_1);

			$goofyarm_1.startSoundShader ("co_05s_machinery_01", SND_CHANNEL_VOICE );
			$goofyarm_1.rotateOnce ( '0 35 0' );
			$goofyarm_2.rotateOnce ( '0 -20 0' );
			$goofyarm_3.rotateOnce ( '0 -15 0' );
			sys.waitFor ($goofyarm_1);

			$goofy_light_2.startSoundShader ("al4_welding_2s", SND_CHANNEL_VOICE );
			$goofy_light_2.setColor( .86, .86, 1 );
			$goofy_flare_2.setColor( .86, .86, 1 );
			sys.wait (2);

			thread crossFadeEnt ($goofy_light_2, '.86 .86 1', '.3 .3 .5', 2);
			thread crossFadeEnt ($goofy_flare_2, '.86 .86 1', '.3 .3 .5', 2);
		
		} 
	}



	////////////////////////////////////////////////////
	//
	//	grate light mover 
	//
	////////////////////////////////////////////////////
	void gratelight_move ()
	{
		$gratelight_mover.time ( 1 );
		$gratelight_mover.accelTime ( .25 );
		$gratelight_mover.decelTime ( .25 );

		float ran1;

		while (1) //begin main while
		{
		ran1=sys.random(3);
		
		if (ran1<1){
			$gratelight_mover.moveTo ($gratelightpoint_1);
			sys.waitFor ($gratelight_mover);
		} else if (ran1<2) {
			$gratelight_mover.moveTo ($gratelightpoint_2);
			sys.waitFor ($gratelight_mover);
		} else {
			$gratelight_mover.moveTo ($gratelightpoint_3);
			sys.waitFor ($gratelight_mover);
		}

		} //end main while
	}



	////////////////////////////////////////////////////
	//
	//	helldoor random movement
	//
	////////////////////////////////////////////////////
	void helldoor_movement ()
	{
		float ran1, ran2, ran3;

		$helldoor1_mover.time (.2);
		$helldoor2_mover.time (.2);

		//shake the scary_door in a loop - TEMP
		while (1) {
			ran3 = ( sys.random(2.5) + 2 );
			sys.wait (ran3);

			$helldoor1_mover.rotateOnce ( '0 2.5 0');
			$helldoor2_mover.rotateOnce ( '0 -2 0');
			sys.waitFor ($helldoor1_mover);

			//trigger speaker
			sys.trigger ($helldoor_speaker);
			sys.trigger ($helldoor1_bang_influence);

			$helldoor1_mover.rotateOnce ( '0 -2.5 0');
			$helldoor2_mover.rotateOnce ( '0 2 0');
			sys.waitFor ($helldoor1_mover);

			ran2=sys.random(.12) + .1;
			$helldoor1_mover.time (ran2);
			$helldoor2_mover.time (ran2);
		}
	}


	////////////////////////////////////////////////////
	//
	//	stop helldoor
	//
	////////////////////////////////////////////////////
	void stop_helldoor ()
	{
		sys.killthread ("map_commoutside::helldoor_movement");
        sys.trigger ($func_door_14);
		sys.trigger ($helldoor_splat1);
		sys.trigger ($helldoor_splat2);
		sys.trigger ($helldoor_splat3);
		sys.trigger ($helldoor_scream);

		sys.wait (2);
		sys.trigger ($func_forcefield_2);
		sys.trigger ($func_door_14);
	}



	////////////////////////////////////////////////////
	//
	//	underlift movedown
	//
	////////////////////////////////////////////////////
	void underlift_movedown ()
	{
		//move the lift to underlift_pos_mid
		$underlift.time ( 3 );
		$underlift.accelTime ( .5 );
		$underlift.decelTime ( .25 );

		$underlift.startSoundShader ("co_lift_down_3s", SND_CHANNEL_VOICE );			// SOUND
		
		$underlift.moveTo ($underlift_pos_mid);
		sys.waitFor ($underlift);
		
		//open underlift_doors_bottom
		$underlift_doors_bottom.open();
		sys.waitFor ($underlift_doors_bottom);

		//move the lift to underlift_pos_top
		$underlift.startSoundShader ("co_lift_down_3s", SND_CHANNEL_VOICE );			// SOUND
		$underlift.moveTo ($underlift_pos_bottom);
		sys.waitFor ($underlift);

		//close underlift_doors_bottom
		$underlift_doors_bottom.close();
		sys.waitFor ($underlift_doors_bottom);
	}
	
	
	
	////////////////////////////////////////////////////
	//
	//	underlift moveup
	//
	////////////////////////////////////////////////////
	void underlift_moveup ()
	{
		//open underlift_doors_bottom
		$underlift_doors_bottom.open();
		sys.waitFor ($underlift_doors_bottom);

		//move the lift to underlift_pos_mid
		$underlift.time ( 3 );
		$underlift.accelTime ( .5 );
		$underlift.decelTime ( .25 );

		$underlift.startSoundShader ("co_lift_up_3s", SND_CHANNEL_VOICE );			// SOUND
		$underlift.moveTo ($underlift_pos_mid);
		sys.waitFor ($underlift);

		//close underlift_doors_bottom
		$underlift_doors_bottom.close();
		sys.waitFor ($underlift_doors_bottom);

		//open underlift_doors_top
		$underlift_doors_top.open();
		sys.waitFor ($underlift_doors_top);

		//move the lift to underlift_pos_top
		$underlift.startSoundShader ("co_lift_up_3s", SND_CHANNEL_VOICE );			// SOUND
		$underlift.moveTo ($underlift_pos_top);
		sys.waitFor ($underlift);

		//close the underlift_doors_top
		$underlift_doors_top.close();
		sys.waitFor ($underlift_doors_top);

		//trigger the gui button
		sys.trigger ($airlock_lift_calldown_button);
	}




	////////////////////////////////////////////////////
	//
	//	Open airlock door
	//
	////////////////////////////////////////////////////

	void airlock_door_open( float airlock, float doornum )
	{
		entity ent;
		entity entdoorr, entdoorl;
		entity speaker;
		string door1;
		string door2;
		float  portalstate;
		float  movedist;

		if ( doornum == 2 ) {
			door1 = "airlock" + airlock + "_door2";
			door2 = "airlock" + airlock + "_door1";
			portalstate = 2;
			movedist = -16;
		} else {
			door1 = "airlock" + airlock + "_door1";
			door2 = "airlock" + airlock + "_door2";
			portalstate = 1;
			movedist = 16;
		}

		//turn door1 light on and door2 light off
		ent=sys.getEntity ( door2 + "_light" );
		thread crossFadeEnt (ent, '.84 .84 .9', '0.37 0.05 0.01', 1);
		
		sys.wait(1);

		ent=sys.getEntity ( door1 + "_light" );
		thread crossFadeEnt (ent, '0.37 0.05 0.01', '.84 .84 .9', 1);

		//move the 4 locks to unlock position
		ent=sys.getEntity ( door1 + "_top_lock" );
		ent.time (0.25);
		ent.move ( UP, 15 );

		speaker=sys.getEntity ("speaker_" + door1 + "_bottom_lock" );
		sys.trigger (speaker);
 
		ent=sys.getEntity ( door1 + "_bottom_lock" );
		ent.time (0.25);
		ent.move ( DOWN, 15 );

		sys.waitFor (ent);

		speaker=sys.getEntity ("speaker_" + door1 + "_left_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door1 + "_left_lock" );
		ent.time (0.75);
		ent.move ( EAST, movedist );

		speaker=sys.getEntity ("speaker_" + door1 + "_right_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door1 + "_right_lock" );
		ent.time (0.75);
		ent.move ( EAST, movedist );

		sys.waitFor (ent);

		//open doors
		speaker=sys.getEntity ( "speaker_" + door1 + "_open");
		sys.trigger (speaker);

		entdoorl=sys.getEntity ( door1 + "_left" );
		entdoorl.time (1.2);
		entdoorl.rotateOnce ( '0 45 0' );

		entdoorr=sys.getEntity ( door1 + "_right" );
		entdoorr.time (1.2);
		entdoorr.rotateOnce ( '0 -45 0' );

		//trigger the portal
		ent=sys.getEntity (door1 + "_portal" );
		sys.trigger (ent);

		sys.waitFor (entdoorr);
		sys.waitFor (entdoorl);

		//set airlock state
		ent=sys.getEntity ("airlock" + airlock + "_door1_portal" );
		ent.setKey ("state", portalstate );

	}


	////////////////////////////////////////////////////
	//
	//	Close airlock door
	//
	////////////////////////////////////////////////////
	void airlock_door_close(float airlock, float doornum )
	{
		entity ent;
		entity entdoorr, entdoorl;
		entity speaker;
		string door;
		float  movedist;

		if ( doornum == 2 ) {
			door = "airlock" + airlock + "_door2";
			movedist = 16;
		} else {
			door = "airlock" + airlock + "_door1";
			movedist = -16;
		}

		//close doors

		speaker= sys.getEntity ("speaker_" + door + "_close");
		sys.trigger (speaker);

		entdoorl=sys.getEntity ( door + "_left" );
		entdoorl.time (1.2);
		entdoorl.rotateOnce ( '0 -45 0' );

		entdoorr=sys.getEntity ( door + "_right" );
		entdoorr.time (1.2);
		entdoorr.rotateOnce ( '0 45 0' );

		sys.waitFor (entdoorr);
		sys.waitFor (entdoorl);

		//trigger the portal
		ent=sys.getEntity ( door + "_portal" );
		sys.trigger (ent);

		//move the 4 locks to unlock position
		ent=sys.getEntity ( door + "_top_lock" );
		ent.time (0.25);
		ent.move ( DOWN, 15 );

		speaker=sys.getEntity ("speaker_" + door + "_bottom_lock");
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_bottom_lock" );
		ent.time (0.25);
		ent.move ( UP, 15 );
		
		speaker=sys.getEntity ("speaker_" + door + "_left_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_left_lock" );
		ent.time (0.75);
		ent.move ( EAST, movedist );

		speaker=sys.getEntity ("speaker_" + door + "_right_lock" );
		sys.trigger (speaker);

		ent=sys.getEntity ( door + "_right_lock" );
		ent.time (0.75);
		ent.move ( EAST, movedist );

		sys.waitFor (ent);

}


	////////////////////////////////////////////////////
	//
	//	Main Activate airlock
	//	conditionally chooses based on entrance
	//
	////////////////////////////////////////////////////
	void airlock_main_activate(float airlock)
	{
		entity ent;

		//check to see which way the palyer entered by checking the airlock_state
		//if 1 then close 1 and open 2

		ent=sys.getEntity ("airlock" + airlock + "_door1_portal" );
			
		if (ent.getFloatKey ("state")==1) {
			airlock_door_close( airlock, 1 );
			airlock_door_open( airlock, 2 );

		} else { //else close 2 and open 1
			airlock_door_close( airlock, 2 );
			airlock_door_open( airlock, 1 );
		}
	}


	////////////////////////////////////////////////////
	//
	//	AIRLOCK main activation
	//	
	////////////////////////////////////////////////////
	void airlock2_activate()
	{
		//disable the guis on the doors
		$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 0);
	
		airlock_main_activate(2);

		//check the airlock state and enable the guis on the closed door
		if ($airlock2_door1_portal.getFloatKey ("state")==1) {
			$airlock2_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock2_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock2_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}
	
	void airlock3_activate()
	{
		//disable the guis on the doors
		$airlock3_door1_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock3_door2_gui.setGuiParm ( "gui_parm1" , 0);
		$airlock3_innerguiholder.setGuiParm ( "gui_parm11" , 0);
	
		airlock_main_activate(3);

		//check the airlock state and enable the guis on the closed door
		if ($airlock3_door1_portal.getFloatKey ("state")==1) {
			$airlock3_door2_gui.setGuiParm ( "gui_parm1" , 1);
		} else { //else close 2 and open 1
			$airlock3_door1_gui.setGuiParm ( "gui_parm1" , 1);
		}

		$airlock3_innerguiholder.setGuiParm ( "gui_parm11" , 1);
	}


	////////////////////////////////////////////////////
	//
	//	AIRLOCK doors opening
	//	
	////////////////////////////////////////////////////
	void airlock2_door1_open()
	{
		airlock_door_open(2, 1);
	}

	void airlock2_door2_open()
	{
		airlock_door_open(2, 2);
	}

	void airlock3_door1_open()
	{
		airlock_door_open(3, 1);
	}

	void airlock3_door2_open()
	{
		airlock_door_open(3, 2);
	}

	void airlock4_door1_open()
	{
		$airlock4_door1_gui.setGuiParm ( "gui_parm1" , 0);
		airlock_door_open(4, 1);
	}

	
	//exits map
	void airlock_exit()
	{
		sys.trigger ($end_level);

		float thread1;

		thread1 = thread airlock_door_close(4, 1);
		sys.waitForThread( thread1 );

		//turn doora light off
		thread crossFadeEnt ($airlock4_door1_light, '.84 .84 .9', '0.37 0.05 0.01', 1);
		sys.wait(1);

		sys.trigger ($end_level);
	}


	////////////////////////////////////////////////////
	//
	//	initial AIRLOCK doors opening
	//	start of map
	//	
	////////////////////////////////////////////////////
	void initial_airlock_open()
	{
		//turn door2 light on
		thread crossFadeEnt ($airlock1_door2_light, '0.37 0.05 0.01', '.84 .84 .9', 1);

		//move the 4 locks to unlock position
		$airlock1_door2_top_lock.move ( UP, 15 );
		$airlock1_door2_bottom_lock.move ( DOWN, 15 );
		
		sys.trigger ($speaker_airlock1_door2_bottom_lock);		// SOUND
		
		sys.waitFor ($airlock1_door2_bottom_lock);

		sys.trigger ($speaker_airlock1_door2_left_lock);
		$airlock1_door2_left_lock.move ( EAST, -16 );
		
		sys.trigger ($speaker_airlock1_door2_right_lock);
		$airlock1_door2_right_lock.move ( EAST, -16 );
		sys.waitFor ($airlock1_door2_right_lock);

		//open doors
		sys.trigger ($speaker_airlock1_door2_open);				// SOUND
		
		$airlock1_door2_left.rotateOnce ( '0 45 0' );
		$airlock1_door2_right.rotateOnce ( '0 -45 0' );

		//trigger the portal
		sys.trigger ($airlock1_door2_portal);

		sys.waitFor ($airlock1_door2_left);
		sys.waitFor ($airlock1_door2_right);
	}



	////////////////////////////////////////////////////
	//
	//	co_drop_floor
	//
	////////////////////////////////////////////////////
	void co_drop_floor_down ()
	{
		$co_drop_floor.time(.5);
		$co_drop_floor.accelTime(.5);
		//$co_drop_floor.decelTime(0);

		//trigger the weird sound
		//sys.trigger($co_drop_floor_weird_speaker);

		sys.trigger ($co_floordrop_01);
		sys.trigger ($co_floordrop_02);

		//move drop_floor down
		$co_drop_floor.move (DOWN, 128);
	}

	void co_drop_floor_end ()
	{
		$co_drop_step_1.time(1);
		$co_drop_step_1.accelTime(.2);
		$co_drop_step_1.decelTime(.2);

		$co_drop_step_2.time(1);
		$co_drop_step_2.accelTime(.2);
		$co_drop_step_2.decelTime(.2);

		$co_drop_step_3.time(1);
		$co_drop_step_3.accelTime(.2);
		$co_drop_step_3.decelTime(.2);

		//move steps out
		$co_drop_step_3.startSoundShader ("co_step_out", SND_CHANNEL_VOICE );
		$co_drop_step_3.move (WEST, 112);
		sys.waitFor ($co_drop_step_3);
		
		sys.wait (0.5);
		
		$co_drop_step_2.startSoundShader ("co_step_out", SND_CHANNEL_VOICE );
		$co_drop_step_2.move (WEST, 80);
		sys.waitFor ($co_drop_step_2);
		
		sys.wait (0.5);
		
		$co_drop_step_1.startSoundShader ("co_step_out", SND_CHANNEL_VOICE );
		$co_drop_step_1.move (WEST, 48);
	}


	////////////////////////////////////////////////////
	//
	//	spectrum hallway
	//
	////////////////////////////////////////////////////
	void spectrum_move() {
		sys.wait (2);
		while(1){
            $spectrumlight_mover.time( 3 );
			$spectrumlight_mover.accelTime( 0 );
			$spectrumlight_mover.decelTime( 0 );
			$spectrumlight_mover.startSpline( $spectrum_spline );

			sys.waitFor($spectrumlight_mover);
			sys.wait(3);
			$spectrumlight_mover.removeInitialSplineAngles();
		}
	}

	void spectrum_stop() 
	{
		sys.wait (3);

		sys.trigger ( $trigger_relay_55 );
		sys.killthread( "map_commoutside::spectrum_move" );
        $spectrumlight_mover.remove();
		sys.trigger ( $speaker_136 );
		sys.trigger ( $speaker_137 );
		$speaker_137.remove();
		$light_5229.remove();
		$light_5230.remove();
	}

	void close_func_door_17()
	{
		$func_door_17.close();
	}

	//close sawyer door
	void close_func_door_1675()
	{
		$func_door_1675.close();
	}


	////////////////////////////////////////////////////
	//
	//	Scary Elevator Shake
	//
	////////////////////////////////////////////////////
	void ele_shake() 
	{
		$ele_mover.time (.25);
		$ele_mover.move (DOWN, 8);
		sys.waitFor ($ele_mover);
		sys.trigger ( $speaker_elebang );
		$ele_mover.move (UP, 8);
	}

	////////////////////////////////////////////////////
	//
	//	sawyer_intro
	//
	////////////////////////////////////////////////////
	void sawyer_intro ()
	{
		$sawyer_light_1.kill();
		$sawyer_light_2.kill();
		//sys.print ("I just killed those lights\n");
	}

	void cache_sounds() {
		sys.cacheSoundShader ("co_step_out");
		sys.cacheSoundShader ("co_lift_up_3s");
		sys.cacheSoundShader ("co_lift_down_3s");
		sys.cacheSoundShader ("al4_welding_2s");
		sys.cacheSoundShader ("co_05s_machinery_01");
		sys.cacheSoundShader ("co_goofy_updown");
		sys.cacheSoundShader ("rec1_steamchuff");
		sys.cacheSoundShader ("co_lift_rotation");
		sys.cacheSoundShader ("co_lift_up_2s");
		sys.cacheSoundShader ("co_lift_down_2s");
		sys.cacheSoundShader ("co_conpanel");
	}


	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void main ()
	{
		cache_sounds();
		setup_objects ();
		thread goofyarm_move ();
		thread gratelight_move ();
		thread helldoor_movement ();
		thread lift_main ();

		//open the airlock doors that need to be open initially
		thread airlock3_door2_open();
		thread airlock2_door2_open();
	}

}// namespace

//@doomscript-blueprint begin 6
//@source 2086F0D3
//@catalog 0C260740
//@node 7AEA71C1-0 40 40
//@node 90ADDF17-0 330 40
//@node 95E8E03B-0 610 40
//@node 92C27E74-0 890 40
//@node FC008B3E-0 1170 40
//@node 4E16D621-0 1450 40
//@node DCEA6FA1-0 1730 40
//@node 184AA6F9-0 2010 40
//@node 3093E4C6-0 2290 40
//@node EA8C2AA0-0 2570 40
//@node C2B9EBFC-0 2850 40
//@node 073F9883-0 3130 40
//@node 585D2515-0 3410 40
//@node E177A083-0 3690 40
//@node 9E3556CF-0 3970 40
//@node 832D6788-0 4250 40
//@node 091942C9-0 4530 40
//@node 1DF553B9-0 4810 40
//@node 57B641A8-0 5090 40
//@node D38FBB9C-0 5370 40
//@node 890BF457-0 5650 40
//@node 5BB9FA66-0 5930 40
//@node 3E90ADD7-0 6210 40
//@node BCF1A8E3-0 6490 40
//@node C0D17B75-0 6770 40
//@node 3D9C01FE-0 7050 40
//@node 1052026A-0 7330 40
//@node 3A27767C-0 7610 40
//@node 670A568E-0 7890 40
//@node 95900629-0 8170 40
//@node 7F08CC8A-0 8450 40
//@node C3FF2CBC-0 8730 40
//@node E3348BF7-0 9010 40
//@node 9D68FEA7-0 9290 40
//@node 8E04FFDA-0 9570 40
//@node A5A237EA-0 9850 40
//@node DF9DEFF3-0 10130 40
//@node 1D83A7D7-0 10410 40
//@node 8DD72689-0 10690 40
//@node 7F04E99A-0 10970 40
//@node BDB634B6-0 11250 40
//@node F41BD170-0 11530 40
//@node 5782A7B2-0 11810 40
//@node 19095D8D-0 12090 40
//@node 63DF25D6-0 12370 40
//@node E6621840-0 12650 40
//@node 454C0913-0 12930 40
//@node E6916053-0 13210 40
//@node 838F747E-0 13490 40
//@node 5E3EDE2D-0 13770 40
//@node 38215C82-0 14050 40
//@node 98934C34-0 14330 40
//@node 8265C4C0-0 14610 40
//@node 05953D9F-0 14890 40
//@node 33995691-0 15170 40
//@node 1060CCB7-0 15450 40
//@node 5C555363-0 15730 40
//@node 5DC99B7C-0 16010 40
//@node 8231D6B5-0 16290 40
//@node 8D4E699D-0 16570 40
//@node 65FA4DE4-0 16850 40
//@node C567D3F8-0 17130 40
//@node 6B19143B-0 17410 40
//@node 030672A7-0 17690 40
//@node E3DF0D84-0 17970 40
//@node 7275CB2E-0 18250 40
//@node A4CE5CBA-0 18530 40
//@node ED080449-0 18810 40
//@node AFEEBD73-0 19090 40
//@node 06458AF9-0 19370 40
//@node 0377F5F1-0 19650 40
//@node 892D469A-0 19930 40
//@node F6828C6B-0 20210 40
//@node 0643AC97-0 20490 40
//@node D2C17A4A-0 20770 40
//@node AE39FCCA-0 21050 40
//@node E70BFF99-0 21330 40
//@node 1E267848-0 21610 40
//@node A87174C1-0 21890 40
//@node 227177BD-0 22170 40
//@node AD904137-0 22450 40
//@node 7C6B0998-0 22730 40
//@node 90B51634-0 23010 40
//@node F9DCAF4E-0 23290 40
//@node AE46AC3C-0 23570 40
//@node ACFC04CF-0 23850 40
//@node 6E1300A0-0 24130 40
//@node 321998DE-0 24410 40
//@node A0C40495-0 24690 40
//@node 02F92A61-0 24970 40
//@node 0E07E040-0 25250 40
//@node 13C0B5C8-0 25530 40
//@node CA404541-0 25810 40
//@node F8D20D3D-0 26090 40
//@node BBC0C5B7-0 26370 40
//@node 76766218-0 26650 40
//@node 6715ABB4-0 26930 40
//@node D03D44CE-0 27210 40
//@node 561AF8BC-0 27490 40
//@node A7075D4F-0 27770 40
//@node 8DEF5220-0 28050 40
//@node CDA1F95E-0 28330 40
//@node F873EE15-0 28610 40
//@node 5AA913E1-0 28890 40
//@node 97F474C0-0 29170 40
//@node DF5A8C89-0 29450 40
//@node AE678347-0 29730 40
//@node 9FB04809-0 30010 40
//@node A64265B3-0 30290 40
//@node 779BFB10-0 30570 40
//@node E7854989-0 30850 40
//@node EE26F116-0 31130 40
//@node 710CE778-0 31410 40
//@node BE3288CD-0 31690 40
//@node F9C68108-0 31970 40
//@node DF62915D-0 32250 40
//@node DC9BCA63-0 40 40
//@node 70207514-0 330 40
//@node A3E57A5E-0 125 145
//@node C936103B-0 610 200
//@node E8C9B622-0 890 200
//@node E8242728-0 1170 200
//@node C2070C9D-0 1450 200
//@node 3D86D81F-0 1730 200
//@node B92495C4-0 2010 200
//@node A544263B-0 2290 200
//@node 4F51279A-0 2570 200
//@node C936103B-1 2850 200
//@node E7758BA9-0 3130 200
//@node E30CE395-0 3410 200
//@node C5EAE6CE-0 3690 200
//@node 4F51279A-1 3970 200
//@node 07D9773E-0 4250 200
//@node 2C2ADEEA-0 4530 200
//@node 6DAD5E16-0 4810 200
//@node 3D86D81F-1 5090 200
//@node 4CAC6EEF-0 5370 200
//@node ABB15307-0 5650 200
//@node C936103B-2 5930 200
//@node E8C9B622-1 6210 200
//@node E8242728-1 6490 200
//@node C2070C9D-1 6770 200
//@node 3D86D81F-2 7050 200
//@node B92495C4-1 7330 200
//@node 2DFE2C90-0 7610 200
//@node 4F51279A-2 7890 200
//@node C936103B-3 8170 200
//@node E7758BA9-1 8450 200
//@node E30CE395-1 8730 200
//@node C5EAE6CE-1 9010 200
//@node 4F51279A-3 9290 200
//@node 91C2BE89-0 9570 200
//@node E8CAB851-0 9850 200
//@node 4625CBED-0 10130 200
//@node 3D86D81F-3 10410 200
//@node E6C4AD4A-0 10690 200
//@node C116E4E2-0 10970 200
//@node BA685BEC-0 40 40
//@node 89E3E739-0 330 40
//@node F2BC952B-0 610 40
//@node DFE5DD54-0 890 40
//@node 831091E7-0 1170 40
//@node 7EE71621-0 965 145
//@node 24FA0F13-0 1450 200
//@node D5C8066A-0 1225 305
//@node 3E27B471-0 1730 200
//@node C95AB8F7-0 1525 305
//@node 9B448693-0 1320 305
//@node FB5753D4-0 2010 360
//@node D87BCCC8-0 2290 360
//@node AB462F03-0 2570 360
//@node 0D699AB1-0 2365 465
//@node 98C82EF8-0 2160 465
//@node 41DF2755-0 2850 360
//@node D87BCCC8-1 3130 360
//@node CD9BFFF6-0 3690 360
//@node D87BCCC8-2 3970 360
//@node 7B44F2BE-0 40 40
//@node 582703C7-0 610 40
//@node 45E402D0-0 890 40
//@node CE64555D-0 890 40
//@node 12EA85B4-0 685 145
//@node 13AE19D7-0 1170 200
//@node CD5B952E-0 965 305
//@node 92ACF756-0 1730 200
//@node 937CA9C3-0 1245 300
//@node 76191D25-0 2010 200
//@node D1E16992-0 2290 200
//@node 9887FD43-0 2570 200
//@node 9A45CE98-0 2850 200
//@node 8278EB5C-0 3130 200
//@node FE77011C-0 3410 200
//@node 9486F99D-0 3690 200
//@node 9887FD43-1 3970 200
//@node 98C8EF8A-0 3970 200
//@node 1B4C94A7-0 3765 305
//@node D7CBC8A6-0 4530 200
//@node 0314056D-0 4045 300
//@node 760EAE99-0 4810 200
//@node B85942B7-0 4325 300
//@node FD58EC71-0 40 40
//@node E4F53545-0 330 40
//@node 0C17206D-0 610 40
//@node CFA32CEB-0 890 40
//@node 3D5518FE-0 1170 40
//@node 3236DA9D-0 1450 40
//@node B846E68D-0 1730 40
//@node 254658D5-0 2010 40
//@node 981EAB87-0 2290 40
//@node 0C17206D-1 2570 40
//@node CFE67164-0 40 40
//@node 12B1C343-0 330 40
//@node 2C216B95-0 610 40
//@node 83612840-0 890 40
//@node EF793BB1-0 1170 40
//@node DC871086-0 1450 40
//@node B796F732-0 1730 40
//@node FC9C00C1-0 2010 40
//@node 23F5E046-0 2290 40
//@node EF793BB1-1 2570 40
//@node EAC315CF-0 2850 40
//@node B796F732-1 3130 40
//@node D12BB0BB-0 3410 40
//@node 23F5E046-1 3690 40
//@node 34C25F05-0 40 40
//@node 89E56584-0 330 40
//@node 09309F6D-0 610 40
//@node 673695F8-0 890 40
//@node E88CCFBE-0 1170 40
//@node 047EA02D-0 1450 40
//@node 119C3A93-0 1730 40
//@node 8FEF151F-0 2010 40
//@node 752B8707-0 2290 40
//@node 419F0640-0 2570 40
//@node 09309F6D-1 2850 40
//@node 104953BE-0 3130 40
//@node 517F1521-0 3410 40
//@node 119C3A93-1 3690 40
//@node 3E744A72-0 3970 40
//@node 752B8707-1 4250 40
//@node 0FC5DA52-0 4530 40
//@node 517F1521-1 4810 40
//@node 77C230CB-0 5090 40
//@node CEED78FA-0 40 40
//@node E1ECBC76-0 330 40
//@node 6BABC571-0 125 145
//@node 691A87AF-0 610 200
//@node E6C1AFFF-0 405 305
//@node 626032BB-0 890 200
//@node 1C1EE256-0 685 305
//@node AE645514-0 1170 200
//@node ECB3C5A3-0 965 305
//@node 2DEA993A-0 1450 200
//@node 0116FF6C-0 1245 305
//@node 27CEA4B6-0 2010 200
//@node 8F78EB09-0 1805 305
//@node B1139F72-0 2290 200
//@node 7C7AEAA5-0 2085 305
//@node A6668713-0 2570 200
//@node C99407A3-0 2365 305
//@node 19182951-0 2850 200
//@node 19FEECD5-0 2645 305
//@node 321DD1C1-0 3130 40
//@node 71D49918-0 2905 145
//@node 3D3BA48E-0 2700 245
//@node 52B92801-0 2495 245
//@node 2F00C980-0 3690 40
//@node 42C6665F-0 3970 40
//@node F302B200-0 3970 40
//@node BFE7ABB2-0 3745 145
//@node FDF5B209-0 3540 245
//@node AC0E27D8-0 3335 245
//@node A57C48F0-0 4530 40
//@node BCA3C573-0 4530 40
//@node AF37F9BE-0 4305 145
//@node 4ACE4600-0 4100 245
//@node 1BEA8DD2-0 3895 245
//@node AAD6AD1B-0 5090 40
//@node A1BB915D-0 5370 40
//@node 00FF346C-0 5370 40
//@node CEA4A06F-0 5145 145
//@node B866AC22-0 4940 245
//@node 2452AB8F-0 4735 245
//@node 6E493998-0 5930 40
//@node 4D25B2F2-0 5445 140
//@node 1A24FFEF-0 5930 40
//@node 255D4FC4-0 5705 145
//@node 84EAF876-0 5500 245
//@node 2676B6F2-0 5295 245
//@node AAD6AD1B-1 6490 40
//@node EB50F722-0 6770 40
//@node DA611564-0 7050 40
//@node D2701743-0 6565 140
//@node 9D28BD6E-0 7050 40
//@node 1EFB8013-0 6825 145
//@node 233A461A-0 6620 245
//@node 5293902D-0 6415 245
//@node 6E493998-1 7610 40
//@node BBF7CB31-0 7125 140
//@node 301D1DE1-0 7610 40
//@node E3E09E9E-0 7385 145
//@node 1CE300E4-0 7180 245
//@node 75AEAF7E-0 6975 245
//@node 77DFDADA-0 8170 40
//@node 711B4858-0 8450 40
//@node 03BBD43A-0 7965 232
//@node 60700BD5-0 8450 40
//@node B787D227-0 8225 145
//@node 71D80658-0 8020 245
//@node 752AB9F0-0 7815 245
//@node 6E493998-2 9010 40
//@node 8E513320-0 8525 140
//@node 76A5F6EC-0 9010 40
//@node 24D5C6AC-0 8785 145
//@node C31E2A20-0 8580 245
//@node A01BA12F-0 8375 245
//@node 77DFDADA-1 9570 40
//@node 711B4858-1 9850 40
//@node C79FCCB7-0 9365 232
//@node DA611564-1 10130 40
//@node 2C9E0C10-0 9645 140
//@node 2D7D5061-0 10130 40
//@node BCD065CE-0 9905 145
//@node 4ED9BDAF-0 9700 245
//@node AE916621-0 9495 245
//@node 6E493998-3 10690 40
//@node A1308487-0 10205 140
//@node 20A52695-0 10690 40
//@node 2F268159-0 10465 145
//@node 29613E22-0 10260 245
//@node 9D0B556E-0 10055 245
//@node 19C82A95-0 11250 40
//@node 803A7600-0 11530 40
//@node ABD83C4C-0 11530 40
//@node 59C3A3D3-0 11305 145
//@node D032F4A5-0 11100 245
//@node 0AEA4E06-0 10895 245
//@node 94596997-0 12090 40
//@node 433FF411-0 12370 40
//@node BFD166B8-0 12370 40
//@node 7F043E8A-0 12145 145
//@node 32348800-0 11940 245
//@node 5C2736ED-0 11735 245
//@node DCE9FEB8-0 12930 40
//@node 315C98A1-0 12445 140
//@node CCB0EA96-0 13210 40
//@node 89CFC56E-0 12725 140
//@node 8A6E8710-0 13490 40
//@node 0980DCD5-0 13005 140
//@node E4C03D88-0 13490 40
//@node 6775B4BE-0 13265 145
//@node 252D606E-0 13060 245
//@node 67308FB4-0 14050 40
//@node 18C53F34-0 13565 232
//@node A4E9DDAE-0 40 40
//@node DA4FD222-0 330 40
//@node 5335ECA8-0 125 145
//@node 891FA2EC-0 610 200
//@node FB759959-0 405 305
//@node 1840AF73-0 890 200
//@node 7862AB9B-0 685 305
//@node EE069209-0 1450 200
//@node 952B83FF-0 1245 305
//@node 4A346F48-0 1730 200
//@node F6D4F29C-0 1525 305
//@node F10998A4-0 2010 40
//@node D0C38F03-0 1785 145
//@node 4E85D055-0 1580 245
//@node 6D0B4ACD-0 1375 245
//@node 42C42724-0 2570 40
//@node 337A728B-0 2085 140
//@node FC280D84-0 2570 40
//@node 6B5CC12C-0 2345 145
//@node 1F1E96B3-0 2140 245
//@node 5B5F313B-0 1935 245
//@node F9F65C09-0 3130 40
//@node 3293E1E7-0 3410 40
//@node 73FD66A7-0 3410 40
//@node 6FE52F81-0 3185 145
//@node C1B29000-0 2980 245
//@node 7DD3A3BD-0 2775 245
//@node A13D3753-0 3970 40
//@node 496925D6-0 4250 40
//@node A16299AA-0 4530 40
//@node F9344E45-0 4045 140
//@node E26548BC-0 4810 40
//@node 7C7F39BA-0 4325 140
//@node 6BB32997-0 4810 40
//@node 4F38FBA7-0 4585 145
//@node 7B756570-0 4380 245
//@node 59FD172D-0 4175 245
//@node 671274EC-0 5370 40
//@node 2D8ED6C4-0 4885 140
//@node C2C0D076-0 5370 40
//@node 1813B352-0 5145 145
//@node 40D2378F-0 4940 245
//@node D9EE39BD-0 4735 245
//@node 384F89B7-0 5930 40
//@node 316546A6-0 6210 40
//@node 16755E2B-0 6210 40
//@node 9E8855F0-0 5985 145
//@node A65EA5E1-0 5780 245
//@node B51C2B30-0 5575 245
//@node 42C42724-1 6770 40
//@node 568D8CB4-0 6285 140
//@node 2F1CE0D4-0 6770 40
//@node 5B7A824C-0 6545 145
//@node A5572946-0 6340 245
//@node 19C43DCA-0 6135 245
//@node 384F89B7-1 7330 40
//@node F2EACD39-0 7610 40
//@node 30A7037F-0 7610 40
//@node 811E9CAE-0 7385 145
//@node D45DAF54-0 7180 245
//@node 91A65863-0 6975 245
//@node 42C42724-2 8170 40
//@node BB508A45-0 7685 140
//@node 57C09E16-0 8170 40
//@node 492FA4B3-0 7945 145
//@node A7F328E5-0 7740 245
//@node B866A6E5-0 7535 245
//@node 71EB324E-0 8730 40
//@node 7DED09B4-0 9010 40
//@node 948A201B-0 8525 232
//@node 020E4D7A-0 9010 40
//@node 15F26050-0 8785 145
//@node 30EDC187-0 8580 245
//@node E158AC31-0 8375 245
//@node 42C42724-3 9570 40
//@node 4230D346-0 9085 140
//@node 0EF0F15D-0 9570 40
//@node F17BADCC-0 9345 145
//@node FD223248-0 9140 245
//@node EE602F03-0 8935 245
//@node 71EB324E-1 10130 40
//@node 7DED09B4-1 10410 40
//@node 7ABFFA0E-0 9925 232
//@node EEC07F98-0 10690 40
//@node 58AE82A2-0 10205 140
//@node 16319330-0 40 40
//@node FF496C56-0 330 40
//@node 28D9DF62-0 105 145
//@node 87D4AE9B-0 -100 245
//@node 79C716BB-0 610 40
//@node 79679DD9-0 405 145
//@node 2CAE6ED8-0 200 145
//@node DF5089D1-0 890 200
//@node 39718B80-0 1170 200
//@node 19A9C5DE-0 1730 200
//@node EFCA60C7-0 2010 200
//@node 96369CDE-0 40 40
//@node 7FB6C619-0 330 40
//@node E72509EE-0 610 40
//@node 281DBAE8-0 890 40
//@node 1B34B511-0 1170 40
//@node 914832A0-0 1450 40
//@node 2D72E2E0-0 1245 145
//@node 5B68314D-0 1730 200
//@node 9B4BDEFA-0 2290 200
//@node 9D9E16C7-0 2570 40
//@node 7C6EE7BB-0 40 40
//@node 9600D0E3-0 330 40
//@node 9FEBBE8C-0 610 40
//@node 4A003CEE-0 890 40
//@node 1B43BC23-0 1170 40
//@node E1B369BE-0 1450 40
//@node 7AC44E43-0 1245 145
//@node 04CE307B-0 1730 200
//@node 31BDC2B4-0 2290 200
//@node BE43644D-0 2570 40
//@node 9AD9FE77-0 40 40
//@node 13DDBD21-0 330 40
//@node EBCE5B94-0 40 40
//@node F0E636ED-0 330 40
//@node 53AAB70E-0 40 40
//@node E578D657-0 330 40
//@node 95993695-0 40 40
//@node DCDB3D6B-0 330 40
//@node D02A1D6D-0 40 40
//@node 04680716-0 330 40
//@node E36662BD-0 610 40
//@node 31628FD5-0 40 40
//@node 960FA92C-0 330 40
//@node C217C696-0 610 40
//@node E26F3B93-0 385 145
//@node FC42E59D-0 890 40
//@node 530ABAB6-0 685 140
//@node 59D19D5E-0 1170 40
//@node DBCF6F2A-0 1450 40
//@node 960FA92C-1 1730 40
//@node D6DA1C78-0 40 40
//@node 06D3E10D-0 330 40
//@node 68BF3E9D-0 610 40
//@node 4F12812E-0 890 40
//@node 0889501A-0 1170 40
//@node ACC89CBC-0 1450 40
//@node 997E7370-0 1730 40
//@node 53E007E7-0 2010 40
//@node 2DF0C843-0 2290 40
//@node C792DA6A-0 2570 40
//@node C3639455-0 2850 40
//@node ECF276F3-0 3130 40
//@node 511A3B8C-0 3410 40
//@node F5567168-0 3690 40
//@node 2187F617-0 3970 40
//@node D13A739C-0 4250 40
//@node 40983F01-0 4530 40
//@node 1260A3D5-0 40 40
//@node 7D99DFFA-0 330 40
//@node 79CF0922-0 610 40
//@node C295C660-0 890 40
//@node 091D99E1-0 1170 40
//@node 8C2799E6-0 1450 40
//@node 4EF9976A-0 40 40
//@node 32495E9B-0 330 40
//@node FC7BAA3A-0 610 40
//@node B4FD4C7D-0 890 40
//@node D0C5F428-0 1170 40
//@node 2F87D671-0 1450 40
//@node 438512CA-0 1730 40
//@node 1F135B49-0 2010 40
//@node 6E839A00-0 2290 40
//@node DF214817-0 2570 40
//@node 90B1EE83-0 2850 40
//@node E25354CF-0 3130 40
//@node 689472E2-0 3410 40
//@node 1FB35009-0 3690 40
//@node 8EB89FE8-0 3970 40
//@node AAD3E614-0 4250 40
//@node CCB071A1-0 4530 40
//@node 1FB35009-1 4810 40
//@node 1F998B65-0 5090 40
//@node 8926BFB7-0 5370 40
//@node 7442A4AE-0 40 40
//@node C463D4B2-0 330 40
//@node 18C36E8B-0 610 40
//@node 3D466061-0 405 145
//@node 082C14ED-0 890 200
//@node 107D1FC8-0 1170 200
//@node CA1DF625-0 1450 200
//@node FE935CC7-0 1730 200
//@node CE7EAD4E-0 2010 200
//@node 94681C01-0 2290 200
//@node 89750DB0-0 2570 200
//@node 312BB12F-0 40 40
//@node 3A2048A4-0 330 40
//@node 15605175-0 610 40
//@node 4DDE3D7D-0 890 40
//@node 8A2A086E-0 1170 40
//@node F95B12BA-0 1450 40
//@node F15E47D3-0 1730 40
//@node F43AEE22-0 2010 40
//@node 5723532C-0 2290 40
//@node A3129F8A-0 2570 40
//@node 3AE36D74-0 40 40
//@node CF257DFC-0 330 40
//@node 06A59BBF-0 40 40
//@node 14C16F7C-0 330 40
//@node C9E7B342-0 40 40
//@node 5AAE5A3C-0 330 40
//@node F502506B-0 610 40
//@node A3608E65-0 890 40
//@node 048686DF-0 1170 40
//@node 24D0E068-0 1450 40
//@node 80DEDFBB-0 40 40
//@node 0A9487A3-0 330 40
//@node A4F901E2-0 610 40
//@node B832CE32-0 40 40
//@node FA977AE5-0 330 40
//@node 6A482ECC-0 610 40
//@node F2FA74C5-0 890 40
//@node 226D4683-0 1170 40
//@node C4A7B487-0 1450 40
//@node 9D962AC4-0 1730 40
//@node D96BA8A7-0 2010 40
//@node B597848A-0 2290 40
//@node 8D618D2B-0 2570 40
//@node B390D5CE-0 2850 40
//@node 866D3724-0 3130 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@node DC4C0128-0 610 40
//@node 31CD7536-0 890 40
//@node B747C531-0 1170 40
//@node 262C493F-0 1450 40
//@node 7E2E5D15-0 1730 40
//@node 868A1338-0 2010 40
//@node 3304E427-0 2290 40
//@doomscript-blueprint end
