namespace map_marscity1 {

	void cache_sounds() {
		sys.cacheSoundShader ("mc1_scanner_rot1s");
		sys.cacheSoundShader ("mc1_scanner_3s_movement");
		sys.cacheSoundShader ("entrance_scanner_loop");
		sys.trigger ($speaker_mouse);			// Turn it off...
	}
	
	void toggle_intro_sounds() {
		sys.print ("Toggling speakers\n");
		sys.trigger ($speaker_83);
		sys.trigger ($speaker_84);
		sys.trigger ($speaker_85);
		sys.trigger ($speaker_86);
		sys.trigger ($speaker_87);
		sys.trigger ($speaker_88);
		sys.trigger ($speaker_89);
		sys.trigger ($speaker_90);
		sys.trigger ($speaker_91);
		sys.trigger ($speaker_92);
	}

	//turret gun movement
	void turret_loop() {
		while(1)
		{
			$security_cannon.time( 3 );
			$security_cannon.accelTime( 0 );
			$security_cannon.decelTime( .25 );
			
			$security_cannon.rotateOnce( '0 -30 0' );
			sys.waitFor($security_cannon);
			
			sys.wait(.5);

			$security_cannon.rotateOnce( '0 30 0' );
			sys.waitFor($security_cannon);
			
			sys.wait(.5);
		}
	}

	// mars city mice movers
	void Startmouse1() {
		while(1)
		{
			$mc_mouse1.time( 15 );
			$mc_mouse1.accelTime( 0 );
			$mc_mouse1.decelTime( 0 );
			sys.trigger ($speaker_mouse);			// Turn it on...
			$mc_mouse1.startSpline( $func_splinemover_3 );
			
			sys.waitFor($mc_mouse1);
			
			sys.trigger ($speaker_mouse);			// Turn it off...
			
			sys.wait(60);
			$mc_mouse1.removeInitialSplineAngles();
		}
	}

	// function for starting shutters1 sound
	void sound_shutter1_start()
	{
		sys.trigger ($speaker_shutters);
	}

	// function for stopping shutters1 sound
	void sound_shutter1_stop()
	{
		//sys.trigger ($speaker_shutters);	
	}


	void kitchenlightsoff()
	{
		sys.wait(1);
		$kitchen_swinglight_1.fadeOutLight(2);
		$kitchen_swinglight_2.fadeOutLight(2);
		$kitchen_swinglight_3.fadeOutLight(2);
		$kitchen_swinglight_4.fadeOutLight(2);
		$kitchen_swinglight_5.fadeOutLight(2);
		$kitchen_swinglight_6.fadeOutLight(2);

	}
	
	void windshutter1_open()
	{
		//start the kitchen lights fading
			thread kitchenlightsoff();

		/// starting shutter sound
		thread sound_shutter1_start();

		//might need this later
		//$windshutter1_gui.setGuiParm( "gui_parm1" , windstatus1);
		
		//fade in the bounce lightlight
		$shutter_bounce_light.fadeInLight(1.5);

		//times for shutters opening
		$windshutter1_1.time(1.5);
		$windshutter1_1.accelTime(1);
		$windshutter1_1.decelTime(.5);

		$windshutter1_2.time(1.5);
		$windshutter1_2.accelTime(1);
		$windshutter1_2.decelTime(.5);

		// Going up
		$windshutter1_1.rotateOnce( '180 0 0' ); 
		sys.wait(0.5);
		$windshutter1_2.rotateOnce( '180 0 0' ); 
		sys.waitFor($windshutter1_2);
		

		// stopping shutter sound
		thread sound_shutter1_stop();
	}

	void kitchenlightson()
	{
		sys.wait(3);
		$kitchen_swinglight_1.fadeInLight(2);
		$kitchen_swinglight_2.fadeInLight(2);
		$kitchen_swinglight_3.fadeInLight(2);
		$kitchen_swinglight_4.fadeInLight(2);
		$kitchen_swinglight_5.fadeInLight(2);
		$kitchen_swinglight_6.fadeInLight(2);

	}

	void windshutter1_close()
	{

		//start the kitchen lights fading
			thread kitchenlightson();

		// starting shutter sound
		thread sound_shutter1_start();

		// Fade bounce light
		$shutter_bounce_light.fadeOutLight(3);
		

		//times for shutters closing
		$windshutter1_1.time(3);
		$windshutter1_1.accelTime(2);
		$windshutter1_1.decelTime(1);

		$windshutter1_2.time(3);
		$windshutter1_2.accelTime(2);
		$windshutter1_2.decelTime(1);
			
		// Going down
		$windshutter1_1.rotateOnce( '-180 0 0' );
		sys.wait(0.25);
		$windshutter1_2.rotateOnce( '-180 0 0' );
		sys.waitFor($windshutter1_2);
			
		// stopping shutter sound
		thread sound_shutter1_stop();
	}

	////////////////////////////////////////////////////
	//
	//	Mars City Bio Scanners
	//
	////////////////////////////////////////////////////
	void bioscan_lockdoors () 
	{
		//close both doors
		$func_door_1.close();
		$func_door_9.close();

		//lock both doors
		$func_door_1.lock(2);
		$func_door_9.lock(2);

		//trigger the relay to remove things in the Hangar
		sys.trigger ( $trigger_remove_floods );

		//change gui and shader parms on doors
		$func_static_4456.setShaderParm (7, 0);
		$func_static_929.setShaderParm (7, 0);
		$func_door_1.setGuiParm ( "gui_parm3" , 0);
		$func_door_1.setShaderParm (7, 0);
		$func_door_9.setGuiParm ( "gui_parm3" , 0);
		$func_door_9.setShaderParm (7, 0);
	}

	void bioscan_opendoor () 
	{
		//trigger the lights to fade
		sys.trigger($bioscan_fadein);

		//slight delay to make sure the sentry is in motion
		//before the doors open
		sys.wait(.85);

		//unlock door
		$func_door_9.lock(0);

		//open door
		$func_door_9.open();
		
		//lock the little room door
		$func_door_11.lock(2);

		//change gui parms on doors
		$func_door_9.setGuiParm ( "gui_parm3" , 1);
		$func_door_9.setShaderParm (7, 1);
		$func_static_4456.setShaderParm (7, 1);
		
		toggle_intro_sounds();				// Trigger the start sounds on when the player gets to this point
		turret_loop();						// Start the turret looping here...
	}

	void bioscan_go () 
	{
		//trigger the particles
		$scan_lazmodel_1.startSoundShader ("entrance_scanner_loop", SND_CHANNEL_VOICE );
		$scan_lazmodel_2.startSoundShader ("entrance_scanner_loop", SND_CHANNEL_VOICE );
		sys.trigger($scan_particle_1);
		sys.trigger($scan_particle_2);

		//change the gui on bioscanner
		sys.trigger($bio_scanner);
		
		//trigger the lights to fade
		sys.trigger($bioscan_fadeout);

		sys.wait(.4);

		//trigger the laser models to unhide them
		
		sys.trigger($scan_lazmodel_1);
		sys.trigger($scan_lazmodel_2);

		//set times 
		//up 64 scan_anchor
		
		$scan_anchor.time (1);
		$scan_anchor.startSoundShader ("mc1_scanner_3s_movement", SND_CHANNEL_VOICE);
		
		$scan_anchor.move ( UP, 64 );
		sys.waitFor ($scan_anchor);

		//rotate 90 scan_anchor
		$scan_anchor.rotateOnce ( '0 0 -90' );
		sys.waitFor ($scan_anchor);

		//move 24 scan_anchor
		$scan_anchor.move ( SOUTH, -24 );
		sys.waitFor ($scan_anchor);

		//rotate 720 scan_thing_1
		$scan_thing_1.startSoundShader ("mc1_scanner_rot1s", SND_CHANNEL_VOICE);
		$scan_thing_1.rotateOnce ( '360 0 0' );
	

		//rotate 720 scan_thing_2
		$scan_thing_2.startSoundShader ("mc1_scanner_rot1s", SND_CHANNEL_VOICE);
		$scan_thing_2.rotateOnce ( '360 0 0' );

		//wait for rotating to stop and a bit extra
		sys.waitFor ($scan_thing_1);
		sys.wait (1);
		
		//move 24 scan_anchor
		$scan_anchor.startSoundShader ("mc1_scanner_3s_movement", SND_CHANNEL_VOICE);
		$scan_anchor.move ( SOUTH, 24 );
		sys.waitFor ($scan_anchor);

		//rotate 90 scan_anchor
		$scan_anchor.rotateOnce ( '0 0 90' );
		sys.waitFor ($scan_anchor);

		//down 64 scan_anchor
		$scan_anchor.move ( DOWN, 64 );
		sys.waitFor ($scan_anchor);

		//trigger the particles
		
		sys.trigger($scan_particle_1);
		
		sys.trigger($scan_particle_2);

		sys.wait(2);

		//trigger the laser models to hide them
		$scan_lazmodel_1.stopSound (SND_CHANNEL_VOICE, false);
		sys.trigger($scan_lazmodel_1);
		$scan_lazmodel_2.stopSound (SND_CHANNEL_VOICE, false);
		sys.trigger($scan_lazmodel_2);

    }

	void bioscan_noreturn () 
	{
		//close both doors
		$func_door_9.close();

		//lock both doors
		$func_door_9.lock(2);

		//change gui parms on doors
		$func_door_9.setGuiParm ( "gui_parm3" , 0);
		$func_door_9.setShaderParm (7, 0);
		$func_static_4456.setShaderParm (7, 0);
	}

	void show_pda () 
	{
		$player_pda.show();
	}

	//move fog brush in the hanger
	void move_hangar_fog () 
	{
		$hanger_fog_mover.time( 5 );
		$hanger_fog_mover.move( UP, 320 );
	}




	////////////////////////////////////////////////////
	//
	//	MAIN
	//
	////////////////////////////////////////////////////
	void main () {
		cache_sounds();
		
		//setup_objects ();
		//init_world();
		
	}
}

//@doomscript-blueprint begin 6
//@source 748DE4C5
//@catalog 0C260740
//@node B832CE32-0 40 40
//@node 1C7C6363-0 330 40
//@node 6045FCBA-0 610 40
//@node 7BB5F279-0 890 40
//@node CB9EC5EA-0 1170 40
//@node A929DFED-0 40 40
//@node 2F5D7176-0 330 40
//@node B8B04E2B-0 610 40
//@node FA2950C2-0 890 40
//@node DF81BA81-0 1170 40
//@node 98F9E700-0 1450 40
//@node 0D3D0E5F-0 1730 40
//@node 0D70ABF6-0 2010 40
//@node 81B3D355-0 2290 40
//@node 4B8C0887-0 2570 40
//@node D60BACA8-0 2850 40
//@node 9CE26889-0 3130 40
//@node 6D30308E-0 40 40
//@node 6768F4CB-0 330 40
//@node 55D83EDF-0 125 145
//@node FA95A9D6-0 610 200
//@node 41DF4B31-0 890 200
//@node 2010624D-0 1170 200
//@node 8AF6D886-0 1450 200
//@node C2C3EC77-0 1730 200
//@node BD30BEE1-0 2010 200
//@node E018DB87-0 2290 200
//@node C2C3EC77-1 2570 200
//@node BD30BEE1-1 2850 200
//@node 2CA54F99-0 40 40
//@node 67BF1B6E-0 330 40
//@node F5CC5635-0 125 145
//@node DB644CE5-0 610 200
//@node 1338EFA9-0 890 200
//@node 01E42138-0 1170 200
//@node 9F8C0B25-0 1450 200
//@node 2133A86A-0 1730 200
//@node E8BD2FAB-0 2010 200
//@node 9F8C0B25-1 2290 200
//@node F27224B1-0 2570 200
//@node 0859302F-0 2850 200
//@node CC990EFE-0 40 40
//@node 1E78A6E9-0 330 40
//@node 336AF886-0 40 40
//@node 83904403-0 40 40
//@node 600D514C-0 330 40
//@node B30D363C-0 610 40
//@node 72D9F077-0 890 40
//@node 05932B12-0 1170 40
//@node C389686D-0 1450 40
//@node 28706B68-0 1730 40
//@node 0BD701B3-0 2010 40
//@node 8212C124-0 40 40
//@node 6B2251C0-0 330 40
//@node D59FE9E3-0 610 40
//@node B36FF73C-0 890 40
//@node 27843201-0 1170 40
//@node 716B48B8-0 1450 40
//@node E1E879A7-0 1730 40
//@node F4FB4C12-0 2010 40
//@node 7711F1B9-0 2290 40
//@node E6D35544-0 2570 40
//@node 6F768313-0 2850 40
//@node 4D962FC3-0 3130 40
//@node F6C35450-0 3410 40
//@node E3A2FDAA-0 3690 40
//@node 3FCA9E85-0 3970 40
//@node 033DED1F-0 40 40
//@node C9926EBA-0 330 40
//@node 2CE364E1-0 610 40
//@node 2715FFD8-0 890 40
//@node A9F6E5DB-0 1170 40
//@node DBBD7E32-0 1450 40
//@node 3005B76D-0 1730 40
//@node A4B53944-0 2010 40
//@node 1C3E1138-0 40 40
//@node 13F872C2-0 330 40
//@node 7C82BD37-0 610 40
//@node F519DE04-0 890 40
//@node 1433EBA2-0 1170 40
//@node F65E45B5-0 1450 40
//@node FC3EBD75-0 1730 40
//@node CFBA64C5-0 2010 40
//@node 43E520E4-0 2290 40
//@node 3851BE30-0 2570 40
//@node 948D5B4C-0 2850 40
//@node FDF7E4C5-0 3130 40
//@node D464A49D-0 3410 40
//@node 959AB3CE-0 3690 40
//@node F2844D91-0 3970 40
//@node C736AAF3-0 40 40
//@node 7137BC9A-0 330 40
//@node C6E241C2-0 610 40
//@node 746CB977-0 890 40
//@node 76A1022F-0 1170 40
//@node 70AD66DB-0 1450 40
//@node ACFB920A-0 1730 40
//@node 9427579D-0 2010 40
//@node FCD79A8E-0 2290 40
//@node 0FD4102A-0 2570 40
//@node 8533F836-0 2850 40
//@node 4180E352-0 3130 40
//@node B934A101-0 40 40
//@node D5D11969-0 330 40
//@node CDDCBEE4-0 610 40
//@node 0DB7BDFF-0 890 40
//@node 38AF057C-0 1170 40
//@node AC4BB504-0 1450 40
//@node 52228F43-0 1730 40
//@node A4DFD7DB-0 2010 40
//@node C7A25357-0 2290 40
//@node DA6CE53F-0 2570 40
//@node EC4B3D9A-0 2850 40
//@node CDCAF797-0 40 40
//@node 3208E8A1-0 330 40
//@node 55F3F4A0-0 610 40
//@node 323CF896-0 890 40
//@node 457958A3-0 1170 40
//@node 7EF705D9-0 1450 40
//@node 9EC1717C-0 1730 40
//@node D28E89F7-0 2010 40
//@node D39B9438-0 2290 40
//@node 9A725019-0 2570 40
//@node 4D4CADFA-0 2850 40
//@node 95C4EB3D-0 3130 40
//@node 6DC98DC6-0 3410 40
//@node 1CA16A95-0 3690 40
//@node 6B7CDFB2-0 3970 40
//@node 1CA16A95-1 4250 40
//@node 92596D9D-0 4530 40
//@node 1CA16A95-2 4810 40
//@node 0AEF28D3-0 5090 40
//@node 385012CC-0 5370 40
//@node A42DC6F8-0 5650 40
//@node 6A99B9B5-0 5930 40
//@node B3D810FC-0 6210 40
//@node A2668B02-0 6490 40
//@node 95C4EB3D-1 6770 40
//@node 8FD7B178-0 7050 40
//@node 1CA16A95-3 7330 40
//@node 3CEC3977-0 7610 40
//@node 1CA16A95-4 7890 40
//@node D5431401-0 8170 40
//@node 1CA16A95-5 8450 40
//@node 323CF896-1 8730 40
//@node 457958A3-1 9010 40
//@node 13A61E71-0 9290 40
//@node 446A3755-0 9570 40
//@node D39B9438-1 9850 40
//@node 87129C2C-0 10130 40
//@node 9A725019-1 10410 40
//@node DDB59590-0 40 40
//@node 51A5B661-0 330 40
//@node 331E7A6C-0 610 40
//@node 7D76F859-0 890 40
//@node 7A2D9F1B-0 1170 40
//@node B2B52CF5-0 1450 40
//@node A42C1D9C-0 40 40
//@node 33039356-0 330 40
//@node 6D0C0859-0 40 40
//@node 577F694D-0 330 40
//@node FDDDF024-0 610 40
//@node 32687650-0 40 40
//@node 6DADACF7-0 330 40
//@doomscript-blueprint end
