namespace map_hellhole {

	void move_entrance_lift()
	{
		//level load lift
		$hellhole_start_lift.time(10);
		$hellhole_start_lift.accelTime(.5);
		$hellhole_start_lift.decelTime(.5);

		$hellhole_start_lift.move(DOWN, 1280);
	}

	void move_first_doors()
	{
		sys.trigger($hhbrickdoors1_portal);
		$hhbrickdoor_1.accelTime(.5);
		$hhbrickdoor_1.decelTime(.5);

		$hhbrickdoor_2.accelTime(.5);
		$hhbrickdoor_2.decelTime(.5);

		$hhbrickdoor_1.time(1);
		
		$hhbrickdoor_1.startSoundShader ("hh_door_movement_1", SND_CHANNEL_VOICE2 );
		
		$hhbrickdoor_1.move(WEST, 32);
		$hhbrickdoor_2.time	(1);
		$hhbrickdoor_2.move(WEST, 32);
		sys.waitFor($hhbrickdoor_1);

		$hhbrickdoor_1.time(2);
		$hhbrickdoor_1.startSoundShader ("hh_door_movement_2", SND_CHANNEL_VOICE );
		$hhbrickdoor_1.move(SOUTH, 64);
		$hhbrickdoor_2.time	(2);
		$hhbrickdoor_2.move(NORTH, 64);
		sys.waitFor($hhbrickdoor_1);
	}

	void move_first_doors_close()

	{
		$hhbrickdoor_1.accelTime(.5);
		$hhbrickdoor_1.decelTime(.5);

		$hhbrickdoor_2.accelTime(.5);
		$hhbrickdoor_2.decelTime(.5);

		$hhbrickdoor_1.time(2);
		$hhbrickdoor_1.startSoundShader ("hh_door_movement_2", SND_CHANNEL_VOICE2 );
		$hhbrickdoor_1.move(NORTH, 64);
		$hhbrickdoor_2.time	(2);
		$hhbrickdoor_2.move(SOUTH, 64);		
		sys.waitFor($hhbrickdoor_1);

		$hhbrickdoor_1.time(1);
		$hhbrickdoor_1.startSoundShader ("hh_door_movement_1", SND_CHANNEL_VOICE );
		$hhbrickdoor_1.move(EAST, 32);
		$hhbrickdoor_2.time	(1);
		$hhbrickdoor_2.move(EAST, 32);		
		sys.waitFor($hhbrickdoor_1);
		sys.trigger($hhbrickdoors1_portal);
	}

	void hellevator_down()
	{
		$hellevator.startSoundShader ("hh_rockride_8s", SND_CHANNEL_VOICE );
		
		$hellevator.time(8);
		$hellevator.accelTime(5);
		$hellevator.decelTime(.5);

		$hellevator.move(DOWN, 2020);	
	}

	void move_next_doors_open()
	{
		sys.trigger($hhbrickdoors2_portal);
		$hhbrickdoor_3.accelTime(.5);
		$hhbrickdoor_3.decelTime(.5);

		$hhbrickdoor_4.accelTime(.5);
		$hhbrickdoor_4.decelTime(.5);

		$hhbrickdoor_3.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE);
		$hhbrickdoor_3.time(3);
		$hhbrickdoor_3.move(NORTH, 32);
		$hhbrickdoor_4.time	(3);
		$hhbrickdoor_4.move(NORTH, 32);		
		sys.waitFor($hhbrickdoor_3);

		$hhbrickdoor_3.time(5);
		$hhbrickdoor_3.startSoundShader ("hh_door_movement_5s", SND_CHANNEL_VOICE2);
		$hhbrickdoor_3.move(WEST, 64);
		$hhbrickdoor_4.time	(5);
		$hhbrickdoor_4.move(EAST, 64);		
		sys.waitFor($hhbrickdoor_3);

	}

	void move_next_doors_close()
	{
		$hhbrickdoor_3.accelTime(.5);
		$hhbrickdoor_3.decelTime(.5);

		$hhbrickdoor_4.accelTime(.5);
		$hhbrickdoor_4.decelTime(.5);

		$hhbrickdoor_3.time(5);
		$hhbrickdoor_3.startSoundShader ("hh_door_movement_5s", SND_CHANNEL_VOICE);
		$hhbrickdoor_3.move(EAST, 64);
		$hhbrickdoor_4.time	(5);
		$hhbrickdoor_4.move(WEST, 64);		
		sys.waitFor($hhbrickdoor_3);

		$hhbrickdoor_3.time(3);
		$hhbrickdoor_3.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE2);
		$hhbrickdoor_3.move(SOUTH, 32);
		$hhbrickdoor_4.time	(3);
		$hhbrickdoor_4.move(SOUTH, 32);		
		sys.waitFor($hhbrickdoor_3);
		sys.trigger($hhbrickdoors2_portal);

	}

	void move_last_doors_open()
	{
		sys.trigger($hhbrickdoors3_portal);
		$hhbrickdoor_5.accelTime(.5);
		$hhbrickdoor_5.decelTime(.5);

		$hhbrickdoor_6.accelTime(.5);
		$hhbrickdoor_6.decelTime(.5);

		$hhbrickdoor_5.time(3);
		
		$hhbrickdoor_5.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE2);
		
		$hhbrickdoor_5.move(NORTH, 32);
		$hhbrickdoor_6.time	(3);
		$hhbrickdoor_6.move(NORTH, 32);		
		sys.waitFor($hhbrickdoor_5);

		$hhbrickdoor_5.time(5);
		
		$hhbrickdoor_5.startSoundShader ("hh_door_movement_5s", SND_CHANNEL_VOICE);
		
		$hhbrickdoor_5.move(WEST, 64);
		$hhbrickdoor_6.time	(5);
		$hhbrickdoor_6.move(EAST, 64);		
		sys.waitFor($hhbrickdoor_5);

	}

	void move_last_doors_close()
	{
		$hhbrickdoor_5.accelTime(.5);
		$hhbrickdoor_5.decelTime(.5);

		$hhbrickdoor_6.accelTime(.5);
		$hhbrickdoor_6.decelTime(.5);

		$hhbrickdoor_5.time(5);
		$hhbrickdoor_5.startSoundShader ("hh_door_movement_5s", SND_CHANNEL_VOICE2);
		$hhbrickdoor_5.move(EAST, 64);
		$hhbrickdoor_6.time	(5);
		$hhbrickdoor_6.move(WEST, 64);		
		sys.waitFor($hhbrickdoor_5);

		$hhbrickdoor_5.time(3);
		$hhbrickdoor_5.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE);
		$hhbrickdoor_5.move(SOUTH, 32);
		$hhbrickdoor_6.time	(3);
		$hhbrickdoor_6.move(SOUTH, 32);		
		sys.waitFor($hhbrickdoor_5);
		sys.trigger($hhbrickdoors3_portal);

	}

	void move_id_brick()
	{
		$id_brick.accelTime(.2);
		$id_brick.decelTime(.2);

		$id_brick.time(1.5);
		
		$id_brick.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE2);
		
		$id_brick.move(NORTH, 16);
		$id_brick.time	(1.5);
		sys.waitFor($id_brick);

	}

	void move_id_door()
	{
		$id_door.accelTime(.5);
		$id_door.decelTime(.5);

		$id_door.time(3);
		
		$id_door.startSoundShader ("hh_door_movement_3s", SND_CHANNEL_VOICE2);
		
		$id_door.move(WEST, 32);
		$id_door.time	(3);
		sys.waitFor($id_door);

		$id_door.time(5);
		
		$id_door.startSoundShader ("hh_door_movement_5s", SND_CHANNEL_VOICE);
		
		$id_door.move(UP, 128);
		$id_door.time	(5);
		sys.waitFor($id_door);

	}

	void spark_mover ()
	{
		//turn on the sparks
		sys.trigger ($doorsparks);

		//move the sparkmover down and wait for it to finish
		$sparkmover.move (DOWN, 116);
		sys.waitFor ($sparkmover);
		
		//turn off the sparks
		sys.trigger ($doorsparks);
	}

	void harden_lava( entity ent, float parm, float fromValue, float toValue, float totalTime ) {
		float i;
		float frac;
		float numTics;

		// customized for the shader "textures/hell/hellhole_lavascroll_fade"
		
		// convert to the total number of game tics
		numTics = totalTime * sys.getTicsPerSecond();

		float parm3 = fromValue;
		float parm5 = sys.getTime()*-0.2;
		float parm6 = sys.getTime()*-0.1;
		float parm7 = -sys.getTime();

		for( i = 0; i < numTics; i++ ) {
			parm5 = (sys.getTime()+parm7)*(-0.2*parm3)+parm5;
			parm6 = (sys.getTime()+parm7)*(-0.1*parm3)+parm6;
			parm7 = -sys.getTime();

			frac = i / numTics;
			parm3 = toValue * frac + fromValue * ( 1 - frac );

			ent.setShaderParm( 3, parm3 );
			ent.setShaderParm( 5, parm5 );
			ent.setShaderParm( 6, parm6 );
			ent.setShaderParm( 7, parm7 );

			// wait one game frame
			sys.waitFrame();
		}
		
		// make sure we are set to exactly the destination value
		parm3 = toValue;
		parm5 = (sys.getTime()+parm7)*(-0.2*parm3)+parm5;
		parm6 = (sys.getTime()+parm7)*(-0.1*parm3)+parm6;
		parm7 = -sys.getTime();

		ent.setShaderParm( 3, parm3 );
		ent.setShaderParm( 5, parm5 );
		ent.setShaderParm( 6, parm6 );
		ent.setShaderParm( 7, parm7 );
	}

	void interpolateRocksShader( entity ent, float parm, float fromValue, float toValue, float totalTime ) {
		float i;
		float value;
		float frac;
		float numTics;
		
		// convert to the total number of game tics
		numTics = totalTime * sys.getTicsPerSecond();

		for( i = 0; i < numTics; i++ ) {
			frac = i / numTics;
			value = toValue * frac + fromValue * ( 1 - frac );
			ent.setShaderParm( parm, value );
			
			// wait one game frame
			sys.waitFrame();
		}
		
		// make sure we are set to exactly the destination value
		ent.setShaderParm( parm, toValue );
	}

	void fade_lava_thread() {
		harden_lava( $hellhole_cyberdeathrocks_2, 3, 1, 0, 3 );
		thread fadeOutEnt( $func_static_808, '1 1 1', 1 );
		interpolateRocksShader( $hellhole_cyberdeathrocks_2, 0, 1, 0, 1 );
	}

	void fade_lava() {
		thread fade_lava_thread();
	}

	void cache_sounds() {
		sys.cacheSoundShader ("hh_rockride_8s");
		sys.cacheSoundShader ("hh_door_movement_3s");
		sys.cacheSoundShader ("hh_door_movement_5s");
		sys.cacheSoundShader ("hh_door_movement_1");
		sys.cacheSoundShader ("hh_door_movement_2");
	}

	void fade_final_room_down() {
		$hhs_1.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_2.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_3.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_4.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_5.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_6.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_7.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_8.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_9.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_10.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_11.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_12.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$hhs_13.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$speaker_60.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$speaker_64.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$speaker_67.fadeSound (SND_CHANNEL_ANY, -60, 5);
		$speaker_70.fadeSound (SND_CHANNEL_ANY, -60, 5);
	}

	void fade_final_room_up() {
		$hhs_1.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_2.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_3.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_4.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_5.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_6.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_7.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_8.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_9.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_10.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_11.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_12.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$hhs_13.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$speaker_60.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$speaker_64.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$speaker_67.fadeSound (SND_CHANNEL_ANY, -1, 5);
		$speaker_70.fadeSound (SND_CHANNEL_ANY, -1, 5);
	}

	void fadeup_thread() {
		$speaker_29.fadeSound (SND_CHANNEL_ANY, -60, 5);	// Fade this speaker down first...
		sys.wait (10);
		thread fade_final_room_up();
	}

	void main ()
	{
		//bind_objects();
		//init_world();
		sys.setcvar( "g_nightmare", "1" );
		cache_sounds();
		thread move_entrance_lift();
		thread fade_final_room_down();
	}
}

//@doomscript-blueprint begin 6
//@source 2A536D28
//@catalog 0C260740
//@node 6336FFD5-0 40 40
//@node EFC2812F-0 330 40
//@node 90FD411D-0 610 40
//@node C132AE36-0 890 40
//@node 30CF45FD-0 1170 40
//@node CA5B402B-0 40 40
//@node 653203DE-0 330 40
//@node 72C517AE-0 610 40
//@node DC4BAC89-0 890 40
//@node 80F9BCB9-0 1170 40
//@node 6D5229F2-0 1450 40
//@node B2DFA386-0 1730 40
//@node 47F82BDD-0 2010 40
//@node CC5CFF61-0 2290 40
//@node 2263B0E9-0 2570 40
//@node E57963E4-0 2850 40
//@node CC58AFCB-0 3130 40
//@node C57C9FD3-0 3410 40
//@node 7E87212E-0 3690 40
//@node 28F1CAF6-0 3970 40
//@node 5B8CF508-0 4250 40
//@node DFC277EB-0 4530 40
//@node CC58AFCB-1 4810 40
//@node 6E4A2760-0 40 40
//@node 22C33415-0 330 40
//@node 1A7F528E-0 610 40
//@node EBCD497A-0 890 40
//@node 9D8F4635-0 1170 40
//@node 794A1BC0-0 1450 40
//@node 1B4B1DB1-0 1730 40
//@node 6C743A0F-0 2010 40
//@node 19D37419-0 2290 40
//@node B0008ADA-0 2570 40
//@node 017E023E-0 2850 40
//@node BFD1EF41-0 3130 40
//@node 1E79340A-0 3410 40
//@node 27D3EF46-0 3690 40
//@node 52FCB838-0 3970 40
//@node D0923783-0 4250 40
//@node 017E023E-1 4530 40
//@node E319ECF5-0 4810 40
//@node 285A5D26-0 40 40
//@node 69842BEC-0 330 40
//@node 067CD963-0 610 40
//@node B0581B84-0 890 40
//@node 582D3937-0 1170 40
//@node 00A0EBDD-0 1450 40
//@node A88107F3-0 40 40
//@node 508B5A75-0 330 40
//@node FDB3CB2C-0 610 40
//@node DC3ACB93-0 890 40
//@node 821A1B37-0 1170 40
//@node 5D524864-0 1450 40
//@node E8027824-0 1730 40
//@node 12427E6A-0 2010 40
//@node F7D3C889-0 2290 40
//@node C4E1D211-0 2570 40
//@node A36ADDDE-0 2850 40
//@node 574E5B21-0 3130 40
//@node EC378544-0 3410 40
//@node A9D22000-0 3690 40
//@node 2704F9C0-0 3970 40
//@node 1F4E63BB-0 4250 40
//@node 6E281BEF-0 4530 40
//@node 574E5B21-1 4810 40
//@node 61CE30F5-0 40 40
//@node F1B27376-0 330 40
//@node 2726B151-0 610 40
//@node 060CE64D-0 890 40
//@node B82F8166-0 1170 40
//@node 3F65F712-0 1450 40
//@node 9C9AA488-0 1730 40
//@node 3074EEC0-0 2010 40
//@node 98280D99-0 2290 40
//@node CBF78CAB-0 2570 40
//@node 41672083-0 2850 40
//@node 99A9E64C-0 3130 40
//@node B16B9914-0 3410 40
//@node F3CE59E9-0 3690 40
//@node 7293D5C3-0 3970 40
//@node 399B9D82-0 4250 40
//@node 41672083-1 4530 40
//@node CFC00247-0 4810 40
//@node D7C1C7EC-0 40 40
//@node 77DC1623-0 330 40
//@node 54ADB129-0 610 40
//@node 03EE3822-0 890 40
//@node 6970615E-0 1170 40
//@node BEF12F39-0 1450 40
//@node 75CA2873-0 1730 40
//@node FA07D5F1-0 2010 40
//@node 3DC816D8-0 2290 40
//@node D4A72E66-0 2570 40
//@node B4612BFB-0 2850 40
//@node A7D45642-0 3130 40
//@node 9B5E6049-0 3410 40
//@node 2FE1F2D3-0 3690 40
//@node 89DF3657-0 3970 40
//@node C73FA4A8-0 4250 40
//@node 23BF9708-0 4530 40
//@node A7D45642-1 4810 40
//@node F67059F0-0 40 40
//@node 9984B5BD-0 330 40
//@node 1743CC56-0 610 40
//@node 3F60C2A2-0 890 40
//@node BA2C6D1D-0 1170 40
//@node 07CE59E5-0 1450 40
//@node C4DCC3E7-0 1730 40
//@node 62A325A5-0 2010 40
//@node 56E106EC-0 2290 40
//@node 4C5078CA-0 2570 40
//@node AF97BB16-0 2850 40
//@node F9C76C67-0 3130 40
//@node C4504B65-0 3410 40
//@node E1EAB772-0 3690 40
//@node 7DD982B2-0 3970 40
//@node C50D824D-0 4250 40
//@node AF97BB16-1 4530 40
//@node 79BFDE0F-0 4810 40
//@node 8A684DE6-0 40 40
//@node 2E9C5A28-0 330 40
//@node 110785DF-0 610 40
//@node AE50C970-0 890 40
//@node 61C954DD-0 1170 40
//@node 6F2B563E-0 1450 40
//@node 1717987C-0 1730 40
//@node 05829A44-0 2010 40
//@node 2E812995-0 40 40
//@node EA37314D-0 330 40
//@node 9C59CC66-0 610 40
//@node 0893B137-0 890 40
//@node 53576895-0 1170 40
//@node C5C8A948-0 1450 40
//@node 0986AEC3-0 1730 40
//@node 0B43137E-0 2010 40
//@node 95FC0475-0 2290 40
//@node 30F10FE7-0 2570 40
//@node 27430BB4-0 2850 40
//@node 2F1AE699-0 3130 40
//@node 0B43137E-1 3410 40
//@node 10F73924-0 40 40
//@node D75D7125-0 330 40
//@node FC570E35-0 610 40
//@node AA9318CD-0 890 40
//@node D75D7125-1 1170 40
//@node 026DB4D6-0 40 40
//@node 840FC8C5-0 330 40
//@node 5197807F-0 105 145
//@node 794EDCF9-0 610 40
//@node 8B1E1501-0 405 145
//@node 35B63D9E-0 200 145
//@node 1005EB20-0 200 229
//@node 1862FF3B-0 890 200
//@node C330049E-0 685 305
//@node 328ED6F5-0 480 305
//@node 2C8ECD83-0 480 389
//@node 2E8ED0A9-0 480 473
//@node DAE20C88-0 1170 200
//@node F6A896B7-0 965 305
//@node 00314920-0 760 305
//@node 053150FF-0 760 389
//@node 04314F6C-0 760 473
//@node 358F74E4-0 1450 200
//@node 0B8D0BB9-0 1225 305
//@node ED9DD90C-0 1730 200
//@node 0D78473A-0 1525 305
//@node 0F06A907-0 1320 305
//@node 04A425E1-0 1320 389
//@node C4276729-0 2010 200
//@node AC1692A4-0 1805 305
//@node 71F8B904-0 1600 305
//@node C1169064-0 3410 200
//@node 2C1DAE98-0 2085 392
//@node A1E521C4-0 3690 200
//@node F223D2E8-0 2365 392
//@node A1E5E0B6-0 3970 200
//@node 7CB98FC6-0 2645 392
//@node 28D0B4B4-0 4250 200
//@node 6B16F946-0 2925 392
//@node 53DE234B-0 4530 200
//@node 7CC8C5C8-0 3690 40
//@node 1862FF3B-1 3970 40
//@node 62703A33-0 3765 145
//@node 5BBB9142-0 3560 145
//@node 55BB87D0-0 3560 229
//@node 57BB8AF6-0 3560 313
//@node DAE20C88-1 4250 40
//@node DF7CD0EA-0 4045 145
//@node 8A95FAA3-0 3840 145
//@node 8D95FF5C-0 3840 229
//@node 8E9600EF-0 3840 313
//@node 358F74E4-1 4530 40
//@node 6727C2BE-0 4305 145
//@node C1169064-1 5930 40
//@node 061F340F-0 4605 232
//@node A1E521C4-1 6210 40
//@node 447C9A6F-0 4885 232
//@node A1E5E0B6-1 6490 40
//@node 5E03CED5-0 5165 232
//@node 28D0B4B4-1 6770 40
//@node 009E25CD-0 5445 232
//@node AFD4468F-0 40 40
//@node C5372522-0 330 40
//@node 3609715A-0 105 145
//@node 9C976CA6-0 610 40
//@node FD38AA6D-0 405 145
//@node 6300C390-0 200 145
//@node 56C91D8E-0 200 229
//@node 7530D7A3-0 890 200
//@node 86563701-0 685 305
//@node 9CFD2AAA-0 480 305
//@node B5D0866C-0 480 389
//@node CA467476-0 1170 200
//@node 90C64FFD-0 965 305
//@node 022522E1-0 760 305
//@node F87607D0-0 1450 200
//@node 0F29C839-0 1245 392
//@node 5C1700C0-0 1730 200
//@node B594A1A5-0 2010 40
//@node C927ECDF-0 40 40
//@node B0B8BB69-0 330 40
//@node 98A9AE3C-0 610 40
//@node DFA40D4B-0 890 40
//@node 0F0E898A-0 40 40
//@node AE1A0D5A-0 330 40
//@node B832CE32-0 40 40
//@node 1901393B-0 330 40
//@node 476B53F5-0 610 40
//@node 72762143-0 890 40
//@node 153B5330-0 1170 40
//@node A15D1D53-0 1450 40
//@node A0D4AA9F-0 40 40
//@node 91DEBED5-0 330 40
//@node 56C1FC86-0 610 40
//@node 1797C36F-0 890 40
//@node 31726FC0-0 1170 40
//@node 4AC47899-0 1450 40
//@node CD89F62A-0 1730 40
//@node 45A9E293-0 2010 40
//@node 564D52A4-0 2290 40
//@node F64C42FD-0 2570 40
//@node 44E2FF29-0 2850 40
//@node ACC27A90-0 3130 40
//@node 91BF4723-0 3410 40
//@node FCEF60FA-0 3690 40
//@node 6C61FAE0-0 3970 40
//@node D917E49C-0 4250 40
//@node 502F640F-0 4530 40
//@node 9F737883-0 4810 40
//@node D922ED36-0 40 40
//@node 47622491-0 330 40
//@node 157881B8-0 610 40
//@node 8B0CB9BB-0 890 40
//@node 2F3723B2-0 1170 40
//@node 41225C7D-0 1450 40
//@node 1E3D3034-0 1730 40
//@node 73F3E587-0 2010 40
//@node 89BFB5CE-0 2290 40
//@node 03F83869-0 2570 40
//@node 1468726B-0 2850 40
//@node 1AA286E8-0 3130 40
//@node 8C6809C1-0 3410 40
//@node 2CA4C7A6-0 3690 40
//@node EE436C54-0 3970 40
//@node 2EEAE358-0 4250 40
//@node DD7865B1-0 4530 40
//@node 10F251CD-0 4810 40
//@node B368B9DB-0 40 40
//@node 37B99171-0 330 40
//@node 0F96293A-0 610 40
//@node F879C52A-0 890 40
//@node 32687650-0 40 40
//@node BEDFC2EB-0 330 40
//@node 6DADACF7-0 610 40
//@node C7ED62A2-0 890 40
//@node DF6D1000-0 1170 40
//@doomscript-blueprint end
