namespace map_cpu {
	
	float	RAISE_HELL_PILLARS = 0;
	float	PLAYED_TRITE_STINGER = FALSE;
		
	void init_world() {
		$fixed_panel.hide();
	}

	void trite_stinger() {
		if ( PLAYED_TRITE_STINGER == FALSE ) {
			PLAYED_TRITE_STINGER = TRUE;
			sys.trigger ($cpu1_monster_trite_1);
			sys.trigger ($trite_stinger_2);
			sys.trigger ($trite_stinger_3);
		}
	}

	void trigger_secmon_exit() {
		sys.trigger ($trigger_relay_20);
		sys.wait (1.2);
		
		sys.trigger ($trigger_relay_21);
		sys.wait (2);
		
		sys.trigger ($trigger_relay_22);
		sys.wait (0.8);
		
		sys.trigger ($trigger_relay_23);
	}
/*
	void haunted_cabinet() {
		
//		sys.print ("Entering haunted_cabinet...\n");
		
                $anchor.time (.3);
		$anchor.moveTo ($hcab_p1);
		sys.waitFor ($anchor);
		
		sys.wait (.1);
		
		$anchor.moveTo ($hcab_p2);
		sys.waitFor ($anchor);
		
		//$fc1.unbind();
		$anchor.moveTo ($hcab_p3);
		sys.trigger ($func_forcefield_4);
		
		sys.wait (0.4);
				
		//sys.waitFor ($anchor);
		$fc1.unbind();
	
	}
*/

	/*
		Returns a random vector from 0-maxValue for each axis
	*/
		
	vector getRandomVector(float maxX, float maxY, float maxZ) {
		vector	vec;
		vec_x = int ( sys.random (maxX) );
		vec_y = int ( sys.random (maxY) );
		vec_z = int ( sys.random (maxZ) );
		
		return vec;
	}
	
	// Open ceiling hatch area in monitoring room.
	void open_cpuhatch() {
		$ladder_floor_hatch.time (0.5);
		$cpuladder.time (3);
		$ladder_ceiling_panel.time (0.5);
		
		$ladder_floor_hatch.move (DOWN, 8);
		$ladder_ceiling_panel.move (UP, 8);
		
		sys.waitFor ($ladder_floor_hatch);
		
		$ladder_floor_hatch.move (SOUTH, 72);
		$ladder_ceiling_panel.move (SOUTH, 72);
		
		sys.waitFor ($ladder_floor_hatch);
		
		$cpuladder.accelTime (1);
		$cpuladder.decelTime (2);
		$cpuladder.move (UP, 264);	
	}	

	
	// HK Lift before Lab A door
	void raise_hlift() {
		$hlift.speed (32);
		$hlift.move (UP, 160);
		sys.wait (0.2);
		
		$mb1.remove();
		$mb2.remove();
		$mb3.remove();
		$mb4.remove();
		
		//sys.trigger ($mb1);
		//sys.trigger ($mb2);
		//sys.trigger ($mb3);
		//sys.trigger ($mb4);
		
		sys.waitFor ($hlift);
		sys.print ("stopped moving\n");		

	}


	void raise_hell_pillars() {
		if (RAISE_HELL_PILLARS == 0) {
			RAISE_HELL_PILLARS = 1;
			$hp_01_anchor.rotateOnce ('0 90 0');
			$hp_01.move (UP, 350);
			sys.wait (1.5);
			
			$hp_02_anchor.rotateOnce ('0 90 0');
			$hp_02.move (UP, 350);
			sys.wait (1.5);
					
			$hp_03_anchor.rotateOnce ('0 90 0');
			$hp_03.move (UP, 350);
			sys.wait (1.5);
		}
	}


	void fixed_maindoor() {
		$fixed_panel.show();
		$broken_panel.hide();
	}

	void sparks_cpubank_01() {
		while (1) {
			sys.trigger ($cpubank_01_sparks);
			sys.wait ( sys.random (4) + 1);
		}
	}

	void sparks_cpubank_02() {
		while (1) {
			sys.trigger ($cpubank_02_sparks);
			sys.wait ( sys.random (3) + 1);
		}
	}

	void move_cpubank_01() {
		$cpubank_01.speed (64);
		thread ( sparks_cpubank_01() );
		$cpubank_01.moveTo ($cpubank_01_target);
	}

	void move_cpubank_02() {
		$cpubank_02.speed (64);
		thread ( sparks_cpubank_02() );
		$cpubank_02.moveTo ($cpubank_02_target);
	}

	void cpu_secret_01() {
		sys.trigger ($cpu_secret_01_speaker);
		sys.print ("You have found a secret area !\n");
	}

	void drop_object(string entityname) {
		entity	ent, ent_anchor;
		vector	vec;
		
		ent = sys.getEntity (entityname);
		
		ent.time (4);
		ent.accelTime (2);
		
		ent_anchor = sys.getEntity (entityname + "_anchor");
		
		//vec = getRandomVector (30, 45, 45);
		vec = getRandomVector (10, 10, 10);
		
		ent_anchor.rotate (vec);
		ent.move (DOWN, 356);
		
		sys.waitFor (ent);
		
		ent.remove();
		ent_anchor.remove();
	}

	void raise_object(string entityname) {
		entity	ent, ent_anchor;
		vector	vec;
		
		ent = sys.getEntity (entityname);
		
		ent.time (4);
		ent.accelTime (2);
		
		ent_anchor = sys.getEntity (entityname + "_anchor");
		
		;vec = getRandomVector (30, 45, 45);
		vec = getRandomVector (10, 10, 10);
		
		ent_anchor.rotate (vec);
		ent.move (UP, 356);
		
		sys.waitFor (ent);
		
		ent.remove();
		ent_anchor.remove();
	}

	void dropscene1() {
		float	i;
		entity	ent;
		
		for (i = 1; i<=2; i++) {
			thread drop_object ("hpp_" + i);
			sys.wait (0.3);
		}

		$hp_3_anchor.time (4);
		$hp_5_anchor.time (4);
		$hp_8_anchor.time (4);
		

		for (i = 1; i<=12; i++) {
			if (i == 3) {
				//$hp_3_anchor.moveTo ($hp3_dest);
				$hp_3.bob (4, 0.2, '0 0 2');
			}
			else if (i == 5) {
				//$hp_5_anchor.moveTo ($hp5_dest);
				$hp_5.bob (4, 0.6, '0 0 4');
			}
			else if (i == 8) {
				//$hp_8_anchor.moveTo ($hp8_dest);
				$hp_8.bob (4, 0.8, '0 0 3');
			}
			else {
				thread drop_object ("hp_" + i);
			}
			sys.wait (0.3);
		}
		$hp_3_anchor.moveTo ($hp3_dest);
		$hp_5_anchor.moveTo ($hp5_dest);
		$hp_8_anchor.moveTo ($hp8_dest);
	}

	void dropscene2() {
		float	i;
		entity	ent;
		
		for (i = 1; i<=10; i++) {
			thread raise_object ("hpc_" + i);
			sys.wait (0.3);
		}
	}

	void dropscene3() {
		float	i;
		entity	ent;
	
		for (i = 1; i<=3; i++) {
			thread drop_object ("hp_wall_" + i);
			sys.wait (0.3);
		}
	}

	void battle_sounds() {
		sys.wait (2);
		sys.trigger ($speaker_cherubs);
		sys.wait (45);
		sys.trigger ($speaker_imps);
	}

	void dropscene() {
		sys.trigger ($speaker_hallway_fall);
		
		sys.trigger ($speaker_inf_01);			// Shut some stuff off
		sys.trigger ($speaker_inf_02);
		sys.trigger ($speaker_inf_03);
		
		thread dropscene1();
		thread dropscene2();
		thread dropscene3();
		sys.wait (7);

		sys.trigger ($speaker_inf_01);			// Turn it back on
		sys.trigger ($speaker_inf_02);
		sys.trigger ($speaker_inf_03);



		//$hpillar_01_anchor.rotateOnce ('0 90 0');
		//$hpillar_01.move (UP, 400);
		//sys.wait (1.5);
		
		//$hpillar_02_anchor.rotateOnce ('0 -90 0');
		//$hpillar_02.move (UP, 400);
	}
	
	void main() {
		init_world();
	}
}

//@doomscript-blueprint begin 6
//@source 000B994F
//@catalog 0C260740
//@node 8846F578-0 40 40
//@node 8FE08B47-0 330 40
//@node 5D199BD8-0 40 40
//@node 7A0CC24A-0 330 40
//@node 376E42CE-0 125 145
//@node D2D53C06-0 -80 145
//@node CE17F19C-0 610 200
//@node 88913D14-0 405 305
//@node C418FE76-0 890 200
//@node BDE29217-0 1170 200
//@node C900D078-0 1450 200
//@node A367441E-0 40 40
//@node 0A80538C-0 330 40
//@node 43A106E3-0 610 40
//@node 6F62C57B-0 890 40
//@node DA72F69A-0 1170 40
//@node DBD77D0E-0 1450 40
//@node EDFFF82A-0 1730 40
//@node 5157D8ED-0 2010 40
//@node 9B53CEDF-0 40 40
//@node F1B6C1F8-0 330 40
//@node 46B58CD1-0 105 145
//@node C9984A5C-0 -100 245
//@node 62182926-0 610 40
//@node D524EFAA-0 385 145
//@node 52560990-0 180 245
//@node 997FA850-0 890 40
//@node DA558069-0 665 145
//@node 437E6C9F-0 460 245
//@node BF82CC72-0 1170 40
//@node C9BE39D2-0 40 40
//@node DD96AD24-0 330 40
//@node 1C179C4A-0 610 40
//@node 3E2A2AA5-0 890 40
//@node 3E661621-0 1170 40
//@node 261C8EA7-0 1450 40
//@node 8E908DF1-0 1730 40
//@node CE92BDA5-0 2010 40
//@node 8152D704-0 2290 40
//@node 8E908DF1-1 2570 40
//@node 8771A220-0 2850 40
//@node 372382E2-0 3130 40
//@node 9DD63EB8-0 3410 40
//@node 6D99A819-0 40 40
//@node A968095C-0 330 40
//@node E958C723-0 610 40
//@node FCB6D58F-0 890 40
//@node 4C75E82D-0 1170 40
//@node 17113164-0 1450 40
//@node F7729BE7-0 1730 40
//@node 180A974E-0 2010 40
//@node 5A21B839-0 2290 40
//@node DA07824A-0 2570 40
//@node 505DD799-0 40 40
//@node 9E5E1947-0 330 40
//@node 7599D90F-0 125 145
//@node 91D7B6F2-0 -80 145
//@node 538D3405-0 610 200
//@node 6802A0B2-0 405 305
//@node 72AF95BE-0 890 200
//@node 6E669BB5-0 1170 200
//@node C5042D4D-0 1450 200
//@node 6ACF962F-0 1730 200
//@node D0F5157C-0 2010 200
//@node C5042D4D-1 2290 200
//@node 083F6A8C-0 2570 200
//@node 139E933F-0 2850 200
//@node C5042D4D-2 3130 200
//@node F68F7D73-0 40 40
//@node 8B26D525-0 330 40
//@node BB9395FF-0 610 40
//@node C6F4BC2A-0 40 40
//@node 08361139-0 330 40
//@node FF46EF1E-0 125 145
//@node 5372830A-0 610 200
//@node 8113F8BB-0 890 200
//@node C5F4BA97-0 40 40
//@node 2BE6EE78-0 330 40
//@node C51FAA64-0 125 145
//@node 2D4D49B4-0 610 200
//@node 28A1D2D9-0 890 200
//@node 5BC55B73-0 40 40
//@node 85843F90-0 330 40
//@node 373CE4A3-0 610 40
//@node 3EB18D79-0 890 40
//@node 5CC55D06-0 40 40
//@node 41B9A860-0 330 40
//@node 30B0DAA9-0 610 40
//@node 49FCE4FE-0 890 40
//@node D3486444-0 40 40
//@node 8249EFD8-0 330 40
//@node B14FDA22-0 610 40
//@node 40D47E6E-0 40 40
//@node 70B53F13-0 330 40
//@node 1DDCEFA0-0 105 145
//@node A3668708-0 890 40
//@node 9EC6BCB0-0 1170 40
//@node 586D6066-0 1170 40
//@node B340F5BE-0 945 145
//@node BFD5E963-0 740 245
//@node 047D0045-0 1450 40
//@node 2C943D90-0 1225 145
//@node 4B97F842-0 2010 40
//@node 1BF8E3F4-0 1525 140
//@node B8F0568E-0 2290 40
//@node 2C3CD920-0 2570 40
//@node 9373E955-0 2085 140
//@node 5B1538FB-0 2850 40
//@node F959C7D1-0 3130 40
//@node 30A26F1B-0 40 40
//@node CFA14FB4-0 330 40
//@node 9C4E35FD-0 105 145
//@node 63470499-0 890 40
//@node F4917007-0 1170 40
//@node 6662FAA3-0 1170 40
//@node E8076107-0 945 145
//@node 086317D7-0 740 245
//@node 11FA48D2-0 1730 40
//@node 51E59FCE-0 1730 40
//@node 792F581E-0 1505 145
//@node 7F3BB511-0 2290 40
//@node 4A64E450-0 1805 140
//@node 67B9BFB4-0 2570 40
//@node 57EC8BFF-0 2850 40
//@node FE3FD546-0 2365 140
//@node F8608DBA-0 3130 40
//@node 185D6C06-0 3410 40
//@node 4CA4D227-0 40 40
//@node 9EE82C89-0 330 40
//@node 3710A5E7-0 125 145
//@node 44BD27F7-0 -80 145
//@node E6BD21F3-0 610 200
//@node 0FB9AF0A-0 890 200
//@node CA1942B0-0 1170 40
//@node F386C69A-0 1450 40
//@node B6E8811B-0 1730 40
//@node 80712398-0 2010 40
//@node 4E46D20F-0 1805 145
//@node 0FEBDE7A-0 1600 145
//@node 930C7889-0 2290 200
//@node E238C2D5-0 2085 305
//@node 5F493945-0 1880 305
//@node 1FBE9E04-0 2570 360
//@node F00682A0-0 2850 200
//@node EFABAAF5-0 2645 305
//@node 282582A7-0 2440 305
//@node 464544D8-0 3130 360
//@node 9421C849-0 3410 200
//@node 545FA6F3-0 3205 305
//@node 4D6E869C-0 3000 305
//@node 7A24FCE0-0 3690 360
//@node 0EC2D9D3-0 4250 360
//@node 0FB9AF0A-1 4530 200
//@node EEAE0785-0 4810 40
//@node 541FCCA5-0 5090 40
//@node C734068D-0 5370 40
//@node 4DA4D3BA-0 40 40
//@node 02C107E3-0 330 40
//@node 1009CF7F-0 125 145
//@node E677D2A4-0 -80 145
//@node 96F0A452-0 610 200
//@node 7F42B7BF-0 890 200
//@node 4EA4D54D-0 40 40
//@node D34C526C-0 330 40
//@node 570A6805-0 125 145
//@node 7756E92A-0 -80 145
//@node 21FD7BB8-0 610 200
//@node A7296FB0-0 890 200
//@node 86FD2BF4-0 40 40
//@node 69C933E0-0 330 40
//@node 0DFAEEEF-0 610 40
//@node E24C5DBD-0 890 40
//@node 9D77A062-0 1170 40
//@node 526199AC-0 40 40
//@node 10E9ADC7-0 330 40
//@node E25E2CCA-0 610 40
//@node 7572B3E7-0 890 40
//@node 012F8C88-0 1170 40
//@node 77AC63D0-0 1450 40
//@node FBD0D7A7-0 1730 40
//@node A5B16F6E-0 2010 40
//@node 1E9F80A7-0 2290 40
//@node E25E2CCA-1 2570 40
//@node 7572B3E7-1 2850 40
//@node 012F8C88-1 3130 40
//@node 32687650-0 40 40
//@node 5531D4DD-0 330 40
//@doomscript-blueprint end
