/***********************************************************************

weapon_plasmagun.script

***********************************************************************/

#define PLASMAGUN_FIRERATE			0.125 //changed by Tim
#define PLASMAGUN_LOWAMMO			10
#define PLASMAGUN_NUMPROJECTILES	1

// blend times
#define PLASMAGUN_IDLE_TO_LOWER		4
#define PLASMAGUN_IDLE_TO_FIRE		1
#define	PLASMAGUN_IDLE_TO_RELOAD	4
#define PLASMAGUN_RAISE_TO_IDLE		4
#define PLASMAGUN_FIRE_TO_IDLE		4
#define PLASMAGUN_RELOAD_TO_IDLE	4

object weapon_plasmagun : weapon_base {
	float		next_attack;
	float		spread;
	
	void		init();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		Reload();
	void		ExitCinematic();
};

void weapon_plasmagun::init() {
	next_attack = 0;
	spread		= getFloatKey( "spread" );
	weaponState( "Raise", 0 );
}

void weapon_plasmagun::Raise() {
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	waitUntil( animDone( ANIMCHANNEL_ALL, PLASMAGUN_RAISE_TO_IDLE ) );
	weaponState( "Idle", PLASMAGUN_RAISE_TO_IDLE );
}

void weapon_plasmagun::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_plasmagun::Idle() {
	float currentTime;
	float ammoClip;
	float avail;
	float clip_size;

	clip_size = clipSize();	
	
	if ( !ammoInClip() ) {
		weaponOutOfAmmo();
	} else {
		weaponReady();
	}
	playCycle( ANIMCHANNEL_ALL, "idle" );
	while( 1 ) {
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", PLASMAGUN_IDLE_TO_LOWER );
		}
		currentTime = sys.getTime();
		ammoClip = ammoInClip();
		if ( ( currentTime >= next_attack ) && WEAPON_ATTACK ) {
			if ( ammoClip > 0 ) {
				weaponState( "Fire", PLASMAGUN_IDLE_TO_FIRE );
			} else if ( ammoAvailable() > 0 ) {
				if ( autoReload() ) {
					netReload();
					weaponState( "Reload", PLASMAGUN_IDLE_TO_RELOAD );
				}
			}
		}
		if ( WEAPON_RELOAD && ( ammoAvailable() > ammoClip ) && ( ammoClip < clip_size ) ) {
			netReload();
			weaponState( "Reload", PLASMAGUN_IDLE_TO_RELOAD );
		}
		if ( WEAPON_NETRELOAD ) {
			WEAPON_NETRELOAD = false;
			weaponState( "Reload", PLASMAGUN_IDLE_TO_RELOAD );			
		}
		waitFrame();
	}
}

void weapon_plasmagun::Fire() {
	float ammoClip;
	float currentTime;
	
	next_attack = sys.getTime() + PLASMAGUN_FIRERATE;
	
	ammoClip = ammoInClip();
	if ( ammoClip == PLASMAGUN_LOWAMMO ) {
		startSound( "snd_lowammo", SND_CHANNEL_ITEM, true );
	}

	launchProjectiles( PLASMAGUN_NUMPROJECTILES, spread, 0, 1.0, 1.0 );
	playAnim( ANIMCHANNEL_ALL, "fire" );
	while( !animDone( ANIMCHANNEL_ALL, PLASMAGUN_FIRE_TO_IDLE ) ) {
		currentTime = sys.getTime();
		ammoClip = ammoInClip();
		if ( ( currentTime >= next_attack ) && WEAPON_ATTACK && ( ammoClip > 0 ) ) {
			weaponState( "Fire", 0 );
		}
		waitFrame();
	}

	weaponState( "Idle", PLASMAGUN_FIRE_TO_IDLE );
}

void weapon_plasmagun::Reload() {
	weaponReloading();
	playAnim( ANIMCHANNEL_ALL, "reload" );
	waitUntil( animDone( ANIMCHANNEL_ALL, PLASMAGUN_RELOAD_TO_IDLE ) );
	addToClip( clipSize() );
	weaponState( "Idle", PLASMAGUN_RELOAD_TO_IDLE );
}

void weapon_plasmagun::ExitCinematic() {
	next_attack = 0;
	weaponState( "Idle", 0 );
}

//@doomscript-blueprint begin 6
//@source D823B42F
//@catalog 0C260740
//@node 8BDB0D30-0 40 40
//@node 671362D9-0 330 40
//@node 366CC422-0 125 145
//@node 2C1BCEC1-0 610 40
//@node 0597EAB1-0 385 145
//@node B2070F5C-0 180 245
//@node E7ED8C9F-0 -25 245
//@node 0AAD97A5-0 890 40
//@node E14CACAE-0 40 40
//@node BFB492C6-0 330 40
//@node 9B546641-0 610 40
//@node 8FD41717-0 890 40
//@node 6521EF23-0 1170 40
//@node 0F0F93B7-0 40 40
//@node A26A8A00-0 330 40
//@node 2A5EB60B-0 610 40
//@node 3FB14B84-0 890 40
//@node 1EE24AC5-0 1170 40
//@node 54E32A8B-0 1450 40
//@node D87F1290-0 1245 140
//@node BAC5D988-0 1730 40
//@node 8B083CEC-0 40 40
//@node CA02F0A9-0 330 40
//@node 69622085-0 105 145
//@node 0E73BDF9-0 610 40
//@node D34DE7B9-0 170 145
//@node A3E59AE9-0 400 145
//@node 1436D0BB-0 890 200
//@node B0837ADF-0 1450 200
//@node 5D934BF4-0 1730 40
//@node 674D04BF-0 2010 40
//@node 2518D012-0 1805 145
//@node D13428EA-0 2290 200
//@node 13B66810-0 2085 305
//@node C71A31DF-0 2570 360
//@node C5090800-0 2850 200
//@node 6D446092-0 2625 305
//@node CF584F59-0 3130 200
//@node B6C4AAFF-0 2905 305
//@node ECB1F80B-0 3410 200
//@node FAE1D77D-0 3205 305
//@node 1185A2C3-0 3000 305
//@node 21F47905-0 3000 389
//@node CD7DD5AE-0 3000 389
//@node 2E4AD6BE-0 3690 360
//@node FC73F796-0 3485 465
//@node 8032E35D-0 3280 465
//@node 41D78ECB-0 3970 520
//@node 8145CADD-0 4250 520
//@node 09F9D4E9-0 4045 625
//@node 28E1C6BD-0 4530 520
//@node 2542FA27-0 4305 625
//@node 246B7D3C-0 4810 680
//@node D95B8C7D-0 5090 680
//@node 01376D54-0 5370 200
//@node 6BC77455-0 5165 305
//@node 22FAED08-0 4960 305
//@node 1988392A-0 4960 389
//@node 53121DC8-0 4960 473
//@node 246B7D3C-1 5650 360
//@node D95B8C7D-1 5930 360
//@node D9CD45D1-0 6210 200
//@node 5273D507-0 6005 305
//@node B5F2FF2B-0 6490 360
//@node DC8EDF3C-0 6285 465
//@node D95B8C7D-2 6770 360
//@node C905DFCC-0 7050 200
//@node F8D494BE-0 40 40
//@node C28538FA-0 330 40
//@node 60824E66-0 125 145
//@node C37776D3-0 610 40
//@node 55D29AE5-0 385 145
//@node BB883851-0 890 40
//@node 20876B13-0 730 156
//@node 7C3B7CE7-0 412 295
//@node E5B75B9E-0 1170 200
//@node FEFD6C59-0 1450 40
//@node 429E4D1A-0 1245 232
//@node 9717B8DB-0 1730 40
//@node 7287037E-0 1525 232
//@node FF46DE23-0 1320 232
//@node E0EDF053-0 2010 40
//@node 80564441-0 1570 145
//@node 7108F8B1-0 1800 145
//@node 6E6DF606-0 2290 200
//@node 9C550A96-0 2065 305
//@node C37776D3-1 2570 200
//@node 728C632C-0 2345 305
//@node B67E8590-0 2850 200
//@node 751AA251-0 2645 305
//@node 7E4F6242-0 2440 305
//@node E858077A-0 2440 389
//@node AF938E9C-0 2440 473
//@node 5E22448F-0 2440 473
//@node B35F34F1-0 3130 360
//@node 779790BA-0 3410 200
//@node D896D387-0 3690 40
//@node F12809FF-0 40 40
//@node C4850306-0 330 40
//@node D82D3541-0 610 40
//@node 1C8FCA93-0 890 40
//@node F94A81FB-0 1170 40
//@node FEA9E12F-0 1450 40
//@node DF863107-0 40 40
//@node 677DBA0A-0 330 40
//@node 13F1EF33-0 125 145
//@node C83A5E32-0 610 40
//@doomscript-blueprint end
