/***********************************************************************

weapon_rocketlauncher.script

***********************************************************************/

#define ROCKETLAUNCHER_LOWAMMO			1
#define ROCKETLAUNCHER_NUMPROJECTILES	1
#define ROCKETLAUNCHER_FIREDELAY		1		// was .75 changed again by Tim to 1

// blend times
#define ROCKETLAUNCHER_IDLE_TO_LOWER	4
#define ROCKETLAUNCHER_IDLE_TO_FIRE		0
#define	ROCKETLAUNCHER_IDLE_TO_RELOAD	4
#define ROCKETLAUNCHER_RAISE_TO_IDLE	4
#define ROCKETLAUNCHER_FIRE_TO_IDLE		0
#define ROCKETLAUNCHER_RELOAD_TO_IDLE	4
#define ROCKETLAUNCHER_RELOAD_FRAME		34		// how many frames from the end of "reload" to fill the clip

object weapon_rocketlauncher : weapon_base {
	float		next_attack;
	float		spread;
	
	string		skin_invisible;
	
	void		init();
	void		UpdateSkin();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		Reload();
	void		ExitCinematic();
};

void weapon_rocketlauncher::init() {
	next_attack		= 0;
	spread			= getFloatKey( "spread" );
	skin_invisible	= getKey( "skin_invisible" );
	weaponState( "Raise", 0 );
}

void weapon_rocketlauncher::UpdateSkin() {
	string skinname;
	float ammoClip;

	if ( isInvisible() ) {
		skinname = skin_invisible;
	} else {	
		ammoClip = ammoInClip();
		if ( ammoClip > 5 ) {
			// can happen in MP - weapon Raising with slightly out-of-sync ammoClip
			ammoClip = 5;
		}
		if ( ammoClip < 0 ) {
			ammoClip = 0;
		}
		skinname = "skins/models/weapons/" + ammoClip + "rox.skin";
	}
	setSkin( skinname );
}

void weapon_rocketlauncher::Raise() {
	UpdateSkin();
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	waitUntil( animDone( ANIMCHANNEL_ALL, ROCKETLAUNCHER_RAISE_TO_IDLE ) );
	weaponState( "Idle", ROCKETLAUNCHER_RAISE_TO_IDLE );
}

void weapon_rocketlauncher::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_rocketlauncher::Idle() {
	float ammoClip;
	float avail;
	float clip_size;
	float currentTime;
	
	clip_size = clipSize();	
	
	if ( !ammoInClip() ) {
		weaponOutOfAmmo();
	} else {
		weaponReady();
	}
	playCycle( ANIMCHANNEL_ALL, "idle" );
	while( 1 ) {
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", ROCKETLAUNCHER_IDLE_TO_LOWER );
		}
		ammoClip = ammoInClip();
		currentTime = sys.getTime();
		if ( ( currentTime >= next_attack ) && WEAPON_ATTACK ) {
			if ( ammoClip > 0 ) {
				weaponState( "Fire", ROCKETLAUNCHER_IDLE_TO_FIRE );
			} else if ( ammoAvailable() > 0 ) {
				if ( autoReload() ) {
					netReload();
					weaponState( "Reload", ROCKETLAUNCHER_IDLE_TO_RELOAD );
				}
			}
		}
		if ( WEAPON_RELOAD && ( ammoAvailable() > ammoClip ) && ( ammoClip < clip_size ) ) {
			netReload();
			weaponState( "Reload", ROCKETLAUNCHER_IDLE_TO_RELOAD );
		}
		if ( WEAPON_NETRELOAD ) {
			WEAPON_NETRELOAD = false;
			weaponState( "Reload", ROCKETLAUNCHER_IDLE_TO_RELOAD );		
		}
		waitFrame();
	}
}

void weapon_rocketlauncher::Fire() {
	float ammoClip;
	
	next_attack = sys.getTime() + ROCKETLAUNCHER_FIREDELAY;
	
	ammoClip = ammoInClip();
	if ( ammoClip == ROCKETLAUNCHER_LOWAMMO ) {
		startSound( "snd_lowammo", SND_CHANNEL_ITEM, true );
	}
	
	launchProjectiles( ROCKETLAUNCHER_NUMPROJECTILES, spread, 0, 1.0, 1.0 );
	playAnim( ANIMCHANNEL_ALL, "fire" );
	waitUntil( animDone( ANIMCHANNEL_ALL, ROCKETLAUNCHER_FIRE_TO_IDLE ) );
	UpdateSkin();
	weaponState( "Idle", ROCKETLAUNCHER_FIRE_TO_IDLE );
}

void weapon_rocketlauncher::Reload() {
	weaponReloading();
	playAnim( ANIMCHANNEL_ALL, "reload" );
	waitUntil( animDone( ANIMCHANNEL_ALL, ROCKETLAUNCHER_RELOAD_FRAME ) );
	addToClip( clipSize() );
	UpdateSkin();
	waitUntil( animDone( ANIMCHANNEL_ALL, ROCKETLAUNCHER_RELOAD_TO_IDLE ) );
	weaponState( "Idle", ROCKETLAUNCHER_RELOAD_TO_IDLE );
}

void weapon_rocketlauncher::ExitCinematic() {
	next_attack = 0;
	UpdateSkin();
	weaponState( "Idle", 0 );
}

//@doomscript-blueprint begin 6
//@source 580FA890
//@catalog 0C260740
//@node 63E4BF30-0 40 40
//@node 0CC01DF3-0 330 40
//@node 903655C4-0 125 145
//@node FA6E05EF-0 610 40
//@node 75BB1DD7-0 385 145
//@node 0A00B430-0 180 245
//@node F14E3641-0 -25 245
//@node 5316BE6F-0 890 40
//@node 77C8D4D7-0 665 145
//@node 8EBF0F3E-0 460 245
//@node F572FCF7-0 255 245
//@node 8C5EC381-0 1170 40
//@node 409EE6D2-0 40 40
//@node 10EF0300-0 330 40
//@node FD19166C-0 105 145
//@node A6B91A98-0 610 200
//@node A83EDD48-0 405 305
//@node FF71EC31-0 1170 200
//@node D4AD6AA3-0 945 305
//@node D427B363-0 1450 200
//@node FEDC48DD-0 1245 305
//@node 91EE7233-0 1040 305
//@node DB036168-0 1730 360
//@node 8780D709-0 1525 465
//@node 8D210B4A-0 2010 200
//@node 0AAAF74D-0 1805 305
//@node 348FBC76-0 1600 305
//@node E30A29C5-0 2290 360
//@node C15BD3C4-0 2085 465
//@node 4E543695-0 2570 200
//@node 9100D614-0 2365 305
//@node 7908E235-0 2160 305
//@node AE53D581-0 2850 40
//@node 96690124-0 2645 140
//@node F88FE2AE-0 40 40
//@node 1C084FDC-0 330 40
//@node 1A2DF0F2-0 610 40
//@node 1C5744CD-0 890 40
//@node 03691763-0 1170 40
//@node 6BA7BD51-0 1450 40
//@node 2652C9B7-0 40 40
//@node C94AB004-0 330 40
//@node 625036FF-0 610 40
//@node 73B926B0-0 890 40
//@node F5EBAF71-0 1170 40
//@node BD9466E7-0 1450 40
//@node 012EC0D9-0 1245 140
//@node 628E353C-0 1730 40
//@node 6311EEEC-0 40 40
//@node 441D13F7-0 330 40
//@node C1DD11B7-0 105 145
//@node 9511A52D-0 610 40
//@node 69F2C365-0 170 145
//@node 54188DD5-0 400 145
//@node AEF1E227-0 890 200
//@node 132E60EB-0 1450 200
//@node 83FDD748-0 1730 40
//@node 2399732F-0 2010 40
//@node 37D5BBC8-0 1805 145
//@node 0B4F4566-0 2290 200
//@node 3A7277D7-0 2085 305
//@node 029E6F43-0 2570 360
//@node 0D2873B3-0 2850 200
//@node 11EAAFB8-0 2625 305
//@node C164A3A6-0 3130 200
//@node 0C288882-0 2905 305
//@node 0742D7B7-0 3410 200
//@node 8C6044B1-0 3205 305
//@node 27591FAD-0 3000 305
//@node B6E44130-0 3000 389
//@node 09F85C37-0 3000 389
//@node F03BD94A-0 3690 360
//@node 3CB0B920-0 3485 465
//@node C8337CC9-0 3280 465
//@node B9F39405-0 3970 520
//@node C57A3699-0 4250 520
//@node EA26C856-0 4045 625
//@node B3ABA929-0 4530 520
//@node BCDC76A1-0 4305 625
//@node 41ABCD20-0 4810 680
//@node 79DFCC7D-0 5090 680
//@node 8200F908-0 5370 200
//@node 9B7F3EEC-0 5165 305
//@node 5FDD1109-0 4960 305
//@node 397DCC45-0 4960 389
//@node 852C8D7F-0 4960 473
//@node 41ABCD20-1 5650 360
//@node 79DFCC7D-1 5930 360
//@node 91D9BD15-0 6210 200
//@node 12CC237E-0 6005 305
//@node 816A5F11-0 6490 360
//@node 0BD6F830-0 6285 465
//@node 79DFCC7D-2 6770 360
//@node FC9A0250-0 7050 200
//@node D0DE46BE-0 40 40
//@node 595A9025-0 330 40
//@node 83FE18F5-0 125 145
//@node D935895D-0 610 40
//@node 4D074B6C-0 385 145
//@node 69F8EC97-0 890 40
//@node 7B744F05-0 685 145
//@node 60BEFA6F-0 480 145
//@node 882350CA-0 1170 200
//@node 81F6F2D7-0 1450 40
//@node FFE25BA0-0 1245 232
//@node 4DB95F17-0 1730 40
//@node DA025378-0 1525 232
//@node 145339BF-0 1320 232
//@node 25A10055-0 2010 40
//@node FA92C300-0 2290 40
//@node 06B20621-0 2570 40
//@node 8FF60BFF-0 40 40
//@node 492422DA-0 330 40
//@node D66F224D-0 610 40
//@node DD665D8E-0 890 40
//@node 8A81DBF7-0 1170 40
//@node A8244019-0 1450 40
//@node 0FDFC8E1-0 1730 40
//@node 8194E9B3-0 2010 40
//@node 463A2707-0 40 40
//@node F9EA4758-0 330 40
//@node 51DCC7A4-0 125 145
//@node 73411731-0 610 40
//@node 096325DE-0 890 40
//@doomscript-blueprint end
