/***********************************************************************

weapon_flashlight.script

***********************************************************************/

// blend times
#define FLASHLIGHT_IDLE_TO_LOWER	4
#define FLASHLIGHT_IDLE_TO_FIRE		2
#define	FLASHLIGHT_IDLE_TO_RELOAD	4
#define FLASHLIGHT_RAISE_TO_IDLE	4
#define FLASHLIGHT_FIRE_TO_IDLE		4
#define FLASHLIGHT_RELOAD_TO_IDLE	4

#define	FLASHLIGHT_MIN_SKIN_INTENSITY	0.2

// for dimming flashlight during plasma discharges in alphalabs2
float global_flashlight_intensity = 1.0;

object weapon_flashlight : weapon_base {
	boolean		on;
	float		intensity;
	string		skin_on;
	string		skin_on_invis;
	string		skin_off;
	string		skin_off_invis;
	
	void		init();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		ToggleOnOff();
	void		EnterCinematic();
	void		ExitCinematic();

	void		updateLightIntensity();

				// called by the game
	void		UpdateSkin();
};

void weapon_flashlight::init() {

	skin_on			= getKey( "skin_on" );
	skin_on_invis	= getKey( "skin_on_invis" );
	skin_off		= getKey( "skin_off" );
	skin_off_invis	= getKey( "skin_off_invis" );
	
	global_flashlight_intensity = 1.0;
	intensity = 1.0;
	setLightParm( 3, 1.0 );
	setShaderParm( 3, 1.0 );
	
	on = true;
	UpdateSkin();
	
	weaponState( "Raise", 0 );
}

void weapon_flashlight::updateLightIntensity() {
	if ( global_flashlight_intensity != intensity ) {
		intensity = global_flashlight_intensity;
		setLightParm( 3, intensity );
		setShaderParm( 3, intensity );
		UpdateSkin();
	}
}

void weapon_flashlight::Raise() {
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	flashlight( true );
	while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_RAISE_TO_IDLE ) ) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Idle", FLASHLIGHT_RAISE_TO_IDLE );
}

void weapon_flashlight::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	while( !WEAPON_RAISEWEAPON ) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Raise", 0 );
}

void weapon_flashlight::Idle() {
	weaponReady();
	playCycle( ANIMCHANNEL_ALL, "idle" );
	while( 1 ) {
		updateLightIntensity();
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", FLASHLIGHT_IDLE_TO_LOWER );
		}
		if ( WEAPON_ATTACK ) {
			weaponState( "Fire", FLASHLIGHT_IDLE_TO_FIRE );
		}
		if ( WEAPON_RELOAD ) {
			if ( sys.isMultiplayer() ) {
				weaponState( "ToggleOnOff", FLASHLIGHT_IDLE_TO_RELOAD );
			}
		}
		waitFrame();
	}
}

void weapon_flashlight::Fire() {
	float waitTime;

	playAnim( ANIMCHANNEL_ALL, "fire" );
	waitTime = sys.getTime() + 0.1;
	while( sys.getTime() < waitTime ) {
		updateLightIntensity();
		waitFrame();
	}
	melee();
	while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_FIRE_TO_IDLE ) ) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Idle", FLASHLIGHT_FIRE_TO_IDLE );
}

void weapon_flashlight::ToggleOnOff() {
	float waitTime;

	playAnim( ANIMCHANNEL_ALL, "reload" );
	waitTime = sys.getTime() + 0.2;
	while( sys.getTime() < waitTime ) {
		updateLightIntensity();
		waitFrame();
	}

	on = !on;
	UpdateSkin();
	flashlight( on );
	
	while( !animDone( ANIMCHANNEL_ALL, FLASHLIGHT_RELOAD_TO_IDLE ) ) {
		updateLightIntensity();
		waitFrame();
	}
	weaponState( "Idle", FLASHLIGHT_RELOAD_TO_IDLE );
}

void weapon_flashlight::EnterCinematic() {
	flashlight( false );
	weaponState( "Idle", 0 );
}

void weapon_flashlight::ExitCinematic() {
	flashlight( on );
	intensity = 1.0;
	updateLightIntensity();
	weaponState( "Idle", 0 );
}

void weapon_flashlight::UpdateSkin() {
	if ( on && ( intensity > FLASHLIGHT_MIN_SKIN_INTENSITY ) ) {
		if ( !isInvisible() ) {
			setSkin( skin_on );
		} else {
			setSkin( skin_on_invis );
		}
	} else {
		if ( !isInvisible() ) {
			setSkin( skin_off );
		} else {
			setSkin( skin_off_invis );
		}
	}
}

//@doomscript-blueprint begin 6
//@source C5B7EB1C
//@catalog 0C260740
//@node 2AA4B38A-0 40 40
//@node BD8DBCB7-0 330 40
//@node 1114B7E9-0 105 145
//@node 5834B336-0 -100 245
//@node CC823AB1-0 -305 245
//@node 8886F95F-0 610 40
//@node 530C5E87-0 385 145
//@node ADBF4B12-0 180 245
//@node A51DB979-0 -25 245
//@node CDA33ACD-0 890 40
//@node 1BE69303-0 665 145
//@node F34B8A51-0 460 245
//@node 3103F6F4-0 255 245
//@node B30CD5AD-0 1170 40
//@node E0131117-0 945 145
//@node F75B18AB-0 740 245
//@node 0554A9E2-0 535 245
//@node C2298454-0 1450 40
//@node C090CCDA-0 1245 145
//@node EFD26B63-0 1730 40
//@node CD62A121-0 1525 145
//@node 74B1CD9C-0 2010 40
//@node 96991273-0 2290 40
//@node CD27BDD0-0 2570 40
//@node E46766B0-0 2365 145
//@node 82E73D98-0 2850 40
//@node 85CD674B-0 3130 40
//@node 4191E000-0 40 40
//@node 0AFBADF7-0 330 40
//@node 092A54CB-0 125 145
//@node 3D7DB4C9-0 -80 145
//@node E3F5AD4C-0 -80 229
//@node A03D79A6-0 610 200
//@node 3C17DE51-0 405 305
//@node 79507CA6-0 890 200
//@node 3FBF8490-0 685 392
//@node 421A54A9-0 1170 200
//@node 46D711F3-0 965 392
//@node 1CACFAE2-0 1450 200
//@node 56CAB278-0 40 40
//@node 09F748AC-0 330 40
//@node 20C99563-0 610 40
//@node 8F06DCB0-0 890 40
//@node E48449F9-0 1170 40
//@node 1E478B44-0 730 145
//@node 062FF474-0 960 145
//@node AEE55B06-0 1450 200
//@node 55C46ED0-0 1730 200
//@node 498EAC09-0 2010 40
//@node 97977BED-0 40 40
//@node F054BEF6-0 330 40
//@node 156DEC7D-0 610 40
//@node 8FEE0AD6-0 890 40
//@node C715DD0F-0 1170 40
//@node C88B610F-0 1450 40
//@node BB6CFC3C-0 1245 145
//@node B882DC1E-0 1040 145
//@node 986E640B-0 1730 200
//@node 050A9AB7-0 2010 200
//@node 6A61D17A-0 2290 40
//@node 0DC4084A-0 40 40
//@node DA61E991-0 330 40
//@node 1BCFCA96-0 610 40
//@node B7C9A175-0 890 40
//@node 5795003C-0 685 145
//@node D11D0E78-0 1170 200
//@node 724E6CE0-0 1450 200
//@node D49A2B0C-0 1245 305
//@node E4127143-0 1730 360
//@node 9A7C8475-0 2010 200
//@node 1497F75B-0 1805 305
//@node 13AFC9C1-0 2290 360
//@node 2F8FE3D0-0 2570 200
//@node 0544CB78-0 2365 305
//@node 08D0B1A4-0 2850 360
//@node 48CB6A18-0 2625 465
//@node A726D61A-0 3130 520
//@node F8C2BFB2-0 3410 200
//@node FB25DC2C-0 40 40
//@node 10F2A3CD-0 330 40
//@node 9884EDA2-0 125 232
//@node CE0C9781-0 -80 232
//@node 8E4D26DC-0 610 40
//@node 54CA0A72-0 405 145
//@node 2FA37B39-0 890 40
//@node 98A3C4D7-0 685 145
//@node 5815BA2B-0 480 145
//@node 822FB1E6-0 1170 200
//@node 52218770-0 1450 200
//@node E24F4B76-0 1730 40
//@node B7772E6D-0 2010 40
//@node 3F1BFD1D-0 1570 145
//@node 2CE24AAD-0 1800 145
//@node 822FB1E6-1 2290 200
//@node 52218770-1 2570 200
//@node 094682CD-0 2850 40
//@node 21016412-0 40 40
//@node 7F0F6292-0 330 40
//@node 16BF943B-0 610 40
//@node 1AAD5C5C-0 405 145
//@node 711842A7-0 890 40
//@node 7AE25A17-0 685 145
//@node E2B124D1-0 480 145
//@node 7BEFBFDC-0 1170 200
//@node DAE8F626-0 1450 200
//@node 89779026-0 1730 40
//@node 117843D1-0 1525 145
//@node 4223BD45-0 1320 145
//@node 971EAC90-0 2010 40
//@node 72557149-0 2290 40
//@node 8A90D447-0 2085 140
//@node EC0F3E0A-0 2570 40
//@node 8B4147D0-0 2130 145
//@node 19D81640-0 2360 145
//@node 7BEFBFDC-1 2850 200
//@node DAE8F626-1 3130 200
//@node 0BBC4954-0 3410 40
//@node 145156AB-0 40 40
//@node 20D397CC-0 330 40
//@node EED6E836-0 610 40
//@node 15C0937D-0 40 40
//@node 595BF23A-0 330 40
//@node 7D970607-0 125 140
//@node 068D9148-0 610 40
//@node 3D168264-0 405 145
//@node E5813EBB-0 890 40
//@node 5EF2C628-0 1170 40
//@node 403DAF34-0 40 40
//@node DBBC5E14-0 330 40
//@node ABC5C7C9-0 125 145
//@node DE1E2DAF-0 -80 145
//@node 9E02FD87-0 -80 229
//@node A97D5779-0 610 200
//@node FAA41C68-0 170 305
//@node 92A30AF8-0 400 305
//@node 72C27946-0 890 360
//@node 1CE15E8B-0 685 460
//@node 905678DE-0 1450 360
//@node DD8993DF-0 1245 460
//@node A97D5779-1 2010 200
//@node 2B2C3D37-0 1570 305
//@node 3E2256C7-0 1800 305
//@node 157F0800-0 2290 360
//@node 7FF89090-0 2085 460
//@node 2D236A88-0 2850 360
//@node 28661169-0 2645 460
//@doomscript-blueprint end
