/***********************************************************************

weapon_handgrenade.script

***********************************************************************/

#define HANDGRENADE_MINRELEASETIME		0.05
#define HANDGRENADE_FUSE				3
#define HANDGRENADE_QUICKTHROWTIME		.2
#define HANDGRENADE_MINPOWER			1.5
#define HANDGRENADE_MAXPOWER			6
#define HANDGRENADE_QUICKTHROWLAUNCH	0.55
#define HANDGRENADE_NORMALTHROWLAUNCH	0.3
#define HANDGRENADE_NUMPROJECTILES		1

// blend times
#define HANDGRENADE_IDLE_TO_LOWER		4
#define HANDGRENADE_IDLE_TO_FIRE		4
#define HANDGRENADE_RAISE_TO_IDLE		4
#define HANDGRENADE_FIRE_TO_IDLE		4

object weapon_handgrenade : weapon_base {
	float		spread;
	float		fuse_start;
	string		skin_nade;
	string		skin_nade_invis;
	string		skin_nonade;
	string		skin_nonade_invis;
	entity		projectile;
	
	boolean		show_grenade;
	
	void		init();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		EnterCinematic();
	void		ExitCinematic();
	void		WeaponStolen();
	void		OwnerDied();
	void		ExplodeInHand();
	
				// called by the game
	void		UpdateSkin();
	
				// used by anim frame commands
	void		GrenadeNade();
	void		GrenadeNoNade();
};

void weapon_handgrenade::init() {
	spread				= getFloatKey( "spread" );
	skin_nade			= getKey( "skin_nade" );
	skin_nade_invis		= getKey( "skin_nade_invis" );
	skin_nonade			= getKey( "skin_nonade" );
	skin_nonade_invis	= getKey( "skin_nonade_invis" );
	
	GrenadeNade();
	
	weaponState( "Raise", 0 );
}

void weapon_handgrenade::Raise() {
	if ( !ammoAvailable() ) {
		weaponHolstered();
		nextWeapon();
		return;
	}
	
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	waitUntil( animDone( ANIMCHANNEL_ALL, HANDGRENADE_RAISE_TO_IDLE ) );
	weaponState( "Idle", HANDGRENADE_RAISE_TO_IDLE );
}

void weapon_handgrenade::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_handgrenade::Idle() {
	weaponReady();
	playCycle( ANIMCHANNEL_ALL, "idle" );
	while( 1 ) {
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", HANDGRENADE_IDLE_TO_LOWER );
		}
		if ( WEAPON_ATTACK ) {
			weaponState( "Fire", HANDGRENADE_IDLE_TO_FIRE );
		}
		waitFrame();
	}
}

void weapon_handgrenade::Fire() {
	float fuse_end;
	float current_time;
	float time_held;
	float power;
	boolean exploded;
	
	projectile = createProjectile();

	if ( projectile ) {
		projectile.startSound( "snd_throw", SND_CHANNEL_BODY, true );
	}
	
	playAnim( ANIMCHANNEL_ALL, "throw_start" );
	
	current_time = sys.getTime();
	fuse_start = current_time;
	fuse_end = current_time + HANDGRENADE_FUSE;
	while( current_time < fuse_end ) {
		if ( ( current_time > fuse_start + HANDGRENADE_MINRELEASETIME ) && !WEAPON_ATTACK ) {
			break;
		}
		waitFrame();
		current_time = sys.getTime();
	}
	
	time_held = current_time - fuse_start;
	power = time_held + HANDGRENADE_MINPOWER;
	if ( power > HANDGRENADE_MAXPOWER ) {
		power = HANDGRENADE_MAXPOWER;
	}

	if ( time_held < HANDGRENADE_QUICKTHROWTIME ) {
		playAnim( ANIMCHANNEL_ALL, "throw_quick" );
		sys.wait( HANDGRENADE_QUICKTHROWLAUNCH );
		exploded = false;
	} else if ( time_held < HANDGRENADE_FUSE ) {
		playAnim( ANIMCHANNEL_ALL, "throw" );
		sys.wait( HANDGRENADE_NORMALTHROWLAUNCH	);
		exploded = false;
	} else {
		// no anim.  grenade just blows up
		ExplodeInHand();
		exploded = true;
	}
	
	if ( !exploded ) {
		GrenadeNoNade();
		current_time = sys.getTime();
		if ( projectile ) {
			projectile.show();
			projectile.unbind();
			launchProjectiles( HANDGRENADE_NUMPROJECTILES, spread, current_time - fuse_start, power, 1.0 );
			projectile = $null_entity;
		}

		waitUntil( animDone( ANIMCHANNEL_ALL, HANDGRENADE_FIRE_TO_IDLE ) );
	}
	
	if ( !ammoAvailable() ) {
		weaponHolstered();
		nextWeapon();
	} else {
		GrenadeNade();
		weaponState( "Idle", HANDGRENADE_FIRE_TO_IDLE );
	}
}

void weapon_handgrenade::EnterCinematic() {
	if ( projectile ) {
		projectile.remove();
		projectile = $null_entity;		
	}
	weaponState( "Idle", 0 );
}

void weapon_handgrenade::ExitCinematic() {
	if ( !ammoAvailable() ) {
		weaponHolstered();
		nextWeapon();
	} else {
		GrenadeNade();
		weaponState( "Idle", 0 );
	}
}

void weapon_handgrenade::GrenadeNade() {
	show_grenade = true;
	UpdateSkin();
}

void weapon_handgrenade::GrenadeNoNade() {
	show_grenade = false;
	UpdateSkin();
}

void weapon_handgrenade::UpdateSkin() {
	if ( !show_grenade ) {
		if ( isInvisible() ) {
			setSkin( skin_nonade_invis );
		} else {
			setSkin( skin_nonade );
		}
	} else {
		if ( isInvisible() ) {
			setSkin( skin_nade_invis );
		} else {
			setSkin( skin_nade );
		}
	}
}

void weapon_handgrenade::WeaponStolen() {
	if ( projectile ) {
		projectile.remove();
		projectile = $null_entity;		
	}
}

void weapon_handgrenade::OwnerDied() {
	float time_held;

	if ( projectile ) {
		time_held = sys.getTime() - fuse_start;
		projectile.show();
		projectile.unbind();

		// allow grenade to drop
		launchProjectiles( HANDGRENADE_NUMPROJECTILES, spread, time_held, 0, 1.0 );

		projectile = $null_entity;
	}
}

void weapon_handgrenade::ExplodeInHand() {
	string	entname;
	entity	explosion;
	vector	forward;
	vector	angles;
	entity	owner;

	if ( projectile ) {
		projectile.remove();
		projectile = $null_entity;
	}

	owner = getOwner();

	GrenadeNoNade();
	startSound( "snd_explode", SND_CHANNEL_ANY, false );

	if ( !sys.isClient() ) {
		useAmmo( HANDGRENADE_NUMPROJECTILES );

		angles = owner.getViewAngles();
		forward = sys.angToForward( angles );

		entname = getKey( "def_explode_inhand" );
		explosion = sys.spawn( entname );
		explosion.setOrigin( getOrigin() + forward * 16 );
		explosion.setShaderParm( SHADERPARM_TIMEOFFSET, -sys.getTime() );
		delayRemove( explosion, 2 );

		// this should kill us
		sys.radiusDamage( getOrigin(), self, owner, $null_entity, getKey( "def_damage_inhand" ), 1.0 );
	}
}

//@doomscript-blueprint begin 6
//@source 35F4E6E8
//@catalog 0C260740
//@node D36620A1-0 40 40
//@node 57390980-0 330 40
//@node F031CDD9-0 105 145
//@node 74E96E7B-0 -100 245
//@node A42CDEA0-0 -305 245
//@node 8F4FF3E6-0 610 40
//@node F2B53F7E-0 385 145
//@node F968AFB0-0 180 245
//@node FBC1D06B-0 -25 245
//@node 5F58E2F6-0 890 40
//@node F39EE9C9-0 665 145
//@node A9F6F847-0 460 245
//@node D712F5B4-0 255 245
//@node 6865A084-0 1170 40
//@node 566C1050-0 945 145
//@node B86C1315-0 740 245
//@node B467F68C-0 535 245
//@node D66FF564-0 1450 40
//@node 3A6A4195-0 1225 145
//@node 95B2B2C9-0 1020 245
//@node A6BF9530-0 815 245
//@node 53739A95-0 1730 40
//@node 382C3FF2-0 2010 40
//@node B7FD2C11-0 40 40
//@node 118835A2-0 330 40
//@node F349B58D-0 -110 145
//@node 6FD7885D-0 120 145
//@node 92F94AF7-0 610 200
//@node 39C80BD8-0 890 200
//@node 29F7D7FE-0 1170 200
//@node 3CE1CF49-0 1450 40
//@node E9E19826-0 1730 40
//@node 380EE811-0 2010 40
//@node 2CFA042F-0 2290 40
//@node FA11805C-0 40 40
//@node 8BA995F3-0 330 40
//@node 1FCA0668-0 610 40
//@node 6F044EB5-0 890 40
//@node 24431470-0 1170 40
//@node E866F056-0 1450 40
//@node 8CA71B01-0 1245 140
//@node C3971569-0 1730 40
//@node 74803FE5-0 40 40
//@node 5EA398F4-0 330 40
//@node B3A7A641-0 610 40
//@node 53364344-0 890 40
//@node 6618028E-0 685 145
//@node 0823278B-0 1170 200
//@node 329024A3-0 965 305
//@node F4CE147B-0 1450 360
//@node A85CFAEC-0 1730 200
//@node D0D3CE40-0 1525 305
//@node 25906CE9-0 2010 360
//@node 26860327-0 2290 200
//@node 08875F53-0 40 40
//@node 7282E7B3-0 330 40
//@node 588088D8-0 105 145
//@node 7B740238-0 610 40
//@node 45EE07DF-0 405 145
//@node 0FB70FD5-0 890 200
//@node 60C29197-0 1170 40
//@node C9EF99B0-0 1450 40
//@node 60490A5F-0 1225 145
//@node AEF00DE7-0 1730 40
//@node AF0F8F7A-0 1525 145
//@node FBEC8C84-0 2010 40
//@node B03D0BC0-0 1805 145
//@node ECB0D531-0 1600 145
//@node AC8B4807-0 2290 40
//@node 9E274ED5-0 2085 145
//@node AC65461B-0 1880 145
//@node F085C5D7-0 1880 229
//@node 549280BA-0 2570 200
//@node CE327E34-0 2365 305
//@node 7A9AAB7F-0 2160 305
//@node FD664871-0 2160 389
//@node 81748B26-0 2160 389
//@node C98489E2-0 2850 360
//@node 9283BDF1-0 3130 200
//@node C9EF99B0-1 3410 200
//@node 6080A814-0 3185 305
//@node 6B184977-0 3690 40
//@node A5564252-0 3485 145
//@node 8A6D4772-0 3280 145
//@node 3058BDBB-0 3280 229
//@node EA6975AC-0 3970 40
//@node 8E9B800A-0 3765 145
//@node EB41D6F1-0 3560 145
//@node C3864EAB-0 4250 40
//@node 70C39044-0 4045 145
//@node 25C0144A-0 3840 145
//@node CC2D7F7A-0 4530 200
//@node 68ACEC0E-0 4325 305
//@node 9D4FEFA2-0 4810 40
//@node 145F37EC-0 4605 145
//@node 123132E1-0 4400 145
//@node C95D7974-0 5090 200
//@node F42A13F1-0 5370 200
//@node 8836721E-0 5650 200
//@node 5E51D852-0 5445 305
//@node 01410E54-0 5930 200
//@node A0C94842-0 5725 305
//@node F7CA3E14-0 5520 305
//@node 5E7A4ABC-0 6210 200
//@node C58671D7-0 6490 200
//@node 8836721E-1 6770 200
//@node DD6E3AB9-0 6565 305
//@node 8A66BC6A-0 7330 200
//@node BED91AD7-0 7610 200
//@node C1D40462-0 7405 305
//@node 3CAD2CFF-0 7890 40
//@node 182999C4-0 7685 145
//@node 6385052E-0 7480 145
//@node 1FEBF866-0 8170 200
//@node C9EF99B0-2 8450 200
//@node F92F61ED-0 8225 305
//@node 7B740238-1 8730 200
//@node 175326DE-0 8525 305
//@node 53B97B7D-0 9010 360
//@node F8E329BA-0 9290 360
//@node DE808239-0 9570 360
//@node AE3FA75A-0 9365 552
//@node 331326BF-0 9365 644
//@node F0DBE225-0 9160 644
//@node AC99F704-0 9160 722
//@node 17B3BD54-0 9365 736
//@node 9DF052BC-0 9850 360
//@node 1CE19D91-0 9645 465
//@node E9739135-0 10130 200
//@node 3EFDC1F0-0 10410 40
//@node EC702000-0 9970 145
//@node 43B2D350-0 10200 145
//@node F1CB3915-0 10690 200
//@node 96282A22-0 10970 200
//@node F9EC6913-0 11530 200
//@node 842AF665-0 11810 200
//@node C712BA2C-0 40 40
//@node 618435E3-0 330 40
//@node 71CB2492-0 125 145
//@node 32C5C52B-0 610 200
//@node 91AB8B99-0 890 200
//@node 5A436160-0 685 305
//@node 79E6F729-0 1170 40
//@node 03F94538-0 40 40
//@node 7BE6ABFB-0 330 40
//@node 65DFF35E-0 -110 145
//@node ED9AD9AE-0 120 145
//@node EED83DF4-0 610 200
//@node 8A6F059D-0 890 200
//@node EF78E236-0 1450 200
//@node D4970109-0 1730 200
//@node BDBDCF81-0 40 40
//@node CCCC2374-0 330 40
//@node CE54BD85-0 125 145
//@node C8F34857-0 610 40
//@node 10331B92-0 40 40
//@node DA56E320-0 330 40
//@node AD6D6A4F-0 125 145
//@node B074B1F8-0 610 40
//@node 2C4E1B63-0 40 40
//@node 82F956D0-0 330 40
//@node 68AE904B-0 125 145
//@node 308D5C1D-0 -80 145
//@node 9EF11C23-0 610 200
//@node FC76775E-0 385 305
//@node 0968A94D-0 890 360
//@node 992D94B5-0 685 460
//@node 0A931FDD-0 1450 360
//@node 26DCEE12-0 1245 460
//@node 9EF11C23-1 2010 200
//@node CEFA7785-0 1785 305
//@node 76D8853C-0 2290 360
//@node 176D6721-0 2085 460
//@node 3B483F8C-0 2850 360
//@node E749140C-0 2645 460
//@node 44D7146C-0 40 40
//@node D18D29CF-0 330 40
//@node F5428D88-0 125 145
//@node 18BD2D1F-0 610 200
//@node C88F805D-0 890 200
//@node 8E14286F-0 685 305
//@node 22BBEA08-0 40 40
//@node B62ECFBF-0 330 40
//@node 5EB9BD5B-0 125 145
//@node D0AB7DF4-0 610 200
//@node 14178E05-0 405 305
//@node 9DD8FE54-0 200 305
//@node 7F3EFFF0-0 890 200
//@node 78F8A6C3-0 1170 200
//@node 51CECAB2-0 1450 200
//@node 67ED3E32-0 1245 392
//@node 9EFE0023-0 1245 484
//@node 88333C93-0 1730 200
//@node 3C0C2521-0 1525 305
//@node 4F7B5A3E-0 40 40
//@node 5AF2332D-0 330 40
//@node F844E8DF-0 125 145
//@node 34BA7B11-0 610 200
//@node 5A4517E5-0 890 200
//@node D5169E1E-0 685 305
//@node F2000DC8-0 1170 40
//@node 2104E232-0 945 145
//@node 6909BFED-0 1450 40
//@node 8259B9F1-0 1730 40
//@node 82C1252A-0 2010 40
//@node 6AA3C52D-0 1570 145
//@node AA9C9D9D-0 1800 145
//@node DF7B8B2D-0 2290 200
//@node C45401F4-0 2570 200
//@node 5BE366EA-0 2345 305
//@node C84A2A2A-0 2850 200
//@node C4508F26-0 2625 305
//@node 4DA5BFE8-0 2420 405
//@node 617BDD15-0 3130 200
//@node 3E5657E1-0 2905 305
//@node 0AB6EB63-0 3410 200
//@node 4CBE9B18-0 3185 305
//@node 1A850BDC-0 2980 405
//@node 59BCADC3-0 3690 200
//@node ADEF0B67-0 3485 300
//@node 5B4B7EFF-0 3280 300
//@node EFC96A14-0 3970 200
//@node C0CD5428-0 4250 200
//@node A60C1D18-0 4045 300
//@node 80721672-0 4530 200
//@node F31F04AA-0 4325 484
//@doomscript-blueprint end
