/***********************************************************************

weapon_bfg.script

***********************************************************************/

#define BFG_MINRELEASETIME		0.05
#define BFG_FUSE				2.0
#define BFG_SHORTFUSE			0.5
#define BFG_MAXPOWER			4.0
#define BFG_FIRERATE			4
#define BFG_FIREDELAY			4
#define BFG_NUMPROJECTILES		1

// blend times
#define BFG_IDLE_TO_LOWER		4
#define BFG_IDLE_TO_FIRE		4
#define	BFG_IDLE_TO_RELOAD		4
#define BFG_RAISE_TO_IDLE		4
#define BFG_FIRE_TO_IDLE		4
#define BFG_RELOAD_TO_IDLE		4

object weapon_bfg : weapon_base {
	float		spread;	
	float		next_attack;
	
	void		init();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		Reload();
	void		OverCharge();
	void		ExitCinematic();
};

void weapon_bfg::init() {
	next_attack = 0;
	spread = getFloatKey( "spread" );
	setGuiParm( "powerlevel", 0 );
	setGuiParm( "overcharge", 0 );
	weaponState( "Raise", 0 );
}

void weapon_bfg::Raise() {
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	waitUntil( animDone( ANIMCHANNEL_ALL, BFG_RAISE_TO_IDLE ) );
	weaponState( "Idle", BFG_RAISE_TO_IDLE );
}

void weapon_bfg::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	waitUntil( animDone( ANIMCHANNEL_ALL, 0 ) );
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_bfg::Idle() {
	float currentTime;
	float ammoClip;
	float avail;
	float clip_size;

	setColor( 0, 0, 0 );
	clip_size = clipSize();	
	
	if ( !ammoInClip() ) {
		playCycle( ANIMCHANNEL_ALL, "idle_empty" );
		weaponOutOfAmmo();
	} else {
		playCycle( ANIMCHANNEL_ALL, "idle" );
		weaponReady();
	}
	while( 1 ) {
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", BFG_IDLE_TO_LOWER );
		}
		currentTime = sys.getTime();
		ammoClip = ammoInClip();
		if ( ( currentTime >= next_attack ) && WEAPON_ATTACK ) {
			if ( ammoClip > 0 ) {
				weaponState( "Fire", BFG_IDLE_TO_FIRE );
			} else if ( ammoAvailable() > 0 ) {
				if ( autoReload() ) {
					netReload();
					weaponState( "Reload", BFG_IDLE_TO_RELOAD );
				}
			}
		}
		if ( WEAPON_RELOAD && ( ammoAvailable() > ammoClip ) && ( ammoClip < clip_size ) ) {
			netReload();
			weaponState( "Reload", BFG_IDLE_TO_RELOAD );
		}
		if ( WEAPON_NETRELOAD ) {
			WEAPON_NETRELOAD = false;
			weaponState( "Reload", BFG_IDLE_TO_RELOAD );
		}
		waitFrame();
	}
}

void weapon_bfg::Fire() {
	float fuse_start;
	float fuse_end;
	float current_time;
	float time_held;
	float power;
	float powerLevel;
	float intensity;
	float fire_time;
	
	playAnim( ANIMCHANNEL_ALL, "fire_begin" );
	
	current_time = sys.getTime();
	fuse_start = current_time;
	fuse_end = current_time + BFG_FUSE;
	while( current_time < fuse_end ) {
		if ( ( current_time > BFG_MINRELEASETIME ) && !WEAPON_ATTACK ) {
			break;
		}
		waitFrame();
		current_time = sys.getTime();
		powerLevel = ( current_time - fuse_start ) / BFG_FUSE;
		setColor( powerLevel, powerLevel, powerLevel );
		setGuiParm( "powerlevel",  powerLevel );
	}
	
	if ( WEAPON_ATTACK ) {
		current_time = sys.getTime();
		fuse_end = current_time + BFG_SHORTFUSE;
		while ( WEAPON_ATTACK && current_time < fuse_end ) {
			waitFrame();
			current_time = sys.getTime();
		}
		powerLevel = ( current_time - fuse_start ) / BFG_FUSE;
		setGuiParm( "powerlevel", powerLevel );
	}
	
	if ( current_time >= fuse_end ) {
		OverCharge();
	} else {
		time_held = current_time - fuse_start;
		power = ( BFG_MAXPOWER * ( time_held / BFG_FUSE ) );
		if ( power > BFG_MAXPOWER ) {
			power = BFG_MAXPOWER;
		}
		playAnim( ANIMCHANNEL_ALL, "fire" );
		fire_time = sys.getTime();
		launchProjectiles( BFG_NUMPROJECTILES, spread, time_held, 1.0, power );
		while( !animDone( ANIMCHANNEL_ALL, BFG_FIRE_TO_IDLE ) ) {
			current_time = sys.getTime();
			intensity = 1 - ( ( current_time - fire_time ) / 0.5 );
			if ( intensity < 0 ) {
				intensity = 0;
			}
			setColor( intensity, intensity, intensity );
			waitFrame();
		}

		while ( powerLevel > 0 ) {
			powerLevel -= 0.05;
			setGuiParm( "powerlevel", powerLevel );
			waitFrame();
		}
	}

	setGuiParm( "powerlevel", 0 );
	weaponState( "Idle", BFG_FIRE_TO_IDLE );
}

void weapon_bfg::Reload() {
	weaponReloading();
	playAnim( ANIMCHANNEL_ALL, "reload" );
	waitUntil( animDone( ANIMCHANNEL_ALL, BFG_RELOAD_TO_IDLE ) );
	addToClip( clipSize() );
	weaponState( "Idle", BFG_RELOAD_TO_IDLE );
}

void weapon_bfg::OverCharge() {
	string	entname;
	entity	explosion;
	vector	forward;
	vector	angles;
	entity	owner;

	owner = getOwner();

	allowDrop( false );
	useAmmo( clipSize() );

	angles = owner.getViewAngles();
	forward = sys.angToForward( angles );

	entname = getKey( "def_overcharge" );
	explosion = sys.spawn( entname );
	explosion.setOrigin( getOrigin() + forward * 16 );
	explosion.setShaderParm( SHADERPARM_TIMEOFFSET, -sys.getTime() );
	delayRemove( explosion, 2 );

	startSound( "snd_explode", SND_CHANNEL_ANY, false );
	sys.radiusDamage( getOrigin(), self, owner, $null_entity, "damage_bfg_overcharge", 1.0 );
}

void weapon_bfg::ExitCinematic() {
	next_attack = 0;
	setColor( 0, 0, 0 );
	setGuiParm( "powerlevel", 0 );
	weaponState( "Idle", 0 );
}

//@doomscript-blueprint begin 6
//@source 817C3D88
//@catalog 0C260740
//@node 8F2DE6D9-0 40 40
//@node E56CC88A-0 330 40
//@node 65BED0E0-0 125 145
//@node 9925647C-0 610 40
//@node 12818C79-0 385 145
//@node 48929106-0 180 245
//@node B434C639-0 -25 245
//@node 1AAEF05B-0 890 40
//@node 8615D3D2-0 1170 40
//@node 4272CDD6-0 1450 40
//@node 3BC14119-0 40 40
//@node 081D288D-0 330 40
//@node 59A0737A-0 610 40
//@node 0FC6770D-0 890 40
//@node 73B5FAEF-0 1170 40
//@node F40311F4-0 40 40
//@node B0C8C27F-0 330 40
//@node EA15E9D4-0 610 40
//@node 77A4DB79-0 890 40
//@node 0D2D9EC4-0 1170 40
//@node 149AB25A-0 1450 40
//@node EBB52556-0 1245 140
//@node D7949905-0 1730 40
//@node A0F8CC4D-0 40 40
//@node A75AD5FE-0 330 40
//@node 1089B9D0-0 610 40
//@node 6E3F91CF-0 385 145
//@node 824DC52A-0 890 40
//@node 857ED3C3-0 450 145
//@node A01E3933-0 680 145
//@node 006CAC17-0 1170 200
//@node 8F04CE58-0 1450 200
//@node 002FC3FD-0 2010 200
//@node 888247A8-0 2290 200
//@node 16FC884C-0 2570 40
//@node DEC710F7-0 2365 145
//@node D45A2C9F-0 2850 200
//@node A6DE3DA3-0 2645 305
//@node 908A7423-0 3130 360
//@node 00DACC0B-0 3410 200
//@node A0D68619-0 3185 305
//@node D01431F6-0 3690 200
//@node 06590EF9-0 3465 305
//@node 4A9E24C4-0 3970 200
//@node C52DB7BB-0 3765 305
//@node 320DD9F9-0 3560 305
//@node C5F50B4C-0 3560 389
//@node A6E3261B-0 3560 389
//@node ECF5CF57-0 4250 360
//@node 0505F7B8-0 4045 465
//@node 5B2B24FF-0 3840 465
//@node 3FDD8905-0 4530 520
//@node B5B2F438-0 4810 520
//@node 481E414E-0 4605 625
//@node AE16D8A8-0 5090 520
//@node 834904FB-0 4865 625
//@node 0F9F8B43-0 5370 680
//@node 3213E473-0 5650 680
//@node 31402DA7-0 5930 200
//@node 3B461546-0 5725 305
//@node 65567A7D-0 5520 305
//@node EF396809-0 5520 389
//@node D9F15EB3-0 5520 473
//@node 0F9F8B43-1 6210 360
//@node 3213E473-1 6490 360
//@node 5B8EB298-0 6770 200
//@node E291B325-0 6565 305
//@node 1FA66DEE-0 7050 360
//@node D6692586-0 6845 465
//@node 3213E473-2 7330 360
//@node 2B665103-0 7610 200
//@node E9D0654B-0 40 40
//@node 0968899A-0 330 40
//@node 6B43D194-0 610 40
//@node 2440418B-0 385 145
//@node BA19199B-0 890 40
//@node E2DA20F4-0 685 145
//@node BA08B864-0 1170 40
//@node 8AFB02F4-0 965 145
//@node FC93E7DD-0 760 145
//@node 42CD162F-0 1450 40
//@node 5B5B41A0-0 1245 145
//@node F6063C70-0 1040 145
//@node C8697798-0 1040 229
//@node ADDACCF1-0 1730 200
//@node A5B2FD7F-0 1525 305
//@node 514F9915-0 1320 305
//@node AD23D36F-0 1320 389
//@node D9E00916-0 2010 360
//@node 2E26C1B5-0 2290 200
//@node 6B43D194-1 2570 200
//@node FAFA56A0-0 2345 305
//@node B72C0EF8-0 2850 200
//@node B2023FF0-0 2645 305
//@node 02B5B0A8-0 2440 305
//@node C030C209-0 2440 389
//@node 5A3EB407-0 3130 200
//@node E48ED9D5-0 2925 300
//@node DF2E8CCC-0 2925 392
//@node 8FA6A4EF-0 2925 484
//@node 5826DE74-0 3410 200
//@node F3340D98-0 3205 392
//@node 35E96166-0 3690 40
//@node A2A7D9C9-0 3485 145
//@node 6B43D194-2 3970 200
//@node A7C22379-0 3745 305
//@node C5FE46CE-0 4250 200
//@node C7150832-0 4045 305
//@node 572D03E3-0 3840 305
//@node F6010858-0 4530 200
//@node 6563EF33-0 4325 305
//@node A24B0BB0-0 4120 305
//@node 83E31CD8-0 4120 389
//@node AE0CFFF8-0 4120 473
//@node 2E26C1B5-1 4810 360
//@node 6B43D194-3 5090 360
//@node 6736647E-0 4865 465
//@node B72C0EF8-1 5370 200
//@node 8EAF2405-0 5165 305
//@node 1187E34D-0 4960 305
//@node 2DD94364-0 4960 389
//@node 5826DE74-1 5650 200
//@node 7A6698C5-0 5445 392
//@node 3381131C-0 5930 40
//@node DF01B66C-0 5725 145
//@node 0B343435-0 5520 145
//@node 05B6AC9D-0 5520 229
//@node 555177D7-0 6210 200
//@node DB9CE07B-0 6770 200
//@node C763D43C-0 6565 305
//@node 77D074F1-0 6360 305
//@node 10D94B18-0 6360 389
//@node 4E01115F-0 7050 200
//@node 5299BB63-0 6845 305
//@node 246E7BEB-0 6640 305
//@node 197BCABB-0 7330 200
//@node 6247BC9D-0 7125 305
//@node F92F777D-0 6920 305
//@node 7C20DE2A-0 7610 360
//@node 9EB6F3D3-0 7405 465
//@node C0BCD034-0 7890 200
//@node CD2C93FE-0 7685 392
//@node E55D6CF3-0 7480 392
//@node 42D222F5-0 8170 200
//@node 6FB3B6FD-0 7945 305
//@node 74591478-0 8450 200
//@node 4118B3C8-0 8245 392
//@node F7CFEFB5-0 8245 484
//@node 8908E333-0 8245 668
//@node EA45D4D1-0 8730 200
//@node 216B9958-0 8290 305
//@node 3A4BC328-0 8520 305
//@node 6B43D194-4 9010 360
//@node 968531EF-0 8785 465
//@node CCF3E1C9-0 9290 360
//@node 30B9E171-0 9085 465
//@node F4AEAA77-0 8880 465
//@node D7D1DC88-0 8880 549
//@node 15182B12-0 9570 360
//@node D27BC3C1-0 9365 465
//@node 0D8373AA-0 9160 465
//@node D48EFD25-0 9850 520
//@node 04CE1BC7-0 9645 625
//@node A333F40D-0 10130 360
//@node 85AC022C-0 9925 460
//@node 0AEB188F-0 9925 552
//@node 5991DF52-0 9925 644
//@node 2E26C1B5-2 10410 360
//@node 6E7348D2-0 10690 200
//@node 7EA5DEB0-0 10485 305
//@node 7512383F-0 10280 305
//@node DC5C20D9-0 10970 360
//@node AC1B6F94-0 10765 465
//@node B4FA6A14-0 10560 465
//@node 5826DE74-2 11250 360
//@node 0E732196-0 11045 552
//@node 2E26C1B5-3 11530 360
//@node 603319DD-0 11810 40
//@node E46C6FF9-0 12090 40
//@node 25893EB6-0 40 40
//@node A72EE2F5-0 330 40
//@node 3CD26A06-0 610 40
//@node BA39E443-0 890 40
//@node B9D15BB4-0 1170 40
//@node C9D009A9-0 1450 40
//@node F9C6A0D1-0 40 40
//@node 7EFB253D-0 330 40
//@node F2857DE0-0 105 145
//@node 999C34F2-0 610 40
//@node A97DC35E-0 890 40
//@node D6E865DD-0 1170 40
//@node 5E7587E8-0 945 145
//@node AE25DFD7-0 1450 40
//@node E9806A7F-0 1225 145
//@node 6A6CC1C3-0 1020 245
//@node 9A2051BA-0 1730 40
//@node 1AB62C2B-0 1505 145
//@node D1EB1942-0 2010 40
//@node 147BFC14-0 1785 145
//@node 9EF86CCB-0 1580 245
//@node B0F16A5E-0 2290 40
//@node F45ED102-0 2085 140
//@node 1B3EAF8E-0 1880 140
//@node 2A3D0677-0 2570 40
//@node 7DC1136D-0 2850 40
//@node 8FE9CD6D-0 2645 140
//@node 7F77D628-0 3130 40
//@node 77AA6B65-0 3410 40
//@node 1DE82A93-0 3205 324
//@node CE7F4F50-0 40 40
//@node 674E66BF-0 330 40
//@node 343B918C-0 125 145
//@node 1D4578F1-0 610 40
//@node 28EB689C-0 890 40
//@node 277BFA3D-0 1170 40
//@doomscript-blueprint end
