/***********************************************************************

weapon_chaingun.script

***********************************************************************/

#define CHAINGUN_FIRE_SKIPFRAMES	7		// 6 shots per second
#define CHAINGUN_LOWAMMO			10
#define CHAINGUN_NUMPROJECTILES		1
#define	CHAINGUN_BARREL_SPEED		( 60 * ( GAME_FPS / CHAINGUN_FIRE_SKIPFRAMES ) )
#define	CHAINGUN_BARREL_ACCEL_TIME	0.4
#define CHAINGUN_BARREL_DECCEL_TIME	1.0
#define	CHAINGUN_BARREL_ACCEL		( CHAINGUN_BARREL_SPEED / CHAINGUN_BARREL_ACCEL_TIME )
#define CHAINGUN_BARREL_DECCEL		( CHAINGUN_BARREL_SPEED / CHAINGUN_BARREL_DECCEL_TIME )

// blend times
#define CHAINGUN_IDLE_TO_LOWER		4
#define CHAINGUN_IDLE_TO_FIRE		0
#define	CHAINGUN_IDLE_TO_RELOAD		4
#define CHAINGUN_RAISE_TO_IDLE		0
#define CHAINGUN_WINDDOWN_TO_IDLE	0
#define CHAINGUN_RELOAD_TO_IDLE		0

object weapon_chaingun : weapon_base {
	entity		world_model;
	float		world_barrel_joint;
	float		barrel_joint;
	float		barrel_angle;
	float		current_rate;
	float		start_rate;
	float		end_rate;
	float		spin_start;
	float		spin_end;
	float		spread;
	
	void		init();
	
	void		UpdateBarrel();
	void		SpinUp();
	void		SpinDown();
	
	void		Lower();
	void		Raise();
	void		Idle();
	void		Fire();
	void		Reload();
	void		ExitCinematic();
};

void weapon_chaingun::init() {
	world_model		= getWorldModel();
	world_barrel_joint = world_model.getJointHandle( "toob" );
	barrel_joint	= getJointHandle( "spinner" );
	barrel_angle	= 0;
	current_rate	= 0;
	start_rate		= 0;
	end_rate		= 0;
	spin_start		= 0;
	spin_end		= 0;
	spread			= getFloatKey( "spread" );

	weaponState( "Raise", 0 );
}

void weapon_chaingun::destroy() {
	stopSound( SND_CHANNEL_BODY3, false );
}

void weapon_chaingun::UpdateBarrel() {
	float currentTime;
	float t;
	vector ang;
	
	currentTime = sys.getTime();
	if ( currentTime < spin_end ) {
		t = ( currentTime - spin_start ) / ( spin_end - spin_start );
		current_rate = start_rate + t * ( end_rate - start_rate );
	} else {
		current_rate = end_rate;
	}
	
	if ( current_rate ) {
		barrel_angle = barrel_angle + current_rate * GAME_FRAMETIME;
		
		ang_x = 0;
		ang_y = 0;
		ang_z = barrel_angle;	
		setJointAngle( barrel_joint, JOINTMOD_LOCAL, ang );

		ang_y = barrel_angle;
		ang_z = 0;
		world_model.setJointAngle( world_barrel_joint, JOINTMOD_LOCAL, ang );	
	}
}

void weapon_chaingun::SpinUp() {
	start_rate = current_rate;
	end_rate = CHAINGUN_BARREL_SPEED;
	spin_start = sys.getTime();
	spin_end = spin_start + ( end_rate - current_rate ) / CHAINGUN_BARREL_ACCEL;
	startSound( "snd_windup", SND_CHANNEL_BODY3, false );
}

void weapon_chaingun::SpinDown() {
	start_rate = current_rate;
	end_rate = 0;
	spin_start = sys.getTime();
	spin_end = spin_start + ( current_rate - end_rate ) / CHAINGUN_BARREL_DECCEL;
	startSound( "snd_winddown", SND_CHANNEL_BODY3, false );
}

void weapon_chaingun::Raise() {
	weaponRising();
	playAnim( ANIMCHANNEL_ALL, "raise" );
	waitUntil( animDone( ANIMCHANNEL_ALL, CHAINGUN_RAISE_TO_IDLE ) );
	playCycle( ANIMCHANNEL_ALL, "idle" );
	weaponState( "Idle", CHAINGUN_RAISE_TO_IDLE );
}

void weapon_chaingun::Lower() {
	weaponLowering();
	playAnim( ANIMCHANNEL_ALL, "putaway" );
	
	while( !animDone( ANIMCHANNEL_ALL, 0 ) ) {
		UpdateBarrel();
		waitFrame();
	}
	
	weaponHolstered();
	waitUntil( WEAPON_RAISEWEAPON );
	weaponState( "Raise", 0 );
}

void weapon_chaingun::Idle() {
	float ammoClip;
	float avail;
	float clip_size;
	
	clip_size = clipSize();	
	
	if ( !ammoInClip() ) {
		weaponOutOfAmmo();
	} else {
		weaponReady();
	}

	while( 1 ) {
		if ( WEAPON_LOWERWEAPON ) {
			weaponState( "Lower", CHAINGUN_IDLE_TO_LOWER );
		}
		ammoClip = ammoInClip();
		if ( WEAPON_ATTACK ) {
			if ( ammoClip > 0 ) {
				weaponState( "Fire", CHAINGUN_IDLE_TO_FIRE );
			} else if ( ammoAvailable() > 0 ) {
				if ( autoReload() ) {
					netReload();
					weaponState( "Reload", CHAINGUN_IDLE_TO_RELOAD );
				}
			}
		}
		if ( WEAPON_RELOAD && ( ammoAvailable() > ammoClip ) && ( ammoClip < clip_size ) ) {
			netReload();
			weaponState( "Reload", CHAINGUN_IDLE_TO_RELOAD );
		}
		if ( WEAPON_NETRELOAD ) {
			WEAPON_NETRELOAD = false;
			weaponState( "Reload", CHAINGUN_IDLE_TO_RELOAD );
		}
		UpdateBarrel();
		waitFrame();
	}
}

void weapon_chaingun::Fire() {
	float ammoClip;
	float currentTime;
	float skip;
	SpinUp();
	ammoClip = ammoInClip();
	while( ( current_rate < end_rate ) && WEAPON_ATTACK && !WEAPON_RELOAD && ( ammoClip > 0 ) ) {
		UpdateBarrel();
		waitFrame();
		ammoClip = ammoInClip();
	}
		
	startSound( "snd_spin", SND_CHANNEL_BODY3, false );
	ammoClip = ammoInClip();
	while( WEAPON_ATTACK && !WEAPON_RELOAD && ( ammoClip > 0 ) ) {
		launchProjectiles( CHAINGUN_NUMPROJECTILES, spread, 0, 1.0, 1.0 );
		startSound( "snd_fire", SND_CHANNEL_WEAPON, false );
		ammoClip = ammoInClip();
		if ( ammoClip == CHAINGUN_LOWAMMO ) {
			startSound( "snd_lowammo", SND_CHANNEL_ITEM, false );
		}

		// skip frames
		for( skip = 0; skip < CHAINGUN_FIRE_SKIPFRAMES; skip++ ) {
			UpdateBarrel();
			waitFrame();
		}
	}

	SpinDown();
	weaponState( "Idle", CHAINGUN_WINDDOWN_TO_IDLE );
}

void weapon_chaingun::Reload() {
	weaponReloading();
	playAnim( ANIMCHANNEL_ALL, "reload" );
	while( !animDone( ANIMCHANNEL_ALL, CHAINGUN_RELOAD_TO_IDLE ) ) {
		UpdateBarrel();
		waitFrame();
	}
	addToClip( clipSize() );
	playCycle( ANIMCHANNEL_ALL, "idle" );
	weaponState( "Idle", CHAINGUN_RELOAD_TO_IDLE );
}

void weapon_chaingun::ExitCinematic() {
	current_rate	= 0;
	start_rate		= 0;
	end_rate		= 0;
	spin_start		= 0;
	spin_end		= 0;

	weaponState( "Idle", 0 );
}

//@doomscript-blueprint begin 6
//@source 18AC8EE6
//@catalog 0C260740
//@node 1B52A095-0 40 40
//@node 8720D542-0 330 40
//@node 534F23E6-0 105 145
//@node F067A9FD-0 610 40
//@node B4163826-0 385 145
//@node D87EAB45-0 890 40
//@node 3CE74331-0 665 145
//@node 6FDE949A-0 1170 40
//@node 3E7D4C47-0 965 145
//@node C75FB4BA-0 1450 40
//@node AB7736B5-0 1245 145
//@node 0193B2D7-0 1730 40
//@node 4789CA59-0 1525 145
//@node 9048C4E6-0 2010 40
//@node 5328C61E-0 1805 145
//@node 27D003F7-0 2290 40
//@node 6D35A0E2-0 2085 145
//@node A3895EC8-0 2570 40
//@node 830BCD1D-0 2365 145
//@node 4DB6B7C6-0 2850 40
//@node FD6E70C2-0 2625 145
//@node D63468EA-0 2420 245
//@node DAB8AE5F-0 2215 245
//@node 3651C162-0 3130 40
//@node 340FDED3-0 40 40
//@node DFC86382-0 330 40
//@node 6A4AEB22-0 40 40
//@node 24E513A4-0 330 40
//@node 6787A15C-0 105 145
//@node E05BB4F0-0 610 40
//@node 7E843251-0 405 145
//@node 9DBFBF40-0 200 145
//@node 43C81E2E-0 200 229
//@node 7B720E56-0 890 200
//@node 129D40FA-0 685 305
//@node D293004A-0 480 305
//@node 61904FD5-0 480 389
//@node 3CE5F70C-0 480 473
//@node CC409596-0 1170 200
//@node 07A758B5-0 965 305
//@node F75B2461-0 760 305
//@node 59A7F08C-0 760 389
//@node 054207EB-0 760 473
//@node 7E576AA1-0 1730 200
//@node F400CDC7-0 1525 305
//@node 3FB4F5C6-0 2010 40
//@node AE1EB557-0 1805 145
//@node 0780EF3F-0 2290 200
//@node F3D90A46-0 2085 305
//@node DFB319EB-0 1880 305
//@node 02892E17-0 1880 389
//@node BC00E116-0 2570 200
//@node EE28ECB8-0 2365 305
//@node 84C80547-0 2850 200
//@node A4131A73-0 2645 305
//@node DC2FC112-0 3130 200
//@node 9FFB889C-0 2925 305
//@node 7FD76C34-0 3410 200
//@node 4EE0E5E3-0 3205 300
//@node 9533924E-0 3205 484
//@node 61B89237-0 3690 200
//@node 7D2F3BC4-0 3485 305
//@node 6B0B5A28-0 3970 200
//@node 5D0C9904-0 3765 305
//@node 4B8CE0B1-0 4250 200
//@node AA61FF4B-0 4045 300
//@node 2D7FA8DD-0 4045 484
//@node 39D5FED2-0 40 40
//@node C4E43742-0 330 40
//@node 56B78C68-0 125 145
//@node 1229F0B3-0 610 40
//@node F934D99E-0 405 145
//@node 699B0C37-0 890 40
//@node 9EF69620-0 665 145
//@node 34971D47-0 1170 40
//@node DF122F74-0 965 145
//@node B3B4EE73-0 760 145
//@node DB689B77-0 760 229
//@node A2651B84-0 760 313
//@node 8DE65666-0 1450 40
//@node F9E78333-0 40 40
//@node 96A26E11-0 330 40
//@node 11FAFEDA-0 125 145
//@node 5E99EB08-0 610 40
//@node 2C4CFC5E-0 405 145
//@node 73F96956-0 890 40
//@node 58E3DA03-0 665 145
//@node 6BDC0346-0 1170 40
//@node 829BBB2A-0 965 145
//@node 3926AE6D-0 760 145
//@node 681BEE3D-0 760 229
//@node 3B8B4C22-0 760 313
//@node FA5C85CE-0 1450 40
//@node 22692405-0 40 40
//@node 7351D719-0 330 40
//@node C4136516-0 610 40
//@node E78A1CE3-0 890 40
//@node B67FB8F9-0 1170 40
//@node 9F2F55EF-0 1450 40
//@node F930FE48-0 40 40
//@node 73B73CC3-0 330 40
//@node C192B8B8-0 610 40
//@node A564EF55-0 890 40
//@node 484C3162-0 450 145
//@node 72554592-0 680 145
//@node 07B04155-0 1170 200
//@node E48E57A0-0 1450 200
//@node 2D438F00-0 1730 40
//@node 4F140326-0 2010 40
//@node 7E8D0B05-0 1805 140
//@node 82EFF059-0 2290 40
//@node 2F0DA601-0 40 40
//@node 9618B592-0 330 40
//@node A9C18890-0 105 145
//@node 5E17D04E-0 610 40
//@node CC08365B-0 170 145
//@node B134C38B-0 400 145
//@node 3F17FD34-0 890 200
//@node 35D02784-0 1450 200
//@node 2F0F1828-0 1730 40
//@node 6598F099-0 1525 145
//@node E819DA1B-0 2010 200
//@node 245E2372-0 1805 305
//@node 42E727F5-0 2290 360
//@node A56E8A34-0 2570 200
//@node B9633E35-0 2345 305
//@node 5D141FDC-0 2850 200
//@node D9569DF8-0 2645 305
//@node 600BA553-0 3130 360
//@node AEABB8B6-0 2925 465
//@node E74BEDCB-0 2720 465
//@node E11189BD-0 3410 520
//@node B2972D14-0 3690 520
//@node 1429E20D-0 3485 625
//@node 677BD904-0 3970 520
//@node 032A72CE-0 3745 625
//@node 7EEDD977-0 4250 680
//@node EC79A2B5-0 4530 680
//@node B737B28B-0 4810 200
//@node 9BD8147F-0 4605 305
//@node CBAE3828-0 4400 305
//@node BF2E0E4A-0 4400 389
//@node F858CAE8-0 4400 473
//@node 7EEDD977-1 5090 360
//@node EC79A2B5-1 5370 360
//@node 5A518CCC-0 5650 200
//@node 41E4A7C5-0 5445 305
//@node 2804C558-0 5930 360
//@node 2C38CF93-0 5725 465
//@node EC79A2B5-2 6210 360
//@node 59F2702C-0 6490 200
//@node 66B9B617-0 6770 200
//@node 4AC536C7-0 40 40
//@node 15793F22-0 330 40
//@node 1C0787E2-0 610 40
//@node 9FAFC3B3-0 385 145
//@node 5A041E05-0 890 40
//@node 878BC62D-0 685 145
//@node 9D40DB1E-0 480 145
//@node 665BB42B-0 480 229
//@node 767FBDDA-0 480 313
//@node 04CE144A-0 480 229
//@node AE90B40E-0 480 313
//@node 75D82662-0 1170 200
//@node E17A5141-0 1450 200
//@node 1C0787E2-1 1730 200
//@node E9C83CD2-0 1505 305
//@node 0B5B9ED4-0 2010 40
//@node 1C0787E2-2 2290 40
//@node 650A7EA9-0 2065 145
//@node A79823E8-0 2570 40
//@node 2C8933BE-0 2365 145
//@node 511C364E-0 2160 145
//@node 1A054CBB-0 2160 229
//@node D0A4EB4A-0 2160 313
//@node F3E9EA6F-0 2850 200
//@node 4D006C8E-0 2645 392
//@node 7D79385D-0 3130 200
//@node 1C0787E2-3 3410 200
//@node B84FCEE0-0 3185 305
//@node DECEB167-0 3690 200
//@node 4EAC3DD3-0 3485 305
//@node D0E4A754-0 3280 305
//@node F50CC1BE-0 3970 360
//@node 63E96297-0 4250 200
//@node F3C03B81-0 4045 305
//@node ECB39AAB-0 3840 305
//@node 75D82662-1 4530 360
//@node E17A5141-1 4810 360
//@node 8A4FB221-0 5090 40
//@node 02E64FDF-0 5370 40
//@node E7976AD2-0 40 40
//@node 08BCCB59-0 330 40
//@node B7A08B62-0 610 40
//@node 26AC4F37-0 890 40
//@node 61B50AE1-0 450 145
//@node 7F6D6691-0 680 145
//@node F2521737-0 1170 200
//@node 9F9E66D6-0 1450 200
//@node 04403DA0-0 1730 40
//@node 9961D38A-0 2010 40
//@node 0ABE5063-0 2290 40
//@node D851B054-0 40 40
//@node 7952DBCD-0 330 40
//@node D188E954-0 125 145
//@node 09626A84-0 610 40
//@node 6F0267F0-0 405 145
//@node F0FEDA21-0 890 40
//@node FE517943-0 685 145
//@node 8E20DB18-0 1170 40
//@node CC8EBEA8-0 965 145
//@node F5DEA5A7-0 1450 40
//@node E7D2775A-0 1245 145
//@node 532DC2B9-0 1730 40
//@doomscript-blueprint end
